### ISSUE TITLE
exception emails not getting sent

### ISSUE THREAD

**Issue by KeeneState** [processwire/processwire-issues#10]
> Briefly describe the issue.

When an internal server error occurs, emails that were getting triggered in PW 2.6 are no longer generated.

> What did you expect to happen?

Receive email on error, sent to $config->adminEmail

> What did actually happen?

No email is generated

> Optional: Have you a suggestion for a possible fix?

WireShutdown.php sends the email if `function_exists("wireMail")`. I think that needs to be changed to `function_exists("\ProcessWire\wireMail")`.

> What are the steps to reproduce the issue?

1. Make sure $config->adminEmail is set, and server/dev environment supports wireMail
2. Break some code to generate a WireException. Hit broken code with browser. You should see the message "Unable to complete this request due to an error. - Error has been logged. Administrator has been notified."
3. Veiw inbox, outgoing maillog.

> Tell us about the setup you experienced the bug in.

Linux, PW 3.0.34, PHP 5.6.x  
$config->templateCompile = false;  
$config->moduleCompile = false;

**Comment by ryancramerdesign** [comment]
Thanks @KeeneState this is a good find, I've pushed a fix.

**Comment by KeeneState** [comment]
@ryancramerdesign, thanks!
