### ISSUE TITLE
Issue with Sanitizer when bootstrapping processwire in a wordpress environment

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#100]
### Short description of the issue

Wordpress does [polyfill mb_strlen](https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-includes/compat.php#L134-L150), which is used by Sanitizer.php to determine if mbstring is available. It then fails by trying to use `mb_internal_encoding`.

### Optional: Suggestion for a possible fix

Maybe Sanitizer.php should check for a more uncommon mbstring function than `mb_strlen`.

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this, making ti check for mb_internal_encoding instead.
