### ISSUE TITLE
custom metadata model - checkbox not saved

### ISSUE THREAD

**Issue by fluctusz** [processwire/processwire-issues#1001]
### Short description of the issue

when using a checkbox in template "field-imagefield" for a images-field "imagefield", checkbox value doesn't get saved.

### Expected behavior

checked checkbox should get saved.

### Setup/Environment
SERVER DETAILS
ProcessWire: 3.0.142
PHP: 7.3.6-nmm1
Webserver: Apache
MySQL: 5.6.44-nmm1-log

SERVER SETTINGS
allow_url_fopen: 1
max_execution_time: 120 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 3000
memory_limit: 256M
post_max_size: 200M
upload_max_filesize: 200M
xdebug: 
xdebug.max_nesting_level: 
mod_rewrite: 
mod_security: 
EXIF Support: 1
FreeType: 1

GD SETTINGS
Version: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1
WebP: 1

IMAGICK SETTINGS
Version: 6.7.7
GIF: 1
JPG: 1
PNG: 1
SVG: 1
PDF: 1
WebP: 

MODULE DETAILS
FieldtypeMultiplier: 0.1.3
InputfieldMultiplier: 0.1.1
MinimalFieldset: 0.1.5
PageimageSrcset: 0.0.4
ProCache: 3.1.8
ProcessProCache: 3.1.8
ProcessTracyAdminer: 1.0.6
TracyDebugger: 4.19.35

**Comment by fluctusz** [comment]
sorry. when ckecked it is correctly saved with value 1 in filedata json. so it seems to be a frontend issue.  tested with admin-theme uikit

**Comment by ryancramerdesign** [comment]
Thanks @fluctusz I've pushed a fix for this issue.

**Comment by fluctusz** [comment]
works now. Thank you Ryan.
