### ISSUE TITLE
ProcessList::render() - incosistence in dealing with icons

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1003]
### Short description of the issue

`AdminThemeFramework.php` allow for option of an admin field overriding the module icon in function `AdminThemeFramework::getPageIcon()` whereas `ProcessList::render()` does not.

### Expected behaviour
Consistency in dealing with icons in the backend. If a page icon is assigned (`$page->page_icon`), it should be used, especially in the case if the process has no icon.

### Possible solution
**replace**  
https://github.com/processwire/processwire/blob/22fe5bf9ef2dbe05fd8d6889810ae367a333fbef/wire/modules/Process/ProcessList.module#L60-L62
**with**
```
if($settings['showIcon'] && $info['icon']) $icon = $info['icon'];
else if($child->page_icon) $icon = $child->page_icon;
if($icon) {
	$icon = "<i style='float: right;' class='fa fa-3x fa-fw fa-$icon ui-priority-secondary'></i> ";
}
```
### Use case
My special use case are modules to which icons are to be assigned based on the instance and not class based. This is not possible because the `getModuleInfo()` function is static. Therefore I decided to use the option to assign icons page based, which is done by another module:
https://github.com/kixe/PageIcon/blob/master/PageIcon.module

* ProcessWire version: 1.0.142
* (Optional) PHP version: 7.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue.

**Comment by kixe** [comment]
Confirmed. Thanks
