### ISSUE TITLE
JqueryWireTabs module produces JavaScript error (admin theme UIKit)

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#1005]
### Short description of the issue

JqueryWireTabs module produces a JavaScript error when used to switch between process pages in admin theme UIKit.

I'm using WireTabs for the admin interface of SnipWire. The tabbed interface is used to link to the different ProcessModule pages and not to switch between sections on same page.

(BTW, the comment manager module from PW core has the same problem)

```
Uncaught Error: Syntax error, unrecognized expression: /pw/setup/snipwire/orders
    at Function.nt.error (JqueryCore.js?v=1571155560:2)
    at ut (JqueryCore.js?v=1571155560:2)
    at vt (JqueryCore.js?v=1571155560:2)
    at vt (JqueryCore.js?v=1571155560:2)
    at Function.nt [as find] (JqueryCore.js?v=1571155560:2)
    at init.find (JqueryCore.js?v=1571155560:2)
    at new init (JqueryCore.js?v=1571155560:2)
    at v (JqueryCore.js?v=1571155560:2)
    at main.js?v=30e:88
nt.error @ JqueryCore.js?v=1571155560:2
ut @ JqueryCore.js?v=1571155560:2
vt @ JqueryCore.js?v=1571155560:2
vt @ JqueryCore.js?v=1571155560:2
nt @ JqueryCore.js?v=1571155560:2
find @ JqueryCore.js?v=1571155560:2
init @ JqueryCore.js?v=1571155560:2
v @ JqueryCore.js?v=1571155560:2
(anonymous) @ main.js?v=30e:88
setTimeout (async)
setupWireTabs @ main.js?v=30e:84
ready @ main.js?v=30e:61
(anonymous) @ main.js?v=30e:897
l @ JqueryCore.js?v=1571155560:2
fireWith @ JqueryCore.js?v=1571155560:2
ready @ JqueryCore.js?v=1571155560:2
A @ JqueryCore.js?v=1571155560:2
```

The problem lies here:

https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js#L88

### Setup/Environment

SERVER DETAILS
ProcessWire: 3.0.142
PHP: 7.2.21
Webserver: Apache
MySQL: 5.7.26

MODULE DETAILS
FieldtypeSnipWireTaxSelector: 0.0.1
MarkupSnipWire: 0.0.1
ProMailer: 0.0.7
ProcessProMailer: 0.0.7
ProcessSnipWire: 0.0.1
ProcessTracyAdminer: 1.0.6
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
SnipWire: 0.0.1
TracyDebugger: 4.19.34

**Comment by ryancramerdesign** [comment]
Thanks @gadgetto I've pushed a fix for this issue.

**Comment by gadgetto** [comment]
Thanks for the fast fix! Seems to work now!
