### ISSUE TITLE
TextFormatters are applied on image descriptions inside RepeaterMatrix

### ISSUE THREAD

**Issue by phlppschrr** [processwire/processwire-issues#1007]
### Description of the issue
TextFormatters are applied on image descriptions on page save when used inside RepeaterMatrix. Only default language is affected, other languages work fine.

**EDIT:** I could narrow the issue: The bug only occurs in matrix types which use an item header like this:
`{matrix_label} ({images.count})` . If I remove `{images.count}`, the textformatters are not applied anymore and everything works like expected. It seems custom labels like this turn on outputFormatting on the repeater page.

### Expected behavior
TextFormatters should only be applied in frontend output

### Steps to reproduce the issue

1. Create a new repeaterMatrix field
2. Create a images field and add a textformatter **HTML Entity Encoder** to it
3. Add a new matrix type with this images field
4. Set itemheader to `{matrix_label} ({images.count})`
5. Edit a page with this matrix field and add a description containing special chars like `>`to an image. Save the page and look at the description.

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.142|
|PHP|7.2.1|
|Webserver|Apache|
|MySQL|5.6.38|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|300 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|256M|
|post_max_size|32M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|7.0.8|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AddTemplateEnhancements|0.1.4|
|AdminOnSteroids|2.0.20|
|AutoTemplateStubs|0.1.6|
|BatchChildEditor|1.8.19|
|DiagnoseFiles|0.0.1|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.4|
|FieldtypeFunctional|0.0.2|
|FieldtypeRepeaterMatrix|0.0.5|
|FieldtypeTable|0.1.9|
|FieldtypeURLLanguage|0.0.2|
|FormBuilder|0.3.4|
|HannaCodeDialog|0.2.5|
|ImageSizerEngineIMagickCLI|0.1.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.2|
|InputfieldRepeaterMatrix|0.0.5|
|InputfieldTable|0.1.9|
|MarkupSrcSet|0.1.2|
|MinimalFieldset|0.1.5|
|PageActionDelete|0.0.2|
|PageimageAssistant|1.0.0|
|ProCache|3.1.9|
|ProcessChildrenCsvExport|1.8.18|
|ProcessDiagnostics|0.2.2|
|ProcessFormBuilder|0.3.4|
|ProcessHannaCode|0.2.0|
|ProcessModuleToolkit|0.2.4|
|ProcessPageListerPro|1.1.3|
|ProcessProCache|3.1.8|
|ProcessRockFinder2|0.0.1|
|ProcessSettingsFactory|1.0.3|
|ProcessTracyAdminer|1.0.6|
|RockFinder2|0.0.2|
|SettingsFactory|1.0.4|
|TemplatesChildPages|0.1.8|
|TextformatterHannaCode|0.2.0|
|TextformatterMailtoProtection|1.0.0|
|TextformatterMakeLinks|1.0.1|
|TextformatterMarkdownSafe|0.1.1|
|TextformatterParsedownExtraPlugin|1.0.2|
|TextformatterStringToShy|1.0.0|
|TextformatterVideoEmbed|1.1.1|
|TextformatterVideoEmbedOptions|0.3.6|
|TracyDebugger|4.19.35|
|WireMailSmtp|0.4.2|
</details>

**Comment by phlppschrr** [comment]
I could narrow the issue, and edited the issue: Item headers like `{matrix_label} ({images.count})` seem to turn on outputFormatting

**Comment by ryancramerdesign** [comment]
@phlppschrr Thanks, I've tracked down the issue and it'll be in the next RepeaterMatrix version. If you want to update yourself, edit the InputfieldRepeaterMatrix.module file and right around line 119 you'll see this:
~~~~~
$out = $this->wire('sanitizer')->text($page->getMarkup($out));
~~~~~
Modify that to be this:
~~~~~
$p = clone $page;
$out = $this->wire('sanitizer')->text($p->getMarkup($out));
~~~~~

**Comment by netcarver** [comment]
@phlppschrr Does Ryan's suggestion above fix things for you? If so, please could you close this issue - or post here again if needed.

**Comment by phlppschrr** [comment]
Thanks. The suggested change fixes my issue.
