### ISSUE TITLE
Toggle field "click to deselect" not working with inputfield dependencies

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1008]
### Short description of the issue

In this example I have a FieldtypeToggle field named "test_toggle" with the "Support click to de-select" option enabled for the inputfield.

I have a dependent text field with show-if visibility set to "test_toggle=1". But the text field is not hidden when "Yes" is deselected in the toggle field.

Screencast:
![toggle](https://user-images.githubusercontent.com/1538852/67444357-1ff83200-f665-11e9-9432-e253f9771b12.gif)

### Setup/Environment

* ProcessWire version: 3.0.142

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
