### ISSUE TITLE
Visibility dependency issue with 4 x 25% width fields

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1009]
### Short description of the issue

I have 4 checkbox fields in a template, all at 25% width so they can fit in a single row. 

![2019-10-24_142145](https://user-images.githubusercontent.com/1538852/67445785-9cd9da80-f66a-11e9-8485-4096184870a9.png)

Checkboxes 2, 3 and 4 have a visibility dependency on the preceding checkbox, e.g. "checkbox_1=1".

There is a column width issue when only the first checkbox is checked. The issue occurs with either uk-width classes or percentage-based widths selected in the AdminThemeUikit config.

![dep](https://user-images.githubusercontent.com/1538852/67445796-a7946f80-f66a-11e9-8edd-9e016e5c48f7.gif)

If I remove the last checkbox field from the template and change the column widths to 33%, 33% and 34% then the column width issue doesn't occur.

![2019-10-24_142555](https://user-images.githubusercontent.com/1538852/67445891-0c4fca00-f66b-11e9-94a2-ead4b9b1207b.png)

![dep2](https://user-images.githubusercontent.com/1538852/67445893-0f4aba80-f66b-11e9-9e70-26ed5c1ae407.gif)

### Setup/Environment

* ProcessWire version: 3.0.142

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
