### ISSUE TITLE
Setting Up ProcessWire In Subdirectory On Nginx Doesn't Work

### ISSUE THREAD

**Issue by brightbart** [processwire/processwire-issues#101]
### Short description of the issue

Setting Up ProcessWire In a Subdirectory On Nginx Doesn't Work, the redirect is off.

### Expected behavior

ProcessWire redirects properly, no 404 errors on links such as http://processwiresite.com/about

### Actual behavior

404 error on visiting any site content, except the start page

### Optional: Suggestion for a possible fix
Maybe this helps?

https://processwire.com/talk/topic/11083-nginx-deployment-in-subdirectory/

### Steps to reproduce the issue
Setup Nginx page with location like this and install ProcessWire in subdirectory /pw

        `location /pw {
                try_files $uri $uri/ /pw/index.php?it=$uri&$args;
        }`

If you remove ?it=$uri&$args you get redirected to the start page, so I think maybe something about the arguments is off.

### Setup/Environment
I'm using Linux Debian Nginx and PHP7.0-FPM

* ProcessWire version:
* (Optional) PHP version: 7.0
* (Optional) MariaDB version: newest 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: none

**Comment by LostKobrakai** [comment]
There's no official support for nginx in processwire until now. Please use the forum for questions/issues regarding nginx.
