### ISSUE TITLE
Anomalies with AJAX-loaded required fields

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1011]
### Short description of the issue

A couple of anomalies with fields when their visibility is set to either "Closed + Load only when opened (AJAX)" or "Open when populated + Closed when blank + Load only when opened (AJAX)" and the field is required (and this includes required-if conditions):

1\. The field is not AJAX loaded when the field is opened - it is actually rendered when Page Edit loads but in a closed state.

2\. The required state is not enforced - no warning is shown to the user if the Page Edit form is submitted with the field empty.

In the screencast below the "Text" field is set to "Closed + Load only when opened (AJAX)" and is required. Note that the field opens immediately without any spinner (field does not AJAX-load) and that no warning shows when the form is submitted with the field in an empty state. The page is also published which should not happen when a required field is empty.

![ajax](https://user-images.githubusercontent.com/1538852/67547740-67adb500-f75c-11e9-8ec0-b632270f7850.gif)

### Setup/Environment

* ProcessWire version: 3.0.142

**Comment by ryancramerdesign** [comment]
@Toutouwai There are a lot of cases where ajax loading is not going to work, so this is very much a YMMV option, which is the reason for the ajax disclaimer in the visibility fieldset. But the case you've mentioned here is one that is planned for, and just isn't working as intended. Ajax loading and required state can't always be combined, so it automatically removes the ajax state if the field is required and empty. But what was missing is that the scenario wasn't being identified property by the processInput side, so it wasn't enforcing the required state. I've fixed that issue. Thanks.

**Comment by Toutouwai** [comment]
Thanks. It would be pretty cool if AJAX-loaded fields with required-if settings could be loaded only when the required-if condition becomes true. I have some "expensive" inputfields that only need to render in certain circumstances, but I can take care of this scenario with custom JS to AJAX-load the field and custom validation for the required status, so that request is just a nice-to-have. Thanks again.

**Comment by Toutouwai** [comment]
> There are a lot of cases where ajax loading is not going to work

Regarding that, I don't think I've ever come across a scenario where AJAX-loading doesn't work for an inputfield, so long as renderReady() is correctly used for loading JS dependencies.
