### ISSUE TITLE
PageListSelectMultiple allows the same page to be selected multiple times

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1012]
### Short description of the issue

PageListSelectMultiple allows the same page to be selected multiple times:

![select](https://user-images.githubusercontent.com/1538852/67608458-c4ed4900-f7e4-11e9-93d0-a849f3eea1e5.gif)

The duplicates are removed on save but it doesn't seem right that the same page could be available for selection more than once in the inputfield. For pages already selected in the inputfield, could the "Select" button be greyed out or replaced with a "Deselect" button?

### Setup/Environment

* ProcessWire version: 3.0.143

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I have pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks.
