### ISSUE TITLE
Operator '&' is not supported for 'status' in ..\wire\core\PageFinder.php:2211

### ISSUE THREAD

**Issue by mikemastercorp** [processwire/processwire-issues#1013]
### Short description of the issue

After upgrading to core 3.0.142 I got an error 500 while trying to browse the frontend of a working profile. In fact, any template I try to browse leads me to the same issue but it works fine with the earlier commits.

### Expected behavior

I needed to upgrade the core from 3.0.137 to 3.0.142, however I've never had issues with earlier upgrades, but just with this one. 

### Actual behavior

Any page I try to browse besides the admin pages is leading me to Error 500 and the content of the exception.log says:
Operator '&' is not supported for 'status'. in ..\wire\core\PageFinder.php:2211

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Presently the only fix I have found was to use the last commit before the 3.0.142 dev branch has been pushed.

### Steps to reproduce the issue

1. Install earlier version of ProcessWire (in my case 3.0,137)
2. Upgrade the core folder with the present version
3. Try to browse any page that has been added with an assigned template containing some selector like status=published

### Setup/Environment

* ProcessWire version: 3.0.142
* (Optional) PHP version: PHP 7.2 x64
* (Optional) MySQL version: 5.7 x64
* (Optional) Any 3rd party modules that are installed and could be related to the issue:
[exception.log](https://github.com/processwire/processwire-issues/files/3774308/exception.log)

**Comment by adrianbj** [comment]
@ryancramerdesign - more details here: https://processwire.com/talk/topic/22475-processwire-upgrade-from-30137-to-30142-failed-error-500/?tab=comments#comment-192781

I can confirm this bug and it was introduced here: https://github.com/processwire/processwire/commit/6fcc0502b6d3c7c4aed2fc1b1842e513e6c5221c

**Comment by adrianbj** [comment]
@mikemastercorp - can this be closed now that it's fixed via: https://github.com/processwire/processwire/commit/80eb2ff3f196b1332e94fc0993c635584cfffe52 ?

**Comment by tbba** [comment]
this fixed for me, at least - thanks @ryancramerdesign

**Comment by adrianbj** [comment]
Yeah, it's fixed for me also.

**Comment by netcarver** [comment]
Ok, closing. @mikemastercorp Please post again if you need to and I'll re-open this issue.

**Comment by teppokoivula** [comment]
@ryancramerdesign, just a heads-up: this issue was fixed, but core version was not updated, so the version available via Composer (/Packagist) is still broken. Just FYI – hopefully there's a version bump at the end of the week :)
