### ISSUE TITLE
PagePathHistory not working when page is renamed

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1014]
### Short description of the issue

The PagePathHistory module does not redirect a page when the page is renamed. It works as expected if a page is moved.

### Steps to reproduce the issue

1. With the "blank" profile installed, install the PagePathHistory module.
2. Create and publish a new page using the basic-page template titled "Foo".
3. View the page on the front-end in a new tab.
4. Change the page name to "bar" and save.
5. Reload the front-end page and note the 404.

Screencast:
![pph](https://user-images.githubusercontent.com/1538852/67818689-0fd5cc00-fb17-11e9-902f-9299890bdcf3.gif)

### Setup/Environment

* ProcessWire version: 3.0.143

**Comment by ryancramerdesign** [comment]
@Toutouwai Can you double check that you've installed the PagePathHistory module? (Modules > Core > Page). If you installed the blank profile, then you've got a blank slate, so some optional modules like PagePathHistory are not going to be installed unless/until you click to install them.

**Comment by Toutouwai** [comment]
Yes, the PagePathHistory module is installed - I listed that in the steps to reproduce. If the module wasn't installed then the redirection wouldn't happen when a page is moved (that part is working as expected).

**Comment by ryancramerdesign** [comment]
@Toutouwai Okay next thing to check is how old the page is. PagePathHistory doesn't come into play until the page is at least 2 minutes old. This is to filter out the noise of the page creation process where renaming is common, but static links to it are not.

**Comment by Toutouwai** [comment]
@ryancramerdesign, thanks - that explains it, I think the cases where I've seen this is on very recently created pages. But a couple of things:

1\. The thing I like about PagePathHistory is that it's sort of "set and forget" - when the module is installed the understanding is that you don't need to worry about broken links from renamed or moved pages because the module has this covered. So if there is some scenario where the module is not going to handle renamed/moved pages then this should be clearly stated somewhere - e.g. in a warning notice after the module is installed. Which leads to...

2\. I don't think it's that unlikely that links to pages might be shared on third-party websites within 2 minutes of their creation. This could be done manually - e.g. a communications employee immediately sharing a link to a new news article on Facebook. And there is automation to consider too - e.g. using IFTTT or other APIs to perform some syndication of new content.

Would it be much of a problem if the window of time where page name changes are ignored is brought down to something much shorter, or dropped altogether? Speaking for myself, given how undesirable a broken link is I'd rather have more clutter in the path history than risk broken incoming links.

**Comment by netcarver** [comment]
> Would it be much of a problem if the window of time where page name changes are ignored is brought down to something much shorter, or dropped altogether?

Or made configurable?

**Comment by BernhardBaumrock** [comment]
Could PagePathHistory only take pages into account that have been viewed at least once? So if a page in the admin is created (foo1) and then renamed to foo2 and foo3 it would have no effect until foo3 was viewed once. Then PW could create an entry in the history table and if the page was renamed to foo4 the entry in the table could be foo3-->foo4 (no idea how the table looks like at the moment).

If foo4 was never viewed and renamed to foo5 PW could do the lookup in the history table, find foo3-->foo4 and change it to foo3-->foo5. If foo5 was viewed it would create a new entry foo5--> (meaning it waits for a new rename to happen and if foo5 was viewed there would be no rename and the page would be viewed just as usual). After rename to foo6 it would be foo5-->foo6 and all visits of foo5 would redirect to foo6.

If foo4 was viewed afterwards there would be no redirect at all... So that could be a culprit. This should not be a problem when sharing links on social media (because there the link gets crawled by the platform and therefore triggers the view hook). But sharing it anywhere else could lead to 404s.

So maybe a timeframe (configurable) is the easiest and therefore best solution...

**Comment by horst-n** [comment]
@BernhardBaumrock When I programatically create pages and send those links out or save them to send out later, I definetly want to have handled page path name changes by the module, regardless if someone already visited the page or not.

**Comment by BernhardBaumrock** [comment]
Yeah. It was a quick idea that I wanted to share. When I finished the post I already had some possible problems in my head, but I wanted to share it nonetheless as sometimes bad ideas can be turned into great ideas by someone else :)

**Comment by ryancramerdesign** [comment]
If it would be useful to you guys, I can certainly add it as a config option for the module. I'll plan to do that.

**Comment by horst-n** [comment]
@ryancramerdesign Not sure what others think, but for me it would be good if the module also can pickup that config option from the site/config.php, means:
1) the module config property is the default, 
2) but when a $config->pagePathHistoryDelayProperty exists, this overwrites the default module option.

**Comment by BernhardBaumrock** [comment]
> @ryancramerdesign Not sure what others think, but for me it would be good if the module also can pickup that config option from the site/config.php, means: the module config property is the default, but when a $config->pagePathHistoryDelayProperty exists, this overwrites the default module option.

This would be a great option for ANY module! Maybe we could have a general solution for that. Eg it would be great to read the config for TracyDebugger or AdminOnSteroids from a config file that can be shared across several projects. Or at least it could save us from a lot of clicking and just copy&paste a skeleton config once for every project and then customize.

If that config was somehow hookable to make different configs based on some variables that would even be better (when possible, no idea about timings of when module configs are loaded and when the api is ready etc).

**Comment by teppokoivula** [comment]
> This would be a great option for ANY module! Maybe we could have a general solution for that.

This is getting way off-topic (perhaps open a new request with more details?) but I've been doing this for my own modules for a while now. In many cases configuration in code is easier for me/us. It could be an interesting option if core had something for this readily available.

**Comment by BernhardBaumrock** [comment]
Agree. Would be great if you could open a new issue @teppokoivula  and show what you have so far. I had nothing more than just the idea when @horst-n mentioned his request ;)

**Comment by adrianbj** [comment]
Tracy also reports reading config settings from config.php, but agreed that having a standard core approach for this would be best.

**Comment by Toutouwai** [comment]
Closing this as PagePathHistory now has a configurable "Minimum age" setting. Thanks @ryancramerdesign .
