### ISSUE TITLE
Fix empty "Untagged" Tag in Templates (From PR148)

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1016]
Link to [PR148](https://github.com/processwire/processwire/pull/148) by Tomas Kostadinov describing the issue, and containing the fix.  I'm reposting this here as it does appear to be an issue with a fix.

### Short description of the issue

If all templates have an assigned tag the "untagged" tag showed up as empty because of system fields being untagged. The linked PR resolves the problem.

### How to reproduce the initial problem:

1. Create Several templates
2. Go to the template overview
3. All Show up in the "untagged" Category
4. Assign a tag to all templates
5. Go to the template overview
6. The untagged category is empty but shows up

**Comment by ryancramerdesign** [comment]
Thanks @netcarver and @TomasKostadinov I've pushed a fix for this, though looks like I didn't tag it quite right, so here's the commit: https://github.com/processwire/processwire/commit/1aaef35474f371c737cea1fba40846d58d0dccb9

**Comment by netcarver** [comment]
@TomasKostadinov could you verify this fix and close the PR?  I have no rights to close issues/PRs on that repository.  Once that's done, please post here and I'll close this issue.

@ryancramerdesign Many thanks!
