### ISSUE TITLE
Fix Typo (from PR154)

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1017]
### Short description of the issue

Originally posted [here](https://github.com/processwire/processwire/pull/154) by rjgamer.

Includes fix.

**Comment by matjazpotocnik** [comment]
@netcarver @rjgamer This is fixed in https://github.com/processwire/processwire/commit/8455e497b7dcaf176bd868a651cb1df02989ca81

**Comment by netcarver** [comment]
@matjazpotocnik Thanks, closing.
