### ISSUE TITLE
Fix for PaginationString on last Page (from PR153)

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1018]
### Short description of the issue

Link to PR153 by Schnapsum.

Fix for last page getPaginationString when count mod limit != 0(e.g. with 15 pages on limit 10)

### Expected behavior

Fixed: P1: 1 to 10 of 15, P2: 11 to 15 of 15

### Actual behavior

Currently: P1: 1 to 10 of 15, P2: 11 to 20 of 20

### Suggestion for a possible fix

See [PR153](https://github.com/processwire/processwire/pull/153).

**Comment by ryancramerdesign** [comment]
@netcarver @Schnapsum I can't seem to duplicate the issue that this fixes, unless the PaginatedArray has errors in the inputs (start, total, limit). So I'm wondering about what's creating the PaginatedArray (or PageArray) that is producing the error you are seeing? I probably need to get a closer look at that to isolate the error. Thanks.

**Comment by netcarver** [comment]
@Schnapsum can you provide any more information to help Ryan out?

**Comment by matjazpotocnik** [comment]
I also can't replicate.

**Comment by netcarver** [comment]
Closing as inactive.
