### ISSUE TITLE
Wrong user language in saveReady()

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1020]
### Short description of the issue

```php
// ready.php

bd($this->user->language, 'ready.php');

$wire->addHookAfter("Pages::saveReady", function() {
  bd($this->user->language, 'saveReady');
});
```
![img](https://i.imgur.com/8pG7FvI.png)

### Expected behavior

User language should be the same in both cases. The language in ready.php is the correct one (german)

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/topic/22503-possible-bug-get-user-language-in-hook-pagessaveready
https://processwire.com/talk/topic/21029-access-user-language-in-init-before-ready/

### Setup/Environment

* ProcessWire version: 3.0.142

**Comment by netcarver** [comment]
Adding multiple status as this has also been reported via the forum.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock The pages.save operation is intentionally done while language is default. It changes it to default language at the beginning of save, and restores it back afterwards. This ensures that all fields are in a predictable state and language values don't get mixed up or overwrite each other. If you need to identify the language, you can hook either before or after `Pages::save()` as the language will be in its original state in either case.

**Comment by BernhardBaumrock** [comment]
Hi @ryancramerdesign  thx for the clarification!
