### ISSUE TITLE
Warning in PHP 7.4.0 RC4

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1021]
I get on some Admin Pages this Warning with PHP 7.4.0 RC4 and PW 3.0.143:

_Notice: Trying to access array offset on value of type int in /var/www/html/wire/core/PagesLoader.php on line 138_

I think I have a fix in this PR:
https://github.com/processwire/processwire/pull/155

**Comment by ryancramerdesign** [comment]
Thanks @tiefenb I have pushed a fix for this issue. Looks like I had some redundant logic in that method, so I ended up refactoring it a bit further than fixing the issue.
