### ISSUE TITLE
Template sorting by modified date is incorrect

### ISSUE THREAD

**Issue by eelke** [processwire/processwire-issues#1023]
### Short description of the issue

In the templates overview, when sorting templates on Modified date, the templates seems to get sorted on the relative string value of the date instead of the actual date. This issue may exist elsewhere too. 

### Expected behavior

Sort by actual date (and display the relative date)

### Actual behavior

Sorts by string value.

### Optional: Screenshots/Links that demonstrate the issue

![Schermafbeelding 2019-11-04 om 11 40 26](https://user-images.githubusercontent.com/738902/68115360-89dfc980-fef8-11e9-88cf-a7768c56207d.png)

### Optional: Suggestion for a possible fix

Split the sorting into two distinct parts: the actual date value is used for sorting, the parsed only gets used for displaying purposes.

### Steps to reproduce the issue

1. Go to Templates overview
2. Sort on 'Modified'

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.144|
|PHP|7.2.21|
|Webserver|Apache|
|MySQL|5.7.26|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|BreadcrumbDropdowns|0.1.21|
|FieldtypeFloatRange|0.0.2|
|FieldtypeImageReference|0.0.1|
|FieldtypeLeafletMapMarker|3.0.3|
|FieldtypeMultiMarker|0.0.2|
|FieldtypeRepeaterMatrix|0.0.5|
|FieldtypeSelectRelation|0.0.3|
|FieldtypeTable|0.1.4|
|FormHelper|0.8.7|
|FrontendUser|0.9.3|
|InputfieldFloatRange|0.0.5|
|InputfieldImageReference|0.0.2|
|InputfieldLeafletMapMarker|3.0.3|
|InputfieldMultiMarker|0.0.1|
|InputfieldRepeaterMatrix|0.0.5|
|InputfieldTable|0.1.4|
|MarkupAddInlineScript|3.0.2|
|MarkupLeafletMap|3.0.2|
|MarkupSEO|0.8.7|
|MinimalFieldset|0.1.5|
|ProCache|3.1.8|
|ProcessPageListerPro|1.1.0|
|ProcessPicturaeImporter|0.0.1|
|ProcessProCache|3.1.8|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|RestApi|0.0.6|
|SelectizeTemplateFieldTags|0.0.8|
|TemplateFieldWidths|0.1.10|
|TextformatterVideoEmbed|1.1.1|
|TracyDebugger|4.19.34|
</details>

**Comment by matjazpotocnik** [comment]
Sorting is working here. Your suggestion about a possible fix is already implemented (added span that contains timestamp).

![Screenshot 2019-11-05 06 29 01_cr](https://user-images.githubusercontent.com/7663992/68180957-fbba2080-ff95-11e9-88ad-6e4e9fd42d93.jpg)

**Comment by eelke** [comment]
> Sorting is working here. Your suggestion about a possible fix is already implemented (added span that contains timestamp).

Thank you for your insightful reply @matjazpotocnik, but it seems you are on a different version. Yours (not sure which) uses `<span style='font-size: 0'>` to hide the span, while (my) version 3.0.144 uses `<span style='display:none;'>` for that purpose. In fact, it seems this has been the case [for about 3 years](https://github.com/processwire/processwire/blame/dev/wire/modules/Process/ProcessTemplate/ProcessTemplate.module#L451). 

Regardless, the correct timestamps are in fact put into this <span>, so my current guess is the javascript isn't working correctly.

![Schermafbeelding 2019-11-05 om 07 53 59](https://user-images.githubusercontent.com/738902/68185305-881e1080-ffa1-11e9-8c48-ab375c3d23fb.png)

**Comment by matjazpotocnik** [comment]
Aha, we are not looking at the same source! My screenshot is from ProcessLogger, where font-size: 0 is used, while yours is from ProcessTemplate, where display: none is used. I tried on PW 3.0.104 and sorting is working in all cases, regardless of what method is used to hide the actual data/timestamp.

**Comment by BernhardBaumrock** [comment]
That's a clever and easy solution :) For me it works on Chrome both with `display: none` and `font-size: 0`

**Comment by eelke** [comment]
> That's a clever and easy solution :) For me it works on Chrome both with `display: none` and `font-size: 0`

@BernhardBaumrock On pw 3.0.144?

Edit: I have noticed the same behaviour on another site, another server, running PW 3.0.123, both in Chrome and Firefox.

**Comment by eelke** [comment]
It's getting weirder. With a little bit of jQuery to display the hidden span `$("tr[role=row] td span").css({"display": "inline", "font-size":"1rem","margin-right": "5px", "color":"red"});`, it now seems that this behaviour appears at random. While one group of templates (I use tags) seems to get sorted correctly, another does not. 

![screenshot](https://user-images.githubusercontent.com/738902/68204646-bd8a2480-ffc8-11e9-8f17-f20fad8a2558.png)

**Comment by matjazpotocnik** [comment]
Hm, that's odd. Can't test right now, but it looks like a combination of "1 month" and "11 months" plays a role here? Any odd characters before 1544736745?

**Comment by eelke** [comment]
> Any odd characters before 1544736745?

Not that I can tell. This is the full TD node: `<td><span style="display: none;">1544736745</span>11 months ago</td>`

**Comment by matjazpotocnik** [comment]
I'm able to reproduce:

![image](https://user-images.githubusercontent.com/7663992/68217742-6cd3f500-ffe3-11e9-867d-27ec45558cf7.png)

**Comment by matjazpotocnik** [comment]
And a possible fix: in ProcessTemplate.module, line 451, change form this:

`$row[] = $mod > 0 ? "<span style='display: none;'>$mod</span>" . wireRelativeTimeStr($mod) : '';`

to this (blank character inserted before closing span):

`$row[] = $mod > 0 ? "<span style='display: none;'>$mod </span>" . wireRelativeTimeStr($mod) : '';`

And possibly the same in ProcessPageEditImageSelect.module, L 1549 (untested).

**Comment by eelke** [comment]
@matjazpotocnik's Suggested fix indeed fixes my original problem

**Comment by ryancramerdesign** [comment]
Thanks guys, good find — I've pushed a fix using @matjazpotocnik suggested solution

**Comment by BernhardBaumrock** [comment]
nice find :) thx @matjazpotocnik

**Comment by netcarver** [comment]
@eelke If you could close this now, that would be great. Thank you!

**Comment by eelke** [comment]
Closing. Thanks everyone!
