### ISSUE TITLE
Moving fieldset with fields within a template leads to unexpected sorting after save

### ISSUE THREAD

**Issue by NilsWiere** [processwire/processwire-issues#1025]
**Expected behavior**
When I move a fieldset (open) within the template setup page, the fields inside should follow on the new position as well while staying inside the fieldset. So it should remain a consistent group without any changes.

**Actual behavior**
I drag the fieldset and drop it to the new position. All fields inside follow as well, the group looks the same es before but on the desired position. Fine. However, when I hit "Save", other fieldsets appear in the fieldset (see attached GIFs). Plus, when I drag the fieldset to a position further down I get this Error: "ProcessTemplate: Error with placement of fieldset/tab "fieldset_open_a" - please fix and save again".

Moving the fieldset down
![fieldset-issue](https://user-images.githubusercontent.com/10728361/68213383-c1737200-ffdb-11e9-967a-524392f5142c.gif)

Moving the fieldset up
![fieldset-issue-2](https://user-images.githubusercontent.com/10728361/68213409-ccc69d80-ffdb-11e9-8294-78a297d6b7a8.gif)

**Steps to reproduce the issue**

1. Create several fields and assign them to a template
2. Create fieldset field and assign it to the template
3. Add a few fields between fieldset (open) and fieldset (close).
4. Drag the fieldset (open) to a new position
5. Hit "Save"

ProcessWire version: 3.0.142 (but also happend with older versions)

**Comment by ryancramerdesign** [comment]
@NilsWiere Thanks for the report. I can duplicate the issue here as well. I think I've got it fixed now (latest commit), but need more testing to be sure. Please let me know if you find anything still doesn't work with this? Thanks.

**Comment by NilsWiere** [comment]
@ryancramerdesign Yes, I can confirm it works now in my setup. Thanks for the quick response!

**Comment by netcarver** [comment]
@NilsWiere Hi Nils, great to hear this is now working for you. Could you close this issue now? (If you close it, you can re-open it again if needed - if I close it, you can't.)  Thank you!
