### ISSUE TITLE
Page Path History not redirecting when home template has urlsegments enabled

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1026]
### Short description of the issue

Page Path History not redirecting when home template has urlsegments enabled. The logic in my home.php file checks to see if the segment is valid and, if not, it throws a 404, but PagePathHistory doesn't seem to kick in after the 404 is thrown.

### Expected behavior

If a 404 is thrown, PagePathHistory should check to see if there is an entry to a valid page for the current url and redirect to it.

### Actual behavior

Page stays at the 404

**Comment by ryancramerdesign** [comment]
@adrianbj Path history comes into play if the URL did not resolve to a Page. In your case, the URL did resolve to a Page, but you threw your own 404 afterwards. Since you threw the 404, it assumes that's what you want and intend, and so it specifically detects that case to prevent PagePathHistory from overriding your command. See here: https://github.com/processwire/processwire/blob/dev/wire/modules/PagePathHistory.module#L552

I do think it should honor a 404 thrown manually and intentionally on the front-end, and not convert it to be something different. But I understand what you are suggesting and I'd like to support the option. Perhaps it makes sense as a configuration setting for the PathPathHistory module?

**Comment by adrianbj** [comment]
Ah I see - I didn't see the difference with a manually thrown 404. 

I would love to see some way to support this though - maybe even when you throw the 404? with a `true` parameter or something? Not sure what's best.

If it's not too much trouble it would be awesome to know what timeframe you think you might consider working on this because it's kinda a big deal on a project here at the moment. I can probably sort out a workaround, but would be good to know if I need to or not :)

Thanks a lot.

**Comment by adrianbj** [comment]
Ryan - is this really "not a bug"? I guess I don't understand how it's currently possible to have urlsegments enabled on the home template and still have PagePathHistory work at all. There are always going to be times with urlsegments where you need to throw a 404. Is there an alternate approach that I am missing that makes it possible to use the two together?

Thanks.

**Comment by teppokoivula** [comment]
I would say that it's a bit opinionated, but the way that PagePathHistory currently handles this can definitely be seen as a feature, not a bug: basically it's being very cautious about what the real intention of the user might've been.

While this seems unexpected to me as well (I would've expected that throwing a 404 would result in a redirect – when I use that in my own code, my intention has always been that things should work just as they would if a page really wasn't found) a good alternative might be documenting this behaviour somewhere (if it's not already documented), and instructing the developer to perform a manual check in such cases.

Technically that manual check just means calling the (public) PagePathHistory::getPage() method and performing a redirect, but if you're working on multi-lingual site it gets a bit more complex and you'll end up duplicating all of the PagePathHistory::hookPageNotFound() method. Doable, but I wonder if Ryan would consider moving everything after the Page check to separate method, in which case one would just have to call that and provide a path to get the expected result? :)

Just an idea, really.

**Comment by ryancramerdesign** [comment]
> Is there an alternate approach that I am missing that makes it possible to use the two together?

When using URL segments, you can specify what URL segments the template is allowed to be a handler for (or you can specify the pattern if that's preferable). But if you enable URL segments with no filters/limits, and the URL doesn't resolve to some other page, then your template is in full control of it. In your case, it sounds like that's not what you want, so specifying what URL segments you want it to handle (in template settings URLs tab) would be a solution. 

> …maybe even when you throw the 404? with a true parameter or something? Not sure what's best.

Yes, I like that idea: `throw new Wire404Exception(true)`. I'll implement that. Even though the first argument to an Exception object is technically a string, it can still be detected as `$value === "1"`.

**Comment by adrianbj** [comment]
The problem with using the pattern limit for the segment is that these segments are partner/affiliate links, like: https://mysite.com/nike so they could be anything. I almost went with https://mysite.com/partner/nike but decided that the root was shorter / cleaner for the user, but that was obviously before I discovered the issues with PPH. 

> Yes, I like that idea: throw new Wire404Exception(true). I'll implement that.

Thanks, that would be great!

**Comment by ryancramerdesign** [comment]
@adrianbj I meant to link the commit to this thread, but this commit [here](https://github.com/processwire/processwire/commit/595429d425c5e6a64c24f61af2edc5503d792101) adds support for this. You can call `throw new Wire404Exception(true);` and PagePathHistory will be used. But I wanted something a little shorter and easier to remember, so added a `wire404()` function that you can call instead (as a dedicated 404 function for the front-end), and it does the same thing.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that is exactly what was needed. Now I can have my homepage url segments and page path history still works!

Thank you!
