### ISSUE TITLE
Page name not cleaning up double dash characters

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1029]
### Short description of the issue

Short description goes here.
![image](https://user-images.githubusercontent.com/871211/68532085-4ad1bf80-02ce-11ea-8cf8-3e794846bd89.png)

### Expected behavior

I would expect the name would be `this-that`

### Actual behavior

Name is `this--that`

Not sure if this in intentional or a bug, but I think it's a bug :)

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks Ryan.
