### ISSUE TITLE
InputfieldButton with href attribute within process page - href target is triggered twice

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#1030]
### Short description of the issue

In a process page, clicking an an InputfieldButton with href attribute - the href target is triggered twice. In my sample the button target is "linked" to a method which resends an invoice for an order. Due to the problem the invoice is sent twice. 

### Expected behavior

If an InputfieldButton with href attribute is clicked, the href target should be only triggered once.

### Actual behavior

Clicking an an InputfieldButton with href attribute - the href target is triggered twice: 1 times as native browser behavior (when clicking a tags) and 1 times initiated by JavaScript. See sample code below:

```php
        /** @var InputfieldButton $btn */
        $btn = $modules->get('InputfieldButton');
        $btn->id = 'resend_invoice';
        $btn->href = $this->currentUrl . '?action=resend_invoice&modal=1';
        $btn->value = $this->_('Resend Invoice');
        $btn->icon = 'refresh';
        $btn->secondary = true;

        $out .= $btn->render();
```

If I use a simple a href instead of the InputfieldButton it works like expected (see sample clip below).

```php
        $out .= '<a href="' . $this->currentUrl . '?action=resend_invoice&modal=1">Resend invoice</a>';
```

### Optional: Screenshots/Links that demonstrate the issue

![pw_button](https://user-images.githubusercontent.com/876737/68659570-bff3fd80-0537-11ea-8809-6b4e71280d56.gif)

### Optional: Suggestion for a possible fix

I think the problem lies here:

https://github.com/processwire/processwire/blob/4e4b3afdcbe9aef27d03170dab64dc6e8e6c5a4d/wire/templates-admin/scripts/main.js#L90-L98

```javascript
        ....
		}).on('click', 'a > button', function() {
			var $a = $(this).parent();
			var target = $a.attr('target');
			if(typeof target != "undefined" && target == '_blank') {
				// skip
			} else {
				// make buttons with <a> tags click to the href of the <a>
				window.location = $a.attr('href'); <--- problem!
			}
		});
	},
```

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.145|
|PHP|7.2.21|
|Webserver|Apache|
|MySQL|5.7.26|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeSnipWireTaxSelector|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.7|
|ProcessProMailer|0.0.7|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SnipWire|0.0.1|
|TracyDebugger|4.19.36|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @gadgetto I've pushed your suggested fix for the issue. I don't know why that code was there in the first place (seems redundant), but thinking it might have been related to working around some Firefox issue a long time ago. I don't really know for sure, but will keep an eye out for any side effects just in case.

**Comment by gadgetto** [comment]
Thanks, this seems to fix the problem!
