### ISSUE TITLE
Error notifications in admin should not be collapsed

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1032]
### Short description of the issue

When multiple notifications of the same type occur in admin they are collapsed and only the first notification is shown. Error notifications should never be collapsed IMHO because errors are critical information that the user should see.

Demonstration:
```php
$pages->addHookAfter('saveReady', function(HookEvent $event) {
    $page = $event->arguments(0);
    if($page->template == 'news_item') {
        $event->wire()->error('Error number one.');
        $event->wire()->error('Error number two.');
    }
});
```
![2019-11-13_163052](https://user-images.githubusercontent.com/1538852/68730856-0d08ca00-0633-11ea-9da8-7ec2626708c1.png)

One more thing: besides error notifications that should never be collapsed, sometimes you might want to show particular warning or notice level notifications in an uncollapsed state. Is there some way to specify that a particular notification you are issuing should never be collapsed?

### Setup/Environment

* ProcessWire version: 3.0.145

**Comment by teppokoivula** [comment]
Agreed. Makes sense to hide the messages if they are identical, but if they are not then current behaviour is very likely to result in users not noticing those additional messages at all.

> Is there some way to specify that a particular notification you are issuing should never be collapsed?

In case there is, I'd be interested in this as well. Just ran into this with one of my modules where I need the user to acknowledge various notices, yet currently only the first one gets displayed and others are hidden (and thus unlikely to be seen).

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai @teppokoivula I agree, I have added support for this.

**Comment by Toutouwai** [comment]
Thanks!

**Comment by ryancramerdesign** [comment]
Btw to force any notification to display on its own rather than grouped with others, you add the Notice::noGroup flag when adding it:
~~~~~
$this->message('Some message you must see', Notice::noGroup); 
~~~~~
Error notifications now do this automatically as well.
