### ISSUE TITLE
WebP image extra not deleted when original is replaced

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1033]
When the original image that has webp extra is replaced, webp extra is not removed (or recreated?). To replicate the behavior: upload an image, create webp extra (by calling $myimage->webpurl), then in the admin replace the image by uploading image with the same name eg. replace img.jpg with img.jpg. Original image is replaced, admin thumb is recreated, but webp stays the same. 

![webp](https://user-images.githubusercontent.com/7663992/68743466-d57a2d80-05f2-11ea-8946-bb6ef7564017.gif)

I added `$pagefile->extras('webp')->unlink();` in InputfieldFile.module in ___processInputAddFile() method, after $pagefile->removeVariations(), line 800.

PW 3.0.145

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks for the report. I've pushed a fix for this issue.

**Comment by matjazpotocnik** [comment]
Thx!
