### ISSUE TITLE
Pagefile(s)/image(s) - no sort value

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1034]
### Short description of the issue

Pagefile and Pageimage objects do not appear to have a sort value as outlined here: https://processwire.com/api/ref/pageimage/#pwapi-methods-other

### Expected behavior

```php
foreach($page->files as $f) {
	echo $f->sort;
}
// 0, 1, 2, 3 etc
```

### Actual behavior

Nothing is returned (null).

### Setup/Environment
* ProcessWire version: 3.0.145
* (Optional) PHP version: 7.3

**Comment by ryancramerdesign** [comment]
@chriswthomson Looks like you are right, there is no sort property at runtime. Technically there is one in the database but it's not used at runtime. I'm updating the phpdoc to remove that property. Thanks.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

Thanks - it would be a useful property to be able to access, but I guess it can easily inferred while traversing Pagefiles anyway.

Cheers,

Chris
