### ISSUE TITLE
$datetime->elapsedTimeStr returns blank when 0 seconds have elapsed

### ISSUE THREAD

**Issue by 16th-earl** [processwire/processwire-issues#1035]
### Short description of the issue

```
$datetime->elapsedTimeStr(time(), time(), false)
$datetime->elapsedTimeStr(time(), time(), true)
$datetime->elapsedTimeStr(time(), time(), 1)
```

… all return blank. These examples are contrived but I've had the problem crop up in the real world when measuring a task that completed very quickly.

`$datetime->elapsedTimeStr(time(), time(), 0)
`
… correctly returns 00:00:00

### Expected behavior

```
$datetime->elapsedTimeStr(time(), time(), false) === "0 seconds"
$datetime->elapsedTimeStr(time(), time(), true) === "0 secs"
$datetime->elapsedTimeStr(time(), time(), 1) === "0s"
```
### Actual behavior

```
$datetime->elapsedTimeStr(time(), time(), false) === ""
$datetime->elapsedTimeStr(time(), time(), true) === ""
$datetime->elapsedTimeStr(time(), time(), 1) === ""
```
* ProcessWire version: 3.0.142
* (Optional) PHP version: 5.4.16

**Comment by matjazpotocnik** [comment]
This might be intended behavior. It can be "fixed" by adding `$times['seconds'] = 0` in WireDateTime.php, line 606.

**Comment by ryancramerdesign** [comment]
Thanks @16th-earl I've pushed a fix for this issue.

**Comment by 16th-earl** [comment]
Thanks Ryan!
