### ISSUE TITLE
webp not served when pagefileSecure=true

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1038]
Webp images are served with content type application/octet-stream instead of as 'image/webp' when $config->pagefileSecure = true;

I can fix this with $config->fileContentTypes('webp', 'image/webp'); but I think it would be good to have this covered by adding webp to fileContentTypes array in config.php L597.

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik good idea — I have updated the fileContentTypes.

**Comment by matjazpotocnik** [comment]
Thank you.
