### ISSUE TITLE
Setting variable to user object results in isLoggedin() returning true

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1039]
### Short description of the issue

Short description goes here.
![image](https://user-images.githubusercontent.com/871211/69757857-e65a9100-1112-11ea-96cf-076ececb232a.png)

### Expected behavior

Honestly I am not sure if this is expected behavior or not, but I it surprised me - I thought a
`$session->forceLogin($u);` would be required before `isLoggedin()` would return true.

Note that I am viewing the site as a guest user.

**Comment by teppokoivula** [comment]
If you take a look at User.php, you'll notice that a User object is always considered logged in unless it's the guest user: https://github.com/processwire/processwire/blob/dev/wire/core/User.php#L422:L440. In that regard I'd say that this is indeed the expected behaviour.

Note that what you're doing here is not the same as logging _current_ user in; that still requires forceLogin or something similar. You're instantiating a specific user, and in this scenario I don't really see much sense in checking the isLoggedin() state of said user :)

**Comment by adrianbj** [comment]
> You're instantiating a specific user, and in this scenario I don't really see much sense in checking the isLoggedin() state of said user :)

I agree, it probably doesn't make much sense, but it tripped me up for a minute because if the current user wasn't logged in, I wanted to work with a different user (1033 in the example above).

Thanks for pointing to that code - I don't think I realized that `isLoggedin()` is really just the opposite of `isGuest()` - I guess that makes sense when applied to the current `$user`, but it does seem a little weird to me if your applying the check to a manually instantiated user.

Not to worry I suppose :)

**Comment by Toutouwai** [comment]
@adrianbj, if you're wanting to find out if some given user is currently logged in then one approach is to install SessionHandlerDB and then look for the user's ID in that module's table.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - not actually what I was trying to do - I was just simply trying to check if the current user is logged in but I started by setting the current `$this->wire('user')` to `$u` (working in a module) and then kept using that `$u` when I really needed to be looking back at `$this->wire('user')`. It's basically user error on my part, but I still was surprised to see the way `isLoggedin()` worked in this scenario. I have probably come across this before, but forgotten about it :)

**Comment by kixe** [comment]
> @adrianbj, if you're wanting to find out if some given user is currently logged in then one approach is to install SessionHandlerDB and then look for the user's ID in that module's table.

@Toutouwai Could you provide a code snippet?

**Comment by Toutouwai** [comment]
@kixe, a forum post that will get you started: https://processwire.com/talk/topic/4553-how-do-i-get-a-list-of-online-users/?do=findComment&comment=196272

**Comment by kixe** [comment]
@Toutouwai Thanks. I found the same in core (since?)
https://processwire.com/talk/topic/4553-how-do-i-get-a-list-of-online-users/?do=findComment&comment=209209
... but it does not work if ProcessWire is bootstrapped ...
