### ISSUE TITLE
InputfieldPageAutocomplete - Pipes (|) in data-url issue

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1040]
### Short description of the issue

When using [6G htaccess firewall](https://perishablepress.com/6g/), pipes (|) are not allowed in URLs. 

When using InputfieldPageAutocomplete with multiple selectable templates, the data-url value is rendered with pipes (e.g. template|another-template). This leads the query to fail.

### Optional: Suggestion for a possible fix

`InputfieldPageAutocomplete::getAjaxUrl()` change | to %7C (line 300).

For the time being I use this hook:

```php
$wire->addHookAfter("InputfieldPageAutocomplete::render", function(HookEvent $event) {
	$out = $event->return;
	if(strpos($out, "data-url") === false) return;
	$url = explode("'", ltrim(explode("data-url=", $out)[1], "'"))[0];
	$event->return = str_replace($url, str_replace(" ", "+", str_replace("|", "%7C", $url)), $out);
});
```

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed your suggested fix here. Also added an str_replace() as it's possible there are other pipes (if user defined them in custom selector).

**Comment by chriswthomson** [comment]
Nice one, thanks.
