### ISSUE TITLE
Ongoing list of PHP 7.4 errors

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1041]
Now that PHP 7.4 is stable, it's important that PW supports it. Here is the start of the list of errors that I am seeing. Please feel free to add new ones to this issue!

ErrorException: Trying to access array offset on value of type bool in /Users/ajones/Sites/ecoreportcard/wire/core/PageTraversal.php:432

**Comment by matjazpotocnik** [comment]
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in:
/wire/core/PWGIF.php line 150, 154, 190, 313, 358, 402, 407, 412, 415, 423, 429, 45

**Comment by adrianbj** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in /wire/modules/Markup/MarkupHTMLPurifier/htmlpurifier/HTMLPurifier.standalone.php on line 3987, 14634, 21164, 21164

Note that this was fixed in the HTML purifier library back in July: https://github.com/ezyang/htmlpurifier/commit/b88fcd180c1d358baa2cf2346d0bb7e02fded20a

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed updates for these. I'd never seen that curly bracket syntax for arrays before, didn't even know that was ever a thing. Seems like a good thing to deprecate!

@adrianbj That PageTraversal error actually suggests it might be getting an invalid return value from PageFinder. I tried to duplicate, but couldn't find any way to get an invalid return value from PageFinder or get the the "array offset on value of type bool" there (I only ever had array). So while I've pushed an update that should fix this for PHP 7.4, it makes me think there's potentially something deeper in PageFinder revealed by this. Do you know how to duplicate it? What was the situation where you called next() to get that error?

**Comment by adrianbj** [comment]
@ryancramerdesign - the call was to `prev()` when there wasn't actually a previous sibling. It showed up in Tracy's RequestInfo panel when viewing the main page tree in the admin where `page->id` equals 3.

Your fix takes care of it though so I think we're all good.

**Comment by netcarver** [comment]
@ryancramerdesign Ryan, do you want this left open and tagged 'ongoing-open' or close it and have new issues opened for 7.4 compat issues?  The latter may happen anyway if users don't search for open issues first.

**Comment by ryancramerdesign** [comment]
@adrianbj Good to hear, thanks for testing. Also forgot to mention that HTMLPurifier updated as well. 

@netcarver I think better to have new issues opened, unless we end up with a regular stream of reoccurrence of this issue, so I'll close it for now. Thanks.
