### ISSUE TITLE
Typo in Wire.php, line 1199

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1042]
Version 3.0.146:

`@param string $text|array|Wire Title of notice` should be `@param string|array|Wire $text Title of notice`

**Comment by chriswthomson** [comment]
Found another tiny one in WireMail.php, line 613:

`if($toName) $to = $this->bundleEmailAndName($to, $toName); // bundle to "User Name <user@example.com"`

should be:

`if($toName) $to = $this->bundleEmailAndName($to, $toName); // bundle to "User Name <user@example.com>"`

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've corrected those.

**Comment by chriswthomson** [comment]
👍
