### ISSUE TITLE
$config->setLocation() uses undefined variable $path instead of $dir

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1043]
Crosslinking to PR by @thkuhn https://github.com/processwire/processwire/pull/156 where an undefined variable name `$path` is used in /wire/core/Config.php line 296 (linked PR has suggested fix)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik @thkuhn good find, I've pushed the suggested fix for this

**Comment by matjazpotocnik** [comment]
Thank you.
