### ISSUE TITLE
Caching Error Message not Helpfull

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#1044]
### Short description of the issue
If an array is saved to cache with not well formated utf8 content, processwire throws an unspecific error, because of json_encode returning "false".

/wire/core/WireCache.php in ProcessWire\WireCache::save at line 450
```
   if(is_array($data)) {
	$data = json_encode($data);
	if($data === false) throw new WireException("Unable to encode array data for cache: $name"); 
   }
```

### Expected behavior

json_encode has flags, that would throw more specific errors pointing out the data that is incorrect, as well as options to simply ignore the problematic parts:

JSON_THROW_ON_ERROR
JSON_INVALID_UTF8_IGNORE

### Optional: Screenshots/Links that demonstrate the issue

https://sentry.io/share/issue/59801717a39648bd97c73c1c959ab4cd/

### Optional: Suggestion for a possible fix

Use at least the JSON_THROW_ON_ERROR flag:
json_encode($data, JSON_THROW_ON_ERROR);

Or even json_encode($data, JSON_INVALID_UTF8_IGNORE + JSON_THROW_ON_ERROR);

### Setup/Environment

Lastest DEV Version…

**Comment by noelboss** [comment]
Or try catch with the cache name…

**Comment by ryancramerdesign** [comment]
@noelboss I don't think we can do that here because those flags are new to to PHP 7.3 and 7.2, and we currently support earlier versions of PHP than that.
