### ISSUE TITLE
Ajax Page Search Selectors Ignore Fields With Uppercase Letters

### ISSUE THREAD

**Issue by zoaked** [processwire/processwire-issues#1045]
### Short description of the issue

When an ajax search that references a field name with an uppercase letter is performed, the search is completed only using the other criteria.

### Expected behavior

All valid selector parameters are incorporated into the page search

### Actual behavior

The ajax searching is handled by `ProcessPageSearch->executeFor()`.  In there each selector parameter is sanitized before being checked if it can be used or not.  The sanitizer is calling `pageName()` for some reason even though it is checking field names.  Page names are automatically lower cased as a part of the sanitization process.  Then later these lowercased names no longer match the real field names and so are being ignored.

(sanitization) https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageSearch/ProcessPageSearch.module#L340
(verification) https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageSearch/ProcessPageSearch.module#L385
(where the fields should be matching, but are not) https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageSearch/ProcessPageSearch.module#L961

### Optional: Suggestion for a possible fix

There is a comment on L340 that references not using `fieldName` as the period was required.  Both `fieldName` and `pageName` delegate the actual filtering to `nameFilter` so this can be resolved by calling that directly and passing appropriate parameters that the `fieldName`/`pageName` helper methods typically set.
`$name = $sanitizer->nameFilter($name, array('_', '.'), '_');`

### Steps to reproduce the issue

1. Create any field with an uppercase letter in the name
2. Use any of the page searching mechanisms to find pages that match that some criteria
3. Notice that the results brings back a page list with every page in the system

In my specific case the ajax search was being done by a Page Reference field and used the "Selector String" under "Input" "Selectable Pages" section to reference the uppercase letter field.  This page reference field was added to a template and the issue occurred while editing a page using that template.

### Setup/Environment

* ProcessWire: 3.0.123 (same issue exists in master)
* PHP: 7.1.10

**Comment by ryancramerdesign** [comment]
Thanks @zoaked I've pushed a fix for this. We now have a sanitizer method that's perfect for the case, which is the `$sanitizer->fieldSubfield()` method.

**Comment by netcarver** [comment]
@zoaked Closing this now. Please post here again if needed.
