### ISSUE TITLE
FilenameArray::remove() should use getKey() instead of array_search()

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1046]
### Short description of the issue
In a custom module, I need to replace/ remove a script added by the **FilenameArray** class. For a proper search, the attached version number should be ignored. The **add()** and **prepend()** functions already use **getKey()** to avoid duplicates. **remove()** should use this function as well.

### Expected behavior

Proper **remove()** of script or style files if needed.

### Actual behavior

Cannot easily find the filename in array added by **Modules::loadModuleFileAssets()** due to appended query string (version number)

### Suggestion for a possible fix

Replace line 109 and 110 with:
```
		$key = $this->getKey($filename);
		unset($this->data[$key]); 
```
https://github.com/processwire/processwire/blob/987d23154df1cda79c46e8bacf4a5fdf07bc2056/wire/core/FilenameArray.php#L109-L110

### Setup/Environment

* ProcessWire version: 3.0.145

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed your suggested fix.

**Comment by kixe** [comment]
Thanks
