### ISSUE TITLE
PHP 7.4 warning

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1047]
Ryan, you missed this one:

PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in:
/wire/core/PWGIF.php line 407

And this one popped up:

PHP Notice: Trying to access array offset on value of type null in ProcessTemplate.module:638 while editing a template, introduced here: https://github.com/processwire/processwire/commit/8e91a05fd111ffee2f0ac0aef486259412f462ba

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed fixes for this
