### ISSUE TITLE
Wrong CSS

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1048]
There is a wrong CSS declaration in InputfieldImage.scss, line 731 and 886,
` width: 100% important;` should be `width: 100% !important;`

And this:

`transition: opacity .2s 02;` (line 285)
`transition: opacity .2s 1s;` (line 290)

I'm not familiar with "02" or "1s" transition-timing-function.

In InputfieldFile.scss line 208 we have `filter: alpha(opacity=0);`. I think we don't need this anymore.

And while working with css, would you please add to uikit.pw.scss, see https://github.com/processwire/processwire-issues/issues/812:

```
.pw-masthead-hidden {
    display: none;
}
```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Thanks. Are you aware of any of these causing output issues at present? If they aren't causing anything to break, I'd like to return to these after the next master, just in case they introduce some new unexpected issue, despite producing likely useless css at present. 

I'm not sure about those two transition opacity lines. I think those originally came from @LostKobrakai since he developed large parts of the current image field implementation (especially on the JS/CSS side), so adding him here in case he knows.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I'm not aware of any issues with the width, transition and filter, I just found them by chance, Firefox reported them. I guess browsers fix or ignore them so it looks a good plan to tackle them in the next dev with Benjamin's support.

But the last one regarding .pw-masthead-hidden is something that affects Firefox users on smaller viewports for a long time and many users has reported that the fix is ok. Then again, I'm also ok with the plan to fix this in the next dev, just please keep it on your radar.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign @LostKobrakai 
Found another one that makes IE11 render the image field strange:

![Screenshot 2019-12-30 09 54 45_cr](https://user-images.githubusercontent.com/7663992/71574811-b2e09d00-2aea-11ea-861c-22d67511ba2d.jpg)

1. There is a background image shown around an image. The problem is that IE doesn't understand `background: initial` set on `.InputfieldImageEditAll .gridImage__overflow`. I changed that to `background: none` to fix it. 

2. Also, when you hover over the image, the whole area around the image is colored green. Again:
`.InputfieldImageEditAll .gridImage:hover .gridImage__inner {background: none}`

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I have added the items you've mentioned that seem safe to do before master merge. Will wait to hear from @LostKobrakai on the transition properties, and will apply the others in 3.0.150.

**Comment by matjazpotocnik** [comment]
@LostKobrakai, I would like to close this issue, would you mind commenting on this:

`transition: opacity .2s 02;`

in 

https://github.com/processwire/processwire/blob/31524d7a5a06182614301d88bf0921fa171f6405/wire/modules/Inputfield/InputfieldImage/InputfieldImage.scss#L290

as requested by Ryan?

**Comment by LostKobrakai** [comment]
I'm not sure how the `02` came into being (it's been years), but the notation of `property timing delay` is a valid one (https://developer.mozilla.org/de/docs/Web/CSS/transition#syntax). I don't have a processwire install at hand to test this. Feel free to adjust the values to make sense.

**Comment by matjazpotocnik** [comment]
I can't find "timing delay" property, there are transition-property (opacity), transition-duration (.2s), transition-timing-function (02) and transition-delay (not specified). Supported values for transition-timing-function are (https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function):

```
/* Keyword values */
transition-timing-function: ease;
transition-timing-function: ease-in;
transition-timing-function: ease-out;
transition-timing-function: ease-in-out;
transition-timing-function: linear;
transition-timing-function: step-start;
transition-timing-function: step-end;

/* Function values */
transition-timing-function: steps(4, jump-end);
transition-timing-function: cubic-bezier(0.1, 0.7, 1.0, 0.1);

/* Steps Function keywords */
transition-timing-function: steps(4, jump-start);
transition-timing-function: steps(10, jump-end);
transition-timing-function: steps(20, jump-none);
transition-timing-function: steps(5, jump-both);
transition-timing-function: steps(6, start);
transition-timing-function: steps(8, end);

/* Multiple timing functions */
transition-timing-function: ease, step-start, cubic-bezier(0.1, 0.7, 1.0, 0.1);

/* Global values */
transition-timing-function: inherit;
transition-timing-function: initial;
transition-timing-function: revert;
transition-timing-function: unset;
```

**Comment by LostKobrakai** [comment]
From the docs I linked:
```css
/* property name | duration | delay */
transition: margin-right 4s 1s;
```

> transition: opacity .2s 1s; (line 290)

This is valid

> transition: opacity .2s 02; (line 285)

This is not valid. It could be I intended this to be `2s`, but I can't be sure after all the time.

**Comment by matjazpotocnik** [comment]
`transition: opacity .2s 1s;` is interpreted as `transition: opacity .2s ease 1s;`
`transition: opacity .2s 02;` is invalid and ignored by the browser

There are two options:

1. change from `transition: opacity .2s 1s;` to transition: `transition: opacity .2s ease 1s;` (line 295) and remove `transition: opacity .2s 02;` (line 290) or 
2. change from `transition: opacity .2s 1s;` to transition: `transition: opacity .2s ease 1s;` (line 295) and change`transition: opacity .2s 02;`  to `transition: opacity .2s ease 1s;` (line 290)

I would go with option 1 as this wouldn't break anything since the invalid transition property wasn't working in the first place. Let @ryancramerdesign decide what to do.
