### ISSUE TITLE
InputfieldToggle::sanitizeValue 

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1050]
### Short description of the issue

This is not a real bug. I get an error notice using this Inputfield in combination with a custom Fieldtype. The value of this fieldtype is an object. The class instantiating the value object provides a magic **__toString()** function. Would be great if the sanitizer could handle this as well.

```
Notice: Object of class CustomClass could not be converted to int in .../wire/modules/Inputfield/InputfieldToggle/InputfieldToggle.module on line 178
```
https://github.com/processwire/processwire/blob/3bf29d050b7f542f04628fc69c2448466e167acd/wire/modules/Inputfield/InputfieldToggle/InputfieldToggle.module#L178

### Suggestion for a possible fix

Typecast $value to string before converting to int by surrounding $value with quotes.

```
	$intValue = strlen("$value") && ctype_digit("$value") ? (int) "$value" : '';
```

### Setup/Environment

* ProcessWire version: 3.0.147

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've added your suggestion for this.

**Comment by kixe** [comment]
Thanks @ryancramerdesign
