### ISSUE TITLE
custom fields in file/image fields don't work with url multilanguage field

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1054]
When using a multi-language URL field as a [custom field](https://processwire.com/blog/posts/pw-3.0.142/#how-to-setup-and-use-custom-fields-in-file-image-fields) , it does not show up.
If I use a normal URL field it shows correctly.

### Steps to reproduce
I created the fields images (Image field) and external_url (URL multilanguage).
Created a template field-images.
Added external_url field to field-images template.
Edit a page where the images field is being used.
The external_url field does not show up.

Changed the field external_url to URL and it shows up in the page editor.

### Setup/Environment
SERVER DETAILS
ProcessWire: 3.0.145
PHP: 7.2.3
Webserver: Apache/2.4.27 (Win64) OpenSSL/1.0.2l 
MySQL: 5.7.19

**Comment by ryancramerdesign** [comment]
@jmartsch Currently only core multi-language fieldtypes are supported for file/image custom fields. Though will get back to adding support for more fieldtypes after the next major version is finished, and I'll add a note to also check on the multi-language URL one when the time comes. Below are the current limitations for file/image custom fields (source: https://processwire.com/blog/posts/pw-3.0.142/): 

> You may use fields of these types: Text, Textarea (non CKEditor), Integer, Float, Page Reference, Checkbox, Toggle, Datetime, Email, URL. You may also use the multi-language versions of core Fieldtypes. For Page Reference fields, you may also use any of the core input types it supports.
