### ISSUE TITLE
Wrong sample code in docblock for vex dialog: ProcessWire.confirm

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#1056]
In file `/wire/templates-admin/scripts/main.js` the sample code for vex confirm dialog seems to be wrong:

https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/templates-admin/scripts/main.js#L451

As far as I know vex dialogs don't have a return value so "if(" won't work (In some tests I always get undefined as return value).

I could be wrong, but in this case there is a missing parenthesis at the end of the code block:

```
	 * if(ProcessWire.confirm('Send this message now?', function() {
	 *   // user clicked Ok
	 * }, function() {
	 *   // user clicked Cancel
	 * })); // <-- added a parenthesis
```

**Comment by ryancramerdesign** [comment]
Thanks @gadgetto I've corrected that code example. That if() statement shouldn't be there, as you are right, there is no return value.

**Comment by gadgetto** [comment]
Perfect!
