### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1057]
When a field is deleted from a template, this is written in the messages.txt:

`Deleted field &quot;test&quot; data in 0 row(s) from 0 page(s) using template &quot;demo-upload&quot;. [page-by-page] (Fields)`

Originating in fields.php, line 709. It would be nice to have " or ' characters in logs.

Edit: its the _() function that encodes the string, so encoded characters appears in other log files too, like system-updater.txt (`Detected core version change 3.0.146 =&gt; 3.0.147`)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this.

**Comment by matjazpotocnik** [comment]
Thank you.
