### ISSUE TITLE
Login to developer directory not possible - not core related

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1058]
When I try to log in to https://directory.processwire.com/login/ to create/edit a profile, the login does not work and redirects me to https://login/.
Because of that we are not able to change our information.

Could you please make the login work again?
This was also mentioned here: https://processwire.com/talk/topic/22691-pw-developer-forum-login-button-is-broken/

**Comment by teppokoivula** [comment]
Possibly related: https://processwire.com/talk/topic/22782-help-joining-the-pw-developer-network/.
