### ISSUE TITLE
Typo in ProcessCommentsManager.module line 586

### ISSUE THREAD

**Issue by adamspruijt** [processwire/processwire-issues#106]
### Short description of the issue
**Line 586:**
`$buton->showInHeader();`
should be:
`$button->showInHeader();`
causes a fatal error.

**Comment by ryancramerdesign** [comment]
This one was already fixed earlier this week so I'll close this. But if you grab the latest dev branch it has the fix in there. Thanks.

**Comment by adamspruijt** [comment]
Ah, thanks, and sorry, tried searching for it, must've missed that.
