### ISSUE TITLE
Select options field: options won't save with custom user role

### ISSUE THREAD

**Issue by nurkka** [processwire/processwire-issues#1062]
### Short description of the issue

I'm maintaining a website where two different design agencies are working with fields and templates in the ProcessWire backend. I defined a custom user role for those agencies, with the permissions "field-admin" and "template-admin", but with no superuser-permissions.

When logging in as a user with that custom role and editing a "Select Options" field, changing and saving the selectable options in the "Details"-tab doesn't work. The options won't be saved and immediately change back to the previous values. 

### Expected behavior

The changes should be saved.

### Actual behavior

The changes aren't saved, because according to the sourcecode in SelectableOptionConfig.php, superusers are not allowed to save "Select Options"-field options.

### Screenshots/Links that demonstrate the issue

![grafik](https://user-images.githubusercontent.com/803637/72116641-3308cd00-334b-11ea-8f3d-e6b8c80de95f.png)

### Suggestion for a possible fix

Allow users with "field-admin" permission to save options.

In /wire/modules/Fieldtype/FieldtypeOptions/SelectableOptionConfig.php:

```
protected function process(Inputfield $inputfield) {
	// ...

	// original code:
	//  if($this->wire('process') != 'ProcessField' || !$this->wire('user')->isSuperuser()) return;

	// modified code:
	if($this->wire('process') != 'ProcessField' || ( !$this->wire('user')->isSuperuser() && !$this->wire('user')->hasPermission('field-admin'))) return;

	// ...
```

### Steps to reproduce the issue

1. Create a custom user role and add the permissions "field-admin" and "template-admin"
2. Login as a user of that custom role
3. Create a Select Options field and save it
4. Change the selectable options in the details tab and save it again

### Setup/Environment

* ProcessWire version: 3.0.148
* (Optional) PHP version: 7.3.x

**Comment by ryancramerdesign** [comment]
Thanks @nurkka I have pushed your suggested fix for this. Though I should mention that field-admin and template-admin are undocumented permissions that haven't been used before, as far as I know. When I build modules for superuser, I'll make up a permission setting just as a way to prevent automatic admin user access to it. Doing so ensures only superuser can access it, unless someone overrides that by creating the permission themselves, which I suppose is a good option to have for the rare occasion like this. 

These permissions in particular, they essentially make one a type of superuser. So I think it may be better just to make the users that need that access to be superusers, reducing the chances of a permission conflict like this. Though if you find they work how you expect otherwise, then it should also be fine, as they are simply module permissions.

**Comment by nurkka** [comment]
Thanks @ryancramerdesign for your quick response and pushing the fix!

**Comment by teppokoivula** [comment]
> Though I should mention that field-admin and template-admin are undocumented permissions that haven't been used before, as far as I know.

@ryancramerdesign, just wanted to mention that these two are definitely in use; I've come across discussion regarding them on the forums, and I've even personally ran into sites that used them. I get what you're saying here, but the way I see it there's still a huge gap between superusers and a "regular" user who can only edit fields and/or templates.

Anyway, it's not really that I think using these would be a great idea – just wanted to point out that even if they are indeed undocumented, some users are already relying on them :)

**Comment by ryancramerdesign** [comment]
@teppokoivula @nurkka Sounds like it's been used more than I realized. That's good to know, thanks. I'll get a closer look to see if I can spot any other situations where we might need to add an additional permission check like the one from this report. 

Like with the Modules part of the admin (also one for superuser-only), my concern with non-superusers in these tools is that they have a superuser level of power to manipulate things that affect the entire system. You can go in there and really break things for the whole site if you wanted to. So having roles other than superuser for these purposes feels suggestive of some layer of safety that isn't there. On the other hand, if you really only want them to edit fields or templates (understanding the superuser level of access to them), but not edit/install modules, then I suppose having a role with those extra field/template permissions is safer than a superuser.
