### ISSUE TITLE
admin_theme field rendering in profile

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1069]
When system field admin_theme has Input Type set as _Select_ (rather than default _Radios_) and Options label is set to _Title and summary_ the select field on the profile edit page looks odd:

This is the settings page:

![admin_theme_settings](https://user-images.githubusercontent.com/7663992/72867361-ef18af00-3cde-11ea-843f-2488a6d6cd9c.png)

And this is the profile page:

![admin_theme_profile](https://user-images.githubusercontent.com/7663992/72867375-02c41580-3cdf-11ea-83e7-9dc46f6d75fd.png)

I would simply remove those span elements in FieldtypeModule.module line 95.

Also, the settings for the "Blank value type" are not saved. This is missing in line 190:

`$f->attr('value', $field->blankType); `

**Comment by matjazpotocnik** [comment]
Blank value type issue is fixed: https://github.com/processwire/processwire/commit/32e031ab7da4c973184afdfd3756228733878875

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this issue

**Comment by matjazpotocnik** [comment]
Thanks.
