### ISSUE TITLE
After update to 3.0.43 site not working

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#107]
Today i updated from 3.0.42 master version to 3.0.43 dev version, website stopped working. When i check logs, i am getting this error :

2016-12-03 14:10:54	guest	http://domain.ltd/	Error: 	Call to a member function formatted() on null (line 1303 of /wire/core/Page.php)

I can't access admin side & front-end of website.

For the moment, i copied 3.0.42 files back and all working.

**Comment by adrianbj** [comment]
This should be fixed with this morning's commit: https://github.com/processwire/processwire/commit/423fbe6f5751e429cd3a89eb5290abceb7d382cf

**Comment by trk** [comment]
@adrianbj this commit fixed issue
