### ISSUE TITLE
string '0' evaluated incorrectly as false when using $page->get('field1|field2') but not $page->get('field1')

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1072]
Assume your page has a title of '0' and a headline of 'blah'.
```
echo $page->get('title'); // outputs 0; correct
echo $page->get('title|headline'); // outputs 'blah'; incorrect
```

PW 3.0.149

**Comment by ryancramerdesign** [comment]
@jlahijani The `this|that` syntax for the [WireData::get](https://processwire.com/api/ref/wire-data/get/) method (as used by Page) is intended to find the first "non-empty" value (per PHP's [empty](https://www.php.net/manual/en/function.empty.php) function), not the first non-null value. PHP considers both int 0 and string "0" to be empty values.

**Comment by jlahijani** [comment]
OK.  I'll close this.
