### ISSUE TITLE
Inconsistent folder name when deleting module

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1073]
When you delete a module and module contains directories, the path has mixed slashes:

Modules: Scanning: C:/inetpub/wwwroot/site/modules/MyModule/
Modules: Scanning: C:/inetpub/wwwroot/site/modules/MyModule\Assets

Possible fix: in Modules.php, line 2137, change
`$dirs[] = $file->getPathname();` to
`$dirs[] =$this->wire('files')->unixDirName($file->getPathname());`

**Comment by ryancramerdesign** [comment]
Does the slash variation prevent it from working? My understanding was that PHP could manage the mixed slash issue, but I don't have an installation using backslashes to confirm.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign it doesn't prevent it from working but it looks odd. This is just something that pops up while working on this issue https://github.com/processwire/processwire-issues/issues/1076

**Comment by ryancramerdesign** [comment]
Thanks matjazpotocnik I've pushed your suggested fix.
