### ISSUE TITLE
Error deleting module

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1076]
If a module directory in /site/modules has a folder (or folders) the module folder is not deleted.

I have the following structure (sample module):

```
C:/inetpub/wwwroot/site/modules/MyModule
C:/inetpub/wwwroot/site/modules/MyModule/MyModule.module
C:/inetpub/wwwroot/site/modules/MyModule/subfolder1
C:/inetpub/wwwroot/site/modules/MyModule/subfolder1/subfolder2
```

The module is not installed. I go to Setup->Modules->Site and there I click Delete button to delete MyModule from the disk. I get the error "Failed to remove directory: C:/inetpub/wwwroot/site/modules/MyModule" and "Failed to delete module MyModule". The error is coming from ProcessModule.module in ___delete() method. After some debugging, it turns out that this part of the code makes wireRmdir() to fail:

```
do {
  $dir = array_shift($dirs); 
  $this->message("Scanning: $dir", Notice::debug); 
  
  foreach(new \DirectoryIterator($dir) as $file) {
    if($file->isDot()) continue;
    if($file->isLink()) {
      $numLinks++;
      continue; 
    }
    if($file->isDir()) {
      $dirs[] = $file->getPathname();
      continue; 
    }
    if(in_array($file->getBasename(), $files)) continue; // skip known files
    if(strpos($file->getBasename(), '.module') && preg_match('{(\.module|\.module\.php)$}', $file->getBasename())) {
      // another module exists in this dir, so we don't want to delete that
      $numOtherModules++;
    }
    if(preg_match('{^(' . $basename . '\.[-_.a-zA-Z0-9]+)$}', $file->getBasename(), $matches)) {
      // keep track of potentially related files in case we have to delete them individually
      $files[] = $matches[1]; 
    }
  }
} while(count($dirs)); 
```
There is nothing wrong with this code but it looks like DirectoryIterator and/or some of its methods somehow lock the folder and rmdir() fails. This is certainly very odd, maybe some undocumented bug, maybe windows specific, I couldn't find any useful information on the web. I decided to get rid of DirectoryIterator and go with scandir. With success! So this is the code:

```
do {
  $dir = array_shift($dirs);
  $this->message("Scanning: $dir", Notice::debug);

  $d = array_diff(@scandir($dir), array('.', '..')); // array_diff removes . and ..
  foreach($d as $file) {
    $pathname = rtrim($dir, '/') . '/' . $file;

    if(is_link($pathname)) {
      $numLinks++;
      continue;
    }
    if(is_dir($pathname)) {
      $dirs[] = $pathname;
      continue;
    }
    if(in_array($file, $files)) continue; // skip known files
    if(strpos($file, '.module') && preg_match('{(\.module|\.module\.php)$}', $file)) {
      // another module exists in this dir, so we don't want to delete that
      $numOtherModules++;
    }
    if(preg_match('{^(' . $basename . '\.[-_.a-zA-Z0-9]+)$}', $file, $matches)) {
      // keep track of potentially related files in case we have to delete them individually
      $files[] = $matches[1];
    }

  }
} while(count($dirs));
```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik In many instances PW is not going to be able to delete module files due to /site/modules/ not being writable, as ideally no directories other than those in /site/assets/ would be writable. I made my site/modules/ writable, installed WireMailSmtp (which also has a subdirectory within it), then uninstalled, then clicked the Delete button. It was able to delete everything okay. Are you still observing this issue? Currently PW uses `$files->rmdir()` in recursive mode to remove module directories, but I'm not sure if it did when you originally posted this issue. Thanks.

**Comment by matjazpotocnik** [comment]
Yes, it's working now, thank you.
