### ISSUE TITLE
Unselecting page from PageListSelect Inputfield doesn't update visibility of field dependencies

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#108]
### Short description of the issue

If I have a field that has a showIf dependency set to: `pagelistselectfield.count=0` or `pagelistselectfield=''`, selecting a page correctly hides that field, but unselecting all pages doesn't restore the visibility of the other field.

### Expected behavior

The fields with showIf rule should show again when the page are unselected. Note that it works with a PageSelectListMultiple Inputfield

### Actual behavior

The field with the showIf dependency won't show again

**Comment by ryancramerdesign** [comment]
Adrian, since you are not dealing with a single value field (not a multi-value), there is no "count" – there is just a value. That value is a specific page ID, which is an integer. Meaning, the unselected value would be `0`, so your showIf dependency would need to be `pagelistselectfield=0`.

**Comment by adrianbj** [comment]
Apologies Ryan - I had tried that also, but it didn't work when using the unselect shortcut added by the AdminOnSteroids module. It does however work using the core unselect feature.

Just pinging @rolandtoth for his input on the issue with the AoS module.
