### ISSUE TITLE
Password mysteriously reset / corrupted / stops working

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1080]
### Short description of the issue

My company used ProcessWire extensively on our websites and web applications. We have found that on rare occasions the superuser or some other account's password will stop working. It can be quite disconcerting, especially when it is the superuser's password. We are able to reset it via the API, but of course it makes us wonder whether we've been hacked. However, we've never found any evidence of a hack or malicious manipulation of data following these cases.

### Steps to reproduce the issue

I cannot provide steps to reproduce this issue since it is so rare and I have no idea what causes it, but I wanted to bring it up in case others have also experienced the issue, so perhaps we can figure it out together.

### Setup/Environment

* ProcessWire version: Last observed on 3.0.141
* PHP version: 7

**Comment by adrianbj** [comment]
Strangely, this happened to me yesterday. It was not a superuser account. 

My assumption was that browser autocomplete had changed the password while I was editing something else in the profile. Any chance it could be that in your case also?

**Comment by thetuningspoon** [comment]
Anything is possible, but autocomplete doesn't usually touch password fields, and the password field requires confirmation to change it, doesn't it?

**Comment by netcarver** [comment]
I have experienced the case where autofill has populated the password field "behind my back" as it were, when editing user pages in PW. It's been a while - but IIRC it was the fill feature on Lastpass that did it.

**Comment by adrianbj** [comment]
For me it's not even Lastpass.

Preventing browsers from autocompleting has become a total PITA. I went through this recently and it's almost impossible. I did finally come up with a solution, but I'll have to dig it up later.

**Comment by thetuningspoon** [comment]
Can either of you reproduce the autofill issue?

**Comment by thetuningspoon** [comment]
This just happened to me again. Neither I or the other developer working on the project made any changes in the user profile or to the user page, so it wasn't autofill related. This morning the password simply stopped working and we had to reset it from the API. This was the superuser, so our customer couldn't have reset it either. Very strange.

**Comment by thetuningspoon** [comment]
Good news this time. The issue was on our end with our custom sign-up form. This may also explain at least one of the prior instances of this occurring. I'm going to close this for now.
