### ISSUE TITLE
Problems due to hardcoded HTTP URL for modules directory in wire/config.php

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1083]
Hey @ryancramerdesign! It appears that $config->moduleServiceUrl in wire/config.php is causing some issues right now due to HTTP requests getting redirected to HTTPS:

```
$config->moduleServiceURL = 'http://modules.processwire.com/export-json/';
```

More details here: https://processwire.com/talk/topic/23067-error-retrieving-modules-directory-data-processwireupgradecheck/.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've updated the config.php file to use the https URL. The forced https on the modules site was not intended either. We added a node to the load balancer and there was a rule forcing https already in place, so that is also turned off now.

**Comment by teppokoivula** [comment]
Thanks Ryan — though I might add that forcing HTTPS seemed like a good idea in itself due to security, SEO, and probably few other usual suspects. But anyway, glad that this is sorted now :)
