### ISSUE TITLE
MarkupAdminDataTable.module: Associative arrays are not getting converted to anchor when the key is numeric

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#1084]
### Short description of the issue

Associative arrays are not getting converted to anchor when the key is numeric.

```php
$table->row(array(
	'404' => './view/404/'
));

```

### Screenshots/Links that demonstrate the issue

![logs](https://user-images.githubusercontent.com/17672049/73990407-4f4b5a00-4949-11ea-900d-f22d9dbbf4bf.png)

### Suggestion for a possible fix

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/modules/Markup/MarkupAdminDataTable/MarkupAdminDataTable.module#L192

```php
foreach($a as $k => $v) {
	if(is_string($k)) {
		// Associative arrays get converted to: 
		// Anchor Text => URL
		$v = "<a href='$v'>" . $this->encode($k) . "</a>";
	} else if(is_array($v)) {

```

Using `is_string()` on a array key is not reliable because:

> Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key "8" will actually be stored under 8.

https://www.php.net/manual/en/language.types.array.php

As a workaround we can prepend a space character before the key:

```php
$table->row(array(
	' 404' => './view/404/'
));

```

So here is a fix for **ProcessLogger.module**, which suffer from this issue (as seen in the screenshot above):

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/modules/Process/ProcessLogger/ProcessLogger.module#L82

Change `$log['name'] => "./view/$log[name]/",` to `" $log[name]" => "./view/$log[name]/",`

Or can this be fixed in the **MarkupAdminDataTable.module**?

### Setup/Environment

* ProcessWire version: 3.0.149 dev

**Comment by ryancramerdesign** [comment]
@fijha Thanks, I've pushed your suggested fix for this.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign fix doesn't work for me. 

```
$table->row(array(
        //other items
	'404' => './view/404/'
));
```

looks like this:

![image](https://github.com/processwire/processwire-issues/assets/7663992/2932f3c5-f392-45bf-a158-c569a091e8ff)

while this (added a space in front of 404):

```
$table->row(array(
        //other items
	' 404' => './view/404/'
));
```

looks like expected:

![image](https://github.com/processwire/processwire-issues/assets/7663992/3c3057cf-8993-49ba-b915-d613c7aef030)

**Comment by matjazpotocnik** [comment]
![image](https://github.com/processwire/processwire-issues/assets/7663992/4c121dfa-ea92-4a79-806a-3d26bfb77690)

> Strings containing valid integers will be cast to the integer type. E.g. the key "8" will actually be stored as integer 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.

So, it's up to the developer to be aware of this odd (IMHO) behaviour and add a blank string at the beginning of the key (or perhaps a null character `"\0"` at the end).
