### ISSUE TITLE
PHP Notice: Undefined property: ProcessWire\Pageimage::$original in /var/www/html/wire/core/PageimageVariations.php:256

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1086]
### Short description of the issue

Received that error from this URL:
/page/image/resize?id=5495&file=testimage.1101x1100-cropx386y12-is.jpg&width=200&height=200&hidpi=0

**Comment by matjazpotocnik** [comment]
I got this one on live site today. I'm still gathering data, but it looks like the image name with dimensions is a problem.

```
Page: https://mysite/myadmin/page/image/resize
User: myuser

Fatal Error: 
Uncaught Error: Cannot access protected property ProcessWire\Pageimage::$original in D:\mysite\wire\core\PageimageVariations.php:256
Stack trace:
#0 D:\mysite\wire\core\Pageimage.php(1327): ProcessWire\PageimageVariations->getInfo('stamina.157x162...', Array)
#1 D:\mysite\wire\core\Wire.php(386): ProcessWire\Pageimage->___isVariation('stamina.157x162...', true)
#2 D:\mysite\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___isVariation', Array)
#3 D:\mysite\wire\core\Wire.php(450): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Pageimage), 'isVariation', Array)
#4 D:\mysite\wire\core\Pageimage.php(1369): ProcessWire\Wire->__call('isVariation', Array)
#5 D:\mysite\wire\core\Pageimage.php(399): ProcessWire\Pageimage->getOriginal()
#6 D:\mysite\wire\core\WireData.php(333): ProcessWire\Pageimage->get('original')
#7 D:\mysite\wire\core\PageimageVariations.php(256): ProcessWire\WireData->__get('original')
#8 D:\mysite\wire\core\Pageimage.php(1327): ProcessWir (line 256 of D:\mysite\wire\core\PageimageVariations.php)  
```

**Comment by matjazpotocnik** [comment]
Hmm, I can't replicate. I have the original image, uploaded/resized/inserted into CKE textarea several times, no errors...

**Comment by adrianbj** [comment]
I haven't tried to reproduce this myself - it's happening while one of my site editors is resizing images.

**Comment by matjazpotocnik** [comment]
Yes, it happens during resize. I review the history and found this:
https://github.com/processwire/processwire/commit/c2ee22b3348fbc69f0233d27bbdb30bb1f7ddaff#diff-9620c754e535bb740fe4be6b9672bec4
https://github.com/processwire/processwire/commit/0e9cc868b76890c5272128f9a0491abba98ea625#diff-2dac6cae1c0a13a65e1ebe10ea3fd946
Not sure if it's relevant.

**Comment by adrianbj** [comment]
I just had another one of these today.

**Comment by Toutouwai** [comment]
These steps reliably reproduce the issue for me:

1. Click "Image" button in CKEditor toolbar.
2. Click an image.
3. Click crop icon.
4. Apply crop.
5. Click "Insert Image".

**Comment by adrianbj** [comment]
@ryancramerdesign - that commit seems to have fixed things for me - thanks.
