### ISSUE TITLE
 Parent pages with thousands of children timeout

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1087]
### Short description of the issue

Parent pages with thousands of children do not open for editing in backend here. They timeout with Error 500. I remember from another site that in the past that I could open such a parent there.  So the problem is either new or specific for my site.

Anyone else is having that too?

### Expected behavior

The work the same as pages without many parents.

### Actual behavior

Parents, which I could open before, do not open for edit any more. The admin pages tree works as normal and the frontend of the parents also work normal.

### Steps to reproduce the issue

I had imported 5000 - 30000 entries to various parents via the "Import Pages with CSV" module. (I saw a error 500 after a while but the pages finished importing nonetheless after an hour - different subject, just in case that matters, not my point here.)

The children are just title and a few text fields. 

### Setup/Environment

The site is set multilingual
Localhost / MAMP / Mac - PHP timeout set to 3 min but page timeout is earlier.
PHP 7.3
MySQL 5.7
ProcessWire 3.0.150 dev

**Comment by BernhardBaumrock** [comment]
I think this one would be better to ask in the forum than reporting an issue. PW is built to handle millions of pages without problems, so it is 99% something else causing this problem (3rd party module or custom code).

1st thing to do would be to import the same set of pages on a fresh installation of PW and see if it works there...

**Comment by tbba** [comment]
This IS a fresh installation - I.m.h.o. the issue belongs here if that problem is shared by others, otherwise not, I agree. I plan to wait another day for responses before I close this eventually.

**Comment by BernhardBaumrock** [comment]
> This IS a fresh installation

Sorry, didn't know that, but

> ..."Import Pages with CSV" module

...at least this statement tells me that it is not a fresh installation ;)

Maybe you can disable all modules in the site folder by moving them temporarily to another place and see if that makes a difference...

**Comment by adrianbj** [comment]
@tbba - any chance you have BatchChildEditor installed? If so, that is likely the problem. It doesn't handle that many child pages well at all if it's by default in edit mode. Other modes will be ok, and if you have lots of children, it should be set to open via AJAX only, but with this many, it will likely always be a problem. I really need to do something about this, but not a priority for me the moment I'm afraid.

**Comment by tbba** [comment]
@BernhardBaumrock - in this respect you are right. the installation is fresh, but I was evaluating BCE, Import Pages with CSV to get all that stuff in. I go the module testing route now, since I now that the core CAN still handle that amount of files... Thanks @adrianbj for pointing me to that direction. - I agree to close this now.
