### ISSUE TITLE
Update jquery-ui-timepicker-addon to the latest version

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#1088]
### Short description of the issue

There is some issue with 'Now' button. When I click it for the first time it sets right current time and date. Then if I change the time manually by and again click 'Now' it sets some random time and date. 
There is a GIF that demonstrates the issue

https://bit.ly/2Hbf35V

I have manually updated jQuery Timepicker Addon to v1.6.3 and it seems that this issue has been fixed. 

Thanks.

**Comment by matjazpotocnik** [comment]
@Lazerproof jQuery Timepicker is now at v1.6.4. Can you check if it fixes this issue?

**Comment by matjazpotocnik** [comment]
@Lazerproof I'm closing this, please reopen if needed.
