### ISSUE TITLE
Reset image variations after action has been executed

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1089]
### Short description of the issue

I have an image field that stores some images for a gallery on that page. The gallery has thumbnails and a large image in a lightbox when you click on them. Today I had to rotate one image 90° which worked well, but when I clicked on the image the large image was still 90° wrong (not recreated).

### Expected behavior

All image variations should be recreated when any action was executed.

### Actual behavior

![img](https://i.imgur.com/Ptsl8Ha.png)

### Setup/Environment

* ProcessWire version: 3.0.149

PS: The margin at the top of the variations modal could also be improved (it's too much spacing).

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock, is this issue similar (or duplicate?)  to https://github.com/processwire/processwire-issues/issues/1301 ?

**Comment by netcarver** [comment]
I'm going to assume it is and close it. @BernhardBaumrock please comment here again if I'm wrong and I'll re-open.
