### ISSUE TITLE
WireHttp::download: multiple issues…

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#1090]
## 1. Short description of the issue

`WireHttp::download` uses 3 methods to download a file. When one method fails, it tries another, but the problem is (in my case), when `curl` method fails, because of `$options['timeout']`, a partially downloaded file is not deleted and the second method (`fopen`) will continue to write to an existing file.

### Expected behavior

When one of the methods fail, it should delete partially downloaded file before trying another method. Or maybe throw an exception if timeout?

### Actual behavior

Downloaded file is bigger than original or corrupted if `curl` fails and `fopen` continues.

### Suggestion for a possible fix

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/WireHttp.php#L829

Use `unlink()` or delete file content before trying another method. Or maybe would be better to throw an exception if timeout, because another method will probably also fail (timeout).

## 2. Short description of the issue

`WireHttp::downloadFopen` method is using `file_get_contents()` istead of `fopen()`, which can cause memory issues.

### Suggestion for a possible fix

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/WireHttp.php#L936

```php
// download the file
set_error_handler(array($this, '_errorHandler'));

$fremote = @fopen($fromURL, 'rb', false, $context);

if($fremote === false) {
	$result = false;
} else {
	$length = 1 * 1024 * 1024;

	while(!feof($fremote)) {
		$buffer = fread($fremote, $length);
		fwrite($fp, $buffer);
	}
	fclose($fremote);

	$result = true; 
}

restore_error_handler();

return $result; 

```

## 3. Short description of the issue

I'm using `$page->files->add('http://domain.com/large-file');` to add/download remote files to the page, but I'm experiencing issues as described above, because of`$options['timeout']` in `WireHttp`, when `curl` method is in use, when downloading large files.

### Suggestion for a possible fix

Would be possible to specify timeout or method when adding files to the page, to be able to download larger files? Something like:

`$page->files->add('http://domain.com/large-file', ['timeout' => 300, 'use' => 'fopen']);`

### Setup/Environment

* ProcessWire version: 3.0.150 dev

**Comment by ryancramerdesign** [comment]
@fijha Thanks, good suggestions, I've pushed the updates for issues 1 and 2 that you mentioned. For issue 3, here's how you can set the timeout and use options. This should come right before your $page->files->add():

~~~~~
$wire->addHookBefore('WireHttp::download', function(HookEvent $event) {
  $options = $event->arguments('options'); /** @var array $options */
  $options['timeout'] = 300;
  $options['use'] = 'fopen';
  $event->arguments('options', $options);
}); 
~~~~~
or if you prefer something less verbose:
~~~~~
$wire->addHookBefore('WireHttp::download', function($e) {
  $o = $e->arguments(2);
  $e->arguments(2, array_merge($o, ['timeout' => 300, 'use' => 'fopen']));
}); 
~~~~~

@matjazpotocnik Thanks for bumping this, somehow I missed this one before.

**Comment by matjazpotocnik** [comment]
@fijha, do you find Ryan's fix resolves the issue?

**Comment by matjazpotocnik** [comment]
Closing on the assumption this is fixed. @fijha, please comment here again if that is not the case.
