### ISSUE TITLE
Sanitizer::url() returns unexpected results if scheme is tel

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1091]
### Short description of the issue

```
$tel = $this->wire('sanitizer')->url('tel:+49 78 90');
var_dump($tel); 
// current result: string(15) "tel:24520782090" 
// expected result: string(11) "tel:+497890" 
```

### Expected behavior

result: **"tel:+497890"**

### Actual behavior

result: **"tel:24520782090"** 

### Optional: Suggestion for a possible fix

<del>Do not apply **filter_var()** before scheme: `tel` is detected.</del>
*See my comment below*

### Setup/Environment

* ProcessWire version: 3.0.148

**Comment by teppokoivula** [comment]
Not filtering seems potentially problematic, but it looks like FILTER_SANITIZE_NUMBER_INT is a common suggestion to tel links. Perhaps that should be used instead if a phone number is detected?

~Just my five cents, but when an "atypical" URL scheme is detected, such as tel, Sanitizer::url() should probably pass it to separate method that specializes in that — in this case it could mean Sanitizer::urlTel() or something along those lines. Requirements for tel links, for an example, are quite different from http(s) URLs after all :)~

**Edit**: a variation of what I suggested above is already happening, so this comment is largely irrelevant.

**Comment by kixe** [comment]
@teppokoivula 
Its not `filter_var()`, its the `rawurlencode()` in line 1654 which prevents `str_replace() `in line 1712 doing its job.

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/Sanitizer.php#L1654

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/Sanitizer.php#L1712

Currently the function is built to handle any scheme. No passion for a specific solution. It should just work :)

**Comment by teppokoivula** [comment]
Right, looks like I didn't read far enough... :)

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue

**Comment by kixe** [comment]
thanks. closed.
