### ISSUE TITLE
$sanitizer->pageName ignores settings of InputfieldPageName

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1096]
### Short description of the issue

In german it is very common to have umlauts (ö ä ü) in page titles and also page names. InputfieldPageName has a textarea to define replacements for such characters, which is great!

![img](https://i.imgur.com/I9s7CVF.png)

I wonder why $sanitizer->pageName() does not take these replacements into account when sanitizing pageNames. Or at least I think there should be an option that it does.

I've created a QuickFix for this issue: https://github.com/BernhardBaumrock/PwQuickFixes/commit/c731431d4a2d08de37f241dab53e430f0652990c#diff-f755353699615a25aecef7d904919092

### Expected behavior

![img](https://i.imgur.com/IrF6em4.png)

I'd expect the pagename to be sanitzied like shown in the second dump/line.

### Actual behavior

Currently when someone saves the page manually the replacements are correctly applied. But when renaming the page via the API page names get generated differently!

### Steps to reproduce the issue

1. Setup replacements in InputfieldPageName like shown in the screenshot ( ö => oe )
2. Save a page with name Österreich (=Austria)
3. Page name will be oesterreich
4. Try $sanitizer->pageName("Österreich");

PS: Uppercase umlauts are also a little special! strtolower("Österreich") will result in "Österreich" depending on the locale, whereas mb_strtolower("Österreich") seems to work (at least for this case).

Thx in advance!

**Comment by adrianbj** [comment]
@BernhardBaumrock - I know it's not what you are looking for, but remember there is also:
![image](https://user-images.githubusercontent.com/871211/75119260-fdd3e800-5635-11ea-9431-26f51f993176.png)

which at least doesn't remove those characters completely.

**Comment by BernhardBaumrock** [comment]
It is exactly what I want, thx @adrianbj :D But at least I worked a little on the PwFixes module :)

**Comment by adrianbj** [comment]
Oh, I assumed you wanted the `ä` replaced with `ae` rather than just `a`

**Comment by adrianbj** [comment]
You might also find this module useful for other similar tasks:
http://modules.processwire.com/modules/sanitizer-transliterate/

**Comment by BernhardBaumrock** [comment]
> Oh, I assumed you wanted the `ä` replaced with `ae` rather than just `a`

Yeah, that's what it does here. You have to define those replacements in InputfieldPageName config!

![img](https://i.imgur.com/9GKCRHc.png)

**Comment by BernhardBaumrock** [comment]
![img](https://i.imgur.com/ijSsCt5.png)

Exactly what I was looking for - Thx :)

**Comment by adrianbj** [comment]
> You have to define those replacements in InputfieldPageName config!

Right, I assumed those were in that config by default - sorry, I should have checked.

All that said, I have always thought that `pageName()` should translate by default with maybe an option not to? I think you used to have to use `Sanitizer::translate` as an option for `pageName`. I think the `pageNameTranslate` is a relatively new addition.

https://processwire.com/api/ref/sanitizer/page-name/

**Comment by BernhardBaumrock** [comment]
Thx again. I've read the docs for pageName() - not good enough as I see now:

> 

beautify (optional) | bool, int, array | [...] Sanitizer::translate (constant): This will make it translate non-ASCII letters based on InputfieldPageName module config settings.
-- | -- | --

**Comment by adrianbj** [comment]
Don't forget the usefulness of `testAll()` - it's not perfect in that it doesn't allow testing optional arguments, but still worth a first check:

![image](https://user-images.githubusercontent.com/871211/75120363-121ce280-5640-11ea-9c08-e891ae2a13ce.png)

**Comment by BernhardBaumrock** [comment]
Yeah, I know about testAll(), thx - and I know that it does not list all methods, so I thought it would be better to go to the API docs... Wrong decision :D
