### ISSUE TITLE
PWLink plugin causes loss of italic/bold styling

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1098]
### Short description of the issue

If the text selected for a link has italic or bold styling, this is lost after adding a link via the PWLink CKEditor plugin.

This issue does not occur with the standard CKEditor link plugin.

Screencast:
![link](https://user-images.githubusercontent.com/1538852/75207483-bb4d0f80-57dd-11ea-9e08-8fd79acaf073.gif)

### Setup/Environment

* ProcessWire version: 3.0.151

**Comment by jacmaes** [comment]
I’m bumping into this bug all the time when I try to link an italicized book or movie title. Thanks for opening this issue!

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks I have pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign.

The CKEditor link plugin is still a bit better at handling formatting that the PWLink plugin - it can handle scenarios where the link text contains a mixture of bold, italic and plain text. Rather than construct a new link element like PWLink it applies a link "style" to ranges within the selected text: https://github.com/ckeditor/ckeditor4/blob/7c439953d7239985cee28213a17cf1014f0c06b7/plugins/link/dialogs/link.js#L69

I think PWLink could potentially follow the link plugin example and thereby support adding links to more kinds of selections but this would be a bigger job.

**Comment by ryancramerdesign** [comment]
@Toutouwai Interesting to look at, thanks — yes they are doing it in a completely different way, I don't completely understand it yet. When you say it's a bit better a handling formatting, can you clarify? I tested every case I could think of using and all seemed to work with this update, but it would be good for me to know if there are any common use cases that still need attention.

**Comment by Toutouwai** [comment]
The case that fails with the PWLink plugin is where you want to add a link to text that contains some formatting but not all of the text has that formatting, e.g. "wreck of *Titantic*".

![link](https://user-images.githubusercontent.com/1538852/127753547-979e8949-83f0-4c6c-b084-2fb5f01b7ca7.gif)

And it's not a big problem but even if you make a link from text that has the same formatting throughout (e.g. only the word *Titanic*) the PWLink plugin puts the `<a>` tags inside the `<em>` tags whereas I think it would more standard for this to be the other way around. Compare a link from PWLink above and from the CKEditor link plugin below:

![2021-08-01_101044](https://user-images.githubusercontent.com/1538852/127753600-525f42d3-6c96-420d-8f4d-745642a41dcd.png)

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks for the example. I've added a couple more updates to cover that case and similar ones. As for order of `<a>` and `<em>` I think this is just a matter of style and one isn't more correct than the other (?), as far as I know. Though I know back when we all used XHTML 1.0 the order of `<a>` tags was important when it came to block-level elements, like `<a><h1>` was bad, whereas `<h1><a>` was good, but that was a long time ago. I don't prefer one style over the other, I just prefer whatever I can get CKEditor to accept through the plugin.

**Comment by Toutouwai** [comment]
Thanks, that's working great.

**Comment by matjazpotocnik** [comment]
Just to mention that `<a href='...'><button></button></a>` used in InputfieldButton.module when used with href property is also bad practice. It's not valid HTML and it has accessibility issue since button get double focus when tabbing.
