### ISSUE TITLE
Drag and drop replacement of image clears custom field values

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1099]
### Short description of the issue

When using the new [custom fields for images](https://processwire.com/blog/posts/pw-3.0.142/) feature, if a replacement image is dropped onto the thumbnail while the image is in edit mode then the custom field values are lost.

By drag and drop replacement I'm referring to the feature described [here](https://processwire.com/blog/posts/major-images-field-upgrade/):

> Replace an image by dropping a new one on top of it
>
>When the "edit" panel is open, you have a larger preview of the image. You can replace that image simply by dragging a new image from your computer right on top of that preview image. It doesn't get any simpler than that!

### Setup/Environment

* ProcessWire version: 3.0.151

**Comment by matjazpotocnik** [comment]
@Toutouwai is this still an issue? I can't replicate...

**Comment by Toutouwai** [comment]
Thanks @matjazpotocnik, it seems to be working now so I guess it got fixed at some point.
