### ISSUE TITLE
Pressing enter in home page name field opens image edit modal

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#11]
When having LanguageSupport installed plus the LanguagePageNames module, there's page name field also on "home" page. When editing one of the page name field and hitting enter, the image modal opens.

* ProcessWire version: 3.0.33

**Comment by gingebaker** [comment]
Stumbled over the same issue here (3.0.33 and 3.0.30). It happens on ProcessPageEdit Screens whenever I press Enter on a Textfield. (for example the standard Title field).
The edited Page has to have one or more ImageFields. Language Support is also enabled.

**Comment by isellsoap** [comment]
I can reproduce this issue on a fresh 3.0.34 installation. What a weird bug!

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix. The issue was that the Crop button (in InputfieldImage) lacked a `type="button"` attribute. If that's not present, the browser will attempt to use it as a form submit button.

**Comment by somatonic** [comment]
Thanks for the fix. Glad you found the issue, that's a common known problem.
