### ISSUE TITLE
Wrong permissions for compiled files and directories

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#110]
### Short description of the issue

When FileCompiler.php compiles a file, the permissions on the compiled file/directory at /site/assets/cache/FileCompiler/... are not correct. It's 0644 and not what is set in /site/config.php with $config->chmodDir and $config->chmodFile

### Expected behavior

Correct permissions, as set in /site/config.php

### Actual behavior

Wrong permissions, always 0644/0755.

### Optional: Suggestion for a possible fix

Add
```
$config->fileCompilerOptions = array(
    'chmodFile' => $config->chmodFile,
    'chmodDir' => $config->chmodDir,
);
```
in /install.php after line 716.

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7.0
* (Optional) Any 3rd party modules that are installed and could be related to the issue: none

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this one to the dev branch.
