### ISSUE TITLE
Repeater (Matrix) +  Multi-Language > Language Tab and visible Inputfield miss-match

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#1100]
### Requirements:

- Repeater (matrix & normal) with mutlilanguage fields (text, textarea…) 
- Backend language set to something other than default (ie. German) 

### Reproduce:

- Add a new repeater Item (ajax, I found no way to possible to disable it with matrix)

(Notice how the default language tab is active instead of the backend language…)

- Write something into the (default language) field
- Try to save, if field is required, this will not work. If not required, then when reloading, the content will be inside the backend language field, instead of the default language field who was (presumably) active

### Analysis:

When  loading  a new repeater element with ajax, the default langue tab is active, but the backend language inputfield is visible (with no visual indication). When writing into the field, it will populate the backend language. When manually clicking on the default language tab (which is already active), the field will switch to the actual default language field (which is [now] empty) (that can now be populated…)

Also Notice, the labels of the elements to be added are in default language as well instead of the translated label (images instead of Bilder)…

ProcessWire 3.0.148, Profields 0.0.5…

This is a screen recording of the bug:
https://s3.us-west-2.amazonaws.com/processwire-forums/monthly_2020_02/409845907_ScreenRecording2020-02-25at14_18_31.mov.e6c0812415546857cd2f28ae6307576b.mov

**Comment by matjazpotocnik** [comment]
@noelboss is this still an issue? Can you reproduce it on the latest dev version?

**Comment by matjazpotocnik** [comment]
@noelboss Closing, let me know if it needs re-opening.
