### ISSUE TITLE
update Lazy cron documentation

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1103]
On the page https://processwire.com/docs/more/lazy-cron/ under section "How to make it not-lazy" the wget example should be corrected so that there are two dashes in front of the options:
`wget --quiet --no-cache -O - http://www.your-site.com > /dev/null`

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch I've edited that page and changed it to what you suggest.
