### ISSUE TITLE
Image Custom Fields Broken/Error

### ISSUE THREAD

**Issue by outflux3** [processwire/processwire-issues#1104]
### Short description of the issue

Page editor crashes when using file/field custom fields.

### Expected behavior

Page won't crash

### Actual behavior

Crash/Error

### Optional: Screenshots/Links that demonstrate the issue

![ProcessWire_PageFinderSyntaxException__Field_does_not_exist__author_images_db6743af9d8d5b173db10daf57b726dc_-_Mozilla_Firefox](https://user-images.githubusercontent.com/1743040/75468976-215fa100-595c-11ea-89e7-5a03bb523785.jpg)

### Optional: Suggestion for a possible fix

Not sure, haven't looked at the PageFinder.php

### Steps to reproduce the issue

1. Create template, field-images
2. Add text field to template
3. Load page with images field.

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.148|
|PHP|7.1.33|
|Webserver|Apache|
|MySQL|5.6.45|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|240 (changeable)|
|max_input_nesting_level|64|
|max_input_time|240|
|max_input_vars|1000|
|memory_limit|512M|
|post_max_size|30M|
|upload_max_filesize|30M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.7.8|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminCustomFiles|0.9.62|
|AdminOnSteroids|2.0.20|
|AdminPageFieldEditLinks|3.1.2|
|AdminTemplateColumns|1.0.1|
|AutoSmush|1.1.6|
|BatchChildEditor|1.8.19|
|ContextHelpLister|1.0.0|
|ContextHelpTemplate|1.0.0|
|CookieManagementBanner|0.4.11|
|CustomInputfieldDependencies|0.1.9|
|FieldDescriptionsExtended|1.0.9|
|FieldtypeAdminComments|1.0.7|
|FieldtypeColor|1.0.9|
|FieldtypeConfigForm|1.0.0|
|FieldtypeFontIconPicker|1.0.0|
|FieldtypeMultiplier|0.1.1|
|FieldtypeRuntimeMarkup|0.0.4|
|FieldtypeSecureFile|1.0.3|
|FieldtypeTable|0.1.9|
|FieldtypeTemplates|1.0.0|
|FontAwesomePro|1.0.4|
|FormBuilder|0.3.4|
|ImportExternalImages|2.0.8|
|InlineCompleteAction|0.1.4|
|InlineCompleteActionEvents|0.1.4|
|InlineCompleteActionMedia|0.1.4|
|InlineCompleteActionWorks|0.1.4|
|InputfieldAceExtended|1.1.3|
|InputfieldAdminComments|1.0.7|
|InputfieldCheckboxesExtended|0.0.1|
|InputfieldChosenSelect|1.2.5|
|InputfieldChosenSelectMultiple|1.2.2|
|InputfieldColor|1.0.9|
|InputfieldConfigForm|1.0.0|
|InputfieldFontIconPicker|1.0.0|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldIcon|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldRuntimeMarkup|0.0.4|
|InputfieldSelectExtended|0.0.1|
|InputfieldSelectExtendedMultiple|0.0.1|
|InputfieldSelectize|1.2.0|
|InputfieldSelectizeAjax|1.2.0|
|InputfieldSelectizeMultiple|1.2.0|
|InputfieldSimpleMDE|1.0.7|
|InputfieldTable|0.1.9|
|InputfieldVisualPageSelector|0.0.6|
|JqueryIonRangeSlider|0.0.4|
|JquerySwitchButton|0.0.4|
|MarkupFontIconPicker|1.0.0|
|MarkupSimpleNavigation|1.3.6|
|MarkupSiteMetaAdvanced|1.8.0|
|MarkupSocialShareButtons|1.0.5|
|MarkupThemeEngine|1.6.2|
|PageActionExportCSV|0.0.2|
|PageActionMove|0.0.1|
|PageActionSetField|0.0.1|
|PageActionSetStatus|0.0.1|
|PageEditSoftLock|1.0.1|
|PageFieldInfo|0.1.2|
|PageSnapshot|1.1.21|
|PageTableExtraActions|0.1.1|
|Pages2Pdf|1.1.7|
|PrevNextTabs|0.1.5|
|ProCache|3.1.8|
|ProcessAdminComments|1.0.7|
|ProcessCKInlineComplete|0.1.8|
|ProcessChangelog|1.7.1|
|ProcessChangelogHooks|1.4.1|
|ProcessChildrenCsvExport|1.8.18|
|ProcessCustomMarkup|1.0.0|
|ProcessDashboards|1.0.0|
|ProcessDatabaseBackups|0.0.5|
|ProcessDocumentation|1.0.4|
|ProcessFormBuilder|0.3.4|
|ProcessGetVideoThumbs|1.1.4|
|ProcessHannaCode|0.2.0|
|ProcessPageEditSoftLock|1.0.1|
|ProcessPageListerPro|1.1.3|
|ProcessProCache|3.1.8|
|ProcessSettingsFactory|1.0.5|
|ProcessTracyAdminer|1.0.6|
|ProcessVersionControl|1.3.0|
|ProcessVisualPageSelector|0.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|RestrictTabView|1.1.3|
|SelectizeTemplateFieldTags|0.0.8|
|SettingsFactory|1.0.5|
|SimpleBlogEngine|1.9.0|
|SiteUtilities|0.0.1|
|TemplatesChildPages|0.1.8|
|TextInputAwesomplete|0.0.5|
|TextformatterBBCodeMini|1.0.0|
|TextformatterHannaCode|0.2.0|
|TextformatterJqueryUITabs|0.0.1|
|TextformatterMarkupCSS|0.0.1|
|TextformatterSoundmanager|1.1.0|
|TextformatterTagParser|2.2.0|
|TextformatterUtilities|1.0.0|
|TracyDebugger|4.20.11|
|VersionControl|1.3.0|
|WireMailSmtp|0.4.2|
|WirePDF|1.0.4|
</details>

**Comment by outflux3** [comment]
I have been able to narrow this problem down to a module of mine, TextInputAwesomplete. 

The issue was that the module allows users to configure certain fields to use the auto complete. 

In order for this to work, there is a $pages->find in the module. 

Somehow the virtual field that is created for the custom fields on images cause the PageFinder to crash. 

So for example, if i have a title field and that is also used on an image, then the title field ends up being part of the array of fields enabled for auto complete. Then the Pagefinder crashes when running a query on this system defined field (e.g. Field does not exist: title_images2_3edfc3f340120243dffd62e857fc6f91) .

My fix for this in the module is to add:

```
                $fieldExists = $this->wire('fields')->get("name=$field");
                if(!$fieldExists) return;
```

which fixes the problem. But i do wonder if the core shouldn't have some built in test to exclude the system named fields.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, any thoughts on what Marc describes? Is it the developer's responsibility to check for "unexisting" fields?

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @outflux3 I'm not sure I fully understand, but I do know that PageFinder will throw an Exception if you try to find a field that doesn't exist. If it can't locate a field, first it will pass the field to the hookable getQueryUnknownField() (in case you want to substitute something or process it yourself) but if that returns false then it'll throw the Exception. I think that's the right behavior, otherwise typos on field names would be silently ignored, result in big bugs that are hard to find.

**Comment by outflux3** [comment]
Could there be a way for the page finder to take into account those fields that are being defined by the system, like those attached to image fields (as described above)?

**Comment by Toutouwai** [comment]
@outflux3, I think the key thing here is the distinction between inputfields and fields. Inputfields can be used independently of fields and there is no guarantee that any given inputfield is associated with a field.

In your module you are [hooking](https://github.com/outflux3/TextInputAwesomplete/blob/a839f73a5d56e8fcfdfd6d2f7a39c6c602e46fd8/TextInputAwesomplete.module#L85) `InputfieldText::renderReadyHook` and then in the method you get the event object (InputfieldText) as `$that` and then use the [inputfield name](https://github.com/outflux3/TextInputAwesomplete/blob/a839f73a5d56e8fcfdfd6d2f7a39c6c602e46fd8/TextInputAwesomplete.module#L225) as a field name in the $pages->find() selector.

But in repeaters, custom file/images fields, and anywhere else that InputfieldText might be used independently of a PW field, there won't necessarily be a field name that matches the inputfield name.

To get the Field object that is associated with an Inputfield object you can use `$inputfield->hasField`, and this will be null if there isn't an associated Field object.

So in the method you could do this:
```php
$field = $that->textField ? : $that->hasField;
if(!$field) return;
```

**Comment by outflux3** [comment]
Thanks Robin - i will make that correction - much appreciated also your explanation!

**Comment by matjazpotocnik** [comment]
@outflux3, can this be closed?

**Comment by outflux3** [comment]
Yes, @matjazpotocnik - i'm updating my mentioned module and this is not an issue any more. I will close it.
