### ISSUE TITLE
PHP Warning: class_parents(): Class ProcessWire\2020-03-03 09:46:43 does not exist and could not be loaded in wire\core\Functions.php:955

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1107]
### Short description of the issue

When opening any user edit screen this warning shows up in the tracy debug bar.

### Expected behavior

There should not be any warnings.

### Setup/Environment

* ProcessWire version: 3.0.149

**Comment by JanRomero** [comment]
Do you have a more complete stack trace? The class ProcessWire\2020-03-03 09:46:43 is obviously invalid, so it looks like some DateTime got mixed up in something it shouldn’t have. It would be interesting to see how wireClassParents() is called.

**Comment by BernhardBaumrock** [comment]
Good idea :)

![image](https://user-images.githubusercontent.com/8488586/75858247-168f8b00-5df8-11ea-94dc-8be556b430d5.png)

No idea though. Only thing I can think of is that I'm using my custom copy of AdminThemeUikit (see list point 31). But that's an untouched copy I'm only using for parsing LESS into a new admin CSS.

**Comment by JanRomero** [comment]
Yeah so, [in RockDateTime you override the module’s __toString() method with a formatted date](https://github.com/BernhardBaumrock/RockDatetime/blob/5c485a044b64bfc5ff7a8e2c40528581f8298f82/RockDatetime.module.php#L435). Then in FieldtypeModule->getInputfield() it’s calling all wireClassParents() for each module’s string representation, which should be the class name but in your case is a date, so it trips up.

**Comment by BernhardBaumrock** [comment]
Wow, thanks for finding that @JanRomero ! Could you please give me a hint how you did that? I can't seem to find any indications pointing to RockDatetime in my log :|

**Comment by JanRomero** [comment]
The clue is that the throwing function is called with "$module" in quotes, so the module is passed as a string.

Actually I tried to replicate the error in one of my installations by overriding toString() in a random site module, but since I couldn’t make it happen that easily, there might be something else playing into it.

But the error was complaining about a misplaced DateTime and knew from the forums you were working on RockDateTime (which looks epic btw), so I went for a little scroll in there :)

**Comment by BernhardBaumrock** [comment]
Hey @JanRomero thank you very much for your investigations :) Also thank you for the kind words. RockDatetime is actually just a necessity for RockDaterange (this will hopefully really be epic ;) ), but as the forum member with the unspellable name mentioned all (and much more) of RockDatetime is already done in https://carbon.nesbot.com/ so I'll likely switch to that library when I find the time.
