### ISSUE TITLE
$sanitizer->truncate returns result longer than maxLength

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1108]
### Short description of the issue

![img](https://i.imgur.com/waK9xRl.png)

The first dump returns a string of length 87 that is longer than the max setting of 84.

### Expected behavior

It should cut off one sentence to make sure the result matches the maxLength setting.

### Additional info

I narrowed down this issue to the existance of special characters. In my case that are the quotes that are causing the problem. The string is actually longer than what humans see as characters because the quotes are represented by some other encoding (ascii?).

### Steps to reproduce the issue

Here's the code to copy+paste:

```php
$strings = [
    "Das Thema „Coronavirus“ beherrscht im Moment. Die Schlagzeilen und beunruhigt auch. Viele Menschen in Niederösterreich.",
    'Das Thema "Coronavirus" beherrscht im Moment. Die Schlagzeilen und beunruhigt auch. Viele Menschen in Niederösterreich.',
    'Das Thema Coronavirus beherrscht im Moment. Die Schlagzeilen und beunruhigt auch. Viele Menschen in Niederösterreich.',
];
$options = [
  'type' => 'sentence',
  'maxLength' => 84,
  'visible' => true,
  'keepFormatTags' => true,
  'more' => '',
];
foreach($strings as $str) {
    db($s = $sanitizer->truncate($str, $options), strlen($s));
}
```

### Setup/Environment

* ProcessWire version: 3.0.149

**Comment by matjazpotocnik** [comment]
```
foreach($strings as $str) {
    db($s = $sanitizer->truncate($str, $options), mb_strlen($s));
}
```

**Comment by BernhardBaumrock** [comment]
Thx @matjazpotocnik are you saying that the truncate() method should use mb_strlen() instead of strlen() ?

**Comment by matjazpotocnik** [comment]
Sorry for the short response in a hurry. What I'm saying that YOU should check the length of the string with mb_strlen() instead of strlen().

**Comment by JanRomero** [comment]
Clearly the first dump has the same “length” in terms of human readable characters as the second dump, which is 83 characters long. Because `strlen()` [returns the number of bytes in a string](https://www.php.net/manual/en/function.strlen.php), not the number of characters, and your first test case contains the multi-byte quotation marks (as it should 💪), the count is off. So I would say the sanitizer works as expected.

**Comment by BernhardBaumrock** [comment]
Thx, that makes sense! :)
