### ISSUE TITLE
Broken top nav links in Google Chrome

### ISSUE THREAD

**Issue by uiii** [processwire/processwire-issues#111]
### Short description of the issue

PW detect Google Chrome on desktop as a touch device by adding the `touch-device` class to the `body` element. This breaks the links in the the top nav buttons (Pages, Setup, Modules). 

### Expected behavior

Click on top nav buttons will change the location to corresponding admin section.

### Actual behavior

Click on button it will only toggle the dropdown menu but don't change the location.

### Steps to reproduce the issue

1. Open Google Chrome
2. Go to http://demo.processwire.com/admin/page/
3. Click on "Setup" button in top navigation
4. The page location won't change

### Setup/Environment

* ProcessWire version: 3.0.42+
* Google Chrome version: 54.0.2840.99

### Notes
e.g. Firefox works fine

**Comment by mikerockett** [comment]
I'm unable to reproduce this in 3.0.43, and I have a touch device. When using the mouse, the page navigates as expected. Demo is running on 3.0.41, which does appear to have the issue on my device.

**Comment by uiii** [comment]
I've found out this is in fact a duplicate of #84. So, I'm closing.
