### ISSUE TITLE
wireBytesStr() bug

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1110]
```
$bytes = 10737418240; // 10 GB
echo wireBytesStr($bytes); // output: -2147483648 bytes

$bytes = 5368709120; // 5 GB
echo wireBytesStr($bytes); // output: 1 GB

$bytes = 10995116277760; // 10 TB
echo wireBytesStr($bytes); // output: 0 bytes
```

If I comment this line then it works:

`if(!is_int($bytes)) $bytes = (int) $bytes;`

I assume this is the size limitation of integer, different on 32 and 64 bit platforms.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I can't seem to duplicate this one here. Here's the output that I get in testing:
~~~~
10737418240 = 10 GB
5368709120 = 5 GB
10995116277760 = 10240 GB
~~~~
Note that wireBytesStr() doesn't cover TB. The intention with this method is to cover the range of assets that might be in ProcessWire, so I'm guessing the GB+ range is not likely for many, though still good to have support for it either way.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign thanks for testing. As I said, this is likely due to the size of an integer in different environments. Does commenting out the line in question make any difference in your testing? Since I can't use wireBytesStr function, I'm using this (taken from AIOM by David Karich):

function _wireBytesStr($bytes) {
	$label  = array('B', 'kB', 'MB', 'GB', 'TB', 'PB');
	for ($i = 0; $bytes >= 1024 && $i < 5; $bytes /= 1024, $i++);  // 5 = (count($label) - 1
	return round($bytes) . ' ' . $label[$i];
}

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Commenting out that line doesn't change the results here. Maybe makes sense to remove it then. Any idea why skipping the (int) typecasting makes it work in your case? Is PHP instead typecasting it as a float or something?

**Comment by matjazpotocnik** [comment]
![image](https://user-images.githubusercontent.com/7663992/88930050-3ded6580-d27b-11ea-8798-c5d201574366.png)

While my OS (windows) is 64 bit, PHP is 32 bit and thus max integer is limited to 2147483647, 2GB.
