### ISSUE TITLE
FieldTypeCache broken with 3.0.142+

### ISSUE THREAD

**Issue by GuyVerville** [processwire/processwire-issues#1113]
### Short description of the issue

Can no longer edit a page based on a template that use a FieldTypeCache field. Reverting to 3.0.139 (or before 3.0.148) works.

### Expected behavior

Be able to edit the page. 

### Actual behavior

1. Edit a page based on template containing a FieldTypeCache field. 
2. Data in the the field must be in the database. Example : {"ambience":[{"data":"distinction-laminate.jpg","description":"[\"\"]","modified":"2018-06-18 11:11:45","created":"2018-06-18 11:11:45","filedata":null},{"data":"distinction-laminate-1.jpg","description":"[\"\"]","modified":"2018-06-18 11:14:22","created":"2018-06-18 11:14:22","filedata":null}],"body":{"data":"<p>Distinction is a&nbsp;6.6\"X50.6\" laminate plank with a natural oak wood grain. Beautify your spaces with a hardwood look at a fraction of the cost. Distinction laminate flooring installs easily with its clip system technology making it a breeze to update your home or commercial decor!</p>","data2904":"<p>Distinction est une planche stratifiée de 6,6 « x&nbsp; 50,6 » avec un beau grain de bois de chêne naturel. Embellissez vos espaces avec un look de bois franc à une fraction du coût. Les planchers de bois laminé Distinction s’installent facilement grâce à leur technologie de système de clips. C’est un jeu d’enfant de mettre à jour votre décor qu’il soit résidentiel ou commercial&nbsp;avec Distinction.</p>"}}
3. The pages crashes.
4. Clear your FieldTypeCache table (or revert to a Processwire prior to 3.0.142). Problem disappears.

### Optional: Screenshots/Links that demonstrate the issue

![1798420548_CleanShot2020-03-07at14_54_11 png 6afe9f8dab0f2f6a15c3c6b889a50dd0](https://user-images.githubusercontent.com/61939221/76163888-9717f980-6120-11ea-9919-685b6883a6e4.png)

**Comment by ryancramerdesign** [comment]
@GuyVerville I think I've got this one fixed, but please let me know if you continue to run into it. Looks like it primarily affects file/image fields. Thanks.

**Comment by netcarver** [comment]
@GuyVerville Can you confirm if this is fixed for you or not?

**Comment by GuyVervillePerso** [comment]
I will have to reuse this functionality. Consider it closed then because I am not sure I will use it again for the moment.

**Comment by netcarver** [comment]
Done, thank you.
