### ISSUE TITLE
Manual Page Sort Causes RSOD

### ISSUE THREAD

**Issue by outflux3** [processwire/processwire-issues#1114]
### Short description of the issue

Manually moving pages in the page tree (when a sort is configured) causes Red Screen of Death.

### Expected behavior

Manually moving pages when a sort is configured shows a notification or warning, but not Red Screen of Death.

### Actual behavior

RSOD

### Optional: Screenshots/Links that demonstrate the issue

![rsod_page_move](https://user-images.githubusercontent.com/1743040/76221491-8da99280-61ef-11ea-94ca-352e2300976e.jpg)

### Optional: Suggestion for a possible fix

Do not throw WireException, as non superusers users doing this will be horrified and confused if they make a mistake.

### Steps to reproduce the issue

1. Setup a page with children sorted by a field
2. Try to move the pages manually in the page tree.
3. Experience RSOD (not sure what happens if Tracy is not installed).

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.148|
|PHP|7.2.28|
|Webserver|Apache|
|MySQL|5.6.45|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|3600 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|32M|
|post_max_size|8M|
|upload_max_filesize|2M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminCustomFiles|0.8.7|
|AdminHelp|1.0.9|
|AdminHelpTab|1.0.8|
|AdminOnSteroids|2.0.20|
|AdminPageFieldEditLinks|3.1.2|
|BatchChildEditor|1.8.19|
|ClearCacheAdmin|0.0.5|
|CustomInputfieldDependencies|0.1.9|
|FieldtypeAdminCustomPagesSelect|1.0.0|
|FieldtypeColorPicker|2.0.3|
|FieldtypeCroppableImage3|0.9.15|
|FieldtypeMultiplier|0.1.1|
|FieldtypeTable|0.1.7|
|FieldtypeTemplates|1.0.0|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|ImportExternalImages|2.0.8|
|InputfieldAceExtended|1.1.3|
|InputfieldColorPicker|2.0.3|
|InputfieldCroppableImage3|0.9.15|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldSelectExtended|0.0.1|
|InputfieldSelectize|1.2.0|
|InputfieldSelectizeMultiple|1.2.0|
|InputfieldSimpleMDE|1.0.7|
|InputfieldTable|0.1.7|
|InputfieldTextareas|0.0.7|
|JqueryDataTables|1.9.4|
|JqueryIonRangeSlider|0.0.4|
|JquerySelectize|1.0.4|
|LimitPageTable|0.1.10|
|MarkupRSSEnhanced|1.0.0|
|MarkupSimpleNavigation|1.3.6|
|MarkupSiteMetaAdvanced|1.6.0|
|MarkupSocialShareButtons|1.0.5|
|PageTableExtraActions|0.1.1|
|PrevNextTabs|0.1.5|
|ProCache|3.1.8|
|ProcessAdminCustomPages|1.1.1|
|ProcessAdminHelp|1.0.8|
|ProcessChangelog|1.5.7|
|ProcessChangelogHooks|1.2.2|
|ProcessChildrenCsvExport|1.8.18|
|ProcessCroppableImage3|0.9.15|
|ProcessCustomPageIframe|1.0.0|
|ProcessDatabaseBackups|0.0.5|
|ProcessFormBuilder|0.3.4|
|ProcessGeneralSettings|1.2.1|
|ProcessGetVideoThumbs|1.1.4|
|ProcessJumplinks|1.5.52|
|ProcessModuleTookit|0.1.5|
|ProcessPageListerPro|1.1.1|
|ProcessProCache|3.1.8|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SelectizeTemplateFieldTags|0.0.8|
|SimpleBlogEngine|0.0.1|
|SimpleSiteEngine|1.2.0|
|SimpleSiteMeta|0.0.1|
|SimpleThemeEngine|0.0.1|
|SiteUtilities|0.0.1|
|TextformatterSoundmanager|1.1.1|
|TracyDebugger|4.19.7|
</details>

**Comment by ryancramerdesign** [comment]
@outflux3 I can't seem to duplicate this one. When I move the pages (that have a predefined sort), I get a dialog popup that says the move wasn't allowed and the reason why. Any other steps I'm missing?

**Comment by outflux3** [comment]
Just tested again and i'm still getting that RSOD...

Template "Sort settings for children" is setup a field, with Reverse sort direction checked.

I can get you a login to the site where it is happening, otherwise i'm just basically moving a page in the tree, where the template has the sort...

**Comment by matjazpotocnik** [comment]
@outflux3, I also can't replicate this. In my test case, I set up to sort by created date, reversed. Upon the page move, I get a dialog, not RSOD.

**Comment by outflux3** [comment]
This isn't happening anymore on this site. 

But it was definitely happening 3.0.148. That site is now on 3.0.165. Something must have changed with the core, or a module upgrade that fixed it.
