### ISSUE TITLE
PagefilesManager::dirToPageID() doesn't work correctly with $config->pagefileExtendedPaths

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1115]
### Short description of the issue

Screenshot demonstrates the issue:
![2020-03-13_173605](https://user-images.githubusercontent.com/1538852/76590126-24a87e80-6551-11ea-8827-c1e6bac40101.png)

This issue in turn affects `PagefilesManager::getFile()` which relies on `PagefilesManager::dirToPageID()` when the method is supplied with a URL or path.

### Setup/Environment

* ProcessWire version: 3.0.151
* (Optional) PHP version: 7.2

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
