### ISSUE TITLE
Unique option for email field makes field unsaveable

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1117]
### Short description of the issue

When the "Unique" option is enabled for the "email" field (and any InputfieldEmail field I think) it becomes impossible to save any value to the field. Whatever email address is entered the error is always:

**Email [address] is already in use, please use a different one**

![2020-03-16_145215](https://user-images.githubusercontent.com/1538852/76716699-139c7f00-6796-11ea-86e1-aa49882ba9ad.png)

![email](https://user-images.githubusercontent.com/1538852/76716706-18613300-6796-11ea-99c9-075b658006b1.gif)

### Optional: Suggestion for a possible fix

Perhaps [this conditional](https://github.com/processwire/processwire/blob/00b89f71b3a67f0222bfb85a620a9e65e3045cb3/wire/modules/Inputfield/InputfieldEmail.module#L78-L79) should be:

```php
$pageId = $fields->tableTools()->valueExists($this->hasField, $value);
if($pageId && $pageId != $page->id) {
```

### Setup/Environment

* ProcessWire version: 3.0.152

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai, good find, I've pushed the suggested fix.
