### ISSUE TITLE
Multi-language Inputfields on single-language Pages

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1118]
### Short description of the issue

If you have multilang Inputfields on a Page that has setting noLang = 1 the Inputfield will still be a multilang Inputfield. So far, so good and correct, but if you also set noLang = 1 for this field, you'll have a problem! The value of the input will be dependent on the user's current language and not on the active language of the page being edited!

### Expected behavior

The Inputfield's value should be stored and viewed in the language that is set for the page (default language).

### Actual behavior

The value will be stored depending on the user's language and therefore result in unexpected and different results!

Example:

I have a multilang site with 2 languages: default = German, english = English. I also have a template `FOO` that is set to `noLang = 1` (as the frontend of this site is only in german and the backend is multi-language for different editors).

Editor `DE` has a german backend and edits page `example page` with a file field set to `description rows = 1, noLang = 1`. The inputfield shows only one row for the description, so he inputs `Datei-Beschreibung in Deutsch`.

Now Editor `EN` opens this page and *does not see a file description*! She inputs `File-description in english` and saves the page.

Now we have 2 values for the same thing: A german and an english value for a file description on a single-language page that should only have a german file-description! On the frontend `EN` will never see her description that she just saved to that page. The only way to change the file description shown in the frontend would be to change her language in the backend to `default` (german) and then save the page again.

I understand that multi-lang fields must still be multi-lang fields under the hood as you've already explained to me here: #963 But the Inputfield/Fieldtype should IMHO really take care of saving the input value to the correct language - namely the language of the page and not to the language of the user!

I guess this behaviour also affects all other multi-language inputfields!

### Steps to reproduce the issue

1. Setup a multilang site
1. Setup 2 languages
1. Setup a template noLang = 1
1. Add a file field with a single discription input and also setting noLang = 1
1. Set your user's language to lang nr. 1
1. Input `some text lang 1`
1. Save the page, you'll see the saved value
1. Change the language to lang nr. 2, you'll see an empty value for your file description
1. Input `other text lang 2`
1. Save and see `other text lang 2` as value
1. Change back to lang nr. 1 and you'll see `some text lang 1` again

### Setup/Environment

* ProcessWire version: 3.0.152

**Comment by BernhardBaumrock** [comment]
As a dirty fix I have this hook in place now:
```php
$wire->addHookAfter("InputfieldFile::processInputFile", function(HookEvent $event) {
  $pagefile = $event->arguments(1);
  foreach($this->languages as $lang) {
    $pagefile->description($lang, $pagefile->description);
  }
});
```
This writes the description to every available language. The problem with that solution is that if I added a language later, the inputfield would be empty for that language overwriting existing descriptions on page save!

I think this is a severe issue and would be really greatful for a proper solution so that the value is on one hand stored for the correct language (the page language) and on the other hand also displayed correctly, so that if I added a new language the inputfield still showed the value of the default language!

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign it would really be great to hear your thoughts about this. I'll try to rephrase the problem:

* multilang setup
* multilang field (eg title = FieldtypeTextLanguage)
* template with setting "disable multilang for pages having this template"

* edit page with user "english-user" having lang = EN --> save title "test english"
* edit page with user "german-user" having lang = DE --> save title "test german"

You end up having different titles for one single page that should be single-language only! Whenever "english-user" edits or views the page, it will see "test english" as title. Whenever "german-user" opens the page, it will see "test german" - but the inputfield is single-language only! There are no language tabs! The user sees only one inputfield and can only input text in his language.

I understand, that the field is multilang behind the scenes, but it should use/populate the default language only on single-language pages!

Thx

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Thanks, I think I've got this one fixed, but needs confirmation if you get a chance. I wasn't able to duplicate the issue from your first message in this thread (file field), and still can't. But I was able to duplicate (and fix, hopefully) the one you mentioned directly above, testing with a multi-language title field.

**Comment by netcarver** [comment]
@BernhardBaumrock Can this be closed now?

**Comment by MrSnoozles** [comment]
@BernhardBaumrock This still happens in 3.0.200, at least for multilanguage textareas that have noLang=1. Seems like it is not yet fixed completely?

**Comment by BernhardBaumrock** [comment]
@MrSnoozles I don't know where I had the issue so I would need some time to confirm but If you have the issue present it would be great if you could assist @ryancramerdesign to fix it!

**Comment by MrSnoozles** [comment]
@ryancramerdesign I [opened a PR](https://github.com/processwire/processwire/pull/256) with a possible fix. I don't know if this added line would have any unintended side effects. But it would fix the problem.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock @MrSnoozles Thanks, I was able to duplicate the issue here and attempted a fix, which seems to work here. (The mentioned PR didn't fix it for me, though it looked like it did at first). I found the source of the issue was in both FieldtypeTextareaLanguage and in InputfieldFile. (Single line text inputs using FieldtypeTextLanguage did not appear to have the issue). Do you find this also fixes the issue for you? Thanks.

**Comment by BernhardBaumrock** [comment]
Great @ryancramerdesign  thank you! I've done a test install and from what I saw it looks good! @MrSnoozles I'll close the issue and can reopen it if necessary.
