### ISSUE TITLE
Error: strpos(): Empty needle on line: 462 in /wire/core/Sanitizer.php

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1119]
### Short description of the issue

That error appears if you do a `testAll()` or `attrName()` on non letter chars

### Expected behavior

No error

### Actual behavior

You get the above error.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/871211/76814582-5cfdc600-67b8-11ea-9381-a2d30f8e5ef6.png)

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this
