### ISSUE TITLE
Fields randomly disappearing from Templates

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1120]
### Short description of the issue

When adding and removing fields to templates in the admin, we have on occasion discovered random fields being removed from the user template. This has happened several times (3-4) over a period of 3-4 months, and every time the fields that are dropped appear to be a different random set. The last time, even the roles and password fields were removed from the user.  For what it's worth, we are working in advanced mode and have added our own fields to the user template. However, while the issue only seems to effect the user template, it doesn't seem to only be limited to making changes on the user template.

Thankfully, the data is not actually dropped from the database. It appears that only the fieldgroups_fields table is effected by this. So once you add the fields back to the template, the data is visible again. This seems like our best clue towards discovering the source of this issue.

I hesitate to report this one since it is not one I am able to reliably reproduce yet and so far it has only been an issue on one of our projects, but it is an extremely concerning issue for us and I'm sure for anyone else who might stumble upon it. Perhaps there are others who have encountered this issue who could shed further light on it.

### Steps to reproduce the issue

Each time this has happened (probably 3 or 4 times in total), we have tried recalling the exact steps that led to the fields disappearing from the user template, but have been unable to reliably recreate the problem. All we know for sure is that it happens while adding or removing fields to templates.

### Setup/Environment
We are using the InnoDB engine and have Advanced Mode on. We're running on an AWS server. We're using database sessions. We've done our best to remove any modules or hooks that could possibly be related to the core field/template management. 

Another factor that may be of interest is that in this project we use a camelCase naming convention for field names, rather than the usual underscores.

* ProcessWire version: 3.0.147 (also observed on a prior version)
* (Optional) PHP version: 7.2.24
* (Optional) MySQL version: 8.0

**Comment by thetuningspoon** [comment]
I just had another possible recurrence of this issue on a different project, this time with a custom template rather than the user template. The template's modified date was still showing as "2 years ago", yet all of the fields were missing from the template. Adding them back to the template allowed me to see the data again on the pages that used the template.

I don't really have any further insight into the circumstances that lead to this happening. Hoping someone else will come across this who has the same issue. 

This project uses PW 3.0.123

**Comment by thetuningspoon** [comment]
This just happened again with another custom template. All fields but one disappeared from the template. No changes were made to the template directly, so it is a complete mystery.

All projects this has happened on are very large applications, with many templates, fields, and pages.

PW 3.0.123, using InnoDB

**Comment by ryancramerdesign** [comment]
@thetuningspoon I haven't yet heard of this occurring anywhere else, but am keeping an eye out. A few things I'd suggest:

- Use a newer version of PW like 3.0.164+ if possible, especially given that you are using MySQL 8.
- You mentioned this being on large applications, so I think it would be worth checking your PHP max_input_vars setting in php.ini and bumping it up to 5000 if it's less than that. The default value of 1000 is sometimes not enough for larger applications.
- Look for any common 3rd party modules common among the installations you've observed the issue in, especially any that autoload and/or add hooks. 
- Double check that neither "suhosin" or "mod_security" is installed, as either of these can mess with your input and break things, especially when configured aggressively.

**Comment by thetuningspoon** [comment]
Thanks for these suggestions, Ryan. Can you think of a specific scenario under which low max_input_vars being set too low would actually cause this to happen?

**Comment by netcarver** [comment]
@thetuningspoon Michael, longshot: could you add a hook on Fieldgroups::save() and Fieldgroups::delete() and look for unexpected group or field deletions? Updated: maybe saveContext() as well.

**Comment by thetuningspoon** [comment]
@netcarver That's a good idea. I just had this happen again tonight on our internal time keeping system. All fields disappeared from one of the templates, and I had to import them again from my dev copy. It's really odd.

Anyway, I'll try to add some logging with those hooks.

**Comment by netcarver** [comment]
You could try doing something like this in site/ready.php with those hooks (technique recently used to track down a redirect loop on a site, just change the hook as needed...)

```
if (wire()->config->debug) {
    /**
     * Add debug backtraces to redirect() calls. This can help detect redirect loops in debug mode.
     */
    function nc_debug_backtrace($limit = 12) {
        ob_start();
        debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, $limit);
        $trace = ob_get_contents();
        ob_end_clean();

        // Remove first few stack frames from the backtrace as it's this function and the hook execution chain's calls to it...
        $trace = preg_replace ("/^#0\s+[^\n]*\n/", '', $trace, 1);
        $trace = preg_replace ("/^#1\s+[^\n]*\n/", '', $trace, 1);
        $trace = preg_replace ("/^#2\s+[^\n]*\n/", '', $trace, 1);
        /* $trace = preg_replace ("/^#3\s+[^\n]*\n/", '', $trace, 1); */

        return $trace;
    } 

    $session->addHookBefore("redirect", function (HookEvent $event) {
        $url  = $event->arguments(0);
        $type = $event->arguments(1);
        $type = var_export($type, true);
        $backtrace = nc_debug_backtrace();
        wire()->log->save('session', "Redirecting to [$url], 301? = $type, [$backtrace]");
    });
}
```
Hope that helps.

**Comment by thetuningspoon** [comment]
While trying to figure out which methods I should be hooking for this, I came across something in WireSaveableItemsLookup::save() that looks odd to me. This is the method that Fieldgroups::save() is calling. Fieldgroups is the only class that extends WireSaveableItemsLookup.

```/**
	 * Save the provided item to database
	 * 
	 * @param Saveable $item
	 * @return bool
	 * @throws WireException
	 *
	 */
	public function ___save(Saveable $item) {

		if(!$item instanceof HasLookupItems) throw new WireException($this->className() . "::save() requires an item that implements HasLookupItems interface"); 
	
		$database = $this->wire('database'); 	
		$lookupTable = $database->escapeTable($this->getLookupTable());
		$lookupField = $database->escapeCol($this->getLookupField());
		$table = $database->escapeTable($this->getTable());
		$item_id = (int) $item->id; 

		if($item_id) {
			$query = $database->prepare("DELETE FROM $lookupTable WHERE {$table}_id=:item_id");
			$query->bindValue(":item_id", $item_id, \PDO::PARAM_INT);
			$query->execute();
		}
			
		$result = parent::___save($item); 
		$item_id = (int) $item->id; // reload, in case it was 0 before

		$sort = 0; 
		if($item_id) foreach($item->getLookupItems() as $key => $value) {
			$value_id = (int) $value->id; 
			$query = $database->prepare("INSERT INTO $lookupTable SET {$table}_id=:item_id, $lookupField=:value_id, sort=:sort"); 
			$query->bindValue(":item_id", $item_id);
			$query->bindValue(":value_id", $value_id);
			$query->bindValue(":sort", $sort); 
			$query->execute();
			$this->resetTrackChanges();
			$sort++; 
		}

		return $result;	
	}
```

Why are we deleting the item from the lookup table (fieldgroups_fields)? It looks like it is being recreated afterwords, but perhaps if the request died before it finished, you could end up with rows missing from fieldgroups_fields?

**Comment by thetuningspoon** [comment]
I finally have what may be some helpful information on this. I had added a hook to Fieldgroups::save to log when that function was called, and that came in useful today when I once again ended up with fields missing from a template (the user template this time).

Earlier today, I used the Actions tab on a field to add the field to a template (not the user template). After clicking save, the page spent at least 30 seconds processing, until it finally timed out. Later on, I noticed that several fields (including the pass field!) had disappeared from the user template. Upon checking the logs, I see that Fieldgroups::save was called for every single template in the system. That's about 150 templates. So I suspect that it has something to do with using the Actions tab to add/remove fields when working with a high volume of templates. 

As I mentioned in my last post above, the function that Fieldgroups::save() calls removes data before repopulating it. So it seems like adding a database transaction here would be some good quality assurance, if reworking the save logic to avoid the delete altogether is not possible.

We're now running on PW 3.0.172

**Comment by ryancramerdesign** [comment]
@thetuningspoon The method where that happens is `ProcessField::___executeSendTemplatesSave()` but if it was saving all of the templates and fieldgroups, you'd have notifications that it did so for all of those templates/fieldgroups, since it does `$this->message()` calls for those that it modifies. So I'm wondering if there's another hook or module (like FieldtypeFieldsetGroup) involved that might be adding more to this.

When I add a field or remove a field, on my installation, it's only calling `$template->fieldgroup->save()` and `$template->save()` on those that actually changed. So it's still a mystery why you would have a fieldgroup like `user` getting modified when you add (or remove?) a field from a different template. If I was seeing something strange like that, I would add a hook to capture it and have a look at the debug backtrace to see what initiated the call to save the user fieldgroup:
~~~~~~
$wire->addHookBefore('Fieldgroups::save', function($event) {
  $fieldgroup = $event->arguments(0);
  if($fieldgroup->name === 'user') {
    $fieldgroup->error(Debug::backtrace()); 
    // or if timing out, throw exception instead to see that backtrace (in debug mode):
    // throw new WireException('gotcha!'); 
  } else {
    $fieldgroup->warning("Saving fieldgroup: $fieldgroup->name"); 
  }
}); 
~~~~~~
Please let me know what you find? Thanks.

**Comment by matjazpotocnik** [comment]
@thetuningspoon can you provide more info?

**Comment by thetuningspoon** [comment]
@ryancramerdesign Thanks for the hook. I tried it out while adding/removing a field from just one template and I got a warning message for every fieldgroup in the system, as well as the error trace from the user fieldgroup:

```
Array
(
    [0] => Array
        (
            [file] => /wire/core/Fieldgroup.php:425
            [call] => $fieldgroups->save([ Fieldgroup(user) ])
        )

    [1] => Array
        (
            [file] => /wire/modules/Process/ProcessField/ProcessField.module:2658
            [call] => Fieldgroup->save()
        )

    [2] => Array
        (
            [file] => /wire/core/ProcessController.php:337
            [call] => ProcessField $process->executeSendTemplatesSave()
        )

    [3] => Array
        (
            [file] => /wire/core/admin.php:160
            [call] => ProcessController->execute()
        )

    [4] => Array
        (
            [file] => /wire/modules/AdminTheme/AdminThemeUikit/controller.php:15
            [call] => require("/Users/mspooner/dev/mcm-ecommerce/wire/core/admin.php")
        )

    [5] => Array
        (
            [file] => /site/templates/admin.php:15
            [call] => require("/Users/mspooner/dev/mcm-ecommerce/wire/modules/AdminTheme/AdminThemeUikit/controller.php")
        )

    [6] => Array
        (
            [file] => /wire/core/TemplateFile.php:327
            [call] => require("/Users/mspooner/dev/mcm-ecommerce/site/templates/admin.php")
        )

    [7] => Array
        (
            [file] => /wire/modules/PageRender.module:553
            [call] => TemplateFile->render()
        )

    [8] => Array
        (
            [file] => /wire/modules/Process/ProcessPageView.module:225
            [call] => $page->render()
        )

    [9] => Array
        (
            [file] => /wire/modules/Process/ProcessPageView.module:171
            [call] => ProcessPageView->renderPage(Page $obj)
        )

    [10] => Array
        (
            [file] => /index.php:57
            [call] => ProcessPageView->execute([ true ])
        )

)
```

Looking at the code in ProcessField::___executeSendTemplatesSave(), this makes sense as under the "additions" section of the function (line 2658 in PW 3.0.178) it is calling save for every fieldgroup of every template without condition:

 
```
// first handle additions, since it's possible for removals to take a long time or remote chance of timeout
		foreach($this->wire('templates') as $template) {
	
			foreach($fields as $key => $field) {
					
				// usually just 1 element in $fields, except when $field is a FieldtypeFieldsetOpen in which case 
				// there is also the corresponding FieldtypeFieldsetClose
				$isFieldsetEnd = $isFieldset && $key > 0;
				
				$addFieldID = $this->wire('input')->post("add_{$field->id}_template_$template->id");
				if(!$addFieldID) continue;
				if(!$this->allowFieldInTemplate($field, $template)) continue;
				if($isFieldsetEnd && $template->fieldgroup->hasField($field)) continue;
				if($addFieldID === '-' && !$isFieldsetEnd) {
					// add as first field
					$template->fieldgroup->add($field);
					continue;
				}
				
				$before = substr($addFieldID, 0, 1) == '-';
				$addFieldID = (int) ltrim($addFieldID, '-');
				$fieldNames = array();

				foreach($template->fieldgroup as $f) {
					$fieldName = $f->name;
					$fieldNames[$fieldName] = $fieldName;
					
					if($f->id != $addFieldID) continue;
					
					if($isFieldsetEnd && !isset($fieldNames[$fields[0]->name])) {
						// force to insert after opening fieldset
						$before = false;
						$addFieldID = $fields[0]->id;
						continue;
					}

					if($before) {
						$template->fieldgroup->insertBefore($field, $f);
						$this->message(sprintf($this->_('Added field "%1$s" to template "%2$s" before "%3$s"'),
							$field->name, $template->name, $f->name));
					} else {
						$template->fieldgroup->insertAfter($field, $f);
						$this->message(sprintf($this->_('Added field "%1$s" to template "%2$s" after "%3$s"'),
							$field->name, $template->name, $f->name));
					}
				}
			}
			$template->fieldgroup->save();
		}
```

**Comment by ryancramerdesign** [comment]
@thetuningspoon Can you try the dev branch? I think the reason I'm seeing a different result from you is that it looks like this section of code has changed quite a bit since the version you are running, so there appear to be a lot more conditions as to when it saves a fieldgroup or template. It looks to have been updated last year for an unrelated issue (1448) but I suspect it'll also fix the issue you are seeing.

**Comment by thetuningspoon** [comment]
@ryancramerdesign You're right, this is not a problem on the dev branch. Thanks! I'm going to close this as I assume it will resolve the original issue.

**Comment by BernhardBaumrock** [comment]
@adrianbj just found this by coincidence and thought it might be related to your recent issues?
