### ISSUE TITLE
SVG image background needs grey/white checkerbox

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1128]
### Short description of the issue

If you upload a fully white SVG which is quite common for a logo that you want to appear on a dark background, you can't see it in the admin.

### Expected behavior

This would behave the same way as transparent PNG images - the grey checkerbox pattern would allow you to see the logo and identify that it's transparent.

### Actual behavior

You can't see the logo because the background is white.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/871211/77429635-341c9880-6d97-11ea-9499-4bf92b8acd1e.png)

**Comment by cb2004** [comment]
Definitely agree

**Comment by cb2004** [comment]
Think I have found the issue, for me anyway. When the grid mode for the image is set to 'Vertical list', this CSS is removing the checkbox:
```
.InputfieldImageEditAll .gridImage__overflow {
background: none;
}
```
/wire/modules/Inputfield/InputfieldImage/InputfieldImage.css

**Comment by cb2004** [comment]
Still not sure this is the best fix. Happy to look into it further if you need @ryancramerdesign

**Comment by adrianbj** [comment]
@ryancramerdesign - do you need any help reproducing this one - that white version of the PW logo I just sent you will be a perfect test image for this.

**Comment by ryancramerdesign** [comment]
@adrianbj @cb2004 Well I didn't know before today that you could put a "background-image:" CSS on an `<img>` tag, but apparently you can, as it seems to work here at least with SVG. If I added the checkerboard to anything else, it wasn't quite right, so glad it worked. Does this seem to resolve it there also? Thanks.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that works!
