### ISSUE TITLE
Selector documentation: https://processwire.com/docs/selectors/#limit

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1129]
_This tells ProcessWire to return 50 results starting at the 50th (results 50–100)._

should be:

_This tells ProcessWire to return 50 (or less) results starting at the 51st (results 51–100)._

as the `start` selector field is being utilized as mysql OFFSET value

**Comment by ryancramerdesign** [comment]
Thanks @pine3ree I've corrected that.
