### ISSUE TITLE
Trashing or Restoring a page with children should change the modified date of those children

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1132]
If you trash a page, it's modified date gets updated. (good)

If you restore that page, it's modified date gets updated again. (good)

If you trash or restore a page that has children, its children will NOT have their modified dates updated. (bad)

Ideally, I would think these child pages should have their modified dates updated.

**Comment by BernhardBaumrock** [comment]
Hi @jlahijani  Hm. I'm not sure if I'd aggree on that. Do you have an example where/why this would make sense?

**Comment by jlahijani** [comment]
I realized this was occurring as a result of writing a special import script for a project that takes advantage of PagesExportImport.php.

Given the needs of my script, I have a check to see what pages have been modified or deleted on the site I'm importing from (aka the "source" site).  If a page with children no longer exists on the source site (trashed), it will delete it on the site I'm importing into.  If I restore that page (and it's children by result) on the source site, my script will know to import that restored page because I'm doing checks against its modified date.  However since the children do not have their dates modified on restore, it will not import them based on date checks I'm using.

(note: I'm using PagesExportImport.php in a unique way, so I'm not importing a page and it's children in one shot, mainly due to memory limits and other optimizations).

**Comment by matjazpotocnik** [comment]
@jlahijani, do you think this would be better suited as a feature request rather than an issue?

**Comment by jlahijani** [comment]
It's not an issue anyone, at least for me.  Furthermore, I think the existing functionality makes sense as it is.
