### ISSUE TITLE
Pasting a password on the Profile page does not activate the 'New password' field

### ISSUE THREAD

**Issue by MoritzLost** [processwire/processwire-issues#1133]
### Short description of the issue

On the Profile edit page (ProcessProfile module), the field to set a new password is disabled until the old password is disabled. However, the field for the new password does **not** become active if the old password is _copy-and-pasted_ instead of entered manually. This results in some users being unable to change their password.

### Expected behavior

Pasting your existing password in the _Current password_ field should activate the _New password_ field, the same as entering it manually. This is not really an edge-case, because if you're using a password manager you are likely to copy and paste passwords instead of entering them manually.

### Actual behavior

Pasting a password does not trigger the event handler which activates the _New password_ field. As a workaround, I instructed a client to paste the password, then delete the last character with the backspace key and enter it manually again just to trigger the event handling which activates the second field. This is of course suboptimal :)

### Optional: Suggestion for a possible fix

I'f im not mistaken [this snippet in InputfieldPassword.js](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPassword/InputfieldPassword.js#L23-L31) is responsible for activating the _New password_ field after the old one has been entered. Currently, this uses a `keyup` event listener, which doesn't always trigger when pasting something. It should be sufficient to just add event listeners for the `input` event (as well as `change` and `blur` for good measure):

```
$inputOld.on('keyup input change blur', function() {
    // ...
}); 
```

### Setup/Environment

* ProcessWire version:3.0.153
* PHP version: 7.4.4

**Comment by MoritzLost** [comment]
Minor correction: The issue only occurs if the password is pasted using the context menu (right-click -> paste) since this doesn't trigger a `keyup` event. Pasting with keyboard shortcuts works fine. Though I believe there are more edge-cases (not sure about auto-fill in password managers like LastPass) that would be better handled through the _input_ event instead of the _keyup_ event (or just using both).

**Comment by ryancramerdesign** [comment]
Thanks @MoritzLost - that pasting via the context menu was it, I could easily duplicate that. I just hadn't pasted that way in a long time, so didn't even think of it. Good find. I've pushed a fix for this like the one you suggested.
