### ISSUE TITLE
InputfieldInteger: defaultValue is always set if field is emptied, not only on newly created pages

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#1134]
### Short description of the issue

Using an **InputfieldInteger** with a `defaultValue`, this default value is always set if field is emptied. Not only on newly created pages.

### Expected behavior

The default value of an input field should only be used on newly created pages. 

**This is the field config (json):**

```
{
  "description": "Trial period for customers in days. Empty for no trial!",
  "notes": "Integer number (min value = 1).",
  "min": 1,
  "inputType": "number",
  "tags": "Snipcart",
  "zeroNotEmpty": 0,
  "collapsed": 0,
  "size": 10
}
```

### Setup/Environment
ProcessWire: 3.0.151
PHP: 7.0.33-0+deb9u6
Webserver: Apache/2.4.25 (Debian)
MySQL: 10.1.41-MariaDB-0+deb9u1

**Comment by ryancramerdesign** [comment]
@gadgetto The behavior of defaultValue is working how it's supposed to, but the description in the FieldtypeInteger config settings was not right. The defaultValue applies to an integer input that has no value present. It cannot differentiate whether it's a new page or not, it can only see if there is a value present or not. Such value won't exist for any page in the database until it is saved, which is what the "new page" thing was attempting to get across (albeit poorly). If you wanted "empty for no trial" then you would either want to have no defaultValue set or you would want to designate "0" (or some other number you decide) as your "no trial" value. I've updated the description for defaultValue in the field settings to remove reference to new pages, though it may still need work. Thanks.

**Comment by netcarver** [comment]
@gadgetto Martin, please could you check this and close the issue if done.

**Comment by ivangretsky** [comment]
@gadgetto, is it done and could be closed?

**Comment by gadgetto** [comment]
It's fixed now!
