### ISSUE TITLE
"Owner" selector doesn't allow for check_access

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1135]
### Short description of the issue

I have a Page Reference field named "district", the selectable pages for which live under page ID 6072. The district field is in the "user" template (among others).

I have the following selector in a template file to get all the district pages that are selected in the district field on user pages:

```php
$districts = $pages->find("parent=6072, district.owner.template=user");
```

This works when the current user is a superuser but gets no results when the current user is not a superuser. I guess this is because the user doesn't have access to the "user" template.

But after adding check_access=0 the selector still returns no results.

```php
$districts = $pages->find("parent=6072, district.owner.template=user, check_access=0");
```

I think it should be possible to use "owner" selectors like this for Page Reference fields in the user template.

### Setup/Environment

* ProcessWire version: 3.0.151

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this

**Comment by Toutouwai** [comment]
Thanks
