### ISSUE TITLE
Language Translator & custom namespacing : fails to find the translatable text 

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1139]
### Short description of the issue

Under a custom namespacing setup, the admin "Language Translator" tool fails at finding the translatable text strings.

### Expected behavior

"Language Translator" tool displays the translatable text strings of the source file.

### Actual behavior

None displayed.

### Steps to reproduce the issue

Example of my namespacing setup :

```
<php namespace Myapp\Feature

use ProcessWire as pw;
use Myapp\Feature\ClassB;

class ClassA {
   $pg = pw\pages()->get("testpage");   // this is how I perform every calls to the Processwire API, and it works perfectly
   $out = pw\__("text to translate");   // this also works (in terms of API & frontend rendering), no problem - but the admin "Language Translator" doesn't display this text

```

### Optional: Suggestion for a possible fix

In LanguageParser.php , method parseFile() : 

Currenty, the regexes used by preg_matches_all() don't capture pattern like `xxxxx\__(`
I propose to support such pattern, by adding support to a leading backslash : `\__()`
-> this may be fixed for example as follows : 
. currently : 
`		preg_match_all(	'/([\s.=(]__|^__)\(\s*' . 		// __(
`
. fixed : 
`		preg_match_all(	'/([\s.=(\\\\]__|^__)\(\s*' . 		// __(
`
(same goes for the other expressions)

### Setup/Environment

PW 3.0.153, PHP 7.4.3.

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed your suggested fix for this.
