### ISSUE TITLE
[has PR] Inputfield's wrapper markup is not hookable

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1141]
### Short description of the issue

At the moment there's no possibility to change the markup of an Inputfield's wrapper. The wrapper always has the following markup:

```html
<li class="Inputfield ..." id="wrap_Inputfield_...">
  <label class="InputfieldHeader ..." ...>...</label>
  <div class="InputfieldContent ...">...</div>
</li>
```

The problem is, that with the available options we cannot add markup here:

```html
## here ##
<li class="Inputfield InputfieldTextarea ..." id="wrap_Inputfield_...">
  ## here ##
  <label class="InputfieldHeader ..." ...>...</label>
  <div class="InputfieldContent ...">...</div>
  ## here ##
</li>
## here ##
```

### Expected behavior

See my simple real-life example here: https://github.com/processwire/processwire-issues/issues/1141#issuecomment-612356459

I've created a PR that makes it easy to modify the markup for any rendered Inputfield's wrapper:

```php
// add hook to modify inputfield markup
$class = "InputfieldWrapper::getItemVars(id=my_inputfield_id)";
$this->wire->addHookAfter($class, function(HookEvent $event) {
  $vars = $event->return;
  $out = "{out}<div>foo</div>";
  $vars['markup'] = str_replace('{out}', $out, $vars['markup']);
  $event->return = $vars;
});
```
This is the Information that you can modivy easily in your hook:

![image](https://user-images.githubusercontent.com/8488586/78883431-cb514380-7a59-11ea-8bdc-fbbedaeeca9b.png)

This means it would then be easy to modify almost any aspect of the markup **on a per-Inputfield basis**.

### Why current options are not enough

Currently we have these options:
* Hooking Inputfield::render
* InputfieldWrapper::setMarkup(...)

The problem with hooking the Inputfield's render() method is, that this makes only the InputfieldContent part editable. There's no way to control the final markup of the wrapper! The problem with using InputfieldContent is that this markup is hidden for collapsed Inputfields! I need some markup that is shown wheter the Inputfield is toggled or not.

The problem with `InputfieldWrapper::setMarkup` on the other hand is, that this modifies the markup of ALL Inputfields!

There is an option to define the Inputfield like this:

```
InputfieldAnything => array( any of the properties above to override on a per-Inputifeld basis)
```

The problem here is that I have a custom InputfieldWrapper that holds other Inputfields as children. I need to modify the markup of all direct children of this wrapper. These are all different Inputfield types, so I can't use setMarkup(['InputfieldWhatsoever' => ...])

### Optional: Screenshots/Links that demonstrate the issue

This is how it looks like using my hook above and the provided PR:

![image](https://user-images.githubusercontent.com/8488586/78882531-7eb93880-7a58-11ea-9d66-d5efb15c7021.png)

### Optional: Suggestion for a possible fix

**Please see this simple but powerful PR** https://github.com/processwire/processwire/pull/171

This is another hook to demonstrate the issue/solution:

```php
$this->addHookAfter("InputfieldWrapper::getItemVars(InputfieldPageTitle)", function($event) {
  $vars = $event->return;
  $out = "<div> --- top of inputfield li --- </div>"
    ."{out}"
    ."<div> --- bottom of inputfield li --- </div>";
  $vars['markup'] = str_replace('{out}', $out, $vars['markup']);

  $vars['markup'] = "<li class='Inputfield' style='border: 1px solid green; z-index: 2;'>new list item before title</li>".$vars['markup'];
  $vars['markup'] .= "<li class='Inputfield' style='border: 1px solid blue; z-index: 2;'>new list item after title</li>";

  $event->return = $vars;
});
```

![image](https://user-images.githubusercontent.com/8488586/78882898-0d2dba00-7a59-11ea-83a5-d57537a5623f.png)

And when toggled:

![image](https://user-images.githubusercontent.com/8488586/78882937-1ae33f80-7a59-11ea-882c-de48ab11a327.png)

**Comment by BernhardBaumrock** [comment]
@netcarver who's responsible for adding labels to issues? I guess this issue could get `has PR` or `has FIX` labels :)

**Comment by teppokoivula** [comment]
This seems more like a request than an actual issue. Maybe move to the requests-repository? :)

**Comment by BernhardBaumrock** [comment]
Hi @teppokoivula I get your point but for me this is really an issue and not a feature request. I simply cannot do what I need to do without this simple modifications. So it's not an "this request would make things easier" but a "I had to hack core files and without these modifications my code will break on any update".

**Comment by teppokoivula** [comment]
Right — I get what you're saying, and though I don't necessarily see this the same way, it's true that whether something is an issue / bug or a feature is not always 100% obvious :)

While you're waiting for Ryan to consider this, just wondering if something like this could work? It's entirely possible that I'm missing something or that you've already tried this, but just posting this in case it's of some help. Even if it would work, it's not as obvious as what you're suggesting, of course.

```
$custom = false;
$markup = InputfieldWrapper::getMarkup();
$wire->addHookBefore("InputfieldWrapper::render", function($event) use (&$custom, $markup) {
	if ($event->object->id == 'Inputfield_repeater_form_content_blocks') {
		$custom = true;
		$event->object::setMarkup([
			'item' => "<li {attrs}>{out}<div>foo</div></li>", 
		]);
	} else if ($custom) {
		$custom = false;
		$event->object->setMarkup($markup);
	}
});
```

**Comment by BernhardBaumrock** [comment]
Hi @teppokoivula 
thx for jumping in! I've tried your suggestion, but this solution is not only "not as obvious" but also does not work ;)
The problem ist that my Inputfield is actually an InputfieldWrapper having several dynamically loaded Inputfields as children. And I don't need to modify the parent wrapper, I need to modify the wrapper of every single direct child. That means I don't have an ID to check for.

Maybe I'm still missing something, but RobinS has also mentioned that things like this are not possible here: https://processwire.com/talk/topic/23358-how-to-modify-inputfield-markup/

> LoginRegisterPro has a similar setMarkup() method but has the added feature of letting you use "name=some_inputfield_name" as a key: https://processwire.com/store/login-register-pro/docs/#customizing-markup-and-or-class-attributes-html
>
> It would be cool if a feature like that was added to the core InputfieldWrapper::setMarkup method.

Or do you know of any way to modify the markup of field1 and field2 here?

```php
  public function executeTeppo() {
    $this->headline('Teppo Demo');
    $this->browserTitle('Teppo Demo');
    /** @var InputfieldForm $form */
    $form = $this->modules->get('InputfieldForm');
    
    $form->add([
      'type' => 'fieldset',
      'label' => 'wrapper',
      'children' => [
        [
          'type' => 'markup',
          'label' => 'field1',
          'value' => 'foo',
        ],[
          'type' => 'markup',
          'label' => 'field2',
          'value' => 'foo',
        ]
      ]
    ]);
    
    return $form->render();
  }
```

**Comment by Toutouwai** [comment]
This is probably best discussed in the forum, but it's not clear to me in what situation a person would ever need to insert markup anywhere other than in the content of the inputfield.

Can't you just not render the default label using the [SkipLabel](https://processwire.com/api/ref/inputfield/) constants and then if you want some custom label with markup before it then render it inside the content (i.e. hook the render method of the inputfield)?

**Comment by Toutouwai** [comment]
Sorry, I just saw your comment which explains why you can't put the markup within the inputfield content:

> The problem with using InputfieldContent is that this markup is hidden for collapsed Inputfields! I need some markup that is shown wheter the Inputfield is toggled or not.

**Comment by BernhardBaumrock** [comment]
This is what I need (what I'm doing now with my core hack:

![img](https://i.imgur.com/8mBSe0Z.png)

It's a simple hook when the PR is in place but impossible without it:

```php
// add hook to modify inputfield markup
$selector = "InputfieldWrapper::getItemVars(id={$inputfield->id})";
$this->wire->addHookAfter($selector, function(HookEvent $event) use($actions, $plusIcon) {
  $vars = $event->return;

  // replace wrapper markup
  $vars['markup'] = str_replace('{out}', "{out}".$plusIcon, $vars['markup']);
  $vars['label'] = str_replace('</label>', "$actions</label>", $vars['label']);

  $event->return = $vars;
});
```

**Comment by teppokoivula** [comment]
Thanks for the clarifications, Bernhard. This does indeed sound more complex than I originally thought :)

I'm really taking stabs in the dark here not knowing the full context, but in the case of your field1 + field2 example earlier you might be able to modify wrapper markup just for those specific inputfields by pre-fetching the IDs:

```
		$custom = false;
		$markup = InputfieldWrapper::getMarkup();
		$child_ids = $form->child()->children()->explode('id');
		$form->addHookBefore("InputfieldWrapper::render", function($event) use (&$custom, $markup, $child_ids) {
			if (!$custom && in_array($event->object->id, $child_ids)) {
				$custom = true;
				InputfieldWrapper::setMarkup([
					'item' => "<li {attrs}>{out}<div style='background:yellow'>foo</div></li>", 
				]);
			} else if ($custom) {
				$custom = false;
				InputfieldWrapper::setMarkup($markup);
			}
		});
		InputfieldWrapper::setMarkup($markup);
```

The point here is that we're only modifying the (static) markup of InputfieldWrapper right before rendering one of the children of the first fieldset you've added within the form object (this seems to be what you were after), and then returning markup to its original state so that subsequent inputs are not affected.

The problem is that I don't really know what you mean by dynamically added inputfields: inputfield always has an ID, so assuming that you're somehow able to get to them, you should be able to get those IDs and then use them to target the inputfield (or its parent for that matter).

On a loosely related note, this seems similar to what I've done in VersionControl. Back then I decided it'd be too much of a hassle to try to make this work on markup side, so I injected the UI elements with JS. Admin largely depends on JS anyway, so generally that's a viable solution.

**Comment by BernhardBaumrock** [comment]
@teppokoivula almost ;)

First of all thx for your efforts! The problem is, that the InputfieldWrapper::render is not called for every child of InputfieldWrapper. All child Inputfields are rendered in another way and so they end up being non-hookable.

Try this an any page edit form:

```php
// site/ready.php
$wire->addHookBefore("InputfieldWrapper::render", function(HookEvent $event) {
  bd($event->object->id);
});
```

How would you modify the markup of the wrapper of InputfieldPageName?

![image](https://user-images.githubusercontent.com/8488586/79065611-12397600-7cb2-11ea-9ea7-5196692d29dc.png)

As you can see the hook is not fired for the InputfieldPageName field. It is even not fired for any of the ProcessPageEditSettings fields. It is only fired once for the parent wrapper having id `ProcessPageEditSettings`.

The problem is that all inputfields are rendered as one huge concatenated string: https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/InputfieldWrapper.php#L537
https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/core/InputfieldWrapper.php#L762

I have found no hookable method call within that foreach which means that all children of any InputfieldWrapper are not hookable at all. You can either modify all or none of the children's wrapper markup using the setMarkup() technique.

If the method was built recursively your concept of hooking InputfieldWrapper::render based on some id would work. But it is not. And that's the issue.

Hooking Inputfield::render on the other hand does not work because this does only return the InputfieldContent portion.

I hope that makes sense and I didn't miss anything.

**Comment by BernhardBaumrock** [comment]
> On a loosely related note, this seems similar to what I've done in VersionControl. Back then I decided it'd be too much of a hassle to try to make this work on markup side, so I injected the UI elements with JS. Admin largely depends on JS anyway, so generally that's a viable solution.

I've thought about that as well. But that's my point: The issue is that modifying the markup of an Inputfield's wrapping markup is too much of a hassle! And it should really not be. PW has a lovely modular architecture anywhere but here.

JS is no option because of four main reasons:
* Access control
* Multilanguage
* Delay on page load (flicker, jumping around elements etc)
* AJAX loaded fields get more complicated and error prone

All that could be prevented with my pr and a simple hook:

```php
// add hook to modify inputfield markup
$class = "InputfieldWrapper::getItemVars(id=my_inputfield_id)";
$this->wire->addHookAfter($class, function(HookEvent $event) {
  $vars = $event->return;
  $out = "{out}<div>foo</div>";
  $vars['markup'] = str_replace('{out}', $out, $vars['markup']);
  $event->return = $vars;
});
```
