### ISSUE TITLE
Detailed error messages are shown to unauthorized visitors

### ISSUE THREAD

**Issue by JanRomero** [processwire/processwire-issues#1143]
### Short description of the issue

When ProcessWire encounters an error, it will show the detailed description to anyone who sends the headers `Host` and `X-Requested-With: XMLHttpRequest`, because WireShutdown believes to be in CLI mode (“This error message was shown because: you are using the command line API”).
[See this thread in the forums](https://processwire.com/talk/topic/23431-suppressing-“command-line-api”-error-messages-ajaxxhr/).

### Expected behavior

Non-superusers should only get the public error message.

### Actual behavior

Even if a visitor gets the public error message, they can resend the request as XMLHttpRequest and read the helpful message, potentially including code extracts, sql, database name etc.

### Suggestion for a possible fix

I’ve made a half-baked pull request here processwire/processwire#172 that just adds a superuser check and corrects the class description at the top.

### Steps to reproduce the issue
1. Introduce an error into any publicly accessible page, eg. remove a semicolon.
2. View the page as a guest and receive a generic “Internal Server Error”.
3. Use your browser’s dev tools to add `X-Requested-With: XMLHttpRequest` to the request and resend.
4. Receive some info including the line number and the entire file path from the web root.

### Setup/Environment

* ProcessWire version: 3.x

**Comment by adrianbj** [comment]
Just wanted to chime in to say that I can reproduce this and I think fixing this should be very high priority.

Interestingly, if you have Tracy installed and it's in Production mode (which it will be for guest users on a live site), then it will protect your site from this vulnerability.

**Comment by adrianbj** [comment]
PS, the easiest way I found for adding `X-Requested-With: XMLHttpRequest` was to use Chrome's "Copy as cURL" option, editing the captured request, adding `-H 'X-Requested-With: XMLHttpRequest'` to that and running from my terminal.

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix.

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - I am not seeing any difference in behavior here. Did that change make a difference at your end?

**Comment by adrianbj** [comment]
@JanRomero - would you mind checking Ryan's fix at your end please? My curl call is still returning the error message.

**Comment by JanRomero** [comment]
@adrianbj mh, I swapped out WireShutdown.php and it’s looking good on my end. I get “Unable to complete this request due to an error. - Error has been logged.” with `XMLHttpRequest` and the HTML-formatted “Internal Server Error” without the header.

**Comment by adrianbj** [comment]
Thanks @JanRomero for checking. I just tried again and it does seem to be ok. The thing that was throwing me is that it turns out if you're logged in as a superuser in your browser, a cURL call from your computer terminal detects that you are logged in because of the `wire` and `wire_challenge` cookies that are included in the cURL request. I hadn't considered those initially.
