### ISSUE TITLE
PagePaths module stops PagePathHistory module from working

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1144]
### Short description of the issue

If you have the core PagePaths module installed then the core PagePathHistory module does not record any path history when page names change.

The problem is in [this line](https://github.com/processwire/processwire/blob/00de278dc790e7714ff4c021d1c1b0ff998959e9/wire/modules/PagePathHistory.module#L167) of PagePathHistory::addPathHistory():

```php
if($this->wire('pages')->count("path=$path")) return false;
```

This always returns false because PagePaths has already added the new path for the page in question.

I thought it might be possible to solve this with hook priority settings but I had no success with this, either by setting higher priority numbers for the hooks in PagePaths or lower priority numbers for the hooks in PagePathHistory.

So I think the line above needs to test that the new path doesn't exist for any pages _besides the page that the history is being added for_.

~~Assuming that it's never possible to have more than one page with the same path, something like this:~~

```php
$existing = $this->wire('pages')->findIDs("path=$path");
if($existing && $existing[0] !== $page->id) return false;
```

Edit: this is simpler...

```php
if($this->wire('pages')->count("path=$path, id!=$page->id")) return false;
```

### Setup/Environment

* ProcessWire version: 3.0.151

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed the fix
