### ISSUE TITLE
Extends-Selector crashes with FieldtypeFile in 3.0.153-dev

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1147]
### Short description of the issue

After updating to PW version 3.0.153-dev (as of April 16, 2020), my search no longer works, which makes use of the ".extends" function. But this is only the case with selectors of the type "FieldtypeFile". Here a example selector: 

```php
$search .= // ... many other selectors
$search .= "(content.FieldtypeFile.extends%=demo),";
$search .= // ... and so on
```
The result is: 
![screenshot-localhost-2020 04 16-12_17_20](https://user-images.githubusercontent.com/708183/79445004-4081c300-7fdc-11ea-9644-0a2ea85f6f15.png)

Before the update there were no problems.

### Setup/Environment

* ProcessWire version: 3.0.153 (April 16)
* (Optional) PHP version: 7.4.x

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia I've attempted a fix for this issue, but your query looks potentially more complex than my test cases (and I don't see your entire selector) so can you double check that this also fixes it there? Thanks.

**Comment by flipzoom** [comment]
Works, thanks.
