### ISSUE TITLE
Image field ignores maximum allowed files

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1148]
### Short description of the issue

In PW-DEV version 3.0.153 (as of April 16), the check for "Maximum files allowed" in image fields is ignored after an image has been replaced and the page is saved. The result is that after saving, there are 2 images in the image field, even if only one is allowed.

### Expected behavior

If only one image is allowed, remove the old one and use the new one.

### Actual behavior

After saving the page, two images are present.

### Optional: Screenshots/Links that demonstrate the issue

Here is a screencast: https://github.com/FlipZoomMedia/RepoAssets/raw/master/Screencasts/screencast-localhost-2020.04.16-13_01_11.mp4

### Setup/Environment

* ProcessWire version: 3.0.153 (April 16)
* (Optional) PHP version: 7.4.x

**Comment by BernhardBaumrock** [comment]
Here's the screencast of my double-posted issue:
![img](https://user-images.githubusercontent.com/8488586/79860610-3ba18280-83d3-11ea-821a-3e1921bde3e4.gif)

**Comment by cb2004** [comment]
Confirmed

**Comment by ryancramerdesign** [comment]
Thanks @FlipZoomMedia @BernhardBaumrock @cb2004 I've pushed a fix for this issue
