### ISSUE TITLE
Wrong permissions on file upload on windows

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#115]
### Short description of the issue

PHP stores the uploaded file in the folder determined by upload_tmp_dir directive in php.ini. By default this is C:\Windows\Temp directory. After the uploaded file is stored to the upload_tmp_dir, ProcessWire will then move/rename the file to the final destination directory and that doesn’t inherit destination directory’s permissions.

### Expected behavior

Correct permissions, honouring permissions set on files (assets) folder.

### Actual behavior

Wrong permissions, since chmod has no effect on windows.

### Optional: Suggestion for a possible fix

Add:

`$config->uploadTmpDir = dirname(__FILE__) . '/assets/uploads/';`

to /site/config.php on install if PHP is running on windows.

### Setup/Environment

* ProcessWire version: all versions on windows

**Comment by ryancramerdesign** [comment]
I think there are a lot of developers that develop on Windows locally, but then launch the site on a unix-based server. In fact, I'd say likely most of the Windows usage of PW is specific to development environments. If we put that in $config automatically then a Windows-specific setting will end up in places where it wasn't intended. So I'm thinking maybe detecting something at runtime is a better way to go. What do you think is the best way to accomplish that? Thanks.

**Comment by matjazpotocnik** [comment]
Yes, this is a valid point, it never crossed my mind because all of my installations are on windows. I'm not sure what would be the best way. I think that runtime decisions might be unnecessary overhead? Maybe you could just inform the user at install time that this config setting is recommended on windows?

On the other hand, what would be wrong if upload dir would be permanently set at /site/assets/uploads/? Now files are uploaded to /tmp on linux and everyone have at least read access there? Wouldn't it be more secure (in shared hosting) that files that might have sensitive information stays in inside PW installation? I know, files are not left on /tmp forever, but just in case something goes wrong. I'm not a linux user so my knowledge is very basic and I might be wrong all the way ...

**Comment by ryancramerdesign** [comment]
>  I think that runtime decisions might be unnecessary overhead? 

What about using the [PHP_OS](http://php.net/manual/en/reserved.constants.php#constant.php-os) constant? I've not used it before but maybe this would be a good case. There wouldn't be any overhead in doing that. Besides, we're talking about a pre-upload check, not really a place where I'd be too concerned about overhead, even if we needed it. I'd rather not rely on users having to remember to change config settings when moving from dev to live server.

> On the other hand, what would be wrong if upload dir would be permanently set at /site/assets/uploads/? Now files are uploaded to /tmp on linux and everyone have at least read access there? Wouldn't it be more secure (in shared hosting) that files that might have sensitive information stays in inside PW installation?

There are some good reasons to use the default PHP setting for this if I recall. It's been awhile so I can't specifically remember what they were. But I do remember adding the /site/assets/uploads/ option, using it for some time, and finding that it was better not to use it unless the default PHP setting didn't work for one reason or another. I think part of it was that some hosts don't let you override it, but with no way to determine that fact ahead of time. There was more too it too, but my memory fails me here. In any case, I don't think any of it was Windows related, so seems like a simple PHP_OS check might be suitable for this case.

**Comment by matjazpotocnik** [comment]
I also never used PHP_OS myself, but I think it could be used, something like that perhaps:

```
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') ...
if (DIRECTORY_SEPARATOR === '\\') ... //this is faster
```
I would be happy with that solution. That would also solve issue [#1652](https://github.com/ryancramerdesign/ProcessWire/issues/1652)

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/51bda526eb637f86fc56694cc85f6d5a7fba306b

Thx!
