### ISSUE TITLE
Page List Select Multiple doesn't allow selecting root page

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1151]
### Short description of the issue

First of all I'm not entirely sure if this is how it _should_ work, but when I'm using Page List Select Multiple inputfield (not sure but presumably this also applies to Page List Select), instructions on Input tab state the following (emphasis added):

> You have selected an input type that has specific requirements. Specify only the “Parent” option below when configuring “Selectable pages”. Note that the parent you specify implies the root of the tree of selectable pages. **If you want to make everything selectable, then specify nothing.**

It seems to me that I should be able to select any page (including root page) if I "specify nothing" as parent, yet doing that doesn't seem to have any noticeable difference with selecting the root page itself as parent.

The ability to select anything _including_ the root page is something I've often missed with this inputfield — I know I could achieve just that using something like autocomplete input, but in my opinion (and in my experience working with clients) Page List inputfield is often superior in terms of usability: autocomplete is only helpful if you already know the name (or some other identifying factor) of the specific page(s) you're going to select, which is often not the case.

### Expected behavior

Per the instruction I would expect not specifying a parent page to make everything selectable, and everything would include the root (home) page.

### Actual behavior

There doesn't seem to be any difference between selecting the root / home page as the parent vs. not selecting a parent at all.

### Setup/Environment

* ProcessWire version: 3.0.148
* (Optional) PHP version: 7.2

**Comment by Toutouwai** [comment]
> Per the instruction I would expect not specifying a parent page to make everything selectable, and everything would include the root (home) page.

If I understand right, this does already work. If you _don't_ specify a parent then every page in the site is selectable, including the Home page. This works for both PageListSelect and PageListSelectMultiple.

![2020-04-17_100136](https://user-images.githubusercontent.com/1538852/79511075-afb9ee80-8092-11ea-9cbb-60ebbe02b014.jpg)


I think perhaps the issue is that if you _do_ specify a parent then that parent is not selectable in the inputfield - you can only select descendants of the parent page.

**Comment by teppokoivula** [comment]
> I think perhaps the issue is that if you do specify a parent then that parent is not selectable in the inputfield - you can only select descendants of the parent page.

This is interesting — for me the problem is exactly that if I _don't_ select a parent at all, it _still_ behaves exactly the same as if I'd selected "Home" as the parent, i.e. Home itself never becomes selectable. Here's a screenshot of all the settings I have on Input tab — collapsed inputs are empty:

<img width="1583" alt="Screenshot 2020-04-17 at 8 10 22" src="https://user-images.githubusercontent.com/1252021/79534379-12a38980-8083-11ea-8b1b-a054ea91a535.png">

In your screenshot Home is clearly selectable, so there must be some difference here. Just in case I'll give this a try in a completely blank install and see how that goes :)

**Comment by ryancramerdesign** [comment]
@teppokoivula I am also unable to duplicate this one, and Home is selectable for me like in Toutouwai's screenshot. I'm wondering if maybe some setting is stuck in the field configuration or something. You might try using the Fields > Export to have a closer look in the JSON to see if you can spot anything in there (or paste into here).

**Comment by teppokoivula** [comment]
Thanks, Ryan! I'm going to give this another try soon(ish). It's not an active issue anymore and seems to work for others, so definitely not a high priority thing.

I've made a note about this behaviour before as well, but that was in a completely different environment, so not sure if it's related. I'll try to reproduce this on one of my own setups next.

**Comment by teppokoivula** [comment]
This is the same issue as https://github.com/processwire/processwire-issues/issues/1239. To summarise: if the page with the page reference field has children, "home" doesn't show up — but if there are no children then "home" _does_ show up.

**Comment by kevinvermeersch** [comment]
@teppokoivula: Adding "showRootPage: true" in wire/modules/Inputfield/InputfieldPageListSelect/InputfieldPageListSelect.js should fix this issue.

https://github.com/kevinvermeersch/processwire/commit/e3e9077b785d0fa4062f1a585d1fdec0d43d435e

**Comment by neeltjechanterie** [comment]
> @teppokoivula: Adding "showRootPage: true" in wire/modules/Inputfield/InputfieldPageListSelect/InputfieldPageListSelect.js should fix this issue.
> 
> [kevinvermeersch/processwire@e3e9077](https://github.com/kevinvermeersch/processwire/commit/e3e9077b785d0fa4062f1a585d1fdec0d43d435e)

@teppokoivula I can confirm that kevin's solution works, he is my co-worker and I've tested it on my project.

**Comment by kevinvermeersch** [comment]
A little background on the issue:  The ProcessPageEdit.module overwrites the default "showRootPage" option when the current page has children.

https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L1102

**Comment by teppokoivula** [comment]
This was resolved in https://github.com/processwire/processwire/commit/ee4c46a442f09cf81f9e1800c5fdfcd1176f538a. Thank you @kevinvermeersch for pinpointing the problem! :)
