### ISSUE TITLE
New Image Fieldtype SQL Error on german locale

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1155]
### Short description of the issue

Uploading images failed today for a user with a german locale. Thx to the help of adrian I found out that the system tried to store the ratio as `1,33` (german comma) instead of `1.33` (english dot).

### Optional: Screenshots/Links that demonstrate the issue

> SQLSTATE[01000]: Warning: 1265 Data truncated for column 'ratio' at row 1

This is the error I get.

### Optional: Suggestion for a possible fix

Changing [this line](https://github.com/processwire/processwire/blob/dde4c92b784b3d89ef36fa3a731081b10e50422d/wire/modules/Fieldtype/FieldtypeImage.module#L141) makes sure the DB receives a number formatted with DOT and fixes the issue:

```
$item['ratio'] = number_format($pagefile->ratio, 2, '.', '');
```

### Setup/Environment

* (Optional) MySQL version: MariaDB 10.2.31

**Comment by kongondo** [comment]
Similar report [here](https://processwire.com/talk/topic/23560-strange-error-uploading-image-sqlstate01000-warning-1265-data-truncated-for-column-ratio-at-row-1/).

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed your suggested fix for this.
