### ISSUE TITLE
Image field with maxFiles=1 shows multiple files

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1156]
### Short description of the issue

![img](https://user-images.githubusercontent.com/8488586/79860610-3ba18280-83d3-11ea-821a-3e1921bde3e4.gif)

### Expected behavior

The image should be replaced

### Actual behaviour

First the image gets replaced, but after save it recovers all previously uploaded images.

### Steps to reproduce the issue

1. Create an image field
2. Set Maximum Files allowed to 1
3. Replace an existing image

### Setup/Environment

* ProcessWire version: 3.0.153 dev

**Comment by flipzoom** [comment]
I already opened it as a ticket. 🤙
[#1148 ](https://github.com/processwire/processwire-issues/issues/1148)

**Comment by BernhardBaumrock** [comment]
Thx, missed that!
