### ISSUE TITLE
Restoring trashed page from "Restore" tab does not trigger Pages::restored() hook

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1157]
### Short description of the issue

I have the following hooks in /site/ready.php:

```php
$pages->addHookAfter('restore', function(HookEvent $event) {
    bd('restore');
});

$pages->addHookAfter('restored', function(HookEvent $event) {
    bd('restored');
});
```

If I restore a trashed page from Page List then both hooks fire as expected:

![restore-1](https://user-images.githubusercontent.com/1538852/79861220-260a7800-8428-11ea-9d8e-4f17aab7ccd4.gif)

But if I open the trashed page for editing and restore it via the "Restore" tab then the hook to Pages::restored() does not fire.

![restore-2](https://user-images.githubusercontent.com/1538852/79861357-65d15f80-8428-11ea-9acb-1f81978ca093.gif)

### Expected behavior

Hooks to Pages::restored() fire regardless of how the page is restored.

### Setup/Environment

* ProcessWire version: 3.0.153

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.
