### ISSUE TITLE
Page Reference field - unpublished pages showing up in frontend

### ISSUE THREAD

**Issue by Jonatan-r** [processwire/processwire-issues#1159]
Using Page Reference type fields with the option to allow unpublished pages activated, the expected behaviour is that the unpublished pages are only selectable in the backend when logged in, but doesn't actually appear on the frontend, as the options description also states.

The issue is that unpublished pages actually do show up in the frontend.

Please see this PW forum thread for further reference: [https://processwire.com/talk/topic/23539-page-reference-field-unpublished-pages-showing-up-in-frontend/]

The bug has kindly been confirmed by PW forum user @kongondo 

Thanks :) 

(latest PW, PHP, MySQL ver)

**Comment by kongondo** [comment]
I can confirm I was able to reproduce this bug.

**Comment by ryancramerdesign** [comment]
Thanks @Jonatan-r @kongondo I've pushed a fix for this one. Though I'm suspicious I'm going to get another issue report in a week or two saying that unpublished pages stopped showing up where they used to, so we'll see. :) But I don't think they should be showing up in the formatted value at all, per your issue report, so I think that's the correct behavior. They should continue appearing in the unformatted front-end value though.

**Comment by Jonatan-r** [comment]
Thanks @ryancramerdesign! 😄
