### ISSUE TITLE
FieldtypePage settings template_id unable to clear

### ISSUE THREAD

**Issue by Rayden** [processwire/processwire-issues#116]
### Short description of the issue

When configuring a FieldtypePage field it is impossible to undo (clear) the **Template of selectable page(s)** `template_id` value, once it has a value.

### Expected behavior

- `template_id` = **Template of selectable page(s)**
- `template_ids` = **Need more tempaltes? Select them here**

After saving a FieldtypePage field containing a `template_id` and clearing the field by selecting the empty value, and also removing the selected template from the `template_ids` field. Both fields should return empty after saving the field.

### Actual behavior

After removing the selected template from both `template_id` and `template_ids` field and saving the field, it does not clear the field. Instead it returns the assigned template id. Making it impossible to clear the field(s).

### Steps to reproduce the issue

1. Create a field of the type Page Reference (FieldtypePage)
2. On the **Details** tab leave **Dereference in API as** `derefAsPage` on 'Multiple pages (PageArray)'
3. On the **Input** tab select 'basic-page' for the field `template_id`
4. Save the field
5. On the **Input** tab remove the 'basic-page' value for the `template_ids` field
6. On the **Input** tab select the empty value for the `template_id` field
7. Save the field again

(skipping step 5 will also give the same result)

### Setup/Environment

* ProcessWire version: 3.0.44
* (Optional) PHP version: 5.5.8

**Comment by ryancramerdesign** [comment]
Thanks for the report. I was able to duplicate and fix this, so the current dev branch should have it fixed. Thanks.
