### ISSUE TITLE
Import of fields / templates fails without error message

### ISSUE THREAD

**Issue by WebWorkingMan** [processwire/processwire-issues#1163]
### Import not working

When you try to import fields or templates this will not work under certain circumstances.

### Expected behavior

See here: https://processwire.com/talk/topic/23515-import-of-fields-fails-without-error/

I'm trying to import some fields to a mirrored PW site with same version (3.0.153). The import stops without any error message. 

### Actual behavior

Fields are not imported. See attached video.

### Optional: Screenshots/Links that demonstrate the issue

https://s3.us-west-2.amazonaws.com/processwire-forums/monthly_2020_04/import_fields_fails.mp4.f25d9911bcc3e44d6fbe05b5ebca3866.mp4

### Optional: Suggestion for a possible fix

I figured out, that this only happens, when the last trailing slash " / " is not present.

At least there should be a error message or better just work without the trailing slash.

### Steps to reproduce the issue

1.  try to import a field via /cms/setup/field/import
2. Make sure to to forget trailing slash

### Setup/Environment

ProcessWire 3.0.153 dev © 2020 and earlier

**Comment by ryancramerdesign** [comment]
@DV-JF I can't seem to locate the link that lacks the trailing slash. Where are you arriving onto that import page without a trailing slash? Sounds like an easy fix once I know where it is. PW admin uses trailing slash for most cases, but there are a few where it also requires no trailing slash, so it is careful to render links for the right context, but it sounds like I may have missed one somewhere.

**Comment by matjazpotocnik** [comment]
@WebWorkingMan, I can't replicate this. Can you provide more information? The links on the Import and Export buttons at the bottom of the fields page have the trailing slash.

**Comment by netcarver** [comment]
@WebWorkingMan   Closing this as inactive - mention me if you need it reopening.
