### ISSUE TITLE
PHP 7.4: /wire/modules/Image/ImageSizerEngineAnimatedGif/gif_encoder.php throws deprecation warning

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#1164]
### Short description of the issue

PHP 7.4 throws a lot of deprecation warning when ImageSizerEngineAnimatedGif is used, for example:
"Deprecated: Array and string offset access syntax with curly braces is deprecated in /wire/modules/Image/ImageSizerEngineAnimatedGif/gif_encoder.php on line 104"

The file gif_encoder.php is a third party file and as old as a stone. I was not able to find a newer version which does not use curly braces, but I guess it's just a matter of tools - for example, VS Code with some php plugin repairs that issue automatically.

Some generic info about the warnings:
https://wiki.php.net/rfc/deprecate_curly_braces_array_access

* ProcessWire version: 3.0.155
* PHP version: 7.4

**Comment by ryancramerdesign** [comment]
Thanks @processwired  I think those gif_encoder/decoder.php files might have the most difficult to read PHP code I've ever seen. I don't mean bad code, I just mean very technical, looks like a different language almost. I think I've successfully converted all of the curly brace arrays to square brace arrays, but it's a little hard to tell what's what so I'm hoping I didn't screw anything up in there.

**Comment by netcarver** [comment]
@processwired Can this be closed now?
