### ISSUE TITLE
Comments showing to admin users with no indication that they are not approved

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1165]
### Short description of the issue

When viewing the frontend of a site, all comments are rendered, regardless of whether they have been approved or not and there is no indicator if a comment isn't approved. This makes it confusing because you don't realize that no-one else can see it.

### Expected behavior

Either an admin users shouldn't be able to see a comment if it isn't approved, or there should be some sort of flag to let you know that it's not approved.

I am getting OT, but I also wonder if it would be possible for comments written by users with certain roles to be automatically approved. It's confusing for site editors to write a comment and then have to approve their own comment.

Thanks.

**Comment by ryancramerdesign** [comment]
@adrianbj Strangely I can't duplicate this one, but am able to see how it could occur stepping through the code. I think it may be that it can only occur when depth is disabled, but not positive. Either way, I think I've corrected the issue, but please let me know if not. The intention is that admin users only see unapproved comments if the 'admin' option is specified for the comment list, and I'm assuming it isn't in your case.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - those changes do fix the problem, except for the number of comments counter which is generated by `$page->comments->count()` - this still includes the pending message in the count. It would be nice if this returned just the count of approved comments like it does for guest users.

Or maybe showing the total number is correct for comment admin users? Not sure.
