### ISSUE TITLE
Can't uninstall module

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1168]
I'm developing a module and using it on several sites.  On some sites, I can't uninstall it.  When I uninstall, the notices say that it uninstalled, but then it also immediately re-installs (my installation function has various notices of things during the install process).

I tried the following without luck:
- bumping up the version and uninstalling, reinstalling
- removing the code from "install", refreshing module cache, then uninstalling
- removing various bits of code, refreshing module cache, then uninstalling

What could be the issue?  Any tips of how to forcefully uninstall?

**Comment by adrianbj** [comment]
> Any tips of how to forcefully uninstall?

Just remove the files and the row from the `modules` DB table. This generally works just fine for individual modules without dependencies, although the core Notices module doesn't always give in that easily - it's very difficult to uninstall :)

**Comment by jlahijani** [comment]
@adrianbj Any idea how I can get it to stop auto-installing?  Have you had this issue before?

**Comment by adrianbj** [comment]
Making a call to `$modules->get('modueName')` will install it, so perhaps that is the problem?

**Comment by jlahijani** [comment]
Yes... that was it.  I knew that happens, but wasn't thinking about it in a different context.  Thank you!
