### ISSUE TITLE
InputfieldCKEditor.module: "+" sign should be trimmed when getting config from ProcessPageEditLink

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1169]
### Short description of the issue

The "+" sign is not trimmed when getting config for the purifier from ProcessPageEditLink. This causes target and rel attributes to be removed from the CKEditor contents on save.

The "+" sign is added by recommendation: `Enter one attribute value per line. The user will be able to select these as options when adding links. To make an option selected by default (for new links), precede it with a plus "+".`

### Expected behavior

The "+" sign should be trimmed.

### Optional: Suggestion for a possible fix

Change [this line](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldCKEditor/InputfieldCKEditor.module#L572) to trim "+" value.

### Setup/Environment

* ProcessWire version: 3.0.153

**Comment by ryancramerdesign** [comment]
Thanks @ivangretsky I've pushed your suggested fix for this.
