### ISSUE TITLE
Weird HTML entities behavior in repeater item labels

### ISSUE THREAD

**Issue by CalleRosa40** [processwire/processwire-issues#117]
### Short description of the issue

Uppercase umlaut HTML entities (`&Ouml;` / `&Auml;` / `&Uuml;`) are displayed in repeater item label. The label is pulled from a page's default title field (HTML Entity Encoder text formatter is set). Page is added to repeater via Page field set to "single page".

### Expected behavior

Entities should be converted to the actual characters: ÄÖÜ.

### Actual behavior

Screenshot:
![grafik](https://cloud.githubusercontent.com/assets/24602813/21258425/41a593de-c37d-11e6-97ae-635fc9595a6c.png)

However, there's more ... If the page's title contains ä, ö, ü or ß, _all_ umlauts are displayed correctly. Just one of these characters suffices to fix all other characters.

Screenshot (notice the final "ß"):
![grafik](https://cloud.githubusercontent.com/assets/24602813/21258550/d6f94cf0-c37d-11e6-8fc8-116430d38e92.png)

* ProcessWire version: 3.0.42

**Comment by kixe** [comment]
The regex in class Inputfield should detect uppercase letters too
https://github.com/processwire/processwire/blob/dev/wire/core/Inputfield.php#L1550
solution: change to:
`if(strpos($str, '&') !== false && preg_match('/&(#\d+|[a-zA-Z]+);/', $str)) {`

**Comment by ryancramerdesign** [comment]
Thanks I've pushed the suggested fix for this issue to the dev branch. Note that if you are literally inserting HTML entities like `&Ouml;` into your repeater label, make sure you use the actual character `Ö` instead, as typing in literal HTML entities in anything in the admin is likely going to result in it getting double-encoded in most cases.
