### ISSUE TITLE
Extended file and image properties feature causes errors with existing site profiles

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1171]
### Short description of the issue

The new [expanded file and image field properties](https://processwire.com/blog/posts/processwire-updates-and-additions-in-progress/#expanded-file-and-image-field-properties) feature causes SQL errors for existing site profiles that contain image fields. I expect file fields are also affected but I didn't test this.

I've created a simple site profile using PW 3.0.148 to demonstrate the issue. This profile is based on the core "blank" profile, but has an images field added to the "home" and "basic-pages" template. TracyDebugger and ProcessDatabaseBackups are installed to aid with debugging.

[site-test-profile.zip](https://github.com/processwire/processwire-issues/files/4625348/site-test-profile.zip)

To reproduce the issues, install PW 3.0.155 and select "Test profile" during installation.

Two ways the errors can manifest:

1\. When attempting to get the value of an images field an SQL error is thrown.

![2020-05-14_120546](https://user-images.githubusercontent.com/1538852/81878474-461ef880-95dc-11ea-8ad7-cb0d538da557.png)

2\. When creating a new page using a template that contains an images field several errors appear in admin.

![2020-05-14_120625](https://user-images.githubusercontent.com/1538852/81878551-7f576880-95dc-11ea-8e7b-c007fb2a3fe9.png)

Note that you only get one chance to see either of these errors: after that the database schema is updated and the errors don't occur. During debugging I used ProcessDatabaseBackups to create a DB backup immediately after install so I could return to the original state.

### Optional: Suggestion for a possible fix

Perhaps there needs to be some routine as part of the core upgrade to >= PW 3.0.154 that updates the database schema for all file and image fields rather than using the Fieldtype modules which seem not to be able to update the schema before these errors are thrown.

### Setup/Environment

* ProcessWire version: 3.0.155

**Comment by BernhardBaumrock** [comment]
I've seen those "page with same parent is already using name ..." errors quite often lately but had no time to investigate... I'll pay more attention from now on!

**Comment by flipzoom** [comment]
I had the same problem after a direct update from 3.0.153 to 3.0.156. I noticed that for image fields that are currently not used or have no data in the DB, the DB schema is not updated. This then results in the error described above. That the new columns are not available. 

I have currently adjusted this manually in the database to make it work. Just search the image field tables which do not contain the new columns like width, height and ration. And with the following SQL, I have added the new columns and indexes. 

```SQL
ALTER TABLE `field_YOUR_IMAGE_FIELD_TABLE_NAME`
  ADD COLUMN `filesize` int(11) DEFAULT NULL,
  ADD COLUMN `created_users_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  ADD COLUMN `modified_users_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  ADD COLUMN `width` int(11) DEFAULT NULL,
  ADD COLUMN `height` int(11) DEFAULT NULL,
  ADD COLUMN `ratio` decimal(4,2) DEFAULT NULL,
  ADD KEY `filesize` (`filesize`),
  ADD KEY `width` (`width`),
  ADD KEY `height` (`height`),
  ADD KEY `ratio` (`ratio`);
```

Note: the table name has to be adjusted and done for each image field which has not yet been updated. Plus: no guarantee for this and please make a backup before. This worked for me.

**Comment by ryancramerdesign** [comment]
@Toutouwai I installed your test profile. While I didn't get the "Another page with same parent..." error message that you did when creating a page named "test", I did get the error about the images field after creating the new "test" page. However, it immediately fixed itself, which is what it's supposed to do. I also confirmed it properly updated the table automatically with the new columns. One difference I also noticed is that the error I observed was in ProcessPageEdit, not in ProcessPageAdd like in your screenshot. It should not be necessary to manually adjust anything, as this table update is supposed to be self healing. Did you find the issue did not self-heal and continued to appear every time you created a new page? cc: @FlipZoomMedia 

<img width="974" alt="Screen Shot 2020-07-30 at 3 20 41 PM" src="https://user-images.githubusercontent.com/328272/88965644-0c739a80-d279-11ea-8f11-8fc8c0f5acae.png">

**Comment by Toutouwai** [comment]
@ryancramerdesign, I just tested some more and found that this issue doesn't just affect site profiles. It affects any site that is upgraded to a PW version after the extended file and image properties were added.

So if I have a site running PW 3.0.148, I upgrade it to PW 3.0.162, and then some API code like this executes...

```php
$foo = $pages(1)->images;
// more code...
```

...then I get "Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_images.modified_users_id' in 'field list' on line: 166 in ...\wire\core\WireDatabasePDOStatement.php". 

So that code is not going to execute due to the exception, which depending on what the code is doing might cause a significant problem. And I guess this is going to happen once for every Files and Images field? Even though the table is fixed after this one exception, it's one exception more than is ideal  :-)

Isn't there some way to update the affected tables when the PW upgrade occurs?

**Comment by ryancramerdesign** [comment]
@Toutouwai Hitting reload till all messages, warnings and errors are cleared has long been part of the update process in PW, but I understand this particular one is confusing. It might lead folks to think there is a problem, they need to revert, or they did something wrong, etc., which we don't want. So if we can suppress the error part from appearing, we should; and in this case I think we can. I've suppressed the temporary error message behind a system update (18), which seems to resolve it here. Can you confirm it also resolves the issue there? Thanks.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, that fixes it.
