### ISSUE TITLE
FieldtypeOptions: options are retained in the fieldtype_options table after the related field has been deleted

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1172]
### Short description of the issue

FieldtypeOptions: options are retained in the fieldtype_options table after the related field has been deleted.

### Expected behavior

After deleting a field of type Select Options the related entry in the db should be deleted.

**Comment by ryancramerdesign** [comment]
Thanks @kixe good find, I've pushed a fix for this issue.

**Comment by kixe** [comment]
Thanks for the fix
