### ISSUE TITLE
Renaming a fieldset doesn't rename its corresponding _END field

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1175]
This one goes back to 2016: 
https://github.com/ryancramerdesign/ProcessWire/issues/1854

Just want to make sure it isn't lost forever :)

**Comment by rogersarrasin** [comment]
Oh, that's funny!

Yes, I've experienced the same.

Roger


On May 20, 2020 at 10:19:33 AM, Adrian Jones (notifications@github.com) wrote:

This one goes back to 2016:
ryancramerdesign/ProcessWire#1854

Just want to make sure it isn't lost forever :)

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue

**Comment by adrianbj** [comment]
Great thanks!
