### ISSUE TITLE
Page::changed hook: `$old` contains same value as `$new` for MultiLanguage fields

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#1177]
### Short description of the issue

Something seems off with how MultiLanguage fields are handled. When hooking into Page::changed the method is called twice. The first time $old and $new are the same, the second time $old and $new are both null.

### Code snippet

~~~php
wire()->addHookAfter('Page::changed(body)', function(HookEvent $e) {
    /* @var $old LanguagesPageFieldValue */
    $what = $e->arguments('what');
    $old = $e->arguments('old');
    $new = $e->arguments('new');

    bd($old, 'old'); // TracyDebugger is required for this function
    bd($new, 'new');
});
~~~

### Expected behavior

The hooked method is just called once and $old contains the value before the change.

### Actual behavior

The hooked method is called twice and with wrong arguments.

### Screenshots/Links that demonstrate the issue

![grafik](https://user-images.githubusercontent.com/17496592/82832935-e0c0e680-9ebc-11ea-9420-332b93e3c457.png)

### Steps to reproduce the issue

1. Hook into Page::changed for a multilingual field, e.g. with  the code snippet posted above
2. Log in to the backend and edit a page that contains the multilingual field

### Setup/Environment

* ProcessWire version: 3.0.148 and 3.0.153
* PHP version: 7.4.4
* MySQL version:  5.7.24
* Any 3rd party modules that are installed and could be related to the issue:  I tried it in two installations, it occurred in both. The only module that was present in both was TracyDebugger, but the error occurred with Tracy being disabled too.

**Comment by ryancramerdesign** [comment]
@MrSnoozles The "old" and "new" are not used with all change events, but they are going to be the same in this case because a Multi-language value is an object (LanguagesPageFieldValue), and the object is the same instance. So the object hasn't changed, but a field within it has. What you are looking for is likely the changed event on the LanguagesPageFieldValue. Not 100% positive on why it's getting called twice without confirming (I can have a closer look), but do know that it's not unusual when objects are used because the object may notify the Page of the change, but the Page may also detect it on its own, depending on the case.

**Comment by MrSnoozles** [comment]
@ryancramerdesign Thanks for the info. It's not really intuitive though and I think something that can certainly be improved. I did some debugging and found the following:

1. As you said objects are worked on by reference, so $old and $new is the same instance. This could be improved in ProcessPageEdit.module around line 2330 if we're working on a clone of the instance instead of the instance itself. Then $old would be the old instance and $new the new instance with the new value. I don't know if it has any other side effect though. As far as I have tested everything still seems to work as intended.

~~~php
$v = $this->page->get($name); 
if(is_object($v)) {
	$v = clone $v;  // this would be the only line to be added
	$v->setFromInputfield($inputfield); 
	$this->page->set($name, $v); 
	$this->page->trackChange($name); 
} else {
	$this->page->set($name, $inputfield->value); 
}
~~~

2. As for why it's called twice I couldn't yet figure out why exactly that occurs but if I remove the `trackChange` call in the is_object() block it works correctly.

~~~php
$v = $this->page->get($name); 
if(is_object($v)) {
	$v = clone $v;  // this would be the only line to be added
	$v->setFromInputfield($inputfield); 
	$this->page->set($name, $v); 
	// $this->page->trackChange($name);  // when I remove this line Page::changed is only called once
} else {
	$this->page->set($name, $inputfield->value); 
}
~~~

**Comment by MrSnoozles** [comment]
I created a new PR to fix this issue, at it's still impossible to use hooks to get what the old value was when a MultiLanguage field has been updated in the backend.

https://github.com/processwire/processwire/pull/186 fixes this issue

**Comment by ryancramerdesign** [comment]
Closing since the mentioned PR was added.
