### ISSUE TITLE
 Ajax repeater - wrong language field active

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#1179]
### Requirements:
- Repeater (matrix & normal) with mutlilanguage fields (text, textarea…) 
- Backend language set to something other than default (ie. German) 

### Reproduce:

- Add a new repeater Item (ajax, I found no way to possible to disable it with matrix)

(Notice how the default language tab is active instead of the backend language…)

- Write something into the (default language) field
- Try to save, if field is required, this will not work. If not required, then when reloading, the content will be inside the backend language field, instead of the default language field who was (presumably) active

### Analysis:

When  loading  a new repeater element with ajax, the default langue tab is active, but the backend language inputfield is visible (with no visual indication). When writing into the field, it will populate the backend language. When manually clicking on the default language tab (which is already active), the field will switch to the actual default language field (which is [now] empty) (that can now be populated…)

Also Notice, the labels of the elements to be added are in default language as well instead of the translated label (images instead of Bilder)…

ProcessWire 3.0.148, Profields 0.0.5…

Is it my system configuration, or does anyone else have the same issue? This is a screen recording of the problem:

Screencast bug in action:
https://s3.us-west-2.amazonaws.com/processwire-forums/monthly_2020_02/409845907_ScreenRecording2020-02-25at14_18_31.mov.e6c0812415546857cd2f28ae6307576b.mov

**Comment by ryancramerdesign** [comment]
Thanks @noelboss I've pushed an attempted fix for this issue. I was able to duplicate the first thing you mentioned but not the second. I found that adding a slight delay to the tabs initialization enabled it to work and select the correct language tab rather than staying on the default language tab. I think this only occurs in Uikit. Please let me know if you are still experiencing the issue.

**Comment by netcarver** [comment]
@noelboss Did Ryan's update work for you?  Can we close this issue now?

**Comment by netcarver** [comment]
@noelboss Post again if this needs more attention.
