### ISSUE TITLE
SQLSTATE[HY000]: General error: 1100 Table 'pages' was not locked with LOCK TABLES

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1181]
When saving a page with a paginated Table field I get the above error for PW 3.0.153 - 3.0157

If I switch to a non-paginated table, it's OK, or if I revert to 3.0.152, it is also OK.

I have experienced this error on these two MySQL versions on two different servers:

Server 1: 8.0.19
Server 2: 5.5.5-10.3.22-MariaDB-0+deb10u1

I don't have any ideas for a fix at the moment - I would need to go back through all the commits between 152 and 153, but hopefully you'll have an idea pretty quickly.

Please let me know if you need any other info.

**Comment by ryancramerdesign** [comment]
@adrianbj This week I did a refactor of the FieldtypeMulti class, which is in 3.0.158 and if the issue is what I think it is, it should fix this. Please let me know if you find the issue persists.

**Comment by adrianbj** [comment]
Indeed, that does fix it - thanks!
