### ISSUE TITLE
Cannot add new pages with permission page-edit-created

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1182]
### Short description of the issue

If a user role has the permission page-edit-created it is not possible to add new pages.

### Expected behavior

You should be able to add new pages if the access allows it.

### Actual behavior

Exception gets thrown:
*ProcessWire: ProcessPageAdd: You don't have access to the template required to add pages here*

### Optional: Screenshots/Links that demonstrate the issue

![Template posts family](https://user-images.githubusercontent.com/2794879/83111338-b6da1080-a0c4-11ea-9877-898b5d8eed59.png)
![Template posts access](https://user-images.githubusercontent.com/2794879/83111335-b6417a00-a0c4-11ea-80a8-3a7643ee02b6.png)
![Template post family](https://user-images.githubusercontent.com/2794879/83111334-b6417a00-a0c4-11ea-81d0-788829efd427.png)
![User role employee](https://user-images.githubusercontent.com/2794879/83111710-4d0e3680-a0c5-11ea-81e8-12001beea8ec.png)
![Exception](https://user-images.githubusercontent.com/2794879/83111317-b17cc600-a0c4-11ea-8a46-234571e44101.png)

### Steps to reproduce the issue

1. Create templates
2. Create user role
3. Install permission page-edit-created
4. Add permission to user role

### Setup/Environment

* ProcessWire version: 3.0.148
* PHP version: 7.4.2
* MySQL version: 5.7.26

**Comment by ryancramerdesign** [comment]
@designconcepts For this kind of access control scenario, you want to enable access control on both the "posts" and "post" templates. You've got it for "posts", but it looks to me like you need to enable access control on your "post" (singular) template and then check the boxes for "edit" and "create" for your intended (roles) on that template. Optional, but on the "posts" template, you may also want to uncheck the "edit" and "create", and instead just have "add children" checked.

**Comment by designconcepts** [comment]
Thank you for your answer. This way it works.

I had a special use case, where this permission had a conflict:

* Editor A should only be able to add and edit posts as children of A and C
* Editor B should only be able to add and edit posts as children of B and C
* Employees should only be able to add and edit own posts as children of C

So I had created three parent templates:

* Posts A
* Posts B
* Posts C

And all of them can have child templates of "post".

Then I made three roles:

* editor-a
* editor-b
* employee

So the issue with this setup is, that with the right access controls Editor A and Editor B are able to edit all posts everywhere.
But if I restrict the access, employees couldn't add posts like above.

I hope this is not too confusing, but this was my initial issue with this permission. But I think this case is very rare, so I leave it.

Regards, Andreas
