### ISSUE TITLE
CkEditor background overlay blocks source editing in modal

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#1183]
### Short description of the issue

I routinely check the HTML produced by CkEditor using the "Source" button. It's no longer possible after PW 3.0.154's update of CkEditor to 4.14.0: a "cke_dialog_background_cover" class applies a fixed position and absurdly high z-index value that covers the whole screen, and prevents ANY interaction, including escaping or saving our work. The only solution is to open up the devtools and delete that class to regain interactivity. It's incredibly frustrating and a productivity killer for me.

### Expected behavior

The background overlay should not cover the modals. 

### Actual behavior

The background overlay class blocks all interaction with the page. 

### Optional: Screenshots/Links that demonstrate the issue

![source](https://user-images.githubusercontent.com/1206842/83136246-7344ce00-a0e7-11ea-90fa-ec961b9ed302.png)

![background-cover](https://user-images.githubusercontent.com/1206842/83136265-78a21880-a0e7-11ea-898e-417947e51bdd.png)

**Comment by tbba** [comment]
THere is a known issue with the AOS (adminOnSteroids) module where this high z-index value appears to be coming from. 

Temporarily deactivating the module before editing source in CKE helps for now. Or set the z-Index of .cke_dialog_background_cover in the module's CSS to a lower value, like 9999. That’s what I did. Does that help?

https://processwire.com/talk/topic/13389-adminonsteroids/page/50/?tab=comments#comment-202102

**Comment by jacmaes** [comment]
Thanks, @tbba. I can confirm that disabling AOS solved the issue. I'm closing this issue as it's not a core problem.
