### ISSUE TITLE
New selectorValue Function creates 404 on pages with multiple ---

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#1184]
Hi Ryan, please see:
https://github.com/processwire/processwire/commit/0543548fdd4330b0ec84bab4275e32344b53fe37#r39503419

Also, please consider using the processwire/processwire Repository for issues to streamline  collaboration to use all the handy features git and GitHub provides when issues and code are in the same repo…

**Comment by ryancramerdesign** [comment]
@noelboss I can't seem to duplicate this one, but I think it's because that function went through a few iterations around the time you posted this issue, so it was something that was probably fixed shortly after. But let me know if you are still experiencing the issue anywhere. Thanks.

**Comment by netcarver** [comment]
@noelboss Any update on this?

**Comment by netcarver** [comment]
Closing now. @noelboss Post more if this needs re-opening.
