### ISSUE TITLE
Datetime "separate selects" method shows a PHP error due to empty default value

### ISSUE THREAD

**Issue by Awesomolocity** [processwire/processwire-issues#1187]
### Short description of the issue

Using the Datetime "separate selects" method throws a PHP error when rendering.

### Expected behavior

No PHP errors to be thrown? Lol

### Actual behavior

When using the "Datetime" Inputfield, one of the input methods it allows for is "Separate select inputs for month, day, and year (and optionally time)". Unfortunately when rendering the selects out, it throws a PHP error for line 141.

"Warning: date() expects parameter 2 to be integer, string given in /wire/modules/Inputfield/InputfieldDatetime/types/InputfieldDatetimeSelect.php on line 141"

In the meantime, I've got this fixed by manually typecasting $value by throwing (int) in front of it.

### Optional: Suggestion for a possible fix

 Typecasting $value as an int could work though it seems a little hacky.

### Steps to reproduce the issue

1. Create Form in FormBuilder
2. Add a "Datetime" field
3. On the Details page for the field input, choose "Separate select inputs for month, day, and year (and optionally time)"
4. Preview the form
(This is probably the easiest and quickest way, but any method where processwire renders your field for you should work)

### Setup/Environment

* ProcessWire version: 3.0.157 dev
* PHP version: 7.2.24
* MySQL version: 5.7.29-log
* Any 3rd party modules that are installed and could be related to the issue:

**Comment by Awesomolocity** [comment]
A potentially related issue - it seems that selecting the option "Default to today's date" does nothing. I can open another issue for that if that would be preferable.

**Comment by Awesomolocity** [comment]
Just confirmed that the bug still exists on 3.0.158 dev as well

**Comment by Awesomolocity** [comment]
Solved with 3.0.159 ([Link to commit](https://github.com/processwire/processwire/commit/855cfd7370ff18965311330eed3e318c6faa457a#diff-dbd9244b6362e3cee9a069cdad0ec3fb))

**Comment by ryancramerdesign** [comment]
@Awesomolocity Thanks for the report, I fixed it when I saw your email earlier in the week. I meant to tag this issue and reply here sooner but it slipped my mind. Thanks again.
