### ISSUE TITLE
WireTabs Module - cookie warning

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1188]
The WireTabs Module in Core caused a warning in Firefox about its cookie:

The "WireTabs" cookie will soon be rejected in the future because it specifies either "none" or an invalid value for the "sameSite" attribute without using the "secure" attribute. For more information about the sameSite attribute, see https://developer.mozilla.org/docs/Web/HTTP/Cookies.

(ProcessWire 3.0.158 dev + Firefox 76.0.1 Mac)

**Comment by tbba** [comment]
closed (too old)

**Comment by adrianbj** [comment]
Sorry, what's too old? Did Ryan fix this in 3.0.159? I thought this `sameSite` attribute was something that needed to be dealt with moving forward.

**Comment by tbba** [comment]
reopened on request. :-)

**Comment by ryancramerdesign** [comment]
Thanks @tbba I have added an update that hopefully fixes this. Though I was not seeing the error for the WireTabs module in Firefox, though was seeing it for ProcessPageList, so I just applied the fix to the jquery.cookie.js module rather than individual cases.

**Comment by tbba** [comment]
Thank you!
