### ISSUE TITLE
3.0.45: new Page settings need tweaking

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#119]
### Short description of the issue
* When "Select" is chosen as the inputfield type and the field is not "Required", the "Settings specific to Select" fieldgroup is shown but there is nothing in there. The fieldgroup should be hidden when the Required option is not checked.

* For the "Default Value" option (aside: would be great to have [consistent case](https://github.com/ryancramerdesign/ProcessWire/issues/1512) applied in admin), the description says 'This default value(s) option is available because you checked the "required" box above.' The required box is now below rather than above.

* Didn't it use to be possible to set default values for other inputfield types besides Select? Now the option only seems to be available for Select.

### Optional: Screenshots/Links that demonstrate the issue

![2016-12-19_152524](https://cloud.githubusercontent.com/assets/1538852/21299341/72373758-c5ff-11e6-9e2f-719269516cce.png)
![2016-12-19_152537](https://cloud.githubusercontent.com/assets/1538852/21299342/723fa0e6-c5ff-11e6-852b-b57bc54944e9.png)

* ProcessWire version: 3.0.45

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update for this. 

> Didn't it use to be possible to set default values for other inputfield types besides Select? Now the option only seems to be available for Select.

They all support it except for the PageListSelect and PageAutocomplete types. Though if you've changed from one to another input type, you do have to hit "Save" for the option to appear.
