### ISSUE TITLE
Problem with Image Custom Fields in Repeater Matrix

### ISSUE THREAD

**Issue by robo-wg** [processwire/processwire-issues#1191]
I have an image field for multiple images (array). Furthermore I have defined custom fields (optional text and copyright) for the image field. So far it works fine. 
But if the field is located in a repeater matrix, the values of the custom fields are only saved if I

1. insert the images
2. save the page
3. fill out the custom fields

When I do this:

1. insert the images
2. fill out the custom fields
3. save the page

the entries of the custom fields are unfortunately "lost" / not saved.

However, the field entries for the description fields remain or work as expected.

**Comment by matjazpotocnik** [comment]
Possible duplicate of https://github.com/processwire/processwire-issues/issues/1070 ?

**Comment by robo-wg** [comment]
Yes, of course. Unfortunately, I didn't find this. Thanks for your advice.
