### ISSUE TITLE
@htaccessVersion 301 - activating 9A (force https) leads to "too many redirects"

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#1193]
### Short description of the issue

If I uncomment the .htaccess section 9A to force https, it leads to a "too many redirects" error on the website.

### Expected behavior

Using the 9A section of .htaccess 301 should not lead to an error.

### Optional: Suggestion for a possible fix

Using this directives instead of the existing ones works:

```
RewriteCond %{ENV:HTTPS} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

### Setup/Environment

* ProcessWire version: 3.0.159 dev

**Comment by BernhardBaumrock** [comment]
Hey @gadgetto I'm quite sure that this problem is related to your setup and not to ProcessWire itself. Maybe you have some other rule leading to an endless loop (like vhost or PW setting) - did you check that already?

**Comment by gadgetto** [comment]
Uncommenting the 9A part is the only change I made to the .htaccess file.
But the site where this happens lies in a shared host. So the problem could be related to this. But I don't find anything unusual in the admin panel of the host.

**Comment by BernhardBaumrock** [comment]
Maybe you have set some templates to "non-https"? So htaccess redirects to HTTPS and then ProcessWire redirects to HTTP...
![image](https://user-images.githubusercontent.com/8488586/84292385-9723fd00-ab46-11ea-9b54-40d3c459e1c7.png)

**Comment by gadgetto** [comment]
I have not changed any Scheme/Protocol settings in templates of this site. The "too many redirects" problem also happens in admin area.

If you have a look at my suggestion for a possible fix, you can see, that with my slightly changed version of the 9A section there is a redirect to https and it works.

**Comment by cb2004** [comment]
This is all down to the hosting setup, I have to use the same as you on some sites @gadgetto. I havent tried:

```
RewriteCond %{ENV:HTTPS} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
On a site that doesnt seem to need it to see if it still works though have you?

Not sure this could be classed as a ProcessWire issue, but could be added to the default .htaccess as an instruction to try this if the other does not work?

Having said that, you can force https at the server level which is preferable and does reduce the redirects anyway.

**Comment by ryancramerdesign** [comment]
@gadgetto, @cb2004, @BernhardBaumrock  Thanks, after researching a bit I can confirm that it sounds like a few web hosts use the ENV:HTTPS rather than HTTPS. I'm not really sure why that is, but I've updated our .htaccess to add a note about that.

**Comment by gadgetto** [comment]
Great, thanks! This will definitely save other developers several hours of debugging! :-)
