### ISSUE TITLE
Repeater clone Javascript Error

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1195]
### Short description of the issue
Cloning of Repeater item gets stuck at confirmation Message. Click on OK triggers Javascript Error `TypeError: $addLink.offset() is undefined in InputfieldRepeater.js 150:50`

### Expected behavior
Repeater item gets cloned after click on OK in confirmation message

### Actual behavior
Click on OK triggers Javascript Error `TypeError: $addLink.offset() is undefined in InputfieldRepeater.js 150:50`

### Steps to reproduce the issue
Make repeater item and try to clone it

### Setup/Environment

* ProcessWire version: 3.0.123
* (Optional) PHP version: 7.3.15
* (Optional) MySQL version: 5.0.12

**Comment by ryancramerdesign** [comment]
@gebeer I can't seem to duplicate this one. Watching my JS console but not seeing any errors. Let me know if you can think of anything else to try. Although it might just be that the version you are testing on (3.0.123) is 40 versions behind the current dev branch, so it'd be worth trying a newer version to see if that's it.

**Comment by matjazpotocnik** [comment]
@gebeer could you test on the latest dev version and report back?

**Comment by matjazpotocnik** [comment]
@gebeer I also can't duplicate it, so I'm closing this issue. Please let me know if you need it re-opening.
