### ISSUE TITLE
FieldtypeModule::getConfigInputfields - several values not set

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1196]
### Short description of the issue

After adding a translation to the configuration of the _tfa_type_ field in the configuration setup of the TFA module, I lost some settings and the module stopped working. I found out that **FieldtypeModule** does not render the current setup and overwrites 3 required values (**showNoneOption** , **instantiateModule**, **blankType**) after saving.

### Optional: Suggestion for a possible fix

For the 2 Checkbox Inputfields: **showNoneOption** and **instantiateModule** the _'checked'_ attribute must be added according to the value, otherwise the value is not rendered if 1.

`if($value) $inputfield->attr('checked', 'checked');`

The Radiobuttons Inputfied: **blankType** does not set the current value. This was mentioned already here:
https://github.com/processwire/processwire-issues/issues/1069

Please add:
`$f->attr('value', $field->get('blankType'));`

### Setup/Environment

* ProcessWire version: 3.0.159
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @kixe, good find, I've pushed a fix for this issue.

**Comment by kixe** [comment]
@ryancramerdesign Thanks. Closed.
