### ISSUE TITLE
PW 3.0157+ breaks OR group selectors with checkbox fields

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1199]
### Short description of the issue

I am using this selector:

```
ftr=(free_trial_reminder=0), ftr=(free_trial_reminder='.($currentSubscription->coupon->name == 'free-trial' ? 1 : 0).')
```
which ends up either being:
```
ftr=(free_trial_reminder=0), ftr=(free_trial_reminder=1)
```
```
ftr=(free_trial_reminder=0), ftr=(free_trial_reminder=0)
```
Both of these fail to return any results in 3.0.157 - 3.0.159, but as soon as I revert to 3.0156 they work again. 
### Expected behavior

Please let me know if you can't reproduce, or need any other info.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate it here:
~~~~~
$items = $pages->find("tf=(test_checkbox=0), tf=(test_checkbox=1),
include=all");
~~~~~
The above matches all 3600 pages in my site. I'm wondering though about
that extra single quote you've got at the end of those, before the closing
")". Is that intended in the example or a typo? Because that would likely
prevent it from working, but I'm guessing that's a typo. Any other factors
you can think of? Also, are you sure it's a checkbox and not a toggle field?

**Comment by adrianbj** [comment]
Sorry, the extra single quote was a typo.

It's definitely just a normal checkbox field.

Do you think it might be MySQL version related? Did you change anything in 3.0157 in terms of how checkbox handles null vs 0 or anything on those lines?

**Comment by adrianbj** [comment]
I just checked Tracy's Selector Queries table:


**PW 3.0156**
```
SELECT pages.id,pages.parent_id,pages.templates_id
FROM `pages`
WHERE (pages.status<1024)
AND (
pages.id IN (
SELECT pages.id
FROM `pages`
LEFT JOIN field_free_trial_reminder AS field_free_trial_reminder__blank1 ON field_free_trial_reminder__blank1.pages_id=pages.id
WHERE (((field_free_trial_reminder__blank1.pages_id IS NULL OR (field_free_trial_reminder__blank1.data='0'))))
)
OR pages.id IN (
SELECT pages.id
FROM `pages`
JOIN field_free_trial_reminder AS field_free_trial_reminder ON field_free_trial_reminder.pages_id=pages.id AND (((field_free_trial_reminder.data='1' ) ))
)
)
GROUP BY pages.id
```

**PW 3.0159**
```
SELECT pages.id,pages.parent_id,pages.templates_id
FROM `pages`
WHERE (pages.status<0)
AND (
pages.id IN (
SELECT pages.id
FROM `pages`
LEFT JOIN field_free_trial_reminder AS field_free_trial_reminder__blank1 ON field_free_trial_reminder__blank1.pages_id=pages.id
WHERE (((field_free_trial_reminder__blank1.pages_id IS NULL OR (field_free_trial_reminder__blank1.data=0))))
)
OR pages.id IN (
SELECT pages.id
FROM `pages`
JOIN field_free_trial_reminder AS field_free_trial_reminder ON field_free_trial_reminder.pages_id=pages.id AND (((field_free_trial_reminder.data='1' ) ))
)
)
GROUP BY pages.id
```

so it looks like the issue is the `WHERE (pages.status<0)`

Any ideas why that would be happening?

Adding `include=all` like you did fixes it, but why should this be necessary?

**Comment by matjazpotocnik** [comment]
I have no idea if this is important, but the difference is also here:
`field_free_trial_reminder__blank1.data='0'` vs `field_free_trial_reminder__blank1.data=0`

**Comment by adrianbj** [comment]
Nice catch @matjazpotocnik - I hadn't noticed that. But I just ran the queries with and without those single quotes and it doesn't make a difference. Seems like it's all about the `status`

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj that `status<0` was definitely it. I was testing in findAll mode, so that's why I wasn't able to duplicate it. Once I turned that off, I could duplicate and fix it.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - so far it looks to be working again.
