### ISSUE TITLE
Image Edit "Save as Copy" creates broken "empty" image

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#12]
ProcessWire 3.0.33

When editing a image using "Crop", pressing button "Save as Copy" does not work correctly but produce an empty broken image.

**Comment by ryancramerdesign** [comment]
I'm using this feature almost every day with the site I'm working with now, and just tested it now again. I can't duplicate this one. Can anyone else duplicate?

**Comment by somatonic** [comment]
It seems everybody else except you :)

https://processwire.com/talk/topic/11224-media-manager/?do=findComment&comment=129283
https://processwire.com/talk/topic/11224-media-manager/?do=findComment&comment=129287

**Comment by ryancramerdesign** [comment]
I'm still not clear on how to reproduce the issue. Looking at that thread, it appears the issue occurs when that MediaManager module is installed? Or is it when trying to crop an image that was just uploaded, but before page was saved? Can you clarify what steps are necessary to reproduce the issue? Thanks.

**Comment by somatonic** [comment]
No it has nothing to do with MediaManager. I tested on my local 3.0.33 clean install. It even happens on my other 2.7.3 clean install.

Steps are as mentioned. And you can see it exactly as in Kongondo's screencapture video...

1. Edit image by clicking "Crop" so the modal opens
2. Do nothing
3. Click "Save as Copy"
4. See a new but broken image added

**Comment by somatonic** [comment]
This is how it looks in 2.7.3, the original image is gone, though the variations are still there... :)

![image](https://cloud.githubusercontent.com/assets/370148/18988681/0f5ab992-8708-11e6-8997-2a257c3bbda3.png)

**Comment by somatonic** [comment]
Ah and an important detail I missed: it seems the copy is created correctly, but the orginal is broken. (On a side note the description didn't copy over.)

**Comment by isellsoap** [comment]
I can reproduce the issue. I think step 2 of the [mentioned steps](https://github.com/processwire/processwire-issues/issues/12#issuecomment-250710063) is crucial here.

@somatonic By using the [issue template](https://github.com/processwire/processwire-issues/blob/master/.github/ISSUE_TEMPLATE.md) one can avoid a lot of follow-up comments and make it clear how to reproduce the issue. Anyway, thanks for reporting issues!

**Comment by ryancramerdesign** [comment]
What I didn't understand before is that you are using the Crop function not as a Crop function, but as a Duplicate function, creating an exact copy of the original rather than cropping or resizing it. I've just pushed a commit that fixes the issue. Thanks.
