### ISSUE TITLE
3.0.45: template caches not cleared anymore when page is saved

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#120]
In my most current 3.0.45 installation, some template caches are set. They are configured to "Clear cache for entire site" if a page is saved. This seems not to work anymore: There is no notice saying "Expired page cache for entire site" and the content (although changed) stays the same in frontend when a page is saved.

Downgrade to 3.0.42 (stable) cures the issue.

**Comment by ryancramerdesign** [comment]
I think likely this issue has the same cause as #121, so should now be fixed, but please let me know if you continue to experience it. Thanks.

**Comment by processwired** [comment]
As far as I see, the template caches are cleared now. But the notice "Expired page cache for entire site" does not appear (as it was in 3.0.42). Maybe this is intentional and the notice is not needed? Personally, can live with that ;-)

**Comment by ryancramerdesign** [comment]
Glad to hear that fixed the issue. As for that notice, that's only shown if debug mode is enabled. Are you finding it doesn't appear in debug mode?

**Comment by processwired** [comment]
All is well - if debug mode is enabled, the notice appears again. Thanks for fixing the issue that fast.
I'm closing the issue.
