### ISSUE TITLE
ProcessPageListRender::getPageLabel() render bug - template icon class not removed

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1200]
### Short description of the issue

If the icon of a template is overwritten by setting an individual page icon and furthermore a user-defined format (with curly brackets) is used in the pageLabelField of the template, the page label is not rendered correctly in the page tree.

**ProcessPageListRender::getPageLabel()** tries to replace the page related icon class string instead of the template related one.  

https://github.com/processwire/processwire/blob/51629cdd5f381d3881133baf83e1bd2d9306f867/wire/modules/Process/ProcessPageList/ProcessPageListRender.php#L132-L133

### Expected behavior

![Bildschirmfoto 2020-06-20 um 00 39 34](https://user-images.githubusercontent.com/4683120/85184243-525b3d00-b28f-11ea-9199-114adf9f921e.png)

### Actual behavior

![Bildschirmfoto 2020-06-20 um 00 40 11](https://user-images.githubusercontent.com/4683120/85184215-41123080-b28f-11ea-8d8a-37e114df2c68.png)

### Suggestion for a possible fix

```
// Line 132 predefined format string
			$icon = $page->getIcon();
			$templateIcon = $page->template->getIcon()? $page->template->getIcon() : $icon;
			if($icon) $pageLabelField = str_replace(array("fa-$templateIcon", "icon-$templateIcon", "  "), array('', '', ' '), $pageLabelField);
```

### Setup/Environment

* ProcessWire version: 3.0.159
* (Optional) PHP version: 7.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue among some other refactoring in that class.

**Comment by kixe** [comment]
@ryancramerdesign 
Thanks. closed.
