### ISSUE TITLE
Dragging page out of trash - it retains trashed status

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1201]
### Short description of the issue
Turns out that you can drag a page out of the trash and it will quite happily end up whereever you drop it, but it will keep the trashed status

### Expected behavior

Either it shouldn't be possible to drag a page out of the trash, or if you can, then it should remove the trashed status.

**Comment by ryancramerdesign** [comment]
@adrianbj Just wondering if you are still observing this issue on the dev branch? I can't seem to reproduce it here. It's possible it got fixed while fixing something else. Or it's possible that there is some other factor at play, and I might just need more specific instructions on how to reproduce. 

What I did is edit a page in the trash and look at its settings tab to confirm it had "Trash" status. Then I went back to the Page list, located the page in the trash page-list, clicked "Move" and dragged it into the site tree. Then I edited it again and observed it no longer had trash status.

**Comment by adrianbj** [comment]
It does seem to be only on one site of mine, but at the moment I have no idea why. I am on the latest PW dev version and that doesn't fix it. I'll have to dig into it further when I have more time.

**Comment by ryancramerdesign** [comment]
I'll close this out for now but let me know if you track down the source on that one instance. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I discovered this again - turns out it is specific to user pages that were trashed. 

I have a site where I have changed the user template to allow users to be trashed.

The other thing is that the string of numbers prepended to the user's page name isn't removed when restoring

@netcarver - can you reopen this please?

**Comment by adrianbj** [comment]
@netcarver - sorry, to hassle you again about this, but I want to make sure this isn't forgotten about forever :) Thanks!

**Comment by netcarver** [comment]
I'm seeing this issue as well.

I trash a page from a parent on the tree they end up in the trash as expected.

1. If I drag them out to an invalid parent page, there is an error message but the tree shows them in the location I dropped them even though a refresh shows them still in the trash.
2. If I drag them back into a valid parent page, then they are moved out into the tree under the valid parent, but still show their status as "trash".

![2022-06-13_16-47](https://user-images.githubusercontent.com/16049/173393302-c2a3476e-988f-497e-9f41-cbdf1a24e08f.png)

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.197|
|PHP|7.4.20|
|Webserver|Apache/2.4.46 (Unix) OpenSSL/1.1.1d|
|MySQL Server|5.5.5-10.3.27-MariaDB-1:10.3.27+maria~focal-log|
|MySQL Client|mysqlnd 7.4.20|

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, this is still an issue. If I untrash a page to an invalid parent, I get an error popup, and the page stays where I dropped it - maybe it could be moved back to trash? After the browser refresh, the page is again in the trash; that's ok. If I move a page to the correct parent, it stays there, ok, but still has a trash status.

**Comment by matjazpotocnik** [comment]
In processPageSort.module, in movePage() method, just before $page->save() I added:

```php
                //if page was in trash, and we are moving it out of the trash, then remove trash status
		if($parent->id !== 7) { //trashpage id
			$page->removeStatus(Page::statusTrash);
		} 
```

@adrianbj @netcarver can you guys test this? Of course, I'm not sure this is the correct approach to fix this, but at least it works here.

**Comment by adrianbj** [comment]
@matjazpotocnik - yes, that does fix it. I'm also not sure if it's the right approach, but hopefully @ryancramerdesign can reproduce the issue.

**Comment by ryancramerdesign** [comment]
@adrianbj @netcarver @matjazpotocnik 

Thanks, I have pushed a fix for this issue. I found it occurred with any page manually dragged out of the trash (rather than using the restore action), so didn't find anything specific to other types of pages. As a result, we may  need others to confirm that it also seems to be fixed. 

>  If I untrash a page to an invalid parent, I get an error popup, and the page stays where I dropped it - maybe it could be moved back to trash? 

@matjazpotocnik  For that case, it never moved out of the trash, but it just looks like it did. The same goes for moving any page (whether trash or not) to a parent where it's not allowed. I'm sure it's possible, but my JS abilities are limited here and I don't know how to visually move it back to the trash (or previous parent) without a refresh. Maybe the solution is just to force a refresh after the alert box closes?

> If I drag them back into a valid parent page, then they are moved out into the tree under the valid parent, but still show their status as "trash".

This issue should now be fixed hopefully. Though you my need to edit the page and view the Settings tab to confirm (rather than inspecting the ajax data, which might still have the older page instance).

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that fixes my issue of dragging pages out of trash. 

I do agree with @matjazpotocnik about the moving to an unallowed parent, but that is a different issue to this so I'll close this one.

**Comment by ryancramerdesign** [comment]
> I do agree with @matjazpotocnik about the moving to an unallowed parent, but that is a different issue to this so I'll close this one.

I agree also, I'm just not yet sure how to do it, so thinking of forcing a refresh.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign It's fixed here too. It was more work than I thought... Thanks for fixing it!
