### ISSUE TITLE
Width of fields in a template not correctly

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#1202]
### Short description of the issue

When editing the width of fields in a template or the repeater, values ​​are not correctly substituted.

### Expected behavior

It is necessary to display 6 fields:
15%, 15%, 15%, 15%, 20%, 20%

Fields where the width is 20% is assigned the class uk-width-1-5@m (width: calc(100% * 1 / 5)) = 20% - it's correctly.

Fields where the width is 15% is assigned the class uk-width-1-6@m (width: calc(100% * 1 / 6.001)) = 16,666666% - it's not correctly!

### Actual behavior

The width must be calculated correctly.

### Optional: Suggestion for a possible fix

Add classes .width-1 to .width-100

### Steps to reproduce the issue

1. Create 6 fields
2. Add this fields in any template
3. Setup fields width: field 1 = 15%, field 2 = 15%, field 3 = 15%, field 4 = 15%, field 5 = 20%, field 6 = 20%

### Setup/Environment

* ProcessWire version: 3.0.160

**Comment by adrianbj** [comment]
@germankirichenko - you should probably have a read of this: https://github.com/processwire/processwire-issues/issues/480

It doesn't really solve anything, but there is lots of discussion about the problems :)

**Comment by germankirichenko** [comment]
@adrianbj, thanks!
