### ISSUE TITLE
Thumbnail not being updated when cropping with an image field set to maxFiles=1

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1203]
### Short description of the issue

When you crop an image on a single image field (maxFiles=1), you only get the "Save and Replace" option which makes sense, but the thumbnail isn't updated - it still shows the full uncropped area of the original image which makes you think the crop hasn't worked.

### Expected behavior

The thumbnail should be updated to the cropped version because the full sized image no longer includes all the content shown in the thumbnail.

**Comment by Toutouwai** [comment]
Seems to be working for me, PW 3.0.160

![rep](https://user-images.githubusercontent.com/1538852/85340138-ad17c180-b539-11ea-8ba6-1fbd42a8e1e8.gif)

**Comment by adrianbj** [comment]
Thanks for testing @Toutouwai - I just checked on my local dev environment and it works there, but I am working directly on a remote server which is where the problem is. I ran the test again and realized that it's actually due to this error: https://github.com/processwire/processwire-issues/issues/1167

**Comment by adrianbj** [comment]
@ryancramerdesign @Toutouwai 

Solution to fix this is provided here: https://github.com/processwire/processwire-issues/issues/1167#issuecomment-648999395

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've added your suggested fix from #1167 though in a different location so that API calls don't need to know about the date format.
