### ISSUE TITLE
Try "help" in live search input not translatable

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#1204]
### Short description of the issue
When you add the _search-form.php file to the list of language files for translation, the value in the search field does not change.

### Expected behavior
Still - echo Try "help".

### Actual behavior
The value specified for the current language should be displayed.

### Steps to reproduce the issue
Create language
Add this file to translate (_search-form.php)
Translate values and go to the main admin page.
Focus-in / Focus-out to the live search input.

ProcessWire version: 3.0.160

**Comment by ryancramerdesign** [comment]
@germankirichenko Thanks, this is now fixed. I moved the term (along with others) into the file /wire/core/AdminTheme.php, so it can be translated from that file instead, which enables it to be recognized by ProcessPageSearchLive, as well as available to other admin themes down the road.

**Comment by germankirichenko** [comment]
@ryancramerdesign, thanks!
