### ISSUE TITLE
InputfieldRepeater::renderRepeaterLabel() renders encoded tags

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1205]
### Short description of the issue

**InputfieldRepeater::renderRepeaterLabel()** does not strip tags if previously html encoded.

### Screenshots/Links that demonstrate the issue

![Bildschirmfoto 2020-06-27 um 13 25 42](https://user-images.githubusercontent.com/4683120/85921175-87145900-b87a-11ea-943c-77625c0f7b24.png)

### Suggestion for a possible fix

Apply **htmlspecialchars_decode** before **strip_tags**. Replace line **172** in **InputfieldRepeater** class with:

`$out = trim(strip_tags(htmlspecialchars_decode($out)));`

### Setup/Environment

* ProcessWire version: 3.0.160
* PHP version: 7.2

**Comment by ryancramerdesign** [comment]
@kixe Any idea why there is a `<br />` in there in the first place? Part of the field's content?

**Comment by kixe** [comment]
> @kixe Any idea why there is a `<br />` in there in the first place? Part of the field's content?

Yes, it's part of the field's content and no, it's not in the first place.

The content used for personalized newsletter includes placeholders: {name_first} {name_last} surrounded by curled brackets, which are replaced by a span with class "ui-priority-secondary" in the label – which doesn't hurt me.

Would be great if you could add my solution for the fix. Currently I use a Workaround in **ready.php**

```
/**
 * BUGFIX
 * InputfieldRepeater - remove previously encoded tags
 * @see https://github.com/processwire/processwire-issues/issues/1205
 * @todo remove if fixed
 *
 */
$this->addHookAfter('InputfieldRepeater::renderRepeaterLabel', function($e) {
	$out = $e->return;
	$e->return = strip_tags(htmlspecialchars_decode($out));
});
```

**Comment by matjazpotocnik** [comment]
Similar problem with strip_tags() and htmlspecialchars(): https://github.com/processwire/processwire-issues/issues/1111
@kixe is this still an issue? There is no htmlspecialchars_decode() call in InputfieldRepeater, but strip_tags() is there https://github.com/processwire/processwire/blob/55ec568070212859525bef0191ee9f4644eceb34/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L184

**Comment by kixe** [comment]
@matjazpotocnik Thanks for pointing on this. issue is gone.
Fixed!
