### ISSUE TITLE
Uikit theme masthead logo in SVG doesn't work if SVG is "responsive" (ie has no dimensions specified).

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1206]
### Short description of the issue

Title says it all

### Expected behavior

PW should assign appropriate height to image so it looks good in the nav banner

### Actual behavior

No height assigned, so the image doesn't show at all.

### Optional: Suggestion for a possible fix

Add height to the `img` tag for SVGs

**Comment by BernhardBaumrock** [comment]
Bugs me all the time :)

**Comment by cb2004** [comment]
A height attribute would be great. Although, a responsive SVG has a viewbox attribute to make it responsive, you can still add height="" to the opening <svg tag in the file. Forgive me if wrong, on mobile.

**Comment by ryancramerdesign** [comment]
@adrianbj @BernhardBaumrock Can you send me a URL to an example svg file that demonstrates the issue so I can see it here?

**Comment by adrianbj** [comment]
@ryancramerdesign 

Just use this one:
[processwire.svg.zip](https://github.com/processwire/processwire-issues/files/4972849/processwire.svg.zip)

There's nothing special about it, other than it doesn't have any width or height attributes.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Looks good - thanks!
