### ISSUE TITLE
FieldtypePage: does not account for allowUnpub settings in template context

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1208]
### Short description of the issue

If a Page Reference field has "Allow unpublished pages?" enabled for overrides in template context then this template context setting is not accounted for in methods `FieldtypePage::wakeupValue` and `FieldtypePage::formatValue`.

I know that there's a warning that not all overrides will work but it looks like these methods could get the allowUnpub setting in template context without much trouble because both $field and $page are arguments to the methods.

E.g.

```php
$fieldgroup = $page->template ? $page->template->fieldgroup : null;
if($fieldgroup) $field = $fieldgroup->getFieldContext($field);
// Now $field->allowUnpub is correct for the template context of $page
```

### Setup/Environment

* ProcessWire version: 3.0.161

**Comment by ryancramerdesign** [comment]
@Toutouwai Good idea, I have added support for that.

**Comment by Toutouwai** [comment]
Thanks
