### ISSUE TITLE
WebP image is not generated if source PNG equals the requested size

### ISSUE THREAD

**Issue by timohausmann** [processwire/processwire-issues#1209]
### Short description of the issue

When I resize a PNG image to it's original size and ask for the WebP url, no WebP file is generated but a newly generated PNG URL is returned. Interestingly, this is only happening with PNG, not JPG. 

Example: I upload a PNG image of 1280x800

* `$page->image->webp->url` ➝ filename.webp ✔️
* `$page->image->width(800)->webp->url` ➝ filename.800x0.webp ✔️
* `$page->image->width(1281)->webp->url` ➝ filename.1281x0.webp ✔️
* `$page->image->width(1280)->webp->url` ➝ filename.1280x0.png ❌

I tried many variants with `webp()`, `url(false)`, different config settings for webp ... [Original Forum Post](https://processwire.com/talk/topic/23929-webp-is-not-generated-if-source-png-already-has-target-size/)

### Expected behavior

I expect a WebP file to be generated and a WebP url to be returned.

### Actual behavior

No WebP file is generated but a url to a newly generated PNG is returned.
When I set `useSrcUrlOnFail` to `false` inside `$config->webpOptions`, the webp url is returned, but the file is not found. This indicates to me the creation is tried but fails.

### Optional: Suggestion for a possible fix

Just a possible workaround on template level: 

    if($image->width == $width) {
        $url = $image->webp->url;
    } else {
        $url = $image->width($width)->webp->url;
    }
    echo "<img src='{$url}' />";

### Steps to reproduce the issue

1. Setup Processwire, create `image` field in home template
2. upload a png file and remember it's original width
3. In home.php template: `echo "<img src='{$page->image->first()->width(640)->webp->url}' />";` (where 640 needs to be the original width)
4. observe the png output and no generated webp file in /site/assets/files/1/. If you increase or decrease width by 1, a webp file will be created and the correct webp url will appear. If the same is done with a JPG, it works as expected.

### Setup/Environment

* ProcessWire version: 3.0.148 and 3.0.160 dev
* PHP version: 7.2.4
* GD Lib "bundled (2.1.0 compatible)"

**Comment by ryancramerdesign** [comment]
@timohausmann This sounds like the `useSrUrlOnSize` option coming into play. The goal with webp is to create a file that's smaller than the original. But sometimes a webp file ends up larger than the original. When that happens, the non-webp version will be returned, because it's smaller in filesize. Can you check to see if this might be the case for your instance? Let me know if you find your webp is actually smaller than the png, in which case it wouldn't be behaving correctly.

Also if you want to turn off the option you can do so from your /site/config.php file:
~~~~~
$config->webpOptions('useSrcUrlOnSize', false); 
~~~~~
Below are all the options and default values: 
~~~~~
$config->webpOptions = array(
	'quality' => 90, // Quality setting of 1-100 where higher is better but bigger
	'useSrcExt' => false, // Use source file extension in webp filename? (file.jpg.webp rather than file.webp)
	'useSrcUrlOnSize' => true, // Fallback to source file URL when webp file is larger than source?
	'useSrcUrlOnFail' => true, // Fallback to source file URL when webp file fails for some reason?
);
~~~~~

**Comment by matjazpotocnik** [comment]
@ryancramerdesign please see this post: https://processwire.com/talk/topic/23929-webp-is-not-generated-if-source-png-already-has-target-size/ 

> 
> - I checked that the PNG version is not smaller in filesize (PNG=450KB, WebP (from other tool)=60KB)
> 
> - Setting 'useSrcUrlOnFail' => false inside $config->webpOptions results in correct output URL (filename.1280x0.webp), but still the file is not generated. So maybe the webp conversion fails? Apparently I see zero webp logs in logs/image-resizer.txt

**Comment by timohausmann** [comment]
@ryancramerdesign thanks for your reply and @matjazpotocnik for quoting. The original PNG is 450 KB and when I do `$page->image->webp->url` (without `width(1280)`) a webp image is generated and linked that is indeed only 60.8 KB. 

`$config->webpOptions('useSrcUrlOnSize', false);` in combination with `width(1280)` makes no difference in the webp generating or url output. 

Observed with GD under Windows (WAMP) and Debian. Cannot test ImageMagick at the moment ...

**Comment by ryancramerdesign** [comment]
Thanks @timohausmann @matjazpotocnik, I wasn't able to duplicate it with ImageSizerEngineImagick (my GD doesn't support webp), but I tried on a web server that uses GD for webp and then was able to duplicate it there. I was able to track it down to an issue in the ImageSizerEngineGD class and fix it. Thanks

**Comment by timohausmann** [comment]
Thanks for your fast response and fix! If this will be in the next dev release I will test and report here.

**Comment by timohausmann** [comment]
Just tested this again with Processwire 3.0.165 and everything works as expected!

Thanks for the fix again 👍
