### ISSUE TITLE
Can't edit Home page name or state (multilanguage)

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#121]
### Short description of the issue

After updating to PW 3.045 I can't edit the Home page names (slug) on a multilanguage site, nor the "active" state of languages. They always become "active" and their names get the name of the default language (but only if there was no name saved beforehands).

On PW 3.044 I could rename an existing name of the Home page (eg "/de/" to "/des/") but after updating to v30.45 I couldn't.

Screen capture:
http://rolandtoth.hu/pic/pw3045names.gif

### Setup/Environment

* ProcessWire version 3.0.45
* (Optional) PHP version 7.14

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this issue. Please let me know if you continue
to experience it.

**Comment by rolandtoth** [comment]
Looks like it's fixed, thanks!
