### ISSUE TITLE
Custom image fields: required fields can be empty

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#1212]
# Short description of the issue

When adding custom fields to an image (https://processwire.com/blog/posts/pw-3.0.142/) and setting one of the fields as required (e.g. title), I can save a page containing images without that title.

### Expected behavior

I get an error that the image title is missing.

### Actual behavior

The page save goes through.

**Comment by ryancramerdesign** [comment]
@MrSnoozles Thanks for the report, I have pushed a fix for this issue.

**Comment by netcarver** [comment]
@MrSnoozles Any update on this?  Could you close the issue if it's fixed.

**Comment by MrSnoozles** [comment]
All good now thank you ryan. And thanks too for the reminder @netcarver
