### ISSUE TITLE
FieldtypeComments: `classes` options are not used in renderFormNormal() of CommentForm class

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1213]
### Short description of the issue

There are options for changing output markup, including classes for the comments form output. But they are used only for the threaded comments in `renderFormThread()` method, but not for the normal comments in `renderFormNormal()`. Maybe it is not only classes, but I spotted those.

### Expected behavior

`classes` options should be used for both threaded and normal comments.

### Optional: Suggestion for a possible fix

- Update `renderFormNormal()` method of CommentForm class to use `classes`.
- Check, if other options are not being used where they should )))

### Setup/Environment

* ProcessWire version: 3.0.153

**Comment by ryancramerdesign** [comment]
@ivangretsky This was fixed a couple weeks ago, so I'll close this. Thanks.
