### ISSUE TITLE
Undefined index: keepEscapePrefix in WireTextTools.php

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1214]
### Short description of the issue

I saw this error when creating a Page Reference field in PW 3.0.162:

PHP Notice: Undefined index: keepEscapePrefix in ...\wire\core\WireTextTools.php:1171

Looks like this key needs to be defined in the $defaults array: https://github.com/processwire/processwire/blob/6a1b6a21ae4f6df599eaa81176ace6b161a59263/wire/core/WireTextTools.php#L1138-L1145

### Setup/Environment

* ProcessWire version: 3.0.162

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
