### ISSUE TITLE
Creating a 'edit' role breaks all role editing

### ISSUE THREAD

**Issue by derixithy** [processwire/processwire-issues#1215]
### Short description of the issue

CReating a role with the name edit, breaks the edit page for all roles.

### Expected behavior

The edit page for the role shows up

### Actual behavior
The edit page for roles redirects to /processwire/roles/edit/?login=1, which will display the Login and a link to edit your profile.

### Optional: Suggestion for a possible fix

Do no allow the use of name edit

### Steps to reproduce the issue

1. Create a role named edit
2. Submit the page

### Setup/Environment

* ProcessWire version: 3.0.148
* (Optional) PHP version: PHP 7.4.3 (cli)
* (Optional) MySQL version: 10.3.21-MariaDB
* (Optional) Any 3rd party modules that are installed and could be related to the issue: None

**Comment by ryancramerdesign** [comment]
Thanks @derixithy I've pushed a fix for this issue. This should also enable you to use the role name "edit" (or any other that might collide with existing methods)
