### ISSUE TITLE
AdminThemeUikit not consistent with git Version (less)

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1218]
I use some custom AdminThemes based on AdminThemeUikit. Until now it was a great help to download/ fork/ clone AdminThemeUikit from github https://github.com/ryancramerdesign/AdminThemeUikit/ and to do modifications via less compiler.

Actually there are some changes in the core but not here https://github.com/ryancramerdesign/AdminThemeUikit
Please stay consistent or provide less or sass files in ProcessWire git repo.

**Comment by BernhardBaumrock** [comment]
I have the same problem and wanted to report it soon, so thanks for opening that issue!

**Comment by BernhardBaumrock** [comment]
@kixe I think this issue can be closed now that we have uikit in the core :)

**Comment by ryancramerdesign** [comment]
@kixe Closing because we are no longer using the AdminThemeUikit repo as it's all in the core now, thanks to @BernhardBaumrock
