### ISSUE TITLE
Two factor recommandation notification reappears with remembered password.

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1219]
### Short description of the issue

The [two factor recommandation notification](https://processwire.com/blog/posts/think-affordable-artificial-blast/) enabled for user roles reappears after the second login with a remembered password for users with enabled two factor authentification.

### Expected behavior

The two factor recommandation notification should always be hidden for users with enabled two factor authentification.

### Actual behavior

After the first login the notification is hidden as expected. After the second login the notification reappears.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/2794879/88631088-e18b1a00-d0b1-11ea-9df0-24b581a70368.png)

### Steps to reproduce the issue

1. Install latest version 3.0.163 dev
2. Install Tfatotp module
3. Enable two factor authentifiaction
4. Enable the notification in the ProcessLogin module
5. Logout and login two times

### Setup/Environment

ProcessWire: 3.0.163
PHP: 7.4.2
Webserver: Apache
MySQL Server: 5.7.26
MySQL Client: mysqlnd 7.4.2

**Comment by ryancramerdesign** [comment]
Thanks @designconcepts I've pushed a fix for this issue.

**Comment by designconcepts** [comment]
Thank you for fixing the issue.
