### ISSUE TITLE
3.0.45: Repeater out of memory

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#122]
### Short description of the issue

The repeater is causing an out of memory issue

### Expected behavior

To load the edit page

### Actual behavior

The following error occurs :
```Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 179280872 bytes) (line 176 of /home/peterand/forte.peterandpauldev.co.uk/wire/core/PagesLoaderCache.php)```

### Steps to reproduce the issue

1. Create a repeater
2. Try to edit page with repeater on
3. See the large amount of memory it requires

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.45
PHP: 5.5.38
Apache: Apache
MySQL: 10.0.25-MariaDB-cll-lve

<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1
max_execution_time: 120 (changeable)
max_input_nesting_level: 64
max_input_time: 120
max_input_vars: 5000
memory_limit: 256M
post_max_size: 100M
upload_max_filesize: 100M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 1
FreeType: 1
Imagick Extension: 1

</details><details><summary><strong>Module Details</strong></summary> FieldtypeRepeaterMatrix: 0.0.3
InputfieldRepeaterMatrix: 0.0.3
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
TracyDebugger: 3.5.0
</details></details>

* ProcessWire version: 3.0.45

EDIT: 
I can't edit the repeater field to delete it, I'm getting the error:
```	Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 247463936 bytes) (line 176 of /home/peterand/forte.peterandpauldev.co.uk/wire/core/PagesLoaderCache.php)```

EDIT2: 
I've commented out line 176 and that's fixed it. 
```
if(is_array($value)) $value = print_r($value, true);
```
No idea what effect this will have, but since it's only printing a value I imagine it should be okay.

**Comment by ryancramerdesign** [comment]
I've got repeaters running all over the place, but am not seeing this
issue. Can you provide more details on what repeater setup is necessary to
duplicate the issue? Also how may repeater items are present?

**Comment by ryancramerdesign** [comment]
I replied via email before, where the edits weren't visible. Based on what you mentioned in the edits, I'm guessing it's the template property of that $value. I'm going to see if we can replace that print_r with something else. Thanks.

**Comment by ryancramerdesign** [comment]
While I can't duplicate the issue here, that line 176 you mentioned was pretty specific, so I've pushed an update that replaces that print_r() with a custom function. Please let me know if you find this fixes it. Thanks.

**Comment by TomS-** [comment]
@ryancramerdesign That's got it! Thank you :-)
