### ISSUE TITLE
$sanitizer->truncate doesn't work unless PHP mbstring is installed

### ISSUE THREAD

**Issue by 16th-earl** [processwire/processwire-issues#1221]
### Short description of the issue

$sanitizer->truncate only works if PHP mbstring is installed, but this isn't clear from the documentation and there's no error message – it just returns a "0".

### Expected behavior

```
$text = 'Let us see how this goes. Does it truncate the string?';
echo $sanitizer->truncate($text, 15);
```

Result: string "Let us see how…"

### Actual behavior

Result: string "0…"

### Optional: Suggestion for a possible fix

This works as long as PHP mbstring is installed. My suggestion is to update the "ProcessWire software requirements" page at https://processwire.com/about/requirements/ to say that mbstring is "required" (currently it says "recommended"). It would also be good to update the documentation page at https://processwire.com/api/ref/sanitizer/truncate/ to say that mbstring is required.

### Steps to reproduce the issue

1. On a server without PHP mbstring installed, attempt to use the $sanitizer->truncate method with any valid input.

### Setup/Environment

* ProcessWire version: 3.0.148
* (Optional) PHP version: 7.2.24

**Comment by ryancramerdesign** [comment]
Thanks @16th-earl this issue has been fixed. I didn't intend for it to require mb_string() here, the issue instead turned out to be a typo in another function.

**Comment by 16th-earl** [comment]
Thanks Ryan!
