### ISSUE TITLE
Array sanitizer doesn't work as second argument to $input->post()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1224]
[This blog post](https://processwire.com/blog/posts/pw-3.0.125/#input-api-variable-upgrades) introduced new features for $input->get(), $input->post() and $input->cookie() methods.

> Provide a sanitization method as the 2nd argument to include sanitization in the return value. You can specify almost any sanitizer method available in the Sanitizer class.

But this isn't working for $sanitizer->array()...

![2020-08-04_130648](https://user-images.githubusercontent.com/1538852/89241565-60a0c500-d653-11ea-8195-4f3d77c47216.png)

The blog post does say _almost any_ sanitizer method, but given that sanitizing to an array is a common need I expected this sanitizer to work.

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've refactored that method to improve how it deal with array values and sanitizers and this should also fix this issue.

**Comment by Toutouwai** [comment]
Thanks
