### ISSUE TITLE
Email field unique setting not staying checked

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1225]
Using 3.0.164 I am trying to set the email field to be unique, but it is not saving the status.

**Comment by ryancramerdesign** [comment]
@cb2004 I can't duplicate that one here, testing on both a blank install and the processwire.com site. Also tried it on both system email field and a newly created "test_email" field. Can you think of anything else necessary to duplicate it?

If it's an existing email field that already has rows stored in it, another possibility is that there are already duplicate rows present and the index can't be added. Though it's supposed to tell you if that happens, but it'd be worth checking just in case.

**Comment by cb2004** [comment]
@ryancramerdesign a quick export to CSV and a duplicate check in Excel would highlight that there are already duplicates, I am just not seeing a notification of this.

**Comment by ryancramerdesign** [comment]
Thanks @cb2004 — now that I am able to duplicate, the errors/warnings weren't showing when they should have been. I have fixed it.

**Comment by netcarver** [comment]
@cb2004 Hi, could you verify this fix please and either close this issue or update it. Thank you.
