### ISSUE TITLE
$files->render() cannot pass variable named "data"

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1226]
#### Works

basic-page.php
```php
echo $files->render('test-render', ['foo' => 'bar']);
```

test-render.php
```php
echo $foo;
```

#### Does not work

basic-page.php
```php
echo $files->render('test-render', ['data' => 'bar']);
```

test-render.php
```php
echo $data; // causes undefined variable notice
```

It is so common to want to use "data" as a variable name that this trips me up again and again.

It would be great if an exception could be thrown to explain what the cause of the issue is (the variable name "data" is reserved and cannot be used), and please document any reserved variable names in the PW docs for the [$files->render()](https://processwire.com/api/ref/wire-file-tools/render/) method.

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by teppokoivula** [comment]
Exception would be a nice compromise here. I've banged my head on this issue numerous times myself, would've been better if the system outright rejected this :)

**Comment by BernhardBaumrock** [comment]
Same here, exception + explanation would definitely help =)

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've updated it so that you can use 'data' as a variable name. No reserved variable names are intended here.

**Comment by Toutouwai** [comment]
Thanks
