### ISSUE TITLE
findMany still runs out of memory when processing 150,000+ pages

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1228]
### Short description of the issue

Recently wrote a command line script to delete ~150,000 pages, using findMany() to grab the pages and loop over them, deleting one at a time. It immediately failed due to memory being exhausted. Added a limit of 50,000 and it worked again. So it seems that there's some kind of memory leak that only appears at very large scale.

### Expected behavior

I expected no limit to the number of pages I could manipulate, since findMany is supposed to batch the page load.

### Actual behavior

findMany exhausted the server memory allocated at large scale (150,000 pages).

### Steps to reproduce the issue

Here is the CLI script I used:

```
require("index.php");

foreach(wire('pages')->findMany("template=sc-order|sc-order-item|BlogPost|Fundraiser|Participant|Tag, include=all, check_access=0") as $p) {
	$p->delete(true);
}
```

* ProcessWire version: 3.0.148
* (Optional) PHP version: 7.1.23

**Comment by BernhardBaumrock** [comment]
Did you try adding https://processwire.com/api/ref/pages/uncache-all/ in your foreach?

Does it also fail if you remove the $p->delete() and just fire the findMany() call without any actions?

**Comment by ryancramerdesign** [comment]
@thetuningspoon When you use the findMany() option to find 150k pages, it's still creating 150k pages in memory, but just as placeholders without anything loaded into them (other than template) until they are in the current batch. So if you are finding it fails immediately on a search for 150k pages before getting to iterate any of them, that means that there's not enough memory to store the 150k placeholder pages. The principle is the same as lazy loading images — there's still an `<img>` tag, even if its src attribute hasn't been populated. If you increase the memory available to PHP, that should help. Though sticking with 50k page chunks would be a good way to go also.

**Comment by thetuningspoon** [comment]
Thanks for the explanation, @ryancramerdesign.
