### ISSUE TITLE
Multi-Instance support with custom page types

### ISSUE THREAD

**Issue by sebastiandittrich** [processwire/processwire-issues#1230]
### Short description of the issue

```php
<?php

use ProcessWire\Page;
use ProcessWire\ProcessWire;

class CustomPage extends Page
{
    public function __construct()
    {
        parent::__construct($this->templates->get('basic-page'));
    }
}

$p1 = new ProcessWire();

$p2 = new ProcessWire();
$page = $p2->wire(new CustomPage());
var_dump('page wire', $page->wire->instanceID); //  => 1
var_dump('template wire', $page->template->wire->instanceID); // => 0
```
When running this, `$page->wire` would be the second instance, and `$page->template->wire` would be the first.
This is the case because `$wire->wire($page)` is called **after** the constructor. 

I understand that this is not an exactly issue with processwire, but it can become a problem when using these both techniques together. For me it causes poorly debuggable issues when using multiple instances while running tests. It leads to tests influencing each other, because of the wrong processwire references.

### Expected behavior

`$page->template->wire` should be the same as `$page->wire`.

### Actual behavior

`$page->template->wire` is always the first processwire instance, no matter what processwire instance the page uses.

### Suggestion for a possible workaround

A workaround would be to give a `ProcessWire\Wire` instance as parameter to the page constructor. Then you could do this: 
```php
<?php

use ProcessWire\Page;

class CustomPage extends Page
{
    public function __construct(Wire $wire)
    {
        parent::__construct($wire->templates->get('basic-page'));
    }
}

$p2->wire(new CustomPage($p2));
```

### Steps to reproduce the issue

1. Create two Processwire instances
2. Declare a custom page type with a default template, which is loaded in the constructor
4. Make a new Page and wire it to Processwire instance 2
5. Compare both `$page->wire` and `$page->template->wire`. They are different, while they should be the same.

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.164|
|PHP|7.4.8|
|Webserver|Apache/2.4.35 (Win64) OpenSSL/1.1.1g mod_fcgid/2.3.9|
|MySQL Server|5.7.24|
|MySQL Client|mysqlnd 7.4.8|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|36000 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|512M|
|post_max_size|2G|
|upload_max_filesize|2G|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|EXIF Support||
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|BookingStudio|1.0.0|
|FieldtypeMystique|0.0.15|
|InputfieldMystique|0.0.15|
|Mystique|0.0.15|
|ProcessTracyAdminer|1.0.7|
|TracyDebugger|4.21.20|
</details>

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@sebastiandittrich ProcessWire's constructor has no required arguments. If it did, I think the majority of code people write for creating pages would stop working. We're trying to keep things simple so we don't want API users to have to always think about instances, when most people don't need it. We only want people to have to consider multi-instance in their code if they are trying to use multiple-instances. The constructor does however optionally accept a Template (object) argument. If you give it one, it'll inject the ProcessWire instance from the Template object automatically. However, Page objects are most often constructed without any arguments. And for any object in ProcessWire (Page or not), I wouldn't suggest having constructors that have some dependency on the ProcessWire instance. For any Wire-derived object, that kind of dependency can instead be put in a `wired()` method, which gets called after ProcessWire injects its instance to the object. So at that point it's a safe bet to call something like `$this->wire()->templates`:
~~~~
public function wired() {
  parent::wired();
  $this->setTemplate('basic-page'); 
}
~~~~

**Comment by sebastiandittrich** [comment]
Ok thanks, this should be a workaround when working with multiple instances!

**Comment by ryancramerdesign** [comment]
Sure, no problem. I'll close this out, but let me know if I can help with anything else.
