### ISSUE TITLE
PageFinder cannot sort by FieldtypeOptions subfield

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1231]
### Short description of the issue

This issue is to carry over and expand on an issue in the old PW repo: https://github.com/ryancramerdesign/ProcessWire/issues/2049

Selectable options in a FieldtypeOptions field have some subfields stored in the `fieldtype_options` database table: "title", "value" and "sort". But it isn't possible to sort results from PageFinder by these subfields:

![2020-08-19_094222](https://user-images.githubusercontent.com/1538852/90568721-91126280-e200-11ea-9e31-e66bcf1db606.png)
![2020-08-19_094203](https://user-images.githubusercontent.com/1538852/90568723-92438f80-e200-11ea-82d3-9ca9a483c04d.png)
![2020-08-19_094401](https://user-images.githubusercontent.com/1538852/90568716-8fe13580-e200-11ea-8c06-d0ee94cc778d.png)

Related forum topics:
https://processwire.com/talk/topic/1352-sorting-results-of-find-by-admin-order/
https://processwire.com/talk/topic/24168-sorting-pages-by-select-options-title-not-id/

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by ryancramerdesign** [comment]
@Toutouwai This option should be supported now, per the above referenced commit. Though please let me know if you find otherwise. Thanks.

**Comment by Toutouwai** [comment]
Thanks
