### ISSUE TITLE
Uninstalling ProCache v4 doesn't properly remove its .htaccess code and causes 500 error

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1233]
Let's say you have ProCache v4 successfully installed and the .htaccess code properly inserted.

If you uninstall ProCache, it will leave a remnant of this in .htaccess:

```
-------------------------------------------------------------------------------------
```

which is invalid code causing a 500 error.

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I can confirm—I will fix that in the ProCache board.
