### ISSUE TITLE
Cannot use get_total with selector's array syntax

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#1236]
### Short description of the issue

Cannot use get_total with selector's array syntax

### Expected behavior

```
 $selector = [
        'template' => 'provider',
         'limit' => 10,
 ];
$selector['get_total'] = "0";

```
This would remove the counting when calling find()

### Actual behavior

Returns this error:

`Fatal Error: Uncaught WireException: Item 'get_total' set to Selectors is not an allowed type in wire/core/WireArray.php:458
`
* ProcessWire version: 3.0.164

**Comment by Toutouwai** [comment]
It works for me. I would be inclined to set 0 as an integer rather than a string but it works as a string in any case. Tested in PW 3.0.164.

![2020-08-29_102346](https://user-images.githubusercontent.com/1538852/91619653-caf21e80-e9e1-11ea-9f74-9f719899e983.png)

**Comment by elabx** [comment]
You are correct, it was a mistake on my own code, can confirm it works. Closing.
