### ISSUE TITLE
Lister: styling of unpublished page titles is misleading

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1237]
### Short description of the issue

I have four news items...

One: Published and not Hidden
Two: Published and Hidden
Three: Unpublished and not Hidden
Four: Unpublished and Hidden

![2020-08-31_140824](https://user-images.githubusercontent.com/1538852/91676422-ddac5500-eb93-11ea-8972-b8cabb60edf4.png)

Each of these status combinations is distinguishable in Page List.

But in Lister, pages that are unpublished look like they are also hidden, based on the expectations from using Page List. There is no visible distinction between pages Three and Four yet they have different status combinations.

![2020-08-31_140908](https://user-images.githubusercontent.com/1538852/91676526-3bd93800-eb94-11ea-9362-ff4fb93c2fa8.png)

### Suggestion for a possible fix

Use the same styling in Lister as in Page List, i.e. strikethrough means unpublished, lowered opacity means hidden. And it would be good to use the same opacity reduction for hidden status across these two contexts (currently it's 0.6 in Page List and 0.5 in Lister).

On the topic of Lister / Page List standardisation, please consider this request: [Use Page List fields from template settings in Lister](https://github.com/processwire/processwire-requests/issues/187)

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai good observation, I hadn't noticed that inconsistency before, it has been fixed.

**Comment by Toutouwai** [comment]
Thanks
