### ISSUE TITLE
New ProcessWire version (3.0.165)

### ISSUE THREAD

**Issue by jotamartos** [processwire/processwire-issues#1238]
Hi, 

This is not an issue but a question about the new version of the application. Please let me know if I need to use any other channel to ask this. 

I can see that you made some changes in master to bump the app's version to 3.0.165

https://github.com/processwire/processwire/commit/d8945198f4a6a60dab23bd0462e8a6285369dcb9

However, you didn't create a new tag for that new version. Is 3.0.165 a stable release and you simply forgot to create a new tag or should we avoid using this new version for any reason?

Thanks,
Jota

**Comment by MrSnoozles** [comment]
Hey Jota,

there seems to be a tag, at least now. Does this solve the issue?

https://github.com/processwire/processwire/tree/3.0.165

**Comment by matjazpotocnik** [comment]
@jotamartos can this issue be closed?
