### ISSUE TITLE
Error: Exception after upgrading to 3.0.165 from 3.0.155 

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#1242]
I'll update this bug report with more information when I manage to narrow down the possible origin of the error, but on my blog template, which was working correctly before upgrading to 3.0.165 from 3.0.155, I'm getting the following exception:

`Oh no… Error: Exception: Unrecognized operator: $ (in wire/core/Selectors.php line 410)

#0 wire/core/Selectors.php (244): Selectors->extractOperators()
#1 wire/core/Selectors.php (145): Selectors->extractString()
#2 wire/core/Selectors.php (131): Selectors->setSelectorString()
#3 wire/core/PagesLoader.php (311): Selectors->init()
#4 wire/core/Pages.php (255): PagesLoader->find()
#5 wire/core/Wire.php (400): Pages->___find()
#6 wire/core/WireHooks.php (823): Wire->_callMethod()
#7 wire/core/Wire.php (465): WireHooks->runHooks()
#8 wire/core/Page.php (4557): Process

This error message was shown because: site is in debug mode. ($config->debug = true; => site/config.php). Error has been logged.`

**Comment by jacmaes** [comment]
Found the culprit:

`	$entries = $page->entries_per_page;
$posts = $page->children("limit=$entries");`

If  `limit=$entries` is in single quotes, the error occurs. With double quotes, the error goes away. The field `entries_per_page`  is an integer. Is that normal?

**Comment by teppokoivula** [comment]
> If limit=$entries is in single quotes, the error occurs. With double quotes, the error goes away. The field entries_per_page is an integer. Is that normal?

With double quotes it gets interpolated into an integer (limit=5), with single quotes it gets added as-is (limit=$entries). Sounds reasonable enough to me — single quotes don't make any sense in this context, and thus the error message reveals an actual error in code.

**Comment by jacmaes** [comment]
Understood. Thanks for the clarification. I'm closing the issue then.
