### ISSUE TITLE
Custom page classes not used for language pages

### ISSUE THREAD

**Issue by daun** [processwire/processwire-issues#1246]
### Short description of the issue

When using the new custom page classes feature (`$config->usePageClasses`), language pages seem to ignore any custom classes from `/site/classes/LanguagePage.php`.

### Expected behavior

Language pages are instantiated from the custom `LanguagePage` class.

### Actual behavior

Language pages are instantiated from the default `Language` class.

Normal pages and user pages seem to be working fine and show `DefaultPage` and `UserPage` as classnames.

Setting the `pageClass` setting of the `language` template to `LanguagePage` manually makes no difference.

### Screenshots that demonstrate the issue

<img width="412" alt="Screenshot 2020-09-12 at 13 26 35" src="https://user-images.githubusercontent.com/22225348/92994560-a9258b00-f4fb-11ea-9d42-fba5a225289e.png">

### Steps to reproduce the issue / code example

```php
// /site/classes/LanguagePage.php

<?php namespace ProcessWire;

class LanguagePage extends Language
{
    public function get($key)
    {
        if ($key == 'is_it_working') {
            return 'yes';
        }
        return parent::get($key);
    }
}

// /site/ready.php

echo $user->language->is_it_working;
```

### Setup/Environment

* ProcessWire version: 3.0.164

**Comment by ryancramerdesign** [comment]
Thanks @daun this previously was not supported, but I looked into it and found I could add support for it relatively easily so have gone ahead and added it. If you get a chance, please try it out to confirm it is also working for your environment.

**Comment by daun** [comment]
Just tested this on a local install and it works perfectly — languages are created from the custom class now.

Thanks for the quick resolution!
