### ISSUE TITLE
Can't access last url segment using API

### ISSUE THREAD

**Issue by salvw** [processwire/processwire-issues#1247]
### Short description of the issue

The API for accessing the url segments in reverse uses zero based indexing instead of 1 based. 
That means $input->urlSegment(-1) and $input->urlSegmentLast return the second to last item.

### Expected behavior

For example in the url: https://domain.com/page/seg1/seg2/seg3/seg4/
$input->urlSegment(-1); and $input->urlSegmentLast return "seg4"
$input->urlSegment(-2) returns "seg3" 
$input->urlSegment(-3) returns "seg2" 

### Actual behavior

$input->urlSegment(-1); and $input->urlSegmentLast return "seg3"
$input->urlSegment(-2) returns "seg2" 
$input->urlSegment(-3) returns "seg1" 

### Optional: Suggestion for a possible fix

"The URL segments array has a 1-based index but this is lost to a 0-based index when the array is reversed here: https://github.com/processwire/processwire/blob/ee4c46a442f09cf81f9e1800c5fdfcd1176f538a/wire/core/WireInput.php#L576"

https://processwire.com/talk/topic/24310-cant-access-last-url-segment/?do=findComment&comment=206109

### Setup/Environment
ProcessWire: 3.0.165

**Comment by ryancramerdesign** [comment]
Thanks @salvw I've pushed a fix for this issue
