### ISSUE TITLE
$page->parents doesnt accept a template ID

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1249]
As the title suggests, this works fine:

`<?php foreach($page->parents("template!=categories-summary") as $p): ?>`

This doesnt:

`<?php foreach($page->parents("template!=115") as $p): ?>`

* ProcessWire version: 3.0.166

**Comment by adrianbj** [comment]
Did you try `template.id!=115` ?

**Comment by cb2004** [comment]
@adrianbj I did now, works fine.
