### ISSUE TITLE
Enter key doesn't work with admin's search autocomplete

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#125]
### Short description of the issue

Pressing the "Enter/Return" key doesn't navigate to the highlighted item in the autocomplete search.

### Expected behavior

I expected to be able to search for something and navigate the autocompleted results with my keyboard up and down keys and then press "Enter" to navigate to that item.

### Actual behavior

Pressing the down key causes errors to be shown in the console.

### Optional: Screenshots/Links that demonstrate the issue

![edit page home pwtwig dev 2016-12-21 15-22-01](https://cloud.githubusercontent.com/assets/40570/21406435/448a34ac-c791-11e6-9087-2c09231223c6.jpg)

![edit page home pwtwig dev 2016-12-21 15-15-05](https://cloud.githubusercontent.com/assets/40570/21406286/5bdf0fd4-c790-11e6-8b71-bd5b029e6632.jpg)

### Optional: Suggestion for a possible fix

Not sure yet.

### Steps to reproduce the issue
1. Type a keyword in the search field
2. press the down key on the keyboard to highlight one of the autocomplete results
3. notice the errors in Google Chrome's console

### Setup/Environment
* ProcessWire version: Tested on PW 3.0.44 and PW 2.7.2 with Google Chrome and Firefox on a Mac

**Comment by Toutouwai** [comment]
Same as this issue raised in the old repo: https://github.com/ryancramerdesign/ProcessWire/issues/1816

**Comment by Toutouwai** [comment]
@gmclelland, as a workaraound you might like to try my HotkeySearch module which has a configurable hot key binding for triggering search results.
https://github.com/Toutouwai/HotkeySearch

**Comment by gmclelland** [comment]
Thanks @Toutouwai!  Hopefully we can get this fixed.

While reviewing the code I noticed this may be a small bug? https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/Process/ProcessPageSearch/ProcessPageSearch.module#L1003

Should ->entities1( be ->entities(  ?

**Comment by LostKobrakai** [comment]
There is in fact an $sanitizer->entities1() method. That's not a bug/misspelling.

**Comment by gmclelland** [comment]
Good to know.  Thanks @LostKobrakai.

**Comment by gmclelland** [comment]
Just wanted to let everyone know that I have a fix for this.  I will be preparing a pull request.  The pull request will probably involve changing minifying and compiling js and scss files located in /wire/modules/AdminTheme/AdminThemeDefault/.

How do those get processed?  I see the compile.sh for the sass files, but what about the minifying for the javascript files?

Should I not include the compiled files in the pull request and just let @ryancramerdesign or someone else compile the files before committing everything?

**Comment by ryancramerdesign** [comment]
Don't worry about compiling the files, as I think PhpStorm just re-compiles them immediately anyway, so it shouldn't matter if they are present or not.

**Comment by gmclelland** [comment]
For anyone that wants to test the fixes, here is the pull request https://github.com/processwire/processwire/pull/47

Sorry @ryancramerdesign, I had already compiled the css files and minified the javascript files.  Hope that is still ok?  If not, I guess you could git cherry pick the commits you need?

**Comment by gmclelland** [comment]
This is fixed in core now.  https://github.com/processwire/processwire/commit/928a399b8ae9e8629461b98c5579f4b99889197f
