### ISSUE TITLE
Run-time notices in WireDatabasePDOStatement

### ISSUE THREAD

**Issue by gRegorLove** [processwire/processwire-issues#1252]
### Short description of the issue

Executing a prepared statement with question marks and debug mode on generates run-time notices.

### Expected behavior

Query executes with no run-time notices.

### Actual behavior

Run-time notice:
> Trying to access array offset on value of type int in /wire/core/WireDatabasePDOStatement.php on line 107

The query still executes successfully. 

### Optional: Suggestion for a possible fix

[This loop](https://github.com/processwire/processwire/blob/master/wire/core/WireDatabasePDOStatement.php#L180) presumes the input parameters is an associative array and is passing the array index to setDebugParam() as the parameter name. Could add a check before this loop to only process associative arrays that way. 

### Steps to reproduce the issue

```php
$stmt = $database->prepare('
	INSERT INTO example_table SET 
		foo = ?
		,bar = ?');

$stmt->execute([
	'value1',
	'value2',
]);
```

### Setup/Environment

* ProcessWire version: 3.0.165
* (Optional) PHP version: 7.4.6
* (Optional) MySQL version: 5.7
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @gRegorLove I've pushed a fix for this issue that hopefully fixes that, though let me know if not.

**Comment by gRegorLove** [comment]
That worked!
