### ISSUE TITLE
Non-superuser cannot use image actions inside repeater

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1253]
### Short description of the issue

The actions dropdown for images inside a repeater is rendered for non-superusers, but if any of the actions are selected they are not applied when the page is saved.

![actions](https://user-images.githubusercontent.com/1538852/94320759-d422db00-ffe1-11ea-9b88-d1b41f4fd9bb.gif)

Looks like the problem comes from this line: https://github.com/processwire/processwire/blob/b77840c14fc1293d2c5bc29663d9fceee45e5254/wire/modules/Inputfield/InputfieldImage/InputfieldImage.module#L1317

### Setup/Environment

* ProcessWire version: 3.0.166

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks.
