### ISSUE TITLE
Image rename not possible when maximum files allowed is 1

### ISSUE THREAD

**Issue by schwaaab** [processwire/processwire-issues#1255]
### Short description of the issue

Image file names can be changed in the admin. If the image field option "Maximum files allowed" is not 0 but 1, the renaming fails.

### Expected behavior

The file should be renamed after page save. 

### Actual behavior

The image name does not get saved on page save. The renaming seems possible though.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/26468756/94603858-20e30c00-0297-11eb-9c2c-d3e48c82d460.png)

### Setup/Environment

* ProcessWire version: 3.0.148
* (Optional) PHP version: 7.4 / 7.3
* (Optional) MySQL version: 10.2.32-MariaDB

**Comment by matjazpotocnik** [comment]
@schwaaab I can't replicate this. Maybe it was fixed already?
![image](https://user-images.githubusercontent.com/7663992/119542739-29410780-bd90-11eb-8c10-61865b142a08.png)

**Comment by schwaaab** [comment]
@matjazpotocnik What version do you have?

**Comment by matjazpotocnik** [comment]
3.0.178

**Comment by schwaaab** [comment]
I tried it with version .165 and .178 and no difference.
The problem only appears when I set maximum allowed files to 1. I can rename the image with the value 0 or 2 or any other value but 1.

**Comment by netcarver** [comment]
@schwaaab Hi Simon, does this still hold true if you try a different "formatted value" for the field?

**Comment by schwaaab** [comment]
@netcarver Yes, I tried automatic and single item.

**Comment by Toutouwai** [comment]
There does seem to be something odd going on. What I experienced with an image field with maxFiles set to 1:

* Renaming the image from "list" mode always works.
* Renaming the image from "proportional" mode always works.
* Renaming the image from "square" mode mostly fails. The only times it worked for me was if I changed to list or proportional mode, then changed back to square mode, then renamed the image.

![image-rename](https://user-images.githubusercontent.com/1538852/119736553-fbfc7280-bed1-11eb-97c6-83fd74768aa6.gif)

**Comment by matjazpotocnik** [comment]
I can always rename the image, regardless of mode. But, in rare situations, there are javascript errors, then rename fails. This is the error:

```
Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'disable'
    at Function.error (JqueryCore.js?v=183:2)
    at HTMLUListElement.<anonymous> (JqueryUI.js?v=1621021081:6)
    at Function.each (JqueryCore.js?v=183:2)
    at init.each (JqueryCore.js?v=183:2)
    at init.e.fn.<computed> [as sortable] (JqueryUI.js?v=1621021081:6)
    at HTMLHeadingElement.<anonymous> (InputfieldImage.js?v=123-1621021080:1026)
    at HTMLDocument.dispatch (JqueryCore.js?v=183:2)
    at HTMLDocument.u (JqueryCore.js?v=183:2)
error @ JqueryCore.js?v=183:2
(anonymous) @ JqueryUI.js?v=1621021081:6
each @ JqueryCore.js?v=183:2
each @ JqueryCore.js?v=183:2
e.fn.<computed> @ JqueryUI.js?v=1621021081:6
(anonymous) @ InputfieldImage.js?v=123-1621021080:1026
dispatch @ JqueryCore.js?v=183:2
u @ JqueryCore.js?v=183:2
```
line 1026 in InputfieldImage.js: $list.sortable('disable');

I also observed that rename leaves orphan admin generated files behind, like `aa.0x260.png` where aa.png is the previous image name.

**Comment by schwaaab** [comment]
@matjazpotocnik I can replicate that javascript error

`Uncaught Error: cannot call methods on sortable prior to initialization; attempted to call method 'disable'
    at Function.error (JqueryCore.js?v=183:2)
    at HTMLUListElement.<anonymous> (JqueryUI.js?v=1622051973:6)
    at Function.each (JqueryCore.js?v=183:2)
    at init.each (JqueryCore.js?v=183:2)
    at init.e.fn.<computed> [as sortable] (JqueryUI.js?v=1622051973:6)
    at HTMLHeadingElement.<anonymous> (InputfieldImage.js?v=123-1622051970:1026)
    at HTMLDocument.dispatch (JqueryCore.js?v=183:2)
    at HTMLDocument.u (JqueryCore.js?v=183:2)`

**Comment by schwaaab** [comment]
@Toutouwai You got it right. I get the error only when I load the page in grid mode. When I switch to left or list mode, I can rename the image. Even when I switch back to grid mode, it works. But having grid as standard, the renaming does not work correctly.

**Comment by ryancramerdesign** [comment]
@schwaaab @matjazpotocnik @Toutouwai Thanks, I was able to reproduce this issue and have pushed a fix. 

> I also observed that rename leaves orphan admin generated files behind, like aa.0x260.png where aa.png is the previous image name.

This was actually a different (and bigger) issue, and is also fixed in the same commit now too.

**Comment by matjazpotocnik** [comment]
The fix works here.

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I'll close this.
