### ISSUE TITLE
ProcessField array to string conversion error

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1258]
### Short description of the issue

When saving field overrides in the context of a Repeater Matrix type, array to string conversion errors occur in ProcessField. I think this is because array_diff_assoc() is used on multi-dimensional arrays.

Screenshot of errors and variable dumps in Tracy:

![2020-10-12_155944](https://user-images.githubusercontent.com/1538852/95700644-0b60df80-0ca4-11eb-8cb8-b638f2795323.png)

### Setup/Environment

* ProcessWire version: 3.0.167

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this

**Comment by Toutouwai** [comment]
Thanks
