### ISSUE TITLE
Live Search on translation page stopped working

### ISSUE THREAD

**Issue by madebymats** [processwire/processwire-issues#126]
### Text shows up under the Live search title on translation page

When translating Form Builder text appeared under the Live search box after saving part of the translation. Live Search stoped working at the same time. See screenshot. The error only appears for the language that has translations. The other languages has the message: _Click here to build search phrase index_

### Expected behavior

Text shouldn't be there and Live Search should work.

### Actual behavior

Text appears and Live search doesn't work. 

### Screenshot

![translate](https://cloud.githubusercontent.com/assets/1630407/21408678/99e42f3a-c7d6-11e6-99f3-caf6f8b95fc8.png)

### Steps to reproduce the issue
I think this happened when translating the Form Builder Module (to Swedish). 

### Setup/Environment
* ProcessWire version: Latest stable (3.0.42)
* Form Builder 3.0

**Comment by ryancramerdesign** [comment]
It looks like the phrase index may have gotten hosed somehow or another. Can you try clicking the "Find files to translate" button – that should force it to rebuild the cache, and hopefully fix the issue.

**Comment by madebymats** [comment]
Clicking the "Find files to translate" button did not solve the issue.

**Comment by ryancramerdesign** [comment]
So far I still can't duplicate this one. Maybe I need to get closer to the exact steps. Which file were you trying to translate when the error occurred? Are there any other specific steps I should take to duplicate the error?

**Comment by madebymats** [comment]
I checked the folder containing the translation files and manually deleted two zip-files (site and core translation) and a a .txt file. This solved the problem. But after indexing the translation files the issue occurred again. 

The txt-translation file is attached:

[phrase-index.txt](https://github.com/processwire/processwire-issues/files/689803/phrase-index.txt)

**Comment by PWaddict** [comment]
@ryancramerdesign I figured why this is happening. Adding the closing tags `</body>` and/or `</script>` inside translatable strings breaks "Live Search". Currently I have 2 modules installed that causing this issue. One of my own and the EmailObfuscator. Is this something that you can fix or should we start removing those tags from the modules?

**Comment by tbba** [comment]
A video to demonstrate the effect...
https://processwire.com/talk/topic/20294-live-search-is-messed-up/?tab=comments#comment-175874
The loading of the page gets interrupted and messes up.

**Comment by rolandtoth** [comment]
In case of the Cookie Management Banner a module field notes contained HTML markup which caused the same issue, even tough it was properly escaped. I needed to  use HTML entities for the "<" and ">" characters:

https://processwire.com/talk/topic/19525-cookie-management-banner/?do=findComment&comment=177988

**Comment by rolandtoth** [comment]
I disagree, the HTML entities is just a workaround, it's the indexer that should take care of that.

**Comment by PWaddict** [comment]
It seems that with HTML entities just removes the whole messed up text but Live Search still remains broken. I will wait for an official fix from @ryancramerdesign.

**Comment by netcarver** [comment]
@ryancramerdesign Does the recent discussion here give you something to go on for this one?

/remind me to review issue in 1 week

**Comment by ryancramerdesign** [comment]
@madebymats @tbba @PWaddict @netcarver I agree that it shouldn't break if you happen to put HTML tags in the translation phrase (though should probably avoid putting HTML in there either way). The thing is, I can't seem to duplicate it, even if I put a closing `</body>` tag in a translatable string. I put this in my /site/templates/sitemap.php file:
~~~~~
__('hello </body> world'); 
~~~~~
Then I refreshed the search index so it was in there, and did the live search and it still worked properly:
<img width="496" alt="screen shot 2019-02-22 at 6 57 30 am" src="https://user-images.githubusercontent.com/328272/53241308-4ba6c080-366f-11e9-9704-27ca5c17e05f.png">

It looks like I can't duplicate the issue here. But it's a simple matter for me to have it strip any tags out of the search phrase index, so I've gone ahead and done that. Please let me know if you continue to observe the issue? Also, make sure you refresh your search index when testing (I added a new link for that next to the live search). Thanks.

**Comment by tbba** [comment]
I do not see the issue any more. The conflicting modules had updated their code in the meantime.

@ryancramerdesign  The problem did _not_ appear here when the original English strings had tags, but if  _translation_ files (German in my case) had tags in their strings. In case that info matters.

The general fix with a filter is welcome. I would not mind closing the issue and reopen it if the problem should re-appear in the future.

**Comment by ryancramerdesign** [comment]
> The problem did _not_ appear here when the original English strings had tags, but if _translation_ files (German in my case) had tags in their strings. In case that info matters.

Thanks @tbba, glad to hear it is working. I tried to cover both cases the fix, just to be thorough. I don't think it's likely to happen again, but let me know of so. I'll close this report. Thanks.
