### ISSUE TITLE
Multilingual CKEditor toolbar buttons requiring double click

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1260]
### Short description of the issue

When a CKEditor textarea is present in a repeater with multilanguage on, its toolbar buttons sometimes require double-clicking to trigger their action.

### Suggestion for a possible fix

Apparently the [LanguageTabs.js](https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/LanguageTabs.js) file is a bit too generous when targetting links, resulting in `<a>`s within the CKEditor having (double-)click handlers added.

(when not in a repeater, only the double-click handler is added to the CKEditor buttons)

A fix would be to be more specific in the selectors here:
https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/LanguageTabs.js#L60
https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/LanguageTabs.js#L182

### Screenshot that demonstrate the issue

<img width="1440" alt="Capture d’écran 2020-10-15 à 14 01 14" src="https://user-images.githubusercontent.com/6616448/96120581-0643a080-0eef-11eb-927a-70590060261f.png">

### Setup/Environment

* ProcessWire version: 3.0.165
* PHP version: 7.1.12

**Comment by ryancramerdesign** [comment]
@romaincazier I can't seem to duplicate the issue here. But I understand the issue from what you've pointed out, it makes sense to me that there should be more specific selectors in those spots. I have gone ahead and done that, but I can't test that it resolves the issue since I can't yet duplicate it. Are you able to test the committed update from there? Thanks.

**Comment by romaincazier** [comment]
It works perfectly with the fix ! Thank you for checking this.

I'm closing the issue.
