### ISSUE TITLE
$sanitizer->url(): allowQuerystring option has no effect

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1261]
### Short description of the issue

When using `$sanitizer->url()` with `allowQuerystring` set to false I expected any querystring to be removed from the sanitized URL. However the querystring remains.

![2020-10-18_134156](https://user-images.githubusercontent.com/1538852/96356203-bca1c280-1147-11eb-8330-61dcf38c79e4.png)

### Setup/Environment

* ProcessWire version: 3.0.167

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai good find, I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
