### ISSUE TITLE
InputfieldText gone since fix of Issue 1260

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1263]
I have a FieldtypeRepeater which contains a FieldtypeRepeater which contains a FieldtypeTable with an Multilang Textfield.

since this Commit: https://github.com/processwire/processwire/commit/09bd61f91d88676395fc7c14e4f9f3e4bb6dac20
which fixes this Issue: https://github.com/processwire/processwire-issues/issues/1260

the Textfield is gone. I see the Tabs of the Languages but the Inputfield itself is not here.

<img width="1377" alt="Bildschirmfoto 2020-10-20 um 22 00 51" src="https://user-images.githubusercontent.com/488163/96639843-95ebb380-1322-11eb-9147-579ad97aab74.png">

MySql: 5.7
PHP 7.4.10

**Comment by ryancramerdesign** [comment]
Thanks @tiefenb I've pushed a fix for this issue. My test case setup was a little different than yours, so please let me know if you find the issue is not resolved.

**Comment by tiefenb** [comment]
Thanks @ryancramerdesign - this fixed it!
