### ISSUE TITLE
Table Field Crash - not possible to edit then

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1264]
I tried to setup a table pagefield to some selection, which obviously was not working.

Then the  field crashed in the backend with 
SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters search

....which means I cannot edit and modify the value to some other way of searching. No access since the crash.

PW version is latest DEV

**Comment by ryancramerdesign** [comment]
@tbba Can you clarify what you mean by a table pagefield? Are you referring to a Page selection field in a ProFields Table field (FieldtypeTable), or are you referring to a FieldtypePageTable field? If its for ProFields Table (not core) can you post this in the ProFields board instead? But if it's FieldtypePageTable then this is the right place. I just want to make sure I know what kind of field we are talking about first. Thanks.

**Comment by tbba** [comment]
@ryancramerdesign I'm sorry, I could not provide any further information at first as long as I had the corrupted database, but I wanted to let you know already. Now I was able to undo this field by hacking the database (thus avoiding a complete rollback with loss of many working hours).

Ok, the problem is the "Pro Fields: Table". I show the problem with 2 screenshots, correct setting and incorrect setting. With the incorrect settings there is an error message even in a soft grey colour. This is easy to overlook.

By the way, the target field "commercial_status" is a "Select Options" field with the settings: 1=A, 2=B, 3=C.

What happened after saving "Table" with the error:
Critical Error for the field edit page and all pages where the field was used.

Expected:
Since ProcessWire can determine that a critical error has occurred, the error should be clearly marked (not grey). It would also be good if the field could not be saved this way. Or that at least the Select selection is reset to default instead of showing a crash during edit. So you can at least fix it.

GOOD

![Bildschirmfoto 7](https://user-images.githubusercontent.com/652879/97082688-cde94400-160b-11eb-8b67-7cbd49a22a8b.jpg)

BAD

![Bildschirmfoto 8](https://user-images.githubusercontent.com/652879/97082686-ccb81700-160b-11eb-8629-b2518783a5d7.jpg)

**Comment by matjazpotocnik** [comment]
@tbba is this still an issue?

**Comment by matjazpotocnik** [comment]
@tbba I can't replicate this.

**Comment by matjazpotocnik** [comment]
@ttba I'm closing this, but please reopen if needed.
