### ISSUE TITLE
Special characters in new usernames when Extended Page Names enabled

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1265]
### Short description of the issue

If you enable [Extended Page Names](https://processwire.com/blog/posts/page-name-charset-utf8/) it is possible to create usernames with special characters like f.e. mäx-müstermänn, but you cannot login with these usernames.

### Expected behavior

Either the new username should be sanitized like normal or it should be able to login with a username containing special characters.

### Actual behavior

After creating a new username with special characters you cannot login with this username.

### Steps to reproduce the issue

1. Enable Extended Page Names in the config file.
2. Create a new user with a username containing special characters.
3. Try to login with this username

### Setup/Environment
SERVER DETAILS
ProcessWire: 3.0.165
PHP: 7.4.9
Webserver: Apache/2.4.46 (Unix) OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
MySQL Server: 5.7.30
MySQL Client: mysqlnd 7.4.9

**Comment by ryancramerdesign** [comment]
Thanks @designconcepts I've pushed a fix for this issue, can you confirm it works for your extended character configuration?

**Comment by netcarver** [comment]
Hi @designconcepts . Just following up on this. Could you check if Ryan's change resolves this for you and report back, closing the issue if appropriate. Thank you.

**Comment by designconcepts** [comment]
Thanks @ryancramerdesign I can confirm that this fix works.
