### ISSUE TITLE
Image tags in a multilingual setup

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1266]
### Short description of the issue

When following this [trick](https://processwire.com/blog/posts/processwire-updates-and-new-field-types/) to have an image per language, I noticed there were languages tabs above the tags input. Clicking on them does nothing, as expected (to me), but then I think they shouldn't be there in the first place.

### Suggestion for a possible fix

Do not display the languages tabs when using image tags.

### Screenshot the issue

![Capture d’écran 2020-10-28 à 17 18 51](https://user-images.githubusercontent.com/6616448/97464857-b8dd1f80-1941-11eb-909c-441a703453f5.jpg)

### Setup/Environment

* ProcessWire version: 3.0.165
* PHP version: 7.1.12

**Comment by romaincazier** [comment]
Actually, to counter this behavior, you can first disable multi-language for descriptions (by ticking the appropriate checkbox) before hiding the description field by putting "0" in the "number of lines" field.

**Comment by ryancramerdesign** [comment]
@romaincazier Thanks for the report. The tags field doesn't support different languages like the description field does, though tags can be predefined and translated. As a result, I'm thinking the language tabs you are seeing must be for the description field? Does that seem to be the case to you also? It's not clear to me why they appear there, assuming you've disabled the description field by setting the number of lines to 0. All of the code that has anything to do with the description field or languages in it is surrounded by an `if(this->descriptionRows > 0) { ...` statement. Though you mentioned that disabling multi-language descriptions before setting its rows to 0 seemed to resolve it?

**Comment by romaincazier** [comment]
Hm that is weird, I tried to reproduce the issue by enabling back the multi-language descriptions and then setting rows to 0, but the tabs are not here anymore...

We can close the issue for now, if I happen to come across this bug again I'll check if it's indeed the tabs for the description field and then update here.

Thanks for checking this anyway.
