### ISSUE TITLE
Custom image fields: checkboxes don't get saved

### ISSUE THREAD

**Issue by daun** [processwire/processwire-issues#1267]
### Short description of the issue

When adding checkboxes as custom image metadata fields, the data doesn't seem to save. Neither in normal page edits nor in Repeater contexts. The data is being transferred as POST data and normal text fields are saving as expected.

Example request data (`video_url` is saved, `autoplay` isn't):
```
video_url_images_1249012c0808866acd48b3015fdaeff6: https://vimeo.com/391193091
autoplay_images_1249012c0808866acd48b3015fdaeff6: 1
```

Example repeater request:
```
video_url_images_repeater1210_66561f4fb1719146c3764ba2ef161aec: https://vimeo.com/391193091
autoplay_images_repeater1210_66561f4fb1719146c3764ba2ef161aec: 1
```

### Expected behavior

Checkboxes are saved and the data in the filedata column will be `1`.

### Actual behavior

Data in the filedata column is `0`.

### Steps to reproduce the issue

1. Add a checkbox field to the image data template (`files-images`)
2. Add an image, check the box, save the page.
3. Check the image metadata (box will be unchecked).

### Setup/Environment
* ProcessWire version: 3.0.168
* (Optional) PHP version: 7.3
* (Optional) MySQL version: 5.7.26

**Comment by Toutouwai** [comment]
I tested this but couldn't reproduce the problem. The checkbox in the image custom fields saved properly in both states.

Screencast:
![cb](https://user-images.githubusercontent.com/1538852/98731835-2c336680-2403-11eb-9078-c2f79365f80e.gif)

**Comment by ryancramerdesign** [comment]
@daun Is the test case that Toutouwai setup consistent with the one that you are using, or can you spot any differences that might account for it? Also, are any field dependencies (show if...) involved?

@Toutouwai Thanks for setting up the test case that you did.

**Comment by daun** [comment]
@ryancramerdesign Thanks, Ryan, you pointed me in the right direction. Looks like a show-if dependency is the culprit here. If I remove that, the checkbox field works as expected.

Are those kinds of dependencies not supported? They do show and hide correctly on the frontend.

**Comment by daun** [comment]
Duplicate of https://github.com/processwire/processwire-issues/issues/1269, closing.
