### ISSUE TITLE
Typos in template documentation

### ISSUE THREAD

**Issue by strugee** [processwire/processwire-issues#1268]
(Omitting the issue template because these are trivial documentation templates, not a code bug - the only reason I'm not PR'ing is because I couldn't find the source code to the docs.)

In the first paragraph of https://processwire.com/docs/start/structure/templates/, there are a few typos: primariy -> primary, and in the same sentence, then -> them.

**Comment by strugee** [comment]
Another one: under "Examples of templates", lets -> let's

**Comment by ryancramerdesign** [comment]
Thanks @strugee I have fixed those typos on the site.

**Comment by strugee** [comment]
Thanks!
