### ISSUE TITLE
InputfieldPassword Javascript Bug

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#127]
### Expected behavior

CSS: text-decoration: line-through; should be added to the span Element with class 'pass-require-minlength' after reaching minlength by JavaScript.

### Actual behavior

The CSS switches immediately after typing the first letter.

### Optional: Suggestion for a possible fix

Since html attribute 'minlength' in input is not well supported _InputfieldText_ removes the attribute resp. change it to 'data-minlength'.
InputfieldPassword.js retrieves the var minlength from 'minlength' attribut (which currently doesn't exist) instead of 'data-minlength'.

Get minlength from 'data-minlength' instead of 'minlength' attribute.
https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/Inputfield/InputfieldPassword/InputfieldPassword.js#L15

Alternatively leave the 'minlength' attribut in InputfieldText additionally to 'data-minlength'
https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/Inputfield/InputfieldText.module#L142

### Setup/Environment

* ProcessWire version: > 3.0.34

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed your suggested fix to the dev branch.
