### ISSUE TITLE
The new abstract Selector-class incorrectly forces the not-property to false

### ISSUE THREAD

**Issue by sforsman** [processwire/processwire-issues#1270]
### Short description of the issue

The new abstract _Selector_-class initializes the _not_-property to `false` in the constructor even though _setField_ has already determined the correrct value for the property.

This has fatal consequences when selectors are created through _Selector_-classes, because inverted operations turn into regular operations. When a _Selectors_-object is constructed from a (selector) string, the _not_-property is set correctly, i.e. string based selectors remain unaffected.

### Expected behavior

When a new selector type is instantiated, the _not_-property must be set correctly based on the name of the field.

### Actual behavior

When a new selector type is instantiated, the _not_-property is always (re-)initialized to `false`.

### Optional: Suggestion for a possible fix

Any initialization of the _not_-property must occur before calling _setField_ in the following constructor:

https://github.com/processwire/processwire/blob/b429de71e33066f611b0bf6e2cc3782b7e5dafa3/wire/core/Selector.php#L193

### Steps to reproduce the issue

```
<?php

namespace ProcessWire;

require 'index.php';

$field    = '!lastname';
$op       = '=';
$value    = 'Smith';
$selector = $field . $op . $value; // !lastname=Smith

// This is the expected result (i.e. selector strings are parsed correctly):
$obj = new Selectors($selector);
var_dump($obj->first()->not); // bool(true)
echo $obj . PHP_EOL; // !lastname=Smith

// This demonstrates the problem when the selector is created from objects:
$obj2 = new Selectors();
$obj2->add($obj2->create($field, $op, $value));
var_dump($obj2->first()->not); // bool(false)
echo $obj2 . PHP_EOL; // lastname=Smith
                      // ^- the exclamation mark (inversion) is lost

// ...or like this by constructing the selector type:
$opClass  = __NAMESPACE__ . '\\' . Selectors::$selectorTypes[$op]; // ProcessWire\SelectorEquals
var_dump((new $opClass($field, $value))->not); // bool(false)
```

### Setup/Environment

* ProcessWire version: 3.0.168

The bug was introduced in 3.0.164 and still exists in the latest (dev) commit. I.e. the bug does not exist in 3.0.148.

**Comment by ryancramerdesign** [comment]
Thanks @sforsman that's a good find. All defaults in the constructor should be set before any method calls there, looks like I got off track there, thanks for finding it. I've pushed a fix for the issue.

**Comment by sforsman** [comment]
Perfect, thank you @ryancramerdesign. We have now finished testing the latest dev and can confirm the issue is resolved.
