### ISSUE TITLE
Impractical admin rendering of PageTable when "page-view" permission only

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1274]
### Short description of the issue

When "page-view" only permission on field of type PageTable,

- Current behaviour : in the admin, the rendering of the field only displays the page IDs of the items (ex : "1234|1235|1236")

    -> this is rather rough ! :-)

- Expected behaviour : display the table/matrix view, as defined in the field's "Input" settings, similarly to the display when "page-edit" permission is set, except that here there should not be any clickable link towards the target pages (well, I guess)

[Code](https://github.com/processwire/processwire/blob/341342dc5b1c58012ae7cb26cffe2c57cd915552/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.module#L13) review (as well as [matjazpotocnik](https://github.com/processwire/processwire-requests/issues/284#issuecomment-473832912) :-) show that this is an identified TODO for class InputfieldPageTable, for quite some time. 
Maybe it's time to consider that the lack of implementation of this TODO is an issue, and it should be fixed ?

Additional point : when "page-edit" permission is also set, but "page-delete" sub-permission is NOT set, then anyway the entries of the pageTable can be removed, with the trashcan icon located in the matrix view. Well, they are not actually deleted, they are removed/disassociated from the PageTable (and can later be added to it again).
Is this the intended behaviour ?
Wouldn't it be more relevant and more clear, that, when there's no "page-delete" permission for a PageTable, BOTH delete AND removal/disassociation would be denied ? (+ the trash icon wouldn't show).

### Screenshots that demonstrate the issue

- 1st screenshot is the display of a PageTable field, where "view" + "edit" permissions are enabled on this field for the target user role :
_(note that this role doesn't have any "page-delete" permissions whatsoever on any associated templates)_

![image](https://user-images.githubusercontent.com/8220747/98362694-fd497900-202d-11eb-839d-19888293ed49.png)

- 2nd screenshot is after disabling "edit" permission on this field for the target user role :
(note : "view" permission is still set, + the access toggle "_Show field in page editor if viewable but not editable (user can see but not change)_" is also checked)

![image](https://user-images.githubusercontent.com/8220747/98362809-2833cd00-202e-11eb-8976-a34fc3fb2ca1.png)

**Comment by ryancramerdesign** [comment]
@er314 Thanks, I have added support for a non-editable view here and have removed the trash icon for non-deletable items.

**Comment by er314** [comment]
very cool, thanks.
