### ISSUE TITLE
FileCompiler cache path does not set via $config->paths->set('cache', ...

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1275]
The FileCompiler->globalOptions['cachePath] is set in `wire/config.php` via `$config->fileCompilerOptions` using the value of `$config->paths->cache` before `$config->paths->cache` may be altered in `site/config.php`. Thus, if we set a custom location for filsystem cache, the file-compiler cache path is not affected. I discovered it using the SettingsFactory module: the module fails to load a compiled file because the FileCompiler cache path is no more inside an allowed path (custom cache path is allowed).

```php
// site/config.php sample custom path config
//...
$config->paths->set('cache', $config->paths->root . 'var/cache/');
//...
``

**Comment by ryancramerdesign** [comment]
@pine3ree While the Paths object might let you do that, it's not something I'd recommend doing because PW isn't designed for it. While it might appear to work, the root `.htaccess` file that protects those paths from http access isn't going to know about your custom paths, so changing these paths is a potential security issue. If you are aware of the security issues and covering it in some other way (like using a cache path outside of the web root), then the FileCompiler cache path can be changed like this in your site/config.php file: 
~~~~~
$config->fileCompilerOptions('cachePath', '/your/new/secure/path/'); 
~~~~~

**Comment by pine3ree** [comment]
> @pine3ree While the Paths object might let you do that, ...

Hello @ryancramerdesign ,

since I have always prefer using a linux/unix dir structure with variable files inside a `/var` folder for my web projects as well I have always used the following config:

```php
// file site/config.php
//..
$root_path = $config->paths->root;
$root_url  = $config->urls->root;

$config->paths->set('sessions', $root_path . 'var/session/');

$config->paths->set('logs', $root_path . 'var/log/');
$config->urls->set('logs', $root_url . 'var/log/');

$config->paths->set('cache', $root_path . 'var/cache/');
$config->urls->set('cache', $root_url . 'var/cache/');

$config->paths->set('tmp', $root_path . 'var/tmp/');
$config->urls->set('tmp', $root_url . 'var/tmp/');.
//..
```
and I prefer keeping only real-web-assets - such as images or downloadable files - inside the assets dir.

As you explained I always add these files to .htaccess configuration (even if in my opinion having them outside the webroot would be even better).

What I was trying to suggest is that the file-compiler cachePath is set to its default value, relative to cache-path, inside the default/base/wire configuration file, using another config value before the custom/site config file is read and before its changes have been applied.  I believe it woud be better having a blank default path in `wire/config.php` and use a default fallback value `$this->wire('config')->paths->cache . 'FileCompiler/'` in the class itself. I am not sure I am being very clear :-) Let me try this way: the default configuration file should not reference configuration values that may be overriden in the customizable configuration file. Inside class files wire/config and site/config are both already processed, so overriden values are set. 

The line you suggested is of course what I used in my config, but in my mind, having set a custom cache path I expected that to be done automatically.

thanks and kind regards,
maks

**Comment by ryancramerdesign** [comment]
@pine3ree Okay, I understand what you mean now. You are right it does make sense for that to be left blank in the wire/config.php, so that FileCompiler instead determines it dynamically. Thanks.

**Comment by pine3ree** [comment]
You are welcome @ryancramerdesign . Kind regards!
