### ISSUE TITLE
Page field not shown as link inside Repeater field

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#128]
### Short description of the issue

Page field in AsmSelect mode inside Repeater, doesn't show the edit link when option is enabled. I have also tested on a clean instalation with the same PW version.

### Expected behavior

Page selections made through the field, should appear as a link.

### Actual behavior

Page view links are not showed whe viewed inside a Repeater 

### Screenshots/Links that demonstrate the issue

http://imgur.com/Og23U1v - Image with hovered page field selected option, inside repeater.
http://imgur.com/gG0aI9j - Same field but added to the page, behaves as expected.

### Steps to reproduce the issue

1. Setup repeater
2. Setup page field
3. Add page field to repeater

### Setup/Environment

ProcessWire: 3.0.45
PHP: 5.6.29
Apache: 2.4.18 (Unix) OpenSSL/1.0.1f
MySQL: 5.5.53-0ubuntu0.14.04.1-log

allow_url_fopen: 1
max_execution_time: 30 (changeable)
max_input_nesting_level: 64
max_input_time: -1
max_input_vars: 5000
memory_limit: 256M
post_max_size: 1G
upload_max_filesize: 512M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: 

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 1
FreeType: 1
Imagick Extension: 1

FieldtypeRepeaterMatrix: 0.0.3
HelperFieldLinks: 1.0.8
ImageExtra: 1.0.1
InputfieldRepeaterMatrix: 0.0.3
PageGIM: 0.1.0
TracyDebugger: 3.5.0

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue in the latest commit to the dev branch.

**Comment by elabx** [comment]
Hi! I have detected this same behaviour with Repeater Matrix fields, when the Repeaters are rendered collapsed for the first time.
