### ISSUE TITLE
Invalid form submissions are persisted

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1280]
Hello, I noticed a strange behaviour when saving a page. It happens in all my installed pw versions (from 2.7 to 3.0.165).

Suppose you edit a page, set an empty Title field and save.
The form processor complains about the missing required field, but the page is persisted and the title field value is gone from the database. You can also use the view link on page-edit page and you'll see that the title actually disappeared.

This may have sensible consequences:

- If a user edits a page removing a missing field and forgets to complete the operation (phone call, etc etc), the page will be published with invalid state maybe for hours or days. The same happens with a price field for a product page. 
- If a user empties by mistake a long required text/textarea field it will be completely lost even if the user dismiss page-editing

Is there a way to stop field persistence on missing/invalid input?

kind regards

**Comment by ryancramerdesign** [comment]
@pine3ree This is the intended default behavior, but it's also something you can modify on a per template basis if you want to. See Setup > Templates > [your-template] > Advanced > Required field action. This lets you specify whether to just alert the user (default), un-publish the page, or restore the previous value.

**Comment by pine3ree** [comment]
@ryancramerdesign Thanks!

**Comment by pine3ree** [comment]
@ryancramerdesign Sorry, I do not understand how I forget that...here's a bit of code in one of my modules:
```php
    // if the json values of the processed MetaTags are different from the
    // previous, then flag this Inputfield as changed so that it will be
    // automatically saved with the page
    if ($newValue->toJSON() !== $value->toJSON()) {
        $errorAction = $this->page ? (int)$this->page->template->errorAction : 0;
        if ($valid || $errorAction !== 1) {
            $this->trackChange('value', $value, $newValue);
        } else {
             if ($errorAction === 1) {
                $this->error($this->_('Restored previous value'));
            }
            $this->resetTrackChanges(); 
        }
    }
```

**Comment by pine3ree** [comment]
Hello @ryancramerdesign 

I was able to recreate the desired behaviour of commonly used post-redirect-get form submissions in custom forms using pw forms api. I basically check all the inputfields for errors and store their invalid values into the session (as it's done for the error messages) and skipping persisting anything to the database when any error is present. When the page reloads (after post+reload=get) presenting the form and its errors I ovewrite the inputfields valid data loaded from the db with the invalid submitted data from the session, if any. In this way db valid data is preserved, but the form displays the last submitted data

kind regards
