### ISSUE TITLE
PageReference field visibility option (Locked) raises an error

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#1283]
### Short description of the issue

When the PageReference field uses Repeater as values ​​and visibility set "Open when populated + Closed when blank + Locked (not editable)" this results in an error.

### Expected behavior

When the PageReference field uses Repeater as values ​​and visibility is set "Open when populated + Closed when blank + Locked (not editable)" this results in an error.
> Too few arguments to function ProcessWire\RepeaterPageArray::__construct(), 0 passed in /wire/core/WireData.php on line 438 and exactly 2 expected

When the visibility is set to "Closed + Locked (not editable)" an error also occurs.

No error detected when selecting other visibility parameters.

### Steps to reproduce the issue

1. Create Repeater field (test), add field (title), add test field to any template.
2. Create items in repeater.
3. Create PageReference field (reference), set input field type "select", set selectable pages setting "template=repeater_test".
4. Set visibility in "Open when populated + Closed when blank + Locked (not editable)" or "Closed + Locked (not editable)".
5. Add reference field to any template.
6. Go to page edit with reference field and get error.

### Setup/Environment

* ProcessWire version: 3.0.165
* PHP version: 7.2.31

**Comment by matjazpotocnik** [comment]
@germankirichenko is this still relevant? Could you test on the latest dev version?

**Comment by germankirichenko** [comment]
@matjazpotocnik Hi! I will test it next week and write the result.

**Comment by matjazpotocnik** [comment]
@germankirichenko, did you manage to test?

**Comment by germankirichenko** [comment]
SERVER DETAILS
ProcessWire: 3.0.200
PHP: 7.4.28
Webserver: nginx/1.21.6
MySQL Server: 5.7.37
MySQL Client: mysqlnd 7.4.28

@matjazpotocnik, the error does not appear, everything works.
