### ISSUE TITLE
3.0.165 & latest dev: wakeupLinks() in MarkupQA.php returns wrong livePath, if multi language is used

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#1285]
### Short description of the issue

In Admin, create a simple language switch like this:
* I'm using a setup with two languages (let's call them default and language2).
* I have created a simple page with a multi-language textarea with CKEditor enabled.
* Now I enter a link in the language tab of the first language (default): this link should simply switch to language2 in frontend view (something like `<a href="/language2/mypage/">Language 2</a>`)
* I do the same in the language tab of the second language (language2): this link should simply switch to default in frontend view (something like `<a href="/mypage/">Default</a>`)

**Problem is:**
* Now, if I try this in frontend, it works when I'm on the default language (path: /mypage/). The link correctly leads to /language2/mypage/.
* But if I'm on the /language2/mypage, the link on that page does not point to /mypage/. It leads to /language2/mypage/ - yes, it basically links to itself and doesn't point back to the default language. That's obviously wrong.

### Observations so far
The entries in the database for that multilanguage field are correct. The links are saved like this: `<a data-pwid=1234-1020	href="/language2/mypage/">Language 2</a>` and `<a data-pwid=1234 href="/mypage/">Default</a>`.

The "data-pwid" attribute is part of ProcessWires Markup Quality Assurance. The class for this is MarkupQA.php. The interesting part for this problem is at line number 521:
```
$livePath = $this->wire('pages')->getPath($pageID, array(
    'language' => $language,
));
```
ProcessWire returns the path of the page with that data-pwid here. But getPath() defined in PagesLoader.php has another parameter in it's function definition: 'useCache'. If you inspect that method, you see that 'useCache' is true by default. That leads to the error which has been described.

### Temporary fix
The method call in MarkupQA.php has to be modified like this:
```
$livePath = $this->wire('pages')->getPath($pageID, array(
    'language' => $language,
    'useCache' => false
));
```
I have no idea if there might be other consequences by disabling the cache (I guess it's slower as before). But it cures the error and the language switch works.

I wonder how that fix can be made permanent without patching the wire files, because this obviously does not survive the next updates without patching again.

* ProcessWire version: 3.0.165 and the latest dev version as well

**Comment by processwired** [comment]
I temporarily solved that problem with a hook in ready.php for now, which feels a bit hacky – but it's much better than to patch the core at least.
```
$wire->addHookAfter('FieldtypeTextarea::sleepValue', static function (HookEvent $event) {
    $page = $event->arguments(0);
    if($page->id !== 12345) { // or use any other condition
        return;
    }

    $values = $event->return;
    foreach ($values as &$value) {
        if(strpos($value, 'data-pwid=') === false) {
            continue;
        }
        $value = preg_replace('/\tdata-pwid=[-\d]+\t/', ' ', $value);
    }
    $event->return = $values;
});

**Comment by ryancramerdesign** [comment]
@processwired It sounds like you might be on to something with regard to caches, but before we look closer at that I want to make sure I understand first the behavior you are describing. The way I'm reading it, it sounds like the intended behavior for link abstraction. When you are in a non-default language, it keeps you in that language by correcting default language links to be updated for the current language. It doesn't do this in the default language where it's less likely to be useful. That's because content usually originates in the default language and is translated to other languages. When someone is translating copy (or pasting it in) they don't have to figure out and redo all the links, the links update automatically. This is a behavior I know many depend on. But if you are trying to build a language switcher directly in CKEditor, then that's a case where it isn't helpful. For that case you'd want to use full http URLs or keep the language switcher out of the content if possible. Let me know if I've misunderstood what you are describing?

**Comment by processwired** [comment]
Thanks for the explanation, Ryan. You're guess is right - it's a language switcher directly in CKEditor. I double checked that full http urls are used, so this does not fix the problem. The second idea - keeping it out of CKE - is not feasible, as the editors want to place the links wherever they want (that decision is out of my control). I think I'll try something basen on Hanna Code or I'll go the route with that hook posted above and make that configurable. I'm closing this issue.

**Comment by teppokoivula** [comment]
Just for the record, this seems like the same issue as https://github.com/processwire/processwire-issues/issues/1244. In that case the users also wanted to create links between language versions, which currently fails. In my case the (perhaps temporary) solution was to disable link abstraction altogether.

In my opinion this is a rather problematic — and surprising — feature, and thus I'd very much prefer it to at least be configurable.

**Comment by processwired** [comment]
Oh, thanks for that reference, I hadn't found issue [#1244](https://github.com/processwire/processwire-issues/issues/1244) before I started this one here. You explained it much better than me :)

If you have link abstraction disabled, how do you deal with renamed pages? Won't the links in CKEditor break over time?

**Comment by teppokoivula** [comment]
> Won't the links in CKEditor break over time?

Simply put: yes, they may break over time. That's the downside with that approach. On that particular site those links were quite common, and I really didn't want the client to have to go through obscure extra steps to make this work — creating some links using special tags or something along those lines — so this was still a better approach in my opinion :)

I still hope that one day the core will be able to handle link abstraction without messing with links between language versions.
