### ISSUE TITLE
PHP 8 - Too few arguments to function ProcessWire\WireHttp::_errorHandler(), 4 passed and exactly 5 expected

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1286]
I think this screenshot from Tracy should give you what you need to know, but let me know if you need more details. This came when running the PW Upgrade module and it actually stems from the ModuleReleaseNotes module, but I think the issue is coming from the PW core.

![image](https://user-images.githubusercontent.com/871211/100525296-67a89180-3174-11eb-8d02-f0d9db0418e3.png)

**Comment by adrianbj** [comment]
Just got the same error when viewing the frontend of my site which uses the cookie management banner. In both cases, `WireHttp` is being called.

**Comment by cb2004** [comment]
I can confirm this with PHP 8 and the upgrade module. No modules installed you mention so core issue.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj @cb2004 It looks like PHP 8 has dropped the `$errcontext` argument for `set_error_handler()` functions, so I have updated it so that it's optional.

**Comment by cb2004** [comment]
I get a new error now:

Fatal Error: Uncaught TypeError: Cannot access offset of type string on string in site/modules/ProcessWireUpgrade/ProcessWireUpgradeCheck.module:336

**Comment by adrianbj** [comment]
@cb2004 - I am not seeing that - any chance you could find out the value of `$key` and `$info` for that iteration of `$data`. Seems to me like it might be a problem with a particular installed module (or at least the data for that module).
