### ISSUE TITLE
Files and Images Fields Use Tags Require Multiple Saves to Take Effect

### ISSUE THREAD

**Issue by kongondo** [processwire/processwire-issues#1287]
### Short description of the issue

**Use Tags** for Files and Images fields requires multiple saves to take effect at the database level. The fields database table is not altered to add the column _tags_ until after multiple saves. The issue also affects enabling tags for these type of fields via the API ($f->useTags = 1).

### Expected behavior

**Use Tags** for Files and Images fields should work after first save both when using the GUI and the API.

### Actual behavior

**Use Tags** for Files and Images fields does not work until after multiple saves if using the GUI and does not work at all if using the API.

### Optional: Screenshots/Links that demonstrate the issue
Forum discussion [here](https://processwire.com/talk/topic/24718-create-field-with-tags-enabled/).

### Optional: Suggestion for a possible fix

None.

### Steps to reproduce the issue

1. Create new a field of type Images OR Files.
2. Enable Use Tags in the field's Details Tab by selecting '_User enters tags by text input_'.
3. Save the field.
4. The setting is saved but the Database is not altered (Tags column not created for the field).
5. In Actions tab, add the field to a template, save.
6. Edit a page that uses template in # 5.
7. ProcessWire throws an error: **WireDatabasePDO: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_you_field_name.tags' in 'field list'** (Tags column still not created for the field).
8. Edit the field again and disable tags, save.
9. Reenable tags, save. 
10. Now it works. Tags column is created.

### Setup/Environment

* ProcessWire version: 3.0.167
* (Optional) Any 3rd party modules that are installed and could be related to the issue: None

**Comment by netcarver** [comment]
@kongondo Francis, do you know if anyone else on the forum is hitting this issue?

**Comment by kongondo** [comment]
Yes, @adrianbj.

**Comment by adrianbj** [comment]
Yeah @netcarver - I tested and confirmed the issue.

**Comment by ryancramerdesign** [comment]
@kongondo So far I can't duplicate it here. I followed the instructions as written and tried for 2 different files fields, creating them anew. I'm testing on a blank installation, are there any other factors I need to include? Is the error message that you see one that halts the request, or is it appearing as a notification? 

As for when the tags are added to the DB schema, this is done once something asks for the DB schema from the FieldtypeFile::getDatabaseSchema() method -- in this case the page editor. If the current settings differ from the current schema, it alters the table for the updated schema on the fly. This seems to be working as intended in testing here, but I'm guessing there's something I'm missing... is there anything more you are doing between steps 6 and 7 to get the error to appear? When I didn't get any errors editing the page, I tried uploading files, adding tags, saving page, etc. Anything else I should try?

**Comment by kongondo** [comment]
@ryancramerdesign 

If editing a page using the GUI, the error message appears as a notification. If creating a page via the API, the error halts the operation related to adding files to the field (the page itself is created).

As per you explanation when the tags are added to the DB schema, how does that work if we want to enable tags using the API? i.e, $field->useTags=1 alone does not work.

There is nothing else I am doing between steps 6 and 7. However, I did try adding the field to a template using the two GUI methods, i.e. (i) adding via Actions Tab when editing the field and (ii) adding to via editing the template itself. Both produced the same results.

I have tested both in a multi-site setup (one core, different databases) as well as a standalone site. Let me test again on a fresh standalone install but this time I'll screen record the whole thing. This way, I can more clearly see the steps.

**Comment by kongondo** [comment]
@ryancramerdesign,

I have gotten to the bottom of this. The issue was not creating file/image fields via the GUI. Nor was it creating file/image fields via the normal API method:

````php
// WORKS FINE
$f = new Field();
$f->type = $modules->get('FieldtypeFile');
$f->name = 'test_tags_issue';
$f->label = 'Test Tags Issue';
$f->useTags = 1;
$f->save();
````
Instead the issue was when using **setImportData()** to create a field and the import data contains a **fileSchema**. In my case, I had **fileSchema** set at **7**. Removing this entry altogether resolved the issue. I am closing this issue as solved. 

In case someone wants to reproduce the issue:
1. Create a file/imge field using the API and using setImportData() method.
2. In the import data, set a fileSchema, e.g. 7.
3. Also set useTags, e.g. 1.
4. In the GUI, edit the field and add it to a template in its Actions Tab.
5. Edit a page using this template.
6. An error is thrown. If you examine the table for this field in the database, no tags column was created (due to the fileSchema being declared).


Thanks.
