### ISSUE TITLE
Notice when editing page that has created_user_id of an deleted user

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#1292]
### Short description of the issue

When you edit page where created user has been deleted you get an notice "Trying to get property 'id' of non-object.

### Expected behavior

No notice should be thrown. UI wise probably should be shown something like "removed user" on settings tab?

### Actual behavior

Notice is shown. In our environment we use Whoops to catch all exceptions (also notices), so this shows us an error page like this (with good debug info):

![image](https://user-images.githubusercontent.com/131855/102321371-40303200-3f86-11eb-8b44-fc2dde0553d2.png)

In usual PW-admin without whoops, you probably get an technical error message somewhere?

### Optional: Suggestion for a possible fix

We should check that getUser() actually returns an object - or make sure it always returns an object (like NullPage()).

### Steps to reproduce the issue

1. Create page
2. Completely delete the user that created page in step 1
3. Edit page again with another user

* ProcessWire version: 3.0.169 
* (Optional) PHP version: 7.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: We catch errors with whoops.

**Comment by ryancramerdesign** [comment]
Thanks @apeisa - the getUser() method is only allowed to return a User or NullPage and it's not yet clear to me how a non-object is coming out of it, but I have added some additional checks that should ensure it always returns either a User or NullPage (always an object).

**Comment by netcarver** [comment]
@apeisa Hi Antti, can this be closed now?

**Comment by netcarver** [comment]
Ok, closing this, Antti. Let me know if it needs re-opening.

**Comment by apeisa** [comment]
Sorry, totally missed this. Looked through the commit and this most probably fixes the issue (haven't tested yet). Thanks!
