### ISSUE TITLE
function User::isLoggedin() does not take in account a valid session

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1293]
### Short description of the issue

e. g. check if superuser is loggedin

`$pages->get(41)->isLoggedin()`
returns always **true** even if superuser is not logged in

`$pages->get(41) // object(ProcessWire\User)`
returns an instance of user. The user instance is not only the loggedin user. It can be any.
The function **isLoggedin()** does not take in account a valid session. It checks only against the guest user id

### Expected behavior

`$pages->get(41)->isLoggedin()`
should return false if superuser is not logged in.

### Setup/Environment

* ProcessWire version: 	3.0.169

**Comment by adrianbj** [comment]
There's a thread about it somewhere (but I can't find it) - you can only use `isLoggedin()` on the current `$user`.

So if you are looking for a superuser: `$user->isSuperuser()`

**Comment by kixe** [comment]
@adrianbj 
Thanks for the feedback, but I'm not looking for the superuser. The **isLoggedin()** function should return a correct result. `$pages->get(41)` and `$user` are both instances of **ProcessWire\User** and **isLoggedin()** is a method of this class and should tell me whether the related instance is logged in or not.

**Comment by adrianbj** [comment]
I agree it's a bit weird that it doesn't work the way you are suggesting, but isn't it as simple as doing this:
![image](https://user-images.githubusercontent.com/871211/102523231-19d4ca00-404c-11eb-86da-745d641af4f8.png)

**Comment by adrianbj** [comment]
Or even just getting the ID from $user
```
if($user->id === 41)
```

That will tell you if the current user is the one you are looking for. I know you know this, so perhaps I am not actually understanding what you're trying to do.

**Comment by kixe** [comment]
I stumbled upon this bug (I still believe it is a bug and the function should return the result I expect) because I have been trying to access multiple users, i.e. all currently loggedin user(s) of multiple ProcessWire instances. Unfortunately I have not managed so far. The `$user` and `$session` var is not set correctly in this case. Therefore I tried to get the current user via looping `$users` or `$pages`. I will open another thread and link it to this one – see next comment.

```
$xy = new ProcessWire($config->paths->root . 'site-xy/');
$userIDs = $xy->users->findIDs('check_access=0');

foreach ($userIDs as $userID) {
	$u = $xy->pages->get($userID);
	if ($u->isLoggedin()) break; // breaks at any user except guest user
}
```

**Comment by kixe** [comment]
https://github.com/processwire/processwire-issues/issues/1294

**Comment by kixe** [comment]
> There's a thread about it somewhere (but I can't find it) - you can only use `isLoggedin()` on the current `$user`.

Maybe I found it: https://github.com/processwire/processwire-issues/issues/1039

**Comment by adrianbj** [comment]
Yup - that's it :)

**Comment by ryancramerdesign** [comment]
@kixe I think it would be cool if the isLoggedin() method could tell us about users other than the current user, but I don't know how that would be implemented, if it's even possible. I'll have to keep thinking about that, would be nice to have. As it is currently, isLoggedin() is the reverse of isGuest(). It's only meant to apply to the current $user API variable and on the User object just by necessity. If I had to start over, I might make it `$session->isLoggedin()` instead.

**Comment by kixe** [comment]
@ryancramerdesign 
As a minimum the function should work only for the instatiated wire('user') and not for every user object.
```
/**
 * Is the current user logged in?
 *
 * @return bool
 *
 */
public function isLoggedin() {
	if ($this != $this->wire('user')) throw new WireException('Method isLoggedin() is available only for the current user object and not for every user.');
	return !$this->isGuest();
}
```

**Comment by ryancramerdesign** [comment]
@kixe While I don't want this method to throw an exception like you indicated (would prefer it just return false), I do think the comparison to the current user API var is a good addition. I have added that and also updated the phpdoc to be more clear about what the return value of this method indicates.
