### ISSUE TITLE
Session and user variable are not set correctly in multiple instances

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1294]
### Short description of the issue

In an environment with multiple ProcessWire instances, the `$session` and the `$user` variable are not set correctly.

### Steps to reproduce the issue

1. Create two ProcessWire installations each with individual session name which allows independent sessions in both instances.
```
$config->sessionName = 'wire0'; // site/config.php
$config->sessionName = 'wire1'; // site-xy/config.php
```
2. Bootstrap one inside the other
```
$xy = new ProcessWire($config->paths->root . 'site-xy/');
```
3. Login a user (e. g. with ID = 14179) in the bootstrapped instance

4. Try to get the loggedin user with ID = 14179
```
var_dump($xy->session->isValidSession(14179)); // false, should be true
var_dump($xy->user->isLoggedin()); // false, should be true
```
---

 If  I use the `$pages`, the `$users`, `$config` or any other API of the `$xy` instance generally I get what I expect. e. g.

```
$userIDs = $xy->users->findIDs('check_access=0');
var_dump(count($userIDs)); // correct number of users in related instance
var_dump($xy->config->sessionName); // wire0
var_dump($config->sessionName); // wire1
```
except function **Users::getCurrentUser()**

```
var_dump($xy->users->getCurrentUser(); // returns 40 instead of 14179
```
### Setup/Environment

* ProcessWire version: 3.0.169
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by kixe** [comment]
Now I tried to get the current user via **SessionHandlerDB**. Strange behaviour here as well ...

```
$xy_sessions = $xy->modules->get('SessionHandlerDB')->getSessions();
var_dump(array_column($xy_sessions, 'user_id')); // returns array(40) instead of array(41)
```

Visiting a page of the instance (A) where the user is loggedin the DB Table shows up correctly **(screenshot)**

![Bildschirmfoto 2020-12-18 um 13 27 22](https://user-images.githubusercontent.com/4683120/102614635-dbffa080-4134-11eb-8046-848227f5ec67.png)

If I switch to the instance (B) where instance (A) is bootstrapped  SessionHandlerDB makes the loggedin user a guest and changes the DB entry to **(screenshot)** but the superuser is still loggedin in instance (A)

![Bildschirmfoto 2020-12-18 um 13 27 02](https://user-images.githubusercontent.com/4683120/102614653-e457db80-4134-11eb-9eb9-7d764dff7a74.png)

Explanation:
**If a Processwire instance is instatiated within another, the user of this instance is set to the guest user via SessionHandlerDB::write() but can be set with Users::setCurrentUser() (see below)**

**Comment by kixe** [comment]
Possible solution using a setup with multiple sites ([multiple databases Option #1)](https://processwire.com/docs/more/multi-site-support/), module **SessionHandlerDB** and different session names for each instance. Put this code in your **ready.php**

```
$xy = new ProcessWire($config->paths->root . 'site-xy/');

/**
 * if a session AND a challenge cookie is present we check if the user is still loggedin in xy
 * if yes we set the @var wire('user') to the xy instance
 *
 */
if ($xy->session->hasCookie() && $xy->session->hasCookie(true)) {

	// get xy session ID
	if ($xy>config->https && $xy->config->sessionCookieSecure) {
		$cn = $xy->config->sessionNameSecure;
			if (!$cn) $cn = $xy->config->sessionName . 's';
	} else {
		$cn = $xy->config->sessionName;
	}
	$SID = $input->cookie->$cn;

	// set the wire('user') if loggedin
	if ($SID) {
		$SHDB = $xy->modules->getModule('SessionHandlerDB', array('noPermissionCheck' => true))->getSessionData($SID);

		if ($SHDB['user_id'] != 40) {

			// get fingerprint and session timestamp
			$fp = isset($SHDB['data']['Session']['_user']['fingerprint'])? $SHDB['data']['Session']['_user']['fingerprint'] : false;
			$ts = isset($SHDB['data']['Session']['_user']['ts'])? (int) $SHDB['data']['Session']['_user']['ts'] : 0;

			// validate fingerprint
			if ($xy->session->getFingerprint() !== $fp) {
				$this->session->error(__('Unable to assign XY user. XY-Session fingerprint does not match.'), Notice::debug | Notice::log);
			}

			// check if session timed out
			else if ($xy->config->sessionExpireSeconds && $ts < (time() - $xy->config->sessionExpireSeconds)) {
				$this->session->error(__('Unable to assign XY user. XY-Session timed out.'), Notice::debug | Notice::log);
			}

			else {
				$_user = $xy->users->get($SHDB['user_id']);
				if ($_user->id) {
					// session valid, assign user & user_id will be set correctly in DB via SessionHandlerDB::write()
					$xy->users->setCurrentUser($_user);
				}
			}
		}
	}
}
```

**Comment by ryancramerdesign** [comment]
@kixe As far as I know, neither ProcessWire nor PHP can maintain two different sessions for a single request. Only the first instance can maintain a session, which would be the instance serving the web request. A session on the 2nd booted instance would not apply, because it's essentially a CLI instance. So I recommend not even thinking of $session on a separately booted instance because it's not applicable. You could set a $user variable for that 2nd instance if you wanted to, but any session has got to be exclusive to the instance serving the web request.

**Comment by kixe** [comment]
@ryancramerdesign In general you are right, but PHP session is not exactly the same like ProcessWire session. Some functions of the class indeed use PHP session functions or the global `$_SESSION` and are therefore dependent on PHP session, e.g. `Session::set()`, `Session::get()`, `Session::login()`, `Session::logout()` ...

Fortunately, the functions `Session::getFingerprint()` and `Session::hasCookie()` are independent of PHP session. In my workaround, `$session->hasCookie(true) `checks whether there is a challenge cookie associated with the corresponding instance. This is possible because I use different cookie names for my different ProcessWire instances. With the cookie value and a database query (SessionHandlerDB) I can check whether the current user is loggedin in another ProcessWire instance regardless of the current PHP session.

My way of setting the current user of another instance is already working fine. Probably my use case is too specific to add a function e.g. in SessionHandlerDB. In this respect, this thread can be closed.
