### ISSUE TITLE
Caching a JSON string value converts to an array

### ISSUE THREAD

**Issue by brlnr23** [processwire/processwire-issues#1295]
### Short description of the issue

When trying to cache a JSON string WireCache converts it into an array which leads to a "Array to string conversion" notice and it stores the wrong value

### Expected behavior

A JSON string should be stored as string in the table.

### Actual behavior

The string "Array" is stored

### Optional: Suggestion for a possible fix

Not sure how this could be fixed, but I am pretty sure, that this is line causes the issue:
https://github.com/processwire/processwire/blob/dev/wire/core/WireCache.php#L453

### Steps to reproduce the issue

You can use this code in any template file you have:

```
$testArray = array(
	"a" => 1,
	"b" => 2,
	"c" => 3,
);
$testString = json_encode($testArray);

echo "<pre>testArray: ".print_r($testArray,true)."</pre>";
echo "<pre>testString: ".print_r($testString,true)."</pre>";

// cache values
$cache->save("as-array", $testArray);
$cache->save("as-string", $testString);

// get values from cache
echo "<pre>testArray: ".print_r($cache->get("as-array"),true)."</pre>";
echo "<pre>testString: ".print_r($cache->get("as-string"),true)."</pre>";

```

the above code outputs the following

```
testArray: Array
(
    [a] => 1
    [b] => 2
    [c] => 3
)
testString: {"a":1,"b":2,"c":3}
testArray: Array
(
    [a] => 1
    [b] => 2
    [c] => 3
)
testString: Array

```

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.165|
|PHP|7.4.11|
|Webserver|Apache/2.4.29 (Ubuntu)|
|MySQL Server|5.7.32-0ubuntu0.18.04.1|
|MySQL Client|mysqlnd 7.4.11|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|2M|
|xdebug||
|xdebug.max_nesting_level|256|
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.0|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|MarkupGoogleRecaptcha|2.0.0|
|MarkupImageSitemap|0.0.2|
|PrivacyWire|0.2.4|
|ProcessTracyAdminer|1.1.0|
|TextformatterPrivacyWire|0.0.6|
|TracyDebugger|4.21.34|
|chunkRenderer|0.0.1|
</details>

**Comment by adrianbj** [comment]
At a quick glance, I think this is related to this: https://github.com/processwire/processwire-issues/issues/919

**Comment by brlnr23** [comment]
Can confirm. It's the same issue. Closing this report as duplicate.
