### ISSUE TITLE
Template losing data on image->size() operation with missing image file

### ISSUE THREAD

**Issue by nzmuzzer** [processwire/processwire-issues#1298]
### Short description of the issue

Template data is returned to default upon failed image operation. In my case the major resulting impact/effect is to lose the slashUrls setting for the template resulting is total site failure from endless redirects.
This is an upgrade from v2.7 where this did not happen.

### Expected behavior

$image->size() should size image only and not affect page template.

### Actual behavior

Template loses data and returns to containing default PW data.
This occurs when a page has an image field but for some reason the actual image file for the field is absent in the filesystem. Upon calling the $image->size() method all data for the page template is reverted to default.

### Optional: Suggestion for a possible fix

My temporary fix is to check the image filesize is not zero before performing the $image->size() operation. But obviously something else odd is happening here as this should not be necessary.

### Setup/Environment

* ProcessWire version:3.0.165
* PHP version: 7.2.34-8
* MySQL version: 5.7.32
* OS: Ubuntu 18.04

**Comment by teppokoivula** [comment]
This seemed potentially problematic, so did a quick test but so far I've been unable to reproduce the issue. Same version of ProcessWire and same PHP version on Ubuntu 16.04, so nearly-identical environment in this regard.

Can you think of any other factors? In my case I added an image to an image field, then removed the files manually from the disk, and finally added call to $page->image->size(1024) to the template file. That doesn't seem to trigger the described behaviour.

You wouldn't happen to have custom code or modules that hook into Pageimage::size(), or some related methods? Is this a "regular" core image field and not CropImage or something similar?

**Comment by nzmuzzer** [comment]
Further investigation:
I've removed all non-core modules and still seeing the issue. Image is a simple pageImage ("core" image field)
But it gets more bizarre. This is the code which loops through the page images and is causing the problem:

`foreach($room->smRoomImages as $image)
{
   $options = array( 'quality' => 80, 'upscaling' => false );
   $thumb1 = $image->size( 250,180, $options );
   $html .= "<img src='$thumb1->url' width='46%' height='' />";
}
`

I excluded the three lines in the loop and the problem resolved so I assumed it was the size() method causing the issue - but it is actually the next line in the loop - if I remove just the $thumb1->url from next line (leaving the img src attr empty as follows:) the issue vanishes.


`foreach($room->smRoomImages as $image)
{
   $options = array( 'quality' => 80, 'upscaling' => false );
   $thumb1 = $image->size( 250,180, $options );
   $html .= "<img src='' width='46%' height='' />";
}
`

I realise this sounds just ridiculous but it is totally consistent - I've run this dozens of times with the described result with and without the "$thumb1->url".
I can't replicate this on v2.7. I'm leaning towards this being and upgrade issue, something gone sideways in the change from 2.7 database to 3.0 system. Otherwise it should be reproducible surely.

Apologies if code is not formatting on separate lines, new to Github and can't seem to get it to format right in the preview.

**Comment by nzmuzzer** [comment]
Have reinstalled PW3 three more times and cannot now replicate this in any of those instances although the code and setup seems to be identical. I am baffled as to what the issue was but it appears to be an unexplained glitch which has not disappeared. Thanks to those who tried to assist and replicate this issue.
