### ISSUE TITLE
Zip upload of modules without wrapping folder (Helloworld)

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#13]
> Briefly describe the issue.

When installing the Helloworld.module via the .zip upload it's creating a folder structure like this:

> What did actually happen?

```
├── modules
│   ├── Helloworld.module
│   ├── Helloworld
│   │   ├── Helloworld.module
```

This way the updated module is never found even by doing a refresh.

> Optional: Have you a suggestion for a possible fix?

I think putting the Helloworld.module in a folder is the most simple fix for such inconviencies, but as long modules are allowed without wrapping folder this should probably prevented or at least be noted to the user.

> What are the steps to reproduce the issue?

Fresh installation and upload a updated Helloworld.module as .zip.

> Tell us about the setup you experienced the bug in:

* ProcessWire version: 3.0.35

**Comment by ryancramerdesign** [comment]
Thanks, yes it's best if modules have their own directory, so I have moved the Helloworld module into its own directory.
