### ISSUE TITLE
"Warning: Declaration of ProcessWire\User::editUrl() should be compatible" error in latest dev

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#130]
### Short description of the issue

Warning: Declaration of ProcessWire\User::editUrl() should be compatible with ProcessWire\Page::editUrl($options = Array) in /Users/ajones/Sites/ecoreportcard/wire/core/User.php on line 479

### Expected behavior

No warning

### Optional: Suggestion for a possible fix

The error is because the editUrl() method defined in User.php doesn't include the new $options argument in its definition.

### Setup/Environment

* ProcessWire version: 3.0.46
* PHP version: 7.1

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix.
