### ISSUE TITLE
Error when creating new Images field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1300]
### Short description of the issue

In PW 3.0.170 I get the following error when trying to create a new Images field:

![2021-01-06_175229](https://user-images.githubusercontent.com/1538852/103730541-f77d0d80-5047-11eb-92c9-6cd3cd7a72a3.png)

I checked the source code and it looks like the variable `$fieldtype` isn't defined. Maybe it was supposed to be `$this->fieldtype`?

### Setup/Environment

* ProcessWire version: 3.0.170

**Comment by adrianbj** [comment]
Me too!

**Comment by tiefenb** [comment]
I am not 100% sure but I think it happens since this commit: https://github.com/processwire/processwire/commit/ebdf0b9388bb77614d25aec85ad13002a462587f

**Comment by gibson-sk** [comment]
Same here

**Comment by netcarver** [comment]
This has also been reported in the PW Forums.

**Comment by adrianbj** [comment]
Looks like this was fixed in 3.0.171 - can anyone else confirm?

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/3370e108022c896886e06a2c42aea7f8c8364c08
