### ISSUE TITLE
Front end inline editing allows entering new lines for a single line text input

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1303]
### Short description of the issue

I'm trying out the front end features in earnest for the first time. I'm trying to edit my title field inline. It works, but for some reason it's allowing me to enter new lines for a single line text input. If I enter new lines and hit save, they are converted to <br /> tags (via the html entities output formatter). But if I double click to edit again, the tags are processed as live html in edit mode (potential security flaw?). And if I try to remove all of the new lines, I still end up with at least one stray <br /> tag at the end of the line.

I found this bug a while ago and posted about it on the forum (https://processwire.com/talk/topic/20634-front-end-editing-with-inline-text-fields/) but never on here. There is a little gif video on there to demonstrate it. My apologies if this has already been fixed. I couldn't find any other reference to it.

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@thetuningspoon Michael, please could you check this and close the issue if done.
