### ISSUE TITLE
Variation with original's width created via ->webp() even with "allowOriginal" set to true

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1311]
### Short description of the issue

When calling `$image->size($width, ["allowOriginal" => true])->webp`, if `$width == $image->width` the webp() function will trigger the creation of a variation at the original width, even with `"allowOriginal"` set to `true`.

### Expected behavior

If `$width == $image->width`, only the webp variation should be created.

### Suggestion for a possible fix

The [line 685](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/core/Pageimage.php#L685) of Pageimage.php does not check if it's the original image or not and still defines the `"_width"` and `"_height"` size options. When calling `webp()`, it [checks](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/core/Pageimage.php#L1679) if the image has the `"_width"` size option and decides it is not an original, even though it is in our case.

A suggestion (that I tested) would be to add `&& $result != $this` on line 685.

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.165|
|PHP|7.4.14|
|Webserver|Apache|
|MySQL Server|5.7.30-log|
|MySQL Client|mysqlnd 7.4.14|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|On|
|max_execution_time|60 (changeable)|
|max_input_nesting_level|64|
|max_input_time|0|
|max_input_vars|3000|
|memory_limit|640M|
|post_max_size|300M|
|upload_max_filesize|300M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite||
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.8.9|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminPageFieldEditLinks|3.1.2|
|FieldtypeColor|1.1.5|
|FieldtypeFunctional|0.0.2|
|FieldtypeMultiplier|0.1.3|
|FieldtypeRepeaterMatrix|0.0.5|
|FieldtypeTextareas|0.0.8|
|FileValidatorSvgSanitizer|0.0.3|
|InputfieldChosenSelect|1.2.5|
|InputfieldChosenSelectMultiple|1.2.2|
|InputfieldColor|1.1.4|
|InputfieldFunctional|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.5|
|InputfieldTextareas|0.0.7|
|MarkupSrcSet|0.1.2|
|PageQueryBoss|0.0.6|
|ProcessImportLegacyPages|0.0.1|
|ProcessMediaLibraries|0.1.6|
|ProcessTracyAdminer|1.0.7|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|TracyDebugger|4.21.29|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @romaincazier I've pushed your suggested fix for this issue.
