### ISSUE TITLE
Select Options title in "List of fields to display in the admin Page List" has extra space

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1312]
### Short description of the issue

Using `{first_name} {last_name} ({staff_status.title})` in the " List of fields to display in the admin Page List" setting results in the extra space seen here:

Adrian Jones ( Alumni)

![image](https://user-images.githubusercontent.com/871211/105915195-47fedf80-5fe4-11eb-8a1f-e80ddba1ffc1.png)

Note that I just changed to this (without ".title"), the problem remains.

`{first_name} {last_name} ({staff_status})`

### Expected behavior

No additional space

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/871211/105915304-6369ea80-5fe4-11eb-945a-6f41c909f62d.png)

**Comment by matjazpotocnik** [comment]
Hey @adrianbj , I can't replicate this one, although I used {title} ({staff_status}) in the "List of fields to display in the admin Page List" setting.
![image](https://user-images.githubusercontent.com/7663992/119532594-50dea280-bd85-11eb-94e7-5b50a9810136.png)

**Comment by adrianbj** [comment]
@matjazpotocnik - thanks for investigating. I just checked on the site where I was having this problem and it seems to be resolved now. I recently updated to the latest dev version, so I am pretty sure that a fix was implemented (perhaps inadvertently).
