### ISSUE TITLE
WireArray::prepend() does not preserve sort order

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1313]
### Short description of the issue

When prepending WireArray1 to WireArray2 I expected the order of items in WireArray1 to be preserved.

Demo:

![2021-01-28_111523](https://user-images.githubusercontent.com/1538852/106061352-23c50f00-615a-11eb-8b66-b68738981d70.png)

This reversal of the sort order of the prepended WireArray is unexpected. Looking at the `prepend()` method I can see why this happens due to the items in the prepended WireArray being prepended individually in a `foreach()`. But that is not what I think users would assume when they prepend one WireArray to another.

Changing it now would be breaking but could we get a new argument/option for `WireArray::prepend()` that allows the sort order to be preserved?

### Setup/Environment

* ProcessWire version: 3.0.171

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I agree that is not the expected order, I've pushed a fix for this.

**Comment by Toutouwai** [comment]
Thanks
