### ISSUE TITLE
Not possible to change createdUser via GUI when using alternate template/parent user setup

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1318]
### Short description of the issue

If you are using the alternate user template/parent setup and you have the option enabled that allows changing the createdUser on a page's settings tab, it only allows you to choose from users who have the `user` template, but not other ones.

### Expected behavior

I should be able to select any user from any of the available templates / parents.

**Comment by matjazpotocnik** [comment]
@adrianbj, if there is more than one $config->usersPageID, then you can type the user ID in the input field rather than select the user from InputfieldPageListSelect. So, it's possible to change the user, but it's not that handy, I agree. buildFormCreatedUser() is hookable, maybe you can find a solution/woraround for this issue?

**Comment by adrianbj** [comment]
@matjazpotocnik - that doesn't seem to be my experience - I don't have anywhere to enter a user ID - I am just limited to selecting from the branch where the current user lives. In the OP I stated only from users with the `user` template, but I think that's not quite accurate - it seems to be the branch of the current user, or maybe it's random, or ??? 

Anyway, not sure where you are seeing the option to enter an ID.

**Comment by matjazpotocnik** [comment]
It looks like this:

![image](https://github.com/processwire/processwire-issues/assets/7663992/71305feb-9443-4807-ad10-1ae71525ff27)

And this is relevant part of the code:

```
	protected function ___buildFormCreatedUser() {
		$modules = $this->wire()->modules;
		$config = $this->wire()->config;
		$pages = $this->wire()->pages;
		$selector = "parent_id=$config->usersPageID, include=all, limit=100";
		if(count($config->usersPageIDs) < 2 && $pages->count($selector) < 100) {
			/** @var InputfieldPageListSelect $f */
			$f = $modules->get('InputfieldPageListSelect');
			$f->parent_id = $this->config->usersPageID;
			$f->showPath = false;
		} else {
			/** @var InputfieldInteger $f */
			$f = $modules->get('InputfieldInteger');
			$f->description = $this->_('Enter the created user’s ID.'); 
			$f->notes = "{$this->page->created_users_id} = {$this->page->createdUser->name}";
		}
		$f->label = $this->_('Created by User');
		$f->attr('id+name', 'created_users_id');
		$f->attr('value', $this->page->created_users_id);
		$f->required = true;
		return $f;
	}

```

**Comment by adrianbj** [comment]
Weird - I don't see that - I have a PageListSelect interface.

**Comment by ryancramerdesign** [comment]
@adrianbj The logic it uses to decide what to show is located [here](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L1447)

**Comment by adrianbj** [comment]
@ryancramerdesign - ah yes, I remember seeing that before. It still doesn't solve the issue in my OP though :)

**Comment by matjazpotocnik** [comment]
Sorry, Adrian, I don't understand why you couldn't change created user by entering the user ID in the text input field; it doesn't matter where this user is in the page tree. If you're getting the PageListSelect interface, then your $config->usersPageIDs array only has one item. If you're saying that you can't use the PageListSelect interface to select a new user when using multiple user templates, then this is expected as the PageListSelect inputfield can only have one parent. The alternative would be using another inputfield, maybe Page Auto Complete or Select, if there is a manageable number of users?

**Comment by adrianbj** [comment]
@matjazpotocnik - I had forgotten that I had already added a hook to deal with this:
```
$this->wire()->addHookBefore('ProcessPageEdit::buildFormCreatedUser', function($event) {
    $f = $this->wire('modules')->get('InputfieldPageListSelect');
    $f->parent_id = 8493; // custom user parent
    $f->showPath = false;
    $f->label = $this->_('Created by User');
    $f->attr('id+name', 'created_users_id');
    $f->attr('value', $event->object->getPage()->created_users_id);
    $f->required = true;
    $event->replace = true;
    $event->return = $f;
});
```

In reality you can't expect regular site editors to enter an ID in that text field so I modified to point to the branch I needed.

I honestly don't remember now why my OP states what it does, but clearly I have a "good enough" solution in place. I'm OK if you want to close this issue.

**Comment by matjazpotocnik** [comment]
Thanks for the response. You would get the same result by setting `$config->usersPageID = 8493` in site config.php (unless you have more than 100 users). I agree that regular site editors are not expected to enter user ID in the text box. I think Ryan went with the text field solution because of performance - you can't load all possible users (who knows, there might be 1000 of them) into, let say select field, on every page edit. I played with various input types, and a Page Reference field (single page) with a custom selector like `parent.id=29|8493, include=all, limit=100` combined with Page Auto Complete input type that use Ajax, could be a possible solution that would support single and multiple parents. Or if PageListSelect would support multiple parents.

**Comment by adrianbj** [comment]
But I have three branches of users, so I can't just set usersPageID to that one ID. The select interface doesn't load them all at once: InputfieldPageListSelect ajax loads as you open each branch. Yes, autocomplete might be a decent option, but I have what I need for this current situation.

**Comment by matjazpotocnik** [comment]
$config->usersPageID (single) expect only one parent ID, while $config->usersPageID**s** (array) expects multiple parents IDs and there you have three IDs, correct? Aparat from ProcessPageEdit.module, "singular version" is only used in User.php, so this is somehow left from before PW supported multiple user parents (and templates) - at least I think so, Ryan might provide the answer. I know PageListSelect uses AJAX, but it doesn't support multiple parents (and templates, as you discovered in https://github.com/processwire/processwire-issues/issues/1314). Autocomplete unfortunatelly don't support searching by ID ('*=' operator).

**Comment by adrianbj** [comment]
Sorry, I didn't pick up on usersPageIDs vs usersPageID but it doesn't really solve the issue that having multiple user branches makes this selection complicated. But, in my case I only need selection from one branch, so my solution is working. It's just not initially obvious how to solve unless you look into the hook option. Again, happy to close this as I don't really see a better option being made available given how few people use the multiple user branches option. I have a lot of other open issues about that functionality and it doesn't seem like anyone else is suffering from them.

**Comment by matjazpotocnik** [comment]
> but it doesn't really solve the issue that having multiple user branches makes this selection complicated

You're right.

> I have a lot of other open issues about that functionality and it doesn't seem like anyone else is suffering from them.

Yes, I know, I have them listed in my notes about open issues. As far as I'm aware, only you and Teppo are using user branches.

**Comment by teppokoivula** [comment]
To be fair I'm no longer using this feature. Ran into issues (can't remember which, it has been a while) and had to change course.

We do use them for one large project, and for that they work well, but it's a different kind of beast. Custom GUI etc.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, if you ever decide to deal with this issue, I'm attaching modified version of ___buildFormCreatedUser() method in ProcessPageEdit.module that uses InputfieldPageAutocomplete with support for multiple users parents.

[buildFormCreatedUser.zip](https://github.com/processwire/processwire-issues/files/11787086/buildFormCreatedUser.zip)

**Comment by ryancramerdesign** [comment]
I've pushed an update based in part on Matjaz's above, that adds autocomplete for selecting created user, at least when there is more than one user template, or more than 100 users.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks good, but I wonder if you'd consider adding the user's email in parentheses for the autocomplete results because sometimes you might have more than one account for the same user - let's say the user has as an admin account, but also a frontend user account - it becomes impossible to know which one is which with the current interface.

**Comment by adrianbj** [comment]
Or perhaps username (in parentheses) might actually be better.

**Comment by ryancramerdesign** [comment]
@adrianbj It should be showing the email already, see line 1485 [here](https://github.com/processwire/processwire/commit/5e9a62e405fe06a814f6bb1c0fe35d61d955dec1#diff-9aade6a95b00259f67b47aecf60ee18ad8debe23f23543eab8679448b5c01afcR1485) which uses a default label format of `{name} ({email}) [{roles.name}]`. But if you've defined a label format for the 'user' template, then it'll use that instead. So maybe you already have a format that's using just the name? You should be able to go to Setup > Templates > user, then on the Advanced tab you can specify what fields to show for the label in the page list, which is also used by the autocomplete.

**Comment by adrianbj** [comment]
Yes of course - that was it - thank you!

**Comment by matjazpotocnik** [comment]
@adrianbj @ryancramerdesign this is how it looks here:

![image](https://github.com/processwire/processwire-issues/assets/7663992/38319aba-5756-482c-9883-4b49230290f8)

roles are not shown, adrian has guest and superuser roles (and no email address). Should I configure this somehow?

EDIT: I setup a label for user template like this: `{name} ({email}) [{roles.name}]` and it works. If I remove custom custom label for the user template, then {roles.name} doesn't work. For the ProcessPageList module, I have 'title' for the "Name of page field to display' (if that matters).

Line 1485:

`$f->labelFieldFormat = '{name} ({email}) [roles.name]';`

should be:

`$f->labelFieldFormat = '{name} ({email}) [{roles.name}]';`

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/223c0e79bedd0e6cf1b927e3cefd5fd3e6dee96f Thanks, Ryan.
