### ISSUE TITLE
In WireClassLoader's addPrefix() method there seems to be a typo

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#1319]
In WireClassLoader's addPrefix() method there seems to be a typo:
https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/core/WireClassLoader.php#L153

`if(!isset($this->suffixes[$prefix])) $this->prefixes[$prefix] = array();`

Why testing the state of `$this->suffixes[$prefix] `in this method? Shouldn't it be `!isset($this->prefixes[$prefix])` instead? Looks like a copy/paste error to me.

* ProcessWire version: at least from 3.0.155-dev up to current dev 3.0.171.

**Comment by ryancramerdesign** [comment]
Thanks @szabeszg you are right that looks like a copy/paste typo, I have pushed your suggested fix, good find.
