### ISSUE TITLE
SQL Error when uploading multiple files

### ISSUE THREAD

**Issue by anilex** [processwire/processwire-issues#132]
### Short description of the issue

1. When uploading multiple images (and/or just files) at once (6-7 files, 30-300k each), an error occurred `Duplicate entry '1027-0' for key 'PRIMARY' ...`. 

2. Also,... incorrect value (1970... ) for `created` in the INSERT query.

### Expected behavior

No SQL error and all uploaded files to be saved.

### Actual behavior

01. When uploading multiple images (and/or just files) at once (6-7 files per 30-200k), an error occurred "Duplicate entry '1027-0' for key 'PRIMARY' (full error shown below)". The files with the error are not uploaded (100%). Some of the files without an error are uploaded (15%), others not (85% possibility). 

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1027-0' for key 'PRIMARY' INSERT INTO `field_images_work_process` (pages_id, sort, `data`, `description`, `modified`, `created`) VALUES(1027, 0, 'new-3-3.jpg', '', '2016-12-25 18:04:05', '1970-01-01 02:00:10')
```

Same behavior found: 
- using InnoDB and MyISAM table types. Flushed caches and indexes; 
- when uploading also small pdf files (tested with 4-5-6 files max);
- 3x new fresh installed websites, current master and latest dev. 3.0.4x-46
- on local and server environment;
- by me and some other people when using the CMS to upload content;

02. Also,... just saw the incorrect value (1970... ) for `created` in the INSERT query.

### Optional: Screenshots/Links that demonstrate the issue

![screenshot](https://cloud.githubusercontent.com/assets/480999/21472089/b8e915b4-cad1-11e6-84fd-6599b3bb9ea5.jpg)

DB dump: 
[db_dump_innodb.txt](https://github.com/processwire/processwire-issues/files/672263/db_dump_innodb.txt) 

### Suggested fix

The FieldtypeMulti::savePageField assume one ajax request. Many ajax requests fired. 

### Setup/Environment

* ProcessWire version: current master and all of the latest dev (3.0.4x-46). Found the issue 3-4 weeks ago.  
* PHP version: 7.0.11 (on both local and server env.)
* MySQL version: (local) Oracle MySQL latest using the default conf by the installer, later replaced by Percona Server 5.7.16-10 installed with Homebrew during the attempts to find a fix another issue. (server) Percona Server 5.7.15-9.

my.cnf settings added in the attempts to find a solution: 
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES 
interactive_timeout = 200
wait_timeout = 200
table_open_cache = 250

* Apache and nginx.

**Comment by ryancramerdesign** [comment]
I've tried to reproduce this one several times, but am unable to. The applicable code here has been the same for quite a long time, and haven't heard similar reports, so am currently thinking it might be some combination of factors coming together in the environment(s) where you are testing (maybe the my.cnf settings?). So lets leave this open for a little while to see if anyone else can reproduce. Also the 1970 date is correct, that's what PW uses for uploaded items on a page that hasn't yet been officially saved. Thanks.

**Comment by adrianbj** [comment]
Any image-related third party modules installed?

**Comment by anilex** [comment]
01. Does it helps to point that many ajax requests are fired simultaneous? Check the screenshot.. 11 ajax simultaneous requests, most of them uploading one file, some of them uploading/inserting two files. The latest red SQL error is inserting two records ```VALUES(...), (...)```

In other words... `FieldtypeMulti->savePageField` is called 11 times simultaneous - deleting all the entries and inserting one or more records. The second ajax request deletes all entries in the field db table and inserts one or two records. The third ajax request.. the same.. 11 times simultaneous. I am guessing that this is the reason of so many files are uploaded but not saved in the DB after the page is saved and reloaded. 

And the SQL error makes sense too. There are many ```INSERT``` with a same Primary Key. The PK is page_id+sort columns. Each of the ajax request ends with insert "page_id+0" as PK. 

I believe it's not mysql or php related issue, but javascript. Probably some ajax "improvements" in the latest Chrome and Firefox when using html5 upload? 

02. Understood for the ```created``` date. Makes sense. 

@adrianbj Clean install, no other image related modules. 

When I disable html5 upload in ```InputfieldImage.js``` or ```InputfieldFile.js``` all is working as expected. Then there is one form submit request and all the files are saved, without SQL error about the concurrent inserts with a same PK.

**Comment by anilex** [comment]
It seems that changing the PHP handler on the local environment fixed the problem. Both versions are the same (7.0.11). The old one was the default included with ZendServer and the second one is custom install script for Sierra). Have kept the phpinfo output of both to compare the loaded extensions. 

An upgrade of the php version on the server also fixed the same problem. Weird. 

@ryancramerdesign Sorry for the time spent to reproduce it. Many thanks!

**Comment by ryancramerdesign** [comment]
Glad you found a fix. It seems like you were on to something there though, as I could see how in your case that FieldtypeMulti method was getting clobbered with multiple http requests at once and trying to process them together, rather than one by one. But I've never observed that behavior, and am not exactly sure how it could occur. Apparently there is some situation where it can, so I'll be keeping an eye out to see if it pops up again. Thanks.

**Comment by anilex** [comment]
It seems like something was delaying the result of the DB requests. After the ```delete``` (followed by any of ```closeCursor()```, ```close_connection()```, etc), the ```insert``` still randomly raised duplicate PK issue. Even if both were closed in transaction when the other concurent delete+insert requests should to be queued. 

Haven't tested when the ajax upload was handled by just one ```insert``` with subquery (SELECT max(sort))+1 where pages_id=:page_id), without the weight of transactions and complete delete and insert with hardcoded 'sort'. Just a raw idea, don't know if its suitable for the ajax uploads case here.

```
INSERT INTO `field_images` (`pages_id`, `data`, `sort`, `description`, `modified`, `created`) 
VALUES (1001, 'file.jpg', (SELECT max(sort)+1 FROM (SELECT * FROM `field_images`) as something WHERE pages_id=1001),'[""]', '2016-09-21 21:57:16','1970-09-21 21:57:16');
```

**Comment by anilex** [comment]
Just find out that the current version of [phpredis session handler](https://github.com/phpredis/phpredis#php-session-handler), when configured globally in php.ini doesn't have [lock session feature](https://github.com/phpredis/phpredis/issues/37) and this caused issues with concurrent php requests. Based on [some tests](https://habrahabr.ru/post/318836/) 20-40% of the concurrently opened sessions are rewritten and lost. Apparently, I believe that this was the reason for this issue and it not related to the php version, or ProcessWire or mysql. Thanks to Ryan and the community for the patience and understanding. 

Worth to note that it's safe to use session handler with Redis via phpredis when used with any php library which supports session write lock.
