### ISSUE TITLE
strpos(): Empty needle when attempting to save email address that is already in system 

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1326]
### Short description of the issue

If you try to save an email address that is already in the system (when you have set up unique email addresses), you get this error

![image](https://user-images.githubusercontent.com/871211/107539192-93cf8e00-6b79-11eb-92c0-52faf317c571.png)

PW 7.0.172

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this
