### ISSUE TITLE
Inline doc links still exist to old repo

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#133]
### Short description of the issue

Some inline docs still link to the old repo.

### Expected behavior

Should link to files in the new repo

### Optional: Suggestion for a possible fix

Do a search for /ryancramerdesign/ or click this:
https://github.com/processwire/processwire/search?utf8=%E2%9C%93&q=%2Fryancramerdesign%2F&type=Code

There are several links that need fixing. I can put together a PR if you want, but figure you might prefer to do this yourself.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, these should now be fixed.
