### ISSUE TITLE
LazyCron implements ConfigurableModule but doesn't implement required getModuleConfigInputfields method

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1331]
### Short description of the issue

Got an error after upgrading to the latest dev (3.0.172) saying that LazyCron didn't validate properly and I should refresh my modules. 

It looks like LazyCron now implements ConfigurableModule but doesn't implement the required getModuleConfigInputfields method.

### Setup/Environment

* ProcessWire version: 3.0.172

**Comment by lesaff** [comment]
I am getting the same error. Is this related to https://github.com/processwire/processwire-issues/issues/1323?

**Comment by thetuningspoon** [comment]
@lesaff I don’t think so. It looks like Ryan might have started on an enhancement to LazyCron last week but didn’t continue on it. All you have to do to remove the error is edit wire/modules/LazyCron.module and remove “implements ConfigurableModule” from the top.

**Comment by adrianbj** [comment]
Doesn't this commit fix it?
https://github.com/processwire/processwire/commit/4d04aac2a646d6c387d1afff28253225dace8474

**Comment by thetuningspoon** [comment]
@adrianbj Looks like it!
