### ISSUE TITLE
Exception emails are blank

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1332]
### Short description of the issue

On the dev branch (3.0.172), the exception emails going to the adminEmail have no content.

### Optional: Suggestion for a possible fix

Line 647 of WireShutdown.php is checking empty($emailSubject) when it should be checking empty($emailBody)

### Setup/Environment

* ProcessWire version: 3.0.172

**Comment by jlahijani** [comment]
I think I'm experiencing this too.  It was introduced before 3.0.172 I believe.

**Comment by horst-n** [comment]
I had some with PW 3.0.168 on a newer site!

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon good find, I have pushed your suggested fix.
