### ISSUE TITLE
Saving a page using the API does not save values set in custom image fields

### ISSUE THREAD

**Issue by billhemsley** [processwire/processwire-issues#1334]
### Short description of the issue

When using the the API, saving a page does not save values set in custom image fields.

### Expected behavior

Saving a page would save custom image fields, just as it saves other fields.

### Actual behavior

Saving the page via the API ($page->save() ) does not save the field content. Saving the field ($page->save('images') ) does save the content.

### Links that demonstrate the issue

This issue has been discussed on the forums https://processwire.com/talk/topic/25164-image-custom-fields-set-values-with-the-api/

Note that even if the behaviour is intended, it's likely to cause confusion.

### Steps to reproduce the issue

```
$page->outputFormatting(false);
foreach($page->images as $image) {

	$image->custom_field_1 = "Some text";
        $image->custom_field_2 = "Some more text";

	// Saves image custom fields
        $page->save('images');

	// Does not save image custom fields
	$page->save();
}

// Does not save image custom fields
$page->save();
```

### Setup/Environment

* ProcessWire version: 3.0.165

**Comment by adrianbj** [comment]
FYI - this is similar to the way that the Table field works: 
https://processwire.com/talk/topic/23065-need-to-save-table-field-explicitly-not-just-entire-page-when-updating-value/ 
https://processwire.com/talk/topic/19083-table-changes-not-saved-with-page-save/

so it might give you an idea of @ryancramerdesign's thinking on this.

**Comment by billhemsley** [comment]
@adrianbj Thanks, useful to know. I'll add this to the forum discussion.

Those two links seem no longer to be valid, and searching for topics doesn't find them.

**Comment by adrianbj** [comment]
Those links are to the Profields Table support board - sorry for the confusion.

**Comment by billhemsley** [comment]
No, my apology! I've just remembered that Table is a Pro field and my subscription has lapsed. Time for a renewal!

**Comment by Toutouwai** [comment]
Ryan's comment from the ProFields Table topic:

> Likely the page can't see that the table changed. This can happen when you are 2+ object instances away from the $page, or the object that changed (or any in between) has change tracking disabled. I'm not sure exactly which it would be in this case, but the solution is simple. When $page can't see a change for whatever reason, you just need to tell the $page that you changed something related to the field, by calling $page->trackChange('field_name');  Replace 'field_name' with the name of the field, i.e. 'table_2'. I think your second example works because the save is being forced just for that field, whether $page knows that it changed or not.

So when $page doesn't detect that has a field has changed you can either...

Tell $page that the field has changed:

```
$page->trackChange('images');
$page->save();
```

Or force the saving of the field by saving it specifically by name:

```php
$page->save('images');
```

Of course it would be good if PW could automatically detect the change so it isn't necessary to remember this.

**Comment by Toutouwai** [comment]
Looking at Pagefile.php, I'm wondering if the `setFieldValue()` method needs to notify the Pagefiles object of the change. Similar to what is done for specific properties in `Pagefile::___changed()`. So `Pagefile::setFieldValue()` would become:

```php
public function setFieldValue($name, $value, $changed = null) {
		
	$template = $this->pagefiles->getFieldsTemplate();
	if(!$template) return false;
	
	$fieldgroup = $template->fieldgroup;
	if(!$fieldgroup) return false;
	
	$field = $fieldgroup->getFieldContext($name);
	if(!$field) return false;
	
	$page = $this->pagefiles->getFieldsPage();

	/** @var Fieldtype $fieldtype */
	$fieldtype = $field->type;
	$value = $fieldtype->sanitizeValue($page, $field, $value);

	if($changed === null && $this->page->trackChanges()) {
		// detect if a change has taken place
		$oldValue = $this->getFieldValue($field->name, false);
		if(is_object($oldValue) && $oldValue instanceof Wire && $oldValue === $value) {
			// $oldValue and new $value are the same object instance, so ask it if anything has changed
			$changed = $oldValue->isChanged(); 
			if($changed) $this->trackChange($field->name);
			// Alert the $pagefiles of the change
			$this->pagefiles->trackChange('item');
		} else if($oldValue != $value) {
			// $oldValue and new $value differ, record change
			$this->trackChange($field->name, $oldValue, $value);
			// Alert the $pagefiles of the change
			$this->pagefiles->trackChange('item');
		}
	} else if($changed === true) {
		$this->trackChange($field->name);
		// Alert the $pagefiles of the change
		$this->pagefiles->trackChange('item');
	}

	$this->fieldValues[$field->name] = $value;

	return true;
}
```

This seems to fix the issue for me.

**Comment by Toutouwai** [comment]
Or maybe better to update `Pagefile::___changed()`?

```php
public function ___changed($what, $old = null, $new = null) {
	if(in_array($what, array('description', 'tags', 'file', 'filedata')) || array_key_exists($what, $this->fieldValues)) {
		$this->setUser(true, 'modified');
		$this->set('modified', time()); 
		$this->pagefiles->trackChange('item');
	}
	parent::___changed($what, $old, $new); 
}
```

@ryancramerdesign, could a `___changed()` method be added to ProFields Table to deal with the similar change tracking issue there?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai that's a very good suggested solution, I have added it. If ProFields Table is doing something similar I can have a look.

**Comment by netcarver** [comment]
@Toutouwai Robin, can this be closed now?

**Comment by Toutouwai** [comment]
@netcarver I think this is fixed, but I'm not the person who opened this issue so I'm not able to close it myself.
