### ISSUE TITLE
Textformatter doesn't work in Custom fields for images 

### ISSUE THREAD

**Issue by nurkka** [processwire/processwire-issues#1337]
### Short description of the issue

When using custom fields for images ( https://processwire.com/blog/posts/pw-3.0.142/#custom-fields-for-files-images ) , the textformatters, which are assigned to those custom fields, don't work.

### Expected behavior

Output should be filtered through assigned textformatter

### Actual behavior

Output is not filtered

### Optional: Screenshots/Links that demonstrate the issue

N/A

### Optional: Suggestion for a possible fix

I just have a workaround: Calling the corresponding textformatter manually on the template

### Steps to reproduce the issue

1. assign custom fields with textformatters to images (see https://processwire.com/blog/posts/pw-3.0.142/#custom-fields-for-files-images )
2. enter text in those fields
3. output text via template
4. => output will not be filtered through textformatter

### Setup/Environment

* ProcessWire version: 3.0.165
* (Optional) PHP version: 7.3
* (Optional) MySQL version: 5.x
* (Optional) Any 3rd party modules that are installed and could be related to the issue: no

**Comment by Toutouwai** [comment]
I can't reproduce this in 3.0.172. In the example below the Parsedown Extra textformatter is applied to field text_1 and it works both when the field is in the page template and in the custom image fields template.

![2021-03-02_105347](https://user-images.githubusercontent.com/1538852/109564490-02cf4f80-7b46-11eb-87a4-fee76cd5b054.png)

I tested in the template file too with the same results.

**Comment by nurkka** [comment]
Thank you for testing the issue. I updated to 3.0.172 – but the issue still persists in my case. Since my workaround works and since it works in your case, I think the issue is just something in my installation. I will close the issue. Thanks!

**Comment by Toutouwai** [comment]
My guess would be that somehow the output formatting is turned off for the Page object in your template code. You could check by dumping or echoing `$page->of()`.

And see if explicitly getting the formatted value of the images field makes a difference, e.g. 
```php
$images = $page->getFormatted('images');
```

**Comment by nurkka** [comment]
Thanks for the hint! That brought me to the corresponding point in the code and I was able to fix it there. It wasn't even in the templates, but in a module I am using, ImagePicker. Thanks again!
