### ISSUE TITLE
Can't make languages not available on user page because there is no unpublished option

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1338]
### Short description of the issue

I can't set a language to unpublished via the GUI or the API so there is no inbuilt way to remove a language from being selectable from the language page reference field on the user template.

### Expected behavior

I should be able to unpublish a language.

### Actual behavior

I can't, unless I manually set the status of the language page to `2049` and then everything works as expected in terms of preventing it from being selected.

I don't know if this has any other impacts, but for my needs it seems to be working well. Is there any reason this can't be provided via the GUI / API?

**Comment by Toutouwai** [comment]
There is a template setting that determines whether pages of that template can be unpublished:

![2021-03-03_140735](https://user-images.githubusercontent.com/1538852/109736936-10f69c00-7c2a-11eb-8564-937a77b77392.png)

Looks like once that setting is changed for the language template then languages can be unpublished via the admin GUI. Not sure if there are any side-effects to unpublished languages though.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I had forgotten about that option. It certainly fixes the issue although I would like to hear from @ryancramerdesign if there might be any side effects.

**Comment by ryancramerdesign** [comment]
It is okay to unpublish a language if you need to. I have one site where I am doing this also.

**Comment by adrianbj** [comment]
Ok, thanks @ryancramerdesign
