### ISSUE TITLE
Configurable module check failed for LazyCron

### ISSUE THREAD

**Issue by snobjorn** [processwire/processwire-issues#1339]
### Short description of the issue

After update to 3.0.172 dev, the "Module" log is filled with three new entries every few seconds, where one of the entries are from the page with a LazyCron hook.

- https//domain.com/processwire/setup/logs/view/modules/?Notifications=update&time=1614774497
- https//domain.com/processwire/setup/logs/view/modules/?q=&date_from=&date_to=&time=1614774503
- https//domain.com/lists/list/

Text for all entries are: "Configurable module check failed for LazyCron. If this error persists, please do a Modules > Refresh."

### Expected behavior

LazyCron should not leave this message in the "Module" log. And a click on Modules > Refresh should fix it.

### Actual behavior

Modules > Refresh does not work.

### Steps to reproduce the issue

1. Have Lazy Cron activated, use it on a page
2. Have ProcessWire 3.0.172 dev installed

**Comment by Toutouwai** [comment]
I think this is already fixed: https://github.com/processwire/processwire/commit/4d04aac2a646d6c387d1afff28253225dace8474

**Comment by BernhardBaumrock** [comment]
hooray :) don't forget to close the issue @snobjorn

**Comment by snobjorn** [comment]
Thanks @Toutouwai , that solved it.
