### ISSUE TITLE
Can't set "precision" of decimal field via API

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1340]
### Short description of the issue

I need to set the precision setting of a new decimal field via API (RockMigrations). The setting is properly set and even the message that the database is altered is shown, but the input of the field is still showing 0-digit precision (I'm expecting 2).

As soon as I save the field, the precision takes effect.

### Expected behavior

```php
$rockmigrations->setFieldData('myfield', [
  'precision' => 2,
]);
```

Should have this result:

![img](https://i.imgur.com/nWFBqxt.png)

### Actual behavior

![img](https://i.imgur.com/QxYGwf9.png)

Any ideas what could be the reason?

I'm on v171 due to this issue: https://github.com/processwire/processwire-issues/issues/1339

**Comment by ryancramerdesign** [comment]
> As soon as I save the field, the precision takes effect.

@BernhardBaumrock I'm not sure I totally follow, but it is true that the field would have to be saved before the setting would take effect. Though saving the field is also what triggers the DB schema change, so I'm confused if you saw that before saving the field.  

I don't know how to reproduce this one, but my best guess is that maybe there are two instances of the Field in memory somehow? For instance, when fieldgroup context settings are present for a Field, it's possible for there to be more than one instance (i.e. one with changes contextual to a fieldgroup and another without).
