### ISSUE TITLE
Setting $config->pageNameWhitelist to blank prevents page add

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1342]
### Short description of the issue

The documentation for `$config->pageNameWhitelist` says:

> To allow any characters, you can make this blank, however using a whitelist is strongly recommended.
> Please note this whitelist is only used if pageNameCharset is 'UTF8'.

In my /site/config.php I have:

```php
$config->pageNameCharset = 'UTF8';
$config->pageNameWhitelist = '';
```

So this should allow me to use any characters in a page name. But instead this happens in ProcessPageAdd:

![pagename](https://user-images.githubusercontent.com/1538852/110199192-1408bb00-7ebc-11eb-9948-a0eb8764fd6b.gif)

### Setup/Environment

* ProcessWire version: 3.0.172

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai  I must have been mistaken when I wrote that part of the documentation, or maybe I wrote it before the feature was finished being built. I don't think it would be safe to have an "anything goes" setting for page names. I have removed the part that says you can leave it blank.

**Comment by Toutouwai** [comment]
> I don't think it would be safe to have an "anything goes" setting for page names.

I don't think so either, but the whitelist system doesn't seem practical for languages that have many thousands of characters. Instead you might want to use some regex to define the range of characters that are allowed, e.g. `/[^\p{L}\p{N}\.\-_]/u` or `/[^[:alpha:][:digit:]\.\-_]/u`.

So you want to be able to turn off the whitelist and use your own PHP in hooks - e.g. before a page is saved, use regex to validate its page name.

This scenario doesn't affect me personally but @gideonso has raised issues about dealing with Chinese characters in page names a few times:
https://github.com/processwire/processwire-issues/issues/810
https://github.com/processwire/processwire-issues/issues/724
https://github.com/processwire/processwire-requests/issues/393

And you've recommended setting the whitelist to blank for such cases: https://github.com/processwire/processwire-issues/issues/810#issuecomment-464109884

Interestingly, recently he said that setting the `$config->pageNameWhitelist` to blank did solve the problem...
https://github.com/processwire/processwire-requests/issues/393
https://processwire.com/talk/topic/25235-non-ascii-character-page-name/
...but in PW 3.0.174 I get the error shown above when any non-ascii character is in the page name. So I'm not sure why that is - different PW versions?

**Comment by gideonso** [comment]
@Toutouwai 

I jumped to the conclusion too soon. I didn't save the page to see if it is okay to have $config->pageNameWhitelist  blank. I have just tested it again and got the same error as you did.

@ryancramerdesign really need a better way to do the pageNameWhitelist. It is almost impossible to place all the Chinese characters into the config.php file.

**Comment by gideonso** [comment]
Please read this comment. It seems propose a good way to fix this issue.

https://github.com/processwire/processwire-requests/issues/393#issuecomment-867593330

**Comment by ryancramerdesign** [comment]
@gideonso Yes, thanks, I think that makes sense. I have added that.

**Comment by gideonso** [comment]
@Toutouwai

I have just tested the fix and it works for me and I think this issue can be closed now.
