### ISSUE TITLE
ProcessPageEdit.css Renamed to ProcessPageEdit.scss

### ISSUE THREAD

**Issue by kongondo** [processwire/processwire-issues#1345]
### Short description of the issue

**ProcessPageEdit.css** was renamed to **ProcessPageEdit.scss** in this [commit](https://github.com/processwire/processwire/commit/94e71209b348335b9ceeb44219c72c94723be554#diff-568bd702dc39c09bd756a731520900fb98307231ca8c65435133b8d5c0a5b60b) hence affecting some admin styles. 

### Expected behavior

Admin styles such as display:none on #PageIDIndicator should be available.

### Actual behavior

Admin styles such as display:none on **#PageIDIndicator** are no longer available, hence when editing a page, the page ID is displayed under the page title.

### Optional: Suggestion for a possible fix

Rename ProcessPageEdit.scss to ProcessPageEdit.css.

### Steps to reproduce the issue

1. Step 1: Install the ProcessWire dev 3.0.173 on a new site.
2. Step 2: Edit a page.
3. Step 3: Observe the behaviour.

### Setup/Environment

* ProcessWire version: 3.0.173 (and 3.0.172 was the genesis).

**Comment by tiefenb** [comment]
Can confirm this issue.

**Comment by tiefenb** [comment]
I guess this is fixed in 3.0.174? I don't see the style issues again? Any other can confirm?

**Comment by ryancramerdesign** [comment]
I think this must be fixed in 3.0.174, as I'm not observing the issue here. I'm not sure why this one might have shown up unless Git automatically commits renamed files?

**Comment by kongondo** [comment]
I can confirm issue resolved in 3.0.174. The required file ProcessPageEdit.css is back :-). Closing issue.

Thanks.
