### ISSUE TITLE
Pages with pagination throw a 404 (3.0.173)

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1346]
https://processwire.com/talk/topic/25233-pw-30173-%E2%80%93-core-updates-new-hook-type/?do=findComment&comment=211984

**Comment by ryancramerdesign** [comment]
I can't duplicate this one, but I did add pagination support to the new hook type last week, so a lot of code has changed in relevant parts since this was posted. If you are still seeing the error, can you provide steps to reproduce? Thanks.

**Comment by cb2004** [comment]
This is working when I upgraded to 3.0.175
