### ISSUE TITLE
next() with page reference field in selector not working

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1349]
### Short description of the issue

If you use `$page->next()` with a page reference field in the selector, no results are returned.

### Expected behavior

It should return the first sibling matching the selector

### Actual behavior

No siblings are returned

### Optional: Screenshots/Links that demonstrate the issue

As you can see, a simple `id!=` selector works as expected, but if you want to use a page reference field (in this example, `course`), then you either need to include the `$page->siblings()` or you need to do a `$pages->findOne` specifying the template and sorting in reverse order to get the "next" sibling that matches the selector.

Presumable because specifying the siblings optional parameter reverts `next()` to use the older / slower method, there is an issue with the new method and page reference fields. Maybe this is simply a limitation of the new method, but I don't believe it's documented anywhere.

![image](https://user-images.githubusercontent.com/871211/111177148-34451380-8567-11eb-97a6-40e16b1735cd.png)

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this one.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks to be working as expected!
