### ISSUE TITLE
PHP 8: TypeError in ImageSizerEngine.php#L855

### ISSUE THREAD

**Issue by schwarzdesign** [processwire/processwire-issues#1351]
### Short description of the issue

There's a bug in ImageSizerEngine with the handling of focus points in PHP 8. Depending on the focus point set through the backend, using $page->image->size() with a defined focus point will either result in a TypeError or handle the focus point incorrectly, resulting in incorrect crops.

### Expected behavior

The ImageSizerEngine should handle focus points correctly in PHP 8.

### Actual behavior

The ImageSizerEngine performs some conversions between strings representing percentages (e.g. `10.5%`) and integers / floats which doesn't work correctly in PHP 8. This is most likely related to the [change regarding string handling](https://www.php.net/manual/en/migration80.incompatible.php) in core functions that expect integers or floats:

> The concept of a "leading-numeric string" has been mostly dropped; the cases where this remains exist in order to ease migration. Strings which emitted an E_NOTICE "A non well-formed numeric value encountered" will now emit an E_WARNING "A non-numeric value encountered" and all strings which emitted an E_WARNING "A non-numeric value encountered" will now throw a TypeError.

The specific error comes from [ImageSizerEngine.php#L855](https://github.com/processwire/processwire/blob/0c0fb16e4de3f73f5d41e954b10d89c54c0ca2ff/wire/core/ImageSizerEngine.php#L855):

`$cropping[0] = round(min(100, max(0, $cropping[0]))) . '%';`

`$cropping[0]` is a string in this case, so `round()` throws a TypeError. See the screenshow below for the callstack

Even when no error is thrown, the generated image is cropped incorrectly, so there are likely more issues regarding this string to int/float conversion.

### Screenshots/Links that demonstrate the issue

![php-8-typeerror-imagesizerengine](https://user-images.githubusercontent.com/2513281/111299461-3fc03980-8650-11eb-9fdc-91dad4e4f9ef.png)

### Suggestion for a possible fix

The line mentioned above most likely expects the $cropping parameters to be floats or ints at this point, so this needs to be handled at some point (though I'm not sure where the correct place is for that conversion).

Also, it's likely errors like this will crop up in other places, so ImageSizerEngine should be checked thoroughly for PHP 8 compatibility.

### Steps to reproduce the issue

I wasn't able to reliably reproduce this issue, the TypeError only seems to crop up when setting a focal point close to or touching the edges of the images.

1. Use PHP 8.
2. On any site with an image field, upload an image and set a focus point.
3. In the template file, request an image transformation that requires the image to be cropped, e.g.: `$page->get('the_image_field')->size(200, 100);`
4. The resulting image will likely have an incorrect crop or a TypeError will be thrown. If it doesn't, try changing the focus point a couple of times until the problem appears (make sure to use [removeVariations](https://processwire.com/api/ref/pageimage/remove-variations/) so ProcessWire can't use the existing variations).

### Setup/Environment

- ProcessWire: 3.0.174
- PHP: 8.0.3
- Webserver: Apache

**Comment by ryancramerdesign** [comment]
@schwarzdesign I can't get a successful PHP 8 install here, and am pretty confused by these changes made in PHP 8, so am doing some guesswork, but I've attempted a fix for this one. Please let me know if you find this does or doesn't resolve the issue. Thanks.

**Comment by matjazpotocnik** [comment]
@schwarzdesign, can you verify Ryan's fix?

**Comment by netcarver** [comment]
@schwarzdesign Ping. See comment above. Could you close please.

**Comment by schwarzdesign** [comment]
@ryancramerdesign @matjazpotocnik @netcarver Sorry for the late reply! Was a bit difficult to test because I couldn't reliably reproduce the error before. But it looks like the fix worked. I managed to reproduce the error on PW 3.0.165 and after updating to 3.0.183 it went away! So as far as I can tell this issue is fixed, thanks Ryan!
