### ISSUE TITLE
FileLogger::getTotalLines() checks if file exists only if filesize() >= chunkSize (and even then it gives PHP warnings when fails)

### ISSUE THREAD

**Issue by the-ge** [processwire/processwire-issues#1352]
### Short description of the issue

I got
```
Warning: filesize(): stat failed for /var/www/html/site/assets/logs/cache-control.txt in /var/www/html/wire/core/FileLog.php on line 416
Warning: file(/var/www/html/site/assets/logs/cache-control.txt): Failed to open stream: No such file or directory in /var/www/html/wire/core/FileLog.php on line 417

Fatal Error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in wire/core/FileLog.php:411
```
when I tried to clear cache after log files in /site/assets/logs/ were deleted.

### Expected behavior

If the log file does not exist, it should return 0 with no warnings.

### Actual behavior

If the file does not exist, it will attempt to do filesize, which results in a warning, then count(false), which results in a fatal error.

### Optional: Screenshots/Links that demonstrate the issue

![Screenshot_2021-03-16 https www tenita e0](https://user-images.githubusercontent.com/6468893/111364617-5fc01f00-8689-11eb-8bef-f3449142bcf0.png)

### Optional: Suggestion for a possible fix

The test can be moved at the beginning. The fopen test would be no longer needed (and it would not be another source of warnings when it fails).

```php
	public function getTotalLines() {

		if(!is_readable($this->logFilename)) return 0;

		if(filesize($this->logFilename) < $this->chunkSize) {
			$data = file($this->logFilename); 
			return count($data); 
		}

		$fp = fopen($this->logFilename, "r");
		$totalLines = 0;
```

### Steps to reproduce the issue

1. I tested in an existing WIP site and a new 3.0.174 installation, debug mode enabled.
2. Install ProcessCacheControl
3. Delete log files in /site/assets/logs/
4. Navigate through the admin menu: Setup > Cache Control > Clear all

### Setup/Environment

* ProcessWire version: 3.0.174
* (Optional) PHP version: 8.0
* (Optional) MySQL version: MariaDB 10.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: ProcessCacheControl

**Comment by ryancramerdesign** [comment]
Thanks @the-ge I've pushed your suggested fix for this.
