### ISSUE TITLE
Minor admin UI glitch with required state asterisk in case content is injected before .InputfieldHeader element

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1355]
Hey Ryan. This is related to https://github.com/teppokoivula/VersionControl/issues/28 and not exactly a core bug, but also hopefully pretty small thing (and definitely easier to fix in the core than it is in any module), so perhaps you'd be willing to consider making this change.

Currently the "required" asterisk is injected with CSS like this:

```
.InputfieldStateRequired>.InputfieldHeader:first-child:after {
    content: ' *';
```

Now, if anything (in my case the VersionControl module) needs to inject extra elements within the Inputfield markup, this may break. Robin suggested in the issue linked above a small change that could fix this:

```
.InputfieldStateRequired>.InputfieldHeader:after {
    content: ' *';
```

Unless of course you can think of a reason why there would indeed be multiple direct descendant .InputfieldHeader elements, the suggested change would seem to both fix this problem, and actually make the CSS a little less specific, which can be a good thing :)

Loosely related note: injecting content like this with CSS can be an issue in terms of accessibility: screen readers can read said content as part of the text, which in turn may sound pretty confusing. Technically it would be better to inject the asterisk directly within markup, hide it with aria-hidden, and provide a screen reader alternative text — but that's _way_ out of the scope of this issue, I think.

**Comment by ryancramerdesign** [comment]
@teppokoivula I don't recall where or why but there was some situation that required the first-child, so I think if we change this it's likely to end up as another issue report at some point. It's also used in many different places, like all the admin themes, FormBuilder themes, etc. Can you think of any other ways around it, or does it need to change in the core in order to fix the other issue you referenced?

**Comment by matjazpotocnik** [comment]
@teppokoivula, any more thoughts on this issue?

**Comment by teppokoivula** [comment]
Hey @matjazpotocnik. Been busy with other stuff lately, but will take a closer look at this soon.

I'd still like to find a solution for this that doesn't involve essentially replicating the core behaviour in modules ([which is what I've done for now for Version Control](https://github.com/teppokoivula/VersionControl/blob/dev/res/css/VersionControl.css#L144:L147)), but don't know the context well enough (yet).

**Comment by matjazpotocnik** [comment]
@teppokoivula ping

**Comment by teppokoivula** [comment]
Hey @matjazpotocnik — I can't remember the specifics anymore, but I think we can close this one!

If anything it would be better to look for some other way of signaling required fields, due to the (likely) accessibility issues with current solution.
