### ISSUE TITLE
FieldtypeOptions::getSelectorInfo does not support user language if not default

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1357]
### Short description of the issue

If I use a field of Type FieldtypeOptions within FieldtypeSelector the selectable options are provided only in the default language.

### Expected behavior

User language should be used here.

### Screenshots/Links that demonstrate the issue

![Bildschirmfoto 2021-03-24 um 11 18 58](https://user-images.githubusercontent.com/4683120/112294012-0c565e00-8c93-11eb-8eee-f5488adc43d7.png)

### Suggestion for a workaround in **init.php**
```

/**
 * BUGFIX
 * FieldtypeOptions::getSelectorInfo does not handle user language if not default
 * @todo remove if fixed
 *
 */
$this->addHookAfter('FieldtypeOptions::getSelectorInfo', function($e) {
	// quick exit
	if(!$this->wire('modules')->isInstalled('LanguageSupportFields')) return;
	if (wire('user')->language->isDefault()) return;
	$info = $e->return;
	$lid = wire('user')->language->id;
	$field = $e->arguments[0];
	foreach($e->object->get('manager')->getOptions($field) as $option) {
		$info['options'][$option->id] = $option->{"title$lid"};
	}
	$e->return = $info;
});

```

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue.

**Comment by kixe** [comment]
@ryancramerdesign 
Thanks!
