### ISSUE TITLE
Mismatch between docs and actual behaviour: $page->get() won't return parent properties if output formatting is on

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1359]
According to the docs (https://processwire.com/api/ref/page/get/) `$page->get('parent.title')` returns the parent title, but in reality it only returns it in case output formatting is turned off. Stumbled upon this today after spending quite a while trying to figure out what it was that I was doing wrong in my code.

TL;DR: If returning parent properties with Page::get() only works when output formatting is off, this should probably be mentioned in the docs to avoid further confusion :)

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this so that it works when output formatting is on also.

**Comment by teppokoivula** [comment]
Amazing, thanks @ryancramerdesign! Tested and seems to work great, closing the issue :)
