### ISSUE TITLE
PW htaccess rules to serve static 404 on image files not working consistently

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1360]
### Short description of the issue

[This blog post](https://processwire.com/blog/posts/optimizing-404s-in-processwire/) explains how you can optimise 404s by serving a static HTML 404 page. There is a section for filtering out missing image files: https://processwire.com/blog/posts/optimizing-404s-in-processwire/#filtering-out-missing-image-files

But the [RewriteCond supplied in the PW .htaccess](https://github.com/processwire/processwire/blob/dev/htaccess.txt#L456) that is intended to support this doesn't work consistently for all image file URLs. 

In item 2 of my .htaccess:
```
ErrorDocument 404 /404.html
```

I uncommented the line in item 18 of my .htaccess:
```
RewriteCond %{REQUEST_FILENAME} !\.(jpg|jpeg|gif|png|ico|webp|svg)$ [NC]
```

Works (serves static 404): 
```
https://mydomain.com/does-not-exist.jpg
```

Works (serves static 404): 
```
https://mydomain.com/site/does-not-exist.jpg
```
The /site/ part of the path can be substituted with any *existing* directory path and it works.

Does not work (PW serves non-static 404):
```
https://mydomain.com/does-not-exist/does-not-exist.jpg
```

So the supplied RewriteCond doesn't seem to account for image 404s where the path includes a directory that doesn't exist.

For some background, the reason I need this is because if you are running Varnish cache then it strips cookies from requests to static files (e.g. jpg) and so if an asset path is wrong for some reason and PW loads its non-static 404 page then a new session is started and you are logged out of PW.

### Setup/Environment

* ProcessWire version: 3.0.174

**Comment by ryancramerdesign** [comment]
@Toutouwai I think that in this line below, the REQUEST_FILENAME probably needs to be a REQUEST_URI instead:
~~~~
RewriteCond %{REQUEST_FILENAME} !\.(jpg|jpeg|gif|png|ico|webp|svg)$ [NC]
~~~~
like this:
~~~~~
RewriteCond %{REQUEST_URI} !\.(jpg|jpeg|gif|png|ico|webp|svg)$ [NC]
~~~~~
Can you confirm?

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, that fixes it.

**Comment by Toutouwai** [comment]
Closing because fixed in this commit: https://github.com/processwire/processwire/commit/f99d20dfa5838e0071c8a314bb76053f4c96ae9b
