### ISSUE TITLE
inconsistent treatment with tags with hyphens

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1362]
If you create a field and give it a tag like 'my-tag' when editing the field, it will create it just fine.  Notice the hyphen.

However if you create a tag using the 'Manage Tags' feature and name it 'my-tag', it will convert it to 'my_tag' (replaces the hyphen with underscore).

Ideally it will keep hyphens.

**Comment by ryancramerdesign** [comment]
@jlahijani I can't duplicate it here, but the manage tags features were refactored quite a bit in the last couple of weeks, so I suspect that this one was resolved in that process, though please let me know if you are still experiencing it.

**Comment by netcarver** [comment]
@jlahijani Jonathan, can this be closed now?
