### ISSUE TITLE
Misleading info when deleting modules

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1365]
When the module contains multiple files in a directory, and you delete a module, an error message is displayed: "Modules: Failed to delete module 'ModuleName'".

An example of such a module is Dashboard. There are multiple .module files inside /site/modules/Dashboard, each .module file is a separate module, listed in the site modules admin interface. When you delete a module, for example, DashboardPanelHelloWorld, files inside /site/modules/Dashboard are scanned and corresponding files (DashboardPanelHelloWorld.module, DashboardPanelHelloWorld.js, DashboardPanelHelloWorld.css) are successfully deleted, but the error message is nevertheless shown. This happens in /wire/core/modules.php in the ___delete() method.

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this issue
