### ISSUE TITLE
getTotal() shows wrong result when paginating PageArrays with autojoined fields.

### ISSUE THREAD

**Issue by lmd-code** [processwire/processwire-issues#1366]
This issue was mentioned in the forum (first by Jan Romero - [here](https://processwire.com/talk/topic/25088-pw-30172-%E2%80%93-find-faster-and-more-efficiently/?do=findComment&comment=211362)) but I thought I post a formal report here too.

### Short description of the issue

When paginating the results of a PageArray retrieved with a `find()` selector with autojoined fields, `getTotal()` is incorrect, which also makes `renderPager()` and `getPaginationString()` incorrect.

### Expected behavior

`getTotal()` should show the correct number of total results matching the selector.

### Actual behavior

The `getTotal()` result is too large -- the total returned is actually the _total number_ of results **plus** the _current count_ (`count()`).

For example, if a selector matched a total of 45 pages with a limit of 10, then `getTotal()` incorrectly shows **55** on pages 1-4 and **50** on page 5 (the last page).

The error occurs regardless of the actual method used; e.g., all these produce the same error:
```
$pages->find('templates_id=45, limit=10, join='foo|bar')
$pages->findJoin('templates_id=45, limit=10', 'foo|bar')
$pages->findJoin('templates_id=45, limit=10', ['foo', 'bar'])
```

This in turn has knock-on effects:
- `getPaginationString()` shows the wrong result.
- `renderPager()` shows one too many page links (with the phantom page being blank), except on the last page if `count()` is low enough that it doesn't cause the incorrect total to exceed `page num * limit`.

### Demonstration

The following dump is the result of paginating a PageArray of 24 pages (out of 24 _maximum possible_) with a couple of fields autojoined (fields not shown).

`$result = $pages->find('templates_id=45, limit=10, join=cw_issuenum|cw_title');`

As you can see the correct number of items are found and returned on each page, it's just the `total` (and therefore anything derived from it) that is incorrect.

```
// PAGE 1
ProcessWire\PageArray Object
(
    [count] => 10
    [total] => 34
    [start] => 0
    [limit] => 10
    [pager] => 1 to 10 of 34
    [items] => Array (
        [Page:0] => Array ([id] => 1019)
        [Page:1] => Array ([id] => 1020)
        [Page:2] => Array ([id] => 1021)
        [Page:3] => Array ([id] => 1022)
        [Page:4] => Array ([id] => 1023)
        [Page:5] => Array ([id] => 1024)
        [Page:6] => Array ([id] => 1025)
        [Page:7] => Array ([id] => 1026)
        [Page:8] => Array ([id] => 1027)
        [Page:9] => Array ([id] => 1028)
    )
    [selectors] => templates_id=45, limit=10
)

// PAGE 2
ProcessWire\PageArray Object
(
    [count] => 10
    [total] => 34
    [start] => 10
    [limit] => 10
    [pager] => 11 to 20 of 34
    [items] => Array (
        [Page:0] => Array ([id] => 1029)
        [Page:1] => Array ([id] => 1030)
        [Page:2] => Array ([id] => 1041)
        [Page:3] => Array ([id] => 1042)
        [Page:4] => Array ([id] => 1043)
        [Page:5] => Array ([id] => 1044)
        [Page:6] => Array ([id] => 1045)
        [Page:7] => Array ([id] => 1046)
        [Page:8] => Array ([id] => 1047)
        [Page:9] => Array ([id] => 1048)
    )
    [selectors] => templates_id=45, limit=10
)

// PAGE 3
ProcessWire\PageArray Object
(
    [count] => 4
    [total] => 28
    [start] => 20
    [limit] => 10
    [pager] => 21 to 24 of 28
    [items] => Array (
        [Page:0] => Array ([id] => 1049)
        [Page:1] => Array ([id] => 1050)
        [Page:2] => Array ([id] => 1051)
        [Page:3] => Array ([id] => 1052)
    )
    [selectors] => templates_id=45, limit=10
)
```

### Steps to reproduce the issue

In a PW version with autojoin in selectors (3.0.172 and above, I think).

1. Build a list of pages that can be paginated (if necessary).
2. In a template or in a Tracy console, do something like:
```
$joined = $pages->findJoin('template=templateName, limit=10', ['fieldName']);
echo $joined->getTotal();
```
The actual selector doesn't matter as long as it has a limit and at least one autojoined field.

### Setup/Environment

* ProcessWire version: 3.0.175
* PHP version:  7.2.0
* MySQL version: 5.7.19
* 3rd party modules: None (deliberately uninstalled/disabled them to test).

**Comment by ryancramerdesign** [comment]
Thanks @lmdade I've pushed a fix for this issue.

**Comment by lmd-code** [comment]
Thank you! Closing the issue.
