### ISSUE TITLE
$page->matches() returns wrong result

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1367]
### Short description of the issue

`$page->matches()` doesn't seem to take the  "limit" of a selector into account, meaning it can return the wrong result.

Page structure:

![2021-04-23_114911](https://user-images.githubusercontent.com/1538852/115798560-a9d7b580-a42a-11eb-8b04-22830c1d43f6.png)

When I create a selector that would exclude page "Blue" by setting a limit, $blue->matches($selector) returns the wrong result.

![2021-04-23_115203](https://user-images.githubusercontent.com/1538852/115798639-cf64bf00-a42a-11eb-8be5-8fe71a7a275c.png)

### Setup/Environment

* ProcessWire version: 3.0.175

**Comment by ryancramerdesign** [comment]
@Toutouwai The matches() method is performing a comparison rather then a find, so find-specific selector modifiers are ignored because they don't apply here. Actually the database is not even queried as it's all done in memory. https://github.com/processwire/processwire/blob/master/wire/core/PageComparison.php#L232

I think you can get the result you are looking for by performing a find rather than a match, like this:
~~~~~
$matches = $pages->find($selector)->has($blue); // returns bool
~~~~~

**Comment by Toutouwai** [comment]
> The matches() method is performing a comparison rather then a find, so find-specific selector modifiers are ignored because they don't apply here.

Maybe something about that could be added to the docs for this method because I think otherwise people would assume any selector can be used.

And perhaps this method could be enhanced by going to the database when it needs to? If someone is trying to find if a page matches a selector I think they would rather have a slightly slower result than an incorrect result, which is likely to be what is returned if any of the terms in the `$ignores` array are present in the selector.

To cover a broader range of selectors I'm doing this in a module:

```php
/**
 * Does the supplied page match the supplied selector string?
 *
 * @param Page $page
 * @param string $selector
 * @return bool
 */
protected function pageMatchesSelector(Page $page, $selector) {
    $need_find = false;
    // Selector fields that are ignored by $page->matches() and therefore trigger the need for a database search
    $triggers = ['limit', 'start', 'sort', 'include'];
    $selectors = new Selectors($selector);
    // Check selector for trigger fields
    foreach($selectors as $s) {
        if(in_array($s->field, $triggers)) {
            $need_find = true;
            break;
        }
    }
    if($need_find) {
        $ids = $this->wire()->pages->findIDs($selector);
        return in_array($page->id, $ids);
    } else {
        return $page->matches($selector);
    }
}
```

**Comment by matjazpotocnik** [comment]
@Toutouwai ~~how does [this commit](https://github.com/processwire/processwire/commit/13114afe08ffed974ef122033829f717149150bf) affect this issue?~~ Database matches selector will be supported sometime after PW 3.0.225

**Comment by matjazpotocnik** [comment]
https://github.com/processwire/processwire/commit/754fb2b1fd5e70be5c3f24ce06e244734b9086f5

**Comment by Toutouwai** [comment]
Thanks @matjazpotocnik. Closing now that the alternative `Page::matchesDatabase()` method has been added.
