### ISSUE TITLE
ProcessModuleInstall: too few arguments to sprintf()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1371]
### Short description of the issue

PHP Warning: sprintf(): Too few arguments in .../ProcessModule/ProcessModuleInstall.php:306

[Code is](https://github.com/processwire/processwire/blob/94d8cae85a596e7d42e8909fde441f44ef111093/wire/modules/Process/ProcessModule/ProcessModuleInstall.php#L305):

```php
$this->message(sprintf($this->_n('Extracted %d file', 'Extracted %d files', $qty)));
```

### Setup/Environment

* ProcessWire version: 3.0.175

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix

**Comment by Toutouwai** [comment]
Thanks
