### ISSUE TITLE
Unable to remove system status in advanced mode

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1377]
### Short description of the issue

`$config->advanced = true;` provides to edit system statuses via ProcessPageEdit Settings Tab.
Currently it is not possible to remove **statusSystemID** and **statusSystem** if once set

### Expected behavior

If checkbox is provided it should be possible to remove the status.

### creenshots/Links that demonstrate the issue

![Bildschirmfoto 2021-05-06 um 11 36 46](https://user-images.githubusercontent.com/4683120/117277734-6afd2300-ae60-11eb-9621-ee33c9280463.png)

### Setup/Environment

* ProcessWire version: 3.0.177

**Comment by ryancramerdesign** [comment]
System status is not intended to be removable. This is why it is only revealed by advanced mode, a mode used for low level development of the core and such. There are only 2 ways you can remove it (which are intentionally difficult):

- Modify the DB directly
- Manually add the status Page::statusSystemOverride to the page (from PHP code). In a separate statement, remove Page::statusSystem and Page::statusSystemID. In a separate statement, remove Page::statusSystemOverride. Save.

**Comment by kixe** [comment]
I agree. What about adding attribute 'disabled' in this case?
