### ISSUE TITLE
PHP Warning: Undefined array key "tag" in ...\ProcessTemplate\ProcessTemplate.module:3300

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1379]
There is a warning when you create a template tag by going to Setup->Templates->Manage tags. I guess there is a typo in line 3300 $labels[tag**s**] vs. $labels[tag]

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this
