### ISSUE TITLE
renderPager() wrong behaving in admin and frontend

### ISSUE THREAD

**Issue by godmok** [processwire/processwire-issues#138]
### Short description of the issue

renderPager() function is not behaving like it should. If I click to the next page, the URL is changed, but the pagination is set like on page 1, actual page is not selected/marked in pagination. Results are set to the page number.
This is happening in the Admin as also in the frontend API output. ProcessWire 3.0.45 is working normal.

### Expected behavior

renderPager() modifies the markup of the pagination by set page number. Page number is selected/marked by actual page.

### Actual behavior

renderPager() generates the same markup on every page. A click to a page/link on the pagination will not updated the markup and stays the same. The previous link will not be generated.

### Steps to reproduce the issue

1. go to /processwire/access/users/ or /processwire/page/lister/
2. use the pagination on the right side to get to the next/last or any other page
3. the list will be updated but markup will stay the same

### Setup/Environment

* ProcessWire version: 3.0.46
* PHP version: 7.0

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate and fix this yesterday. Please let me know if you run into any further issues with it.
