### ISSUE TITLE
TypeError in_array(): Argument #2 ($haystack) must be of type array, string given

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1380]
This error is shown in /wire/modules/Process/ProcessTemplate/ProcessTemplate.module, line 3360, when you go to Setup->Templates->Manage Tags. It happens when you clear all checkboxes and click Submit. `$tagsTemplates` is empty since `$input->post('tag_templates')` is null.

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
Thanks.
