### ISSUE TITLE
Forgot Password Bug

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#1381]
### Short description of the issue

Setting email field unique and using email field for ProcessForgotPassword fails to reset.

### Expected behavior

I would expect it to work :)

### Actual behavior

It says "this email address is already in use"

### Optional: Screenshots/Links that demonstrate the issue

After following link to reset password:

![image](https://user-images.githubusercontent.com/190857/117584158-2d6bf480-b103-11eb-8099-61b3a7cffade.png)

You enter the details in the form above and get this message:

![image](https://user-images.githubusercontent.com/190857/117584170-45437880-b103-11eb-9a27-8724bf00e2e5.png)

### Optional: Suggestion for a possible fix

All I can help with is the line where it breaks: Line 113 of InputfieldEmail.module:

`$changed = strtolower($value) !== strtolower($valuePrevious);`

$valuePrevious appears to be empty so it thinks it has changed when it hasn't.

### Steps to reproduce the issue

1. Make system "email" field unique under the field's advanced tab
2. Edit ProcessForgotPassword module to tick "Use email rather than name" and set "email" as the field to confirm:
![image](https://user-images.githubusercontent.com/190857/117584248-c0a52a00-b103-11eb-9cc4-1c0f67c2834c.png)

3. Hopefully you'll see the error

Note: in the screenshot above I noticed it says to use "text or number field" and I'm using email, so that could well be it - and to be fair it doesn't make much sense using that as the field to confirm if they just clicked on the email, but I think it's good enough field to use to ensure it's hopefully a human resetting the password and not a bot.

### Setup/Environment
* ProcessWire version: 3.0.177
* (Optional) PHP version: 7.4.16

**Comment by ryancramerdesign** [comment]
Thanks @Notanotherdotcom I've pushed a fix for this issue.

**Comment by Notanotherdotcom** [comment]
Thanks Ryan - that was fast 😄
