### ISSUE TITLE
"recursive" option for $files->find() is confusing

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1382]
### Short description of the issue

The documentation for the "recursive" option of `$files->find()` says:

> recursive (int): How many levels of subdirectories this method should descend into (default=10)

That makes it sound like if I don't want it to descend into any subdirectories then I should set recursive to 0. But this has the effect of not limiting the recursion.

It turns out that the correct setting for "recursive" if you don't want to descend into subdirectories is 1, but if I didn't know better I would think this allows descent into 1 level of *sub*directories.

Of course it wouldn't be good to change the behaviour of the "recursive" option now but perhaps the documentation could be edited to somehow indicate that 1 means find files in the given *directory* and doesn't mean a descent into *any subdirectories*.

I believe @adrianbj has been caught out by this too so I'm not the only one :slightly_smiling_face:

**Comment by Toutouwai** [comment]
And maybe there could be some easy shortcut to find files in the given directory without recursion because it seems like quite a common need.

**Comment by matjazpotocnik** [comment]
@Toutouwai there is some improvement regarding this issue in this commit https://github.com/processwire/processwire/commit/3229d2371e9391111792c23567ef9026258d7712 (https://github.com/processwire/processwire/blob/3229d2371e9391111792c23567ef9026258d7712/wire/core/WireFileTools.php#L696)

**Comment by Toutouwai** [comment]
Looks great, thanks @ryancramerdesign
