### ISSUE TITLE
FieldtypeTextUnique outdated

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1383]
Hi, on the late PW betas, FieldtypeTextUnique starts throwing SQL errors here.
Comparing the code with FieldtypeText, the code there looks kind of outdated.

_Details, if that matters:_
I used it on a fresh PW install where I tried to set a new field and got this:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (checkFieldTable)
In "fields" the field was created as a new entry, but there was no associated field table installed with it.
(On existing PW installs, the field still works, just with the fresh PW beta install the SQL I saw this, where using normal FieldtypeText work fine for the new field.)

_And a long-standing wish for this fieldtype:_
When duplicating a page using a FieldtypeTextUnique field, instead of throwing a "duplicate found" error maybe just leave the field blank on the newly created page copy?

**Comment by ryancramerdesign** [comment]
@tbba This module is not part of the core and not updated to support ProcessWire 3.x. I guess I didn't realize anyone was using it. But now that I know you are using it, I'll bring it up-to-date. If possible, could you move this issue report to the repo for that module, where is [here](https://github.com/ryancramerdesign/FieldtypeTextUnique). Thanks.

**Comment by tbba** [comment]
Interesting. I thought it was from the core and never spent much thought on it. 
I use it quite a lot actually. License keys for example and all sorts of Ids.
I  close this and move this over now. Thanks for considering to updating it.
