### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1384]
Hello @ryancramerdesign ,
is it possible to inhibit multilanguage redirects to the default language url for templates with useLanguages disabled?
I have a sitemap-xml template (name=sitemap.xml) and I would like to have the one page using it being accessed via:
`https://mysite.tld/sitemap.xml`, without being redirected to `https://mysite.tld/en/sitemap.xml`, but at the same time keeping the `en` prefix for the other (language-aware) pages.
kind regards

**Comment by ryancramerdesign** [comment]
URL hooks might be a good way to accomplish that?
https://processwire.com/blog/posts/pw-3.0.173/

**Comment by pine3ree** [comment]
Hello @ryancramerdesign, thanks. I was looking for a more general solution for different pages with names/urls editable by users, but maybe there is no point: all pages have page ID=1 as top-level parent (root, one of the peculiar things of pw that I like), so the root url-segment is always inherited! I was looking for a way to force skipping redirection (to a root-name prefixed path) for any generic user editable page...

**Comment by pine3ree** [comment]
mmm.. @ryancramerdesign  its seems that if the page has the same path that gets intercept the redirect still happens, I had to rename it to "sitemap-xml" and intercept the non-existing '/sitemap.xml' path
