### ISSUE TITLE
URL Input in ProcessPageEditLink

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1385]
In ProcessPageEditLink, on the input field where you enter the link URL, there is a small icon at the beginning. When you enter the URL the text is displayed over the icon making it hard to read. It looks like the left padding of 8px is too small.

![image](https://user-images.githubusercontent.com/7663992/119085182-8b51e380-ba03-11eb-859c-3f81a35d646e.png)

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I can't seem to duplicate this one. Which admin theme are you seeing it in? Here's what I see in AdminThemeUikit, though I think the padding comes directly from the PageAutocomplete module. 

<img width="361" alt="Screen Shot 2021-06-01 at 11 37 05 AM" src="https://user-images.githubusercontent.com/328272/120351347-ce4a6b80-c2cd-11eb-9d80-6a0c75f9d749.png">

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, thanks for looking into this. Strangely, I can't reproduce either. Weird. I'll close this. Sorry for wasting your time.
