### ISSUE TITLE
Comments reply depth not working correctly in pw 3.0.165/dev, also general problem with comments field/module

### ISSUE THREAD

**Issue by q107** [processwire/processwire-issues#1387]
### Short description of the issue

Comments reply depth option is not working correctly in latest stable and dev versions.
Also, when installed on local environments (i.e. XAMP on windows) several comment features are broken after saving changes in comments field. 

### Expected behavior

~~Replies should appear with comment being replied to.~~
Replies should work at maximum allowed depth level.
_(xamp only)_ User votes, stars ratings and website field should not reset or disappear after changes made to comments field.

### Actual behavior

~~Replies are always displayed as normal (flat) comments, no matter the value entered in Reply depth input.~~
Replies are not working at the maximum depth allowed level (ie. when max allowed level is set to 4, the replies will work only up to level 3).
_(xamp only)_ Votes, star ratings, and website field are working correctly only after initial setup. When any changes are made to the comments field after first comment is added, everything kind of resets/breaks itself. Already stored votes and stars will disappear in the front-end. Initially enabled star ratings and website field will now also disappear from the comment form.
Submitting new comments will work without any problems though.

### Screenshots/Links that demonstrate the issue

![comments](https://user-images.githubusercontent.com/47921517/119750193-15cd9380-be99-11eb-9eb3-980264c125bb.gif)

### Suggestion for a possible fix

Regarding the reply depth, I think the problem is with this if statement:
https://github.com/processwire/processwire/blob/b087149c4071d88a590ec144daf2e9117855bf92/wire/modules/Fieldtype/FieldtypeComments/CommentForm.php#L876-L882

Changing:
`if($parents->count() >= $maxDepth) {`
to
`if($parents->count() > $maxDepth) {`

seems to fix the the reply depth problem.

### Steps to reproduce the issue

1. Install Comments module in the latest stable or dev.
2. Add new comments field, set comments depth to 1, enable voting, star rating and website field. In Action tab assign comments field to a desired template.
3. Output comments on the front-end as instructed in field's Detail tab (load jquery, comments.css and comments.js).
4. Add comment and then reply to that comment (reply will not be assigned to the parent comment).
5. Add more comments / replies and interact with votes and stars.
6. Go back to the comments field, change any option and save your changes.
7. Refresh page with comments in the front-end.

### Setup/Environment

* ProcessWire version: blank 3.0.165 with no 3rd party modules (also tested on 3.0.148, 3.0.163, 3.0.170 and 3.0.178)
* PHP version: 7.3.1 and 7.4.15
* MySQL version: MariaDB 10.1
* Tested on blank install with just comments module installed

**Comment by ryancramerdesign** [comment]
@q107 Thanks for the report. So far, I can't seem to duplicate these. I'm using comment depth on a few different installations, including the main PW site (always running latest dev branch) - [example](https://processwire.com/blog/posts/find-faster-and-more-efficiently/#comments). I've also implemented threaded comments for a new site 2 months ago, but didn't experience the issues you've mentioned. Can you think of any other potential factors that might be present or needed to duplicate? Thanks.

**Comment by q107** [comment]
@ryancramerdesign 
After trying to troubleshoot this issue for the past two days, it seems that my local (windows 7) xampp installation is affected with the save glitch. Installing new xampp version didn't help, nor did LAMP server on a virtual machine,

Switching to remote hosting seems to resolve the comments field saving glitch, but the reply depth is still not working as expected. It is working (kinda) from depth level 2 onward.
Here's the updated scenario:
- Depth level 1: the 'Reply' link is displayed, but replies are submitted as normal, flat comments.
- Depth level 2: submits the first reply no problem. The 'Reply' link on the first reply is visible, but it will be submitted as reply to the first comment.
- Depth level 3: first reply, and reply to the first reply are working ok. Reply to the second reply will be submitted as reply to the first reply.
And so on...

Pic below might visualize it more clearly.
![comments-depth](https://user-images.githubusercontent.com/47921517/120687230-17ebaf80-c4a2-11eb-98b6-ad9ea9afb6d6.png)

I've scanned some of the processwire.com blog posts with high comment count, and replies mostly end at level 3. So if the reply depth is at level 4 or higher, this issue might be practically unnoticeable.


**EDIT**:
I think the problem is with this if statement:
https://github.com/processwire/processwire/blob/b087149c4071d88a590ec144daf2e9117855bf92/wire/modules/Fieldtype/FieldtypeComments/CommentForm.php#L876-L882

I changed:
`if($parents->count() >= $maxDepth) {`
to
`if($parents->count() > $maxDepth) {`

And the depth now is working as expected.

**Comment by MrSnoozles** [comment]
Confirming that something is off with the comments (Windows 10 here).

Depth, or upvotes and downvotes are not loaded into the CommentArray. It seems to be correct in the database, but not loaded from there. (Database table `field_comments`)

![grafik](https://user-images.githubusercontent.com/17496592/120996856-00a11080-c787-11eb-90f3-9f77d1d53c37.png)

When outputting the comments with `$page->comments->render()` there is no hirarchy and no upvotes

![grafik](https://user-images.githubusercontent.com/17496592/120997132-4067f800-c787-11eb-9db6-44ac013e0420.png)

**Comment by MrSnoozles** [comment]
Problem for me is that `$field->get('schemaVersion')` returns 0. It therefore doesn't return anything that has been added after the initial version of the module. Still figuring out why it returns 0 and where the schema version is stored.

**EDIT:**
Updating the schemaVersion in the database table `fields` to 6 has fixed all the issues. Problem seems to be that upon installation the correct version wasn't written. MySQL version 5.7.24

![grafik](https://user-images.githubusercontent.com/17496592/121014941-c80b3200-c79a-11eb-8e45-e72e0966d092.png)


@q107 This is probably not what's causing your issue, right? Does the data look identical in the local and remote database tables (in the `field_comment` table)?

**Comment by q107** [comment]
@MrSnoozles thanks, but just to be sure that depth is really working on your end, can you please test replies with depth level set to 1?

Also good catch with schemaVersion. On my local installation schemaVersion is initially (after module is installed, and field is added to the template) set to 6. Then if I make changes to the field, the schemaVersion switches to 0 and breaks everything (as shown in first gif). If I manually update the schemaVersion to 6, then everything (except depth) is again working ok.

**Comment by MrSnoozles** [comment]
Just checked it. Reply depth seems to be working without problems once the schemaLevel is set to 6. Sorry I can not confirm the issue.
Also it doesn't change back to 0 for me when I save the field. (I'm relatively sure this issue is related to saving the field somehow, but I could not reproduce that it gets set back to 0 by changing the reply depth). Do you have a way to reproduce the save bug?

Question to Ryan: Would you accept a PR that adds a public method to remove the vote for a given userId and that allows only an up- or a downvote from a single user, but not both?

**Comment by q107** [comment]
@MrSnoozles The reason why I specifically asked for reply depth at level 1, is because it's the fastest way to check if it's working correctly (in your pic I see it's on level 2 or higher - so it's kind of working as I stated [here](https://github.com/processwire/processwire-issues/issues/1387#issuecomment-854096333).)

I have also edited the OP to (hopefully) clear the confusion, and provided a fix for the reply depth issue.

**Comment by ryancramerdesign** [comment]
> I think the problem is with this if statement:

@q107 If I make the change you suggested, I'm now getting 5 layers of depth rather than the configured 4. But I think it comes down to how you interpret the term "depth". I'm interpreting it to be a visual thing, like how many visual levels a comment can appear at. I think you are interpreting it to mean how many levels past the first level. In reading the "reply depth" field description, I think your interpretation is probably the right one here, so I will update this.
