### ISSUE TITLE
$pages->findRaw() ignores selector sort

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1389]
### Short description of the issue

`$pages->findRaw()` seems to ignore the sort specified in the selector.

![2021-05-27_223323](https://user-images.githubusercontent.com/1538852/119811777-9349e000-bf3b-11eb-8a9e-1e7a93d8e171.png)

The introductory blog post says:

> The $selector argument can be any page-finding selector that you would provide to a regular $pages->find() call.

So not sure if that means it is supposed to respect the specified sort. I know it's getting raw data straight from the database but I thought an ORDER BY could be possible?

### Setup/Environment

* ProcessWire version: 3.0.178

**Comment by Toutouwai** [comment]
Looks like the sort is doing *something* but it's not what you'd expect.

![2021-05-27_225113](https://user-images.githubusercontent.com/1538852/119814146-2edc5000-bf3e-11eb-8e0b-134b1dca638f.png)

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this. I found the fix is only necessary when there are no native pages table columns included in the list of values to return.

**Comment by matjazpotocnik** [comment]
@Toutouwai is this issue fixed?

**Comment by Toutouwai** [comment]
Fixed now, thanks.
