### ISSUE TITLE
Page List Select: Array to string conversion in /wire/core/Inputfield.php on line 1358

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1390]
Hello, I am using pw-dev.3.0.178. I have a couple of pages with a page fieldtype. When saving the page I noticed the array to string conversion happening [here]( https://github.com/processwire/processwire/blob/c93423365f94e0f8de56b30935d6e5d699b5cada/wire/core/Inputfield.php#L1358)

This happens either if I actually choose a page or I do not. The values of `$value` and `$previousValue` are both arrays:
```php
// 1 .required page not selected
$value === [""];
$previousValue === [];

// 2 . required page selected
$value === ["ID-of-the-selected-page"];
$previousValue === [];
```
Using a simple html Select input the warning disappears.
Before line 1331 (php`if(is_array($value)) {`), `$value` is the empty string, so I guest it is altered via `setAttribute()` in line 1356;
kind regards

(edited) fixed some typos and comments

**Comment by adrianbj** [comment]
I have also seen this.

**Comment by pine3ree** [comment]
mmm...i believed it was already solved here: https://github.com/processwire/processwire/commit/c93423365f94e0f8de56b30935d6e5d699b5cada
