### ISSUE TITLE
"Move" page list action does not determine "sortable" correctly

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1394]
### Short description of the issue

ProcessPageListActions.php determines if a page is sortable with [this code](https://github.com/processwire/processwire/blob/04e2de28f057335979aa2a821fa4684d74303515/wire/modules/Process/ProcessPageList/ProcessPageListActions.php#L103):

```php
$sortable = $page->sortfield == 'sort' && $page->parent->id && $page->parent->numChildren > 1 && $page->sortable();
```

But a page is sortable or not depending on the `sortfield` of the _parent_ page/template, not of the page itself. And instead of checking the `sortfield` property it should call the `sortfield()` method to account for sort rules defined for the template as well as for the page.

This issue means that the "Move" action appears in Page List in situations where it shouldn't, namely when the page is not moveable and is not sortable due to sort settings on the parent. In these cases the sort will always fail so there's no point in showing the "Move" action in Page List.

### Suggestion for a possible fix

Change the line above to:

```php
$sortable = $page->parent->sortfield() == 'sort' && $page->parent->id && $page->parent->numChildren > 1 && $page->sortable();
```

### Setup/Environment

* ProcessWire version: 3.0.179

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai good find, I've pushed your suggested fix.

**Comment by Toutouwai** [comment]
Thanks
