### ISSUE TITLE
Logs showing incorrect entries when saved with the showURL option set to false.

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1396]
### Short description of the issue

Logged lines saved with showURL option set to false sometimes show with the message text in the URL position (as shown here).

![Selection_114](https://user-images.githubusercontent.com/16049/121783564-d8f2e380-cb9e-11eb-8a87-65ac6628c8cf.png)

This appears to happen when the message being logged has a URL in it - other lines appear to render correctly.

### Expected behavior

Logs written with the showURL option set to false should correctly render logged lines.

### Suggestion for a possible fix

The WireLog::save() method does not write an empty url value + field separator to the logged text if the showURL option is false.  If I add an extra tab character to the log lines where the URL field would have been, everything displays correctly.

I think moving [L159](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/core/WireLog.php#L159) down one line, placing it outside the closing brace, should fix this. The $url variable will need a default value if this is done.

This probably also applies to L171 of the same file for the case of dealing with showUser as well.

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.148|
|PHP|7.4.4|
|Webserver|Apache/2.4.41 (Unix) OpenSSL/1.1.1d|
|MySQL Server|5.5.5-10.3.22-MariaDB-1:10.3.22+maria~bionic|
|MySQL Client|mysqlnd 7.4.4|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|120|
|max_input_vars|8000|
|memory_limit|512M|
|post_max_size|72M|
|upload_max_filesize|64M|
|xdebug||
|xdebug.max_nesting_level|256|
|mod_rewrite|1|
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.10|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG||
|PDF|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|ClearCacheAdmin|0.0.5|
|LoginRegisterPro|0.0.4|
|NiftySlackLogs|0.0.2|
|ProCache|4.0.1|
|ProcessDatabaseBackups|0.0.5|
|ProcessEmailTracker|0.1.0|
|ProcessFeatureRollout|0.1.0|
|ProcessForgotPassword|1.0.3|
|ProcessOrgcharts|1.6.2|
|ProcessPageListerPro|1.1.3|
|ProcessProCache|4.0.1|
|ProcessResque|0.5.0|
|ProcessResqueEchoCRMJobControls|0.0.1|
|ProcessResqueWatchdogJobControls|0.0.1|
|ProcessSwitchUser|0.0.5|
|ProcessTracyAdminer|1.1.0|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SendinBlueIntegration|0.1.0|
|TracyDebugger|4.21.41|
|WireMailMailgun|0.5.1|
|WireMailResqueMailer|0.0.1|
</details>

**Comment by ryancramerdesign** [comment]
@netcarver It doesn't seem like that good of an idea anymore, but the original intention was that one could dictate their own log format when/if they wanted to for other purposes. I also wanted some flexibility to decide later what log format worked best for us, so had those options there. ProcessLogger was built quite a bit later and designed to display logs that use the ProcessWire/default log format. While we could add extra tabs or blank columns in the log so that other formats might work in ProcessLogger, I think it probably wouldn't be useful for it's original purpose anymore. Though maybe nobody needs it for that purpose, I don't really know.

**Comment by netcarver** [comment]
@ryancramerdesign Hi Ryan - yes at least we can hook that function to write it the way we need. On a similar note then, could you make ProcessLogger::formatLogText() hookable?  This would then allow customisation of the display format as well via a hook  - at the moment I'm having to use a copy of ProcessLogger in the site/modules directory.

**Comment by netcarver** [comment]
BTW, I made the changes I posted about in the OP (plus defining a default URL) to the save method and it seems to work.

**Comment by matjazpotocnik** [comment]
@netcarver, based on this [commit ](https://github.com/processwire/processwire/commit/50dff006b5af2ba8c9bb79d7df58c499425728b1) ProcessLogger::formatLogText() is now hookable.

**Comment by netcarver** [comment]
Thanks, @matjazpotocnik closing now.
