### ISSUE TITLE
Language titles gone in the admin panel with specific user role after Processwire upgrade

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1397]
Since one of the last (2-3?) updates, something happend with the translation-roles in our admin panel.

I have for each languages separate translation roles (translate-de, translate-en, translate-es, ...) and one "translate-all" role.

Since an upgrade the titles of the languages are gone and the name is displayed instead. 

User with translate-all role.
![image](https://user-images.githubusercontent.com/488163/121857365-d787ff00-ccf5-11eb-9685-094eb6dc6435.png)

Superuser
![image](https://user-images.githubusercontent.com/488163/121857449-ef5f8300-ccf5-11eb-879a-7d4ac27e0454.png)

When I give the User the translate-de, translate-en, etc. role, the titles are back.
But I don't understand why this doesn't work with my translate-all role.

Current PW Version: 3.0.179

**Comment by ryancramerdesign** [comment]
@tiefenb That's strange, I'm not sure what could account for that. Or is it possible you've got access control enabled for your title field?

**Comment by tiefenb** [comment]
> @tiefenb That's strange, I'm not sure what could account for that. Or is it possible you've got access control enabled for your title field?

Yes Access Control for the title field ist also enabled - I need this for ProcessGraphQL:

![image](https://user-images.githubusercontent.com/488163/122463843-69be2a80-cfb6-11eb-9a49-50e07a31fa34.png)

**Comment by ryancramerdesign** [comment]
@tiefenb [Here](https://github.com/processwire/processwire/blob/dev/wire/modules/LanguageSupport/LanguageTabs.module#L179) is where this is happening. It asks the language for the title and if it returns blank then it asks the language for the name. The question is why it's returning blank for the title for users with your translate-all role.  Here's a few more questions:

- What permissions does that translate-all role have? 
- What permissions does a translate-de role have? 
- What other roles does a user with translate-all permission have?
- Can you check the “Overrides” tab when editing your title field to see if there are any contextual access modifications (especially with the 'language' template)?
- I'm also curious if you might have access control enabled for your Language template?

If you are interested in seeing where the logic happens, the field viewable permission is located [here](https://github.com/processwire/processwire/blob/dev/wire/modules/PagePermissions.module#L456). I suspect it is getting to the last statement in the method which calls `$field->editable($page)`, and that is arriving to `Fields::_hasPermission()` located [here](https://github.com/processwire/processwire/blob/dev/wire/core/Fields.php#L1050), which is likely what is making the final call on whether the field is viewable.

**Comment by matjazpotocnik** [comment]
@tiefenb any progress with this issue? Can you provide more info? Or perhaps close it?

**Comment by netcarver** [comment]
@tiefenb Markus, could you update of close this one as well please?

**Comment by tiefenb** [comment]
It still happens but our authors can work with this issue and I haven't enough time to go deeper into it.
