### ISSUE TITLE
PagePaths: table not updated when parent changed, causes 404

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1398]
### Short description of the issue

If the PagePaths module is installed and a page's parent is changed via the API then the `pages_paths` table is not updated, and when you attempt to view the page in the front-end a 404 occurs.

Page tree before:

![2021-06-15_210352](https://user-images.githubusercontent.com/1538852/122026037-fd102800-ce1d-11eb-9404-60bce19a5866.png)

API code:

![2021-06-15_210918](https://user-images.githubusercontent.com/1538852/122026064-04cfcc80-ce1e-11eb-8cb0-3168302b51ac.png)

Page tree after:

![2021-06-15_210406](https://user-images.githubusercontent.com/1538852/122026084-0c8f7100-ce1e-11eb-851b-3033c6f70ab2.png)

`pages_paths` table after:

![2021-06-15_210236](https://user-images.githubusercontent.com/1538852/122026143-174a0600-ce1e-11eb-8bf6-2a1bee84acb7.png)

Attempting to view moved page:

![2021-06-15_211047](https://user-images.githubusercontent.com/1538852/122026307-2e88f380-ce1e-11eb-9f15-23c8ebfc38be.png)

And it is possible to view the page at its old URL as if the page has not been moved.

### Setup/Environment

* ProcessWire version: 3.0.179

**Comment by Toutouwai** [comment]
It looks like this issue affects PagePathHistory also. No previous paths are being saved when the page is moved by changing its parent via the API.

**Comment by Toutouwai** [comment]
The issue doesn't occur when a Page object is set as the new parent. 

![2021-06-15_214609](https://user-images.githubusercontent.com/1538852/122031768-1d8eb100-ce23-11eb-8f97-822dbce3c689.png)

But according to Page:set() an ID should be accepted when setting the parent.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue

**Comment by Toutouwai** [comment]
Thanks
