### ISSUE TITLE
Overflowing text in descriptions/notes

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#14]
> Briefly describe the issue.

Repost of https://github.com/ryancramerdesign/ProcessWire/issues/1132

> What did you expect to happen?

Long words to break at the line end.

> What did actually happen?

Line does overflow.

> Optional: Do you have screenshots/links that demonstrate the issue?

https://www.dropbox.com/s/xhdnkdum8ozaric/Screenshot%202016-10-01%2010.58.24.png?dl=0

> Optional: Have you a suggestion for a possible fix?

`word-wrap: break-word;`

> What are the steps to reproduce the issue?

Put a long url in the field description or notes.

> Tell us about the setup you experienced the bug in.

* ProcessWire version: 3.0.35

**Comment by ryancramerdesign** [comment]
Thanks I've an update that applies the fix you suggested.
