### ISSUE TITLE
PHP-Notice when using TextformatterMarkdownExtra with ParseDown Extra and PHP 7.4

### ISSUE THREAD

**Issue by tobaco** [processwire/processwire-issues#1401]
### Short description of the issue

When using the core MarkDown textformatter I get the following PHP-Notice

`Trying to access array offset on value of type null in /wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php on line 241`

### Expected behavior

No notice.

### Actual behavior

Notice with the message above.

### Optional: Suggestion for a possible fix

This seems to be an issue with the ParseDown Extra package. see https://github.com/erusev/parsedown-extra/issues/140
Upgrading the package should do the trick.

### Steps to reproduce the issue

1. Enable debug mode or show notices
2. Create a textarea field
3. Use TextformatterMarkdownExtra with ParseDown Extra 
4. See output in frontend

### Setup/Environment

* ProcessWire version: 3.0.179
*  PHP version: 7.4

**Comment by ryancramerdesign** [comment]
Thanks @tobaco I have updated the Parsedown and ParsedownExtra versions to the newest.
