### ISSUE TITLE
InputfieldDatetimeSelect.php issue & fix - February is output as as March with mktime()

### ISSUE THREAD

**Issue by alexmercenary** [processwire/processwire-issues#1402]
### Short description of the issue

When you use DateTime Inputfield with separate fields, the months that are rendered show January, March, March, April, May etc.

### Expected behavior

February should be output

###  Suggestion for a possible fix

It needs a 5th parameter of 1 so that it uses the first day of the month, as with February being shorter it tries to grab a day that doesn't exist and rolls over onto the next month (March).

On line 93 of InputfieldDatetimeSelected.php:
strftime($monthFormat, mktime(0, 0, 0, $n)) changed to strftime($monthFormat, mktime(0, 0, 0, $n, 1))

**Comment by ryancramerdesign** [comment]
Thanks @alexmercenary that's a good find, I've pushed your suggested fix.

**Comment by alexmercenary** [comment]
Thanks @ryancramerdesign
