### ISSUE TITLE
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. 

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1404]
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /src/html/wire/modules/LanguageSupport/LanguageTranslator.php on line 181

* ProcessWire version: 3.0.181
* PHP version: 7.4

**Comment by ryancramerdesign** [comment]
Thanks @tiefenb I've pushed a fix

**Comment by tiefenb** [comment]
Thx!
