### ISSUE TITLE
Files are not deleted from filesystem

### ISSUE THREAD

**Issue by nabo** [processwire/processwire-issues#1406]
### Short description of the issue

When I have an unpublished page I check the files I want to delete. If publish the page files disappear from frontend but remain stored in filesystem. If I save the page (not publish) files are deleted in both places.

### Expected behavior

I expect files to be deleted

### Optional: Suggestion for a possible fix

I think it depends on directory renaming before delete process. I noticed this behavior with big files.

### Steps to reproduce the issue

1. Create a page with pagefiles field and load a file and do not publish (only save)
2. Delete the file(s) and publish
3. Watch the filesystem

* ProcessWire version: 3.0.165

**Comment by ryancramerdesign** [comment]
@nabo Thanks, I've pushed a fix for this issue. You were right about it having to do with the directory renaming, so this would only apply if you were using the `$config->pagefileSecure = true;` option. If you aren't using that option, please let me know.

**Comment by nabo** [comment]
@ryancramerdesign I confirm you that I'm using that option :)
