### ISSUE TITLE
Capitalization ignored in InputfieldTextTags

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1407]
### Short description of the issue

If you create a tag with capitalization (f.e. "Foo") and select it via autocomplete in an other field, the capitalization is ignored.

### Expected behavior

The capitalization should not be ignored. 

### Actual behavior

A new tag with no capitalization will be created.

### Steps to reproduce the issue

1. Create a tag with capitalization (f.e. "Foo") on a field or template.
2. Select the tag via autocomplete on an other field or template.
3. Save the field or template.
4. After saving the tag has no capitalization.

### Setup/Environment

* ProcessWire version: 3.0.181

**Comment by designconcepts** [comment]
On a fresh installation of ProcessWire 3.0.189 dev I don't seem to have this issue anymore.
I can select every new created tag with capitalization.
So I think this issue can be closed.

Regards, Andreas

**Comment by gRegorLove** [comment]
@ryancramerdesign @designconcepts This appears to be an issue in stable 3.0.184. Can you provide more details on the fix in subsequent versions so I can maybe backport it? I don't want to run PW dev currently, but would like to clean this bug up if possible.
