### ISSUE TITLE
Languages submenu doesn't visually indicate hidden / unpublished

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1408]
### Short description of the issue

Languages in the Setup > Languages > submenu are all the one color whether they are normal, hidden, or unpublished.

![image](https://user-images.githubusercontent.com/871211/125177811-bb13a100-e193-11eb-8243-89d6220d29e1.png)

### Expected behavior

It should look like the Tree submenu with the lighter grey (hidden) and strikethrough (unpublished)

### Actual behavior

They are all the same color

**Comment by ryancramerdesign** [comment]
@adrianbj I have pushed an update that adds support for this.

**Comment by adrianbj** [comment]
Thanks.
