### ISSUE TITLE
Language tabs activity does not get set according to user language

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1411]
### Short description of the issue

The language tabs indicators for multilanguage firlds are not set correctly accordingly to user language on page load in admin edit page. Though the fields' inputs are.

### Expected behavior

The language tabs indicators for multilanguage firlds should be set accordingly to user language.

### Optional: Screenshots/Links that demonstrate the issue

![изображение](https://user-images.githubusercontent.com/6697626/125957320-93af52ee-fbcd-4c8d-99cc-8cd7980941b1.png)

The selected lang is Deutsch, the content of the "Titel" field is Uber (in German), but the field label is still English. At first I [thought it is AdminOnSteroids related](https://processwire.com/talk/topic/13389-adminonsteroids/?do=findComment&comment=216123), but now I disabled AOS and see the same thing, I guess it must be a core issue.

### Setup/Environment

* ProcessWire version: 3.0.181

**Comment by ivangretsky** [comment]
There was a [recent commit](https://github.com/processwire/processwire/commit/fb7406c3e6115806d6dcd5f47c4600c822eaa229) that changed the code dealing with LanguageTabs. Could it affect this? I didn't find issues there, but still worth mentioning.

**Comment by ryancramerdesign** [comment]
@ivangretsky I can't duplicate it here. But I could before that recent commit you mentioned. The Uikit upgrade broke the language tabs in the manner you are seeing there but LanguageTabs.js was updated to work around the Uikit changes. It could be that you've got the older LanguageTabs.js stuck in your browser cache or something, so you may want to try with your browser dev tools open to disable browser cache. Doing a Modules > Refresh may also solve it.

**Comment by jmartsch** [comment]
This problem exists in PW 3.0.179. It is fixed in 3.0.181

**Comment by ivangretsky** [comment]
Yep. It seems to work fine after modules refresh and with the dev tools open. But caching issue is really bad. Maybe we could think about adding version urls for assets.

**Comment by szabeszg** [comment]
> Maybe we could think about adding version urls for assets.

For "versioned" URLs I recommend appendig timestamps of the last modification of the file in question instead of some sort of manually/automatically incremented integers.

**Comment by jmartsch** [comment]
Yes. The problem is not fixed by refreshing the modules, but instead when having cache disabled (dev tools open) or clearing the cache.

**Comment by jmartsch** [comment]
I suggest to re-open this issue, until the problem with the cache is fixed.

**Comment by madebymats** [comment]
I was bit by this one too. I had to log out and log back in again for the changes to apply.

**Comment by matjazpotocnik** [comment]
@madebymats @jmartsch (and others): is this issue now fixed?

**Comment by ivangretsky** [comment]
@matjazpotocnik the issue now is that the admin caching works in such a way that we cannot cleat it easily. Should we split the issue/create the new one?

**Comment by matjazpotocnik** [comment]
As far as I can test, the language tabs are working as they should – the language tabs indicators for multilanguage fields are set accordingly to the user language. The cache issue with LanguageTabs.js is still here. Opening a new issue would most likely get more attention from Ryan.

**Comment by ivangretsky** [comment]
I've created a [dedicated issue](https://github.com/processwire/processwire-issues/issues/1752) for caching problem and closing this one.
