### ISSUE TITLE
UI glitch on template access field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1412]
### Short description of the issue

When the "Do you want to manage view and edit access for pages using this template?" field value is changed from "No" to "Yes" the "What roles can access pages using this template (and those inheriting from it)?" field appears. But this field is missing its normal outline.

When the settings are saved and the page reloads with the ""What roles can access pages using this template..." field visible then the outline is shown.

See the screencast:

![outline](https://user-images.githubusercontent.com/1538852/126056787-297afa9b-4b7b-4ddf-a0fb-04a6e6c7f04f.gif)

### Setup/Environment

* ProcessWire version: 3.0.181

**Comment by ryancramerdesign** [comment]
@Toutouwai This seems to have something to do with the jQuery version. Try setting `$config->debug = 'dev';` in your /site/config.php file, which will make it user a newer jQuery version. The outline/border will then appear, at least once the Inputfield finishes opening. I notice in your GIF also that your "Do you want..." Inputfield remains open when clicking Yes. Mine closes while the roles open. I don't recall changing anything related to that recently, so don't think it's a version difference, but wanted to mention it.

**Comment by Toutouwai** [comment]
When I set `$config->debug = 'dev';` then I see the same as you: the outline appears after the field has expanded and the "Do you want..." field automatically collapses when clicking Yes. Although the second of these things doesn't seem right to me. I think users still want to see the Yes/No setting when Yes is selected, and in fact when you save and reload that field is no longer collapsed.

**Comment by Toutouwai** [comment]
Actually, when I test on two very similar v3.0.182 installations I get different behaviour for the "Do you want..." field. On one site it collapses when Yes is selected and on the other it doesn't. Will see if I can work out what is different about them.

**Comment by Toutouwai** [comment]
I've cleared both sites and reinstalled v3.0.182 with the blank profile and now neither of them now collapse the "Do you want..." field when Yes is selected, with or without `$config->debug = 'dev';`. So that collapsing behaviour must be caused by some non-default core setting or a non-core module.

**Comment by Toutouwai** [comment]
I found what's responsible for the collapsing of the "Do you want..." field. It's the newish "Inputfield label toggle behavior" setting in the Uikit module:
![2021-07-30_124535](https://user-images.githubusercontent.com/1538852/127583114-b5d174f2-97d6-41d2-893f-f0f476103999.png)
If that is set to "Consistent" then the field collapses due to [this line](https://github.com/processwire/processwire/blob/aed7dfc8f1fd4a9f5e3fb73da74fbd3e5d4c6eb6/wire/modules/Process/ProcessTemplate/ProcessTemplate.js#L435):
```js
$("#wrap_useRoles > label").click();
```
Not sure what the purpose of that line is - maybe it could be removed?

And to fix the missing outline without upgrading jQuery (although that might be a good thing to do regardless) [this line](https://github.com/processwire/processwire/blob/aed7dfc8f1fd4a9f5e3fb73da74fbd3e5d4c6eb6/wire/modules/Process/ProcessTemplate/ProcessTemplate.js#L434) 
```js
$("#useRolesYes").slideDown();
```
...could be changed to...
```js
$("#useRolesYes").slideDown(400, function(){ $(this).css('overflow','visible') });
```
FYI, original jQuery bug report: https://bugs.jquery.com/ticket/11635

**Comment by ryancramerdesign** [comment]
@Toutouwai Nice work tracking that down. Thanks. I have added your suggested fix.

**Comment by Toutouwai** [comment]
Thanks
