### ISSUE TITLE
Page modified timestamps are being advanced an hour during daylight savings time.

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1413]
### Short description of the issue

Timestamps being written back into the database are not aligning with daylight savings time.

When comparing the time output from the time() with the value being written to the modified field, the modified field is calculating 1 hour ahead.

### Expected behavior

The timestamp shouldn't deviate from the system timestamp. After saving a page and checking the modified timestamp against the system timestamp, there should not be a 60 minute+ difference.

### Optional: Screenshots/Links that demonstrate the issue

![Screenshot_1](https://user-images.githubusercontent.com/58667283/126076946-35445260-5b3a-473e-8bf2-bb461597cda6.jpg)

### Steps to reproduce the issue

1. Set up a processwire instance set to America/Chicago as the default time zone.
2. Set up a page template so that it outputs both the system time and the modified time. For example:
`<p>Now: <?=( time() )?> Edited: <?=( $page->modified )?></p>`
3. Change the page and save - it may affect created timestamps also.
4. Observe the time difference during a daylight savings time period.

### Setup/Environment

* ProcessWire version: 3.0.181
* (Optional) PHP version: 7.3

**Comment by ryancramerdesign** [comment]
@solonmedia ProcessWire pages uses the MySQL time for created and modified dates. Ideally your PHP timezone configuration should be consistent with your MySQL, and most commonly it is. But if you aren't able to make them consistent by configuration then you can tell MySQL what timezone to use by UTC offset. For instance, America/Chicago would be -5 hours relative to UTC. You can communicate this to MySQL from your `/site/init.php` file:
~~~~~
$database->exec("SET time_zone='-05:00'");  
~~~~~

**Comment by solonmedia** [comment]
So MySQL is making the timecode adjustment? I was under the impression that this was persistent based on UTC and then adjusted based on the local timezone - I will give that SQL a try. Thanks.

**Comment by adrianbj** [comment]
I always do:
```
SET GOLBAL time_zone = 'America/New_York';
```

so that mysql also handles daylight savings time changes the same way that PHP does. I never set timezones by hour adjustment from UTC because that changes with DST. At least that's been my experience.

**Comment by ryancramerdesign** [comment]
@solonmedia I don't know much about the MySQL side of time zones, but yes it does sound like your MySQL may likely have a timezone setting that differs from your PHP. Please let me know what you find. 

@adrianbj Good idea, though I think MySQL needs timezones loaded into it (presumably by an administrator?) before it recognizes strings like that. My local MySQL installation doesn't recognize time zone strings at least. But in cases where it does, yes that would be simpler.

**Comment by solonmedia** [comment]
I was able to run the SET query using the named timezone string and this resolved the weird offset problem on created, modified timestamps as well as simultaneous editing notifications, so I think over time that will resolve my issue.

**Comment by ryancramerdesign** [comment]
Great, thanks for letting me know. Glad to hear the named timezone string
worked. It doesn't work on my MySQL for some reason, so I have to use the
offset.

**Comment by adrianbj** [comment]
It might be a Maria vs MySQL thing. I think I've been on Maria for several years now and never had an issue with the timezone strings which seem like the only viable solution year round.

https://mariadb.com/kb/en/time-zones/
