### ISSUE TITLE
Modules Directory does not prepopulate the correct GitHub branch name

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1415]
### Short description of the issue

GitHub has changed the default branch name from `master` to `main`. All new repositories use `main` as the default branch name unless the user has manually changed to a different default name.

Info:
https://github.com/github/renaming
https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

When adding a module to the PW Modules Directory the "Download URL" field gets automatically populated with URL that doesn't take the actual branch name of the repository into account.

![2021-07-24_193056](https://user-images.githubusercontent.com/1538852/126861129-9840926d-6bbc-4e49-91a2-b4f5a080b270.png)
![2021-07-24_193230](https://user-images.githubusercontent.com/1538852/126861155-2e67905a-ba6d-44ea-9267-7cf6a2a69902.png)

It's possible to override the automatic URL but it's easy to overlook in which case the wrong download URL prevents the module from being installed via the Modules Directory.

### Expected behavior

Modules Directory uses the GitHub API to retrieve the default branch name of the repository of the module being added.

### Actual behavior

Modules Directory automatically sets a download URL that is not going to be correct for most repos going forward.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I wasn't aware of that change, I've updated the default branch name to be "main" rather than "master".

**Comment by Toutouwai** [comment]
@ryancramerdesign, GitHub users can set their default branch name to be anything they want, and a proportion of users are likely to set their default branch name back to "master" because they might be integrating with other systems that expect "master" or they just don't want to have a mixture of "main" and "master" across their repos.

So rather than hardcode any particular branch name in the Download URL could you configure the Modules Directory to make a call to the GitHub API and retrieve the actual default branch name for the repo being added? I think the Modules Directory must already be using the GitHub API to get the module info so it should just be a simple addition to that.

As an example, you can get the default branch name of the ProcessWire repo like this:

```php
$http = new WireHttp();
// Optionally set auth token to increase the rate limit 
$http->setHeader('Authorization', 'token ' . 'token_goes_here');
$repo_data = $http->getJSON("https://api.github.com/repos/processwire/processwire");
$default_branch_name = $repo_data['default_branch'];
```

**Comment by ryancramerdesign** [comment]
@Toutouwai I understand now, thanks. Turns out that particular form already has that repo data array with the default_branch already there, so I just updated it to use that value rather than hard coding 'main'.

**Comment by Toutouwai** [comment]
Great, thanks
