### ISSUE TITLE
UIKit theme Language Tabs non-default language are broken

### ISSUE THREAD

**Issue by duerrsimon** [processwire/processwire-issues#1417]
### Short description of the issue

With the UI Kit admin theme the order of language tabs when the user language is not the default is wrong. 
The field displays the correct value but the wrong tab is selected.

### Expected behavior

User lang default: 
![image](https://user-images.githubusercontent.com/16979577/127128952-41f2cec7-fc9d-4ffc-b910-4117d05f5617.png)

User lang fr
![image](https://user-images.githubusercontent.com/16979577/127129021-c691bcc2-89db-4108-b43a-a92a8418925d.png)

### Actual behavior

User lang fr:
![image](https://user-images.githubusercontent.com/16979577/127129118-5c41d47f-1989-4027-b35a-b0ff067c2389.png)

### Optional: Suggestion for a possible fix

There are no JS errors (in Firefox). I get two warning when editing a site

Empty string passed to getElementById(). 229 autofill.js:252:20
Empty string passed to getElementById(). 21 edit

### Steps to reproduce the issue
This is on processwire 3.0.179 with additional modules disabled using Tracy debugger. I have two languages default and fr. The order is default, fr. (If I reorder them in the backend the fr one works correctly but for the default the tabs are wrong. It seems that always the first tab is highlighted if using the UiKit theme). The problem occurs on any multi language field with the UiKit theme. With the old theme everything is fine. 

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.179|
|PHP|7.4.21|
|Webserver|Apache/2.4.39 (Unix)|
|MySQL Server|5.5.5-10.3.27-MariaDB|
|MySQL Client|mysqlnd 7.4.21|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|90 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1500|
|memory_limit|512M|
|post_max_size|2048M|
|upload_max_filesize|2048M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.2|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.12|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeTime|1.0.2|
|Fluency|0.2.3|
|InputfieldTime|0.2.2|
|PageQueryBoss|0.0.6|
|ProcessTracyAdminer|1.1.3|
|TracyDebugger|4.22.5|
</details>

**Comment by ryancramerdesign** [comment]
@duerrsimon Thanks for the report. This was due to changes in the Uikit library and fixed in 3.0.180, so if you grab the newest dev branch that should fix it. Though one person reported browser cache was pretty pesky here so make sure you do a Modules > Refresh after upgrading, just to make sure new CSS/JS file versions get picked up.
