### ISSUE TITLE
Forgot Password does not work if 'email' field on 'user' template uses 'required only if'

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1418]
I have a checkbox field called 'no_email'.  I added it to the 'user' template.

I modified the context settings of the 'email' field on the 'user' template so that 'Required only if' is set to: no_email=0

That works fine, but it messes up the Forgot Password feature.

If doing Forgot Password, the initial verification email comes through fine.  When clicking the link and filling out the required information (verification code + email + new password) and clicking the submit button, it will take you right back to the same form but with the fields empty, instead of giving the message that the password was reset successfully and taking you back to the login form.

The warning it throws is (I was able to see this by forcing the output in the module and exiting):
```
Array ( [0] => Warning (requiredIf): dependency field 'no_emailemail' is not present in this form. )
```

**Comment by ryancramerdesign** [comment]
@jlahijani Looks like we'll have to blank out the showIf/requiredIf conditions for those confirmation fields (like email). I've pushed an update that does this. Does this solve the issue you are seeing? Thanks.

**Comment by jlahijani** [comment]
Fixed.
