### ISSUE TITLE
no rendering of Integer and Float fields when "page-view" permission only and field value is 0

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1419]
### Short description of the issue

Hi, another glitch wrt the admin rendering, when the user only has "page-view" permission : 
For fields of type **Integer** and **Float**, when the field value is 0 (zero), then PW just skips the rendering of this field.
As soon as another value is set, PW renders the field.

### Expected behavior

When the setting _"show field in page editor if viewable but not editable"_ is enabled, PW should render the field in the admin, whatever the field value (non-zero, zero, empty).

### Setup/Environment

* ProcessWire version: 3.0.182

**Comment by ryancramerdesign** [comment]
Thanks @er314 I have pushed a fix for this issue.

**Comment by er314** [comment]
nice, thanks
