### ISSUE TITLE
InputfieldTextTags not working in repeatable context with dynamic loading

### ISSUE THREAD

**Issue by zumpixel** [processwire/processwire-issues#1421]
### Short description of the issue
If an InputfieldTextTags is used in a repeater or in files such as multiple images dynamically loaded with AJAX, the field remains empty and does not show any options. If the field is set as another input field like ASMSelect or Checkboxes, it works. 
It does not matter whether the field type is PageReference or SelectOptions.

Tested with PHP 7.3.27
ProcessWire: fresh installed 3.0.183 without any 3rd party modules

**Comment by ryancramerdesign** [comment]
Thanks @zumpixel I've pushed a fix for this issue.

**Comment by zumpixel** [comment]
Thanks for the quick attention, @ryancramerdesign ! It now works for Select Option field, but not for a Page Reference field. Or am I doing something wrong? Tested only on Repeater.

**Comment by zumpixel** [comment]
Many thanks, @ryancramerdesign! With the two relevant commits from August 20th, it works fine.
