### ISSUE TITLE
selectorValue sanitizer stripping out pipe character

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1422]
### Short description of the issue

`$sanitizer->selectorValue` strips `|`

### Expected behavior

I would have thought these should be allowed

### Actual behavior

They are removed

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/129225567-6a39a1b7-8e97-4845-a6b1-cab5a9bd63ff.png)

I see that the pipe character is listed in the blacklist, so it seems to be intentional behavior:

```
		$blacklist = array(
			'"', "\\0", "\\", "`", "|", '=', '*', '%', '~', '^', '$', '#',
			'<', '>', '[', ']', '{', '}', "\r", "\n", "\t", 
		);
```

Obviously it's possible to use `explode` and then sanitize as an array, but is this the best option?

**Comment by ryancramerdesign** [comment]
@adrianbj The purpose of selectorValue() is to remove anything that is not allowed in selector values. Pipes are a modifier, they modify the meaning of the selector from "equal" to "or".  This is exactly the sort of thing the selectorValue method is intended to remove. It's not something you'd typically want to allow as input in a text search engine. I'm not recommending it, but if you have a case where you want to include it, you could put it in the whitelist option.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - I don't want a pipe in a text search engine. I had inadvertently applied the selectorValue() sanitizer to a pipe separated array of page IDs and noticed that it removed the pipe. I assumed that given that this is a common value to put in a selector, that it would be allowed. I guess I hadn't really thought about the pipe as a modifier in this case, eg: `find('pagefield=1001|1002')` - I think of `1001|1002` as the value of the selector, but I see your point as well.
