### ISSUE TITLE
Incorrect description for "Allow unpublished pages?" setting for Page Reference fields

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1423]
### Short description of the issue

The setting for "Allow unpublished pages?":

![2021-08-13_100233](https://user-images.githubusercontent.com/1538852/129275775-71ebb444-5de0-4822-96a6-9362c685528f.png)

The highlighted part of the setting description is not correct. Whether or not unpublished pages appear in the field value in template files (I assume this is what is meant by "appear on the front-end") depends on whether or not you get the unformatted or formatted value. Being logged in as a user with edit access to the unpublished pages has no effect.

I tested by viewing as superuser:

```
<p>Formatted: <?= $page->select_page->title ?></p>
<p>Unformatted: <?= $page->getUnformatted('select_page')->title ?></p>
```

![2021-08-13_100814](https://user-images.githubusercontent.com/1538852/129276235-078b96da-b478-477c-8935-2ca85daf725b.png)

Refer this resolved issue: https://github.com/processwire/processwire-issues/issues/1159

### Setup/Environment

* ProcessWire version: 3.0.181

**Comment by ryancramerdesign** [comment]
@Toutouwai Looks like you are right, that description is not correct. The question is then, should the behavior be updated to be consistent with the description, or should the description be updated for the current behavior... I'm not sure. I usually don't think links to unpublished pages should be showing in front-end output whether editable or not, but since it's an option that's not enabled by default, maybe someone using it would want it to be included there. I've never had a need for this option myself, so I'm not really sure. What do you think?

**Comment by Toutouwai** [comment]
I'm not sure either and it isn't something that I've needed myself. But your comment in the [linked](https://github.com/processwire/processwire-issues/issues/1159#issuecomment-620191761) issue was correct:

> Though I'm suspicious I'm going to get another issue report in a week or two saying that unpublished pages stopped showing up where they used to, so we'll see.

Because after you made the change at least a couple of people have been affected when they've updated PW:
https://processwire.com/talk/topic/23539-page-reference-field-unpublished-pages-showing-up-in-frontend/?do=findComment&comment=205262
https://processwire.com/talk/topic/26001-solved-page-page_reference_field-is-false-when-referenced-page-is-unpublished/

I think having the pages appear only in the unformatted value is good because it means the developer needs to consciously do something different than the default before the unpublished pages will appear in the value, so it's less likely that they'll sneak through accidentally on the front-end. So the setting description should be updated to explain that.

The thing in the current setting description about needing edit access could be added as an additional restriction. But the problem is that this wouldn't just be limited to the front-end (template files) but would presumably apply across the API, and so might make it difficult in cases where the developer wants to override and have the unpublished pages in the field value regardless of the user's permissions. So maybe that part of the setting description should just be removed and the API behaviour not changed.

**Comment by ryancramerdesign** [comment]
@Toutouwai How about this below, which describes the current behavior more accurately:

> When checked, unpublished pages will be selectable for input and allowed in the *unformatted* field value. They will still be excluded from the *formatted* field value either way.

**Comment by Toutouwai** [comment]
That sounds good to me.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed that update
