### ISSUE TITLE
404 page calling $page->render('field_name') can result in an exception

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1424]
### Short description of the issue

This issue is a bit of an obscure one: in some situations calling $page->render('field_name') from template used for the 404 page can throw an exception, whereas $page->renderField('field_name') works as expected.

One situation where this occurs consistently is when an unpublished (or otherwise protected) page contains a repeater item with an image, and pagefileSecure is enabled. Now if someone attempts to access that image by URL and they don't have permission to view it, they should see 404 message, but instead they see an error (or partial page content and error.)

This is loosely related to another case I reported earlier in relation to ProMailer. The root cause seems to be that in this case the (repeater) page uses admin template, which prevents the hook in PageRender::ready() from firing, and thus render isn't synonymous to renderField like it usually is in template files.

Removing that template!=admin condition from PageRender makes this work, but I have no idea what else it might change or break.

### Expected behavior

I would expect the 404 page to render. I've been seeing these errors more often after moving new sites to a Repeater Matrix based page builder; took a while to make the connection, but it makes sense now; in that context this is somewhat likely to occur eventually.

### Actual behavior

```
Aw shucks… Error: Exception: Invalid output file location or specified file does not exist. (in wire/modules/PageRender.module line 518)
```

### Optional: Suggestion for a possible fix

The straightforward fix would seem to be removing the admin template check from the PageRender module, but again I have no idea what else this might affect so not sure if that's still needed. If this can't be fixed, then perhaps $page->render('field') should be strongly discouraged, or perhaps even deprecated? 

### Steps to reproduce the issue

- Enable pagefileSecure
- Add call to $page->render('body') — or any field, really — to the template used on the 404 page (basic-page)
- Add a Repeater field with an image field to the template
- Add an image to the image field in the Repeater 
- Unpublish the page, or disable access to it via template access settings
- Try to access the image with direct URL

This should now result in an exception. If not, make sure that directories for both the "parent" page (if it has file fields) and the repeater item within it are `-` -prefixed. This is likely not required, but while attempting to reproduce this, I ran into some situations where this did not happen (possibly related to access being prevented when the image/directory already existed, or something along those lines).

### Setup/Environment

* ProcessWire version: 3.0.165

**Comment by ryancramerdesign** [comment]
@teppokoivula I don't currently see any harm with removing the template=admin exclusion, as I think that was just there because I didn't expect the hook would ever be needed in the admin, so more just a micro optimization, if I recall. I'll remove it and test here for awhile first though. 

My best guess why render('field_name') is being called on an admin page is because while repeaters don't use template=admin, they are protected by the admin page structure. So in lieu of the page owning the repeater being available, direct access to an image in a repeater gets access delegated to the admin. Since the user lacks access, the $page becomes the login page, which uses the admin template.

**Comment by teppokoivula** [comment]
Thanks. And yes, that makes sense; was also wondering why the template used here would be admin, but to be honest repeaters are a bit of a strange territory for me and was too lazy to really dive in 🙂

**Comment by ryancramerdesign** [comment]
I'll close this since this update is now on the dev branch. Thanks.
