### ISSUE TITLE
Empty required image/file custom fields in repeater do not show error message in repeater inputfield 

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1426]
### Short description of the issue

If a repeater field contains an item with a required inputfield that has been saved in an empty state, the repeater inputfield shows an error message and the relevant repeater item is shown in an open state when Page Edit reloads.

![2021-08-19_165725](https://user-images.githubusercontent.com/1538852/130010178-e14a8689-f3cd-4213-bed6-2f21c2d31816.png)

But if the required inputfield is an images or files [custom field](https://processwire.com/blog/posts/pw-3.0.142/#how-to-setup-and-use-custom-fields-in-file-image-fields) then the repeater inputfield doesn't show an error message and the relevant item is not shown in an open state.

There is an error message in the PW notifications area, but it isn't easy for the user to trace this to the specific repeater item.

![2021-08-19_170637](https://user-images.githubusercontent.com/1538852/130011079-1686082d-62ef-4ad4-9401-1f6aa3e49a64.png)

### Setup/Environment

* ProcessWire version: 3.0.183

**Comment by Toutouwai** [comment]
Possible fix?
Replace [this line](https://github.com/processwire/processwire/blob/28621140211296e81714a6c0059cb8dec566b56f/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L1067) with:
```php
$error_message = "$this->label ($pagefile->name): $error";
$this->error($error_message);
$f->error($error_message);
```

For now I'm using a hook:
```php
$wire->addHookAfter('InputfieldFile::processItemInputfields', function (HookEvent $event) {
    /** @var InputfieldFile */
    $inputfield = $event->object;
    /** @var InputfieldWrapper $custom_fields */
    $custom_fields = $event->arguments(1);
    foreach($custom_fields->getAll() as $f) {
        foreach($f->getErrors() as $error) {
            $inputfield->error($error);
        }
    }
});
```

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai your suggested fix makes sense to me, I have added it. I don't have a test scenario setup to confirm it at the moment, but if I understand the issue correctly I'm pretty sure that'll do it.

**Comment by Toutouwai** [comment]
Thanks
