### ISSUE TITLE
Language alternate field with value 0 not respected

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [processwire/processwire-issues#1431]
### Short description of the issue

I have the two integer fields called _price_ and _price_de_. When I request the value of price with language _de_, it only provides the correct value if _price_de_ is any other than empty or greater than 0.

### Expected behavior

While I would expect an empty field to fall back to the value of the default language, having a value 0 should actually return 0.

### Actual behavior

When _price_de_ has a value of 0, it returns the value of _price_.

### Optional: Suggestion for a possible fix

The problem lies in LanguageSupportFields.module on [line 159](https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/LanguageSupportFields.module#L159), where `empty()` is used to determine if the field has a value. It seems to me that `!(isset($value) && $value !== '')` should be used there.

### Setup/Environment

ProcessWire 3.0.165

**Comment by ryancramerdesign** [comment]
@dsdsdsdsdsds Thanks, I've pushed a fix for this. Note that in your integer field settings, on the Details tab, for the "Are 0 and blank equivalent?" field, you'll have to select "No - blank and 0 have different meanings".

**Comment by dsdsdsdsdsds** [comment]
Works, thanks!
