### ISSUE TITLE
The page does not have a custom class in Pages::saved hook

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1432]
### Short description of the issue

When dealing with a newly created page in Pages::saved hook, it's class is Page, not the custom class that it has to have according to it's template (like `TemplateNamePage`).

### Expected behavior

The page has to have the custom class and all it's methods available.

### Setup/Environment

* ProcessWire version: 3.0.181

**Comment by ryancramerdesign** [comment]
@ivangretsky I can't duplicate this one, but I suppose it depends what is creating the page. I tested with ProcessWire creating the page (ProcessPageAdd) and my saved hook showed the correct class for the Page (i.e. BlogPostPage). Here's the hook I used to test:
~~~~~
$pages->addHookBefore('Pages::saved', function($event) {
  $page = $event->arguments(0); 
  bd("Saved page id=$page->id, template=$page->template, class=" . $page->className());
}); 
~~~~~
TracyDebugger result when creating a new page:
~~~~~
Saved page id=8558, template=blog-post, class=BlogPostPage
~~~~~
If it's something else in the core creating the Page then let me know how to reproduce, as it should be a simple fix. But if it's a page that another module is creating, then the module would likely have to know about the custom page classes feature if it is to create a page using a custom class.

**Comment by matjazpotocnik** [comment]
@ivangretsky, can you provide more info?

**Comment by ivangretsky** [comment]
Thanks @matjazpotocnik for bringing this up. I do remember that I was quite sure the bug was real. I will try to reproduce it again and report here ASAP.

**Comment by matjazpotocnik** [comment]
@ivangretsky, could you reproduce it?

**Comment by matjazpotocnik** [comment]
@ivangretsky Ivan, any update on this?

**Comment by matjazpotocnik** [comment]
@ivangretsky Ivan, closing this issue, let me know if it needs re-opening.
