### ISSUE TITLE
Security: HTMLPurifier.standalone uses eval

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1433]
Use of eval() is discouraged and should be removed
It's usage may have negative readability, performance and security implications, especially if you accept strings from untrusted or unknown sources.

PHP has features that gives possibility to avoid using eval() in most cases.

![image](https://user-images.githubusercontent.com/551551/131459425-8fa10f78-810f-476c-9413-df86bc7314b7.png)

**Comment by ryancramerdesign** [comment]
@jmartsch Use of eval is not an error, but I agree it should be discouraged. And if I had written the library I likely would not have used it unless there was no other option. For cases where it can only operate upon something provided by the developer then it's okay, even if we still wouldn't prefer it, as it is also slow. I had looked into it before and my understanding is that the HTMLPurifier library maintains this boundary and only uses eval on developer provided strings through configuration of the library, so it's not a security issue. However, if you still have concerns feel free to open an issue report at https://github.com/ezyang/htmlpurifier/issues
