### ISSUE TITLE
WebP doesnt support URL (uppercase buster)

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#1435]
$image->webp->URL needs to be supported to break cache

**Comment by ryancramerdesign** [comment]
@cb2004 This is something that PW already supports. Just confirmed it here and both `$image->webp->URL` and `$image->webp->HTTPURL `appear to be working from here at least. Is it not working for you? What kind of error are you seeing?

**Comment by cb2004** [comment]
It doesn't produce a WebP version of the image, it uses the original format like jpg

**Comment by ryancramerdesign** [comment]
@cb2004 It's working here at least and is creating a webp version from the URL property. Is it possible that maybe your webp files are larger (in filesize/bytes) than the source image it is created from? If so, it'll fallback to the source image (jpg). Though this is the case whether using url or URL.

**Comment by cb2004** [comment]
It creates a WebP for me lowercase (url) no problem. With uppercase (URL) it uses jpg.

**Comment by ryancramerdesign** [comment]
Double check the file sizes just in case. But assuming the webp is smaller, you should get the webp, which is what I get here. The URL property does call the url() method directly [here](https://github.com/processwire/processwire/blob/master/wire/core/PagefileExtra.php#L276), so there shouldn't be any difference. But perhaps there's something unique to your case that is not yet clear. Maybe something to do with the filename that is preventing it from matching in the string replacement. Let me know if you spot anything. It might also be worth us looking at your entire API call as it relates to any resizes or anything else that might be part of it.

**Comment by cb2004** [comment]
WebP filesize is around 18kb and the JPG is around 70kb, my code looks like (not complete, just showing relevant):

```
<?php

foreach($slides as $s):
	$image = $s->image_01->size(2160, 720);

?>
<picture>
	<source srcset="<?= $image->webp->URL ?>" type="image/webp">
	<img src="<?= $image->URL ?>" loading="lazy" width="<?= $image->width ?>" height="<?= $image->height ?>" alt="<?= $image->description ?>">
</picture>
```

**Comment by cb2004** [comment]
@ryancramerdesign any other thoughts on this one, I am getting numerous clients who don't change the names of images getting a cached version?

**Comment by ryancramerdesign** [comment]
@cb2004 I can't duplicate it here at least. Here's the code I'm using:
~~~~~
<picture>
  <source srcset="<?=page()->image->webp()->URL?>" type="image/webp">
  <img src='<?=page()->image->url?>' alt='<?=page()->title?>' />
</picture>
~~~~~
and here's the output:
~~~~~
<picture>
  <source srcset="/pwsite/site/assets/files/2789/signs.webp?nc=1631110912" type="image/webp">
  <img src="/pwsite/site/assets/files/2789/signs.jpg" alt="Signs">
</picture>
~~~~~
or with ProCache installed (which uses a shorter buster string): 
~~~~~
<picture>
  <source srcset="/pwsite/site/assets/files/2789/signs.webp?1r17m" type="image/webp">
  <img src="/pwsite/site/assets/files/2789/signs.jpg" alt="Signs">
</picture>
~~~~~

> WebP filesize is around 18kb and the JPG is around 70kb, my code looks like (not complete, just showing relevant):

Are you sure that's for your 2160x720 resized version? Where you'll usually see the most difference between webp vs. original is on the source file, not on resized files. Once it's gone through a resize, it may already be as small as it's going to get, and as a jpeg. PW is pretty good at making small jpegs when it passes through size(), so very often resized jpegs will end up smaller than the resized webp version, in which case PW will use the smaller of the two. Meaning, there's a very good chance it'll use the jpeg, depending on whether the photo content lends itself well to webp compression or not. If you want to disable that behavior and force it to always us the webp version, add this to your /site/config.php file:
~~~~~
$config->webpOptions('useSrcUrlOnSize', false); 
~~~~~

**Comment by cb2004** [comment]
@ryancramerdesign and there we go, I looked into buster in the ProCache settings and with type C it doesn't work. This is the type that seems to score higher in Lighthouse, GTMetrix etc if I can remember exactly why I was using this method, so it would be great to get it fixed with this method

**Comment by ryancramerdesign** [comment]
@cb2004 Great, it looks like that's it! The PagefileExtra will need its own noCacheURL() method to support that, so I have gone ahead and added it. Can you let me know if it works now?

**Comment by cb2004** [comment]
@ryancramerdesign that got it 👍
