### ISSUE TITLE
ProcessPageLister does not take into account the user language

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1437]
### Short description of the issue

ProcessPageLister does not take into account the user language.

### Suggestion for a possible fix
As far as I can see, `ProcessPageLister::identifyLanguage()` returns the default language if the language could not be identified by the field name. User language should be returned in this case, not default language.

### Setup/Environment

* ProcessWire version: 3.0.180

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed your suggested fix for this. Note that this affects only Lister (not ListerPro, if you are using it, it works differently). ListerPro supports column selection per language, so the default "title" field value (for example) is always default language, unless/until a different language is selected.

**Comment by kixe** [comment]
@ryancramerdesign Thanks for the fix. I use ListerPro v1.1.1 (License from late 2018) Maybe the feature was added later?
> ListerPro supports column selection per language
