### ISSUE TITLE
Pagination broken after upgrading from 3.184 to current dev (sept 10 commits)

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#1438]
### Short description of the issue

My function paginating results – moving from one sibling to the next – returns unexpected results after upgrading to latest dev version. It looks like it's caused by the September 10 commits because when I return to 3.184 stable, everything works as expected. 

### Expected behavior

Here's my function, abbreviated here. Nothing fancy:
```

function renderBottomPagination() {

	$out = '';
	if (is_null($page)) $page = wire('page');

	$current_number = $page->siblings->getItemKey($page) + 1;
	$prev_number = $current_number - 1;
	$next_number = $current_number + 1;
	$total = $page->siblings->count;

	$out .= "<nav aria-label='Pagination'>";
	$out .= "<div class='container'>";
	$out .= "<ul class='pagination'>";
	if ($page->prev->id) {
		$out .= "<li class='pagination--prev'><a class='btn' aria-label='Previous page' href='{$page->prev->url}'> {$page->prev->title} ($prev_number/$total)</a></li>";
	}
	if ($page->next->id) {
		$out .= "<li class='pagination--next'><a class='btn' aria-label='Next page' href='{$page->next->url}'>  {$page->next->title} ($next_number/$total)</a></li>";
	}
	$out .= "</ul>";
	endif;

	$out .= "</div>";
	$out .= "</nav>";
	if ($page->siblings->count > 1) echo $out;
}

```
### Actual behavior

The `$page->next->id` always returns something, even when I've reached the end of the siblings list and it should return nothing. What it returns is seemingly random, an item in the first half of the list. 

Sorry if it's not very clear. I don't really know how to explain it better. Let me know if you need more details.

**Comment by ryancramerdesign** [comment]
Thanks @jacmaes I've pushed a fix for this issue. Can you confirm it also fixes it there? Thanks.

**Comment by jacmaes** [comment]
Wow, that was fast! Thanks, it seems fixed now.
