### ISSUE TITLE
Page Autocomplete/ProcessPageSearch executeFor() ignores fields to query with new 3-digit operators

### ISSUE THREAD

**Issue by ro-webdesign** [processwire/processwire-issues#1439]
### Short description of the issue

If you use any of the newer 3-digit selector operators in an Autocomplete field (e.g. ~*=, ~%=), the entire search field section ("fields to query for autocomplete") of the query is stripped out.

### Expected behavior

Search fields and chosen operator should combine to filter the returned results.

### Actual behavior

The code in ProcessPageSearch::___executeFor() appears to assume the search operator will only be 2 characters, leaving the first character in a 3-digit operator appended to the search field name(s).  This part of the query is then removed with the sanitizer and isSelectableFieldName(). 

### Optional: Screenshots/Links that demonstrate the issue

These are examples of the ajax search urls copied and pasted into the admin:
1. With a 2-digit search operator (%=):

![2-characterSearch](https://user-images.githubusercontent.com/7632630/134513656-953ca9d9-e371-41f9-8a2f-efa13bf185eb.JPG)

2.  With a 3-digit search operator (~%=). The filter part is stripped out and only the template id remains:

![3-characterSearch](https://user-images.githubusercontent.com/7632630/134513736-48af985c-37b0-457c-9e06-737780234a49.JPG)

### Optional: Suggestion for a possible fix

Not sure.  The problem seems to lie around lines 340-343 of ProcessPageSearch.module, where the operator is obtained by a `substr($name, -1)` and the name is obtained with `substr($name, 0, -1)`

### Steps to reproduce the issue

1. Create a page reference Autocomplete field that has multiple selectable pages, and add this to a template.
2. Set the Autocomplete search operator to *= or %= and use in a page to perform a lookup.
3. Change the search operator to ~*= or ~%= and perform another lookup.  Notice that there are many more pages returned and these are not filtered for your search term.

### Setup/Environment

* ProcessWire version: 3.0.184

**Comment by ryancramerdesign** [comment]
Thanks @ro-webdesign you were right about the location of the error (good find), I've pushed a fix for this issue.

**Comment by ro-webdesign** [comment]
@ryancramerdesign Thanks Ryan, that seems to have sorted it. 👍
