### ISSUE TITLE
Newline character in string breaks translation

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [processwire/processwire-issues#1442]
### Short description of the issue
If I follow the [documentation](https://processwire.com/docs/multi-language-support/code-i18n/#translation-function-calls-must-be-on-one-line-and-in-one-pair-of-quotes) to translate strings with newline characters in them (with double quotes and \n inside the string), it is not working for me. PW then always returns the value of the default language.

### Expected behavior
It should return the translated value, even with newline characters inside the string. Either this, or the [documentation](https://processwire.com/docs/multi-language-support/code-i18n/#translation-function-calls-must-be-on-one-line-and-in-one-pair-of-quotes) has to be updated to not say that it is possible.

### Steps to reproduce the issue

1. Add `echo __("It's time for you \nto get to the party.");` to a template
2. Translate string to another language
3. View page in that language

### Setup/Environment

ProcessWire 3.0.184
PHP 7.3.3.

**Comment by ivangretsky** [comment]
Had the same problem.

**Comment by ryancramerdesign** [comment]
Thanks @dsdsdsdsdsds @ivangretsky I've pushed a fix for this. 

It doesn't look to me like we ever actually had support for this, so it must have been one of those things where the docs came before the code. As a result, if you already have translated strings with newlines in them, you may need to re-translate them before they will start working. 

Note that it doesn't matter whether you use "double quotes" or 'single quotes' to mark your translation, so use whichever you prefer (I usually stick with single quotes on these strings to be clear that PHP variables can't be referenced in them).

**Comment by dsdsdsdsdsds** [comment]
Thanks a lot, working!
