### ISSUE TITLE
Process::executeNavJSON() does not take in account if request is ajax or not.

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1443]
### Short description of the issue

Process::executeNavJSON() does not take in account if request is ajax or not. A page with JSON string is rendered  sometimes after re login.

### Expected behavior

Should throw 404 if request is not ajax.

### Screenshots/Links that demonstrate the issue

URL: .../setup/template/navJSON/

![Bildschirmfoto 2021-10-02 um 12 56 16](https://user-images.githubusercontent.com/4683120/135713449-6cbbe429-eacf-41e1-8e0c-233175a26239.png)

### Setup/Environment

* ProcessWire version: 3.0.185

maybe related: https://github.com/processwire/processwire-issues/issues/818

**Comment by ryancramerdesign** [comment]
@kixe I like to have that navJSON output accessible without ajax for debugging purposes, but it sounds to me like you must have arrived there without intending to.  I'm not exactly sure how to duplicate that, but I've added a couple of checks for it in ProcessLogin to hopefully prevent it from redirecting to the navJSON output of Process modules. Please let me know how to duplicate if you still run into the issue. Thanks.

**Comment by matjazpotocnik** [comment]
@kixe any update on this? Could you close the issue if it's fixed?

**Comment by kixe** [comment]
@ryancramerdesign @matjazpotocnik
It still happens from time to time if a session has been expired until the window is still open and I try to re-login.

**Comment by kixe** [comment]
> @kixe I like to have that navJSON output accessible without ajax for debugging purposes

... if so:

> Should throw 404 if request is not ajax.

AND `$config->debug = true; `

Currently this also happens when `$config->debug = false; `

**Comment by ryancramerdesign** [comment]
@kixe I've still not run into this particular issue before except when intending to view the navJSON output for debugging purposes, but it sounds like you still are seeing this regularly? I've pushed another update so that it redirects to the non-JSON output when a non-ajax request is made to it and debug mode is off.

**Comment by matjazpotocnik** [comment]
@kixe I'm closing this issue, let me know if it needs re-opening.
