### ISSUE TITLE
Limit selector return empty page array, if limit value bigger than total count of pages

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#1445]
- ProcessWire 3.0.185 dev

Getting pages without limit, we have totally `13` pages

Result: **work**

![no-limit](https://user-images.githubusercontent.com/455983/135760290-e0d8b083-d7ee-493c-beb8-474a6b6abeae.png)

Getting pages with limit, limit value `4` lower than total pages `13` count

Result: **work**

![limit-4-less-than-count](https://user-images.githubusercontent.com/455983/135760287-b4b8d451-a9ad-4a26-b1c7-70e8dd35f3d5.png)

Getting pages with limit, limit value `15` bigger than total pages `13` count

Result: **Empty PageArray**

![limit-15-more-than-count](https://user-images.githubusercontent.com/455983/135760289-1c5eee21-844e-4b8f-9d2c-105c5c6d61fb.png)

**Comment by incognitoms** [comment]
I tried that with one of my test instances of PW 3.0.185 and was not able to reproduce the issue. What happens if you change the selector to:
`template=destination-list,limit=4,start=0`

(Because on the last screenshot it returns "start: 15". But start should be 0 by default.)

Note that this "start=0" was not necessary for my tests. It worked correctly right out of the box with a vanilla setup.

**Comment by trk** [comment]
Its look like `pagination` on page `effect` all `$pages->find*` method results.

Normally i have list of yachts on this page with pagination, if user on page2 or page* this action also effect other `$pages->find*` methods.

Lets make an example

```php
// We have 50 posts
$posts = $pages->findMany('template=post, limit=15');

// we have 10 categories
$categories = $pages->findMany('template=category, limit=10');
```

@incognitoms can you make a test like this on your side ?

on page2 we can't see categories, in this scenario.

**Comment by ryancramerdesign** [comment]
@trk When viewing a page on a pagination greater than 1, it automatically affects the "start" value of all PageArray-returning database finding operations that have a `limit=n` in the selector, ensuring that they paginate properly. The `limit=n` in the selector is what tells it to paginate. If there are cases where you don't want your result set to paginate consistently with the current page number, and you are using a limit in the selector, then you want to also add a `start=0` in your selector. [More details here](https://processwire.com/docs/front-end/markup-pager-nav/#are-there-any-side-effects). Please let me know if this is what you were looking for or if I've misunderstood the report? Thanks.
