### ISSUE TITLE
Adding a field to a template via field's action does not update the 'modified' date of said template

### ISSUE THREAD

**Issue by eelke** [processwire/processwire-issues#1448]
### Short description of the issue

Adding a field to a template (using the 'Add or remove field from templates' action) does not update the  'modified' timestamp of the template, even though the template was in fact modified. 

### Expected behavior

Any change to a template should update the 'modified' timestamp. 

### Actual behavior

It does not update. 

### Steps to reproduce the issue

1. Make note of the Modified timestamp of a template
2. Add a new field via this fields own 'Add or remove field from templates' action to the template 
3. Re-check modified timestamp. It has not changed. 

### Setup/Environment

* ProcessWire version: 3.0.184
* (Optional) PHP version: 7.4.2
* (Optional) MySQL version: 5.7.26
* (Optional) Any 3rd party modules that are installed and could be related to the issue: -

**Comment by ryancramerdesign** [comment]
@eelke Fields are added to Fieldgroups rather than Templates. So technically the template would not have changed if a field was added. Fieldgroups are largely hidden from the admin/UI side, but on the API side they are their own type with their own API variable ($fieldgroups). Do you have a use case where it would be good for the template modification date to be updated if a change is made to the fieldgroup used by the template? Let me know, as we may be able to add that option.

**Comment by eelke** [comment]
Hi @ryancramerdesign, thanks for getting back to me.

My use case is the following: 

I use the field & template import/export features all the time to copy changes from a development server to a live server. The templates export page shows the date a template has been modified. There are many usability improvements that could be made to this export page, but the basic way of visually finding the recently modified templates works most of the time — except in the situation I describe above. 

Whenever fields were added to templates using the 'Add or remove field from templates' action, the export page will not reflect those changes. Especially on larger sites, with dozens of templates & fields and changes this is rather impractical, and you have to manually keep track of any updated templates.

This [github request](https://github.com/processwire/processwire-requests/issues/343) from 2019 is related to the same use case: It is currently not possible to identify recently updated fields anywhere.

**Comment by ryancramerdesign** [comment]
Thanks @eelke that use case makes sense to me. I have updated it so that it updates the modified date of templates when fields are added in that way.

**Comment by eelke** [comment]
That is great news, thanks @ryancramerdesign!
