### ISSUE TITLE
Can't save changes in Image input when "Overwrite existing files" is disabled.

### ISSUE THREAD

**Issue by PawelGIX** [processwire/processwire-issues#1450]
### Short description of the issue

I have a field called "promobox_img"
Single picture.
It always worked fine, but I haven't been able to save changes to it for a while.
I mean, I can't replace the image.
I can delete it but I can't upload a new one.
Can someone check if he also has it on your installation?

I already know a little more.
The error disappears if I enable this option.

![image](https://user-images.githubusercontent.com/391153/136617805-e6694f31-25c0-4fae-b153-0cc1b6b1a2a4.png)

If I turn it back on. This is the problem again.
The files are uploaded. But despite clicking save, they are not set as active.
What's worse, files that have not been saved with the Save button are not deleted from the server. So each upload attempt creates a new file without deleting the old ones: /

Can someone tell where the "magic" is happening. I'll try to debug it.
I mean the part of the code that processes AJAX uploaded images. That is:
1. After clicking save, the loaded files are selected as active and old files are deleted.
2. Normally when you upload files using AJAX and (not save with the save button) the loaded files should be deleted. It doesn't happen with me either.
Where can I find the part of the code that does this?

* ProcessWire version: 
* (Optional) PHP version: 7.4
* (Optional) MySQL version:  5
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by teppokoivula** [comment]
Hey @PawelGIX. Which version of ProcessWire are you running?

If you want to dig into this, you could start from [Pageimage::___install()](https://github.com/processwire/processwire/blob/master/wire/core/Pageimage.php#L1675), which in turn calls Pagefile::___install(), and so on. You should also make sure that there's no module or hook that might be interfering with the normal behaviour of pagefiles.

**Comment by PawelGIX** [comment]
This was on ProcessWire 3.0.148.
I did update to 3.0.184 but the problem persists

This is how it looks after uploading the file with AJAX. 
![image](https://user-images.githubusercontent.com/391153/136672120-6a7f5006-0090-410e-8630-aef80816181a.png)
I marked the new file with the red arrow. It stays that way. Clicking the save button changes nothing.
Refreshing the edit page changes nothing. The change takes place only after loading a new file, but only the inactive one is always changed. The line with the age.jpg file remains unchanged.
```
[
    {
        "error": false,
        "message": "Added file: shaker_door_promo_box_image-8.jpg",
        "file": "\/site\/assets\/files\/1017\/shaker_door_promo_box_image-8.jpg",
        "size": 41081,
        "markup": "<li id='file_249a2d0d3d869e2b8ae6af309412c281' class='ImageOuter gridImage ui-widget'><div class='gridImage__tooltip'><table><tr><th>Dimensions<\/th><td>500x375<\/td><\/tr><tr><th>Filesize<\/th><td>40&nbsp;kB<\/td><\/tr><tr><th>Variations<\/th><td>0<\/td><\/tr><\/table><\/div>\n\t\t\t<div class='gridImage__overflow'>\n\t\t\t\t<img src=\"\/site\/assets\/files\/1017\/shaker_door_promo_box_image-8.0x260.jpg?nc=1633809091\" alt=\"\" data-w=\"500\" data-h=\"375\" data-original=\"\/site\/assets\/files\/1017\/shaker_door_promo_box_image-8.jpg?nc=10\" data-focus=\"50 50 0\"  \/>\n\t\t\t<\/div>\n\t\t\t\n\t\t\t\t<div class='gridImage__hover'>\n\t\t\t\t\t<div class='gridImage__inner'>\n\t\t\t\t\t\t<label for='' class='gridImage__trash'>\n\t\t\t\t\t\t\t<input class='gridImage__deletebox' type='checkbox' name='delete_promobox_img_249a2d0d3d869e2b8ae6af309412c281' value='1' title='Delete' \/>\n\t\t\t\t\t\t\t<span class='fa fa-trash-o'><\/span>\n\t\t\t\t\t\t<\/label>\n\t\t\t\t\t\t<a class='gridImage__edit'>\n\t\t\t\t\t\t\t<span>Edit<\/span>\n\t\t\t\t\t\t<\/a>\n\t\t\t\t\t<\/div>\n\t\t\t\t<\/div>\n\t\t\t\n\t\t\t\t<div class='ImageData'>\n\t\t\t\t\t<h2 class='InputfieldImageEdit__name'><span contenteditable='true'>shaker_door_promo_box_image-8<\/span>.jpg<\/h2>\n\t\t\t\t\t<span class='InputfieldImageEdit__info'>40&nbsp;kB, 500&times;375 <\/span>\n\t\t\t\t\t<div class='InputfieldImageEdit__errors'><\/div>\n\t\t\t\t\t<div class='InputfieldImageEdit__buttons'><small><button type='button' data-href='\/admin\/page\/image\/edit\/?id=1017&file=1017,shaker_door_promo_box_image-8.jpg&rte=0&field=promobox_img' class='InputfieldImageButtonCrop ui-button ui-corner-all ui-state-default pw-modal-large pw-modal' data-buttons='#non_rte_dialog_buttons button' data-autoclose='1' data-close='#non_rte_cancel'><span class='ui-button-text'><i class='fa fa-crop'><\/i> Crop<\/span><\/button><button type='button' data-href='\/admin\/page\/image\/variations\/?id=1017&file=shaker_door_promo_box_image-8.jpg&modal=1&varcnt=varcnt_promobox_img_249a2d0d3d869e2b8ae6af309412c281' class='ui-button ui-corner-all ui-state-default pw-modal-large pw-modal' data-buttons='button'><span class='ui-button-text'><i class='fa fa-files-o'><\/i> Variations <span class='ui-priority-secondary'>(1)<\/span><\/span><\/button><\/small> <select class='InputfieldFileActionSelect' name='act_promobox_img_249a2d0d3d869e2b8ae6af309412c281'><option value=''>Actions<\/option><option value='fv'>Flip vert<\/option><option value='fh'>Flip horiz<\/option><option value='fb'>Flip both<\/option><option value='r90'>Rotate 90&deg;<\/option><option value='r180'>Rotate 180&deg;<\/option><option value='r270'>Rotate 270&deg;<\/option><option value='r-90'>Rotate -90&deg;<\/option><option value='r-180'>Rotate -180&deg;<\/option><option value='r-270'>Rotate -270&deg;<\/option><option value='bw'>B&amp;W<\/option><option value='sep'>Sepia<\/option><\/select> <span class='InputfieldFileActionNote detail'>Action applied at save.<\/span><\/div>\n\t\t\t\t\t<div class='InputfieldImageEdit__core'><div class='InputfieldFileDescription'><label for='description_promobox_img_249a2d0d3d869e2b8ae6af309412c281' class='detail pw-hidden'>Description<\/label><input type='text' name='description_promobox_img_249a2d0d3d869e2b8ae6af309412c281' id='description_promobox_img_249a2d0d3d869e2b8ae6af309412c281' placeholder='Description&hellip;' value='' \/><\/div><\/div>\n\t\t\t\t\t<div class='InputfieldImageEdit__additional'><\/div>\n\t\t\t\t\t<input class='InputfieldFileSort' type='text' name='sort_promobox_img_249a2d0d3d869e2b8ae6af309412c281' value='1' \/>\n\t\t\t\t\t<input class='InputfieldFileReplace' type='hidden' name='replace_promobox_img_249a2d0d3d869e2b8ae6af309412c281' \/>\n\t\t\t\t\t<input class='InputfieldFileRename' type='hidden' name='rename_promobox_img_249a2d0d3d869e2b8ae6af309412c281' \/>\n\t\t\t\t\t<input class='InputfieldImageFocus' type='hidden' name='focus_promobox_img_249a2d0d3d869e2b8ae6af309412c281' value='50 50 0' \/>\n\t\t\t\t<\/div>\n\t\t\t<\/li>",
        "replace": true,
        "overwrite": 0
    }
]
```

I think the Ajax answer is okay.
When I click save, this file is no longer being processed.
Only "age.jpg" appears in places where I set var_dump: __processInput or __processInputFile


My input data after submit
![image](https://user-images.githubusercontent.com/391153/136675180-f12119fd-db7c-41e4-87cd-a6a7b44df835.png)

**Comment by matjazpotocnik** [comment]
@PawelGIX, I can't replicate this. If I understand your field setup, it's a single file, max files 1? How about creating a new image field configured as the existing one and checking if that works?

**Comment by matjazpotocnik** [comment]
@PawelGIX Closing, let me know if it needs re-opening.
