### ISSUE TITLE
Fieldgroup specific field setting got restored to default after save in template edit page

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#1453]
### Short description of the issue

Fieldgroup specific field setting got erased after save in template edit page. The template contains a lot of fields (around 40 fields). When I add/remove fields in the template edit page and hit save, the bottom most field setting , such as label and field width etc, restored to default unwillingly.

### Expected behavior

The fieldgroup specific setting remains unchanged after hitting save in template edit page.

### Actual behavior

The fieldgroup specific setting got erased starting from the bottom fields after hitting save in template edit page. The amount of erased setting field is random.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/26466450/137189846-fdc6b694-a731-4087-bb77-8788f9bc5d2f.png)
t_general21 and t_general22 are the newly added fields. All fields under repeater_ck become blank. The tab label is the field default setting, so it can survive.

### Steps to reproduce the issue

1. Make a template with around 40 fields
2. Add some more fields into the template
3. Save the change

### Setup/Environment

* ProcessWire version: 3.0.165

**Comment by adrianbj** [comment]
@karltdev - that version is over a year old, so it would probably be helpful to know if you're still seeing this in the latest master version.

**Comment by karltdev** [comment]
Thanks for reminding. I will update the core version and test again.

**Comment by karltdev** [comment]
![image](https://user-images.githubusercontent.com/26466450/137198032-f6a3b31a-ddb3-46c2-be4f-9e50bc3319f1.png)


I found an error when testing. It happens when I move the position of the field inside template edit page. And then click the field above the moved field. The above error will show up if you click within 2 seconds. If you wait like 3second to click the above field after move the field, the field setting may show blank. If you wait for more than 5 second, the field show the original setting correctly. I am not sure if the above is related to my issue. After updating the core to 3.0.184, my original issue is gone for now. I close the issue first.
