### ISSUE TITLE
ProcessPageEditLink - new "link-text"-feature removes special chars

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1454]
The core module ProcessPageEditLinks updated with PW version 3.0.184 Master and the new function "link-text" is buggy. 

For example, I use plugins in CKE that can insert icons (e.g. Bootstrap or FontAwesome). These are placed as SPAN tags in the CKE like this. 

```
<p><a href="/link-target/"><span class="bi bi-alarm-fill bi-bw">&nbsp;</span> Links with an Icon</a></p>
```

If I now place an icon within a link, the icon and the SPAN tag are lost after editing via the new "link text" dialogue box.

https://user-images.githubusercontent.com/708183/137329783-fa27418e-af1f-4b3f-a0d4-50aee8f0e2a5.mp4

I think only a conversion for HTMLSpecialChars has to be made here in the JS so that the HTML code is simply displayed as plain text in the "link text" field and can thus also be returned.

Concerns the changes from PR#38: https://github.com/processwire/processwire/pull/38

Alternatively, if there is no fix for here, perhaps an option to disable the "link text" function would be useful.

PW: 3.0.184 master

**Comment by flipzoom** [comment]
Anything new here? 🤔

**Comment by flipzoom** [comment]
I have submitted a PR to disable this feature again. In all my environments there is always markup in the link, this feature from PR38 is unfortunately totally counterproductive for me and my customers. Would be great if the option from my PR#224 (https://github.com/processwire/processwire/pull/224) is included in the new master.

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia Thanks, I will return to this one soon after 3.0.200. Since this involves potential user-editing-markup I need to take a little more time with it for testing, playing it safe.

**Comment by matjazpotocnik** [comment]
@FlipZoomMedia this is fixed in https://github.com/processwire/processwire/commit/e0af32189e8364cee87cc9d4edf5e4f0fe39b982
