### ISSUE TITLE
Multiple templates or parents for users cannot be viewed as a guest

### ISSUE THREAD

**Issue by cyrdam** [processwire/processwire-issues#1458]
### Short description of the issue

Users with another parent than default have a profile page to display for the public. This profile page shows some/all of the requested fields in the template.

### Expected behavior

Guest can view the profile page of the user.

### Actual behavior

404 Page not found message is shown.

### Optional: Screenshots/Links that demonstrate the issue

As logged in user:

![image](https://user-images.githubusercontent.com/51902761/137760160-fc0f04fe-c9a5-4629-958f-5b5cc294e7b3.png)

As guest:

![image](https://user-images.githubusercontent.com/51902761/137760201-975460f4-42a1-4e36-bfa8-2daa89f70e91.png)

### Optional: Suggestion for a possible fix

-

### Steps to reproduce the issue

1. Create ProcessWire page from a new installation
2. Go over the steps from: https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users
3. Create templates for
  * 'members'
  * 'member' profile page
4. View profile page as logged in user
5. View the profile page as guest

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.186 dev
* (Optional) PHP version: 7.2.19
* (Optional) MySQL version: 5.1.72
* (Optional) Any 3rd party modules that are installed and could be related to the issue:
  * ProcessDatabaseBackups

### Example page and database files

See attachment: [different-user-template.zip](https://github.com/processwire/processwire-issues/files/7366350/different-user-template.zip)

Database can be found in the zip file at: site/assets/backups/database/different-user-template.sql

**Comment by adrianbj** [comment]
I think this is a duplicate of https://github.com/processwire/processwire-issues/issues/1455

**Comment by cyrdam** [comment]
Yes, it looks like a duplicate. In my case I have included files, so feel free to use them if they are useful.

**Comment by adrianbj** [comment]
Actually, re-reading this, I think you might be able to get things working in your scenario - if you assign `user-view-rolename` to the guest user, where "rolename" is the name of one of the roles assigned to your user profles.

My specific problem is that some of my users only have the guest role. I have added a dummy role to their profiles so I can use that to give guests view access, but this is unnecessarily cumbersome.

**Comment by cyrdam** [comment]
You are right, after reading your issue it is similar, but it's not the same. It still feels somehow related.

But I don't understand your suggestion: do you mean to add the permission `user-view-member` to guest? I don't see how this will help. I set that up, but it is not working. Adding another `user-view-member` as a new role (+ added to the template) didn't do anything, too.

The permission for viewing the page is the same as if the guest would not have the permission, even if it is checked. It looks like the view permission is ignored for the template if not logged in. Removing the view permission from guest and redirecting to another page works.

I have a similar installation with an older PW version (3.0.110) that is working as expected.

The only option I could check now is when this behaviour changed and use that previous version.

**Comment by adrianbj** [comment]
If you add `user-view-member` to the guest role, then they should be able to view users with the `member` role. Does that work for you?

**Comment by cyrdam** [comment]
No, it is not working:

![image](https://user-images.githubusercontent.com/51902761/137983224-93fd74d0-52ba-4ecd-a828-395ca610d425.png)

**Comment by cyrdam** [comment]
I checked with the tagged version https://github.com/processwire/processwire/releases/tag/3.0.165 and it works just fine, the page is shown as a guest user without login.

**Comment by adrianbj** [comment]
Sorry @cyrdam - I'll have to leave this to Ryan then. While I still find the setup for this feature confusing (and still with several bugs - many which I reported recently), this does work for me on 3.0.184. Maybe it was broken in 3.0.186 dev, but I feel like something else might be amiss. I think the reason it's working in 3.0.165 is because the view permissions were added somewhere since then because of the issue of a user being able to view other user's frontend profiles, but not their own (which was really weird). At least that is fixed now.

**Comment by cyrdam** [comment]
The last working version was 3.0.177.

From 3.0.178 it is not working anymore.

**Comment by cyrdam** [comment]
@adrianbj you were right with your suggestion.

I mixed up the permission with role. Additionally the role name was not in sync with the permission part, so this works now.

Within the example I uploaded, the permission name was `user-view-member` but should be `user-view-member-default`.

Thank you for the help!

**Comment by adrianbj** [comment]
Awesome - glad to hear you got it working!
