### ISSUE TITLE
pages_parents scalability issues

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1459]
### Short description of the issue

We have been developing an application on ProcessWire which uses pages to model users' shopping carts. The way that we distinguish a cart from a real order is by its parent page. When a user checks out, the page is moved from under the Carts page (/data/carts) to under the Orders page (/data/orders). This has been working okay for a few years now running on 3.0.148. 

We recently upgraded from 3.0.148 to ProcessWire 3.0.178 and things ran fine for a while. However, we suddenly began getting errors while trying to move the pages from the carts parent to the orders parent. I think it either has to do with the overall number of pages in the system, the number of pages under the subtree, or the increased frequency of orders (with two or more orders now often coming in within seconds of one another).

The total number of carts in the system is currently 32,827 and the total number of completed orders is 120,359. Total number of pages in the system is about 800,000.

We've isolated the issue to line 502 of PagesParents.php, where $this->rebuildAll() is called when the page is moved. Commenting out this line solves the problem, although it also means that the pages_parents table isn't updating the index for has_parent, which is something we were using frequently in the code to identify whether orders and order items were complete or not. To solve this problem, we've reworked the system to rely on an order_complete date field to distinguish the carts from completed orders, instead of the parent. But of course this is a workaround that ideally wouldn't be necessary.

### Expected behavior

Pages can be moved from one parent to another quickly and painlessly regardless of the number of pages in the system. :)

### Actual behavior

The most common exception we've been getting is: 
**SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-2' for key 'PRIMARY'**

More recently we started seeing:
**SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes**

Finally, we started getting:
**SQLSTATE[HY000]: General error: 2006 MySQL server has gone away**

We're on AWS and have been throwing more and more resources at the problem, ultimately moving the database to its own server, which helped in other regards but did not solve this particular problem. Interestingly, even when we began getting the "MySQL server has gone away" error, the site would load up quickly and everything else was fast. So it doesn't appear to be a problem with the database getting bogged down.

* ProcessWire version: 3.0.178
* PHP version: 7.4
* MySQL version: 5.7.mysql_aurora.2.09.2

**Comment by adrianbj** [comment]
Likely related? 
https://github.com/processwire/processwire-issues/issues/1297

**Comment by Lazerproof** [comment]
Hi @ryancramerdesign 
I also encountered this problem. We currently have 300,000 pages in the pages tree and it takes an average of 100 seconds to move a page to the trash. Commenting out this line improves trashing time to 16-19 seconds.

**Comment by adrianbj** [comment]
Interesting about the trashing scenario - I had to trash 10,000 pages the other day and ended up having to do it from a CLI script to prevent timeouts. I didn't consider it might be related to this.

**Comment by jlahijani** [comment]
> Interesting about the trashing scenario - I had to trash 10,000 pages the other day and ended up having to do it from a CLI script to prevent timeouts. I didn't consider it might be related to this.

Related: https://processwire.com/talk/topic/15049-delete-100-000-pages/

**Comment by jlahijani** [comment]
For what it's worth, I have a site where I'm completely refactoring the page structure, and part of that involves moving 20,000 pages from various parent parents to a single parent page.  It takes 3 hours to do using:

`$p->setAndSave('parent', $newParentID);`

... but will probably be a minute if doing:

```
$database->query("UPDATE `pages` SET `parent_id` = '".$newParentID."' WHERE `id` = '".$p->id."';");
```

I'd then rebuild `pages_parents` like so: `$pages->parents()->rebuildAll();`

**Comment by ryancramerdesign** [comment]
@thetuningspoon @Lazerproof @adrianbj @jlahijani I've attempted a fix for this issue but don't have a site with 800k+  pages to test and confirm it resolves the performance issue at that scale. Please let me know if you are able to test it in a dev environment. Thanks.

**Comment by thetuningspoon** [comment]
@ryancramerdesign Just tested this in the same environment that it was previously failing and it worked perfectly! So assuming it is still correctly maintaining the pages_parents table relationships, I think we can close this one.

**Comment by ryancramerdesign** [comment]
Great, thanks for testing it out.
