### ISSUE TITLE
'useNavJSON' => true in Process module "Add New" issue.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#146]
### Short description of the issue

I find that I have to specifically set:
```
$options['add'] = null;
```
to prevent the "Add New" submenu from appearing. 

### Expected behavior

I would have thought that leaving it undeclared completely would suffice.

### Actual behavior

It appears unless I set it to null or ''

### Setup/Environment

* ProcessWire version: 3.0.47

**Comment by ryancramerdesign** [comment]
The $options['add'] has a default value supplied by the base Process class since it accompanies most usages, so you do have to specifically set it to null or blank if you don't want it. Basically, what you are doing is the correct way.

**Comment by adrianbj** [comment]
OK, thanks. I guess I got thrown off by the "optional" and "if applicable" in:
> // Optional URL for adding new items (if applicable)

from here: https://processwire.com/blog/posts/processwire-2.5-updates/#ajax-json-navigation
