### ISSUE TITLE
Superuser cannot change language in user profile

### ISSUE THREAD

**Issue by the-ge** [processwire/processwire-issues#1460]
### Short description of the issue

The superuser cannot change his user profile language in his profile admin interface by checking the desired language and clicking "Submit".

### Expected behavior

The checked language should stay checked after the user profile page reloads.

### Actual behavior

After the user profile page reloads, the default language is checked, instead of the desired one.

### Optional: Screenshots/Links that demonstrate the issue

![Screenshot 2021-10-23 at 02-22-03 Profile • ProcessWire • pwregular r0](https://user-images.githubusercontent.com/6468893/138533956-36ec986c-9f42-45c4-a73d-7ddf0fe8c245.png)

### Optional: Suggestion for a possible fix

The issue happens in 3.0.186. It does not exist in 3.0.184.

### Steps to reproduce the issue

1. Install processwire 3.0.186 with the multi-language profile
2. Login as the superuser
3. Try to change the language from the user profile page.

### Setup/Environment

* ProcessWire version: 3.0.186
* (Optional) PHP version: 8.0
* (Optional) MySQL version: MariaDB 10.5
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by the-ge** [comment]
The issue still exists in 3.0.187.

**Comment by ryancramerdesign** [comment]
Thanks @the-ge I've pushed a fix for this issue.

**Comment by matjazpotocnik** [comment]
@the-ge does Ryan's fix solve the issue? If so, could you close it?

**Comment by netcarver** [comment]
@the-ge Gabriel, closing this now. Please comment again if you need it re-opening.
