### ISSUE TITLE
WireHttp hangs until max_execution time (with use-socket)

### ISSUE THREAD

**Issue by Radon8472** [processwire/processwire-issues#1461]
### Short description of the issue
I tried to make an api-request to instagram api using wireHttp() like this:

```php
$http = new WireHttp();
$json = $http->getJSON('https://graph.instagram.com/me/media?......');
```

### Expected behavior

Data should be loaded from instagram-api and result should be stored in $json;

### Actual behavior

Processwire hangs until max_execution time.
(to be exact, it hangs in the `sendSocket()`-method while reading the contents with `$response .= fgets($fs, 1160);` )

### Screenshots that demonstrate the issue
![grafik](https://user-images.githubusercontent.com/30496382/139103084-64984ec6-c06f-4be3-bc6d-3262c788e614.png)

### Suggestion for a possible fix
I knew that I did`t have this bug before updating to ProcessWire version 3.0.184, so I restored the WireHttp class from the version before, and bug was gone.
After more investigation I discovered:
- my processwire chooses `socket` connection method per default
- method `wireHttp::sendSocket()` changed what caused the issue
  - problem was that [WireHttp Line 749] was changed to use protocol from config (what is `HTTP/1.1` per default)
  - but http 1.1 needs a `Connection`-header

So the fix would be, adding `$request .= "Connection: close\r\n";` in `sendSocket()` after writing the headers

### Steps to reproduce the issue

1. run any http-call with wireHttp (when curl is not active, or with adding the option `['use' => 'socket']`)
2. open the side, that contains your code in browser

Example-code:

```php
 $http = new WireHttp();
$http->get('https://github.com/processwire', [], ['use' => 'fopen'])); // works fine
$http->get('https://github.com/processwire', [], ['use' => 'socket'])); // hangs until max_execution time
```

### Setup/Environment

* ProcessWire version: 3.0.184
* PHP version: 7.3.13
* `curl`-extension is NOT present

[WireHttp Line 749]: https://github.com/processwire/processwire/blob/d78276e2c265f6b70384a13eb4febd4811a1db77/wire/core/WireHttp.php#L749

**Comment by ryancramerdesign** [comment]
Thanks @Radon8472 I've pushed your suggested fix for this issue.

**Comment by Radon8472** [comment]
@ryancramerdesign

Thx,

Is there a reason, why the assigned PullRequest (processwire/processwire#202) is displayed as open?

**Comment by ryancramerdesign** [comment]
@Radon8472 When I do pull requests I try and make a day (or a week) of it, so review them all in batches. I haven't reviewed the queue of new PRs just yet and didn't realize you'd submitted that related to this. Thanks for letting me know,  I'll close it out.
