### ISSUE TITLE
InputfieldImage: proportional thumbnails not displayed properly in some situations

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1465]
### Short description of the issue

I've seen this issue on and off in different situations for a long time but only recently came up with a test case that shows it consistently.

The issue is that when the "Proportional grid images" mode is selected for an images field it doesn't always display correctly. Sometimes the width of the thumbnail container isn't the same as the width of the thumbnail image - you get a square container that crops the edges of landscape images and leaves the checkerboard pattern visible on portrait images.

![2021-11-06_131804](https://user-images.githubusercontent.com/1538852/140591166-fa5beae8-ed2a-4165-b04f-6061dcf93e10.png)

### Steps to reproduce the issue

1\. Create a Repeater field that contains an Images field, where the Images field has "Proportional grid images" mode set.

2\. Set the Repeater field to "Items always open (disables dynamic loading for existing items)".

3\. Set the Repeater field visibility to "Closed".

4\. On a page that includes the Repeater field, note that when the Repeater field is opened the thumbnails are not proportional.

### Screencast

![images](https://user-images.githubusercontent.com/1538852/140591370-d7c0f829-9b22-4712-903c-d31d91af9d87.gif)

### Setup/Environment

* ProcessWire version: 3.0.189

**Comment by Toutouwai** [comment]
A simpler way to reproduce this issue is to put an images field inside a fieldset whose visibility is set to closed. Note how the images field in the screencast below has its thumbnail mode set to proportional but the thumbnails are square.

![images](https://user-images.githubusercontent.com/1538852/185831587-86d4857a-d0a5-4fb2-9765-f4c95eb641f2.gif)

I think the issue is that if the thumbnails are not visible when the images field is initialised then they don't get the correct grid proportion set.

A solution is to reinitialise the images field whenever a parent inputfield triggers the "opened" event. There are similar reinitialisations on different events already in InputfieldImage.js and I just tacked an extra listener on the end. 

```js
$(document).on('reloaded', '.InputfieldImage', function() {
    var $inputfield = $(this);
    initInputfield($inputfield);
    initUploadHTML5($inputfield);
    //console.log('InputfieldImage reloaded');
    Inputfields.init($inputfield);
}).on('wiretabclick', function(e, $newTab, $oldTab) {
    $newTab.find(".InputfieldImage").each(function() {
        initInputfield($(this));
    });
}).on('opened', '.InputfieldImage', function() {
    //console.log('InputfieldImage opened');
    initInputfield($(this));
}).on('opened', function() {
    $(this).find(".InputfieldImage").each(function() {
        initInputfield($(this));
    });
});
```

There would probably be a way to consolidate the two "opened" listeners into a single function.

Result:

![images2](https://user-images.githubusercontent.com/1538852/185832112-47ee4063-41fa-4a9f-b908-170092a6ea37.gif)

**Comment by Toutouwai** [comment]
@ryancramerdesign, could you please take a look at the suggested fix and add to the core if you think it's suitable?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've added your suggested fix for this. As for a combined `opened` event, how about this?
~~~~~~
}).on('opened', function() {
  var $t = $(this);
  if($t.hasClass('InputfieldImage') {
    initInputfield($t);
  } else {
    $t.find('.InputfieldImage').each(function() {
      initInputfield($(this));
    }); 
  }
});
~~~~~~

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, and the combined version looks good to me.
