### ISSUE TITLE
Pages->find Selector throws error if can't match against FieldtypeOptions field

### ISSUE THREAD

**Issue by mrjcgoodwin** [processwire/processwire-issues#1468]
### Short description of the issue
Running a pages->(selector) against a _Select Options Fieldtype (FieldtypeOptions)_ field using checkboxes throws an error if the selector returns no matches.

### Expected behavior
If no matches are found, return an empty pages object with count property set to zero (as per other field types).

### Actual behavior

An error is thrown if selector doesn't find a match:
_Error: Exception: SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters (in wire/core/PageFinder.php line 627)"._

### Steps to reproduce the issue

1. Create a FieldtypeOptions field with multiple checkbox options.
2. Apply field to a template and create a page using that template (do not check any checkbox options).
3. Create a selector: `$foo = $pages->find("your_checkbox_field=bar")`
4. Load page to see error.

### Setup/Environment
PHP version: 7.4.24
ProcessWire 3.0.165

**Comment by ryancramerdesign** [comment]
@mrjcgoodwin If I recall, this issue was fixed already. Are you able to test with a newer version? (3.0.184 or newer?)

**Comment by mrjcgoodwin** [comment]
> @mrjcgoodwin If I recall, this issue was fixed already. Are you able to test with a newer version? (3.0.184 or newer?)

@ryancramerdesign Sure - will update the installation and report back asap.

**Comment by mrjcgoodwin** [comment]
Hi @ryancramerdesign - have updated to 3.0.184 and I _think_ it's fixed. It is now working in most cases, but I've found that using certain selectors still throws an error - albeit a different one to above so not sure if it is related or not. I could just be misunderstanding selector use against this field type.

If I use `=` selector or `*=` selector it throws:
`Error: Exception: SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list (in wire/core/DatabaseQuery.php line 752)`

Using `~|%=` works fine in the same circumstance and generates the results we were hoping for with the search.

If it helps this is the final combined selector:

`stripe_subscription_status=active,(clinicdetails_description|clinicdetails_short_description|clinicdetails_clinic_name|clinicdetails_first_name|clinicdetails_last_name*=$query),(clinicdetails_specialisms.title~|%=$query))`

`$query` is a free text search field so can be multiple keywords.
`clinicdetails_specialisms` is the options field.

**Comment by ryancramerdesign** [comment]
@mrjcgoodwin It looks like you are doing it right, separating your options field from the text fields in the selector. I do see an extra ")" at the end of your selector which shouldn't be there, but am guessing that's just a copy/paste error. So far I can't duplicate that error here, so the issue may be isolated to the master branch and not present on the dev branch. Here's the test I was using (toggles is my options field):
~~~~~
$query = $sanitizer->selectorValue('content'); 
$items = $pages->find("(title|summary*=$query), (toggles.title~|%=$query)");   
~~~~~

**Comment by matjazpotocnik** [comment]
@mrjcgoodwin any news on this? Can you test on the latest dev?

**Comment by netcarver** [comment]
Closing on the assumption this is fixed. @mrjcgoodwin Please comment here again if that is not the case.

**Comment by mrjcgoodwin** [comment]
@ryancramerdesign @matjazpotocnik @netcarver Apologies guys have been AWOL on a big project. I will test this ASAP and confirm back 100%.

**Comment by mrjcgoodwin** [comment]
Hi again - finally had a chance to double check this. Can confirm seems fixed in latest Master.
