### ISSUE TITLE
Incorrect path returned from $input->url() when called before page is available

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#147]
### Short description of the issue

If you make a call to `$input->url()` before the page is available to PW, you get something like:
```
//processwire/page/edit/-id-1111/?id=1111
```

### Expected behavior

It should return:
```
/processwire/page/edit/?id=1111
```

### Actual behavior

```
//processwire/page/edit/-id-1111/?id=1111
```

### Optional: Suggestion for a possible fix

Pull request is ready: https://github.com/processwire/processwire/pull/46

### Steps to reproduce the issue

1. Call `$input->url()` in a module's init, or any other place that is before page is available.

### Setup/Environment

* ProcessWire version: 3.0.47

**Comment by ryancramerdesign** [comment]
The API is not considered ready until the ready state (when the ready() methods are triggered), so no guarantees on API vars being fully functional before that. But happy to have the support added in the PR, so thanks for that–will add this.

**Comment by adrianbj** [comment]
Thanks for adding the PR!

I understand that there is no guarantee of the API vars being fully functional before `ready()` has been called. 

Just an FYI - I didn't add any new support in that PR - I just fixed what was there, which was broken in its current state, but now works because now it is properly parsing just the `path` and not the `query` component of `parse_url($_SERVER['REQUEST_URI'])`

**Comment by ryancramerdesign** [comment]
Thanks for the fix Adrian. I have now merged it.
