### ISSUE TITLE
Inline Inputfield width styles in PW 3.0.184 

### ISSUE THREAD

**Issue by chrisbennett-Bene** [processwire/processwire-issues#1470]
### Short description of the issue

Adding inline width styles to each sized Inputfield seems like a backward step

### Expected behavior

I'm probably missing something, but the addition of inline styles to Inputfield in addition to data-colwidth="" seems counterproductive in terms of easily customising CSS.

It can be 'solved' using !important, but I can't understand why it is a better option than, as previously, targeting via external CSS.

For example, in previous versions something like li[data-colwidth="33%"] {width: 33%} could easily be overwritten by:
li[data-colwidth="33%"] {
    width: calc(33% - var(--input-margin));
}

### Optional: Suggestion for a possible fix

As a general rule, I prefer to let CSS take care of whatever it can and avoid inline styles, so my preference would be a simple list of css styles which could then be easily overwritten, along these lines:
....
li[data-colwidth="15%"] {width:15%;}
li[data-colwidth="16%"] {width:16%;}
li[data-colwidth="17%"] {width:17%;}
li[data-colwidth="18%"] {width:18%;}
li[data-colwidth="19%"] {width:19%;}
li[data-colwidth="20%"] {width:20%;}
li[data-colwidth="21%"] {width:21%;}
li[data-colwidth="22%"] {width:22%;}
li[data-colwidth="23%"] {width:23%;}
li[data-colwidth="24%"] {width:24%;}
li[data-colwidth="25%"] {width:25%;}
etc...

Even if you added all 100 possible options, it's going to come in at a max of around 5kb before it is gzipped.

Gzipped and cached, the one-off CSS transfer would be very small in comparison to the addition of the extra inline style in the html on every sized Inputfield and would remain easily overridden when needed.

* ProcessWire version: PW 3.0.184

**Comment by chrisbennett-Bene** [comment]
Okay, this problem can be avoided by following Robin S's excellent advice from here:
https://processwire.com/talk/topic/26360-use-option-a-uikit-uk-width-to-avoid-processwire-30184-inline-style-widths-and-maxcolheightspacer

I believe it is new behaviour as I am sure I have always previously used Option B, but at least there may be some rationale behind it in instances where widths are misbehaving.

I'd still much prefer a CSS approach or even a third C: 'nuclear' option for the injected js widths option, but without knowing exactly what the use case was for this change I can only guess at what problems it was attempting to solve. 

I would be very happy to help try to solve whatever use case it was using an alternate CSS method

So if, like me, you spend a lot of time making things work with custom CSS then a lot of hassle can be avoided by selecting:
Admin>Modules > Uikit
Layout + interface > Inputfield column widths > **A: Uikit uk-width classes (up-to 6 columns)**

**Comment by matjazpotocnik** [comment]
@chrisbennett-Bene looks like you're ok with Robin's reply. Could you close this issue?

**Comment by matjazpotocnik** [comment]
@chrisbennett-Bene Closing. Post more if it needs re-opening.
