### ISSUE TITLE
findRaw() error on fields that don't have a DB table

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1471]
### Short description of the issue

If you do a `findRaw()` without specifying the fields you want and the template of any of the matching pages includes a field that doesn't have a DB table, then you get an error like this: Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'field_coupon_link' doesn't exist on line: 744 in /var/www/html/wire/core/PagesRaw.php 

### Expected behavior

It should check if there is a DB table and handle it gracefully is there isn't one.

### Actual behavior

The error as shown above.

### Steps to reproduce the issue

1. Set up a template with a core concat field (or @Toutouwai's RuntimeOnly field)
2. `$pages->findRaw('template=basic-page');`

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this one.
