### ISSUE TITLE
Outline glitch for fields in Repeater

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1472]
### Short description of the issue

The inputfield outline is missing.

3.0.189
![2021-11-13_153147](https://user-images.githubusercontent.com/1538852/141602694-ffefd074-3139-417b-a7ea-9c592a308d79.png)

3.0.184 master
![2021-11-13_153331](https://user-images.githubusercontent.com/1538852/141602699-a199ed28-e9c1-4ca9-be76-d235648e9809.png)

### Setup/Environment

* ProcessWire version: 3.0.189

**Comment by Toutouwai** [comment]
I think it's caused by this change: https://github.com/processwire/processwire/commit/a19a224c208e8aede41547e712c3c9fc7cbd399c#diff-825e66cf1f26c50853e92125ff0702124c199f005aa00993a023a0bb1192bc33R22
Maybe this style could target the header more specifically?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this.

**Comment by Toutouwai** [comment]
Thanks
