### ISSUE TITLE
ProcessDatabaseBackups producing errors in TracyDebugger

### ISSUE THREAD

**Issue by chimmel** [processwire/processwire-issues#1473]
### Short description of the issue

Backup appears to generate, but these errors appear:
```
2× 	PHP Warning: fgets() expects parameter 1 to be resource, bool given in .../wire/core/WireDatabaseBackup.php:537

2× 	PHP Warning: fseek() expects parameter 1 to be resource, bool given in .../wire/core/WireDatabaseBackup.php:549

2× 	PHP Warning: fread() expects parameter 1 to be resource, bool given in .../wire/core/WireDatabaseBackup.php:550

2× 	PHP Warning: fclose() expects parameter 1 to be resource, bool given in .../wire/core/WireDatabaseBackup.php:552
```

Nothing past that observed yet. 

### Expected behavior

Expected behavior goes here.

### Actual behavior

Actual behavior goes here.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Install TracyDebugger
2. Install ProcessDatabaseBackups
3. Backup via

### Setup/Environment

* ProcessWire version: 3.0.184-master
* (Optional) PHP version: 7.4.4
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@chimmel So far I can't duplicate this issue. Tested with Tracy and ProcessDatabaseBackups but backup was successfully created and no warnings or errors from Tracy. Were there any specific settings you used when creating the backup? In my case I just used the default settings.

**Comment by matjazpotocnik** [comment]
@chimmel can you provide more info for Ryan?

**Comment by netcarver** [comment]
@chimmel Please could you provide more information?  Will close soon if you can't.

**Comment by netcarver** [comment]
Closing.
