### ISSUE TITLE
FieldtypeRepeater is sending dumps to Tracy Debugger

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1474]
### Short description of the issue

When I save a repeater field I'm seeing these bar dumps, which are triggered in the core FieldtypeRepeater:
![2021-11-17_113343](https://user-images.githubusercontent.com/1538852/142077687-50467b29-1044-41fb-af21-0d3fdea1582d.png)

I expect this is for debugging purposes while new repeater features are under development, but I expected these sort of debugging dumps would use some kind of debug flag so they only occur during development and not in the public PW release.

It's not a big deal but it causes distraction when Tracy Debugger is also being used for site development.

### Setup/Environment

* ProcessWire version: 3.0.189

**Comment by Toutouwai** [comment]
@ryancramerdesign, could the [FieldtypeRepeater::bd()](https://github.com/processwire/processwire/blob/aa87cc5603660cad9bb23285b29359bec3717271/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L2151-L2159) method...

```php
protected function bd($msg, $func = '') {
	if(!$this->wire()->config->debug || !class_exists('\\TD')) return;
	call_user_func_array('\\TD::barDump', array($msg, $this->className() . "::$func"));
}
```
...please be active only according to some internal debug flag as I've seen in other PW classes rather than the global `$config->debug` setting? I think these dumps are only intended for you and not for everyone who has their site in debug mode?

**Comment by matjazpotocnik** [comment]
@Toutouwai This is fixed in https://github.com/processwire/processwire/commit/fa3fb8ec892cc7f4c0fcc2094b17c4bd19c1d004
