### ISSUE TITLE
PageAutocomplete matches everything if "Fields to query for autocomplete" includes unsupported field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1476]
### Short description of the issue

I have a Page Reference field using PageAutocomplete. If I set "Fields to query for autocomplete" like this...

![2021-11-22_180009](https://user-images.githubusercontent.com/1538852/142803500-a8c88432-6769-4144-8aad-451c4dbe7afd.png)

...then the selector string is as expected:

![2021-11-22_175946](https://user-images.githubusercontent.com/1538852/142803521-7be5d646-0f12-4a43-98f8-91861065b1df.png)

But if "Fields to query for autocomplete" includes an unsupported field...

![2021-11-22_180242](https://user-images.githubusercontent.com/1538852/142803697-9e68eb22-607c-454f-87e7-3e22c3961334.png)

...then the search input just gets discarded and the PageAutocomplete matches everything.

![2021-11-22_180403](https://user-images.githubusercontent.com/1538852/142803830-06af345f-110f-4d38-a431-88f3dafd130a.png)

By "unsupported field" I mean any field that the PageAutocomplete doesn't know how to query (I tried a Combo subfield) or a field name that doesn't exist (maybe the field got deleted after the setting was set, or there is a typo in the field name).

In such cases I'm hoping PageAutocomplete could handle this more gracefully, e.g. ignore the unsupported field but still match against any supported fields rather than discarding the whole search input. And maybe give feedback in the field settings that the entered setting contains an unsupported field?

### Setup/Environment

* ProcessWire version: 3.0.189

**Comment by Toutouwai** [comment]
It looks like subfields are already intended to be supported by PageAutocomplete: https://github.com/ryancramerdesign/ProcessWire/pull/994

PageAutocomplete is eventually using a PageFinder selector string to find matches, so in principle anything that is valid in a selector string will work and ideally should be supported. So a Combo subfield would actually work if it could get into the selector string but the problem is that it gets filtered out before it makes it to the selector.

After digging into this I can see a couple of things that would be good to consider changing.

1\. In ProcessPageSearch (which is used by PageAutocomplete), when you set multiple fields to query these all get lumped together into a comma separated string. At the moment all the fields are passed through `ProcessPageSearch::isSelectableFieldName($name)` at once. So `$name` is something like "field_1,field_2,field_3". But this method only returns a single true/false value so either everything in the string passes or everything fails. It would be better to separate the fields first and pass them through this method individually. 

2\. The idea of "subfields" in PageAutocomplete/ProcessPageSearch seems to only extend as far as standalone fields that are used within a Page-type field. So if I have created a field "text_1" in PW and then I use that within a Page Reference or Repeater or PageTable field then this is supported. But subfields also exist in Fieldtypes like Table, Textareas, Combo, FieldtypeEvents, and probably more. `ProcessPageSearch::isSelectableFieldName()` rejects these kinds of subfields because it is only checking for the existence of standalone fields with the given subfield name. Can this method be updated to support the full range of subfields that PW supports in PageFinder selectors?

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I've pushed a fix for this and have also added support for searching subfields here, so you should now be able to use "field.subfield" in your PageAutocomplete if you'd like.

**Comment by Toutouwai** [comment]
Thanks, works great!
