### ISSUE TITLE
Wrong redirect on multilanguage setup when page name is equal to language name

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1479]
### Short description of the issue

When setting the page name for a direct child of home to be the same as a language name, PW dev branch redirects to the home page and PW master branch throws 404.
Example URL: /cn/cn/

### Expected behavior

The page with URL /cn/cn/ is displayed

### Actual behavior

PW master throws 404, PW dev redirects to /cn/

### Optional: Screenshots/Links that demonstrate the issue

In depth sescription can be found [in the forum](https://processwire.com/talk/topic/26462-wrong-redirection-for-page-with-name-that-equals-language-root-name/).

### Optional: Suggestion for a possible fix

[PagesPathFinder->getPathPartsLanguage(&$parts)](https://github.com/processwire/processwire/blob/46215bdfc26babb8793568d5279b11d7b3c4c21b/wire/core/PagesPathFinder.php#L531) seems to be causing this. No fix found yet.

### Steps to reproduce the issue

1. Install latest PW with multilang profile
2. add language Chinese with name 'cn'
3. set homepage name for language Chinese to 'cn'
4. add a child page to home with name 'cn'
5. for the new page set only language cn as active (optional, doesn't make a difference)
6. try to open the page at /cn/cn/

### Setup/Environment

* ProcessWire version: 3.0.184 master and 3.0.189 dev
* (Optional) PHP version: 7.4
* (Optional) MySQL version: 5.7.35
* (Optional) Any 3rd party modules that are installed and could be related to the issue: none installed

**Comment by ryancramerdesign** [comment]
@gebeer When I create new page /cn/ that duplicates the language name "cn" (specified on homepage), and the view it at /cn/cn/, it shows the /cn/cn/ page, which seems like what we'd want it to do? Though I think it's confusing to have a page having the same name as a language, so not sure there's a good use case for doing it, but I agree it should show the /cn/cn/ page in this instance. That's what it's doing in my case at least. Maybe I'm missing some part of it?

**Comment by gebeer** [comment]
> @gebeer When I create new page /cn/ that duplicates the language name "cn" (specified on homepage), and the view it at /cn/cn/, it shows the /cn/cn/ page, which seems like what we'd want it to do? Though I think it's confusing to have a page having the same name as a language, so not sure there's a good use case for doing it, but I agree it should show the /cn/cn/ page in this instance. That's what it's doing in my case at least. Maybe I'm missing some part of it?

Are you sure you have the same setup?
I am testing this on a clean PW multilang install. When I view /cn/cn/, I get redirected to /cn/ 
When I view child page /cn/cn/home/ it redirects to /cn/home
PW 3.0.189 dev
PHP 7.4.22
Can you please share your environment details, so we can find out the difference?

Unfortunately the URL structure /cn/cn/ is mandatory for this project since we are porting an existing Typo3 installation to PW.

**Comment by ryancramerdesign** [comment]
@gebeer I did some manual testing with PagesPathFinder on my /cn/cn/ page and found that it was locating it with the core PagePaths module. I'm thinking you likely don't have this core module enabled. So I disabled the PagePaths module and then was able to duplicate the issue, track it down and fix it. Though please let me know if you still run into it.

**Comment by gebeer** [comment]
> @gebeer I did some manual testing with PagesPathFinder on my /cn/cn/ page and found that it was locating it with the core PagePaths module. I'm thinking you likely don't have this core module enabled. So I disabled the PagePaths module and then was able to duplicate the issue, track it down and fix it. Though please let me know if you still run into it.

Yes, I didn't have core PagePaths module installed.

I can confirm that on latest dev the URL /cn/cn/ is working as expected now.
Thank you very much for fixing!
