### ISSUE TITLE
Pages still in runtime cache after deletion

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#148]
### Short description of the issue

After deleting pages, there are sill accessible with all their properties.
PageCache?

### Expected behavior

Deleted pages should be instanceof `ProcessWire\NullPage`
This was the behavior in at least version `3.0.39` and below

### Actual behavior

Deleted pages are instances their respective page classes

This only applies only on runtime, the pages are actually deleted as expected. A reload makes them the expected `NullPage`

### Steps to reproduce the issue

```php
$hans = $users->get('hans');
$users->delete($hans);
var_export($users->get('hans')); // ProcessWire\User ... should be ProcessWire\NullPage
var_export($users->get('hans')->id); // 123 ... should be 0
var_export($users->get('hans')->name); // hans ... should be null
```

### Setup/Environment

* ProcessWire version: 3.0.47
* PHP version: 5.5.12
* MySQL version: 14.14 Distrib 5.6.17

**Comment by ryancramerdesign** [comment]
Removing a page from the runtime memory cache after deletion could cause issues in various cases, so we had to disable that behavior. However, if you need it enabled, and it doesn't cause problems in your instance, do your deletion like this:
~~~~~
$pages->delete($page, [ 'uncacheAll' => true]); 
~~~~~
Another alternative is that you can test a page's deletion state like this: 
~~~~~
if($page->hasStatus('deleted')) {
  // page is deleted
} else {
  // page is not deleted
}
~~~~~

**Comment by owzim** [comment]
I see. Thanks @ryancramerdesign for providing an alternative after the apparently important change. Solved!
