### ISSUE TITLE
ProcessPageEditImageSelect always defaults to first Repeater item

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1482]
### Short description of the issue

When inserting an image into a CKEditor field inside a repeater, or in a template that also contains a Repeater field, ProcessPageEditImageSelect always defaults to the first Repeater item.

In the demo below, note that the CKEditor field in the template is below the Repeater field. This seems to affect the ProcessPageEditImageSelect behaviour.

![select-image](https://user-images.githubusercontent.com/1538852/145358708-fe08c293-0718-4261-afb6-b4446c23995a.gif)

Related forum topic: https://processwire.com/talk/topic/26493-processpageeditimageselect-problem-with-repeaters/

### Expected behavior

ProcessPageEditImageSelect defaults to the page that contains the CKEditor field, be it a Repeater page or the edited page itself.

### Setup/Environment

* ProcessWire version: 3.0.190

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
