### ISSUE TITLE
v3.0.184: strtotime reliant created, modified and published finds are broken for PHP < 8.0

### ISSUE THREAD

**Issue by sforsman** [processwire/processwire-issues#1483]
### Short description of the issue

The fix introduced for https://github.com/processwire/processwire-issues/issues/1288 breaks finds such as `modified>=yesterday` and `created>=today` in environments with PHP < 8.0.

The reason can be found here:

https://github.com/processwire/processwire/blob/master/wire/core/WireDateTime.php#L449

The line always passes at least `null` as the second argument to PHP's internal `strtotime()`, which is handled as `0` in PHP < 8.0. (PHP introduced the nullable second argument in 8.0.) In these earlier versions the result is obviously a different timestamp than the user intended.

Because ProcessWire also uses the new WireDateTime.strtotime() -method internally, the side effect is that finds using the native date fields with strtotime-compatible strings produce completely incorrect results. For example, a search like `created>=today, include=all` will always return every page from the database (assuming the pages have reasonable timestamps). Before v3.0.184 this would only return pages that were created after midnight, regardless of the PHP version in use.

In the rest of the issue report I'll only refer to the WireDateTime.strtotime() -method, because the issue is easier to demonstrate (i.e. producing the results do not depend on the state of the database) and the method is also the underlying reason for the current behavior.

### Expected behavior

`wire()->datetime->strtotime('yesterday') === strtotime('yesterday')`

### Actual behavior

`wire()->datetime->strtotime('yesterday') !== strtotime('yesterday')`

### Suggestion for a possible fix

```diff
--- a/wire/core/WireDateTime.php
+++ b/wire/core/WireDateTime.php
@@ -446,7 +446,7 @@ class WireDateTime extends Wire {
 			$test = trim(preg_replace('/[^\d]/', '', $str), '0');
 			if(!strlen($test)) return $options['emptyReturnValue'];
 		}
-		return strtotime($str, $options['baseTimestamp']); 
+		return ($options['baseTimestamp'] !== null) ? strtotime($str, $options['baseTimestamp']) : strtotime($str);
 	}
```

### Steps to reproduce the issue

```php
<?php

namespace ProcessWire;

require 'index.php';

// Should print the current unix timestamp, instead prints 0
// with a delta depending on the current timezone.
var_dump(wire()->datetime->strtotime("now"));
```

### Setup/Environment

* ProcessWire version: 3.0.184
* PHP version: 7.4

**Comment by ryancramerdesign** [comment]
Thanks @sforsman that's a good find, I've pushed your suggested fix.

**Comment by sforsman** [comment]
Thanks @ryancramerdesign for responding so quickly!
