### ISSUE TITLE
Datetime field Year/Y saves year as 1970

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#1484]
### Short description of the issue

Am I right in saying that the [datetime field](https://processwire.com/api/ref/inputfield-datetime/) doesn't support year as the only input?

Field: year
* Type: Datetime
* Date/Time output format code: Y (I said "none" to all other output formats)
* Input
	* Input type: Text input with jQuery UI datepicker.
	* Date Picker: None.

### Expected behavior

I would expect Year to be part of datetime, as it is [in PHP](https://www.php.net/manual/en/book.datetime.php).

* Date Picker shows years only.
* Entering "2021" is stored correctly.

### Actual behavior

* When entering 2021 in the Year field on a page, then the value is set to 1970.
* DateTime picker (when enabled) shows both month/year dropdowns and calendar (not needed)

Obviously, the workaround is to convert to an Integer field and that works fine:

* Default value: 2021 (I would prefer current year or a code: `date('Y',time())`)
* Input size: 4
* Numeric input type: Number (HTML5)
* Minimum value: 1970
* Maximum value: 2025

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Datetime shall support year as input ("2021").

### Steps to reproduce the issue

1. Create datetime field: "Year"
2. Add to template
3. Edit Page, enter "2021". Year is shown as "1970" on save.

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.184 © 2021

**Comment by ryancramerdesign** [comment]
@klor I don't think you'll be able to use just year because it is a digit-only value, and so it's going to get confused with a unix timestamp. It accepts inputs as either unix timestamp or strtotime compatible formatted date, and a 4-digit year would be neither of those. In addition, you can't store just a year in the DB with a date field, so there's not much point in using a date field for this. Since a year is an integer, using an Integer field would be a better bet.

**Comment by klor** [comment]
@ryancramerdesign - Noted. Let me offer some background info: I have a date field on a template that I can show as a date (d.m.Y), month (m.Y), or year only (Y). In case I decide to change the field type from date to year, I will need to:

1) create new field, 
2) migrate data, 
3) delete the old field, and 
4) modify the template.
5) ... Compare this to just changing the field type.

My reasoning behind this request is that ProcessWire doesn't make asummptions about what users do. `ProcessWire is designed to be friendly to schema changes. We assume that you are probably not defining everything you need ahead of time.` [#](https://processwire.com/talk/topic/2199-checkbox-default-value/#comment-20663_wrap). So, "change Field type date to anything you want."

> you can't store just a year in the DB with a date field

Timestamp to the rescue. If the date / year / month-year / .. is stored as a timestamp then it's no issue.

```php
foreach (range(2020,2022) as $v) {
	$ts = strtotime("1/1/$v");
	echo
		date("Y",$ts)
		. " = " . $ts
		. ". Add +1 year with strtotime: " . date("Y", strtotime("+1 year",$ts))
		. ".\n";
}
```

Output:
2020 = 1577836800. Add +1 year with strtotime: 2021.
2021 = 1609459200. Add +1 year with strtotime: 2022.
2022 = 1640995200. Add +1 year with strtotime: 2023.

And again - noted. I can understand if this gets rejected, it's more my OCD than a top priority.. ;-)

Merry Christmas and Happy New Year from Denmark!

**Comment by ryancramerdesign** [comment]
@klor If you have a field where you don't know for sure what components of the date you will need for output purposes (whether now or later) then I think it's actually a good idea to stick with the date field. I do something similar, using a date field when I only just need to output month+year on the front end (without day). The thing to keep in mind in your API or input usage is that you are still working with a date field, so while you might only use the year on the front-end, you'll still want to use a date when you set a value... So it could be any date in the given year you are wanting. When I only need month+year, I usually use the first day of the month, i.e. if I need October 2021 then I'll set the value as 2021-10-01.
