### ISSUE TITLE
Multilang Page Reference - Text Tag Input does not show on non-default languages

### ISSUE THREAD

**Issue by Matoseb** [processwire/processwire-issues#1485]
### Short description of the issue
If I set Text Tag as the input field for a Page Reference Field. The tags added are only shown when the language of my Profile is set to default.

### Expected behavior
It should show the text tags with any profile language, with the label shown in the proper language

### Actual behavior
The tags are not visible in the text tag field if I have Processwire in a non-default language

### Optional: Screenshots/Links that demonstrate the issue

- Default Admin Language (french):
<img width="500" alt="default-language" src="https://user-images.githubusercontent.com/24431250/146012322-a8547a05-1362-4d1f-b876-9f108bdb20a6.png">

- Non-default Admin Language (english):
<img width="500" alt="non-default-language" src="https://user-images.githubusercontent.com/24431250/146012340-b710e511-f507-4571-a279-30e021558287.png">

### Steps to reproduce the issue
- Have at least 2 languages
- Have a page reference field
1. Set the default language in the admin profile
2. Add/create some tags to the page reference, then save
3. Set to another language in the admin profile
4. Go back to the page reference. Nothing is shown anymore

### Setup/Environment
- Database: MariaDB 10.4
- PHP 7.3 
- Apache 2.4.51

* ProcessWire version: 3.0.190

**Comment by ryancramerdesign** [comment]
Thanks @Matoseb I've pushed a fix for this issue.

**Comment by Matoseb** [comment]
Works great, thank you!
