### ISSUE TITLE
InputfieldPageAutocomplete doesn't work with page.* in selector until page is saved

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1486]
### Short description of the issue

When using a Page field with the Select or AsmSelect inputfields, you can set the Selector String under Selectable Pages to something like "field_on_pages_im_searching=page.field_on_this_page" and when field_on_this_page is changed, ajax will kick in and reload the selectable options. Cool feature!

This type of selector also works for limiting the results of InputfieldPageAutocomplete, but for some reason it doesn't trigger the ajax reload. So the results are not limited/updated until after the entire page is saved and reloaded.

### Expected behavior

Editing field_on_this_page should cause my page field using InputfieldPageAutocomplete to update and from then only return results that match the new selector. It seems like this would be as simple as triggering the reload event on the field.

### Actual behavior

Nothing happens until the page is saved/reloaded.

### Setup/Environment

* ProcessWire version: 3.0.165

**Comment by ryancramerdesign** [comment]
@thetuningspoon If I recall this feature is limited to just select fields. But the InputfieldPageAutocomplete didn't support subfields until just last week (dev branch), so it may be that using the dev branch will help for what you are trying to do. I'm not 100% positive but am thinking the page.* still won't work because the "page" would be the ProcessPageSearch page since it is the ajax handler at that point. Have you looked into the InputfieldTextTags autocomplete option?  With that one you can provide your own ajax handler with a path/URL hook, which opens up a lot of flexibility. I think you'll need to upgrade to the current master branch though as I don't think that one was in 3.0.165.

**Comment by Toutouwai** [comment]
@thetuningspoon, I was just this morning working on a [module](https://github.com/Toutouwai/SelectOncePerTable/blob/46a983593625027c4ea7b28e009456f6766e5315/SelectOncePerTable.js#L26-L50) that needed to dynamically change the AJAX url used by PageAutocomplete so it is fresh in my mind. 

If you're up for using custom JS here is an example of how you might do it...

In this example I have two Page Reference fields: "select_parent" (Select) and "select_child" (Autocomplete). The selector string for selectable pages in select_child is:

![2021-12-16_120635](https://user-images.githubusercontent.com/1538852/146278761-5b034ece-5a94-4372-ae8e-1d20c5702c84.png)

The custom JS to load in Page Edit:
```js
// When the source field changes
$(document).on('change', 'select[name="select_parent"]', function() {
    // Get the page ID that is selected in the source field
    var value = $(this).val();
    // If no page selected set value to -1
    if(!value) value = -1;
    // Get the URL data attribute from the dependent PageAutocomplete
    var $dependent_field = $('input[name="select_child[]"');
    var url_pieces = $dependent_field.data('url').split('?');
    // Get the URL parameters
    var params = new URLSearchParams(url_pieces[1]);
    // Set the parent parameter to the value of the source field
    // You would vary this step according to how you are using the source field in the selector for the Page Autocomplete
    params.set('parent', value);
    // Set the modified URL back to the data attribute and remove the init class so the PageAutocomplete can be reinitialised
    $dependent_field.attr('data-url', url_pieces[0] + '?' + params.toString()).removeClass('InputfieldPageAutocompleteInit');
    // Reinitialise the PageAutocomplete
    InputfieldPageAutocomplete.initFromInputfield($dependent_field.parents('.InputfieldPageAutocomplete'));
});
```

![dependent-autocomplete](https://user-images.githubusercontent.com/1538852/146279148-5647549b-a575-46b4-82d6-bc2f7f67feba.gif)
