### ISSUE TITLE
Can't select created user from alternate user parent / template when changing page created user

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1487]
### Short description of the issue

If you have the `allowChangeUser` option selected for a template, you can't select from a users from an alternate parent / template.

### Expected behavior

Should be able to select from any set of users. The list should be configurable.

### Actual behavior

Only "normal" users are selectable.

### Optional: Suggestion for a possible fix

I see you have a comment about supporting this here: https://github.com/processwire/processwire/blob/697158d6534f4665d6c7413f99954f48ee1b0aff/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L1393

In some systems it will be essential to be able to define which tree of users shown because if it includes frontend users it becomes unusable when there are too many. On that note, an autocomplete approach might be better anyway.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've updated this so that you can enter a user ID when the conditions require it. Maybe later will have the time to make it some kind of autocomplete, but for now I've made the method hookable in case someone needs something more than entering a user ID.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that hook makes things easy. In case anyone is interested, I ended up with the following to use the traditional InputfieldPageListSelect while being able to set the parent to the branch I need.
```
$this->wire()->addHookBefore('ProcessPageEdit::buildFormCreatedUser', function($event) {
	$f = $this->wire('modules')->get('InputfieldPageListSelect');
	$f->parent_id = 8493; // custom user parent
	$f->showPath = false;
	$f->label = $this->_('Created by User');
	$f->attr('id+name', 'created_users_id');
	$f->attr('value', $event->object->getPage()->created_users_id);
	$f->required = true;
	$event->replace = true;
	$event->return = $f;
});
```
