### ISSUE TITLE
Internationalization (LanguageSupport) module will not parse phrases initialized in associative arrays or as function parameters

### ISSUE THREAD

**Issue by Tyde** [processwire/processwire-issues#1488]
### Short description of the issue

If you initialize a phase inside a associative array or as a second or later parameter to a function it wont get caught by the parser.
Examples:

1. Example: Here I initialize an associative array with labels for a twig template renderer:
```php
    $parameters = ['name_label'=>__("Name") ,'mail_label'=>__("Mail adress"), 'text_label'=>__("Message"),
            'contact_title'=>__('Contact us'), 'submit_label'=>__("Submit")];

    $content = $factory->render("contactform",$parameters);

```

2. Example: Here I call a function to render some complicated text. The phrase is the third parameter to a function call:
```php
require_once("_calendar.php");

$calendar = render_calendar($pages, $factory,__("Dates"));
```

I know, that if I'd be using proper formatting style in my php, there would be whitespaces in front of the phrase definitions, but nevertheless it is unexpected that it matters to the parser.

### Expected behavior
The initialized phases show up in the Langages menu in the admin panel for these files.

### Actual behavior
The phrases do not show up.

### Optional: Suggestion for a possible fix

First option: Tell the users that the `__('phrase')` shorthand only works if you either have a whitespace, `=`-sign, or opening brackets in front of it. So the following would actually fix my issues (Notice the only difference is the whitespace before):
```php
    $parameters = ['name_label'=> __("Name") ,'mail_label'=> __("Mail adress"), 'text_label'=> __("Message"),
            'contact_title'=> __('Contact us'), 'submit_label'=> __("Submit")];

    $content = $factory->render("contactform",$parameters);

```

Second option: Modify the parsing regex in [`LanguageParser.php:230`](https://github.com/processwire/processwire/blob/d78276e2c265f6b70384a13eb4febd4811a1db77/wire/modules/LanguageSupport/LanguageParser.php#L230) 
from 
```regex
/([\s.=(\\]__|^__)\(\s*(['"])(.+?)(?<!\\)\2\s*(?:,\s*[^)]+)?\)+(.*)$/m
```
to
```regex
/([\s.=(\\,]__|=>__|^__)\(\s*(['"])(.+?)(?<!\\)\2\s*(?:,\s*[^)]+)?\)+(.*)$/m
```
Here I only added `,`to the first capture group and also included an option for `=>__`. If I'd only match for `>__` here this would also include function calls of classes e.g. `$this->__("foo")`
(You can test the regex here: https://regex101.com/r/ZAIGmh/2)
I don't know if that would introduce other issues though.

**Comment by ryancramerdesign** [comment]
Thanks @Tyde I wasn't aware of the whitespace and array issue, it looks like a good addition to me! If you want me to use your PR so that it credits your account on GitHub I'm supposed to have record of a CLA per the contributing.md file. Otherwise, I can just add it as a regular issue fix, please let me know what you'd prefer.

> Before submitting a PR, read the Contributor License Agreement (CLA) at <https://processwire.com/about/license/cla/> and indicate your agreement (electronic signature) by completing the form at the bottom of the page.

Also wanted to mention that in your example for `$parameters` that may still won't work because of the [one translation per line](https://processwire.com/docs/multi-language-support/code-i18n/#there-may-only-be-one-translation-function-call-per-line) rule. Though you may already know that but wanted to mention just in case. Thanks.

**Comment by Tyde** [comment]
I've signed the CLA now and you can use the pull request.

**Comment by ryancramerdesign** [comment]
Thanks @Tyde I've added your PR/fix.
