### ISSUE TITLE
Typo in ProcessCommentsManager.module

### ISSUE THREAD

**Issue by arjenblokzijl** [processwire/processwire-issues#149]
### Short description of the issue

There is a typo in ProcessCommentsManager.

### Expected behavior

I want to see the comments page.

### Actual behavior

I get an error.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Changed $buton to $button.

![screen shot 2017-01-05 at 10 04 39](https://cloud.githubusercontent.com/assets/2040307/21674535/66020df0-d32e-11e6-8d28-7b3e1db52863.png)

### Steps to reproduce the issue

1. Install Comments module
2. Go to Setup > Comments

### Setup/Environment
ProcessWire: 3.0.42

**Comment by ryancramerdesign** [comment]
This one was already fixed a few versions back on the dev branch. It should be migrating to the master branch in the next week or two. Thanks.
