### ISSUE TITLE
Missing field data when using findJoin() in combination with field OR selector

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1490]
### Short description of the issue

When using Pages::findJoin() in combination with an or selector, some of the resulting fields are blank. For example, I have a template called "Individual" with the fields "first_name", "last_name", "email", and "job_title". The following example works correctly with values returned for all fields:

`$this->pages->findJoin("template=Individual, first_name=mike", ['first_name', 'last_name', 'email', 'job_title']);`

However, the following example returns no value for 'last_name' even though the same page is returned:

`$this->pages->findJoin("template=Individual, first_name|last_name=mike", ['first_name', 'last_name', 'email', 'job_title']);`

### Expected behavior

An OR condition in the selector should effect the pages returned, but not the values of the fields returned.

### Actual behavior

See above

### Steps to reproduce the issue

See example above

### Setup/Environment

* ProcessWire version: 3.0.178
* PHP version: 7.4.21
* MySQL version: 5.7.34

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon I've pushed a fix for this issue.

**Comment by thetuningspoon** [comment]
@ryancramerdesign Looks like that worked. Thanks for the quick fix!
