### ISSUE TITLE
Array to string conversion notices in PagesRaw.php when using selector arrays with findRaw()

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1491]
### Short description of the issue

I am getting 2 "Array to string conversion" notices in PagesRaw.php when using selector arrays with findRaw(). The lines are 249 and 888.

It looks like it's only accounting for one-dimensional arrays (for an array of page ids) and not for multi-dimensional ones (a selector array).

### Suggested Fix

For line 249, replace:
`if(ctype_digit("$key") && ctype_digit("$val")) $this->selectorIsPageIDs = true;`
with:
`if(!is_array($key) && !is_array($val) && ctype_digit("$key") && ctype_digit("$val")) $this->selectorIsPageIDs = true;`

For line 888, replace:
`if(!is_array($selector) || !isset($selector[0]) || !ctype_digit((string) $selector[0])) {`
with:
`if(!is_array($selector) || !isset($selector[0]) || is_array($selector[0]) || !ctype_digit((string) $selector[0])) {`

This seems to fix it for my use case, though I haven't tested all scenarios thoroughly.

### Setup/Environment

* ProcessWire version: 3.0.178
* PHP version: 7.4.21
* MySQL version: 5.7.34

**Comment by ryancramerdesign** [comment]
@thetuningspoon That might seem to fix it but I also wonder if it might just be suppressing an error and manifesting in something different further down the line. So I think I need to understand the context a little better. Can you reply with the specific selector array that you are using? Thanks.

**Comment by thetuningspoon** [comment]
@ryancramerdesign Here's the selector I'm using:

```
$results = $this->pages->findRaw([
				['template', '=', 'Individual'],
				[['first_name', 'last_name', 'email'], '~|*=', $searchQuery],
				['limit', '=', '100']
			],
				['id', 'first_name', 'last_name', 'email', 'job_title']);
```

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon I've had a close look and think you've got the right fix for this. I've pushed your suggested fix.
