### ISSUE TITLE
Core should not show module download options that are not usable due to config

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1492]
### Short description of the issue

After updating a site to a more recent PW version I go to install a module from the modules directory...

![2021-12-22_165906](https://user-images.githubusercontent.com/1538852/147033400-e39c55fc-bdda-47a0-bc67-dfb767cbfd12.png)
![2021-12-22_165710](https://user-images.githubusercontent.com/1538852/147033431-e9f4fb2e-b1d4-442f-bbf2-d08fecb8d0f1.png)

...or I attempt to upgrade an existing module...

![2021-12-22_165532](https://user-images.githubusercontent.com/1538852/147033459-8f99a2ce-db13-4a91-a49a-5713fb50af0a.png)

...and after clicking the download button I get this...

![2021-12-22_165552](https://user-images.githubusercontent.com/1538852/147033490-b17cb444-7e3f-463c-a5ae-5e31cc91980a.png)

I understand why the message appears and what the solution is, but it's a bit aggravating to have the core show you download features that it "knows" you're not going to be able to use. When module installation is disallowed due the current `$config` settings the user should not see non-usable controls such as "Add Module From Directory" or "Download Now" buttons and ideally in their place should see some notice informing them that module download is not allowed.

### Setup/Environment

* ProcessWire version: 3.0.190

**Comment by ryancramerdesign** [comment]
@Toutouwai The majority of users will never even know the option is there if we just suppress showing these actions. I think the current behavior is the right approach to ensure the options are known to the 90% of users that don't already know about the `$config->moduleInstall` setting. The purpose here is to ensure the user knows this option is built-in and also instruct them on how to enable it, and specifically at the time they want it (should they want it). What I think might be an improvement here though is for the error message to also have a “How to upgrade module manually” link with additional instructions, as maybe a beginner user might not realize the `moduleInstall` settings aren't required to upgrade the module.

**Comment by Toutouwai** [comment]
> The majority of users will never even know the option is there if we just suppress showing these actions.

I don't want to hide those options from the user, I just want to be alerted that a $config setting is disallowing the options from being used as early in the procedure as possible. I don't want to go through the steps of...

1. Typing a module classname
2. Clicking the "Get Module Info" button
3. Waiting for the module info to be retrieved from the remote modules directory, and waiting for a page reload
4. Clicking the "Download Now" button
5. Waiting for another page reload

...only to see an error message and not to achieve my objective of installing the module.

Instead I want to be alerted right at the start that a $config setting needs to be updated if I am to successfully download and install modules. My suggestion is that the "Get Module Info" button is disabled and an adjacent note is added about the $config setting. And a similar thing for when attempting to update an installed module.

**Comment by jmartsch** [comment]
I agree with Robins comment above

**Comment by ryancramerdesign** [comment]
@Toutouwai I'm not sure when it was added but I think we already have what you describe above. At least I just tried and this is what I get when all the moduleInstall options are disabled:

<img width="739" alt="Screen Shot 2023-08-03 at 11 10 23 AM" src="https://github.com/processwire/processwire-issues/assets/328272/c4b25baa-4fd0-4c93-acc6-215a11320f28">

A similar message appears after clicking the 'check for updates' link on any module.

**Comment by Toutouwai** [comment]
@ryancramerdesign, I took another look at this and the problem occurs when the `directory` option for `$config->moduleInstall` is true but not the `download` option.

When `$config->moduleInstall` features were introduced, the defaults were like this:

![2023-08-04_114920](https://github.com/processwire/processwire-issues/assets/1538852/ddcece20-3c0c-4c4f-933e-5486d8286d10)

In more recent versions the `directory` option also defaults to `debug`, but the original settings can occur when this is in /site/config.php:
```php
$config->moduleInstall('directory', true);
```

Now if `$config->debug` is false the user is presented with the "Add Module From Directory" field, as if this method of module installation will work.

![2023-08-04_114506](https://github.com/processwire/processwire-issues/assets/1538852/23638ccd-7546-48cc-b1ac-8fb75bd4563a)

And you can get to the next screen...

![2023-08-04_114532](https://github.com/processwire/processwire-issues/assets/1538852/6466ba5d-282f-4f09-9284-fe47292e3216)

...but then if you click Download Now you get this:

![2023-08-04_114556](https://github.com/processwire/processwire-issues/assets/1538852/2d8393e2-818a-4897-ae8c-1bc1d95c8090)

So it's like the `directory` option can't actually work unless the `download` option is also true?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I see what you mean, I've pushed a fix for that.

**Comment by Toutouwai** [comment]
Thanks
