### ISSUE TITLE
When creating a new field and forgetting to set Type, Field Label & Name are lost #usability

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#1493]
### Short description of the issue

User is creating a new field and forgetting to set Type, press Enter.
PW says, "InputfieldSelect: Missing required value - Type" and shows an input form without Field Label & Name.

### Expected behavior

1. User gets an error message and the page cannot be submitted when there are mandatory fields.
2. As a service to the user, the reloaded form remembers the user-entered Field Label & Name.

### Actual behavior

Field Label & Name entered by the user are lost.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/129573/147188311-d88c7871-7931-4046-98fb-ff58959a8c34.png)

### Steps to reproduce the issue

1. Create field (`/processwire/setup/field/add`) with field label and name. Forget to set the mandatory Type. Press Enter.
2. Page reloads without the entered label/name - error message is shown - missing Type field is highlighted (`/processwire/setup/field/edit?id=0`).

### Setup/Environment
ProcessWire 3.0.184

**Comment by jlahijani** [comment]
Yea I've noticed this too.  I believe it should preserve the prior selections as well.

**Comment by ryancramerdesign** [comment]
Thanks @klor I've pushed a fix for this.

**Comment by matjazpotocnik** [comment]
@klor, does Ryan's fix work for you? can you close this issue?

**Comment by netcarver** [comment]
@klor Closing. Please comment again if this didn't fix things for you.
