### ISSUE TITLE
$page->editUrl(true) not using https

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1494]
My site is SSL enabled.  I have not touched any of the config settings like `$config->https`.

When outputting `$page->editUrl(true)`, I get `http` not `https`.

**Comment by BernhardBaumrock** [comment]
--removed--

**Comment by jlahijani** [comment]
According to the docs, it's supposed to auto-detect:
https://processwire.com/api/ref/page/edit-url/

**Comment by BernhardBaumrock** [comment]
Sorry that was nonsense :D There is no https setting in editUrl... true simply forces the url to be returned with the schema + host but it will still be auto-detected. Seems there is nothing similar to $page->httpsUrl but maybe I'm missing something...

**Comment by ryancramerdesign** [comment]
@jlahijani The `true` option makes it use scheme + hostname in the returned URL, but it doesn't mean specifically https unless the conditions call for it. It detects which scheme to use (http vs https) from both the admin template and the current request. If the template 'admin' is required to use https, then it'll use https. If the current request is https, it'll also use https. For your case it sounds like you want to go to Setup > Templates > admin > URLs > Scheme/Protocol and choose HTTPS there. If your local/dev environment does not support HTTPS then you can add to your /site/config.php file (dev environment only): 
~~~~~
$config->noHTTPS = true; 
~~~~~
The above will ensure it never uses https in the environment where you've set that config variable. If you share the same config file between dev and live then you could make it conditional:
~~~~~
$config->noHTTPS = strpos($_SERVER['HTTP_HOST'], 'localhost') !== false;
~~~~~

**Comment by jlahijani** [comment]
Hi Ryan,

My site is SSL enabled.

(a): When I do `$pages->get(2)->httpUrl`, I get https.  Good.

(b) When I do `$pages->get(2)->editUrl(true)`, I get http.  Eh...

(c) When I do `$pages->get(2)->editUrl(true)`, AND set the `admin` template to `HTTPS Only`, I get https.  Good.

I guess I would just expect (b) to work like (a) and not have to specifically set the template to `HTTPS Only`.  That's why it seemed like a bug.

Edit: Forgot to add `(true)` to editUrl examples.

**Comment by adrianbj** [comment]
Thanks for reporting - I have been working around this for a long time. It's especially important when you need the full URL when embedding an edit link in an email.

**Comment by ryancramerdesign** [comment]
@jlahijani Thanks for the additional info. For the case "b", if the current scheme is https, the intention is that the returned URL would also be https. It sounds like it isn't. Edit the /wire/core/PageTraversal.php file on dev branch and see line 865:
~~~~~
$url = ($https ? 'https://' : 'http://') . $config->httpHost . $url;
~~~~~
If you change it to the following, does that fix the issue you are seeing?
~~~~~
$url = ($https || $config->https ? 'https://' : 'http://') . $config->httpHost . $url;
~~~~~

**Comment by jlahijani** [comment]
@ryancramerdesign Yes, that did fix it.

**Comment by matjazpotocnik** [comment]
@jlahijani, just for info, this fix is added in https://github.com/processwire/processwire/commit/ee64e114f21bca18844f402fc22dfac893883cc1

**Comment by jlahijani** [comment]
@matjazpotocnik OK.  Good to know.  Closing.
