### ISSUE TITLE
Renaming repeater field doesn't automatically rename its child items parent

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1498]
### Short description of the issue

If you rename a repeater field, the parent page (under Admin > Repeaters) isn't renamed to reflect the new name of the repeater field.

### Expected behavior

The parent page would be renamed (re-titled actually) to match the new name of the repeater field.

### Actual behavior

It isn't renamed.

1. Create a repeater field
2. Create a page which contains the field and populate some items
3. Rename the repeater field
4. Note that `Admin > Repeaters > old_field_name` still exists, instead of `Admin > Repeaters > new_field_name`

While this might seem minor, it's an inconsistency that can be confusing.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign
