### ISSUE TITLE
InputfieldSelector issue with PageListSelect field

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#15]
> Briefly describe the issue.

Trying to select a page by it's PageListSelect value does only present a select box with the first level of children in the InputfieldSelect filter and no way to deviate from those.

Repost of: https://github.com/ryancramerdesign/ProcessWire/issues/1193

> What did you expect to happen?

Either no select at all, a PageListSelect or at least the option to supply a id manually

> Optional: Do you have screenshots/links that demonstrate the issue?

https://www.dropbox.com/s/03etsgly7c0s6e4/Screenshot%202016-10-01%2011.14.13.png?dl=0
https://www.dropbox.com/s/m5ff2m92zrut7no/Screenshot%202016-10-01%2011.14.39.png?dl=0

> What are the steps to reproduce the issue?

1. Setup a page with a PageListSelect field and only a parent limitation to the page field. 
2. Save the page with a chosen page deeper nested below the parent page.
3. Try to filter for just that page.

> Tell us about the setup you experienced the bug in.

* ProcessWire version: 3.0.35

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this
