### ISSUE TITLE
$fieldgroup->fields holds ALL fields, not just the assigned ones

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#150]
### Expected behavior

Say template `home` has only the `title` field:

`$templates->get('home')->fieldgroup` should hold only hold `['title']`

### Steps to reproduce the issue

Loop through all fields of `home`, **presumably** only the ones assigned to `home`:

```php
foreach ($fieldgroups->get('home')->fields as $field) {
    var_export(array(
         'name' => $field->name,
         'hasField' => $fieldgroup->hasField($field->name),
    );
 }
```

But the output shows that `$fieldgroup->fields` holds more than just the `title`
```
array (
  'name' => 'foo_field_not_in_home_but_existent',
  'hasField' => false,
)
array (
  'name' => 'bar_field_not_in_home_but_existent',
  'hasField' => false,
)
array (
  'name' => 'title',
  'hasField' => true,
)
```
So `hasField` is working as expected.

### Setup/Environment

* ProcessWire version: 3.0.47
* PHP version: 5.5.12
* MySQL version: 14.14 Distrib 5.6.17

**Comment by LostKobrakai** [comment]
@ryancramerdesign's answer as code:
`$fieldgroups->get('home')->fields === $fieldgroups->get('home')->wire('fields') === wire('fields')`
