### ISSUE TITLE
Multi-instance results in Cannot redeclare ProcessWire\setting() with `$config->useFunctionsAPI = true;`

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1500]
### Short description of the issue

If you instantiate another PW instance, eg
```
$site = new ProcessWire('/path/to/www/');
```
and you have: '$config->useFunctionsAPI = true;`, you get this error:

Cannot redeclare ProcessWire\setting()

### Expected behavior

Checks should prevent re-declaration of functions.

**Comment by BernhardBaumrock** [comment]
Thx for reporting this. I've had the same issue, so I can confirm this.

**Comment by adrianbj** [comment]
Fortunately I don't actually ever use the functions API so I could easily disable it - not sure why I had it on in the first place.

**Comment by ryancramerdesign** [comment]
@adrianbj Can you give more context about the case? Like are you booting one installation from another, or are you booting from a PHP script independent of either installation?  I use the functions API everywhere, so it is always enabled for me but I've never seen this error on any of my multi-instance setups. One example is processwire.com site, which boots the old modules.processwire.com site with a `new ProcessWire('...')` when you are in the /modules/ section of the site. So I think there must be some combination of factors that I don't know of yet. Can you think of anything?

**Comment by adrianbj** [comment]
I am using Robin's RuntimeOnly field to pull in data from another instance into a dashboard like interface.

Putting this in the runtime only field file caused the error:

```
<?php namespace ProcessWire;

$site = new ProcessWire('/var/www/othersite.com/html', 'https://othersite.com');

**Comment by adrianbj** [comment]
Unfortunately Tracy doesn't work as soon as I instantiate that other instance either so debugging becomes old school :(

**Comment by adrianbj** [comment]
Ok, I just tested without it being in a runtimeonly field. I simply placed `$site = new ProcessWire('/var/www/othersite.com/html', 'https://othersite.com');` in my home.php template file and got the same error. I'll try to keep digging.

**Comment by adrianbj** [comment]
It seems like it's only an issue when both the "calling" site and the "called" site both have the functions API enabled, which makes sense I suppose. Not sure what else to try at the moment.

**Comment by ryancramerdesign** [comment]
Okay thanks, that might be it. I'll experiment some more here.

**Comment by ryancramerdesign** [comment]
@adrianbj I haven't been able to duplicate it yet but I don't think I need to because the solution seems simple. I just pushed an update that should fix it. Thanks.

**Comment by adrianbj** [comment]
Yep, that works, thanks!
