### ISSUE TITLE
In TextformatterVideoEmbed module optional query string doesn't work

### ISSUE THREAD

**Issue by Atlant-Lektanov** [processwire/processwire-issues#1503]
### Short description of the issue

I'm using the code from TextformatterVideoEmbed module, method embedYoutube. Noticed that there is a [code for optional query string](https://github.com/ryancramerdesign/TextformatterVideoEmbed/blob/master/TextformatterVideoEmbed.module#L460) which should put a query string into matches[3] (like ?autoplay=1).

### Expected behavior

The code should put a query string into matches[3] (like ?autoplay=1).

### Actual behavior

It turns out that matches[3] receive an array of empty strings instead of array of query strings.

### Steps to reproduce the issue

1. Create a field with Textarea (Multi-Language) type.
2. Fill it up with two strings of YouTube with query strings, separated by empty strings.
3. Write bd($matches) in the code below [this line](https://github.com/ryancramerdesign/TextformatterVideoEmbed/blob/master/TextformatterVideoEmbed.module#L464).

### Setup/Environment

* ProcessWire version: 3.0.188.

**Comment by matjazpotocnik** [comment]
@Clarity157 it looks like this is the issue with the TextformatterVideoEmbed module? If I'm right, would you mind opening the issue at the https://github.com/ryancramerdesign/TextformatterVideoEmbed/ repository and closing this one? Thanks.

**Comment by Atlant-Lektanov** [comment]
@matjazpotocnik, yes, now I did it. Thank you.
