### ISSUE TITLE
The hookable method mark icon is barely visible in API documentation

### ISSUE THREAD

**Issue by uiii** [processwire/processwire-issues#1504]
### Short description of the issue

The hookable method mark icon is barely visible in API documentation https://processwire.com/api/ref/.

### Expected behavior

The icon is bigger and clearly visible.

### Actual behavior

The icon too small for some reason.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/179219/149125892-d64879d8-7a02-43c5-b335-dd507f977aae.png)

### Steps to reproduce the issue

Go to https://processwire.com/api/ref/pages/ and look up e.g. `$pages->sort(Page $page)` in a list and check the end of the row where should be the "hookable" mark icon

**Comment by ryancramerdesign** [comment]
Thanks @uiii I've pushed a fix for this.

**Comment by netcarver** [comment]
@uiii Hi Richard, closing this now. Post more if it needs re-opening.
