### ISSUE TITLE
Latest dev versions trigger a "moved" event every time user with alternate parent is edited

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1505]
Hey Ryan!

As of recent commit https://github.com/processwire/processwire/commit/fc0db2bb224075e7d6e4105619a2293a5ca4b7a0, "Fix issue processwire/processwire-issues#1495", every time a user page with alternate parent is saved the "moved" event now also gets triggered. In this case it doesn't seem to be intentional, and causes potential issues for anyone assuming that a moved hook means that the page has actually moved from one parent to another — which is not the case here.

In the case of my Process Changelog module this results in page edit no longer being logged (since parent has changed, the module assumes that this is not an edit, but rather a move), and additionally every edit logging a new "moved" event.

(I can't remember the exact reason for the first part — edits where parent is changed not getting logged — but it might've had something to do with trying to identify restore/trash events etc.)

Here's what I've done to test this:

- Enabling alternate user template/parent feature following instructions at https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users.
- I'm using the latest version of ProcessChangelog (1.14.3).
- Before aforementioned commit saving a user page with alternate template and parent was registered as "edited" entry by the Changelog module.
- Starting from said commit, a parent change is registered instead ("moved" hook is triggered).

Difference in hooks can be observed by different data being collected, or placing a call like this in the ProcessChangelogHooks::LogPageEvent() method, right before "check if this event should be logged" row:

```
$this->session->message("Logging event \"$operation\" (event method: $event->method) for $page->url ($page->id)");
```

If you think this is expected behaviour, I can work around it in the Changelog module, but it does seem a bit inconsistent. Parent change may also be related to https://github.com/processwire/processwire-issues/issues/1457, and the fact that even if the user being edited is located under regular page in the page tree, it's still edited via ProcessUser (/processwire/access/users/edit/).

(But of course you already knew that, just trying to be thorough 🙂)

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this issue.

**Comment by teppokoivula** [comment]
Thanks, Ryan — works as expected now!
