### ISSUE TITLE
WireHttp broken in 3.0.192

### ISSUE THREAD

**Issue by csaggo** [processwire/processwire-issues#1506]
### Short description of the issue

WireHttp post Method does not trasmit parameters in latest version

### Expected behavior

Post Parameters are not sent.

### Actual behavior

Request is sent without parameters.

### Steps to reproduce the issue

`$response = $http->post("https://www.google.com/recaptcha/api/siteverify", [
            "secret" => setting("g-recaptcha")["secret"],
            "response" => $token,
        ]);`

This is a recaptcha verification. Google replies with "missing-input-secret". Rolling back the ProcessWire version resolved the issue.

### Setup/Environment
*  ProcessWire version: 3.0.192

**Comment by ryancramerdesign** [comment]
Thanks @csaggo I've pushed a fix for this issue.

**Comment by csaggo** [comment]
works for me in 3.0.193
