### ISSUE TITLE
findOne() finds nothing while find() does

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1507]
### Short description of the issue

When the template subject to the search is access controlled with view denied to the current user,
and even though the pages are published and not hidden,
find("template=test, check_access=0") returns (rightfully) the existing pages, 
but
findOne("template=test, check_access=0") **finds nothing** and returns NullPage.

findOne("template=test, include=all") finds the pages, but this is "overkill" because the pages are published and not hidden.

### Expected behavior

findOne("template=test, check_access=0") should find something, just like the corresponding find().

Please advise if more context is needed to reproduce the issue.

### Setup/Environment

PW 3.0.190
PHP 8.0

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed a fix for this issue

**Comment by er314** [comment]
All right, fixed, thanks.
