### ISSUE TITLE
Error: Undefined index: template_id on line: 473 in wire/modules/Fieldtype/FieldtypePageTable.module 

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1509]
### Short description of the issue

When calling `$field->getExportData()` on a PageTable field that is not assigned to a template an error is thrown:
`Error: Undefined index: template_id on line: 473 in wire/modules/Fieldtype/FieldtypePageTable.module`

### Expected behavior

Array of field data is returned

### Actual behavior

Error thrown

### Suggestion for a possible fix
change line 473 in FieldtypePageTable.module to read:

`if(isset($data['template_id']) && is_array($data['template_id'])) {`

### Steps to reproduce the issue

1. create a field of type FieldtypePageTable, Do not assign it to a template
2. go to Fields->Export, choose that field and click on export
3. or do `$fields->get('fieldname')->getExportData()`

### Setup/Environment

* ProcessWire version: 3.0.192
* (Optional) PHP version: 7.4

**Comment by gebeer** [comment]
I checked the field settings and there were no templates assigned in the Details tab. This explains the error thrown since templates is a required value when you create that field. 
But still it might be good to have the extra check in the code for edge cases like mine, where the field had no templates assigned for whatever reason.

**Comment by ryancramerdesign** [comment]
Thanks @gebeer I've pushed a fix for this issue.
