### ISSUE TITLE
Page::is() and PageComparison::is() returning integer instead of boolean

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1510]
### Short description of the issue

Page::is() is documented with `@return bool`, yet it can currently return an integer. This happens in a few cases, including if status is provided as an integer, since in PageComparison::is() `$is = $page->status & $status` — which returns an integer — is returned directly, with no typecasting: https://github.com/processwire/processwire/blob/dev/wire/core/PageComparison.php#L39.

This behaviour was introduced in 3.0.149, specifically this commit: https://github.com/processwire/processwire/commit/20be0c7fd5a8937f8c052e479a082a0a975cc41d.

In the case of Process Changelog this issue was causing extraneous status change events to be logged, since the module used strict comparison with current status (`if ($page->is(Page::statusHidden) !== (bool) ($page->statusPrevious & Page::statusHidden))`).

### Expected behavior

Page::is() and PageComparison::is() should return boolean values.

### Actual behavior

Page::is() and PageComparison::is() may return a boolean or an integer.

### Optional: Suggestion for a possible fix

Typecast $is to boolean where appropriate, or alternatively at the end of method to prevent future issues. Latter might actually be a safer bet, since even now there are a few of these cases in this method?

Loosely related, but implementing strong typing (at least where it is unlikely to break backwards compatibility) would make it harder to miss issues like this one. Of course that'd mean dropping support for PHP 5 — which is another topic entirely :)

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this issue.

**Comment by teppokoivula** [comment]
Thanks, Ryan!
