### ISSUE TITLE
Possible findRaw() bug with multiple subfields option

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1511]
### Short description of the issue

Sorry for not following protocol, but I think an image explains this best. You can see that nothing is returned when using the "multiple subfields" approach as described here: https://processwire.com/blog/posts/find-faster-and-more-efficiently/#finding-faster-with-raw-data

![image](https://user-images.githubusercontent.com/871211/150665044-a1486c27-e764-4864-961b-2066d005c3d2.png)

I know this might seem like another issue, but if you look at this version where I am trying to get the `cause_of_death` from the `subscriber` - both of which are page reference fields. It works if I don't have the `title` on the end, but when it's there, you can see from the exception that it's trying to get `cause_of_death_title` rather than `cause_of_death.title`

![image](https://user-images.githubusercontent.com/871211/150665123-c918f24f-93c4-4353-8628-99ae81b36161.png)

Perhaps these dumps also help - you can see what the values of `$fieldName` are in PagesRaw.php
![image](https://user-images.githubusercontent.com/871211/150665179-eab15062-0afd-4ff9-b7be-42117d87a6b9.png)

Let me know if you need anything else to reproduce. Thanks!

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks Adrian, I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Perfect - thanks @ryancramerdesign for the quick fix.
