### ISSUE TITLE
Module upgrade warnings not correct

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1513]
### Short description of the issue

I was getting the error in the screenshot below, but those config settings were already applied. The issue was actually that the /site/modules directly had the wrong owner, so the logic inside ProcessModuleInstall.php is not flowing correctly.

### Expected behavior

Error should correctly report the: "Make sure your site modules directory (/site/modules/) is writeable for PHP." option.

### Actual behavior

It incorrectly shows what's in the screenshot.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/150702999-029343c3-cec2-4860-9d25-2a2dd8b744c7.png)

### Steps to reproduce the issue

1. Make sure $config file has the required `$config->moduleInstall()` settings.
2. Make site/modules not writable by PHP
3. Try to update a module from within the admin

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - but I am curious why you went with:
"It must be made writable to ProcessWire before you can enable this module installation option." vs the "Make sure your site modules directory (/site/modules/) is writeable for PHP." wording which exists in the `canUploadDownload()` method.

Obviously not terribly important so ignore me if you want, but I feel like referencing PHP vs ProcessWire is more correct and also just consistent with the other message which is for the same situation.
