### ISSUE TITLE
Repeater in FieldSetPage

### ISSUE THREAD

**Issue by Jehfen** [processwire/processwire-issues#1514]
### Short description of the issue

When using a repeater in the new FieldSetPage, the repeater bar is not rendered nicely.

### Expected behavior

It should look like in a normal repeater.

### Actual behavior

The title bar is "chunky".

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/37275559/151021735-5fd29b14-2cc6-4310-a207-fd7e6ca3e189.png)

top right: repeater in FieldSetPage, bottom right: normal repeater

### Setup/Environment

* ProcessWire version: latest beta
* (Optional) PHP version: 7.4
* (Optional) MySQL version: Maria 10.6

**Comment by matjazpotocnik** [comment]
@Jehfen, I can't replicate:

![image](https://user-images.githubusercontent.com/7663992/168310711-e9b46c68-64a5-480f-a8f1-ded611304008.png)

**Comment by matjazpotocnik** [comment]
@Jehfen Closing. Please comment again to reopen.
