### ISSUE TITLE
Minor docs issue(s) on the Configuration paths and URLs (Paths class) page

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1515]
Couple of observations for https://processwire.com/api/ref/paths/:

- Links look like markdown, but still work. Minor thing, but probably not intentional.
- This may or may not be intentional, but looks a bit weird: under the heading "Paths only" there are only $urls listed. Probably just related to the way this pge is generated, but it's kind of confusing, especially since the description there states that these are only useful as paths :)

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula neither was intentional and I have corrected both issues. For the "Paths only" thing, I had to choose a var name common to all of them, so went with just `$var` and added a paragraph above the table explaining what it means.
