### ISSUE TITLE
Documentation search showing json response instead of page with results

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#1516]
### Short description of the issue

Sometimes while using the search bar in the processwire.com website, a json response seems to show up right after pressing return to execute the search. I am having a hard time spotting the exact conditions on how it happens but it should be fairly quick to try it out.

Tested on Chrome and Firefox and got the same issue reproduced.

### Optional: Screenshots/Links that demonstrate the issue

![search_issue](https://user-images.githubusercontent.com/7674567/151588097-27143ede-968d-4282-9a04-135a82ab8068.gif)

**Comment by matjazpotocnik** [comment]
@elabx, this should be fixed: https://github.com/processwire/processwire-issues/issues/1823#issuecomment-2494183074
