### ISSUE TITLE
Attempt to read property "language_files" / "language_files_site" on null

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1517]
### Short description of the issue

I see this if I view `/setup/language-translator/`

### Expected behavior

No warning.

### Actual behavior

This warning is shown

![image](https://user-images.githubusercontent.com/871211/151611833-be71b0f6-045a-42ed-bd02-f41e74bc8c89.png)

### Optional: Suggestion for a possible fix

I don't honestly know if this is worth worrying about - I don't think many people will visit this page without URL parameters like `add/?language_id=1353` so feel free to close this if you want.

**Comment by ryancramerdesign** [comment]
> I don't honestly know if this is worth worrying about - I don't think many people will visit this page without URL parameters like add/?language_id=1353 so feel free to close this if you want.

True, but since you posted it and since it's a simple fix, why not. :)
