### ISSUE TITLE
Inputfield dependencies feature does not distinguish between zero and empty

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1518]
### Short description of the issue

If you use InputfieldInteger in a module config then a distinction is made between an empty value and a value of 0 - you can save the field value as either of these.

But if you have another inputfield with a showIf dependency on the integer field then no distinction is made between empty and 0.

```php
$f = $modules->get('InputfieldInteger');
$f->name = 'number';
$f->label = 'Number';
$f->inputType = 'number';
$f->value = $this->number;
$inputfields->add($f);

$f = $modules->get('InputfieldText');
$f->name = 'text';
$f->label = 'Text';
$f->value = $this->text;
$f->showIf = "number!=''";
$inputfields->add($f);
```

![showif](https://user-images.githubusercontent.com/1538852/151717820-d387c483-0417-4e7c-8072-54e7d44e6f86.gif)

### Expected behavior

The showIf rule shown above should evaluate to true when the field value is anything other than empty.

### Setup/Environment

* ProcessWire version: 3.0.193

**Comment by Toutouwai** [comment]
Another way this issue manifests is if you want to show a field when another field's value is exactly 0 (but not empty).

```php
$f->showIf = "number=0";
```

**Comment by matjazpotocnik** [comment]
@ryancramerdesign @Toutouwai I traced this to the matchValue() function in inputfields.js. If the integer field value is "0" this line returns false indicating no match:

```js
case '!=': if(value != conditionValue) matched++; break;
```

> If the two operands are not of the same type, JavaScript converts the operands then applies strict comparison. If either operand is a number or a boolean, the operands are converted to numbers if possible; else if either operand is a string, the other operand is converted to a string if possible.

```
console.log(0 == '0');  // true
console.log(0 == '');   // true
```

In my testing it helps if we use strict comparison:

```js
case '=': if(value === conditionValue) matched++; break;
case '!=': if(value !== conditionValue) matched++; break;
```

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai @matjazpotocnik I've pushed the fix suggested by Matjaz.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, thank you for the fix. Please update the version info of the admin theme(s) so that the new version of inputfields.js is loaded. Cachebusting issue is nicely described in https://github.com/processwire/processwire-issues/issues/1791 and (a bit vague description) https://github.com/processwire/processwire-issues/issues/1752

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I have updated the URLs for cache busting.

**Comment by matjazpotocnik** [comment]
Ryan, thank you. @Toutouwai, based on your thumb up, I'll close this issue, but please reopen if it's not fixed. Thx!
