### ISSUE TITLE
Out-of-memory error when two pages mutually connected by 'single' Page field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#152]
### Short description of the issue

When two pages are mutually connected by 'single' page fields (i.e. Page A has Page B selected in a single Page field and vice versa), an out-of-memory error occurs: 

> Fatal error: Allowed memory size of xxxxxx bytes exhausted...

If either or both Page fields are 'multiple' fields then no error occurs.

### Expected behavior

Two pages may be mutually connected by 'single' page fields without errors.

### Steps to reproduce the issue

1. Create two templates: template_a and template_b. Create template files for each template (these may be empty PHP files - it makes no difference).
2. Create two Page fields (page_field_a and page_field_b) and set "Dereference in API as" to either of the "Single page" options. Add one field to each template.
3. Create two pages (page_a and page_b), one using each template. In page_a select page_b in the Page field and vice versa.
4. View either page on the front end and note the out-of-memory error.

### Setup/Environment

* ProcessWire version: 3.0.45
* (Optional) PHP version: 7

**Comment by adrianbj** [comment]
Is this at all related to: https://github.com/ryancramerdesign/ProcessWire/issues/663

I know we are talking about different inputfields, but maybe it is still related and I don't think that issue is actually fully dealt with - maybe it has been fixed since thought - it's a while ago now!

**Comment by LostKobrakai** [comment]
I know the issue is the same on 2.7.3, so it's probably not a recently introduced issue.

**Comment by ryancramerdesign** [comment]
I don't know of a way we can support circular references like this between pages at present. The same goes for a Page referencing itself, though PW is at least able to detect and cancel that scenario, so that it doesn't get committed to the DB. But I don't know of an efficient way to detect the circular reference mentioned here. If it's possible for us to support this someday as a feature we will, but until then I would avoid creating these types of circular references between page fields if possible.

**Comment by Toutouwai** [comment]
> I don't know of a way we can support circular references like this between pages at present. 

Circular references work fine if either of the Page fields is a 'multiple' field - just not when they are both 'single' fields. Why should it work with 'multiple' fields but not 'single'?

**Comment by netcarver** [comment]
@ryancramerdesign Did Robin's insight help at all?

@Toutouwai Do you know if this is still an issue in more recent versions of PW?

**Comment by adrianbj** [comment]
@netcarver - there is a more detailed discussion here: https://github.com/processwire/processwire-issues/issues/572

**Comment by netcarver** [comment]
@adrianbj Thank you Adrian. Does that discussion include this issue? If so, I'd like to close this one to allow that to become the focus.

**Comment by adrianbj** [comment]
@netcarver - I think it probably does, but I would suggest that @Toutouwai clarify that for sure.

**Comment by Toutouwai** [comment]
I'm not sure that the problem is exactly the same between these two open issues, but I think there's a good chance that a solution to #572 will also solve this issue. And if not I can reopen.
