### ISSUE TITLE
Multilanguage URL-field can not be used in custom fields in file/image fields

### ISSUE THREAD

**Issue by weberhofer** [processwire/processwire-issues#1520]
### Expected behavior

The multilanguage URL field should be visible and editable in any of the pages incorporating the Image-Field.

### Actual behavior

The field is not visible. There are no messages logged. Switching to the non-multilingual URL makes the field appear.

### Setup/Environment
* ProcessWire version: 3.0.193 dev
* php7-7.4.6
* mariadb-10.5.13

**Comment by ryancramerdesign** [comment]
@weberhofer Not all fieldtypes are compatible with usage in file/image fields. Though I'm not aware of multi-language URL is one that fits that or not, so you'd want to check in Modules > Configure > FieldtypeFile and see which Fieldtypes you have enabled to be allowed in file/image custom fields. If you see an option to enable the field you want to use, check the box and save.

**Comment by matjazpotocnik** [comment]
@weberhofer Multilanguage URL is not 100% compatible, but it works with file and image fieldtype, at least in the admin. Can you verify and close this issue?

**Comment by matjazpotocnik** [comment]
@weberhofer Closing. Please comment again to reopen.
