### ISSUE TITLE
2FA-suggestion notification should be dismissable for session duration

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1522]
### Short description of the issue

The [2FA-suggestion notification](https://processwire.com/blog/posts/pw-3.0.159/) "Strongly suggest two-factor authentification for these roles" should be dismissable for the duration of the session.

### Expected behavior

Once you close the the notification it should stay close for the duration of the session.

### Actual behavior

The notification is reappearing for as long as you don't have setup 2FA for your account.

### Steps to reproduce the issue

1. Active the 2FA-suggestion notification in the ProcessLogin settings.
2. Don't have 2FA setup on your account.
3. Login into your account.
4. Dismiss the notification.

Regards, Andreas

**Comment by ryancramerdesign** [comment]
@designconcepts The purpose of this particular notification is to be insistent and annoying. I think it would probably just get ignored otherwise. But it is something that you can turn on or off in your settings.

**Comment by designconcepts** [comment]
@ryancramerdesign Thank you for the explanation. I knew that this notification should be annoying, but I didn't thought that it should annoy you on every page, even if dismissed once. But if that is on purpose, I will get used to it. 😀

> But it is something that you can turn on or off in your settings.

Do you mean for everybody in the ProcessLogins settings or is it possible for users in their settings? Because I cant' find an option in the user settings.
