### ISSUE TITLE
Since PW 3.0.189 user is not redirected to URL when viewing an access controlled page

### ISSUE THREAD

**Issue by didierbrouwers** [processwire/processwire-issues#1527]
### Short description of the issue

Since PW 3.0.189 Redirecting to another URL (option C) at _Template Settings > Access_ does not redirect the user to the given URL (e.g. '/no-access/ ?pid={id}') but shows a 404 Page Not Found.

### Expected behavior

When a user has no access to a page he should be redirected to the page URL entered under:
_Template Settings > What to do when a user... > Redirect to another URL (option C)_

### Actual behavior

When a user has no access to a page he will not be redirected. Instead a 404 Page Not Found is displayed.

Tracy Debugger shows the following error: 
`PHP Warning: Attempt to read property "id" on string in .../wire/core/PagesRequest.php:437`

When a **page ID** is entered under _Template Settings > What to do when a user... > Redirect to another URL (option C)_ the user will be redirected to the correct page.

### Setup/Environment

* ProcessWire version: 3.0.189 dev
* PHP version: 8.0.8
* MySQL version: 5.7.34

**Comment by ryancramerdesign** [comment]
Thanks @didjee I've pushed a fix for this issue, can you confirm it also fixes it there?

**Comment by didierbrouwers** [comment]
@ryancramerdesign I can confirm that this issue is fixed now. Thanks!
