### ISSUE TITLE
WireArray::sort float issue

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1528]
### Short description of the issue

```php
$arr = new WireArray();
$arr->add((new WireData())->setArray(['int'=>200, 'float'=>2]));
$arr->add((new WireData())->setArray(['int'=>199, 'float'=>1.99]));
$arr->add((new WireData())->setArray(['int'=>100, 'float'=>1]));
$arr->add((new WireData())->setArray(['int'=>201, 'float'=>2.01]));
$arr->add((new WireData())->setArray(['int'=>300, 'float'=>3]));

db($arr->sort('float', SORT_NUMERIC)->each('float'), 'float = correct');
db($arr->sort('-float', SORT_NUMERIC)->each('float'), '-float = wrong');
db($arr->sort('float', SORT_NUMERIC)->reverse()->each('float'), 'float reverse = wrong');
```

![img](https://i.imgur.com/WgnxgKi.png)

Am I missing something?

**Comment by BernhardBaumrock** [comment]
Clear case of RTFM :D
https://processwire.com/api/ref/wire-array/sort-flags/

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I can't seem to duplicate it here yet. There were some improvements to the WireArray sort methods  a few weeks ago so I'm wondering if maybe this one got fixed along the way inadvertently. Are you still experiencing the error in the current dev branch? Here's the result I get when testing: 
~~~~~
$arr = WireArray([
  WireData([ 'int' => 200, 'float' => 2 ]),
  WireData([ 'int' => 199, 'float' => 1.99 ]),
  WireData([ 'int' => 100, 'float' => 1 ]),
  WireData([ 'int' => 201, 'float' => 2.01 ]),
  WireData([ 'int' => 300, 'float' => 3 ])
]);

print_r($arr->sort('float', SORT_NUMERIC)->each('float'));
print_r($arr->sort('-float', SORT_NUMERIC)->each('float'));
print_r($arr->sort('float', SORT_NUMERIC)->reverse()->each('float'));
~~~~~
Result:
~~~~~
Array
(
    [2] => 1
    [1] => 1.99
    [0] => 2
    [3] => 2.01
    [4] => 3
)
Array
(
    [4] => 3
    [3] => 2.01
    [0] => 2
    [1] => 1.99
    [2] => 1
)
Array
(
    [0] => 3
    [1] => 2.01
    [2] => 2
    [3] => 1.99
    [4] => 1
)
~~~~~

**Comment by BernhardBaumrock** [comment]
Interesting... It does indeed work correctly on another installation...

I tried upgrading PW to see if it makes a difference. It does not. On the working instance it works even with old and new PW version. On the "broken" installation it does not work with each 3.0.194 and 195

Any ideas how I could debug this?

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.195|
|PHP|7.4.26|
|Webserver|Apache/2.4.51 (Debian)|
|MySQL Server|5.5.5-10.3.32-MariaDB-1:10.3.32+maria~focal-log|
|MySQL Client|mysqlnd 7.4.26|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|600 (changeable)|
|max_input_nesting_level|64|
|max_input_time|-1|
|max_input_vars|3000|
|memory_limit|1024M|
|post_max_size|100M|
|upload_max_filesize|100M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.0|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.11|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG||
|PDF|1|
|WebP|1|
</details>

---

Working setup:
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.195|
|PHP|7.4.26|
|Webserver|Apache/2.4.51 (Debian)|
|MySQL Server|5.5.5-10.3.32-MariaDB-1:10.3.32+maria~focal-log|
|MySQL Client|mysqlnd 7.4.26|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|600 (changeable)|
|max_input_nesting_level|64|
|max_input_time|-1|
|max_input_vars|3000|
|memory_limit|1024M|
|post_max_size|100M|
|upload_max_filesize|100M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.0|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.11|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG||
|PDF|1|
|WebP|1|
</details>

**Comment by BernhardBaumrock** [comment]
I just tried disabling all modules via Tracy Module Disabler and get the same results. Also on the live server I get wrong sorting on that installation...

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Could it be due to locale settings?

**Comment by BernhardBaumrock** [comment]
That's it!!! Every site that has the german language pack installed will return false results!

![image](https://user-images.githubusercontent.com/8488586/164724327-6b65efd7-e8ce-4fb8-8403-a5e8a8272dac.png)

![image](https://user-images.githubusercontent.com/8488586/164724482-b5850ef4-654b-4cdb-a16f-e175251b3e81.png)

https://github.com/jmartsch/pw-lang-de/archive/refs/heads/main.zip

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Interesting, thanks for testing and confirming. Now the question is: why does the locale matter for sorting in this particular case... I'm not yet clear on that, but will have to investigate.

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock do you have translated "C" as "de_DE.UTF-8"? Can you remove that translation and retest?

**Comment by BernhardBaumrock** [comment]
@matjazpotocnik no I just installed the module and did not change any settings. Can you reproduce this?

**Comment by matjazpotocnik** [comment]
No, I can't, it's working here. I'm on windows if that matters and don't have language pack installed. I think that language pack has the translation already included.

**Comment by BernhardBaumrock** [comment]
Well the issue is that with installed language pack the sorting is false. So if you don't have the language pack installed of course there is no issue...

Can you confirm this issue @jmartsch ?

**Comment by matjazpotocnik** [comment]
Ok, I installed the german language pack and still can't duplicate
![image](https://user-images.githubusercontent.com/7663992/164886495-a87d8eba-b84d-45e3-a792-51bc433e1fce.png)

**Comment by BernhardBaumrock** [comment]
Thx @matjazpotocnik that is interesting!! I'll try to check different locale settings and see how that affects it

**Comment by jmartsch** [comment]
> Well the issue is that with installed language pack the sorting is false. So if you don't have the language pack installed of course there is no issue...
> 
> Can you confirm this issue @jmartsch ?

I did not check it, but this has to be a problem with your locale setting. Locales modify how PHP sorts strings and numbers. Maybe take a look at the collator class and also this blog post which explains it a little: https://tommcfarlin.com/sort-array-by-locale-in-php/

But I think changing your locale setting (C setting) in ProcessWire might be the solution. Please remember, that a locale has to be installed on the operating system to work. There is a script from me somewhere in the PW forums, to check which locales are installed on your machine.

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock what's the status of this issue? Would you like to close it or leave it open?

**Comment by BernhardBaumrock** [comment]
Thx @matjazpotocnik I've just tested on a current installation with german language pack and I can't reproduce the issue any more, so I'll close it.
