### ISSUE TITLE
505 HTTP Version Not Supported: HTTP Version Not Supported (ProcessWireUpgradeCheck)

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1529]
### Short description of the issue

I am getting this almost every time and on every site when running the PWUpgrades module.

### Expected behavior

No error

### Actual behavior

I get this error. Sometimes it only ends up listing updates to the PW core, but other times, all the modules are still listed, but it takes a long time to load.

Let me know if you can't reproduce.

**Comment by ryancramerdesign** [comment]
I'm also getting an error. But only on the first instance. Once I hit the
"refresh" button, it is successful. I'll experiment here next week to
figure out why.

**Comment by adrianbj** [comment]
FYI - sometime a refresh works for me, but not always.

**Comment by ryancramerdesign** [comment]
@adrianbj I'm off this week so haven't gone that far into it just yet, but so far I can't seem to duplicate it anymore. I never did see that it was a 505 error, just a generic 'http request failed' error message. I got it the first time on two different sites, then no longer, no matter how many times I refresh. I've tried another new installation and not getting errors anymore at all. I'm also curious if it's a client side or server side issue, as 505 is not one I've come across before. If you are still able to duplicate the issue, could you try replacing the code in ProcessWireUpgradeCheck.php around line 268 there is this:
~~~~~
if(!is_array($data)) {
  $error = $http->getError();
  ...
}
~~~~~
Could you try replacing that block of code above with this below? If so, I'm interested in seeing the full error message if you are able to copy/paste into here (also including the URL that it shows). Thanks. 
~~~~~
if(!is_array($data)) {
  $error = $http->getHttpCode(true) . " - " . $http->getError();
  $this->error("$error - URL: $url"); 
  return $versions;
}
~~~~~

**Comment by adrianbj** [comment]
I can't see the error today either. I saw this error everyday for the last week from multiple sites, so I know it was real. I'll keep an eye out and get the full error if I see it again.

**Comment by ryancramerdesign** [comment]
@adrianbj Interesting, now I'm wondering if something was going on with the server. It's all behind a load balancer, which occasionally adds a strange twist.

**Comment by adrianbj** [comment]
I haven't seen this in a few days, so I'll close for now.
