### ISSUE TITLE
Selector parsing fails on field=",value"

### ISSUE THREAD

**Issue by init2null** [processwire/processwire-issues#153]
### Short description of the issue

Selector fails when quoted value starts with a comma. For instance, _title=",ABC"_ fails.

### Expected behavior

Tries to match quoted value exactly.

### Actual behavior

```
Error: Uncaught ProcessWire\WireException: Unknown Selector operator: '' -- was your selector value properly escaped? in wire/core/Selectors.php:394
Stack trace:
#0 wire/core/Selectors.php(437): ProcessWire\Selectors->create('A', '', '')
#1 wire/core/Selectors.php(159): ProcessWire\Selectors->extractString('')
#2 wire/core/Selectors.php(145): ProcessWire\Selectors->setSelectorString('title=",A"')
#3 wire/core/PagesLoader.php(217): ProcessWire\Selectors->init('title=",A"')
#4 wire/core/Pages.php(232): ProcessWire\PagesLoader->find('title=",A"', Array)
#5 [internal function]: ProcessWire\Pages->___find('title=",A"')
#6 wire/core/Wire.php(376): call_user_func_array(Array, Array)
#7 ... (line 394 of wire/core/Selectors.php) 
```

### Steps to reproduce the issue

1. $pages->find('title=",A"');

### Setup/Environment

* ProcessWire version: 3.0.48
* (Optional) PHP version: 7.0.8

**Comment by LostKobrakai** [comment]
It seems like leading and trailing commas are not allowed even with quotes: https://github.com/processwire/processwire/blob/master/wire/core/Sanitizer.php#L1521

**Comment by LostKobrakai** [comment]
Also you can just let `$selectorValue = $sanitizer->selectorValue($value)` take care of making sure your value can be used in a selector.

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed .
