### ISSUE TITLE
Object of class ProcessWire\SelectableOptionArray could not be converted to int in /wire/core/WireArray.php:1429

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1530]
### Short description of the issue

Since upgrading to 3.0194 where `sort()` was updated, I am getting this warning.

### Expected behavior

No error

### Actual behavior

The double quotes in the `else if(ctype_digit("$key"))` check in the `stableSort()` method is converting the SelectableOptionArray to a string with the ID of the selected option. This causes the ctype_digit check to return `true` and therefore it tries to cast the SelectableOptionArray object as an integer, which is what causes the error. 

I am running PHP 8 so perhaps in older versions, it allows this by internally casting as a string before the integer casting?

* ProcessWire version: 3.0194
* (Optional) PHP version: 8.015

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks!
