### ISSUE TITLE
3.0.194 found 2 PHP-8 deprecation warnings

### ISSUE THREAD

**Issue by horst-n** [processwire/processwire-issues#1531]
### Short description of the issue
I used **PW 3.0.194** against **PHP 8.1.12** and got two deprecation warnings

a) ```Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ... wire-3.0.194\core\PagesPathFinder.php on line 1928```

b) ```Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ... wire-3.0.194\modules\LanguageSupport\LanguageSupportPageNames.module on line 515```

### Optional: Suggestion for a possible fix
I could fix these with 

a) ```1928:			if(is_null($segment) || !strlen($segment)) continue;```

b) ``` 515:			if($name == Pages::defaultRootName || is_null($name) || !strlen($name)) return '/';```

**Comment by horst-n** [comment]
I found some more. 

The following belong to **PW core**:

``` 
Deprecated: Automatic conversion of false to array is deprecated in ... wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module on line 141 
```
possible fix:
```
  78:				static protected $isReady = false;  // change to null for PHP 8.1+ ?? 
```

----------

``` 
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in wire-3.0.194\modules\Inputfield\InputfieldMarkup.module on line 93 
```

```
   93:		if(is_string($markupText) && strlen($markupText)) { 
```

----------

The following belongs to **RepeaterMatrix**:
``` 
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in ... site\modules\FieldtypeRepeaterMatrix\InputfieldRepeaterMatrix.module on line 102 
```
possible fix:
```
 100:			if(!$label) $label = $this->field->get("matrix{$type}_label");
 101:			if(!$label) $label = $this->field->get("matrix{$type}_name");
 102:			$out = str_replace('{matrix_label}', $label, $out);
to
 100:			if(!$label) $label = $this->field->get("matrix{$type}_label");
 101:			if(!$label) $label = $this->field->get("matrix{$type}_name");
 102:           if(is_null($label)) $label = '';  // add this additional check
 103:			$out = str_replace('{matrix_label}', $label, $out);
```

----------

And the last one for this time belongs to **FieldtypeCombo**:
``` 
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in ... site/modules/FieldtypeCombo/ComboSchema.php on line 224 
```
possible fix:
``` 
 224:			$type = strtolower($comboSettings->get($prefix . 'type'));
to
 224:			$type = is_null($comboSettings->get($prefix . 'type')) ? '' : strtolower($comboSettings->get($prefix . 'type'));
 ```

**Comment by matjazpotocnik** [comment]
> b) Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ... wire-3.0.194\modules\LanguageSupport\LanguageSupportPageNames.module on line 515

> Deprecated: Automatic conversion of false to array is deprecated in ... wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module on line 141

Horst, thanks for the report. Ryan, those two are already reported in https://github.com/processwire/processwire-issues/issues/1467#issuecomment-1030754816

**Comment by kixe** [comment]
@horst-n 
Could this be merged in #1467 and closed?

**Comment by ryancramerdesign** [comment]
@horst-n Thanks, I've pushed a fix for these and have also updated the matrix & combo modules, so those will appear in the next versions of those as well.

**Comment by horst-n** [comment]
Thanks @ryancramerdesign !
