### ISSUE TITLE
$templates->getAll() does not return all templates

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1532]
### Short description of the issue

Since recent core changes, `$templates->getAll()` does not return all templates, contrary to what the method name implies.

PW 3.0.184
![2022-02-16_164353](https://user-images.githubusercontent.com/1538852/154192387-da8ec58d-b397-4517-9495-9d9b46ac2aab.png)

PW 3.0.194
![2022-02-16_164725](https://user-images.githubusercontent.com/1538852/154192556-0accb9d8-9fce-45e3-9361-b9d15def8de0.png)

This breaks at least one module of mine that expects the previous behaviour. If the `getAll()` method no longer returns all templates, what is the recommended way to get all templates?

### Setup/Environment

* ProcessWire version: 3.0.194

**Comment by Toutouwai** [comment]
This seems to do it:
```php
$templates->find('');
```

Maybe Templates::getAll() should do this internally so the method name continues to make sense?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
