### ISSUE TITLE
No new pages created from the field for non-superusers since 3.0.191

### ISSUE THREAD

**Issue by zumpixel** [processwire/processwire-issues#1533]
### Short description of the issue
Since the commit of ["Add a $pages->new() API method..." on December 10, 2021](https://github.com/processwire/processwire/commit/f4592435aabe1c79890b328a15dac3814a827df0), it is no longer possible for non-superusers to create a new page from a field. Creating the new page in the page tree is possible for the user.

### Expected behavior
All users with appropriate rights can create pages from a field

### Actual behavior
An error message "No access to add basic-page pages to / - pageref" appears - where pageref is the page reference field.

### Setup/Environment
- Processwire 3.0.194
- PHP 7.4.21
- MySQL 5.7.34

**Comment by BernhardBaumrock** [comment]
Same here: https://processwire.com/talk/topic/26801-inputfieldpage-non-super-user-cannot-add-page-from-within-field/

**Comment by ryancramerdesign** [comment]
Thanks @zumpixel @BernhardBaumrock I've pushed a fix for this issue.

**Comment by zumpixel** [comment]
Thanks @ryancramerdesign, works perfectly now!
