### ISSUE TITLE
Superusers can be locked out of admin by ProcessLogin setting

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1534]
### Short description of the issue

Not sure if this should be considered a bug or just a case of "be more careful".

But if you set the "Login type" setting of ProcessLogin to "Email address" and the "email" field has the "Unique" setting checked then any/all superusers that do not have an email address defined will be unable to log into the PW admin.

Seems like one of the following would be good:

1. The "unique" option cannot be enabled for "email" if some users do not have an email address defined (an empty value isn't exactly unique)
2. The "Email address" option for ProcessLogin cannot be selected if any (or all?) superusers do not have an email address defined.
3. If disabling these options is not favoured, then at least a prominent warning could be shown in the cases above.

After being locked out I resolved the problem by directly editing the "allowEmail" setting for ProcessLogin in the database.

### Setup/Environment

* ProcessWire version: 3.0.194

**Comment by ryancramerdesign** [comment]
@Toutouwai There was already a note about the 'unique' requirement in the notes for the "Login type" field, but I have updated it so that the email options are now disabled completely if the requirements aren't met.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign.

But there is still the problem that the "unique" option can be enabled (and therefore the email login option can be enabled) when one or more users don't have an email address defined. So if the superuser doesn't have an email address defined then the lockout problem can still occur.

When attempting to enable the unique option, if there are multiple users with the same email address defined then the unique option is prevented and this notice is shown:
![2022-03-05_105752](https://user-images.githubusercontent.com/1538852/156847783-8289f933-62de-4b87-af43-e72ecc523962.png)
Could the same thing be done when multiple users have no email address defined? The empty values are also non-unique rows.

And even then, if a superuser was the one user without an email address defined then the lockout could still occur. So maybe the email address option in ProcessLogin could specifically check for superusers without email addresses?

**Comment by ryancramerdesign** [comment]
@Toutouwai @matjazpotocnik The ProcessLogin module already verifies that all superusers have an email address populated before it will let you make the change. I'm not sure if this is something I added with the previous update or sometime later, but just wanted you to know it was there.
