### ISSUE TITLE
findMany very slow

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1535]
### Short description of the issue

I am not sure if this is a bug or not, but I am getting very slow processing times for findMany vs find.

### Expected behavior

It should be no slower in most cases.

### Actual behavior

As you can see from several examples below, it is very slow, even when limited to 200. And in some of the examples, I am not even iterating through the results. From what I can tell, a regular `find` with an `uncacheAll()` is much faster and has no memory issues.

I have tried this on multiple servers with different PW installs and they all seem to experience the problem. I am seeing this on PHP 7.3 and 8.0.

Please let me know if you can't reproduce and I'll try to find some more information for you.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/155153133-1d15bead-1dbb-4f27-8974-2ade18a72bdc.png)

![image](https://user-images.githubusercontent.com/871211/155153203-fa48a615-6e1d-4e71-969a-5316689bcd7d.png)

![image](https://user-images.githubusercontent.com/871211/155153955-bf44a0e5-e163-4cfa-b7e7-23d793b8a4d8.png)

![image](https://user-images.githubusercontent.com/871211/155154489-0598578a-88c9-4121-aeb8-c0a0da4f95a5.png)

![image](https://user-images.githubusercontent.com/871211/155245938-80ff8570-38c2-4129-8d88-b91b31108450.png)

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I was able to duplicate that too. Looks like I broke it when I added the newPageOptions() method a couple dev versions back. I have pushed a fix.

**Comment by adrianbj** [comment]
Awesome - thanks @ryancramerdesign for the quick fix - that `limit=200` example is now down from 48s to 200ms - much better :)

**Comment by adrianbj** [comment]
@ryancramerdesign - this seems to be back again - note the execution times at the bottom of the console screenshots. 

I have tested on 3.0.200 and 3.0.201. Please let me know if you have problems reproducing. Thanks!

![image](https://user-images.githubusercontent.com/871211/171698421-5019fe62-9719-4243-a9ac-855fc6e7eba0.png)
 
vs

![image](https://user-images.githubusercontent.com/871211/171698470-07a3d2c4-4a21-4467-a7d7-ca8484a9cf85.png)

**Comment by netcarver** [comment]
@ryancramerdesign I've removed the fixed label as I'm also seeing slowness for findMany() operations when compared to find() - though not as severe as that reported by @adrianbj.

**Comment by ryancramerdesign** [comment]
@adrianbj This one I can't duplicate so far. My findMany() is performing at the same speed as find() when the limit is 1000. And if I remove the limit, findMany() can iterate everything while find() runs out of memory. Though I'm working with around 10k pages not 43k, and my pages are not template=user but use other templates. I'm curious if it's occurring just on user template matches or others?

@netcarver The difference between find() and findMany() isn't always about speed but more about memory. On a find that doesn't really need findMany() then find() can definitely be faster. But on those larger result sets where it's going to be more pages than can fit in memory, then the benefits of findMany() should come into play.

**Comment by matjazpotocnik** [comment]
@adrianbj what's the status of this issue? Are you able to find out if the issue is present only on a user template or just any template? EDIT: tested on regular template with 17000 pages and time is measured in milliseconds.

**Comment by adrianbj** [comment]
@matjazpotocnik - lastest PW version:

<img width="485" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/404fdfaf-bc21-4072-a298-8d6f6b76c22e">

vs

<img width="485" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/359a94e6-da0e-4494-817f-a7cd98e8ef31">

**Comment by adrianbj** [comment]
The templates I have tested with have a lot of fields, so maybe that is the distinguishing factor?

**Comment by matjazpotocnik** [comment]
Hmm, that could be. How many fields do you have on that template?

**Comment by adrianbj** [comment]
There are 96 on the message template and 139 on the user template. So, yes, a lot :)

But, I just tested on a template with 6 fields and findMany takes 6 times longer - not as bad, but still not good.

**Comment by matjazpotocnik** [comment]
> There are 96 on the message template and 139 on the user template. So, yes, a lot :)

Wow, that's a lot :-) I guess it must play a role.

**Comment by matjazpotocnik** [comment]
Ok, so now I'm testing on 32846 pages using a template with 7 text fields:

![image](https://github.com/processwire/processwire-issues/assets/7663992/d01a50a3-6606-42e8-badb-e978d03eae3c)

![image](https://github.com/processwire/processwire-issues/assets/7663992/9ab154d2-9953-498e-8745-c3368bdb6e6f)

So, find() is much faster than findMany().

What I also discovered, is that page edit is taking a looong time:

![image](https://github.com/processwire/processwire-issues/assets/7663992/540f959c-937a-4209-83c9-e363020638a6)

Why loading 32904 pages?

```
SELECT false AS isLoaded, pages.templates_id AS templates_id, pages.*, pages_sortfields.sortfield,
(SELECT COUNT(*) FROM pages AS children WHERE children.parent_id=pages.id) AS numChildren,field_title.data AS `title__data`,field_title.data1231 AS `title__data1231`
FROM `pages`
LEFT JOIN pages_sortfields ON pages_sortfields.pages_id=pages.id
LEFT JOIN field_title ON field_title.pages_id=pages.id
WHERE pages.id IN(18727,18728,18729,18730,18731,18732,18733,18734,...a lot of IDs here...,51570,51571)
AND pages.parent_id=18722
AND pages.templates_id=97
GROUP BY pages.id -- [577.2ms]
```
@ryancramerdesign can you help?

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Since you are using a "limit=" there is no reason to use findMany here, as it does not use limit. findMany() is for when you want to load all the pages, and find() with limit=n is for when you don't.  

The findMany() loads all the matching page IDs rather than the pages. So if you use findMany() to match 30000 pages, it's going to load 30000 IDs, and then break them into chunks that it will load them as pages as you iterate them. Loading 30000 IDs is still a significant amount to load. And that'll definitely take longer than doing a find() with a limit of 1000.  

A better test would be to use find() and findMany() without a limit=n specified. For instance, if I find 2200 pages with find(), it takes 5 seconds, and with findMany it takes 2 seconds. As you increase the number matched, the greater the difference, and find() may no longer be able to load them due to memory, whereas findMany() will be able to. 

If your page editor is loading 32k pages, that sounds like there must be a page reference field on that page that has 30k selectable options. Can you check your template for that page to see what Page fields are present that might be loading that many? If you don't find any, the next thing I would check is is if any modules or hooks are loading them.

**Comment by adrianbj** [comment]
@ryancramerdesign - what about my example in this post (https://github.com/processwire/processwire-issues/issues/1535#issuecomment-1685377354) above. I don't specify a limit there, but still `findMany` is much slower. I don't see the "Pages Loaded" issue with those queries. The `findMany` loads only 66 pages while the `find` version loads 1188 pages.

**Comment by matjazpotocnik** [comment]
$pages->find('template=city');
7278.64 ms (32846 items)

$pages->findMany('template=city');
500: Internal Server Error
ERROR: Maximum execution time of 120 seconds exceeded on line: 168 in C:\inetpub\wwwroot\wire\core\WireDatabasePDOStatement.php

**Comment by ryancramerdesign** [comment]
@adrianbj Could it be something with Tracy analyzing the result? If I do this in Tracy:
~~~~~
d($pages->findMany("template=villa|tour"));
~~~~~
It takes `15 seconds` to find ~2300 pages. Whereas if I do this from a template file:
~~~~~
$timer = Debug::timer();
$items = $pages->findMany("template=villa|tour");
echo Debug::timer($timer); 
~~~~~
It takes `0.07 seconds`. 

Interestingly, the regular find() version takes a similar amount of time in either case (5s). But it does seem that something about being in Tracy makes the findMany() slow? Does Tracy iterate through the PageArray() on the d() call?

**Comment by matjazpotocnik** [comment]
> If your page editor is loading 32k pages, that sounds like there must be a page reference field on that page that has 30k selectable options. Can you check your template for that page to see what Page fields are present that might be loading that many? If you don't find any, the next thing I would check is is if any modules or hooks are loading them.

There is no page reference field on that template. The template has 7 text fields. I have uninstalled some modules: core PagePaths and Dynamic Roles. Now it's all good. How can I detect what module or hooks are loading them? What would be the name of the hook to look for? Thanks for the hint! (and sorry Adrian for hijacking this thread).

**Comment by ryancramerdesign** [comment]
@matjazpotocnik I doubt it would be the PagePaths module, but I would guess it could be the Dynamic Roles module? That's a module that I developed for the needs of a client (Avoine) but it was like 10 years ago, back when PW was in the 2.x versions. I don't think I've worked with that module since then, so I'm guessing it's likely not compatible with current versions of PW. I'd be curious if you find it is that module or isn't?

**Comment by adrianbj** [comment]
@ryancramerdesign - you might be onto something - let me see if I can narrow down where / why Tracy is having an impact.

**Comment by matjazpotocnik** [comment]
O yes, it's compatible, and it's working, with some changes - added namespace and these:
 
 https://github.com/ryancramerdesign/DynamicRoles/pull/18/commits/f4e9e668c621e4f2254e26a0a5a8706c5277d571
 https://github.com/LostKobrakai/DynamicRoles/commit/5548722a566f7e4e23d326bd64a0783098b67108
 https://github.com/ryancramerdesign/DynamicRoles/commit/915794bb169fb48a14118c5c72533f3605845f3e

It's been in production for years on PW 3.0.148, I find it invaluable! But I discovered that it maintains its own table that has (had) 32k rows.

**Comment by matjazpotocnik** [comment]
From the template file using debug timers:

```
pages->findMany('template=city'): 0.2237 sec
pages->find('template=city'):     3.1585 sec
```

**Comment by adrianbj** [comment]
@ryancramerdesign - I tracked it down to `debugInfo()`. If I disable the Debug Info tab from the dumps output, then it's speedy again in both `d()` and `bd()` calls. 

So, I think it's something to do with PW's `__debugInfo()` methods - I'll try to narrow down which one is causing the problems.

**Comment by adrianbj** [comment]
@ryancramerdesign - it seems to be this block here: https://github.com/processwire/processwire/blob/af80005a9c57db750dcb3177ddcd0a368c44aa05/wire/core/WireDebugInfo.php#L110-L117

That said, I am not sure how it should be better handled. I am sure many of us use Tracy's console to debug the speed of various methods and having it output the Debug Info version is generally nicer than the Full Object.

Any thoughts?

I guess I would still like to know why @matjazpotocnik is seeing the slowdown in his last example above though because it seems like the debugInfo method isn't involved there.

**Comment by ryancramerdesign** [comment]
@adrianbj 

> That said, I am not sure how it should be better handled. I am sure many of us use Tracy's console to debug the speed of various methods and having it output the Debug Info version is generally nicer than the Full Object.

With any debugger some overhead is expected, so likely it's not a problem. I think in this case, it sounds like it is iterating through all the pages to gather debug info from them, and that takes awhile. With findMany() pages are lazy-loaded, so iterating the result set would also swap chunks of pages in and out of memory as needed. 

> I guess I would still like to know why @matjazpotocnik is seeing the slowdown in his last example above though because it seems like the debugInfo method isn't involved there.

His latest test above seems more what I'd expect (0.2s findMany, 3.1s find) though both are really good times for finding 30k pages. Matjaz must have a fast computer and lots of memory. I think in most sites only a findMany() could load that many pages at once.

**Comment by adrianbj** [comment]
@ryancramerdesign - I understand it's OK to expect some overhead for debugging - it's just a shame it's so much with `findMany()` because in general I think we can rely on the timings displayed in Tracy, but clearly not in this case when that Debug Info tab is enabled and you're testing `findMany()`. It almost makes me want to remove it to avoid confusion, but it's still generally such a much nicer way of reading page info.

Sorry, I misread @matjazpotocnik's latest results - swapped the order, so all good there.

I suppose it's ok to close this issue now.
