### ISSUE TITLE
Field editor error caused by field tags with unallowed characters

### ISSUE THREAD

**Issue by aagd** [processwire/processwire-issues#1536]
s.a. [forum thread
](https://processwire.com/talk/topic/26818-field-editor-not-showing-anything/)

### Short description of the issue

On a multilanguage site the field editor failed to show anything after setting a field tag containing the character 'Œ'. The field editor then also failed for all other fields (without field tags). The error screenshot can be seen below. Removing the tags restores all functionality.

The problem occured in a local MAMP installation. An identical copy of the site on a live webserver didn't show the error in German, just in French.

The site is in German as default language, plus English & French. Locally switching to English in the Admin fixes the error, switching to French not. On the live server German and English work, French doesn't.

Clearing caches, switching to other browsers didn't show any differences. Since the problem seems to be affected by the server configuration, it might be difficult to reproduce.

### Expected behavior

The field editor should never fail. Tags should be sanitzed so they stay within the range of allowed characters.

### Actual behavior

The field editor fails in certain configurations. There seem to be no limitations to use umlauts (äöüÄÖÜ) or other invalid characters (œŒ etc.). Tags containing these characters can cause problems, even if often they don't. In Multilanguage sites, especially in a non-english Admin UI, there seems to be some kind of problem to handle their JSON encoding.

### Screenshots

![Screen Shot 2022-02-26 at 19 33 30](https://user-images.githubusercontent.com/141630/156187991-26c376cc-fb3a-46b8-aab6-d27cb2b230f8.png)

### Suggestion for a possible fix

The interface of the "Manage Tags" dialogue (Fields Overview) says "Any combination of letters (a-z), numbers (0-9) and underscores (no spaces)." but it's still possible to enter umlauts and other characters beyond this range. The Tags input in the field settings dialogue, probably the main input for tags, doesn't mention these limitations at all.

These two dialogues should be adjusted to convey the same message, and their input might need sanitizing.

### Steps to reproduce the issue

The exact server environment seems to matter here.

In a field setting dialogue, adding a tag like "Œuvre" or "Übersicht" would make the field editor dialogue (for all fields) inaccessible on save. I had to restore from a backup to remove the tag again (until I figured out that switching to English would also help)

### Setup/Environment

* ProcessWire version: 3.0.183
* PHP version: local with problem: 7.3.29 - live without problem: 7.3.31
* MySQL version: local with problem: 5.7.34 - live without problem: 5.7.36

**Comment by ryancramerdesign** [comment]
@aagd Thanks for the report. I wasn't able to duplicate the issue here, and I tested on systems using both UTF8 and UTF8MB4 database charsets. But I did find some things that may account for it and made some related updates. Since I can't duplicate the issue (also testing in MAMP) I don't know if the updates I made will resolve it, are you able to test? Thanks.

**Comment by aagd** [comment]
OK. If I do understand this correctly: I need to install the updated `wire/core/Sanitizer.php` to test this? If not please advise what I have to do. The changes in Sanitizer.php didn't seem to make any difference (cleared both PW & browser caches). I can still add tags with umlauts and those would still crash the field editor in a non-english admin.

**Comment by ryancramerdesign** [comment]
@aagd Sorry, looks like my commit didn't go through the first time, but just got it now.

**Comment by aagd** [comment]
@ryancramerdesign Sorry, the problem persists (eg. body field). Let me know if i can collect more details to help you.

![Screen Shot 2022-03-04 at 15 08 49](https://user-images.githubusercontent.com/141630/156778188-9b345d29-ccbb-422c-8095-2c33581495a7.png)

**Comment by ryancramerdesign** [comment]
@aagd Thanks for testing. I am not sure what else to try here so I think we'll need to wait for someone else that is experiencing the issue. Though it would be worth checking your DB charset to make sure it is UTF8MB4 as you'll likely need that to accurately store the characters you are using.

**Comment by aagd** [comment]
@ryancramerdesign Thank you, Ryan! It looks like DBs (live & dev) are on utf8. I never considered utf8mb4 because of this installer warning: _"The DB Charset option “utf8mb4” may not be compatible with all 3rd party modules."_ Would it make sense to make utf8mb4 default? I'll try to move to utf8mb4, and will report back. It might take me a week or two, though.

**Comment by aagd** [comment]
@ryancramerdesign I did a quick test with a clean install of the latest dev with multilanguage site profile, and both utf8 and utf8mb4 don't work when switching the admin to German and adding the tag `œuvre` to the body field (tried both innodb & myisam modes).

**Comment by aagd** [comment]
One more clue I could find: The JSON error seems to occur because `data-opts` is empty (`data-opts=""`). It appears that something goes wrong when `data-opts` is put together, probably the `tags` string, in `wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.module`. Normally the `data-ops` content would look more like:

```
{
    "allowUserTags":true,
    "closeAfterSelect":1,
    "createOnBlur":true,
    "delimiter":" ",
    "maxItems":0,
    "tagsUrl":"",
    "tags":{"mytag":"mytag"}
}
```
(In the example I replaced all `&quot;` with ")


The `$tags` values right before the unsuccessful JSON encoding look like:

```
Array
(
    [�uvre] => œuvre
    [œuvre] => œuvre
)
```
Not sure why the first œ shows as a question mark, while the others are ok. in the database that character is escaped as `\u0153`, so maybe it breaks somewhere when that value is read in again/decoded from the db. Just in case the characters render differently on other platforms I'll also add it as a screenshot:

![Screen Shot 2022-04-21 at 22 35 36](https://user-images.githubusercontent.com/141630/164548328-ad23ea42-0ed7-4a8e-892f-62e1e5393d0a.png)

**Comment by aagd** [comment]
@ryancramerdesign I put together some more infos above to help with the debugging. Hope this will help. So far I couldn't figure out where the DB JSON gets decoded for a field admin page...

**Comment by aagd** [comment]
@ryancramerdesign One problem seems to be that the array key is ASCII-encoded, not UTF-8 (tested via `mb_detect_encoding($key)` in L.347). Another is that there are two items in the array for just one tag. Or should the key actually be a language identifier?

**Comment by aagd** [comment]
When deactivating the L.609 in `wire/modules/Inputfield/InputfieldTextTags/InputfieldTextTags.module`
```
// $tags = $this->getTagsList($language && $language->id ? $language : null);
```
the problem seems to be solved. The `$tags` array shows only the second, valid entry and the interface works again. I'm not sure what `$language` is used for here, as there are no translations for tags.

**Comment by ryancramerdesign** [comment]
@aagd Thanks for the additional tests. I've tried to duplicate again here, but still not able to. I've had a look at the data-opts but not seeing the duplication you mentioned. But since you are seeing that, there's clearly an encoding mixup somewhere, but whether it's in PHP, MySQL, the browser or PW is not clear. Since I can't duplicate it, and you also aren't observing it on your live host, nor have there been any other reports of it, I think it's more likely something in the environment rather than in PW.  Commenting out that line 609 likely fixed it in your case because that just prevents the pre-defined tags from being used. But commenting the line would hide the issue rather than fix it, while breaking InputfieldTextTags for other usages, so I don't recommend it as a long term solution. Have you tried a newer version of PW? It might be worth trying the current dev branch to see if it makes any difference, but since the issue seems to be present just one that one machine (if this is still the case) then the version may not matter, but it would probably be worth trying just in case.

**Comment by aagd** [comment]
> Have you tried a newer version of PW? It might be worth trying the current dev branch to see if it makes any difference

@ryancramerdesign Hi Ryan, thanks for the reply. Yes I already upgraded to _ProcessWire 3.0.198 dev_. Could you explain why `$language` is involved for the tags? Would it help to send you a dump of the site?

**Comment by ryancramerdesign** [comment]
@aagd InputfieldTextTags supports multi-language tag labels, where you have the same tag but with different labels depending on language. This particular feature is not used in the context of ProcessField or ProcessTemplate though. I don't think a dump of the site will be worthwhile here as it seems to be the environment rather than the site, assuming I understand correctly. For an issue like this, we usually need for someone else to be able to duplicate it as the next step, which is why we've got the help-wanted tag on this issue.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Robin can duplicate: https://processwire.com/talk/topic/26818-field-editor-not-showing-anything/#comment-222013

**Comment by matjazpotocnik** [comment]
Sorry for hijacking this issue, but while trying to duplicate, I got this:

TypeError in_array(): Argument #2 ($haystack) must be of type array, string given in 
...\wire\modules\Process\ProcessField\ProcessField.module:533

I went to Setup -> Fileds -> Manage tags, then entered Œ as tag name and pressed submit. The list of fields to add the tag is displayed, but I didn't add a check to any of them, I just clicked Submit.

On the other hand, I can add tags with whatever characters in the field advanced settings without an error.

**Comment by Toutouwai** [comment]
@ryancramerdesign, I'm not sure if this is the same issue that the OP is talking about, but the issue I encountered is...

When you try and add a tag containing an umlaut at Edit Field > Advanced, something crashes and then you can no longer edit the field. The tabs/form are no longer displayed, the main admin dropdown menus don't work, and there is a JS error in the console. 

![tags](https://user-images.githubusercontent.com/1538852/164801621-6a638902-2b10-4f41-9e08-18f175fa270c.gif)
![2022-04-23_095958](https://user-images.githubusercontent.com/1538852/164801616-e2cb744a-5c33-4f3a-82b2-0b6bf08822ff.png)

The tag in the fields table of the database looks like this:
![2022-04-23_100620](https://user-images.githubusercontent.com/1538852/164802109-f05ac614-777e-4e65-9d67-cc7a615dcd9e.png)

I tested in PW 3.0.198 with UTF8MB4.

**Comment by Toutouwai** [comment]
@ryancramerdesign, I did some exploring and the issue seems to be the usage of `strtolower()` on the keys of tag arrays. If I change the instances of `strtolower()` in Field.php and ProcessField.php (there are probably other instances relating to template tags) to `mb_strtolower()` it seems to resolve the problem here.

**Comment by aagd** [comment]
> @ryancramerdesign, I'm not sure if this is the same issue that the OP is talking about...

yes, exactly the same issue.

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I've added your suggested fix for this. Regarding template tags, I don't think there have been similar reports for that one yet (?), and I never even able to duplicate the issue with fields. I think we'll need to hear from someone that's seeing the issue (you or @aagd) to test if the same issue appears with template tags?

**Comment by aagd** [comment]
@ryancramerdesign Thank you! In my setup the issue didn't occur with template tags, just with field tags.
