### ISSUE TITLE
Images custom fields: fieldgroup and template not removed after field deleted

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1537]
### Short description of the issue

After deleting an images field that uses the "custom fields" option, the related fieldgroup and template items are not removed from the database.

In this example I have deleted a field named "images_custom":

![2022-03-02_143356](https://user-images.githubusercontent.com/1538852/156278043-2064eca0-ca14-4fca-83b8-64b8b43c0151.png)

![2022-03-02_143508](https://user-images.githubusercontent.com/1538852/156278039-c214d9e5-e07d-4d63-80b4-82b8c39c06f4.png)

![2022-03-02_143551](https://user-images.githubusercontent.com/1538852/156278035-4ccb54fe-eec1-49e7-b7dd-d927d5cba9c4.png)

### Setup/Environment

* ProcessWire version: 3.0.195

**Comment by ryancramerdesign** [comment]
@Toutouwai The template for custom fields in files/images is meant to be a user managed template. More recently a convenience was added where it would create the template for you when you checked a box, but it still remains primarily a user managed template. I know it might also be a nice convenience for the field to do everything else too, but it's more code and responsibility than I'd like the files field to maintain at this time.

**Comment by Toutouwai** [comment]
For some reason I thought the custom fields template was a system template and so was hidden by default at Setup > Templates. But I see now it is visible and easily deletable from there, so not a problem.
