### ISSUE TITLE
In memory sort error when sort field does not exist on some of the pages

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1538]
### Short description of the issue

Not sure if this is a bug or expected behavior so please bear with me - when using `sort()` on an in memory page array if you sort by a field that doesn't exist on some of the pages you get:

```
ProcessWire\PageArray::getItemPropertyValue(): Argument #1 ($item) must be of type ProcessWire\Wire, bool given, called in /var/www/html/wire/core/PageArray.php on line 581
```

### Expected behavior

I feel like it should handle this scenario the same way the sort works when doing a sort within a `$pages->find`

### Actual behavior

Fails and returns the error noted above.

### Steps to reproduce the issue

I haven't tested this in all scenarios yet, but this works even when there are some pages where there is no selected `dates`:

```
$pages->find('template=basic-page, sort=dates.date_priority');
```
but this doesn't:
```
$pp = $pages->find('template=basic-page');
$pp->sort('dates.date_priority');
```

Note that in this case, `dates` is a page reference field and `date_priority` is a select options field on the "date" pages.

To reiterate, the second option fails when one of the pages in `$pp` doesn't have any selected pages in the `dates` field.

Again, I am not sure if this is a bug or expected, but if it could be handled without an error, that would be much appreciated, thanks!

**Comment by ryancramerdesign** [comment]
@adrianbj That looks like a bug to me, it looks like it needs an if() statement added. I have added one, does this seem to fix the issue for the query you are testing?

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that fixes things. Much appreciated!
