### ISSUE TITLE
Documentation incorrect for $page->delete() return value

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1539]
### Short description of the issue

page()->delete()  API documentation says that the return is bool true or false.
But when option resursive is set, delete() returns an int (number of deletions).

### Expected behavior

The documentation should be updated to clarify this behavior.

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed a fix for this.

**Comment by matjazpotocnik** [comment]
Closing on the assumption this is fixed. @er314  Please comment here again if that is not the case.
