### ISSUE TITLE
Page titles in admin breadcrumbs do not show formatted value

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#154]
### Short description of the issue

Everywhere else, the value gets formatted, but not in breadcrumbs.

Example:

```php
$this->addHookAfter('Fieldtype::formatValue', null, function(HookEvent $event) {
    $field = $event->arguments('field');

    if ($field->name !== 'title') return;

    $value = $event->arguments('value');

    $event->return = "{$value} foo";
});
```

### Screenshots

`foo` gets successfully added, like seen here in the page tree:

![screen shot 2017-01-08 at 21 51 34](https://cloud.githubusercontent.com/assets/1720088/21753414/d599b8c8-d5ec-11e6-86fb-87f0fe404c9b.png)

Not in the breadcrumbs trail:

![screen shot 2017-01-08 at 21 51 47](https://cloud.githubusercontent.com/assets/1720088/21753415/d59c7e46-d5ec-11e6-94bb-557064f63560.png)

### Setup/Environment

* ProcessWire version: 3.0.47
* PHP version: 5.5.12
* MySQL version: 14.14 Distrib 5.6.17

**Comment by ryancramerdesign** [comment]
Breadcrumbs are kind of a unique case because they can contain a mixture of Page titles and non-page related labels. This is one of the reasons why the formatting is handled by the admin theme rather than by the field. Another reason is that the admin theme passes them through a language translation function to automatically translate common titles/labels that appear in the breadcrumbs, so the breadcrumb labels need to arrive in an unformatted state.

**Comment by owzim** [comment]
Thanks @ryancramerdesign for the insight. Is there a way for me to force them to get formatted besides modding the admin theme?

I have this scenario, where titles have to be split in two by a `<br />` in some places, so I provide the option to include a pipe `|` in the title field. By default (via hook `formatValue`) I replace it with nothing and within the menu creation I replace it with a break. This way the client does not have to maintain a separate `menuTitle`-field (or similar).

But with the breadcrumbs not being formatted, the ugly pipe is visible (only) there. It's a minor but bugging (OCD-alert 😄) thing.

**Comment by adrianbj** [comment]
Interesting that grandparents and "older" actually are formatted in the breadcrumb.

![screen shot 2017-01-21 at 12 26 56 pm](https://cloud.githubusercontent.com/assets/871211/22177550/0193217a-dfd5-11e6-84ff-42649639fe32.png)

**Comment by rolandtoth** [comment]
It's possibly related but no further ideas in my mind :)

**Comment by Toutouwai** [comment]
> But with the breadcrumbs not being formatted, the ugly pipe is visible (only) there. It's a minor but bugging (OCD-alert 😄) thing.

This seems to work:

```
// replace pipe in linked breadcrumbs
$this->addHookAfter('Process::breadcrumb', function(HookEvent $event) {
	foreach($this->breadcrumbs as $breadcrumb) {
	    $breadcrumb->title = str_replace('|', '', $breadcrumb->title);
	}

});
// replace pipe in final breadcrumb / page title
$this->addHookBefore('Process::headline', function(HookEvent $event) {
	$event->arguments('headline', str_replace('|', '', $event->arguments('headline')));
});
```

**Comment by owzim** [comment]
Thanks @Toutouwai, this solved my specific issue. Though it's:
```php
foreach($event->object->breadcrumbs as $breadcrumb) {
// ...
```
