### ISSUE TITLE
Empty Repeaters after 3.0.165 => 3.0.184 Master

### ISSUE THREAD

**Issue by tirrenian** [processwire/processwire-issues#1541]
### Short description of the issue

After updating core from 3.0.165 to 3.0.184 Page reference (Select type) in Repeater goes empty, but only in back-end. The database is still having actual values and front-end as well.

### Expected behavior

Select field should be populated with value.

### Actual behavior

Select field is empty in back-end. Front-end and Database have actual values.

### Optional: Suggestion for a possible fix

Downgrade to 3.0.165 resolve this issue.

* ProcessWire version: 3.0.184 Master

**Comment by BernhardBaumrock** [comment]
Have you tried the latest dev version?

**Comment by tirrenian** [comment]
Thank you for suggestion, Bernhard.

I tried, but issue is still there (ProcessWire 3.0.196).

**Comment by ivangretsky** [comment]
I think I am experiencing kind of the same issue. In my case the Page field is not in Repeater (so it might not matter), but the inputfield is ASM Select. I can see values in the DB, but on the edit screen the field is empty. If I change the inputfield to something else, I can see the selected pages. So it might be an issue with ASM Select.

**Comment by tirrenian** [comment]
@ivangretsky I checked again: we experienced issue with Select, not with ASM select. 

Please be careful, as it seems like the data has actual values in DB, but if page will saved with empty Select information will be rewrite with empty values.

**Comment by ryancramerdesign** [comment]
@AlexanderPotapov @ivangretsky I can't duplicate the issue here. Can you compare what 3rd party modules you two have installed to see if there are any in common? To me it sounds like maybe some kind of admin enhancement module is interfering or maybe something is causing a JS error, preventing an Inputfield from initializing.

**Comment by tirrenian** [comment]
@ryancramerdesign @ivangretsky Ryan, thank you for your attention to this issue. After some further research I can confirm that this issue related not only to repeater Select, but to all Select fields. When this issue was discovered for the first time I checked the developer console, as client side script is most obvious point of failure for UI, however there was no errors there.

Sometimes select are empty, sometimes select in repeater and unfortently I can not see any particular pattern.

We don't use many modules for backoffice.

So for the moment, we downgraded to ProcessWire 3.0.165 (PHP 7.2) and it seems that it stops crash database.

**Comment by matjazpotocnik** [comment]
I can't replicate it. I put the page ref field in repeater and tested it with all input selectors. I specified the parent and template as the selectable pages.

**Comment by matjazpotocnik** [comment]
@AlexanderPotapov can you replicate this on a fresh install?

**Comment by matjazpotocnik** [comment]
@AlexanderPotapov  closing this now. Please comment again if you need it re-opening.

**Comment by tirrenian** [comment]
Thank you for suggestion, Bernhard.

I tried, but issue is still there.

Best regards
Alexander
