### ISSUE TITLE
Cloned template files have incorrect filesystem permissions

### ISSUE THREAD

**Issue by giovvv** [processwire/processwire-issues#1542]
### Short description of the issue

Template files that are cloned via the admin interfaces are created with wrong permissions

### Expected behavior

New files should be created with the filesystem permissions set in $config->chmodFile

### Actual behavior

Template php file is created with default filesystem permissions (644 in my case).

### Steps to reproduce the issue

1. Go to the admin interface. Select a template that already has an associated php file.
2. Edit the template > Clone
3. Check filesystem permissions of the new file.

### Setup/Environment

* ProcessWire version: 3.0.165
* PHP version: 7.2.24

**Comment by ryancramerdesign** [comment]
Thanks @giovvv I've pushed a fix for this issue

**Comment by matjazpotocnik** [comment]
@giovvv can this be closed?

**Comment by matjazpotocnik** [comment]
@giovvv Closing this now. Post more if it needs re-opening.
