### ISSUE TITLE
Enabling access control for the "roles" field breaks the admin for non-superusers

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1544]
### Short description of the issue

Enabling access control for the "roles" field breaks the admin for non-superusers

### Expected behavior

Either it should be possible to change access to the roles field without breaking anything, or the option to turn on access control should be disabled.

### Actual behavior

It's possible to enable it, but it breaks the admin.

### Optional: Suggestion for a possible fix

Maybe it was intended to be used this way, but it would be kinda nice to be able to give an admin user the rights to edit other user profiles, while completely preventing access / hiding the roles field. 

I achieved it via a hook which I am happy with, but I do think it's important that Access tab is disabled unless it works as expected.

```
// hide roles field from otherwise user-admin authorized users
$this->wire()->addHookAfter('Field::getInputfield', function(HookEvent $event) {
    if($this->wire('user')->isSuperuser() || $this->wire('user')->hasRole('editor') || $this->wire('page')->process !== 'ProcessUser') return;
    $field = $event->object;
    $inputfield = $event->return;
    if($field->name == 'roles') {
        $inputfield->collapsed = Inputfield::collapsedHidden;
    }
});
```

**Comment by Toutouwai** [comment]
It might be the kind of field that needs the "Make field value accessible from API even if not viewable" toggle activated if it is accessed controlled?

**Comment by adrianbj** [comment]
Thanks very much @Toutouwai - I should have opened up that set of options to check what was available there.

It does seem to fix things, but I think perhaps there could still be some improvement in the case of critical system fields so we don't end up with fatal errors unless that option is checked.
