### ISSUE TITLE
Save hooks not triggered as expected

### ISSUE THREAD

**Issue by JanRomero** [processwire/processwire-issues#1547]
### Short description of the issue

These calls do not trigger hooks after Pages::save and Pages::saved:

- `$p->save('fieldname')`
- `$pages->saveField($p, 'fieldname')`
- `$p->setAndSave('fieldname', 'value')`

Likewise, `$pages->save($p, 'fieldname')`, i.e. a field-specific save, does not trigger a hook after `Pages::saveField`.

Additionally, while `$pages->save($p, 'fieldname')` _does_ trigger both `Pages::save` and `Pages::saved`, the hooks receive mismatched event arguments. Argument 1 is an _array_ of changed fields for `Pages::save` and an individual _string_ for `Pages::saved`. That is to say, the same hook function will receive different arguments depending on how it was triggered, and might throw an error if it gets a string while expecting an array.

### Expected behavior

Personally I would expect the ❌s in this matrix to be ✔s. If ProcessWire’s logic is to use disparate hooks for single-field saves and page-level saves, that seems understandable, but I could not find any mention of this in the docs. That logic would also be muddied by `$p->save('fieldname')` and `$pages->save($p, 'fieldname')`, because the same method name is used for page-level saving. Really I would prefer the hooks `Pages::save` and `Pages::saved` to be subscriptions to any change whatsoever. If the call site does not want to be hooked, it should pass the `noHooks` option.

|                                      | after Pages::saved | after Pages::save | after Pages::saveField
| ------------------------------------ | :--:               | :--:              | :--:
| $p->save()                           | ✔                 | ✔                |  —
| $p->save('fieldname')                | ❌                 | ❌                | ✔
| $pages->saveField($p, 'fieldname')   | ❌                 | ❌                | ✔
| $pages->save($p, 'fieldname')        | ✔                 | ✔                | ❌
| $p->setAndSave('fieldname', 'value') | ❌                 | ❌                | ✔

I would also expect a hook function to always receive the same argument types. Alternatively it should be mentioned in the docs.

### Actual behavior

Hooks are triggered according to the check marks in the above table. The type of argument 1 for `Pages::save` and `Pages::saved` hooks seems to be:

|                                      | after Pages::saved | after Pages::save |
|--------------------------------------| :--:               | :--:              |
| $p->save()                           | array              | array             |
| $pages->save($p, 'fieldname')        | array              | string            |

### Steps to reproduce the issue
This is just some stupid code I wrote to arrive at the tables above.

Some hooks in ready.php. I have only tested `addHookAfter`:

```PHP
$this->addHookAfter("Pages::saved", function(HookEvent $event) {
    $x = gettype($event->arguments(1));
    echo "\tafter Pages::saved (changes: $x)";
});

$this->addHookAfter("Pages::save", function(HookEvent $event) {
    $x = gettype($event->arguments(1));
    echo "\tafter Pages::save (changes: $x)";
});

$this->addHookAfter("Pages::fieldSaved", function(HookEvent $event) {
    echo "\tafter Pages::fieldSaved";
});

$this->addHookAfter("Pages::saveField", function(HookEvent $event) {
    echo "\tafter Pages::saveField";
});
```
(Note that [Pages::fieldSaved is mentioned here](https://processwire.com/api/ref/page/save/), but it is not triggered and the [link](https://processwire.com/api/ref/pages/field-saved/) doesn’t go anywhere)

Triggering the hooks:
```PHP
$p->of(false);

echo "\n\$p->save()";
$p->title = 'test 1';
$p->save();

echo "\n\$p->save('fieldname')";
$p->title = 'test 2';
$p->save('title');

echo "\n\$pages->saveField(\$p, 'fieldname')";
$p->title = 'test 3';
$pages->saveField($p, 'title');

echo "\n\$pages->save(\$p, 'fieldname')";
$p->title = 'test 4';
$pages->save($p, 'title');

echo "\n\$p->setAndSave('fieldname', 'value')";
$p->setAndSave('title', 'test 5');
```

### Setup/Environment
* ProcessWire version: 3.0.191 dev

Thanks!

**Comment by JanRomero** [comment]
Right, I just learned about `Pages::savedPageOrField`. That definitely solves my problem, although I feel like my concerns remain valid. It feels like `savedPageOrField` is what most people will need 99% of the time, but it’s pretty well hidden in the docs. It’s not mentioned on the other hook pages and it doesn’t appear [in the “see also” section here for example](https://processwire.com/api/ref/page/save/). It might be nice to introduce this one in the [Hooks Tutorial](https://processwire.com/docs/modules/hooks/) instead of `saved`?

**Comment by BernhardBaumrock** [comment]
Hi @JanRomero I think your issue title is misleading.

For me the hooks are triggered as expected. I don't know where I read about it, but I read it somewhere or just found out by try and error. I agree that this might not be obvious to newcomers, but changing the inner workings would likely break a lot of applications so that is no option in my opinion.

But your matrix is great and would be a good addition to the docs! I think it would become more obvious then for everybody and I think your issue would then also be solved as the expectation of everybody reading the docs would match to what really happens in the system :)

**Comment by szabeszg** [comment]
> It might be nice to introduce this one in the [Hooks Tutorial](https://processwire.com/docs/modules/hooks/) instead of `saved`?

`Pages::savedPageOrField` was added more than 5 years ago, without any publication, even though it should have deserved more than that, I agree.

See: https://processwire.com/talk/topic/14526-pw-3037-core-updates-profields-text-blocks/?do=findComment&comment=130672

**Comment by ryancramerdesign** [comment]
@JanRomero I've added some `@see` phpdoc notes on the hook methods mentioned here so that all these hooks will soon cross-reference each other in the documentation, hopefully making the `savePageOrFieldReady()` and `savedPageOrField()` hook methods easier to find.  

You mentioned `$pages->save($p, 'fieldname')` but I can't find that this type of call is supported (https://processwire.com/api/ref/pages/save/) and that may account for the unexpected values in the hook. Maybe I'm forgetting something though, did you see that call used in an example on the PW site somewhere? Thanks.

**Comment by matjazpotocnik** [comment]
@JanRomero, any more thoughts on this?
