### ISSUE TITLE
findRaw doesn't return an array item for empty values

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1553]
### Short description of the issue

Not sure if this is expected (as a way to reduce the size of the array), or it's a bug, but if a field is blank on a page, then the field is missing completely from the array for that page.

### Expected behavior

Array item should still exist, at least optionally.

### Actual behavior

Best demonstrated by the screenshot. See how `email` is listed (presumably because it's a system field), but `last_name` isn't shown when it's empty. Note some of the other pages in the array have 4 items - these include the `last_name` item because it's not blank.

In case you're wondering why this is important - I am looping through to populated an export to Excel and a missing array item shifts the values into the wrong columns.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/160948305-cc09488f-4752-4109-9b2a-cfeb91eb1eb4.png)

### Optional: Suggestion for a possible fix

Could you have a setting to optionally show / hide empty items?

**Comment by BernhardBaumrock** [comment]
For me this would also be better. The scenario is using findRaw as content for a grid and if all properties were the same for each row it would save me from a lot of if(array_key_exists(...))

**Comment by ryancramerdesign** [comment]
@adrianbj @BernhardBaumrock I've added support for this. See the new `nulls` option for the pages.findRaw() method.

**Comment by thetuningspoon** [comment]
I was also wishing for this feature. Thanks @ryancramerdesign!

**Comment by matjazpotocnik** [comment]
@adrianbj Closing on the assumption this is fixed. Please comment here again if that is not the case.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - the new nulls option works great!
