### ISSUE TITLE
Strange inconsistent warning notice when using AdminThemeUikit custom markup files

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1554]
### Short description of the issue

When using the feature introduced [here](https://processwire.com/talk/topic/26876-pw-30196-%E2%80%93%C2%A0core-updates/) and documented [here](https://github.com/processwire/processwire/blob/47f2742b729c7936b76bb49fbbeb4f60d576f24a/wire/modules/AdminTheme/AdminThemeUikit/README.md), a strange warning notice is shown in a way that's not consistent.

If I copy file `_masthead.php` from `/wire/modules/AdminTheme/AdminThemeUikit/` to `/site/templates/AdminThemeUikit/` then I get the following warning notice on every admin page load:

![2022-04-01_141030](https://user-images.githubusercontent.com/1538852/161175569-59747a95-3026-409c-a33e-f3031327ba89.png)

This notice isn't self-explanatory (it's just a file path - what does this mean?), and even if more information was added about why it's appearing it's not clear why the user needs to see this on every admin page load.

If I instead copy file `_content-body.php` from `/wire/modules/AdminTheme/AdminThemeUikit/` to `/site/templates/AdminThemeUikit/` then I don't see any notice, but why are these files treated differently?

### Setup/Environment

* ProcessWire version: 3.0.197

**Comment by BernhardBaumrock** [comment]
I don't see this on my end. Also on 3.0.197
Can you share your _masthead.php - maybe that makes a difference? Or did you just copy the one from wire folder? Maybe a Windows issue?

**Comment by Toutouwai** [comment]
> Can you share your _masthead.php - maybe that makes a difference?

Just copying the original file without any changes still causes the issue. It's due to this line: https://github.com/processwire/processwire/blob/47f2742b729c7936b76bb49fbbeb4f60d576f24a/wire/core/AdminThemeFramework.php#L844

If you copy all 10 eligible files to `/site/templates/AdminThemeUikit/` and dump before the `warning()` call then every file is involved but only 4 actually cause a visible warning, probably because the other includes are too late in the render process.

![2022-04-01_210550](https://user-images.githubusercontent.com/1538852/161222079-e2028843-76b7-46ed-b04e-7ce19938c45d.png)

**Comment by BernhardBaumrock** [comment]
Interesting. I found the difference: I'm using the SystemNotifications Module and there the warning does not show up!

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, it looks like that must be something I left from testing, as I don't think that warning was intended to be there. I have removed it.
