### ISSUE TITLE
[3.0.185] wireEmpty returns true for pages that don't have children

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#1555]
### Short description of the issue

`wireEmpty` returns true for pages, even if those pages are not NullPages.

### Expected behavior

wireEmpty($page) should return `true` for NullPages and `false`, if a page exists.

### Actual behavior

wireEmpty($page) only returns `false`, if  $page also has child-pages.

### Optional: Suggestion for a possible fix

In wireEmpty, check if the object is instance of Page -> then don't check Countable.

### Setup/Environment
* ProcessWire version: 3.0.185
* (Optional) PHP version:  7.4

**Comment by Toutouwai** [comment]
Seems to me like it's working as [documented](https://processwire.com/api/ref/functions/wire-empty/):
> It returns true for Countable objects that have 0 items.

And if you check `Page::count()` (which is how Countable is implemented) you can see it returns the count of the page's children.

**Comment by MrSnoozles** [comment]
True, thanks for that. I remember it could be used to check if a returned page is an actual page or a NullPage. That does not seem to work (anymore?), because it has to be a page that also has children.

Closing this, but still doesn't seem 100% intuitive to me. Thank you again for your reply.
