### ISSUE TITLE
InputfieldPassword : using language fr_FR breaks complexifyFactor calculation

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1557]
### Short description of the issue

Setting "fr_FR" as a translation for key "C" in LanguageSupport.module makes InputfieldPassword.js interpreting "complexity factor" (a property of "pass" field) as an integer instead of a float, and thus breaking password complexity calculation.

### Expected behavior

InputfieldPassword.js should interpret "complexity factor" as a float.

### Actual behavior

For a given complicity factor of 0,7, InputfieldPassword interprets it as 0.

### Suggestion for a possible fix

Using InputfieldPassword with "fr_FR" language, the html code generated for a password input is (I removed unnecessary code) :
`<input class="FieldtypePassword" data-factor="0,7">`
Notice the comma for the data-factor value.

The javascript associated with this component, and located in file `InputfieldPassword.js`, get this data using parseFloat method at line 20 :
`strengthScaleFactor: parseFloat($input.attr('data-factor')),`

Problem is that parseFloat("0,7"), with a comma, returns 0, not 0.7.
`console.log( parseFloat("0,7") == 0 ); // => true : numbers following comma are not interpreted`

A possible fix is to replace comma by a dot before using parseFloat :
`strengthScaleFactor: parseFloat($input.attr('data-factor').replace(/,/, '.')),`

### Steps to reproduce the issue

1. Install LanguageSupport.module.
2. Add a language.
3. Add a translation for LanguageSupport.module.
4. Translate "C" to "fr_FR".
5. Go to fields > system fields > "pass" and check that it has a complexity factor of 0,7 (with a comma).
6. Use InputfieldPassword in a template (I use it from LoginRegister module).
7. Enter a simple password, just satisfying basic conditions, and see that your password complexity is shown at **100%**.
8. Go back to language translations and translate "C" to "en_US".
9. Reproduce step 7 and see that your password complexity is shown around **50%**.

Note : In Windows, using XAMPP, I was unable to get a comma when using fr_FR.

### Setup/Environment

* OS: Linux Debian.

* ProcessWire version: 3.0.184

**Comment by matjazpotocnik** [comment]
Related: https://github.com/processwire/processwire/pull/220

**Comment by ryancramerdesign** [comment]
Thanks @hiboudev I've pushed a fix for this, similar to what you suggested, but on the php rather than js side.

**Comment by matjazpotocnik** [comment]
@hiboudev, based on your thumb-up reaction, I'm assuming Ryan's fix is working for you, so I'm closing this issue. Let me know if it needs re-opening.
