### ISSUE TITLE
"Required" asterisk disappears for fields in Repeater

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1558]
### Short description of the issue

When a field that's used in a Repeater is set to "Required" then the asterisk that indicates the required status initially appears in the fields list. But once the page is reloaded the asterisk doesn't appear. The asterisk in the fields list is quite useful for identifying required fields so it would be good if it was displayed consistently.

## Screencast

![repeater](https://user-images.githubusercontent.com/1538852/162859309-3e691091-32ac-4013-af87-047b8ab97646.gif)

### Setup/Environment

* ProcessWire version: 3.0.197

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this.
