### ISSUE TITLE
New repeater items not addable by non-superuser (AJAX)

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1559]
### Short description of the issue

Clicking 'Add New' returns an error in the Javascript console:

```
[Error] Error: Syntax error, unrecognized expression: {"error":true,"message":"You don&#039;t have access to edit"}
	(anonymous function) (JqueryCore.js:2:59374)
	ut (JqueryCore.js:2:46780)
	vt (JqueryCore.js:2:49271)
	vt (JqueryCore.js:2:60720)
	nt (JqueryCore.js:2:45854)
	find (JqueryCore.js:2:61707)
	init (JqueryCore.js:2:10624)
	v (JqueryCore.js:2:9416)
	(anonymous function) (InputfieldRepeater.js:510)
	l (JqueryCore.js:2:17002)
	fireWith (JqueryCore.js:2:17785)
	T (JqueryCore.js:2:81005)
	r (JqueryCore.js:2:86565)
```

This does not happen if AJAX loading is disabled.

### Steps to reproduce the issue

1. Create repeater field and add it to a template
2. Set AJAX setting to 'Existing and new items'3. 
3. Login as a non-superuser with page-edit permissions
5. Try to create a new repeater (Click 'Add New')

### Setup/Environment

* ProcessWire version: 3.0.197

**Comment by chriswthomson** [comment]
A colleague has reported not being able to upload images to a repeater item while logged in as a non-superuser.

**Comment by ryancramerdesign** [comment]
@chriswthomson Can you check the template used by your repeater field to see if you have overridden the default access control settings? You can find the template in Setup > Templates > Show system templates > repeater_[field-name]. On the access tab for the template, the access control should be disabled, so that it can inherit access from the owning page.

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

This seems to only happen on fields inside a RepeaterMatrix field so I've posted details in the forum and will close this issue.

Cheers,

Chris
