### ISSUE TITLE
Bad evaluation of repeater template when importing fields

### ISSUE THREAD

**Issue by perrarina** [processwire/processwire-issues#156]
### Short description of the issue

When you import a repeater field, PW don't validate the template of the parent_id and assign it to repeater page.

### Expected behavior

Export the repeater field and import it without problems.

### Actual behavior

 If you export the repeater and the parent_id has a template that already contains the repeater you'll create a loop of pages creation. And in the other hand, the repeater pages will be created under a wrong parent.

### Optional: Suggestion for a possible fix

When importing a repeater field check that the template assigned to the repeater's parent doesn't contains the repeater itself or at least that is type admin.

### Steps to reproduce the issue

1.- Export a repeater field.

2.- When importing, edit the parent-id to match with the ID of a page which template contains that repeater.

3.- Pw enter's in a loop of repeater pages creation.

### Setup/Environment

* ProcessWire version: 2.6.23 rc2

**Comment by LostKobrakai** [comment]
The fix here should be that the repeater parent is not imported at all, but rather reevaluated for the current environment. There's no point in ex- and importing a value which is automatically computed  anyways.

**Comment by perrarina** [comment]
Yes @LostKobrakai , we made that test and that solution work's.

**Comment by ryancramerdesign** [comment]
@perrarina can you outline the solution that resolved it for your case? If you've already solved it, and don't mind pasting the code snippet in here, it would save me a bit of time in trying to reproduce and track down. Thanks.

**Comment by netcarver** [comment]
@perrarina Francesco, if it is possible, could you supply Ryan with the requested information. If not, please consider closing this issue as it is now quite dated. Many thanks!

**Comment by perrarina** [comment]
Hi I'm really sorry for this, let me search for the snippet: this was a long time ago.
