### ISSUE TITLE
Ignored options in PageImage rebuildVariations

### ISSUE THREAD

**Issue by julianwinkel** [processwire/processwire-issues#1560]
The detected options for rebuild the file variation are partly ignored.

File: /wire/core/PageimageVariations.php
Method: rebuild

The following values are set but never used:
`$o['hidpi'] = true;` LINE 488
`$o['forceNew'] = true;` LINE 527
`$o['suffix'] = $info['suffix'];` LINE 528

**Solution:** 
Something like that
`$options = $o;` or `$options = array_merge($options, $o);` in LINE 529 or later

The problem occurred when I set a focus point on a hidpi image. 
After saving the rebuilded image version was no longer hidpi.

* ProcessWire version: 3.0.198 dev
* PHP version: 8
* MySQL version:  5.7

**Comment by ryancramerdesign** [comment]
Thanks @julianwinkel good find, I've pushed a fix for this.

**Comment by matjazpotocnik** [comment]
@julianwinkel, please could you check this and close the issue if done?

**Comment by julianwinkel** [comment]
issue fixed, thanks
