### ISSUE TITLE
"You don't have access to edit" for AJAX edits of file fields within a Repeater Matrix

### ISSUE THREAD

**Issue by MoritzLost** [processwire/processwire-issues#1561]
### Short description of the issue

We recently updated a site from 3.0.192 to 3.0.198 and have encountered a new bug regarding file uploads. Editors can't upload files to file fields within a Repeater Matrix anymore, they're getting the following error:

> You don't have access to edit

We tracked this problem to this line in `ProcessPageEdit::___ajaxSave`:

```
if(!$this->ajaxEditable($page)) throw new WirePermissionException($this->noticeNoAccess);
```

Super user accounts don't get this buggy behaviour, so it's got to be related to a permission check. Editor accounts have all permissions to edit the page. Access control for the repeater matrix field and the files field is turned off. Other fields can be edited fine, it's only file uploads that are causing problems.

We downgraded to 3.0.192 again and the error went away, so the bug has to have been introduced between 3.0.192 and 3.0.198.

### Expected behavior

File uploads should work correctly for users that have permission to edit this page and field.

### Actual behavior

File uploads don't work and produce the error mentioned above.

### Setup/Environment

* ProcessWire version: 3.0.198 
* PHP version: 7.4

**Comment by ryancramerdesign** [comment]
@MoritzLost Thanks, I think I've tracked this one down (related to new lazy loading fields) and have pushed a fix, though please let me know if you continue to see it.

**Comment by daun** [comment]
@ryancramerdesign Thanks for fixing this. Could we have this as a dev channel release as soon as possible? I've had clients bugging me about this for a few days and it'd be great to update those sites to the latest release without manual git cloning.

**Comment by ivangretsky** [comment]
@MoritzLost , can you confirm it is fixed?

**Comment by MoritzLost** [comment]
@ryancramerdesign @ivangretsky @daun I've just tested the new 3.0.199 release, looks like the bug is gone indeed! Thanks for the quick resolution! 🚀
