### ISSUE TITLE
Alerts for the _lazy property 

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1562]
When you perform Check Field Data on the Advanced tab in field setup, you get this warning:

![image](https://user-images.githubusercontent.com/7663992/166204503-f55043ac-b479-4bba-8bec-265e5cd8997d.png)

**Comment by ryancramerdesign** [comment]
@matjazpotocnik The `_lazy` property is used at runtime when debug mode is on.  It's okay to remove it (or to leave it), but it will likely just re-appear so long as debug mode is on.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Thanks for the explanation. Yes, it re-appears after it's deleted. Perhaps some description of that particular property would be beneficial? Otherwise, we can close this issue.
