### ISSUE TITLE
findRaw subfield selectors not working with array-type syntax for page reference fields

### ISSUE THREAD

**Issue by billhemsley** [processwire/processwire-issues#1563]
### Short description of the issue

Using the array-type selector syntax for subfields, as described in the documentation, findRaw() does not work with page reference fields.

Either there seems to be a bug with the syntax, or the documentation is incorrect.

### Expected behavior

Return values from the specified subfields in the same way as the dot syntax does.

### Actual behavior

The following causes an exception (where the page reference field is name 'article_regions'):

    $pages->findRaw("template=article", [ "title", "article_regions" => [ "id", "title" ] ]);

Exception:

    Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list' on line: 166 in /home/273028.xxxxx/public_html/wire/core/WireDatabasePDOStatement.php

Note that the following works as expected:

    $items = $pages->findRaw("template=article", [ "title", "article_regions.id", "article_regions.title" ]);

### Setup/Environment

ProcessWire: 3.0.184
PHP: 7.2.34

**Comment by ryancramerdesign** [comment]
@billhemsley I can't duplicate this one, but it looks like you are using an old version. Can you again using the dev branch?

**Comment by billhemsley** [comment]
@ryancramerdesign I'll try that and report back.

**Comment by matjazpotocnik** [comment]
@billhemsley any update on this?
