### ISSUE TITLE
`zeroNotEmpty` option of the `FieldtypeInteger` does not limit the matching to empty values only.

### ISSUE THREAD

**Issue by dadish** [processwire/processwire-issues#1567]
### Short description of the issue

When the `zeroNotEmpty` option of the `FieldtypeInteger` is turned on. The selector for empty value includes the `0` values too.

### Expected behavior

For example if I create a field `year` of type `Integer` and choose `No - Blank and 0 have different meanings` option. Add that field to `basic-page` template. The selector `template=basic-page, year=""` should match only pages with empty values for the field `year`.

### Actual behavior

It matches both the pages with `0` value for `year` field and the pages with empty value for the field `year`.

### Optional: Screenshots/Links that demonstrate the issue

<img width="1617" alt="Screen Shot 2022-05-16 at 10 10 34" src="https://user-images.githubusercontent.com/2578542/168529910-fd6cbe23-60fe-46bf-886e-6a5117912158.png">
<img width="1624" alt="Screen Shot 2022-05-16 at 10 11 01" src="https://user-images.githubusercontent.com/2578542/168529935-d78652de-84d3-4b2a-a337-e49c1e219518.png">

### Optional: Suggestion for a possible fix

Don't have a solution atm. But I was able to pinpoint the bug to the specific commit.

Commit that introduced the bug: `d4db88ec7b9ad051740ff74271378b853d8aea28`
Commit right before it that works as expected: `2b69123f598ac7893ee7b483ce9ed6372bae5a1a`

Will update with a possible solution later when/if I have time to figure it out.

### Steps to reproduce the issue

1. Setup a new processwire installation with the default profile.
2. Create a `year` field with type `FieldtypeInteger`. Choose `No - Blank and 0 have different meanings` option in the **Details** tab in the field's settings.
3. Add the `year` field into `basic-page` template.
4. Edit "Child page example 1" and "Child page example 2" pages and set `0` for the field `year` and save those pages.
5. Go to page lister and select `template=basic-page, year=""`. (see screenshot above)
6. Confirm that the result includes the "Child page example 1" and "Child page example 2" pages, even though their `year` field is not empty.

### Setup/Environment

* ProcessWire version: 3.0.200
* (Optional) PHP version: 7.4.29
* (Optional) MySQL version: 10.6.5-MariaDB
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Nothing added. Default profile.

### Related Issues 

#1518

**Comment by ryancramerdesign** [comment]
@dadish Thanks, I've pushed a fix for this on dev

**Comment by dadish** [comment]
Confirmed! Thank you for the quick fix!
