### ISSUE TITLE
Duplicate field action doesn't work correctly for fieldsets

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1568]
### Short description of the issue

For FieldtypeFieldsetOpen, when using the "Duplicate/clone this field?" option on the Actions tab of Edit Field you do not end up with a new fieldset open/close pair. Instead it seems that the close part of the original pair gets associated with the new fieldset and lost from the original fieldset.

Before:
![2022-05-18_113311](https://user-images.githubusercontent.com/1538852/168929655-42775a7e-6fc9-4cf4-a46b-05a199bbc710.png)

Cloning:
![2022-05-18_114455](https://user-images.githubusercontent.com/1538852/168929768-c854bf34-e391-49b1-a37c-882c4fb3b5fb.png)

After:
![2022-05-18_113836](https://user-images.githubusercontent.com/1538852/168929699-13557f8f-ca3a-445d-8be8-9ed064cae2a5.png)

### Setup/Environment

* ProcessWire version: 3.0.200

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
@ryancramerdesign in my testing, the cloned fieldset_END is created, but it's missing tags.

**Comment by matjazpotocnik** [comment]
Just an observation: if I clone fieldset_END, a matching new fieldset (open) is not created. Should it be?

**Comment by Toutouwai** [comment]
I can confirm what @matjazpotocnik said about the missing tags. See screenshot after duplicating the fieldset:

![2022-05-22_094006](https://user-images.githubusercontent.com/1538852/169669842-6b4bce49-dcdc-422f-943c-876714af2e01.png)

As a more general thing, maybe it would be better if the _END part of fieldset pairs didn't appear in ProcessField? I can't think of a scenario where it would be useful to edit or do anything with the _END part separate from the FieldsetOpen.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @Toutouwai I've pushed an update that also clones the tags with fieldset_END fields, but also agree there's no reason for these fields to even be visible/editable. So I've set it to hide them unless showing system fields or config.advanced is true (just in case they are needed for some reason).
