### ISSUE TITLE
Error while uploading files with only non-ANSI names

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#157]
### Short description of the issue

Error while uploading files with only non-ANSI names via admin.

### Expected behavior

Files should be uploaded without errors and their names should get transliterated.

### Actual behavior

When I try to upload a file that contains no ANSI characters in admin on a Linux server , I get an error `Unable to move uploaded file to: ...` If I have at least 1 ANSI character, everything after that character in a filename will get transliterated and the file will be uploaded correctly. On Windows localhost everything works without errors.

I think this case is similar to the one described [here](https://processwire.com/talk/topic/8105-unable-to-upload-an-image-with-non-ascii-chinese-characters/#comment-92709).

### Steps to reproduce the issue

1. Upload a file with a name like this: `привет.jpg` - get an error.
2. Upload a file with a name like this: `привет мир.jpg` or `привет_мир.jpg` - a file gets uploaded with the name `mir.jpg`. Note that the 1st word does not get transliterated and is simply gone.
3. Try no. 2 on Windows - a file gets uploaded with the name `privet_mir.jpg`

### Setup/Environment

* ProcessWire version: 3.0.45
* OS: Linux

**Comment by matjazpotocnik** [comment]
I tried this on linux box (PHP Version 7.0.8-3ubuntu3) and it's working for me. But it could be php basename bug. What do you get if you run:

```
var_dump(explode(";", setlocale(LC_ALL, 0)));
echo basename("привет.jpg\n");

setlocale(LC_ALL,'en_US.UTF-8');
echo basename("привет.jpg\n");
```

**Comment by ivangretsky** [comment]
I get this (with <br\>s):
```
array(1) { [0]=> string(1) "C" }
.jpg
привет.jpg 
```

**Comment by matjazpotocnik** [comment]
Locale should be set on the server, like in /etc/apache2/envvars, where I uncommented this line:

`#. /etc/default/locale`

Then you have to set system locale (this example is for Slovenia):

`update-locale LANG=sl_SI.UTF-8`

Commands may vary depending on you OS. I guess you could also set locale in config.php?

**Comment by ivangretsky** [comment]
I am on shares hosting platform so it is not that easy to change locale on the server.

I did put `setlocale(LC_ALL,'en_US.UTF-8');` in config.php. That did solve the initial issue with image uploads. I do not know if it will affect anything else. If anyone could give recommendation what [locale category and locale setting](http://www.php.net/setlocale) it is safe to set system wide, would appreciate it. 

I wonder if this is anywhere in the installation instructions. Probably should be there.

**Comment by ryancramerdesign** [comment]
When I upload a file named `привет.jpg` it uploads normally, and the resulting filename is `privet.jpg`. This is on a blank profile with no multi-language modules installed. As a result, I'm not exactly sure how to duplicate this one?

**Comment by matjazpotocnik** [comment]
@ryancramerdesign you failed to duplicate the issue because your apache is set as it should be :-) that is you have set locale correctly. Possible solution for basename bug (yes, it's a bug) would be replacing all basename calls with something similar to this (found somewhere on net):

```
function wireBasename($path, $suffix = '') {
  $separator = " qq ";
  $path = preg_replace("/[^ ]/u", $separator."\$0".$separator, $path);
  $base = basename($path);
  $base = str_replace($separator, "", $base);
  if($suffix !== '') $base = rtrim($base, $suffix);
  return $base;
}
```
But I guess that would be too much. I would rather write this somewhere in the "manuals" or maybe even check in install.php and issue a warning.

**Comment by ivangretsky** [comment]
It seems to be dependent on locale settings. I would gladly provide any info that is needed.

**Comment by ryancramerdesign** [comment]
Thanks guys. When you say it's a bug, are you saying it's a PHP bug? If so, what's the best way to detect it? (version specific?) I'd rather detect rather than replace a fast native PHP function, if possible.

**Comment by matjazpotocnik** [comment]
Yes, it's PHP bug, even in 7.1.2, after all this years...

The actual culprit is that php_basename() uses mblen() if available, and that is locale dependend. If an invalid character is passed to mblen(), -1 is returned, and the length is assumed to be 1, what appears to be doubtful. Bailing out returning FALSE, or at least a notice/warning might be more useful.

As of November 2010 it is documented[1]:

| basename() is locale aware, so for it to see the correct basename with multibyte character paths, the
| matching locale must be set using the setlocale() function.

So clearly, setting the appropriate locale is the job of callers of basename().

Source: https://bugs.php.net/bug.php?id=62119

pathinfo() is also problematic, possible solution:

```
function wirePathinfo($path, $options = null) {
  $result = pathinfo(' ' . $path, $options);
  return substr($result, 1);
}
```
or
```
function wirePathinfo($path, $opt = "") {
    $separator = " qq ";
    $path = preg_replace("/[^ ]/u", $separator."\$0".$separator, $path);
    if ($opt == "") $pathinfo = pathinfo($path);
    else $pathinfo = pathinfo($path, $opt);

    if (is_array($pathinfo)) {
      $pathinfo2 = $pathinfo;
      foreach($pathinfo2 as $key => $val) {
        $pathinfo[$key] = str_replace($separator, "", $val);
      }
    }
    else if (is_string($pathinfo)) $pathinfo = str_replace($separator, "", $pathinfo);
    return $pathinfo;
  }
```
Source: http://stackoverflow.com/questions/4451664/make-php-pathinfo-return-the-correct-filename-if-the-filename-is-utf-8

**Comment by ivangretsky** [comment]
That's what people suggest to check locale in php (both links are about the same):
http://stackoverflow.com/questions/27983867/exists-getlocale-method-in-php
http://stackoverflow.com/a/3386589/5036469

**Comment by ryancramerdesign** [comment]
I don't want to introduce replacements to PHP's basename() and pathinfo() functions to account for a PHP bug, or a locale that's going to break these functions and who knows what else, it seems like going down the wrong road. Instead, I'd rather detect it and show some kind of warning, or maybe auto-adjust the locale to something that will work. @ivangretsky I'm not sure I understood the links you mentioned. They outlined how to detect locale, but I'm not really sure what to do with it from there. What locales would we need to detect as invalid before issuing a warning or a  `setlocale(LC_ALL,'en_US.UTF-8');`?

**Comment by ivangretsky** [comment]
In my case I get just `C` - which seems to mean ["use whatever locale is hardcoded"](http://stackoverflow.com/questions/5231620/what-does-set-localelc-ctype-c-actually-do). 
My guess is that some sort of  `LC_CTYPE=[something here].UTF-8` should be present, so it is possible to check against it, but I got no experience in this area, so double check that.

**Comment by matjazpotocnik** [comment]
Do not set the locale but instead issue a warning (at the install time?) that the user should take care to set the proper locale either on the server or in /site/config.php.
```
$l = setlocale(LC_CTYPE, "0");
if($l === false || $l == "C") -> issue warning 
```
Windows use different languages code from Unix!

**Comment by ivangretsky** [comment]
Installation time might not be enough (like in my case). One might develop locally, where everything is ok.

**Comment by ryancramerdesign** [comment]
> Do not set the locale but instead issue a warning (at the install time?) that the user should take care to set the proper locale either on the server or in /site/config.php.

I'm thinking I'll add this as one of our post-login checks. That's where we perform other kinds of checks, like permission issues or the like. Doing it at install time isn't ideal just because most people develop locally and then migrate to a production server, where the installer never gets run. That's why post-login is when I do these kinds of checks. 

Thanks for the code suggestion, I'll apply that. Just to confirm, the setlocale(LC_CTYPE, "0"); doesn't change anything about the locale?

> Windows use different languages code from Unix!

Can you expand on this? Thanks.

**Comment by matjazpotocnik** [comment]
post-login checks looks fine to me.

If locale is "0", the locale setting is not affected, only the current setting is returned, so it's safe to use.

Windows doesn't support multi-byte character sets so you have to use [language]_[country].[code_page] syntax:
```
setlocale(LC_ALL, "sl_SI.UTF-8"); // return false
setlocale(LC_ALL, "Slovenian_Slovenia.1250") // ok

setlocale(LC_ALL, "nl_NL.UTF-8"); // return false
setlocale(LC_ALL, "Dutch_Netherlands.1252"); // ok

setlocale(LC_ALL, "en_US.UTF-8"); // return false
setlocale(LC_ALL, "en-US"); // ok
setlocale(LC_ALL, "English"); //ok
setlocale(LC_ALL, "English_United States.1252"); // ok
```
On Windows, setlocale(LC_ALL, "") sets the locale names from the system's regional/language settings (accessible via Control Panel). I'm really not an expert on this, it's rather confusing to me, but I was bitten by basename bug when I was playing around trying to retain non-ascii characters when uploading files, see https://github.com/processwire/processwire-requests/issues/56

**Comment by ryancramerdesign** [comment]
Thanks guys. Here's what I've got based on what I understand so far. Does this look about right for a post login check?
~~~~~
$locale = setlocale(LC_CTYPE, "0");
if($locale === false || $locale == "C") {
  $s = strpos(PHP_OS, 'WIN') === 0 ? 'en-US' : 'en_US.UTF-8';
  $this->error(
    $this->_('Warning: your server locale is undefined and may cause issues.') . ' ' . 
    sprintf($this->_('Please add this to /site/config.php file (adjust “%s” as needed):'), $s) . ' ' . 
    "setlocale(LC_ALL,'$s');"
  );
}
~~~~~

**Comment by matjazpotocnik** [comment]
It looks fine to me. Maybe  use $this->warning instead of $this->error ?

**Comment by ivangretsky** [comment]
Looks good. Will be happy to test it.

**Comment by ryancramerdesign** [comment]
In testing here, it looks like this doesn't work. I got the warning right upon login, because it turns out "C" is my locale here on my dev environment. But no problems uploading and transliterating the привет.jpg file. So there must be something else to it?

**Comment by matjazpotocnik** [comment]
Hm, I just tested on linux server (php 7.0.7, Debian 2.6.32, Apache2) that has "C" as locale and basename("привет.jpg") is returning ".jpg". Setting the locale to "en_US.UTF8" solved the problem. It looks like it could be the combination of factors that affect the outcome of basename() ? Maybe OS, apache version, some other system specific settings? How about this:
```
if(basename("п") != "п") {
  // it could be any UTF-8 character, as long as it's on the first position in the string
  $s = stripos(PHP_OS, 'WIN') === 0 ? 'en-US' : 'en_US.UTF-8';
  $this->warning(
    $this->_('It looks like your server locale is undefined and may cause issues.') . ' ' . 
    sprintf($this->_('Please try adding this to /site/config.php file (adjust “%s” as needed):'), $s) . ' ' . 
    "setlocale(LC_ALL, '$s');"
  );
}
```

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik this looks like a good solution! Just curious why are you using "\xc2\xa7" rather than the "п" or "§" (or whatever that string maps to)? Our source files are UTF-8 so shouldn't need to encode this, but wanted to make sure I understood.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, some files are UTF-8 encoded and some are not, so "\xc2\xa7" is the safest approach.

**Comment by ryancramerdesign** [comment]
Okay thanks, makes sense. If we've got any non-UTF-8 files left, that means they are very old. This particular file is UTF-8 encoded, so I'm just going to keep it simple. Mainly wanted to make sure it wasn't specific to some other weird basename behavior we needed to account for. I usually try and avoid any kind of encoded text in PHP code. It's one of those things my tools flag for a closer look in security scans of PHP files (my part time job is helping people fix their hacked WordPress installs, heh).

**Comment by matjazpotocnik** [comment]
@ryancramerdesign , had a case (https://github.com/processwire/processwire-issues/issues/184) where putting the proper setlocale() to /site/config.php didn't work, I had to put setlocale() to /site/templates/admin.php . I have no idea why /site/config.php wasn't good enough.

**Comment by LostKobrakai** [comment]
What about init.php / ready.php? They're as well loaded later than config.php.

**Comment by matjazpotocnik** [comment]
It's working with both files.

**Comment by matjazpotocnik** [comment]
Another installation (https://processwire.com/talk/topic/15515-has-anyone-installed-processwire-on-amazon-ec2/?do=findComment&comment=138928) where placing setlocale() in config.php worked. I'm really interested to know why it didn't work for @jacmaes

**Comment by LostKobrakai** [comment]
Having a multi language installation does call setlocale as well (in one of the language support modules). Maybe that's the difference here.

**Comment by matjazpotocnik** [comment]
Aha! Yes, that's it, LanguageSupport.module:

```
$locale = $this->_('C'); // Value to pass to PHP's setlocale(LC_ALL, 'value') function when initializing this language // Default is 'C'. Specify '0' to skip the setlocale() call (and carry on system default).
if($locale != '0') setlocale(LC_ALL, $locale); 
```

Now, how should we deal with that?

**Comment by matjazpotocnik** [comment]
This is now fixed. @ivangretsky can you close this issue?
