### ISSUE TITLE
ProcessPageExportImport.module needs wireCount on line 810

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1572]
### Short description of the issue

https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/Process/ProcessPagesExportImport/ProcessPagesExportImport.module#L810

### Expected behavior

It works without error

### Actual behavior

It throws the [count(): Argument #1 ($var) must be of type Countable|array] error

**Comment by BernhardBaumrock** [comment]
@adrianbj is this related? https://github.com/processwire/processwire/pull/225

**Comment by adrianbj** [comment]
@BernhardBaumrock - it's the same error. I actually just found another one in Profields Table as well.

Remember that these errors were really prevalent when PHP 7.2 was first released. Ryan fixed most of them with the new `wireCount()` function, but there are obviously some still lingering.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've fixed that line
