### ISSUE TITLE
Templates with a digital name suggested to create indefinitely

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#1573]
### Short description of the issue

Templates with a digital name suggested to create indefinitely.

### Expected behavior

If you create a file in the templates folder with the name "404" or any other ("200", "300", "11", etc.), go to the "Templates" section and click add, the system will detect a file without a template and prompts you to create it. After creating a template in the system, it is still suggested to create a template with the names "404", "200", etc.

I can’t say exactly when this problem appeared, but earlier it was possible to create a template with the name 404 and there were no problems.

### Optional: Suggestion for a possible fix

In file /wire/modules/Process/ProcessTemplate.module function ___executeAdd() uncomment string:
`if(count($templates->find("name=$basename"))) continue;`

### Steps to reproduce the issue

1. Create file with name 404.php in templates folder
2. Go to Template system folder and add new template 404
3. Go to Template folder again and click to add

### Setup/Environment

SERVER DETAILS
ProcessWire: 3.0.200
PHP: 7.4.28
Webserver: nginx/1.21.6
MySQL Server: 5.7.37
MySQL Client: mysqlnd 7.4.28

**Comment by matjazpotocnik** [comment]
@ryancramerdesign I can duplicate. Looks like `$templates->get('100')` returns null even when the template exist - '100' is most likely interpreted as 'id=100' instead 'name=100'. `$config->useLazyLoading = false;` also helps.

**Comment by matjazpotocnik** [comment]
https://github.com/processwire/processwire-issues/issues/1588

**Comment by matjazpotocnik** [comment]
@germankirichenko as Ryan explained in issue 1588, creating a digit-only template was not intentional and is now disabled in PW 3.0.209. If you create a file in /site/templates with a name consisting only of digits (numbers), like 100.php, then go to templates and add a new template, 100 is not shown on the list of found template files.
