### ISSUE TITLE
Switching FieldtypePageTitleMultilanguage to FieldtypePageTitle renders wrong input when within image/file custom fields. 

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#1575]
### Short description of the issue

The scenario is: You have an "image" field with custom fields in template "field-image", specifically the PageTitle field. If you switch the title field back to use FieldtypePageTitle (you want to remove the multilanguage feature), the data is then read as something like "array-2" or "array-1" which I guess it's echoing the array data in the filedata column under the "field_image" table.  This seems to happen with the PageTitle field only, although I only tested with a textarea field and that one seemed to work okay when turning off the FieltypeMultilanguage. 

### Expected behavior

Default language value should show up?

### Optional: Screenshots/Links that demonstrate the issue

<img width="1186" alt="Screen Shot 2022-05-25 at 9 07 15" src="https://user-images.githubusercontent.com/7674567/170282045-46bb407d-02cb-4193-904f-4ff86c52bde6.png">

* ProcessWire version: 3.0.200
* PHP version: 7.3
* Tested on a clean install

**Comment by ryancramerdesign** [comment]
@elabx Thanks I've pushed a fix for this.

**Comment by elabx** [comment]
I can confirm this fixed in ProcessWire version 3.203.
