### ISSUE TITLE
getModuleInfo Alternative Methods not Correctly Applying Module Title

### ISSUE THREAD

**Issue by BrendonKoz** [processwire/processwire-issues#1576]
### Short description of the issue

While beginning the development of a module ("Description List"), I decided to use the JSON file method of providing module info instead of the static getModuleInfo method. In doing so, and upon installing and testing out adding a new field with my Fieldtype, I noticed that the name of the field was, "FieldtypeDescriptionList," instead of the provided title within the JSON file of simply, "Description List". Both the JSON and *.info.php methods of providing this information created this result. The static getModuleInfo worked as expected, however.

### Expected behavior

I would have expected these methods to provide the same functionality as the getModuleInfo, where the labelled name of the Fieldtype was the nicely formatted version, as provided in the value of the title property.

### Actual behavior

It seems as though the fallback of the className is used to label the fieldtype in the PW admin.

### Optional: Screenshots/Links that demonstrate the issue

When using either the ModuleName.info.php or ModuleName.info.json method:

![image](https://user-images.githubusercontent.com/194731/170305624-fc882ca4-79be-42bd-8b8b-a9671c7b7f95.png)

When using the getModuleInfo method, directly within the Fieldtype.

![image](https://user-images.githubusercontent.com/194731/170309163-4466a07b-3ed3-4fd5-bf97-fa166f6aa879.png)

### Steps to reproduce the issue

1. Replace any module's getModuleInfo method with the alternate option of providing module information (external JSON or PHP file)
2. Clear the compiled files cache (under Site Modules in PW admin)
3. View the "Type" selection of any of the adjusted module's associated fields in the PW admin

Example PHP and JSON as used for my module (to verify formatting issues, if any):

**FieldtypeDescriptionList.info.json:**
```json
{
    "title": "Description List",
    "version": "0.0.1",
    "summary": "Field that stores data for a representation of the HTML definition/description list element.",
    "author": "Brendon Kozlowski",
    "icon": "",
    "autoload": false,
    "singular": true,
    "permanent": false,
    "requires": [
        "PHP>=5.6.0",
        "ProcessWire>=3.0.0"
    ],
    "installs": [
        "InputfieldDescriptionList"
    ],
    "requiredBy": [
        "InputfieldDescriptionList"
    ]
}
```

**FieldtypeDescriptionList.info.php:**
```php
<?php namespace ProcessWire;
$info = array(
    'title' => 'Description List',
    'version' => "0.0.1",
    'summary' => 'Field that stores data for a representation of the HTML definition/description list element.',
    'author' => 'Brendon Kozlowski',
    'icon' => null,
    'autoload' => false,
    'singular' => true,
    'permanent' => false,
    'installs' => 'InputfieldDescriptionList',
    'requiredBy' => 'InputfieldDescriptionList'
);
```

### Setup/Environment

* ProcessWire version: 3.0.200
* UIKit admin theme
* (Optional) PHP version: 8.0.18
* (Optional) MySQL version: 8.0.28

**Comment by ryancramerdesign** [comment]
Thanks @BrendonKoz I've pushed a fix for this issue

**Comment by BrendonKoz** [comment]
Tested and this does fix the issue. Thanks, Ryan!
