### ISSUE TITLE
"Use fewer pages for storage" option doesn't seem to be working

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1580]
### Short description of the issue

When I check the "Use fewer pages for storage" option on a RM field (sorry, didn't test a normal repeater), several "repeater" pages are still created under Admin > Repeaters as soon as I create a new main page - right after the very first save.

### Expected behavior

No additional pages created

### Actual behavior

I am seeing a "main" repeater page, as well as sub repeater pages for repeater fields within the RM field.

I noticed this because I was dumping `$event->arguments[0]->id` on a `Pages::added` hook and I am seeing several entries.

**Comment by ryancramerdesign** [comment]
@adrianbj It will still create a main repeater page as well as parents for fields (pages with name "for-field-..."). What the option should prevent is the creating of parents for each page having the field (pages with name "for-page-..."), at least until the page has one or more repeater items.
