### ISSUE TITLE
`id.sort` omits all other results

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#1581]
### Short description of the issue

When using `id.sort` in a selector only results with the given ids are returned.
That might have been desired, I found it unintuitive however.

### Expected behavior

I expected the given ids to be at the beginning of the result set and the other results following after.

### Actual behavior

Actually the given ids are the only results returned.

### Example to demonstrate the issue

~~~
wire('pages')->find('template=basic-page,limit=15'); // returns 15 pages

wire('pages')->find('template=basic-page,limit=15,id.sort=71|89'); // I would expect to return 15 pages with page id 71 being the first and 89 being the second. instead just 2 pages are returned
~~~

### Optional: Suggestion for a possible fix

In MySQL it is possible to sort by ID. 

~~~
SELECT * FROM `pages` ORDER BY id = 71 DESC, id = 89 DESC;
~~~

**Comment by MrSnoozles** [comment]
This issue can be closed, if the behavior should stay like it currently is. I just wanted to share my expectations.

**Comment by ryancramerdesign** [comment]
@MrSnoozles This can be thought of kind of like an `id=71|89` in your selector, in that it's saying "match these page ids". The `id.sort` is just an extension of that, saying "match these pages and in this order".  For your case, I would suggest removing the "id.sort" entirely and just prepending the two pages you want at the beginning after completing your find().
