### ISSUE TITLE
Argument #1 ($value) must be of type Countable|array, null given in Repeater Matrix via ProcessPageEditImageSelect

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1584]
### Short description of the issue

The error above appears when opening the Image Insert button on a CkEditor field.

### Expected behavior

No error

### Actual behavior

The problem seems to occur when there is an image field (set to 1 max files) on on of the RM types, but you're editing a different RM type which has an images field (set to 0 max files), or perhaps with no images field at all. 

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/173130214-8ca9f983-55ce-494b-859a-f33c01bd63e6.png)

### Optional: Suggestion for a possible fix

The key thing is that this foreach: https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/Process/ProcessPageEditImageSelect/ProcessPageEditImageSelect.module#L498 includes the "image" field, but here: https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/Process/ProcessPageEditImageSelect/ProcessPageEditImageSelect.module#L503 the `$page->get($field->name)` returns null. I'm not sure `wireCount()` is the best solution here - I feel like it needs fixing properly so the list of fields to foreach is limited.

### Steps to reproduce the issue

1. A RM field with one type with a 0 maxFiles "image" field and another type with an CkEditor and an "images"
2. Open the image insert dialog on the Ckeditor field

**Comment by adrianbj** [comment]
FYI - `wireCount()` does prevent the error and get the dialog working again, so that's what I am doing for now, but still not sure it's the correct approach.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for that issue. Using wireCount() is is exactly what's needed since single image fields can either be a Pageimage or null, and PHP's count() no longer likes null.
