### ISSUE TITLE
InputfieldSelector's $showInitValue setting doesn't do anything

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#159]
### Short description of the issue

The `$showInitValue` setting doesn't appear to be used anywhere. It is set to false by default, but never evaluated to show the non-modifiable inputs for the initValue like it is supposed to.

### Expected behavior

It should show the non-modifiable inputs for the initValue

### Actual behavior

Shows nothing

### Setup/Environment

* ProcessWire version: 3.0.48

**Comment by ryancramerdesign** [comment]
This was an idea being considered at the time of original development, but in the end decided not to implement. I'll remove the reference to it. Thanks.

**Comment by adrianbj** [comment]
Would you consider adding this functionality at some point - it could be very handy in many scenarios. Is it a priority/time issue, or do you think it's just not a good idea?
