### ISSUE TITLE
MarkupPagerNav anomalous(?) output

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1591]
#### Screenshots 1
the 2nd pager is built with MarkupPagerNav: a separator appears between 9 and 10
![markup-pager-nav-2](https://user-images.githubusercontent.com/3229979/175837764-e897cf80-5547-45be-b2e5-49f5c84bae4a.png)

#### Screenshots 2
the 2nd pager is built with MarkupPagerNav
I have adapted very old custom paginator class for pw (1st pager).: current page is in the middle (because I always use odd number of num links, looks better) of visible page-links (I do not use separators and show first/last links as arrows before and after other links)
![markup-pager-nav-1](https://user-images.githubusercontent.com/3229979/175837708-40d0cf78-a828-4593-9c25-757869fc6bf9.png)

### Steps to reproduce the issue
Render a paginated page array (total-items=100, per-page=10) using MarkupPagerNav with for instance 3 numPageLinks

### Setup/Environment
* ProcessWire 3.0.200:
* PHP version:  7.4

kind regards

**Comment by pine3ree** [comment]
Hello @ryancramerdesign ,

I was able to solve this but I rewrote half+ of the PagerNav class? Should I open a PR or copy+paste here the code?
kind regards

**Comment by matjazpotocnik** [comment]
@pine3ree some improvements to MarkupPagerNav are [commited ](https://github.com/processwire/processwire/commit/42e56c5f3e0e61e9c55ec5014dcbfec374668519) recently ...

**Comment by pine3ree** [comment]
Thanks @matjazpotocnik, I will take a look on my next pw project. kind regards.

**Comment by matjazpotocnik** [comment]
@pine3ree did you have a chance to take a look?

**Comment by pine3ree** [comment]
Hello @matjazpotocnik ,

sorry I haven't . I have been mostly working with framework base projects in the latest months.
But I can close the issue since you confirmed that some enhancements were commited into latest releases. Anyway it's also easy to customize and/or extends. ..and since Ryan's comment: https://github.com/processwire/processwire/pull/232#issuecomment-1397221226. Cheers!!!
