### ISSUE TITLE
Decimal field formatting is not consistent

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1594]
### Short description of the issue

In the screenshot below, the "Price" and "Ten price" fields have identical configurations, with two digits present after the decimal.

![2022-07-07_145603](https://user-images.githubusercontent.com/1538852/177680849-af598122-e771-49d4-b778-e40332214e1a.png)

The formatting of these decimal values is not consistent. If the rule is "redundant decimal places are not shown" then the values shown should be "8" and "7.2", or if the rule is "redundant decimal places are shown" then the values shown should be "8.00" and "7.20".

The formatting should follow a consistent rule, and it would be great if this was a configurable option. Using a decimal field for prices will be a really common need, and often it will be desirable to always show the decimal places, e.g. "8.00".

And this falls into the category of request rather than issue, but given that prices are a common need it would be handy to have the option to prefix the inputfield with a currency symbol, e.g. 

![2022-07-07_150242](https://user-images.githubusercontent.com/1538852/177681691-90f21b2d-1e0c-46c0-a384-7f4666ed44b8.png)

### Setup/Environment

* ProcessWire version: 3.0.201

**Comment by szabeszg** [comment]
> And this falls into the category of request rather than issue,

Let me disagree please :) Let's say this is not a bug per se but definitely an issue to solve. Thank you for reporting it, btw!

**Comment by BernhardBaumrock** [comment]
It would be great if the decimal field could be improved in general :) #1341

**Comment by teppokoivula** [comment]
> And this falls into the category of request rather than issue, but given that prices are a common need it would be handy to have the option to prefix the inputfield with a currency symbol, e.g.

While I also feel that this is more of a feature request than an issue, I do agree that it's a common need — but just to add a bit of nuance: correct placing depends at least on currency and language. € sign, for an example, [is prefixed to the sum in English, while in (most) other languages (such as Finnish) it is added as a suffix](http://publications.europa.eu/code/en/en-370303.htm#position). If currency prefix gets added, I would suggest also adding an option for suffix.

That being said, it would be nice to have a global prefix/suffix option for inputfields. This is relevant for many non-currency situations as well :)

**Comment by Toutouwai** [comment]
For anyone wanting a quick solution I'm using a hook for now:

```php
// Format decimal price fields and add currency symbol prefix
$wire->addHookAfter('InputfieldFloat::renderReadyHook', function(HookEvent $event) {
	/** @var InputfieldFloat $inputfield */
	$inputfield = $event->object;
	$field = $inputfield->hasField;
	if($field && in_array($field->name, ['price', 'ten_price'])) {
		$inputfield->prependMarkup = '<span class="units">$</span>';
		if($inputfield->value) {
			$inputfield->value = number_format($inputfield->value, 2);
		}
	}
});
```

**Comment by ryancramerdesign** [comment]
@Toutouwai I've pushed an attempted fix for this one. Does it seem to resolve the issue there too? This is the sort of thing that can be affected by locale and decimal type so want to make sure I'm also not introducing any new issues for others.

**Comment by Toutouwai** [comment]
@ryancramerdesign, that fix is working here, thanks.
