### ISSUE TITLE
$sanitizer markupToText times out if 'newline' option is either '' or false

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1595]
Either of these will time out:
```
wire('sanitizer')->markupToText($mymarkup, ['newline'=>''])
wire('sanitizer')->markupToText($mymarkup, ['newline'=>false])
```

In my case however I realized I needed ' ' (not '') which works fine.

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I've pushed a fix for this. The newline value has to be a string and it can't be a blank string, so I have updated it so that it converts an empty value to a space.
