### ISSUE TITLE
Can't configure complex fields (eg Options) from Templates "create a new field" link.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#16]
> Briefly describe the issue.

The second time you click the save button, the field creation modal closes before you can adjust additional settings on the Input tab that weren't available until after the second save.

> What did you expect to happen?

I should be able to save as many times as needed before adding to the template and closing the modal

> What did actually happen?

Modal closes and adds the field, but I need to go back to fields to do final config.

> Optional: Do you have screenshots/links that demonstrate the issue?

Your screenshots/links go here.

> Optional: Have you a suggestion for a possible fix?

https://github.com/processwire/processwire/pull/11

**Comment by ryancramerdesign** [comment]
Adrian, I'll close this one out since we've added your suggested fix.
