### ISSUE TITLE
FileCompiler compiles templates that have the namespace?

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#160]
I started experimenting with PW 3 and namespace. So far I'm noticing something strange I thought it would not do. It compiles all files in template that have ProcessWire namespace. They end up being 1:1 so what's the deal?

* ProcessWire version: 3.0.42
* (Optional) PHP version: 5.6

**Comment by szabeszg** [comment]
This might shed some light on it:
https://processwire.com/talk/topic/13176-session-and-input-variables-in-templates-in-v3/?do=findComment&comment=119300

**Comment by ryancramerdesign** [comment]
The FileCompiler keeps copies of template files even if it doesn't compile them. It does this only for the sake of keeping track and comparing things. You should expect to see copies of your template files in /site/assets/cache/FileCompiler/site/templates/, unless you completely disable it with `$config->templateCompile = false;`. 

If you want to tell if a file is actually getting compiled or not, add `FileCompiler=?` somewhere in your output. If the file is compiled, it will change to `FileCompiler=Yes` in your output. If the file is not getting compiled, then it will remain as `FileCompiler=?`.
