### ISSUE TITLE
Installation error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'SystemUpdater' for key 'modules.class'

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1601]
When doing a fresh install of PW 3.0.203 using PHP 8.1 and MySQL 8, I get this error:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'SystemUpdater' for key 'modules.class'`

The installation went through fine however.

See attached screenshot.

![Untitled-4](https://user-images.githubusercontent.com/4558/181643193-85d190e8-2aad-450a-a369-87d83403c2ab.jpg)

**Comment by ryancramerdesign** [comment]
@jlahijani I can't duplicate this one. I'm testing with the only core site profile (site-blank). Which site profile did you observe it with?

**Comment by jlahijani** [comment]
I was using blank.  I tried reinstalling again twice with the same settings and slightly different settings but I couldn't reproduce the error again.  Not sure why it happened that one time, but maybe it was something on my end.  Closing.

**Comment by adrianbj** [comment]
Just an FYI that I have seen this randomly before also.

**Comment by ryancramerdesign** [comment]
I'm going to close this for now as it doesn't appear anyone can reproduce it at present. Will keep an ear out in case it turns up again though.
