### ISSUE TITLE
Wrong image width and height on upload

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1602]
### Short description of the issue

Image that demonstrates the problem: 
![pouring-water](https://user-images.githubusercontent.com/1538852/181692178-4fb50873-f0b2-4d72-a2ff-d4680d8a62de.jpg)

When this image is uploaded to a PW images field the width and height are wrongly transposed.

If an image variation is created at the same dimensions as the original then the width and height are calculated correctly.

![2022-07-29_175947](https://user-images.githubusercontent.com/1538852/181692875-7293cb9b-45b2-4a95-91f9-2b1531df3875.png)

I'm guessing this has something to do with the auto-rotation of uploaded images, like PW is calculating the width and height before the uploaded image has been auto-rotated?

### Setup/Environment

* ProcessWire version: 3.0.203

**Comment by Toutouwai** [comment]
After looking at this some more I don't think it's related to auto-rotation on upload but is instead due to PHP's `getimagesize()` not being smart enough to correct the width and height info when the embedded EXIF data indicates a portrait orientation.

A modification to `Pageimage::getImageInfo()` fixes it for me. After [line 509](https://github.com/processwire/processwire/blob/fe9417dcfc42a58362aaf6d528d748d335e30cfb/wire/core/Pageimage.php#L509)...

 ```php
if(function_exists('exif_read_data')) {
	$exif = $filename ? @exif_read_data($filename) : @exif_read_data($this->filename);
	if(!empty($exif['Orientation']) && (int) $exif['Orientation'] > 4) {
		// Image has portrait orientation so reverse width and height info
		$imageInfo['width'] = $info[1];
		$imageInfo['height'] = $info[0];
	}
}
```

The whole modified method...

```php
public function getImageInfo($reset = false) {

    $imageInfo = $this->imageInfo;
    $filename = is_string($reset) && file_exists($reset) ? $reset : '';

    if(!$reset && $imageInfo['width'] && !$filename) {
        return $imageInfo;
    }

    if($this->ext == 'svg') {
        $imageInfo = array_merge($imageInfo, $this->getImageInfoSVG($filename));
    } else {
        if($filename) {
            $info = @getimagesize($filename);
        } else {
            $info = @getimagesize($this->filename);
        }
        if((!$info || empty($info[0])) && !empty($this->sizeOptions['_width'])) {
            // on fail, fallback to size options that were requested for the image (if available)
            $imageInfo['width'] = $this->sizeOptions['_width'];
            $imageInfo['height'] = $this->sizeOptions['_height'];
        } else if($info) {
            $imageInfo['width'] = $info[0];
            $imageInfo['height'] = $info[1];
            if(function_exists('exif_read_data')) {
                $exif = $filename ? @exif_read_data($filename) : @exif_read_data($this->filename);
                if(!empty($exif['Orientation']) && (int) $exif['Orientation'] > 4) {
                    // Image has portrait orientation so reverse width and height info
                    $imageInfo['width'] = $info[1];
                    $imageInfo['height'] = $info[0];
                }
            }
        }
    }

    if(!$filename) $this->imageInfo = $imageInfo;

    return $imageInfo;
}
```

For existing images the incorrect data could still be stored in the width and height database columns after the method is fixed. Is there a way to tell PW to rebuild that stored width/height data in the DB?

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai good find there, I have added your suggested fix
