### ISSUE TITLE
Ajax load option for tabs missing?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1603]
### Short description of the issue

The ability to choose "Closed + Load only when opened (AJAX) †" is no longer available.

### Expected behavior

<img width="388" alt="image" src="https://user-images.githubusercontent.com/871211/181863120-15a485ad-2d2b-4d8f-847a-94c6eb733bd7.png">

### Actual behavior

<img width="385" alt="image" src="https://user-images.githubusercontent.com/871211/181863163-91c1603b-97ce-4aa4-86ab-9928d6e0cdbb.png">

### Optional: Suggestion for a possible fix

Not sure when this started, but my intuition thinks it was probably with the introduction of the new feature that lets a field be a tab without the need for a wrapper FieldsetTabOpen/Close

### Setup/Environment

* ProcessWire version: 3.0.201

**Comment by netcarver** [comment]
I can reproduce this.

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks, I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks Ryan - looks good!
