### ISSUE TITLE
InputfieldPage.js can create invalid urls for use in ProcessPageSearch

### ISSUE THREAD

**Issue by MetaTunes** [processwire/processwire-issues#1605]
### Short description of the issue

ProcessPageSearch.module correctly replaces '-' with '.' (since '.' is not allowed in URL variable names) in line 351 in v3.0.200:
`if(strpos($name, '-')) $name = str_replace('-', '.', $name);`
However, InputfieldPage.js, which, in line 60, builds a selector for submission to ProcessPageSearch, thus:
`var url = ProcessWire.config.urls.admin + 'page/search/for?' + selector + '&limit=9999&get=' + labelFieldName;` 
does not convert '.' to '-' in the selector.

### Expected behavior

InputfieldPage.js should convert '.' to '-' in variable names to create a valid url that will then be correctly converted back by ProcessPageSearch.

### Links that demonstrate the issue

See https://processwire.com/talk/topic/26999-page-field-based-on-parent-in-matrix-or-repeater-field/?do=findComment&comment=225409

### Suggestion for a possible fix

Add the line 
`selector = selector.replace(/\./g, '-');`
after line 56 in InputfirldPage.js

**Comment by ryancramerdesign** [comment]
Thanks @MetaTunes I've added your suggested fix for this.

**Comment by matjazpotocnik** [comment]
@MetaTunes, can you confirm the fix is working for you?

**Comment by MetaTunes** [comment]
Yes - it seems to be working fine now
