### ISSUE TITLE
Pattern/Placeholder not valid for HTML date input

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1608]
https://validator.w3.org/nu/ returns these errors:

Error: Attribute pattern is only allowed when the input type is email, password, search, tel, text, or url.
Error: Attribute placeholder is only allowed when the input type is email, number, password, search, tel, text, or url.

https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/Inputfield/InputfieldDatetime/types/InputfieldDatetimeHtml.php#L69
https://github.com/processwire/processwire/blob/3acd7709c1cfc1817579db00c2f608235bdfb1e7/wire/modules/Inputfield/InputfieldDatetime/types/InputfieldDatetimeHtml.php#L70

These lines should be removed.

**Comment by ryancramerdesign** [comment]
@chriswthomson The validator is correct that date doesn't use those attributes, but it's also assuming the browser recognizes the date type, which is an HTML5 type, and Inputfields also support XHTML and HTML4. Those attributes are there for browsers that do not support the "date" input type, or for non HTML5 markup, where the browser treats "date" as a "text" input. Browsers that support the date input type ignore those attributes just like they ignore `uk-*` attributes or other custom attributes you might add that a validator will correctly note.

**Comment by teppokoivula** [comment]
A bit off-topic, but:

> Those attributes are there for browsers that do not support the "date" input type

My first thought was that "wasn't date supported _everywhere_ like a decade ago", but according to caniuse.com Safari only started supporting this about a year ago. And even now their support is still considered "partial". While not really surprising, that's still a bit disappointing :)

**Comment by matjazpotocnik** [comment]
@chriswthomson @teppokoivula Whta's the status of this issue? Can it be closed?
