### ISSUE TITLE
No multilanguage support for findRaw()

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1609]
### Short description of the issue

The findRaw() function returns only data of the default language. There is no possibility to query the fields explicitly for a language. Would it be possible to introduce this feature? For example, I tried it this way, but it does not work:

```php
$lang_id  = ($user->language->name === "default") ? "" : $user->language->id;
$tags = $pages->findRaw("template=tag", "title{$lang_id}")
```
Results in:
`
Error: Exception: Unknown column/field name(s) for findRaw: title1041 (in wire/core/PagesRaw.php line 1685)
`

### Expected behavior

An option or possibility to get the raw data language dependent.

### Setup/Environment

* ProcessWire version: 3.0.200 Master
* (Optional) PHP version: 7.4

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia Title is held in the "data" or "data1234" column (where 1234 is non-default language ID). So here's how you retrieve that: 
~~~~~
$lang_id  = $user->language->isDefault() ? "" : $user->language->id;
$pages->findRaw("template=tag", "title.data$lang_id")
~~~~~
or you can do this to return all columns from the table, which includes all the languages:
~~~~~
$pages->findRaw("template=tag", "title.*"); 
~~~~~

**Comment by flipzoom** [comment]
Oh man. Thanks Ryan. Makes sense. Sometimes you're on the fence. 🤷🏻‍♂️

**Comment by BernhardBaumrock** [comment]
RockFinder does that out of the box and it does also take care of default fallbacks: https://github.com/baumrock/RockFinder3#multi-language

Maybe that's something that could also be added to findraw? @ryancramerdesign
