### ISSUE TITLE
Default image of an image field deleted when page with that field is deleted

### ISSUE THREAD

**Issue by f-b-g-m** [processwire/processwire-issues#161]
### Short description of the issue
When i delete a page (through api), containing an empty image field, that has a default value and allows only 1 image, the default image is deleted too, just from disk, not database.

### Expected behavior
Page is deleted default image not.

### Actual behavior
Image is deleted too.

### Steps to reproduce the issue
1. Create image field with only one image allowed
2. Give it a default value
3. Delete a page containing that field (should be empty) through api
4. Check default image

### Setup/Environment
Windows 10 x64
* ProcessWire version: 3.0.48
* (Optional) PHP version: 5.6
* (Optional) MySQL version: 5.6.31
* (Optional) Any 3rd party modules: 0

**Comment by ryancramerdesign** [comment]
Thanks @f-b-g-m I have pushed a fix for this issue to the dev branch.
