### ISSUE TITLE
Overwriting `assets` path-variable causes unexpected issues

### ISSUE THREAD

**Issue by tobisalad** [processwire/processwire-issues#1610]
Not really an active issue since I found the problem but I think it should be mentioned in the docs or prevented altogether.

### Short description of the issue

When you overwrite the `assets` path-variable in config.php via `$config->setLocation('assets', 'site/templates/alternative_assets_folder/');` and then try to delete a page that contains a repeater-item that contains an image-field via `$page->delete(true);` you encounter the following Exception/Error: 

```
Call to a member function emptyAllPaths() on null on line: 1693 in [...]/wire/core/PagesEditor.php
```

### Suggestion for a possible fix

Mention it in [the docs](https://processwire.com/api/ref/config/set-location/) or make Processwire notify users when they overwrite an internally used path-variable.

**Comment by ryancramerdesign** [comment]
@tobisalad To be honest I'm not sure to what extent changing the assets path could be successful, but theoretically it should be. The error that you observed here doesn't appear to be related to the assets path and instead related to the fact that `$page->filesManager` is null when a page is deleted, and we still need it to work in this case. I have pushed a fix for this. Thanks.

**Comment by matjazpotocnik** [comment]
@tobisalad does Ryan's fix work for you? If it does, could you close this issue?

**Comment by tobisalad** [comment]
I'd have to set up a dev-installation to check but I'll believe Ryan if he says he fixed it so I'll close it
