### ISSUE TITLE
utf8mb4 191 chars limit

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#1612]
Hello, 

there are a few db columns that use ascii character set:
```sql
templates: `name` varchar(191) CHARACTER SET ascii NOT NULL
fieldgroups: `name` varchar(191) CHARACTER SET ascii NOT NULL
fields: `name` varchar(191) CHARACTER SET ascii NOT NULL
```
for these columns we could skip the 191 limit, even if we will probably never hit it.

**Comment by ryancramerdesign** [comment]
@pine3ree I don't think it's necessary in this case because ProcessWire uses 128 maxlength for most resource names if I'm remembering right, so if anything they could be reduced, but probably safest just to leave them at the current value.

**Comment by matjazpotocnik** [comment]
@pine3ree, Maks, are you ok with Ryan's answer?

**Comment by pine3ree** [comment]
@matjazpotocnik Yes, I forgot to close the issue. Sorry.
