### ISSUE TITLE
Broken link on the CKEditor docs page

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1614]
Since the site-default profile was removed from core, the "ready-to-go mystyles.js" link on the CKEditor docs page (https://processwire.com/docs/fields/ckeditor/) is broken. It should probably link to https://github.com/processwire/site-default/blob/main/modules/InputfieldCKEditor/mystyles.js instead.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula, good find, I have corrected that link.
