### ISSUE TITLE
No index after 99 Elements and black background in Repeater

### ISSUE THREAD

**Issue by gs-df** [processwire/processwire-issues#1617]
### Short description of the issue

When i add the 100th Repeater Element the index counts just to 99 and the repeater element background change from green to black. But the repeater still works.

### Expected behavior

Continue counting over 100 and green background. (Any reason for black background?)

### Screenshots/Links that demonstrate the issue
![repeater-fail](https://user-images.githubusercontent.com/91260858/186684989-ecb49dff-577a-4eb1-bd4f-a65a1e9d05f4.PNG)
![repeater-works](https://user-images.githubusercontent.com/91260858/186684996-26680b20-1f64-44e5-b91e-7e47044423ef.PNG)

### Suggestion for a possible fix
When i comment this code out, it works like expected
Filename: InputfieldRepeater.module
Row: 480 - 489
```
				if(strpos($wrapLabel, '#') !== false && preg_match('/(?<!&)#([0-9a-fA-F]{3,})/', $wrapLabel, $matches)) {
					// background-color definition
					if(strlen($matches[1]) === 3 || strlen($matches[1]) === 6) {
						$wrapLabel = str_replace($matches[0], '', $wrapLabel);
						$typeStyles[$itemTypeName] = 
							".Inputfield_$this->name .InputfieldContent " . 
							".InputfieldRepeaterItem[data-typeName=\"$itemTypeName\"] > .InputfieldHeader " . 
							"{ background-color: #$matches[1]; outline-color: #$matches[1] }";
					}
				}
```

### Steps to reproduce the issue

1. Create Repeater
2. Add 100 Elements
3. Look behavior (No counting over 99 and black background)
4. Remove 1 Element (Green Background again)

### Setup/Environment
* ProcessWire version: 3.0.200

**Comment by ryancramerdesign** [comment]
@gs-df The index number must be confusing the label color configuration option. I think we did recently fix a related issue on the dev branch (maybe in 3.0.201 or 3.0.202) and I suspect this is the same thing. I don't have any installs with 100+ repeater items to test with here but if you get a chance to try the dev branch sometime please let me know if you continue to observe the issue.  Thanks.

**Comment by matjazpotocnik** [comment]
@gs-df, did you test on the latest dev branch?

**Comment by matjazpotocnik** [comment]
@gs-df Closing this now. Post more if it needs re-opening.

**Comment by BitPoet** [comment]
Unless there's side effects in Repeater Matrix that I'm not aware of, swapping the code parts for replacing color and #n in InputfieldRepeater___renderRepeaterLabel() should be enough to fix this.

![repeater-numbers-and-colors](https://github.com/processwire/processwire-issues/assets/3358724/f530e277-f24a-49b3-8dd8-5bc80f51ccc3)

**Comment by ryancramerdesign** [comment]
@BitPoet Thanks, I have added your suggestion for this.

**Comment by matjazpotocnik** [comment]
@BitPoet I'm closing this now. Thanks for the fix!
