### ISSUE TITLE
PNG images throw "File not supported" warning in PHP 8

### ISSUE THREAD

**Issue by Sebiworld** [processwire/processwire-issues#1618]
### Short description of the issue

PNG images throw warnings caused by the freshly integrated use of exif_read_data in PW version 3.0.204. PHP >= 8

### Expected behavior

No warnings. If any image function cannot be done it should return empty data, but not emit any warnings.

### Actual behavior

When I try to do things with Pageimage objects and the underlaying image is a png (maybe other extensions as well), the function throws a warning "exif_read_data(test.png): File not supported" from location /wire/core/Pageimage.php in line 514.

### Optional: Suggestion for a possible fix

I've dug into the research for this problem a bit. It seems that only certain types of images can have exif data at all. And all other file types that the function cannot handle throw warnings. But I could not find a list with all types that are supported yet, or if we could suppress the warning in any way. Warnings are thrown only in PHP versions 8 or higher in my test-system. 

### Steps to reproduce the issue

1. Create an Image field
2. Upload a png image
3. Get the image programmatically as an Pageimage object
4. Call getImageInfo() or any function that uses that (like width() or height())

### Setup/Environment
* ProcessWire version: 3.0.204 (dev)
* PHP version: 8.0.8 or 8.1.1
* $config->debug is true in  config.php

**Comment by Toutouwai** [comment]
This issue relates to changes in PHP >= 8 to how the error suppression  `@` operator is treated. 

https://www.php.net/manual/en/language.operators.errorcontrol.php

Will have implications for many places in the core?

**Comment by Sebiworld** [comment]
@Toutouwai I think so. But I do not completely understand what's the best practice now. 

Do try-catch blocks work better in the exif_read_data case? I think we have a lot of places in the core code where ´@´ does not work as expected anymore. I try to do some experiments when I have spare the time for that...

**Comment by ryancramerdesign** [comment]
@Sebiworld Thanks, of the image formats that PW supports I think that only JPG would support EXIF, so I have added a condition to make it call exif_read_data only if the extension is jpg or jpeg.

**Comment by Sebiworld** [comment]
@ryancramerdesign Thank you! I've tested the current dev version and can confirm that this error is fixed.
