### ISSUE TITLE
Markdown escaping not working in field description/notes

### ISSUE THREAD

**Issue by owzim** [processwire/processwire-issues#162]
### Short description of the issue

Escaping markdown emphasis indicators does not work on field description/notes.

It is however supported by Parsedown:

```php
$modules->get('TextformatterMarkdownExtra')->markdown('\*\*hello\*\*');
```
Renders as \*\*hello\*\*

Perhaps `TextformatterMarkdownExtra` is not even applied.
Setting the formatting via api to the field, does not seem to have an effect:

```php
$field->entityEncodeText = Inputfield::textFormatMarkdown;
$field->save();
```
Although the setting `entityEncodeText` is saved correctly in the fields table, for that field.

Logging, how it is formatted in `Inputfield::entityEncode()` gives me `markdown = true`, although it should yield `8` (the value of `Inputfield::textFormatMarkdown`)

```php
public function entityEncode($str, $markdown = false) {
    if ($this->name === 'title') {
        $this->wire->log(var_export([$this->name, $str, $markdown], true));
    }
// ...
```

### Expected behavior

`Use \*\*bold\*\* for **bold** text`

should render as

Use \*\*bold\*\* for **bold** text

### Actual behavior

`Use \*\*bold\*\* for **bold** text`

renders as

Use \\bold\\ for **bold** text

### Steps to reproduce the issue

1. Escape markdown indicators on any field description/notes
2. Edit a page, where that field is used to see this behavior

### Setup/Environment

* ProcessWire version: 3.0.47

**Comment by LostKobrakai** [comment]
Description/notes do not use markdown. It's only allowing for a small subset of markdown features to be present.

**Comment by kixe** [comment]
@LostKobrakai
Is it planned in the future?
```
	/**
	 * Full markdown support with HTML also allowed
	 * #pw-group-textFormat-constants
	 *
	 */
	const textFormatMarkdown = 8;
```
@owzim 
entityEncodeText is a property of **Inputfield** not of **Field**. You can manipulate it runtime-only (if provided by the Inputfield).
`$field->inputfieldSetting('entityEncodeText',8);`

Unfortunately it is not implement in core Inputfields. If you look for example in InputfieldCheckbox::render() you have only 2 options. Meaning enable the subset as @LostKobrakai mentioned or not.
`$entityEncode = $this->getSetting('entityEncodeText') === false ? false : true;`

**Comment by LostKobrakai** [comment]
I'm not sure. Until now ryan's  argument against full markdown was to keep overhead as low as possible.

**Comment by owzim** [comment]
If it's configurable, the overhead is optional.

**Comment by owzim** [comment]
@kixe, thanks will try that out later.

**Comment by ryancramerdesign** [comment]
That `textFormat` setting is really meant for specific API cases like when you are creating a form for module configuration. But @kixe is right that you can specify it on your own manually via the API perhaps in a hook, and it should work for page editor forms. Though note that it may interfere with some other cases that are expecting the default Inputfield textFormat, so that would be something to watch out for.

**Comment by owzim** [comment]
Thanks to all you three, this is solved then.
