### ISSUE TITLE
PHP Warning when using TextformatterMarkdownExtra (ParseDownExtra.php)

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1621]
### Short description of the issue

```
Warning: Undefined array key "text" in .../wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php on line 249
Warning: Undefined array key "text" in .../wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php on line 213
```

To reproduce this error:
```
$markup = "## Hello World";
$modules->get('TextformatterMarkdownExtra')->format($markup);
```

### Setup/Environment

* ProcessWire version: 	3.0.204
* (Optional) PHP version: 8.0

**Comment by ryancramerdesign** [comment]
@kixe I'm running the same PW version 3.0.204 and PHP 8.0.8, but I can't seem to duplicate here. The line numbers in your error message also don't line up with the relevant lines in the ParsedownExtra.php file. They are quite a few lines off,  so I'm wondering if you might have a modified copy of the ParsedownExtra.php file?  See line [249](https://github.com/processwire/processwire/blob/dev/wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php#L249) and [213](https://github.com/processwire/processwire/blob/dev/wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php#L213). Please let me know what you find. Thanks.

**Comment by kixe** [comment]
@ryancramerdesign I am sorry. For testing purposes I switched to the 0.8.1 branch of parsedow-extra which caused this error.
https://github.com/erusev/parsedown-extra/tree/0.8.x

Regarding PHP 8.1 it might be interesting to check the 2.0 branches

- https://github.com/erusev/parsedown/tree/2.0.x
- https://github.com/erusev/parsedown-extra/tree/2.0.x

**This Issue can be closed.**

**Comment by ryancramerdesign** [comment]
@kixe Thanks, sounds good. I'll check those out too.
