### ISSUE TITLE
Language tab focus is lost after saving

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1622]
### Short description of the issue

Newly, there is the issue that after saving a page, the active language tab does not stay focused, but always falls back to the first language tab. However, I have not been able to pinpoint the problem.

https://user-images.githubusercontent.com/708183/189931412-40e2edb3-eac3-4366-8bf6-35b2b1c91eba.mp4

Here are the possibilities I have already ruled out, or what I have already tested: 

- Browser test: I don't think it's a browser issue as it shows up in all the latest browsers I've tested - FireFox, Chrome, Edge, Chrome mobile, Brave, etc.
- Theme test: the same problem in all three backend themes, default, UiKit and Reno, so the theme is also excluded.
- Browser extensions: extensions such as AdBlocker, Cookie-Blocker, etc. are also excluded and deactivated.
- The problem exists on all my multi-language websites, with completely different modules. There are no overlaps.
- Settings for "JqueryWireTabs.module" -> Remember tab positions between requests? Always or only after submitting the form. Still the problem with both.
- Settings for "LanguageTabs.module" -> Field to use for tab labels -> title or name. Still the problem with both.

### Setup/Environment

* ProcessWire version: 3.0.200 Master
* PHP version: 7.3, 7.4 and 8.1 (Different between the projects)
* Languages Support - Tabs: Core 1.1.5
* jQuery Wire Tabs Plugin: Core 1.1.0

**Comment by BernhardBaumrock** [comment]
Are you using RockMigrations on that site?
https://github.com/baumrock/RockMigrations/blob/main/RockMigrations.js

**Comment by flipzoom** [comment]
Hi @BernhardBaumrock, none of the sites use RockMigrations.

**Comment by matjazpotocnik** [comment]
I don't have multilanguage installation anywhere in production but are you sure the language tabs module should remember language tabs? It will remember the main tabs (Content, Children, Settings, but not Delete), while the active language tab is fetched from the current user language ($user->language). You may also provide an active tab for frontend editing by specifying "language" as a GET parameter (aka <a href='{$config->urls->admin}page/edit/?id=$page->id&language=$user->language'>Edit</a>).

**Comment by flipzoom** [comment]
Hi @matjazpotocnik – Yes, this has been the current behaviour so far. Since the update to 3.0.200, however, the language tabs lose focus after saving. This is otherwise an unwholesome workflow for editors if you have to change the language tab over and over again after each intermediate save. I don't know if the two core modules are connected, I just wanted to test it. The main tabs do not lose their focus, they continue to work and a cookie is set. The language tabs do not.

**Comment by flipzoom** [comment]
I'm a little confused right now. I looked at old installations again and they have the same behaviour. So it's not because of the 3.0.200 update. Either I have been dreaming for years that the LanguageTabs remember the focus or I come from a parallel universe. 👀 I can't find any signs in the code that the LanguageTabs ever behaved like this either. 

That's why I'm turning the BugTicket around: can we implement this feature so that the LanguageTabs also remember the focus like the WireTabs after a submit? @ryancramerdesign @matjazpotocnik 

Just today I had to maintain an incredible amount of content in other languages and I noticed this behaviour, how inconvenient it is to have to change the language again and again after each save.

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia The language tabs focus whatever your language setting is. So if you wanted it to focus on one particular language you could choose that language in your Profile. Having it remember the focused language in a cookie might have merit too though. I'm not really sure if that's what people would want or not, I guess it depends on what you are doing. It's not been requested before (that I know of) so maybe it would be worthwhile to open this in the requests repo to gauge interest? Perhaps a safe bet would be to just make it a configurable option in the LanguageTabs module.

**Comment by flipzoom** [comment]
Good suggestion @ryancramerdesign , I have implemented the function and created a PR. 😊 See https://github.com/processwire/processwire/pull/244

**Comment by flipzoom** [comment]
Feature and PR has been implemented in the Dev-Branch and works.
