### ISSUE TITLE
Js error when toggling fields with visibility option: Open when populated + Closed when blank + Load only when opened (Ajax) 

### ISSUE THREAD

**Issue by q107** [processwire/processwire-issues#1623]
### Short description of the issue

Non empty Inputfields with visibility option set to "Open when populated + Closed when blank + Load only when opened (Ajax)" won't open again after being manually closed.

### Expected behavior

Toggling open/close button should open or close non empty inputfields without js errors.

### Actual behavior

Closing non empty inputfield with "Open when populated + Closed when blank + Load only when opened (Ajax)" visibility option will render it permanently closed. Browser console shows "JqueryCore.js?v=183:2 Uncaught RangeError: Maximum call stack size exceeded" when attempting to toggle it open again.
Only resolution is to refresh the page.

### Optional: Screenshots/Links that demonstrate the issue

![error2](https://user-images.githubusercontent.com/47921517/190833860-01f9beb6-3f1e-4e27-91ad-7887f84b534d.gif)

### Steps to reproduce the issue

1. Edit field (let's say: Title).
2. Change field's visibility option (Input tab->Visibility) to "Open when populated + Closed when blank + Load only when opened (Ajax)".
2. Open page with said field (if empty, fill it up and save the page).
5. Now close the field and try to open it again.

### Setup/Environment

* ProcessWire version: from at least 3.0.123 up to the most recent master 200 / dev 205

**Comment by matjazpotocnik** [comment]
I can confirm. It looks like there is a loop in Inputfields.js, I think these lines are the culprit:
```
if(isCollapsed && isAjax) {
    $toggleIcon.click();
    return $inputfield;
}
```

I added `var wasCollapsed = $inputfield.hasClass("InputfieldStateWasCollapsed");` in the toggle function and changed the condition to `if(isCollapsed && !wasCollapsed && isAjax)`. I'm not sure this is the right way to fix, but it works.

**Comment by ryancramerdesign** [comment]
Thanks @q107 and @matjazpotocnik I've pushed @matjazpotocnik fix for this -- that looks right to me.

**Comment by ryancramerdesign** [comment]
Commit: https://github.com/processwire/processwire/commit/f510392e7e2d609d1c28adb6f20711a86faee4d7

**Comment by q107** [comment]
Thanks, it's working now.
