### ISSUE TITLE
Translated pageNumUrlPrefix breaks pager function in admin users list

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1628]
### Short description of the issue

Having non-default value in pageNumUrlPrefix ("sivu") seems to break the pager in the admin users list — pager links result in visible error message `{"error":false,"message":"Unknown action"}`. If I change page num prefix via LanguageSupportPageNames module config back to "page", things start working again.

Perhaps somehow related to https://github.com/processwire/processwire-issues/issues/1447?

Note: if this turns out to be a real issue (one that others can reproduce as well), it would be awesome if we could get a fix for it for the stable (master) branch (in addition to dev). This is a rather critical feature for the project, but since the dev branch has gone through pretty large updates recently, I don't feel particularly comfortable upgrading a live site to use it just yet.

### Optional: Screenshots/Links that demonstrate the issue

<img width="547" alt="Screen Shot 2022-09-30 at 17 18 01" src="https://user-images.githubusercontent.com/1252021/193290041-21420f75-d0ac-4ab0-b75f-95c114d6f555.png">

### Setup/Environment

* ProcessWire version: 3.0.200
* (Optional) PHP version: 7.4

**Comment by ryancramerdesign** [comment]
@teppokoivula I think this one may already be fixed in the dev branch, maybe in this commit: https://github.com/processwire/processwire/commit/4aa75a7d17d70942d1150721ef9ccfd4ccf133b0 ?

**Comment by matjazpotocnik** [comment]
@teppokoivula can you check this and close if it's fixed?

**Comment by matjazpotocnik** [comment]
@teppokoivula ping

**Comment by matjazpotocnik** [comment]
@teppokoivula Closing. Please comment again to reopen.
