### ISSUE TITLE
Admin panel breadcrumb returns html-encoded apostrophe 

### ISSUE THREAD

**Issue by lesaff** [processwire/processwire-issues#163]
### Short description of the issue
Admin panel breadcrumb returns html-encoded apostrophe 

### Expected behavior
single and double quotes should be returned as is?

### Optional: Screenshots/Links that demonstrate the issue
**Default admin theme**
![screen shot 2017-01-17 at 11 06 23 am](https://cloud.githubusercontent.com/assets/1151181/22025809/3b9c23a4-dca5-11e6-9628-2b54c5f81643.png)
**Reno admin theme**
![screen shot 2017-01-17 at 11 05 52 am](https://cloud.githubusercontent.com/assets/1151181/22025821/4c3b999c-dca5-11e6-83fd-2d71b2c9fafd.png)

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7.0.1
* (Optional) MySQL version: MariaDb 10.1.20

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. I notice there is an "fa-external-link" icon at the end of your breadcrumb trail. I would disable whatever module is adding that, to see if it might be what's double-encoding your breadcrumb trail.

**Comment by adrianbj** [comment]
That fa-external is part of AdminOnSteroids which I am also running, but I also can't duplicate the encoding issue.

**Comment by lesaff** [comment]
It was fine when you're looking at its immediate child. The unencoded string comes out when I am editing its grand child. See anim gif below

![pw-breadcrumb-issue](https://cloud.githubusercontent.com/assets/1151181/22157814/a74ee854-df0f-11e6-9758-8823a56b361a.gif)

**Comment by rolandtoth** [comment]
I neither can reproduce. Could you paste here the quote character you are using?
Plus are you sure it's happening even with AdminOnSteroids disabled?

**Comment by lesaff** [comment]
Still seeing it with AOS disabled

The rendered text
`Shareholder&#039;s Information`

The original text
`Shareholder's Information`

**Comment by adrianbj** [comment]
Just to confirm that I can reproduce this when editing a grandchild the way @lesaff describes. The problem exists without AOS.

**Comment by Toutouwai** [comment]
I can't reproduce when editing a grandchild - tried both core admin themes.
![2017-01-21_102909](https://cloud.githubusercontent.com/assets/1538852/22166176/af97d11e-dfc4-11e6-9f82-61770e3b3aed.png)
![2017-01-21_102810](https://cloud.githubusercontent.com/assets/1538852/22166177/af9c90b4-dfc4-11e6-99f7-3a23c1f8253c.png)

**Comment by rolandtoth** [comment]
Thanks, it seems to be AOS - disabling the tweak "Add long-click and ctrl+click actions to breadcrumbs" in the Hotkeys submodule fixes it. I'll try to find a fix, sorry for the trouble.

**Comment by rolandtoth** [comment]
No success - this is the code that causes the issue but I don't see how this could cause this. Even if I disable all JavaScripts (globally in the browser) the problem still persists.

https://github.com/rolandtoth/AdminOnSteroids/blob/master/AdminOnSteroids.module#L756-L781

**Comment by adrianbj** [comment]
I hope you figure it out @rolandtoth because those long and ctrl + click options are indispensable!

**Comment by Toutouwai** [comment]
> Thanks, it seems to be AOS - disabling the tweak "Add long-click and ctrl+click actions to breadcrumbs" in the Hotkeys submodule fixes it.

Weird, I have that AOS option enabled and I still can't reproduce this issue in any browser.

**Comment by adrianbj** [comment]
What's really weird is even this causes the problem:

```
            // add breadcrumb tweaks
            if (in_array('breadcrumbTweaks', $configData[ $subModule ])) {

                $page = $this->pages->get('has_parent!=2, id=' . $this->input->get->id);

                if ($page->id) {

                    foreach ($this->wire->pages->get(1)->and($page->parentsUntil(1)) as $p) {
                        // don't do anything :)
                    }
                }
            }
```

I have removed any action on the page and its parents. But, as soon as I remove the foreach loop, the problem goes away!

**Comment by rolandtoth** [comment]
I've noticed that and tried a bunch of things but no luck (renaming variables, esp. $page, lowering php version, etc).

This one seems to work though I got incorrect results a few times (cache?).

``` php
foreach($this->wire('pages')->find('template=basic-page, limit=4') as $pp) {
	$url = $pp->viewable() ? $pp->httpUrl : null;
 	$editUrl = $pp->editable() ? rtrim($homepage->httpUrl, '/') . $pp->editUrl : null;
	$breadcrumbUrls[] = array(
		'url'     => $url,
		'editUrl' => $editUrl
	);
}
` ` ` 

Perhaps there's something with `->and() `?` In my tests it correctly outputted the parent pages IDs, but looping over them still caused html-encoded breadcrumb. My best guess is that it uses a query that switches DB encoding somehow.

**Comment by adrianbj** [comment]
I even tried: `foreach ($page->parents() as $p) {` and no luck :) I actually am not sure why that wouldn't suit your needs compared with home and parentsUntil. Maybe I am missing something obvious?

I also renamed $page and lots of other stuff with no luck :)

**Comment by rolandtoth** [comment]
https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/AdminTheme/AdminThemeDefault/AdminThemeDefaultHelpers.php#L92

Not sure why but adding `html_entity_decode` fixes this:

`if(!$title) $title = $this->wire('sanitizer')->entities1(html_entity_decode($this->_($breadcrumb->title)));`

@adrianbj  Thanks for the $page->parents() !

**Comment by lesaff** [comment]
@rolandtoth, that's great. I added `html_entity_decode` to the site in question and it fixes the issue.

**Comment by adrianbj** [comment]
@rolandtoth - try this in your AOS module. It fixes things at my end:
```
$this->addHookAfter('Fieldtype::formatValue', null, function(HookEvent $event) {
    $event->return = $event->arguments('value');
});
```
Not sure if there are any side-effects at this stage though.

**Comment by adrianbj** [comment]
Here's another fix for you. See where I added: `$this->wire->pages->of(false);`

```
// add breadcrumb tweaks
if (in_array('breadcrumbTweaks', $configData[ $subModule ])) {

    $page = $this->pages->get('has_parent!=2, id=' . $this->input->get->id);

    if ($page->id) {
        $homepage       = $this->wire->pages->get(1);
        $breadcrumbUrls = array();

        $this->wire->pages->of(false);
        foreach ($this->wire->pages->get(1)->and($page->parentsUntil(1)) as $p) {
            $breadcrumbUrls[] = array(
                'url'     => $p->viewable() ? $p->httpUrl : null,
                'editUrl' => $p->editable() ? rtrim($homepage->httpUrl, '/') . $p->editUrl : null
            );
        }

        // add to js config (head)
        $this->config->js("AOS_breadcrumbs", $breadcrumbUrls);
    }
}

$jsFiles[] = $root . '/' . $subModule . '/' . $subModule . '.js';
}
```

**Comment by rolandtoth** [comment]
Thanks, both are fixing the issue here too. I've added $p->of(false) inside the foreach - do you think it's a safer approach or does it matter anything?

**Comment by adrianbj** [comment]
Oh yeah doing it on $p inside the loop sounds better. I didn't actually try because I didn't think it would work given the weirdness of the problem appearing even with nothing inside the loop.

Maybe @ryancramerdesign has some insight into why this is actually happening and only at grandparent and higher levels.

**Comment by adrianbj** [comment]
@ryancramerdesign - I just looked into this a little more and you can reproduce this easily without the AOS module. Just place this in your ready.php and make sure you're editing a grandchild of a page with an apostrophe in the title. 

```
$cp = $pages->get($this->input->get->id);
foreach ($cp->parents() as $p) {}
```

Something about calling `parents()` seems to be turning on outputformatting. If you do this instead, everything is fine again:

```
$cp = $pages->get($this->input->get->id);
foreach ($cp->parents() as $p) { 
    $p->of(false); 
}
```

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I was finally able to duplicate it, but only if I had multi-language support installed. Fixing it was just a matter of updating an htmlspecialchars() call to set the $double_encode argument to false.
