### ISSUE TITLE
Default language no longer set on new user (starting with 3.0.204)

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1630]
### Short description of the issue

If you create a new user (via the admin or API), there is no language set anymore.

### Expected behavior

The user should be assigned the default language.

### Actual behavior

No language is set.

### Optional: Suggestion for a possible fix

Not sure exactly what code introduced the bug, but everything works as expected in 3.0.203 and is broken in 3.0.204 and all more recent versions

### Steps to reproduce the issue

1. Create a new user
2. Note that no language is set

* ProcessWire version: 3.0.204+
* (Optional) PHP version: 8.0.x

**Comment by adrianbj** [comment]
@ryancramerdesign - presumably the problem was introduced in this commit: https://github.com/processwire/processwire/commit/866f91424fad305bda533c718a21c20a06bbe8b4

**Comment by netcarver** [comment]
Hi @ryancramerdesign any chance this could be addressed?

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks good.
