### ISSUE TITLE
Comments Manager Bulk Action Broken

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#1632]
### Short description of the issue

When using the Actions select menu to change multiple comment actions, this does not work.

### Expected behavior

It *should* change the action dropdowns for all selected (checked) comments

### Actual behavior

It highlights the selected comments as though it has changed something, but it doesn't actually change anything :)

### Optional: Suggestion for a possible fix

Line 106 of ProcessCommentManager.js needs changing from this:

The comments manager issue I was having appears that maybe it used to be radio buttons previously but now the status box is a select field, so the fix is to change line 106 of ProcessCommentsManager.js from this:

`$(this).find(".CommentStatus > input[value='" + val + "']").click();`

to this:

`$(this).find("select.CommentStatus").val(val);`

This is in latest dev branch of PW but I think has been an issue before now.

**Comment by Notanotherdotcom** [comment]
I think perhaps previously the actions were radio buttons, so this then got broken when it changed to a select element.

**Comment by Notanotherdotcom** [comment]
Semi-related, but hardly seems opening a new report for, when there are zero results in the tab you're viewing in Comments Manager it says "1-0 of 0" whereas it would be better to just have "Pending (0)" for example.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/190857/197330476-de8b9c0b-1ca7-49cb-a8cd-a1a98fc1adbf.png">

**Comment by ryancramerdesign** [comment]
Thanks @Notanotherdotcom I've pushed your suggested fix for this and also corrected the headline.

**Comment by matjazpotocnik** [comment]
@Notanotherdotcom Pete, can you verify the fix and close it?

**Comment by Notanotherdotcom** [comment]
Yep works thanks.
