### ISSUE TITLE
hasPathHooks is imprecise

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1635]
Let's say I have this in ready.php:
```
$wire->addHook('/x', function($event) {
  return 'hello';
});

// must come after addHook above
echo wire('hooks')->hasPathHooks($_SERVER['REQUEST_URI']);
```

If I were to visit `/x`, it will output "1" and "hello".  Correct.

If I were to visit `/y`, it will 404.  Correct.

If I were to visit `/x1` (or anything that starts with `/x`), it will 404 (correct), *not* output "hello" (correct), BUT it *will* output "1" (incorrect) because it thinks hasPathHooks is true, when I believe it shouldn't be.

**Comment by ryancramerdesign** [comment]
@jlahijani The way path hooks work, they filter down based on the starting path. This enables the core to quickly filter requests that it should consider for path hooks vs those that it should exclude. It only indicates that it might match, as path hook patterns can have variable components. I wasn't really thinking others might need this function, but if you'e got a use case where it's something you need, let me know.

**Comment by matjazpotocnik** [comment]
@jlahijani Should we leave this issue open? Do you have a use case so Ryan can potentially work on it?

**Comment by matjazpotocnik** [comment]
@jlahijani closing, post more and reopen if needed.
