### ISSUE TITLE
PHP Warning: Undefined array key "func" in wire/core/WireFileTools.php:1590

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1637]
### Short description of the issue

I'm using $wire->files->include() on a module's settings page and it throws the given warning. I did some research and found that on admin pages it seems that the fuel contains an "options" property which then causes the error in WireFileTools

![image](https://user-images.githubusercontent.com/8488586/200054887-ce4b11bf-460d-428f-83b2-40e2343385c7.png)

### Steps to reproduce the issue

Add this line in any `getModuleConfigInputfields` of a module and load the module's settings page:

```
$this->wire->files->include($this->wire->config->paths->siteModules . "README.txt");
```

### Setup/Environment

* ProcessWire version: 3.0.206

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign I've added a PR to fix it: https://github.com/processwire/processwire/pull/248

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock good find, I've pushed something similar to your PR. Since that extract() can potentially overwrite any local variables, I moved the needed variables to be class variables instead so there's no way the extract() could overwrite them.

**Comment by BernhardBaumrock** [comment]
Nice! Thx
