### ISSUE TITLE
Extended field values incorrectly exported

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1638]
### Short description of the issue

Extensions to field values added by modules such as MinimalFieldset are incorrectly exported by the core getExportData() api or the Field export Admin functions.

### Expected behavior

Extended values are correctly exported.

### Steps to reproduce the issue

1. Install the MinimalFieldset Module
2. Create a field of type FieldtypeFieldsetOpen and check the "Remove label and padding for this fieldset" option and save the field.

![2022-11-03_19-43](https://user-images.githubusercontent.com/16049/200312375-9a3e40c0-d80c-4b86-8b38-3db438af2fbc.png)

3. Navigate to Setup > Fields > Export and export the data for the field you added.
4. The "minimal" value is null, but should be 1.

![2022-11-03_19-41](https://user-images.githubusercontent.com/16049/200312390-77773a59-e6a3-4e71-90e7-2cea84bcc588.png)

### Suggestion for a possible fix

Switch the order of the [`array_merge()` arguments in Field.php L515](https://github.com/processwire/processwire/blob/c2eaa0a8da0221942b99f2e1fb4e103e18a70d33/wire/core/Field.php#L515) so the typeData values don't override the field's values. (Thanks to Robin Sallis for the suggestion.)

![2022-11-07_12-54](https://user-images.githubusercontent.com/16049/200315853-c75f54f6-afda-4672-947a-06df00e5a7ee.png)

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.206|
|PHP|8.0.24|
|Webserver|Apache/2.4.54 (Debian)|
|MySQL Server|8.0.26-0ubuntu0.20.04.3|
|MySQL Client|mysqlnd 8.0.24|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|600 (changeable)|
|max_input_nesting_level|64|
|max_input_time|-1|
|max_input_vars|5000|
|memory_limit|1024M|
|post_max_size|100M|
|upload_max_filesize|100M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|2.3.3|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.11|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG||
|PDF|1|
|WebP|1|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @netcarver I've pushed the suggested fix. I do wonder about potential side effects here so keep an eye out just in case, but so far it looks like this should have been this way originally.

**Comment by netcarver** [comment]
Thank you, will re-open if needed.

**Comment by ryancramerdesign** [comment]
Fix for issue #1792 might potentially break this fix
