### ISSUE TITLE
ProcessPageEdit: Unknown page + DEBUG MODE BACKTRACE

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#1639]
Is this the intended behavior when trying to edit a non-existent page in the admin with debug mode turned on?

What extra information do we get by seeing this backtrace? Wouldn't the simple information that it is an "Unknown page" be enough in this case?

![processpageedit-unknown-page](https://user-images.githubusercontent.com/7194945/200334804-b0fe7dd0-886d-432c-9dec-7262cfd9783d.png)

**Comment by ryancramerdesign** [comment]
@szabeszg If debug mode is enabled then any exceptions automatically include a backtrace, so I'd say that yes this is the correct output for debug mode.

**Comment by szabeszg** [comment]
> so I'd say that yes this is the correct output for debug mode.

I see. However, what I do not fully understand is why throwing an exception in such a case? This way it appears to be a serious error of some sort but I just simply edited the ID in the address bar, intentionally.

Anyway, I guess it is a conceptual issue and I can learn to live with it :)

Thanks for the reply, btw!

**Comment by adrianbj** [comment]
The thing that has always confused me about this is that it's also shown for non-superusers.
