### ISSUE TITLE
ProcessModule::renderListTable() - Name of the module include numbers

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#164]
### Short description of the issue

In case of included numbers in the modules /class name splitting of camelCase names doesn't work as expected. Example names: Process101, Process102 etc.

### Expected behavior
Listing under the same headline
![bildschirmfoto 2017-01-19 um 08 11 07](https://cloud.githubusercontent.com/assets/4683120/22097158/e0e363ba-de1f-11e6-9798-f54a72d56c20.jpg)

### Actual behavior
Headline is generated twice
![bildschirmfoto 2017-01-19 um 08 11 34](https://cloud.githubusercontent.com/assets/4683120/22097167/ef56f358-de1f-11e6-9b6d-aecc02160c6c.jpg)
### Optional: Suggestion for a possible fix
add numbers to regex
```
// Line 620:
if(strpos($name, $section) !== 0 || preg_match('/' . $section . '[^A-Z0-9]/', $name)) {
// ...
}
```
### Setup/Environment
* ProcessWire version: 3.0.49 and any older

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed your suggested fix to the dev branch.
