### ISSUE TITLE
Multilanguage image description not saving with language specific edit permissions

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1640]
### Short description of the issue
When a user with language specific edit permission tries to save an image description, the text is not saved to the DB and after save the text field for that specific language is empty.

### Expected behavior
The language specific text gets saved

### Actual behavior
The language specific text does not get saved

### Optional: Screenshots/Links that demonstrate the issue
With only page-edit-lang-pl permission values does not get saved.
![only-pl-perm](https://user-images.githubusercontent.com/3088950/200512422-0775decd-0653-4527-8732-99f349101648.png)
Field hint says: Changes to this field will not be saved because you do not have permission for language: (Default)
![edit-only-pl-perm](https://user-images.githubusercontent.com/3088950/200512719-a29e2557-7d4a-4209-bc7d-652379ce96a4.png)
With page-edit-lang-pl and page-edit-lang-default permissions value for lang pl gets saved
![pl-and-default-perm](https://user-images.githubusercontent.com/3088950/200512904-b6ec5557-7add-476c-9c8c-6f5d6a802b8a.png)
Field hint is gone
![edit-pl-and-default-perm](https://user-images.githubusercontent.com/3088950/200513011-94b3933b-bdf4-402f-8dd7-6a17f1dd4fc0.png)

### Optional: Suggestion for a possible fix
If I also enable page-edit-lang-default for the user role, they can save values to pl language. But it is not desired that they can also edit default language. So this is only a temp workaround, no solution.

### Steps to reproduce the issue
1. Create a role with permissions like illustrated in the screenshots above.
2. Try to save a value to image description field of the specific language

### Setup/Environment

* ProcessWire version: 3.0.184
* (Optional) PHP version: 7.4

**Comment by matjazpotocnik** [comment]
@gebeer I can't replicate. In my testing, the value for the description in a language the user doesn't have permission is not saved. The value for the description user has permission is saved. Could you try the latest master version, currently 3.0.225?

**Comment by gebeer** [comment]
@matjazpotocnik thanks for looking into this. It will take us some time until we can upgrade the site to latest PW version. You can close this for now and If the problem then still occurs, I will reopen.
