### ISSUE TITLE
Comment in empty _init.php  probably questionable

### ISSUE THREAD

**Issue by napengam** [processwire/processwire-issues#1641]
### Short description of the issue

Comment in empty _init.php  mentions  $config->**append**TemplateFile in /site/config.php

### Expected behavior

Comment in empty _init.php should mentions  $config->**prepend**TemplateFile in /site/config.php

because in config.php it is written

// Prepend this file in /site/templates/ to any rendered template files
$config->**prepend**TemplateFile = '_init.php';

### Optional: Suggestion for a possible fix

change text in comment within _init.php

### Setup/Environment

* ProcessWire version: 3.0.200
* (Optional) PHP version:  8.1

**Comment by szabeszg** [comment]
Note that there is an always kept open issue for spelling/typo/copy-paste mistakes like this one over here: https://github.com/processwire/processwire-issues/issues/797

**Comment by ryancramerdesign** [comment]
@napengam Thanks, this one is actually already fixed a couple months ago on the dev branch.
