### ISSUE TITLE
WireArray sort expects items to be Wire type

### ISSUE THREAD

**Issue by neonwired** [processwire/processwire-issues#1642]
### Short description of the issue

If you call sort on a WireArray with containing anything other than wire objects it will fail

### Expected behavior

Expect sort to be compatible with all data types WireArray excepts or at least catch the error

### Actual behavior

Fails with a php fatal error

### Steps to reproduce the issue

1. Create a WireArray object
2. Add a number of array items
3. Call sort on the WireArray.

### Setup/Environment

PHP 7.3
ProcessWire 3.0.200

**Comment by ryancramerdesign** [comment]
Thanks @neonwired I've pushed a fix for this so that it should now support sorting by other types.

**Comment by matjazpotocnik** [comment]
@neonwired, can you confirm and close this issue?

**Comment by matjazpotocnik** [comment]
Closing on the assumption this is fixed. @neonwired, please comment here again if that's not the case.
