### ISSUE TITLE
Lister creates multiple spinners on keyup

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1644]
### Short description of the issue

A new Lister spinner gets added on every keyup event resulting in multiple spinners. This becomes noticeable if the server is slow to respond and refresh the results.

I have simulated a slow server in the screencast below by executing sleep(30) in the Tracy console before using the Lister filters.

![lister](https://user-images.githubusercontent.com/1538852/202331166-d8ad65de-656d-438e-bda0-b85a5b24b7e9.gif)

Sidenote: it would be good if Lister/InputfieldSelector used `autocomplete="off"` in text inputs to avoid these sorts of dropdowns which are almost always irrelevant and therefore unwanted form history suggestions:

![2022-11-17_142446](https://user-images.githubusercontent.com/1538852/202331435-274ebeba-18a3-45b4-a001-1f40862ed728.png)

### Setup/Environment

* ProcessWire version: 3.0.206

**Comment by matjazpotocnik** [comment]
@ryancramerdesign @Toutouwai I tracked this down to line 164 in ProcessPageLister.js where a spinner is added even if it exists. So I did this:

```js
var $headline = ProcessLister.results.find('.lister_headline');
if(!$headline.find('i.fa-spin').length) {
  $headline.append("<i class='fa fa-spin fa-spinner'></i>");
}
```

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @Toutouwai Thanks, I've pushed Matjaz's fix.

**Comment by Toutouwai** [comment]
@matjazpotocnik, thanks for working out that fix.

@ryancramerdesign, there needs to be some sort of cachebusting done for ProcessPageLister.js or else the fix isn't going to take effect for existing admin users. 

![2023-08-18_100851](https://github.com/processwire/processwire-issues/assets/1538852/f646472d-665a-4efe-99ad-f42b94f3e620)

**Comment by matjazpotocnik** [comment]
@Toutouwai, this is how it looks here, with $config->debug="dev"

![image](https://github.com/processwire/processwire-issues/assets/7663992/33a5060f-f35c-4696-9624-ee3fc43a7238)

and with $config->debug = false

![image](https://github.com/processwire/processwire-issues/assets/7663992/71da4f65-ae9e-4d42-aaae-2301d7ab23b1)

**Comment by Toutouwai** [comment]
Looks like it's a Lister Pro thing - it is loading the ProcessPageLister JS and CSS without any query string.
