### ISSUE TITLE
InputfieldTextTags error with hidden language

### ISSUE THREAD

**Issue by Hurmeli** [processwire/processwire-issues#1645]
### Short description of the issue

Processwire installation with two languages, one language set hidden. Open a textarea (multilanguage) field and tracy will throw an error on InputfieldTextTags.module on line 349.

If you don't get error, change profile to use the hidden language.

### Setup/Environment

PW 3.0.207, it seems perhaps 3.0.200 might have introduced this error

**Comment by ryancramerdesign** [comment]
@Hurmeli I've attempted a fix by updating the line number you mentioned, but since I don't know what the error message is I'm not positive if this is it. If this doesn't fix it, please let me know what error message you are seeing. Thanks.

**Comment by matjazpotocnik** [comment]
@Hurmeli, could you check this and close the issue if fix work for you?

**Comment by matjazpotocnik** [comment]
@Hurmeli, I'm closing this on the assumption Ryan's fix is working for you.
