### ISSUE TITLE
$sanitizer->email() does not work for IDN

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1647]
### Short description of the issue

```php
$sanitizer->email("example@schönewelt.de"); // outputs example@schnewelt.de
```

https://en.wikipedia.org/wiki/Internationalized_domain_name

### Expected behavior

It should output example@schönewelt.de

### Actual behavior

It outputs outputs example@schnewelt.de

### Optional: Suggestion for a possible fix

https://processwire.com/talk/topic/27172-sanitizer-email-for-idn-domain/?do=findComment&comment=224278

#note: ögkv

**Comment by BernhardBaumrock** [comment]
Maybe we should just add $sanitizer->isEmail() that works like the linked method?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Good suggestion. Previously we've not supported IDNs for email, and this is the first it's been requested as far as I know, but it makes sense to me. I've updated the sanitizer email method to accommodate every option I could think of for this. Currently the IDN option is disabled by default, but you can enable it (among other options)  with the new $options argument. I think we'll probably add a configuration setting to InputfieldEmail to support it.

**Comment by BernhardBaumrock** [comment]
Cool, thx!!
