### ISSUE TITLE
Upgrade from 3.0.201 to 3.0.207 breaks Umpaluts (special characters) in page-names/URLs

### ISSUE THREAD

**Issue by weberhofer** [processwire/processwire-issues#1648]
### Short description of the issue

I am running a multilingual Processwire instance  for a few years. I have configured  german umlauts to be used in page names with the following setting:
```php
$config->pageNameCharset = 'UTF8';
$config->pageNameWhitelist = '-_.abcdefghijklmnopqrstuvwxyz0123456789æåäßöüđжхцчшщюяàáâèéëêěìíïîõòóôøùúûůñçčćďĺľńňŕřšťýžабвгдеёзийклмнопрстуфыэęąśłżź';
```
The system has been generating URLs like the following for several years `/de/für-interessierte/richtlinien/`

After upgrading, the generated URLs and the page names in the editor looks like `/de/xn--fr-interessierte-jzb/richtlinien/` (punycode?). Not only, that those links are not the ones desired, they are not working, too.

### Expected behavior

The links should be the same as they used to be.

**Comment by ryancramerdesign** [comment]
Thanks @weberhofer I've pushed a fix for this issue, can you confirm it also fixes it there?

**Comment by weberhofer** [comment]
@ryancramerdesign Thanks a lot! It's working again! I was digging into the code but was unable to locate the problem!
