### ISSUE TITLE
$input->whitelist joins array values with a comma

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#165]
### Short description of the issue

I'm using nette forms for a filter form and $input->whitelist to pass arguments down to further pages in the pagination. 

### Expected behavior

GET parameters passed by the form are also appended to the pagination links.

### Actual behavior

Instead of project[]=12345&project[]=12346 processwire will append project=12345,12346, which is not how array values are send by forms. This is therefore not parsed correctly by nette forms.

### Steps to reproduce the issue

1. Send a multi value input via a form submitted by $_GET
2. Whitelist it via `$input->whitelist($fieldName, $value)`
3. The link to page2 does show the different representation

Hint: pagination is on purpose not enabled for the template

### Setup/Environment

* ProcessWire version: 2.7.3

**Comment by ryancramerdesign** [comment]
See the `$arrayToCSV` option in MarkupPagerNav. You'll want to set this to false if you want the more verbose array format in the URL:
https://github.com/processwire/processwire/blob/master/wire/modules/Markup/MarkupPagerNav/MarkupPagerNav.module#L62

**Comment by LostKobrakai** [comment]
Thanks, should've looked there before writing :D
