### ISSUE TITLE
PagePaths module PHP 8 deprecation warning

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1652]
### Short description of the issue

Deprecation warning with PHP 8.1:
PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in
https://github.com/processwire/processwire/blob/a3cc73bd87c3fed53a2afd52f36acd568df588ff/wire/modules/PagePaths.module#L638
### Expected behavior

No warnings

### Actual behavior

Warnings

### Steps to reproduce the issue

install PagePaths module on PHP >= 8

### Setup/Environment

* ProcessWire version: 3.0.200 and latest dev
* (Optional) PHP version: 8.1

**Comment by gebeer** [comment]
@ryancramerdesign 
Supposed Fix for https://github.com/processwire/processwire/blob/a3cc73bd87c3fed53a2afd52f36acd568df588ff/wire/modules/PagePaths.module#L638
```
if(!strlen((string) $name)) continue;
```
Working for me. 
Since $query->fetch() returns NULL for empty name fields, it should be fine to cast that to an empty string. But maybe it would be more efficient to do this on the query level?

Inserting this after l 616 also solves the problem for me:
```
		$database->setAttribute(\PDO::ATTR_ORACLE_NULLS, \PDO::NULL_TO_STRING);
```
See https://www.php.net/manual/en/pdo.setattribute.php

**Comment by ryancramerdesign** [comment]
Thanks @gebeer I've pushed a fix for this issue.
