### ISSUE TITLE
findRaw for subfields should  respect indexed false option

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#1653]
```
 $results = $this->pages->findRaw(
        'template=user',
        [
          "id",
          'name',
          'references.title',
        ],
        ['flat' => '_', 'indexed' => false]
      );
      bd($results);
```
should respect the indexed false option. Right now the output of references.title returns the page id as the index.

![image](https://user-images.githubusercontent.com/551551/205676264-f44db463-842c-45d0-88a5-71e83fd96afd.png)

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch while this isn't technically a page field I think it makes sense to have it inherit the indexed behavior too, I have pushed an update for it.
