### ISSUE TITLE
Translation import says "Invalid Json" for json file which are validated with multiple services

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1655]
PHP 8.0.26
Processwire:  3.0.208 

I am trying to import following JSON Translation file: https://pastebin.com/fgDZWYp8

It have validated it with many services but it says always it's invalid during the import.

![Bildschirm­foto 2022-12-05 um 22 34 05](https://user-images.githubusercontent.com/488163/205747368-eae0461e-cc83-4ca1-a27e-99c40607455b.png)

**Comment by tiefenb** [comment]
Also de CSV Version of the file does not work and I have no clue why

[de-default.csv](https://github.com/processwire/processwire-issues/files/10163947/de-default.csv)

**Comment by matjazpotocnik** [comment]
@tiefenb while JSON might be valid, data is missing; in your case 'fields' object.

PHP Warning: Undefined array key "fields" in [...\ProcessLanguageFieldExportImport\LanguageFieldImporter.php:154]

**Comment by tiefenb** [comment]
thx found it
