### ISSUE TITLE
Modules page breaks if any module name starts with 2 capital letters.

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1658]
### Short description of the issue

I just installed the module named JKPublishingOptions from [here](https://github.com/juergenweb/JKPublishingOptions) and the ProcessWire modules pages broke. Tracy error and option for a fix shown below.

### Expected behavior

The install should not lead to the module page being unusable.

### Actual behavior

Error on loading module page:
![image](https://user-images.githubusercontent.com/16049/206871031-bd7972ea-3930-47c1-84c1-de35b8a6ea48.png)

### Suggestion for a possible fix

I fixed this on my local install by changing line 995 of ProcessModule.module to the following

```php
		$out .= $table ? $table->render() : '';
```
Which allowed the module page to render, showing the following error at the top of the page...
![image](https://user-images.githubusercontent.com/16049/206871391-7631c071-c420-4399-ba9c-c6ab1188380c.png)

### Steps to reproduce the issue

1. Go to the module page
2. Install [this module](https://github.com/juergenweb/JKPublishingOptions/archive/refs/heads/main.zip) using the upload via URL option. 

### Setup/Environment

* ProcessWire version: 3.0.208

**Comment by ryancramerdesign** [comment]
Thanks @netcarver I've pushed your suggested solution for this.

**Comment by netcarver** [comment]
@ryancramerdesign Thank you, Ryan.
