### ISSUE TITLE
PHP 8.2 - InputfieldFile - Deprecated: Creation of dynamic property

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1659]
PHP 8.2
Deprecated: Creation of dynamic property ProcessWire\InputfieldFile::$maxFilesize is deprecated in [.../modules/Inputfield/InputfieldFile/InputfieldFile.module:216](subl://open/?url=file:
%2Fwire%2Fmodules%2FInputfield%2FInputfieldFile%2FInputfieldFile.module&line=216)

**Comment by matjazpotocnik** [comment]
@tbba Fixed in https://github.com/processwire/processwire/commit/d6c54bda6a51f9f811d59e4aa57df6199178a3ba

**Comment by matjazpotocnik** [comment]
@tbba, closing, let me know if it needs re-opening.
