### ISSUE TITLE
Weird lag after logging into admin section

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1660]
I'm almost certain you won't be able to replicate this but I wanted to create this issue to see if anyone else is experiencing it.

When I log into the admin of ProcessWire on most of my sites, I get a strange lag that lasts about 5 seconds and ramps up my CPU fan briefly.  During that time, I can't click anything in the admin... it's truly frozen or very heavily lagged.  This will also happen on a fresh ProcessWire installation.

I know it's related to Chrome and is either related to some sort of native Chrome feature or one of my Chrome extensions.  I disabled all my extensions and it went away but I wasn't able to pinpoint the exact one.  I then re-enabled all of them and the lag went away.  A week later, the issue has returned.

If anyone has experienced this or know of a better way to diagnose, please comment.

**Comment by ryancramerdesign** [comment]
@jlahijani I've not observed that here in Chrome, but since you  mentioned disabling chrome extensions made the issue go away, and that it occurs right after login, I'm wondering if any of those extensions might be login related? For instance, maybe a password manager or anything like that?

**Comment by BernhardBaumrock** [comment]
I've been noticing something similar, but not on login, but when using tracy (or the tracy console). I'm on Mac + Chrome and no idea what's going on or how I could debug this. I'm only seeing that on PW sites though!

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Like any debugger, Tracy definitely slows things down a lot, but that's expected because it adds a lot of overhead. But well worth it in a local dev environment.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign I'm not talking about the expected slowdown but about "freeze + mac loading spinner" when using the tracy console (just typing text) well after the page has finished loading.

**Comment by jlahijani** [comment]
Hmm, this also happens when I log into a WordPress backend admin.  Closing this issue since it doesn't seem PW related.
