### ISSUE TITLE
Debug panel error, when calling hook method with custom class with different namespace

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#1662]
When you call hook method for Custom class with different namespace, there is debug panel error appear.

![debug inc](https://user-images.githubusercontent.com/455983/210735013-ae7fe829-715e-4c1a-9472-3c385d98ad01.png)

## Possible fix

https://github.com/processwire/processwire/blob/dev/wire/templates-admin/debug.inc#L212

```php
"<td>" . ($toObject ? "$toObject::$toMethod" : $toMethod) . "()</td>" . 
```
### Replace with

```php
"<td>" . ($toObject ? get_class($toObject) . "::$toMethod" : $toMethod) . "()</td>" .
```

# Example usage:

```php
<?php

namespace Greeting;

class HelloWorld
{
     public function message()
     {
          echo 'Hello World !';
          exit;
     }
}
```

```php
<?php

namespace ProcessWire;

use Greeting\HelloWorld;

wire()->addHook('/hello-world', new HelloWorld, 'message');

```

**Comment by ryancramerdesign** [comment]
Thanks @trk I've pushed a fix for this.

**Comment by trk** [comment]
👍  @ryancramerdesign
