### ISSUE TITLE
"Usage" fieldset/info shows a default value during field creation

### ISSUE THREAD

**Issue by v-maillard** [processwire/processwire-issues#1663]
### Short description of the issue

On the "Add New Field" page, the "Usage" fieldset/info displays the word "value".

### Expected behavior

The section could display a sentence indicating that the field is not yet used by templates or that it can be added to templates once created.

### Suggestion for a possible fix

A simple fix could be to change this line [ProcessField.module#L1719](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessField/ProcessField.module#L1719) (`$field->value = 'value';`) to:

```
$field->value = $this->_('This field is not currently in use.');
```

or:

```
$field->value = $this->_('Once created, see the Actions tab to add/remove this field from templates.');
```

A more complex fix could be to copy/move some lines concerning the "\_usage_table" inputfield from `___buildEditFormActions()` to `___buildEditFormBasics()`.

### Steps to reproduce the issue

1. Create a new field
2. Open the "Usage" fieldset/info

### Setup/Environment

ProcessWire 3.0.210

**Comment by ryancramerdesign** [comment]
Thanks @v-maillard I've pushed a fix for this so that it doesn't show Usage until the field exists.
