### ISSUE TITLE
PHP 8.2 Deprecation and other notices

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1664]
### Short description of the issue

Can we build up a list here like we've done before?

PHP Deprecated: Creation of dynamic property HTMLPurifier_Lexer_DOMLex::$_entity_parser is deprecated in [.../MarkupHTMLPurifier/htmlpurifier/HTMLPurifier.standalone.php:7794]

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've upgraded the htmlpurifier version which should fix this issue.

**Comment by adrianbj** [comment]
Looks good now - thanks @ryancramerdesign - do you want to keep this open for other 8.2 issues like we have in the past or would you prefer separate ones?

**Comment by tiefenb** [comment]
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/site/modules/FieldtypeTable/FieldtypeTable.module on line 1676

**Comment by tiefenb** [comment]
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/site/modules/FieldtypeCombo/ComboSchema.php on line 224

**Comment by matjazpotocnik** [comment]
@tiefenb, based on the paths, I'm assuming those deprecations are related to the non-core modules? If so, it would be best to report them in the appropriate place (Pro Board?).

**Comment by JavonX** [comment]
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vhosts/httpdocs/wire/core/WireInput.php on line 371

Warning: Undefined array key 1 in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 471

Warning: Undefined array key 2 in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 471

Deprecated: setcookie(): Passing null to parameter #1 ($name) of type string is deprecated in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 133


I get these messages. The first one is the only one related to the core. I posted all of them in case it has something to do with the loginPersit messages

**Comment by ryancramerdesign** [comment]
@JavonX Just checked and that first one is already fixed on the dev branch.  For the others, it looks like that LoginPersist module would need to be adjusted, here's a link to the author's issue page for that module: https://github.com/craigrodway/LoginPersist/issues

**Comment by gmclelland** [comment]
Here's a interesting project that might help with these types of PHP upgrades?  https://github.com/rectorphp/rector

**Comment by designconcepts** [comment]
This warning in 3.0.219 after deleting compiled module files:

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /path/to/site/wire/core/ModulePlaceholder.php on line 68

**Comment by adrianbj** [comment]
@ryancramerdesign - the deprecation that @designconcepts mentioned is breaking Tracy's Console panel for me because of the `TracyDebugger::getApiData()` call trying to populate all the PW methods etc into its autocomplete list.

**Comment by ryancramerdesign** [comment]
Thanks @designconcepts @adrianbj I've pushed a fix

**Comment by Toutouwai** [comment]
~~Some more from HTML Purifier in PW 3.0.222...~~
Sorry, false alarm, had an older version of MarkupHTMLPurifier in /site/modules/

**Comment by Toutouwai** [comment]
I saw this in Page Edit when a ProFields Table field has a CKEditor column:
PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in ...\Inputfield\InputfieldCKEditor\InputfieldCKEditor.module:725

**Comment by Toutouwai** [comment]
PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ...\1testing\wire\modules\Inputfield\InputfieldSelect.module:917

Seen in PW 2.0.223 when editing a ProFields Table field.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed fixes for those.

**Comment by esszett** [comment]
Deprecated trim(): Passing null to parameter #1 ($string) of type string is deprecated in …  wire/modules/PagePathHistory.module on line 172

fix: $path = $sanitizer->pagePathName('/' . trim((string)$path, '/'), Sanitizer::toAscii);

**Comment by Toutouwai** [comment]
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in \wire\modules\Inputfield\InputfieldMarkup.module:107
PW3.0.240
