### ISSUE TITLE
template with noParents=1 shows up on page's change-template selectbox

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1665]
### Short description of the issue

My module creates a page with template "foo". The template has the setting "may this template be used for new pages" = "no". When I edit a "basic-page" I can see the "foo" template in the selectbox that lets me change the page's template.

### Expected behavior

"foo" should not show up in the template selectbox.

### Actual behavior

"foo" shows up in the template selectbox.

### Optional: Screenshots/Links that demonstrate the issue

![img](https://i.imgur.com/uN00X7s.png)

### Setup/Environment

* ProcessWire version: 2.0.209
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock It sounds like you have advanced mode enabled, which allows changing templates independent of family settings. Check your /site/config.php to see if you have `$config->advanced=true;`.  Set to false.

**Comment by BernhardBaumrock** [comment]
Of course I have, didn't know that, thx! :)
