### ISSUE TITLE
Hook InputfieldButton::render issue on 3.0.210

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#1668]
### Short description of the issue

I have upgraded a site to 3.0.210 from 3.0.165 and the following hook doesn't work properly (worked fine on 3.0.165). It changes the text but it won't let the non-superuser to delete the page. Pressing the button redirects the page https://mysite.test/admin/page/edit/?id=11293 to https://mysite.test/admin/page/edit/?id=11293&s=1&c=1 

```
/**
 * Rename "Move to Trash" text on Delete tab's button
 *
 */
$wire->addHookBefore('InputfieldButton::render', function(HookEvent $event) {

  if ($event->object->id != "submit_delete") return;
  if ($this->wire('user')->isSuperuser() == false) $event->object->value = "Hello World";

});
```
Another [user](https://processwire.com/talk/topic/28013-hook-issue-after-upgrading-to-30210-from-30165/?do=findComment&comment=229774) from the forum confirmed the issue too on a clean installation of 3.0.210.

### Expected behavior

The page should be moved to trash.

### Steps to reproduce the issue

1. Add the above hook code on ready.php
2. As non-superuser go to any page and from the Delete tab check the  confirm and press the button to move it to Trash.

### Setup/Environment

* ProcessWire version: 3.0.210

**Comment by ryancramerdesign** [comment]
@PWaddict For increased security, ProcessWire is validating that the button contains the same value at processing that it did when it was rendered. So the hook above is updating the value at render but not at process. I'd recommend using a different hook instead:
~~~~~
$wire->addHookAfter('ProcessPageEdit::buildFormDelete', function($e) {
        $e->return->getByName('submit_delete')->val('Hello World');
}); 
~~~~~
Another option is that you don't need to use a hook at all, as you could always do this instead: 
~~~~~
wireLangReplacements([ 'Move to Trash' => 'Hello World' ]);
~~~~~

**Comment by teppokoivula** [comment]
I must admit that this behaviour sounds a bit obscure, and I'm also pretty sure that I've used similar hook before. Security implications aside, could ProcessWire throw an exception here, so that the developer has a chance to realize what's going on?

**Comment by ryancramerdesign** [comment]
@teppokoivula That's a good idea, but I'm worried that it could end up breaking more than it helps. If someone is using their own logic with input()->post('submit_button_name'); which I think is fairly common, they might start getting exceptions when they aren't wanted.

**Comment by matjazpotocnik** [comment]
@PWaddict does Ryan's answer help in solving this issue? If yes, can you close it?
