### ISSUE TITLE
Array to string conversion error in $templates->find()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1669]
### Short description of the issue

Using `childTemplates` or `parentTemplates` in `$templates->find()` causes an array to string conversion error.

![2023-01-21_102206](https://user-images.githubusercontent.com/1538852/213807595-c02f2b0e-0924-4207-8282-66eccb7c5e57.png)

Related forum topic: https://processwire.com/talk/topic/28047-how-to-filter-templates-by-selector-childtemplates-solved/

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this.
