### ISSUE TITLE
Template import error

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1670]
### Short description of the issue

When attempting to import a template from another PW installation, PW gives the warning that it is unable to load the associated fieldgroup.

![2023-01-24_125037](https://user-images.githubusercontent.com/1538852/214178443-138a9644-577d-444e-880c-07df02641df8.png)

If you choose to create the template anyway it gives this error:

![2023-01-24_125147](https://user-images.githubusercontent.com/1538852/214178278-ba323da0-4a6c-4f1d-ba28-95e825cd5334.png)

I don't remember having this problem in earlier PW versions. I would expect PW to create the fieldgroup as part of the import process.

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by adrianbj** [comment]
@ryancramerdesign - just to confirm that I saw this a couple of days ago also.

**Comment by ryancramerdesign** [comment]
@Toutouwai @adrianbj Thanks, I've pushed a fix for this issue.
