### ISSUE TITLE
Option stripQuotes in Sanitizer

### ISSUE THREAD

**Issue by Atlant-Lektanov** [processwire/processwire-issues#1671]
### Short description of the issue

$sanitizer->text() method with stripQuotes option always removes quotes regardless of the value of this option.

### Expected behavior

$sanitizer->text() method with stripQuotes option should replace quotes with the value of this option.

Example:

$sanitizer->text('"Text"', ['stripQuotes' => '\&quot;']) = '\&quot;Text\&quot;'.

### Actual behavior

Example:

$sanitizer->text('"Text"', ['stripQuotes' => '\&quot;']) = 'Text'.

### Optional: Screenshots/Links that demonstrate the issue

The problem is in [this](https://github.com/processwire/processwire/blob/master/wire/core/Sanitizer.php#L1671) line.

### Optional: Suggestion for a possible fix

$options['strip_quotes'] should be replaced to $options['stripQuotes'].

### Setup/Environment

* ProcessWire version: 3.0.207 dev.

**Comment by ryancramerdesign** [comment]
Thanks @Clarity157 I've pushed a fix for this.
