### ISSUE TITLE
URL field should support use of tilde ~ characters in different situations

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1672]
I have a URL field and I'm trying to enter this URL in it:
https://www.houzz.com/professionals/general-contractors/jade-construction-and-remodeling-pfvwus-pf~220578561

ProcessWire says it's invalid.  If I remove the ~ it accepts it.

It does seem to accept URLs with tildes, but it has to be after a forward slash, like this old style URL:
http://infolab.stanford.edu/~sergey/

**Comment by ryancramerdesign** [comment]
@jlahijani Which version of ProcessWire? I tested on a URL field here and it accepted the houzz.com URL. Then I tried this and the sanitizer does not modify the URL:
~~~~~
$url = 'https://www.houzz.com/professionals/general-contractors/jade-construction-and-remodeling-pfvwus-pf~220578561';
echo $url . "\n";
echo $sanitizer->url($url) . "\n";
~~~~~
If your PW version is up to date (3.0.210 or 3.0.211) then I'd be curious about your PHP version and if maybe its URL sanitize/validate/filter flags behave differently depending on PHP version.

**Comment by jlahijani** [comment]
Hmm, I was using a slightly older version of PW (3.0.210?) and updated to latest bleeding edge and now it works fine.  Not sure what it was but I'll close this ticket.  BTW, I'm using PHP 8.1.
