### ISSUE TITLE
ProcessWire\ProcessUser::getEditableRoles(): Argument #1 ($page) must be of type ProcessWire\User, ProcessWire\RepeaterPage given, called in ProcessUser.module on line 352

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1673]
### Short description of the issue

If you have a repeater (or RM) field nested inside another repeater field on a user template page then this error appears.

### Expected behavior

It should check the editable roles on the "For Page", not the repeater parent page.

### Actual behavior

It tries to call `getEditableRoles()` on the parent repeater page.

### Optional: Screenshots/Links that demonstrate the issue

<img width="819" alt="image" src="https://user-images.githubusercontent.com/871211/215189850-d90050b8-1ca0-417b-ba5b-a9df5137e996.png">

### Optional: Suggestion for a possible fix

Check to see if `$page` is a repeater page and if so call `getForPage()` on it first.

### Steps to reproduce the issue

1. Create a nested repeater field setup on the user template
2. Create a new repeater item on the repeater field nested inside the parent.

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - working great now.
