### ISSUE TITLE
Table `->find()` issues introduced in 3.0.211

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1674]
### Short description of the issue

`$page->survey_results->find('survey_parent=15415');` works as expected in 3.0.210 but returns no results in 3.0.211. To make it work in 3.0.211 I can use `$page->survey_results('survey_parent=15415');` but not sure why the find version no longer works. To be honest I have never understood the different between using `find()` on a table field vs using the field like a method directly (as per the version that works in 3.0.211).

### Expected behavior

`->find()` should work.

### Actual behavior

The expected rows are present in the `itemsRemoved` property, rather than the `items` property.

### Optional: Screenshots/Links that demonstrate the issue

**These are from 3.0.211**

<img width="558" alt="image" src="https://user-images.githubusercontent.com/871211/215198835-85c8cfb3-261c-44b9-a000-b56023c1b418.png">

<img width="496" alt="image" src="https://user-images.githubusercontent.com/871211/215199032-15e22872-5ce4-4c27-ac66-f72e75d87b94.png">

**These are from 3.0.208**

<img width="559" alt="image" src="https://user-images.githubusercontent.com/871211/215199968-2adc5029-6395-44e0-99ee-1344b257e8d1.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/871211/215200111-e14df4e8-13ca-44f4-bc20-b1a8d0fbb769.png">

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by adrianbj** [comment]
@ryancramerdesign - just a note that I confirmed that it worked in 3.0.210 so it seems like this might be connected to @toutouwai's recent issue noted above.

**Comment by adrianbj** [comment]
@ryancramerdesign - it looks like your fix for https://github.com/processwire/processwire-issues/issues/1675 has also taken care of this, but if you have a minute, I would still love to better understand why `$page->survey_results('survey_parent=15415')` still worked when the bug was in place and in general when we should use that vs find().

Thanks.

**Comment by ryancramerdesign** [comment]
@adrianbj The `$page->survey_results('survey_parent=15415')` is a feature that enables it to directly query the database without loading the entire field value. Whereas a `WireArray::find()` operates on a field value that's already been loaded into memory.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that sounds like a potentially huge difference on large tables. I am not sure how I never knew that before. I am curious if that is documented somewhere. As far as I know, the only docs are in this post: https://processwire.com/talk/topic/6246-table/ but it doesn't appear to mention either approach to finding table rows that match a selector. Am I missing other docs somewhere? Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I have been doing some digging and discovered why have found confusion around the in memory vs DB selectors on Table fields. The problem is that I use a lot of Runtime fields (https://processwire.com/modules/inputfield-runtime-only/) and the DB selector approach for table fields doesn't work in these. The selector is ignored and all rows are returned. I have been playing around with output formatting in various places and even doing a `getFresh()` in `renderMarkup()` in attempt to get it working. I'll keep digging because the time and memory savings are enormous (as expected), but if you have any ideas, it would be greatly appreciated.

PS the DB selector approach works just fine in frontend templates, process modules, Tracy console, etc. It's just these runtime only fields. It's all very confusing :)

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - on a somewhat related note - I feel like if we can find table rows via a DB query (rather than in-memory selector), then we should also be able to count the number of rows without first loading them. I know it's easy via a direct SQL query, but I still feel like the API should also support this. 

Maybe `$page->count()->survey_results('survey_parent=15415')`

Or maybe it would need to be like `$page->survey_results('count=1, survey_parent=15415')` - a little bit similar to how findRaw() supports `objects=1` in the selector.

**Comment by ryancramerdesign** [comment]
@adrianbj If I remember correctly the ability to call a field name as a method and have it use that selector argument is a feature of FieldtypeMulti, so will only be available on fields that extend it, such as FieldtypeTable. It looks to me like that RuntimeMarkup field is not a FieldtypeMulti. However, I would guess that you could still make use of the selectors in those template files that the runtime markup field uses. 

Good point about counting, yes I would guess that would be possible. The `count=1` in the selector seems like a worthwhile thing to support. I've not tried but I'm thinking you could accomplish it now with `$count = $page->survey_results('limit=1, selector...')->getTotal();`

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - I tried making RuntimeMarkup extend FieldtypeMulti, but that didn't help. And unfortunately as I noted, the selector in field method approach doesn't work in the file that RuntimeMarkup uses. I've even tried hacking that directly into RuntimeMarkup's `___wakeupValue` in case there was an issue with the way it uses $files->render, but still no luck.

Regarding `getTotal()` - it doesn't seem to work at all on Table fields - it always returns zero (even when used in a place where the field method approach works). In fact it returns 0 all the time, even when I do a `find` on the table field, or even directly on a `$page->survey_results->getTotal()`.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - I'd also love to know if there is a way to use the field method approach to return unformatted values. In other words, a way to replicate: `$u->getUnformatted('contact_log')->find('person='.$user)->last();` without loading all the results in the contact_log table first.

All I can think of is to turn `of` off on the page first and then turn it back on after the table query.

**Comment by adrianbj** [comment]
@ryancramerdesign - I am seeing some more things that might be related to: https://processwire.com/talk/topic/26980-exception-formatted-value-may-not-be-used-for-saving-when-get-ing-or-find-ing-page-via-ajax-unless-i-call-pages-offalse/#comment-223173

Compare these, noting that I am already on the 2261 page so `$page` is already set to the same page as when I load it via the `$pages->get(2261)`. In one case you need to turn off `of` on `$pages`, but for the other turning it off for `$u` is enough.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/871211/217926577-87646dd2-9f1c-4399-bdcf-f578eaee083b.png">

<img width="741" alt="image" src="https://user-images.githubusercontent.com/871211/217926629-afc07ed6-f96c-4614-987f-f7d61036f639.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/871211/217926781-d8aaec9d-43e8-47dd-9f15-dfb850c8c0e9.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/871211/217926900-0c900241-16f8-43af-8b9b-77bc5d7fd35a.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/871211/217927021-afe1a607-fc7e-4180-bf4b-698c0141fa6b.png">

**Comment by adrianbj** [comment]
Hi again @ryancramerdesign - I have another issue while trying to convert all my table `find()` queries to the method approach. 

The issue is sub-selectors. Take this which works (via the in-memory selector):
<img width="834" alt="image" src="https://user-images.githubusercontent.com/871211/217961404-8adb2ea5-41ed-42f4-95ee-2b9938bee747.png">

But if you try the method approach it fails with this error: "Unknown column 'field_received_messages.message_send_method' in 'where clause'"

<img width="767" alt="image" src="https://user-images.githubusercontent.com/871211/217961467-e1e81d33-5c56-48ba-bd4d-3cebdc11c28d.png">

It would be great to have DB level support for sub-selectors, because the `find()` version is taking many seconds because the table has a lot of rows.

**Comment by adrianbj** [comment]
@ryancramerdesign - another thought for you. I feel like we could all really benefit from a `findRaw()` type approach for table fields that allowed us to just return an array of the required subfields. I think supplying an array of fields as a second argument to the field method would work well.

The reason I bring it up is that in one of my use cases, I just need the IDs of pages held in a page reference subfield. 

Compare the very slow 2.6 secs for:

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/871211/217971628-d41ed9e1-f7b7-48e5-9383-9fb6bacce4c4.png">

vs the 27 ms for: 

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/871211/217972749-970252c6-7d52-4d3e-a34d-0f9922ce945f.png">

Now obviously it's an easy SQL query, but it would still be much nicer to do this via the API.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - just wondering if you'd like me to post the above new bugs and requests in the Table field's board in the forum, or if here is OK. I want to make sure this stuff doesn't get lost, especially the issues with output formatting, sub-selectors and the bug with runtime field queries. Thank you.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - just following up regarding the table subfield selectors when doing a DB query vs an in-memory find. Do you think this is something that can be supported?

There are quite a few other questions / requests above but this is the key one for now that I think really needs addressing.

Thanks.
