### ISSUE TITLE
$fields->find() not working

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1675]
### Short description of the issue

`$fields->find()` seems to have broken since 3.0.210

PW 3.0.210 master:
![2023-01-30_170345](https://user-images.githubusercontent.com/1538852/215385311-6c2911bd-32b2-4b18-9015-0ff422297d84.png)

The same site running current PW 3.0.211 dev:
![2023-01-30_170515](https://user-images.githubusercontent.com/1538852/215385323-9a4d6fee-0093-4b89-9ce4-8bdf93aa651b.png)

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by adrianbj** [comment]
@Toutouwai - do you think this might be related to https://github.com/processwire/processwire-issues/issues/1674 ?

**Comment by matjazpotocnik** [comment]
My tests show that 3.0.211 works fine, but this commit https://github.com/processwire/processwire/tree/2ebb0055bec1fb0af768ec1e07ebafcceccacc26 seems to be a culprit, line 1616

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
