### ISSUE TITLE
Fieldgroup::get() dropped support getting fields by selector

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1679]
### Short description of the issue

Since Update to 3.0.211
`Fieldgroup::get()` dropped support getting fields by selector string `'type=FieldtypeText'` if $page is an item of **FieldtypeRepeater**

### Steps to reproduce the issue

```
// in 3.0.211
$page->fields->get(type=FieldtypeText'); // return NULL
// in 3.0.210
$page->fields->get(type=FieldtypeText'); // return object(ProcessWire\Field)
```

* ProcessWire version: 3.0.211
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@kixe I'm pretty sure this is the same issue as #1675 which has been fixed, can you confirm? Thanks

**Comment by kixe** [comment]
Perfect. Thanks
