### ISSUE TITLE
Emails in IDN format do not get saved, cannot be entered in GUI

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#1680]
### Short description of the issue

Emails in IDN format do not get saved, cannot be entered in GUI

### Expected behavior
Emails in IDN format can be entered into email field and saved. Since PW 3.0.208 sanitizer email supports IDN format. But  InputfieldEmail and FieltypeEmail do not atm.

### Actual behavior
Emails in IDN format can neither be entered through the email input field nor saved via API.

### Optional: Suggestion for a possible fix
Replace all occurences of sanitizer->email($value) with sanitizer->email($value, ['allowIDN' => 2]) in InputfieldEmail.module and FieldtypeEmail.module. This allows for saving through API
But still the client side email validation for the input will not accept IDN strings. This should be addressed, too. 

### Steps to reproduce the issue
Try to enter a value like "hans.müller@müller.com" into an email input and save it.
Try to save a string like "hans.müller@müller.com" via API to an email field like
```
$p->setAndSave('email', 'hans.müller@müller.com');
```
### Setup/Environment

* ProcessWire version: 3.0.209dev
* (Optional) PHP version: 8.1

See related forum post: https://processwire.com/talk/topic/28125-emails-in-idn-format-do-not-get-saved-cannot-be-entered/

**Comment by ryancramerdesign** [comment]
@gebeer Thanks, I have added support for this

**Comment by matjazpotocnik** [comment]
@gebeer, could you check this and close the issue if done?
