### ISSUE TITLE
FilesMatch regex in .htaccess blocks .well-known directory access

### ISSUE THREAD

**Issue by isellsoap** [processwire/processwire-issues#1682]
### Short description of the issue

[This line in the .htaccess file](https://github.com/processwire/processwire/blob/dev/htaccess.txt#L116) early on blocks all access to URL paths starting with a dot, including `.well-known`, which is used by many tools as an authentication mechanism. 

### Expected behavior

`.well-known` should be allowed to be accessed by the outside world.

### Actual behavior

Access for every URL path starting with a `.` (including `.well-known`) is being blocked.

### Optional: Screenshots/Links that demonstrate the issue

Check out the [corresponding regex101.com link](https://regex101.com/r/NxT3Kj/1) to see that the current regex matches `.well-known` and thus blocks access to it.

### Optional: Suggestion for a possible fix

Include `(?!well-known)` in the corresponding place to allow `.well-known` from being accessed.

```
<FilesMatch "\.(inc|info|info\.(json|php)|module|module\.php|sh|sql)$|^\.(?!well-known).*$|composer\.(json|lock)$">
```

Check out the [corresponding regex101.com link](https://regex101.com/r/WKe369/1) to see the fix in action.

### Setup/Environment

* ProcessWire version: Latest dev version (as of creation of this ticket)

**Comment by ryancramerdesign** [comment]
@isellsoap I don't find that it is blocking it here because rule 12 lets it through, though only if `.well-known` directory is in the web root (same directory as the .htaccess file). Just tested to confirm. I thought that web root is the only place a .well-known would be, but do you find that they can also be in subdirectories? If so, then we would need to account for that in the .htaccess.

**Comment by isellsoap** [comment]
@ryancramerdesign You are correct, in my case the `.well-known` directory doesn’t actually exist physically, but is only being used as a redirect. Specifically, setting up [fed.brid.gy](https://fed.brid.gy/docs#setup) requires a few redirects in that regard. And that is not possible with the current PW .htaccess file.

I’m not sure if this argument is solid enough for you to change the FilesMatch regex as proposed. :-)

**Comment by ryancramerdesign** [comment]
@isellsoap I don't know for sure yet if we should update that FilesMatch rule or not, maybe it makes sense to, let's see if anyone else runs into it or has additional info. The .htaccess file is a file that's meant to be customized for each installation, kind of like the /site/config.php file and to a lesser degree, the /index.php file. We've also got a section in there that has some .well-known examples of things you can uncomment if needed, though it sounds like your case is different. The goal is for the .htaccess just to be a good starting point to customize from, as well as lock down as much as possible. When I've used the self hosted SSL, it's been cPanel that adds new rules with .well-known the top of the .htaccess automatically that seem to take precedence. But it sounds like these things vary quite a bit depending on the environment.

**Comment by matjazpotocnik** [comment]
@isellsoap based on your response I'm closing this issue, let me know if it needs re-opening.
