### ISSUE TITLE
ProcessPageEditLink returns "Unrecognized path" on links including ".php"

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [processwire/processwire-issues#1684]
### Short description of the issue

When entering a link that includes ".php" into a URL field (e.g. https://google.com/index.php), the system returns a "Unrecognized path" upon re-opening the link modal. This seems to be a new issue. Before upgrading from 3.0.165 to 3.0.210, the same links were working just fine.

### Steps to reproduce the issue

1. Create a link in a CKEditor field
2. Add `https://google.com/index.php` as link
3. Click "Insert Link"
4. Re-open the just added link
5. The modal should say "ProcessWire: Unrecognized path"

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.0

**Comment by ryancramerdesign** [comment]
Thanks @dsdsdsdsdsds I've pushed a fix for this issue

**Comment by dsdsdsdsdsds** [comment]
Fixed, thanks!
