### ISSUE TITLE
Fresh install of latest Processwire doesn't let user login to admin

### ISSUE THREAD

**Issue by dicabrio** [processwire/processwire-issues#1685]
### Short description of the issue

Cannot login after a fresh install of the latest Processwire

### Expected behavior

After login and credentials are verified I should see the admin panel.

### Actual behavior

I keep seeing the Login screen.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

No fix at the moment

### Steps to reproduce the issue

1. Download v3.0.210 from the website
2. Install downloaded version
3. Go to admin page 
4. Login with credentials
5. Resulting screen is the Login screen

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.1.5
* (Optional) MariaDB version: 10.6.7

I have other versions of Processwire running like v3.0.200 and have no problem with that version.

**Comment by matjazpotocnik** [comment]
@dicabrio, based on [this forum post](https://processwire.com/talk/topic/28160-php-error-after-upgrading-to-php-81/), it looks like you fixed this? Should we close this issue then?

**Comment by dicabrio** [comment]
Yes You can close it. It's due to reformatting the .htaccess. I added a .prettierignore file where I added `.htaccess`. This stopped prettier to format .htaccess files
