### ISSUE TITLE
ProcessWire\ProcessUser::getEditableRoles(): Argument #1 ($page) must be of type ProcessWire\User, ProcessWire\Page given

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1686]
### Short description of the issue

You get the above error if you try to visit: /access/users/edit/?id=xxxx when xxxx is the ID of a regular page rather than a user page. I understand this is not a supported situation and you have to manually adjust the URL to result in this, but I still think it could be handled more gracefully by redirecting to /admin/page/edit/?id=xxxx in the same way it does when you do the reverse of the described scenario, ie you put the ID of a user page at the end of the regular page edit URL.

### Expected behavior

Automatic redirect to page edit URL

### Actual behavior

Error in title

**Comment by matjazpotocnik** [comment]
@adrianbj Duplicate of https://github.com/processwire/processwire-issues/issues/1570 ?

**Comment by adrianbj** [comment]
Ah yes - good catch - thanks :)
