### ISSUE TITLE
Typo in Modules::findByInfo()

### ISSUE THREAD

**Issue by the-ge** [processwire/processwire-issues#1687]
### Short description of the issue

The normalization (for the lack of a better word) of the `$selector` argument of the Modules::findByInfo() method seems to have a typo. I'm pretty sure that, instead of an `if`, it should've been an `elseif` at line 1794.

### Expected behavior

If `$selector` is an array, `$has` remains an empty string.

### Actual behavior

If `$selector` is an array, `$has` gets its content.

### Optional: Screenshots/Links that demonstrate the issue

```PHP
		if(is_array($selector)) {
			// find matching all values in array
			$keys = $selector;
			$properties = array_keys($keys);
1794		} if(!ctype_alnum($selector) && Selectors::stringHasOperator($selector)) {
			// find by selectors
```

### Optional: Suggestion for a possible fix

```PHP
		if(is_array($selector)) {
			// find matching all values in array
			$keys = $selector;
			$properties = array_keys($keys);
1794		} elseif(!ctype_alnum($selector) && Selectors::stringHasOperator($selector)) {
			// find by selectors
```

### Steps to reproduce the issue

1. Use the Modules::findByInfo() method with an array as the first argument.

### Setup/Environment

* ProcessWire version: 3.0.210 (also on GitHub, both master and dev)

**Comment by ryancramerdesign** [comment]
Thanks @the-ge good eyes, you are right it's a typo. I've pushed a fix.
