### ISSUE TITLE
ProcessPageEditLink: attempt to ready property "id" on null

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1689]
### Short description of the issue

After creating a link in a CKEditor field (in the case below I use the "Select Child Page" option), Tracy Debugger records an error: "Attempt to read property "id" on null in ...\Process\ProcessPageEditLink\ProcessPageEditLink.module:422"

![2023-02-17_113120](https://user-images.githubusercontent.com/1538852/219502240-01a03f0f-879f-4479-b4a9-68a9194b0ee5.png)

### Setup/Environment

* ProcessWire version: 3.0.211

**Comment by ryancramerdesign** [comment]
@Toutouwai I'm not seeing the issue here, and my line numbers don't match up with yours, so maybe it's already been fixed. But just in case, I updated a conditional to add an additional check. Please let me know if you continue to see it.

**Comment by Toutouwai** [comment]
Thanks
