### ISSUE TITLE
Documentation: Add "owner" selector to the Selectors page of the docs

### ISSUE THREAD

**Issue by rastographics** [processwire/processwire-issues#1692]
### Short description of the issue

Please add information about the "owner" selector to the documentation on selectors.

### Expected behavior

There should be a section on the [Selectors Documentation page ](https://processwire.com/docs/selectors/) explaining the owner selector.

### Actual behavior

There is only [a blog post that describes owner selector](https://processwire.com/blog/posts/processwire-3.0.95-core-updates/). But if a developer does not already know about it, it is very difficult to find out about this very useful selector.

### Optional: Suggestion for a possible fix

Please just put the information from the blog post onto the documentation page.

### Steps to reproduce the issue
N/A

### Setup/Environment
N/A

* ProcessWire version: N/A
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@rastographics Thanks, I didn't realize they weren't mentioned there,I have updated the Selectors doc page to mention owner selectors and link to the dedicated post.
