### ISSUE TITLE
Impossible to trash current page using the api in any situation

### ISSUE THREAD

**Issue by rastographics** [processwire/processwire-issues#1693]
### Short description of the issue

The `$pages->trash($page)` method OR `$page->trash()` method do not work from any front-end template.
[This issue hints at the problem](https://github.com/processwire/processwire-issues/issues/869) but this is not specific for Superuser. This is applicable to any user.

### Expected behavior

I would expect to be able to trash (not delete) the current page, especially as I will be redirecting to a different page after the operation. 

### Actual behavior

When trying to trash the current page, the error message "This page may not be placed in the trash" is thrown.
This is because `isDeletable()` returns false because the current page is not allowed to be deleted (even if it may be safe to Trash).

### Optional: Screenshots/Links that demonstrate the issue

[Issue outlined on the forum](https://processwire.com/talk/topic/28209-error-this-page-may-not-be-placed-in-the-trash/#comment-230866)

### Optional: Suggestion for a possible fix

Avoid checking if page is current page, when checking if it is trashable.
Should `isDeleteable()` be checked when determining if page is "trashable"? Because these are 2 different operations.
As @ryancramerdesign says [here](https://github.com/processwire/processwire-issues/issues/356#issuecomment-328575889), it is not safe to **delete** the current page, but it is OK to **trash** the current page.

Solution then may be on line 44 of PagesTrash.php, replace the check on `pages->isDeleteable($page)` with a new method `pages->isTrashable($page)` that is not as strict as needed for actual deleting.

### Steps to reproduce the issue

1. Add a form to the template file, with a submit button, that posts to the current page.
2. Handle the form post with this code: `$page->trash(); $session->redirect("/")` or similar.

### Setup/Environment

ProcessWire: 3.0.211
PHP: 8.1.13
Webserver: Apache/2.4.54 (Debian)
MySQL Server: 10.4.27-MariaDB-1:10.4.27+maria~ubu2004-log
MySQL Client: mysqlnd 8.1.13

**Comment by ryancramerdesign** [comment]
@rastographics I think it's probably going to be problematic to trash the current page too. At least, I imagine anything part of  the shutdown process won't be happy if the current page is in the trash, since trashed pages are not renderable, and thus would never be expected to be a $page API variable. A better strategy would be to trash it from another page. But if you find it is necessary to trash the current page, you could try swapping out the $page API variable with another, before doing the trash operation:
~~~~~
$wire->wire('page', $pages->get('/')); 
$page->trash(); 
~~~~~

**Comment by matjazpotocnik** [comment]
@rastographics, does Ryan's comment resolve your use case? Can you close this issue?

**Comment by matjazpotocnik** [comment]
@rastographics (and others), based on Ryan's answer, I'm closing this issue.
