### ISSUE TITLE
PHP 8.1 Deprecation in ProFields Combo Field

### ISSUE THREAD

**Issue by nurkka** [processwire/processwire-issues#1694]
### Short description of the issue

Using a ProFields Combo-Field with 3 Text-MultiLanguage-Subfields and 2 Languages. The tabs for the second language are currently not filled yet. While editing pages in the backend, the following warning is displayed in the error log:

```
PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in [.../site/modules/FieldtypeCombo/ComboLanguagesValue.php:101]
```

### Setup/Environment
* ProcessWire version: 3.0.210
* PHP version: 8.1.13
* MySQL version: 8.0
* ProFields Combo Field 0.1.1

**Comment by ryancramerdesign** [comment]
@nurkka Thanks, I will update FieldtypeCombo for that and it'll appear in the next released version.
