### ISSUE TITLE
Functions API missing log() despite support in FunctionsWireAPI.php

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#1696]
### Short description of the issue

Whilst the `FunctionsWireAPI.php` support file contains a `wireLog()` function, it is not exposed as `log()` via the functions API.

### Suggestion for a possible fix

For completeness, perhaps this could be added to `FunctionsAPI.php`

### Setup/Environment

* ProcessWire version: https://github.com/processwire/processwire/blob/d2cde11e4dba7cfea6b748093d99d564a42683a0/wire/core/FunctionsAPI.php

**Comment by ryancramerdesign** [comment]
@netcarver The `log()` is a native PHP function, so we couldn't implement that one. I recommend just using `wireLog()` or `wire()->log()`
