### ISSUE TITLE
Admin theme settings (UIKit) Panel background overrides all style definitions with white

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1697]
### Short description of the issue

Jquery overrides for background color on AdminThemeUiKit settings.

### Expected behavior

Should be able to style using LESS or CSS but the jquery call overrides.

### Actual behavior

Jquery call overrides background color style.

### Optional: Screenshots/Links that demonstrate the issue

![image png a71659fae279248a2a07c470e4674f06](https://user-images.githubusercontent.com/58667283/222160605-07f2f146-2186-4077-bccd-1be10f9fbb4e.png)

### Optional: Suggestion for a possible fix

Either eliminate or replace this code in \wire\modules\AdminTheme\AdminThemeUikit\config-field.js::

```
$(document).ready(function() {
	$('#_adminTheme').find('input[type=radio],input[type=checkbox]').change(function() {
		updateAdminThemeUikitExample();
	});
	$('#_adminTheme, #_adminTheme > *').css('background-color', '#fff'); // <--- This seems to be the culprit.
	updateAdminThemeUikitExample();
	initAdminThemeUikitColumnWidth();

});
```

* ProcessWire version: 3.0.213

**Comment by ryancramerdesign** [comment]
@solonmedia I don't have that color theme to test with, but I tried moving the color setting code and have it pull from the existing background color rather than #fff. The reason it needs to do this is so that the "Border: None" example works properly. Please let me know if you find the update here doesn't work. Thanks.

**Comment by solonmedia** [comment]
Yes! Perfect, that did it.

**Comment by netcarver** [comment]
Closing this.
