### ISSUE TITLE
PagePathFinder and urlSegments work differently with UTF8 config 

### ISSUE THREAD

**Issue by juruus** [processwire/processwire-issues#1699]
### Short description of the issue

**PagePathFinder** works differently with **UTF8** config. When a urlSegment has an underscore and an uppercase character the pagePathFinder sanitizes the url differently and adds the urlsSegment to the badNames array and returns 400.

### Expected behavior

UrlSegment sanitation should work similarly with or without $config->pageNameCharset = "UTF8";
Documentation says that only lowercase characters are supported. But then again UTF8 config and pageNameWhitelist provide a way to set a different behavior. 

### Actual behavior

Without a UTF8 config an urlSegment like `fi_FI` is valid. With UTF8 the segment is sanitized to fi_fi and it differs from the original url which leads to 400 error.

### Optional: Suggestion for a possible fix

We hacked this in production by modifying pagePathFinder around #519 with this:

```php
foreach($parts as $n => $name) {
  $lastPart = $name;
  if(ctype_alnum($name)) continue;
  // $namePrev = $name; ORIGINAL
  $namePrev = strtolower($name); // QUICK FIX
  $name = $sanitizer->pageNameUTF8($name);
  $parts[$n] = $name;
  if($namePrev !== $name) $badNames[$n] = $namePrev;
}

if($result['response'] < 400 && count($badNames)) {
  $result['response'] = 400; // 400=Bad request
  $this->addResultError('pathBAD', 'Path contains invalid character(s)');
}
```

### Steps to reproduce the issue

1. set $config->pageNameCharset = 'UTF8';
2. set $config->pageNameWhitelist = '-_.abcdefghijklmnopqrstuvwxyz0123456789æåäßöüđжхцчшщюяàáâèéëêěìíïîõòóôøùúûůñçčćďĺľńňŕřšťýžабвгдеёзийклмнопрстуфыэęąśłżź-F-I-S-E-N';
3. create a template that allows url segments
4. create a page with the template
5. create a simple test template with code from below
6. test the page with urlSegment /pageUrl/fi_FI 
7. the url fails

```php
<?php namespace ProcessWire;

echo $input->urlSegment1

```

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.2.1
* (Optional) MySQL version: MariaDB 10.4.12

**Comment by juruus** [comment]
More details:
https://processwire.com/talk/topic/28234-urlsegments-underscores-together-with-uppercase-characters-cause-404-redirect/

**Comment by ryancramerdesign** [comment]
@juruus Thanks, I've pushed a fix for this. Note that PW does not use anything but lowercase for page names/paths, but for your URL segments you can now. Since mixed case URLs are kind of rare and may not be expected, you may want to check for both `fi_fi` and `fi_FI` in your conditionals that check the URL segment(s), like below. If you do that, also use the correct version you intend in your `<link rel='canonical' ... />` head tag so that the search engines don't get confused. 
~~~~~
if(strtolower($input->urlSegment1) === 'fi_fi') {
  // fi_FI, fi_fi, etc. 
}
~~~~~

**Comment by juruus** [comment]
Thank you @ryancramerdesign, works as it should!
