### ISSUE TITLE
TfaEmail: Values from module config will not be taken into account

### ISSUE THREAD

**Issue by juergenweb** [processwire/processwire-issues#1700]
### Module config values not used 

TfaEmail module comes with configuratin settings for code length and expiration time in the backend,  but it seems that the configuration values will not be taken into account.

### Expected behavior

If I change fe the expiration time from 180 to 200 seconds in the module configuration, then the following code should output the changed value:

`$tfa->codeExpire`

This should output 200 in this case, but it always returns 180.

### Actual behavior
The value always stays on 180 as default value. You will find the setting of the value inside the constructor on line 28 of the TfaEmail.module file:

`$this->set('codeExpire', 180);`

This value will never be overwritten inside the code with the value as set inside the module configuration. I think this is not the way it should go.

### Optional: Suggestion for a possible fix

The hardcoded values should be replaced by the configuration values .

**Comment by ryancramerdesign** [comment]
@juergenweb I can't seem to duplicate this. The 180 value set in the constructor is just the default value, which is overwritten with the module configured value when the module is init()'d, and this is how the configuration of all modules work. 

To test, I went to Modules > Configure > TfaEmail and set the codeExpire value to 200, then saved. The module screen now shows 200. In a PHP file that boots PW, I put this in there:
~~~~~
$tfa = $modules->get('TfaEmail');
echo $tfa->codeExpire;
~~~~~
It also outputs 200. Can you provide more detail on how to duplicate the issue? For instance, I'm not sure what the source of your `$tfa` variable is. Make sure you are getting it from `$modules` and not from a `$tfa = new TfaEmail();`

**Comment by juergenweb** [comment]
@ryancramerdesign 

You are right, this was my fault: I have used the object (instance) as $tfa and not the module. :-(
It works as expected, so I close this issue!
Sorry for bothering you!
