### ISSUE TITLE
PageExportImport data-pwid persisting

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1702]
I wasn't sure where to communicate this, it's almost not a bug more a note...

I recently used PagesExportImport to transfer a large number of pages from one install to another. I've launched this site this morning, and 'markup-qa-errors' has gone a bit mental, resolving page paths to repeaters and then flagging them as admin urls.

After a lot of time trying to figure out why, I discovered that the html in the database field already has the data-pwid attributes which MarkupQA uses to resolve links. I'm almost certain that the IDs are from the initial install that I transferred the data from using PagesExportImport.

It could be that I've done something wrong in the process, but it could also be that PagesExportImport needs to check and replace, or at least remove the data-pwid attributes.

**Comment by ryancramerdesign** [comment]
@chriswthomson So far I can't seem to reproduce this one. The de-abstraction of links is handled during export [here](https://github.com/processwire/processwire/blob/master/wire/modules/Fieldtype/FieldtypeTextarea.module#L357). I tested out a few exports and found it to be working, with no data-pwid attributes surviving export. I wonder if you might have the link abstraction not enabled in the HTML options for your field, or if maybe the Content-Type Textarea field setting is not set to HTML? Or if this is for something other than a Textarea field please let me know what kind it is. Thanks.

**Comment by chriswthomson** [comment]
Thanks for looking into this @ryancramerdesign, I use PagesExportImport reasonably frequently and this is the first time I've come across the problem. I will have had those settings in place, on a standard textarea too. I'll close this ticket as I expect there's something I've done in the process that's caused it.
