### ISSUE TITLE
PageFrontEdit module saving bug with new InputfieldTinyMCE

### ISSUE THREAD

**Issue by jploch** [processwire/processwire-issues#1703]
### Short description of the issue

Editing a Textarea with InputfieldTinyMCE with the inline editor (option A) is not saving if you cancel the first edit and than start another one. The second attemp to save shows the alert "No changes to save" and is not saving. It works fine if you switch the textarea to CKEditor.

### Expected behavior

The changes should always be saved when clicking the save button.

### Actual behavior

If you click the cancel button after you started to type something and then try to edit the same field again, saving is not working anymore (It seems like the "pw-changed" class is not added).

### Steps to reproduce the issue

1. Double click the area where the field is output in your frontend.
2. Type some text.
3. Click cancel button und confirm the cancel alert.
4. Double click the area again.
5. Type some text.
6. Click save button.

* ProcessWire version:  3.0.210
* PHP version: 8.0

**Comment by ryancramerdesign** [comment]
Thanks @jploch I've pushed a fix for this issue.

**Comment by jploch** [comment]
@ryancramerdesign Works like a charm. Thank you!
