### ISSUE TITLE
Template used for images custom fields should not be available for pages

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1704]
### Short description of the issue

When using the "Custom fields" option for an images field, a "field-name_of_images_field" template is created.

When adding a new page this special template is available for selection.

![2023-03-16_161549](https://user-images.githubusercontent.com/1538852/225504985-974d6bba-7e7d-4d04-a28a-912e22d47c93.png)

I don't think this sort of special template should appear in the template dropdown for pages because it almost certainly isn't something a user will want to select (e.g. there won't be a template file and so the page will thereafter throw a 404).

### Setup/Environment

* ProcessWire version: 3.0.213

**Comment by adrianbj** [comment]
@Toutouwai - a duplicate of https://github.com/processwire/processwire-issues/issues/1524 ?

**Comment by Toutouwai** [comment]
Right you are, thanks.
