### ISSUE TITLE
Url field: When modifying a valid url, entering invalid characters will delete both the invalid and the original / valid url

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#1705]
### Short description of the issue

When using a url field on a page in the ProcessWire editing interface:
When modifying a valid url, entering a url with invalid characters will delete both the invalid and the original / valid url

### Expected behavior

* When entering a valid url, the url is saved (works)
* When modifying the valid url and entering invalid characters, then the "original, valid url" is restored (not deleted)

### Actual behavior

This url is saved in my page:
![image](https://user-images.githubusercontent.com/129573/226187065-c072d6ac-fe0e-47a5-81c4-20b38010b835.png)

As an editor, I modify the url (note the invalid Danish ø-character -> https://prøcesswire.com/)
![image](https://user-images.githubusercontent.com/129573/226187104-c9d64604-96a6-428d-bb4e-fffa3f5bd8a8.png)

Error message is shown - url is gone
![image](https://user-images.githubusercontent.com/129573/226187125-f68b1cab-4d65-4295-bab0-0b2ff80701d7.png)

On page refresh, the url is still gone
![image](https://user-images.githubusercontent.com/129573/226187143-d849bea8-28ec-456e-94fe-c1fa83fcb79d.png)

### Optional: Suggestion for a possible fix

* When a valid url exists and the editor modifies the url using invalid characters, then keep the "original, valid url" (don't delete it)

### Steps to reproduce the issue

1. Create template 'foo'
2. Add url field
3. Create page (use template 'foo')
4. Enter valid url: https://processwire.com/
5. Save page. Url field is now populated
6. Modify url: https://prøcesswire.com/
7. Save page
8. Refresh page (press CTRL+F5 on Windows). Url field is now empty.

### Setup/Environment

* ProcessWire version: 3.0.210

**Comment by matjazpotocnik** [comment]
Ryan, it looks like `if($error) $value = $this->val();` is missing at the and of setAttributeValue() in InputfieldURL.php ?

Klor, just for info, URL field allows IDN characters.

**Comment by ryancramerdesign** [comment]
Thanks @klor and @matjazpotocnik I've added matjazpotocnik suggested fix for this.

**Comment by matjazpotocnik** [comment]
@klor closing this, let me know if the fix isn't working for you.
