### ISSUE TITLE
"Unknown log: xyz" since 3.0.214 dev

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#1707]
I have upgraded Processwire from 3.0213 to 3.0.214 and now I can't open any logfile.
Logfiles are visible but when I am click on the file the requests need very long and says for example: "Unknown log: session".

I have tried to delete my logfiles on the server but this did not help. Logfiles are created but can not be opened.

PHP/FPM: 8.0.28
MySQL: 8

**Comment by matjazpotocnik** [comment]
https://github.com/processwire/processwire/pull/265/commits/a333bb3d642ca586381e74257c588c91182399f7

**Comment by gebeer** [comment]
> [processwire/processwire@a333bb3](https://github.com/processwire/processwire/commit/a333bb3d642ca586381e74257c588c91182399f7)

Yes this helps and makes logs viewable again. But the Log overview still has same changed time for all logs in the list.

**Comment by matjazpotocnik** [comment]
Yes, I had to delete all logs

**Comment by tiefenb** [comment]
@ryancramerdesign can you add this PR to fix this issue?
https://github.com/processwire/processwire/pull/265

**Comment by tiefenb** [comment]
Fixed in https://github.com/processwire/processwire/commit/f7ee00d78530d4922ce1d8fb1343b66b07895ee4
