### ISSUE TITLE
Wrong link for Module interface

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1708]
At https://processwire.com/docs/modules/types/ there is a link to Module Interface linked to https://processwire.com/processwire/module/ resulting in 

![image](https://user-images.githubusercontent.com/7663992/226976070-0fbbdc05-b939-442e-bc58-3c2b5f654cfc.png)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've fixed that link
