### ISSUE TITLE
Pages find with parent that doesn't exist bug

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1709]
### Short description of the issue

If you do a find like this where you use the parent selector and specify a name or path to a page that doesn't exist, it returns the homepage
<img width="573" alt="image" src="https://user-images.githubusercontent.com/871211/227079736-76beb6f2-faa8-4551-b4ad-969cb2598542.png">

I have been using code like this code on a site for at least 5 years and I am certain it used to work as expected, but in my current testing even going back to 3.0.206 still shows the bug.

### Expected behavior

An empty page array

### Actual behavior

A page array with home in it.

### Optional: Suggestion for a possible fix

Note that the generated query looks like this with the IN(0) being the culprit.
```
SELECT pages.id,pages.parent_id,pages.templates_id
FROM `pages`
WHERE (pages.parent_id IN(0))
AND (pages.status<1024)
GROUP BY pages.id
```

### Setup/Environment

* ProcessWire version: Current dev back to at least 3.0.206

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks good now!
