### ISSUE TITLE
TinyMCE throws open_basedir error

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1710]
### Short description of the issue

```php
PHP Warning: is_file(): open_basedir restriction in effect. File(/wire/modules/Inputfield/InputfieldCKEditor/InputfieldCKEditor.module) is not within the allowed path(s): (xxx) in [.../modules/InputfieldTinyMCE/InputfieldTinyMCESettings.php:528](vscode://file/.../InputfieldTinyMCESettings.php:528)
```

### Suggestion for a possible fix

Change `config->urls->root` to `config->paths->root` in InputfieldTinyMCESettings.php:528

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock could you verify Ryan's fix please and close this issue?
