### ISSUE TITLE
HTML entities in ProcessPageList JS alerts are not displayed correctly

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1712]
### Short description of the issue

Example when attempting to move a page to a disallowed parent:

![2023-03-29_120259](https://user-images.githubusercontent.com/1538852/228386260-5e8b595a-792c-4006-ba00-6928d2b2f3ad.png)

### Setup/Environment

* ProcessWire version: 3.0.214

**Comment by Toutouwai** [comment]
Looking again it might not be a double-encoding issue or a PW issue specifically. Perhaps due to security updates in browsers?

If I do the following (which should all render the same character)...
```
<script>
	alert('&ldquo; &#8220; “');
</script>
```
...then only the last one shows correctly.

![2023-03-29_122229](https://user-images.githubusercontent.com/1538852/228388552-0e1a7cdb-1e02-406c-8593-defb02a58606.png)

Edit: `\u201C` also works

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this. I set it to decode the entities and then use Vex rather than a regular JS alert here. It may be that the same fix is okay for a regular JS alert, but I'm not positive yet if it's okay to send anything and everything into a JS alert just yet.
