### ISSUE TITLE
Call to a member function numChildren() on null

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#1714]
### Description of the issue

Trying to access the module configuration page of ProcessPageList, I get an error 
```
member function numChildren() on null 
wire/core/PagesEditor.php:366
```
I have debugged and found that [this code](https://github.com/processwire/processwire/blob/de8307a2a9549c5fa7897ea25b6b41a545aa715c/wire/modules/Process/ProcessPageList/ProcessPageList.module#L783) returns NullPage, at least in a multilingual setup. I have changed the 'get' method to 'getByPath ' and that fixed the issue.

* ProcessWire version: 3.0.210

**Comment by matjazpotocnik** [comment]
It doesn't happen here on 3.0.214. `$admin->path` is `/processwire/` and thus `$pages->get($admin->path . 'page/list/');` returns a page object with id 8.

**Comment by Lazerproof** [comment]
@matjazpotocnik  Thank you for testing.
I have dug a little deeper and found out that there are two additional conditions to get the issue:

- The PagePaths module has to be installed
- The page name for the homepage for the default language has to be non-empty

![image](https://user-images.githubusercontent.com/5707348/229460330-b613ac54-9d31-4847-a2f4-c0227dbc3be3.png)
![image](https://user-images.githubusercontent.com/5707348/229461011-a511edaf-68e6-40ea-b4a0-33e02d0aed86.png)

**Comment by matjazpotocnik** [comment]
What is $admin and $admin->path in this scenario?

**Comment by Lazerproof** [comment]
> What is $admin and $admin->path in this scenario?

$admin is the admin root page and $admin->path is the path of this page, by default, it is a page with ID: 2. The path of admin root page could be different as you can change it while installation process or later by changing the name of it. By default, it is 'processwire'.

**Comment by matjazpotocnik** [comment]
Yes, I know that. I'm just curious what's the path in your case. As I can't replicate here, even with PagePaths module instaled (and rebuilt index) and set the page name for the homepage for the default language.

**Comment by ryancramerdesign** [comment]
@Lazerproof I can't duplicate it either, but have pushed an update to the line in the PagesEditor.php file you indicated was producing an error. I think it can be avoided just by checking that $parent has a id before accessing the numChildren method. Though please let me know if it continues to appear.

**Comment by matjazpotocnik** [comment]
@Lazerproof would you please test on the latest PW dev?

**Comment by matjazpotocnik** [comment]
Closing on the assumption this is fixed. @Lazerproof Please comment again if Ryan's fix doesn't work for you.
