### ISSUE TITLE
Method Page::getForPage does not exist or is not callable in this context on a page reference field

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1717]
### Short description of the issue

Trying to edit a page reference field and I am getting that error

### Expected behavior

No error - able to edit field settings

### Actual behavior

Error in title

### Optional: Screenshots/Links that demonstrate the issue

These are the settings for the page:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/871211/229632494-ef978ba4-1ce8-45cb-a5f5-479de4b42b78.png">

Note that template id 206 is a repeater template named "repeater_materials"

I am currently running 3.0.213 on this site and I know on previous versions this wasn't broken. I remember you making a change for getForPage for a similar bug I reported not long ago (can't currently find), so I wonder if that change may have broken this?

**Comment by adrianbj** [comment]
Ok, turns out this was due to a hook for `InputfieldPage::getSelectablePages` for this field and the `getForPage` on `$event->arguments('page')`. I would just close this, because I've worked around it, but I am kinda surprised  `InputfieldPage::getSelectablePages` hook would be called within ProcessField. Is that intentional?

**Comment by ryancramerdesign** [comment]
@adrianbj While ProcessField doesn't call it specifically, it's certainly possible for it to be called there since field configuration is being done, so I'm guessing it's being called by a field being configured.
