### ISSUE TITLE
"Enter file to translate" wipes existing translations

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1719]
### Short description of the issue

When using "Enter file to translate" for a file that already has some translations in it, the translation screen opens up but will be empty since the file is being created again which wipes all translations.

### Expected behavior

Existing translations should persist. Before creating the translation json file there must be a check if the file already exists.

### Steps to reproduce the issue

1. Translate any file
2. get the path of the json file for that translation, eg /site/templates/foo.php
3. Enter that path in the field "Enter file to translate"
4. Translations will be wiped.

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.214|
|PHP|8.1.13|
|Webserver|Apache/2.4.54 (Debian)|
|MySQL Server|10.6.11-MariaDB-1:10.6.11+maria~ubu2004-log|
|MySQL Client|mysqlnd 8.1.13|

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix for this
