### ISSUE TITLE
FieltypeTable in repeater: sqlstate error on clone

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#172]
### Short description of the issue

When cloning a repeater item that has a ProField Table in it, after save I get the following error:

`Error saving field "pricelist_2col" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '367' for key 'PRIMARY'`

### Actual behavior

The repeater gets saved but the table vanishes.

### Setup/Environment

* ProcessWire version: 3.0.50
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Unfortunately you can't usually nest repeating types among each other. If you need to do this, you'd have to stick with a repeating type that supports nesting, like FieldtypeRepeater or FieldtypeRepeaterMatrix, which supports nesting of Repeaters in Repeaters. I think there are probably a lot of things that would prevent a Table field from working in a repeater, but now that I know someone wants it I'll look into adding support in a future version of FieldtypeTable. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I haven't used Tables in a Repeaters myself, but I did test it for my TableCSVImport/Export modules as someone requested support for it. They seem to work fine. I know this issue is about cloning issues, but just wanted to let you know that others are using Tables in Repeaters.

**Comment by Toutouwai** [comment]
I have recently been working on a Table-related module and was testing tables inside repeaters. Seemed to work fine for me also.

**Comment by ryancramerdesign** [comment]
Glad to hear it works in appearance at least. But I think there are likely
areas beyond just the cloning of an item where issues would arise. Still, I
do think support is possible with some updates to the Table field in the
future, especially if it sounds like it works with the basics. But until
full support for it is there and confirmed, I'd probably avoid mixing
different types of repeating types if possible.
