### ISSUE TITLE
value="Label" syntax not working in ProcessPageEditLink

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1720]
### Short description of the issue

When I enter this in the "class" textarea:
```
uk-button="Button"
```

I get this after save:
```
uk-button-Button
```
I also tried different versions like `uk-button=Button` but none of them worked.

### Expected behavior

It should work like stated in the notes:

> To include labels, specify value=label to show “value (label)” for each selectable option. Or specify value="label" (label in quotes) to show just “label” (hiding the value) for each selectable option.

### Steps to reproduce the issue

1. Go to /processwire/module/edit?name=ProcessPageEditLink
2. Enter what I showed above

### Setup/Environment

* ProcessWire version: 2.0.214
* (Optional) PHP version: 8.1
* (Optional) MySQL version: MariaDB 10.6

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix for this
