### ISSUE TITLE
TypeError in inputfields.js

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1721]
### Short description of the issue

When editing a field in the PW admin the form isn't visible and there is a JS error in the browser console. Maybe related to the recent jQuery update?

![2023-04-17_132228](https://user-images.githubusercontent.com/1538852/232356724-b9d462d2-a573-447c-a7fe-7d94006869d5.png)

### Setup/Environment

* ProcessWire version: 3.0.215

**Comment by adrianbj** [comment]
Should be fixed by https://github.com/processwire/processwire/commit/3f2488de7d433d5df4f3047e1e38f09fa253d05f

**Comment by Toutouwai** [comment]
Thanks @adrianbj
