### ISSUE TITLE
ProcessPageEditLink no longer allows space-separated "rel" attributes

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1722]
### Short description of the issue

It's common to want to set multiple "rel" attributes on a link. For example, on external links often you want "nofollow noopener".

It used to be possible to have this configuration:

![2023-04-17_152630](https://user-images.githubusercontent.com/1538852/232370866-cd9a876e-b8a7-4352-88a0-6249908de1fd.png)

But since [this commit](https://github.com/processwire/processwire/commit/a29da160af6471f9bb240da072f486de5c3bd921) PW will not save space-separated values in the "Attribute options > rel" field.

This is a problem because:

 1\. It ought to be possible to specify multiple "rel" attributes for a link, particularly seeing as "noopener" is needed as a security measure.

 2\. If you save the ProcessPageEditLink module config that had a previously working configuration it's easy to overlook that the "nofollow noopener" option has been stripped out of the "Attribute options > rel" field but still persists in the "External link attributes > rel" field. This then causes a JS error when adding an external link in CKEditor that actually prevents the link from being inserted.

![2023-04-17_153404](https://user-images.githubusercontent.com/1538852/232371863-b27b0051-c24c-4ad6-9452-144c691dff80.png)

### Setup/Environment

* ProcessWire version: 3.0.215

**Comment by matjazpotocnik** [comment]
It looks like htmlClasses() sanitizer in the new set() method in the ProcessPageEditLink.module is problematic.

**Comment by ryancramerdesign** [comment]
@Toutouwai I was trying to duplicate this after fixing #1720 but wasn't able do, so am thinking the updates I made in that fix may have also fixed this issue as well. Can you confirm? Thanks.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, it's working now.

Something else I only just now discovered: if you have a target set for external links in the ProcessPageEditLink settings and you have HTML Purifier enabled for the CKEditor field (as it is by default) then HTML Purifier will automatically set "noreferrer noopener" on the link regardless of the ProcessPageEditLink rel settings for external links. Not a problem for me because I'm happy to have those attributes on the links.
