### ISSUE TITLE
Lister table not full width

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1726]
### Short description of the issue

The table of Lister results no longer spans the full width of the content area.

3.0.216
![2023-04-27_125311](https://user-images.githubusercontent.com/1538852/234732850-f78fbe27-e70e-4ec3-a789-d5d6617f80bf.png)

3.0.215
![2023-04-27_125458](https://user-images.githubusercontent.com/1538852/234732882-acc63530-49d6-4e88-b1dd-90cf9041af77.png)

### Setup/Environment

* ProcessWire version: 3.0.216

**Comment by matjazpotocnik** [comment]
The new version of jQueryTablesorter causes this. It adds width and min-width styles if parent element is set to overflow. Could you please edit /wire/modules/AdminTheme/AdminThemeUikit/AdminThemeUikit.module and remove uk-overflow-auto class in line 524? Perhaps there is better solution (other than "fixing" that in tablesorter)?

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I've pushed a fix for this based on @matjazpotocnik suggestion. We need the uk-overflow-auto for most tables in the admin to work properly at mobile sizes, but it appears the Lister table does not need that, as it works properly without it, so I have set it to exclude the uk-overflow-auto only for the Lister table.
