### ISSUE TITLE
New Updated jQuery not loading in admin in 3.0.216

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#1727]
### Short description of the issue

Latest jQuery not loading in admin when setting when setting `$config>debug = 'dev';`

### Expected behavior

Jquery loaded successfully.

### Actual behavior

Jquery loaded unsuccessfully with 404.

### Optional: Suggestion for a possible fix

Changing the file name `[jQueryCore.js](https://github.com/processwire/processwire/blob/dev/wire/modules/Jquery/JqueryCore/dev/jQueryCore.js)`
to JqueryCore.js.

### Steps to reproduce the issue

1. Upgrade the Processwire Core to 3.0.216
2. set `$config>debug = 'dev';`
3. At admin panel, JQuery fails to load

### Setup/Environment

* ProcessWire version: 3.0.216
* (Optional) PHP version: 8.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @karltdev I've pushed a fix for this
