### ISSUE TITLE
InputfieldPage - Label Field "Custom Format" options doesn't unhide the format entry form input

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1728]
### Short description of the issue

When configuring a Page Input field, selecting the "Custom Format (multiple fields) ..." option under Label Field has no effect. The form field used to define the Custom Format doesn't appear. The form flashes indicating a script has triggered.

In the source code the input has a data-show-if attribute that looks for a select value=. but the script doesn't trigger when the appropriate selection is made.

No console error is thrown but the input field remains hidden by the uk-hidden class.

Saving the field results in an error because the custom label format field is empty.

![image](https://user-images.githubusercontent.com/58667283/236511607-5c74a2a8-fff8-4d83-b20a-445d5aaebec9.png)

### Expected behavior

When the "Custom Format" selection is selected, the Inputfield_labelFieldFormat form input should dynamically appear.

### Setup/Environment

* ProcessWire version: 3.0.216
* (Optional) PHP version: 8.1

**Comment by solonmedia** [comment]
Does the . need to be escaped in the evaluation context? Autocomplete has nothing to do with this actually, so I will change the title.

**Comment by matjazpotocnik** [comment]
I can't replicate:

![1728](https://user-images.githubusercontent.com/7663992/236522124-ef91df5c-5958-4a03-bffc-5c2a87ad1ec0.gif)

**Comment by solonmedia** [comment]
This is using AdminThemeUIKit in Chrome on Windows 10.

The width of the Label Field form input is properly reduced to 50% but the uk-hidden class is not removed from the labelFieldFormat list element.

What browser are you using on mac?

**Comment by solonmedia** [comment]
I can confirm it works properly on the skyscraper demo but that's 3.0.101 so it doesn't help a ton here.

**Comment by Toutouwai** [comment]
@solonmedia, I raised a similar issue in the FormBuilder forum recently and Ryan replied to say that he fixed it in the core. So check that you have downloaded a fresh copy of 3.0.216 dev with the latest commits. Edit: or 3.0.217 now it is released.

**Comment by solonmedia** [comment]
Yes the new commit solved the issue after clearing all caches and recompiling.
