### ISSUE TITLE
"Repeater item labels" setting not working

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1729]
### Short description of the issue

Setting:

![2023-05-05_141659](https://user-images.githubusercontent.com/1538852/236365175-8650ff12-7de2-474e-ad11-549867910b84.png)

Working in 3.0.214

![2023-05-05_141647](https://user-images.githubusercontent.com/1538852/236365192-59844ab1-59d1-4046-982d-793420429333.png)

Not working in 3.0.216

![2023-05-05_141550](https://user-images.githubusercontent.com/1538852/236365201-fde73c9a-82ea-4227-a46c-ab0553c34090.png)

### Setup/Environment

* ProcessWire version: 3.0.216

**Comment by matjazpotocnik** [comment]
Hm, I can't replicate here, it shows label as expected.

**Comment by Toutouwai** [comment]
@matjazpotocnik, do you have the dev version with the latest commits? I think the [most recent commit](https://github.com/processwire/processwire/commit/f2a72ad8ea3fecaca2fd77c36df2fedc3501c17e) broke this.

**Comment by matjazpotocnik** [comment]
Yes, you're right, now I can replicate. It's line 158 `$repeaterTitle = preg_replace('/#([a-f\d]{3,})/i', "$colorPrefix$1", $out);`  Perhaps $out should be $repeaterTitle?

**Comment by ryancramerdesign** [comment]
@Toutouwai @matjazpotocnik Looks like you are right, that $out should be a $repeaterTitle, thanks :)
