### ISSUE TITLE
Repeater item labels not displayed for nested Repeaters

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#173]
### Short description of the issue

If a Repeater is nested inside another Repeater, any custom item label for the nested repeater isn't displayed: the name/title of the nested repeater field is displayed instead.

### Optional: Screenshots/Links that demonstrate the issue

![2017-01-27_144236](https://cloud.githubusercontent.com/assets/1538852/22357750/1eebfbb0-e49f-11e6-86ce-de3bfd7c9c7d.png)
![2017-01-27_144118](https://cloud.githubusercontent.com/assets/1538852/22357751/1ef2a488-e49f-11e6-8e1f-252bcc1bd466.png)

### Steps to reproduce the issue

1. Place a Repeater field inside another Repeater field.
2. Check nested Repeater label in Page Edit.

### Setup/Environment

* ProcessWire version: 3.0.50
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. My nested repeater has the proper label. However, I see in your screenshot that the nested repeater label is "Test nested repeater" and the title is "Green" – what's going on there? Does this repeater item just need to be saved?

**Comment by Toutouwai** [comment]
> However, I see in your screenshot that the nested repeater label is "Test nested repeater" and the title is "Green" – what's going on there? Does this repeater item just need to be saved?

This is the bug that I am describing here. The repeater item label should be "Green (Round)" but instead the repeater item label shows the label of the repeater field itself. The repeater item has been saved.

I can reproduce this issue on fresh PW 3.0.51 installation. I have a demo site online I can give you access to if that helps.

**Comment by ryancramerdesign** [comment]
Just tried again after changing my label format and field names to be the same as yours, but still can't duplicate it. What are your repeater settings for both repeaters for these? 

- Repeater item visibility in editor? 
- Repeater dynamic loading (AJAX) in editor 
- Remember which repeater items are open?
- Use accordion mode?

My settings are the defaults for all of these, which for the first 2 (radio buttons) means the first item is checked, and for the second two (checkboxes) means neither is checked.

**Comment by Toutouwai** [comment]
My two repeater fields have the default settings for everything apart from the "Repeater items labels" setting. In the simplified demo shown below, the setting for both repeaters is {title}. I will PM you via the forum with access details for this demo installation.

![2017-02-04_105744](https://cloud.githubusercontent.com/assets/1538852/22610146/e8ab785c-eac8-11e6-9abd-a27d3fc5dd8e.png)

**Comment by AndZyk** [comment]
I recently experienced this issue and avoided it by disabling "Repeater dynamic loading (AJAX) in editor" for the parent repeater field.

**Comment by ethanbeyer** [comment]
I recently bumped an installation from 3.0.42 to 3.0.62 and found this issue - and like @AndZyk, I was able to "fix" the issue by disabling "Repeater dynamic loading (AJAX) in editor" for the parent.

The console prints: `Empty string passed to getElementById().`

<img width="1202" alt="screen shot 2017-06-27 at 16 23 13" src="https://user-images.githubusercontent.com/6864684/27608311-01e82c64-5b55-11e7-99f1-72d71737f53a.png">

**Comment by Toutouwai** [comment]
I have tracked this problem back to [this commit](https://github.com/processwire/processwire/commit/cbdf8e9063b44cc0b0674e3e62f04ef843f52c11#diff-5b6467e10f38b4f029cceee7d95c4083).

The problematic part seems to be that $allowRender is declared with the "static" keyword. So when a nested repeater item label is rendered $allowRender can already be "false" from when a previous repeater item called the function. 

Not sure why the variable should be static - shouldn't it be evaluated to true or false freshly each time the renderRepeaterLabel() function is called?

Removing the static keyword seems to fix the issue.

**Comment by justb3a** [comment]
+1. Disabling *"Repeater dynamic loading (AJAX) in editor"* for the parent repeater field solved the issue as mentioned above.

<sub>ProcessWire 3.0.74</sub>

**Comment by ethanbeyer** [comment]
Is this commit in any of the dev builds?

**Comment by adrianbj** [comment]
> Is this commit in any of the dev builds?

There is the one Ryan just referenced above - is that what you are looking for?

**Comment by Toutouwai** [comment]
Thanks for the fix.

**Comment by ethanbeyer** [comment]
<img width="995" alt="screen shot 2018-02-07 at 15 41 48" src="https://user-images.githubusercontent.com/6864684/35940511-737c4a44-0c1d-11e8-8df7-5504e7bb6613.png">

@adrianbj sorry, I should've looked harder! I wasn't sure if it had been pulled into the dev branch with a new version number. I see that it's apart of 3.0.90! 

💃 

thanks, @ryancramerdesign!
