### ISSUE TITLE
Cloning images field does not clone custom fields

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1730]
### Short description of the issue

When an images field that uses custom fields is cloned...

![2023-05-08_105424](https://user-images.githubusercontent.com/1538852/236706645-238255ee-3889-4dd5-abd0-2efe7d3d82d8.png)

...the custom fields configuration is not copied to the new field.

![2023-05-08_105717](https://user-images.githubusercontent.com/1538852/236706646-8dbe2504-d600-47ce-97a2-0d8ee6213dce.png)

### Setup/Environment

* ProcessWire version: 3.0.216

**Comment by matjazpotocnik** [comment]
Custom fields toggle value is not saved to the database and thus not available in the field's getExportData() method. The toggle ON value is determined by the presence of the accompanying template field-yourimage which is not created (should it be?) during the image field clone operation.

@ryancramerdesign there is also this:

JQMIGRATE: jQuery.fn.select() event shorthand is deprecated in ProcessField.js line 93 (use trigger('select'))

**Comment by matjazpotocnik** [comment]
@Toutouwai @ryancramerdesign I used a hook to clone a template:

```php
$wire->addHookAfter('Fields::clone', function($event) {
  $clonedField = $event->return;
  if($clonedField === false) return false; //clone field failed
  
  $templates = $event->wire()->templates;
  $originalField = $event->arguments(0);
  
  $originalTemplatePrefix = 'field-';
  $originalTemplate = $templates->get($originalTemplatePrefix . $originalField->name);
  if(!$originalTemplate) {
    $originalTemplatePrefix = 'field-x-';
    $originalTemplate = $templates->get($originalTemplatePrefix . $originalField->name);
    if(!$originalTemplate) return; //there is no custom field-* template present
  }
  
  $clonedTemplate = $templates->clone($originalTemplate, $originalTemplatePrefix . $clonedField->name);
  if($clonedTemplate) {
    $this->message(sprintf($this->_('Cloned template %1$s => %2$s'), $originalTemplate->name, $clonedTemplate->name));
  } else {
    $this->error(sprintf($this->_('Error cloning template %1$s => %2$s'), $originalTemplate->name, $clonedTemplate->name));
  }
}
```

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik @Toutouwai I've pushed a fix for this based on Matjaz's code above.

**Comment by Toutouwai** [comment]
Thanks @matjazpotocnik and @ryancramerdesign
