### ISSUE TITLE
Page Reference (Label Custom Format) is not shown

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1731]
Under ProcessWire 3.0.216 and 3.0.217 DEV with activated Debug-Modue the input field for the option Page Reference -> Label field -> Custom format (multiple fields) is not shown. I think this is related to the current jQuery update, because the input field "Inputfield_labelFieldFormat" below it remains hidden via ".uk-hidden".

![screenshot-motorenring dermotor flipzoom dev-2023 05 10-15_41_27](https://github.com/processwire/processwire-issues/assets/708183/150c9085-cc40-4599-9a3d-51fb6062b508)

**Comment by matjazpotocnik** [comment]
Duplicate of https://github.com/processwire/processwire-issues/issues/1728 ? Maybe it's browser cache?

**Comment by flipzoom** [comment]
Ha, you're right. It was Cache. Sorry.
