### ISSUE TITLE
Refreshed page children list data not appearing when expanding/collapsing a page's children in page tree

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1733]
(just read my last comment; keeping here for historical purposes)

I'm using the latest ProcessWire dev version.

Assume you are viewing the admin page tree.  Expand a page that has children.  Edit one of the child pages in a new tab and change the title of that page and save.

Now go back to the tab with the admin page tree and collapse the children, then expand it again.  The title of the page that was just edited will remain the same rather than pulling the updated info.

On some of my sites, it gets the updated info, but on others it doesn't.  I don't know if you will be able to replicate this issue, but I recommend trying on a few different sites.

I tried a bunch of things that I thought might be related to this but I can't pinpoint it.  Toggling these settings (and logging out then back in after the change) didn't work:
- Session Handler Database
- $config->debug
- $config->useLazyLoading

**Comment by jlahijani** [comment]
Actually I figured this out.  It has to do with the limit of the ProcessPageList module.  Depending on the limit, it will either refresh entirely or pull from cookies.

**Comment by jlahijani** [comment]
Actually disregard my previous comment.  That had nothing to do with it.

I pinpointed the issue and how to replicate it.  Please view this short video with narration:
https://app.screencast.com/4TNtkAa6A8RpO?conversation=87layUMWiSxTlXbD0rVP1A

**Comment by matjazpotocnik** [comment]
I can confirm this. I narrowed it down to lines 597-602 in ProcessPageList.js - commenting them fix the issue, but then ayax call is triggered every time the page (parent) is expanded and thus preventing caching I think...

**Comment by ryancramerdesign** [comment]
@jlahijani @matjazpotocnik For performance reasons, PageList uses a browser memory cache so that it doesn't have to reload items for a particular page and pagination more than once per visit to the page list. Though it'll clear that cache for a branch if you modify it within the PageList (like moving a page). The cache is only present in JS memory, so it's gone as soon as you navigate elsewhere or reload the page.

**Comment by jlahijani** [comment]
@ryancramerdesign Would it be possible to make an option so it can be disabled?

**Comment by jlahijani** [comment]
@ryancramerdesign I figured this out with a little hack taking advantage of PageListForceReload:

```
// code to load in admin
$(document).ready(function(){
  if($('body').hasClass('ProcessPageList')) {
    $(document).ajaxComplete(function(event, xhr, settings) {
      $('#PageListContainer .PageListItem').addClass('PageListForceReload');
    });
  }
});
```
