### ISSUE TITLE
ProcessPageEditLink not applying "external" class

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1735]
### Short description of the issue

By default ProcessPageEditLink is supposed to add an "external" class and the "_blank" target attribute to links that are detected as external.

![2023-05-17_153428](https://github.com/processwire/processwire-issues/assets/1538852/98956b4c-c39a-4dcb-b96a-7acf9c5be878)

The "_blank" is added as expected but not the "external" class:

![2023-05-17_153647](https://github.com/processwire/processwire-issues/assets/1538852/6b39d212-77b4-4da3-8769-0bc80972b9a6)

Sidenote: I think there is a typo in the description text for the "External link attributes" fieldset - "attributed" should be "attributes".

### Setup/Environment

* ProcessWire version: 3.0.217

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this
