### ISSUE TITLE
`page-edit-images` permission issue on user template

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1737]
### Short description of the issue

I don't have the `page-edit-images` permission installed, but when certain users try to edit images on pages on a user template (only tested with alt template / parent), they can't edit images because `$this->wire()->user->hasPermission('page-edit-images', $page)` in InputfieldImage.module returns false.

### Expected behavior

They should be able to edit images

### Actual behavior

All editing buttons are missing

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks, I think I have tracked this down and have pushed a fix. Can you confirm?

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that seems to do the trick and now I can remove my hook for fixing it.

Just wondering while you have your mind wrapped about user editing permissions if you would mind taking a look at some of these: https://github.com/processwire/processwire-issues/issues?q=is%3Aopen+is%3Aissue+author%3Aadrianbj+user+label%3A%22type%3A+users%22

I guess the main one is: #1455
