### ISSUE TITLE
$pages->closest([...]) returns nullpage when using array syntax

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1738]
<img width="620" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/fefc5208-6778-4ae2-8ec1-fd16fa4aaf14">

Not sure if that is intended, but the docblock states it supports arrays:
<img width="502" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/4ffb8842-becc-4417-bf3b-4b942eb5495c">

If it's not a bug then I'd kindly ask if we could get support for array syntax here? :)

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix for this.
