### ISSUE TITLE
Repeater access problems for non-superusers

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#174]
### Short description of the issue

Non-superuser roles cannot upload images to an image field inside a Repeater (upload occurs but then thumbnail disappears and image is not retained on save). 

Also, non-superuser roles cannot open a nested Repeater item inside a Repeater (endless spinner), and cannot create a new nested Repeater item inside a Repeater (clicking "Add New" has no effect). 

If the Repeater system template is edited and the role is explicitly given access then the role may use the Repeater as expected. 

### Expected behavior

Image and Repeater fields inside a Repeater should be accessible to roles that have edit access to the page the Repeater is on.

### Steps to reproduce the issue

1. Create a non-superuser role "editor" and give it page-edit permission.
2. Edit the access tab for the "home" template and specify that edit access is not inherited by children (not sure if this is necessary but that is how my installation is configured).
3. Create an Image field and a Repeater field.
4. Create another Repeater field, and add the Image and Repeater fields from step 3 to it.
5. Create a template and add the Repeater field from step 4. Give the editor role edit access to this template.
6. Create a page that uses the template.
7. Log in as a user with the editor role and test.

Note that if the Repeater system template is edited and the editor role is explicitly given access then the role may use the Repeater as expected. However, once this has been done the access issue cannot be reproduced even after reverting to the "No" option for "Do you want to manage view and edit access for pages using this template?". It's as if changing these settings once is enough to trigger the expected role access that should happen in the first place.

### Setup/Environment

* ProcessWire version: 3.0.50
* (Optional) PHP version: 7

**Comment by Toutouwai** [comment]
The JS error that comes with the endless spinner:

```
Uncaught Error: Syntax error, unrecognized expression: {"error":false,"message":"The requested process does not exist"}
    at Function.nt.error (JqueryCore.js?v=1485015048:2)
    at ut (JqueryCore.js?v=1485015048:2)
    at vt (JqueryCore.js?v=1485015048:2)
    at vt (JqueryCore.js?v=1485015048:2)
    at Function.nt [as find] (JqueryCore.js?v=1485015048:2)
    at init.find (JqueryCore.js?v=1485015048:2)
    at init (JqueryCore.js?v=1485015048:2)
    at v (JqueryCore.js?v=1485015048:2)
    at Object.success (InputfieldRepeater.js?v=106-1485015048:229)
    at l (JqueryCore.js?v=1485015048:2)
```

**Comment by ryancramerdesign** [comment]
I also can't duplicate either of the issues mentioned here. Images upload just fine with my editor role (and appear normally after save), and no problem doing an "Add New" in a nested repeater. My PHP version is the same as yours, and PW version (3.0.52) close enough to the same, as there haven't been any recent Repeater or Access changes. Since I can't duplicate the label issue mentioned in your other issue report either, I guess we should take a closer look at what else is installed. What other modules are installed?

**Comment by Toutouwai** [comment]
Hi Ryan,

Sorry for the trouble - I have tracked this issue back to AdminOnSteroids. What was making that harder to detect was that the issue occurs even when the "Disable AdminOnSteroids" toggle is set to disable.

**Comment by adrianbj** [comment]
> What was making that harder to detect was that the issue occurs even when the "Disable AdminOnSteroids" toggle is set to disable.

@Toutouwai 
Have you tried the "Module Disabler" panel in Tracy? It is really helpful for things like this. It lets you disable all autoload modules with one click and automatically backs up the "modules" DB table so you can easily restore if disabling any of the modules breaks anything (which is a minor possibility).

**Comment by Toutouwai** [comment]
@adrianbj 
I haven't used that panel before. That's good advice, thanks.
