### ISSUE TITLE
Less autocomplete search suggestions after upgrade to 3.0.218 dev

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1740]
### Short description of the issue

After the upgrade from 3.0217 dev to **3.0.218 dev** there are no more autocomplete search suggestions for fields, templates or users in the backend.

### Expected behavior

Type a few letters in the search field of the backend and get autocomplete suggestions for fields, templates or users.

<img width="264" alt="Bildschirmfoto 2023-05-30 um 11 34 03" src="https://github.com/processwire/processwire-issues/assets/2794879/02257b25-e54e-4fe1-88f1-59de9c7ec2c8">

### Actual behavior

There are only autocomplete suggestions for pages and modules.

<img width="264" alt="Bildschirmfoto 2023-05-30 um 11 34 49" src="https://github.com/processwire/processwire-issues/assets/2794879/08848e47-6e54-4396-aec7-f4005db0fcff">

### Steps to reproduce the issue

1. Upgrade to 3.0.218 dev
2. Type a few letters in the search field
3. Wait for autocomplete search suggestions

**Comment by ryancramerdesign** [comment]
@designconcepts I think this is related to a different issue where some of the verbose module info was falling back to default values. I pushed some updates today that I think might fix that, though please let me know if you find the issue remains. You'll want to do a Modules > Refresh after grabbing the latest commits.

**Comment by designconcepts** [comment]
Thank you @ryancramerdesign. The updates fixed the issue. 😃
