### ISSUE TITLE
Issue in InputfieldSelect when using optgroup and numerical values starting from 0

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1742]
### Short description of the issue

This is a very tiny bug but if we use optgroup along with numerical values starting from 0, [`$lastOption`](https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/modules/Inputfield/InputfieldSelect.module#L225) is falsy and thus creates a new group:

```
Days
      0=Monday
      1=Tuesday
      2=Wednesday
      3=Thursday
      4=Friday
      5=Saturday
      6=Sunday
+7=day
8=weekday
9=weekend day
```

<img width="786" alt="Screenshot 2023-05-31 at 17 25 23" src="https://github.com/processwire/processwire-issues/assets/6616448/7b9afca6-94df-4102-b8c1-3a363480feae">

### Suggestion for a possible fix

Replace `!empty($lastOption)` by `$lastOption !== ''`, unless there was a reason for using `empty()` ?

<img width="786" alt="Screenshot 2023-05-31 at 17 25 11" src="https://github.com/processwire/processwire-issues/assets/6616448/01ad99a0-84d3-4d04-80ac-369a5e0da62a">

### Setup/Environment

* ProcessWire version: 3.0.217

**Comment by ryancramerdesign** [comment]
Thanks @romaincazier I've pushed your suggested fix for this. Usually when I use empty() it's because I want to match null, false, 0, '0', '', and !isset(). But as far as I can tell in this case, you are right and we just want to match a blank string.
