### ISSUE TITLE
WireCache::save - selectors not recognized in $expire argument

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#1744]
### Short description of the issue

WireCache::save in dev 3.0.218 doesn't recognize selectors. While the textual selector is passed on to $cacher->save(), WireCacheInterface implementations rely on selectors being passed in the data array.

### Example

Run this code as an example with WireCacheDatabase active:
```php
$cache->save('my-page-sel-1', 'my-value', 'parent=/home/');
```

This creates the following entry in the caches table:
```txt
# name, data, expires
'my-page-sel-1', 'my-value', '0000-00-00 00:00:00'
```

### Expected behavior

The selector should be passed along in the data array. The database record should look like this:

```txt
# name, data, expires
'my-page-sel-1', '{\"selector\":\"parent=\\/home\\/\",\"WireCache\":\"my-value\"}', '2010-01-02 02:02:02'
```

### Explanation

The issue stems from the fact that WireCache::expireNow is numeric zero. In the if/else sequence inside WireCache::getExpires, in the branch before the selector would would be recognized, PW checks if $expire contains one of the WireCache::expire* constants. Unfortunately, textual selectors like 'parent=/somepage/' evaluate to numeric '0' in the comparison, so this branch is accidentally entered.

This can be verified by running this code that tests the same condition as the if clause in question:
```php
if(in_array('parent=/home/', [WireCache::expireNever, WireCache::expireReserved, WireCache::expireSave, WireCache::expireNow])) {
    echo 'Oh No!' . PHP_EOL;
}
```

### Suggestion for a possible fix

The order of _if_ branches [for expire* constants](https://github.com/processwire/processwire/blob/02e3e0cd1b14ed958d0df969af4f1923719e5f18/wire/core/WireCache.php#L629) and [for selectors](https://github.com/processwire/processwire/blob/02e3e0cd1b14ed958d0df969af4f1923719e5f18/wire/core/WireCache.php#L633) should be swapped.

* ProcessWire version: 3.0.218 (dev)

**Comment by ryancramerdesign** [comment]
@BitPoet So far I can't seem to duplicate this. I tried this:
~~~~~
$cache->save('my-page-sel-1', 'my-value', 'parent=/home/');
~~~~~
And got this row in the database:
~~~~~
('my-page-sel-1', '{\"selector\":\"parent=\\/home\\/\",\"WireCache\":\"my-value\"}', '2010-01-02 02:02:02')
~~~~~
Could it just be a version difference? Maybe 3.0.218 had an issue that 3.0.219 doesn't? I don't know for sure, because I don't recall working with this particular issue. 

Also, I don't understand what this example is supposed to show (I added the 'NO MATCH' just so that it produces output): 
~~~~~
if(in_array('parent=/home/', [WireCache::expireNever, WireCache::expireReserved, WireCache::expireSave, WireCache::expireNow])) {
    echo 'Oh No!';
}  else {
    echo 'NO MATCH';
}
~~~~~
and of course got `NO MATCH`. Are you getting something different?

**Comment by BitPoet** [comment]
@ryancramerdesign Mea culpa. Somehow PHP 7 got activated, which matched strings to numeric zero in in_array in non-strict mode. That in_array behaved differently for you brought me onto the right track.

People please move on, there's nothing to see here.

**Comment by ryancramerdesign** [comment]
@BitPoet Technically we do still support PHP 7 (and PW still works even with PHP 5.4). So just wanted to double check that there isn't still something that needs to be fixed related to this?

**Comment by BitPoet** [comment]
@ryancramerdesign For PHP 7 compatibility, switching the two if branches (checking for selectors before checking for expire*) will be necessary (and sufficient). It wasn't an issue before since expireNow only entered the game with 3.0.218. I'll reopen this issue then.

**Comment by ryancramerdesign** [comment]
Thanks @BitPoet I've made that change you suggested. Though if you can, please double check that I did it correctly, just in case I misunderstood.

**Comment by BitPoet** [comment]
Yep, that's exactly what I meant. Thank you!

I encountered another small issue though that could quickly be fixed. Where WireCache::save [calls getExpires()](https://github.com/processwire/processwire/blob/6fe5c10dde668315b2860e859a1f4c5b37ecfe77/wire/core/WireCache.php#L514), it should pass a second argument ($verbose) of null. Otherwise it won't get back the necessary array when getExpires recognizes a selector.

```php
$expire = $this->getExpires($expire, null);
```

There's only [one other line](https://github.com/processwire/processwire/blob/6fe5c10dde668315b2860e859a1f4c5b37ecfe77/wire/core/WireCache.php#L618) where $verbose is checked against null. Judging from the comment there, the change shouldn't cause any side effects.

**Comment by ryancramerdesign** [comment]
@BitPoet Thanks, I just went to check that but null is the default value for the $verbose argument. Meaning, if no 2nd argument is specified to getExpires() then $verbose is automatically null. Or have I misunderstood?

**Comment by BitPoet** [comment]
@ryancramerdesign Sorry for taking up your time with that. After resetting everything here and running my tests with a fresh download, everything works.
