### ISSUE TITLE
SQL error HY093 from WireCacheDatabase

### ISSUE THREAD

**Issue by the-ge** [processwire/processwire-issues#1745]
### Short description of the issue

When told to do a `WireCacheDatabase::expireAll()` (by `ProcessCacheControl` in my case) it returns a SQL error due to mismatched PDO value binding. `WireCacheDatabase::deleteAll()` calls the same `WireCacheDatabase::_deleteAll()` method, so it probably does the same.

### Expected behavior

There should be no error.

### Actual behavior

```
WireCache: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
```

### Optional: Suggestion for a possible fix

In `WireCacheDatabase::_deleteAll()` the query calls for bound variables `:never` and `:reserved`, while the one actually bound is `:expires`. One fix could be replacing line 179

```		$sql = 'DELETE FROM caches WHERE ' . ($expireAll ? 'expires>:never' : 'expires!=:reserved');```

with

```		$sql = 'DELETE FROM caches WHERE ' . ($expireAll ? 'expires>:expires' : 'expires!=:expires');```

### Steps to reproduce the issue

1. Install [ProcessCacheControl](https://processwire.com/modules/process-cache-control/)
2. Go to admin > Setup > Cache Control
3. Press the `Clear All` button

### Setup/Environment

* ProcessWire version: 3.0.218 dev
* (Optional) PHP version: 8.2.2
* (Optional) MySQL version: MariaDB 10.6
* (Optional) [ProcessCacheControl](https://processwire.com/modules/process-cache-control/) 1.1.0

**Comment by ryancramerdesign** [comment]
Thanks @the-ge I've pushed a fix for this

**Comment by the-ge** [comment]
Thanks @ryancramerdesign
