### ISSUE TITLE
Single Image Field generates Pageimages Array within RepeaterMatrix Item

### ISSUE THREAD

**Issue by nurkka** [processwire/processwire-issues#1746]
### Short description of the issue
I am using an image field in conjunction with the RepeaterMatrix module, within several RepeaterMatrix items. The image field is defined as a single image field, and should ideally generate a Pageimage Object with the image properties or "null", if no image was given. But when used within the RepeaterMatrix item, it generates a Pageimages Object, which is unexpected as it is an array.

### Expected behavior
The image field should always return a Pageimage object or null, as it is defined in the image field settings, when used within a RepeaterMatrix item.

### Actual behavior
When the image field is used within a RepeaterMatrix item, it generates a Pageimages Object, which is an array.

### Steps to reproduce the issue
- Define an image field as a single image field ("Single-file when populated, null when empty (Pageimage)")
- Use this field within a RepeaterMatrix item.
- Observe that it generates a Pageimages Object.

### Setup/Environment
ProcessWire version: 3.0.210
RepeaterMatrix version: 0.0.9
PHP version: 8.1
Using Processwire with Languages Support (5 languages)

**Comment by ryancramerdesign** [comment]
@nurkka Just set it up (single image field in repeater matrix item) and I can't duplicate that here. A couple things to check:

The option for "Pageimage object or null" is a "formatted value" option. So if output formatting is OFF, or you retrieved the value with $page->getUnformatted('image'), the value is always a Pageimages object. 

Edit your Image field and click on the "overrides" tab to see if you have overridden the formatted value type somewhere, such as with your repeater matrix type.

**Comment by nurkka** [comment]
@ryancramerdesign Thanks for the hint regarding output formatting. I had already checked "overrides" before posting here, and there are none, but my issue definitely is related to output formatting. 

After adding the line `$page->of(true);` to every template before my `image_single` field is accessed, the field now always returns a Pageimage object. 

I can't seem to find the issue in my modules/fields/templates, but I obviously must have caused it myself somehow. I'll solve this in my templates with the said workaround, so I'll close the issue now.

**Comment by ryancramerdesign** [comment]
@nurkka That's strange that something is turning off output formatting. Rather than adding `$page->of(true)` to templates, I would see if you can track down the source of it. Check these files first (if you have them):

/site/init.php
/site/ready.php
/site/templates/_init.php

If not found, next would be to check any autoload modules in your admin > Modules > Site (/site/modules/*). If still not turning up, you can add a `$page->of(true);` to your /site/ready.php file to enable it for all templates, as that's what it's supposed to be in the first place.
