### ISSUE TITLE
Get warning in ProcessModule

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1747]
### Short description of the issue

Get warning in ProcessModule  .**../admin/module/edit?name=MyModule**

```
Warning: Array to string conversion in .../wire/core/Modules.php on line 1353
```

### Setup/Environment

* ProcessWire version: 3.0.219

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this

**Comment by kixe** [comment]
fixed
