### ISSUE TITLE
tfa_type selected value always 'None'

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1748]
When TFA is installed on 3.0.219 and `TOTP - Works with Authy, Google Authenticator, Microsoft Authenticator, or any TOTP app.` is selected and the user profile saved, it defaults back to 'None' e.g. the value isn't saved.

As this is a module reference field I assume this issue is related to refactoring of modules in .219.

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this

**Comment by chriswthomson** [comment]
Excellent thanks @ryancramerdesign, can confirm this has resolved it for me.
