### ISSUE TITLE
On state menu AdminThemeDefaultHelper

### ISSUE THREAD

**Issue by Da-Fecto** [processwire/processwire-issues#175]
### Short description of the issue

'On' state menu items not always set. When ProcessModules are in the root of the  #topnav the on state will not be replaced in the method  renderTopNavMarkCurrent because of a typo?

### Expected behavior

When the ProcessModule is active the active menu item has the class on.

### Actual behavior

The str_replace never takes place because renderTopNavItem() probably produces wrong output on line 346.

### Optional: Screenshots/Links that demonstrate the issue

--

### Optional: Suggestion for a possible fix

```
// 
class: AdminThemeDefaultHelpers.php
method: renderTopNavItem
// Change (line 346)
$out .= "<a class='page-id-$p-' href='$url'>$icon$title</a>";

// To 
$out .= "<a class='page-$p-' href='$url'>$icon$title</a>";
```

### Steps to reproduce the issue

```
// Comment out the block (line 418)

$cache = $this->wire('session')->getFor('AdminThemeDefault', 'topnav');
if($cache) {
	$this->renderTopNavMarkCurrent($cache);	
	return $cache;
}
```

**Comment by ryancramerdesign** [comment]
Thanks @Da-Fecto I've pushed a fix for this issue. In order to see it, you'll have to logout and login again (if you are already logged in when upgrading the /wire/ dir).
