### ISSUE TITLE
Error 'ProcessWire: ProcessPageEditCustom: Field 'some_field' is not applicable to this page'

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#1750]
Hi @ryancramerdesign 

I'm working on a custom process module for page editing that extends the ProcessPageEdit module and I'm facing an issue where I can't add nested repeater items. After clicking 'Add new' I'm getting such an error 
```
ProcessWire: ProcessPageEditCustom: Field 'some_field_repeater144134' is not applicable to this page
```
I dug into it and found that you already [have a fix for that](https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L173-L174) but it's commented out with @todo comment. 

Could you please uncomment this line so there is no need for me to search for a workaround?
Thanks, Eugene.

**Comment by ryancramerdesign** [comment]
@Lazerproof The line mentioned has more implications than I can test at the moment, but I have pushed an update that makes it support classes extending ProcessPageEdit. Do you find this fixes this issue?

**Comment by matjazpotocnik** [comment]
@Lazerproof can you verify Ryan's fix and close this issue?

**Comment by matjazpotocnik** [comment]
@Lazerproof Closing, reopen if needed.
