### ISSUE TITLE
Drop admin cache when something changes in admin js/css

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#1752]
### Short description of the issue

Admin caching is not get dropped when expected. Only manual cleaning in not so obvious way does the job. See https://github.com/processwire/processwire-issues/issues/1411#issuecomment-885462429 for an example.

### Expected behavior

Cache would get cleaned automatically when assets change.

* ProcessWire version: 3.0.220

**Comment by ryancramerdesign** [comment]
@ivangretsky ProcessWire already does what was linked in the example, so I'm not sure I understand. Can you describe more about which cache or file you are talking about and how to duplicate it?

**Comment by matjazpotocnik** [comment]
@ivangretsky could you please be more descriptive?

**Comment by matjazpotocnik** [comment]
@ivangretsky, Ryan added cache-busting to some of the js/css files and updated version numbers of admin themes in [this commit](https://github.com/processwire/processwire/commit/3b5e1adb7d8a3ebfb92b75eedff5efee9b69c3f6). While some other files also need cache-busting fixed, those will most likely be addressed on the go when assets are changed. I will close this issue, but please reopen it if I misunderstood you. Thanks.
