### ISSUE TITLE
ProcessModule information about the unininstall field is wrong

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1753]
After saving a module configuration by clicking the Submit button, ProcessModule issues the message "ProcessModule: Saved Module - Somemodule (uninstall)", even if no settings on the module config page are changed.
 
I fix that by replacing line 1799 in ProcessModule.module with:

`if($name === 'submit_save_module' || $name === 'uninstall') continue;`

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed your suggested fix for this.
