### ISSUE TITLE
Plural: zero is not plural

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1757]
In LanguageFunctions.php:
```
function _n($textSingular, $textPlural, $count, $textdomain = null) {
	return $count == 1 ? __($textSingular, $textdomain) : __($textPlural, $textdomain); 	
}
```
This function is considering zero as plural.

It should be:
```
function _n($textSingular, $textPlural, $count, $textdomain = null) {
	return $count <=1 ? __($textSingular, $textdomain) : __($textPlural, $textdomain); 	
}
```

**Comment by Toutouwai** [comment]
> This function is considering zero as plural.

That is the correct usage, in English at least. For example, you would say:

"There are 2 cars in the carpark."
"There is 1 car in the carpark."
"There are 0 cars in the carpark."

**Comment by szabeszg** [comment]
> "There are 0 cars in the carpark."

Also: "There are no cars in the carpark." So no wonder 0 requires plural in English. However, for example in Hungarian we use singular in such a case.

**Comment by hiboudev** [comment]
I didn't know that was language dependent, in french zero is not plural.
So that should be integrated in PW language management.

**Comment by ryancramerdesign** [comment]
@hiboudev I have added support for non-plural 0 quantities in translations from the `_n()` function. To use it, edit the language you want it for and add new file to translate: `wire/modules/LanguageSupport/LanguageTranslator.php`. At the top will be a  setting where you can choose whether the language should use plural or singular for 0 quantity.

**Comment by matjazpotocnik** [comment]
@hiboudev is it ok to close this issue?

**Comment by hiboudev** [comment]
Fix **NOT** working.

![image](https://github.com/processwire/processwire-issues/assets/15386877/7e8a2c8a-e135-4abb-a822-b4b1925acdfb)

```
echo($user->language->name); // default (french)
echo _n('test','tests',0); // tests
```

Tried with english language, not working either.

**Comment by ryancramerdesign** [comment]
@hiboudev It turns out it only works if you have provided translations for singular and plural. I have updated it so that it no longer requires translations and also works with whatever is provided in the _n() call.
