### ISSUE TITLE
DB Backups GUI unusable when dumps are not readable.

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1759]
### Short description of the issue

In my setup I have a db dump created by the root user of the webserver. When logging into the PW backend's db backups tool I get this:

<img width="854" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/6b55d025-3752-4365-858b-4ac6499a031d">

### Expected behavior

PW should show a warning but stay usable.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock The code in your screenshot seems to be from an older version? If I look in WireDatabaseBackup on the dev branch, it has an error check for that, and it also opens the file as "r" rather than "r+". Do you see any errors with the dev branch version of WireDatabaseBackup?

**Comment by BernhardBaumrock** [comment]
Sorry Ryan, you are right it's already fixed in the latest dev version :)
