### ISSUE TITLE
sessions table not cleaning up old sessions and growing huge over time

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1760]
### Short description of the issue

When using SessionHandlerDB on Ubuntu it is (or can be) the case that the "sessions" database table grows huge after time.

In my case it was a tiny site with a cronjob running every minute and that led to a 80MB database within a month! Now it's back at 2.7MB

It's been an issue for a very long time and it has been discussed in the forum: https://processwire.com/talk/topic/5796-session-handler-database-do-not-delete-old-sessions/

There the suggested solution is to add this to config.php:

```php
ini_set("session.gc_probability", 1);
ini_set("session.gc_divisor", 100);
```

This worked for me today (and in the past), but I think it's less than ideal to have to do this on every single install. I think this should be done automatically.

What I also found is that even without those settings when viewing the page `admin > access > session-db` then it also cleans up everything! So it should be possible to have something in place that works even without those ugly and tedious `ini_set` lines.

I could also add something to RockMigrations or RockShell but that would only be a solution for me and it really feels like this should be properly handles by the core :)

Thx in advance!

**Comment by ivangretsky** [comment]
I am [having this issue forever](https://processwire.com/talk/topic/5796-session-handler-database-do-not-delete-old-sessions/?do=findComment&comment=221656) and gave up on it. I am just cleaning the bd manually. Would be great if it could be fixed.

**Comment by ryancramerdesign** [comment]
@Bernhard The settings you've mentioned are the default values for PHP (gc_probability=1, gc_divisor=100). If they've been changed from the defaults in the php.ini then presumably there's a reason why, and I'm not sure ProcessWire should override them. Can you check what they've been overridden to in your installation? You can do this by looking at the output of `phpinfo();`. If they are set to 0 or something, then maybe that's a case where PW could override them.

**Comment by BernhardBaumrock** [comment]
Hey Ryan, yes, that's the problem: On Ubuntu/Debian 0 is the default:

<img width="799" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/5d971a7e-0573-485a-b219-4822cd952268">

https://www.howtoforge.com/php_session_data_is_not_deleted_when_using_custom_session_management_on_debian_and_ubuntu_solved

So if ProcessWire could overwrite that value I think the issue would be fixed for me (and many others).

Please note though that Ivan reported that this does not fix the problem for him. Maybe @ivangretsky you can provide more details?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock As I understand it, on Ubuntu/Debian it is 0 because the OS handles the garbage collection rather than PHP. But it sounds like it does so only if the session_handler is 'files'. I've pushed an update to populate the gc_probability and gc_divisor with the defaults in cases where either is 0 and the session_handler is not files. Do you find solves the issue?

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign thx for the quick fix!

I've updated to latest dev and removed my old config settings.

Is there any way I can check if it is working other than waiting for a month and check the size of the sessions table?

Memo: This is the current end of the sessions table, I'll check tomorrow to see if it get's cleaned up properly

<img width="1111" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/ca212ea8-0168-45f4-ad74-5cafb8f4bdb0">

**Comment by BernhardBaumrock** [comment]
Looks like it works, thx a lot! :)
