### ISSUE TITLE
module throws fatal error after recompiling

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1761]
The latest ProcessWire DEV 3.0.220 seams to break the **WireMailSmtp** module (namespace fatal error) **after a module recompiling**:

_Class "ProcessWire\WireMailSmtp" not found_

I cannot reach the settings any more and probably it does also not send out mails. 
It also crashes the admin "Modules" page after pressing the "refresh" button.

Without that recompiling the module. does not throw errors.
The problem appears to be new. Recompiling worked before. But I remember there was work on PW Modules code lately.

It is already mentioned in the forum, so I am not the only one with the issue:
https://processwire.com/talk/topic/5704-wiremailsmtp/page/17/#comment-233775

**Comment by ryancramerdesign** [comment]
Thanks @tbba I've pushed a fix for this issue

**Comment by tbba** [comment]
fixed on 2 tested instances!
still a problem on 1 instance, even after uninstall+new install + compile new:

Class "ProcessWire\WireMailSmtp" not found : 
.../FileCompiler/site/modules/WireMailSmtp/WireMailSmtpConfig.php:151

Not sure this is still the bug or some cache issue. I experiment a little.

**Comment by tbba** [comment]
Works! Thank you!

**Comment by matjazpotocnik** [comment]
@tbba closing this issue based on your response.
