### ISSUE TITLE
FieldtypePage: wrong parsing of selector value starting with "page."

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1762]
### Short description of the issue

When using a page reference field with InputfieldPageAutocomplete, that is targeting pages containing another page reference field using a complex selector string (game.gameId=page.game.gameId), parsing of the autocompletion query is wrong and triggers an error in ProcessPageSearch.

### Expected behavior

Getting completion for the searched pages.

### Actual behavior

No completion at all.

### Optional: Suggestion for a possible fix

In FieldtypePage->getMatchQueryCustom(), line 1171, the regex is removing "page.game" and keeping ".gameId", resulting in an error thrown by ProcessPageSearch.

Replace this regex:
`/[a-zA-Z0-9_.]+\s*[=!]+\s*page\.[a-zA-Z0-9_]+\s*,?/`
by this one:
`/[a-zA-Z0-9_.]+\s*[=!]+\s*page(\.[a-zA-Z0-9_]+)+\s*,?/`

### Steps to reproduce the issue

I'm using a page reference field with InputfieldPageAutocomplete.
Template targeted by this field has also a page reference field with a selector string : "game.gameId=page.game.gameId".

When I edit a page using the first field, the InputfieldPageAutocomplete builds a broken search query and ProcessPageSearch throws:
`ProcessPageSearch: Unknown Selector operator: '[empty]' -- was your selector value properly escaped? field='.gameId', value='', selector: 'include=all, .gameId, sort=title, templates_id=113, title~|*=aaaaa'`

If I use a simpler selector value it works:
page.gameId => OK
page.game.gameId => Not ok

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.2

**Comment by ryancramerdesign** [comment]
@hiboudev Since ProcessPageSearch operates from user input (GET requests) it is a web service that does not provide access to the entire API, just stuff that's commonly used and safe/secure for admin search needs. It also doesn't support features specific to one Fieldtype module or another. In cases where you need to do something beyond what it supports, consider changing to the "Text Tags" input field type, and using the "Custom PHP code" option—that'll give you access to the full API for autocomplete needs.

**Comment by hiboudev** [comment]
Will Text tags allow to select multiple pages like a page reference field? I can't find this field in admin, it's installed but not listed in "types" when creating new field.

Actually there's an inconsistency in Page Reference, a selector working with ASM Select is not working with autocompletion module, that's why I edited this regEx.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, does the proposed fix make ProcessPageSearch less safe/secure?

**Comment by ryancramerdesign** [comment]
@hiboudev 

> Will Text tags allow to select multiple pages like a page reference field? 

Yes. 

>  I can't find this field in admin, it's installed but not listed in "types" when creating new field.

Technically it's just a Page field, but you select TextTags as the input type. So when creating a new field, create a Page field. 

> Actually there's an inconsistency in Page Reference, a selector working with ASM Select is not working with autocompletion module, that's why I edited this regEx.

Autocomplete is limited by what can safely be passed through in a query string, and what is supported by the ProcessPageSearch module. If the full selector API was opened up to it, it would be a security hole. The benefit of using the custom PHP hook option is that the selector does not pass through input, just the search text. So it gives you more options. The vast majority of use cases are just fine with autocomplete/ProcessPageSearch, but for your case it sounds like you need something more complex so the custom option is ideal for that.

**Comment by hiboudev** [comment]
@ryancramerdesign 

There's something I don't understand, or you don't understand. ;)

My fix just suggests to remove the whole "page.foo.bar" selector from query, I'm not adding anything, just removing, **because your regex is removing only half of the page selector**. Instead of removing "page.game.gameId", you remove "page.game" and let a lone ".gameId" in the query, that triggers an exception in ProcessPageSearch.

The whole code is:
`$selector = preg_replace('/[a-zA-Z0-9_.]+\s*[=!]+\s*page(\.[a-zA-Z0-9_]+)+\s*,?/', '', $selector);`

I don't really understand the whole process, but it happens that removing the whole page selector makes my page selector to work... :D

**Comment by ryancramerdesign** [comment]
@hiboudev Thanks, I understand now -- I've pushed a fix for this issue so that it should now properly remove the whole thing rather than leaving the ".gameId"

**Comment by hiboudev** [comment]
@ryancramerdesign 
Looks like it's working, but behavior is not exactly the same between components "Select" and "Page Auto Complete".

"Select" is not listing current page, when "Page Auto Complete" does.

I'm talking about a page reference field with a selector targeting multiple pages including the current one.
I don't need it but I suppose this behavior should be consistent between these components.

**Comment by ryancramerdesign** [comment]
@hiboudev ProcessWire won't let you select the current page in the editor in order to prevent a circular reference. When using PageAutocomplete, the pages are found in a separate http ajax request (where the current page is not the page being edited), so this behavior is expected.
