### ISSUE TITLE
PageFrontEdit javascript errors

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1763]
Ryan, in [this commit](https://github.com/processwire/processwire/commit/1d7f029fa5e4db5dc35996e86538544892aaf5b5#diff-8365aff85a51f8e06aa48bcc3ba86fafabc74fc5ec556d09d16fce7c8b76b30f) you changed 

`target.load(viewURL + ' #' + targetID, {}, function() {`

with 

`target.on('load', viewURL + ' #' + targetID, {}, function() {`

in PageFrontEdit.js and that produces the error:

![image](https://github.com/processwire/processwire-issues/assets/7663992/9869df41-3e94-43d7-b3d3-e0d1302024a6)

The intention was to use the jQuery load() method to replace edited content on the page and not to establish an onload event handler. The fix is simple: revert the change.

And please consider adding support for loading the dev version of jQuery and jQuery UI based on `$config->debug = 'dev'` (lines 801 and 815 in Page FrontEdit.module).

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed your suggested fix for this and updated it to recognize config.debug==dev
