### ISSUE TITLE
Page Reference AsmSelect: Combining template selection with selector string is CPU intensive

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1764]
### Short description of the issue

When a page reference field with AsmSelect uses a selector string, and the target template is set with the form (not setting the template in selector string but in the Template select form in field Input tab), and that we have thousands of pages found by this field, there is a high CPU overload that disappears if we set the template in selector string.

### Expected behavior

Normal performances.
When setting a template in the select form, it should add to selector string "template=xxx" and so behavior should be the same.

### Actual behavior

Page needs 5 seconds to load (CPU 5900X), Apache is running high on CPU.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://github.com/processwire/processwire-issues/assets/15386877/9cdce902-cd78-4454-a532-2a881c7c6fe1)

### Steps to reproduce the issue

- In admin, on the settings page of a page reference field using AsmSelect, on the input tab > Selectable pages : select a template from the select form AND a selector string like "id>1".
- You must have thousands of pages targeted by this field.
- Still in admin, go on a page using this field, you should see that page loading is highly CPU intensive.
- Go back to field settings, remove the template from the select form, and add it in selector string.
- There's no more CPU usage issue.

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.2

**Comment by ryancramerdesign** [comment]
@hiboudev Thanks, I have pushed an attempted fix for this issue. Do you find that it resolves the issue?

**Comment by matjazpotocnik** [comment]
@hiboudev can you verify and close this issue if fix is working for you?

**Comment by hiboudev** [comment]
I have 2 issues to confirm, I'll try to do it before end of week.

**Comment by hiboudev** [comment]
Fix working.
