### ISSUE TITLE
Modules::getModuleInfoVerbose() not working in PW 2.0.2020

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1765]
### Short description of the issue

A user in the forums reported that after installing ProcessDatabaseBackups in PW 2.0.2020 no corresponding page is created in the Setup menu: https://processwire.com/talk/topic/28651-processdatabasebackups-and-pw-dev-30220/

When I dump the result of `Modules::getModuleInfoVerbose()` within `Process::___install()` after [this line](https://github.com/processwire/processwire/blob/f1c20282f62f47b66bf24786f80e141e60f16ff4/wire/core/Process.php#L279) these are the results...

PW 2.0.220

![2023-06-22_101112](https://github.com/processwire/processwire-issues/assets/1538852/ac1a89a7-56b9-4172-8ec1-58fec056a542)

It was working in PW 2.0.218

![2023-06-22_101213](https://github.com/processwire/processwire-issues/assets/1538852/9fee171a-72fa-43db-8b12-91949a862e88)

### Setup/Environment

* ProcessWire version: 3.0.220

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.
