### ISSUE TITLE
Imposible to set $expire argument in $cache->save() method to WireCache::expireNow

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#1766]
Hi @ryancramerdesign 

`
$cache->save($cacheName , $output, WireCache::expireNow);
`
The expire argument will always fallback to WireCache::expireDaily if you pass WireCache::expireNow, the reason for that behavior is [here ](https://github.com/processwire/processwire/blob/3fa65dfc83eed248bdb1fa31d06c1f14e65a2af2/wire/core/WireCache.php#L492)

**Comment by ryancramerdesign** [comment]
Thanks @Lazerproof I've pushed a fix.
