### ISSUE TITLE
ProcessPageList: jQuery error unsupported pseudo :hover

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1767]
### Short description of the issue

ProcessPageList.js contains 3 occurrences of the pseudo-class ":hover" in a jQuery selector. 

https://github.com/processwire/processwire/blob/3fa65dfc83eed248bdb1fa31d06c1f14e65a2af2/wire/modules/Process/ProcessPageList/ProcessPageList.js#L254
https://github.com/processwire/processwire/blob/3fa65dfc83eed248bdb1fa31d06c1f14e65a2af2/wire/modules/Process/ProcessPageList/ProcessPageList.js#L271
https://github.com/processwire/processwire/blob/3fa65dfc83eed248bdb1fa31d06c1f14e65a2af2/wire/modules/Process/ProcessPageList/ProcessPageList.js#L285

I'm not sure when jQuery dropped support for this but in the version used in PW 2.0.221 it throws this error:

> Syntax error, unrecognized expression: unsupported pseudo: hover

Another occurrence is here: https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/templates-admin/scripts/main.js#L167

### Setup/Environment

* ProcessWire version: 3.0.221

**Comment by ryancramerdesign** [comment]
@Toutouwai I can't see to duplicate it here whether using `$config->debug=false; $config->debug=true;` or `$config->debug = 'dev';` (to target different jQuery versions). As I understand, `:hover` is a CSS pseudo rather than a jQuery one, so I'm wondering if it might be browser related. I'm testing in the latest Chrome here. Which browser are you using?

**Comment by Toutouwai** [comment]
@ryancramerdesign, I tested some more and it seems jQuery will throw the "unsupported pseudo: hover" whenever it is used in a selector on a jQuery object containing anything other than exactly one element. So I think this makes it a bit fragile.

I tested by editing `wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js` and adding lines at the bottom within `$(document).ready()`

```js
// No error: object contains exactly one element (assuming there is an <a> tag in the page)
var working = $('a').first().is(':hover');
```

```js
// Error 1: object contains more than one element
var error1 = $('a').filter(':hover');
```

```js
// Error 2: object contains zero elements
var error2 = $('a.no-element-with-this-class').first().is(':hover');
```

So the [usage](https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/templates-admin/scripts/main.js#L167) in `/wire/templates-admin/scripts/main.js` is going to cause an error like Error 1, as `filter()` wouldn't be used in cases where it's certain the object contains exactly one element.

I saw the errors in ProcessPageList when I was testing a module that modifies the page list, so it might be that I was injecting markup that ProcessPageList.js isn't expecting. But to add robustness and avoid the potential of errors like Error 2 maybe there should be a `length` check before contructions like `.first().is(':hover')`, e.g.

```js
if($('a.something').length && $('a.something').first().is(':hover')) {
   // ...
}
```

**Comment by matjazpotocnik** [comment]
Robin, I'm on phone and on a vacation with limited internet, but could we use jQuery match() ? I guess it won't help, just an idea.

**Comment by Toutouwai** [comment]
@matjazpotocnik, is match() a jQuery method? I can't find it in the docs: https://api.jquery.com/?s=match

**Comment by matjazpotocnik** [comment]
oh, yes, I didn't check, sorry. How about the native function matches? I found this article: https://stackoverflow.com/questions/14795099/pure-javascript-to-check-if-something-has-hover-without-setting-on-mouseover-ou

**Comment by ryancramerdesign** [comment]
@Toutouwai @matjazpotocnik Thanks, that's good debugging. I guess it makes sense that :matches only works on length=1 jQuery objects since the Javascript matches() is for single elements, and jQuery probably delegates the is() selector through to that matches() method when just one item, like it does with some other things. I have updated ProcessPageList.js to verify that there is exactly one item before attempting to use the :hover selector, and I've updated the main.js to use matches(':hover') instead.  Do you find that it fixes the issue there?

**Comment by Toutouwai** [comment]
Looks good, although not sure I understand the mixture of jQuery and native JS in the different fixes. I think `$a[0].matches(':hover'))` is effectively the same thing as `$('a').first().is(':hover')`.

Is the `wire/templates-admin/scripts/main.js` code supposed to handle cases where `$ul` contains multiple elements? Only wondering because the previous use of `.filter()` makes me think that might be the case. If `$ul` and `$a` only expects a single element then either of the code examples above would work, but if it needs to handle multiple elements then I think it will need to loop over and check each individual element for :hover regardless of whether a jQuery or native JS approach is taken.

**Comment by ryancramerdesign** [comment]
@Toutouwai It is just for one $ul at a time, and it doesn't need to handle more than that. The $ul[0] is used just because it is shorthand to convert the jQuery object to a Javascript node, and not about getting a particular index as there will only be index 0 here.
