### ISSUE TITLE
Trailing Slashes (slashUrls) redirect not implemented for 2nd/3rd etc level child pages

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1768]
### Short description of the issue

When a sub page e.g. /page/child is viewed the slashUrls setting isn't respected - it does not redirect to the chosen setting.

### Expected behavior

slashUrls = 0, /page/child/ would redirect to /page/child
slashUrls = 1. /page/child would redirect to /page/child/

It does work for /page/ and /page.

### Actual behavior

Redirect does not happen.

### Steps to reproduce the issue

1. Install blank install (master or dev)
2. Add a basic-page, then add a child page
3. View the child page without the slash
4. Change the template setting to remove trailing slashes
5. View the child page with a slash

### Setup/Environment
* ProcessWire version: 3.0.210+
* PHP version: 8.1

I thought this was maybe related to our server setup, perhaps htaccess, but I'm seeing it across multiple servers. Where I am not seeing it is on a couple of externally hosted sites (IIS) using 3.0.62 and 3.0.123 respectively. I'm not sure however whether this server environment may be making the difference and not the PW version.

Our setup is always to have the trailing slashes removed. As far as I can tell, the trailing slash in a request is being removed by applyPagesRow() in PagesPathFinder. The `$parts` passed don't include the trailing slash so I think whatever evaluation this is doing should be retaining it? Or perhaps applyResultTemplate should be doing something like:

```php
if($fail || $_path !== $path || rtrim($path) . '/' === $result['request']) {
...
}
```

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks, I've pushed a fix for this issue.

**Comment by chriswthomson** [comment]
Thanks, it has fixed it for me
