### ISSUE TITLE
labelFieldFormat - issues with PageArray values

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1770]
When using a PageArray value in labelFieldFormat for a field, a leading space is added.

Example:

<img width="1293" alt="Screenshot 2023-06-29 at 10 03 23" src="https://github.com/processwire/processwire-issues/assets/7858587/c9b30d8c-bf0c-45a1-adf5-4904b32f4aa6">

type_area is a Page field, multiple values. This is how this displays:

<img width="1293" alt="Screenshot 2023-06-29 at 10 03 48" src="https://github.com/processwire/processwire-issues/assets/7858587/54e75eb3-e7e0-47be-9e5d-8905e5a7dddd">

When I switch type_area to single (Page), it displays (correctly) like this:

<img width="1293" alt="Screenshot 2023-06-29 at 10 04 02" src="https://github.com/processwire/processwire-issues/assets/7858587/a00ab952-c5ba-4df3-9e3c-9f5fad2c4dab">

Working on 3.0.221.

**Comment by chriswthomson** [comment]
I've discovered a further issue with PageArray values in labelFieldFormat.

When the label referred to in this issue appears in PageLister, it does so like this:

<img width="1293" alt="Screenshot 2023-06-29 at 10 15 04" src="https://github.com/processwire/processwire-issues/assets/7858587/12c45bec-0302-4f4e-8db6-a5a7847db191">
 
Interestingly the leading space doesn't appear to be there.

I tried switching the type_area field to single Page and this removed the markup.

**Comment by adrianbj** [comment]
Thanks @chriswthomson - this has bugged me for years :)

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks I've pushed a fix for this.

**Comment by chriswthomson** [comment]
Thanks @ryancramerdesign, this has fixed it for me.
