### ISSUE TITLE
adjustName options when saving pages doesn't work

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#1771]
### Short description of the issue

`adjustName` option on `$pages->save()` doesn't do what it's documented to do

### Expected behavior

Pages are not saved when their name is not unique across siblings.

### Actual behavior

Page is created with appended `-{n}` on name.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

The code doesn't actually seem to check for made adjustments. It only checks if the name was autogenerated, which is only a subset of adjusted names.

https://github.com/processwire/processwire/blob/6ff498f503db118d5b6c190b35bd937b38b80a77/wire/core/PagesEditor.php#L642

### Steps to reproduce the issue

1. 
```
$u = new User();
$u->of(false);
$u->name = "abc"
$users->save($u);
```
3. Run again
4. See two users in the system

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.2.3
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix for this. I've updated the default value of adjustName=true to maintain the same behavior as before the fix, unless you specifically don't want it, in which case set it to false. With an exception: the default for adjustName on users/roles/permissions is false.

**Comment by matjazpotocnik** [comment]
@LostKobrakai does Ryan's fix work for you? If it does, could you close this issue?

**Comment by LostKobrakai** [comment]
I haven't been able to test it yet, but it should.
