### ISSUE TITLE
WireHttp::setTimeout() doesn't apply float values correctly

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1773]
### Short description of the issue

`WireHttp::setTimeout()` accepts a float value which suggests that values like 0.5 or 2.5 would be effective.

But when WireHttp uses cURL (which is the first tried option by default now) it sets the timeout using `CURLOPT_TIMEOUT` which seems to have the following behaviour when supplied with a float value:
- values less than 1 are ignored
- floating point values more than 1 are converted to an integer value

I think `CURLOPT_TIMEOUT_MS` needs to be used instead when the timeout value is not an integer.

Maybe `WireHttp::sendCURL()` could be updated to something like this:
```php
if($timeout == (int) $timeout) {
    curl_setopt($curl, CURLOPT_TIMEOUT, $timeout);
} else {
    curl_setopt($curl, CURLOPT_TIMEOUT_MS, $timeout * 1000);
}
```
Or just use CURLOPT_TIMEOUT_MS for all cases (this option has been available in cURL since 2007)

### Setup/Environment

* ProcessWire version: 3.0.221

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this. I think it makes sense just to have it use CURLOPT_TIMEOUT_MS and CURLOPT_CONNECTTIMEOUT_MS all the time, per your suggestion.

**Comment by Toutouwai** [comment]
Thanks for the speedy fix!
