### ISSUE TITLE
WireDateTime, date localization: days and months names are not localized

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1774]
### Short description of the issue

In a date field, I set the format to display a month name, but it is always displayed in english by Processwire, even when PHP does the translation correctly (meaning my setup is good).

### Expected behavior

With a date format set to 'F', and the french language selected (locale is 'fr_FR') I expect the month to be displayed in french,  'juin' and not 'june'.

### Actual behavior

Actually days and months names are always displayed in english.

### Optional: Suggestion for a possible fix

It's necessary to use IntlDateFormatter in class WireDateTime.

1. Enable extension intl in php.ini (on Debian also install package php-intl).
2. This code shows the localized month name, using the current locale:
```
<?php namespace ProcessWire;
use IntlDateFormatter;

$format = IntlDateFormatter::create(null, pattern: 'MMMM');
echo $format->format(new \DateTime());
?>
```

### Steps to reproduce the issue

1. Create a date field with format 'j F Y H:i'.
2. Set up multi-language configuration in PW.
4. Select another language than english.
5. Display the current date: month name is not localized.

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version:  8.1

**Comment by ryancramerdesign** [comment]
@hiboudev Unfortunately we lost that ability when PHP killed off the strftime() function in PHP 8.1. (Prior to PHP 8.1 it did work). As far as I understand it, the IntlDateFormatter is not something that's universally available in PHP the way that strftime was (unless something has changed?), so not something we can depend on, as enabling PHP extensions is not something all PW users can do. I was however considering just making the month/day/meridiems and abbreviations as translatable text, as it amounts to just 40 words. But for now if you  need the ability and you have the IntlDateFormatter extension installed, that's a fine way to go.

**Comment by hiboudev** [comment]
@ryancramerdesign Yes I understood it was broken since PHP 8.1. And yes IntlDateFormatter requires to enable/install extension.

Your idea of making days/months names translatable looks fine.

Maybe another way would be to make date formatting hookable. I see I could hook InputfieldDateTime->__renderValue().
But maybe it would be better to add a hookable method in WireDateTime, only to replace the usage of php date() function?

**Comment by ryancramerdesign** [comment]
@hiboudev I've pushed an update that makes the day and month names and abbreviations translatable in /wire/core/WireDateTime.php

**Comment by hiboudev** [comment]
Thanks @ryancramerdesign.  I'll have a look at all your fixes in some days.

**Comment by matjazpotocnik** [comment]
@hiboudev, did you try Ryan's fix? Does it work for you?

**Comment by hiboudev** [comment]
Yes it works.
