### ISSUE TITLE
ProFields Table: page referenced in Table is not listed by $page->references('include=all')

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1775]
### Short description of the issue

In a ProFields Table I have a page reference field for template user.
I added a general hook to make impossible to delete a page that is referenced by another, but this hook is not working with ProFields Table:
```
$checkPageIsDeletable = function (HookEvent $event) {
    /* @var Page $page */
    $page = $event->arguments(0);

    // Don't delete pages referenced by another.
    if ($page->references('include=all')->count()) {
        $message = "La page $page->name est référencée par d'autres pages, supprimez les références pour pouvoir la supprimer.";

        if (wire()->page->process == "ProcessPageEdit") {
            $this->session->error($message);
            $event->replace = true;
        } else {
            throw new WireException($message);
        }
    }
};
$this->addHookBefore('Pages::trash, Pages::delete', $checkPageIsDeletable);
```

### Expected behavior

Pages referenced in a ProFields Table should be detectable, like any other page in PW.

`$page->references('include=all')->count()` should return 1.

### Actual behavior

`$page->references('include=all')->count()` returns 0.

### Steps to reproduce the issue

1. Create a table including a page reference field.
2. Create a template and page and add a reference in the table.
3. Add a hook before Pages::trash or, Pages::delete, in this hook display the value of $page->references('include=all')->count().
4. Try to delete the page referenced by Table, and see that PW says this page is not referenced by another page.

### Setup/Environment
* ProcessWire version: 3.0.210
* (Optional) PHP version:  8.1

**Comment by ryancramerdesign** [comment]
@hiboudev The Page::references() method just covers page references known by the core. It does not know of pages linked  by modules outside of the core, such as those by Table. Such an ability would need to be provided by the 3rd party module.

**Comment by hiboudev** [comment]
That would be fine to implement it in ProFields Table, I feel bad with this PW features that stop working with ProFields.

Actually my workaround is to execute this function in a Pages::trash + Pages::delete before-hook (hotlapLeaderboard is the table):
```
$checkPageIsReferencedInTable = function (HookEvent $event): void {
    /* @var Page $page */
    $page = $event->arguments(0);

    // TODO il faudra chercher dans davantage que les hotlaps.
    $templates = implode('|', ['hotlap']);

    $referencingPages = match ($page->template->name) {
        'user' => wire()->pages->find("template=$templates, hotlapLeaderboard.user=$page"),
        'car' => wire()->pages->find("template=$templates, hotlapLeaderboard.car=$page"),
        default => new PageArray()
    };

    if ($referencingPages->count()) {
        $message = "La page $page->name est référencée par d'autres pages, supprimez les références pour pouvoir la supprimer.";
        wire()->error($message);
        throw new WireException($message);
    }
};
```
