### ISSUE TITLE
ProcessSessionDB (SessionHandlerDB) loses ability to sort table after ajax reload

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1776]
### Short description of the issue

When ProcessSessionDB first loads, the table of sessions is sortable by clicking any of the column headers. 

But as soon as the first automatic ajax reload occurs the table is no longer sortable. Also, if the user has clicked one of the column headers to change the sorting from the default then this sort is lost when the ajax reload occurs.

It would be great if the table can remain sortable and retain the user's sorting through the ajax reload, but if this is going to be too much work then the `MarkupAdminDataTable` should have `sortable` set to `false` before the initial rendering.

### Setup/Environment

* ProcessWire version: 3.0.221

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I have pushed a fix. I hadn't planned on this table being sortable and looks like it was just because it inherited the default setting and I neglected to disable it.
