### ISSUE TITLE
AdminThemeFramework.php getAddNewActions()

### ISSUE THREAD

**Issue by BrendonKoz** [processwire/processwire-issues#1777]
### Short description of the issue

Upon immediately signing into the admin backend (chosen theme: AdminThemeUikit) I was going to quickly add a new page from the add-page shortcut menu of the theme's content header. I noticed it was missing. The path after signing in was `/processwire/page/list/?login=1`. Clicking in the nav for "Pages", which essentially renders the same view, changes the path to `/processwire/page/`. The $page->name value is "list" for the former, and "page" for the latter.

### Expected behavior

I'd expect to see the add-page shortcut for both of these views since they render the same output.

### Actual behavior

The add-page shortcut is not rendered when the $page->name value is set to 'list'.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://github.com/processwire/processwire-issues/assets/194731/4eb8bf61-abde-46dd-b9e4-8bdc65f3d312)

![image](https://github.com/processwire/processwire-issues/assets/194731/474d98ca-2a3f-4926-b7bb-409c74eaa302)

### Optional: Suggestion for a possible fix

Modifying `wire/core/AdminThemeFramework.php` line 265 from:
```php
if($page->name != 'page' || $input->urlSegment1 || $input->get('modal')) return array();
```
...to...
```php
if(!($page->name == 'page' || $page->name == 'list') || $input->urlSegment1 || $input->get('modal')) return array();
```
...allows the page list to display the add-page shortcut.

### Steps to reproduce the issue

1. Sign in to the PW backend with appropriate rights.
2. Notice the page-add shortcut does not appear.
3. Click "Pages" in the navigation (or PW logo) to navigate to a different view file of the same view.
4. Notice the page-add shortcut appears.

### Setup/Environment

**Server Details**

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.214|
|PHP|8.0.18|
|Webserver|Apache/2.4.53 (Unix) OpenSSL/1.1.1n|
|MySQL Server|8.0.28|
|MySQL Client|mysqlnd 8.0.18|

**Comment by ryancramerdesign** [comment]
Thanks @BrendonKoz I've pushed your suggested fix for this.
