### ISSUE TITLE
Can't hook Users::save

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1778]
### Short description of the issue

[Documentation gives example](https://processwire.com/api/ref/users/save/) to hook Users::save, but it's not working

### Expected behavior

Hook should be executed.

### Actual behavior

Hook is not executed.

### Optional: Suggestion for a possible fix

Hook on Pages::save(template=user).

### Steps to reproduce the issue

1. Add a hook with the example given in documentation:
$this->addHookBefore('Users::save', function(HookEvent $event) {
  exit('hook executed');
});
2. Save a user and see that the hook is not executed.

### Setup/Environment

* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
@hiboudev That Users::save hook will only save pages that are saved through the $users API var. Unfortunately it won't work if users are saved through $pages->save() instead, which is often the case. So in retrospect Users::save probably shouldn't be hookable at all, as it's not going to catch all instances. I'd recommend hooking Users::saveReady or Users::saved instead, as those should catch all instances. Or use one of the $pages hooks instead while checking `$page instanceof User`.  I'll add a hook note to the Users::save methods (and any others that'll have the same issue) suggesting what they should hook instead.

**Comment by hiboudev** [comment]
@ryancramerdesign Yes, editing/removing documentation is enough.
I don't use `saved` or `saveReady ` cause I want to block the save on some conditions.

**Comment by matjazpotocnik** [comment]
@hiboudev, Ryan added hook documentation https://github.com/processwire/processwire/commit/b656b254e85d02a83ec5f1bc73f81a96c28df949. Is it ok to close this issue?
