### ISSUE TITLE
"sort=path" doesn't work in $pages->find()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1782]
### Short description of the issue

I expected to be able to sort by path when the PagePaths module is installed. But it doesn't seem to work.

See for example the circled item which is not in the correct place if sorting by path:

![2023-07-08_190233](https://github.com/processwire/processwire-issues/assets/1538852/d8b7fd4e-53f2-4ddd-b4ab-00b6ae62528f)

### Setup/Environment

* ProcessWire version: 3.0.221

**Comment by ryancramerdesign** [comment]
@Toutouwai It doesn't look like we had support for sorting by path. I have just added it in this commit: https://github.com/processwire/processwire/commit/a53e809fc40908293eee4947191f1a30940b081d

**Comment by Toutouwai** [comment]
Working great, thanks @ryancramerdesign!
