### ISSUE TITLE
Integer field, $pages->find: Empty value is not considered different from a filled value

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1784]
It's me again.

### Short description of the issue

A page has an Integer field that is empty.
I search pages where this field is different from "2023".
I don't find pages with empty field.

```
$myUser = $users->get(5866);
var_dump($myUser->membershipYear); // Empty Integer field
var_dump($users->count("membershipYear!=2023")); // Zero result, empty value is not different from 2023?
```

### Expected behavior

Empty value is different from 2023, so I should find the page.

### Actual behavior

Page not found.

### Steps to reproduce the issue

1. Create an Integer field
2. Add it to user template
3. (Saving the user changes nothing)
4. Search users where this field value is different from 2023
`$users->count("membershipYear!=2023");`
5. See that you didn't find the page.

### Workaround

- Workaround only in code:

`var_dump($users->count("(membershipYear!=2023), (membershipYear='')")); // Workaround`

- Or workaround only in PW:
--  Integer field: Select "empty and zero are different"
-- Integer field: Set a default value to zero,
-- Save all pages using this field.

**EDIT** : the PW workaround works only if you first set on the field "empty and zero are different". Then you save users. And then you may set that "empty and zero are not different" and it still work for existing users **but it won't work for new users**...

### Setup/Environment
* ProcessWire version: 3.0.210
* (Optional) PHP version: 8.1
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @hiboudev I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
@hiboudev, could you check this and close the issue if done?
