### ISSUE TITLE
Long checkbox labels cause overflow and horizontal scrollbar

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1788]
### Short description of the issue

<img src=https://i.imgur.com/ovozLfM.png>

### Optional: Suggestion for a possible fix

I added `white-space: break-spaces;` and that fixed it for me

### Setup/Environment

ProcessWire: 3.0.222
PHP: 8.1.16

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I can't seem to duplicate it here. Is this a regular checkbox field, or a checkbox within some other fieldtype?

<img width="578" alt="Screen Shot 2023-07-25 at 8 59 10 AM" src="https://github.com/processwire/processwire-issues/assets/328272/3a264d5b-ff6c-4009-8016-338ba1ed7f04">

**Comment by BernhardBaumrock** [comment]
Sorry for being unclear @ryancramerdesign 

Steps to reproduce:

- Install RockMigrations
- Go to RockMigrations settings
- See field overflow on checkboxes field

<img width="539" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/cfe147f1-a2c8-49da-aa39-f024059dda8e">

I used `InputfieldCheckboxes` to add them:

```php
    $f = $this->wire->modules->get('InputfieldCheckboxes');
    $f->name = 'enabledTweaks';
    $f->label = "ProcessWire Tweaks";
    $f->entityEncodeText = false;
    foreach ($this->tweaks as $tweak) {
      $f->addOption($tweak->name, implode(' - ', array_filter([$tweak->name, $tweak->description])));
    }
    $f->value = (array)$this->enabledTweaks;
    $inputfields->add($f);
```

Same behaviour both with AdminThemeUikit and AdminStyleRock

Does that help? :)

**Comment by matjazpotocnik** [comment]
@BernhardBaumrock you test this on a phone or at screen size below 600px width? Maybe just removing white-space from .InputfieldCheckboxes ul li label would be enough?

**Comment by BernhardBaumrock** [comment]
Yeah it's in InputfieldCheckboxes.css on line 16

<img width="765" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/5a4dd4bf-a93f-4074-bbd3-32e0c2555ea6">

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I was able to duplicate it once I changed from InputfieldCheckbox to InputfieldCheckboxes. I have pushed your suggested fix.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign
