### ISSUE TITLE
Presistent Errors in Modules Screen related to TinyMCE

### ISSUE THREAD

**Issue by outflux3** [processwire/processwire-issues#1789]
### Short description of the issue

ProcessModule: Invalid module name: “.Modules.info” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “Modulesinfo”
ProcessModule: Invalid module name: “.Modules.site/modules/” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “Modulessitemodules”
ProcessModule: Invalid module name: “.Modules.wire/modules/” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “Moduleswiremodules”
ProcessModule: Invalid module name: “.ModulesUninstalled.info” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “ModulesUninstalledinfo”
ProcessModule: Invalid module name: “.ModulesVerbose.info” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “ModulesVerboseinfo”
ProcessModule: Invalid module name: “.ModulesVersions.info” Please use uppercase [A-Z] for first character, lowercase [a-z] for 2nd character, and [a-z A-Z 0-9] for the rest. For example: “ModulesVersionsinfo”

### Expected behavior

No Errors

### Actual behavior

Errors

### Optional: Screenshots/Links that demonstrate the issue

<img width="1525" alt="Screen Shot 2023-07-22 at 10 19 38 AM" src="https://github.com/processwire/processwire-issues/assets/1743040/6614e7a6-e5a5-4ec4-a2bd-9b14d81f86f1">

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Upgrade to latest dev version
2. Install TinyMCE
3. Downgrade to latest stable version; try to uninstall TinyMCE

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.223|
|PHP|8.1.21|
|Webserver|Apache|
|MySQL Server|8.0.34|
|MySQL Client|mysqlnd 8.1.21|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|2M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite||
|mod_security||
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminCustomFiles|0.9.62|
|AdminOnSteroids|2.0.21|
|AdminPageFieldEditLinks|3.1.4|
|AdminTemplateColumns|1.0.1|
|AutoSmush|1.1.6|
|BatchChildEditor|1.8.25|
|ConnectPageFields|0.3.4|
|ContextHelpLister|1.0.0|
|Duplicator|1.4.29|
|FieldDescriptionsExtended|1.1.1|
|FieldtypeAdminComments|1.0.7|
|FieldtypeColor|1.1.8|
|FieldtypeConfigForm|1.0.0|
|FieldtypeFontIcon|0.0.1|
|FieldtypeFontIconPicker|2.0.2|
|FieldtypeForms|1.0.0|
|FieldtypeMultiplier|0.1.4|
|FieldtypeRuntimeMarkup|0.0.6|
|FieldtypeTable|0.2.4|
|FileValidatorSvgSanitizer|0.0.5|
|FontAwesomePro|1.0.4|
|FormBuilder|0.5.3|
|HannaCodeDialog|0.4.4|
|ImportExternalImages|2.0.15|
|InputfieldAceExtended|1.1.3|
|InputfieldAdminComments|1.0.7|
|InputfieldColor|1.1.6|
|InputfieldConfigForm|1.0.0|
|InputfieldFontIcon|0.0.1|
|InputfieldFontIconPicker|2.0.2|
|InputfieldFormBuilderFile|0.0.3|
|InputfieldIcon|0.0.2|
|InputfieldMultiplier|0.1.4|
|InputfieldRuntimeMarkup|0.0.6|
|InputfieldSelectize|1.2.0|
|InputfieldSelectizeMultiple|1.2.0|
|InputfieldSimpleMDE|1.0.8|
|InputfieldTable|0.2.4|
|JqueryIonRangeSlider|0.0.4|
|LimitPageTable|0.1.10|
|MarkupFontIconPicker|2.0.2|
|MarkupSiteMetaAdvanced|1.6.0|
|MarkupSocialShareButtons|1.0.5|
|MarkupThemeEngine|1.6.2|
|PageActionExportCSV|0.0.6|
|PageActionSetField|0.0.1|
|PageFieldContexts|0.0.1|
|PageFieldInfo|0.1.2|
|PageImageManipulator02|0.2.9|
|PageRenameOptions|2.0.1|
|PageTableExtraActions|0.1.1|
|Pages2Pdf|1.1.7|
|PrevNextTabs|0.1.6|
|ProCache|4.0.1|
|ProcessAdminComments|1.0.7|
|ProcessCKInlineComplete|0.1.8|
|ProcessChildrenCsvExport|1.8.24|
|ProcessDashboards|1.0.0|
|ProcessDatabaseBackups|0.0.6|
|ProcessDocumentation|1.0.5|
|ProcessDuplicator|1.4.29|
|ProcessFormBuilder|0.5.3|
|ProcessGetVideoThumbs|1.1.7|
|ProcessHannaCode|0.3.2|
|ProcessMenuLink|0.0.1|
|ProcessPageListerPro|1.1.5|
|ProcessProCache|4.0.1|
|ProcessSettingsFactory|1.0.7|
|ProcessTracyAdminer|1.1.3|
|ProcessWireUpgrade|0.1.1|
|ProcessWireUpgradeCheck|0.0.9|
|SelectizeImageTags|0.1.0|
|SelectizeTemplateFieldTags|0.1.2|
|SettingsFactory|1.0.7|
|SimpleBlogEngine|1.9.0|
|SiteUtilities|0.0.1|
|TemplatesChildPages|0.1.8|
|TextInputAwesomplete|0.0.7|
|TextformatterHannaCode|0.3.2|
|TextformatterJqueryUITabs|0.0.1|
|TextformatterMarkupCSS|0.0.1|
|TextformatterSoundmanager|1.1.6|
|TextformatterUtilities|1.0.0|
|TracyDebugger|4.25.3|
|WirePDF|1.0.4|
|WireSitemapXML|0.0.3|
</details>

* ProcessWire version:
* (Optional) PHP version:  8.1.21
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by outflux3** [comment]
This might be related to Tracy Debugger; i found these entries in the database,

<img width="1245" alt="Screen Shot 2023-07-22 at 10 49 07 AM" src="https://github.com/processwire/processwire-issues/assets/1743040/8b12057b-3cfc-4def-8a42-cf178ea7ebf0">

...and deleting them has solved the issue. Not sure what caused this (maybe the upgrade/downgrade), possibly good to keep an eye on it in case someone else runs into it; But in any case, removal of those rows in the modules table has stopped the errors from appearing, so technically this issue report is resolved.

**Comment by ryancramerdesign** [comment]
@outflux3 Newer dev branch versions moved the modules info storage into the module table with those `.Modules.*` rows. Those rows aren't recognized by earlier versions of PW, so if you downgrade, you'd have to remove those rows manually. Not ideal I know, but I can't send myself into the past to modify older version of PW to ignore those rows. :)

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Dumb question: if earlier versions of PW don't know anything about those `.Modules.*` rows, why would removing them help? Maybe some guidance (just a statment or two) about those rows would be benefitial - what are they, is there any harm if they are deleted (obviously not), etc.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik 

>  if earlier versions of PW don't know anything about those .Modules.* rows, why would removing them help?

The newer version knows that any module names beginning with a period "." are not actual module names and instead are for internal or cache use. Previous versions don't know that. Removing those rows would make the error disappear because the error message is basically stating that it doesn't recognize those rows, as they don't map to module names. 

> Maybe some guidance (just a statment or two) about those rows would be benefitial - what are they, is there any harm if they are deleted (obviously not), etc.

They are cached values previously stored in the $cache API var. And actually, they still are stored in $cache also, but now only as a backup (like if you downgrade). By storing them in the modules table, they get bundled into the modules table load which was already occurring, so piggybacking on that reduced overall boot time. 

I wouldn't delete these rows unless you downgrade to a version that doesn't recognize them (and is showing that error message).

**Comment by ryancramerdesign** [comment]
Btw, the error is unrelated to TinyMCE. Just downgrading from dev branch to master branch would show this error, at least once the modules are refreshed. That's likely why it was observed when uninstalling TinyMCE.

**Comment by matjazpotocnik** [comment]
Ryan, thank you for the explanation.

@outflux3, Marc, I'm closing this issue, you can reopen it if needed.
