### ISSUE TITLE
WireCache: get() $expire selector not saved in database record when using $func

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1790]
```php
$cache->get('test', 'template=post', function() use ($pages) {
    return $pages->find('template=post,limit=5');
});

```

### Expected behavior

```json
{"selector":"template=post","WireCache":{"PageArray":[4516,4518,4546,4568,4583],"template":55}}
```

### Actual behavior

```json
{"WireCache":{"PageArray":[4516,4518,4546,4568,4583],"template":55}}
```

I'm getting this on the latest dev branch. I expect this bug has been around since the refactor of WireCache: I'm using cache selectors quite heavily on a project at the moment and all the database records appear to be missing the selector, so it has been around for a little bit.

The bug exists for any $data value I pass it. If I set the value via `$cache->save()`, it works fine.

**Comment by ryancramerdesign** [comment]
@chriswthomson As far as I know, the `$cache->get()` method does not support a selector, or at least hasn't been documented to. That's a feature of the `$cache->save() `method. But sounds like you are saying it used to support a selector?

**Comment by adrianbj** [comment]
@ryancramerdesign - I have always relied on selectors in `$cache->get` which I learned about in this post: https://processwire.com/blog/posts/processwire-2.6-rc1-2.5.29-and-more/

**Comment by chriswthomson** [comment]
Hi @ryancramerdesign,

I think so - not really paid that much attention to it before but I'm pretty sure I used this successfully in the past.

Just checked on a 3.0.210 site and it works as I expected:

```json
{"selector":"template=post","WireCache":{"PageArray":[1057,1065,1067,1069,1071],"template":49}}
```

**Comment by ryancramerdesign** [comment]
@chriswthomson I've pushed an update so that it will support that. Do you find it fixes the issue there? There may be some factor or issue I'm forgetting as to why it wasn't mentioned in the method phpdoc before, so I'll continue to leave it undocumented for now.

**Comment by chriswthomson** [comment]
Thanks @ryancramerdesign, yes that's fixed it.
