### ISSUE TITLE
Export and import of repeater field can cause the wrong parent page to be used for repeater items

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1792]
### Short description of the issue

When a repeater field is exported, one of the values is "parent_id". In the example below the parent_id is 1127.

![2023-07-27_151144](https://github.com/processwire/processwire-issues/assets/1538852/904a2948-d505-41cf-a587-bd9fed36925f)

If the exported data is used to import the repeater field into a different site where a page with that ID already exists this page is wrongly taken over as the parent page for repeater items.

In the site I imported into, page 1127 is among a set of country pages - it is the page for Latvia. As shown in the screenshot below this page has had its title changed and is now wrongly used to hold repeater items for the "simple_repeater" field.

![2023-07-27_151523](https://github.com/processwire/processwire-issues/assets/1538852/6b032b73-91d4-4cfb-9ce6-cd75b50bc647)

Related forum topic: https://processwire.com/talk/topic/28845-repeaters-odd-behaviour/

### Setup/Environment

* ProcessWire version: 3.0.222

**Comment by netcarver** [comment]
I am seeing this on a 3.0.204.dev install where I imported a repeater.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this. @netcarver it looks like the fix for an issue #1638 you opened is what broke this, so I'm wondering if this fix might break what was fixed in #1638 ?  I put in an alternative that I'm hoping might solve it but I'm not sure.

**Comment by Toutouwai** [comment]
Thanks, it's working.
