### ISSUE TITLE
Not equals in find selector broken since 3.0.222 or 3.0.223

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1793]
### Short description of the issue

```
foreach($pages->find("template=user, lat!=, lng!=") as $u) {
    if($u->lat == '') d($u->lat);
}
```
has started returning results whereas previously it would correctly have no output.

### Expected behavior

No results dumped.

### Actual behavior

<img width="611" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/df1cef83-0980-40d3-a10f-b380dca60533">

### Setup/Environment

* ProcessWire version: 3.0.223
* (Optional) PHP version: 8.2

**Comment by cb2004** [comment]
I believe I had a similar problem, I was doing something like:

`$pages->find("image!=");`

But after an upgrade to the latest ProcessWire I had to use:

`$pages->find("image.count>0");`

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj @cb2004 I've pushed a fix for this, can you confirm it also fixes it there?

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks good here.

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - this isn't properly fixed.

Now with page fields I am getting some concerning results.

With the `user_type` page field this is what I am getting.

This is what is expected:
<img width="912" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/8765b7b2-9162-464f-ba42-a9e489a7cf3f">

but this is what I get with the most recent dev version:
<img width="911" alt="image" src="https://github.com/processwire/processwire-issues/assets/871211/43930d14-bf4e-4dfa-a8ea-4869830eb19d">

The inclusion of the `id` is just to force it to limit it to a person that should be excluded by the `user_type!=1147`.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed another update for that, does it also fix there? please let me know if you spot any more.

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - unfortunately it doesn't help. It never gets to the point of calling `whereEmptyValuePossible()` because the `if($useEmpty` check on this line: https://github.com/processwire/processwire/blob/df081407120a1646ebfa6a62e717452af724b26e/wire/core/PageFinder.php#L1833 returns `false`

**Comment by ryancramerdesign** [comment]
@adrianbj I'm not sure I understand,  as I'm using the same selector as you, just a different Page field. The last part of the selector matches and sends it into whereEmptyValuePossible:
~~~~~
$useEmpty = $isEmptyValue || $operator[0] === '<' || ((int) $value < 0 && $operator[0] === '>') 
  || ($operator === '!=' && $isEmptyValue === false);	
~~~~~
this part:
~~~~~
|| ($operator === '!=' && $isEmptyValue === false);	
~~~~~

**Comment by adrianbj** [comment]
Sorry @ryancramerdesign - my bad - I had tweaked my test selector yesterday while trying to debug for you and didn't return it to the correct one. This morning's fix does seem to be working as expected now, although I must admit I am pretty nervous about using all these changes in production - just worried there might be other breakages still.
