### ISSUE TITLE
ProcessWire 3.0.222: severe performance degradation after commit 67b6f5

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#1794]
### Short description of the issue
Starting with commit [67b6f5](https://github.com/processwire/processwire/commit/67b6f5817bfee1bef7dcf45534e6e29605a9ece7), ProcessWire began to exhibit significant performance issues, particularly when editing pages in the backend. The load time for the page editor has increased, taking upwards of 25 seconds to fully load. Notably, no error messages are being generated during this process.

The issue was not present in the preceding commit, [fa5fae](https://github.com/processwire/processwire/commit/fa5fae9c583700d1b2ecf05d7a521b05a68d5105). Everything functioned as expected without any noticeable delays or performance issues.

Since the "faulty" commit introduces some changes related to database code, I guess there are some MySQL bottlenecks now which stress the database. I checked the MySQL load on the server and can see that the MySQL process uses all CPU resources during the problematic time frame when the page editor is loading.

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: PHP 8.2.8
* (Optional) MySQL version: MariaDB 10.5.19

**Comment by adrianbj** [comment]
@processwired  - has today's update to PageFinder fixed the issue for you?

**Comment by processwired** [comment]
Thanks @adrianbj! The issue appears to have been resolved - everything is fast again. Awesome! I think that this is the quickest fixed issue I have ever reported... ;)

(I had used the most recent commit available this morning. However, it did not include the latest commit from 5 hours ago. Thanks to everyone involved in the speedy solution!)
