### ISSUE TITLE
FieldtypePage - Autocomplete with multiple templates selected returns 0 results

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1796]
### Short description of the issue

When using only the template and additional template settings for an Inputfield Page set to use single page autocomplete, no results are returned. However switching to select, asmselect, etc. yields a dropdown with the expected pages available to select.

### Expected behavior

The autocomplete should return a found page matching the selector text and any of the selected templates configured in the field setup.

### Actual behavior

Zero results are returned, and if the AJAX /processwire/search/for call is processed manually, it looks like an extra encoding step is being taken in the template_ids selector:

ProcessPageSearch: Found 0 pages using selector: templates_id=85%7C130%7C166,status<2048,title|name|headline%=general,limit=50

### Optional: Screenshots/Links that demonstrate the issue

![Screenshot 2023-08-02 125926](https://github.com/processwire/processwire-issues/assets/58667283/30101a9e-56d1-45e7-b88b-e2596cd711cd)

This includes the AJAX call in the URL box and PWs response.

As mentioned above, changing the page selection mode to select or asmselect or other prepopulated dropdowns show pages from the correct templates without any other field configuration changes.

### Steps to reproduce the issue

1. Create 2-3 pages with different templates.
2. Create an InputfieldPage using Autocomplete
3. Select 1 template in the selector asm select box and two additional templates in the additional templates selector asm select
4. Add the InputfieldPage field and try to enter title text using the %= selector operator.
5. Grab the AJAX call URI from Tracy and try manually accessing it.

### Setup/Environment

* ProcessWire version: 3.0.223
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
@solonmedia I can't seem to duplicate it here. It worked when I did it, and I got this in the message notification after copying/pasting the ajax URL into the browser: 

> Found 267 pages using selector: templates_id=48|51|29|43,status<2048,title|name|headline%=process,limit=50

What seems different in your screenshot is the encoding of the templates_id part of the selector. I'm wondering where that came from, or if there might be a cache issue here.

**Comment by solonmedia** [comment]
Hmmmm cache. Yes let me try clearing that up.

**Comment by solonmedia** [comment]
I refreshed the wire folder with a fresh dev download and the autocomplete is delivering proper results now.

**Comment by ryancramerdesign** [comment]
@solonmedia Great! Thanks for checking it, glad it's working now.
