### ISSUE TITLE
Remove "like TinyMCE" from core modules descriptions

### ISSUE THREAD

**Issue by isellsoap** [processwire/processwire-issues#18]
Repost of https://github.com/ryancramerdesign/ProcessWire/issues/958.

Descriptions of core modules shouldn’t mention specific WYSIWYG editors (if it isn’t necessary). One core module states "like TinyMCE" in its description in a fresh 3.0.35 installation. The description should be more generic.

**Comment by ryancramerdesign** [comment]
I found one reference in the TextformatterEntities module description and this has been removed.

**Comment by adrianbj** [comment]
@ryancramerdesign - on the topic of tinymce appearing in other places.

Should it be installed with the classic site profile: 
https://github.com/processwire/processwire/blob/ee89ddcea54f9a697c828b2892e9c9dc68ff13c6/site-classic/install/install.sql#L350

The module (now a site module) is not included with the profile, so this would be a superfluous entry in the modules database - no?

Also referenced here which I think is no longer appropriate:
https://github.com/processwire/processwire/blob/bac5b0de5d95b5a10c09f48ba5e63b419ee68799/wire/modules/Process/ProcessPageEditLink/ProcessPageEditLink.module#L6-L7

Are these types of changes you'd now like to see as a PR - just wondering if that would save you time, or just complicate your workflow?

**Comment by ryancramerdesign** [comment]
Thanks I missed that one in the comment, I'll adjust that in the next
commit. For the ones in SQL it doesn't matter because InputfieldTinyMCE
(when not installed) is considered an alias for InputfieldCKEditor by the
modules loader. No need for a PR for this kind of stuff – PRs take lots
more typing and double checking things, etc.
