### ISSUE TITLE
PHP 8.1 deprecated warning for ParsedownExtra.php in core

### ISSUE THREAD

**Issue by jjozsi** [processwire/processwire-issues#1801]
The Parsedown Extra library causes a PHP deprecated error in PHP 8.1 or later:

`Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /wire/modules/Textformatter/TextformatterMarkdownExtra/parsedown-extra/ParsedownExtra.php`

The 2.0 branch of the library seem to have fixed this: https://github.com/erusev/parsedown-extra/issues/173 but I wouldn't know how to integrate the 2.0.x versions (Parsedown and Parsedown Extra) into the module.

Temporary fix:
Replacing line #628 with the following makes the warning go away:
`$elementMarkup = htmlspecialchars_decode(iconv('UTF-8', 'ISO-8859-1', htmlentities($elementMarkup, ENT_COMPAT, 'UTF-8')), ENT_QUOTES);`
The above solution was found in the following Drupal thread: https://www.drupal.org/project/smart_trim/issues/3342481

**Comment by ryancramerdesign** [comment]
Thanks @jjozsi I've pushed a fix for this. I omitted the iconv() part because we're not working with ISO-8859-1, but also that call gave me an error.

**Comment by jjozsi** [comment]
Thanks Ryan, I tested it and I have no warning.
