### ISSUE TITLE
Error with $page->url() when getting current URL segments

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1804]
### Short description of the issue

When viewing a page at a URL that includes one or more URL segments, if you do...

```php
$url = $page->url(['urlSegments' => true]);
```

...or...

```php
$url = $page->url(['urlSegmentsStr' => true]);
```

...you get "Error: Undefined offset: 0 on line: 655 in \wire\core\PageTraversal.php"

![2023-08-30_202007](https://github.com/processwire/processwire-issues/assets/1538852/039e9be5-7a2a-41c5-b317-13662a8ca109)

### Setup/Environment

* ProcessWire version: 3.0.226

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I pushed a fix for this
