### ISSUE TITLE
Selector issue - role name no longer used?

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1805]
When investigating an error in an existing site that had been recently updated to 3.0.226 I discovered that the issue was being cause by a selector not behaving properly.

```
// This
$users->find('roles!=admin-c, listings_c.count>0');
// Was returning the same as this
$users->find('listings_c.count>0');
```

After some investigation (and finding it working in Lister) I discovered that the role name was not working. Replacing it with the ID did:

```
$users->find('roles!=1118, listings_c.count>0');
```

Is this intentional or something that requires a fix?

**Comment by adrianbj** [comment]
It seems like it's only an issue with the negative check `roles!=admin-c` because `roles=admin-c` still seems to work as expected. This is the third new `!=` selector bug in this version, so it's not limited to roles.

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this. When you don't specify a subfield on a field having subfields, you leave it up to that field to decide what subfield it will match (or not match). For example, a page field (like roles) without a subfield is assumed to refer to an ID. But if you specify a non-digit ID then it can look it up and attempt to match it to a page name as a convenience. That conversion is unique to the FieldtypePage module, and it wasn't working for this particular case. It's possible to avoid the issue by specifying subfields when you want to match subfields. For instance, `roles.name!=admin-c` when want to match/not-match a role name. Though `roles!=admin-c` should also work now too.

**Comment by matjazpotocnik** [comment]
@chriswthomson, can you please check Ryan's fix and close this issue?
