### ISSUE TITLE
Template files in default site-blank profile need comments that explain the Markup Regions feature

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1806]
### Short description of the issue

The two frontend template files included in the default site-blank profile ([home.php](https://github.com/processwire/processwire/blob/fdb5a1994167a29ced4b4fe6e7fcb3b4b9ae9a42/site-blank/templates/home.php), [basic-page.php](https://github.com/processwire/processwire/blob/fdb5a1994167a29ced4b4fe6e7fcb3b4b9ae9a42/site-blank/templates/basic-page.php)) make use of the Markup Regions feature but there are no comments in the files that explain this.

Markup Regions are mentioned at the top of [_main.php](https://github.com/processwire/processwire/blob/fdb5a1994167a29ced4b4fe6e7fcb3b4b9ae9a42/site-blank/templates/_main.php) but new users may not have examined this file before looking at the template files. For those who are not familiar with the Markup Regions feature it is confusing to see just see the #content div in the template files.

Maybe these two template files could contain a comment along the lines of:

```php
// The #content div in this file will replace the #content div in _main.php when the Markup Regions feature is enabled, as it is by default.
// You can also append to or prepend to the #content div, and much more. 
// See the Markup Regions documentation: https://processwire.com/docs/front-end/output/markup-regions/
``` 

Related forum topic: https://processwire.com/talk/topic/28974-what-is-this-behaviour-template-html-replacement-by-id/

### Setup/Environment

* ProcessWire version: 3.0.226

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai that's a good idea, I have added it.

**Comment by Toutouwai** [comment]
Thanks
