### ISSUE TITLE
Images custom fields: fields are lost from page editor if images field is renamed

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1808]
### Short description of the issue

I have a field named "images_custom" that has "Custom fields" enabled and a "Countries" field added.

![2023-09-07_110831](https://github.com/processwire/processwire-issues/assets/1538852/9a2b8dfc-3761-4e6d-ad2a-31b70668115b)

If the field is later renamed (in this case to "images_custom_fields") then the custom fields disappear from the page editor.

![2023-09-07_110905](https://github.com/processwire/processwire-issues/assets/1538852/65e2a373-36ab-488d-b7b1-cbd7ff58fd99)

The problem seems to be that the custom fields template is not renamed when the images field is renamed, and so it becomes disconnected from the images field.

### Expected behavior

Able to rename an images field without losing custom fields configuration.

### Setup/Environment

* ProcessWire version: 3.0.226

**Comment by ryancramerdesign** [comment]
@Toutouwai The custom fields template for file fields is supposed to be an entirely user-managed template. So I'm usually reluctant to add code to FieldtypeFile to manage a template. But handling the rename seems like a worthwhile convenience we can add, and there's already a Fieldtype method called after a rename occurs, so it's a simple addition. I've gone ahead and added this. Thanks.

**Comment by Toutouwai** [comment]
Thanks
