### ISSUE TITLE
Missing normal "Publish" button when adding a page

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#181]
### Short description of the issue

In some scenarios, the normal "Publish" button is removed via JS after the page finishes loading.

### Expected behavior

It should exist :)

### Actual behavior

The new "Publish and Add Another" button exists, but the normal "Publish" button is removed.

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2017-02-01 at 7 04 48 am](https://cloud.githubusercontent.com/assets/871211/22512209/077e8342-e84d-11e6-9172-92cc1ff1d2e6.png)

### Steps to reproduce the issue

Not sure exactly what combo is required, but I have seen it several times in the last couple of days, so just keep an eye out for it.

### Setup/Environment

* ProcessWire version: 3.0.51

**Comment by adrianbj** [comment]
Actually, related to this the fact that the Save + Publish + Add Another button doesn't seem to publish the page, nor does it proceed to add another. It just saves it and leaves you on its edit page.

**Comment by ryancramerdesign** [comment]
Thanks Adrian this has been fixed. The Save+Publish+Add button is supposed to show/hide with the Save+Publish button, but some JS code just needed to be updated to add it.
