### ISSUE TITLE
Changing Files field to Images field errors

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1811]
Easy to replicate:

- Create a new Files (single file) field called x1.
- Fully save it.
- Change it to an Images field and save it and this error will occur:
```
PDOException #42S01
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'field_x1_pwtmp' already exists
```

Tested on PW latest master.

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani, looks like this bug has been hiding for awhile — I've pushed a fix.
