### ISSUE TITLE
Pageimage width(), height() and ratio() methods don't use database values

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1812]
### Short description of the issue

For a while now PW has stored the width, height and aspect ratio of each image in the database table for each image field.

![2023-09-14_153854](https://github.com/processwire/processwire-issues/assets/1538852/00c88e34-ac2a-4383-9a55-c1b8a097116d)

I expected that when PW has already calculated width/height/ratio for an image and saved it to the database, calling `$pageimage->width()`, `$pageimage->height()` or `$pageimage->ratio()` would return the saved value in preference to recalculating it on every method call.

Calculating those values can be quite costly for performance, expecially in the case where an SVG file does not have width or height attributes in its code ([related issue](https://github.com/processwire/processwire-issues/issues/1810)). It seems to depend on the hosting environment somewhat, but here is an example where it takes over 6 seconds to get the width, height and ratio of 9 SVG images:

![2023-09-14_154622](https://github.com/processwire/processwire-issues/assets/1538852/17129a30-8211-4e23-ab05-9517c169ef51)

It would have been a lot faster if these were retrieved from the database.

In the case of an SVG without width or height attributes, going to ImageMagick to get the width and height is quite slow. Although I'm not 100% sure about this I think the width and height of the [viewBox attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) will be accurate and will be much faster. It will also be an advantage for environments where ImageMagick isn't installed.

When I add the following code to `Pageimage::getImageInfoSVG` after [line 549](https://github.com/processwire/processwire/blob/2ea60ee7d545f347a68bcfa5f6c4507e092f8aed/wire/core/Pageimage.php#L549) ...

```php
if((!$width || !$height) && $a->viewBox) {
    $values = explode(' ', $a->viewBox);
    if(count($values) === 4) {
        $width = (int) round($values[2]);
        $height = (int) round($values[3]);
    }
}
```

...then the example from above that took 6 seconds now takes only 13 milliseconds.

![2023-09-14_162710](https://github.com/processwire/processwire-issues/assets/1538852/0fa209cc-9c88-4ee7-a32e-2ef32a10e767)

### Expected behavior

Width/height/ratio retrieved from database when values exist, and when they don't hopefully faster performance by using viewBox rather than ImageMagick as a last resort.

### Setup/Environment

* ProcessWire version: 3.0.227

**Comment by adrianbj** [comment]
Just in case it helps a little, here is some code I use elsewhere:

```
        preg_match('/<svg([^>]*?)width\s*=\s*\"(\d+\.?\d*)\"/is', $code, $matches);
        if(count($matches) > 0) {
            $width = $matches[2];
        }

        preg_match('/<svg([^>]*?)height\s*=\s*\"(\d+\.?\d*)\"/is', $code, $matches);
        if(count($matches) > 0) {
            $height = $matches[2];
        }

        if(!isset($width) || !isset($height)) {
            preg_match('/viewBox\s*=\s*\"(.*?)\"/is', $code, $matches);
            $attrs = explode(' ', $matches[1]);
            $width = $attrs[2];
            $height = $attrs[3];
        }
```

Of course I think it's still important to keep that imagick fallback in case the SVG also doesn't have a viewbox.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai Thats's a good find! I have pushed a fix for this. 

Note the ratio value is stored in the DB but is not stored in Pageimage objects and instead is calculated when requested at runtime. But width and height are of course supposed to use the DB value (unless a reset is requested).

**Comment by Toutouwai** [comment]
Thanks

**Comment by ryancramerdesign** [comment]
@Toutouwai I have added your faster SVG width/height detection code, thanks. I didn't realize IMagick was so slow to do the same thing. https://github.com/processwire/processwire/commit/a0fabd68111c3c19f09b112eb66c7cc29dd65746

@adrianbj Didn't you post another SVG width/height detection code earlier, but now it seems to be deleted? Just wanted to double check, did you delete it because the one Toutouwai posted already accomplishes the same thing? Or should we revisit it?

**Comment by adrianbj** [comment]
@ryancramerdesign - @Toutouwai's version does the same thing and is cleaner in the context of the code around it, so all good.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign.

One issue is that the database can contain invalid width and height values, possibly because of a failed attempt to calculate the width and height when the image was originally uploaded.

![2023-09-26_114933](https://github.com/processwire/processwire-issues/assets/1538852/d6cab0e6-e1d8-4f7d-9fc6-5e0db00ed814)

Now when you use $pageimage->width or $pageimage->height this seems to get translated to "100%", which isn't really what's wanted.

You can see this within the core images field:
![2023-09-26_115141](https://github.com/processwire/processwire-issues/assets/1538852/e1276c81-a30d-41c6-9eb1-a90939322b40)

Often the core _will_ be able to calculate a width and height for these images (e.g. because of the change just committed, or because ImageMagick was installed since the image was first uploaded). So when getting the image info could the core check for this kind of invalid data and if present attempt to calculate the width and height again? Ideally if the new attempt to calculate the width and height is successful this would also be written to the database.

**Comment by ryancramerdesign** [comment]
@Toutouwai The negative numbers are meant to refer to percentages rather than pixels, if I'm remembering correctly. So they are expected values. Though I think you should only see it on SVG images that didn't specify dimensions. But it sounds like maybe you are looking for an option to force it to recalculate the dimensions? This might be a good public function to add to the Pageimage class, and perhaps add to our image actions select in InputfieldImage?

**Comment by Toutouwai** [comment]
@ryancramerdesign, what I had in mind was changes within `Pageimage::getImageInfo()` so correct dimensions and ratios can be returned and stored when PW is able to calculate them.

When `Pageimage::getImageInfo()` returns width 100% height 100% ratio 1 this is not information that's useful. It's just the result of failing to successfully get a width, height and ratio and doesn't reflect the real attributes of the image. I think it would be better to return something that is more clearly an indication of "cannot get the requested value" rather than something that could be misinterpreted as a real value. Maybe it should just return null for width, height and ratio?

And although it's great to have this latest commit that returns the database values, when the database contains these values that indicate a previous failed attempt to calculate width/height/ratio (I'll call them "fail values" as a shorthand) this represents a case where the old behaviour produced a better result. Prior to the commit PW attempted to calculate the width/height/ratio each time these were requested, and that allowed for returning correct values in the following case: the database contains fail values but as a result of core changes or environment changes since the initial upload (which could have been many years ago) PW can now actually calculate the width/height/ratio.

So what I'm proposing is that `Pageimage::getImageInfo()` follows a procedure like this when the `$reset` argument is false (the default):

1. Look for stored database values.
2. If there are stored values, are they real values or fail values?
3. If they are real values then return them. If they are fail values then attempt to calculate the values by calling `getImageInfo(true)`.
4. If real values are available then return them and save the values to the database so they will be available more efficiently next time. If the result is fail values again then return that (as above my preference is for null but maybe that would be a breaking change even though the previous fail values are not really usable?)

**Comment by ryancramerdesign** [comment]
@Toutouwai The thing with it returning something like 0 or -1 is the return values of these width/height properties/methods are most commonly used or width/height attributes in img tags, and folks use things like `$image->width` directly in `<img>` tag attributes. I think it was @adrianbj (?) that originally suggested using 100% (rather than 0) as the return value since the issue is apparently common with svg images. So the idea is it's better to at least show the image than make it invisible with width=0 or null. 

Since a 100% could also be considered a fail value, it sounds like it should attempt a redo when it encounters a stored 100% value? And if someone wants a fail value, they could consider 100% to be that, or perhaps an argument like `false` in `$image->width(false)` could return some different fail value?

**Comment by Toutouwai** [comment]
@ryancramerdesign, what is returned as fail values is just a side-issue really. Personally I would never want to directly use the current fail values because they are probably wrong (e.g. the ratio is unlikely to be 1 and using width="100% height="100%" in an img tag is liable to do some strange stuff depending on the preserveAspectRatio attribute of the SVG). But as long as they are identifiable by checking for "100%" then anyone can handle them as they like.

The more important thing is making an attempt to calculate the width/height/ratio when the database contains fail values, so that the previous commit doesn't introduce a new issue for anybody's code that was working prior to the commit.

**Comment by ryancramerdesign** [comment]
@Toutouwai  I have updated it so that it will not use the DB cached values when they are 100%x100% and instead it'll attempt to recalculate.

**Comment by Toutouwai** [comment]
Thanks
