### ISSUE TITLE
getModuleInfo no longer returns info for string with namespace

### ISSUE THREAD

**Issue by mpsn** [processwire/processwire-issues#1813]
### Short description of the issue

After 3.0.226's module info rework $modules->getModuleInfo is no longer able to find modules by string if the string includes the namespace. While probably not the most pressing of issues, this could potentially break stuff from ≤3.0.210.

I didn't try all combinations of parameter types, but since Wire::className also uses get_class if you specify `$options["namespace"]` (and hence returns the module name with namespace), there could be several ways where getModuleInfo is unable to locate the corresponding module.

### Steps to reproduce the issue

```php
<?php # site/modules/TestModule.module.php
namespace ExampleNamespace; // or any namespace

class TestModule extends \ProcessWire\Process {
	public function ___execute() {
		// "TestModule"
		$thisworks   = \ProcessWire\wire('modules')->getModuleInfo(basename(str_replace('\\', '/', __CLASS__)));

		// "ExampleNamespace\TestModule"
		$thisdoesnot = \ProcessWire\wire('modules')->getModuleInfo(__CLASS__);
	}
}
```

### Setup/Environment
PW 3.0.226+

**Comment by ryancramerdesign** [comment]
@mpsn I wasn't aware that we supported namespaced module names for a getModuleInfo call, as module names still have to be unique even if in a namespace. It seems easy enough to support though. Just curious what is calling getModuleInfo() with a module's namespaced class name? If it's something in the core or one of my modules, I'd like to fix that too.

**Comment by mpsn** [comment]
I don't know about an immediate problem with the core, i stumbled upon this when i was throwing strings at getModuleInfo and got blank results. It still returns module info as expected when passing objects, but a call like `$modules->getModuleInfo("ProcessWire\FieldtypeCombo");` will no longer work post-update.
Since PW itself is using a namespace and getModuleInfo returns namespace information, i'd assumed this to be an unintended side effect of the module info update.

**Comment by ryancramerdesign** [comment]
Thanks @mpsn I have pushed an update that adds support for namespaces in the getModuleInfo call.

**Comment by mpsn** [comment]
Thanks, i'll give it a try later.
