### ISSUE TITLE
Inputfield TextTags is not fully translatable

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1817]
When adding a new item, the "Add" text that appears in front of the item label doesn't seem to be translatable. As far as I can tell Selectize doesn't have i18n support per se, but templates are configurable and "Add" is part of the "option_create" template:

```
				'option_create': function(data, escape) {
					return '<div class="create">Add <strong>' + escape(data.input) + '</strong>&hellip;</div>';
				}
```

Perhaps InputfieldTextTags could override this by default with a translatable version?

### Setup/Environment

* ProcessWire version: 3.0.227

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this.
