### ISSUE TITLE
Single file field wrongly retains uploadName after new upload

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1819]
### Short description of the issue

Single file fields have a feature where existing data such as description, tags, etc, are retained after a new file is uploaded. This is useful in general (although maybe this should be configurable somehow in case there are scenarios where it's not wanted?)

But if the field contains a file that caused the uploadName property to be set from the original filename...

![2023-09-25_134818](https://github.com/processwire/processwire-issues/assets/1538852/4d4ecfce-2b96-448f-96e3-644bd01c776b)

...and I then upload a different file which does not contain any disallowed characters that would cause the uploadName property to be set, then the previous uploadName is retained.

![2023-09-25_135016](https://github.com/processwire/processwire-issues/assets/1538852/6089068b-c111-45c7-9f14-465f0a878833)

That doesn't seem correct to me.

### Setup/Environment

* ProcessWire version: 3.0.228

**Comment by ryancramerdesign** [comment]
@Toutouwai A file is temporary until the page is saved, so you wouldn't see the new uploadName until after uploading the new file and then saving the page. I did try to duplicate here, but the upload name is getting updated for the new file, at least once I save the page.

**Comment by Toutouwai** [comment]
@ryancramerdesign, did the second file you uploaded have a name that already conforms to name format allowed by file fields?

To reproduce this issue you need two files: one with a name that doesn't conform to the allowed format (and hence will generate an uploadName when uploaded) and one with a name that does conform to the allowed format (this will not generate an uploadName when uploaded). When you upload the second file it replaces the first but the uploadName value from the first file is retained when it should be cleared.

**Comment by ryancramerdesign** [comment]
@Toutouwai Okay, I understand now. I have pushed a fix for this. Thanks.
