### ISSUE TITLE
has_parent issue with multiple piped values

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#182]
### Short description of the issue

`has_parent=$pageArray` as selector does yield unexpected results.

### Expected behavior

Multiple parents to be possible for `has_parent` by using pipes. or-groups do already work.

### Actual behavior

It does return pages, which shouldn't be returned.

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/topic/15455-order-of-selectors-in-pages-find/
https://github.com/processwire/processwire-requests/issues/17
https://github.com/ryancramerdesign/ProcessWire/issues/1232

### Setup/Environment

* ProcessWire version: 2.7. / 3.0

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix for this issue in the latest commit.
