### ISSUE TITLE
File field always return Pagefiles even if configured for only one file

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1820]
### Short description of the issue

File field always return Pagefile**s** even if configured for only one file and formatted value is set to single-file.

### Expected behavior

$page->myFileField should be of type Pagefile and not Pagefile**s**.

### Actual behavior

$page->myFileField is of type Pagefile**s**.

### Steps to reproduce the issue

1. Create a file field,
2. Configure it with maximum number of files to 1,
3. Configure it with formatted value to either "Automatic" or "Single-file",
4. Upload a file and see that $page->myFileField is of type Pagefile**s** instead of Pagefile.

### Setup/Environment

* ProcessWire version: 3.0.228
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
The "formatted value" setting is referring is referring to how you want the value to behave when it is formatted for output purposes. This is for front-end output convenience. Its sounds like you  have output formatting turned off. See [this article](https://processwire.com/blog/posts/output-formatting/) for more details. There also a brief section on how it affects [file and image fields](https://processwire.com/blog/posts/output-formatting/#file-and-image-fields).

**Comment by hiboudev** [comment]
Hi @ryancramerdesign, I forgot to mention I'm in a hook, I never thought about output formatting in hooks, so I suppose it's disabled?
So I will always get a Pagefile**S** instance? That's fine for me. I just thought there was a bug because behavior was different from what is documented.
