### ISSUE TITLE
PageAutoComplete throws ajax error if "Parent" and "Selector string" are combinated (PW > 3.0.222)

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#1821]
### Short description of the issue
PageAutoComplete throws an ajax error if "Parent" and "Selector string" are combinated

### Steps to reproduce the issue
1. Create a PageAutoComplete field
2. In the field configuration, set "Parent" of the pages that are selectable
3. In the field configuration, set a "Selector string" like "include=hidden"

**This combination will always give no results**, because it leads to an ajax error like this (check browser console -> network tab).
{"error":true,"message":"Unrecognized &#039;hiddenhas_parent=1040 &#039;in &#039;include=hiddenhas_parent=1040 &#039;- use only: hidden, unpublished, trash, all"}

Notice that the concatenation between "include=hiddenhas_parent" misses a comma. It should be: include=hidden,has_parent

The error was introduced in this commit:
[1c70f8b](https://github.com/processwire/processwire/commit/1c70f8b5e31ba97d04451567086be7a07c3cd23c)

**Comment by ryancramerdesign** [comment]
Thanks @processwired I've pushed a fix for this issue

**Comment by matjazpotocnik** [comment]
@processwired, can this be closed?

**Comment by matjazpotocnik** [comment]
@processwired closing. Reopen if needed.
