### ISSUE TITLE
findRaw() is very slow when getting Page Reference field with null value

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1824]
### Short description of the issue

findRaw() is fast when...

Example 1 - I find some pages that have a value in the "structural_class" Page Reference field:
![2023-10-05_165651](https://github.com/processwire/processwire-issues/assets/1538852/f8ef3424-fea4-4dd0-865c-9fa5a1deca2c)

Example 2 - I find some pages that do not have a value in the "structural_class" Page Reference field but I don't include "structural_class" in the $field argument:
![2023-10-05_165724](https://github.com/processwire/processwire-issues/assets/1538852/a5933025-51fc-4787-b4f5-a8d196c0874b)

But is very slow when...

Example 3 - I use the same selector as example 2 but I do include "structural_class" in the $field argument:
![2023-10-05_171033](https://github.com/processwire/processwire-issues/assets/1538852/e9bf271e-198b-4f80-a7c5-214863d9880e)

It's nothing specific to that particular Page Reference field. Here is another slow result when getting a different empty Page Reference field:
![2023-10-05_171409](https://github.com/processwire/processwire-issues/assets/1538852/6517c02f-d4f7-4945-ac2d-f2301636e884)

It seems like as soon as there is at least one non-null result it is fast:
![2023-10-05_172133](https://github.com/processwire/processwire-issues/assets/1538852/96e303b5-d51c-4dbd-96c8-7944de5784ec)

### Setup/Environment

* ProcessWire version: 3.0.229

**Comment by ryancramerdesign** [comment]
@Toutouwai I'm not sure I'm duplicating exactly what you are seeing because if I setup the same scenario, I'm only seeing a 20ms difference between the slow one and the fast one. But I was able to make adjustments so that they now both execute at the same speed, in my setup at least. Can you check if this applied fix does the same there? Thanks.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, that fixes it.
