### ISSUE TITLE
Upon creation a FieldsetPage’s output formatting is on because of parent

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1825]
### Short description of the issue

When creating a page with a FieldsetPage, this FieldsetPage’s [output formatting is turned on because of its `forPage`](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/modules/Fieldtype/FieldtypeRepeater/FieldsetPage.php#L53).

### Suggestion for a possible fix

I don’t know if there would be unexpected consequences to this but adding a check against `isNew` solves this issue:

```php
53	// mirror the output formatting state of the owning page
54	if($this->forPage && !$this->getOf && !$this->isNew) {
55		$of = $this->forPage->of();
56		if($of != $this->of()) $this->of($of); 
57	}
```

### Setup/Environment

* ProcessWire version: 3.0.227

### How it came to be an issue

In a project I’m working on I need to export / import pages but also in-between make changes to accomodate the new structure. These pages contain a (necessary) mess of FieldsetPages/RepeaterPages/RepeaterMatrixPages with some being within others.

During the import, I’m facing an issue right at the creation of the page, even with a simple `$pages->new("my-template")`.

My template (short version) is as such:
```
my-template
↳ my-fieldsetpage
  ↳ my-other-fieldsetpage
    ↳ my-table
```

The creation fails because of FieldtypeTable complaining during the `___sleepValue()` call that the value is formatted. Normally this is ignored thanks to this [try/catch](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/core/PagesEditor.php#L728), ~~but in my setup, for a reason I do not understand, `$config->allowExceptions` ends up being true and blocks my import script, and yet, somehow, with a simplified case it doesn’t~~, scratch that it’s because of one of TracyDebugger’s latest update setting [`$config->allowExceptions`](https://github.com/adrianbj/TracyDebugger/blob/ec79b76bf0443118a6c402c9ffe2a9c491a8b5cc/TracyDebugger.module.php#L914) to true (see this [issue](https://github.com/adrianbj/TracyDebugger/issues/58)).

**Comment by adrianbj** [comment]
@romaincazier - sorry that change to Tracy has confounded things for you. I'll wait for @ryancramerdesign to chime in first before I change anything though if that's ok.

**Comment by ryancramerdesign** [comment]
@romaincazier I'm not sure how to duplicate the issue, but the suggestion seems to make sense even without the issue, so I have added it. Thanks!
