### ISSUE TITLE
Adding image to Page via API when the url contains a © symbol (copyright) results in a mismatch between filenames

### ISSUE THREAD

**Issue by thytruong** [processwire/processwire-issues#1829]
### Short description of the issue
When using the API to add an image to a page, e.g. : `$p->image->add($src)` where the url string `$src` contains a © symbol, 
the image upload is OK but when viewing the page editor, the image shows 0KB in size and an error message says 'Pageimage: Original image does not exist to create size variation: [filename].jpg'.

### Expected behavior
The image should show a proper size and should be correctly referenced. 
The image should have the same filename in the `assets/files/` directory and in the image field in the page.

### Actual behavior
But in the upload process, the © symbol was transformed to `_C_` for the file in the assets folder and was transformed as `_c_` in the image field in the page. 

### Suggestion for a possible fix
Now, manually renaming the filename in the `assets/files/` directory with a small cap `c` does solve the issue.
A correction of the renaming process in the `p->image->add` function should be straightforward.

### Steps to reproduce the issue
1. With the API, add an image from source with an url containing a © symbol with `$p->image->add($url)` to a certain page
2. Go to the editor of this page
3. The image should be shown as 0KB in size and with the error : `Pageimage: Original image does not exist to create size variation: [filename with "_c_" in it.jpg]`

* ProcessWire version: 3.0.229
* (Optional) PHP version: 8.2

**Comment by ryancramerdesign** [comment]
Thanks @thytruong I've pushed a fix for this issue

**Comment by thytruong** [comment]
Thanks for the good work !
