### ISSUE TITLE
Markup Regions shouldn't remove HTML Comments

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1830]
I'm using markup regions and have some HTML comments, however it is stripping them out.

To test, simply take a fresh installation using the site-blank profile and modify basic-page.php like so:
```
<div id="content">
	<!-- this is a comment -->
	Basic page content 
</div>
```

When viewing the page, the comment gets stripped and doesn't appear.  When HTML comments are added outside the region area (such as _main.php), the comments do appear however.

**Comment by jlahijani** [comment]
Investigating WireMarkupRegions.php and I see it looks like ProcessWire is removing them purposely.

My use case for them being maintained is that I'm using a 3rd party ticketing service that hits a particular page on my site and takes the HTML of that page.  The service requires the existence of a special HTML comment so it knows where to inject its content.

I can work around this for now however.

**Comment by jlahijani** [comment]
A bit of a related request.  In ProCache, if "Strip HTML Comments" is enabled, ideally comments within NoMinify should not be stripped?  Example of bar comment being stripped even though it is inside NoMinify:

```
<!--NoMinify-->
<p>Foo <!-- bar --> baz.</p>
<!--/NoMinify-->
```

**Comment by ryancramerdesign** [comment]
@jlahijani Markup Regions shouldn't strip comments that begin with `<!--#` (with the `#` added) ... does that provide a solution for this case?

**Comment by jlahijani** [comment]
Yes.  This works well.
