### ISSUE TITLE
Suppress notice for missing file in `Pageimage::size`

### ISSUE THREAD

**Issue by hirasso** [processwire/processwire-issues#1831]
### Short description of the issue

I'm looking for a way to suppress the warning for missing image files, if the URL starts with `http`. 

### Context

I have a lot of very image-heavy websites. Storing all assets for those locally on my machine would not be possible. That's why I have done the folllowing:
#### Config:

```php
// load locally missing files from this URL
$config->remoteAssetMirror = "https://example.com";
```

#### Hook:

```php
/**
 * Mirror locally missing files from the remote asset server
 */
wire()->addHookAfter('Pagefile::url', function (HookEvent $event) {
	$config = $event->wire()->config;
	$file = removeTrailingSlash($config->paths->root) . (string) $event->return;

	// Bail early if there is no remote mirror defined
	if (!$config->remoteAssetMirror) return;

	// Bail early if the file exists locally
	if (file_exists($file)) return;

	$event->return = "{$config->remoteAssetMirror}$event->return";
});
```

This is all working fine, especcially with the fix implemented in #1812 to get the width and height of the image from the database.

The only problem I'm still facing that with missing images, I'm bombarded with errors in the admin panel now:

![Screenshot 2023-10-25 at 13 08 39](https://github.com/processwire/processwire-issues/assets/869813/77e0b6b9-b6fa-4e7a-8c7c-2cc4800eb1bd)

### Optional: Suggestion for a possible fix

Is there a way to suppress this warning? Probably by just checking if the `url` of a `$pageimage` starts with `http`? Maybe I can do this already, I'm just missing how to?

### Setup/Environment

* ProcessWire version: 3.0.229

**Comment by ryancramerdesign** [comment]
@hirasso Those error messages come from the Pageimage::___size() function, so if you just needed to suppress those error messages, then you should be able to do it with another hook:
~~~~~
$wire->addHookAfter('Pageimage::size', function($event) {
  $image = $event->object; /** @var Pageimage $image */
  if($image->error) $image->errors('clear'); 
}); 
~~~~~

**Comment by hirasso** [comment]
@ryancramerdesign thanks so much, this is working nicely!

```php
/**
 * Suppress warnings for size generation of images loaded from remote mirror
 */
$wire->addHookAfter('Pageimage::size', function ($event) {
	$config = $event->wire()->config;

	/** @var Pageimage $image */
	$image = $event->object;

	/** Bail early if there is no remote mirror defined */
	if (!$config->remoteAssetMirror) return;

	/** Allow errors if the url of the image is local */
	if (!str_starts_with($image->url, $config->remoteAssetMirror)) return;

	if ($image->error) $image->errors('clear');
});
```
