### ISSUE TITLE
PagePathHistory multi-language handling

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1833]
### Short description of the issue

PagePathHistory does not take into account changes for languages other than default if the page parent has changed but not the name.

### Expected behavior

Redirects for all languages instead of 404.

### Optional: Suggestion for a possible fix

<img width="790" alt="Bildschirmfoto 2023-10-28 um 11 22 03" src="https://github.com/processwire/processwire-issues/assets/4683120/3ea39aa6-6eb1-4d50-837d-879ff33875ee">

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed your suggested fix for this. I also left the existing line as a fallback in case no "name$language" is populated.
