### ISSUE TITLE
issue with ProcessCommentsManager.module on non-UiKit admin theme

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#1834]
### Short description of the issue

ProcessCommentsManager fails to execute on the non-UiKit admin theme

### Actual behavior

In the below code, 

[github](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module#L1104)
```
$classes['select'] = $adminTheme->getClass('select-small');
$outs['status'] = "<select name='CommentStatus$id' class='CommentStatus $classes[select]'>";
```

$classes[select] fails when **not** using AdminThemeUikit, 
probably because :
- 	_(context)_ the standard admin theme does not populate class 'select-small'
- 	_(bug)_ and the initilization of $classes is missing the entry 'select' => ''

### Optional: Suggestion for a possible fix

Add initialization here :

[github](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module#L1010)
`			'select' => ''`

### Setup/Environment

* ProcessWire version: 3.0.228
* (Optional) PHP version: 8.0

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed a fix for this.
