### ISSUE TITLE
ShowIf with TextArea target doesn't work if TextArea is locked

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1838]
### Short description of the issue

2 fields on a page, a TextArea and an Integer. I want the Integer to show only if TextArea has text.
I set the showIf condition: raceResultsParsingSummary!=''
But the field is always hidden if raceResultsParsingSummary visibility is locked.

### Setup/Environment

* ProcessWire version: 3.0.228

**Comment by Toutouwai** [comment]
Duplicate of https://github.com/processwire/processwire-issues/issues/1079

**Comment by ryancramerdesign** [comment]
@hiboudev If a field is locked then no inputs are rendered for it, and so there's nothing for the dependency to compare against. I'm not really sure of a way around it short of just rendering the inputs as if it weren't locked. But then that's also confusing if inputs are present and the user can't edit them. It might seem fine for a standard text field combined with a disabled attribute, but it's not something that scales well to more complex Inputfield types, especially those that use lots of JS.

In my post last week I mentioned I was working on a module that lets you lock fields individually in the page editor, and with this module there's an option to still render the inputs even if a field is locked. If you click in any locked input, it pops up an alert saying the field is locked. This mode should enable the show-if/required-if dependencies to still work, but give it a try and see. I expect to release it later today.

**Comment by hiboudev** [comment]
What do you mean by "no inputs are rendered for it"?
The field is locked but displayed and I see the text in it.

It's just a field to give a feedback to user on PW admin, I lock it so user can not edit it. I also like the fact that field is extended to its content when locked. Maybe I could use another field type for this?

For now I'll do it with a hook, and I'll look at your module when released. Thanks.

**Comment by ryancramerdesign** [comment]
> What do you mean by "no inputs are rendered for it"?

This is an oversimplification, but field dependencies use JS to monitor the `<input>` (and similar) elements `value` attributes and make comparisons with that. When a field is locked, then those `<input>` elements are not rendered, and just the value is. 

Take a TinyMCE or CKEditor field for example, if it's locked, then just the markup is rendered (`<p>` elements and such), rather than the `<textarea>` that allows input to it.  Without that textarea, the dependencies don't have an input element to work with. So when another field uses a showIf or requireIf pointing to that locked field, that's why we run into this issue.

> I also like the fact that field is extended to its content when locked. Maybe I could use another field type for this?

If this is a TinyMCE field, then using the inline" mode it'll expand vertically to fit the full content, even when not locked. But that would be an editable field, so probably not what you are looking for.

**Comment by hiboudev** [comment]
OK I see the logic. I don't know the implementation, but isn't it possible for you in that case to create a kind of "fake input" that still manage showIf/requiredIf but without all the input stuff?

**Comment by adrianbj** [comment]
@hiboudev - my tweaked version of @Toutouwai's code (https://github.com/processwire/processwire-issues/issues/1079#issuecomment-1218057264) works pretty well in most cases, but I still think this needs to be a core feature.

**Comment by ryancramerdesign** [comment]
> I don't know the implementation, but isn't it possible for you in that case to create a kind of "fake input" that still manage showIf/requiredIf but without all the input stuff?

Yes, that would be one way to go. But it's potentially a lot of overhead and duplication as we'd have to both render the value for presentation purposes and then hidden inputs, just for the dependencies. Plus, every Inputfield would have to have a new method for rendering hidden inputs. Perhaps simple for text inputs, but imagine Table, Repeater, etc. There's a real danger of overcomplexity and code bloat. Every Inputfield type would have to be expanded manually to support it. It doesn't seem worth it. So I think it's better just to avoid locking fields that you use for dependencies. After all, why have a dependency against a fixed value? Another route is the new PageEditLockFields provides an option where it can render the inputs for locked fields. I may end up adding a similar option to the core, where a field is locked, but still renders it's inputs. I figured we'd test on this module for a bit and see how it goes, then maybe migrate something similar to the core.

**Comment by hiboudev** [comment]
> After all, why have a dependency against a fixed value?

Value is modified by a hook after processing a file, it can be empty or with text.

> But it's potentially a lot of overhead and duplication

OK, thanks for explaining.

I had a look to your Lock module, it looks fine, didn't test it yet but it looks like it solves this issue, so I can close.

Thanks.

**Comment by ryancramerdesign** [comment]
Make sure to grab the latest commits to the module as there was an issue
with this particular feature which I pushed a fix for an hour ago.

**Comment by adrianbj** [comment]
> After all, why have a dependency against a fixed value?

@ryancramerdesign - I often have fields locked in the admin that are populated and modified by users via frontend fields. It's important that staff don't changed these in the admin though which is why they are locked. So I think the key difference here is "locked" vs "fixed" as you describe - make sense?

**Comment by szabeszg** [comment]
> I often have fields locked in the admin that are populated and modified by users via frontend fields. It's important that staff don't changed these in the admin though which is why they are locked.

Me too. So far I used hooks and/or JavaScript for workarounds but that was mostly possible when field dependency was not required.

I understand that supporting something like this can be time consuming so in the future when ProcessWire 4 is in planning, I would seriously consider using htmx + alpine.js as the bases for completely refactoring the admin's UI.
