### ISSUE TITLE
Hook pages::restored is never called

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1848]
I take the [example in documentation](https://processwire.com/api/ref/pages/restored/), but it's never called:
```
$this->addHookBefore('Pages::restored', function(HookEvent $event) {
    wire()->log->message("Restored!!");
});
```

### Setup/Environment

* ProcessWire version: 3.0.228
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by kixe** [comment]
Hook is called if Page is restored via Edit Interface, but not via Action Button in Page-tree.

**Comment by ryancramerdesign** [comment]
Thanks @hiboudev @kixe This should now be fixed in the commit referenced above.

**Comment by matjazpotocnik** [comment]
@hiboudev could you verify Ryan's fix, please, and close this issue?
