### ISSUE TITLE
FieldtypeOptions: Impossible to check / compare a value by ID

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1851]
### Short description of the issue

```
$page->optionsfield->hasID($id); // returns always bool false
```

`SelectableOptionArray::hasID($id)` will always fail (return bool false) due to the type conversion to integer in the function itself and the strict (identity) comparison in `SelectableOptionArray::getOptionByProperty('id', $id)`.

`SelectableOption::getProperty('id')` returns a string not int.

**Comment by kixe** [comment]
Furthermore, I recommend **not** making strict comparisons with numerical values `SelectableOptionArray::hasValue($numeric)`

### Example Setup

**1=2345|Audio  
2=6789|Video**


### Actual behaviour
```
$numeric = 2345; // int
$page->optionsfield->hasValue($numeric); // false

$numeric = '2345' // string
$page->optionsfield->hasValue($numeric); // true
```

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue.

**Comment by matjazpotocnik** [comment]
@kixe can this be closed?

**Comment by kixe** [comment]
Thanks. Fixed.
