### ISSUE TITLE
Should module text files be web accessible?

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1852]
I noticed I can hit this file:
https://processwire.com/site/modules/ProCache/CHANGELOG.txt

Considering that /README.md is blocked by .htaccess, I would think text files like the one I demonstrated should be as well?

**Comment by ryancramerdesign** [comment]
@jlahijani We do block both .md and .txt files, but only those having certain name prefixes: COPYRIGHT, INSTALL and README. I think you are right, it makes sense to add CHANGELOG to that as well.
