### ISSUE TITLE
Non-listable pages still included in parent item labelling

### ISSUE THREAD

**Issue by MetaTunes** [processwire/processwire-issues#1853]
### Short description of the issue

When viewing the page tree, if some pages are not listed because $page->listable is set to false, their parent item listed still behaves as if all its children are listed.

### Expected behavior

If a page has $page->listable = false, then it should be excluded in the page count shown against the parent. If the parent has no listable children, then no caret should be shown - i.e. it should be class PageListNoChildren, not PageListHasChildren. 

### Actual behavior

All pages, whether listable or not are included in the list total shown against the parent, so the number of pages listed is not equal to the number indicated against the parent. If there are children, but none of them is listable, a caret is shown, but clicking tjhe caret has no effect.
This is confusing to the user, who is usually someone with lower privileges and (if they are smart) makes them realise that there is stuff that is hidden from them.

### Steps to reproduce the issue

1. Set up a hook in ready.php to hook after Page::listable
2. In the hook (for example) set $event->return to be false if(!$user->isSuperUser()) for certain templates (NOT the home page as then nothing is seen!)
3. Sign in without superuser access and observe the behaviour described

### Possible fix
Amend the ProcessPageListRender::numChildren() method to not count non-listable chidren.

This seems to be the case for all PW versions I am using (latest is 3.0.229)

**Comment by Toutouwai** [comment]
This has been previously raised and discussed here: https://github.com/processwire/processwire-issues/issues/649

**Comment by MetaTunes** [comment]
Thanks @Toutouwai, I hadn't spotted that - will try the hook.
