### ISSUE TITLE
ProcessPageEdit Config Option 'Allow Use of Bookmarks ticked causes Red Screen'

### ISSUE THREAD

**Issue by solonmedia** [processwire/processwire-issues#1854]
### Short description of the issue

When modifying the Page Edit core module configuration as superuser, attempting to turn on the
'Allow Bookmarks' option and saving the configuration successfully saves the configuration, but causes fatal errors until
the value is returned to 0 in the db.

### Expected behavior

The config should get saved without incident.

### Optional: Screenshots/Links that demonstrate the issue

The result after saving the configuration:

![image](https://github.com/processwire/processwire-issues/assets/58667283/09bef834-b598-4920-a3d1-6b36dab52fc2)

The site at this point continues to operate, but any attempts to review the module config page for ProcessPageEdit fails.

### Setup/Environment

* ProcessWire version: 3.0.231
* (Optional) PHP version: 8.1

**Comment by ryancramerdesign** [comment]
@solonmedia Thanks for the report. I tried on 2 different installations but can't duplicate the issue. Are you able to duplicate it on an installation without any 3rd party modules installed?

**Comment by matjazpotocnik** [comment]
@solonmedia I also can't duplicate.

**Comment by matjazpotocnik** [comment]
@solonmedia, closing, reopen if needed.

**Comment by matjazpotocnik** [comment]
Closing.
