### ISSUE TITLE
Exception when uploading german language pack

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1857]
### Short description of the issue

Line 1227 of InputfieldFile.module has this:

    } else if($pagefile->filedata('uploadName')) {

which throws an error if $pagefile is null

### Suggestion for a possible fix

    } else if($pagefile && $pagefile->filedata('uploadName')) {

### Steps to reproduce the issue

Upload german language pack in one language

### Setup/Environment

* ProcessWire version: 3.0.231
* (Optional) PHP version: 8.2
* (Optional) MySQL version: MariaDB 10.6

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix

**Comment by BernhardBaumrock** [comment]
Thx :)
