### ISSUE TITLE
Can not save page with parent=home if I empty page name field and hit enter

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1859]
### Short description of the issue

Strange issue here.
In admin, if I want to add a child page to home, and if I delete name field content and press Enter, I can't save page.

Here is a video:
1. The first page I create, I just modify page name by adding chars and it works.
2. The second page, I delete page name to write a new one, then press Enter, and then I can not save page, not with save button, not with Enter key.

 https://www.youtube.com/watch?v=O_0kZDw4SwQ

Issue is **only with home child creation**, if I do the same in another parent it works.

I disabled all my hooks.

### How to reproduce

1. Add new page to home
2. Delete name field content, write a new one
3. Press Enter (don't click save button)
4. Now it's impossible to save page

### Setup/Environment

* ProcessWire version: 3.0.228

**Comment by ryancramerdesign** [comment]
@hiboudev So far I can't duplicate it, bit it sounds a lot like a JS error. Are you seeing anything in your console? Also, I noticed you have En and Fr for title inputs, but not for the name inputs, so it seems like something is missing.

**Comment by hiboudev** [comment]
@ryancramerdesign Actually I can't reproduce it myself.

About the name, I didn't install Language Support Page Names, can it lead to issues?
Since I configured languages I have read that SEO prefer to have different URLs, so I plan to update this later using Language Support Page Names.
Actually language is defined on user account, or detected with HTTP_ACCEPT_LANGUAGE for guests.
