### ISSUE TITLE
Update Link To Reference The New Repository

### ISSUE THREAD

**Issue by Mustafa-Online** [processwire/processwire-issues#186]
Please Update This link on contact page to reference the new Repo :

![1111](https://cloud.githubusercontent.com/assets/5323832/22838517/9a41bb00-efd6-11e6-9180-7cc94fa916b6.PNG)

**Comment by adrianbj** [comment]
Thanks @Mustafa-Online 

That is fixed, along with some others at the bottom of that page. Please let us know if you notice any others.

**Comment by ryancramerdesign** [comment]
Thanks for fixing that @adrianbj – I'll close this one.
