### ISSUE TITLE
FieldtypeOptions: value is empty

### ISSUE THREAD

**Issue by flihub** [processwire/processwire-issues#1865]
### Short description of the issue

Create FieldtypeOptions field with name "test_options"

### Expected behavior

In field details tabs api usage example : 
If you want to output values rather than titles, then replace “title” with “value” in the examples above.

### Actual behavior

"$page->test_options->value"  always empty.
$page->test_options->id gives value.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://github.com/processwire/processwire-issues/assets/16720735/5e6a6b5a-2f56-4f9b-adfa-ef7939300cb4)

dump: 
object(ProcessWire\SelectableOptionArray)#182 (5) { ["count"]=> int(1) ["items"]=> array(1) { ["SelectableOption:1"]=> array(3) { ["id"]=> int(1) ["title"]=> string(4) "True" ["value"]=> string(0) "" } } ["of"]=> int(1) ["page"]=> string(1) "/" ["field"]=> string(12) "test_options" }

* ProcessWire version: 3.0.229
* (Optional) PHP version: 8.2.10
* (Optional) MySQL version: 8.1.0

**Comment by ryancramerdesign** [comment]
@flihub Your setup here doesn't actually have any values entered. The 1 and 2 are IDs, which each option will always have, though PW will generate them for you. If you want values, you have to enter them like this below. For example, lets say you wanted the value for "True" to be "yes" and the value for "False" to be "no":
~~~~~
1=yes|True
2=no|False
~~~~~
Note that the 1 and 2 come from PW, so if you were entering them for the first time, then you would just enter this:
~~~~~
yes|True
no|False
~~~~~
See the FieldtypeOptions doc page on [Separate Option Values](https://processwire.com/docs/fields/select-options-fieldtype/#separate-option-values) for more details.

**Comment by flihub** [comment]
ok thank you.
