### ISSUE TITLE
WireHTTP defaultTimeout is too low

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1868]
I'm using WireHTTP (curl) and sending a large amount of JSON to an API.  When the json payload is large, the request times out.  When it is slimmed down, it goes through correctly.

After (A LOT) of trial and error, I realized it has to do with the default timeout value WireHTTP assigns to curl.  Right now, it gets set to 4.5 seconds, which seems very small for a default value.  I realize I can change it using the options array (which I have done), but 4.5 seconds is... crazy low?

**Comment by teppokoivula** [comment]
> but 4.5 seconds is... crazy low?

I wouldn't necessarily call this crazy low, or even low for that matter. The thing is that in many cases WireHttp is used within a web request, and in that context having a _relatively low_ timeout is a sensible solution. In my opinion having a low default and allowing developers to adjust it is by far the safest solution.

In my opinion a default value between 5 and 10 seconds would be the absolute highest it should go, and if it was up to me, I would probably keep it as-is. On the other hand the default timeout and how it can be adjusted could definitely be better documented.

(I've not had a closer look at code and don't know if 4.5 seconds is a value set in core, but if it is, I can't see any obvious mention of it in the docs for WireHttp, WireHttp::getTimeout(), or WireHttp::setTimeout().)

For the record — and I'm not saying that it's the greatest example in all cases — in WP the default timeout for WP_Http is 5 seconds flat.

**Comment by BernhardBaumrock** [comment]
Agreed @teppokoivula I'm using 2 seconds for RockMigrations filesOnDemand for example and thinking of lowering that even further so that if files don't exist on the remote it does not wait so long :)

**Comment by jlahijani** [comment]
I'm doing something on my end.  Closing.

**Comment by ryancramerdesign** [comment]
I think most often WireHttp is triggered from another http request. For instance, viewing a page on a site, and pulling in an RSS feed. The danger with a high timeout is requests could pile up and overwhelm the server, and it could also create DOS target. In this respect, even 4.5s is pretty high. So I guess I see 4.5s as a compromise timeout as being not too short, but also not too long. I've updated the phpdoc for the `setTimeout()` method to mention what the default value is.

**Comment by jlahijani** [comment]
As for Google Docs, it's a bit quirkier I just realized.  I'll make a video sometime next week for both MS Word and Google Docs.  I'll also check both Windows and macOS for each.
