### ISSUE TITLE
$page->httpUrl doesn't respect slashUrls

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#187]
### Short description of the issue

To try not to waste anybody's time, I started this discussion in the forums
https://processwire.com/talk/topic/15535-page-httpurl-doesnt-respect-slashurls/

The problem is $page->httpUrl always adds a trailing slash to the end of the url even if the template's slashUrls(Should page URLs end with a slash?) setting is set to No.

$page->url; method honors template slash settings for page, URL segments and page numbers shouldn't the $page->httpUrl as well?

You can do $page->url(true); which will give you the correct equivalent to $page->httpUrl.

### Expected behavior

I expected it to honor the template's slashUrls setting by removing the trailing slash.

### Actual behavior
If you echo $page->httpUrl; it prints:
http://mysite.dev/about-us/ instead of http://mysite.dev/about-us

### Setup/Environment
* ProcessWire version: ProcessWire 3.0.52
* (Optional) PHP version: 5.6

**Comment by gmclelland** [comment]
Looks like this was discussed here as well https://processwire.com/talk/topic/318-hacking-the-core-to-have-no-trail-slash-as-default/?do=findComment&comment=139372

**Comment by ryancramerdesign** [comment]
Thanks–I've pushed a fix for this issue.

**Comment by ryancramerdesign** [comment]
Commit d7d392fe95c9c7c6d3d4ed2fa806d213674345c4

**Comment by gmclelland** [comment]
Thank you
