### ISSUE TITLE
Logs page and JqueryTableSorter Module

### ISSUE THREAD

**Issue by BrendonKoz** [processwire/processwire-issues#1870]
### Short description of the issue

The JqueryTableSorter plugin doesn't understand units in a table's value field, so sorting breaks. The best example page to display this is the "Logs" (Setup > Logs) page, and trying to sort by the "SIZE" column.

### Expected behavior

Clicking on the "SIZE" column of the Logs page sorts the values in that column appropriately by size.

### Actual behavior

Nothing happens, aside from the sort direction on the table header toggles one way or the other.

### Optional: Screenshots/Links that demonstrate the issue

![processwire-log-jquerytablesort](https://github.com/processwire/processwire-issues/assets/194731/4240cdce-bd1d-40e9-8c75-ee098ff59a42)

### Optional: Suggestion for a possible fix

The fastest solution would be to display all values in the smallest unit (byte). If nicely rendered units are preferred, an [additional widget](https://mottie.github.io/tablesorter/docs/example-parsers-metric.html) for the TableSort may be required.

### Steps to reproduce the issue

1. Log into an administrative account on a ProcessWire install.
2. Navigate to "Setup" > "Logs"
3. In the column marked, "SIZE", click it to (attempt to) toggle ascending or descending order.

### Setup/Environment

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.228|
|PHP|8.0.27|
|Webserver|Apache/2.4.54 (Unix) OpenSSL/3.0.7|
|MySQL Server|8.0.32|
|MySQL Client|mysqlnd 8.0.27|

**Comment by Toutouwai** [comment]
This type of sorting (where the sorting happens on a value that's different than what is visible in the column) is already done in the log viewer: on the Modified column. There is a hidden timestamp as the first item in the each table cell, and so the sorting works on this rather than on the visible relative time string.

![2024-01-25_134748](https://github.com/processwire/processwire-issues/assets/1538852/a2cce9fc-f151-4a58-83f2-adbcf19422a9)

So the Size column just needs something similar, where the size in bytes is the hidden value.

**Comment by BrendonKoz** [comment]
Thanks Robin, I didn't seem to catch that, was too focused i guess. I'll look to see if I can provide a possible patch.

**Comment by BrendonKoz** [comment]
It seems it already attempts the same trick, just without success. Will try to take a closer look in the morning.

https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/modules/Process/ProcessLogger/ProcessLogger.module#L89

**Comment by Toutouwai** [comment]
Looks like it's the presence of a decimal point in the visible content that prevents the sorting. A bit hacky, but adding a non-digit character (but not a whitespace character) at the end of the hidden content gets it working. In this case I used an underscore:

```php
"<span style='font-size: 0;'>$logInfo[size]_</span>" . wireBytesStr($logInfo['size'])
```

**Comment by BrendonKoz** [comment]
Another option, without requiring a custom sort within JqueryTableSorter, would be to round up to the nearest full unit:

```php
"<span style='font-size: 0;'>$log[size] </span>" . wireBytesStr($log['size'], ['decimals' => 0])
```

**Comment by BrendonKoz** [comment]
The issue seems to stem from the parser's attempt at magically discerning what the value is in the cell. The space could be a separator, but so can the decimal (or a comma, depending on locality). I added a hyphen and space where the singular space was within the first value's span, and it fixes the issue, while still allowing the single decimal place after the visible unit.

```php
"<span style='font-size: 0;'>$log[size] - </span>" . wireBytesStr($log['size'])
```

This _could_ have a negative impact in future builds of the Jquery module if the parser attempts to automatically calculate mathematical values, but I'm thinking that would be better suited to a widget or data-element assignment within a custom sort, outside of the module's core focus. This _should_ be good, and keep all visible content the same! I also think that since the core module is seemingly no longer being actively developed, the likelihood of that being a problem is negligible.

**Comment by ryancramerdesign** [comment]
@BrendonKoz @Toutouwai I've pushed your suggested fix by adding a non-digit/non-whitelist character (underscore) in the hidden size. Tested and that seems to do the trick. Thanks!
