### ISSUE TITLE
File compiler causing "class not found" errors on high traffic site

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#1874]
### Short description of the issue

My colleagues and I have run into an issue which only seems to appear on one of our ProcessWire web applications during periods of very high traffic. The issue appears to be related to the file compiler. What happens is that the site will suddenly begin throwing "class not found" errors, even though nobody has made any change to the file system. The missing class is always a module that has been compiled by the file compiler (We disable file compiling on templates, so I can't say whether this issue would also affect template files). Since no change has been made to the modules (and it appears to me from a cursory look through the code that the module file compiler cache is not supposed to time expire) I can't figure out what would cause this sudden malfunction.

After this took down our client's site 2-3 times in a span of a couple weeks, I finally decided to go through each legacy module and manually add the necessary namespaces, disable module compiling, and clear our the cache. So far this has resolved the issue. I was reluctant to go this route at first, but it appears that Ryan now includes namespaces in all of his first party modules, so now I am thinking this is the right way for us to go, even if this issue gets resolved.

### Optional: Suggestion for a possible fix

Our temporary fix had been to manually remote onto the server and delete the file compiler cache directory (since the errors take down the entire site including the admin panel). However, this only seems to work if we also temporarily prevent access to the site (by throwing up a raw index.html file). Our working theory is that when lots of people are accessing the site at the same time, this is causing the compiler cache to become corrupted while it is being rebuilt. Perhaps a database lock is needed during the rebuild so that all requests are halted until it's finished? Still, that leaves the mystery of why the compiler suddenly decided to rebuild in the first place.

### Steps to reproduce the issue

This one is a challenge to reproduce since it only seems to happen on high traffic sites, and it seems almost random.

### Setup/Environment

We are deployed to an AWS server farm. I can get more info if needed.

* ProcessWire version: 3.0.178
* (Optional) PHP version: 7.4

**Comment by ryancramerdesign** [comment]
@thetuningspoon I'm not sure this is one I can act upon as I'm not able to duplicate it and it's not been reported before (high traffic sites or others). Though it sounds like it may be related to the server environment in some way or another. 

I'm also running in a AWS environment with load balancer and multiple nodes with a few higher traffic sites, though they are in some kind of cluster where they are sharing the same file system rather than mirroring between nodes. Are multiple file systems involved in your environment? If that's the case, you'd want to be sure they are always acting upon the same exact /site/assets/cache/. If they aren't, I can see that causing an error like this. 

Also double check that your database and server are both on the same timezone (I think AWS is usually UTC). 

In any case, if you don't need file compiler then it's always preferable to disable it unless still transitioning between PW 2.x and 3.x. I personally keep both moduleCompile and templateCompile disabled on production sites that were originally developed in PW 3.x. Though I usually keep it enabled in development sites as I think TracyDebugger still needs moduleCompile, though not certain.

**Comment by elabx** [comment]
I have also experienced this issue with also no clue on how to reproduce it. But I can say almost surely that this has happened to me right after updating content through rsync in Gitlab pipelines. Also I can an almost surely correlate the event with high traffic times too, although I feel my sites aren't really "high traffic".

I deploy on DigitalOcean VPS.

Good to know your workaround @thetuningspoon ! I also had the idea of turning off compiling and adding namespace to old modules and it's great to know it works!

**Comment by BernhardBaumrock** [comment]
--- removed (found the issue in RockMigrations) ---

**Comment by thetuningspoon** [comment]
@ryancramerdesign The filesystem is shared, and /site/assets/cache is common between all web servers. We do occasionally have bottlenecks where that filesystem gets really loaded down, so if sluggishness for writing files into the cache directory could cause this problem, then that might be a reasonable explanation.

The servers are configured for Eastern Time, whereas the RDS database servers are UTC. But we are using $config->dbInitCommand to set the time zone to match each site (different sites are running different time zones), like so:

`$config->dbInitCommand .= ", time_zone='America/New_York'";`

**Comment by BernhardBaumrock** [comment]
I removed my comment because I found the issue in RockMigrations :) In my case the autoloader caused issues after deployment if the DB cache had references to outdated file paths in it.

**Comment by matjazpotocnik** [comment]
@thetuningspoon what's the status of this issue?

**Comment by thetuningspoon** [comment]
No change in status. We disabled the file compiler on the site that was having the issue and we haven't had a problem since.

**Comment by matjazpotocnik** [comment]
Thanks for the update. Do you want to leave this issue open, or should we close it?

**Comment by si-mspooner** [comment]
We can close it since I doubt Ryan will be able to do anything on it until someone else runs into the issue and can perhaps provide further insight.

**Comment by thetuningspoon** [comment]
We can close it since I doubt Ryan will be able to do anything on it until someone else runs into the issue and can perhaps provide further insight.
