### ISSUE TITLE
No ID search possible

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1876]
It is not possible to search for an ID via the PageSearch module in the backend. Neither by simply entering an ID, nor via an explicit selector such as "id=1234" or "pages.id=1234". The ID cannot be added as a search field in the settings either.

PW Version: 3.0.229

**Comment by matjazpotocnik** [comment]
https://processwire.com/talk/topic/23613-search-for-page-id/ 
https://processwire.com/talk/topic/21499-admin-ajax-search-search-by-page-id-number/

**Comment by flipzoom** [comment]
Thanks @matjazpotocnik for the links and the workaround with the hook. 👍🔥

@ryancramerdesign I'm just wondering what exactly is the problem with making the ID configurable as a field for the search? I don't see why a hook should be implemented for this instead of making the ID (optional) searchable. Somehow there is a break in the selector approach in the ProcessWire universe and design pattern for me that you can't search for an ID in the backend search.

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia That's because ProcessPageSearch is a text searching engine, the search input is a live/ajax search "as you type", and so the `=` operator is actually behaving like a `%=` or `*=` operator. If you want to force an exact match, you'd have to use two equals signs. For instance typing `pages.id==1234` will match page having ID 1234.

**Comment by flipzoom** [comment]
Thanks @ryancramerdesign – it seems to be a misunderstanding on my part as well. I had an old version somewhere where `pages.id==1234` didn't work. Since then I had that in my head. But it could also be that I linked the double equals operator incorrectly in my head and had only ever tried with a single one. Anyway: sorry for the ticket. Everything works as it should. Thanks for the link with the hook though.

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign what about adding a shortcut like `#1234` to search for page id?

<img width="459" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/7a2ec8b3-ac59-48dd-950d-9e342187f51e">
