### ISSUE TITLE
Hide pages setting in ProcessPageList doesn't work unless combined with "except" setting

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1879]
### Short description of the issue

ProcessPageList has settings for "Hide these pages in page list(s)" and "Except when (AND condition)".

The issue is the the hide pages setting doesn't work unless one of the except options is also selected.

So with this configuration...

![2024-02-11_111853](https://github.com/processwire/processwire-issues/assets/1538852/d7597294-d42e-4490-9734-7e8543c0e4d5)

..."A basic page" is never hidden in Page List, not for superusers or non-superusers.

If you select one of the "Except when (AND condition)" options then it does work but based on the field labels it's not clear why this would be required.

### Setup/Environment

* ProcessWire version: 3.0.235

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this.

**Comment by Toutouwai** [comment]
Thanks
