### ISSUE TITLE
WireDatabaseBackup::backupPDO() does not handle table columns of data type bit(1) correctly. 

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1881]
### Short description of the issue

A custom module uses a database table including a column of type bit(1).
This leads to the SQL error: '1406 - data too long for column ...' when restoring the database from the backup file created by **WireDatabaseBackup**.

This happens because **WireDatabaseBackup::backupPDO()** places each value in quotation marks without taking the data type into account. In principle, this is unproblematic, with the exception of the **bit(1)** data type.

### Optional: Suggestion for a possible fix

As numerical values do not have to be set in quotation marks, there is a simple solution to the problem. The value should not be enclosed in quotation marks if it is equal to "1".

https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/core/WireDatabaseBackup.php#L872

```
// prevent error if datatype is bit(1), no need to quote numeric values ...
if ($value !== "1") $value = $database->quote($value);
```

### Setup/Environment

* ProcessWire version: 3.0.235

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this. Can you think of any other column types that might have a similar consideration, or is bit unique in this regard?

**Comment by kixe** [comment]
@ryancramerdesign

I don't know if a value of another data type except the (not) value `NULL` or a function (e.g. `CURRENT_TIME()`) would cause an error if valid on its own but quoted.

Beyond functions and `NULL` a value does not need to be quoted anyway if it contains only the ASCII characters:
**[0-9,a-z,A-Z$_]** (basic Latin letters, digits 0-9, dollar, underscore). However, checking this would make the script unnecessarily complicated.

Thanks! Issue can be closed.
