### ISSUE TITLE
FieldtypeRepeater is dumping to Tracy debug bar

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1883]
### Short description of the issue

In [this commit](https://github.com/processwire/processwire/commit/d82194816f0a44df8dee567642b0b3a5cc3c7565) $devMode was set to true and it effectively causes this issue again: https://github.com/processwire/processwire-issues/issues/1474

@ryancramerdesign, if $devMode is just something for when you are testing maybe there's another way to toggle this? For example, rather that changing anything in a core file maybe you could set something in your `/site/config.php`?

### Setup/Environment

* ProcessWire version: 3.0.236

**Comment by matjazpotocnik** [comment]
@Toutouwai https://github.com/processwire/processwire/commit/d5116166d0a075fabd006cbf90fecefb2e21cf35 sets devMode to false again
