### ISSUE TITLE
ProcessLister: selector gets wrongly changed based on user role and it's access to edit the pages in question

### ISSUE THREAD

**Issue by poljpocket** [processwire/processwire-issues#1885]
Associated forum post: https://processwire.com/talk/topic/29706-processlister-problems-with-unpublished-pages-and-edit-access-inheritance/#comment-239447

### Short description of the issue

Selectors with `include=unpublished` get wrongly changed into `include=hidden` and associated error message in Admin when the user has edit access to the template but said access is only given indirectly by inheritance.

A lister bookmark configured with

```'has_parent!=2, template=62, categories=1072, limit=25, sort=-modified, include=unpublished'``` 

works fine on a superuser account but gets changed into

```'has_parent!=2, template=62, categories=1072, limit=25, sort=-modified, include=hidden'```

for non-superusers even though, by edit access inheritance, all the pages returned by the selector are editable by the non-superuser.

#### Thoughts / Background

The behaviour is consistent with the code, so this issue really boils down to the question **if this is intended or actually a bug**. In ProcessPageLister, the `includeMode` gets changed if a simple `editable` check on a temporary page object fails:

Editable check [ProcessPageLister.module#L1164](https://github.com/processwire/processwire/blob/b824f645a9c999fae08858042254da0863fbd883/wire/modules/Process/ProcessPageLister/ProcessPageLister.module#L1164):

```php
foreach($templates as $template) {
    $test = $pages->newPage($template);
    $test->id = 999; // required (any ID number works)
    if($test->editable()) $numEditable++;
}
```

I believe, this doesn't take into account any edit access inheritance on a per-template basis since it can't know which parent pages (there are none!) inherit edit access to the pages returned by the selector.

Error message and includeMode change [ProcessPageLister.module#L1170](https://github.com/processwire/processwire/blob/b824f645a9c999fae08858042254da0863fbd883/wire/modules/Process/ProcessPageLister/ProcessPageLister.module#L1170):

```php
// if all specified templates are editable, include=unpublished is allowed
if($numEditable == count($templates)) {
    // include=unpublished is allowed
} else if($includeMode == 'unpublished') {
    // include=unpublished is not allowed
    if($showIncludeWarnings) {
        $this->resultNotes[] = $this->_("Not all specified templates are editable. Only 'include=hidden' is allowed");
    }
    $includeSelector->value = 'hidden';
    $changed = true;
}
```

### Possible Workaround

Adding direct access control with edit capabilities to the template 62 solves the issue. This makes sense as this way, the editable check can directly determine access.

Another workaround is to set `allowIncludeAll` to true, but this is a possible security risk.

### Thoughts on a fix

I don't know what the performance impact for this could be but the only feasible way to fix this is to look at all the pages returned by the selector (so the lister first needs a dry-run). Only looking at the templates is not possible because they don't necessarily include any information about the page tree and it's access inheritance.

### Setup Info

* ProcessWire version: 3.0.227
* PHP version: 8.2 (probably irrelevant)

**Comment by ryancramerdesign** [comment]
@poljpocket Unfortunately testing edit access for each page individually doesn't work here because Lister needs to paginate among potentially thousands of pages at a time. Meaning it needs to dictate what pages will be loaded by a selector, and not by factors on a page-by-page basis. That way everything can be can be paginated. 

Technically it does test edit access for each page individually (to determine whether to show the 'edit' button), but by that time it knows that all the pages loaded are 'listable' and will be displayed in the Lister. So when it comes to a state like 'unpublished' which always has view/edit restrictions for non-superusers, the best it can do is run a test on a page using that template ahead of time. 

I suppose it could also attempt to load an actual page using that template rather than creating a mock one, which might solve it in some cases, but not all. But if that would be suitable for your case, you could always use a hook to do it:
```php
if($page->process == 'ProcessPageLister') { // or ProcessPageListerPro
  $wire->addHookAfter('Page(id=999)::editable', function($event) {
    $page = wire()->pages->findOne('template=' . $event->object->template);
    if($page->id) $event->return = $page->editable();
  }); 
}
```

**Comment by poljpocket** [comment]
Thanks @ryancramerdesign for the clarification. That's exactly what I expected and it makes perfect sense. It would be illusional to check for all those edge cases. I will try your suggestion.
