### ISSUE TITLE
Repeater inconsistency: empty in page but contains item in admin section

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1888]
### Short description of the issue

In a page using a repeater I add an item to the repeater. This item has one required field 'title' but I don't fill it and try to save the page.
The page is not saved because the required field of the repeater item is not set, but this creates the empty/invalid item in Page Tree > Admin > Repeaters, but when I refresh my page the repeater is empty.
So data in Admin section is not the same as data displayed on the page containing the repeater.

### Expected behavior

The page data should reflect the real data.

I don't know how it's supposed to work when we save a page with an invalid repeater item.
Usually when a field in a page is invalid, the page is saved with an invalid state ( $page->hasStatus(Page::statusFlagged) ), but that's not the case here, this status is true on page and repeater item.

I think the PW standard behavior is to save the invalid item but with the page in an invalid state. Displaying the red or orange notices like with any field.

### Optional: Screenshots/Links that demonstrate the issue

Empty repeater in my page:
![image](https://github.com/processwire/processwire-issues/assets/15386877/d3e809bf-6f3e-4613-89f5-63367d95c2bd)

Real data, there's an invalid item:
![image](https://github.com/processwire/processwire-issues/assets/15386877/623bb94e-49d2-4367-a8b5-04cdc06fd7d4)

### Steps to reproduce the issue

1. Create a repeater field with a required sub-field.
2. Add the repeater to a template.
3. Create a page using this template, save.
4. Add an item to the repeater, don't fill the required field and try to save the page. See that the page doesn't appear to be saved, displaying a popup that we missed a required field.
5. Refresh the page.
6. See that the repeater is empty.
7. Check Page Tree > Admin > Repeaters, and see that the item has been created.

### My use case

I use this repeater to ease page creation for my clients, each item in this repeater will generate a new child page after save. Then the repeater is emptied.
In a beta-test, one of my client had several invalid child pages without title.
I figured out it was caused by this bug, after step 7 (from previous section), if the user save the page, my hook finds an item in this repeater and generates the page without title.
So I have to check if required field are filled before to process repeater item to be sure it's valid.

### Setup/Environment

* ProcessWire version: 3.0.236
* (Optional) PHP version: 8.2

**Comment by ryancramerdesign** [comment]
@hiboudev Repeaters maintain what are called "ready" pages, which are pages that are ready to be used the next time a new item is added. The source of these ready pages is repeater items that were added but never saved. So it's normal for there to be extra unused pages, and Repeater will use them the next time it has an opportunity to do so. If you want to get rid of them, edit your repeater field, click the Details tab, and under the "Repeater Storage" fieldset, check the box to delete old/unused repeater items. Though there's no harm in just leaving them there either.

**Comment by hiboudev** [comment]
@ryancramerdesign Thanks for the tips. I'll test this option in repeater storage.

What looks like an error is that items are not displayed in the repeater while they exist, like a view not displaying the model data.
Because in the end, a hook sees this items so they will be processed, but the user doesn't know it because the repeater appears empty in page.

I imagine you do this to avoid incrementing indexes in DB for nothing?
Can I test in my hook that this item is "old/unused"?

**Comment by ryancramerdesign** [comment]
@hiboudev It's possible you are talking about something different than ready items. A ready item is a RepeaterPage instance that is both unpublished and hidden. You can test for it by calling `$item->isReady()` and it'll return true if it's a ready item. You'd want to skip over such items if you see them in a hook. In terms of the admin, you shouldn't ever see ready items anywhere other than if you navigate to them directly in Pages > Admin > Repeaters. Ready items are removed from formatted repeater values automatically. And InputfieldRepeater skips rendering ready items or doesn't show them, depending on settings.

**Comment by hiboudev** [comment]
@ryancramerdesign Yes, isReady() is what I need in this case, I'll update my repeater hooks with this. Thanks.

Is this documented somewhere? I can't find any API documentation about repeaters: https://processwire.com/api/ref/
Maybe at least you could document this behavior about isReady() on this page: https://processwire.com/docs/fields/repeaters/

This is the kind of behavior that we need to be aware when using hooks with repeaters, this is really hard to find on one's own. :)

**Comment by hiboudev** [comment]
@ryancramerdesign On your side, is it necessary to return repeater items that are not on the page?
It looks really strange to me, and error prone, that when I access a repeater on a specific page, and looping over items, I get items that are not on this page!
