### ISSUE TITLE
Options does not equal, not functioning as expected

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#189]
### Short description of the issue

Options field not respecting the "does not equal" (!=) selector, when other options are empty.

### Expected behavior

Should still select the empty options page as they are still technically not equal. 

### Actual behavior

Returns empty if the options field is empty. 

### Steps to reproduce the issue

1. Create an options field, with multiple options (single select used in my case)
2. Select one of the options for one page, leave the rest as empty
3. Use field.value!=option and it will return nothing, even though technically the other pages do not equal the value.

**Comment by LostKobrakai** [comment]
By now you could use this to get around the issue: `(field.value!=option), (field.value='')`

**Comment by TomS-** [comment]
Thanks lost, however that doesn't work. Even with field.value='' nothing shows.

**Comment by ryancramerdesign** [comment]
Thanks @TomS- I've pushed a fix for this issue. Although I'm not positive what you mean by `field.value=`, don't you mean just `field=`?
