### ISSUE TITLE
SELECT ... FOR UPDATE and likely other locking reads not working with dbReader

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#1890]
In a codebase that makes use of SELECT ... FOR UPDATE (and likely other locking reads, though I haven't tested others) the core WireDatabasePDO class uses reader instance, which results in an exception since the database is in read-only mode.

Seems like something that WireDatabasePDO::pdoType() should and could handle?

More about different locking reads: https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html

**Comment by ryancramerdesign** [comment]
@teppokoivula Thanks, I've pushed a fix for this issue. Though I've not used these locking reads as most of the queries I write have to be compatible across myisam and innodb, so I'm just going by the examples mentioned on the linked page. If you find other queries where the solution doesn't work, please let me know.

**Comment by teppokoivula** [comment]
Awesome, thanks! We'll get to testing likely next week, so I'll leave the issue open until then.

**Comment by matjazpotocnik** [comment]
@teppokoivula, any news on this?

**Comment by teppokoivula** [comment]
Haven't heard back from the team yet, but I'll assume that the fix works, so closing the issue :)
