### ISSUE TITLE
Integer field default value doesn't get set on respective pages when added to template

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1891]
I'm not sure if this is necessarily a bug, but it feels like the current functionality is incorrect.  Here's how to easily test:

Let's say we create an integer field called `myint` and put the "Default Value" as 5.  I then assign that to basic-page template and edit a page and I **visually see** that the value is set to 5.  So I'm assuming the value has actually been set.

If I echo the field in basic-page.php `<?php echo $page->myint; ?>`, nothing comes up.  So it actually hasn't been set.

But, if I save the page in the editor, *then* echoing the field works, meaning I had to save the page for the value to actually be set.

I would have expected the value of the `myint` field to be automatically set to the default value once the field was assigned to the template.

**Comment by jlahijani** [comment]
OK I see that I'm not the first to bring this up and it's not a bug:
https://github.com/processwire/processwire-issues/issues/1797

This modules "solves" the issue:
https://github.com/Toutouwai/FieldInitialValue

**Comment by ryancramerdesign** [comment]
@jlahijani I'll close this one since not technically a bug as the default value is for the Inputfield, not the Fieldtype, and I avoid building in features that won't be practical at larger scale. But I'm glad to see Toutouwai has that module to provide an option. Thanks.
