### ISSUE TITLE
Incorrect @since comment in LazyCron

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1892]
### Short description of the issue

A recent commit added some new methods to LazyCron: https://github.com/processwire/processwire/commit/660ea794963d8ec9cf438f15cc0efbc7ca0d9a54

But the `@since` comment says 3.0.136 when I think it should have been 3.0.236

### Setup/Environment

* ProcessWire version: 3.0.236

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix
