### ISSUE TITLE
WireTextTools::populatePlaceholders() with Option 'removeNullTags' => false fails

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1895]
### Short description of the issue
The function `wirePopulateStringTags($str, $vars, ['removeNullTags' => false])` does not work properly.

If `$vars` is a Page object, every tag with an empty value (string) is removed, even if the option: **removeNullTags** is set to **false**.

Page values are first translated into strings, and the subsequent strict comparison against NULL fails, and the previously set option is ignored.

```
// @see
WireTextTools::populatePlaceholders()

// always returns a string:
Page::getText()
Page::getMarkup()
PageValues::getText()
PageValues::getMarkup()
```

### Suggestion for a possible fix

https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/core/WireTextTools.php#L1027-L1028

```
// if value resolves to empty string and we are not removing empty tags, then do not add to replacements
if(strlen("$fieldValue") == 0) && !$options['removeNullTags']) continue;
```

The option **removeNullTags** in a function that processes strings is misleading anyway. A clearer option would be **removeEmptyTags**, which, if set to true (default), removes all tags with values that are **empty as strings**.

### Setup/Environment

* ProcessWire version: 3.0.236
* (Optional) PHP version: 8.1
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix, and have also added the removeEmptyTags option that you mentioned.

**Comment by kixe** [comment]
Thanks
