### ISSUE TITLE
Image width, height and ratio not updated after rotation

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1896]
### Short description of the issue

I have an image that needs rotation:

![2024-03-12_140806](https://github.com/processwire/processwire-issues/assets/1538852/7853705c-1887-466c-8262-07690ffc6bee)

After I rotate the image using the "Actions" dropdown the image looks as expected but the width, height and ratio values in the database have not been correctly updated:

![2024-03-12_141035](https://github.com/processwire/processwire-issues/assets/1538852/a9608bea-dd31-49db-a422-cf1fcb32ddea)

### Setup/Environment

* ProcessWire version: 3.0.236

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai good find, I've pushed a fix for this.

**Comment by Toutouwai** [comment]
Thanks
