### ISSUE TITLE
"Is not empty" selector for subfield matches pages that do not contain field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1899]
### Short description of the issue

Demoing here with Lister and FieldtypeEvents but I can reproduce the issue with other fieldtypes that contain subfields so I think it's due to some underlying PageFinder problem.

I have a test_events field on a single template that is used for a single page.

![2024-03-22_105341](https://github.com/processwire/processwire-issues/assets/1538852/b94e9ce1-8967-4dd2-acf8-e64dda4fd022)

In Lister if I attempt to match pages where the Title subfield of test_events is not empty then all pages are matched.

![2024-03-22_105542](https://github.com/processwire/processwire-issues/assets/1538852/b4267f1d-abe6-4645-8f28-9e43d265ffd6)

I expected only a single page to be matched, because if a template does not contain the test_events field then how could the subfield be  "not empty"?

### Setup/Environment

* ProcessWire version: 3.0.236

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai It looks like the JS in InputfieldSelector was converting it to a `!field=''` rather than a `field!=''`, I have pushed a fix for that.

**Comment by Toutouwai** [comment]
Thanks
