### ISSUE TITLE
"move" action visible even though sorting not allowed

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1901]
### Short description of the issue

I'm cleaning up my forms module and have a page structure like this:

<img width="772" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/ff25d1d0-9db1-44fa-8ab6-e4dccbb7aaa6">

As you can see there is a "move" action for every saved form entry. The thing is... It is not allowed to sort/move these pages:

<img width="862" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/00f7ace2-97be-4f6f-9d2f-fa96ce4ad44e">

### Expected behavior

Wouldn't it be nice to not show the move action at all if the family setting prevents manual sorting? I guess it's not as easy as in my example, right? Because one could also want to move the page to another parent, which could actually be allowed. Not sure how to tackle this - has there been any discussion about that? I couldn't find anything.

### Workaround

As I'm hiding these pages in the pagetree and only showing them in a custom process module I came up with this workaround:

```css
.PageListTemplate_rockforms_entry .PageListActionLock,
.PageListTemplate_rockforms_entry .PageListActionMove {
  display: none !important;
}
```

<img width="635" alt="image" src="https://github.com/processwire/processwire-issues/assets/8488586/79380e44-063b-4eca-a0e6-9aeb9120bc93">

---

If there is already a way to solve this properly please let me know, thx! :)

**Comment by adrianbj** [comment]
Not sure if this is actually a good idea or not (probably not), but if there was a new sort button that was tied to the sort permission, I wonder if the move button could actually work differently by displaying a popup with an autocomplete field to choose the destination parent. Moving across branches has always been a little frustrating.

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock The "Move" can refer to sorting within the same parent or moving to another parent. But if there are no other potential parents to move to (as a result of allowed parent templates setting), and sorting is automatic, then it's definitely preferable that it doesn't show a "Move" at all. I've pushed a commit that should correct that for many of the cases where it might currently show a Move link.

**Comment by BernhardBaumrock** [comment]
Thx @ryancramerdesign :)
