### ISSUE TITLE
Autojoined page fields are returned in wrong order

### ISSUE THREAD

**Issue by daun** [processwire/processwire-issues#1903]
### Short description of the issue

Page fields with activated `autojoin` return pages unordered, i.e. ordered by id.

### Expected behavior

Pages from an autojoined field should be returned in the order they were saved in the page field, i.e. by the `sort` column. This is how it's been working until a somewhat recent release.

### Actual behavior

Pages are returned in the order of their id, the `sort` column is ignored.

### Ideas where this might stem from

I have a feeling this was introduced in [this commit](https://github.com/processwire/processwire/commit/b85c1c48b06af7630485900cd72793f979487c5e), which in turn was made to fix [this issue](https://github.com/processwire/processwire-issues/issues/1649).

I've noticed the new behavior after upgrading from 3.0.148 to 2.0.236, which would make sense given the changes above.

### Suggestion for a possible fix

Not yet :( Disabling autojoin obviously "fixes" it, but that's not an option given the performance benefits in this specific case.

### Steps to reproduce the issue

1. Create a page reference field with multiple pages and ordered input (AsmSelect or Autocomplete)
2. Activate autojoin on the field
3. Add the field to a template
4. Create a new page, add two separate pages to the field
5. Save the page
6. Reorder the pages, i.e. reverse them
7. Save the page
8. Pages should be stuck in the order of their ids

### Setup/Environment

* ProcessWire version: 3.0.236
* PHP version: 8.2.4
* MySQL version: 5.7.39

**Comment by ryancramerdesign** [comment]
@daun  I was able to duplicate and have pushed a fix for this. In any case, for multi-value page reference fields it's best to avoid using autojoin.

**Comment by daun** [comment]
@ryancramerdesign Thanks for the quick fix! Can confirm this indeed fixes the issue.

I hear you about avoiding autojoin for multi-page fields. In this particular case, it's a complex repeater matrix with two or three pages for each item, and it's noticeably more performant with autojoins.
