### ISSUE TITLE
Inputfield not collapsible unless toggle icon clicked

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#1905]
### Short description of the issue

This issue came up in 2018 already https://github.com/processwire/processwire-issues/issues/536 by @jlahijani
It was said that this is intended behavior, but it was said that it may be revisited at a later point. And it still is quite unintuitive, especially when working with repeaters.

### Expected behavior

When a header of a toggle element is clicked the content should collapse.

### Actual behavior

The tiny down-arrow flashes but the content stays expaned.

### Related code

[wire/templates-admin/scripts/inputfields.js:2146](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/templates-admin/scripts/inputfields.js#L2146)

**Comment by Toutouwai** [comment]
It's configurable in Modules > AdminThemeUikit > Forms + input:

![2024-04-09_093356](https://github.com/processwire/processwire-issues/assets/1538852/39b2fa61-b248-4244-bce5-f4cdeb754993)

**Comment by MrSnoozles** [comment]
Thanks for the super fast reply. Didn't know there was an option to change it.
