### ISSUE TITLE
Page clone unpublished default inconsistency

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#1909]
### Short description of the issue

If you clone a page without children from the "copy" button in the page list, it is cloned as unpublished, but if the page has children it opens the clone dialog page and you need to check the unpublished checkbox, otherwise it is automatically published.

### Expected behavior

Page cloning of pages with children should result in the clone being unpublished by default.

**Comment by Toutouwai** [comment]
@ryancramerdesign, when addressing this could you please also take a look at this related request? https://github.com/processwire/processwire-requests/issues/186

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I agree, I've pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - much better. 

I would also like to see @Toutouwai's suggestion implemented as well though please - I think it's generally nicer to have to explicitly go through the process of naming the copy.
