### ISSUE TITLE
Display “Today” and “Done” buttons under calendar in toggle stays Off

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#1912]
/wire/modules/Inputfield/InputfieldDatetime/types/InputfieldDatetimeText.php, line 50 and 486:

`'showButtonPane' => false, `
`$f->val($module->get('showButtonPane'));`

showButtonPane should be showButtonPane**l** ?.

**Comment by tbba** [comment]
same here
![Bildschirmfoto 82](https://github.com/processwire/processwire-issues/assets/652879/1a267685-b0b1-4e0e-ba83-7bd82921e363)

**Comment by tbba** [comment]
Any progress? This is hurting a lot!

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/processwire/processwire/commit/2690115966b2b07dd2aef61edf04920ad358dc56

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Good catch, thanks, I meant to commit that separately
