### ISSUE TITLE
Going to example.com/trash/ gives a warning

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1917]
I somehow ended up on example.com/trash/ (example.com being any ProcessWire site).

Going there shows "This page has no process assigned." which is right, but it also shows this warning in TracyDebugger:
```
Warning: Uninitialized string offset 0 in example.com/vendor/composer/ClassLoader.php:497
```

**Comment by ryancramerdesign** [comment]
@jlahijani You should see a "no process assigned" message if you happen to be logged in. Otherwise you should see a 404. The Tracy warning message appears to be coming from a file that is not part of ProcessWire, so I don't think I have the ability to fix that one.

**Comment by jlahijani** [comment]
You are right.  I had a separate hook causing this.
