### ISSUE TITLE
Error: Call to a member function editUrl() on null

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1918]
### Short description of the issue

A recent commit on the dev branch causes error "Call to a member function editUrl() on null" at /processwire/module/

![2024-05-07_153123](https://github.com/processwire/processwire-issues/assets/1538852/0c84eb20-53e8-4109-9604-d12801ef3839)

### Setup/Environment

* ProcessWire version: 3.0.238

**Comment by ryancramerdesign** [comment]
@Toutouwai What's the environment where you are seeing it? Is it in the page editor or outside of it?

**Comment by adrianbj** [comment]
@ryancramerdesign - it's when you click on the "Modules" menu item in the PW admin, hence the `/processwire/module/` path noted above.

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks, I was able to duplicate that after setting `$config->moduleInstall('upload', 'debug');` in /site/config.php, and then viewing the Modules page. I've pushed a fix.
