### ISSUE TITLE
AdminThemeUikit main.min.js is never used

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#1920]
I'm not sure if this if this is a bug or a conversation, but I noticed in AdminThemeUikit [`_head.php`](https://github.com/processwire/processwire/blob/dev/wire/modules/AdminTheme/AdminThemeUikit/_head.php#L32) never actually loads main.min.js (just main.js).

**Comment by jlahijani** [comment]
Unrelated, but I am wondering what tool you use to minify JS when developing ProcessWire?

**Comment by ryancramerdesign** [comment]
Thanks @jlahijani I've pushed a fix for this. I don't manually minify the core JS as PhpStorm seems to do it automatically. I think it uses uglifyjs, but not certain.
