### ISSUE TITLE
When settings tab of template is disabled, lock status is not respected

### ISSUE THREAD

**Issue by kiwigringo** [processwire/processwire-issues#1930]
### Short description of the issue

When the settings tab of a template is disabled either through UI in advanced mode, or via third party module, changes to a locked page can be saved.

### Expected behavior

Attempting to save a locked page should generate a warning, and changes should not save.

### Actual behavior

Locked page saves as if it were unlocked.

### Steps to reproduce the issue

1. On the Sytem Tab of a template in advanced mode, check disable settings tab
2. Create a page from the template.
3. Set the status of the page to locked (in tree view or lister - obviously not available via settings)
4. Edit the page and attempt to save.
5. Edit the template again and uncheck disable settings tab.
6. Attempt to edit and save page. (Page shouldn't save).

### Setup/Environment
* ProcessWire version: 3.0.238 (and older)
* (Optional) PHP version: 8.0.30
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Same behaviour is exhibited with RestrictTabView module if it is installed and settings tab is hidden via module.

**Comment by ryancramerdesign** [comment]
@kiwigringo Thanks, I've pushed a fix for this. You mentioned via 3rd party module, and I don't know which one that would be or how it works, so if you are able to, please test that 3rd party module with this update.

**Comment by adrianbj** [comment]
@ryancramerdesign - he noted the use of my RestrictTabView module.

**Comment by kiwigringo** [comment]
I've tested and can confirm this works now both through the built-in system tab in template config, and Adrian's third party module.

**Comment by ryancramerdesign** [comment]
@kiwigringo Great! Thanks for testing it out.
