### ISSUE TITLE
PHP 8.2 - depreciated htmlspecialchars in Inputfield.php

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#1931]
PHP Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /wire/core/Inputfield.php

(PW Dev latest)

**Comment by ryancramerdesign** [comment]
Thanks @tbba I've pushed a fix for this.

**Comment by matjazpotocnik** [comment]
@tbba, closing.
