### ISSUE TITLE
Duplicate values in installer config

### ISSUE THREAD

**Issue by designconcepts** [processwire/processwire-issues#1936]
### Short description of the issue

After a fresh installation of PW 3.0.239 there are duplicate values in the installer config section of the config.php file.

### Expected behavior

Every config value in the installer config section should be unique.

### Actual behavior

The database configuration, user authentication salt and table salt have duplicates.

### Optional: Screenshots/Links that demonstrate the issue

<img width="628" alt="Bildschirmfoto 2024-06-06 um 15 38 30" src="https://github.com/processwire/processwire-issues/assets/2794879/1e8b4ac4-9262-4b43-8d3a-91991abb9315">

### Steps to reproduce the issue

1. Download PW 3.0.239
2. Install PW 3.0.239
3. Check the config.php

Regards, Andreas

**Comment by ryancramerdesign** [comment]
@designconcepts Which site profile are you installing where you see the duplication?

**Comment by matjazpotocnik** [comment]
@ryancramerdesign install.php, line 921, 922, double `$cfg .=`

**Comment by designconcepts** [comment]
@ryancramerdesign Just the blank profile. 😉

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik @designconcepts -- fixed!
