### ISSUE TITLE
ProcessPageEdit module fatal error - when trying to edit on admin

### ISSUE THREAD

**Issue by sevenstudio** [processwire/processwire-issues#1937]
ProcessWire 3.0.239
PHP 8.1.10

I was testing latest DEV version and while trying to access  setup -> configure -> ProcessPageEdit for a edit I'm getting fatal error:

Fatal Error: Uncaught Error: Call to a member function get() on null in \wire\modules\Process\ProcessPageEdit\ProcessPageEdit.module:3476

This is a localhost server where I have few installations based on 3.0.225, no issues there.

**Comment by matjazpotocnik** [comment]
@sevenstudio, can you edit ProcessPageEdit.module and replace lines 3468-3470:

```
$config = $this->config;
$pages = $this->pages;
$modules = $this->modules;
```

with:

```
$config = $this->wire()->config;
$pages = $this->wire()->pages;
$modules = $this->wire()->modules;
```

**Comment by sevenstudio** [comment]
@matjazpotocnik thanks, it works correctly now. I see that older installations were using $this->wire() (at least 3.0.225 that I have on hand), not sure since when this has been changed. Could you please create PR for this?

**Comment by matjazpotocnik** [comment]
It's changed in [this commit](https://github.com/processwire/processwire/commit/b9d8a741ee053260d540d93a5749e9a104d0d3e5)

No need for PR, Ryan will fix it soon.

**Comment by sevenstudio** [comment]
Great, I will close this one in this case. Thanks a lot for your contribution.

**Comment by matjazpotocnik** [comment]
I reopened it and will close it when it is fixed.

**Comment by matjazpotocnik** [comment]
fixed in https://github.com/processwire/processwire/commit/abe1216c8976444c53018ede024ea6c45c0d3924
