### ISSUE TITLE
Markup Regions Docs: pw-append="id" example in "Adding HTML attributes" is wrong.

### ISSUE THREAD

**Issue by lemachinarbo** [processwire/processwire-issues#1939]
### Short description of the issue

Using  the region action `<ul pw-append="mylist" class="bar">hello</ul>` doesn't merge the class, and appends the whole region action tag, instead of the `hello`, into the region definition. Probably the same as described in  #302 and https://processwire.com/talk/topic/17309-markup-regions-add-class-without-replacing-content/?do=findComment&comment=152062

### Expected behavior

Having a region definition in *_main.php*:
```html
<ul pw-id="mylist" class="foo">
    <li>One</li>
</ul>
```
And a region action in *basic_page.php*:
```html
<ul pw-append="mylist" class="bar">
  <li>Two</li>
</ul>
```

The output expected was:
```html
<ul pw-id="mylist" class="foo bar">
    <li>One</li>
    <li>Two</li>
</ul>
```

### Actual behavior
The whole action tag was included inside the region:
```html
 <ul class="foo">
    <li>One</li>
    <ul id="mylist" class="bar">
        <li>Two</li>
    </ul>
</ul>
```
But if, instead of `pw-append="mylist"`, we use:
```html
<ul id="mylist" class="bar" pw-append>
    <li>Two</li>
</ul>
````
The output is correct:
```html
<ul class="foo bar">
    <li>One</li> 
    <li>Two</li>
</ul>
```
### Setup/Environment
* ProcessWire: 3.0.239
* Procache 4.0.5 (disable)

**Comment by Toutouwai** [comment]
I think it's working correctly. See this closed issue for an explanation: https://github.com/processwire/processwire-issues/issues/677

**Comment by lemachinarbo** [comment]
Thanks @Toutouwai I missed that! 

So isn't an issue at all, but if I understood correctly, [the markup regions docs](https://processwire.com/docs/front-end/output/markup-regions/), need to be updated. 

```
Adding HTML attributes

When using action attributes with value, along with a replace, 
prepend or append action, any HTML attributes you add to the
action tag that do not begin with pw- or data-pw- will be added 
to the originally defined region tag. Meaning, you can add new 
attributes in the region definition tag. 
Lets say that you've got this region defined in your 
/site/templates/_main.php file…

<ul id="foo" class="bar">
  <li>First item</li>
</ul>
…and you've got this in your /site/templates/basic-page.php template file:

<ul pw-append="foo" title="Hello">
  <li>Second item</li>
</ul>
The final output would be this:

<ul id="foo" class="bar" title="Hello">
  <li>First item</li>
  <li>Second item</li>
</ul>
```

That example produces:
```html
<ul id="foo" class="bar">
  <li>First item</li>
  <ul title="Hello">
    <li>Second item</li>
  </ul>
</ul>
```

**Comment by Toutouwai** [comment]
@lemachinarbo, yes, good spotting. The section of the docs that explains action attributes with value and boolean action attributes does correctly describe the difference between them, but that example you highlighted is wrong.

**Comment by lemachinarbo** [comment]
@Toutouwai must I keep this "issue" open? is there another place to report docs issues?

**Comment by Toutouwai** [comment]
Yes, keep it open I think as then @ryancramerdesign will notice it and update the docs.

**Comment by ryancramerdesign** [comment]
@lemachinarbo @Toutouwai @matjazpotocnik Sorry for the error, I've fixed the docs for that. Thanks!
