### ISSUE TITLE
wireClassName will prevent any non namespaced class names to be used as pageClass

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#194]
### Short description of the issue

wireClassName($class, true) will return classes with the added ProcessWire\ prefix even if it isn't a class that should receive the namespace. 

### Expected behavior

Return correct class names.

### Actual behavior

E.g. the dynamic roles module does not work, because the un-namespaced DynamicRoles class will be mapped to a non-existing ProcessWire\DynamicRoles class.

### Optional: Screenshots/Links that demonstrate the issue

<img width="1086" alt="screenshot 2017-02-21 20 16 24" src="https://cloud.githubusercontent.com/assets/2489835/23180719/a8554a78-f872-11e6-8b94-08337c6dded3.png">

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Dynamic Roles (0.0.7)

**Comment by LostKobrakai** [comment]
```diff
--- wire/core/Functions.php
+++ wire/core/Functions.php
@@ -654,7 +654,7 @@
 	
 	if($withNamespace === true) {
 		// return class with namespace, substituting ProcessWire namespace if none present
-		if($pos === false && __NAMESPACE__) $className = __NAMESPACE__ . "\\$className";
+		if(!class_exists($className) && $pos === false && __NAMESPACE__) $className = __NAMESPACE__ . "\\$className";
 		
 	} else if($withNamespace === 1) {
 		// return namespace only

```

**Comment by ryancramerdesign** [comment]
Thanks,  I've pushed a fix for this. The wireClassName() function is actually working how it's supposed to (it's not meant to get into checking whether things exists), but it was an error nevertheless, in PagesLoader::getById() instead.
