### ISSUE TITLE
wirePopulateStringTags() loses custom file/image fields when they are duplicated

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1941]
### Short description of the issue

I'm using a text formatter for page images that populates image properties and custom image fields via **wirePopulateStringTags()**. For all default properties, it doesn't matter if they are present multiple times in the string to be replaced, but if I do the same with custom fields, some are lost.

### Expected behavior

All tags should be populated, even if duplicated.

### Actual behavior

**Example**
`echo wirePopulateStringTags($string, $pageimage);`

**Results**
```
// usage with default Pageimage properties: works as expected
$string = "1={description}, 2={filesize}, 3={description}, 4={description|filesize}, 5={filesize|description}, 6={width|height}, 7={height|width}, 8={height}, 9={width}, 10={description|width|height}";

// usage with mixed custom fields and default properties: missing 3d, 4th, 5th and 7th item
$string = "1={description}, 2={description|image_creator}, 3={image_creator}, 4={image_creator}, 5={image_creator}, 6={image_alt|image_creator}, 7={image_alt}, 8={description}";
```

### Setup/Environment

* ProcessWire version: 3.0.239
* (Optional) PHP version: 8.2

**Comment by ryancramerdesign** [comment]
@kixe I think the issue might be that Pagefile doesn't support `a|b` syntax for getting custom field values. But looks like it's a simple matter to support, so I have added it. Can you confirm this fixes the issue?

**Comment by kixe** [comment]
@ryancramerdesign
Thanks. Fixed.
