### ISSUE TITLE
3.0.240 --uk-animation-stroke not resolved

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1943]
Just updated to 3.0.240 and PHP Storm shows error in uikit distribution: --uk-animation-stroke is not resolved.

![image](https://github.com/processwire/processwire-issues/assets/15386877/5f26f752-8cb7-455e-b54b-1d576a3eab36)

**Comment by ryancramerdesign** [comment]
@hiboudev We're just using Uikit as provided by the developer, and everything compiles normally. I prefer not to modify Uikit itself. Like you, I've noticed PhpStorm inspections often flag stuff in Uikit (and other libraries), and I think it's more to do with PhpStorm inspections configuration than with Uikit. I would turn off those inspections or ignore them.
