### ISSUE TITLE
Layout issues in InputfieldFile

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1944]
### Short description of the issue

A couple of minor layout issues with InputfieldFile...

1\. Note the extra space between the label and the description compared to other inputfield types.

![2024-06-29_104013](https://github.com/processwire/processwire-issues/assets/1538852/72ff06af-31e2-4ed5-aa65-de99d1eea2e0)

2\. Note how after upload the file list is between the label and the description, but after save the file list is below the description (where it should be).

![if](https://github.com/processwire/processwire-issues/assets/1538852/02ca9b94-37bf-465a-825b-334b6a9bf324)

### Setup/Environment

* ProcessWire version: 3.0.240

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this.
