### ISSUE TITLE
float field is rounded when rounding is disabled

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1949]
Field should not be rounded:
![image](https://github.com/processwire/processwire-issues/assets/15386877/5b572db5-1caf-4606-9d88-5cb590973db0)

I set a value via code or admin: 2387.04123456
and value recorded in database is: 2387.04

* ProcessWire version: 3.0.240
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@hiboudev I can't duplicate that here. The value `2387.04123456` saves correctly and remains here. Are you using a FieldtypeFloat field (what I'm using), or using the InputfieldFloat with some other field type?

**Comment by hiboudev** [comment]
@ryancramerdesign I did another test, inserting directly in database and I see the same rounding, and here is the solution: https://stackoverflow.com/a/62515384
If I set the type double to this field, it saves correctly the decimal value.
My database was created by ProcessWire, so why do we have a difference? Because I'm using InnoDB? What is the type in your database?
This is the configurations PW created:

![image](https://github.com/processwire/processwire-issues/assets/15386877/a593168c-0d6e-4c03-b1e8-5f3ae1c4c1b7)

![image](https://github.com/processwire/processwire-issues/assets/15386877/8faf87a6-35ca-4a6f-a546-fbbeaa93b276)

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, I can confirm what @hiboudev is experiencing - the value is truncated. My table/fields uses MyISAM engine and utf8_general_ci Collation. As soon I change the data type to double, the value is shown as it should, not truncated.

**Comment by hiboudev** [comment]
@ryancramerdesign In FieldtypeFloat, this 'float NOT NULL' should be a  'double NOT NULL'.
```
public function getDatabaseSchema(Field $field) {
  $schema = parent::getDatabaseSchema($field); 
  $schema['data'] = 'float NOT NULL';
  return $schema;
}
```

**Comment by matjazpotocnik** [comment]
@hiboudev, this issue should be fixed in https://github.com/processwire/processwire/commit/6e93844c19387e137b4900fab8b990a898f963bc (PW 3.0.241). Can you confirm?

**Comment by matjazpotocnik** [comment]
@hiboudev I'm closing this issue; reopen it if Ryan's fix isn't working for you.
