### ISSUE TITLE
Creating a page does not add a row to pages_parents table

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1956]
### Short description of the issue

I noticed that no new row is added to the pages_parents table when a page is added and published.

In a clean installation of PW 3.0.240...

Page with ID 1019 is added and published:

![2024-08-08_123726](https://github.com/user-attachments/assets/0a742098-136a-4d4f-846b-3c26c1cc12bd)

pages_parents table afterwards (note that there is no row for page ID 1019):

![2024-08-08_123811](https://github.com/user-attachments/assets/f788d5b9-d36f-4ada-a985-62ae776bf8c3)

If I add a child page to this newly created page there is no row for that child page either.

I don't understand exactly how the pages_parents table is used, but it looks like it's important for the functioning of the PagesParents class so I wanted to check if it's meant to be added to as pages are created.

### Setup/Environment

* ProcessWire version: 3.0.240

**Comment by ryancramerdesign** [comment]
Having every page in the pages_parents table isn't necessary. The pages_parents table should just have pages_id columns for pages that themselves have children.

**Comment by Toutouwai** [comment]
Thanks for the explanation.
