### ISSUE TITLE
Broken link in InputFieldCKEditor README.md

### ISSUE THREAD

**Issue by gRegorLove** [processwire/processwire-issues#1960]
### Short description of the issue
The PW admin links to [these instructions](https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldCKEditor/README.md#custom-editor-js-styles-set) and the "ready-to-go mystyles.js" link there is 404.

### Steps to reproduce the issue

1. Edit a textarea field like "body"
2. Select the "Input" tab
3. Scroll to "Custom Editor JS Styles Set"
4. Click the "Instructions" link in the field's description text
5. Click the "ready-to-go-mystyles.js" link

### Setup/Environment

* ProcessWire version: 3.0.200

**Comment by ryancramerdesign** [comment]
Thanks @gRegorLove I've pushed a fix for that
