### ISSUE TITLE
Icon in item header gets replaced by fa-arrows when closing/opening

### ISSUE THREAD

**Issue by romaincazier** [processwire/processwire-issues#1962]
### Short description of the issue

When using `icon-name` to add an icon in a repeater item header, it gets replaced by `fa-arrows` when closing/opening because of [InpufieldRepeater.js#L457](https://github.com/processwire/processwire/blob/80f425f9da46b3ab2a8c315f3e1d5b0c9b2fb801/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.js#L457)

### Suggestion for a possible fix

Check for the presence of the attibute `data-icon` and replace accordingly

**Comment by ryancramerdesign** [comment]
Thanks @romaincazier I've pushed a fix for this
