### ISSUE TITLE
InputfieldSelector preview does not show strings that are HTML tags

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1965]
### Short description of the issue

There seems to be an entity encoding issue with selector preview of InputfieldSelector.

In the screenshot the selector preview should be `title*=basic, body*="<strong>"`, but the `<strong>` is invisible because it's being displayed as HTML instead of text.

![2024-09-03_120727](https://github.com/user-attachments/assets/c8b6c588-5423-474d-a067-854339126281)

### Setup/Environment

* ProcessWire version: 3.0.241

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for that.
