### ISSUE TITLE
RepeaterMatrix Item header {images.count} causes statusCorruptedFields

### ISSUE THREAD

**Issue by Rayden** [processwire/processwire-issues#197]
### Short description of the issue

A Repeater Matrix item with an `images` field and an item header with value `{images.count}` displays the number of images as label of the regarding item. 

This goes well when adding a new repeater matrix item and assigning images to it. 

It breaks saving the repeater matrix item when editing the specific repeater matrix item on two occasions: 

(1) modifying an image description field causing an error regarding output formatting / Page:statusCorrupted, 

and 

(2) when assigning new images to it (with our without description) causing the new image not being assigned to the repeater matrix item (unset:images), altough its uploaded correctly to the files folder.

### Expected behavior

I would expect it to save the new images that where assigned when editing an existing repeater matrix item, and/or save the modified image description. (This works fine when removing {images.count} from the repeater matrix item header.)

### Actual behavior

As mentioned above, saving the page after editing a repeater matrix item with images, where new images where assigned or image description was modified. It will throw an error (after modifying an image description) or remove (unset) the image from the repeater matrix item (while still existing in the files folder)

### Optional: Screenshots/Links that demonstrate the issue

Sorry, no screenshot, just the Session messages after modifying an image description and assigning an new image to the already existing repeater matrix item:

Session: Saved Repeater /processwire/repeaters/for-field-140/for-page-4683/1487968207-6603-1/ (unset:images, images, status, _statusCorruptedFields)

 Session: Error saving field "repeater_matrix_content" - Can't save page 4685: /processwire/repeaters/for-field-140/for-page-4683/1487968207-6603-1/: Call $page->setOutputFormatting(false) before getting/setting values that will be modified and saved. [Page::statusCorrupted] fields: images

### Steps to reproduce the issue

1. Create an images field with the name `images` and allow description
2. Create a repeater matrix field named `repeater_matrix_content`
2. Add a new type to it and name it `photos` and label `Photos`
3. Assign the images field (with the name images) to the just added repeater matrix type
4. Set the following value to the Item headers field: {matrix_label} [• {images.count}]
5. Assign the repeater matrix field to a template.
6. Add a new page with the regarding template
7. Add a new repeater matrix item
8. Assign atleast 1 image to it 
9. Save the page
10. The Label should now read "Photos • 1"
11. Edit the regarding repeater matrix item
12. Modify the image description by adding some text to it.
13. Assign an new image to it, so the total is 2 images
14. Save the page

### Setup/Environment

* ProcessWire version: 3.0.52
* No further custom modules installed, i reproduced this issue on a clean install

**Comment by rdunk** [comment]
I'm also encountering this, although in my case I am referencing the field itself with {matrix_label} • {images}.

**Comment by ryancramerdesign** [comment]
@Rayden Thanks, I've pushed a fix for this issue. 

@rdunk you probably aren't going to be able to use a field like {images} in a label, but you should be able to use {images.count} like Rayden did (that's what we fixed).
