### ISSUE TITLE
ProcessPageLister CSS causes unwanted scrollbar

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1975]
### Short description of the issue

I'm using ListerPro here as a convenient way of adding modal editing to pages in Lister, but the problem is with CSS in the core ProcessPageLister.

I have filters set to show pages where there is 1 item in the `image` field.

![2024-09-19_133136](https://github.com/user-attachments/assets/6d9ae627-8c9c-432f-b07d-08cdfbd997fe)

I open one of the pages for modal editing and delete the image, so the page no longer matches the filter and automatically drops out of the Lister results. This causes an unnecessary and unwanted scrollbar in the results table.

![2024-09-19_133205](https://github.com/user-attachments/assets/a3397a55-4d9e-4cdd-aac9-c7f5255fb065)

This is caused by [this rule](https://github.com/processwire/processwire/blob/fef2a76f391bb1250af56ff6caa7f26fdfe9fc6a/wire/modules/Process/ProcessPageLister/ProcessPageLister.scss#L22) in the ProcessPageLister CSS.

No overflow rule should be needed for this div, as by default it will expand and contract to fit its contents. Removing the overflow rule fixes the problem.

### Setup/Environment

* ProcessWire version: 3.0.241

**Comment by ryancramerdesign** [comment]
@Toutouwai If I recall, that overflow-x was necessary when the table could not horizontally physically fit in the viewport. So the rule would make just the table horizontally scrollable, rather than the entire page. I'm not sure why it's causing a vertical scrollbar, but maybe adding an `overflow-y:visible` rule would be an alternative?

**Comment by Toutouwai** [comment]
> maybe adding an overflow-y:visible rule would be an alternative?

It would be great if that worked but unfortunately it doesn't: https://stackoverflow.com/a/6433475/1036672

I think I'll just override the overflow in custom CSS because the unwanted vertical scrollbar affects my clients more often than the lack of a horizontal scrollbar (and you can use the window scrollbar to reveal any horizontal overflow anyway). But other PW users may not feel the same so perhaps best to leave the core as it is.

**Comment by Toutouwai** [comment]
Actually, the unwanted scrollbar disappears as soon as there is a window resize, as presumably this forces the browser to recalculate the div dimensions and it realises that there is no vertically overflowing content.

So could we add this line after [line 309](https://github.com/processwire/processwire/blob/1c0aa2d2486f9ef141092783f54077131f5d14e4/wire/modules/Process/ProcessPageLister/ProcessPageLister.js#L309) in ProcessLister.js?
```js
window.dispatchEvent(new Event('resize'));
```
For me this resolves the issue.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have added your suggested fix for this.
