### ISSUE TITLE
FieldtypeCombo getSubfields() issue when in RepeaterMatrix () 

### ISSUE THREAD

**Issue by flihub** [processwire/processwire-issues#1979]
### Short description of the issue

add combofield  to repeater matrix.  If repeater matrix item has no images field Combofields gives error when try to select images from TinyMCE field.

"Fatal Error: Uncaught Error: Call to a member function getSubfields() on null." 
block2 has no button field but block2 tries to get block1->button getSubfields().  The problem occurs here.

### Optional: Screenshots/Links that demonstrate the issue

![image](https://github.com/user-attachments/assets/8efcfa56-791c-4751-9a97-b1dd37433212)
![image](https://github.com/user-attachments/assets/dec747a2-1ab3-4c74-8e28-ee1dd11541b8)
![image](https://github.com/user-attachments/assets/c8a99226-4550-4d92-be4f-ed09e7a9b16e)

### Setup/Environment
ProcessWire 3.0.229 (works)
ProcessWire 3.0.241

**Comment by ryancramerdesign** [comment]
@flihub I'm not clear on the source of the error message, was there a filename/line number as part of that error message? Usually fatal error messages include that info.

**Comment by flihub** [comment]
```php
Fatal Error: Uncaught Error: Call to a member function getSubfields() on null in E:\Laragon\www\protest\site\modules\FieldtypeCombo\FieldtypeCombo.module:1442

#0 E:\Laragon\www\protest\wire\modules\Process\ProcessPageEditImageSelect\ProcessPageEditImageSelect.module(479): FieldtypeCombo->getPageimages(Object(RepeaterMatrixPage), Object(ComboField))
#1 E:\Laragon\www\protest\wire\modules\Process\ProcessPageEditImageSelect\ProcessPageEditImageSelect.module(457): ProcessPageEditImageSelect->getImages(Object(RepeaterMatrixPage), Object(Fieldgroup), 1)
#2 E:\Laragon\www\protest\wire\modules\Process\ProcessPageEditImageSelect\ProcessPageEditImageSelect.module(553): ProcessPageEditImageSelect->getImages(Object(Page), Object(Fieldgroup))
```

**Comment by ryancramerdesign** [comment]
@flihub I think that would match up with this line in FieldtypeCombo.module
~~~~
$subfields = $comboSettings->getSubfields();
~~~~
I'm replacing it with this:
~~~~
$comboSettings = $comboValue->comboSettings;
if(!$comboSettings) return [];
$subfields = $comboSettings->getSubfields();
~~~~
