### ISSUE TITLE
Deprecated: Constant E_STRICT is deprecated in PHP8.4

### ISSUE THREAD

**Issue by jefhar** [processwire/processwire-issues#1980]
### Short description of the issue

Constant E_STRICT is unused after PHP 5.x except for 2 special cases, and [is deprecated in PHP 8.4](https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant).

### Expected behavior

Constant `E_STRICT` is removed from all PHP code PHP > 5.6

### Actual behavior

Constant `E_STRICT` exists.

### Optional: Screenshots/Links that demonstrate the issue

https://github.com/processwire/processwire/blob/6cd8516a6f398317250fe75a35418f38ff19509d/wire/core/ProcessWire.php#L291
https://github.com/processwire/processwire/blob/6cd8516a6f398317250fe75a35418f38ff19509d/wire/core/ProcessWire.php#L452
https://github.com/processwire/processwire/blob/6cd8516a6f398317250fe75a35418f38ff19509d/wire/core/WireShutdown.php#L161

### Optional: Suggestion for a possible fix

Remove `E_STRICT` uses.

### Steps to reproduce the issue

1. Install PHP 8.4
2. Install ProcessWire
3. Load a page.

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 8.4

**Comment by ryancramerdesign** [comment]
Thanks @jefhar I've pushed an update to remove E_STRICT.
