### ISSUE TITLE
$sanitizer->fieldName() with beautify true does not trim redundant separators

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1983]
### Short description of the issue

In most `$sanitizer` methods that accept a `beautify` option, when this is true it trims redundant separators between words. But this is not happening for `$sanitizer->fieldName()`.

![2024-10-30_113858](https://github.com/user-attachments/assets/b1b194d5-1242-4c8a-b0bb-927d39224ba0)

### Setup/Environment

* ProcessWire version: 3.0.241

**Comment by ryancramerdesign** [comment]
The pageName() sanitizer has its own beautify behavior, which is quite a bit more thorough than that used by fieldName() and others. In the case of fieldName, the beautify focuses more on leading and trailing characters, and translating non ascii.

**Comment by Toutouwai** [comment]
Okay. It means there's no one sanitizer for what I think is a pretty common use case, where you want the result to be words (with character translation) separated by a single underscore. But it's no big deal to combine two sanitizer methods:

```php
$out = $sanitizer->snakeCase($sanitizer->pageName($in, Sanitizer::translate));
```
