### ISSUE TITLE
Page Reference option label incorrect if page title starts with "less than" character

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1984]
### Short description of the issue

The selectable pages for the Page Reference field:

![2024-10-30_180500](https://github.com/user-attachments/assets/40e4023e-b5e2-484d-bf44-11f127942eca)

The Page Reference field settings:

![2024-10-30_180555](https://github.com/user-attachments/assets/48e984cc-c05d-4c16-90eb-9f5e05f63d1d)

Page Edit:

![2024-10-30_180620](https://github.com/user-attachments/assets/4f690efb-0dc5-442b-a6b2-d3a170e80f64)

### Setup/Environment

* ProcessWire version: 3.0.241

**Comment by Toutouwai** [comment]
The problem is with a $sanitizer method and occurs here: https://github.com/processwire/processwire/blob/6cd8516a6f398317250fe75a35418f38ff19509d/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L636

Temporary workaround:
```php
$wire->addHookBefore('InputfieldPage::renderPageLabel', function(HookEvent $event) {
    $event->arguments(1, true);
});
```

**Comment by ryancramerdesign** [comment]
@Toutouwai This is coming from PHP's strip_tags() function. It apparently thinks a single greater than sign is safe, but a less than sign followed by a letter or number is not. I'm not qualified to second guess its logic, so I think the best bet is to give it something that it will leave alone. It won't strip a `<` followed by a regular space, so I experimented with inserting zero-width and narrow-width spaces after the `<` but wasn't able to fool strip_tags with that. What I was able to do is replace the `<` with a UTF8 character that looks a bit like it `≺` , and then it will leave it alone. Not a perfect solution, but the best I can think of for now.

**Comment by Toutouwai** [comment]
@ryancramerdesign, unless I'm overlooking something I don't think there will be anything that strip_tags() needs to remove if the string doesn't contain a closing angle bracket. So could [this](https://github.com/processwire/processwire/blob/af5cbd7e3ccdc260aa3ab087da2f9b8c1bc09858/wire/core/Sanitizer.php#L2007) part be changed to:
```php
if(strpos($value, '>') !== false) {
    // remove tags
    $value = trim(strip_tags($value));
}
```
Although that still doesn't solve the issue for a label like "<5 but >2"

**Comment by Toutouwai** [comment]
@ryancramerdesign, is `sanitizer->markupToLine()` in `renderPageLabel()` for aesthetic rather than security reasons? Because when the sanitizer isn't used (e.g. when `$allowMarkup` is true) the label is still entity encoded so HTML doesn't get interpreted in the label.

![2024-11-02_123156](https://github.com/user-attachments/assets/9e4c753c-0841-4e89-b24a-21962ffba6f6)

**Comment by ryancramerdesign** [comment]
@Toutouwai Unless the `<` is followed by whitespace, strip_tags() still strips even just a single `<` without a closing `>`.

**Comment by Toutouwai** [comment]
I'll just use the hook from my earlier post, as there doesn't seem to be any downside to it that I can see.
