### ISSUE TITLE
PHP warnings ProcessPageEditLink

### ISSUE THREAD

**Issue by flipzoom** [processwire/processwire-issues#1993]
### Short description of the issue

I don't know if this has already been reported, but in PW Main 3.0.229 The following PHP warning appears within repeaters:

![image](https://github.com/user-attachments/assets/b9470b4d-7870-45cb-864b-7034c5774d40)

**Comment by ryancramerdesign** [comment]
@flipzoom I can't seem to duplicate it here. Though 3.0.229 is more than a year old, so I'm guessing this has been fixed on the dev branch.

**Comment by matjazpotocnik** [comment]
@flipzoom the only diff between PW 3.0.218 (just happened to have this version on my computer) and PW 3.0.242 is that the getFilesPage() method is hookable. Could you debug why $page->template->fieldgroup is null?

**Comment by flipzoom** [comment]
So first of all: the warnings are no longer present in PW 3.0.242.

Out of interest, I have nevertheless debug and checked where the problem comes from. Only in a weird constellation:

- A RepeaterMaxtrixField named "Content" has two inputs of type FieldsetPage, let's call them "Column 1" and "Column 2".
- A Maxtrix type named "A" has only one of the two FieldsetPage assigned, a second Maxtrix type named "B" has both assigned. Both Maxtrix types A and B have an input field CKEditor.
- ProcessPageEditLinks searches for file fields in all page types. In the first matrix type, however, "Column 2" is not assigned and yet an attempt is made to access "Column 2" in the context. However, this is only a NullPage.

This resulted in the warning. Perhaps a check should still be carried out at this point to ensure that Page is not a NullPage, just to avoid such strange constellations in future? What do you think? @matjazpotocnik @ryancramerdesign

**Comment by flipzoom** [comment]
The scheme again:

- RepeaterMaxtrixField (Content)
  - MatrixType A
    - Text (Inputfield CKEditor)
    - Column 1 (FieldsetPage)
  - MatrixType B
    - Text (Inputfield CKEditor)
    - Column 1 (FieldsetPage)
    - Column 2 (FieldsetPage)

**Comment by matjazpotocnik** [comment]
@flipzoom, thank you! I agree, a check should be carried out.

**Comment by ryancramerdesign** [comment]
@flipzoom Thanks I have added a check for that.

**Comment by flipzoom** [comment]
Fixed, thanks.
