### ISSUE TITLE
Warning: Undefined array key "fields_id" in .../wire/core/WireSaveableItemsLookup.php:126

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#1995]
### Short description of the issue

I get that warning when installing RockCommerce with RockMigrations. I did quite some debugging but I can't seem to find the source of the problem. I think it might be related to ProcessWire creating repeater templates on the fly for repeater fields that I create via RockMigrations? But I might be wrong.

It does not look like there are any problems after installation. I have seen this warning in the past with other modules as well and I also didn't see any other side effects. So the solution might be just to add a condition in the linked method?

But I'd be thankful for any insights.

I'll attach the tracy bluescreen with the complete trace - maybe that helps anybody to spot something? Just save it as .html and you can view it in the browser.

[WireSaveableItemsLookup.html.txt](https://github.com/user-attachments/files/17790651/WireSaveableItemsLookup.html.txt)

**Comment by BernhardBaumrock** [comment]
When tracy is not installed this causes an even uglier problem:

<img width="901" alt="image" src="https://github.com/user-attachments/assets/7540c1a5-ccc2-44c8-b2f8-779a09d01512">

**Comment by Toutouwai** [comment]
I think this error can occur if you don't set the `repeaterFields` property of a repeater field that you create from the API. This is the property that corresponds to the inputfield shown below when creating a repeater in the PW admin.

![2024-11-18_100512](https://github.com/user-attachments/assets/2d1d8016-b10e-4dfc-9367-551dc803635a)

**Comment by BernhardBaumrock** [comment]
Thx @Toutouwai I think that is spot on and I'll look into this as soon as possible!

**Comment by BernhardBaumrock** [comment]
I'll close it for now to not produce any unnecessary workload for ryan :)

**Comment by gebeer** [comment]
@BernhardBaumrock could this maybe handled by RockMigrations? 
With the (not so ) new migration syntax, we define the fields in a repeater-field migration like
`'fields' => [...]` instead of `'repeaterFields' => [...]`
Maybe this is why the `repeaterFields` property is not being set?

**Comment by BernhardBaumrock** [comment]
Yeah @gebeer I thought so as well but did not find the cause of the problem or the solution. If you have some time to investigate that would be awesome!
