### ISSUE TITLE
Error received in debug mode if a session variable is of type object

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#1997]
### Short description of the issue

Error
Object of class stdClass could not be converted to string

https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/templates-admin/debug.inc#L121-L122

### Optional: Screenshots/Links that demonstrate the issue

<img width="1213" alt="Bildschirmfoto 2024-11-20 um 12 08 02" src="https://github.com/user-attachments/assets/55c73f61-9752-4670-8148-37590c1e26cb">

### Optional: Suggestion for a possible fix

Change:
https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/templates-admin/debug.inc#L121-L122
to:
`if(is_array($value) || is_object($value)) $value = print_r($value, true);`

### Setup/Environment

* ProcessWire version: 3.0.242
* (Optional) PHP version: 8.3
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@kixe Thanks, I've pushed a fix for this.

**Comment by kixe** [comment]
thanks
