### ISSUE TITLE
$page->get(fielda|fieldb) wrongly returns null

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1998]
### Short description of the issue

When `title` and `headline` is "0" (or `title` is "0" and `headline` is empty)...

```php
$page->get('headline'); // works
$page->get('title'); // works
$page->get('headline|title'); // doesn't work
```

![2024-11-21_161418](https://github.com/user-attachments/assets/630c2850-ebbb-43be-ad78-2eb1f11f81ee)

### Setup/Environment

* ProcessWire version: 3.0.242

**Comment by ryancramerdesign** [comment]
@Toutouwai I'm not so sure on this one, as the `a|b|c` format is intended to return the first non-empty match (see [here](https://github.com/processwire/processwire/blob/master/wire/core/WireData.php#L149)). A "0" string is empty, according to PHP. So it's more a question of whether you consider a "0" to be empty or not. PW mostly follows the PHP definitions of things like this, but I can also see how a case could be made that a "0" string has a length of 1, so a 0 as a string isn't really empty...

**Comment by Toutouwai** [comment]
If changing this would be a breaking change I'm happy to close.
