### ISSUE TITLE
Page title doesn't appear as Page Edit headline when title is "0"

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1999]
### Short description of the issue

Expected:
![2024-11-21_161910](https://github.com/user-attachments/assets/1b2ef016-5252-41b0-8d96-a8884cb96a48)

Not expected:
![2024-11-21_161856](https://github.com/user-attachments/assets/dbcae9b1-2b97-46a1-a8f5-006a957fcc82)

### Setup/Environment

* ProcessWire version: 3.0.242

**Comment by ryancramerdesign** [comment]
I think this is a similar to #1998, as PHP (and thereby ProcessWire) consider "0" to be empty, but this wouldn't be a breaking change for anyone, and seems like a more obvious case that it should use the "0", so I have updated this. Thanks.
