### ISSUE TITLE
Markup Regions: pw-append to <head> causes recursion/timeout

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#200]
### Short description of the issue

When attempting to append a stylesheet or script to the head element using `pw-append="my-head-id"` some kind or recursion occurs where the markup is repeated over and over, sometime resulting in a PHP max execution timeout.

### Steps to reproduce the issue

_main.php
```
<!DOCTYPE html>
<html lang="en">
<head id="head">
	<meta charset="UTF-8">
	<title><?= $page->title ?></title>
</head>
<body>
</body>
</html>
```

home.php
```
<link pw-append="head" rel="stylesheet" type="text/css" href="/path/to/file.css">
```

Resulting markup:
![2017-03-01_150941](https://cloud.githubusercontent.com/assets/1538852/23443053/2f649f36-fe91-11e6-8f33-587ee64370f4.png)

### Setup/Environment

* ProcessWire version: 3.0.52
* PHP version: 7

**Comment by Toutouwai** [comment]
This also causes a timeout...

_main.php
`<link id="my-stylesheet" rel="stylesheet" href="/site/templates/css/site.css">`

home.php
`<link pw-after="my-stylesheet" rel="stylesheet" href="/site/templates/css/foo.css">`

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.
