### ISSUE TITLE
Pagefiles Custom Fields - showIf conditional prevents save of field value

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#2001]
When using custom fields with a Pagefiles/Pageimages field, if a showIf conditional is added to a field on the custom fields template, the entered value does not save when editing a page.

### Steps to reproduce the issue

1. Create a Pageimages field (e.g. images)
2. Set up custom fields via a template (e.g. field-images)
3. Add two fields, only show the second field if the first has an entered value (e.g. field1!="")
4. Add the Pageimages field to a template
5. Edit a page with that template, add an image and save.
6. Add a value to the first field, the second should appear.
7. Add a value to the second field
8. Save the page.

### Setup/Environment
* ProcessWire version: dev latest, but I've been aware of this issue for a few years.

**Comment by Toutouwai** [comment]
Possible duplicate of #1889

**Comment by chriswthomson** [comment]
@Toutouwai indeed it is, will close.
