### ISSUE TITLE
Inputfield toggle 'helper' text (field name) causes display issues in some cases

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#2002]
When hovering over the Inputfield toggle arrow, the field name appears. There are examples where this is not helpful, for example on a RepeaterMatrix field, and futhermore on a Pagefiles/Pageimages field with custom fields within that field.

https://github.com/user-attachments/assets/e272d806-ae95-4912-bf70-e5e3c57b3f82

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
@chriswthomson, could you confirm Ryan's fix and close this issue?

**Comment by chriswthomson** [comment]
Hi, just downloaded 3.0.243, yes this has been resolved. I think the labels could be refined further, but will close this ticket.
<img width="630" alt="Screenshot 2024-12-23 at 10 04 20" src="https://github.com/user-attachments/assets/d7649bb3-f1ac-4afd-972b-208e32e47276" />
