### ISSUE TITLE
preload() corrupts getChanges()

### ISSUE THREAD

**Issue by tuomassalo** [processwire/processwire-issues#2004]
### Short description of the issue

Using `preload(['foo')]` will set `foo` as changed.

### Expected behavior

`preload` should not affect `getChanges()`.

### Steps to reproduce the issue

Add a template with a non-autojoined field `firstname`. Create a page with a firstname field. Run this:

```php
$p = $pages->get(1234);
echo("Changes before preload: " . json_encode($p->getChanges()) . "\n");
$p->preload(['firstname']); // fetches firstname
echo("Changes after preload: " . json_encode($p->getChanges()) . "\n");
```

This incorrectly results in:

```
Changes before preload: []
Changes after preload: ["firstname"]
```

I would expect `$p->preload(['firstname'])` to and `$p->get('firstname')` do the same thing: fetch the value from DB but not set the field as changed.

### Setup/Environment

* ProcessWire version: latest dev

**Comment by ryancramerdesign** [comment]
Thanks @tuomassalo I've pushed a fix for this

**Comment by matjazpotocnik** [comment]
@tuomassalo, could you please confirm if Ryan's fix is working and close the issue? Thank you!

**Comment by tuomassalo** [comment]
Yes, this seems to fix the issue! Closing.
