### ISSUE TITLE
ProcessPageEditLink: exception when edited page not viewable

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#2005]
### Short description of the issue

ProcessPageEditLink throws an exception when the $page->viewable() returns false for the page being edited.

![2024-12-02_093719](https://github.com/user-attachments/assets/5594764d-04c7-4abe-8d39-bd671cdc2d51)

But not having a template file makes the page not viewable (for example) and this shouldn't prevent the user from adding a link within RTE fields on the page.

I think the issue was introduced in this recent commit: https://github.com/processwire/processwire/commit/8a1ba8729842dd138cf3c08fe738fab6c6b0dcce

### Setup/Environment

* ProcessWire version: 3.0.242

**Comment by adrianbj** [comment]
@Toutouwai - is this related?
https://github.com/processwire/processwire-issues/issues/1933

**Comment by Toutouwai** [comment]
@adrianbj, not directly, because the change that caused this issue wasn't in place when you opened #1933.

I'm not sure what the reason was for commit 8a1ba87, but Ryan's comment in the other issue...

> Plus, no need to have edit permission just for linking to something. I think that the page-view check here is likely just as much about making sure we're linking to something that actually renders output rather than a 404

...makes me wonder if there is some confusion about what `$this->page` is in this case. `$this->page` is the page being edited, not the page being linked to (the test occurs when ProcessPageEditLink is being loaded, before there is a chance to add any link).

**Comment by adrianbj** [comment]
Thanks @Toutouwai - I have reverted the change in https://github.com/processwire/processwire/commit/8a1ba8729842dd138cf3c08fe738fab6c6b0dcce and that has at least fixed this new issue you found, which I was also experiencing, but initially assumed it was the same as the other open one.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai @adrianbj I've pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign, this and my other issue both seem resolved now.

**Comment by Toutouwai** [comment]
Thanks
