### ISSUE TITLE
The old bookmarks recursive redirect issue

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#2007]
### Short description of the issue

This has been an issue for as long as I can remember - probably since ProcessLister got its bookmarks feature.

If you are logged into the admin and visit: https://mysite.com/processwire/access/users/edit/ it will redirect multiple times to the point that the URL looks like: https://mysite.com/processwire/access/users/edit/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/bookmarks/ 

with a "ERR_TOO_MANY_REDIRECTS" error.

### Expected behavior

If the `?id=1234` is missing from the end of the URL, then it should immediately 404, not redirect to /bookmarks/.....

### Actual behavior

As noted above

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - looks good.
