### ISSUE TITLE
FieldtypePassword: confusing feedback to user

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#201]
### Short description of the issue

The password inputfield gives feedback to the user about the minimum requirements of the password they are trying to set, based on the "Password requirements" setting for the field. The trouble is that the complexify requirements override this making the feedback (and the "Password requirements" settings) virtually useless. 

Even with "Complexify factor" set to "0.01" I found it impossible to enter a password equal to the minimum requirements that isn't dismissed as "Too common". With "Minimum length" set to "6", a completely random string containing uppercase/lowercase letters, digits and punctuation is apparently still "Too common".

This isn't such a big deal in the back-end but it's very confusing when the inputfield is used on the front-end, where users think they are playing by the rules by meeting the requirements that the inputfield tells them yet still fail to satisfy the inputfield. This is bad UX.

### Expected behavior

A password that meets the requirements as reported by the inputfield feedback should be accepted as valid when the "Complexify factor" is set to a low level.

### Setup/Environment

* ProcessWire version: 3.0.52
* PHP version: 7

**Comment by Toutouwai** [comment]
Okay, I think I see what is going on here. Once you hit 8 characters things start working as expected. So it seems there is some minimum of 8 characters being enforced regardless of what is set in the "Password requirements".

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.
