### ISSUE TITLE
Changes that you made may not be saved

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#202]
### Short description of the issue

When adding an image to a field and save you will get "Do you want to leave this site?" popup, this is confusing users as the image has finished uploading and will be saved. It stating that some content may be lost is quite scary. Even though that wont happen. 

### Expected behavior

Once the image has finished uploading this should no longer happen. 

### Actual behavior

Popup happens regardless of image upload status

### Steps to reproduce the issue

1. Create an image field
2. Add to template
4. Add image to page using template
5. Save

### Setup/Environment

* ProcessWire version: 3.0.53
* (Optional) PHP version: 7.0

**Comment by LostKobrakai** [comment]
That's not the case. Until you save the field the image should be flagged as "isTemp" (or sth like that), which makes it "not really" saved.

**Comment by TomS-** [comment]
Hi @LostKobrakai I'm confused by the response? Is this intended functionality, I've never had it before in any previous versions, since 2.8.

**Comment by LostKobrakai** [comment]
The error message might be new, but files are considered temporary until a real page save since I know processwire: https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/Inputfield/InputfieldFile/InputfieldFile.module#L591-L592

**Comment by teppokoivula** [comment]
Actually, unless I'm missing something, @TomS- is saying that after adding the file, clicking save button displays this error. If that's indeed the case, it's definitely a bug and not a feature. Please correct me if I'm wrong, though :)

Aforementioned isTemp support was added in 2.5.7, though can't say for sure how long this error has been around. I've been seeing it in somewhat weird situations too, though always thought it might be something I did wrong.

**Comment by LostKobrakai** [comment]
Oh shit, thought the issue would be leaving without hitting save. Sorry :)

**Comment by TomS-** [comment]
@LostKobrakai I made a video demonstrating - https://gfycat.com/PeriodicBarrenAlpaca
@teppokoivula Correct :-)

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this issue. While I was there, I also added drag/drop protection so that if you accidentally drag a file somewhere that it can't be uploaded, it just ignores it (rather than making the browser load the image, for example).
