### ISSUE TITLE
Missing Guest Role (API created users)

### ISSUE THREAD

**Issue by suntrop** [processwire/processwire-issues#203]
### Short description of the issue

Missing guest role when adding user via API

### Expected behavior

Since guest is required (?) it should be added by default

### Actual behavior

New user only gets the role I specify

### Steps to reproduce the issue

I noticed the users I add via the API, are missing the "guest" role. I don't know if the missing role is somewhat preblematic, but if it is required by the system, I think it should be added by default.

$u = new User();
$u->of(false);
$u->name = $email;
$u->pass = $password;
$u->addRole('customer');
$u->email = $email;

// User details
$u->user_name->first_name = $first_name;
$u->user_name->last_name = $last_name;

// User details
$new_addressbook_entry = $u->user_addressbook->makeBlankItem();
$new_addressbook_entry->first_name  = $first_name;
$new_addressbook_entry->last_name   = $last_name;
$u->user_addressbook->add($new_addressbook_entry);

// User Hash
$u->user_hash = md5(uniqid($email, true));

$u->save();

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7
* (Optional) MySQL version: 5

**Comment by lesaff** [comment]
I agree, I think it should be set by default. I just got used to the fact that you have to add `guest` role but it's one less line of code nevertheless.

**Comment by adrianbj** [comment]
FYI - this was brought up here: https://github.com/ryancramerdesign/ProcessWire/issues/588

**Comment by suntrop** [comment]
Thanks for that reference. If there is no problem without that role, I am ok with it :-)

**Comment by adrianbj** [comment]
I'd still rather see it added for the sake of consistency when viewing users in the admin.

**Comment by szabeszg** [comment]
Probably it is still confusing, if this has not been carried out since then:
> Ryan: "Guest was not always a default assumption like it is now, and that's the only reason you see it anywhere... but we should move towards elimination of guest in 2.6."

If I understand it correctly, it should be eliminated rather than added, or at least the default assumption could be pointed out in the admin Description/Note field.

**Comment by ryancramerdesign** [comment]
If we drop the guest role, it's probably not going to be soon, so I see no harm in having it get automatically added to newly created users via the API. I have added this in the latest commit so it should do that for you now.
