### ISSUE TITLE
Multisite Issue with pw 3.0.53 / 3.0.54

### ISSUE THREAD

**Issue by webbear** [processwire/processwire-issues#206]
### Short description of the issue

After upgrading to 3.0.53 and 3.0.54 (today) all other sites in the multisite environment do not get their own db connection 

### Expected behavior

Roll back to 3.0.52 - everything works fine again - db connections are again from /site-mysite/config.php

### Actual behavior

After upgrading to 3.0.53 and 3.0.54 (today) all other sites in the multisite environment do not get their own db connection - the use all db connections from /site/config.php.
Although for templates it follows /site-mysite/templates

### Setup/Environment

https://processwire.com/api/modules/multi-site-support/ => OPTION #1: MULTIPLE SITES WITH MULTIPLE DATABASES

* ProcessWire version: 3.0.53
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
@webbear I think I tracked down what the issue is, but don't currently have a multi-site installation to test with. Could you try out the commit referenced here and let me know if the issue persists? Thanks.

**Comment by webbear** [comment]
that did it - thanks!
The multisite installation now runs on 3.0.54
