### ISSUE TITLE
Multilanguage name fields when cloning have double underscore, but shouldn't

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#207]
### Short description of the issue

When using the Clone module to copy a page, the "name" fields for other languages look like this:
```
id="Inputfield_clone_page_name__1812" name="clone_page_name__1812"
```

### Expected behavior

They should be consistent with page edit/add so they look like this (without the underscores):
```
id="Inputfield_clone_page_name1812" name="clone_page_name1812"
```

### Optional: Suggestion for a possible fix

Just as a quick reference reminder, the actual setup for edit/add is:
```
id="Inputfield__pw_page_name1812" name="_pw_page_name1812"
```
so maybe you might even want an additional underscore before "clone", so maybe this is better:
```
id="Inputfield__clone_page_name1812" name="_clone_page_name1812"
```
or maybe even prefixed with "pw", so:
```
id="Inputfield__pw_clone_page_name1812" name="_pw_clone_page_name1812"
```

* ProcessWire version: 3.0.54

**Comment by adrianbj** [comment]
Also, just wanted to point out that my Page Rename Options module now supports page cloning, but I am waiting for word on this to determine whether or not I need to add a workaround to deal with this: https://processwire.com/talk/topic/7724-page-rename-options/?do=findComment&comment=140639

No rush - just wanted to give you some context as to why this is important - to me at least :)

Thanks!

**Comment by ryancramerdesign** [comment]
Adrian, I'm not sure I understand. I've tested out cloning some multi-language pages, but they do clone properly. Are you seeing something that's not working, or are you just talking about something stylistic here? These two modules are not attempting to mirror each others variable naming style.

**Comment by adrianbj** [comment]
Hi Ryan, sorry if I wasn't clear. Everything works just fine. The problem is partly stylistic, but it does affect those wanting to override default behavior like I do in the Page Rename Options module because I have to deal with two different formats for the name field. I think consistency is really nice in things like this. If you're happy to change then great. If not, just let me know so I can modify my module so it works with the different format.

Here is the issue: https://github.com/adrianbj/PageRenameOptions/blob/a66b92b20934251d3fc982e2b0e32eae142dc7c9/PageRenameOptions.js#L52

It works for the default language in edit, add, and clone forms, but won't currently work in other languages. I can add a workaround, but if the name and ID of the clone field was the same as on the Add and Edit forms, it would work as is.

Does that explain a little better?

Thanks,
Adrian

**Comment by netcarver** [comment]
Adding label to bump.
