### ISSUE TITLE
JqueryWireTabs not remembering active tab between requests

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#208]
### Short description of the issue

The default option for the core JqueryWireTabs module is to remember the active tab "Only after form submit". For example, if you are on the "Children" tab of Page Edit and you save the page you should be on the Children tab when Page Edit reloads. This used to work but I notice it is no longer working in PW 3.0.54

_Edit: I downgraded to 3.0.52 and it is working correctly in this version._

### Expected behavior

Remember the active tab between requests as per JqueryWireTabs settings.

### Actual behavior

The first tab is always active after submitting a form.

### Setup/Environment

* ProcessWire version: 3.0.54

**Comment by ryancramerdesign** [comment]
Thanks, this issue has been fixed.
