### ISSUE TITLE
Custom selector to find selectable pages not working with roles

### ISSUE THREAD

**Issue by mackski** [processwire/processwire-issues#21]
### Short description of the issue

Using a custom selector to find selectable pages not working with user roles.

### Expected behavior

Pages are selected and shown for field page type and saved.

### Actual behavior

Pages are selected and shown for field page type, but cannot save.

### Optional: Screenshots/Links that demonstrate the issue

Attempts include:
 Error saving field "rider_account" - Page 1029 is not valid for rider_account (Page 1029 does not match findPagesSelector: template=user, roles.name=rider)

Error saving field "rider_account" - Page 1029 is not valid for rider_account (Page 1029 does not match findPagesSelector: template=user, roles=rider)

### Optional: Suggestion for a possible fix

Work around is to use PHP custom selector:
return $pages->find("template=user, roles=rider");

### Steps to reproduce the issue

1. Add user roles
2. Create field page type with custom selector: template=user, roles={user role}
3. Add field to page template, and attempt to save page.

### Setup/Environment

* ProcessWire version: 3.0.34
* (Optional) PHP version: 5.3
* (Optional) MySQL version: 5.1.73
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by adrianbj** [comment]
@ryancramerdesign - just wanted to confirm that I am also seeing this issue on this environment:

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.35
PHP: 7.1.0RC2
Apache: 2.4.23 (Unix) 
MySQL: 5.7.15

<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1
max_execution_time: 3000 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 10000
memory_limit: 512M
post_max_size: 100M
upload_max_filesize: 100M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 1
FreeType: 1
Imagick Extension: 1

</details><details><summary><strong>Module Details</strong></summary> AdminRestrictBranch: 0.3.9
AllInOneMinify: 3.2.3
BatchChildEditor: 1.3.8
ClearCacheAdmin: 0.0.5
DescriptionNoteVariables: 0.0.3
EmailNewUser: 0.2.9
FieldtypeImageMarker: 0.1.0
FieldtypeMapMarker: 2.0.9
FieldtypeMatrix: 1.0.4
FieldtypeMultiplier: 0.0.9
FieldtypeRuntimeMarkup: 0.0.2
FieldtypeTable: 0.1.4
FileValidatorSvgSanitizer: 0.0.1
FormSaveReminder: 1.0.6
HelperFieldLinks: 1.0.8
ImageExtra: 0.0.3
ImageRasterizer: 0.2.2
InputfieldImageMarker: 0.1.0
InputfieldMapMarker: 2.0.9
InputfieldMatrix: 1.0.4
InputfieldMultiplier: 0.0.9
InputfieldRuntimeMarkup: 0.0.2
InputfieldTable: 0.1.4
MarkupSitemapXML: 1.1.0
PageEditSoftLock: 1.0.1
PageProtector: 0.1.5
PageRenameOptions: 0.3.2
PasswordForceChange: 0.1.7
Process404Search: 0.1.9
ProcessChangelog: 1.2.15
ProcessChangelogHooks: 1.1.2
ProcessChildrenCsvExport: 1.3.8
ProcessCustomUploadNames: 0.5.9
ProcessHannaCode: 0.2.0
ProcessLoginHistory: 1.2.8
ProcessLoginHistoryHooks: 1.1.2
ProcessMigrator: 0.6.8
ProcessPDFImageCreator: 1.0.3
ProcessPageEditSoftLock: 1.0.1
ProcessPageFieldSelectCreator: 0.2.6
ProcessPageListerPro: 1.1.0
ProcessTableCsvExport: 0.4.1
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
RestrictTabView: 0.0.8
TableCsvImportExport: 0.4.1
TextformatterHannaCode: 0.2.0
TracyDebugger: 3.3.4
</details></details>

**Comment by adrianbj** [comment]
@somatonic pointed out that:
```
template=user, roles=1015
```
works fine, but I am not sure I understand why. Using the role name still populates the select options, but the page won't save.

**Comment by LostKobrakai** [comment]
The field population and validating correct pages are two different parts in the code, which is the reason for the mismatch.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update that accommodates this on the dev branch. We've actually just supported use of the 'id' property for these cases in the past, but clearly that's not flexible enough. Now it should work with any of the syntaxes you listed. Please let me know if you run into any trouble with it. 

https://github.com/processwire/processwire/commit/16a8232dfef74abcf20b5c2db6606eadfe5bb6e7
