### ISSUE TITLE
FileCompilerTags don't work when Processwire Namespace is declared

### ISSUE THREAD

**Issue by PixraelR** [processwire/processwire-issues#211]
### Short description of the issue

FileCompilerTags don't work when the processwire namespace is declared in the template files. 

### Expected behavior

It should always compile if I have the module installed, even though it has been declared the namespace. 

### Actual behavior

It only works if you remove the namespace from the template file.

### Optional: Suggestion for a possible fix

Maybe can be useful an on/off option in the module setup page, or being able to select the templates to compile.

* ProcessWire version: 3.0.55
* (Optional) PHP version: 7.1.1
* (Optional) MySQL version: 5.0.12

**Comment by ryancramerdesign** [comment]
Hi @PixraelR – there is already a setting for this. Go to Setup > Templates > [any template]  > Files. The default setting is to compile when file has no namespace, and don't compile when file has namespace. But you can change that setting.

**Comment by PixraelR** [comment]
I had already tried that too. The problem seems to be that the module does not process the tags that are in the file "_main.php"

**Comment by adrianbj** [comment]
Just confirming that you selected the: "Yes (template file and files included from it)" option?

Assuming you did, I wonder if it matters whether _main.php is included automatically through template settings, or by an include/require statement in your template file?

**Comment by PixraelR** [comment]
Yes I tried all options. The _main.php is include by the factory option "appendTemplateFile" that I think it will do the same as an include file, but I will try to include it right now by configuring the template itself.

**Comment by PixraelR** [comment]
Finally it works, I had previously tried that option but don't work, now I include directly the file _main.php and it works, later I remove the declaration to leave the factory option and it continue working. Maybe it's the cache

**Comment by PixraelR** [comment]
This module is definitely only an example for the file compiler features. Does not always work :-(
