### ISSUE TITLE
Front-End editor + MarkUp Regions conflict 

### ISSUE THREAD

**Issue by palacios000** [processwire/processwire-issues#213]
### Short description of the issue

Conflict using Front-End editor + MarkUp regions on PW 3.0.50
If user has 'editable' privileges on page, fields on front-end page are not rendered; instead we have an empty block.

### Expected behavior

On browser: Front-end editable region should become editable on mouse-over  

### Actual behavior

Editable field becomes empty / content is not rendered

### Setup/Environment
* ProcessWire version: 3.0.50
* Enabled MarkUp Regions, as per https://processwire.com/blog/posts/processwire-3.0.50-core-updates/#more-on-markup-regions

**Comment by ryancramerdesign** [comment]
Hi @palacios000 markup regions are not involved with access control, but most likely you are seeing some other side effect of the combination. What method are you using to make the front-end fields editable?

**Comment by palacios000** [comment]
Hi,
I use option A, the default settings. 
For example the "body" field, there's only one body on the page, I don't see it on the front-end if I can edit the page. 
I also tried with different browsers (Firefox & Chrome)

**Comment by nettings** [comment]
see #294.

**Comment by netcarver** [comment]
@palacios000 Can you check if this issue still exists in recent releases of PW? I suspect it was fixed as mentioned by @nettings in the fix applied in #294.

**Comment by netcarver** [comment]
Closing. If anyone has more information, please post here for review. Thank you!
