### ISSUE TITLE
InputfieldPage: dependent selects not working with default value on new page

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#214]
### Short description of the issue

The ["dependent selects" feature of InputfieldPage](https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/modules/Inputfield/InputfieldPage/InputfieldPage.js#L10-L81) is not working when you are adding a new, as-yet-unpublished page, and the "source" Page field for the dependency has a default value configured for the field. Once the page has been saved or published then the dependent selects feature starts working.

### Expected behavior

Dependent selects feature works for new pages where a default value has been configured for the source Page field. 

### Actual behavior

The dependent Page field shows no available options in the select, despite a value being selected (by default) in the source Page field.

### Steps to reproduce the issue

1. Create a Page field "source_field" using a Select inputfield, make it required and configure a default value for the field. 
2. Create another Page field "dependent_field" using a Select inputfield and a selector string "parent=page.source_field".
3. Create a new page using a template that contains both source_field and dependent_field. While the new page is open in Page Edit and not yet saved/published for the first time, note that the select for dependent_field contains no options despite there being a value selected in the source_field.

### Setup/Environment

* ProcessWire version: 3.0.55

**Comment by Toutouwai** [comment]
It seems that the default value for a Page field is not actually saved to the field until the page being edited is saved in Page Edit. Which is surprising because doesn't the page get saved once already during the first step of Add Page?

In the meantime I have worked around this by hooking Pages::added and setting the default value for the source field there.

```
$this->pages->addHookAfter('added', function($event) {
    $page = $event->arguments('page');
    if($page->template != 'my_template') return;
    if(!$page->source_field->id) $page->setAndSave('source_field', 1234); // set default value for Page field
});
```

**Comment by ryancramerdesign** [comment]
@Toutouwai Just tried and can't duplicate this one. I notice this report is a couple years old and was wondering if you are still experiencing this behavior? Thanks.

**Comment by Toutouwai** [comment]
Yes, the issue still exists in PW 3.0.127

Maybe some screencasts will clarify. In the screencasts below the selectable pages for "Items" is defined by the selector string: `parent=page.category, has_parent=/selects/`. In both cases this is a new page that has not been saved previously.

Here the dependent selects are working correctly:

![working](https://user-images.githubusercontent.com/1538852/55204751-0e68bc00-5235-11e9-9d56-4c6e2055f3a3.gif)

But when the Colours page is set as the default value for the Category field then the dependent selects feature does not work on the initial page load. "Colours" is selected but "Items" remains empty. Selecting "Colours" again from the select does not populate Items (I get why but would be confusing for an editor), but changing the value of Category and then changing back to "Colours" gets it working.

![problem](https://user-images.githubusercontent.com/1538852/55205222-db272c80-5236-11e9-88e2-011e2897e494.gif)

Once the page has been saved with "Colours" selected then Items is populated as expected.

The problem is that selectable pages for the dependent select are only evaluated in two situations:

1. Once when Page Edit loads, according to the saved value of the source field. This doesn't work for a default value because it hasn't been saved yet.
2. When the value of the source inputfield changes. So this is why changing the value and then changing back gets the dependent select working again.

I'm not sure of the best way to resolve this. Maybe a change event could be triggered on DOM ready for any Page Reference field that has a default value set. Or perhaps there is some way for situation 1 to check the default value if the saved value is empty.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I was able to duplicate it after your info above. I have pushed a fix for this, and also ended up refactoring much of the code around it. Hopefully I didn't break anything, but please let me know if you observe any other issues with it. Thanks.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, it's working nicely!
