### ISSUE TITLE
Admin search should not be case sensitive

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#216]
### Short description of the issue
When searching in the admin in the global search menu.  I noticed the search wasn't finding pages because the search is currently case sensitive.  For example if I search for "tracy" it doesn't find anything, but if I search for "Tracy" it does find it.

### Expected behavior
The search should find pages in a case insensitive way.

### Steps to reproduce the issue
For example if I search for "tracy" it doesn't find anything, but if I search for "Tracy" it does find it.

Note: you would probably need the TracyDebugger module installed if you are searching for "Tracy".

**Comment by adrianbj** [comment]
What version of PW?
I am running 3.0.55 and it seems fine to me:
![screen shot 2017-03-16 at 8 09 33 am](https://cloud.githubusercontent.com/assets/871211/24003165/f58ecb02-0a1f-11e7-9a57-27a8e1a12c40.png)

**Comment by gmclelland** [comment]
Strange.. Now it works correctly.  I guess I didn't check it enough.  Thanks @adrianbj
