### ISSUE TITLE
Inline Styling CKeditor 

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#219]
### Short description of the issue

When using the CKEditor inline and the field to set the inline styles from /site/modules/InputfieldCKEditor/contents-inline.css

This does work, but the styling is partly overwritten when the page is edited in a modal (PageTable, Lister etc) For example the modal css has a style for h2.

### Expected behavior

Not getting overwritten by other styles in admin

### Actual behavior

Can conflict with modal css

### Setup/Environment

* ProcessWire version: pw 3.0.42

**Comment by somatonic** [comment]
Also the Link in the CKeditor inline css description leads still to old repo: https://github.com/ryancramerdesign/ProcessWire/blob/dev/wire/modules/Inputfield/InputfieldCKEditor/README.md#custom-editor-css-file

**Comment by matjazpotocnik** [comment]
@somatonic is this still an issue? Looks like the link to the ready-to-go mystyles.js now points to the correct repo: https://github.com/processwire/processwire/blame/d4db88ec7b9ad051740ff74271378b853d8aea28/wire/modules/Inputfield/InputfieldCKEditor/README.md#L89
