### ISSUE TITLE
Unneeded update on page save with "parent" changed

### ISSUE THREAD

**Issue by Zarik** [processwire/processwire-issues#220]
### Short description of the issue

When you move a page to another parent in admin area or change the parent field via API processwire updates "pages_parents" relations table for unchanged pages and this can take a long time. 

For example see screenshot below moving a page in our case fires an update of parent->parent (id 29) and a subtree contains ~80000 pages and tooks 32 minutes.

### Expected behavior

When a page's parent is changed "pages_parents" links should be updated only for this page and all its children recursively. 

There is no need to update new "parent" page or previous "parent" page, or parent->parent page.

### Optional: Screenshots/Links that demonstrate the issue

1. page 29 (users) contains 39000 childs (user)
2. each user contains one child (garage)
3. each garage contains one or more childs (car)

Example: moving car (id: 64438) up one level fires an update for (new_parent->parent) page which is (users id: 29) in our case. Firing more than 80000 updates of unchanged pages.

![image](https://cloud.githubusercontent.com/assets/4989626/23786799/058b2b4e-0580-11e7-8382-6de941869fb2.gif)

### Optional: Suggestion for a possible fix

In the PageEditor.php file function saveParents ignore $numChildren parameter -- always update the given $page_id and its sub-tree. The quickest fix is to comment the line:
`// if(!$numChildren) return true;`

And in the function savePageFinish a single if should be used:
```
if ( $page->parentPrevious || $isNew || $page->_forceSaveParents )
            $this->saveParents($page->id, null /* $page->numChildren */); // numChildren ignored now
```

instead of this code:
```
/*
		// lastly determine whether the pages_parents table needs to be updated for the find() cache
		// and call upon $this->saveParents where appropriate.
		if($page->parentPrevious && $page->numChildren > 0) {
			// page is moved and it has children
			$this->saveParents($page->id, $page->numChildren);
			if($page->parent->numChildren == 1) $this->saveParents($page->parent_id, $page->parent->numChildren);

		} else if(($page->parentPrevious && $page->parent->numChildren == 1) ||
			($isNew && $page->parent->numChildren == 1) ||
			($page->_forceSaveParents)) {
			// page is moved and is the first child of it's new parent
			// OR page is NEW and is the first child of it's parent
			// OR $page->_forceSaveParents is set (debug/debug, can be removed later)
			$this->saveParents($page->parent_id, $page->parent->numChildren);

		} else if($page->parentPrevious && $page->parent->numChildren > 1 && $page->parent->parent_id > 1) {
			$this->saveParents($page->parent->parent_id, $page->parent->parent->numChildren);
		}

		if($page->parentPrevious && $page->parentPrevious->numChildren == 0) {
			// $page was moved and it's previous parent is now left with no children, this ensures the old entries get deleted
			$this->saveParents($page->parentPrevious->id, 0);
		}
*/
``` 

### Steps to reproduce the issue

1. Create a page1 in a tree (not on top level)
2. Create a bunch of children (~10000 will be enough)
3. Now try to move any other page to this subtree (parent page1).
4. This will take a long time.

**Comment by horst-n** [comment]
I'm not competent in this part here, but one question came to my mind: Have you had an eye on the values of the sort field? Maybe only those needs to be updated, due to your hirarchical move?

**Comment by ryancramerdesign** [comment]
> When a page's parent is changed "pages_parents" links should be updated only for this page and all its children recursively.
> There is no need to update new "parent" page or previous "parent" page, or parent->parent page.

Just wanted to mention that these steps are indeed necessary, because the purpose of the pages_parents table is to provide an index for has_parent selector searches. 

What version of the ProcessWire core are you seeing this in? And, do you have any 3rd party modules installed or hooks? I'm testing here moving children between one parent with 11000 children, and another with 20000 children. The operation completes in under half a second. As a result, I can't seem to duplicate the issue here (testing in the current PW 3.x dev core). 

There is an update in 3.x a few months back (might be only in dev, can't remember) that corrects a bottleneck that's likely related to this. Though we were fixing something that took 5-10 seconds when dealing with tens of thousands of pages, not 32 minutes. So it's possible I'm missing something too. I think the first thing to look at is your core version, and next, any site modules that might be hooking into something.

**Comment by netcarver** [comment]
@Zarik Hello there. I know it's been a long time since you posted, but are you able to provide any of the requested information in Ryan's reply to your post? Did the update mentioned fix this issue for you?

**Comment by Zarik** [comment]
@netcarver Unfortunately I am unable to verify the fix. I am not responsible for the system in question anymore and it is left on version 2.8.35.

**Comment by netcarver** [comment]
@Zarik Thank you for getting back regarding this issue.

Closing this issue.
