### ISSUE TITLE
$page->editUrl(true) does not include scheme and hostname

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#221]
### Short description of the issue

$page->editUrl(true) does not include scheme and hostname

### Expected behavior

It should return the editUrl with scheme and hostname
### Actual behavior

If I set the parameter of the function either as true or an array, the function does not return the Url with scheme and hostname, it does only return the path like
/a/path/www/bewerbertool-talents/admin/page/edit/?id=1514

I tried the following variations:
$page->editUrl(true) 
$editUrl = $page->editUrl(["http" => true]);
$editUrl = $page->editUrl($options = ["http" => true]);

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.42
PHP: 7.0.10
Apache: 2.4.23 (Win32) OpenSSL/1.0.2h 
MySQL: 10.1.9-MariaDB-log

<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1
max_execution_time: 36000 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 1000
memory_limit: 512M
post_max_size: 20M
upload_max_filesize: 20M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 
FreeType: 1
Imagick Extension: 

</details><details><summary><strong>Module Details</strong></summary> AbsageVerschicken: 1.0.0
AdminOnSteroids: 1.3.2
AlteBewerbungenLoeschen: 1.0.0
BatchChildEditor: 1.3.8
FieldtypeFields: 0.0.1
FieldtypeListerActionButtons: 0.0.1
FieldtypeRadio: 1.0.0
HidePages: 1.0.0
InputfieldTextareaMarkup: 1.0.4
JqueryDataTables: 1.9.4
MarkupActivityLog: 1.0.1
ModulesManager: 2.1.6
PageActionEmail: 0.0.1
PageActionExportCSV: 0.0.4
PageActionSetField: 0.0.1
ProcessActivityLogService: 1.0.1
ProcessAdminActions: 0.5.1
ProcessChildrenCsvExport: 1.3.8
ProcessDatabaseBackups: 0.0.3
ProcessMigrator: 0.7.0
ProcessPageDelete: 1.2.4
ProcessPageListerPro: 1.1.0
ProcessPageListerSummaryTable: 0.0.1
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
StatusIconsInLister: 0.0.1
TracyDebugger: 3.4.1
WinkelmannAddTab: 0.0.1
WinkelmannEinladungVorstellungsgespraech: 0.0.1
WinkelmannStatusChange: 0.0.1
WireMailSmtp: 0.2.3
</details></details>

**Comment by kixe** [comment]
In ProcessWire 3.0.42 this function doesn't expect any arguments. Feature was introduced in PW 3.0.48.
```
$page->editUrl(true)
$editUrl = $page->editUrl(["http" => true]);
```
issue can be closed.
