### ISSUE TITLE
Wrongly-sized admin thumbnail created when image height less than 260px

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#222]
### Short description of the issue

When an image with a height greater than 260px is uploaded, an admin thumbnail is created: my_image.0x260.jpg. The height is 260px and the width is unconstrained - this is the normal and correct behaviour. 

~~But if an image with a height _less_ than 260px is uploaded then two admin thumbnails are created: my_image.0x260.jpg and my_image.260x0.jpg. If the first of these were used as the admin thumbnail it would be okay, but the second of these is the one that is actually displayed in admin.~~
_Correction: only a single admin thumbnail is created._
But if an image with a height _less_ than 260px is uploaded then the admin thumbnail is my_image.260x0.jpg, with a width constrained to 260px. If the image is significantly wider than it is high then the resulting thumbnail height may be very small (I have some at 60px high) and so the thumbnails look terrible in admin.

I have $config->imageSizerOptions and $config->adminThumbOptions at their defaults.

### Expected behavior

All thumbnails have unconstrained width, regardless of if the uploaded image height is less than 260px.

### Actual behavior

Images with a height less than 260px create an admin thumbnail where width is constrained to 260px.

### Optional: Screenshots/Links that demonstrate the issue

The same image at 259 pixels high (top) and 261 pixels high (bottom).

![2017-03-24_155521](https://cloud.githubusercontent.com/assets/1538852/24278715/5785cd52-10aa-11e7-9175-b72cc93ce4ed.png)

### Steps to reproduce the issue

1. Upload a wide image with a height less than 260 pixels
2. Observe the poor admin thumbnail that results.

### Setup/Environment

* ProcessWire version: 3.0.50

**Comment by ryancramerdesign** [comment]
I think the logic where this is occurring is here in InputfieldImage.module, in the elseif condition:
~~~~~
// use new thumbnail size, 260px (scaled to 130px in output)
if($thumbWidth >= $thumbHeight && $thumbHeight > $gridSize2x) {
	$thumb = $thumb->height($gridSize2x, $imageSizerOptions);
	$thumbHeight = $this->gridSize;
	$thumbWidth = 0;
	$is2x = true;
} else if($thumbWidth > $gridSize2x) {
	$thumb = $thumb->width($gridSize2x, $imageSizerOptions);
	$thumbWidth = $this->gridSize;
	$thumbHeight = 0;
	$is2x = true;
}
~~~~~
What it's doing is trying to avoid a server-side upscale. So if it doesn't have room to resize it by height, then it falls back to resize it by width. It needs to create a thumbnail that's independent of the original, one way or another. I'm thinking to resolve the issue here, it either needs to just accept the server-side upscale, or maybe just create a thumbnail that's a few pixels smaller than the original, and accept the client-side upscale. What do you think?

**Comment by Toutouwai** [comment]
I think the problem is due to a flaw in the logic of the if/else statement.

It looks to me like the if/else is intended to distinguish between landscape and portrait format images. Like the intended logic is: if the image is landscape and its height is greater than the thumb max height then resize its height to the thumb max height, or if the image is portrait/square and its width is greater than the thumb max width then resize its width to the thumb max width.

But the flaw is that the `else` part of the statement is matched not only by portrait images but landscape images with a height less than the thumb max height. I think the code should be something like:

```
// use new thumbnail size, 260px (scaled to 130px in output)
if($thumbWidth >= $thumbHeight) {
	if($thumbHeight > $gridSize2x) {
		$thumb = $thumb->height($gridSize2x, $imageSizerOptions);
		$thumbHeight = $this->gridSize;
		$thumbWidth = 0;
		$is2x = true;
	}
} else if($thumbWidth > $gridSize2x) {
	$thumb = $thumb->width($gridSize2x, $imageSizerOptions);
	$thumbWidth = $this->gridSize;
	$thumbHeight = 0;
	$is2x = true;
}
```
This passes through landscape images with a height less than thumb max height and portrait images with a width less than thumb max width without resizing.

**Comment by ryancramerdesign** [comment]
Thanks for the suggestion. Do you find in practice that it resolves the issue you are observing? If so, I'll go ahead and apply this to the core.

**Comment by Toutouwai** [comment]
Yes, that code does resolve the issue. But it means that for low-height landscape or low-width portrait images no variation is created for the admin thumbnail and the original is used instead - not sure if there are any flow-on implications of that. I've been using in on a development site for a while and haven't encountered any problems so far.

**Comment by ryancramerdesign** [comment]
Thanks, I've changed the code to what you suggested and can confirm it seems to work well here. While a thumbnail is required in some cases (or at least used to be), the reality is that it will get created when/if it's needed, so actually I think the adjusted logic should be just fine.
