### ISSUE TITLE
Logs helper does not respect $config->dateFormat

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#223]
### Short description of the issue

If I open up the logs and then select Helper, the "from" and "to" date selectors don´t show up in the format specified in config.php.

### Expected behavior
For example I have in my config.php
`$config->dateFormat = "d.m.Y H:i:s";
$config->timezone = 'Europe/Berlin';
`
then the from and to fields should show the placeholder in this format, and after selecting a date from the datepicker, it should be in this format.

### Actual behavior

Actual the fields always show the date in yyyy-mm-dd format

### Optional: Screenshots/Links that demonstrate the issue

![chrome_2017-03-24_12-37-31](https://cloud.githubusercontent.com/assets/551551/24292694/b4f25a6c-108e-11e7-8e66-fbe54995c598.png)

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.42
PHP: 7.0.10
Apache: 2.4.23 (Win32) OpenSSL/1.0.2h 
MySQL: 10.1.9-MariaDB-log

<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1
max_execution_time: 36000 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 1000
memory_limit: 512M
post_max_size: 20M
upload_max_filesize: 20M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 
FreeType: 1
Imagick Extension: 

</details><details><summary><strong>Module Details</strong></summary> AbsageVerschicken: 1.0.0
AdminOnSteroids: 1.3.2
AlteBewerbungenLoeschen: 1.0.0
BatchChildEditor: 1.3.8
FieldtypeFields: 0.0.1
FieldtypeListerActionButtons: 0.0.1
FieldtypeRadio: 1.0.0
HidePages: 1.0.0
InputfieldTextareaMarkup: 1.0.4
JqueryDataTables: 1.9.4
MarkupActivityLog: 1.0.1
ModulesManager: 2.1.6
PageActionEmail: 0.0.1
PageActionExportCSV: 0.0.4
PageActionSetField: 0.0.1
ProcessActivityLogService: 1.0.1
ProcessAdminActions: 0.5.1
ProcessChildrenCsvExport: 1.3.8
ProcessDatabaseBackups: 0.0.3
ProcessMigrator: 0.7.0
ProcessPageDelete: 1.2.4
ProcessPageListerPro: 1.1.0
ProcessPageListerSummaryTable: 0.0.1
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
StatusIconsInLister: 0.0.1
TracyDebugger: 3.4.1
WinkelmannAddTab: 0.0.1
WinkelmannEinladungVorstellungsgespraech: 0.0.1
WinkelmannStatusChange: 0.0.1
WireMailSmtp: 0.2.3
</details></details>

**Comment by ryancramerdesign** [comment]
In this case it intentionally uses the standard ISO-8601 date format consistent with the actual log files where the dates appear, since that is the context of this module. Though the date pickers are there to abstract away the format anyway. The `$config->dateFormat` is used as a default fallback for output purposes in some places, but it is not used by the ProcessLogger module at present, which sticks to the log format.

**Comment by jmartsch** [comment]
This could be improved, but closing this issue right now, to remove clutter.
