### ISSUE TITLE
Weird behavior after set $config->useMarkupRegions = true

### ISSUE THREAD

**Issue by karltaidev** [processwire/processwire-issues#224]
### Short description of the issue

After set $config->useMarkupRegions = true in config file, echo(i cannot confirm all functions act like the same) inside _init.php, _func.php and _main.php will print twice if markup region syntax is found inside template. If no markup region syntax found inside template, the echo will not be printed.

### Steps to reproduce the issue

1. Flesh install PW with default site profile.
2. add echo "something" in line #2 in _main.php or somewhere inside _init.php or _func.php.
3. set $config->useMarkupRegions = true inside config.php
4. load homepage, no echo is found.
5. add markup region syntax like div with pw-append='main' after closing php.
6. load homepage, double echo is found.

### Setup/Environment

* ProcessWire version: 3.0.57
* (Optional) PHP version: 7.0

**Comment by Toutouwai** [comment]
This part confuses me:

> add echo "something" in line #2 in _main.php or somewhere inside _init.php or _func.php.

_main.php should contain the doctype, <html>, <head> etc. So line 2 seems like a strange place to echo anything as that would normally be before the <body> of the page.

And normally _init.php and _func.php are where you initialise variables or define functions, so not sure why you would echo something there either.

**Comment by karltaidev** [comment]
It is for testing purpose and due to the sequence of the execution, some function I found useful placing there, but it is not the main point for this issue. You echo inside _init.php or _func.php or _main.php give you the same result, double echo. I just point out from where you could reproduce this. What I concern is every function has been executed twice accidentally after enable markup regions.

**Comment by ryancramerdesign** [comment]
WireMarkupRegions remembers everything you output before the `<doctype>` and looks for a corresponding place for it to go after the doctype. If it can't find your intended location, the last fallback is that it may output it above the doctype, where you originally output it, as regular old PHP would. So if you've done an echo "something" before the doctype, and another after (closing php), then I would expect to see it twice, like you mentioned for #6. Though on #4 I might have expected to see it once (if the last fallback/error condition was triggered), but probably not unless looking directly at the HTML source. If I understand correctly, I can't identify that it's behaving incorrectly here. Though if you think maybe I don't understand, maybe if there a production case you can relate it to where the behavior is problematic? Thanks.

**Comment by karltaidev** [comment]
Thank you Ryan for the clear explanation. It will not be a problem as long as functions do not executed twice unnecessarily. A small note for this behavior somewhere would be nice as I think using echo to debug is common and it may arise confusion like I have.
