### ISSUE TITLE
Backend Search seems to not sanitize inputs

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#228]
### Short description of the issue

Running this request `/processwire/page/search/for?get=template_label,title&include=all&admin_search=!OmUvjGq9suNnVHB2zcEWVFQ0uFu7@nS` via the backend search results in the following error:

`SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected '@', expecting $end`

### Expected behavior

I can put whatever title I need in the search bar.

### Actual behavior

If fails (with the Reno theme).

### Steps to reproduce the issue

1. Try to search the following title: !OmUvjGq9suNnVHB2zcEWVFQ0uFu7@nS

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 7

**Comment by Toutouwai** [comment]
FYI: no errors for me with that string in 3.0.57, default admin theme. But the leading exclamation mark seems to get stripped.

**Comment by LostKobrakai** [comment]
I've already another issue about that: https://github.com/processwire/processwire-issues/issues/227

**Comment by ryancramerdesign** [comment]
I can't duplicate the issue here either. Did test in Reno as well. Are you able to duplicate it from the API side?

**Comment by netcarver** [comment]
@LostKobrakai I can't reproduce this on 3.0.119 with PHP 7. Can you still reproduce this on more recent installs of PW?
