### ISSUE TITLE
$t->cacheTime = 0; not working as expected

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#229]
### Short description of the issue

I was trying to update the `cacheTime` of a **Template** object, and it was not working.

### Expected behavior

I would expect that the following code would update the `cache_time` column value in the Templates table; there are several aliases in `wire/core/Template.php` mapping `cacheTime` to `cache_time`.

```php
$t = $this->wire('templates')->get('template-name');
$t->cacheTime = 0; // was 600
$t->save();
```

### Actual behavior

`var_dump($t->cacheTime); die;` after the previous code displays `600`.

### Optional: Screenshots/Links that demonstrate the issue

[Template Docs suggest Template::cacheTime works.](http://processwire.com/api/ref/template/#pw-methods-cache).

![screen shot 2017-04-03 at 18 46 10](https://cloud.githubusercontent.com/assets/6864684/24634836/f6cc8e00-189d-11e7-96ce-3aa1d024bfad.png)

### Optional: Suggestion for a possible fix

I was able to get this code to work by changing `cacheTime` to `cache_time` in the API call.

```php
$t = $this->wire('templates')->get('template-name');
$t->cache_time = 0; // was 600
$t->save();
```

### Steps to reproduce the issue

1. Set up a template with caching in the back-end. Any time should suffice.
2. Try to update the saved `cacheTime` value with the API:
```php
$t = $this->wire('templates')->get('template-name');
$t->cacheTime = 0;
$t->save();
```

3. dump the result - it should remain unchanged.
4. change `cacheTime` to `cache_time` in line 2 of that snippet and re-run. It should now be updated.

### Setup/Environment

* Vagrant Environment
* Scotchbox
* ProcessWire version: 3.0.42
* (Optional) PHP version: 5.6.14-1+deb.sury.org~trusty+1
* (Optional) MySQL version: 5.5.46

**Comment by ryancramerdesign** [comment]
Thanks @ethanbeyer I've pushed a fix to the dev branch.

**Comment by ethanbeyer** [comment]
Thank you, @ryancramerdesign !
