### ISSUE TITLE
FileCompiler does not inherit site/config.php chmod setting

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#230]
### Short description of the issue

FileCompiler does not inherit site/config.php chmod setting

### Expected behavior

It should inherit it, especially as those are even added by the installation.

### Actual behavior

It's once set in the wire/config.php, but before site/config.php is evaluated.

### Setup/Environment

* ProcessWire version: 3.0.42
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
This one was fixed in PW 3.0.44: https://github.com/processwire/processwire/commit/e2e8c35c2c7617b1a7672d94b6300247f6c79658

Though if you think it's something different, please re-open. Thanks.
