### ISSUE TITLE
Tree dropdown menu confusing for roles with limited edit access 

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#231]
### Short description of the issue

As a superuser the new Tree dropdown menu is very handy for editing pages and adding new pages. I think it's less useful and potentially confusing for roles with limited edit access. Currently pages for which a role has no edit access are not distinguishable from pages that can be edited, and if the role clicks a page with no edit access they are taken to view the page in the frontend. This is unexpected and isn't helpful, particularly for pages such as the 404 and the FormBuilder page which a client can't be expected to understand.

My preferences would be:

- Tree dropdown feature may be disabled/enabled for a given role.
- Non-editable pages are visually distinguishable, e.g. lighter text.
- Clicking a page for which the role has no edit access does nothing.
- Perhaps if a page is not editable, has no children, and adding children is not allowed, then this page should not appear in the tree dropdown at all for non-superusers.

### Setup/Environment

* ProcessWire version: 3.0.58

**Comment by ryancramerdesign** [comment]
I've pushed an update this morning that makes it show a "not allowed" cursor when you hover over a page that isn't editable. (The use of a lighter label text is reserved to identify "hidden" pages, consistent with PageList.) We could also remove the "view" alternative link as you suggested, still thinking about that.

**Comment by Toutouwai** [comment]
> I've pushed an update this morning that makes it show a "not allowed" cursor when you hover over a page that isn't editable.
@ryancramerdesign, I'm not seeing the not-allowed cursor for non-editable pages in 3.0.60. Did you commit that change yet?

**Comment by Toutouwai** [comment]
Thanks for the update.
