### ISSUE TITLE
JqueryWireTabs not honouring "tab position" setting

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#233]
### Short description of the issue

I previously opened an issue regarding JqueryWireTabs not remembering the active tab between requests: https://github.com/processwire/processwire-issues/issues/208
A fix was committed for this, but now I've found that tabs are _always_ remembering the active tab between requests even though the module setting for JqueryWireTabs is at the default of "Only after form submit".

### Expected behavior

JqueryWireTabs honours module setting for "Remember tab positions between requests?"

### Actual behavior

Behaviour is "Always" when setting is for "Only after form submit".

### Steps to reproduce the issue

1. Check that the JqueryWireTabs module setting is at default of "Only after form submit".
2. Open a page for editing, switch to the "Settings" tab, then choose the "Save + Exit" submit action.
3. Open a page for editing (doesn't even have to be the same page) and note that the "Settings" tab is current.

### Setup/Environment

* ProcessWire version: 3.0.58

**Comment by ryancramerdesign** [comment]
I think it's always been this way actually, but agree it's not ideal. I've pushed a update that should fix it. The cookie that it saves to remember the tab now contains some additional info tied to the editor.
