### ISSUE TITLE
Not cropping or upscaling transparent PNG8 results in black background

### ISSUE THREAD

**Issue by phlppschrr** [processwire/processwire-issues#235]
### Short description of the issue
Having an png8 optimized original image with transparency (size 800x600px) and an api call like this results in an png with black background. When I allow PW to upscale the the image the transparency is kept.
```
$page->image->size(2000,2000,['cropping'=>false, 'upscaling'=>false])->url
```

### Expected behavior

When neither cropping nor up-/downscaling is needed just output the original image.

### Setup/Environment

* ProcessWire version: 3.0.58 dev
* Only tested without imagemagick, just with default gd

**Comment by horst-n** [comment]
The expected bevavior you mentioned is wrong. If you want output the original image, you need to avoid manipulation methods. Otherwise, for example with an original JPEG, 100% quality, 2 MB filesize, we would need to output this too. But we create a variation with lesser quality setting and output that.

**Comment by phlppschrr** [comment]
You are right, I did not think about JPEG images. Though I am not sure if the quality setting does anything at PNG images? 

No matter if a new ImageVariation is created or the original image is returned, ProcessWire should never discard the alpha channel of the PNG image.

**Comment by horst-n** [comment]
I'm thinking of, if we can make here a different behave for jpeg and gif/png. With JPEG it should be like it is now, for GIF and PNG, we should do a filecopy from source to destination file and early cleanup and return.

https://github.com/processwire/processwire/blob/35df716082b779de0e53a3fcf7996403c49c9f8a/wire/core/ImageSizerEngineGD.php#L202-L213

**Comment by ryancramerdesign** [comment]
@horst-n I'm not sure I understand all you mentioned well enough to implement what's suggested. But if there's some code you think we should add there, just let me know and I can paste it in. Thanks.

**Comment by phlppschrr** [comment]
I think @horst-n proposes a simple early exit check somewhere around the mentioned lines. Something like this (inserted in line 201): 

```php
        if (0 == $resizeMethod && ($this->imageType == \IMAGETYPE_PNG || $this->imageType == \IMAGETYPE_GIF)) {
            // return the original image if imagetype is png or gif
            $result = @copy($srcFilename, $dstFilename);
            // The cleanup @horst-n mentioned. Anything else to do?
            if(isset($image) && is_resource($image)) @imagedestroy($image); // @horst
            if(isset($thumb2) && is_resource($thumb2)) @imagedestroy($thumb2);
            if(isset($image)) $image = null;
            if(isset($thumb2)) $thumb2 = null;
            // exit here and skip further processing:
            return $result;
        } else if(0 == $resizeMethod) {
``` 

I only did some quick tests, but this code works for me, but feels a bit hacky?

**Comment by phlppschrr** [comment]
Any news on this issue? I have this fix now running on 2 live sites without any issues.

**Comment by matjazpotocnik** [comment]
@phlppschrr I think this might be fixed? See https://github.com/processwire/processwire/blob/d9b30167c7cdf08fc093e007b01a8b871ed08417/wire/core/ImageSizerEngineGD.php#L221-225
