### ISSUE TITLE
InputfieldSelector not respecting "allowSystemTemplates" setting.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#236]
### Short description of the issue

AJAX calls (eg after selecting "Template" from first dropdown) call the setup() method before the settings were populated.

### Expected behavior

The allowSystemTemplates setting should allow system templates :)

### Actual behavior

They aren't allowed.

### Optional: Suggestion for a possible fix

https://github.com/processwire/processwire/pull/49

PS - sorry for posting an issue after you have already reviewed the PR, but I don't want to have to keep track of the PR now that it's been closed.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I could have sworn I applied this update before, but it sure doesn't look like it – must have dreamed it or something. :) I've just applied it here now.
