### ISSUE TITLE
Overriding $config->paths->assets has no effect

### ISSUE THREAD

**Issue by abdusco** [processwire/processwire-issues#240]
### Short description of the issue

[As per this forum post on using same templates for two different sites](https://processwire.com/talk/topic/16001-multisites-with-same-templates-and-different-databases/), I set out to use different `assets` directory for different hosts. When I override `$config->paths->files`, uploads are saved to pointed directory as expected, but not when I change `$config->paths->assets`, PW just ignores it. The same behavior goes with `$config->urls->assets` as well.

### Expected behavior

It should respect my settings and try to save files in the pointed location.

### Actual behavior

It keeps using `/site/assets/files` as usual.

### Optional: Screenshots/Links that demonstrate the issue

```php
$config->dbHost = 'localhost';
$config->dbPort = '3306';

$config->httpHosts = array('pw.dev', 'pw2.dev');

if($_SERVER['HTTP_HOST'] == 'pw.dev') {
    // dev
    $config->dbName = 'pw_dev';
    $config->dbUser = 'pw_dev';
    $config->dbPass = 'password';
    $config->paths->assets = $config->paths->site . 'assets-dev/';
    $config->urls->assets = $config->urls->site . 'assets-dev/';
} else {
    // production
    $config->dbName = 'pw';
    $config->dbUser = 'pw';
    $config->dbPass = 'password';
}
```

### Steps to reproduce the issue

1. Add a new hostname `pw.dev` to `/etc/hosts` that points to same ip as the original site
2. Update server configuration to accept requests from the new site
3. Confirm both sites work
4. Override `$config->paths->assets`
5. Upload a new file on the new site.
6. File is saved to `/site/assets` no matter what

### Setup/Environment
- ProcessWire: 3.0.52
- PHP: 7.0.15-0ubuntu0.16.04.4
- Apache: Caddy/0.9.4
- MySQL: 5.7.17-0ubuntu0.16.04.1

**Comment by matjazpotocnik** [comment]
Override $config->urls->files and $config->paths->files.

**Comment by abdusco** [comment]
@matjazpotocnik that works as expected, however for complete separation, overriding `/site/assets/` directory is necessary since `logs`, `caches`, `sessions`, `backups` are all saved under `assets` directory.

**Comment by matjazpotocnik** [comment]
Overriding just `/site/assets/` in `/site/config.php` will not override `/site/cache|logs|files|sessions|tmp` as config.php is read after all initial paths/urls are already set, so you have to override it manually. No need to override `backups`.

**Comment by abdusco** [comment]
That makes sense. Is there a lower level setting, some hook for PW initialization for instance. 

I'm asking because, some modules (AIOM for example) use 

```php
if(wireMkdir(wire('config')->paths->assets.self::$cacheDir.DIRECTORY_SEPARATOR) === false) {
    
    // ------------------------------------------------------------------------
    // If the folder can not be created, trigger an error.
    // ------------------------------------------------------------------------
    throw new WireException('The cache folder ('.wire('config')->paths->assets.self::$cacheDir.DIRECTORY_SEPARATOR.') could not be created.');
}
```
to store its caches as `assets` directory is the defining location of asset directory for a site, and I understand why the developer used it so.  
So, although I'm satisfied with your answer, now I'm curious as to how to go deeper, and probably because PW should be as flexible as possible to suit every setup, and (within reasonable limits) hardcoded values should be open for user modification.

**Comment by ryancramerdesign** [comment]
No guarantees that overriding the location of all these assets will be stable–ProcessWire thinks they are part of your site directory. But if you want to give it a go, you'll need to override each of them independently. If you look at the bottom of the /wire/core/ProcessWire.php file you'll see a method called buildConfig(). This is where all the directories are defined. Make note of all the ones you want to override in there, and then make sure your code is accounting for all of them. Specifically, you'll want to override assets, cache, logs, files, tmp and sessions.

**Comment by netcarver** [comment]
@abdusco Hi Abdus, thanks for raising this issue. Would it make sense to open a feature request for an easier way to override these paths, and close this given that Ryan has marked this as not being a bug?
