### ISSUE TITLE
Admin search prevents normal browser link behaviour

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#241]
### Short description of the issue

I'm grateful for the merged [pull request](https://github.com/processwire/processwire/pull/47) that got the admin search result links triggerable via keyboard as it's something I use a lot (I was previously using a custom module to get this working), but I don't think that it should be preventing normal link click behaviour. It ought to be possible to Ctrl-click search result links and have them open in a new browser tab.

There should be some test to check that the link triggering event is coming via keyboard before using `event.preventDefault()`. This seems to do the trick - at [line 140](https://github.com/processwire/processwire/blob/81c8d4eb2fa2baa678d29b2b92086867dd1d9db7/wire/modules/AdminTheme/AdminThemeDefault/scripts/main.js#L140)... 

```
if(typeof event.key !== 'undefined') {
    event.preventDefault();
    window.location = ui.item.edit_url;
}
```

### Setup/Environment

* ProcessWire version: 3.0.59

**Comment by ryancramerdesign** [comment]
Thanks! That seems to work here too. I've applied and pushed your suggested fix.
