### ISSUE TITLE
No table created for fieldtype comments if db charset is utf8mb4

### ISSUE THREAD

**Issue by eidecker** [processwire/processwire-issues#242]
### Short description of the issue

If the charset of the database was set to "utf8mb4" during installation fields with type "Comments" cannot be created. 

When a new field is added folowing error occurs: "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (in /wire/core/Fieldtype.php line 670)".

The field is added to the table "fields" but no table to hold the data is created. The field cannot be used.

### Expected behavior

Fields of type "Comments" can be created and used. A table to hold the data is created.

### Actual behavior

An error occurs when fields of type "Comments" are created. The fields can be added to templates but no data can be stored.

### Steps to reproduce the issue

1. Install Processwire with DB Charset "utf8mb4" and DB-Engine "MyIsam"
2. Install Fieldtype "Comments"
3. Enable Debug-Logging
4. Add field of type "Comments". An error should be displayed
5. Check database for data table for the created field

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.59 <br />
PHP: 7.1.1-nmm1 <br />
Apache: Apache <br />
MySQL: 5.5.52-nmm1-log <br />
 <br />
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 30 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 60 <br />
max_input_vars: 3000 <br />
memory_limit: 256M <br />
post_max_size: 200M <br />
upload_max_filesize: 200M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite:  <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> JqueryDataTables: 1.9.4 <br />
ModulesManager: 2.1.6 <br />
PageSnapshot: 1.1.20 <br />
ProcessVersionControl: 1.2.4 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
ProtectedMode: 1.0.1 <br />
TracyDebugger: 4.3.1 <br />
VersionControl: 1.2.9 <br />
</details></details>

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate the issue here, but looking at the code I see a potential way for it to occur. Maybe it depends on MySQL version, but it's possible one of the indexes could be too large, so I've made some adjustments. I've pushed an update that includes this adjustment (along with some other code doc work in the same file). Please let me know if you find this does/doesn't fix the issue. Thanks.

**Comment by eidecker** [comment]
Works now. A data table is created for fields of type comments.
Thanks for the quick fix!
