### ISSUE TITLE
Update bundled HTMLPurifier

### ISSUE THREAD

**Issue by phlppschrr** [processwire/processwire-issues#243]
### description of the issue
currently the MarkupHTMLPurifier module bundles v4.8.0, most recent version is v4.9.2.
I noticed the outdated version, because using the option `HTML.TargetNoopener` gave me a warning.

### Optional: Suggestion for a possible fix
replace the bundled `htmlpurifier` folder with a recent version from here: http://htmlpurifier.org/download

### Steps to reproduce the issue

my test code which gave me a warning:
```
$value = $this->sanitizer->purify( $value, [
                        'HTML.AllowedElements'  => 'strong,b,em,i,p,a,ul,ol,li,br,pre,blockquote,cite,u,hr,dl,dd,dt',
                        'HTML.TargetBlank'      => true,
                        'HTML.TargetNoopener'   => true,
                        'HTML.TargetNoreferrer' => true,
                    ]
                );
```
### Setup/Environment
* ProcessWire version: ProcessWire 3.0.59

**Comment by ryancramerdesign** [comment]
I've been meaning to do this, thanks. I just pushed an update that updates to 4.9.2.
