### ISSUE TITLE
Undefined variable: buton in wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module

### ISSUE THREAD

**Issue by foger** [processwire/processwire-issues#247]
### Syntax error

processwire/wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module at line 586

### Fix:

Change "buton" to "button" :)

* ProcessWire version: 3.0.42
* PHP version: 5.6.29

**Comment by adrianbj** [comment]
Already fixed in dev: https://github.com/processwire/processwire/blob/bb12873a195a7eaf6e0b0ef19e36b0b13e3b4f4b/wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module#L586

**Comment by ryancramerdesign** [comment]
Closing this one since already fixed on dev.
