### ISSUE TITLE
When i want to create a new email field or clone existing email field getting error

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#248]
Working on fresh installed processwire with regular profile.

I am trying to create new email field or clone existing email field getting error :

Field name is : uk_email
```
SQLSTATE[HY000]: General error: 1089 Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
```
After this error field created, when i want to edit this field on template getting error again:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_test_processwire.field_uk_email' doesn't exist
```
After this error i checked database field created but, database table not created.

* ProcessWire version: 3.0.60
* (Optional) PHP version: 7.1.3
* (Optional) MySQL version: 5.6.35
* (Optional) Any 3rd party modules that are installed and could be related to the issue:
- Uikit Theme
- FieldtypeFontIconPicker
- PageTable extended
- Tracy Debugger

**Comment by ryancramerdesign** [comment]
In your /site/config.php file what are the settings for $config->dbEngine
and $config->dbCharset? Thanks.

On Tue, Apr 18, 2017 at 10:32 PM, Iskender TOTOĞLU <notifications@github.com

**Comment by trk** [comment]
```
$config->dbCharset = 'utf8mb4';
$config->dbEngine = 'InnoDB';
```
default options for regular profile

**Comment by trk** [comment]
Now if i want to create new field there is a warning message :
```
SQLSTATE[HY000]: General error: 1089 Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys (checkFieldTable)
```
![ekran resmi 2017-04-19 16 04 44](https://cloud.githubusercontent.com/assets/455983/25181351/f5626bc4-2519-11e7-992c-5a9ca4da1406.png)

**Comment by trk** [comment]
I commented these database settings, and changed my database settings to utf8 - utf8_unicode_ci. now its look like no problem for creation or editing field based pages or edit field settings.

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate it with those DB settings. It looks like we had an index that was a bit too long for utf8mb4+innodb combo. I've pushed a fix just now which corrects it.
