### ISSUE TITLE
Fields not nesting in fields setup screen when used inside repeaters.

### ISSUE THREAD

**Issue by elabx** [processwire/processwire-issues#249]
### Short description of the issue

Fields do not appear to nest when setting up fieldsets inside repeater's Repeater Fields setup. I would expect them to nest as in a normal template field setup. Both repeaters in the screenshot are already saved after adding the fieldsets.

### Optional: Screenshots/Links that demonstrate the issue

http://imgur.com/a/OGRDS

### Setup/Environment

* ProcessWire version: 3.0.52

**Comment by ryancramerdesign** [comment]
That nesting is something provided by the ProcessTemplate module, rather than asmSelect. As a result, you'll only see that kind of indented nesting support in the template editor.

**Comment by LostKobrakai** [comment]
Could we abstract the nesting feature in a separate module, so it can be used in multiple places? E.g. kongondo's menu builder is using a similar nesting feature, so maybe others could use it as well.

**Comment by teppokoivula** [comment]
It would be great if this behaviour was consistent across core features and built-in modules, such as Repeaters. Supporting third party implementations doesn't seem quite as important to me, but I wouldn't be against it either, especially if it's a relatively common need and makes things easier for module authors (and means less code repetition for us all) :)

**Comment by Toutouwai** [comment]
I think this issue has been fixed. In PW 3.0.125 fields inside a fieldset in a repeater are nesting/indenting correctly:

![2019-02-08_212931](https://user-images.githubusercontent.com/1538852/52466897-a7416a80-2be8-11e9-96a4-a0949165b380.png)

The indenting is not working in the current version of RepeaterMatrix (v4) but Ryan has provided the change that is needed in a forum post: https://processwire.com/talk/topic/20317-minor-issues-fieldsets-not-handled-as-per-fieldtyperepeater/?do=findComment&comment=176184

> Edit the config.php file in your FieldtypeRepeaterMatrix directory and around line 283 you'll see this:
> $select->setAsmSelectOption('sortable', true);
> Add this line right after it to enable the fieldset feature in AsmSelect: 
> $select->setAsmSelectOption('fieldset', true);
