### ISSUE TITLE
Incorrect 'Too common' when entering password

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#25]
### Short description of the issue

When adding a new user, the password box tells me the password is too common, even though it satisfies all of the requirements, but only if it has a `^` character in it.

### Expected behavior

When I type in `S7z^w5Fr` as the password, I expect it to tell me it is 'OK'.

### Actual behavior

It tells me it is "Too common"

### Steps to reproduce the issue

1. Create a new user
2. Enter `S7z^w5Fr` as the password
3. Notice it says "too common"
4. Now substitute the `^` for an asterisk or something, and suddenly the password is 'OK'

### Setup/Environment

* ProcessWire version: 3.0.35

**Comment by ryancramerdesign** [comment]
We are using a 3rd party library for making these determinations, and it gets pretty complex in its logic, but I do trust it. Apparently there's something about that combination of characters (using the "^") that prevents the password from meeting some threshold, while using the asterisk enables it to cross the threshold. Some of this can be adjusted from the password field settings if you want to make tweaks to it. But outside of that I have to place trust that the algorithm is doing what it should here.

**Comment by CaelanStewart** [comment]
A ^ is no more predictable than * in a random string. I can't see how that logic is, well, logical haha. Perhaps it is a bug in their software?

Regards,
Caelan Stewart

**Comment by CaelanStewart** [comment]
Also, it's happened a fair few times before. I only noticed this time as I saw that correlation with the '^' character. 

Regards,
Caelan Stewart

**Comment by ryancramerdesign** [comment]
I agree, I don't follow the logic either but also I don't have expertise in
the algo here. Who knows. :) This is purely a JS front end lib, and has
proved trustworthy. But the settings can be adjusted to make it less
aggressive here, which might be worth trying in the field settings. I'll
keep an eye to follow new versions of the front end lib as well.

**Comment by matjazpotocnik** [comment]
The character ^ ads 6 to complexity, while character * ads 10. Those two characters are in different range of characters in the table: ^ is in [0x005B, 0x0060] (6), * is in [0x0021, 0x002F] (10). Complexity factor is then computed using Math.log and Math.pow. The problem would also occur using [, \, ], _,  and `. You have 3 options:

1. Add one more character to the password
2. Change the Complexity factor in pass field to 0.69
3. Change MIN_COMPLEXITY in the js source from 49 to 48.2 or less

**Comment by mikerockett** [comment]
> We are using a 3rd party library for making these determinations ...

Interesting - I never knew this to be the case. What package is being used here?

**Comment by LostKobrakai** [comment]
@mikerockett https://github.com/processwire/processwire/tree/master/wire/modules/Inputfield/InputfieldPassword/complexify

**Comment by ryancramerdesign** [comment]
That's some pretty great detective work @matjazpotocnik

**Comment by CaelanStewart** [comment]
[An explanation from the author](https://github.com/danpalmer/jquery.complexify.js/issues/40), for those interested.
