### ISSUE TITLE
Add support for multiple response headers of the same type

### ISSUE THREAD

**Issue by gRegorLove** [processwire/processwire-issues#253]
### Short description of the issue
WireHTTP does not handle multiple response headers of the same type.

### Expected behavior
Return a nested array for headers when there are multiples of the same type.

### Actual behavior
Only one of the multiple values is returned.

### Optional: Suggestion for a possible fix

I have had a PR open (and examples) on the legacy branch: https://github.com/ryancramerdesign/ProcessWire/pull/1704 Let me know if you'd prefer I open a new PR against 3.x.

I saw PW3 is approaching an official release. I'd really like to get this in there before then if possible.

**Comment by ryancramerdesign** [comment]
Hi @gRegorLove I think this makes sense, but having a method that can return an array with differing types of values is something I usually try to avoid. Any end-user code that iterates it has to specifically check the type of every single value, something that's not desirable unless you specifically need it. Further, it would potentially break any code that's currently using the `getResponseHeaders()` method that isn't looking for arrays. So there's a couple reasons why I wouldn't want to adopt the change as shown in the PR. Given that, I've added a 2nd method to support multi-value headers: `getResponseHeaderValues()`. It provides the behavior you are looking for. Please let me know how it works for you.
