### ISSUE TITLE
$config->cli line in ProcessWire.php gives undefined index notice

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#255]
### Short description of the issue

In [ProcessWire.php](https://github.com/processwire/processwire/blob/3fc9f69da75e1bc4a3f0842f12a57bd6a1b65099/wire/core/ProcessWire.php#L261) there is a line that is meant to set the $config->cli variable if the interface is CLI.
`
$config->cli = (!isset($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' || ($_SERVER['argc'] > 0 && is_numeric($_SERVER['argc']))));`

But when PW is bootstrapped in a script triggered by a cron job, an error notice can result:
`PHP Notice:  Undefined index: argc in /home/myaccount/public_html/wire/core/ProcessWire.php on line 261`

This happens when the cron job calls the php-cgi binary instead of the php-cli binary. This can happen unintentionally because on some hosts the normal path of /usr/bin/php leads to the php-cgi binary (apparently this path changed [starting in EasyApache 4](https://documentation.cpanel.net/display/EA4/EasyApache+4+and+the+ea-php-cli+Package)).

Also, I have read that testing if php_sapi_name() == 'cli' is not a sufficient test for identifying the command line interface. See this comment: http://php.net/manual/en/function.php-sapi-name.php#89858

### Setup/Environment

* ProcessWire version: 3.0.61
* (Optional) PHP version: 7.0

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for that issue. With regard to php_sapi_name(), I really don't know of a 100% way for that, so hopefully `$config->cli` just covers the more common cases. It's true that there may be instances where you need to perform some other kind of check specific to your environment if `$config->cli` isn't providing what you need. Though if you've got changes to suggest I'm happy to implement them too.

**Comment by Toutouwai** [comment]
Thanks for the fix. $config->cli doesn't seem to be used anywhere in the core itself so I reckon it's fine for people to do their own CLI check if the built-in one isn't working for them.
