### ISSUE TITLE
Image upload through CKEditor not working

### ISSUE THREAD

**Issue by td-marc** [processwire/processwire-issues#256]
### Short description of the issue

When inserting an image through the CKEditor in your text, the file is not saved to the selected field.

### Expected behavior

Select image through CKEditor and save it to the field you select in the 'Select Image' modal.

### Actual behavior

I updated my website to PW 3.0.61 from 3.0.58 and now CKEditor can no longer successfully save image files. So I set up a testing environment with a vanilla 3.0.61 installation, same problem. **I can upload images directly to my 'images' field**, but CKEditor can not upload images to the same field. The image shows up in the CKEditor field after 'uploading' it, but after you save the page, no image was actually uploaded. There are no javascript errors. 

### Steps to reproduce the issue

1. Edit a page with a CKEditor field and an image(s) field.
2. In the CKEditor field, click on 'Image'.
3. Click on 'Upload Image'.
4. Click on 'Choose File' on your image(s) field and select an image file.
5. Click on 'Save'.
6. Click on your image and 'Insert Image'.
7. Save the page.

The image will show in the CKEditor but not in your image(s) field. On the front end, the image is not visible because it can not be found.

### Setup/Environment

* ProcessWire version: 3.0.61
* (Optional) PHP version: 7
* (Optional) MySQL version: MariaDB 5.5.54
* (Optional) Any 3rd party modules that are installed and could be related to the issue: no modules installed.
Browser: latest versions of Firefox and Chrome

**Comment by ryancramerdesign** [comment]
Thanks @td-marc I was able to duplicate and fix the issue, and it's now on the dev branch.
