### ISSUE TITLE
ProcessLogger shows wrong URL when $log is used in file that bootstraps PW

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#259]
### Short description of the issue

I have a file that bootstraps ProcessWire. When $log->save() is used in this file, ProcessLogger displays the URL as '/http404/'.

Is it possible for PW to detect when it has been bootstrapped and use some better URL here? I think the path/name of the PHP file would be good, but even no URL at all would be preferable to wrongly showing the 404 URL.

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
You can set what page should be used for the $page API variable with the `$config->externalPageID` setting. Set this to the ID of the page you want it to use, in your /site/config.php file.

**Comment by Toutouwai** [comment]
There isn't any existing page ID that would be any better than the 404 page - it would still be misleading because it does not indicate the file/url that actually wrote to the log. I guess I could especially create a page and name it the same as the PHP file but that seems like a weird way to work around the issue. It's not a major problem so I can live with the 404 url.
