### ISSUE TITLE
Can't create an OptionsField

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#26]
An SQL error appears when you create an "Options" field. 

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXX.fieldtype_options' doesn't exist`

### Steps to reproduce the issue

1. Install a blank version of Processwire 3.0.35
2. Install the core module "Select Options"
3. Create a field named "season" and type "Options"

### Setup/Environment

* ProcessWire version: 3.0.35 (master)
* (Optional) PHP version: 7.0.11
* (Optional) MySQL version: 5.5.52 (MariaDB)

**Comment by ryancramerdesign** [comment]
Not seeing that error here, but sounds like the options field didn't install correctly. You might try uninstalling the FieldtypeOptions module and re-installing. If that doesn't do it, please let me know your $config->dbEngine and $config->dbCharset.

**Comment by FlipZoomMedia** [comment]
I have already tried, unfortunately, the same error is also displayed during the uninstall process.

![screenshot-www xn--hhle-der-lwen-imbj com 2016-10-07 00-18-51](https://cloud.githubusercontent.com/assets/708183/19172771/e27d4428-8c23-11e6-90bd-15f4cd19e070.png)

DB Engine: MyISAM
DB Charset: utf8mb4

**Comment by ryancramerdesign** [comment]
Okay, I know what this is then. :) This one is about utf8mb4  and already
fixed on the dev branch, which will merge to master tomorrow.

**Comment by FlipZoomMedia** [comment]
Sounds good. :) Then I wait for the update. Thanks.

**Comment by ryancramerdesign** [comment]
If you need it now, feel free to grab the dev branch as it is in the repo
now. Should be able to fix it just by grabbing the updated FieldtypeOptions
module files.

**Comment by FlipZoomMedia** [comment]
Actually I just wanted to go to sleep, but it did not leave me any peace. :-D Thanks Ryan, with the current state of DEV it works. Good night from Germany.

**Comment by fluctusz** [comment]
hi ryan,
is this issue revived, have it her eon 3.0.35, tried the options module from the actual dev branch, no luck. also can`t uninstall module, cause can`t delete the damaged field :-)
thanks, martin

**Comment by fluctusz** [comment]
ok, have it working now by removing the field-table and reinstalling the module. solved with current dev-branch version of options field. sorry.
