### ISSUE TITLE
Page::changed hooks are not called

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#261]
### Short description of the issue
Page::changed hooks are not called
Any hooks in format Page::changed, Page::changed(field_name) or Page(template=template-name)::changed(field_name) are not being called.
### Expected behavior
code in Page::change hooks gets executed
### Actual behavior
code in Page::change hooks does not get executed
### Optional: Suggestion for a possible fix
Change [line 1005 in Wire.php](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/Wire.php#L1005)
from
```if(($hooks && $hooks->isHooked('changed')) || !$hooks) {```
to
```if(($hooks && $hooks->isHooked('changed()')) || !$hooks) {```
(note the prantheses after 'changed'
See [this forum post](https://processwire.com/talk/topic/16317-pagechanged-hook-not-called/?do=findComment&comment=144696)
### Steps to reproduce the issue
1. Step 1
place this code in admin.php
```
wire()->addHookAfter('Page::changed', function($event) {
	die('changed');
});
```
2. Step 2
In the admin open a page for editing, change some value and save the page -> nothing will happen. The hook will not fire.
### Setup/Environment
<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.62 <br />
PHP: 5.6.30 <br />
Apache: 2.4.18 (Ubuntu) <br />
MySQL: 10.1.20-MariaDB-1~jessie <br />
 <br />
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 60 <br />
max_input_vars: 1000 <br />
memory_limit: 128M <br />
post_max_size: 20M <br />
upload_max_filesize: 20M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension:  <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminThemeCustom: 0.1.7 <br />
FieldtypeAddressGeonames: 0.0.1 <br />
FieldtypeLeafletMapMarker: 2.0.6 <br />
FieldtypeTable: 0.1.7 <br />
InputfieldAddressGeonames: 0.0.1 <br />
InputfieldDependentCheckboxes: 1.0.0 <br />
InputfieldLeafletMapMarker: 2.0.7 <br />
InputfieldTable: 0.1.7 <br />
InputfieldTrumbowyg: 2.4.2 <br />
MemberChangeActions: 0.0.1 <br />
MemberEmails: 0.0.1 <br />
ProcessDatabaseBackups: 0.0.3 <br />
ProcessFeedback: 0.0.1 <br />
ProcessMigrator: 0.7.5 <br />
ProcessPageListerPro: 1.1.1 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
RedirectRole: 0.0.3 <br />
RenameEvents: 0.0.1 <br />
RestrictTabView: 0.0.9 <br />
TracyDebugger: 4.3.3 <br />
WireMailSmtp: 0.2.3 <br />
</details></details>

**Comment by ryancramerdesign** [comment]
Thanks @gebeer I have pushed your suggested fix to the dev branch.
