### ISSUE TITLE
Sort using "sort=parent.pagefield.subfield" throws an SQL exception

### ISSUE THREAD

**Issue by alguintu** [processwire/processwire-issues#263]
### Short description of the issue

Sorting a pagearray using "sort=parent.pagefield.subfield" throws an SQL exception

### Expected behavior

"sort=parent.pagefield.subfield" should sort the pagearray with the given sort parameter

### Actual behavior

Throws an SQL execption:
Error: Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pagefield' in 'order clause' (in /srv/rewwwards/wire/core/PageFinder.php line 410)

### Steps to reproduce the issue

1. Create a parent template with a page field (e.g. template 'mama', with 'spouse' page field)
2. Create any other template that will be the first template's child (baby)
3. Create pages with the two templates and set them as parent/child of each other
4. Try to select a child page and sort using parent's pagefield or parent's page field's sub-fields:
   $pages->find("template=baby, sort=parent.spouse.age");
   $pages->find("template=baby, sort=parent.spouse");
5. SQL exception will be thrown

### Setup/Environment

* ProcessWire version: 3.0.56
* (Optional) PHP version: 7.1
* (Optional) MySQL version: MariaDB 10.1

**Comment by ryancramerdesign** [comment]
You can use `sort=a.b` with some fields, but `sort=a.b.c` or not a supported syntax. We did recently add support for `a.b.c=` with Page fields, but that's for selection, not sorting. There aren't any cases where that type of field stack is supported after the operator. But knowing that someone was looking for it puts it on my radar, so I'll look into adding support in the future. Thanks.
