### ISSUE TITLE
Selector array with OR-group causes exception

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#264]
### Short description of the issue

When using an OR group with a selector array the parsing of field/value/operator breaks, causing an exception:

> Exception: Unknown Selector operator: '' -- was your selector value properly escaped? field='one', value='', selector: 'one' (in D:\Websites\__www\1testing\wire\core\Selectors.php line 396)

Code (for demonstration - I know this usage doesn't actually need an OR-group):

```php
$selector = [
    [
        'field' => 'title',
        'value' => 'one',
        'operator' => '%=',
        'group' => 'foo'
    ],
    [
        'field' => 'title',
        'value' => 'two',
        'operator' => '%=',
        'group' => 'foo'
    ]
];
$items = $pages->find($selector);
```

The same occurs when 'or' is used instead of 'group' to specify the OR-group.

### Setup/Environment

* ProcessWire version: 3.0.61

**Comment by mn-martin** [comment]
Here's a related forum thread to this issue: https://processwire.com/talk/topic/15523-selector-arrays-with-or/#comment-144775

**Comment by Toutouwai** [comment]
> Also wanted to mention that it would be better/more efficient to use this selector array below, for a case like the above, rather than using a OR-group

Yes, I mentioned in the issue description that the example is just for demonstration and doesn't actually need an OR-group.

Thanks for the fix.
