### ISSUE TITLE
$pages->find("sort=random") doesn't work as expected across pagination

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#266]
### Short description of the issue

When "sort=random" is used in a $pages->find() selector and the results are paginated, a new random sort is applied on each results page. This means that an item may appear more that once across the paginated results, and navigating back to or reloading a results page shows different results each time. 

### Expected behavior

The random sorting is applied only once across paginated results.

### Optional: Suggestion for a possible fix

A solution is to use [RAND(N)](https://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html#function_rand) in the SQL query instead of RAND(), where N is a seed value.

Not sure if there's a good way to be smart about automatically storing and using a seed across pagination so the user (i.e. PW developer) doesn't need to do anything special. 

Or if the existing behaviour for the 'random' keyword should be kept and a new keyword introduced for when a seed should be used, e.g. 'random($seed)' where $seed is an integer supplied by the user. It would be up to the user to supply a seed where needed and keep that across the pagination via GET or session variable. Of course this would be more demanding on the user than an automatic solution.

### See also
Related forum thread: https://processwire.com/talk/topic/16313-using-a-seed-when-getting-random-pages/

**Comment by LostKobrakai** [comment]
> Not sure if there's a good way to be smart about automatically storing and using a seed across pagination so the user (i.e. PW developer) doesn't need to do anything special.

Using a custom session value generated on login should suffice for basic usecases. But as this is not really random – not each refresh is random – it should probably be a new keyword. Maybe randomSession or so. With something like `$session->refreshRandomSeed()` the dev could handle user initiated reshuffling of content. 

Another option of storage would be a second GET parameter for pagination, but this one should be toggleable and not enabled by default.

**Comment by Toutouwai** [comment]
Re: automatic seed - the challenge is that at the time the initial random-sorted $pages->find() is done it's not known if "limit=x" will be used for just a single results PageArray or as part of paginated results.

I had some thoughts about an approach where a hash is created from the selector components (excluding start and limit) and a random integer also generated for use in RAND(N). Then the integer is stored in a session variable named by the hash. On subsequent find() operations a check is made to see if a session variable exists for that hash and if so the integer is used in RAND(N).

But perhaps overly complicated?

**Comment by LostKobrakai** [comment]
> But perhaps overly complicated?

That. 

The random seed will probably always be bound to the session and different selectors yield different results therefore different sorting anyways. So one seed per session should in theory be enough.

**Comment by ryancramerdesign** [comment]
I don't think that tying the existing "sort=random" to a seed is a good way to go here, because the intention with it is that it returns a random set. Previous calls are not meant to influence later calls. After all, someone may be doing multiple similar random calls in the same request. If a seeded sort=random is needed as a new feature, then I think we'd go with the `sort=random.$seed`, similar to what's suggested in the first post.

**Comment by netcarver** [comment]
@ryancramerdesign Does this need to be moved to processwire-requests?

**Comment by ethanbeyer** [comment]
Is it not possible to...

1. `$out = $pages->find(‘template=project, sort=random’);`
2. Cache `$out` with the session (too early for me to think about *how* to do that part)
3. Get the already shuffled PagesArray and paginate it

Maybe this wouldn’t work at all- I haven’t tested it at all, just a thought.

**Comment by ryancramerdesign** [comment]
You could do that but would have to load all the pages in a single request. That might not be practical, depending on the scale. What would be more practical is to load all the IDs (which is fast and takes up very little memory), store them in the `$session` or `$cache` and then convert them to a pagination for each request:
~~~~~~
$limit = 10;
$start = $limit * ($input->pageNum()-1);
$ids = $session->get('ids');
if(!$ids) $ids = $pages->findIDs("template=project, sort=random");         
$session->set('ids', $ids); 
$a = array_slice($ids, $start, $limit); 
if(!empty($a)) {
  $items = $pages->getByID($a)->setStart($start)->setLimit($limit)->setTotal(count($ids));
  echo $items->implode("<li>{title}</li>") . $items->renderPager();
}
~~~~~~
As far as having this in the core, I'm not sure it's a common enough use case to justify having it as a core feature. Plus, it doesn't take much code to do on your own. But if it comes up in the wild repeatedly then we could certainly add it. If you think it'll be a reoccurring request definitely feel free to add to the requests repo.

**Comment by Toutouwai** [comment]
Good idea for loading the IDs, thanks @ryancramerdesign.

I'm happy with that solution so will close this.
