### ISSUE TITLE
InputfieldSelect::addOptions produces unexpected result with regular array

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#268]
### Short description of the issue

I expected these two would produce the same result:

```php
$options = array('Red', 'Green', 'Blue');
foreach($options as $option) {
    $f->addOption($option);
}
```
```php
$options = array('Red', 'Green', 'Blue');
$f->addOptions($options);
```

But the latter produces options where the option value is an integer. I can see why this happens, but is this the intended result? The phpdoc comment says:

`@param array $options May be associative or regular array. If associative, use $value => $label. If regular, use just array($value, ...)`

I took this to mean that for a regular array only the values would be used in the resulting option and not the keys.

### Expected behavior

For a regular array, the same as individually adding options by foreach and addOption($value).

### Actual behavior

Array keys are used as option values, even if array is not associative.

### Optional: Suggestion for a possible fix

Distinguish between associative and regular arrays within addOptions():

```php
if(array_values($options) !== $options) {
    // associative array
    foreach($options as $k => $v) {
        $this->addOption($k, $v);
    }
} else {
    // regular array
    foreach($options as $option) {
        $this->addOption($option);
    }
}
```

**Comment by LostKobrakai** [comment]
Your example is a bit flawed, as there isn't a really good way to distinguish assoc arrays from non assoc ones besides checking for string keys and treating all integer keys as non assoc.

```php
$a = array("one", "two", "three");
unset($a[0]);
$a !== array_values($a); // true, a.k.a. assoc array as by your example
```
So what about the people needing the behaviour of integer keys being used as value. E.g. a common case would be page id's and titles: `[1 => "Home", 1000 => "Child", 1001 => "Another Child"]`

**Comment by ryancramerdesign** [comment]
> So what about the people needing the behaviour of integer keys being used as value. E.g. a common case would be page id's and titles: [1 => "Home", 1000 => "Child", 1001 => "Another Child"]

I think Toutouwai's suggestion would still work here, because of the array_values() call, which would convert the array keys to 0,1,2, rather than 1,1000,1001. Since the !== is used, the array keys and values would have to match before it would be considered a regular (non-associative) array. 

However, I think your point is still good, because what about the cases where someone wants to literally use values 0,1,2 and labels a,b,c? So you are right, we can't 100% know the intention. I think the best bet is for me to leave the function alone, but update the documentation for it to add clarity.

**Comment by ryancramerdesign** [comment]
I changed my mind about leaving the function alone, and instead added a second argument to it where you can specify your intention, if different from the original behavior. Thanks.
