### ISSUE TITLE
Can't change template system flag after mark template as system template

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#269]
I created a template manually from admin panel and saved this template as system template. If i want to remove system flag from this template can't success (from admin panel). Also i tried to change system flag via api can't success.

```php
$template = templates()->get($template_name);
$template->flagSystem = 0;
$template->save();
```

* ProcessWire version: 3.0.62
* PHP version: 7.1.4
* MySQL version: 5.6.35

**Comment by LostKobrakai** [comment]
This is expected behaviour.

From the notes of the field in the backend:
> If checked, this template will be defined as for the system and it won't be deleteable. Once the system flag is enabled, it can only be removed via the API (flagSystemOverride).

And here the flag: https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/Template.php#L121-L125

**Comment by trk** [comment]
I don't want to delete this template, i want to remove system flag.

I will try `flagSystemOverride`
