### ISSUE TITLE
Template files starting with ~ break templates admin

### ISSUE THREAD

**Issue by neonwired** [processwire/processwire-issues#272]
### Short description of the issue

If you have a php file prefixed with a ~ in the templates directory it causes this error 'ProcessWire: ProcessTemplate: Unknown Selector operator: '=~' -- was your selector value properly escaped? field='name', value='categories', selector: 'name=~categories'' and breaks the template admin.

### Expected behavior

~ shouldn't recognized as a selector. The error should be handled.

### Actual behavior

Processwire recognizes ~ as part of the selector rather than the file name. The error is not handled and breaks the template admin screen and causes it to be unusable,

### Steps to reproduce the issue

1. Create a template file named ~example.php
2. Login to admin and click on templates
3. Observe error.

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by Toutouwai** [comment]
When you use the name of a template in a selector it is the name of the _template_ and not the PHP _template file_ that should be used.

And you cannot name a template using the tilde character - the character is sanitized to an underscore.

**Comment by Toutouwai** [comment]
Edit: I get what you mean now - you have first created a template file named with a disallowed character, and then you try to add a new template within admin.

I agree that the error could be handled better.

**Comment by ryancramerdesign** [comment]
Just like with pages and fields, template names have to follow ProcessWire name format. Meaning, stick with -_a-zA-Z0-9. Other characters are not supported. However, the error that occurs when you try to add a new template–that's definitely not intended. What's intended is for it to just ignore the file. I've pushed a fix for that issue. Thanks.
