### ISSUE TITLE
$page->path show trailing slash when disabled for template

### ISSUE THREAD

**Issue by Keuvie** [processwire/processwire-issues#273]
$page->path show path with trailings slash, when trailing slash is disabled for a template
/page/pagename/

I expected the path would be without the trailing slash to skip an unnecessary redirect
/page/pagename

($page->httpUrl does not show this effect and works as expected)

**Comment by ryancramerdesign** [comment]
`$page->path` always has slashes as it represents the system's path to a page (which standardizes on trailing slashes). I think what you are looking for is `$page->url`, which represents the actual URL of the page, and does take trailing slash setting into account.

**Comment by Keuvie** [comment]
Hi Ryan,

Thank you for your clarification.
