### ISSUE TITLE
Ajax upload and drag 'n drop does not work for file fields (API use)

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#274]
### Short description of the issue

The file field in process modules (API use) is missing the Ajax upload functionality. Drag and drop isn't working.

### Screenshots/Links that demonstrate the issue

![drag](https://cloud.githubusercontent.com/assets/8448399/26525969/b7904bf0-4368-11e7-9727-0965b0d49d88.gif)

### Steps to reproduce the issue

1. Install module with class name	"ImportPagesCSV"
2. Select "Import Pages From CSV" from Setup menu
3. Try to drag and drop a file to the CSV file field - it does not work

### Setup/Environment
* ProcessWire version: 3.0.62

**Comment by Toutouwai** [comment]
Similar issue here: https://github.com/ryancramerdesign/ImportPagesCSV/issues/17
Answer was: "Drag and drop is only supported in the page editor at present."

**Comment by teppokoivula** [comment]
If it's difficult to support drag and drop outside of Page Editor, perhaps "drag and drop files in here" should be only be added (or displayed, so that it's there but hidden by default) only when drag and drop support *is* available? :)

**Comment by LostKobrakai** [comment]
We might need to differenciate a bit more here:

- Drag&Drop for selection: Totally possible and might be a nice addition.
- Drag&Drop + Instant upload: Only useful in the page editor, because elsewhere there's no fast way to reference the uploaded file with the submitted form.

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this issue. The "drop here" was not supposed to show outside the page editor, but it was unintentionally getting triggered to show by a window resize event.
