### ISSUE TITLE
Client side image resize not working with Max megapixels

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#275]
### Short description of the issue

When you set Max megapixels for uploaded images, the image is not resized. This is because the value entered "1.0" is saved as "1,0". I guess this has something to do with OS/system/locale settings for float numbers/decimals ("." vs ",").

### Optional: Suggestion for a possible fix

In InputfieldImage.js, insert this after line 1698:

data = data.replace(/,/g, '.');

### Setup/Environment

OS: Windows

**Comment by kixe** [comment]
I had similar issue here but also if dimensions exceeds.
### Short description of the issue
Client size resizing stucks for **jpg** if dimensions **OR** size exceeds.
**Max size is handled and stored correctly as float (even if displayed with comma).** 

### from console log

**in case of jpg (stucks)**
```
PWImageResizer: needsResize=Yes (dimensions exceed max allowed)  PWImageResizer.js:475:24
PWImageResizer: detecting JPEG image orientation...
```
OR
```
PWImageResizer: needsResize=Yes (megapixels exceeds 1)  PWImageResizer.js:475:24
PWImageResizer: detecting JPEG image orientation...
```

**in case of gif (works as expected)**
```
PWImageResizer: needsResize=Yes (dimensions exceed max allowed)  PWImageResizer.js:475:24
PWImageResizer: original image size: 700x700 px  PWImageResizer.js:475:24
PWImageResizer: scaled image size: 100x100 px via max width/height of 100x100
```

**in case of svg (works as expected)**
```
PWImageResizer: needsResize=Yes (dimensions exceed max allowed)  PWImageResizer.js:475:24
PWImageResizer: original image size: 700x700 px  PWImageResizer.js:475:24
PWImageResizer: scaled image size: 100x100 px via max width/height of 100x100  PWImageResizer.js:475:24
PWImageResizer: needsResize=No (megapixels below 1)
```

### Setup/Environment
Mac OS 10.12.4
Firefox 53.0.3
Safari 10.1

**Comment by ryancramerdesign** [comment]
Thanks, I was able to fix the issue that @matjazpotocnik mentioned. Also was able to duplicate at fix the issue @kixe mentioned (after testing in Safari). Turned out to be a bug in the exif.js library per this issue and suggested fix in their repo issue reports: https://github.com/exif-js/exif-js/issues/95

**Comment by matjazpotocnik** [comment]
It's working now, but I stil find it odd that the value you enter in Max megapixels input field is converted from "0.9" to "0,9". 

One typo:

> When using client-side resize ...

**Comment by matjazpotocnik** [comment]
@kixe can this be closed?
