### ISSUE TITLE
text (for translation) in InputfieldImage.module

### ISSUE THREAD

**Issue by Manfred62** [processwire/processwire-issues#276]
### text disordered?

InputfieldImage.module, line 845: 
at first it's 1600x ***1000*** px. After that it's named 1600 and ***1200*** px.

### Optional: Suggestion for a possible fix

Think the pixel values should be the same?

### Setup/Environment
* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
Thanks, good catch, I've fixed the issue.
