### ISSUE TITLE
InputfieldSelect addOptions() confusing

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#280]
I'm not sure if it's really doing what it says. 

https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldSelect.module#L74

If I add options via regular (not assoc) array for convenience:

```$f->addOptions(array(value1, value2))``` 

doesn't give me the same results as if I add them one by one using 

```
$f->addOption(value1)
$f->addOption(value2).
```

addOptions() results in having the values used only as labels and not as the value. values are being set a [0,1,2].

Seems wrong to me. To have values also set the same one has to set them as associative like:

```
addOptions(array(value1 => value1, value2 => value2);
```

I'm not sure changing this behavior would certainly break compatibility. But this is something not only me struggled over.

**Comment by matjazpotocnik** [comment]
Related? https://github.com/processwire/processwire-issues/issues/268

**Comment by somatonic** [comment]
Ah thx I searched for it, but guess not closed ones.
