### ISSUE TITLE
Repeater label should not have forced # symbol before item index

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#284]
### Short description of the issue

When `#n` is used in the "Repeater item labels" setting to represent the index number, a literal # symbol is included in the label. This means it isn't possible to get the index number alone using this setting.

`#n` should be replaced with only the index number. If you actually want a # symbol you could then use `##n`.

* ProcessWire version: 3.0.63

**Comment by LostKobrakai** [comment]
> #n should be replaced with only the index number. If you actually want a # symbol you could then use ##n

Breaking current setups for such a change is not really desirable. But there are probably different solutions to add a key for "just the index".

**Comment by Toutouwai** [comment]
> Breaking current setups for such a change is not really desirable.

Good point.

@ryancramerdesign, to get rid of the # symbol I hooked renderRepeaterLabel() to build my own custom label, and after spending some time puzzling over why the index of my new repeater items was always "1" I discovered that the index is [corrected via Javascript](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.js#L468-L471).

So does the # exist just to give the JS replace something to match against? This JS correction seems not ideal to me - for new items is it not possible to supply the correct index argument to renderRepeaterLabel()?

**Comment by LostKobrakai** [comment]
New items are only added in js (it clones a bunch of html), therefore the index has to be supplied by javascript as well initially.

-- 
www.kobrakai.de | Bauernstraße 5B | 86508 Rehling | 015221616149

**Comment by kixe** [comment]
@Toutouwai 
This is not a real issue since you can adapt it very easy for your needs.

1. If you don't mind about zero based index you can use **{sort}** or **{index}** as a placeholder.
2. If you need a one based index just add a **property** to the **RepeaterPage** object with this oneliner in your **ready.php** and pull the value via placeholder **{oneBasedIndex}** as usual.
`wire()->addHookProperty('RepeaterPage::oneBasedIndex', function($e) { $e->return = $e->object->index + 1; });`

**Comment by Toutouwai** [comment]
@LostKobrakai, the javascript for adding the new repeater item makes an AJAX request that is processed by InputfieldRepeater.module, so the repeater label – including the index number if that is used – is set by InputfieldRepeater::renderRepeaterLabel().

@kixe,
{sort} gives values that can be all over the place if repeater items were deleted in a previous page save.
![2017-06-05_140109](https://cloud.githubusercontent.com/assets/1538852/26767871/d9a33064-49f7-11e7-8f20-080cd3c1e3f8.png)

{index} has the same problem as hooking renderRepeaterLabel() which I am already doing. The index (or $cnt argument to renderRepeaterLabel) stays the same for each new item.
![2017-06-05_140153](https://cloud.githubusercontent.com/assets/1538852/26767942/72a553be-49f8-11e7-95ac-fcdb1c3832d2.png)

This happens because of the way items in the repeater field are [skipped over](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L305) when an $itemID is supplied to the buildForm() method, which happens when a new repeater item is added. Currently the index number has to be [corrected via javascript](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.js#L468-L471), and I'm not sure but it seems like the # character in included with the index number just so that the javascript replace has something it is able to match against.

It seems to me it would be better to get the index/$cnt correct in PHP rather than replace the incorrect index with javascript. At a glance it looks like this would do the trick: [where the $cnt variable is set](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L298)...

```php
$cnt = 0;
if($itemID) $cnt = $this->value->count() - 1;
```

**Comment by kixe** [comment]
@Toutouwai
> {index} has the same problem as hooking renderRepeaterLabel() which I am already doing. The index (or $cnt argument to renderRepeaterLabel) stays the same for each new item.

Sorry. I didn't get that you want updated values already before saving.

To get what you expect use **sort** and update sort before rendering. If you don't find it to expensive put the following code in your **ready.php**
Now **#n** should always be similar to **{oneBasedIndex}** off course without **#**:
```
wire()->addHookBefore('InputfieldRepeater::render', function($e) {
	$pageArray = $e->object->attr('value');
	foreach ($pageArray as $key => $RepeaterPage) {
		if ($RepeaterPage->sort == $key) continue;
		$RepeaterPage->sort = $key;
		$RepeaterPage->save('sort');
	}
});
wire()->addHookProperty('RepeaterPage::oneBasedIndex', function($e) { $e->return = $e->object->sort + 1; });
```

**Comment by Toutouwai** [comment]
I still think the forced # symbol is undesirable and the way that index numbers are handled is pretty weird, but I can see that this couldn't be fixed without potentially breaking other people's setups, so will close this.
