### ISSUE TITLE
markup regions attributes are not removed from final output

### ISSUE THREAD

**Issue by nurkka** [processwire/processwire-issues#285]
### Short description of the issue

Quote from the documentation:

> If you don't like using "id" attributes, you are also welcome to use "pw-id" or "data-pw-id" attributes instead. They do the same thing, but only ProcessWire can see them – **they are removed from the final output and thus not visible to front-end markup,** CSS or JS.

https://processwire.com/blog/posts/processwire-3.0.62-and-more-on-markup-regions/#defining-regions

When using markup regions with e.g. "before"-actions, the data-pw-attributes aren't removed from the final markup output:

_main.php:

```
<div class="container">
	<div data-pw-id="main_content">...</div>
</div>
```

home.php:

```
<section data-pw-before="main_content">...</div>
```

### Actual vs. expected behavior

Resulting final frontend markup:

```
<div class="container">
	<section>...</section>
	<div data-pw-id="main_content">...</div>
</div>
```

While it should be:

```
<div class="container">
	<section>...</section>
	<div>...</div>
</div>
```

### Suggestion for a possible fix

All data-pw-attributes should be removed from the final output.

**Comment by ryancramerdesign** [comment]
Thanks, I've just pushed a fix that should correct this issue.

**Comment by nurkka** [comment]
Thanks Ryan! Currently, I am using PW 3.0.67, where the issue is corrected ... but: I noticed that, if one doesn't override any of the defined markup regions, the data-pw-attributes are not removed from the final output. If one overrides at least one markup region, everything works as expected. 

In my case, I have a basic-page template which doesn't override any markup regions, and a contact-page template, which overrides some of them. Therefore the data-pw-attributes are not removed in 99% of my pages, just on the contact page.

**Comment by netcarver** [comment]
@nurkka This issue is quite dated now. Do you consider this adequately fixed? Can this issue be closed?
