### ISSUE TITLE
repeater fields appear in choosing a template

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#287]
https://processwire.com/talk/topic/16504-on-page-template-there-are-non-exisiting-repeater-fields/#comment-145956

### Short description of the issue

After creating a repeater field it appears for choosing as a template.

### Expected behavior

Should not be so.

### Optional: Screenshots/Links that demonstrate the issue

see in my talk entry.

### Setup/Environment
* ProcessWire version:  ProcessWire 3.0.61
* PHP version: 7.0.17 and 5.6.30
* MySQL version: 5.5.52

**Comment by ryancramerdesign** [comment]
I can't duplicate this one here. Is it possible you've got advanced mode enabled? ($config->advanced). What other modules are installed on the Modules > Site tab? If you go to Setup > Templates, do you see your Repeater templates there too, or do you only see them if enabling System templates via the filters?

**Comment by beatep** [comment]
I just wanted to write, that the problem appears still in 3.0.74.

Do you want to login to this new page?

**Comment by abmcr** [comment]
https://processwire.com/talk/topic/17304-repeater-fields-appears-in-template-settings-of-any-page/?do=findComment&comment=151971

this solve the problem

**Comment by ryancramerdesign** [comment]
I misunderstood the problem, but now understand per the reference you put in #388 so this should now be fixed. Thanks.

**Comment by netcarver** [comment]
@beatep Hello! Could you please close this issue if it is fixed for you now. Thank you!
