### ISSUE TITLE
"Save + Publish + Add Another" does not add page to PageTable field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#288]
### Short description of the issue

When adding a new page to a PageTable field using a title-only template, a "Save + Publish + Add Another" button is shown.

![2017-06-09_090904](https://user-images.githubusercontent.com/1538852/26950882-5d5899be-4cf3-11e7-8913-1a05fc56e6ba.png)

The expectation is that clicking this button saves, publishes and adds another page _to the PageTable field_. But if this button is used the pages are not added to the PageTable field, apart from the last page saved before the dialog is closed.

### Expected behavior

Either the button adds pages to the PageTable field, or the button is never shown when adding a PageTable page.

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
Thanks, that 'add another' isn't supposed to show there, I've pushed a fix for this issue. What are the two "A" letters that appear in the right side of your Title field?

**Comment by Toutouwai** [comment]
Thanks for the fix.

> What are the two "A" letters that appear in the right side of your Title field?

It's an [AdminOnSteroids feature](https://github.com/rolandtoth/AdminOnSteroids/wiki#misc):

> Add toggle button to change case of Page title field: adds a button to the right side of the title field which allows looping through cases of the text (original, sentence case, capitalize, uppercase, lowercase).
