### ISSUE TITLE
Sort by repeater count

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#289]
### Short description of the issue

You are unable to sort by repeater count, however count is accessible by $page->repeater->count but $pages->find("template=repeater-template, sort=repeater.count"); 
doesn't work.

https://processwire.com/talk/topic/16502-sort-by-repeater-count/#comment-145983

### Expected behavior

Should sort by repeater count. 

### Actual behavior

Doesn't sort correctly. 

### Steps to reproduce the issue

1. Create repeater
2. Try to sort pages by repeater

### Setup/Environment

* ProcessWire version: 3.0.63
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks Tom, I've pushed a fix for this.
