### ISSUE TITLE
Array to String Conversion line 135 of WireLog.php

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#29]
### Short description of the issue

Array to String Conversion line 135 of WireLog.php

### Expected behavior

No error

### Actual behavior

The above error

### Optional: Suggestion for a possible fix

I think this might be a new error with PHP7 not interpreting `$option[delimiter]` correctly.
```
$text = "$url$options[delimiter]$text";
```

You might also want to fix line 140:
```
$text = ($user && $user->id ? $user->name : "?") . "$options[delimiter]$text";
```

**Comment by ryancramerdesign** [comment]
Adrian, I'm also running PHP7 but not seeing this error. What steps are necessary to observe the error?

**Comment by adrianbj** [comment]
Sorry for the confusion - it turns out this only happens if you try to send an array as the text to the log file, so this is probably a very valid message as this is a silly thing to do. I guess my only suggestion might be to automatically `json_encode()` arrays. I am not sure if that would be a worthwhile convenience, or a confusion and users should do it themselves if they wish.

I am guessing the latter, so please feel free to close this.

**Comment by ryancramerdesign** [comment]
I think we'll keep the error message here since arrays aren't supported. Might save someone time trying to track down why their log entry is showing up as json at some point. :)
