### ISSUE TITLE
Js error after click on ".InputfieldImageEdit__name"

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#290]
### Short description of the issue
When I try to rename image in image field I get js error 
`Error: cannot call methods on sortable prior to initialization; attempted to call method 'disable'`

### Expected behavior

Sortable should be disabled on image grid while you edit name of image

### Actual behavior

It happens after click on ".InputfieldImageEdit__name span" and error is referred to InputfieldImage.js line 604
`
$list.sortable('disable');
`

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Change 
`$list.sortable('disable');`
to
`
$list.sortable({
    disabled: true
});
`
### Steps to reproduce the issue

1. Upload image and save a page 
2. Click on the uploaded image and click on file name.
### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. I've tried uploading a few images and immediately renaming them, but not seeing a JS error. Any specific image grid mode or key combination that you are finding triggers it?

**Comment by Lazerproof** [comment]
Hi @ryancramerdesign 
I got the same error on 3.0.67.

Take a look at screen capture. 
![rename-image](https://user-images.githubusercontent.com/5707348/28727610-2c2a8738-73ce-11e7-9212-314a2cc69c86.gif)

**Comment by gmclelland** [comment]
I tried, but couldn't reproduce the problem on my end using Google Chrome.  You might want to specify in the issue what web browser you are using?  I'm using the latest PW 3.0.72.

You might also try with a reduced test case without multilingual, Google Maps, etc... to help narrow down your issue.
