### ISSUE TITLE
FieldtypeRepeater should hide clone option in settings

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#295]
### Short description of the issue

Repeater fields throw an error when attempting to clone them via the "Duplicate/clone this field?" setting: "ProcessWire: ProcessField: Sorry, repeater fields are not currently cloneable." Along with "The process returned no content".

If the field is not cloneable then better to simply not show the Duplicate/clone option.

### Expected behavior

Only field settings that are applicable to the current field are shown.

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
As a matter of keeping things simple, I try and avoid having code in one module check for specific cases of other modules, instead preferring to abort it with an exception from the Fieldtype when there's a rare case like this. ProcessField doesn't need to have repeaters code in it. Maybe later we can eventually have something added to the Fieldtype interface, like an isCloneable() method or something. But I don't think there's enough cases to justify adding this to the Fieldtype interface at present. The important thing is that it doesn't let you proceed with the clone that could be problematic.

**Comment by Toutouwai** [comment]
Fair enough. Although it would be possible to remove the "Clone" field without touching ProcessField. FieldtypeRepeater is autoload so you could hook ProcessField::buildEditFormInfo, get the field object via the id POST/GET variable as in ProcessField::init and then remove 'clone_field' according to whether the field is an instance of FieldtypeRepeater. But it's not a big deal so will close.
