### ISSUE TITLE
MarkupQA  - Call to a member function isSuperuser() on null

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#296]
Error:
Uncaught Error: Call to a member function isSuperuser() on null in /kunden//wire/core/MarkupQA.php:76
Stack trace:
/kunden//wire/modules/Fieldtype/FieldtypeTextarea.module(158): ProcessWire\MarkupQA->__construct(Object(ProcessWire\Page), Object(ProcessWire\Field))
/kunden//wire/modules/Fieldtype/FieldtypeTextarea.module(238): ProcessWire\FieldtypeTextarea->markupQA(Object(ProcessWire\Page), Object(ProcessWire\Field))
/kunden//wire/modules/Fieldtype/FieldtypeTextarea.module(221): ProcessWire\FieldtypeTextarea->_htmlReplacement(Object(ProcessWire\Page), Object(ProcessWire\Field), '< h3 >Mit einem B...', false)
/kunden//wire/modules/Fieldtype/FieldtypeTextarea.module(134): ProcessWire\FieldtypeTextarea->htmlReplacements(Object(Proce (line 76 of /kunden//wire/core/MarkupQA.php)

Error occured when setting autojoin for the a textarea field.
But: Only one field body is the problem, a field body2 (same settings) not.
Looks like a rare bug.

Was true
$config->debugMarkupQA = true;
after switching that off, still ~~I get mails occasionally with that error note~~ error messages stopped. 
_(edited)_  

This is an old webpage... I now I could clean up modules some time...
MODULES:
Class	Version	Title
AdminThemeDefault	14	Default
AdminThemeReno	17	Reno
FieldtypeText	100	Text
FieldtypeURL	101	URL
FieldtypeFile	104	Dateien
FieldtypeInteger	101	Integer
FieldtypeDatetime	104	Datetime
FieldtypePassword	101	Password
FieldtypeFieldsetOpen	100	Fieldset (Open)
FieldtypePageTable	8	ProFields: Page Table
FieldtypePage	104	Page Reference
FieldtypeImage	101	Images
FieldtypeModule	101	Module Reference
FieldtypeRepeater	106	Repeater
FieldtypeFieldsetClose	100	Fieldset (Close)
FieldtypePageTitle	100	Page Title
FieldtypeCheckbox	101	Checkbox
FieldtypeTextarea	106	Textarea
FieldtypeEmail	100	E-Mail
MarkupPageArray	100	PageArray Markup
MarkupCache	101	Markup Cache
PageRender	105	Seiten-Rendering
InputfieldSelector	27	Selector
ProcessPageSearch	106	Page Search
ProcessPageClone	103	Seite klonen
LanguageSupport	103	Languages Support
LanguageSupportFields	100	Languages Support - Fields
LanguageSupportPageNames	9	Languages Support - Page Names
PagePermissions	105	Page Permissions
SystemUpdater	16	System-Updater
FieldtypeNotifications	4	Notifications
SystemNotifications	12	System Notifications
JqueryUI	196	jQuery UI
JqueryCore	183	jQuery Core
JqueryTableSorter	221	jQuery Table Sorter Plugin
SessionHandlerDB	5	Session Handler Database
LazyCron	102	Lazy Cron
FieldtypeTextUnique	100	Text Unique
ProcessChangelogHooks	1.1.10	Changelog Hooks
CronjobDatabaseBackup	115	Cronjob Database Backup
ProcessWireUpgradeCheck	7	Upgrades Checker
ProcessLoginHistoryHooks	1.2.1	Login History Hooks
PasswordForceChange	18	Force Password Change
FieldtypeConcat	106	Concat
LoginNotifier	102	Login Notifier
SchedulePages	122	Schedule Pages
MarkupCookieConsent	32	Markup Cookie Consent
BatchChildEditor	1.6.6	Batch child editor
ProcessPageCloneAdaptUrls	0.0.4	Adapt URLs after Cloning
TracyDebugger	4.3.5	Tracy Debugger
MaintenanceMode	107	Maintenance Mode
VersionControl	1.2.9	Version Control
PageSnapshot	1.1.20	Page Snapshot
FieldtypeTable	17	ProFields: Table
FormBuilder	31	Form Builder
SessionLoginAlarm	120	Session Login Alarm
ProfilerPro	1	Profiler Pro (Main)
FieldtypePageTableExtended	233	PageTable extended
PageEditSoftLock	101	Page Edit Soft Lock
ProcessPageEditSoftLock	101	Process Page Edit Soft Lock
PageListPin	100	Page List Pin
ProCache	316	ProCache
AdminOnSteroids	148	AdminOnSteroids
PrevNextTabs	5	Prev/Next Tabs
FormSaveReminder	106	Form Save Reminder
PageTreeAddNewChildsReverse	102	Pagetree Add New Childs Reverse
ProcessPageEditFoldStatus	0.1	Process Page Edit Fold Status
PageEditFoldStatus	010	Page Edit Fold Status
ModuleSettingsImportExport	0.2.4	Module Settings Import Export
HannaCodeHelper	50	Hanna Code Helper

Addition: The textarea mentioned in the error stack had nothing fancy. Just text, no links:
< h3 >Mit einem B

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this one, but the error seemed to indicate that there was no "user" API variable present. Was PW being bootstrapped from something else, or using command line mode? I went ahead and added a check for the `$user` API variable in the location mentioned in the exception, even though I can't duplicate the issue. Please let me know if you continue to experience issues. Thanks.

**Comment by tbba** [comment]
Hm. The user api variable _is_ present, the frontend shows some extra things in that case.
No idea what has confused it in this case but your fix worked - The critical error is _gone_ - Thank you!
