### ISSUE TITLE
WireArray won't import Array

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#297]
### Short description of the issue

I cannot import an array into a new WireArray.

### Expected behavior

```php
$test = ['one' => 'string', 'two' => 'another string'];
$a = new WireArray();
$a->import($test);
```

### Actual behavior

Using the same code, this error is thrown:
`Exception: Item 0 set to ProcessWire\WireArray is not an allowed type (in /var/www/public/wire/core/WireArray.php line 431)`

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

According to the documentation for `WireArray::set()`:

```php
	/**
	 * Set an item by key in the WireArray.
	 * 
	 * #pw-group-manipulation
	 *
	 * @param int|string $key Key of item to set.
	 * @param int|string|array|object|Wire $value Item value to set.
	 * @throws WireException If given an item not compatible with this WireArray. 
	 * @return $this
	 *
	 */
	public function set($key, $value) {}
```
It should be possible to import an array into a WireArray - but since `$test` is not derived from`Wire`, it is not valid. I'm confused by this behavior.

### Steps to reproduce the issue

1. Step 1
2. Step 2
3. Step 3

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by kixe** [comment]
The value of a WireArray item needs to be an instance of Wire. Using the methods **import()** or **setArray()** the argument could be a **WireArray object** or a simple **array of Wire objects**.
```
$wireObject = new WireData;
$anotherWireObject = new WireData;
$array = ['one' => $wireObject, 'two' => $anotherWireObject];
$wireArray = new WireArray;
$wireArray ->import($array);
```

**Comment by szabeszg** [comment]
It would be great to have some methods which convert from plain array to WireArray and vice versa. Are there any? I do not seem to find... This is how I construct a menu, for example:
```
$siteMainMenu = new WireArray();
$menuItem = new WireData();
$menuItem->set("title", "home");
$menuItem->set("url", "");
$siteMainMenu->add($menuItem);
$menuItem = new WireData();
$menuItem->set("title", "about us");
$menuItem->set("url", "about-us/");
$siteMainMenu->add($menuItem);
```
It is "standard OOP style", but it is rather verbose. By constructing a simple associative array and then converting its data into WireArray by a simple method call would be great, for example. And there are lots of other use cases as well, I guess.

**Comment by LostKobrakai** [comment]
I wouldn't call this oop style at all, but really converting arrays is not that difficult.

```php
$array = [
     ['title' => 'a', 'url' => ''],
     ['title' => 'b', 'url' => 'b/'],
     ['title' => 'c', 'url' => 'c/'],
];

$wireArray = array_reduce($array, function($wireArray, $navItem) {
    return $wireArray->add((new WireData)->setArray($navItem));
}, new WireArray);
```

Or in OOP style
```php
class NavArray extends WireArray {
    public function importSetupArray($items) {
        $wiredItems = array_map(function($item) {
            return (new WireData)->setArray($navItem);
        }, $items)

        return $this->import($wiredItems);
    }
}

$navArray = (new NavArray)->importSetupArray($array);
```

Always keep in mind that most core classes are meant to handle core concerns, but like the core does with e.g. PageArrays you can also just extend those classes to cater to your issues.

**Comment by ethanbeyer** [comment]
I appreciate all of your responses to this! I understand that this "issue" is actual a design decision. 

I'm sure this has been explored by the core devs for a long time, but I wonder if someone could illuminate for me why items have to be Wire-derived? Security?

It seems to me that the import command could have a `convert` flag, allowing a vanilla array to become a `WireArray`. I have modules and items from forms that would benefit hugely from `Wire` methods - and the ability to quickly convert an array to a `WireArray` seems logical to me.

Thoughts?

**Comment by LostKobrakai** [comment]
It's not being developed as general purpose collection library (try this one: [tightenco/collect](https://github.com/tightenco/collect)), but it's a more or less low level part of the framework. Any class of the framework is Wire derived, therefore it makes sense to have only Wire instances as items. This way the WireArray class can depend on/use any functionality provided by the Wire base class, which wouldn't be possible otherwise. If you really need a different behaviour from it extend it into your own class and overwrite the `isValidItem()` method. Not the cleanest way, but gets the job done. 

I'll close this here, as it's not an issue, but a design decision.

**Comment by Toutouwai** [comment]
> I have modules and items from forms that would benefit hugely from Wire methods

I think most things that you can do with WireArray methods you can also do with the built-in PHP [array functions](http://php.net/manual/en/ref.array.php). Maybe open a forum topic to discuss this further.
