### ISSUE TITLE
Update CKEditor To v4.7

### ISSUE THREAD

**Issue by Mustafa-Online** [processwire/processwire-issues#298]
Update CKEditor To v4.7

**Comment by cb2004** [comment]
This was implemented a couple of hours ago now. @ryancramerdesign tends to be a mind reader:

https://github.com/processwire/processwire/commit/438a2944cbdfdf0477cc862fc05a33066560c8cd

**Comment by Mustafa-Online** [comment]
He is 😍 Thanx
