### ISSUE TITLE
FieldtypeComments ignores 'dateFormat' setting from module config

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#299]
### Short description of the issue

The comments list uses the "relative" option for the comment date/time even when a date format is specified in the "Date/time format (for comment list)" config setting.

### Expected behavior

If nothing contrary is specified in the $options array when rendering the comments list, the setting defined in the module config is used.

### Actual behavior

A relative time is always shown in the comments list (unless a date format is supplied in an $options array is supplied when the comments list is rendered).

### Optional: Screenshots/Links that demonstrate the issue

This setting is ignored:

![2017-06-26_110246](https://user-images.githubusercontent.com/1538852/27520394-08d92ea2-5a5f-11e7-9bc7-aa9b4effc147.png)

### Optional: Suggestion for a possible fix

Check the field settings when [defining the defaults](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Fieldtype/FieldtypeComments/CommentArray.php#L89-L95):

```php
$defaultOptions = array(
    'useGravatar' => ($this->field ? $this->field->get('useGravatar') : ''),
    'useVotes' => ($this->field ? $this->field->get('useVotes') : 0),
    'useStars' => ($this->field ? $this->field->get('useStars') : 0),
    'depth' => ($this->field ? (int) $this->field->get('depth') : 0),   
    //'dateFormat' => 'relative',
    'dateFormat' => ($this->field ? $this->field->get('dateFormat') : 'relative'),
    );
```

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
Thanks! I've pushed your suggested fix to the dev branch.

**Comment by Toutouwai** [comment]
Thanks for the fix.
