### ISSUE TITLE
Error: strpos() expects parameter 1 to be string, array given on line: 96 in /wire/core/PageComparison.php

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#30]
### Short description of the issue

Error: strpos() expects parameter 1 to be string, array given on line: 96 in /Users/ajones/Sites/ecoreportcard/wire/core/PageComparison.php

### Expected behavior

No error

### Optional: Suggestion for a possible fix

This might be hard for you to reproduce - I am seeing it with a complicated API script and I haven't yet figured out what part of it is initiating this. 

This is the array that is being returned:
```
array (2)
0 => "has_parent"
1 => "id"
```

Trouble is I am not sure if we should be figuring out why `$property` is an array in this situation, or whether it's ok to just check for an array and not proceed with trying to explode since it's already an array.

If you think we need to figure out why `$property` is an array, let me know and I'll try to isolate it.

**Comment by ryancramerdesign** [comment]
I think the issue here is that a database-style selector with an array of field values is getting sent to Page::matches() where it isn't supported. I've pushed an update that converts the array to a string. Thanks.
