### ISSUE TITLE
Markup regions are not being removed if the template file is blank

### ISSUE THREAD

**Issue by cb2004** [processwire/processwire-issues#302]
### Short description of the issue
With markup regions switched on (fresh install today so no need for $config->useMarkupRegions = 2) and if a template file is blank, the markup regions are not removed:

`<pw-region pw-id="css-cdn"></pw-region>`

This is still in the output.

### Expected behavior

Markup code should be removed

### Actual behavior

Markup code is not removed

### Setup/Environment

* ProcessWire version: 3.0.65

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. In my testing here, the `<pw-region...` is completely removed. What file specifically are you putting that code in? Since it's a region definition, I'm assuming _main.php, but wanted to double check.

**Comment by cb2004** [comment]
Yes the in _main.php there is `<pw-region pw-id="css-cdn"></pw-region>`, then lets say I have a template called page, is there is nothing in the page.php template file then the above pw-region is still present in the code.

**Comment by ryancramerdesign** [comment]
Strange, I can't duplicate it here. Anything unique about the placement of it? I pasted your code at the bottom of my _main.php file, but above the closing body tag.

**Comment by cb2004** [comment]
Its in the <head> section of the file. The site is under development at the moment so I can ping you FTP access by email should you require it?

**Comment by cb2004** [comment]
This is an odd one as sites which were setup pre 3.0.65, then upgraded to 3.0.65 are not behaving like this and they have exactly the same setup.

**Comment by cb2004** [comment]
Further testing, this happens with all the sites I have on 3.0.65. Just to double check you have a blank home.php file during testing?

**Comment by Toutouwai** [comment]
I can confirm this issue. If you have a template file that does not contain any markup then any `<pw-region>` tags in the auto-appended _main.php appear in the front-end source for any page using that template.

**Comment by cb2004** [comment]
I also have <main pw-id="main"> where the pw-id remains. It's as if markup regions is not initiated when it has no instructions.

**Comment by cb2004** [comment]
Have you been able to duplicate @ryancramerdesign? I have pages which do not validate because of this and I don't really want to populate template files if they have the same requirements as in _main.php

**Comment by Toutouwai** [comment]
@ryancramerdesign, could you please take another look at this issue?

I think it's a common scenario to have _main.php consist of the markup for the most frequently used template (e.g. basic-page) and for basic-page.php to contain no markup region modifications. And in this scenario `<pw-region>` tags are not removed from the final output.

The problem is [here](https://github.com/processwire/processwire/blob/5a39c9efc9232f37dd0379013a45eb3b280b4421/wire/modules/PageRender.module#L547-L555) in PageRender.module:

````php
$pos = stripos($html, '<!DOCTYPE html');
		
if($pos === false) {
    // if no doctype match, attempt an html tag match
    $pos = stripos($html, '<html'); 
}

// if no document start, or document starts at pos==0, then nothing to populate
if(!$pos) return;
````

If there is no markup before the `<!DOCTYPE html` or `<html` then it's true that there's nothing to populate, but it doesn't mean that there's no work for `WireMarkupRegions` to do - `<pw-region>` tags must always be removed from output.

**Comment by cb2004** [comment]
Wondering if a comment in the file would get around this issue?

**Comment by cb2004** [comment]
@ryancramerdesign @Toutouwai as we head towards a new stable release this is still an issue in my testing, can you reproduce?

**Comment by Toutouwai** [comment]
Yes, I can confirm the issue still exists in v3.0.93

**Comment by ryancramerdesign** [comment]
Thanks, I was able to reproduce this now and have pushed a fix.

**Comment by cb2004** [comment]
@ryancramerdesign @Toutouwai confirmed fixed.

**Comment by PixraelR** [comment]
Yes, it works, but it leaves the "region hints" in the output.. when I don't use a region in my template file, it's deleted from _main.php in the output, but still leaves the <!-#headstyles->

**Comment by cb2004** [comment]
This would be a separate issue as it is just a html comment, which are stripped with ProCache.

**Comment by PixraelR** [comment]
Everyone doesn't have ProCache
