### ISSUE TITLE
Problems with admin when logged into more than one ProcessWire site at a time

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#303]
### Short description of the issue

When I try to login to more than one ProcessWire site at the same time in the same browser (Chrome) the second site's admin panel keep redirecting me to the first site's admin. Specifically, the menu bar links all point to the first site and the menu ajax queries load the list of templates and fields from the other site. I often end up editing the wrong thing without realizing it. I don't know if this is an issue with the sessions getting mixed up or what, but it has been a continual nuisance for a while now.

### Steps to reproduce the issue

1. Open Chrome and log into one PW site
2. Open a separate tab and log into a different PW site
3. Click on a link in the admin menu from site 2. 

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
I'm not seeing that here, but it sounds to me like you've got colliding sessions. Try using a different session name for one of your instances. In your /site/config.php you can do this with the `$config->sessionName` property, i.e. `$config->sessionName = 'baz';`

**Comment by thetuningspoon** [comment]
Thanks for the tip Ryan, I will try that.

I figured out that this issue only occurs when both sites are at the same domain. Since PW behaves so nicely in a subfolder, we have most of our development sites running at the same domain, hence the session name collision!
