### ISSUE TITLE
Odd rendering of fieldset without label

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#304]
### Short description of the issue

If a fieldset field is created but not given a label, that fieldset is rendered without a header, background or border in Page Edit. Possibly this is a feature not a bug, but if so the rendering still looks a bit off as indicated in the screenshot below.

### Expected behavior

Normal inputfield rendering, with field name used as inputfield header if no label supplied.

### Optional: Screenshots/Links that demonstrate the issue

![2017-07-02_173826](https://user-images.githubusercontent.com/1538852/27767527-593f0e90-5f4e-11e7-9bb2-403c0a57c03a.png)

### Setup/Environment

* ProcessWire version: 3.0.65

**Comment by netcarver** [comment]
@Toutouwai Is this still an issue in more recent versions of PW?

**Comment by Toutouwai** [comment]
Yes, there are still issues in PW 3.0.125. 

With AdminThemeDefault the display issues are those shown in the screenshot above.

In AdminThemeUikit the issues are as per the screenshot below.
![2019-02-07_094954](https://user-images.githubusercontent.com/1538852/52372934-487fd200-2abe-11e9-827a-30c599149a99.png)

**Comment by netcarver** [comment]
@Toutouwai Thanks for the update Robin!

**Comment by ryancramerdesign** [comment]
@Toutouwai @netcarver There was a type comparison error for the `skipLabel` property (bool vs int) in InputfieldWrapper.php, which I've pushed a fix for. InputfieldWrapper is allowed to show without a label but all the others (including InputfieldFieldset) are supposed to pull from name when label isn't present. I think this is likely what was causing at least the screenshot above missing the header when it shouldn't be. It's possible some whitespace might still remain (?), but the header should not have been missing, hopefully fixed now, but let me know if not. Thanks.

**Comment by Toutouwai** [comment]
Thanks for the fix!
