### ISSUE TITLE
Column spacer height not calculated correctly inside fieldset

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#306]
### Short description of the issue

When a column height changes in Page Edit, the column spacer heights inside a neighbouring fieldset are not calculated correctly: column spacer divs within fields in the fieldset are removed creating uneven alignment of the fields. The screen recording below demonstrates - in the demonstration I have given the spacer divs a background colour so they are visible.

![fieldset](https://user-images.githubusercontent.com/1538852/27767702-89a5abe8-5f53-11e7-8b65-f17bcd42329d.gif)

If the column spacer JS is triggered again (by changing the window width for example) then the spacer divs are calculated correctly again.

### Setup/Environment

* ProcessWire version: 3.0.65

**Comment by matjazpotocnik** [comment]
It happens in inputfields.js. On initial load the height is adjusted for all needed fields. When file is uploaded, maxColHeightSpacer div (added on page load) is removed and then reapplied, but not for all fields. It aligns files and fieldset to equal height, but not fields inside fieldset. I forced height calculation on all input fields after ajaxupload and it looks ok, but not sure if this is appropriate solution.

![height](https://user-images.githubusercontent.com/7663992/32373058-b06c78ba-c097-11e7-83c7-9900c45b909d.gif)

**Comment by netcarver** [comment]
@matjazpotocnik Thanks for the suggested fix Matjaž, I've relabelled this to bring it out of the pile of old issues.

**Comment by Toutouwai** [comment]
> I forced height calculation on all input fields after ajaxupload and it looks ok

I'm no longer using AdminThemeDefault, but previously I was using the following custom JS to solve some glitches with the column spacer height calculation:

```js
// Force firing of column spacer JS
$(document).ajaxComplete(function() {
	setTimeout(InputfieldColumnWidths, 300);
});
$(window).load(function() {
	setTimeout(InputfieldColumnWidths, 300);
});
```

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
Since it's been more than a year since the report, just wondering if anyone is still experiencing this behavior? I think there have been other related updates in that time. But if anyone still sees it, is it just in AdminThemeDefault? Thanks.

**Comment by Toutouwai** [comment]
The issue still exists in PW 3.0.127 for AdminThemeDefault and AdminThemeReno:

![spacer](https://user-images.githubusercontent.com/1538852/54647579-df9d6800-4b07-11e9-9954-32dee38e4db5.gif)

**Comment by ryancramerdesign** [comment]
@Toutouwai For the solution you proposed above, where did you place it (in the theme's main.js file?) and can you confirm it resolves the issue? Also, I think likely only your ajaxComplete event handler would be necessary, as I think the InputfieldColumnWidths is already called at initialization.

**Comment by Toutouwai** [comment]
For my purposes I placed the JS in a custom admin JS file (which has a few other personal customisations for the admin). But if added to the core I expect `wire/templates-admin/scripts/inputfields.js` would be the place to add it.

It's been a while since I have used AdminThemeDefault and I forget exactly what the issues were that needed the extra triggering of `InputfieldColumnWidths`, which JS events related to which issues, and which ones needed the 300ms setTimeout to reliably correct. I know there were several that I never got around to filing GitHub issues for and I just solved them in custom JS.

The extra firing on window load was to correct some other issue besides the one discussed here. So that part can be ignored and I'll open a new issue if I discover/remember what needed that.

And looking again at the issue discussed here I think it's the `AjaxUploadDone` event that's relevant. Probably the 300ms delay isn't needed but I'm not entirely sure.

This seems to fix the issue here (in the context of inputfields.js):

```js
$(document).on('AjaxUploadDone', InputfieldColumnWidths());
```

**Comment by matjazpotocnik** [comment]
I don't know why, but I had to do this:

```
$(document).on('AjaxUploadDone', function() {
    InputfieldColumnWidths();
});
```
The widths of fields should also be recalculated when the file is deleted:
![deletefile](https://user-images.githubusercontent.com/7663992/54861868-c2e47880-4d31-11e9-9550-5e693c2230d5.gif)

**Comment by LostKobrakai** [comment]
Another option besides fixing the js part of that would be to treat is a progressive enhancement and only fix it using flexbox or css grid styling. Those make it easier to create equal height rows and imho older browsers can simply get the not so pretty/aligned layout, which should work just as well.

**Comment by Toutouwai** [comment]
Have done some more testing and identified several issues.

**1\. Column spacer is not recalculated when a field is AJAX-loaded.**

![1](https://user-images.githubusercontent.com/1538852/54863626-e8b06280-4daf-11e9-9fd2-698aeee2fc7f.gif)

**2\. Column spacers in fieldsets not recalculated when field value changes** (which can change inputfield height)

![2](https://user-images.githubusercontent.com/1538852/54863678-6ecca900-4db0-11e9-9f24-e66c96dd8415.gif)

This is also the issue @matjazpotocnik identified above with marking files for deletion.

**3\. Column spacers in fieldsets not recalculated when CKEditor field height changes** (which includes when CKEditor first loads)

![3](https://user-images.githubusercontent.com/1538852/54863704-c539e780-4db0-11e9-804f-35f0e182ac37.gif)

## Suggested fixes

**1\.** 

Add call to `InputfieldColumnWidths()` in `InputfieldStateAjaxClick()`, after line [1193](https://github.com/processwire/processwire/blob/2cad3ed11b06251b5b79c10b649ee4376500dae0/wire/templates-admin/scripts/inputfields.js#L1193)
```js
//...
if($inputfields.length) {
    $inputfields.trigger('reloaded', [ 'InputfieldAjaxLoad' ]);
    InputfieldStates($li);  
    InputfieldRequirements($li);
    InputfieldColumnWidths();
} else {
    $li.trigger('reloaded', [ 'InputfieldAjaxLoad' ]);
    InputfieldColumnWidths(); // added
}
//...
```

**2\. and 3\. and the original issue described in the first post**

[These lines](https://github.com/processwire/processwire/blob/2cad3ed11b06251b5b79c10b649ee4376500dae0/wire/templates-admin/scripts/inputfields.js#L891-L893) are the problem, because `checkInputfieldHeightChange` does not account for nested rows inside a fieldset. Instead these event listeners can be moved outside of `InputfieldColumnWidths()` and call `InputfieldColumnWidths()` instead of `checkInputfieldHeightChange`.

So remove lines 891-893 and add this at the bottom inside `jQuery(document).ready()`:

```js
$(document).on('change', '.InputfieldColumnWidth :input', function() {
    InputfieldColumnWidths(); // For fields with immediate height change (e.g. AsmSelect)
    setTimeout(InputfieldColumnWidths, 300); // For fields with delayed height change (e.g. Files delete)
});
$(document).on('AjaxUploadDone', '.InputfieldFileList', function() {
    InputfieldColumnWidths();
});
$(document).on('heightChanged', '.InputfieldColumnWidth', function() {
    InputfieldColumnWidths();
});
```

I call InputfieldColumnWidths() twice on `change` because it's nice to have the spacer react immediately on fields that change their height immediately.

Everything working:

![4](https://user-images.githubusercontent.com/1538852/54863927-bbfe4a00-4db3-11e9-8a13-615bfdbb3cbe.gif)

**Comment by netcarver** [comment]
Thanks for the ideas and input on this issue everyone!

**Comment by matjazpotocnik** [comment]
I can confirm it's working here.

**Comment by ryancramerdesign** [comment]
Thanks for the suggested fix @Toutouwai — this has been added. Thanks for testing it out too @matjazpotocnik

**Comment by Toutouwai** [comment]
Thanks.
