### ISSUE TITLE
pagename "..." leads to problems

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#307]
### Short description of the issue

a client wanted to publish a page with the title "..." and it didn't work as expected

### Expected behavior

the pagename should be changed to a valid pagename

### Actual behavior

it stores the pagename empty without error

### Optional: Suggestion for a possible fix

maybe replace the ... by --- ?

### Steps to reproduce the issue

just paste "..." into any pagename field, save the page (should work without error) and try to view the page (leads to an url like example.com// )

### Setup/Environment

* ProcessWire version: 3.0.63

**Comment by ryancramerdesign** [comment]
When I try to change the name of a page to "..." and hit save, it comes back with an error, and restores the previous page name. Is there some other method you are using to make it blank?

**Comment by BernhardBaumrock** [comment]
thank you. see that i missed an important detail: this appears only when 1-step pageadd is active. my settings are:

allowed templates for children: "product"
name format for children: "title"

i add a page under parent "products" and it creates the page instantly. then i fill in the title "..." and it saves without error but has the name "" leading to an url like example.com/products//

**Comment by netcarver** [comment]
@ryancramerdesign Do you need any more information to progress this issue?

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock @netcarver I'm thinking this issue might already be resolved. I just tried to duplicate it using the instructions above, and the page retains its temporary `untitled-12345` name when the title doesn't resolve to a usable name. This is likely because the whole page names system was rewritten last year (PagesNames class).

**Comment by BernhardBaumrock** [comment]
thx, confirmed :)
