### ISSUE TITLE
Trash deleted item counting not working

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#308]
For live page deletions, system not updating trash page count result. For see real result need to refresh page. Like on screenshot.
![ekran resmi 2017-07-04 21 15 19](https://user-images.githubusercontent.com/455983/27839969-ed4b1344-60fd-11e7-9644-1db94f8fd6f9.png)

* ProcessWire version: ProcessWire 3.0.65

**Comment by LostKobrakai** [comment]
The trash is only be shown to superusers anyway so I'm not sure if live update to that number is really a pressing feature we need.

**Comment by trk** [comment]
Live updating trash page count value is not so important, but like other pages it must count when you update page children.

If you think this is not necessary you can close issue.

**Comment by teppokoivula** [comment]
While I wouldn't call this "high priority" by any means, it should be noted that minor inconsistencies like this tend to pile up and can eventually make end-users question the trustworthiness of the system. Just saying.

**Comment by trk** [comment]
@teppokoivula @LostKobrakai You mean, if processwire users catch small issues like these, don't open an issue for it. Keep it same?

I opened an issue and there are unnecessary comments. :( `(Just saying)`

**Comment by teppokoivula** [comment]
@trk: I'm afraid that there's been a slight misunderstanding here. Sorry -- could've communicated more clearly. It was *absolutely not* our intention to say that you should stop reporting issues :)

What @LostKobrakai was trying to point out above, I believe, is that the problem mentioned here could be trivial enough to just leave as-is. Sometimes a fix requires so much work that it just isn't worth it -- but, to be honest, neither of us probably knows yet if that's really the case here.

What I tried to point out above was simply that, in my opinion, this should be dealt with, even if it's a relatively minor issue. I absolutely didn't mean that you should not report issues, so if that's the impression you got, well.. I'm really sorry for not being obvious enough.

You're doing great job, and it's much appreciated :)

**Comment by trk** [comment]
Simple answer, issue managers can add tags to each issue like this :
![ekran resmi 2017-07-05 16 12 42](https://user-images.githubusercontent.com/455983/27865874-e76ba002-619c-11e7-9688-866665c09783.png)

**Comment by ryancramerdesign** [comment]
Just testing here on the dev branch, this issue does not appear to exist anymore, so I'm closing this one out. Thanks.
