### ISSUE TITLE
Password field's default values are not available until field is saved

### ISSUE THREAD

**Issue by fbg13** [processwire/processwire-issues#309]
### Short description of the issue

The default values/settings of the password field (probably others too) are empty if trying to access it before the field was saved in the admin, saving from the api without setting a value doesn't help.

### Expected behavior
In a template file
```
echo $fields->get("pass")->minlength; // Field not saved echoes 6, after field save echoes 6
```

### Actual behavior
In a template file
```
echo $fields->get("pass")->minlength; // Field not saved echoes nothing, after field save echoes 6
```

### Optional: Suggestion for a possible fix

Accessing a value/setting from the password field will return the default regardless if it was saved or not.

### Steps to reproduce the issue

1. Install PW
2. echo $fields->get("pass")->minlength;
3. echo $fields->get("pass")->minlength; again after saving the password field

### Setup/Environment

* ProcessWire version: 3.0.65
* (Optional) PHP version: 7.1
* (Optional) MySQL version: 5.6.35
* (Optional) Fresh PW 3.0.65 installation

**Comment by ryancramerdesign** [comment]
If you go and try to change your password, you should see that it is aware of the defaults. The reason you aren't seeing them in your API call is that the settings are for InputfieldPassword, and that module isn't present unless you are rendering or processing a form. So those settings have nothing to do with the runtime Field object, instead they are for the Inputfield. You can retrieve them from the Inputfield instead: 
~~~~~
$field = $fields->get('pass');
$inputfield = $field->getInputfield($page, $field); 
$minlength = $inputfield->get('minlength'); 
~~~~~
When you save a Field, it is true that it will act as a storage container for those Inputfield settings as well. But it isn't the owner of those settings. So for a case like the one you've mentioned, where you want "user configured value" or "default value", then you'd want to get it directly from the Inputfield like shown above.

**Comment by fbg13** [comment]
Thanks for explaining.
