### ISSUE TITLE
PHP Notice: A non well formed numeric value encountered in

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#31]
### Short description of the issue

PHP 7 is throwing notices these now when trying to do math on non-numeric values.

### Optional: Suggestion for a possible fix
Here's the current one:
https://github.com/processwire/processwire/blob/bac5b0de5d95b5a10c09f48ba5e63b419ee68799/wire/core/Pageimage.php#L680

I wonder if you'd like to keep this issue open and you can edit this post removing them as they are fixed and I can add more as I find them. Might be easier than a new issue every time I find a new one. Obviously not PR worthy, so up to you - how would be best like me to report / you to manage these?

**Comment by LostKobrakai** [comment]
I think you/we could just reopen this if anyone finds a new place and does put it here.

**Comment by ryancramerdesign** [comment]
As far as I can tell, that function shouldn't be affected unless called with an invalid argument? How do I reproduce the issue? Is it possible you are calling the function with a string like "0.5" or something rather than using a float or int? This function will accept either float or int, so the usual solution of typecasting to a number isn't ideal here.

**Comment by adrianbj** [comment]
I think it might have been an SVG file and calling `rebuildVariations()` on it, so perhaps $width was empty or set to "100%" - I would need to look back through that svg related stuff to remember. Getting OT, but I have been thinking about doing a bit of an SVG overall because there are some other issues like being able to manually resize larger and disabling cropping, etc that I would to implement.

**Comment by teppokoivula** [comment]
It's a bit early here so I might not be following your logic here, but it appears that `hidpiWidth()` can run into this issue in at least two cases:

* When the image is an SVG like @adrianbj pointed out above; in this case width can be "100%".
* Alternatively if `hidpiWidth()` gets called with `$width < 1` it will eventually try to get proper width from `width()`, which in turn asks it from `size()`, which delegates it to `___size()`, which returns an instance of `Pageimage`.

SVG file seems the most likely scenario here, but it's not the only problematic case. Admittedly I have no idea why `hidpiWidth()` would get called with a float value smaller than one, but if it does, it will fail :)

**Comment by ryancramerdesign** [comment]
Good point regarding SVG– I've added support for "100%" string to that method. 

> Alternatively if hidpiWidth() gets called with $width < 1 it will try to get a proper width from width(), which in turn requests it from size(), which delegates it to ___size(), and finally this method returns an instance of Pageimage.

This is an intended usage, because $width < 1 means you are specifying a scale that you'd like to get the width at. But unless I've misunderstood what you are saying, it returns an integer for that scenario not a Pageimage.

**Comment by teppokoivula** [comment]
> But unless I've misunderstood what you are saying, it returns an integer for that scenario not a Pageimage.

Agreed, apparently it *was* too early to comment. Looks like I got completely thrown off track and missed or misinterpreted this line: `$width = is_array($options) ? 0 : (int) $options`. Sorry for the confusion :)

This is a bit off-topic, but the phpdoc comment declares that `$options` param can only be an array, while in the comment text int is mentioned too. Might be worth updating.
