### ISSUE TITLE
ProcessForgotPassword module always displays the default requirements

### ISSUE THREAD

**Issue by fbg13** [processwire/processwire-issues#310]
### Short description of the issue

ProcessForgotPassword module always displays the default requirements.

### Expected behavior

ProcessForgotPassword module gets the requirements set to the password field.

### Actual behavior

ProcessForgotPassword module displays the default requirements.

### Screenshots that demonstrate the issue

![password](https://user-images.githubusercontent.com/6839895/27855029-967eb718-6171-11e7-8460-47204814a02f.gif)

### Steps to reproduce the issue

1. install pw
2. activate ProcessForgotPassword module
3. change pass field requirements
4. test the forgot password option

### Setup/Environment
* ProcessWire version: 3.0.65
* (Optional) PHP version: 7.0
* (Optional) MySQL version: 10.1.22-MariaDB
* (Optional) Fresh install

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed an update that should make it now pull those requirements from the system pass field
