### ISSUE TITLE
Lister bookmarks do not retain correct selector operator for parent title

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#314]
### Short description of the issue

If you configure and save a Lister bookmark that has a filter using the "contains text" (%=) operator for parent title, when visiting the bookmark the operator has been changed to the "equals" operator, and if you attempt to change the operator using the dropdown the "contains text" operator is not available. The same issue occurs when editing the lister bookmark.

### Screenshots/Links that demonstrate the issue

Before saving the bookmark all operators are available:

![2017-07-10_110900](https://user-images.githubusercontent.com/1538852/27998297-4b4189e0-6560-11e7-9e6e-c2e626fad55f.png)

Correct operator is shown in the bookmark selector:

![2017-07-10_110052](https://user-images.githubusercontent.com/1538852/27998303-77d2606a-6560-11e7-8c64-9d83e8fb199c.png)

When visiting the bookmark or editing it, the operator has changed and the list of available operators is much reduced:

![2017-07-10_110122](https://user-images.githubusercontent.com/1538852/27998302-62ff6e30-6560-11e7-82f3-535dc6a26aca.png)

### Setup/Environment

* ProcessWire version: 3.0.66

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this issue. Thanks for the screenshots too.
