### ISSUE TITLE
PageTable image fields not displaying

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#315]
### PageTable image fields not displaying

Image fields in PageTable rows are not initially visible

### Expected behavior

Image fields should be always visible as thumbnail: this is convenient for PageTable fields used for storing slider/carousel items.

### Actual behavior

They get visible after opening and closing (even without saving) the popup editing window for a any row.

### Optional: Suggestion for a possible fix

Disabling renderValueFlags in InputfieldPageTable::getItemValue() method seems be a quick fix for the issue

### Steps to reproduce the issue

1. Create a template owning a Pageimage field
2. Create a PageTable field using pages of that template
3. Add the PageTable field to the desired template and edit/add a page.

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 7.0.19
* (Optional) MySQL version:  5.5.5-10.0.31-MariaDB
* (Optional) Any 3rd party modules that are installed and could be related to the issue: A repeater field that stores the same type of data (for comparison). The repeater field do not have this issue.

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate the issue here, but also found that what you mentioned about those renderValueFlags is correct – they are no longer needed, and likely they were breaking something, even if I couldn't see it. They were needed back on an older version of the image fields. I have removed them, along with some supporting code, and that appears in the latest commit. Thanks.

**Comment by pine3ree** [comment]
@ryancramerdesign 
thank You!

**Comment by pine3ree** [comment]
Hello @ryan,
sorry to bring this up again.
I still have strange behaviour with image input fields inside a PageTable input fields.
I think the problem is in the javascript function `setListSize` in inputfieldimage.js. Image sizes are remembered via cookies when we chhane the visualization type and/or the thumb size. So I end up having for instance

name=24
title=52
image=24

a td cell for images 24% of total and inside a `.gridImage__overflow` div with w=39% set via js.

To fix the issue I simply added a custom admin style:
```scss
.InputfieldPageTableContainer {
    .gridImage__overflow {
        width: 240px !important;
        height: 120px !important;
        background: #fefefe;
        img {
            width: 100% !important;
            height: auto !important;
        }
    }
}
```

setListSize only triggers `.gridImage__overflow` divs (In my opinion there is no need for it in page-table rows...we don't have thumb style/magnify controls there), maybe we should have the possibility to customize by context  the InputfieldImage wrapping div class instead of having it hard-coded. Or even simpler we could have the InputfieldPageTable ___render() method automatically replace  `gridImage__overflow` with another class....of course this is easily also possible via hooks.

kind regards.
maks

**Comment by netcarver** [comment]
@pine3ree I take it that this issue is still open in the latest version of Dev?

**Comment by pine3ree** [comment]
Hello @netcarver, I haven't checked lately.

**Comment by pine3ree** [comment]
Hello @netcarver. Yes, sure, You can close it, especially if no one else is reporting it.
kind regards, maks.
