### ISSUE TITLE
$page->setAndSave() method does not work for page name

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#319]
### Short description of the issue

The $page->setAndSave() method does not work for page name:

```php
$p = $pages->get(1234);
$p->setAndSave('name', 'foo');
```

But the API docs for the method say the "key" argument may be a field or property, so "name" should work.

### Expected behavior

Saves the new name.

### Actual behavior

Name change is not saved. The issue seems to be that internally the page is saved like this...
```php
$page->save('name');
```
...which doesn't actually save the name change.

### Setup/Environment

* ProcessWire version: 3.0.66

**Comment by BernhardBaumrock** [comment]
i also experienced some problems with setandsave recently where it didn't work setting the page's language status:
https://processwire.com/talk/topic/4383-how-to-set-language-active-via-api/?do=findComment&comment=147564
https://processwire.com/talk/topic/16794-back-to-the-roots-problems-with-simple-hooks/?do=findComment&comment=147903

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue. Looks like it didn't actually support properties before, just Fields. I've added support for properties so it should work now.
