### ISSUE TITLE
non well-formed numeric in Database.php

### ISSUE THREAD

**Issue by KeeneState** [processwire/processwire-issues#323]
### Short description of the issue

Under certain circumstances, specifically a fast SQL query result, a notice is raised:  
A non well formed numeric value encountered in /.../wire/core/Database.php on line 118

### Expected behavior

No notices should be raised collecting timings in Database.php, at the following line:
$timerTotalSinceStart = Debug::timer() - $timerFirstStartTime; 

### Actual behavior

A noticed is raised.

### Optional: Suggestion for a possible fix

This occurs when timings are small enough to trigger scientific notation, e.g. 9.9897384643555E-5. If I cast to a float, it seems to help.

$timerTotalSinceStart = (float)(Debug::timer() - $timerFirstStartTime); 

### Steps to reproduce the issue

Unfortunately, this may not be easy to replicate. I only saw it after my computer had been upgraded to brand new hardware. Even then, it is rare. The SQL that is tripping it is from the VideoEmbed module:

$result = $db->query("SELECT embed_code FROM " . self::dbTableName . " WHERE video_id='$videoID'"); 

### Setup/Environment

* PW 3, verified with today's (2017-07-19) master branch
* PHP 7.1.6

**Comment by matjazpotocnik** [comment]
I guess this is already fixed: https://github.com/processwire/processwire-issues/issues/316

**Comment by KeeneState** [comment]
Ah, cool--I didn't see that. Thanks @matjazpotocnik.
