### ISSUE TITLE
Non well formed numeric value (Debug mode)

### ISSUE THREAD

**Issue by grexen** [processwire/processwire-issues#324]
### Short description of the issue

There is a problem with strict typing in PHP 7.1 in the ProcessWire\Database line 118

### Expected behavior

Be able to execute SQL queries

### Actual behavior

502 Bad Gateway:
[error] 555#555: *762 FastCGI sent in stderr: "PHP message: PHP Notice:  A non well formed numeric value encountered in .../ProcessWire/wire/core/Database.php on line 118

### Steps to reproduce the issue

1.   /** @var \ProcessWire\Database $db */
      $db = $this->db;
2. $result = $db->query('SELECT DISTINCT test_id FROM test_applications');

* ProcessWire version: 3.0.42 
* (Optional) PHP version: 7.1

**Comment by matjazpotocnik** [comment]
https://github.com/processwire/processwire-issues/issues/316

**Comment by ryancramerdesign** [comment]
Closing since this was fixed in #316 , however I recommend checking to see what module is using the legacy Mysqli ($db) variable, since ideally you don't want in use due to the extra overhead.
