### ISSUE TITLE
Hash fragment in URL breaks pw-panel links

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#325]
### Short description of the issue

If a URL to be opened in a pw-panel contains a hash fragment then the iframe URL for the panel is not created properly in panel.js. Extra elements are wrongly appended to the URL after the hash fragment, when the fragment should always be the last portion of the URL.

Related forum topic: https://processwire.com/talk/topic/16775-is-it-possible-to-link-directly-to-the-content-or-delete-tab/

### Optional: Suggestion for a possible fix

Replace [these lines](https://github.com/processwire/processwire/blob/651e8bd20c1f7bf13c08a2098f862adf82700a28/wire/modules/Jquery/JqueryUI/panel.js#L138-L146) of panel.js with:

```js
if(typeof panelURL != 'undefined' && panelURL.length) {
    var hash = '';
    if(panelURL.indexOf('#') > -1) {
        var url_parts = panelURL.split('#');
        panelURL = url_parts[0];
        hash = '#' + url_parts[1];
    }
    panelURL += (panelURL.indexOf('?') > -1 ? '&' : '?') + 'modal=panel&pw_panel=';

    if($toggler !== null && $toggler.hasClass('pw-panel-links')) {
        panelURL += '2'; // don't update target of links in panel
    } else {
        panelURL += '1'; // update target of links in panel
    }
    panelURL += hash;
}
```

### Setup/Environment

* ProcessWire version: 3.0.66

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix (nice one!) to the dev branch.
