### ISSUE TITLE
Arabic Letters In URL sometimes not working fine :(

### ISSUE THREAD

**Issue by Mustafa-Online** [processwire/processwire-issues#326]
is there any one tried to support Arabic letters in URL? 
i followed the PW Docs and added all letters in .htaccess file + config.php

**Comment by ryancramerdesign** [comment]
Here's more information on [extended page names in ProcessWire]( https://processwire.com/blog/posts/hello-%E5%81%A5%E5%BA%B7%E9%95%B7%E5%A3%BD%C2%B7%E7%B9%81%E6%A6%AE%E6%98%8C%E7%9B%9B/) (link). 

We adhere to IDN standard (international domain name) for page names. It's true there are some potential limitations there, as the characters must be punycode'able, and [as far as I know] must be supported by 3-byte UTF-8. For instance, most emojis can't be used in page names.

**Comment by Mustafa-Online** [comment]
So what i have to do? .. it's weird because in other CMS's [Drupal, WP, Joomla] i can create URLs in arabic without any issues, please help me with this,, This is the only issue in PW.

**Comment by teppokoivula** [comment]
@Mustafa-Online: could you provide an example of an URL or page name you've tried to use that doesn't work for you? This would make debugging much easier.

I just did a quick test with some Arabic characters in URL, and everything worked well after the following steps. These are explained in the link that Ryan provided earlier, so I'm assuming that you've already gone through them too:

- Added `$config->pageNameCharset = 'UTF8';` to /site/config.php
- Added  `$config->pageNameWhitelist = '';` to /site/config.php. The value of this config setting should contain all the Arabic letters you want to support in URLs.
- Commented out rule 16a and enabled rule 16b in .htaccess.
- Added all those Arabic letters I wanted to use to rule 16b in .htaccess.

**Comment by Mustafa-Online** [comment]
@teppokoivula - example : http://ammarkamal.com/جامعة-الخرطوم

it's redirect me to phpmyadmin .. i tried everything.. could you please share your config.php so i can see how you added the Arabic Letters .
Mine looks like this:
$config->pageNameWhitelist = '-_.abcdefghijklmnopqrstuvwxyz0123456789źاأآىإؤءئبتثجحخدذرزسشصضطظعغفقكلمنهةوي';

**Comment by LostKobrakai** [comment]
Did you modify the .htaccess other and enabling rules 16b? Because by default you should rather see a 404 and not a redirect to phpmyadmin

**Comment by Mustafa-Online** [comment]
@LostKobrakai - Yes I Did All of that - i followed the docs line by line (Guide in Ryan's Article)

**Comment by LostKobrakai** [comment]
I'm asking if you did add something else to the .htaccess as well, besides the things in the article.

**Comment by Mustafa-Online** [comment]
no, i didn't do any thing else besides the things in the article.

**Comment by teppokoivula** [comment]
@Mustafa-Online: the URL you mentioned seems to work for me. Here are the most relevant config settings:

```
$config->pageNameCharset = 'UTF8';
$config->pageNameWhitelist = '-_.abcdefghijklmnopqrstuvwxyz0123456789źيوةهنملكقفغعظطضصشسزرذدخحجثتبئءؤإىآأا';
```

Here's the whole page name section from .htaccess:

```
  # PW-PAGENAME
  # -----------------------------------------------------------------------------------------------
  # 16a. Ensure that the URL follows the name-format specification required by PW
  # See also directive 16b below, you should choose and use either 16a or 16b.
  # -----------------------------------------------------------------------------------------------

  # RewriteCond %{REQUEST_URI} "^/~?[-_.a-zA-Z0-9/]*$"

  # -----------------------------------------------------------------------------------------------
  # 16b. Alternative name-format specification for UTF8 page name support.
  # If used, comment out section 16a above and uncomment the directive below. If you have updated
  # your $config->pageNameWhitelist make the characters below consistent with that.
  # -----------------------------------------------------------------------------------------------

  RewriteCond %{REQUEST_URI} "^/~?[-_./a-zA-Z0-9æåäßöüđжхцчшщюяàáâèéëêěìíïîõòóôøùúûůñçčćďĺľńňŕřšťýžабвгдеёзийклмнопрстуфыэęąśłżźاأآىإؤءئبتثجحخدذرزسشصضطظعغفقكلمنهةوي]*$"

  # END-PW-PAGENAME
```

The "redirect to phpmyadmin" part seems very strange. Can't think of any sensible reason why that would happen right now, but it definitely seems that there's something weird going on on your web server.

**Comment by LostKobrakai** [comment]
Maybe the host does have global apache rewrite rules or higher placed .htaccess files, which prevent the processwire one being actually hit. You could test this by placing an syntax error in the top of the .htaccess of processwire and see if you get an 503 error instead of the redirect to phpmyadmin.

**Comment by Mustafa-Online** [comment]
**Thaaaanx, i uploaded the files to live server, everything works just fine 💯 
i will dig more into this issue to know all causes.**
.
Much Love from here (SUDAN), Seriously Nice support, Nice community <3
 
=== [Forgive My English lang, I'm an Arabic Native Speaker]
