### ISSUE TITLE
Instruction link broken for Custom JS on InputfieldCKEditor.module

### ISSUE THREAD

**Issue by shorty2240** [processwire/processwire-issues#328]
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldCKEditor/InputfieldCKEditor.module#L769

Just missing the %s

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix to the dev branch.

**Comment by gmclelland** [comment]
I think this is the same thing as https://github.com/processwire/processwire/pull/69.  I'm going to close the pull request.
