### ISSUE TITLE
Pagefiles::add does create invalid filenames if supplied url with get params

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#329]
### Short description of the issue

When adding a pagefile via a url the created file does include the get params in it's file extention rendering it useless.

### Expected behavior

Stripping of get parameters of the url when calculating the filename.

### Actual behavior

The params are appended to the filename.

### Optional: Screenshots/Links that demonstrate the issue

https://dl.dropboxusercontent.com/s/…/something.pdf?dl=0 => something.pdf_dl_0

### Setup/Environment

* ProcessWire version: 2.7.3, but I've not found any new code in 3.x
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@LostKobrakai Hi Benjamin, can this be closed now?
