### ISSUE TITLE
Inconsistent/buggy Ctrl+click behaviour in Pages breadcrumb

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#33]
Only discovered this by chance: Ctrl+clicking (Command+clicking on Mac?) on Pages breadcrumb links does non-standard behaviour.

In Chrome: Ctrl+click does not navigate to the page tree as per normal click, but instead opens the clicked page for editing. That's unexpected, but would be fine if it were not for...

In Firefox: Ctrl+click does not open the clicked page for editing as per Chrome, but opens the **adjacent** page for editing. So for breadcrumb: Home > Foo > Bar > Baz, clicking Home opens Foo, clicking Foo opens Bar, and clicking Bar opens no page for editing but instead navigates to the page tree.

And in IE11, Ctrl+click is just the same as a normal click - no page editing possible from breadcrumb.

If this Ctrl+click behaviour is a feature not a bug then it should be consistent across modern browsers.

* ProcessWire version: 3.0.36

**Comment by rolandtoth** [comment]
Are you using the module AdminOnSteroids? There's a feature for ctrl-clicking on the breadcrumb items for editing and your description sounds like you have this enabled.

**Comment by Toutouwai** [comment]
Thanks, yes, that is it.
