### ISSUE TITLE
Image size in PageEdit

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#331]
### Short description of the issue

When there are more than one image fields in one PageEdit page, all the image fields lose their saved size(set by the size bar at top right hand corner inside image field), except the first image field. All the image fields follows the size setting of the first image field. 

### Expected behavior

Images size inside the image field should be following the size bar(top right hand corner) inside the image field.

### Actual behavior

The size is following after save reload. If you hit the reload button again, all the size of the images of the page become the same. If the first image field is set to the third layout mode, it's size is still read as the first layout mode after reload.

### Optional: Screenshots/Links that demonstrate the issue
Change size and hit save.
![image](https://user-images.githubusercontent.com/26466450/28726710-dfe3c57a-73f4-11e7-908a-c2ce94a21af8.png)

Reload again after save.
![image](https://user-images.githubusercontent.com/26466450/28726726-f1888d60-73f4-11e7-8146-b4d92a495402.png)

### Steps to reproduce the issue

1. edit any page with template having more than one image field.
2. change the size of the image inside the fields by the sliding bar to make them not the same.
3. hit save and observe.
4. reload and observe. All images become the same size.

### Setup/Environment

* ProcessWire version: 3.0.68

**Comment by Toutouwai** [comment]
### Suggested fix

This issue relates to the retryGridItems array. The fix is to include the gridSize along with the $item when it is pushed to retryGridItems, and then use that associated gridSize when the item is later sized.

So [here](https://github.com/processwire/processwire/blob/e3fc776c5360c9a624e5d22ab7598afd48fd88d9/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L764):

````js
retryGridItems.push({item:$item, gridSize:gridSize});
````

And here:

````js
if(retryGridItems.length) setTimeout(function() {
    while(retryGridItems.length) {
        var one = retryGridItems.pop();
        $item = one.item;
        gridSize = one.gridSize;
        setGridSizeItem($item, gridSize, ragged);
    }
}, 150);
````

**Comment by netcarver** [comment]
@karltdev @Toutouwai Karl, Robin, is this issue still alive given the changes to images since 3.0.68?

**Comment by karltdev** [comment]
I just use 3.0.111 to try. The issue is still alive.

**Comment by ryancramerdesign** [comment]
Thanks @karltdev @netcarver  I've pushed a fix for this issue. Thanks @Toutouwai for tracking this one down (somehow hadn't seen this before)

**Comment by netcarver** [comment]
@ryancramerdesign Great, thanks for the fast turn-around on this one!

@karltdev Could you verify the fix works and then close this issue? Alternatively, if @Toutouwai can verify the fix, I'll close it.

**Comment by Toutouwai** [comment]
That fix is working here, thanks.

**Comment by netcarver** [comment]
Ok, closing. Thank you all.
