### ISSUE TITLE
FieldsetTab + AJAX should be opened after save

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#332]
### Short description of the issue
when you have a fieldsettab that is set to closed + AJAX and you save the page having this tab opened the tab content will not display after saving.

### Expected behavior

the content of this tab should be instantly loaded

### Actual behavior

the content loads only after clicking on the tab. until then the page is white and shows only the save button

### Steps to reproduce the issue

1. create a fieldsettab for one of your templates
2. set the field to closed + ajax
3. go to one page of this template and open the tab
4. save the page
5. the page will reload and the tab will be empty until you click (again) on the tab

### Setup/Environment

* ProcessWire version: 3.0.68

**Comment by netcarver** [comment]
This happens for me as well in 3.0.119.

**Comment by Toutouwai** [comment]
Probably related I think: https://github.com/processwire/processwire-issues/issues/618

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock @Toutouwai @netcarver I've pushed a fix for this issue.
