### ISSUE TITLE
InputfieldPageAutoComplete Has Inconsistent Behavior

### ISSUE THREAD

**Issue by zoaked** [processwire/processwire-issues#333]
### Short description of the issue

There are two minor items that have come up when we were working with the page auto complete input field type.

1) The field can be configured for either single page select or multi-page select.  When working with the multi-page single there are two configuration options shown (Autocomplete search operator & Fields to query for autocomplete) like one would expect.  However, when the single page version is selected these options are not available.

It should be noted that there is a workaround by setting the preferences choosing the multi select version, changing the config, saving, and then switching back to the single select version.  Even though the options do not show up, the single page selector still seems to respect these settings.

2) The notice text below the autocomplete search operator indicates to leave the default value when you are not sure.  However, the option that is indicated in the text (*=) does not match what is actually used as the default value (%=) for new fields. 

According to the documentation, the actual default value the module is using is the slower SQL like matcher.  The reference to speed sure seems to suggest using the newer option.  Perhaps things were in the process of being switched from % to *, but that is only a guess on my part.

### Expected behavior

1) Autocomplete options are shown regardless of single or multi select versions of the module. 
2) Instructions should match actual behavior 

### Actual behavior

Actual behavior was noted in the short description

### Optional: Suggestion for a possible fix

1) Currently, the single select version is (effectively) hard coded. (https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L1162)  This could be resolved by either making the single select a first class module (with possibility of having multiple select simply be a thin wrapper of the single select one) or by hard coding it in the fieldset showIf settings. (https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L1228)
```php
$classname = $inputfield->className();
$fieldset->showIf = 'inputfield=' . $classname;
if($classname === 'InputfieldPageAutocomplete') {
	$fieldset->showIf .= '|_'.$classname;
}
```

2) Change the actual default value (https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.module#L65) to match the note text (https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.module#L375) and implied recommendation in the documentation. (http://cheatsheet.processwire.com/selectors/selector-operators/contains-the-exact-word-or-phrase/ vs http://cheatsheet.processwire.com/selectors/selector-operators/contains-the-exact-word-or-phrase-using-slower-sql-like/)  Alternatively, the opposite is also acceptable.  Mainly, the end result is that these two things agree.

SIDE NOTE: When looking at the code, it seems a bit odd that the older option would reference the language library to allow "Recommended" to be translated, but the newer option on the line above it does not. (https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.module#L378)

### Steps to reproduce the issue
0) Make sure "Page Autocomplete" code module is installed
1) Create a new field with type of "Page Reference"
2) Save
3) Go to the "Input" tab
4) Choose "Page Auto Complete" from "Multiple Page Selection (sortable)" of the "Input Field Type" dropdown
5) Expand "Settings Specific To Page Auto Complete"
6) Take note of default value (%=) and compare to what the note below the field says is default (*=)
7) Switch to "Page Auto Complete" from "Single Page Selection" of the "Input Field Type" dropdown
8) Watch as the settings disappear

### Setup/Environment

* ProcessWire version: Latest stable (3.0.62)
* (Optional) PHP version: 7.1
* (Optional) MySQL version: mysql  Ver 14.14 Distrib 5.7.16
* (Optional) Any 3rd party modules that are installed and could be related to the issue: none

**Comment by netcarver** [comment]
@gingebaker, does this issue effect you too? (I see you gave it a thumbs-up, so just wondering)

**Comment by gingebaker** [comment]
@netcarver, Yes I had this issue too. I just checked with the latest version 3.0.108. I think this is fixed now.
https://github.com/processwire/processwire/commit/b4b40f19f4f9a87a6051de84403968bcbc7bc6ca
At least, the first point from your issue.

**Comment by netcarver** [comment]
@zoaked Is this still an issue for you in later versions of PW? If not, I'd like to close this issue in a weeks time.

/remind me to review this issue and close if no longer live in 1 week

**Comment by netcarver** [comment]
Closing as this seems to be complete. Please post more if it is not.
