### ISSUE TITLE
PageFinder::getQueryAllowedTemplates() does cache sql beyond user changes

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#334]
### Short description of the issue

`PageFinder::getQueryAllowedTemplates()` does cache template access where clauses without considering changes of the current user mid request.

### Expected behavior

When changing the current user with `$this->wire('user', $newCurrentUser)` that new user's template access settings should be used. 

### Actual behavior

If there were previous request the $where query part for determining template access is already cached and therefore incorrect after the current user is changed.

### Optional: Suggestion for a possible fix

Cache the userID with the where clause and skip the cache on mismatches to that id.

### Steps to reproduce the issue

1. Step 1
2. Step 2
3. Step 3

### Setup/Environment

* ProcessWire version: 2.7.3, but seems be the same in master
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai @netcarver that's a good find. I've pushed a fix for this issue.
