### ISSUE TITLE
client side image resize: filesize checked before resize?

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#335]
### Short description of the issue

it seems that the filesize is checked before the image is resized on the client side

### Expected behavior

the image should be resized and THEN checked wheter the file is too large for upload or not

### Actual behavior

i wanted to shrink an image on my local dev that has 4167x4167 and 66MB. the image does not get resized and the image-field says "file too large, limit is 8MB"

### Optional: Screenshots/Links that demonstrate the issue

t-shirt_grau_kurzarm_01.png: Filesize 67858 kb is too big. Maximum allowed is 8192 kb

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue so that it no longer takes the original file size into account when using client side resize.
