### ISSUE TITLE
InputfieldImage - option to always autorotate

### ISSUE THREAD

**Issue by uiii** [processwire/processwire-issues#337]
### Expected behavior

The image is autorotated (according to EXIF orientation) event though it's dimensions doesn't exceed the maximum set in settings.

### Suggestion for a possible fix

Add checkbox option "always autorotate" to the InputfieldImage config.

**Comment by ryancramerdesign** [comment]
I'm not sure I follow. Can you provide instructions on how to setup and duplicate the error?

**Comment by uiii** [comment]
This is not an error, but feature request. Currently if I set the maximum dimensions of the image and when I upload one, the image is resized when exceeds that dimensions and is autorotated as well (according to EXIF orientation). This is all correct. What I want is to be able to set an option to autorotate the image event though it is not exceeding the dimensions. Simply I would like to always autoroate the uploaded image and resize it when necessary.

**Comment by netcarver** [comment]
@uiii Hi Richard, sorry to be a pain, but could you open an issue on processwire-requests for this and close it here? Thanks for your consideration.
