### ISSUE TITLE
Wrong arguments order in WireTempDir createName method

### ISSUE THREAD

**Issue by fbg13** [processwire/processwire-issues#338]
### Short description of the issue

The arguments passed to the explode function are in the wrong order (string first, delimiter second)

https://github.com/processwire/processwire/blob/c1f7e96185a68d5ddb416b676268e0fecc589c9b/wire/core/WireTempDir.php#L92
http://php.net/manual/en/function.explode.php

### Expected behavior

Upload works.

### Actual behavior

On windows upload fails. Works on Ubuntu and probably all other linux OSs.
> Unable to create temp dir: F:/symlinks/localhost/www/pw/site/assets/cache/WireTempDir/.PFM./L1-L2-L3-L4/

### Optional: Screenshots/Links that demonstrate the issue

![upload-fails](https://user-images.githubusercontent.com/6839895/29155044-d6aae004-7da1-11e7-8726-d2401befe753.gif)

### Optional: Suggestion for a possible fix

`$a = explode($name, '.');` to `$a = explode('.', $name);`

### Setup/Environment

* ProcessWire version: 3.0.70
* (Optional) PHP version: 7.1.2

**Comment by ryancramerdesign** [comment]
Thanks this one was fixed last week, please let me know if you continue to experience it.
