### ISSUE TITLE
html entities in log files

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#34]
### Short description of the issue

Log files often have htmlentities in the text

### Expected behavior

```
Deleted field "linked_images_block" data in 0 row(s) from 0 page(s). [page-by-page] (Fields)
```

### Actual behavior

```
Deleted field &quot;linked_images_block&quot; data in 0 row(s) from 0 page(s). [page-by-page] (Fields)
```

### Optional: Suggestion for a possible fix

Not sure if it would be best to decode the entities in the log file itself (my preference), or decode when viewing via Setup > Logs

**Comment by ryancramerdesign** [comment]
I don't think that log files should be adjusting entities–I think it's better that they record exactly what they are given. But in this case, I'm pretty sure it's from Notices that get converted to log entries, as I found they are entity encoding before saving the log entry. As a result, I think the adjustment I just committed should fix it. Thanks.
