### ISSUE TITLE
Inputfield::getConfigInputfields unable to access its field

### ISSUE THREAD

**Issue by abdusco** [processwire/processwire-issues#346]
(I opened a PR in processwire/processwire repo with a fix, I'm opening the issue here.)
https://github.com/processwire/processwire/pull/82

> Hooking into Inputfield::getConfigInputfields, you cannot access any information about the field within the context in which it's used. This fixes it so that `Fieldtype::getConfigInputfields`, `Inputfield::getConfigInputfields` and `getConfigAllowContext` can get the field as the parameter and access field settings related to a certain Fieldgroup.

> I've discussed the issue and the fix in this forum post.
> https://processwire.com/talk/topic/16987-getting-fieldgroup-specific-settings-for-an-inputfield-inside-a-hook/

**Comment by ryancramerdesign** [comment]
@abdusco you should already be able to access the Field from the `$this->hasField` property. That property is present on any Inputfield that is being used on a Page field, whether rendering, configuring, or processing the field (or anything else the Inputfield might be used for). There are also hasFieldtype and hasPage properties present as well. Note that if your Inputfield can be used out side of page editor context (like in FormBuilder, or some other form) then those properties are not going to be present, so you may want to check that they are populated before accessing them as objects.

**Comment by netcarver** [comment]
@abdusco Does Ryan's comment above help resolve this issue? Would you like to continue the conversation?

**Comment by netcarver** [comment]
@abdusco @ryancramerdesign This issue appears to be stale. I therefore intend to close it in about a week unless I hear otherwise.

**Comment by netcarver** [comment]
Closing as this has gone cold. @abdusco Post more if needed and it can be reviewed. Thank you!
