### ISSUE TITLE
Field export/import : issue with Roles

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#347]
Just used Fields Export/Import for the 1st time.
I have observed the following behavior, in regards to the Import of Access permissions to Roles :
- in the export, the target Roles are identified by their"page-like" ID
- when importing, 
	. if this ID exists, the associated Permission is imported
	. if this ID does not exist, the associated Permission is (silently) ignored

-> 2 remarks :
1. I think anything not imported should be subject to a warning.
Especially with permissions : any difference in the permissions may result in security impact.

2. I'm wondering what I (and we) could do better here ?
Identifying a Role with its ID seems logical. But, given how these IDs are attributed (highly depending on the context), chances are that 2 same roles, created on pre-prod and on prod, will not have the same ID.
And when this occurs... well, I see no means for a solution on how to import the Permissions anyway.
It's a problem, because, when permissions are tightly configured, actually it's very useful to rely on Export/Import, in order to make sure that they are strictly the same on both sides (hence no security impact).
-> any thoughts on this ?
-> actually I'm wondering if the Roles Export/Import would not be better if relying on the Role name ?
Update : Now I have also tested the Export/Import of Templates, and actually this is exactly what it does for Roles : it works not with Role ID, but with Role name. And as a result, the import works nicely for the Roles associated with the imported templates.

Tested with latest PW 3.0.71

**Comment by ryancramerdesign** [comment]
Everything you've mentioned actually doesn't sound at all like the new
export/import tool added in 3.0.71, so am wondering – Are you using the
tool in the admin at Pages > Export/Import? Or something else?

Page references (like roles, permissions, etc.) are exported to page paths,
and they don't use IDs. Page IDs are not portable when exporting/importing
between systems, so we don't use them at all. While IDs aren't exported for
page references, you might still see IDs in export data, and that is only
for the possibility of drawing relations within the self contained import
data. Currently PW's importer does use those IDs for anything.

If a page reference is missing, it actually does report an error message
during test and import. For instance, when I tried to import roles here,
one of which had a missing permission, I got this error message:

> Unable to find page '/processwire/access/permissions/fancy-permission/'
to add to field 'permissions'

Most likely I'm missing something. Can you explain more specifically how
you are exporting and importing roles via IDs?

**Comment by er314** [comment]
Sorry if I was unclear Ryan,
I'm talking about the Export/Import for **Fields**.
Setup > Fields > Export/Import

Hope it makes more sense :-)

**Comment by er314** [comment]
Great ! The Fields export/import feature should be rock solid now.

**Comment by ryancramerdesign** [comment]
@er314 There may be other Fieldtypes where IDs are used in export data, let me know if you come across any others. It's up to each Fieldtype to convert IDs to something else at export, and restore them back to IDs at import. They do this with exportConfigData/importConfigData methods, which are part of the Fieldtype interface.

**Comment by thetuningspoon** [comment]
I'm seeing this with the Template import as well in PW 3.0.178. Has this already been fixed in a later version?

<img width="1288" alt="Screen Shot 2022-02-01 at 12 23 22 AM" src="https://user-images.githubusercontent.com/2922773/151916978-adb9ed54-8f7f-4fb1-b27d-2b07c495735f.png">

**Comment by thetuningspoon** [comment]
@ryancramerdesign I fixed the rolesPermissions export issue by adding the following section to the Templates::getExportData() method. It looks like this has not been fixed on the current dev. I tested and it works.

```// convert rolesPermissions to guids
		if($template->useRoles) {
			if(!empty($data['rolesPermissions'])) {
				$rolesPermissions = [];
				foreach($data['rolesPermissions'] as $key => $value) {
					$role = $this->wire('roles')->get((int) $key);
					if(!$role->id) continue;
					$rolesPermissions[$role->name] = $value;
				}
				$data['rolesPermissions'] = $rolesPermissions;
			}
		}
