### ISSUE TITLE
Image resizer doesn't preserve EXIF data

### ISSUE THREAD

**Issue by uiii** [processwire/processwire-issues#348]
### Short description of the issue

Image resizer doesn't preserve image's EXIF data (capture date, place, camera info, ...). 

### Expected behavior

Resized image inherits all the relevant EXIF data.

### Actual behavior

The resized image has all the EXIF data removed like a completely new image.

### Steps to reproduce the issue

1. Create image field
2. Set maximum dimesions (maybe enable client side resizing)
3. Upload image with EXIF data set
4. Download the uploaded image and compare it's EXIF data with the original one.

### Setup/Environment

* ProcessWire version: 3.0.70
* (Optional) PHP version: 5.6

**Comment by ryancramerdesign** [comment]
As far as I know that info only remains in a non-resized image, but @horst-n would know better than me. I think you'd likely have to disable max dimensions (or set it to refuse images exceeding max dimensions) so that you can retain a copy of the original with the extra data in it.

**Comment by uiii** [comment]
My intentions is to resize the image on client size before uploading, which works, but the EXIF data are lost. I can't (don't want to) upload the original image.

**Comment by Toutouwai** [comment]
The client-side resizer includes [exif-js](https://github.com/exif-js/exif-js) which can read the EXIF data from the original, but I don't think it supports writing EXIF data.

Maybe exif-js could be replaced with something like [piexifjs](https://github.com/hMatoba/piexifjs) which can both read and write.

**Comment by horst-n** [comment]
I'm not comfortable with clientsite resizing. Keeping in mind that this includes hundreds of different devices, I'm also will not go into this field.

**Comment by netcarver** [comment]
@uiii Hi Richard, this is quite an old issue now. Do you know if it has been taken care of with the client-side resizing options that were added?

**Comment by uiii** [comment]
@netcarver Hi Steve, could you please give me a link with description of the client-side resizing, I'm not sure if I missed that. Yes it is quite old and I didn't care about this a while, but now it may be relevant again because I will work with a project where I had the issue.

**Comment by netcarver** [comment]
@uiii The link is [here](https://processwire.com/talk/topic/16412-pw-3063-client-side-image-resize-support/), Richard. However, I now see it pre-dates the version of PW you reported this issue against, so it's probable this is still an issue.

**Comment by netcarver** [comment]
@uiii Hi Richard. I'm gradually working through old issus with a view to closing those that are fixed or otherwise now invalid. Could you give us an update on the issue? Is it still valid? I'll review this next week and close if there's no further information.

**Comment by netcarver** [comment]
Closing as no feedback. @uiii Richard, please post again if needed.
