### ISSUE TITLE
line-through decoration disappears when hovering on an unpublished repeater item

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#35]
### Short description of the issue

Strikethrough disappears when hovering on an unpublished repeater item

### Expected behavior

The background of the repeater item header bar should darken (as it does), but the line-through should remain

### Actual behavior

The line-through is removed. Not a huge deal, but just another weird inconsistency.

### Optional: Suggestion for a possible fix

I would send you a PR, but I know for this small stuff you find it easier to do manually.

**Comment by ryancramerdesign** [comment]
Things get hard to read with line-through, so prefer it disappears when I hover it, so long as there is some other indicator that the item is unpublished. In this case, there is (the toggle), so i think it's best to leave this one as-is.
