### ISSUE TITLE
Hard limit on or-groups breaks selectors

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#353]
### Short description of the issue

If I have more than 20 or groups, then selector breaks. This kind of selector returns multiple pages even when it has id=1002 on selector:

template=basic-page, (ref=11015), (ref=11016), (ref=11017), (ref=11018), (ref=11019), (ref=11020), (ref=11021), (ref=11022), (ref=11023), (ref=11024), (ref=11025), (ref=11026), (ref=11027), (ref=11028), (ref=11029), (ref=11030), (ref=11031), (ref=11032), (ref=11033), (ref=11034), (ref=11035), (ref=11036), (ref=11037), id=1002

That selector is of course badly written and can be easily fixed by using ref=11015|11016|...|11037.

But the way the selector breaks in case where there is more than 20 or groups is very dangerous - it leaves out everything that comes after 20th or group.

### Expected behavior

template=basic-page, (ref=11015), (ref=11016), (ref=11017), (ref=11018), (ref=11019), (ref=11020), (ref=11021), (ref=11022), (ref=11023), (ref=11024), (ref=11025), (ref=11026), (ref=11027), (ref=11028), (ref=11029), (ref=11030), (ref=11031), (ref=11032), (ref=11033), (ref=11034), (ref=11035), (ref=11036), (ref=11037), id=1002

Should return only page with id=1002.

### Actual behavior

Now it returns all pages that match selector like:

template=basic-page, (ref=11015), (ref=11016), (ref=11017), (ref=11018), (ref=11019), (ref=11020), (ref=11021), (ref=11022), (ref=11023), (ref=11024), (ref=11025), (ref=11026), (ref=11027), (ref=11028), (ref=11029), (ref=11030), (ref=11031), (ref=11032), (ref=11033), (ref=11034)

### Optional: Screenshots/Links that demonstrate the issue

I have a simple test installation that I wrap up and send as a site profile.

### Optional: Suggestion for a possible fix

Ideal would be supporting more than 20 or groups. If that is not possible, then we should not allow that selector to "work" at all.

### Steps to reproduce the issue

1. Create at least two pages that have more than 20 pages selected in one page reference field
2. Create selector that chooses at least 20 of those references + add after that id=xxxx condition
3. You should get both pages instead of one.

As I told earlier, I have test installation and I send it to Ryan through pw forum.

### Setup/Environment

* ProcessWire version: 3.0.72
* (Optional) Any 3rd party modules that are installed and could be related to the issue:
none

**Comment by ryancramerdesign** [comment]
Thanks Antti, another great find. I've pushed a fix for this issue. It wasn't about OR groups per se but rather some built in overflow protection in the Selectors class. Looking at it now, it's better not to have that overflow protection than to have it, as looks like it could cause more problems than it could prevent.

**Comment by netcarver** [comment]
Hello again @apeisa. Another one for your closure consideration.
