### ISSUE TITLE
pageref1.pageref2.fieldname='' fails on selectors

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#354]
### Short description of the issue

It is possible to use pageref1.pageref2.fieldname syntax on selectors, which is great feature. It works fine when you define exact value for it, like pageref1.pageref2.fieldname=abc

But if you try to find pages where that value is empty, it's not possible:

pageref1.pageref2.fieldname='' or pageref1.pageref2.fieldname=

both return all pages, no matter what the value at fieldname= field is.

This code snippet explains it well:

```
$sel = "template=basic-page, pageref1.pageref2.headline=";
echo "<br>" . $pages->count($sel) . "<br>";
foreach($pages->find($sel) as $p) {
  echo "This should be empty but it is not: " . $p->pageref1->pageref2->headline; 
}
```

That echoes (in my test installation) this text:

This should be empty but it is not: I have a headline

### Expected behavior

Empty value should be possible search criteria when using pageref1.pageref2.fieldname= condition in selector. It should find only those pages where fieldname is empty - now it doesn't matter what there is in fieldname.

### Actual behavior

Currently it doesn't matter what there is in fieldname when you try to find empty values through two page reference fields.

### Optional: Suggestion for a possible fix

Empty should work on selector through two page reference fields.

### Steps to reproduce the issue

1. Create two page reference fields. Call them pageref1 and pageref2 and allow template "basic-page"
2. Add those fields into basic-page template in default processwire installation
3. Then edit/create three pages. First one has second page chosen in pageref1, second has third page chosen in pageref2 and finally third page has some value in "headline" field.
4. Then selector template=basic-page, pageref1.pageref2.headline= should not find the first page, because third page has empty value in headline. 

I will send site profile for Ryan through forums.

### Setup/Environment

* ProcessWire version: 3.0.72
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Nope

**Comment by apeisa** [comment]
This can be avoided with pretty ugly "hack", instead of `headline=''` or `headline=` you can use `headline=valuethatwillnevermatch|`

**Comment by ryancramerdesign** [comment]
Thanks Antti, that's a good find! I've pushed a fix for this issue.

**Comment by netcarver** [comment]
Hi @apeisa. Antti, could you please close this if it's fixed. Thank you!
