### ISSUE TITLE
“PageFinder” ignores “Language Support / Blank Behavior” option

### ISSUE THREAD

**Issue by kondurake** [processwire/processwire-issues#355]
I installed LanguageSupport module and defined two languages: default and romanian. I created a field named “translated” and from “Details” tab for the “Language Support / Blank Behavior” option, I chose “Remain blank”.

Next, I created four pages:
1) Alpha (default “translated=0”, romanian “translated=1”)
2) Beta (default “translated=1”, romanian “translated=0”)
3) Charlie (default “translated=1”, romanian “translated=1”)
4) Delta (default “translated=0”, romanian “translated=0”)

Now I’m trying to use `$pages->find('translated=1')` to get all translated pages for the “active” language. Well, on the “Default” side I get the right results:  Beta and Charlie. However, on the “Romanian” side I get wrong results: Alpha, Beta and Charlie. After some tests, I found out that PageFinder returns the “Beta” page because the field is completed for the default language (for example “Delta” page is not returned in any side, and the “Charlie” page is not returned if I remove “translated” value for default language).

### Suggestion for a possible fix
I was able to fix issue by patching the function [LanguageSupportFields::pageFinderGetQuery](https://github.com/processwire/processwire-legacy/blob/master/wire/modules/LanguageSupport/LanguageSupportFields.module#L305) from the file **/wire/modules/LanguageSupport/LanguageSupportFields.module** — found condition [$subfield === 'data'](https://github.com/processwire/processwire-legacy/blob/master/wire/modules/LanguageSupport/LanguageSupportFields.module#L344) and added the following snippet at the beginning of the conditional block:
```
if ($this->wire('fields')->get($field)->langBlankInherit == LanguagesPageFieldValue::langBlankInheritNone) {
	// Remove default field name from the selector if according to "Blank Behavior" value should "Remain blank"
	unset($fields[$key]);
}
```

Please note that this “fix” doesn’t handle the “multilang alternates” fields (like “translated_ro”). Moreover, I could not assess the correctness of this fix and potential compatibility issues.

### Setup/Environment
* ProcessWire version: 2.8.62
* LanguageSupport.module: 1.0.3
* PHP version: 5.5.0
* MySQL version: 5.5.5
* Nginx: 1.13.4

**Comment by ryancramerdesign** [comment]
The purpose of the langBlankInherit options is actually for front-end output purposes, so that you can sub in the default value if a lang value is blank. I hadn't intended for it to go further than that, affecting page queries and such. But it's an interesting idea, so will have to think about that more. But currently you can target just one language with a page query by specifying `$pages->find("field.data$user->language=value");`

**Comment by kondurake** [comment]
Thanks for the reply and the hint. I think regular selectors like `field=value` are much better. At least for me PW selectors are one of the main advantages, therefore, I hope that soon we will get a simpler solution. If this is not possible, a good replacement would be something like `field.lang=value` which before query should be replaced by `field.data$user->language=value`

**Comment by kondurake** [comment]
As workaround I wrote a hook that allow to use `field.lang=value`. I hope someone will find it useful:
```
wire()->addHookBefore('PageFinder::getQuery', function($event) {
	if ($event->object->template != 'admin') {
		$lang = $this->wire('user')->language;
		$dataid = empty($lang->id) || $lang->isDefault() ? '' : ".data{$lang->id}";

		foreach ($event->arguments[0] as $selector) {
			$fields = (array) $selector->field;
			foreach ($fields as $k => $field) {
				$fields[$k] = preg_replace('#\.lang$#', $dataid, $field);
			}
			$selector->field = $fields;
		}
	}
});
```

**Comment by netcarver** [comment]
@ryancramerdesign Any further thoughts on @kondurake's ideas above? Should this be moved to the requests repo?

**Comment by ryancramerdesign** [comment]
@netcarver I think kondurake came up with a good solution for their use case, but I don't think we should make any changes to the core related to this at present. I'll keep my eyes out to see if the need re-occurs regularly in which case we may want to consider more options at that time.

**Comment by netcarver** [comment]
/remind me to review this issue in 1 month

**Comment by ryancramerdesign** [comment]
@netcarver I don't think we need this as an ongoing (leave open) because no core changes are planned for this, so I think it's okay to close for now.
