### ISSUE TITLE
Cannot use home page ID for redirectLogin in template access settings

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#357]
### Short description of the issue

When disallowing view access in a Template's Access tab, I am not able to specify the home page as the page to redirect to. ProcessPageView::checkAccess() specifically disallows using the home page (ID of 1) for the page ID, silently overwriting it with page ID of the admin login form. 

For some websites and many web applications, all pages except for the login page should be inaccessible to guests.  Since ProcessWire does not allow you to remove the view permission for the guest role from the home template (should this limitation be reconsidered?), this makes the home page the best candidate to serve as the login page. However, due to the above mentioned issue, I am not able to do so.

### Expected behavior

The user is redirected to the home page.

### Actual behavior

The user is redirected to the Admin login page.

### Optional: Suggestion for a possible fix

Remove line 567 in ProcessPageView::checkAccess()

### Steps to reproduce the issue

1. Edit a template.
2. Remove view access from all user roles.
3. Check "Redirect to another URL"
4. Enter "1" in the URL field (the ID of the home page)
5. View page

**Comment by ryancramerdesign** [comment]
That value "1" for the template redirect setting is meant to refer to whatever is the current login page. I don't recommend using the homepage as your login page if at all possible, and instead setup something dedicated for the purpose like /login/ or /tools/login/. Though it's fine if you want to duplicate/display a login form on your homepage, and then have that form submit to your login page. While I've not tried it before, if you still want your homepage to also serve as the login page, you can set the `$config->loginPageID = 1;` But since a homepage most commonly the index page of a hostname, definitely consider an alternative page for you login if possible.

**Comment by thetuningspoon** [comment]
Hi @ryancramerdesign ,

Thanks for the reply. Are you saying that the code does not distinguish between the "Show the Login page" radio button being selected and the "Redirect to another URL" radio button being selected with a value of 1 in the "Enter the URL..." text input?  That seems like a bug that should be fixed.   

I didn't consider replacing the admin login page entirely. That is a possibility, although I really prefer to keep both in many cases (the default admin login when logging into the admin to configure the app, and the front end form for users of the actual application).

I see your argument about not using the home page for the login. I agree. But the problem with using the home page as the actual home page of my app is that I cannot disable view access for guests. So either I have to just make that page a redirect or I have to do something hacky to disable view access. Do you have any suggestions?

I ended up selecting "Show a 404 Page" for all the templates I wanted to redirect to my application login, and then writing my own logic in a hook to redirect to the home page login screen if the 404 was the result of a view access restriction rather than a true 404 not found. Feels hacky.

**Comment by Toutouwai** [comment]
> But the problem with using the home page as the actual home page of my app is that I cannot disable view access for guests.

On this topic, you could write your own logic in the home template to restrict access:

```php
if(!$user->isLoggedIn()) { // or $user->isGuest()
   // do not display content, show login form, redirect, etc
}
```

**Comment by thetuningspoon** [comment]
@Toutouwai Definitely could... I am just trying to work out where it makes sense to make use of PW's built in functionality vs overriding it.

**Comment by netcarver** [comment]
@thetuningspoon Michael, if you are ready, could this be closed?

**Comment by thetuningspoon** [comment]
I suppose
