### ISSUE TITLE
Repeaters not working inside Repeater Matrix

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#359]
### Short description of the issue

I'm using blocks in which you can define sliders or text, as sort of a page builder. Adding a repeater in the repeater matrix will cause the second repeater not to work. 

### Expected behavior

The second repeater should add a repeater item. 

### Actual behavior

Clicking add new will jump you to the top of the page. 

### Steps to reproduce the issue

1. Create a repeater matrix
2. Add a repeater into the matrix
3. When creating a page, try create two matrix items with a repeater
4. The repeater in the second matrix item will not work. 

### Setup/Environment

* ProcessWire version: 3.0.73
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

EDIT: 
Worth noting that this only applies when the repeater matrix with the repeater is open. It seems to be a javascript error.

**Comment by ryancramerdesign** [comment]
Thanks for the report. I've pushed a fix for this. Though the way I duplicated it was a little different than your setup, so just wanted to confirm that it's also working for you? Thanks.

**Comment by netcarver** [comment]
@TomS- Hello there. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.
