### ISSUE TITLE
Image name to include quality when defined

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#361]
### Short description of the issue

It's becoming more common to show a low-res image and lazyload the higher quality image. That way content is always served and quality isn't sacrificed. Using the quality option this can be done easily by defining quality => 20 then quality => 90 as they carry the same file size only the low resolution is saved

### Expected behavior

Two files of different quality is saved

### Actual behavior

Only one file is saved

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. $page->image->size(1920, 1080, ["quality" => 20])->url
2. Then use 
3. $page->image->size(1920, 1080, ["quality" => 90])->url
4. Quality 20 is still shown

### Setup/Environment

* ProcessWire version: 3.0.72
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
I think you can accomplish this by using the `suffix` option, i.e. 
~~~~~
$page->image->size(1920, 1080, ["quality" => 20', 'suffix' => 'low']);
$page->image->size(1920, 1080, ["quality" => 90, 'suffix' => 'high']);
~~~~~
The "low" and "high" could be any words that you want to identify your variation.
