### ISSUE TITLE
Default first item in repeater with min count doesn't save if new item added before first save

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#363]
### Short description of the issue

The default pre-made item in a repeater that has a min count doesn't save upon the first save, but only if another item is added before the first save.

The same bug occurs with the Repeater Matrix, too.

### Expected behavior

Both items should save

### Actual behavior

The first pre-made item doesn't save

### Steps to reproduce the issue

1. Create a repeater with a min count of 1
2. Add it to a template
3. Create a page of that template
4. Edit the page, create an item before touching the first
5. Save page

The first item that was there by default due to the min count doesn't save, but the newly added one does.

If you save before adding another item, the first default item does actually save.

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks @CaelanStewart I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@CaelanStewart Hello Caelan. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.

**Comment by CaelanStewart** [comment]
@netcarver 

Hi,

Yes, this appears to be fixed now.
