### ISSUE TITLE
Reno theme + pro-drafts broken save button

### ISSUE THREAD

**Issue by hagcin** [processwire/processwire-issues#365]
### Short description of the issue

When adding the permission "page-publish" , and logging in as a user that does not have that permission, the publish button will be removed, but only part way, and a set of links belonging to that button will still show.

**Use Case:**
Setting up a workflow where users can draft pages, but not publish them. (so that all content can be reviewed first)

Forum Link: https://processwire.com/talk/topic/17082-bug-when-adding-page-publish-permission/#comment-149976
### Expected behavior

save link should not look broken

### Actual behavior

save link looks broken

### Optional: Screenshots/Links that demonstrate the issue

https://processwire.com/talk/uploads/monthly_2017_08/Screen_Shot_2017-08-29_at_12_20_12_PM.thumb.png.78e5964960dc5a61dd36d7428e0dbb63.png

### Steps to reproduce the issue

1.  Add page-publish permission.
2.  set users theme to RENO.
3. log in in as a user that does not have that permission. (not super user)
4.  Edit existing page. (page might have to support drafts)

### Setup/Environment

**System:**
Clean install with pro drafts, and croppable image 3. ProcessWire 3.0.62

**Browser:**
Safari (but likely more)

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this one, but when testing I was also using the latest version of ProDrafts, which has quite a few updates in it. Please let me know if you continue to experience issues in the latest version. Thanks.

**Comment by netcarver** [comment]
@hagcin Hello. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.
