### ISSUE TITLE
FieldsetPage does not save value of fields in nested repeater matrix

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#367]
### Short description of the issue

I have a setup where I have repeater field and inside of this repeater, I have repeater matrix. In both repeater and repeater matrix I have the same FieldsetPage field.

I fill in some fields inside FieldsetPage field in repeater items and values are saved, then I fill in fields inside FieldsetPage in nested repeater matrix and they are not saved. 

### Expected behavior

Values of fields get saved. 

### Actual behavior

Values of fields are not get saved. 

Page for this FieldsetPage is created under Admin/Repeater. 

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 3.0.74

**Comment by ryancramerdesign** [comment]
Thanks @Lazerproof I've pushed a fix for this. Please let me know if you continue to see any issues.

**Comment by netcarver** [comment]
@Lazerproof Hello, Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.
