### ISSUE TITLE
If template file is not found, there's no entry in the error log to indicate that is what PW is looking for (and missing)

### ISSUE THREAD

**Issue by FrancisChung** [processwire/processwire-issues#368]
### Short description of the issue

If a template module is incorrectly named (e.g. automation.php instead of Automation.php), PW does not log an entry in its Error Log. 

### Expected behavior

A verbatim detailed entry in the Error Log saying the Template (e.g. Automation.php) is not found.

### Actual behavior

I just get a 404 Page not found error with an Edit Link. There are no error log entries or log entries of any kind. It has mislead me to thinking that there was a page missing or page setup incorrectly when it was the actual template file itself.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Create a template (e.g. Automation)
2. Create a page that its casing different but the same spelling (e.g automation)
3. Associate the template to the page
4. Create the template php file with the misspelt name (e.g. automation.php)

### Setup/Environment

* ProcessWire version: 2.8
* (Optional) PHP version: 7.0.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Having a page without a template file connected to it is a common use case in PW, and this is not an error condition. You create a corresponding template file for a page only if you want it to have a front-end URL accessible location for output. Very often pages are used for data storage, not for front-end output. If you want to log 404s independently of Apache, here's a recent post that has more info about doing that: https://processwire.com/blog/posts/optimizing-404s-in-processwire/

**Comment by FrancisChung** [comment]
So would logging 404 errors with either ProfilerPro or PW Logs as specified in the link above catch name mismatching issues I had with templates?

**Comment by netcarver** [comment]
@FrancisChung This issue was opened against an older version of PW. Is this issue still valid in newer versions?

**Comment by FrancisChung** [comment]
@netcarver I'm not using PW these days. You may close the issue if you wish.

**Comment by netcarver** [comment]
@FrancisChung will do, thank you and best wishes with your current endeavours.
