### ISSUE TITLE
Variations page doesn't display the last modified image versions

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#369]
### Short description of the issue

The Variations page displays only the very first cached images. This leads to client confusion.

### Expected behavior

The last modified image versions should loaded.

### Optional: Suggestion for a possible fix

On the wire/core/Pageimage.php replace the lines 1094 & 1108 with:
`'url' => $this->pagefiles->url . $basename . "?nc=" . $this->mtime,`

### Setup/Environment

Using Cloudflare Standard cache. The issue is happening even on localhost.

**Comment by ryancramerdesign** [comment]
While I can't see the issue yet here, I think I understand what you mean, and you are right the variations URL's should probably use nocache versions like the others. I can definitely envision how browser cache could come into play here. I've pushed an update that makes the variations list use nocache URLs. Thanks.

**Comment by PWaddict** [comment]
Thank you @ryancramerdesign. Problem fixed.
