### ISSUE TITLE
Can't select "None" for Date Input Format for InputfieldDatetime

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#37]
### Short description of the issue

If I select "None" in the "Date Input Format" field in the "Input" tab while configuring a Datetime field, It reverts to it's default value when I click save.

### Expected behavior

For it to maintain it's value of "None" after save, and then only be able to select a time using the Datetime field.

### Actual behavior

It reverts to its default value of "2016-04-08".

### Steps to reproduce the issue

1. Create a new field with type "Datetime"
2. Go to the "Input" tab
3. Set the value of "Date Input Format" to "None"
4. Click save
5. Notice how it's value is now "2016-04-08"

### Setup/Environment

* ProcessWire version: 3.0.35

I'm guessing it's because the timestamp, when converted back into a human readable date would actually read "01-Jan-1970 5:10pm", which is obviously not correct.

It's not a big deal, it's just that it would be good if the Datetime input would could just contain a time, as I have a use case, and can think of more. For a site I am working on right now, we need them to be able to select a date, and then two times that are on the same date. And AFAIK, there is no in-built way to enforce those rules on two separate Datetime fields.

Perhaps a better solution might be to remove the "None" option from the field, and then create another field type which is capable of containing only a time, and that time would be represented internally as an integer between 0 and 86400. And then you could just add the timestamp from the date, and the mini-timestamp from the time, and have a complete timestamp?

**Comment by LostKobrakai** [comment]
I'd strongly suggest using this for only time fields: https://processwire.com/talk/topic/7857-module-fieldtypetime-inputfieldtime/

**Comment by CaelanStewart** [comment]
@LostKobrakai, epic! I had pondered the existence of such a thing. I did search the PW modules site for "time field", but there were about six pages of mostly unrelated results. I must have missed it.

Thank you for letting me know of this. Though, I must say, it may be worth removing that "None" option, still, to avoid future confusion.

**Comment by ryancramerdesign** [comment]
Thanks, I have removed the "None" option for the dateInputFormat.
