### ISSUE TITLE
Some classes missing from the API Ref

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#370]
Forum Post Here: https://processwire.com/talk/topic/16897-missing-api-reference-fieldgroups/

### Short description of the issue

The Fieldgroups class is missing from the [reference](http://processwire.com/api/ref/), and I wasn't sure why! 

### Expected behavior

I would expect that the API Ref Docs page would have API references for every Core Class.

### Actual behavior

Several classes are missing.

Also, [according to](https://processwire.com/talk/topic/16897-missing-api-reference-fieldgroups/?do=findComment&comment=148788) @adrianbj:
> There actually seems to be the opposite problem with: http://processwire.com/api/ref/wire-database-backup/ - that page 404s, but is linked to under Core Classes > WireDatabaseBackup in the dropdown.

### Optional: Suggestion for a possible fix

I feel like the docs would be easier to parse/navigate if the API Variables were shown alongside the class they were an instance of.

 - Config ($config)
 - Field
 - Fields ($fields)
 - Fieldgroup
 - Fieldgroups ($fieldgroups)
 - Fieldtype
 - HookEvent
 - Inputfield
 - InputfieldWrapper
 - MarkupPagerNav
 - Module
 - Modules ($modules)
 - ...
 - Page ($page)
 - Pages ($pages)
 - ...

I'm also aware of the API Gen reference page (https://processwire.com/apigen/index.html), which is more robust, but a little harder to parse.

I've been saying for a while that I'd love to help the docs get better. As they are now, I think they're pretty good - but things could always improve, and if there is one thing in development I am uber-passionate about, it's documentation!!

**Comment by netcarver** [comment]
@ethanbeyer Hello Ethan, could you double check this is still an issue. I just had a quick look on the API reference page and found [this](http://processwire.com/api/ref/fieldgroup/). Does that cover what you were expecting? If so, can this issue be closed?

**Comment by adrianbj** [comment]
@netcarver - the issue that I brought up (noted in the OP) is still 404'ing, so this issue still certainly needs some attention.

**Comment by netcarver** [comment]
@adrianbj Noted. @ethanbeyer Please ignore my last regarding closing this issue at the moment.

**Comment by ethanbeyer** [comment]
@netcarver I know this issue is super old/stale, but how are we doing on this front?

**Comment by netcarver** [comment]
@ethanbeyer @adrianbj Looks like the [link](https://processwire.com/api/ref/wire-database-backup/) you originally reported as 404 is now live given the site redesign. Please could you confirm. I'll close if that satisfies this issue.

**Comment by netcarver** [comment]
/remind me to review this issue in 2 days

**Comment by adrianbj** [comment]
Hey @netcarver - $fieldgroups (note plural) exists in the docs (https://processwire.com/api/ref/fieldgroups/), but isn't linked to from here: https://processwire.com/api/ref/

The WireDatabaseBackup issue I mentioned does seem to be resolved now though.

**Comment by netcarver** [comment]
@ryancramerdesign Seems to be nearly done, the rest looks like an easy fix?

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
@netcarver I think it's okay to close. The API reference index just provides a curated selection of classes and API variables that I picked out to appear on that page, focusing just on those that I thought would be good starting points. It would be overwhelming if it showed everything at that index. There are cross references throughout the API reference to most other unlisted classes for cases when they become useful. Of course it's all findable from the search engine too.
