### ISSUE TITLE
Tree menu text gets smaller and smaller with each nesting

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#372]
### Short description of the issue

With every level of nesting, the text in the Tree menu gets smaller and smaller.

![2017-09-14_180111](https://user-images.githubusercontent.com/1538852/30414344-2de24678-9977-11e7-8084-f5cae8767ac9.png)

### Expected behavior

Consistent text size within the menu.

### Setup/Environment

* ProcessWire version: 3.0.74

**Comment by ryancramerdesign** [comment]
It's supposed to get smaller in AdminThemeDefault, but I guess I figured one would run out of screen real estate before it got too small to read. It looks like your top nav is not right aligned how it should be, so you are navigating quite a bit deeper than what I was thinking one would use this for (seems better suited to the regular pages tree). I understand what you are saying, but I'm not sure we should remove this – page titles tend to get longer the further you are from the root, when you get into long article headlines, etc., so going a little smaller can be helpful.

**Comment by adrianbj** [comment]
> It looks like your top nav is not right aligned how it should be, so you are navigating quite a bit deeper than what I was thinking one would use this for

@rolandtoth added this option (https://github.com/rolandtoth/AdminOnSteroids/wiki#admintweaks) to his AdminOnSteroids module after this comment from me and a request by @Toutouwai :
https://github.com/processwire/processwire/commit/bbb8e987c93207472f61e44c5fca3bec8ed935f7#commitcomment-21211994

**Comment by Toutouwai** [comment]
I agree that the text in the Tree menu should be smallish, but I think some fixed size should be determined that is small enough to be efficient but not so small as to create readability issues. Then all nesting levels should get this size. It seems wrong to have a style rule that results in ever-decreasing text size without a lower limit, and it also implies assumptions about nesting level (more deeply nested pages are somehow less significant?) that I'm not sure always hold up.

But this isn't a major issue (in any case, I usually disable the Tree menu for editors for reasons discussed in [another issue](https://github.com/processwire/processwire-issues/issues/231)) and it's fine to close this issue if you'd prefer to keep the status quo.

**Comment by Toutouwai** [comment]
> I figured one would run out of screen real estate before it got too small to read.

On this subject, for any dropdown/flyout menu system it's nice to have "smart" dropdowns that respond the right edge of the browser window by expanding submenus in the other direction.

Example: http://logicalstack.com/demo/scoop/example/horizontal-navigation-onHover.html
![2017-09-22_110204](https://user-images.githubusercontent.com/1538852/30722463-948f3c82-9f85-11e7-986c-8cdd36290dc7.png)

**Comment by Toutouwai** [comment]
Will close this seeing as the issue doesn't apply to the new AdminThemeUikit. Have solved the issue with AdminThemeDefault for myself with a custom CSS override.
