### ISSUE TITLE
publish + next should not redirect to next on error

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#374]
### Short description of the issue

when you publish a page with the option "publish + next" with a required field and you leave this field empty processwire redirects you to the next available item and marks the field of the next page with an error

### Expected behavior

it should stay on that page and not redirect to the next page

### Actual behavior

it throws an error but on the wrong page (next page)

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/8488586/30478533-b793a5ca-9a11-11e7-9cc1-1ef12ea0466c.png)

### Steps to reproduce the issue

1. create a template with a required field
2. create one page and publish it
3. create another page and leave all fields empty
4. click on publish + next

it will throw an error and show the already published page

* ProcessWire version: 3.0.73

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock I've pushed a fix for this issue.

**Comment by BernhardBaumrock** [comment]
thanks!
