### ISSUE TITLE
CKEditor js error on scrollbar hover

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#376]
CKEditor 4.7.0 contains a bug that causes a JS error when hovering the editor scrollbar. It was fixed in version 4.7.2+.

https://github.com/ckeditor/ckeditor-dev/issues/515

I haven't noticed any malfunction though.

### Optional: Suggestion for a possible fix

Update to latest CKEditor (4.7.3 worked fine in my tests).

**Comment by ryancramerdesign** [comment]
Thanks, I've updated the CKEditor version to 4.7.3

**Comment by rolandtoth** [comment]
Thanks!

**Comment by rolandtoth** [comment]
Yes it's fixed, thanks.
