### ISSUE TITLE
Module cache causes issues at installation when using custom site profile

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#377]
### Short description of the issue

When installing PW with a custom site profile (created with ProcessExportProfile) there are issues with Fieldtype modules in /site/modules/ not being loaded to $fieldtypes immediately after installation. Seems to be due to an outdated module cache.

Related forum thread: https://processwire.com/talk/topic/17230-fieldtype-not-found-after-installation-of-site-profile/

### Expected behavior

Error-free PW installation using custom site profile.

### Steps to reproduce the issue

1. Install FieldtypeMapMarker, or any non-core Fieldtype module, to /site/modules/
2. Create field of type Map Marker.
3. Install FieldtypeRepeater (in order to see error in recent PW dev versions)
3. Install ProcessExportProfile and export the site profile.
4. Start new PW installation process, selecting the exported site profile.
5. At the end of the installation process observe the following errors...

PW 3.0.62
![2017-09-20_155753](https://user-images.githubusercontent.com/1538852/30626502-6f875a54-9e1e-11e7-9102-4a1825dc89e5.png)

PW 3.0.75 (when FieldtypeRepeater is installed in site profile)
![2017-09-20_135929-2](https://user-images.githubusercontent.com/1538852/30626521-8b071436-9e1e-11e7-9ca4-e252aeedd441.png)

### Optional: Suggestion for a possible fix

1. Refresh the module cache at the last step of the install process (thanks Abdus for the suggestion).
````php
/**
 * Execution controller
 *
 */
public function execute() {
    // ...
    if(isset($_POST['step'])) switch($_POST['step']) {
        case 0: $this->initProfile(); break;
        case 1: $this->compatibilityCheck(); break;
        case 2: $this->dbConfig();  break;
        case 4: $this->dbSaveConfig();  break;

        case 5: require("./index.php");
            /** @var ProcessWire $wire */

            // Refresh module cache
            $wire->modules->refresh();

            $this->adminAccountSave($wire);
            break;

        default:
            $this->welcome();

    } else $this->welcome();

    // ...
}
````
2. Allow for null field types in code that may run before module cache has had a chance to refresh.
In [FieldtypeRepeater.module](https://github.com/processwire/processwire/blob/2a3be7209cab0fc6f8cb2a686ff6c395fc971f5a/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module#L148)...
````php
if(!$field->type || $field->type->className() != $className) continue;
````

### Setup/Environment

* ProcessWire version: 3.0.62 and 3.0.75
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix to the dev branch.

**Comment by Toutouwai** [comment]
Thanks!
