### ISSUE TITLE
AdminTheme topnav rendering

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#378]
### Expected behavior

Any AdminTheme should render the same items in the Topnav

### Actual behavior

AdminThemeDefault doesn't render Topnav items without page-view permission (expected)
whereas AdminThemeUikit does

### Optional: Suggestion for a possible fix

**AdminThemeFrameWork::getPrimaryNavArray()** (used by AdminThemeUikit) should check `$page->viewable()` similar to
**AdminThemeDefaultHelpers::renderTopNavItems()** Line:444 (used by AdminThemeDefault)

add
`if(!$p->viewable()) continue;` 
in **AdminThemeFrameWork::getPrimaryNavArray()** (Line 370) 

### Setup/Environment

* ProcessWire version: 3.0.74
* AdminThemeUikit version: 0.0.2

**Comment by ryancramerdesign** [comment]
This is deleted to the `AdminThemFramework::allowPageInNav()` method instead, which forces `pageToNavArray` to return null if the page isn't allowed. So if you are seeing something you shouldn't, there must be some additional logic needed in the allowPageInNav()  method. What pages are you seeing that you shouldn't? I'm guessing maybe those using ProcessList, like Setup and Access?

**Comment by kixe** [comment]
Ok. Could you than add a logic to `AdminThemeFramework::allowPageInNav()` forcing return false if `$page->viewable()` returns false or is there any case where an admin page (not viewable) needs a tab in the navigation?

Could you **add after Line 302**: `if($this->isSuperuser) return true;`
**this line**: `if($p->viewable() return false;`

I have a module which hooks in `Page::viewable()` to hide the pagetree for specified roles. But I need page-edit permission for some roles (blog authors e.g.) using a custom Process (kind of very limited Page Edit Interface)

**Comment by ryancramerdesign** [comment]
Which extra tabs are you seeing show up? When it comes to the admin, access is determined a little differently. All the admin pages use template "admin", so it's the permissions provided by each Process module that determine access, and not whether a page is viewable. The viewable() is only supposed to come into play if the page has no Process module assigned to it to dictate access. If we add a line at the top to return false if(!$p->viewable()) that would bypass the intended Process module access control. Though I'm not sure how much of a problem that is just yet, will have to experiment some more. I understand the case you are mentioning though, so have to think a little more about how best to handle it. Maybe the Process module access control used by the admin needs to be moved as a hook to Page::viewable() too, or maybe the logic currently in AdminThemeFramework needs to migrate into PagePermissions.module.

**Comment by kixe** [comment]
The only tab showing up in `AdminThemeUikit` but **not** in `AdminThemeDefault` is the **Pages** Tab. They use different functions to render the Nav as I mentioned. It would be great to have consistent behaviour here.
The related project uses ProcessWire completely without frontend. A login protected information and discussion area. Every page (een home and 404) has the admin template assigned. I use some custom processes.

I have '**page-edit**' permission assigned to a role, to provide `ProcessPageEdit` from another page than the default edit page, but I don't want to show up the (big) pagetree.
It would be a great benefit for some usecases to have one permission for each process, like '**page-list**' for `ProcessPageList` and '**page-edit**' for `ProcessPageEdit`.

In general I would like to see ProcessWire moving in the direction of a PHP based application framework. It is already possible and I have some projects running. But to get it proper working I need always some hacks. Luckily most of the things could be done with hooks, not touching the core or wire modules.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.

**Comment by ryancramerdesign** [comment]
@netcarver @kixe There's more to the access control checks here in AdminThemeFramework than it appears, and if I start messing with the logic in there to try and accommodate a use case like this, I think there's a risk of breaking something else. (AdminThemeDefault does not use the framework but AdminThemeUikit does). As a result, if there is still a need for this, I'm happy to add a special hook or config setting to accommodate it instead. Let me know if it is still needed. Thanks.

**Comment by netcarver** [comment]
@kixe, Christoph I know this is an old issue - but over to you!

**Comment by kixe** [comment]
@ryancramerdesign 
yes there is still a need, meanwhile also for further projects. A hook would be helpful here and would solve my problems. Thanks

**Comment by ryancramerdesign** [comment]
@kixe Which method were you thinking would be useful for a hook? I'm guessing the `AdminThemeFramework::allowPageInNav()` method? The only thing is, that method already calls `$page->viewable()` and returns false if it's not viewable (other than for superuser). So now I'm not sure that's what you are looking for since it sounds like you already were hooking Page::viewable, which would have the same effect.

**Comment by netcarver** [comment]
Hi Christoph, could you update this one as well please?  
Many thanks @kixe !

**Comment by netcarver** [comment]
@kixe Hi Christoph. I intend to close this in a couple of days if we can't get any more information that would allow progress to be made.

/remind me in 2 days
