### ISSUE TITLE
Field dependencies do not account for the situation where a field may be excluded from ProcessProfile

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#379]
### Short description of the issue

Field dependencies do not account for the situation where a field may be excluded from ProcessProfile. Specifically, ProcessProfile will not save if a field depends on a particular role being selected, even if the dependent field is not included on the ProcessProfile. The error message received is "Profile not saved".

Please see this thread for further details:
https://processwire.com/talk/topic/8754-profile-not-saved-help/?tab=comments#comment-151294

### Expected behavior

The profile should be saved.

### Actual behavior

Error message: "Profile not saved". Profile changes are not saved.

### Optional: Suggestion for a possible fix

My hacky fix was to edit the error check around line 140 in ProcessProfile.module so it simply disregards the error if there is only one and it has to do with "showIf":

`$errors = $form->getErrors();
if(count($errors)) {
  if(count($errors) == 1 && strpos($errors[0], 'showIf') !== false) {
  	// Everything is okay
  }
  else {
    $this->error(implode('; ', $errors)); // Show the actual errors instead of just a generic message
    return;
  }
}`

### Steps to reproduce the issue

1. Add a field to the user template
2. Set it's "showIf" setting so that it depends on the value of the roles field
3. Try saving the profile

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
What is the exact showIf dependency (string) that you are creating? If you are talking about the profile editor (rather than the user editor) then there should be no "roles" field present, as we don't allow people to edit their roles as part of their profile because that would be a security problem. If a form lacks a particular field, you can't create a dependency for it, otherwise there would be no way to save it. So a field with a dependency to "roles" is probably not a good candidate to add to your profile editor. Or let me know if I've misunderstood? Thanks.

**Comment by thetuningspoon** [comment]
I think you misunderstood. The field that is dependent on the roles field is NOT part of the profile editor, but it still prevents it from saving.

The exact string is roles=1234

**Comment by netcarver** [comment]
@thetuningspoon Bumping this to bring it back into focus. Do you know if this issue is still live in more recent versions of PW?

**Comment by thetuningspoon** [comment]
I assume so but I haven't tested to find out. We can close and reopen later if it comes up again.

**Comment by netcarver** [comment]
@thetuningspoon Thanks for the reply Michael. If you could close the issue, you'll be able to re-open it yourself later if it turns out to still be applicable. If I do it, you'll be able to comment - but that won't re-open it without a review from one of the repo maintainers.
