### ISSUE TITLE
Module upload doesn't show selected file

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#38]
### Short description of the issue

When selecting a module zip to upload it no longer shows the file that has been selected. I think this change happened maybe when the upload button was styled - I think that was fairly recently.

### Expected behavior

You should see the name of the file that was selected.

### Actual behavior

The button is "grayed out", but that's the only indication you have that a file was selected.

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2016-10-10 at 3 03 27 pm](https://cloud.githubusercontent.com/assets/871211/19252703/18de747c-8efb-11e6-807b-3ddeffb6a43a.png)

**Comment by ryancramerdesign** [comment]
I don't really have any idea how to make that happen with the custom styled button, so I've added a 'noCustomButton' option to InputfieldFile to disable it for cases like this. This appears in the latest commit. Thanks.

**Comment by adrianbj** [comment]
Not sure of how robust this is, but maybe worth a look: http://jsfiddle.net/hw5t2xcu/

![screen shot 2016-10-11 at 9 18 50 am](https://cloud.githubusercontent.com/assets/871211/19278842/c03227b2-8f93-11e6-81df-4a22b3eb6472.png)

![screen shot 2016-10-11 at 9 20 09 am](https://cloud.githubusercontent.com/assets/871211/19278905/f05eba9a-8f93-11e6-84ee-8f66fa5e1f02.png)

**Comment by mikerockett** [comment]
For me, this brings up `C:\fakepath\...`, which isn't ideal. I'd trim out the drive and directory, just keeping the file name. Perhaps a prefix too?

`Selected: filename.zip`

**Comment by adrianbj** [comment]
I get the same path too - I just a quick mod of a fiddle I found to show what might be possible. I just edited out the fakepath bit before taking the screenshot. But yes, if we do something like this then it should probably just be the filename only.
