### ISSUE TITLE
Prevent redirect loop while trying to log in

### ISSUE THREAD

**Issue by fbg13** [processwire/processwire-issues#380]
### Short description of the issue

It's possible for a redirect loop to happen if the 'login' GET variable is present in the url.

### Expected behavior

Redirect loop never happens.

### Optional: Screenshots/Links that demonstrate the issue

![redirect-loop](https://user-images.githubusercontent.com/6839895/30715213-279b4678-9f1e-11e7-9d58-b1e9031ee10e.gif)

### Steps to reproduce the issue

1. Log in in tab1
2. Log out in tab2 or by deleting session
3. Reload tab1
4. Redirect loop happens in tab1

### Setup/Environment

* ProcessWire version: 3.0.75

---
https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/modules/Process/ProcessLogin/ProcessLogin.module#L434

**Comment by kixe** [comment]
Fixed #421
Issue can be closed.
