### ISSUE TITLE
Comma in "selectorValue" sanitizer

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#381]
### Short description of the issue

Using selectorValue on a string with a comma will not properly escape returning the error "was your selector value properly escaped"

### Expected behavior

To escape the comma. 

### Actual behavior

Still returns the comma, puts quotes around it, but the comma still exists. 

### Steps to reproduce the issue

I'll just put the code here
```
$titles = $pages->find("template=post, sort=title"); // Get posts
foreach(array_count_values($titles->explode("title")) as $key => $val)  $dups[] = $sanitizer->selectorValue($key); // Get dups
print_r($dups);
$dupPages = $titles->find("title=" . implode("|", $dups));
```

### Setup/Environment

* ProcessWire version: 3.0.72
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by TomS-** [comment]
https://github.com/processwire/processwire-issues/issues/153 Anything to do with this?

**Comment by TomS-** [comment]
It turns out it doesn't like selectors with quotes and non quotes like "Hello, We are"|We are

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.
