### ISSUE TITLE
Admin homepage can say "page isn’t redirecting properly"

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#382]
My browser says "The page isn’t redirecting properly" in this scenario:

1. Log into the editing interface - here: http://www.example.com/processwire/
User is now redirected to: http://www.example.com/processwire/page/?login=1

2. Delete your cookies (or log out on another tab in your browser)
(You are here: http://www.example.com/processwire/page/?login=1)

3. Refresh the page or type enter in the web address field
(You are here: http://www.example.com/processwire/page/?login=1)

4. Result:
Firefox 55 now says "The page isn’t redirecting properly".
(You are here: http://www.example.com/processwire/page/?login=1)

ProcessWire 3.0.62

**Comment by fbg13** [comment]
It's caused by login=1 in url
#380

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. When I follow the instructions, I end up back at the login page (which is what it should do).

**Comment by adrianbj** [comment]
@ryancramerdesign - I just reproduced following those instructions. I am on Chrome and get the too many redirects error. I did the "log out in another tab approach" and then returned to the first tab and reloaded the page with the ?login=1

**Comment by kixe** [comment]
Fixed
https://github.com/processwire/processwire-issues/issues/421#issuecomment-341427359
Issue can be closed.
