### ISSUE TITLE
Copyright date 2013 & 2016 -> 2017

### ISSUE THREAD

**Issue by EntitySelf** [processwire/processwire-issues#384]
* ProcessWire version: 3.0.76

File: /wire/modules/AdminTheme/AdminThemeDefault/install-foot.inc
`<p>ProcessWire <?php echo PROCESSWIRE_INSTALL; ?> &copy; 2016</p>`

File: /wire/templates-admin/install-foot.inc (is this one used???)
`<p>ProcessWire 2.3 &copy; 2013 by Ryan Cramer</p>`

I usually check the copyright date when I install software to get an indication when it was last updated and how it is supported. Maybe add the (c) year number to a central place as well, along side the version number for example?

**Comment by ryancramerdesign** [comment]
Thanks I've updated it to 2017. For the templates-admin one, that one we can leave as-is, since it really is the PW 2.3 admin theme with fond memories. It's just there as a last resort fallback if there is some major error.
