### ISSUE TITLE
pwimage CKE plugin does not respect ProcessPageEditImageSelect noSizeAttr option

### ISSUE THREAD

**Issue by abdusco** [processwire/processwire-issues#385]
### Short description of the issue

[Link to the discussion](https://processwire.com/talk/topic/17277-skip-width-attributes-on-image-tags-not-working/?tab=comments#comment-151731)

### Expected behavior

<img> tag is inserted without width attribute

### Actual behavior

data-nosize is ignored and <img> tag is inserted with width attribute as long as selected image has its width set.

### Optional: Suggestion for a possible fix

I created a PR with a fix:  
https://github.com/processwire/processwire/pull/91

### Steps to reproduce the issue

1. Go to ProcessPageEditImageSelect module configuration and uncheck "skip width attribute on images"
2. Edit a page with CKE editor, add an image, check source, it shows up with width attribute.

### Setup/Environment
PW 3.0.75

**Comment by matjazpotocnik** [comment]
https://github.com/ryancramerdesign/ProcessWire/issues/1151

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix. Thanks for tracking down the issue and for the PR

**Comment by matjazpotocnik** [comment]
@abdusco can this be closed?
