### ISSUE TITLE
Text correction, FieldtypeCache.module

### ISSUE THREAD

**Issue by EntitySelf** [processwire/processwire-issues#386]
File: /wire/modules/Fieldtype/FieldtypeCache.module
Line: 174

`		$select->notes = 
			"If you don't have 'autojoin' checked under this field's advanced settings, the you will have to " . 
			"call \$page->{$field->name} before the cached fields will be loaded.";
`
"settings, the you will" should be "settings, then you will"

* ProcessWire version: ProcessWire 3.0.76

**Comment by ryancramerdesign** [comment]
Thanks, this is fixed in tomorrow's version.
