### ISSUE TITLE
Import field data not working

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#39]
### Short description of the issue

After updating to the latest master, I'm getting the following error trying to import fields:
Call to a member function setImportData() on a non-object (line 440 of /homepages/42/d264496819/htdocs/wire/core/Templates.php) 

### Expected behavior

The fields import.

### Actual behavior

Error as above. 

### Steps to reproduce the issue

1. Export fields from another install
2. Try to import fields into new one
3. Error as above appears

Input data as follows:
`
{
    "content": {
        "id": 230,
        "type": "FieldtypeTextarea",
        "flags": 0,
        "name": "content",
        "label": "Content",
        "textformatters": [
            "TextformatterEntities"
        ],
        "inputfieldClass": "InputfieldTextarea",
        "contentType": 0,
        "collapsed": 0,
        "minlength": 0,
        "maxlength": 0,
        "showCount": 0,
        "rows": 5,
        "htmlOptions": "",
        "showIf": "",
        "columnWidth": 100,
        "required": "",
        "requiredAttr": "",
        "requiredIf": "",
        "stripTags": "",
        "placeholder": ""
    },
    "pdf": {
        "id": 232,
        "type": "FieldtypeFile",
        "flags": 0,
        "name": "pdf",
        "label": "PDF",
        "extensions": "pdf doc docx xls xlsx gif jpg jpeg png",
        "maxFiles": 1,
        "outputFormat": 0,
        "defaultValuePage": 0,
        "inputfieldClass": "InputfieldFile",
        "descriptionRows": 0,
        "fileSchema": 2,
        "outputString": "",
        "textformatters": "",
        "entityEncode": "",
        "useTags": "",
        "collapsed": 0,
        "showIf": "",
        "columnWidth": 100,
        "required": "",
        "requiredIf": "",
        "unzip": "",
        "overwrite": ""
    },
    "video": {
        "id": 231,
        "type": "FieldtypeFile",
        "flags": 0,
        "name": "video",
        "label": "Video",
        "extensions": "mp4 webm ogv ogg jpeg jpg",
        "maxFiles": 0,
        "outputFormat": 0,
        "defaultValuePage": 0,
        "inputfieldClass": "InputfieldFile",
        "descriptionRows": 0,
        "fileSchema": 2,
        "collapsed": 0,
        "outputString": "",
        "textformatters": "",
        "entityEncode": "",
        "useTags": "",
        "showIf": "",
        "columnWidth": 100,
        "required": "",
        "requiredIf": "",
        "unzip": "",
        "overwrite": ""
    },
    "words_timeline": {
        "id": 229,
        "type": "FieldtypeTable",
        "flags": 0,
        "name": "words_timeline",
        "label": "Words Timeline",
        "maxCols": 2,
        "col1name": "words",
        "col1label": "Words",
        "col1type": "text",
        "col1width": 50,
        "col1sort": 1,
        "col2name": "delay",
        "col2label": "Delay",
        "col2type": "int2",
        "col2width": 50,
        "col2sort": 2,
        "col3sort": 3,
        "collapsed": 0,
        "col1settings": "textformatters=TextformatterEntities\nplaceholder=\ndefault=",
        "col1options": "",
        "col2options": "",
        "renameColumn": "",
        "showIf": "",
        "columnWidth": 100,
        "required": "",
        "requiredIf": ""
    }
}
`

### Setup/Environment

* ProcessWire version: 3.0.36

**Comment by BitPoet** [comment]
Are you actually importing to the Fields tab? The error message looks to me as if you were trying to import the fields into the Templates tab by accident.

**Comment by ryancramerdesign** [comment]
So far I can't duplicate this one either. @TomS- is it possible you were importing into templates tab per what BitPoet mentioned?

**Comment by TomS-** [comment]
That could be possible. I haven't been able to reproduce it on other installs. I will close the issue and reopen it if I come across it again.
