### ISSUE TITLE
ProFields Table date/datetime inconsistent selector behavior

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#390]
### Short description of the issue

Ran into a frustrating issue trying to select a page by a date inside of a ProFields Table field. I was trying to match it to a timestamp, which works for PW datetime fields, and is also the value that it returns when output. After debugging I realized that the SQL query being generated from the selector was looking for the timestamp when the data was actually stored in the db in the YYYY-MM-DD format.

### Expected behavior

I expected the following query:

wire('pages')->get("holiday_dates.date=1506632245"); 

To return a page where the holiday_dates table field contained the date corresponding to the timestamp 1506632245 somewhere in its date column.

### Actual behavior

NullPage returned.

### Steps to reproduce the issue

1. Create table field with a single date column
2. Add a page with a date
3. Run query from Expected Behavior

### Setup/Environment

* ProcessWire version: 3.0.73 
* Table Field version: 0.1.1

**Comment by Toutouwai** [comment]
Table is not a core module so I think this issue belongs in the ProFields support forum rather than in the PW issues repo.

**Comment by thetuningspoon** [comment]
Yes, but I don't have access to the support forum at the moment.

**Comment by netcarver** [comment]
@thetuningspoon Hi Michael, have you managed to post this in the support forum at all? If not, I can post a reference to it in there for you.

**Comment by thetuningspoon** [comment]
Please do. I don't think my license is up to date.

**Comment by netcarver** [comment]
@thetuningspoon Done. Will update here if there is any result in there.

**Comment by netcarver** [comment]
@thetuningspoon Michael, can you try adding the following code...

```
if($column['valid'] === 'date' || $column['valid'] === 'datetime') {
    // convert unix timestamp or other recognized date formats to ISO-8601
    if(ctype_digit("$value")) $value = (int) $value;
    if(!is_int($value)) $value = strtotime($value);
    $value = $column['valid'] === 'date' ? date('Y-m-d', $value) : date('Y-m-d H:i:s', $value);
}
```

Right before the line...
```
if(($column['valid'] === 'Page' || $column['valid'] === 'PageArray') && !ctype_digit("$value")) {
```
...in the getMatchQuery() method. Should be around line 656 in the module. Please could you let me know if this fixes the issue for you.

**Comment by netcarver** [comment]
@thetuningspoon Hi Michael, did the above answer from the forum help at all? If you want me to post more in there for you, please just drop a comment on this issue.

**Comment by thetuningspoon** [comment]
Hi netcarver,
That does the trick!

**Comment by netcarver** [comment]
@thetuningspoon Hi Michael, that's good to hear. I've let Ryan know and will close this issue now as it is not related to a core module. Just post here again if you need the issue re-opened.
