### ISSUE TITLE
Blank page after WampServer update due to Win paths being case-insensitive

### ISSUE THREAD

**Issue by EntitySelf** [processwire/processwire-issues#392]
Version: ProcessWire 3.0.76
Platform: Windows 10, WampServer 3.1.0 64bit

Problem:
After updating to a new WampServer version and restoring the site's files and database I tried opening my website and ended up with a blank page. Clearing the assets sub folders didn't help. 

I solved the problem by changing:

File: /wire/core/ProcessWire.php
Function: buildConfig
Line: 807

Original line:
`// when internal is true, we are not being called by an external script
$cfg['internal'] = $realIndexFile == $realScriptFile;`

Fix for Windows (Don't use for case sensitive OS/FSes, like Linux).
`// when internal is true, we are not being called by an external script
$cfg['internal'] = 0 == strcasecmp($realIndexFile, $realScriptFile);`

![image](https://user-images.githubusercontent.com/32257936/31014644-419700c2-a51c-11e7-8676-bd9e96f982fe.png)

```
// when internal is true, we are not being called by an external script
if(!stristr(PHP_OS, 'WIN')) {
  // Not Windows
  $cfg['internal'] = $realIndexFile == $realScriptFile;
} else {
  // Windows
  $cfg['internal'] = 0 == strcasecmp($realIndexFile, $realScriptFile);
}
```

NTFS can be configured to be case sensitive but this isn't often done AFAIK, there are probably other FS on other OS that can be both as well.

**Comment by ryancramerdesign** [comment]
It's not clear to me why $realIndexFile would have a different case than $realScriptFile? I'm wondering if the `$_SERVER[SCRIPT_FILENAME]` var has the incorrect case or the `realpath()` method is returning an incorrect case. I will go ahead and add a non-case-sensitive comparison here, but just wanted to better understand the issue. There may be other places where we have to consider that one of those return values could have incorrect case, so curious which  variable/function is returning the wrong case. Thanks.

**Comment by EntitySelf** [comment]
Win 10 (Wampserver64)
Apache v2.4.27
PHP v7.1.10

My Apache virtual host config is set to lowercase, $_SERVER[SCRIPT_FILENAME] and realpath() return the volume name in uppercase and __DIR__ is returned in lowercase.

A note in the PHP manual states: For case-insensitive filesystems realpath() may or may not normalize the character case (http://php.net/manual/en/function.realpath.php).

`
// - Apache vhost config
DocumentRoot "c:/wamp64/stage.entityself.com"
<Directory  "c:/wamp64/stage.entityself.com/">

// - /index.php
$rootPath = __DIR__; // out: c:\EntitySelf\Sites\stage.entityself.com (LOW)
$rootPath2 = $_SERVER['SCRIPT_FILENAME']; // out: C:/wamp64/stage.entityself.com/index.php (HIGH)
...
$config = ProcessWire::buildConfig($rootPath);

// - /wire/core/ProcessWire.php
// in: c:/EntitySelf/Sites/stage.entityself.com (LOW)
$realIndexFile = realpath($rootPath . "/index.php"); // out: C:\EntitySelf\Sites\stage.entityself.com\index.php (HIGH)
`

**Comment by EntitySelf** [comment]
Addition, I am using a directory symbolic link from c:/wamp64/stage.entityself.com -> c:/EntitySelf/Sites/stage.entityself.com and this might be why it happens:

```
// pathtest.php
var_dump(__DIR__);
var_dump($_SERVER['SCRIPT_FILENAME']);
var_dump(realpath(__DIR__));
var_dump(realpath($_SERVER['SCRIPT_FILENAME']));

// http://localhost/pathtest.php
C:\wamp64\www\pathtest.php:3:string (UP)'C:\wamp64\www' 
C:\wamp64\www\pathtest.php:4:string (UP)'C:/wamp64/www/pathtest.php'
C:\wamp64\www\pathtest.php:5:string (UP)'C:\wamp64\www' 
C:\wamp64\www\pathtest.php:6:string (UP)'C:\wamp64\www\pathtest.php'

// http://stage.entityself.com/pathtest.php
c:\EntitySelf\Sites\stage.entityself.com\pathtest.php:3:string (LOW)'c:\EntitySelf\Sites\stage.entityself.com' 
c:\EntitySelf\Sites\stage.entityself.com\pathtest.php:4:string (UP)'C:/wamp64/stage.entityself.com/pathtest.php' 
c:\EntitySelf\Sites\stage.entityself.com\pathtest.php:5:string (UP)'C:\EntitySelf\Sites\stage.entityself.com'
c:\EntitySelf\Sites\stage.entityself.com\pathtest.php:6:string (LOW)'c:\EntitySelf\Sites\stage.entityself.com\pathtest.php' 
```

**Comment by ryancramerdesign** [comment]
Okay thanks, I understand now. The case insensitive comparison is in tomorrow's version.
