### ISSUE TITLE
Renaming Repeater field does not rename associated template and fieldgroup

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#395]
### Short description of the issue

If a Repeater/RepeaterMatrix field is renamed, the name of associated template and fieldgroup is not updated. This can be a problem for modules or hooks that are expecting the standard naming of "repeater_fieldname".

Related forum topic: https://processwire.com/talk/topic/17310-rename-repeater-field-including-template-and-fieldgroup/

### Expected behavior

Repeater template and fieldgroup names remain consistent with field name.

### Suggestion for a possible fix

The forum topic contains the code needed to update the template and fieldgroup names.

### Setup/Environment

* ProcessWire version: 3.0.76

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update that fixes this.
