### ISSUE TITLE
Problem with translating "Comments" link in the admin

### ISSUE THREAD

**Issue by sevenstudio** [processwire/processwire-issues#396]
### Short description of the issue

Hello, I've created a complete, new Polish translation for PW, all files and phrases that were reported by PW are translated, but in the admin the "comments" link remains in english (also the "All" , "Pending", "Approved", "Spam" titles stays in english, while tabs titles and links in the sidebar after hover are translated), please take a look at attachment:

![comments](https://user-images.githubusercontent.com/2057593/31070872-4ed3479e-a762-11e7-9233-f6d435a36201.png)

In the breadcrumb the comments link is translated but not in the sidebar. The same happens in both the Core and in the Reno admin theme.
Is there anything special that needs to be done to translate those strings?

* ProcessWire version: 3.0.77
* (Optional) PHP version: 7.0.2

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. Please let me know if you continue to see any missing translations.

**Comment by sevenstudio** [comment]
@ryancramerdesign  Thanks for the fix! 

Titles (Approved, Pending, Spam) are now translated except the "All" - this still remains in english. 

Also, the "Comments" link in the menu is not translated, while all other menu elements like languages, etc. are translated automatically. 

The only way to change it is to change "Comments" page title in the pages tree, but I  think it should be pulled from translation as for other menu items.

I see polish "Komentarze" in the breadcrumb, but not in the menu (as on screenshot above).

**Comment by sevenstudio** [comment]
Ryan, I see that you've included fix also for the "All" title in the latest dev 3.0.80, everything works fine after upgrade, Thanks a lot!

The last thing that remain is the "Comments" menu title. 
I've translated both new strings added to the 

/wire/modules/Process/ProcessCommentsManager/ProcessCommentsManager.module

and I see translated tite and summary under modules - system, but unfortunately title under setup menu remains in english.

**Comment by ryancramerdesign** [comment]
> and I see translated tite and summary under modules - system, but unfortunately title under setup menu remains in english.

Are you still seeing this? Much of the navigation is cached just once per session, so it wouldn't expect it to appear unless/until you logged out and logged back in again.

**Comment by sevenstudio** [comment]
Hello Ryan, yes, menu item title remains in english - "Comments". 


![1](https://user-images.githubusercontent.com/2057593/33773481-49a548c0-dc38-11e7-90dc-b69b4b89eedf.png)
![2](https://user-images.githubusercontent.com/2057593/33773482-49c4a422-dc38-11e7-9cdd-3a02b93def01.png)

I've checked this with different admin themes, (logged in many times in different installations of PW). The only way to change it is to change Comments page title in the pages tree. 

Ryan, maybe you can download my Polish language pack for a test?

http://modules.processwire.com/modules/polski/

**Comment by sevenstudio** [comment]
Hello, Ryan, I know that this is not a major issue but problem with untranslated "Comments" title in the main menu still remains in the latest dev version.

I was trying to edit code of the module to narrow this issue, but with no luck. No changes after clearing sesions, login/logout, refreshing modules, increasing the module version etc. 

Changing the module title brings changes only on the modules - system page, but menu title and "Comments" title in the setup page remains untranslated.

In a spare time could you please take a look at once again?  If there would be anything else that I may do please just let me know. Thanks in advance.

**Comment by netcarver** [comment]
@sevenstudio Hello, is this still an issue in the latest dev version? If so, perhaps you could post another reply here and @ mention Ryancramerdesign in your reply.

**Comment by sevenstudio** [comment]
Hello @netcarver , I've just checked and this is still an issue in the latest dev version. Comments menu item title remains untranslated. @ryancramerdesign could you please take a look at this issue in some spare time? Thanks in advance!

**Comment by netcarver** [comment]
@ryancramerdesign I've removed the fixed resolution label given the recent report from @sevenstudio.

**Comment by matjazpotocnik** [comment]
It looks like this could be fixed by replacing:

`'title' => 'Comments',`

with:

`'title' => __('Comments', __FILE__), //title in the setup menu`

in ProcessCommentsManager.module, line 38.

@sevenstudio would you mind testing it? You have to uninstall ProcessCommentsManager module, make the translation and then reinstall the module.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @netcarver @sevenstudio That line 38 mentioned above I'm pretty sure is only used when the page is created, at the time the module is installed. So I don't think that translating it will resolve the issue. Instead, I'd recommend navigating to the page in the PageList, via Admin > Setup > Comments, and then editing that Comments page and then adjusting the languages/values for title as you see fit here.

**Comment by sevenstudio** [comment]
@matjazpotocnik  Thank you for your input, unfortunately this works only if you will install language package as the default language. If you will add other languages and try to translate this string title will not change after language change. 

After uninstalling/installing ProcessCommentsManager.module, this page title is saved in the database, this why you saw a new title on default language.

Ryan suggestion is the only way to make this title translated for more than a single language, and going that way make sense if you are running multilingual site.

@netcarver  @ryancramerdesign  I think that we can close this issue. Just out of curiosity, why title translation for this specific module works differently than in other modules that display title under setup menu?

Thanks all for your time!
