### ISSUE TITLE
Integer field default value not used

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#399]
### Short description of the issue

FieldtypeInteger has a config inputfield for "Default value" (defaultValue).

![2017-10-07_094248](https://user-images.githubusercontent.com/1538852/31297797-efaaeb88-ab43-11e7-9603-ef9bfb0b0388.png)

But this defaultValue setting doesn't seem to be used anywhere in InputfieldInteger and setting a default has no effect (field is always empty on new pages despite the defaultValue setting). If this setting is not implemented it should be removed from the config inputfields.

### Setup/Environment

* ProcessWire version: 3.0.77

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue so that it should work now.
