### ISSUE TITLE
Incorrect notice from ProcessPageSort

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#406]
### Short description of the issue

If a template has "Sort settings for children" defined using some field other than "Manual drag-n-drop" and an attempt is made to drag-sort a child in the page tree, there is a notice:

> Your sort was not saved because these pages are automatically sorted by sort.

But the sort field stated in the notice is not correct - the child pages are sorted by a field.

### Suggestion for a possible fix

Looking in [ProcessPageSort](https://github.com/processwire/processwire/blob/2771c353ee2ac45c4cbe0ce10712fcfbb17cbd01/wire/modules/Process/ProcessPageSort.module#L122-L124), there seems to be some issue/confusion between $parent->sortfield() the method and $parent->sortfield the property. They give different values for some reason.

Making the following change seems to fix it:
````php
$sortfield = $parent->sortfield();
if($sortfield && $sortfield != 'sort') {
    $msg = sprintf($this->_("Your sort was not saved because these pages are automatically sorted by %s."), $sortfield);
	//...
````

### Setup/Environment

* ProcessWire version: 3.0.77

**Comment by ryancramerdesign** [comment]
Thanks for tracking this one down. I've added your suggested fix for this.

**Comment by Toutouwai** [comment]
Thanks.
