### ISSUE TITLE
Repeater Inside User Template Issue!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#407]
I added a repeater field to "User Template" .. every thing works fine for "**Superuser**" but not for other roles 
.
**Using: PW 3.0.77 || PHP 7.1.7 || AdminThemeUiKit**
.
Only **SuperUser** can add new items .. i don't know why !
![rep](https://user-images.githubusercontent.com/5323832/31650864-fc65f710-b321-11e7-8e8e-cea7cd13068e.PNG)

**Comment by ryancramerdesign** [comment]
I have pushed an update so support repeaters in the user profile. Previously they were not supported here, but should be now.

**Comment by Mu9tafa-Online** [comment]
@ryancramerdesign  - i tested it now.. it didn't work :(
.

**Comment by ryancramerdesign** [comment]
It's working well from this side. Can you provide more details about what's
not working? Try from an incognito mode to make sure you aren't getting old
assets loaded. Make sure you logout and log back in. Make sure the user has
at at least page-edit permission, even if not assigned to any particular
template. Try enabling your browser's developer tools and look for JS
errors as well.

**Comment by Mu9tafa-Online** [comment]
Yes Works Just Fine :) .. i clear the cache and logged-In Again. Thanx Mr. Ryan
