### ISSUE TITLE
Docs update: API $config->imageSizerOptions missing key "sharpening"

### ISSUE THREAD

**Issue by esszett** [processwire/processwire-issues#409]
### Expected behavior

Docs should mention key "sharpening"

### Optional: Suggestion for a possible fix

Add "sharpening" and possible values "soft, …" to API docs

### Setup/Environment

* ProcessWire version: 3.0.62
* PHP version: 7.0

**Comment by Toutouwai** [comment]
You don't say exactly how you are setting the imageSizerOptions in /site/config.php, but be aware that for config settings that are arrays (as imageSizerOptions is) you must merge your settings with the default settings.

So for instance you cannot do this:

````php
$config->imageSizerOptions['upscaling'] = false;
````

But must instead do:
````php
$config->imageSizerOptions = array_merge($config->imageSizerOptions, ['upscaling' => false]);
````

**Comment by esszett** [comment]
I guess it's my mistake: I did in config.php
```
$config->imageSizerOptions = array(
 'upscaling' => false,
 'cropping' => false,
 'quality' => 90
);
```
Thank you for pointing towards array_merge() – I did miss that.

**Comment by Toutouwai** [comment]
> Thank you for pointing towards array_merge() – I did miss that.
I don't think it's documented anywhere - it's just what I've found from personal experience. You would think you would be able to set individual array values by key but for some reason it doesn't work.

**Comment by Toutouwai** [comment]
And you are right in that if the [API docs](https://processwire.com/api/ref/config/) are going to state the defaults then they should be the complete defaults. I think you should reopen this issue so the API docs get updated.

**Comment by ryancramerdesign** [comment]
You can also do this for any array property when you  just want to set one part of it: `$config->imageSizerOptions('upscaling', false);`

**Comment by ryancramerdesign** [comment]
There are now just too many imageSizerOptions to fit within the phpdoc in that class, so I've updated the note to say "see /wire/config.php for all options and defaults".

**Comment by netcarver** [comment]
@esszett Hello there. Could you close this issue if it is resolved to your satisfaction, otherwise post a reply so we know to keep it open and on the radar. Thank you!
