### ISSUE TITLE
image upload via CK Edit popup –> wrong datetime in database

### ISSUE THREAD

**Issue by gerritvanaaken** [processwire/processwire-issues#41]
### Short description of the issue

When you upload an image via the CK editor upload function, it creates an entry in the database for this uploaded image, but with a wrong datetime

### Expected behavior

"created" datetime of newly uploaded files must be current time.

### Actual behavior

"created" datetime is wrong, like "1970-01-01 01:00:10"

### Optional: Screenshots/Links that demonstrate the issue

![pic_2016-10-12_whly5](https://cloud.githubusercontent.com/assets/227735/19309255/0f0dbbbc-9084-11e6-8cca-fada41878ca9.png)

![pic_2016-10-12_7b4mv](https://cloud.githubusercontent.com/assets/227735/19309271/27ccf42e-9084-11e6-9573-b0d4bc2517b9.png)

### Steps to reproduce the issue

1. Upload a new image via CK Editor popup, to any image field
2. look into the database and check the datetime of this newly uploaded image

### Setup/Environment
* ProcessWire version:  3.0.35
* (Optional) PHP version: 5.6.25
* (Optional) MySQL version: 5.6.28
* (Optional) Any 3rd party modules that are installed and could be related to the issue: CK Editor

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this one, but I can provide some additional info that may help to explain why you are seeing the behavior. The timestamp that you see there is one that ProcessWire specifically uses to identify uploaded files that are on a page where the user hasn't yet clicked the "Save" button. So the timestamp is correct, but it would automatically be changed to the correct timestamp after the page has been saved (and thus confirmed that the files/images will remain on the page).

**Comment by gerritvanaaken** [comment]
Thank you for the explaination. I will specify the steps to reproduce this issue:

- have a CK Editor and open the image popup there
- In the image popup choose a *different* page than the the current page you are editing**!**
- upload the image there
- choose the image
- insert the image to the CK Editor
- save the page

-> image will still have the temporary "created" date in database.

I assume it’s because the image was uploaded to a different page. Maybe it’s because the currently edited page template doesn’t even have an image upload field.

**Comment by ryancramerdesign** [comment]
Thanks I misunderstood before that it was specific to uploading an image to a different page than the one being edited. Now I can reproduce it. I have gone ahead and pushed a fix. Can you confirm it also fixes the issue there? Thanks.

**Comment by gerritvanaaken** [comment]
Works for me! Thank you very much, Ryan!
