### ISSUE TITLE
Language Translator overrides other language

### ISSUE THREAD

**Issue by thuijzer** [processwire/processwire-issues#410]
### Short description of the issue

When you open the same translation file for multiple languages, translations are overwritten when you save one language.

### Expected behavior

Expected is that you can edit the same translation file in multiple browser tabs for each language.

### Actual behavior

The settings of the last language are overwritten in the other language.

### Optional: Suggestion for a possible fix

When you open a site translation file the `language_id` can be found in the URI.
But when you POST, the `language_id` is excluded from the URI. The `language_id` is also not send via POST so PW can never know which language is being updated.

### Version

ProcessWire 3.0.62 @ PHP 5.6

**Comment by rolandtoth** [comment]
It was discussed earlier here:
https://github.com/ryancramerdesign/ProcessWire/issues/1698

**Comment by thuijzer** [comment]
@rolandtoth Thank you. I did not find that post while searching.

But I still think it's a bug. It's no fun to loose all your translations because of this unexpected result.

**Comment by rolandtoth** [comment]
That would be great, thanks - any chance of a PR?

**Comment by thuijzer** [comment]
@rolandtoth I don't use github a lot so I hope this is the right way to submit a pull request:
https://github.com/processwire/processwire/pull/93

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed the suggested update here. Though if I recall there was a good reason why we were using the session here rather than GET/POST vars, but it's been awhile and I don't remember exactly what it was. So I've left the session detection in place as the fallback

**Comment by netcarver** [comment]
@thuijzer Hello Thomas, I see Ryan has pushed a fix for this issue into the code base. If you are happy with the fix, please could you close this issue. Thank you!
