### ISSUE TITLE
ProcessPageEditImageSelect - Invalid Image on Variations Modal Load

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#415]
### Short description of the issue

When clicking on an images Variations button to open up the modal, the modal opens but an error is generated "Invalid image file: {id},{file}"

### Expected behavior

The Variations modal opens with a table of image variations

### Actual behavior

The Variations modal opens with the following messages:
Success - "There are no image fields on this page. Choose another page to select images from."
Error - "Invalid image file: {id},{file}"

### Suggestion for a possible fix

It seems that the issue lies with "Field names to skip for selection" in the ProcessPageEditImageSelect config. If a page has no fields which are available to this module (i.e. all image fields on the page have been added to the config field to be skipped) then the error is generated.

### Steps to reproduce the issue

1. Create a template with a image field
2. In the ProcessPageEditImageSelect config, add this image field name into "Field names to skip for selection"
3. Create a page and add an image to that field (and save)
4. Click on the image, then click on the Variations button

### Setup/Environment

* ProcessWire version: 3.0.62
* PHP version: 7.1.7

### Other

I tested this on the dev branch and it returned a different variation of the error message:

"Cannot find image file '{file}' on page: /{name}/

**Comment by netcarver** [comment]
@chriswthomson Hi there. Looks like Ryan pushed a fix for this last year. If he's fixed it to your satisfaction, please could you close this issue. Many thanks!
