### ISSUE TITLE
Repeater field export/import needs to convert parent_id and template_id to paths and names, respectively

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#416]
### Short description of the issue

Repeater field export/import needs to convert parent_id and template_id to paths and names, respectively

### Expected behavior

I should be able to import a repeater field from one site into another

### Actual behavior

Doesn't really work because page/template IDs don't match up

**Comment by Toutouwai** [comment]
Related: https://github.com/processwire/processwire-issues/issues/156

**Comment by ryancramerdesign** [comment]
This is specific to the Field export/import from Setup > Fields, right? Just wanted to make sure we weren't talking about Page export/import (which does support repeaters). But repeaters aren't supported for "field" import.  A repeater field definition involves not just a field, but templates, fieldgroups, pages and field/template contexts. They are quite a bit more complex than what Field export/import is built for. So FieldtypeRepeater would need to implement its own exportConfigData() and importConfigData() methods, that would have to do quite a bit of work. I've been meaning to implement these, so will give it another look this week.

**Comment by adrianbj** [comment]
> This is specific to the Field export/import from Setup > Fields, right?

Yes!

> A repeater field definition involves not just a field, but templates, fieldgroups, pages and field/template contexts. They are quite a bit more complex than what Field export/import is built for.

Yeah, I know - I had to deal with it in my migrator module, but it's not too hard :)

**Comment by ryancramerdesign** [comment]
> Yeah, I know - I had to deal with it in my migrator module, but it's not too hard :)

Okay, you are right, it was easier than I thought. I've gone ahead and added support for this. Seems to be working well here, but definitely needs more testing.

**Comment by adrianbj** [comment]
Great - thank you!
