### ISSUE TITLE
Added/removed repeater subfields messages misleading

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#417]
### Short description of the issue

If there is a failure in adding or removing one subfield, none of the other actions happen, but the session messages state that they did happen.

### Expected behavior

Messages should state things that didn't happen.

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2017-10-25 at 1 50 23 pm](https://user-images.githubusercontent.com/871211/32023989-df5ae558-b98f-11e7-840a-4796136e721c.png)

**Comment by ryancramerdesign** [comment]
Those fields were removed from the fieldgroup (which is what those messages are reporting), but when it went to save, a fatal error occurred. An Exception was thrown in order to prevent the save from occurring, because one field had a flag that blocks the save. This is behaving as it should, but I will append the fatal error message with "Save of fieldgroup changes aborted".

**Comment by ryancramerdesign** [comment]
The error message here was updated, in the other commit today for repeater field export/import. I did look into having the error be non-fatal, letting the other removals proceed, but it looks like there's just too much potential for problems in doing that, so going to leave this one as a fatal error.

**Comment by adrianbj** [comment]
Thanks Ryan - this will be helpful.

It's just my opinion, but I still would have preferred to not see those "Removed field from template" messages. I know that technically they were removed, but then the changes not saved, but that's not really relevant to the user - the end reality is that they aren't removed at all.

**Comment by teppokoivula** [comment]
Already closed, but just wanted to say that I fully agree with @adrianbj on this one. The messages are very confusing, and you must understand a lot about what went on behind the scenes to make any sense of them.
