### ISSUE TITLE
Image drag and drop problems in Internet Explorer 11

### ISSUE THREAD

**Issue by aad-webteam** [processwire/processwire-issues#418]
### Short description of the issue

Drag and drop of images into an empty image field doesn't work in Internet Explorer 11.

### Expected behavior

Would expect to be able to drag and drop the very first image just like in other browsers.

### Actual behavior

Dragging an image over the field does nothing. You have to hit the choose file button and browse. 

Once there is one image in the field you can drag and drop subsequent images.

### Steps to reproduce the issue

1. Using IE 11, edit an existing or new page with an empty image field.
2. Try and drag and drop image(s) into the field.
3. Hit choose file button and browse for an image instead.
4. Now drag and drop will work.

### Setup/Environment

* ProcessWire version: 3.0.79
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Image Extra module (though this only happens in IE, and I also tested with an image field that is not using any additional fields created with that module)

**Comment by ryancramerdesign** [comment]
I don't have access to this browser/platform at present. Is anyone else able to test and duplicate this, and perhaps determine if there are any JS errors occurring or know what the issue might be? It's been quite awhile since we've seen IE-specific issues. Thanks.

**Comment by Toutouwai** [comment]
I can confirm the issue. It affects both File and Image fields.

### Suggested fix

Prevent the default behaviour for the `dragenter` event.

[InputfieldImage.js](https://github.com/processwire/processwire/blob/7bf27cc5e53ebae86313a34bd35826df5c21b903/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L1205)

````js
el.addEventListener("dragenter", function(evt) {
    evt.preventDefault();
    //...
````

[InputfieldFile.js](https://github.com/processwire/processwire/blob/7bf27cc5e53ebae86313a34bd35826df5c21b903/wire/modules/Inputfield/InputfieldFile/InputfieldFile.js#L426)

````js
dropArea.addEventListener("dragenter", function(evt) {
    evt.preventDefault();
   //...
````

**Comment by matjazpotocnik** [comment]
I can also confirm this behaviour, but only in default admin theme and in reno admin theme, it's working as expected in admin theme uikit. Suggested fix solve the issue in all themes and it looks like it doesn't break anything.

**Comment by ryancramerdesign** [comment]
Thanks very much @Toutouwai this is hugely helpful, I really appreciate all of your help, on this issue and the others. I have pushed your suggested fix. Thanks also @matjazpotocnik for the testing and confirmation.

**Comment by netcarver** [comment]
@aad-webteam Looks like a fix has been pushed for your issue. If that has resolved things to your satisfaction, please could you close this issue. Thank you!

**Comment by aad-webteam** [comment]
Oops, it is indeed fixed so I'll close this now. Thanks!
