### ISSUE TITLE
InputfieldImage: images in list view not sized according to slider on page load

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#419]
### Short description of the issue

When images are in list view and the slider is used to adjust the thumbnails to a custom size, that custom size is not retained when the page is reloaded after saving.

Related forum thread: https://processwire.com/talk/topic/17403-bug-in-default-image-grid-mode-vertical-list-verbose/

### Suggestion for a possible fix

The problem is [here](https://github.com/processwire/processwire/blob/e3fc776c5360c9a624e5d22ab7598afd48fd88d9/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L991-L996):

````js
setGridSize($inputfield, size, ragged);
        
if($inputfield.hasClass('InputfieldImageEditAll') || mode == 'list') {
    var listSize = getCookieData($inputfield, 'listSize');
    setListSize($inputfield, listSize);
}
````

It looks like the expectation here is that all thumbnails are sized with `setGridSize()`, but then this is overridden for images in list view which will be sized with `setListSize()`. But this doesn't work because `setGridSize()` includes a `setTimeout()` which fires again after `setListSize()`.

I think it should be okay to do _either_ `setGridSize()` _or_ `setListSize()` based on whether list view is active.

````js
if($inputfield.hasClass('InputfieldImageEditAll') || mode == 'list') {
    var listSize = getCookieData($inputfield, 'listSize');
    setListSize($inputfield, listSize);
} else {
    setGridSize($inputfield, size, ragged);
}
````

### Setup/Environment

* ProcessWire version: 3.0.80

**Comment by ryancramerdesign** [comment]
Thanks! Your debugging skills are awesome. I tested the fix you suggested and all seems to work and this should now be on the dev branch.

**Comment by Toutouwai** [comment]
Thanks.
