### ISSUE TITLE
Endless redirect after manually deletion of cookies

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#421]
### Short description of the issue

Endless redirects after manually deletion of cookies and
reloading page with GET parameter: login=1

### Expected behavior

Render of login screen 

### Actual behavior

Endless redirects

### Optional: Suggestion for a possible fix

Redirect only if user is loggedin

#### Option 1
check if user is loggedin **before** calling **ProcessLogin::afterLoginRedirect()**
https://github.com/processwire/processwire/blob/7bf27cc5e53ebae86313a34bd35826df5c21b903/wire/modules/Process/ProcessLogin/ProcessLogin.module#L434

```
	protected function ___renderLoginForm() {
		if($this->wire('input')->get('login') && $this->wire('user')->isLoggedin()) {
			$this->afterLoginRedirect();
			return '';
		} else { 
                // ...
		}
	}
```

#### Option 2
Add GET:login  only if user is loggedin inside **ProcessLogin::afterLoginRedirect()**
https://github.com/processwire/processwire/blob/7bf27cc5e53ebae86313a34bd35826df5c21b903/wire/modules/Process/ProcessLogin/ProcessLogin.module#L459

```
	protected function ___afterLoginRedirect() {
		$get = $this->wire('user')->isLoggedin()? '?login=1' : '';
		$url = $this->wire('config')->urls->admin . "page/$get";
		$url = $this->afterLoginURL($url);
		$this->wire('session')->redirect($url);
	}
```

**Comment by Toutouwai** [comment]
Possibly duplicate of:
https://github.com/processwire/processwire-issues/issues/382
https://github.com/processwire/processwire-issues/issues/380

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix (similar to option 1).

**Comment by kixe** [comment]
Thanks.
