### ISSUE TITLE
Add empty option on template select at the top

### ISSUE THREAD

**Issue by juergenweb** [processwire/processwire-issues#424]
### Short description of the issue

According to this [discussion](https://processwire.com/talk/topic/17543-possible-to-add-an-select-text-option-to-a-template-select-at-the-top/) in the forum it would be great if you could implement this into the core.

**The situation:**
The template select field offers editors to choose between various templates. At the moment always one template is pre-selected. This leads to that editors often ignore (or dont take care) of this field and press the save button. After that they notice that they have choosen the wrong template. 
It would be better to add the possibility that no template will be pre-selected so that editors will get an error message if they do not choose on of them. So editors will be forced to select one. In other words they need to think over which kind of template to choose.

At the moment we have solved this issue via a Hook, but I think it would be better to add this directly into the core.

### Optional: Screenshots/Links that demonstrate the issue

![screenshot-www juergen-kern at-2017-11-05-19-24-27](https://user-images.githubusercontent.com/9609925/32427776-7f5d13a6-c2c2-11e7-890a-8295c54ee1db.png)

### Optional: Suggestion for a possible fix
Discussion with other people leads to that some of them want to pre select a certain default template to improve the workflow.
Maybe it will be an option to add an additional settings field to the template settings where the allowed children templates are selected to mark the pre-selected template.

![screenshot-www juergen-kern at-2017-11-06-09-35-42](https://user-images.githubusercontent.com/9609925/32431975-fdd19334-c2d5-11e7-97a8-0491681ccb3f.png)

This could even be a default text field where you have to write the name of the default template or it could be a JS-rendered select field where you can choose the prefered default template.
If nothing is entered (selected) than the empty option (or maybe an option with a text like "Please select") will be the default option. Otherwise the choosen template will be the default option after rendering the form.  

This solution satisfies all. The ones who want to force the editor to choose a certain template and the ones who want to make a certain template as pre-selected.

**Comment by juergenweb** [comment]
This is the old repository - I have posted it in the new one ([https://github.com/processwire/processwire-issues/issues/424](url))

**Comment by ryancramerdesign** [comment]
The best way to manage this is to use the Family settings for your templates. That way one can only select templates that are applicable for children of any given parent. Very often, it would only be one possible template for children, which makes it even simpler as they don't need to select anything at all. As far as which template is selected by default, this is based on whatever the last child added was, which tends to be very convenient. I think this is a preferable behavior for most people. But I understand for your case you might be using family settings (your screenshot seems to indicate) but still want no selection for the template. The use case makes sense to me, though I'm just not sure it would be used often enough to warrant an admin UI configured field. Maybe would be okay as a setting that appears in advanced mode though. I'll work on something here.

**Comment by juergenweb** [comment]
That would be great. Thanks Ryan

**Comment by ryancramerdesign** [comment]
I've gone ahead and added this. In your /site/config.php you can specify this `$config->pageAdd('noSuggestTemplates', true);` and it'll disable the template selection globally for adding pages (i.e. blank option at the top, forcing user to select). Or instead of `true` you can specify an array or space-separated string of template names where suggestions should be disabled when adding children.

**Comment by juergenweb** [comment]
Great, I will try it out after the next update is released.

**Comment by juergenweb** [comment]
Works like a charme! Thank you so much.
