### ISSUE TITLE
Getting 404 error for some of css file maps

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#425]
### Actual behavior

After login to admin panel gettin 404 for some of css file maps.

### Screenshots
![ekran resmi 2017-11-06 21 10 32](https://user-images.githubusercontent.com/455983/32456677-173fc6c0-c32f-11e7-8d0d-e440a24f2247.png)

Here are all file list, these files have `/*# sourceMappingURL={css-file-name}.css.map */`:
<img width="902" alt="ekran resmi 2017-11-06 21 16 12" src="https://user-images.githubusercontent.com/455983/32456796-8983f378-c32f-11e7-8527-98b17314bf61.png">

### Suggestion for a possible fix

Remove `/*# sourceMappingURL=AdminTheme.css.map */`
or
Add map files

* ProcessWire version: 3.0.82-dev
* PHP version: 7.1.11

**Comment by jacmaes** [comment]
Agreed. This is very annoying.

**Comment by ryancramerdesign** [comment]
I have disabled the source maps here, so they should begin to disappear as SCSS files get recompiled over the next few dev versions.
