### ISSUE TITLE
Can't remove "title" field from repeater

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#427]
### Short description of the issue

Can't remove "title" field from repeater because it is global required

### Expected behavior

The global flag should be ignored for repeater templates

### Actual behavior

I can't delete it without removing the global flag

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2017-11-06 at 11 22 32 am](https://user-images.githubusercontent.com/871211/32459599-12f7b4d2-c2e5-11e7-80aa-4cff46e9bbcf.png)

**Comment by Toutouwai** [comment]
Is it just PageTitleLanguage that causes this problem or PageTitle too? I can add and remove PageTitle without problem here.

**Comment by adrianbj** [comment]
It was a PageTitleLanguage field, but now even after setting it back to global I can add it to repeaters and delete and it works fine, so I don't know what happened before.

Any thoughts Ryan?

**Comment by ryancramerdesign** [comment]
Is it possible the repeater template was manually created via the API? When
FieldtypeRepeater creates the template, it adds the `noGlobal` setting to
it, which overrides any fields with the global flag.

**Comment by adrianbj** [comment]
> Is it possible the repeater template was manually created via the API?

Yeah, it's possible - it was on my sandbox site, so I don't remember all the things I have done so can't confirm either way. Do you think this is OK behavior if it was created via the API? Should we have to manually add the noGlobal setting when creating via the API?

**Comment by ryancramerdesign** [comment]
FieldtypeRepeater creates the template and parent automatically, even if
the field is created from the API, so it's not necessary to create the
template from the API. But if you do create it from the API, then you'd
want to use the same settings that repeater adds to the template:
~~~~~
$template->flags = Template::flagSystem;
$template->noChildren = 1;
$template->noParents = 1;
$template->noGlobal = 1;
~~~~~

**Comment by adrianbj** [comment]
As I said, I don't remember how this field (or its template were created), but I just looked back through some forum posts on the topic of creating repeater fields via the API. I haven't actually ever seen an official post on creating a repeater via the API. I put this together: https://processwire.com/talk/topic/4736-add-inputfieldrepeater-to-module-configuration-page/?do=findComment&comment=46299 which led to this function: https://processwire.com/talk/topic/5397-assigning-fields-to-repeaters-with-the-api/?do=findComment&comment=52123

Is there a better way that automatically takes care of all template creation etc?
