### ISSUE TITLE
Notice with PageTables when using Custom Page Label Format

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#428]
### Short description of the issue

If you have pagetable, where pages use template which have page-field that uses Custom Page Label Format then when rendering pagetable you get notice:

`Notice: Trying to get property of non-object in /www/processwire/PW30dev/wire/core/MarkupFieldtype.php on line 118`

This is problem is best explained in these two screenshot:

![image](https://user-images.githubusercontent.com/131855/32535337-4319657e-c462-11e7-92b4-898a30bc087f.png)

![image](https://user-images.githubusercontent.com/131855/32535373-6469e3e8-c462-11e7-9fdf-2367b1573df2.png)

As you can see, PW tries to find field called _association_name street_address city_ which is the custom page label.

### Expected behavior

No notice should be given in this valid configuration.

### Actual behavior

Notice is thrown.

### Optional: Suggestion for a possible fix

Not sure - maybe just an isset check there?

### Steps to reproduce the issue

1. Create page field and modify Custom Page Label Format to include multiple fields
2. Create pagetable field and add page field from step 1 there
3. Add pagetable to template and view that

You should then receive the notice (probably requires debug mode):
![image](https://user-images.githubusercontent.com/131855/32535436-b357bb56-c462-11e7-8b30-607eab38da70.png)

### Setup/Environment

* ProcessWire version: 3.0.79

**Comment by ryancramerdesign** [comment]
This is a simple fix, checking that $field is an object before accessing it as an object. I pushed that fix, but I'm not sure if there may be something further upstream or downstream to correct for this particular case. I don't have a good test case setup, but if you find a related issue persists after the fix please let me know and I'll set it up. Thanks.

**Comment by netcarver** [comment]
@apeisa Hello Antti. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.

**Comment by apeisa** [comment]
Sorry, yes this is fixed.
