### ISSUE TITLE
Problems with non-ascii characters in WireMail

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#43]
### Short description of the issue

Umlauts (non-ascii characters) used in the body or subject of messages sent using WireMail appear mangled.

### Expected behavior

Umlauts should display as entered.

### Actual behavior

Umlauts display as two characters with their raw ascii representation.

### Optional: Screenshots/Links that demonstrate the issue

See [forum discussion](https://processwire.com/talk/topic/14490-wiremail-problem-with-charset-and-german-umlauts/)

### Optional: Suggestion for a possible fix

The text and html body parts should always be sent using quoted-printable encoding. This way, even old 7bit-only smtp server won't have any problems in accepting and relaying the mail. Other possible 7bit-compatible encodings like base64 obfuscate too much of the content for debugging purposes.

The subject line and the name parts in the from: and to: header fields should similarly be encoded using quoted printable, enabling the use of utf-8 characters there as well.

Pull request submitted as processwire/processwire/pull/17

### Steps to reproduce the issue
See the examples in the forum discussion

### Setup/Environment
* ProcessWire version: 3.0/dev

**Comment by ryancramerdesign** [comment]
Thanks for the PR. I have added this so will close the issue.
