### ISSUE TITLE
Pages::save() before hook prevents page reference fields from saving when creating new page inside hook  

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#430]
### Short description of the issue

When I create a Pages::save() before or Pages::saveReady() before or after hook in which I have code that creates and saves a new page inside of the hook, any Page reference fields on the original page that triggered the hook are not saved. All other field types are saved correctly.

I ran into this issue a couple times and have now replicated it enough that it should be be possible to identify the cause. There are two forum posts about this that went unresolved:

https://processwire.com/talk/topic/16843-unusual-behavior-when-saving-pages/?tab=comments#comment-148209

https://processwire.com/talk/topic/15122-page-save-inside-of-a-before-savepagefield-hook-prevents-from-saving-the-field/

### Expected behavior

All fields with changes on the original page that triggered the hook are saved.

### Actual behavior

All fields except for Page reference fields are saved.

### Steps to reproduce the issue

1. Create a template with a title and page reference field
2. Write a Pages::saveReady() before or after hook that checks the template of the page and creates a new page when the first page is saved. The page that gets created can be any template. (I suggest creating a page with a different template so you don't create a recursive loop.)
3. In the ProcessWire back end, create a new page with the template you created in step 1.
4. Change the page field and title field and save the page.
4. The title will have saved, but the Page reference field will be unchanged. (if this doesn't happen the first time, try it again)

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 7

**Comment by TomS-** [comment]
https://github.com/processwire/processwire-issues/issues/434 Is this linked? As a repeater is like a PageReference?

**Comment by Toutouwai** [comment]
I can confirm this issue, and it seems to be related to the `uncacheAll` option in [PagesEditor::save()](https://github.com/processwire/processwire/blob/22c69ec599a8c0058e68885c20ad477106b2864d/wire/core/PagesEditor.php#L473). This method is triggered by the `$p->save()` in the hook.

 When `uncacheAll` is true, which it is by default, then the new value of the Page Reference field is lost and it reverts to the old value.

**Comment by ryancramerdesign** [comment]
Toutouwai is right here, if you are creating/manipulating and saving pages in hooks that already are saving pages, you'll have to do an uncached save by using the `uncacheAll=false` option for the $options argument of the save method(s).

**Comment by thetuningspoon** [comment]
Another thing to watch out for here that I just ran into and wanted to document somewhere: 

If you are assigning the page (who's save you're currently hooking into) as a value for a page field on the page you're creating in the hook, you must use assign the page ID property rather than using the object itself.

Like so:
```
$p = $event->arguments(0);

$newP = new Page();
$newP->pageField = $p->id; // <-- Do $p->id, instead of just $p
$newP->save(['uncacheAll' => false]);
```

For some reason assigning the object directly causes the cache to be lost even though I'm saving the new page with uncacheAll=false
