### ISSUE TITLE
Inputfield Dependencies doesn't work with repeaters

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#431]
### Short description of the issue

Using "Show this field only if" doesn't work when outing repeater.count>0 

### Expected behavior

Should display when repeater has item.

### Actual behavior

Stays hidden.

### Steps to reproduce the issue

1. Create a repeater
2. Create a field that only displays if repeater has item
3. Add repeater item, the field is still hidden.

### Setup/Environment

* ProcessWire version: 3.0.82

**Comment by ryancramerdesign** [comment]
That ".count" option is for counting HTML selection/multi-selection widgets. Things like selects and checkboxes (and components that use them, like asmSelect). It won't work for something that isn't built on top of these.
