### ISSUE TITLE
Uploading animated gif

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#433]
### Short description of the issue

When uploading animated gif on image field, I get errors:

<b>Notice</b>:  Undefined property: ProcessWire\PWGIFFILEHEADER::$m_colorTable in <b>C:\inetpub\wwwroot\wire\core\ImageInspector.php</b> on line <b>235</b><br />

### Expected behavior

Successful upload.

### Actual behavior

Spinner rotating, uploaded image is deleted upon save.

### Setup/Environment

The animated gif is created with licecap. https://www.dropbox.com/s/1earkm673job5gj/tabs1.gif

* ProcessWire version: 3.0.83
* (Optional) PHP version: 7.0

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik , I've pushed a fix for this issue. 

@horst-n can you take a look if my fix is okay? Just wondering if I should use a different value than 0 for when `$gfh->m_colorTable->m_nColors` is not set? Thanks.

**Comment by matjazpotocnik** [comment]
Thanks, it's fixed.

**Comment by horst-n** [comment]
@ryancramerdesign to set it 0, when no value is returned, is ok!
Currently we have no further processing that rely on that value.
But maybe it is a good idea to add a comment to it, that setting this to 0 may be the result of a wrong fileheader (?). An image with 0 colors does not make sense :)
