### ISSUE TITLE
Using PageFrontEdit to edit 404 page content works but gets stuck on "saving"

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#435]
### Short description of the issue

Saving contents of the 404 page using PageFrontEdit works (content is saved), but the save button gets stuck at "saving", new content is never populated on page, etc. The reason for this seems to be that the "post save data to server" `$.post` call in PageFrontEdit.js can only handle a success response and fails if the response is something else (404).

### Expected behavior

Contents of the 404 page should be editable using PageFrontEdit, just like any other page.

### Actual behavior

Contents are editable, but after clicking "save" you need to manually refresh the page.

### Optional: Suggestion for a possible fix

One possible fix would require setting 200 OK status code from within PageFrontEdit.module `inlineSaveEdits()` method. This would fix this particular error by overriding the 404 code set earlier.

This seems like the proper behaviour to me either way: since this method returns a JSON string and exists, I don't see why a 404 code would ever make sense here. Additionally PageFrontEdit handles errors via returned "status" value, not based on HTTP codes.

### Steps to reproduce the issue

1. Enable front-end editing for 404 page content
2. Edit content and click "save"

### Setup/Environment

* ProcessWire version: 3.0.83
* (Optional) PHP version: 5.6.x

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've added your suggested fix for this issue.

**Comment by teppokoivula** [comment]
Thanks @ryancramerdesign!
