### ISSUE TITLE
New added FieldtypeOptions-Field doesn't work with existing Pages

### ISSUE THREAD

**Issue by AndreasFaust** [processwire/processwire-issues#436]
### Short description of the issue

When I create a new SelectOptions-Field in a template, it doesn't work for existing Pages with this template, only for new ones.

### Expected behavior

I create a SelectOptions-Field and add it to a template. All Pages, I have created with this template, adept the default values from the new SelectOptions-Field.

### Actual behavior

The new SelectOptions-Field of existing pages has no values (id, value and title are "null").

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Create a Tempalte A.
2. Create a Page with Template A.
3. Create a Field with Fieldtype SelectOptions with default values and add it to A. 
4. Check out the values of the field (with Tracy-Debugger). 

### Setup/Environment

ProcessWire version:  3.0.83
PHP version:  7.1.6
MySQL version: 5.6.35

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Are you referring to use of the "What option(s) do you want pre-selected?" setting? This is referring to pre-selected in the page editor, not to anything else. The page would have to be saved with the selection before it would be committed to the database and appear as live values for pages. So if you create a new field and add it to a template, it's not going to have any value present for a given page using that template until that  page is saved with the value selected. The same goes for any field in PW. If you need the value pre-populated in the DB for a bunch of existing pages, this can be done from the API—let me know, I can provide an example if it helps.

**Comment by AndreasFaust** [comment]
I referred to the subject, that the pre-selection isn't adapted by existing pages. I see now, that this is not a bug and that it's easy to populate the fields via the API afterwards (which didn't occur to me). Thank you very much for explaining.

**Comment by ryancramerdesign** [comment]
Sure, no problem. Thanks.
