### ISSUE TITLE
Radio button form markup gets replaced when using markup regions

### ISSUE THREAD

**Issue by jtborger** [processwire/processwire-issues#437]
### Short description of the issue

I'm using markup regions. Since I enabled them, I found my radio buttons in my form (using FormBuilder) are not displayed correctly. The label value, which is supposed to be in a <span>$label</span> is not there.

### Expected behavior

I expected to render the radio button label correctly <input type="radio" ...><span>$label</span></input>

### Actual behavior

<input type="radio" ...></input>

### Optional: Screenshots/Links that demonstrate the issue

Not working: (see html source opened too)
![schermafbeelding 2017-11-18 om 10 42 15](https://user-images.githubusercontent.com/195674/32978998-3a614ad0-cc4d-11e7-9c5a-cc6d1bb0488d.jpg)

Working:
![schermafbeelding 2017-11-18 om 10 41 42](https://user-images.githubusercontent.com/195674/32978999-3a7d291c-cc4d-11e7-94f0-ad1be8b82db1.jpg)

### Optional: Suggestion for a possible fix

What catched my attention is the class "pw-no-select" in the 'working' version (when disabled markup regions). Does this has to do with it? Since markup regions use 'pw-' as a control thing.

Also, I just posted a question to the support forum about that it seems my templates gets rendered/called twice when running a page with markup regions enabled.
If there is something wrong over there which causes this issue, please close it.

https://processwire.com/talk/topic/17790-using-markup-regions-causes-template-to-render-twice/

### Steps to reproduce the issue

1. Create form with radio buttons
2. Use markup regions
3. Display the form, see if the label value of the radio button is displayed.

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.62 <br />
PHP: 5.6.30 <br />
Webserver: Apache/2.4.10 (Debian) <br />
MySQL: 5.7.17 <br />
 <br />
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: -1 <br />
max_input_vars: 1000 <br />
memory_limit: 128M <br />
post_max_size: 8M <br />
upload_max_filesize: 2M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support:  <br />
FreeType: 1 <br />
Imagick Extension:  <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminThemeUikit: 0.1.6 <br />
FormBuilder: 0.3.2 <br />
InputfieldFormBuilderFile: 0.0.2 <br />
ProCache: 3.1.7 <br />
ProcessFormBuilder: 0.3.2 <br />
ProcessProCache: 3.1.7 <br />
TracyDebugger: 4.7.13 <br />
WireMailSmtp: 0.2.7 <br />
</details></details>

**Comment by jtborger** [comment]
err... I just thought of checking this class="pw-no-select" class being added is the cause of the disappearing, and it seems it is... I altered the $textClass line in InputfieldRadios.module (line 69) so it doesn't say pw- anymore and it fixed the removal of the element being replaced by nothing.

**Comment by ryancramerdesign** [comment]
This one should be already fixed on the dev branch (a couple months ago), so just upgrading to the dev branch should fix it. 

Once on the dev branch, you can also give hints to markup regions to increase their performance and/or fix any region identification issues (should there be any). You can do this by appending an HTML comment with the region ID to the closing tag of the region, i.e. 
~~~~~~
<div id='content'>
  ...
</div><!--#content-->
~~~~~~
More here: https://processwire.com/blog/posts/pw-3.0.70/

**Comment by jtborger** [comment]
OK thats wonderful. Somehow, I did not find anything about this issue, I probably didn't search with the right terms... Sorry for filing an issue which is fixed already.
Is it safe to use dev branch for a live site..? I mainly use stable releases for production just to be on the safe side but since you mention it as a solution I consider it shouldn't be a major problem?

**Comment by ryancramerdesign** [comment]
No problem, I wouldn't expect anyone to know that one is already fixed, it was a pretty esoteric error and think maybe you and I are the only ones to run into it. I think it's fine to use the dev branch so long as you test things thoroughly to confirm everything works that you expect to. And of course keep good backups of site and DB. I'm more likely to use the master branch if I'm handing off a site that I won't be working with for awhile. But if I'm actively working with a site regularly, I'll often use the dev branch.

**Comment by jtborger** [comment]
Esoteric indeed.. I have a good nose for those kind of issues unfortunately :)
I've updated it to .84 since I'm working on this one for the next couple of weeks on and off so its easy to upgrade and maintain.
Thanks again!
