### ISSUE TITLE
Notifications showing before being logged in

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#438]
### Short description of the issue

I opened the admin page of my site and saw these notifications even before I had logged in:
![screen shot 2017-11-21 at 10 19 19 am](https://user-images.githubusercontent.com/871211/33089484-9909a85c-cea5-11e7-8f07-a0700f940227.png)

### Expected behavior

These should be hidden until logged in and only shown to superusers

### Actual behavior

Shown to guest user who visits admin page (/processwire/) 

* ProcessWire version: 3.0.84

**Comment by ryancramerdesign** [comment]
Notifications aren't admin specific. It's up to whatever creates the notification to decide. In this case, when you install an upgrade, some notices usually accompany the process. The reason for this is that if some problem occurs during an upgrade (or even if not), you probably want some feedback on what happened. In some cases an error might log you out, or you might not be able to login, so it's good for these things not to be hidden. You aren't going to see notices like this if you aren't actively there installing upgrades.

**Comment by adrianbj** [comment]
> You aren't going to see notices like this if you aren't actively there installing upgrades.

Ok - sorry about that - I should have checked on another browser - it looks like they won't show unless there is a wire cookie.
