### ISSUE TITLE
Notice: Undefined index: sharpening in Pageimage.php on line 513 

### ISSUE THREAD

**Issue by wanze** [processwire/processwire-issues#439]
### Short description of the issue

If debug mode is active and an image is getting resized, the following notice is displayed:

```Notice: Undefined index: sharpening in Pageimage.php on line 513 ```

The reason is a missing array key `sharpening` in the default options array here:
https://github.com/processwire/processwire/blob/master/wire/core/Pageimage.php#L408

### Expected behavior

No notice is thrown

### Optional: Suggestion for a possible fix

Add a default value for `sharpening` here: https://github.com/processwire/processwire/blob/master/wire/core/Pageimage.php#L408

### Steps to reproduce the issue

1. Enable debug mode
2. Upload a new image to a page where the template performs some resizing 
3. Visit the page

### Setup/Environment

* ProcessWire version: 3.0.84
* PHP version: 7.1

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix. The thing is, the 'sharpening' index is present in `$config->imageSizerOptions`, which gets array_merge'd with the default options, so 'sharpening' does not need to be present in the default options. Is it possible you've got a `$config->imageSizerOptions` in your /site/config.php file that lacks the 'sharpening' index? I'm thinking that might be the source of the error, though it's good for us to add it to the defaults either way, which should correct it for cases like that.

**Comment by wanze** [comment]
You are right @ryancramerdesign, I was using `$config->imageSizerOptions` in my config.php without the `sharpening` key. Thank you for fixing it anyway 👍  :)
