### ISSUE TITLE
Cannot save pass in install.php

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#44]
### Short description of the issue

I get this error on the last step of the installation.

404 Not Found
 Can't save page 41: /manage/access/users/benni/: Call $page->setOutputFormatting(false) before getting/setting values that will be modified and saved. [pass]
### Expected behavior

Saving the password correctly.
### Steps to reproduce the issue

1. Download PW
2. Install with blank template
3. Get to last step
### Setup/Environment

- ProcessWire version: 3.0.36

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Can anyone else? Any other details you can provide?

**Comment by LostKobrakai** [comment]
I got it working by adding `$user->of(false);` to force the user to be unformatted. I'm not sure why it happened either, as the user should've been newly created anyways.

**Comment by ryancramerdesign** [comment]
Yeah, that's a mystery. Were you installing on-top of an existing database? Anything unusual about the username you entered? Where did you add the $user->of(false);? There's no harm in it, so I will do the same just in case whatever conditions caused it occur for someone else. Just want to make sure I know exactly where you added it.

**Comment by LostKobrakai** [comment]
I added it right here: https://github.com/processwire/processwire/blob/master/install.php#L1041
But I'm almost certain that I didn't install it over an existing database.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested update to the install.php in the latest commit

**Comment by lesaff** [comment]
Just encountered this issue. See https://processwire.com/talk/topic/14656-installation-error-fresh-pw-3036-from-composer/

I'll use the latest commit `install.php` for now

**Comment by yuters** [comment]
I have this issue as well, the fix works.

I'm on php5.6.27 if it helps.

**Comment by ryancramerdesign** [comment]
An update was put in for this a couple of weeks ago, but on the dev branch. I just merged that one to the master.
