### ISSUE TITLE
Page list item zIndex not resetting after move

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#440]
### Short description of the issue

The zIndex of a page is elevated while moving, but is not reset after dropping

### Expected behavior

zIndex of moved page should return to default value

### Actual behavior

zIndex stays elevated until page reload

### Optional: Screenshots/Links that demonstrate the issue

See how the dropdown menu is now obscured by the page that was just moved.

![screen shot 2017-11-25 at 7 25 22 am](https://user-images.githubusercontent.com/871211/33231916-25b79476-d1b2-11e7-9da5-6d1595b82690.png)

**Comment by ryancramerdesign** [comment]
I can't duplicate that one here. Tried moving various pages around, but not seeing z-index issues with the menus. Is it possible it's coming from whatever is adding those little superscript numbers to the page labels? (I'm not sure what that is)

**Comment by adrianbj** [comment]
Ah - you're right - sorry for not checking more thoroughly :)

Those page IDs are from AdminOnStreroids by @rolandtoth
