### ISSUE TITLE
Inputfield visibility settings do not work as expected with fieldset

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#441]
### Short description of the issue

Several of the available options for inputfield visibility do not work as expected with fieldset inputfields (affects both Fieldset and FieldsetGroup).

### Problematic visibility options

**1. Open + Cannot be closed:** Fieldset is rendered closed and cannot be opened (so the opposite of the expected behaviour).

**2. Open when populated + Closed when blank + Load only when opened (AJAX):** Fieldset is not rendered.

**3. Open when blank + Closed when populated:** Fieldset is rendered closed even when all child fields are blank.

**4. Closed + Load only when opened (AJAX):** Fieldset is not rendered.

**5. Hidden (not shown in the editor):** Fieldset is not rendered but child fields are rendered. The expectation is that the visibility of the fieldset affects the visibility of the child fields, so having the child fields appear in this case is unexpected.

### Setup/Environment

* ProcessWire version: 3.0.84

**Comment by ryancramerdesign** [comment]
I can't duplicate any of the cases mentioned here, except the last. In all the cases mentioned, it's working as intended here. Do you have some other module installed that might be manipulating something in the admin? If not, what is the contents of your fieldset? Maybe something about the field(s) within it are the source?

Regarding the last one "Hidden (not shown in the editor)," that was intended just for individual fields, not fieldsets. Traditional fieldsets are purely for visual grouping for the page editor, so there's little purpose to make it hidden. Though FieldsetGroup goes beyond that now, so perhaps there's a use case there. It may be possible that support an be added (at least for FieldsetGroup) if there's demand for it. Thanks.

**Comment by Toutouwai** [comment]
I checked again and all of these issues seem to be real, but some are only exhibited when the fieldset does not have a label specified. As a separate issue, not including a label for a fieldset causes some weird display issues which I have raised previously: https://github.com/processwire/processwire-issues/issues/304
I didn't notice this and mention it in the first comment of this issue because the field edit links added by AdminOnSteroids actually corrects the odd rendering of fieldsets without labels.

So a bit more info that might help you reproduce the visibility issues...

**1. Open + Cannot be closed:** to reproduce, make sure the fields within the fieldset are empty. I used empty text and textarea fields inside my fieldset while testing. The result is a closed fieldset without a open/close toggle icon.

**2. Open when populated + Closed when blank + Load only when opened (AJAX)**: to reproduce, make sure the fieldset does not have a label specified and the fields within the fieldset are empty.

**3. Open when blank + Closed when populated:** this option causes one of two kinds of incorrect rendering, depending on if the the fieldset has a label or not. If it does have a label and the subfields are empty the fieldset is rendered closed. If the fieldset does not have a label the fieldset is not visible at all.

**4. Closed + Load only when opened (AJAX):** to reproduce, make sure the fieldset does not have a label specified.

**5. Hidden (not shown in the editor):** I hear what you are saying regarding the intention for the hidden option, but there can be cases where you want to conditionally hide or show a fieldset with a hook. Because hiding the fieldset does not hide the subfields within it you then have to work out which fields in a template are inside the fieldset so that they can be hidden individually. This is doable but a bit awkward because an inputfield does not report if it is contained inside a fieldset or not. It would be nice if the hiding of fields within a hidden fieldset was handled automatically.

**Comment by netcarver** [comment]
@Toutouwai Hi Robin, is this issue still live in newer versions of PW?

**Comment by Toutouwai** [comment]
Looks like several of these issues are resolved now, perhaps due to the recent fix for [fieldsets without labels](https://github.com/processwire/processwire-issues/issues/304).

The issues still outstanding are:

**3. Open when blank + Closed when populated:** fieldset is rendered closed when all fields within the fieldset are blank. Hopefully it will be possible to get this working without too much trouble because it is the inverse of a visibility setting that is working nicely with fieldsets: "Open when populated + Closed when blank".

**5. Hidden (not shown in the editor):** fields within the fieldset are not hidden when the fieldset is hidden. Would be handy to have this working for the reasons stated in my previous comment. Also it would be more consistent with showIf visibility (hiding a fieldset hides the child inputfields). This issue with hidden fieldsets has also been noted separately: https://github.com/processwire/processwire-issues/issues/604

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed fixes for 3 and 5 above. For item 5 I was a little worried about potential side effects before, but in testing here so far, I think it's going to be just fine.

**Comment by Toutouwai** [comment]
Thanks Ryan, working nicely. I think item 5 is going to be quite useful.
