### ISSUE TITLE
$config->urls doesn't return expected values under a certain condition

### ISSUE THREAD

**Issue by jonnykrueger** [processwire/processwire-issues#442]
### Short description of the issue

The $config->urls object doesn't return values as expected in a certain situation:

I have several domains in my document root (shared hosting). With following .htaccess file I redirect all incoming requests for a host to the matching directory:

```
RewriteCond /var/www/virtual/html/hosts/%{HTTP_HOST} -d
RewriteRule . /var/www/virtual/html/hosts/%{HTTP_HOST}/%{REQUEST_URI} [L,NS]
```

This works for all my hosted projects (wordpress, piwik, my own php based framework etc), but not for Processwire, regarding the generation of correct URIs.

Under /var/www/virtual/html/hosts/example.com is my Processwire installation.

### Expected behavior

For example **$config->urls->templates** should return **/site/templates/**.

### Actual behavior

For example **$config->urls->templates** returns **/hosts/example.com/site/templates**.

### Optional: Suggestion for a possible fix

I'm not sure. Since this problem also affects the admin template, hardcoding the URIs of assets doesn't solve my problem.

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
I don't really know on this one, as I've not seen a setup like this before. It looks like there's a redirect occurring for every request that comes in before PW even sees it? You might want to experiment with putting a test PHP file in your hosts/domain.com/ directory and doing a `print_r($_SERVER)` to see what paths are showing up in there. My guess Apache doesn't know about this domain-to-path strategy, so the `$_SERVER` vars don't reflect it, and thus PW doesn't either. You might be able to trick PW by manually setting the `$config->urls->root` (and others if needed) in your site/config.php file.

**Comment by jonnykrueger** [comment]
Thanks for your reply. I will try that.
