### ISSUE TITLE
SQL error for $pages->find() when using count selector for images field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#443]
### Short description of the issue

An SQL error occurs when a count selector is used for an image field that has not been added to any templates.

> Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') ) )) WHERE (pages.status<1024) AND (((num_field_images_1>0 AND pages.templat' at line 4 on line: 410 in D:\Websites\__www\pw3-raw\wire\core\PageFinder.php

### Expected behavior

No results are expected for a field that has not been added to any templates, but no error should occur.

### Steps to reproduce the issue

1. Create an images field named "images". Do not add it to any templates.
2. Execute the following:
````php
$test = $pages->find("images.count>0");
````

### Setup/Environment

* ProcessWire version: 3.0.84
* PHP version: 7
* MySQL version: MariaDB 10.1.16

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai that's a great find. I've pushed a fix.

**Comment by Toutouwai** [comment]
Thanks.
