### ISSUE TITLE
Language Tabs "double click" in Uikit theme

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#444]
### Short description of the issue

Double clicking a language tab to switch all tabs on page, the tabs do not change active states

![image](https://user-images.githubusercontent.com/370148/33500791-722d401c-d6da-11e7-88d3-faac94288c62.png)

### Setup/Environment

* ProcessWire version: 3.0.84
* Module: Uikit Theme

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Double click changes all language tabs in testing here. Since AdminThemeUikit is now in the core, is it possible you are running off an older version in /site/modules/?

**Comment by somatonic** [comment]
No It's a upgrade and I never had Uikit installed. Strange, it seems to be gone, maybe cache.
