### ISSUE TITLE
Advanced Mode indicator shows for non-superusers

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#445]
### Short description of the issue

Advanced Mode indicator shows for non-superusers

### Expected behavior

It shouldn't be shown for anyone but superusers

### Actual behavior

It shows for everyone

**Comment by ryancramerdesign** [comment]
It's a label that indicates `$config->advanced` is set to true, and is intended to show in the admin regardless of who is logged in. While a lot of the features currently enabled by advanced mode might only be available to superuser, the state itself isn't superuser specific.

**Comment by adrianbj** [comment]
> While a lot of the features currently enabled by advanced mode might only be available to superuser, the state itself isn't superuser specific.

I understand it's not user specific, I just thought it might be confusing for regular users - I'd rather not have to answer the question of what "advanced mode" means. Just trying to ensure the cleanest interface possible.

But no big deal!
