### ISSUE TITLE
Can't upvote/downvote comments if comments field is assigned to repeater

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#446]
I have a template and there's a field on that template that is a repeater.  That repeater has a comments field assigned to it.  The comments field works correctly on repeaters (in terms of posting a comment and it saving in the right place), however not with upvote/downvote.

I tried using the same comments field on a normal page and it works fine.

The reason it doesn't work on repeaters is because the vote url is as follows:
site.com/admin/repeaters/for-field-99/for-page-1496/1512503459-2392-1/?comment_success=upvote&comment_id=1&field_id=101#Comment1

Since repeater pages are stored under the admin, it's redirecting the user to the login form (even if the user is logged in and superuser).

PW version 3.0.84.

**Comment by ryancramerdesign** [comment]
I'm not really sure how we'd do this, but will think about it some more. Comments require a landing page URL consistent with the page the comments field lives on. I'm kind of surprised the rest of the comments work, and that it's only upvote/downvote where you are seeing issues. If that's the case, maybe there is some way we could work around it, though it would definitely require comments being aware of their context in a repeater (currently comments have no repeater-specific code in them).

**Comment by netcarver** [comment]
@jlahijani @ryancramerdesign Any further updates to report on this issue?
