### ISSUE TITLE
Can't remove roles from a user as an admin

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#448]
### Short description of the issue

As an admin user, if I edit a user and try to remove a role, I get a javascript error in Chrome's console saying:
"An invalid form control with name='_pass' is not focusable."

This error prevents the form from submitting.

### Setup/Environment
PW 3.0.84

* ProcessWire version:
* (Optional) PHP version: 7.1

**Comment by adrianbj** [comment]
I thought all these issues had been fixed already. I can't reproduce this one here.

For reference: https://github.com/processwire/processwire-issues/issues/432

**Comment by gmclelland** [comment]
Interesting..Thanks for the issue link.  I did a modules refresh and did a hard refresh on my browser several times to make sure to clear the cache, but it didn't seem to make a difference.

I'm still seeing the behavior.

Strange... I tried to remove a role on another site(same PW version) and it worked.

One difference I noticed:
Site that worked used AdminThemeUikit
Site that didn't work used the Default Classic Admin Theme

**Comment by gmclelland** [comment]
More strangeness...I tested the non working website locally and it worked fine.

I test some other sites and they worked fine.

So it is something specific to that one production website.

One thing I notice is that the non-working website show the ****** in the first set password field with an indicator.
![edit page arianne shipley creeksidecleanup com 2017-12-07 10-11-05](https://user-images.githubusercontent.com/40570/33725160-f3d69928-db36-11e7-967f-325941cf815c.jpg)

If I edit the same user on the working local site it looks like this:
![edit page](https://user-images.githubusercontent.com/40570/33725203-1b4134dc-db37-11e7-92a2-ce68430e228d.jpg)

Maybe the InputfieldPassword module didn't fully upgrade?  I wonder if I can reinstall it somehow?

**Comment by adrianbj** [comment]
> Maybe the InputfieldPassword module didn't fully upgrade? 

Can you check to see if the "new-password" value is being added to the autocomplete?

If not, check to see if these changes (https://github.com/processwire/processwire/commit/81a07fde349f27df406a41e3f7bd4200dafbdd2a) exist on your server.

**Comment by gmclelland** [comment]
I found the problem.  It turns out that my Lastpass browser extension was automatically prefilling the password field.

When I tried it in a new incognito session, everything worked correctly.

Thanks for the help @adrianbj

**Comment by adrianbj** [comment]
Maybe PW could help out with this so you don't need to mess with LP.

Have a read of this thread, but in particular this comment:
https://stackoverflow.com/a/44984917/1524576

Looks like: `data-lpignore="true"` might be a useful addition to PW? Although I do worry that other password managers will need their own custom data attribute as well?

**Comment by gmclelland** [comment]
Interesting SO thread, but I think it might be too specific to include work arounds for Lastpass when other password managers will probably have the same problems....Unless.... PW starts getting a ton of reports about this type issue.
