### ISSUE TITLE
AdminThemeUikit continues to apply to login screen even when option is unselected

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#451]
### Short description of the issue

I [previously raised this issue](https://github.com/ryancramerdesign/AdminThemeUikit/issues/30) in the separate AdminThemeUikit repo and it seemed to be fixed, but the problem is back again now.

AdminThemeUikit continues to apply to the login screen even when the "Use this admin theme for login screen" checkbox is unselected and `$config->defaultAdminTheme = 'AdminThemeDefault'` is set in /wire/config.php (on a related note, please see [this forum post](https://processwire.com/talk/topic/17786-pw-3084-%E2%80%93-core-updates-installer/?do=findComment&comment=156128) regarding the mismatch between AdminThemeUikit being used as the default theme on install yet not being defined as the default admin theme in /wire/config.php).

### Steps to reproduce the issue

1. Install PW 3.0.85
2. Log in as superuser and set admin theme to "Default" in user profile.
3. Visit settings for AdminThemeUikit and confirm that "Use this admin theme for login screen" is unchecked.
4. Log out and observe the Uikit theme applied to login screen.

### Setup/Environment

* ProcessWire version: 3.0.85

**Comment by ryancramerdesign** [comment]
Just tried on two different sites but am not able to duplicate that here. However, I should note that AdminThemeUikit is our default for new installations. You mentioned on #1 above "install PW", so if you are starting from a new installation, then there's going to be a `$config->defaultAdminTheme = 'AdminThemeUikit';` in your /site/config.php. On existing installations, there won't be (so it falls back to the one in /wire/config.php). You would have to remove that one in site/config.php (or change it to one of the other admin themes) if you don't want it to be the default, which is also used for the login screen if another theme doesn't override it.

**Comment by Toutouwai** [comment]
> if you are starting from a new installation, then there's going to be a $config->defaultAdminTheme = 'AdminThemeUikit'; in your /site/config.php

That solves it, thanks.

It didn't occur to me that AdminThemeUikit would be automatically set in /site/config.php. If this is the default theme going forward, shouldn't that default be defined in /wire/config.php? I thought /site/config.php is for site-specific overrides (usually consciously chosen by the site dev), not things considered to be the core defaults.

I guess it is done this way to avoid changing the default theme on older sites when they are upgraded. If the installer is going to set the default theme then could you please add an option to the installer allowing the default admin theme to be selected? I don't think it should be hardcoded in there. 

One reason for making it a selectable option is that it is not possible to export $config->defaultAdminTheme = 'AdminThemeDefault' in /site/config.php using the Site Profile Exporter. That's because so long as that setting remains in /wire/config.php the Site Profile Exporter does not recognise it as a customisation to be included in the export - only config values that differ from those in /wire/config.php may be exported.

**Comment by ryancramerdesign** [comment]
> It didn't occur to me that AdminThemeUikit would be automatically set in /site/config.php. If this is the default theme going forward, shouldn't that default be defined in /wire/config.php?

No because it's the default only for new installations at present. What's in /wire/config.php applies to existing installations too. At some point we will make it the default for existing installations too, but didn't want to make that assumption just yet. Now if a user has selected an admin theme in their profile, then this would not override it. It would only apply to existing installations and users where they haven't already selected a particular admin theme in their profile. 

> If the installer is going to set the default theme then could you please add an option to the installer allowing the default admin theme to be selected? I don't think it should be hardcoded in there.

Well the intention is that new installations should see this as the admin theme when they first use PW. This maintains a consistency between the look of the installer, and their first exposure to the admin. I think that what admin theme you ultimately want to use takes more review and consideration than most would have at installation time. I'd rather let folks (that want to) focus on that part once they are installed. 

For exporting site profiles, this will be solved once we make the switchover in /wire/config.php, but if that's going to be later rather than sooner, I can always update the site profile exporter to include the setting too.

**Comment by Toutouwai** [comment]
> I can always update the site profile exporter to include the setting too

That would be appreciated, thanks. And could you also allow Site Profile Exporter to include the setlocale() setting in /site/config.php? This would help to minimise the number of things I have to remember to manually add/override for new installations.

**Comment by Toutouwai** [comment]
Closing here and new issue opened in Site Profile Exporter repo: https://github.com/ryancramerdesign/ProcessExportProfile/issues/12

**Comment by matjazpotocnik** [comment]
I'm reopening this issue as I stumbled on this one. I'm using latest PW, upgraded from PW2. Using Default Admin Theme. I have the option to apply AdminThemUikit to login screen turned off. On the first occurrence of the login screen, everything is ok. But when the session expires (after one day by default) then the login screen comes from AdminThemeUikit and not from AdminThemeDefault.
