### ISSUE TITLE
ListerPro Error On Configuration Page!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#453]
Everything works find but not in lister configure screen :( 

**Error Details:**
Warning: count(): Parameter must be an array or an object that implements Countable in .../../ProcessPageListerPro\ListerProConfig.php on line 119
![listererroe](https://user-images.githubusercontent.com/5323832/33936116-0fbe2014-e007-11e7-93a8-5be1433bda58.PNG)

..
**ProcessWire Version 3.0.85
PHP 7.2 (Localhost)**

**Comment by adrianbj** [comment]
@Mu9tafa-Online - could you please add `.../../ProcessPageListerPro\ListerProConfig.php on line 119` here: https://github.com/processwire/processwire-issues/issues/408 and then close this issue. May as well keep it all together. Thanks!
