### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by webbear** [processwire/processwire-issues#456]
### Short description of the issue
Site with many images and hannacode
Upgrading to dev 3.0.85 + and I get Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /wire/core/WireHooks.php on line 296

No page/no admin access

### Expected behavior
page render as in 3.0.84

### Actual behavior
error screen:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in l/wire/core/WireHooks.php on line 296
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
Warning: Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0

### Optional: Suggestion for a possible fix
Setting Page.php back to before commits:
04b7dd040498e3cef84c1f65717e451defc6bb54 [04b7dd0]
45eadd971b49691ad707c930d595e79b4a322655 [45eadd9]
and page renders as usual
### Steps to reproduce the issue

1. Upgrade to dev 3.0.85 +

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 7.1.8
* (Optional) MySQL version: 5.6.35
* (Optional) Any 3rd party modules that are installed and could be related to the issue:
Hannacode (ProCache installed but disabled)

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Can anyone else? The line indicated in the error message is a `wireClassName()` call (asking for the class name of an object), so I suspect that's not related, just coincidence. Is there any change if you grab a fresh copy of the core from today?

Are you seeing the same issue on any PW installs, or does it seem to be isolated to just this instance? Thanks.

**Comment by webbear** [comment]
In fact it‘s only this instance.
I use pw in a multisite environment and all other sites work well. Will grab a fresh copy a soon as possible and post back

**Comment by ryancramerdesign** [comment]
There were some changes in the way that autojoin fields are handled by the Page class in 3.0.85, as well as some other tweaks to it pushed yesterday. It seems likely to me that the error could be coming from something related to that, perhaps in combination with something unique about that particular instance. The commits pushed yesterday improve upon that further, and might potentially fix the issue. But hard to say for sure since I've not seen it here yet.

**Comment by webbear** [comment]
Now, I exported the site profile and installed it with dev 3.0.84 to isolate it better. With 3.0.84 it works. Then I upgraded to 3.0.86 and I'm getting the same errors as above. I'm going to isolate the problems further during the next few days - it could be, that the size of my files directory is  too large (1.19GB )...

**Comment by incognitoms** [comment]
@webbear Could you please check if your "title" field is set to "Page Title (Multi-Language)" instead of "Page Title" (the default setting)?

**Comment by webbear** [comment]
thanks, i just checked it and was surprised that title was set to Multi-Language although this particular site is not multilingual. I switch to the default and could upgrade without any hassle...

**Comment by incognitoms** [comment]
@ryancramerdesign I think the culprit is found - if the title field is set to "Page Title (Multi-Language" instead of default "Page Title", the memory issues emerge. May you revisit the latest additions (3.0.84 to 3.0.86) with this in mind?

**Comment by webbear** [comment]
And this happened with title set to Page Title (Multi-Language) when there is only one language (default) - upgrading multi language sites with more languages set was no problem.

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate it once I deleted all languages, leaving just "default" as the one and only language. I have pushed a fix to the dev branch. Please let me know how it works for you. Thanks.

**Comment by webbear** [comment]
Thanks, Ryan, the fix works fine!

**Comment by webbear** [comment]
Thanks, Ryan, the fix works fine!

**Comment by netcarver** [comment]
@webbear Hello. I see that this issue is resolved now. Please could you close the issue in that case. Thank you.
