### ISSUE TITLE
Should InputfieldTextarea automatically trim() content?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#459]
### Short description of the issue

InputfieldTextarea always trims content. It happens here: https://github.com/processwire/processwire/blob/aa1f7dbd4718532896e209d694db0340c2d30067/wire/modules/Inputfield/InputfieldTextarea.module#L119

### Expected behavior

I would have thought that blank lines at the start should be valid

### Actual behavior

Leading and trailing blank lines are `trim()`ed.

### Optional: Suggestion for a possible fix

If you think it should be as it currently is, do you think it would be nice to make it an option that we could change on a case by case basis?

**Comment by ryancramerdesign** [comment]
I think we have cases where the core expects the values to be trimmed, but it's been awhile, so I don't remember exactly where. But if you want to try removing it, let me know how it works for you, I can potentially make it a setting. Help me understand though, what's the use case for *not* trimming here? I'm struggling to think of one. But there are drawbacks, like whitespace masking a populated state, unintended and inevitable leading/trailing whitespace getting visually converted to newlines in output, etc.

**Comment by adrianbj** [comment]
The reason this came up for me was with this module: http://modules.processwire.com/modules/process-file-edit/

It uses an inputfield textarea as the container for a codemirror code editor. The problem is that any leading/trailing blank lines are removed which shouldn't really be a problem accept that if I want blank lines they shouldn't be removed automatically. It was also messing with links directly to a specific line because once loaded, the line number would change. The module has been changed to use a manual `<textarea>` so it's not an issue with that module anymore.

Agreed this is an unusual case, but I think the key thing is that in general I think I should be able to decide if I want these lines or not. I don't think it should be forced. I think an option to preserve would be great.

**Comment by netcarver** [comment]
@ryancramerdesign How about making the trim an 'on-by-default' option for textareas? If anyone doesn't need it - for those special cases - it can be disabled.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.

**Comment by ryancramerdesign** [comment]
@netcarver @adrianbj I have added support for this via a `noTrim` option in InputfieldText.module. If you set the `$inputfield->noTrim = true;` it will skip trimming whitespace from the value.

**Comment by adrianbj** [comment]
Sounds good - thanks @ryancramerdesign
