### ISSUE TITLE
Module randomly not found from Modules.php

### ISSUE THREAD

**Issue by 14pixels** [processwire/processwire-issues#46]
### Short description of the issue

I have encountered a problem that randomly after a deploy some modules are not available. It happens randomly, and to different modules. Clearing the FileCompiler Cache does not help in this case, after a redeployment the error is gone most of the time.
The module from the screenshot is inheriting the FieldtypeFile module and is adding some additional meta fields to the file and is hooking on file save and uploads the file to amazon s3.
The bug only occurs when PW is trying to access, when i ssh to the instance i can see and open the files.
The module has the namespace ProcessWire.

### Expected behavior

Find all modules after deployment

### Actual behavior

Sometimes a module is not found after deployment

### Optional: Screenshots/Links that demonstrate the issue

![module_error](https://cloud.githubusercontent.com/assets/7264755/19376948/97675004-91e2-11e6-9e6a-e9cb51f53374.png)

### Steps to reproduce the issue

1. Deploy application to an AWS Elastic Beanstalk application (i dont know if thats relevant for this bug to happen, but thats what we use for hosting) 
2. Bug happens randomly

### Setup/Environment

* ProcessWire version: 3.0.35
* PHP version: PHP 5.6
* MySQL version: MySQL 5.6.23

**Comment by ryancramerdesign** [comment]
Could I get a look at the FieldtypeZZFile.module file? If you'd like you can PM to me in the forums (user "ryan") or by email send it to me at ryan at rc-d dot net.

**Comment by ryancramerdesign** [comment]
Not heard back on this one, so going to close the report, but please re-open if still able to duplicate and can send the file for me to check out.
