### ISSUE TITLE
PageArray::each() method inconsistent with checkbox field output

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#460]
Best to explain with a simple code example:

```
// this outputs the actual checkbox form field markup -- incorrect?
echo $pages->find($q)->each(function($child) {
  return "{some_checkbox_field}";
});

// this outputs the checkbox field value "1" if the checkbox is checked -- correct
echo $pages->find($q)->each(function($child) {
  return "{$child->some_checkbox_field}";
});
```

PW 3.0.84

**Comment by ryancramerdesign** [comment]
That's the correct output. It should be a disabled checkbox, so not one that could actually be used for input, but one that just simply represents the checked (or non-checked) value in markup. When you specify a field name in brackets like that, you are asking for the markup value of the field. Often times this is the same thing as the regular value, but not always. Your example makes it pass through the Fieldtype::markupValue(), which attempts to come up with the most direct way to represent the value in markup. 

The brackets that you are using in your second example are just a PHP language construct, and not actually necessary in that example. Those brackets are never seen by ProcessWire, as they are a signal to the PHP compiler. You don't need to do that unless your string lacks whitespace between the variable and whatever is next to it, or if you need to represent nested variables more than 2 levels, i.e. : `"$a->b->c"` wouldn't work in a string unless it was `"{$a->b->c}"`. However, it's not necessary for `"$a"` or `"$a->b"`.

**Comment by netcarver** [comment]
@jlahijani Hi Jonathan. I know this is an older issue, but does Ryan's comment above resolve it for you?
