### ISSUE TITLE
ListerPro "Config" tab not working when using UiKit

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#461]
### Short description of the issue

It works when using the default theme, but with UIkit clicking on the config tab does nothing.
![image](https://user-images.githubusercontent.com/370148/34299286-6cae5d62-e722-11e7-9316-b6be9c9d513f.png)

* ProcessWire version: 3.0.86

**Comment by gmclelland** [comment]
I'm not seeing any problems here.  When I click on the "Config" tab it does a redirect to a page with the lister's configuration.  However, I'm on 3.0.87.

**Comment by somatonic** [comment]
![2018-03-27 13 13 57](https://user-images.githubusercontent.com/370148/37964221-03930b90-31c1-11e8-8074-bdb7e6ed52e0.gif)

Still this issue persists in latest. All vanilla install....

**Comment by ryancramerdesign** [comment]
What is your ListerPro version? Using 1.1.1 here with PW 3.0.96 and config tab seems to be working fine. Also double check that you are using the core version of AdminThemeUikit, and not one in /site/modules/.

**Comment by somatonic** [comment]
It's working again with lister 1.1.1. (PW3.0.98)
