### ISSUE TITLE
Client-side image resizing prevents upload of file types the resizer cannot handle

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#466]
### Short description of the issue

When max width and height is defined for an images field and "Use client-side resize where possible" is selected, image upload fails for image file types that the client-side resizer cannot handle (i.e. all image types apart from 'jpeg', 'png' and 'gif'). The result is an endless spinner on the image thumbnail. No error messages are displayed, in admin or in the browser console.

When client-side resizing is not enabled the images may be uploaded successfully (although of course the ImageSizer may not be able to work with them).

In case you are wondering why I am trying to upload unsupported image file types to an images field - I am developing a module for working with these file types.

### Expected behavior

Client-side resizer skips image types it cannot handle.

### Actual behavior

Image is not uploaded and endless spinner occurs.

### Optional: Suggestion for a possible fix

I had a go at debugging this but wasn't able to determine exactly where the problem lies. It seems that the `onload` event never fires for the `img` object [here](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Inputfield/InputfieldImage/PWImageResizer.js#L102).

The resizer is supposed to skip unsupported image types [here](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Inputfield/InputfieldImage/PWImageResizer.js#L151-L153). Perhaps this test could be applied earlier (somewhere around [here](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L1646)) so the client-side resizer doesn't need to get involved at all?

### Steps to reproduce the issue

1. Define min and max width settings for an images field.
2. Make sure the "Use client-side resize where possible" setting is selected.
3. Add a file format that the client-side resizer does not support to "Valid file extensions" (e.g. tiff)
4. Attempt to upload a TIFF file to the images field.

### Setup/Environment

* ProcessWire version: 3.0.88
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Regarding the suggested line you mentioned [here](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L1646)… 
~~~~~~
if($useClientResize) {
~~~~~~
…would updating it to the following resolve the issue you are seeing?
~~~~~
var ext = file.name.substring(file.name.lastIndexOf('.')+1).toLowerCase();
if(useClientResize && (ext == 'jpg' || ext == 'jpeg' || ext == 'png' || ext == 'gif')) {
~~~~~
Another option could be to check the `file.type` property (content-type), but I don't know all of the possible variations that might be present to check for that. Might be as simple as image/jpeg, image/png and image/gif, but would need to research and double check that.

**Comment by Toutouwai** [comment]
> would updating it to the following resolve the issue you are seeing?

Yes, that fixes it, thanks.

**Comment by Toutouwai** [comment]
Thanks for the fix.
