### ISSUE TITLE
PaginatedArray 'getPaginationString()' method shows incorrect page number (when $usePageNum param is set)

### ISSUE THREAD

**Issue by lmdade** [processwire/processwire-issues#467]
### Short description of the issue

When using a PaginatedArray, the method 'getPaginationString()' returns an incorrect page number. It always displays as '0 of N' (where 'N' is the total number pages).

### Expected behavior

For a paginated array consisting of six pages (for example), the following code should display the text "Page n of 6" ("Page 1 of 6" and so on) on each paginated page.

`$myArray->getPaginationString('Page', true)`

**Note:** the '$usePageNum' param is set to true to display page number instead of number of items)

### Actual behavior

Instead it displays "**Page 0 of 6**" for every page.

Note: the actual pagination is working correctly, as is setting $usePageNum to false (default behaviour) to display number of items instead (e.g, "items 1 to 20 of 104").

### Optional: Suggestion for a possible fix

The problem is caused by an incorrect pattern in the PHP sprintf() function used in the method, so a fix is very simple.

The problem (line [206](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/core/PaginatedArray.php#L206) (master and dev branches, link is to dev)
`$str = sprintf($this->_('%1$s %1$d of %2$d'), $label, $pageNum, $totalPages); // Page quantity, i.e. Page 1 of 3`

The numbering of the replacement arguments is incorrect.

It needs to be changed to:
`$str = sprintf($this->_('%1$s %2$d of %3$d'), $label, $pageNum, $totalPages); // Page quantity, i.e. Page 1 of 3`

Making this change to the core file on my own installation of PW fixed the issue.

### Steps to reproduce the issue

1. Create a paginated array in a template file
2. Output the result of `$array->getPaginationString('Label', true)`

### Setup/Environment

* ProcessWire version: DEV 3.0.88 (but the error also appears in the master branch 3.0.62)
* PHP version: 7.1.8 (running on XAMPP for Windows 7.1.8)

**Comment by ryancramerdesign** [comment]
Thanks @lmdade that's a good find, I've pushed a fix.

**Comment by lmdade** [comment]
Cool, it works as expected now.
