### ISSUE TITLE
Page Auto Complete using "starts with" not working.

### ISSUE THREAD

**Issue by Renobird** [processwire/processwire-issues#468]
On a fresh 3.0.88 install and an older 3.0.76 install if you set a page auto complete field to "^= starts with" the field will always return all possible results, regardless of what you search. I've recreated this on several different installs, across multiple versions.

See screenshots.

![screen shot 2018-01-08 at 3 30 40 pm](https://user-images.githubusercontent.com/121969/34690914-f5ec690c-f488-11e7-861f-6c451020eda3.png)
![screen shot 2018-01-08 at 3 30 53 pm](https://user-images.githubusercontent.com/121969/34690915-f606ec96-f488-11e7-9c3c-bbb321afefff.png)

No matter what you enter in the search, you will always get all the pages returned by findPagesSelector.

**Comment by ryancramerdesign** [comment]
Thanks @Renobird I've pushed a fix for this issue .
