### ISSUE TITLE
wire/config setting maybe misplaced?

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#469]
wire/config.php has this code:

`/**
 * Disable template suggestions when adding new pages?
 *
 * Applies when adding a new page where more than one template may be selected for the newly added page.
 *
 * - true: Always disable template suggestions (forcing user to make selection)
 * - false: Never disable template suggestions (default)
 * - array: Array of template names or IDs where suggestions should be disabled when children are added.
 *
 * @var bool|array
 *
**$config->noSuggestTemplate = false;**
 */
`

is it intended to have that config setting inside of the commented out area? 
  
(current v3 beta)

**Comment by ryancramerdesign** [comment]
That setting was replaced by a `$config->pageAdd` property. I think I must have left it commented for reference, but no need to have it anymore—I'll remove it. Thanks.
