### ISSUE TITLE
Notices when using copy page list action on a page with no children (hence ajax copy mode)

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#47]
### Short description of the issue

I get these notices when the copy uses the ajax copy mode.

![screen shot 2016-10-14 at 8 56 40 pm](https://cloud.githubusercontent.com/assets/871211/19407248/ea706632-9250-11e6-8b4c-0e5b262ad959.png)

### Steps to reproduce the issue

1. Click the copy page list action on a page with no children

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by BitPoet** [comment]
This is a problem with ProcessPageClone. The array key to $actions needs to match the name of the action used in the URL, but here in the hook to getExtraActions it assigns $actions['copy'] while the URL path and the hook to processExtraActions use 'clone'. If different names are used, [the condition in ProcessPageListAction](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageList/ProcessPageListActions.php#L205) can't find the action name in $actions, leaving the variables undefined.

**Comment by adrianbj** [comment]
Thanks @BitPoet for investigating - I was in the middle of something and didn't want to get too distracted!

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.
