### ISSUE TITLE
PageFrontEdit (Front-End Page Editor) Module XSS Vulnerability

### ISSUE THREAD

**Issue by lkarinja** [processwire/processwire-issues#470]
### Short description of the issue

The PageFrontEdit module is vulnerable to Cross-Site Scripting attacks via modifying any field in either the front-end or back-end.

### Expected behavior

Adding, for instance, a `<script>` tag in either the front-end or back-end field editor should properly escape the string and not treat it as a tag when loading the page in the front-end.

### Actual behavior

Adding a `<script>` tag in either the front-end or back-end field editor causes the script to be run in the front-end when viewing the page, even when HTML Entity Encoder is added to the field in the back-end for regular text.

### Suggestion for a possible fix

Sanitize all fields before pushing to the front-end, specifically in the `div class=pw-edit-copy`

### Steps to reproduce the issue

1. Install the PageFrontEdit module in the back-end
2. Under configuration, allow the editing of any fields in the front-end
3. In either the front-end or back-end, insert a `<script>` tag, such as `<script>alert('XSS in PageFrontEdit');</script>` in the fields allowed for editing set above
4 . Save and View the page in the front-end, and see the script executed

### Setup/Environment

* ProcessWire version: 3.0.62
* PageFrontEdit version: 0.0.2

**Comment by ryancramerdesign** [comment]
Thanks @lkarinja another good find! I've pushed a fix in the referenced commit.
