### ISSUE TITLE
Field Type "Page Title" Not Sanitized in Modal Popup

### ISSUE THREAD

**Issue by lkarinja** [processwire/processwire-issues#471]
### Short description of the issue

Field Type "Page Title" is not sanitized properly when being displayed in the Modal Popup view option in the back-end. This allows tags such as `<script>` to be inserted and executed when viewing the Modal Popup.

### Expected behavior

Tags should be sanitized properly for the Modal Popup, disallowing tags like `<script>` to be executed.

### Actual behavior

Tags are not sanitized, and therefore certain tags such as `<script>` are executed when viewing the Modal Popup for a page in the back-end.

### Suggestion for a possible fix

Sanitize the Page Title when viewing the page in Modal Popup in the back-end.

### Steps to reproduce the issue

1. While editing the page in the back-end, insert a script in the Page Title
2. Save the page and view the page by Modal Popup in the back-end
3. The tag will be parsed and something like a `<script>` tag will be executed

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by Toutouwai** [comment]
Not sure I understand this issue. When you choose View > Modal Popup from the page editor you are viewing the front-end of your site inside an iframe. How content is output of the front-end is the responsibility of the developer - the developer should ensure that all text fields have the HTML Entity Encoder textformatter applied.

The Page Title field is a pre-installed field and the HTML Entity Encoder is active on this field by default, so output should be encoded unless the developer has specifically removed this textformatter.

**Comment by lkarinja** [comment]
@Toutouwai HTML Entity Encoder IS active. This is an issue on how the Page Title is being displayed in the iframe with Modal Popup, resulting in tags being executed rather than parsed as text.

**Comment by ryancramerdesign** [comment]
Thanks lkarinja and Toutouwai, I have pushed a fix for this issue in the referenced commit.
