### ISSUE TITLE
Field Option "Label" Not Sanitized in Template Editor

### ISSUE THREAD

**Issue by lkarinja** [processwire/processwire-issues#472]
### Short description of the issue

Field Option "Label" is not sanitized properly in the "Edit Template" page in the back-end. This allows tags such as `<script>` to be inserted and executed when initially saving the edited field option, as well as when expanding the Usage list. This may be related to #471

### Expected behavior

Tags should be sanitized properly when editing templates, disallowing tags like `<script>` to be executed.

### Actual behavior

Tags are not sanitized, and therefore certain tags such as `<script>` are executed when viewing areas of the template editor in the back-end.

### Suggestion for a possible fix

Sanitize the field's Label when editing templates in the back-end.

### Steps to reproduce the issue

1. Edit a Field directly from the template editor
2. Insert a `<script>` in the option for a Label for the field
3. The script should be executed after saving the field, as well as when Usage is checked for the template

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks lkarinja, good find—I have pushed a fix for this issue in the referenced commit.
