### ISSUE TITLE
FieldtypeOptions::addOptions() argument incompatible with SelectableOptionManager::addOptions()

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#473]
### Short description of the issue

The second argument supplied to [FieldtypeOptions::addOptions()](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Fieldtype/FieldtypeOptions/FieldtypeOptions.module#L494-L505) must be a SelectableOptionsArray. This method then passes that argument to [SelectableOptionManager::addOptions()](https://github.com/processwire/processwire/blob/f3749d241a5f4da4d9df3731d1b99d001eaf0f50/wire/modules/Fieldtype/FieldtypeOptions/SelectableOptionManager.php#L636-L644).

This causes a type error because that method has a type declaration of `array` for its second argument.

> TypeError: Argument 2 passed to ProcessWire\SelectableOptionManager::addOptions() must be of the type array, object given, called in ...\wire\modules\Fieldtype\FieldtypeOptions\FieldtypeOptions.module on line 504

### Setup/Environment

* ProcessWire version: 3.0.88

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks!
