### ISSUE TITLE
Editing of roles unsets permissions

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#474]
### Short description of the issue
For templates the guest user has no view permission, permissions for these templates get unset for another role if this role is being edited and saved. I had a lot of templates which had no view access for guest (intranet) and killed unintentionally all my view permissions for the other roles  :(

### Expected behavior
Permissions should stick, should not get overwritten.

### Steps to reproduce the issue
1. Create a new template
2. Create a new role, for example with name "testrole".
3. Disable guest view access for template in template's settings. Enable view access for testrole.
4. Head over to masthead -> Permissions -> User roles -> testrole
5. See that page-view is disabled for testrole. If you enable the permission again and save, it doesn't stick.

### Setup/Environment
* ProcessWire version: 3.0.88

**Comment by ryancramerdesign** [comment]
Thanks @processwired and @godmok I've pushed a fix for this issue. Please let me know if you continue to observe any errors with this. Thanks.

**Comment by godmok** [comment]
Hi @ryancramerdesign , the first part was fixed, normal templates do not loose the permission, but the FieldsetPage Template is loosing it again:
![image](https://user-images.githubusercontent.com/1888579/35500489-eb4ba3ec-04d6-11e8-8cec-c4da1ea9818f.png)

**Comment by ryancramerdesign** [comment]
@godmok Repeater templates shouldn't come into play here since they inherit the access control settings of their owning page. But if you've enabled access control on them yourself, I think that might cause the error you are seeing here. I've just pushed an update that should detect this and avoid removing those permissions. Please let me know if you continue to see any errors. Thanks.

**Comment by godmok** [comment]
Hi @ryancramerdesign, it is working now. Sorry for the very long delay.
