### ISSUE TITLE
Multiple allowed templates for users: can't create new user if creating user != superuser

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#475]
### Short description of the issue
It's a more advanced setup: if $config->userTemplateIDs is set with some template ids assigned, and superuser creates new users with these templates, all is well. If a user, which has user create permission, creates a new user, a fatal error ocurrs after submission of the new user creation page.

### Actual behavior
Error message is:
`Catchable fatal error: Argument 2 passed to ProcessWire\ProcessUser::checkSaveRoles() must be an instance of ProcessWire\User, instance of ProcessWire\Page given, called in /wire/modules/Process/ProcessUser/ProcessUser.module on line 356 and defined in /wire/modules/Process/ProcessUser/ProcessUser.module on line 368`

### Optional: Suggestion for a possible fix
In ProcessUser.module is a checkSaveRoles() method and a checkSaveUserAdminAll() method, which both get the wrong type hinting.  Currently, it's set to:
Line 368: checkSaveRoles(User $user, User $page)
Line 414: checkSaveUserAdminAll(User $user, User $page)

I think more correct would be:
checkSaveRoles(User $user, Page $page)
checkSaveUserAdminAll(User $user, Page $page)

I have fixed my local setup like this and it works well now.

### Steps to reproduce the issue
1. Create an additional user template with, for example, template id = 4
2. Set $config->userTemplateIDs = [3, 4] in /site/config.php
3. As a superuser, create a new user. Give the new user create user permission.
4. Log in as the new user. Try to create a new user: error message appears. 

### Setup/Environment

* ProcessWire version: 3.0.88

**Comment by chriswthomson** [comment]
Hi,

I'm also getting this error but I don't think my setup is as complex as you've stated.

I have an extra user role, admin, which has user-admin permissions (and page-view, some page-edit). The admin role can edit users without an issue, but when I try to add a user I get the error reported here.

This happens when I click Save on the initial username screen. I do have an extra field on the User Template - title, with a custom label - and this also appears on this initial screen.

I tried assigning Edit/Create permissions to admin on the User template but this had no effect.

Running 3.0.88, superuser can create users without any problems.

Cheers,

Chris

**Comment by processwired** [comment]
Thanks, may I encourage you to try out the fix I posted above? I did not find any glitches with it so far. Sure, I would prefer not to fiddle around with the core, but as long as Ryan does not find some time to fix it, there is no way around that. I freezed the involved project to 3.0.88 and don't do any updates until the issue is fixed - I think Ryan will fix it as soon as he has finished the really important things in life. Thanks for all Ryan - can't say that often enough. :)

**Comment by chriswthomson** [comment]
Hi,

Just finishing up for the day so won't get to try it out until next week but I think your fix is correct, just wanted to add that it was happening on a less complex setup too.

Cheers,

Chris

**Comment by lesaff** [comment]
@processwired, thanks for the suggestion. I had the same issue and it fixed it. 👍

**Comment by ryancramerdesign** [comment]
Thanks @processwired I've pushed your suggested fix for this issue.
