### ISSUE TITLE
Cloning a page with a Table field give an integrity constraint violation error

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#48]
### Short description of the issue

Sorry, maybe this should be posted in the Table support thread, but it's the core Copy action that triggers, so went with here. 

### Expected behavior

No error

### Actual behavior

Error saving field "cc_emails" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'

None of the rows from the Table field are copied to the new page.

### Steps to reproduce the issue

1. Click the copy page list action button on a page that has a table field

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I actually ran into the same issue recently and turned out that Table just didn't support cloning yet, but this is actually fixed in my dev copy (along with other things), so I'll release that soon.
