### ISSUE TITLE
Copy page with FieldsetPage has empty content in copy

### ISSUE THREAD

**Issue by godmok** [processwire/processwire-issues#481]
### Short description of the issue

Copy a page with a FieldsetPage field will not copy the content from the original FieldsetPage field.

### Expected behavior

Content from all fields is set with the original content.

### Actual behavior

Content from FieldsetPage fields is empty.

### Steps to reproduce the issue

1. Create FieldsetPage field with a ckeditor body field, page reference field, normal textfield, repeater, etc.
2. Create a page with the FieldsetPage field inside.
3. Install Page Clone module from core
4. Clone the created page
5. Check content from the copied page -> FieldsetPage field is empty

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.88
* (Optional) PHP version: 7.0
* (Optional) MySQL version: 5.7

**Comment by ryancramerdesign** [comment]
Thanks @godmok I've just pushed a fix for this issue. It's in the latest commit (I forgot to tag the issue number so that it would link here).

**Comment by netcarver** [comment]
@godmok Hello. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.

**Comment by godmok** [comment]
Hi @netcarver, looks like the problem is solved on my site. The Problem is fixed and the issue can be closed.
