### ISSUE TITLE
PageFrontEdit not detecting field="pageid.fieldname" syntax correctly, throws error

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#484]
### Short description of the issue

In PageFrontEdit, when you use edit tags, the syntax (option C)
`<edit field="pageid.fieldname">`
is not detected.

In debug mode, the error

> Argument 1 passed to PageFrontEdit::inlineSupported() must be an instance of Field, null given, called in C:\inetpub\wwwroot\intranet\wire\modules\Page\PageFrontEdit\PageFrontEdit.module on line 527

is shown because pageid.fieldname in $name don't get split into pageID and name variables and the combination value is passed to `$this->wire('fields')->get()` in line [524](https://github.com/processwire/processwire/blob/dev/wire/modules/Page/PageFrontEdit/PageFrontEdit.module#L524).

### Suggestion for a possible fix

The detection starting at line [495](https://github.com/processwire/processwire/blob/dev/wire/modules/Page/PageFrontEdit/PageFrontEdit.module#L495) needs to be moved outside of the surrounding if. 

```php
			foreach($attrs as $attr) {
				$attr = trim($attr);
				if(empty($attr)) continue;
				if(strpos($attr, '=') !== false) {
					list($attrName, $attrValue) = explode('=', $attr);
					$attrName = trim($attrName, ' ');
					$attrValue = trim($attrValue, ' "\'');
					if(in_array($attrName, array('name', 'names', 'field', 'fields'))) {
						$names = $attrValue;
					} else if($attrName == 'page') {
						$pageID = $attrValue;
					}
				} else if(empty($names)) {
					$names = $attr;
				}
				// This was moved outside the above else if(empty($names))...
				if(strpos($names, ':') !== false) {
					list($pageID, $names) = explode(':', $names);
				} else if(strpos($names, '.') !== false) {
					list($pageID, $names) = explode('.', $names);
				}
			}
```

### Steps to reproduce the issue
1. Enable PageFrontEdit
2. Surround the output of a page field in a template with `<edit field='{$page->id}.fieldname'>...</edit>`
3. Visit page on frontend

**Comment by ryancramerdesign** [comment]
Thanks @BitPoet that's some good debugging work there. I've pushed the suggested fix.

**Comment by BitPoet** [comment]
Thanks!
