### ISSUE TITLE
PageArray $array->add() and $array->remove() not consistent

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#486]
### Inconsistent behaviour of PageArray

A PageArray field does not act consistent when adding and removing items. using `$field->add(123);` with an Page ID works, but removing the item `$field->remove(123);` does not remove this item.

### Expected behavior

```
$page->pagerelation->add(1029); // adds page with the id 1029
$page->pagerelation->remove(1029); // does not remove page with the id 1029
```

### Actual behavior

Removing the page needs an instance:

```
$page->pagerelation->add(1029); // adds page with the id 1029
$page->pagerelation->remove($pages->get(1029)) // removes page 1029 from PageArray
```

### Optional: Suggestion for a possible fix

Check if there is a $key with the id and if not present, check if there is an object with the id.

### Setup/Environment
<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.89 <br />
PHP: 7.0.17-2+deb.sury.org~trusty+1 <br />
Webserver: Apache/2.4.7 (Ubuntu) <br />
MySQL: 5.5.54-0ubuntu0.14.04.1 <br />
</details>
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 600 <br />
max_input_vars: 1000 <br />
memory_limit: 512M <br />
post_max_size: 500M <br />
upload_max_filesize: 300M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: 2.2.3 <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.7.6 <br />
AdminPageFieldEditLinks: 3.1.0 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FrontEndEditLightbox: 1.3.6 <br />
IcfActionFieldManipulation: 0.0.1 <br />
IcfActionSendMail: 0.0.1 <br />
IcfActionTest: 0.0.1 <br />
IcfUtil: 0.0.1 <br />
IftRunner: 0.1.7 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
Oauth2Login: 0.1.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessIft: 0.1.6 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.1.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.9.8 <br />
WireMailMandrill: 0.0.1 <br />
</details>

**Comment by Toutouwai** [comment]
I think you may be mixing up WireArray and PageArray methods.

There is [WireArray::add()](https://processwire.com/api/ref/wire-array/add/) and [WireArray::remove()](https://processwire.com/api/ref/wire-array/remove/).

Then there is [PageArray::add()](https://processwire.com/api/ref/page-array/add/), which is the method that accepts a page ID as an argument. There is no PageArray::remove() method.

The API docs for all these methods describe the arguments that may be used. So not sure this is a bug at all - maybe more a feature request for a new method PageArray::remove()?

**Comment by ryancramerdesign** [comment]
This would be specific to PageArray rather than WireArray (like @Toutouwai mentioned). I don't think we can support a page ID for the remove() method because the context of something already in a PageArray is different from something outside of it— add() and remove() are different contexts. The remove() method accepts either the Page instance, or the index of the page in the array (integer). An index only becomes applicable once an item is already in the array. An index and a page ID are both integers, so remove() can't support both. The ability for the add() method to accept an ID is for the convenience of loading functions, like in FieldtypePage or similar, to reduce the steps needed to construct a PageArray, where you don't already have the Page instances loaded. What I could support with the remove()  method is a selector string, like "id=123", if that would be helpful?

**Comment by noelboss** [comment]
Sorry, I actually confused WireArray with PageArray – The field I'm talking about is a PageArray field. 

so $PageArrayField->add() does accept an ID, but $PageArrayField->remove() not…

**Comment by netcarver** [comment]
@noelboss Is this still an issue?

**Comment by netcarver** [comment]
Closing as this has gone cold. @noelboss Post more if needed and it can be reviewed. Thank you!
