### ISSUE TITLE
Non-default language description not retained when replacing image

### ISSUE THREAD

**Issue by rdunk** [processwire/processwire-issues#489]
### Short description of the issue

When replacing an image asset in an image field, non-default language description field values are not retained.

### Expected behavior

The non-default language description field should retain its value.

### Actual behavior

The non-default language description field value is cleared.

### Optional: Suggestion for a possible fix

I suspect it might be that PW saves new description fields when the image is replaced, but somehow the secondary language value isn't being passed correctly. I've tried logging the value at various points in the Pagefile and InputfieldFile and can't find the point at which the value disappears.

### Steps to reproduce the issue

1. Create a new image field with a multilingual description and max images set to 1.
2. Upload an image and set descriptions for both the default language and secondary language(s).
3. Save the page.
4. Replace the current image via drag-and-drop.
5. The non-default language description field will now be blank, but the default language retained.

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks @rdunk I've pushed a fix for this issue.

**Comment by rdunk** [comment]
Much appreciated @ryancramerdesign.

**Comment by netcarver** [comment]
@rdunk Hi Rupert, could you close this issue now as it appears to be resolved to your satisfaction. Thank you!

**Comment by rdunk** [comment]
Apologies, closed and thanks once again!
