### ISSUE TITLE
Locked pagefield loading all selectable pages

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#49]
### Short description of the issue

A locked pagefield seems to still load all possible pages in the PageEditor, even though only the selected one should be displayed.
### Expected behavior

Show the selected page without issue.
### Actual behavior

I've an installation with ~9000 users, which started to time out on editing any registration page. Hiding the page field, where the corresponding user is selected,  from the editing form resolved the issue, while "Open when populated, …, Locked" as visibility did initiate the timeout. 
### Steps to reproduce the issue

1. Have a page field with a large number of selectable pages.
2. Add it to a template and set the visibility to "Open when populated, Closed when empty, Locked"
3. Try to edit a page of that template.
### Setup/Environment

- ProcessWire version: 3.0.30
- (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix for this issue.
