### ISSUE TITLE
Cloning FieldsetOpen doesn't clone END field

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#491]
### Short description of the issue

When you clone a FieldsetOpen field, the corresponding FieldsetClose field isn't created.

### Expected behavior

Since deleting and adding fields in the backend also affects FieldsetClose fields, the same should be true for cloning.

### Optional: Suggestion for a possible fix

Creation of the corresponding close field happens through a hook to ProcessField::fieldAdded, but that isn't triggered when cloning a field. This could be fixed by adding two lines starting at [Line 1658 of ProcessFields.module](https://github.com/processwire/processwire/blob/f573473066592b587f4d30ed2652a7132f11e014/wire/modules/Process/ProcessField/ProcessField.module#L1658):

```php
						$clone->set('closeFieldID', null);
						$this->fieldAdded($clone);
```

Since closeFieldID is copied, it has to be nulled so the hook in FieldtypeFieldsetOpen creates the closing field.

### Setup/Environment
* ProcessWire version: 3.0.90

**Comment by ryancramerdesign** [comment]
Thanks, I have added your suggestion here and it seems to work well.

**Comment by BitPoet** [comment]
Thank you Ryan!
