### ISSUE TITLE
Maximum function nesting level of '1000' reached

### ISSUE THREAD

**Issue by anilex** [processwire/processwire-issues#492]
### Short description of the issue

When trying to edit one of the pages on a fresh install:
`Fatal error: Maximum function nesting level of '1000' reached ..`

xdebug nesting level to 1000. Without xdebug - the max memory reached regardless the size. 

The same setup was fine with an older version of "wire" folder of PW. Can't say how older. 

### Expected behavior

To edit the page in the CMS as usual. 

### Actual behavior

`Fatal error: Maximum function nesting level of '1000' reached,`

### Optional: Screenshots/Links that demonstrate the issue

```
​Fatal error: Maximum function nesting level of '1000' reached, aborting! in /xxx/app/wire/core/WireData.php on line 170
Fatal error: Maximum function nesting level of '1000' reached, aborting! in /xxx/app/wire/core/WireShutdown.php on line 66
```

### Steps to reproduce the issue

Fresh install of the site-languages profile. Other languages deleted. First time trying to edit the "about" page. 

### Setup/Environment
* Apache 2.4
* ProcessWire version: 3.0.91 (dev branch)
* PHP version: 7.1 
* fresh install, "site-languages" profile. 
* xdebug nesting level to 1000. Without xdebug - the max memory reached regardless the size. 

ref: [https://processwire.com/talk/topic/339-urgent-matter-fatal-error-maximum-function-nesting-level-of-100-reached/](https://processwire.com/talk/topic/339-urgent-matter-fatal-error-maximum-function-nesting-level-of-100-reached/)

**Comment by ryancramerdesign** [comment]
I couldn't duplicate this one the first time, but this morning tried again and was able to. The issue is now fixed. Thanks.

**Comment by anilex** [comment]
Yes, it's fixed. 
Many thanks!
