### ISSUE TITLE
Can't save image field inside FieldtypeFieldsetPage

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#493]
### Short description of the issue
When i try to save images, getting error (images field inside FieldtypeFieldsetPage field)
`
Can't save field from page 1053: /processwire/repeaters/for-field-155/for-page-1/: Call $page->of(false); before getting/setting values that will be modified and saved. [Page::statusCorrupted] fields: images
`
### Setup/Environment

* ProcessWire version: 3.0.91
* (Optional) PHP version: 7.2 (also tested on 7.1)
* (Optional) MySQL version: 10.2.12-MariaDB

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Is there any setup necessary or steps to take to duplicate? When I drag a photo into an images field in my FieldsetPage field, it uploads normally and saves normally when I Save the page. What 3rd party modules are present?

**Comment by trk** [comment]
I am also choosing files for upload. I tested same images field outside of FieldtypePage, its working.
I deleted old FieldtypePage field and re-created it, i have same error.

I will duplicate current dev site for make test without modules and let you know about test results.

Modules:
- Modalception
-  AvbHelper (private module)
- Components (private module)
- Fieldtype Dynamic Fields Data (private module)
- E-Mail (Multi-language)
- URL (Multi-language)
- Database Backups
- Hanna Code
- FieldtypeFontIconPicker
- Map Marker
- Custom Upload Names
- Google Analytics
- Tracy Debugger

**Comment by trk** [comment]
Its look like my private module breaks uploading, sorry for take your time. :(
