### ISSUE TITLE
FieldsetTab Description and Notes not displaying

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#494]
### Short description of the issue

The Description and Notes don't display in a FieldsetTab

I think it would be nice if this worked to provide general instructions for a tab of fields.
### Expected behavior

They should display

### Actual behavior

The option to enter them is there, but they aren't output.

**Comment by ryancramerdesign** [comment]
InputfieldFieldsetTabOpen is an InputfieldWrapper, which is an invisible container for Inputfields. It's not intended to display description or notes. I suppose ProcessPageEdit could use description as a title attribute on the tab that you click? (browser tooltip)

**Comment by adrianbj** [comment]
> It's not intended to display description or notes.

Is there any reason this behavior couldn't be changed to match a normal fieldset where the description and notes do display?

If for some reason this isn't possible, I think the description and notes options when setting up a fieldsettab need to be disabled to avoid confusion.

Thanks for the thought, but I don't think a tab title tooltip is much use.

The current workaround as I see it is to either create an InputfieldMarkup inside the tab, or a normal fieldset inside the fieldsetTab which can then be used to display description/notes for the entire tab of fields.

**Comment by arjenblokzijl** [comment]
> If for some reason this isn't possible, I think the description and notes options when setting up a fieldsettab need to be disabled to avoid confusion.

I've ran into this several times as well. It would be nice if we can't use them they should not be visible to avoid confusion.

**Comment by teppokoivula** [comment]
> Thanks for the thought, but I don't think a tab title tooltip is much use.
> 
> The current workaround as I see it is to either create an InputfieldMarkup inside the tab, or a normal fieldset inside the fieldsetTab which can then be used to display description/notes for the entire tab of fields.

This is why it'd be nice to have a FieldsetTab description, and perhaps the notes as well, visible. It's a rather common need for me/us to document what you'll find within a specific FieldsetTab, but currently it requires going through some unnecessary hoops.

While InputfieldMarkup has been my go-to approach for solving this in modules, you can't use that on regular Pages, so you're basically left with just the "Fieldset inside FieldsetTab" option, which not only feels a bit weird, but also makes the UI less clean.

**Comment by netcarver** [comment]
@ryancramerdesign Any further thoughts on this?

**Comment by ryancramerdesign** [comment]
@netcarver It looks like I can support this, at least in ProcessPageEdit, but it's not pretty. None of the admin themes have needed styles for this before, so it looks pretty out of place. All of the admin themes will need to be updated to support it, so I think I'll return to this one a little later. However, that's just for the description. The "notes" part seems to work/look fine, so will enable that one now. However, notes also isn't particularly useful here, but if it's populated we might as well display it.

**Comment by netcarver** [comment]
Right, I'll leave this open for now. Setting a reminder for 2 weeks.

/remind me to review this issue in 2 weeks

**Comment by ryancramerdesign** [comment]
@netcarver Maybe this one can be moved to requests repo?
