### ISSUE TITLE
Word counter: maxlength not displayed when textarea empty

### ISSUE THREAD

**Issue by sarmoh** [processwire/processwire-issues#495]
### Short description of the issue

Word counter does not display maxlength, when nothing is entered yet.

### Expected behavior

Word counter displays maxlength, even before characters are entered into the field

### Actual behavior

Word counter appears only after the first character is entered into the field (and disappears once all characters in the field are deleted)

### Optional: Suggestion for a possible fix

InputfieldTextLength.js, line 92:
```
				} else if(len > 0 && !hasError) {
```
replace it with
```
				} else if(len >= 0 && !hasError) {
```

### Steps to reproduce the issue

1. Create a field with a maxlength and a word-counter
2. Add it to a template
3. Create a page with that template
4. See that the maxlength is not displayed, enter a character into the field and see the maxlength

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks, I have applied your suggestion to that file.

**Comment by netcarver** [comment]
@sarmoh If Ryan's fix solves this for you, please could you close this issue. Many thanks!
