### ISSUE TITLE
$process->logout() send warning

### ISSUE THREAD

**Issue by smbdelse** [processwire/processwire-issues#497]
### Short description of the issue

Problem might be related to 3rd party modules, as I use PW as headless API provider (with [ProcessGraphQL](https://github.com/dadish/ProcessGraphQL)). But I discovered that simple change in PW core file: Session.php might fix(?) the problem.

### Expected behavior

Successful logout without warnings

### Actual behavior
It's Vue js app, with Apollo on top of  Processwire with ProcessGraphQL
All queries works well but after logging in, when I send [logout()](https://github.com/dadish/ProcessGraphQL/blob/958389136f8237e2c9456a9b9e9a2875e11c2c9e/src/Field/Auth/LogoutField.php#L32), I get warning in response header:

`Warning: session_destroy(): Session object destruction failed in [PWpath]\wire\core\Session.php on line 950`

### Suggestion for a possible fix

[Here](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/Session.php#L913), after changing:
```
		if($startNew) {
			session_destroy();
			session_name($sessionName);
			$this->init();
			session_regenerate_id(true);
			$_SESSION[$this->sessionKey] = array();
		}
```
to:
```
		if($startNew) {
			session_regenerate_id();
			session_destroy();
			session_name($sessionName);
			$this->init();
			session_regenerate_id(true);
			$_SESSION[$this->sessionKey] = array();
		}
```
Everything seems to work fine

### Setup/Environment
Processwire is running as API provider on local WAMP server and is set to virtual host xyz.prv
ProcessGraphQL endpoint is exposed under xyz.prv/graphql
Vue js with Apollo are run by Webpack server and are set to xyz.prv:8080, also to avoid cross origin problems there is proxy set for xyz.prv/graphql in webpack server config

* ProcessWire version: 3.0.87
* 3rd party modules that are installed and could be related to the issue: Vue.js on top of ProcessGraphQL

**Comment by ryancramerdesign** [comment]
Nice work on tracking down what prevents the warning from appearing. But I'm not sure I understand why the warning was appearing in the first place, or why the extra session_regenerate_id(); before the session_destroy(); prevents the warning? Any idea why? I like to understand these things fully before implementing because there's always possibility for unintended side effects or breaking something else as a result. Also curious if you see any other issues beyond the warning message (i.e. would simply suppressing the warning message have the same effect?). Thanks.

**Comment by smbdelse** [comment]
I agree It need a lot of precaution to push this kind of change. I currently don't have much time to spend on this project, but I'll try to catch the cause of those problems as soon as I can. I'll also ping author of GraphQL module for PW about this, maybe it happens only to me.

**Comment by smbdelse** [comment]
It seems, that it was purely Apollo-related problem. I posted solution in [second thread](https://github.com/dadish/ProcessGraphQL/issues/16#issuecomment-367634362)

**Comment by netcarver** [comment]
@smbdelse Kamil, as that is the case, I'm closing this issue now. Many thanks for your input.
