### ISSUE TITLE
missing translation in ProcessPageEditImageSelect.module

### ISSUE THREAD

**Issue by Manfred62** [processwire/processwire-issues#499]
### Short description of the issue

in the settings of ProcessPageEditImageSelect module the strings in the part of "Skip width attributes on image tags?" aren't translatable (see screenshot). 

Strings can be found in ProcessPageEditImageSelect.module in line **1392** and **1393**

### Expected behavior

make them translatable

### Actual behavior

no possibilty to translate them

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![grafik](https://user-images.githubusercontent.com/5367033/36343394-0ee9df6e-140c-11e8-8c7e-20ecb5776e88.png)

### Setup/Environment

* ProcessWire version: 3.0.92
* (Optional) PHP version: 7.2.2

**Comment by ryancramerdesign** [comment]
Thanks @Manfred62 I've pushed a fix for this issue.
