### ISSUE TITLE
"ProcessWire: ProcessPageEditImageSelect: Page is not editable" when I click variations for image inside repeater

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#5]
> Briefly describe the issue.

Getting "ProcessWire: ProcessPageEditImageSelect: Page is not editable" when i click on "Variations" for image inside repeater for role with minimal permissions.

> What did you expect to happen?

For ProcessWire to show the variations of the image.

> What did actually happen?

Got the error "ProcessWire: ProcessPageEditImageSelect: Page is not editable"

> Optional: Do you have screenshots/links that demonstrate the issue?

![2016-09-26 11_13_02-](https://cloud.githubusercontent.com/assets/11272013/18830800/3fa45440-83da-11e6-8761-b2ba44e89f9c.png)

> What are the steps to reproduce the issue?

1. Create an image field
2. Create a repeater
3. Add image field to repeater
4. Create a template
5. Add repeater to template
6. Create page using template, create repeater item, upload image.
7. Create a role
8. Assign minimal permissions to the role/template that just allow for the creation/editing of content
9. Create a user using the role
10. Log into the user
11. Edit the page
12. Click on the "Variations" button for the image inside the repeater

> Tell us about the setup you experienced the bug in.

* ProcessWire version: 3.0.34

This happens on multiple environments (local, staging, production) which are difference servers

**Comment by isellsoap** [comment]
Thank you for using the issue template. 👍 

I can reproduce this issue and couldn’t get it to work.

[I found a related comment in the forum](https://processwire.com/talk/topic/9724-modules-module-processpageeditimageselect-failed-init/?do=findComment&comment=122998), maybe that can help you?

**Comment by CaelanStewart** [comment]
@isellsoap, well, a template is there to be used, so why not? :p

I reported a similar issue for ProcessWire 3.0.33, except that the error occurred when I clicked on the "crop" button instead. Ryan said he had pushed a fix, which he did, but there is still an error occurring when viewing variations.

I have just quickly set up a test case so you can see the problem for yourself.

[Attached](https://github.com/processwire/processwire-issues/files/493043/test-case.zip), is a zip archive. This archive contains an installation of the latest release of ProcessWire (3.0.34), and a .sql export from phpMyAdmin.

I have already set up the various fields/templates/roles/users.

**Admin Credentials:**
Username: `admin`
Password: `password`

**Client Credentials:**
Username: `client`
Password: `password123!@#`

**Instructions to reproduce:**
1. Get attached PW installation working locally
2. Login with client account
3. Edit `Test Case Page`
4. Open up the repeater item, click 'Edit' on the image thumbnail, and click on the 'Variations' button.

**Comment by CaelanStewart** [comment]
@isellsoap, I somehow misread your saying "I can reproduce this issue" for "I can't..." hehe.

Hehe, seems I didn't need to make the test case!

Never mind.

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix for this issue.

**Comment by isellsoap** [comment]
Fixed with https://github.com/processwire/processwire/commit/835b7ce07d37e73d05e1d8f6563ab3a8fea8b9fd.
