### ISSUE TITLE
Front-End editing of multiple fields of other page not showing all fields

### ISSUE THREAD

**Issue by alexisibmbraga** [processwire/processwire-issues#50]
### Short description of the issue

When specifying multiple fields of an another page than that being rendered in the edit tag, it only appear the first field in the modal window.
the edit tag would have a a syntax like `<div edit="1024.intro,1024.image,1024.events"> ... </div>`

### Expected behavior

It should appear all fields specified in the `<edit>` fields in the modal window.

### Actual behavior

Only first field of the list is present in modal window and behave correctly.

### Optional: Suggestion for a possible fix

None

### Steps to reproduce the issue

1. Step 1 I have the following code 
`<tr edit="1244.priority,1244.startdate,1244.enddate,1244.title,1244.Description,1244.context">
		<td><?= $info->priority ?></td>
		<td><?= $info->title ?></td>
		<td><?= $info->context->title ?></td>
		<td><?= $info->startdate ?></td>
		<td><?= $info->enddate ?></td>
		</tr>`
2. Step 2 double click the row in the table
3. Step 3 the frontend editing modal window appears with only the field 'priority'

### Setup/Environment

Local Apache server 2.4.17
* ProcessWire version: 3.0.35
* (Optional) PHP version: 7.0.3
* (Optional) MySQL version: 5.7
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by Toutouwai** [comment]
I think you only need the page ID prefix for the first field:
`<tr edit="1244.priority,startdate,enddate,title,Description,context">`

**Comment by alexisibmbraga** [comment]
Thanks a lot Toutouwai, your syntax works fine.
