### ISSUE TITLE
PW 3.0.92: $pages->clone() does not work as documented

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#500]
### Short description of the issue
If a page is cloned with $pages->clone(), the title is not set like documented at https://processwire.com/api/ref/pages/clone/

### Expected behavior
Title should be set with first save().

### Steps to reproduce the issue
I installed a fresh PW 3.0.92. I tried with the example from documentation: [https://processwire.com/api/ref/pages/clone/](https://processwire.com/api/ref/pages/clone/)

My source code:
```
<?php

namespace ProcessWire;

include './index.php';

// Clone the Westin Peachtree skyscraper page
// $building = $pages->get('/skyscrapers/atlanta/westin-peachtree/');
$building = $pages->get(1015);
$copy = $pages->clone($building);

// Bonus: Now that the clone exists, lets move and rename it
// $copy->parent = '/skyscrapers/detroit/';
$copy->title = 'Renaissance Center';
$copy->name = 'renaissance-center';
$copy->save();
```

If you try that, you end up with a copy of page id 1015, but the copy has the title of 1015 and NOT 'Renaissance Center'.

**Comment by ryancramerdesign** [comment]
Looks like change tracking might be off here, and maybe the clone() method needs to turn it on manually. If you put a `$copy->setTrackChanges(true);` right after your clone() call, does that fix it? Thanks.

**Comment by processwired** [comment]
Ryan, thanks a lot - that does the trick! Complete working script for the record:
```
<?php

namespace ProcessWire;

include './index.php';

// Clone the Westin Peachtree skyscraper page
// $building = $pages->get('/skyscrapers/atlanta/westin-peachtree/');
$building = $pages->get(1015);
$copy = $pages->clone($building);
$copy->setTrackChanges(true);

// Bonus: Now that the clone exists, lets move and rename it
// $copy->parent = '/skyscrapers/detroit/';
$copy->title = 'Renaissance Center';
$copy->name = 'renaissance-center';
$copy->save();
```

I guess it's normally not intended to call this method manually, because it is [not reflected in the docs](https://processwire.com/api/ref/pages/clone/) for clone()?

**Comment by ryancramerdesign** [comment]
Thanks for testing, glad that did it. That's correct, you shouldn't need to call setTrackChanges() on your own. Now I just need to figure out why it's necessary here, and will likely add that to the end of the clone method. Strangely I haven't seen this issue come up with page cloning before, but I think it's likely because most usages changing the title after an initial save.

**Comment by processwired** [comment]
Even an initial save() and setting the title afterwards followed by a second save() did not work. I had to pull the clone from a find() again to set the new title - this puzzled me as well and was actually the reason for this issue report.

**Comment by ryancramerdesign** [comment]
Well I went in to look at the $pages->clone() method and sure enough, it was turning off track changes at the very end for some reason. There must be a good reason, but I don't know what it was, and after fixing it and testing it all seems to be working normally, so I think it's all ok now.
