### ISSUE TITLE
PW 3.0.93 | Error on Installer

### ISSUE THREAD

**Issue by savvakis** [processwire/processwire-issues#502]
![screenshot-localhost-2018 02 23-20-30-53](https://user-images.githubusercontent.com/5842689/36610336-9902548a-18d8-11e8-8464-81263c3e84e0.png)

# Occurs on last step of installation!

**Comment by ryancramerdesign** [comment]
I can't duplicate this one yet. Can you tell me what options you entered or selected in the prior screen before you saw the error? Also, which site profile did you select? Thanks.

**Comment by savvakis** [comment]
False Alarm! 

And sorry for this...my hard drive had problems and i found out that some files were missing from the folder wire/templates-admin that most possibly caused the error.

Sorry for that again! The installation completes smoothly after i downloaded all files again.
