### ISSUE TITLE
"Pages" -> "Recent" -> "Add another" throws error.

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-issues#503]
### Short description of the issue

Clicking "Pages" -> "Recent" -> "Add another" throws error message when no previous action is available.
Message: "Notice: Undefined index: no-created in <path>/wire/modules/Process/ProcessRecentPages/ProcessRecentPages.module on line 400"

### Expected behavior

No Error Message.

### Setup/Environment

ProcessWire version: 3.0.93
PHP version: PHP 7.0.7

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed an update that should fix this issue.

**Comment by theo222** [comment]
The error message is gone. Now it says "No pages match (yet)".
Fixed.
Thank you.
