### ISSUE TITLE
using "or" condition with "path" in find selector not working

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#504]
### Short description of the issue

the following selector does not work:

$pages->find('path=/path1/|/path2/');

### Expected behavior

Providing multiple paths should result in multiple pages returned

### Actual behavior

Empty PageArray gets returned.

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.89 <br />
PHP: 7.0.17-2+deb.sury.org~trusty+1 <br />
Webserver: Apache/2.4.7 (Ubuntu) <br />
MySQL: 5.5.54-0ubuntu0.14.04.1 <br />
 <br />
</details>
<details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 300 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 600 <br />
max_input_vars: 1000 <br />
memory_limit: 512M <br />
post_max_size: 500M <br />
upload_max_filesize: 500M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: 2.2.3 <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.7.6 <br />
AdminPageFieldEditLinks: 3.1.0 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldDescriptionsExtended: 1.0.2 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FrontEndEditLightbox: 1.3.6 <br />
IcfAttachments: 0.0.1 <br />
IcfFeaturedImage: 0.0.2 <br />
IcfUnsplash: 0.0.2 <br />
IcfUtil: 0.0.1 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
Oauth2Login: 0.1.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.1.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.9.8 <br />
WireMailMandrill: 0.0.1 <br />
</details>

**Comment by ryancramerdesign** [comment]
OR values can't be used with path/url unless the core PagePaths module is installed. They also can't be used with multi-language paths, though support is planned in PagePaths. The error message could definitely use improvement here though. I have pushed a commit to throw an Exception when you attempt to use OR values and support isn't available (whether due to PagePaths module not installed or multi-language page names in use).

**Comment by noelboss** [comment]
Thank you @ryancramerdesign – is there no way top support it with multi-language?

**Comment by netcarver** [comment]
@ryancramerdesign @noelboss Would this be better off as an issue in processwire-requests? Either way, the initial issue doesn't seem fixed to me - so removing the "resolution: fixed" label.

**Comment by noelboss** [comment]
Seems to be a request then…

**Comment by noelboss** [comment]
I added a feature request:
https://github.com/processwire/processwire-requests/issues/219
