### ISSUE TITLE
Markup regions timeout with mismatched <div> tags

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#505]
### Short description of the issue

If you have a mismatched `<div>` tag, this error can result.

### Expected behavior

Some more graceful handling of this situation.

### Actual behavior

See the screenshot

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![image](https://user-images.githubusercontent.com/871211/36762683-b4a831b0-1bd9-11e8-9aac-11da04b828b4.png)

### Optional: Suggestion for a possible fix

Not really sure, but this is one of those nasty annoying bugs that means you either need to wait the 120 seconds, or restart apache.

### Steps to reproduce the issue

This was the code the caused the problem for me:
```
<div pw-before id='main'">
	<div class="uk-cover-background" style="height: 436px;background-image: url('<?=page()->images->first->url?>') ;background-repeat: no-repeat ;background-position: 50% 50% ;background-size: 100% ;background-color: transparent ;background-size: cover;">
</div>
```

You can see that I inadvertently forgot to close the div with the background image.

### Setup/Environment

* ProcessWire version: 3.093
* (Optional) PHP version: 7.2

**Comment by Toutouwai** [comment]
Does using "Markup Region hints" help? https://processwire.com/blog/posts/pw-3.0.70/

```html
<div pw-before id='main'">
	<div class="uk-cover-background" style="height: 436px;background-image: url('<?=page()->images->first->url?>') ;background-repeat: no-repeat ;background-position: 50% 50% ;background-size: 100% ;background-color: transparent ;background-size: cover;">
</div><!--#main-->
```

I'm trying to remember to use these on all regions now.

**Comment by adrianbj** [comment]
> Does using "Markup Region hints" help?

It does prevent the error yes, and it's definitely a good habit to get into, but if I can forget to add the closing `</div>` I am probably likely to forget to add the hint at some point also ;)

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed an update so that it now detects a missing closing tag, avoids the timeout, and puts a note about it in the errors list if you've got debug mode enabled and a `<!--PW-REGION-DEBUG-->` present in the markup.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that is much better :)

The only thing I am seeing that could possibly be improved is that the content is being output three times. Not a big deal though.
