### ISSUE TITLE
Feature request: get the page that the PageTable field belongs to

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#506]
I am using [CustomUploadNames](https://github.com/adrianbj/CustomUploadNames) module with my projects. I have rules for renaming uploaded files. If page created by **PageTable** module (auto-name), renaming for uploaded files not working well, i want to rename files based on the page that the PageTable field belongs to.

> @adrianbj Currently it's not really possible to get the page that the PageTable field belongs to.

I have an issue on CustomUploadNames module repo https://github.com/adrianbj/CustomUploadNames/issues/7

@adrianbj  comment :

> Hi @ukyo - thanks for the access, but I am not really sure how I can help you at the moment. Currently it's not really possible to get the page that the PageTable field belongs to. I think you need to contact Ryan to see if he'll add $editID to the query string on this line: https://github.com/processwire/processwire/blob/8acd06646ff55af4dca6e4aa61991165b94c3447/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.module#L149
That is part of issue, but then it also needs to be propagated to the next step in creating the page (after you save the page with the title field populated). Once it's available there, CustomUploadNames will be able to use it to populate the image name as defined.

@ryancramerdesign can you add this feature to PageTable module ?

* ProcessWire version: 3.093
* (Optional) PHP version: 7.2
* (Optional) MySQL version: Mariadb
* (Optional) Any 3rd party modules that are installed and could be related to the issue: CustomUploadNames

**Comment by ryancramerdesign** [comment]
A PageTable field could be on any number of pages. Do you mean get the Page that a PageTable *Page* belongs to? If so, here's how you do that below. The $page variable is a PageTable page.
~~~~~
$owner = $pages->get("page_table_field=$page, include=all");
~~~~~
I'll close this report because it's a feature request and this repo is only for issue reports (we have a separate processwire-requests repo [here](https://github.com/processwire/processwire-requests). If I didn't understand or answer your question correctly, please re-open in the feature-requests repo. Thanks.

**Comment by adrianbj** [comment]
Hey @ryancramerdesign - I'll let @trk move this to the requests repo, but I think the issue with the code you posted is that from the PageTable page (when you're editing in the modal), you don't know the name of the PageTable field, so you can't make the pages selector call. Or have I missed something?

**Comment by szabeszg** [comment]
Seems to be related?
https://processwire.com/talk/topic/17884-how-to-pass-data-to-modal-edit-windows/
Maybe I'm also not getting what this issue is exactly about?

**Comment by ryancramerdesign** [comment]
> you don't know the name of the PageTable field, so you can't make that pages selector call that you posted. Or have I missed something?

Yes, you would need to know the name of the field. Though now you can also do this, which might be what you need?`$pages->get("FieldtypePageTable=$page");`

**Comment by adrianbj** [comment]
> Though now you can also do this, which might be what you need?$pages->get("FieldtypePageTable=$page");

Thanks @ryancramerdesign - it does seem like that will work.

@trk - I'll implement this into CustomUploadNames and try to get a new version out for you.

@szabeszg - Robin's hook does work in some situations, but unfortunately not in this case, but thanks for pointing it out.

**Comment by trk** [comment]
Sorry for open this issue on wrong place.
Thanks @ryancramerdesign @adrianbj @szabeszg
