### ISSUE TITLE
Ajax dropdown menu not populating

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#508]
### Short description of the issue

When trying to get the items from an ajax menu, sometimes the items don't display and spinner keeps spinning. This has happened for as long as I can remember, but I never get around to reporting it.

### Expected behavior

Should display items

### Actual behavior

Items aren't displayed. Notice in the screenshot how "logs" never gets populated. The only way to restore this is to reload the page.

### Optional: Screenshots/Links that demonstrate the issue

![ajax_menu_bug](https://user-images.githubusercontent.com/871211/36929234-bdf94ad6-1e42-11e8-97b7-93729806c284.gif)

### Steps to reproduce the issue

It's all about timing, but it seem I manage to get the timing "right" more often than not :) It seems like it happens if you move across another 2nd level (eg fields, template, logs, etc) but move quickly onto another one. 

### Setup/Environment

* ProcessWire version: 3.0.93
* (Optional) PHP version: 7.2

**Comment by adrianbj** [comment]
Just because adding a status tag doesn't notify watchers I am bumping this to see if others can reproduce it.

**Comment by Toutouwai** [comment]
@adrianbj, I just tried to replicate what you are doing in the screen capture, moving quickly from menu to menu at different speeds (reloading the page before each to ensure an ajax-load happens), but I couldn't reproduce the issue you're seeing.

**Comment by adrianbj** [comment]
Thanks @Toutouwai and @matjazpotocnik for testing. I can't reproduce at the moment either, yet the other day I couldn't get it to stop doing it that way and I have seen it for a long time, so I don't know :) I am going to close for now and when I see it again I'll try to debug and provide some more info.
