### ISSUE TITLE
Fields inside Fieldset on User template don't save when fieldset has showif condition

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#509]
### Short description of the issue

Fields inside Fieldset on User template don't save

### Expected behavior

They should save

### Actual behavior

They don't save :)

### Steps to reproduce the issue

1. Add a fieldset to the user template
2. Set the showif condition for the fieldset to `roles=a-user-role`
3. Move some fields inside the fieldset open/end fields
4. Set one of the fields inside the fieldset and save

### Setup/Environment

* ProcessWire version: 3.0.94

**Comment by Toutouwai** [comment]
Do you mean in ProcessProfile or when editing a user at Access > Users? And if ProcessProfile, did you enable the editing of both the fieldset and the contained fields in the module config?

I can't reproduce the issue - editing fields within fieldsets is working for me in both scenarios above.

**Comment by adrianbj** [comment]
Hi @Toutouwai - thanks for looking into this. I am talking about editing a via Acess > Users. I just figured out that to reproduce this you need to set the showif for the fieldset. In my case I have `roles=user` as the showif condition for the fieldset. As soon as I remove this condition, fields save as expected. Can you reproduce this way?

**Comment by Toutouwai** [comment]
This issue has come up in the forums previously: https://processwire.com/talk/topic/16773-page-reference-field-not-updating-with-show-if/

The roles field is like a Page Reference field so you have to match roles in a showif dependency by ID (same as other Page Reference fields). What confuses things is that the visibility does update when editing the user in admin, but when saving the showif doesn't pass validation. So the fact that it *seems* to work in the editor is an anomaly of the roles field.

**Comment by adrianbj** [comment]
Thanks @Toutouwai - really appreciate your input on this. I am not keeping up with the forum as much as I used to, so missing stuff like this.

It's funny I have lots of page reference showif dependencies on this site (using the page ID), but forgot about it with the Roles showif. I definitely think that inconsistency of the visibility working with role name needs to be fixed though because it's definitely confusing and doesn't inspire confidence in the checks that are going on. To that end I think it's worth keeping this open.

**Comment by ryancramerdesign** [comment]
That's correct that you've got to use page IDs for showIf conditions connected with Page fields. I think it may be working with your role names on the front-end because the show/hide JS is general purpose to work with HTML select, checkbox and radio inputs, rather than knowing the details of specific Fieldtype modules. I could have it detect if you might be doing this (in ProcessField) and show a warning if it would help?

**Comment by adrianbj** [comment]
I do think a warning would be helpful because I am sure others will come across this.

**Comment by ryancramerdesign** [comment]
Okay sounds good, I have added this.

**Comment by adrianbj** [comment]
Thanks!
