### ISSUE TITLE
Fields not beeing saved when "Show this field only if" is active

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#51]
### Fields not beeing saved when "Show this field only if" is active

I got a field with the dependency ```bewerbungs_status='Abgelehnt'```
When I am on the page  with the data I click on "Abgelehnt" and the correct field appears.
But when I enter a value into it and save the page, the value is gone.

I tried this with a text field and a datetime field. The behaviour is the same.

### Expected behavior

The value should be saved

### Actual behavior

The value is not being saved.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.
![processwire-visible-error](https://cloud.githubusercontent.com/assets/551551/19428312/b20f901a-9449-11e6-8769-e0ff05062871.png)

### Steps to reproduce the issue

1. Create a new page in the tree `bewerbungs_status` and add two children in it
2. The two pages should be named 'Eingestellt' and 'Abgelehnt'
3. Create a field "bewerbungs_status" with type "Page". As parent select 'bewerbung_status' from the tree list. 
4. Assign the field to a template
5. Create a field "somename" with type "Text" and assign it to the same template
6. Go to the Input Tab of the "somename" field and under "Visibility" enter ```bewerbungs_status='Abgelehnt'```

### Setup/Environment
ProcessWire: 3.0.36
PHP: 7.0.10
Apache: 2.4.23 (Win32) OpenSSL/1.0.2h 
MySQL: 10.1.9-MariaDB-log

AdminOnSteroids: 0.7.6
BatchChildEditor: 1.3.8
FieldtypeRadio: 1.0.0
ProcessChildrenCsvExport: 1.3.8
ProcessPageDelete: 1.2.4
ProcessPageListerPro: 1.1.0
TracyDebugger: 3.4.1

**Comment by Toutouwai** [comment]
I tested this using the steps described and can confirm.

But is `bewerbungs_status='Abgelehnt'` a valid format for inputfield dependency from a Page field? This format doesn't show/hide the dependent inputfield if the Page inputfield is a select. And [according to the documentation](https://processwire.com/api/selectors/inputfield-dependencies/#example-page) the only supported way to match a Page field in an inputfield dependency is by ID.

**Comment by jmartsch** [comment]
If I use ID´s it works and the values are saved.

**Comment by jmartsch** [comment]
Closed this issue because my approach would not work in a multilanguage environment. So selecting the values with the ID is the correct way.
