### ISSUE TITLE
Field <field_name> is not saveable because it is in a specific context on upgrade to 3.0.93 dev

### ISSUE THREAD

**Issue by KeeneState** [processwire/processwire-issues#512]
### Short description of the issue

Upgrading from 3.0.62 (master) to 3.0.93 (dev) results in image fields throwing a fatal error, "Field <field_name> is not saveable because it is in a specific context." Once the field has thrown the error, it appears to be fine, the error not seen again. 

### Expected behavior

No errors thrown on upgrade.

### Actual behavior

The errors are thrown, once per affected field. While the errors are limited to imagefield types in my instance, it may affect the fields based on FieldtypeFile.

### Optional: Suggestion for a possible fix

I've traced the error back into the PW internals. From what I can tell, there is a schema upgrade occurring during the time of error. Specifically, the field is adding a new column, "filedata."

*FieldtypeFile.module/getDatabaseSchema*
```
$field->set('fileSchema', $field->get('fileSchema') | self::fileSchemaFiledata);
$field->save();  // <-- error is beginning here
```

At the same time, the save action occurs while the field has been been flagged as flagFieldgroupContext/2048, which has a comment above it "Field has been placed in a runtime state where it is contextual to a specific fieldgroup and is no longer saveable."

I think the field needs placed into a saveable state prior to the schema update. 

### Steps to reproduce the issue

I've had a great deal of difficulty reproducing the error from a fresh, minimal install of 3.0.62. I have, however, cut an existing database back to core, removing all but a few fields and removing non-core modules. Due to the self healing property of the error, it's proving difficult to track back to a presumed admin setting that could be responsible.

### Setup/Environment

PW 3.0.62, upgrading to 3.0.93
PHP 7.1.6
MariaDB 10.2.6

Edited 3/6/18, schema is adding a column, not a row.

**Comment by zeb600** [comment]
First of all, great work @KeeneState tracking this down, thanks!
This post is basically just a +1, happened on a 0.75 to 0.93 upgrade on PHP 5.6.x (starting today I'm on holiday the next couple of weeks and unfortunately can't list the exact env rn), on image fields.

**Comment by jacmaes** [comment]
I’ve also experienced the same thing while upgrading from an old dev version.

**Comment by ryancramerdesign** [comment]
If you've seen that error message it can safely be ignored. But I've pushed an update that should prevent that error message from appearing. Thanks.

**Comment by KeeneState** [comment]
Thank you @ryancramerdesign. Just tested, this eliminates the errors on upgrade--closing the issue.
