### ISSUE TITLE
z-index issue with datepicker

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#513]
### Short description of the issue

When opening a date picker using the UIKIT admin theme, and there's an image field below, the image thumbnail shows through. It becomes very difficult to properly select a date.

### Expected behavior

The date picker shows itself above anything else.

### Actual behavior

Actual behavior goes here.

### Optional: Screenshots/Links that demonstrate the issue

![date-picker](https://user-images.githubusercontent.com/1206842/36995753-31405f74-20b5-11e8-8064-df8118e8d2b7.png)

Note: the image field in the screenshot is using the Horst's CroppableImage3 module.

### Steps to reproduce the issue

I think the screenshot is self-explanatory.

### Setup/Environment

* ProcessWire version: 3.0.93 dev
* (Optional) PHP version: 7
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: CroppableImage3

**Comment by matjazpotocnik** [comment]
https://github.com/ryancramerdesign/AdminThemeUikit/issues/1

@ryancramerdesign ping

**Comment by ryancramerdesign** [comment]
Thanks, I was able to duplicate the issue once I put my images field in list mode (did not appear in the grid modes). I have pushed a fix.

**Comment by marloren** [comment]
This fix has solved this issue. Thanks! I'm closing the issue.

**Comment by jacmaes** [comment]
This fix has solved the issue. Thanks! I'm closing the issue.

**Comment by teppokoivula** [comment]
@ryancramerdesign, I'm still experiencing a very similar issue with ProcessWire 3.0.98:

![processwire-datepicker-z-index-issue](https://user-images.githubusercontent.com/1252021/46140953-31e98480-c25b-11e8-8ffa-615549e01bd7.jpg)

To be more specific everything is fine as long as the datepicker is overlapping image itself, but when it overlaps the `.InputfieldImageEditAll .gridImage .ImageData` element which has `z-index: 3`, the datepicker (which has inline style `z-index: 2`) is unusable.

For the time being I've solved this locally by adding `z-index: 3 !important` to `#ui-datepicker-div` in InputfieldDatetime.css.

@jacmaes, is this working correclty for you? It seems from your screenshot that you've got almost exactly the same setup as I do, yet for me the rightmost datetime field doesn't work with a datepicker. Then again, you don't seem to have image descriptions available, so perhaps that's the difference here  :)

**Comment by jacmaes** [comment]
@teppokoivula I'm on 3.0.114, and I can confirm that it works for me, both on the latest Firefox and Chrome. I've tried adding a description field just to see if it makes a difference, but it still works as it should. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1206842/46141434-2e063400-c254-11e8-957b-15a3b4daf575.png)

**Comment by teppokoivula** [comment]
Thanks for checking, @jacmaes! I wonder what's the difference here – probably should  create a test case just to be sure. It might've also been fixed in 3.0.114 through some other commit, thought that seems a bit unlikely. I'm using the latest Chrome myself.

One difference I can still spot is that you've predefined crops there – is that a core feature or CroppableImage3? Perhaps that could make some difference, but hard to say without testing. :)

**Comment by jacmaes** [comment]
@teppokoivula Yes, I'm using CroppableImage3 in this case. I've just tested on another site running 3.0.111 that has a couple of date fields above a regular image field. On Firefox, it still works:

![image2](https://user-images.githubusercontent.com/1206842/46142117-2b0c4300-c256-11e8-9d44-fd776e903fa1.png)

**Comment by teppokoivula** [comment]
@jacmaes, thanks again. I'll have to set up a test case and isolate my issue a bit further. Currently I've no idea what could cause the difference. I don't think I've got any third party modules that should interfere with this functionality :)

**Comment by Toutouwai** [comment]
@teppokoivula, I can reproduce the issue you're seeing. PW 3.0.114 in Chrome:

![2018-09-29_000746](https://user-images.githubusercontent.com/1538852/46207587-04482c80-c37c-11e8-806b-5349afc1f627.png)

@jacmaes, do you maybe have AdminOnSteroids installed? I notice that seems to fix the z-index issue.

Incidentally, applying the z-index fix I suggested in [another issue](https://github.com/processwire/processwire-issues/issues/602#issuecomment-391567484) will also fix this issue.
```css
.Inputfield { z-index:1; } 
```
@ryancramerdesign, could you please take another look at that suggestion?

**Comment by teppokoivula** [comment]
Thanks @Toutouwai – looks like I'm not going crazy after all :D

**Comment by jacmaes** [comment]
The plot thickens: I do have AdminOnSteroids installed on one of the sites, but not on the other running 3.0.111 (see above)…

**Comment by jacmaes** [comment]
Never mind, I was able to reproduce the issue on the site running 3.0.111  also:
![screen shot 2018-09-28 at 14 47 44](https://user-images.githubusercontent.com/1206842/46209227-89f0bb80-c32d-11e8-8c5b-5c373d7f19b3.png)

**Comment by teppokoivula** [comment]
Thanks @jacmaes. Would you mind re-opening this issue? Also I'm not sure if @ryancramerdesign has been following the discussion here, but the issue still needs some attention.

**Comment by netcarver** [comment]
Reopening as per request from @teppokoivula

**Comment by netcarver** [comment]
@ryancramerdesign Looks like this needs a little more attention.

/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
@netcarver I was able to duplicate it once making the date field floated right and have pushed a fix, bumping up the z-index of the datepicker a bit. Thanks.

**Comment by netcarver** [comment]
@jacmaes Could you verify this fixes the issue and close it if it does? If not, just post an update. Thank you.

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by jacmaes** [comment]
I can confirm the fix works. Closing this issue
