### ISSUE TITLE
InputfieldImage - portrait image resize fails when min/max width is set

### ISSUE THREAD

**Issue by rogersarrasin** [processwire/processwire-issues#515]
### Short description of the issue

When uploading an image using the InputfieldImage field, the image resizing fails (portrait orientated upload/not landscape) when a max and min width is set for uploaded images.
Error message reports that the image does not meet the minimum size requirements regardless if the image uploaded is wide enough.

### Expected behavior

Expected behavior is that the portrait orientated image would be resized by width first.

### Actual behavior

It seems that the image resize on a portrait image is using the height as the primary resize dimension, which can cause the width to become too small, regardless if the uploaded image is initially wide enough.

### Optional: Screenshots/Links that demonstrate the issue

![screen shot 2018-03-05 at 3 49 22 pm](https://user-images.githubusercontent.com/3981323/37050717-72eb1288-2129-11e8-999e-b9214c184e12.png)

![screen shot 2018-03-05 at 3 50 51 pm](https://user-images.githubusercontent.com/3981323/37050750-890ddb86-2129-11e8-9f99-94f754d31196.png)

### Steps to reproduce the issue
Included InputfieldImage field settings.
{
    "feature_panel_image": {
        "id": 120,
        "type": "FieldtypeImage",
        "flags": 0,
        "name": "feature_panel_image",
        "label": "Feature Panel Image",
        "description": "1. Upload Original (wait for spinner to stop)\n2. Click Save\n3. Click Image to **Edit**\n4. **Crop** to dimensions below and set **Focus**\n\nMin upload width: **1600px**\nCrop to:  **1600px** x **1192px**\nRatio: **1.3421**\n\n[Styleguide Example](https://styleguide.thepointerestaurant.ca/?p=base-feature-panel--desktop)",
        "fileSchema": 6,
        "extensions": "jpg jpeg",
        "maxFiles": 1,
        "outputFormat": 0,
        "defaultValuePage": "",
        "useTags": 0,
        "inputfieldClass": "InputfieldImage",
        "descriptionRows": 1,
        "gridMode": "list",
        "resizeServer": 0,
        "clientQuality": 90,
        "collapsed": 0,
        "maxWidth": 1600,
        "minWidth": 1600,
        "icon": "camera",
        "focusMode": "on",
        "outputString": "",
        "textformatters": "",
        "entityEncode": "",
        "tagsList": "",
        "showIf": "",
        "themeOffset": "",
        "themeBorder": "",
        "themeColor": "",
        "columnWidth": 100,
        "required": "",
        "requiredIf": "",
        "unzip": "",
        "overwrite": "",
        "maxHeight": "",
        "maxSize": "",
        "maxReject": "",
        "minHeight": "",
        "dimensionsByAspectRatio": ""
    }
}

Example image can be provided if required. Issue can be replicated w/ a variety of images.
Issue was caused using following image details.

1. Upload landscape image (2842px x 2841px 6.4mb). Works
2. Upload square image (2847px x 2847px 6.4mb). Works
3. Upload portrait image (2847px x 2848px 6.4mb). Fails b/c image does not meet minimum size requirements.

### Setup/Environment
PW - 3.0.93

* ProcessWire version:
* (Optional) PHP version: 7
* (Optional) Any 3rd party modules that are installed and could be related to the issue: MarkupSrcSet

**Comment by ryancramerdesign** [comment]
Thanks for posting your field settings, this helped me to see what the issue was. You've got client-side resize enabled and no max Height specified. In the "How to resize to max dimensions" setting in your image field settings, it states this:

> When using client-side resize, please specify both max width and max height in the fields above, or max megapixels in the field below.

It needs you to specify both max width and max height, otherwise it won't work. It becomes a max for either dimension at that point. If you don't want to specify a max height, turn off the client-side resize so that it uses only a server-side resize, and that should work.

**Comment by rogersarrasin** [comment]
Thanks for looking into this post. I thought it was a bug. I am allowing the height to be blank so that the client can crop the image with only the height to work out. Will move to turn off the client-side resize.
