### ISSUE TITLE
$datetime->convertDateFormat() conversion to strftime returns wrong result with $ symbols instead of %

### ISSUE THREAD

**Issue by alguintu** [processwire/processwire-issues#516]
### Short description of the issue

$datetime->convertDateFormat() conversion to strftime returns wrong result with $ symbols instead of %

### Expected behavior
`echo $datetime->convertDateFormat("d/m/Y","strftime");
// %d/%m/%Y`

### Actual behavior
`echo $datetime->convertDateFormat("d/m/Y","strftime");
// $d/$m/%Y`

### Optional: Screenshots/Links that demonstrate the issue

```
// output looping through getDateFormats()
l, j F Y : %A, $-d %B %Y
j F Y : $-d %B %Y
d-M-Y : $d-%b-%Y
dMy : $d%b%y
d/m/Y : $d/$m/%Y
d.m.Y : $d.$m.%Y
d/m/y : $d/$m/%y
d.m.y : $d.$m.%y
j/n/Y : $-d/$-m/%Y
j.n.Y : $-d.$-m.%Y
j/n/y : $-d/$-m/%y
j.n.y : $-d.$-m.%y
Y-m-d : %Y-$m-$d
Y/m/d : %Y/$m/$d
Y.n.j : %Y.$-m.$-d
Y/n/j : %Y/$-m/$-d
Y F j : %Y %B $-d
Y-M-j, l : %Y-%b-$-d, %A
Y-M-j : %Y-%b-$-d
YMj : %Y%b$-d
l, F j, Y : %A, %B $-d, %Y
F j, Y : %B $-d, %Y
M j, Y : %b $-d, %Y
m/d/Y : $m/$d/%Y
m.d.Y : $m.$d.%Y
m/d/y : $m/$d/%y
m.d.y : $m.$d.%y
n/j/Y : $-m/$-d/%Y
n.j.Y : $-m.$-d.%Y
n/j/y : $-m/$-d/%y
n.j.y : $-m.$-d.%y
```

### Optional: Suggestion for a possible fix

Change the $ symbols in WireDatetime to %

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks @alguintu, I'm not sure why we had `$` in there, but I have corrected it.

**Comment by alguintu** [comment]
Thanks. 👍
