### ISSUE TITLE
Multiple issues in AdminThemUikit

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#517]
Ryan, just in case you aren't following [AdminThemeUikit repository](https://github.com/ryancramerdesign/AdminThemeUikit/) ... there are some issues/annoyances that you could look at? Don't know if we should reopen them here? Thank you.

**Comment by ryancramerdesign** [comment]
Thanks I have just now pushed fixes for these

**Comment by matjazpotocnik** [comment]
Thank you.

If you don't mind looking at https://github.com/ryancramerdesign/AdminThemeUikit/issues/46 again? There is an inconsistency about the look of Crop, Variations and Focus links/buttons on images if they are inside or outside of repeater. I still think my proposed fix is the way to go because it preserves consistency between all admin themes.

**Comment by matjazpotocnik** [comment]
Thanks.
