### ISSUE TITLE
Multi-instance Support in Multi-site Setup (Windows)

### ISSUE THREAD

**Issue by kongondo** [processwire/processwire-issues#518]
### Short description of the issue

Using multi-instance feature in a MS Windows environment leads to a fatal *Failed to open stream* error when passed an absolute path to initiate a new ProcessWire instance. I am using [multi-site setup option #1](https://processwire.com/api/modules/multi-site-support/)

### Expected behavior

The Processwire Class should be able to detect that paths in Windows do not start with a slash. 

### Actual behavior

Failed opening required file. This is because ProcessWire pre-pends a slash (/) to the path.  For instance, **/F:/vhosts/sandpit.dev/wire/config.php**

### Suggestion for a possible fix

A workaround by @matjazpotocnik for Windows users is to use the **Processwire::buildConfig()** API to build a config with the path to pass to new ProcessWire().

````php
$rootPath = "F:/vhosts/sandpit.dev";
$sitePath = "site-mediamanager";
$url = "http://mediamanager.sandpit.local/";

$cfg = Processwire::buildConfig($rootPath, $url, array("siteDir" => $sitePath));

$site = new ProcessWire($cfg);// works fine; no errors

````

### Steps to reproduce the issue

1. Step 1
````php
$path = "F:/vhosts/sandpit.dev/site-mediamanager/";
// OR
// $path = "F:\\vhosts\\sandpit.dev\\site-mediamanager\\";
$url = "http://mediamanager.sandpit.local/";
/* this will throw an error because ProcessWire will build the path as 
'/F:/vhosts/sandpit.dev/wire/config.php' */
$site = new ProcessWire($path, $url);

````
Fatal error occurs on on this [line](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/ProcessWire.php#L877) in ProcessWire.php.

Origin of the error seem to be this [line](https://github.com/processwire/processwire/blob/57b297fd1d828961b20ef29782012f75957d6886/wire/core/ProcessWire.php#L784) in ProcessWire.php where a forward slash (/) is pre-pended to the path

Forum [thread](https://processwire.com/talk/topic/18561-multi-instance-support-in-multi-site-setup/) about the issue including the possible resolution.

* ProcessWire version: 3.085

**Comment by ryancramerdesign** [comment]
Thanks @kongondo I think I've got this fixed, can you try the latest commit referenced above?

**Comment by matjazpotocnik** [comment]
@ryancramerdesign thanks for the fix (can't test right now), but there is another issue on windows if $rootPath contains .. notation eg. c:/foo/../bar since in that case you are calling realpath() function and on windows this will return backslashes:

```
if(DIRECTORY_SEPARATOR != '/') {
    $rootPath = str_replace(DIRECTORY_SEPARATOR, '/', $rootPath);
}
if(strpos($rootPath, '..') !== false) $rootPath = realpath($rootPath);
```
Possible fix would be first calling realpath() and then convert backslashes to slashes? Also, I would check for the return value of realpath() function, if it's false, then I would throw new WireException("Path not found or not accessible."); or something alike.

**Comment by kongondo** [comment]
That fixes it @ryancramerdesign, thanks.. Should I close the issue of leave it open in light of @matjazpotocnik comment above?

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik good suggestions. I have applied them in the latest commit.
