### ISSUE TITLE
3.0.93+ broke the frontend ckeditor image plugin from loading

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#519]
### Short description of the issue

I noticed after updating from 3.0.92 to 3.0.93, I could no longer insert an image using ckeditor with the frontend editing.  This also happens in 3.0.94.

I believe the problem was introduced in this commit.  https://github.com/processwire/processwire/commit/72e00189b52acf530dd93e715a7824b33a662618

### Expected behavior

Click on the image icon in ckeditor should popup and load the PW Image Chooser/Editor Plugin.

### Actual behavior

When I click the image icon in the ckeditor, nothing happens and I get an error message in Chrome's console.

![imageicon](https://user-images.githubusercontent.com/40570/37181740-e1ab7282-22f3-11e8-8a15-e62f1104aa5f.jpg)

### Optional: Screenshots/Links that demonstrate the issue

![error](https://user-images.githubusercontent.com/40570/37181438-a3fb1cea-22f2-11e8-8811-212be9aab176.jpg)

### Optional: Suggestion for a possible fix

Not sure.

### Steps to reproduce the issue

1. Enable frontend editing on a text area field.  I'm using option A
2. Go to frontend and double click on the text to edit
3. Click the image icon in ckeditor and observe the error

### Setup/Environment
ProcessWire version:3.0.92
PHP | 7.1.12
ServerApache/2.4.29 (Unix) PHP/7.1.12

**Comment by ryancramerdesign** [comment]
This sounds like browser cache having an older version of InputfieldCKEditor.js stuck in there. Can you try again from an Incognito window? Please let me know if the issue persists. Thanks.

**Comment by gmclelland** [comment]
FYI...I noticed this problem on several sites.  I just checked again in an Incognito window.  3.0.92 works, but starting with 3.0.93 it doesn't work.

The way I checked:
Open Incognito window, login to site that is on 3.0.92.  Test frontend editing by click the image button.  That works.  Close the Incognito window.

Upgrade site to 3.0.93.  Open new Incognito window.  Login into site that is now on 3.0.93.  Test frontend editing by clicking the image button.  Nothing happens.  Error in console.

**Comment by gmclelland** [comment]
Just tried in Firefox and PW 3.0.94 with the same errors.  Here is a screenshot of the error if it helps.
![error](https://user-images.githubusercontent.com/40570/37215497-b5fa0aec-237d-11e8-8e76-d78894c8ea2c.jpg)

**Comment by matjazpotocnik** [comment]
Function ckeGetProcessWireConfig() is defined in InputfieldCKEditor.js, but that file is not loaded on frontend. A temporary fix is commenting out `var pwCkeSettings = ckeGetProcessWireConfig(editor);` in /wire/modules/Inputfield/InputfieldCKEditor/plugins/pwimage/plugin.js

**Comment by gmclelland** [comment]
Thanks @matjazpotocnik!  I actually had to comment out the following two lines in /wire/modules/Inputfield/InputfieldCKEditor/plugins/pwimage/plugin.js to get it to work:

```js
var pwCkeSettings = ckeGetProcessWireConfig(editor);
		
if(pwCkeSettings && pwCkeSettings['pwAssetPageID']) page_id = pwCkeSettings['pwAssetPageID'];
```

Commenting out those two lines allows the pwimage plugin load, but I bet it wouldn't work fully with the new Asset Page setting/functionality that Ryan introduced?

I think those lines cause the problem because they call ckeGetProcessWireConfig which is in wire/modules/Inputfield/InputfieldCKEditor/InputfieldCKEditor.js and strangely that file doesn't seem to get loaded into the browser.  Since inputfieldCKEditor.js isn't loaded, it results in an "... is not defined" error.

I really don't understand how it is working at all without InputfieldCKEditor.js?

**Comment by matjazpotocnik** [comment]
I think the most important thing is that we found the cause of the problem, even if we don't completely know what are Ryan's plans with assets page :-)

**Comment by ryancramerdesign** [comment]
Thanks for helping me track this one down. I've pushed a fix.

**Comment by gmclelland** [comment]
Thank you!
