### ISSUE TITLE
Page field inside a repeater not working on the user template

### ISSUE THREAD

**Issue by f-b-g-m** [processwire/processwire-issues#52]
### Short description of the issue

Page field (using the PageListSelectMultiple input type) inside a repeater on the user template is not working as expected. Works on other templates.
### Expected behavior

Repeater field displays the PageListSelectMultiple button.
### Actual behavior

Repeater field displays a text box.
### Optional: Screenshots/Links that demonstrate the issue

[screenshots](http://imgur.com/a/ZLCJ4)
### Steps to reproduce the issue
1. Create a repeater field containing a page field with input field type set to PageListSelectMultiple 
2. Add the repeater field to the user template
3. Edit an user page and add a new repeater, instead of the button to select pages there is a text box
### Setup/Environment

<details><summary>

<strong>Server Details</strong></summary>

ProcessWire: 3.0.36
PHP: 7.0.6
Apache: 2.4.20 (Win32) OpenSSL/1.0.2g 
MySQL: 5.6.30
</details><details><summary>

<strong>Server Settings</strong></summary>

 allow_url_fopen: 1
max_execution_time: 30 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 1000
memory_limit: 128M
post_max_size: 8M
upload_max_filesize: 2M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 1
FreeType: 1
Imagick Extension: 
</details><details><summary>

<strong>Module Details</strong></summary>

 FormHelper: 0.8.7
FrontendUser: 0.9.3
FrontendUserRegisterEmailValidation: 0.0.9
InputfieldImageNT: 1.2.4
ProcessFileEdit: 1.1.0
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
TracyDebugger: 3.4.1
</details>

Same behavior on debian 8 with php 5.6

**Comment by ryancramerdesign** [comment]
Thanks @	f-b-g-m I have pushed a fix for this issue.
