### ISSUE TITLE
Modules in the core

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#522]
Not really an issue, more a request, but since the master version is due I thought to mention here.

In one of your blog posts (I can't find that post so I'm writing from memory), you said that eventually, some modules will make into the core and some modules will be removed from the core. I was thinking about the multilanguage fields and wonder why FieldtypeEmailLanguage and FieldtypeURLLanguage are not in the core? If they were, we (and all new users) would have complete multilanguage support already built in. On the other hand, I wonder how would PW look like if none of the ML fields were present in the core and user would have an option to download all of them in one go? Also, please consider putting WireUpgrade module in the core.

**Comment by szabeszg** [comment]
@teppokoivula could run a poll or two to decide what percentage needs what modules, and I agree that it is a good idea to include some already solid and widely used ones such as the ones @matjazpotocnik mentioned. The WireUpgrade is especially a good candidate.

> I wonder how would PW look like if none of the ML fields were present in the core and user would have an option to download all of them in one go?

It's a good idea to speed up the installation process for those who need all the ML features, but probably not in this master as it is new feature request after all. However, including well tested modules is a "not risky" I guess.

**Comment by adrianbj** [comment]
In addition to PW Upgrade, I would also add @netcarver 's Module Release Notes - I think if you are running the upgrade module you really need an easy way to see what the changes are going to be and if there are an breaking changes.

**Comment by matjazpotocnik** [comment]
Of course, it would be good to have ReleaseNotes in the core, but I'm almost sure Ryan will not add it as he only adds modules he wrote and maintain. I think the functionality of ReleaseNotes module should be part of upgrade module... Maybe sometime in the future, who knows.

While it's easy to vote for a module that should be in the core it's much harder to decide what modules shouldn't be in the core. And how would the reduction of a number of modules impact to the overall PW execution speed, if at all?

**Comment by netcarver** [comment]
Thanks for the kind vote, @adrianbj. However, I disagree - I think the ReleaseNotes module should not be part of the core.

**Comment by adrianbj** [comment]
>  I think the ReleaseNotes module should not be part of the core.

Do you think the functionality isn't needed at all, or just not everything that your module brings?

Perhaps Ryan could implement something much simpler - like detection of "Breaking Changes" in the module's commit log. That is the key functionality I am looking for. I install your module on all my sites because I like to see what's new, but the key thing I am looking for is possible breaking changes.

**Comment by szabeszg** [comment]
related popular request:
https://processwire.com/talk/topic/13043-changelog-support-in-processwireupgrade-module/

**Comment by ryancramerdesign** [comment]
This repo is just for issue reports. We have a dedicated feature requests repo at: https://github.com/processwire/processwire-requests

> why FieldtypeEmailLanguage and FieldtypeURLLanguage are not in the core?

I don't think they are needed widely enough to justify their inclusion. When it comes to adding modules to the core, I try to avoid adding modules that wouldn't be used by at least 30% of installations. 

>  Also, please consider putting WireUpgrade module in the core

I feel it's a dev and staging tool, and not a production server tool at present (at least on servers where Apache doesn't run as the user), and so I feel it doesn't belong in the core. At some point we may get an FTP installation option in that module (or core), which would allow upgrade files to be owned by the user, regardless of how Apache is running. And then I think this module might be workable as a production tool, opening it up to potential core inclusion.

**Comment by matjazpotocnik** [comment]
Ryan, I know this repo is for issues (as I stated at the beginning) and that we have separate repos for feature requests and pull requests but you don't regularly provide the answers there. This repo is thus the only way to get your attention or opinion.

I know how you decide to include modules to the core, I just thought it would be nice to have all ML fields under one roof.

Looking forward towards enhanced upgrade module.

Thank you for your time.
