### ISSUE TITLE
ProcessRole Dialog - Minor UI Inconsistency!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#524]
The Dialog should use **UiKit** Styles, See The Screenshot below.

![pw_processrole](https://user-images.githubusercontent.com/5323832/37238914-38ccd7c2-2439-11e8-8560-0afdcc0fb0af.png)

**Comment by ryancramerdesign** [comment]
That uses the Vex library, which is not part of Uikit. They are not part of the admin theme any more than JS alert/confirm boxes are, just an enhanced version of alert/confirm boxes. At present they look the same on all admin themes. I agree it'd be nice to have them styled with the admin theme, and we may do that at some point if it's possible, but something to revisit later. I will add a reminder to myself to take a closer look soon.

**Comment by Mu9tafa-Online** [comment]
Fair Enough, and as said it's a minor issue, not a big deal.
