### ISSUE TITLE
repeater items 

### ISSUE THREAD

**Issue by junofornow** [processwire/processwire-issues#525]
### Short description of the issue

Repeater item with a field where the user enters a 0 (zero) isn't outputted.
Tried it with different fields, even with Integer field that is configured with a different output for 'empty' and 'zero'.

### Expected behavior

Items with a zero value in it should be included

### Actual behavior

The repeater item with zero value input isn't included in the $page->myrepeater

### Optional: Screenshots/Links that demonstrate the issue

![1](https://user-images.githubusercontent.com/37275559/37258230-fc6f57c2-2574-11e8-8599-4ae3a3ac5dba.JPG)
![2](https://user-images.githubusercontent.com/37275559/37258231-02db8356-2575-11e8-97d1-a029c9d56bd7.JPG)
![3](https://user-images.githubusercontent.com/37275559/37258232-04cbaaba-2575-11e8-951c-a0917e6532d0.JPG)
![4](https://user-images.githubusercontent.com/37275559/37258234-06ebce60-2575-11e8-98a8-be4bc8e5c418.JPG)

### Setup/Environment

* ProcessWire version: 3.0.62
* (Optional) PHP version: 7.1
* (Optional) MySQL version: MariaDB 10.1.21
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Netcarvers Time inputfield is in the same repeater

**Comment by junofornow** [comment]
btw the same occurred when converting the repeater to the new repeaterMatrix.

**Comment by Toutouwai** [comment]
Have you raised your problem in the forums? How do you know this is a bug and not just a problem with your code?

**Comment by junofornow** [comment]
> not just a problem with your code?

it's always a problem with my code, depends on how you look at it :-)

After some more testing the problem however is not with the repeater, but with a filter.
Filters are destructive, but shouldn't they reset when doing a new find?
```
1 $gameday = $tournament->children()->first();
2 $games = $gameday->games_repeater->filter("score1!=,score2!=");
3 echo count($games);
```
 returns 0 items if scores are zero or empty.
further down in the same page:
```
4 $gameday = $tournament->children()->first();
5 $games = $gameday->games_repeater;
6 echo count($games);
```
still returns 0 items if scores are zero or empty.
The destructive filter isn't reset.

**Comment by ryancramerdesign** [comment]
The filter() method is destructive, meaning it's modifying the `$gameday->games_repeater` value. There is no such thing as a reset on a destructive method, you would need to use a non-destructive method instead. I think what you want here instead is the find() method, which does the same exact thing, except in non-destructive way. Meaning, your `$games` will have the value you want, without modifying `$gameday->games_repeater`. You would just replace your "filter" with "find".

**Comment by junofornow** [comment]
thanks, I figured as much out.

Probably pretty standard but kinda weird that you fill out a new wireArray (I would expect it to be fetched again when redefining) and the previous filter still applies.
