### ISSUE TITLE
Language tabs click & hold action not updating active tab for all tabs :: AdminThemeUikit

### ISSUE THREAD

**Issue by trk** [processwire/processwire-issues#526]
### Short description of the issue
When you click and hold mouse button on language tab, its not updating other language tabs active class for AdminThemeUikit theme.

![2018-03-12 16 56 10](https://user-images.githubusercontent.com/455983/37287723-85420954-2616-11e8-90ed-8aff5fc23512.gif)

**Comment by ryancramerdesign** [comment]
Thanks, the action is supposed to be double click, not long-click. It was changed awhile back, but looks like some of the long-click stuff was still present, so I have updated that to correct it.
