### ISSUE TITLE
Cannot use ProFields table within a repeater

### ISSUE THREAD

**Issue by richgcook** [processwire/processwire-issues#527]
### Short description of the issue

Cannot use ProFields table within a repeater.

### Expected behavior

I expect the 'Add Row' button to add a new row. It doesn't but instead adds the hash on the button to the URL.

### Actual behavior

I am using ProFields Table within a repeater and upon adding a new row it simply adds the hash in the link button to the URL (guess is the JS is missing thus not preventing the default action of the hash link) – if I turn off AJAX loading for the repeater the table renders and functionality works fine.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Add AJAX loading of scripts required for table if used within a repeater

### Steps to reproduce the issue

1. Create a repeater field
2. Create a ProFields Table field
3. Add the table to the repeater field
4. Try to add a new row to the table on the page the repeater is on

**Comment by ryancramerdesign** [comment]
A ProFields Table field is an alternative to a Repeater field, but it can't be combined with a repeater field. They are both repeatable types with definable types, so they will conflict with each other. In PW 3.x versions you can nest one repeater in another though.

**Comment by adrianbj** [comment]
@richgcook - I haven't tested in a while, but despite not being officially supported, I have successfully used a table inside a repeater. The only difference is that it was before repeaters were ajax loadable. Perhaps you should try with ajax off and see if they still work.

**Comment by richgcook** [comment]
> @richgcook - I haven't tested in a while, but despite not being officially supported, I have successfully used a table inside a repeater. The only difference is that it was before repeaters were ajax loadable. Perhaps you should try with ajax off and see if they still work.

This is exactly what it was!

**Comment by adrianbj** [comment]
> This is exactly what it was!

So just to confirm - it's working as expected with ajax loading of repeaters turned off?

I think this is fine so long as you don't have lots of repeater items (which is why ajax loading was implemented) and is an OK solution in many situations.

**Comment by ryancramerdesign** [comment]
It definitely won't work with ajax enabled, but I'm still surprised if it works consistently without it. They both namespace field names used in repeatable items, and this is where I thought potential for conflict was possible. For this reason, I usually suggest not mixing repeatable types unless support for it is stated. But if you find it works reliably to have a Table in a Repeater for your case (with ajax off), then that's good to hear.

**Comment by richgcook** [comment]
It didn't work with AJAX enabled but did of course with AJAX disabled so this is good.

But yes I understand what you're saying, Ryan. Odd that it works then... no problems so far anyway. You can put a repeater inside a repeater though so isn't this just the same?

**Comment by netcarver** [comment]
@ryancramerdesign How do you want to proceed with this issue?

**Comment by ryancramerdesign** [comment]
@netcarver I'm thinking maybe we should keep Pro-modules related issues in the relevant board in the PW forums rather than here, as I think it's simpler if this repo is focused purely on PW core. For this particular issue, the Table field wasn't built to itself be repeated in that manner (though it sounds like maybe it partially works even if not intended), so I'm adding a `@todo` in my FieldtypeTable.module file to get a closer look at this possible combination.

**Comment by netcarver** [comment]
@ryancramerdesign Ok, however, that policy may prevent a user who no longer has access to the Pro-module area of the forum from reporting issues. I know there is one such issue from thetunningspoon that I posted in there for you yesterday.

**Comment by ryancramerdesign** [comment]
@netcarver I think that's probably okay since the support of Pro modules is
based on a different model than the core. Though it's certainly fine if
someone wants to post in here too. I was just thinking in general it might
be better to focus this repo on the core when/where possible, but
exceptions here are there are just fine too.

**Comment by netcarver** [comment]
/remind me to review in 1 week

**Comment by teppokoivula** [comment]
+1 to what @ryancramerdesign said above, i.e. keeping Pro module issues out of the ProcessWire repositories :)

I get why those (and issues related to other non-commercial modules from Ryan) often pop up here, but it'd be great if we could keep them separate. ProcessWire is a non-commercial open source project with various parties involved, while those other projects are clearly separate entities.

Those other projects are (solely) Ryan's projects, while we've often mentioned ProcessWire being a community effort. Allowing non-PW issues to leak (and remain) in the same issue list blurs that line, and can result in unnecessary confusion.

**Comment by netcarver** [comment]
Closing this issue. Thank you all.
