### ISSUE TITLE
$config->paths->adminTemplates inconsistent

### ISSUE THREAD

**Issue by gRegorLove** [processwire/processwire-issues#53]
### Short description of the issue

When using AdminThemeReno, `$config->paths->adminTemplates` still defaults to `/wire/templates-admin/` in some contexts, even if `$config->defaultAdminTheme` is set.
### Expected behavior

`$config->paths->adminTemplates` should always point to the specified, default theme.
### Actual behavior

`$config->paths->adminTemplates` defaults to `/wire/templates-admin/` in some contexts, like within template files.
### Steps to reproduce the issue

In my example, the desired effect is a template=documentation that can be used to add documentation pages in the admin, displaying their body in the default Reno theme. The ProcessDocumentation module lists all of these pages and handles some management tasks for the documentation pages. (outside the scope of these steps).
1. Create a Process module, e.g. ProcessDocumentation
2. Add documentation.php template file with:

```
$page->process = 'ProcessDocumentation'; 
$page->body .= $config->paths->adminTemplates;
require($config->paths->adminTemplates . 'controller.php'); # following the admin.php example
```
1. Create a page with template=documentation.
2. View the new page and note it displays the classic theme and shows the path is `/wire/templates-admin/`
3. Contrast with `$this->config->paths->adminTemplates` inside the ProcessDocumentation::execute() method, where it will display the path to AdminThemeReno.
### Setup/Environment
- ProcessWire version: 2.8.35
### Notes

Discussed briefly before: 
- https://processwire.com/talk/topic/3474-admin-custom-pages-module/?do=findComment&comment=56409
- http://processwire.com/talk/topic/4650-new-processwire-admin-theme-on-dev-branch/?p=55635

More context of ProcessDocumentation
- https://processwire.com/talk/topic/14479-process-module-adding-items-to-sidebar-template-without-file/#comment-130849

I've achieved these documentation pages in the past with "duplicate" pages, parent being the ProcessDocumentation and child page with template=documentation where the actual content is. I'd like to avoid having to keep creating two pages for every new documentation page, though, which has led me to dig into this further.

**Comment by Toutouwai** [comment]
I think the path for adminTemplates is being reported correctly, but it's a legacy thing that isn't used in recent versions of PW.

For some time now the core admin themes have been modules. If you want the path to AdminThemeReno then it's `$config->paths->AdminThemeReno`

**Comment by ryancramerdesign** [comment]
An admin theme has to be loaded in order to populate that particular $config property. It is determined from the user's profile when the PW admin is serving a request. If you are on the front-end, then no admin theme is loaded or applicable. Like with what @Toutouwai mentioned, if you are outside of the admin context (like in a front-end template file), you'd have to specify which admin theme you want to point to.

**Comment by gRegorLove** [comment]
I will try some more things to see if I can get this working. Wouldn't `$config->paths->adminTemplates . 'controller.php'` implicitly be the admin context, though? `$config->defaultAdminTheme` seems oddly named with this behavior, too.

**Comment by gRegorLove** [comment]
Changed to `require($config->paths->AdminThemeReno . 'controller.php');` in documentation.php but I get:

Compile Error: require(): Failed opening required '/usr/home/sfrbm/public_html/site/templates-admin/default.php' (include_path='.:/usr/local/lib/php') (line 174 of /usr/home/sfrbm/public_html/wire/core/admin.php)

**Comment by ryancramerdesign** [comment]
It sounds like you are doing this on the front-end, where no admin theme is loaded. So none of these things are going to be populated. AdminTheme modules only autoload if "template=admin", so you are loading it outside of the intended context, and I'm not positive it will work. 

You could try loading one via `$modules->get('AdminThemeReno');`. Following that, if it loads correctly, you should be able to access its path from the `$config->paths` as you were trying to do. But you may still run into problems as AdminTheme modules expect the current page to be using template "admin", and so if that's not the case then expected fields may not be present, causing errors. What might be better is for you to add your needed fields (from documentation template) to the admin template, and use that admin template for your page(s) instead.
