### ISSUE TITLE
RepeaterMatrix drag-and-drop indentation quirk

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#531]
Video:
http://www.youtube.com/watch?v=0st76xkvVKU

PW Latest as of 3/13/2018, Chrome latest, Windows 10

**Comment by ryancramerdesign** [comment]
Thanks for the videos, these are very helpful. I was able to duplicate the issue once I put the repeater field in a Fieldset. I've pushed a fix.
