### ISSUE TITLE
404 errors if in admin, editing page with repeater and chrome devtools open

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#532]
If you're (1) in the backend (2) editing a page with a repeater field and (3) have Chrome DevTools open, it will 404 on the following files

"GET /processwire/wire/modules/Inputfield/InputfieldFile/InputfieldFile.css.map HTTP/1.1" 404 355
"GET /processwire/wire/modules/Inputfield/InputfieldFile/vex-theme-default HTTP/1.1" 404 355
"GET /processwire/wire/modules/Inputfield/InputfieldFile/contents-inline.css.map HTTP/1.1" 404 355

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. Which version of PW, and any other factors you can think of?

**Comment by jlahijani** [comment]
It occurs when "enable css source maps" is checked in Chrome DevTools' settings, which is disabled by default.  This isn't a ProcessWire issue.  Closing.
