### ISSUE TITLE
Typo in panel.js

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#533]
In /wire/modules/Jquery/JqueryUI/panel.js, line 166, event "mouseut", should that be "mouse**o**ut"?

And some others...

Typo in /wire/modules/Page/PageFrontEdit/PageFrontEditConfig.php, line 50, word "be"
Doc-block typo in /wire/core/Config.php, line 124, word "substitutute"
Doc-block typo in /wire/core/AdminTheme.php, line 98, word "systme"
Wrong link in /site-default/modules/README.txt, line 72-74
Wrong link in /wire/modules/LazyCron.module, line 88, should be "https://processwire.com/api/modules/lazy-cron/"

**Comment by ryancramerdesign** [comment]
Thanks! I've pushed a fix for these.
