### ISSUE TITLE
Admin-Theme UiKit PageTree left: Pages in Pagetree doen't show all editing options

### ISSUE THREAD

**Issue by AndreasFaust** [processwire/processwire-issues#534]
### Short description of the issue

When I use Admin-Theme UiKit with the PageTree on left, the Home-page doesn't show the editing field "New" on mouse-hover. It is also not possible to empty the trash.

### Expected behavior

Normally it is possible to hover a page in the PageTree and get the full range of editing options.

### Actual behavior

Hovering the Home-page doesn't show "New".
Hovering the Trash-page doesn't show "Empty".

### Setup/Environment
ProcessWire 3.0.95

**Comment by ryancramerdesign** [comment]
Thanks @AndreasFaust I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@AndreasFaust Hello there. Could you close this issue if it is resolved to your satisfaction, otherwise post a reply so we know to keep it open and on the radar. Thank you!
