### ISSUE TITLE
Custom User Types, Page Edit vs. Profile Edit

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#538]
### Short description of the issue

Processwire utilizes a Profile Editing screen that differs a lot from the Page Edit screen.

Tab Groups are not visible and there is no "View" link. Several fieldtypes (mainly repeaters from what I have encountered) do not work as expected on Profile Edit.

For users without `page-edit` permissions that *do* have `profile-edit` permissions, the `$user->editUrl()` points to the Page Edit screen rather than the Profile Edit (which users with these permissions cannot access).

### Expected behavior

The Profile Edit and Page Edit should be exactly the same in functionality and structure.

### Actual behavior

- The editUrl sends Users without Page-Edit permissions to a 404 in admin
- On Profile Edit, Tab Groups do not show up and there is no View Link
- On Profile Edit, Repeaters loaded with AJAX cannot add new items (unless the User has Page-Edit permissions for the user-template being edited), and this seems to be a bug with [`InputfieldRepeater.module:627`](https://github.com/processwire/processwire/blob/dev/wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module#L627)

### Optional: Screenshots/Links that demonstrate the issue

I've gone into fine detail here: https://processwire.com/talk/topic/18712-custom-user-types-page-edit-vs-profile-edit/

### Optional: Suggestion for a possible fix

I would suggest using the *exact same code* for Profile Edit and Page Edit. If they are to be seen as different by URL, the `editURL()` and `editable` calls need to be able to differentiate between **/access/users/edit** and **/profile/**.

### Steps to reproduce the issue

1. Create a new User Type
2. Create a new role with Page-View and Profile-Edit permissions
3. Create a new user, give them that new role
4. Put a call on the frontend to `$user->editUrl()`.
5. Click the link and you will see the admin equivalent of a 404.
6. Add a repeater field to the new User Template
7. Navigate to `/admin/profile` and try to add a new Repeater Item (without giving the user Page-Edit access)

### Setup/Environment
* ProcessWire version: 3.0.96

**Comment by ryancramerdesign** [comment]
I think you may be thinking of the profile editor as being equivalent to a page editor, but it's really quite different by intention. The profile editor is a really locked down process, and it's not intended to do everything the page editor can do. At the same time, it offers more security than the page editor could. It is intentionally limited for security reasons, because it can be accessible to non-trusted users. It's primary purpose is to allow password and email address changes, though it supports several other fieldtypes that you can add by name to ProcessProfile module config. 

There is no view link because this is not intended as a page editor, just a profile editor. User pages generally aren't viewable anyway. Tabs are not supported in the user profile, though fieldsets should be. 

Repeatable page types support (like repeaters) is limited because repeaters are pages and thus require page-edit permission (and access to ProcessPageEdit), which the user may or may not have. A user does not have page-edit permission to any user page unless they have user-admin permission or page-edit permission to the User template. That's because users may have access to edit their profile, that don't have access to edit any pages. So you can have access to edit your profile, without having access to edit your User page. Anything that uses external pages (Repeater, RepeaterMatrix, PageTable, FieldsetPage) is fine to have on a User template, but probably not going to be useful on the profile edit. 

Regarding $page->editUrl(), this is not contextual to the current user. It is contextual to the page it is called from, and is often used in things like admin notification emails, log entries, and such. It simply represents the URL to edit the page, and doesn't say anything about whether the user has access to edit the page. There isn't any instance where it would point to the profile editor, because that does not represent the editor for a page.

**Comment by ethanbeyer** [comment]
Ah, @ryancramerdesign thank you for weighing in!

I appreciate the explanation on the differences between the Profile and Page Edit screens - I see where you're coming from with Security! That makes sense. There are a few places I am losing the plot though, and if you'll allow me these arguments, please do not think I am being hateful in any way. I love Processwire very much and am hoping to help make it better, or at the very least understand how to solve specific problems by using it.

So here are the issues I take with keeping Profile and Page Editors separate in the exact state that they are currently in:

1. There are times when a User = Content. I don't know how to lock a single page down to be editable by only a single user, outside of the Profile Editor. It's already there, and that's why I chose to use it. If there's a way to do this, where User A can only edit Page A and Page A can only be edited by User A and Directory Admins, I'd probably have no further problem...

2. The main issue with Repeaters on the Profile page is when they're generated via AJAX. If they're not generated via AJAX, a user could add as many new items as they so chose, save their profile, and then add the info to the new Repeater Pages - so I am arguing in defense of making what's already possible more streamlined.

3. I wasn't aware of the fact that the editUrl wasn't contextual - because everywhere I've seen or used the `$page->editURL()`, it's wrapped in a `$page->editable` check. So I wrongfully assumed that the Permissions check == a Permissions URL. I see that it doesn't - but I now see the need for something like `userEditUrl()` that *would* be contextual. Again, I am speaking based on this limited use-case where I am building a directory - but there are plenty of times when I have built sites that displayed Users and there was a need for an Edit link. And if the person is only able to edit their own information, it would make sense to be able to get that Edit URL dynamically, rather than hardcoding `$config->urls->admin  . 'profile/'`.

I am afraid I am rambling, just trying to sort this whole issue out.

**Comment by ethanbeyer** [comment]
Is there a way outside of `profile-edit` to allow a user to edit their own page? It seems like if a User is a Page (outside of /admin/access), giving them the ability to edit their own page with `page-edit` is only possible if that user also has `user-admin`.

Am I wrong?

**Comment by ethanbeyer** [comment]
Wanted to weigh in again, due to @gebeer and I talking about it on the forums.

One of the reasons I don't want to give directory-members Page Edit permissions is because then they have access to the entire Page Tree, which is not desired at all.

**Comment by ethanbeyer** [comment]
Continuing to research and tinker, and maybe this course of action would allow for a fix:

Add a new Core permission: `profile-page-edit`. Why?

- Right now a Member that I want to give Page Edit access to their own profile has to have `page-edit` and `user-admin` permissions, which is too broad (full page tree + other user's profiles), but
- `profile-edit` permissions don't give the full level of access I'd like.

Right now I'm stuck in the middle, and a lot of seems to be as a result of ProcessPageEdit::___loadPage(). Specifically [this bit](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module#L384:L402):

```php
if($page instanceof User) {
    // special case when page is a User
    
    $userAdmin = $user->hasPermission('user-admin');
    $field = $input->get('field') ? $this->wire('fields')->get($input->get->fieldName('field')) : null;
    
    if($userAdmin && $this->wire('process') != 'ProcessUser') {
        // only allow user pages to be edited from the access section (at least for non-superusers)
        $this->wire('session')->redirect($config->urls->admin . 'access/users/edit/?id=' . $page->id);
        
    } else if(!$userAdmin && $page->id === $user->id && $field && $config->ajax) {
        // user is editing themself and we're responding to an ajax request for a field
        /** @var PagePermissions $pagePermissions */
        $pagePermissions = $this->wire('modules')->get('PagePermissions');
        $editable = $pagePermissions->userFieldEditable($field); 
        // prevent a later potential redirect to user editor
        if($editable) $this->setEditor = false;
    }
}
```

If that was rewritten to use the `profile-page-edit` permission like this, I think this issue would be solved:

```php
if($page instanceof User) {
    // special case when page is a User
    
    $profilePageEdit = $user->hasPermission('profile-page-edit');
    $userAdmin = $user->hasPermission('user-admin');
    $field = $input->get('field') ? $this->wire('fields')->get($input->get->fieldName('field')) : null;
    
    if($profilePageEdit && $page->id === $user->id) {
        // user is editing their profile AS A PAGE
        $this->page->setEditor($this->editor ? $this->editor : $this);

    } else if($userAdmin && $this->wire('process') != 'ProcessUser') {
        // only allow user pages to be edited from the access section (at least for non-superusers)
        $this->wire('session')->redirect($config->urls->admin . 'access/users/edit/?id=' . $page->id);
        
    } else if(!$userAdmin && $page->id === $user->id && $field && $config->ajax) {
        // user is editing themself and we're responding to an ajax request for a field
        /** @var PagePermissions $pagePermissions */
        $pagePermissions = $this->wire('modules')->get('PagePermissions');
        $editable = $pagePermissions->userFieldEditable($field); 
        // prevent a later potential redirect to user editor
        if($editable) $this->setEditor = false;
    }
}
```

Would that work, @ryancramerdesign ?

**Comment by ethanbeyer** [comment]
[Just realized](https://media1.giphy.com/media/Qb5AnG2cn5m1y/giphy.gifv) my directory member users won't be able to use the Focus+Zoom feature on `/admin/profile/`.

**Comment by gebeer** [comment]
@ethanbeyer you could implement that as a module that extends ProcessPageEdit. That way you can make things work without the need for changing the core process

**Comment by ethanbeyer** [comment]
@gebeer late on my reply, sorry!

I will probably have to. I've taken a look at the code you posted in the forums. To be honest, it's all a little over my head to work out how exactly to untangle this, otherwise I'd make much more of an effort to do so.

Thanks for all the work you've put in on this issue though!

**Comment by netcarver** [comment]
Moving this one to the request repo, we can continue the discussion over there.

/move to requests
