### ISSUE TITLE
Sanitizer::selectorValue stripping °

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#54]
### Short description of the issue

Sanitizer::selectorValue does strip ° characters even though there's no reason to. This will prevent finding things by values including this character.
### Expected behavior

`$sanitizer->selectorValue('°test'); // °test`
### Actual behavior

`$sanitizer->selectorValue('°test'); // test`
### Setup/Environment

- ProcessWire version: 2.7.3 & 3.0.36

**Comment by ryancramerdesign** [comment]
Thanks, I've opened up the allowed UTF-8 symbols further, which fixes this issue.
