### ISSUE TITLE
Repeater item labels double-encoded

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#542]
### Short description of the issue

Repeater item labels are being double-encoded.

In the screenshots below, the repeater contains the title field (which has the HTML Entity Encoder textformatter applied), and the "Repeater item labels" setting is {title}

![2018-03-16_175931](https://user-images.githubusercontent.com/1538852/37504536-d952c684-2943-11e8-998f-a0c6a4eabad0.png)

![2018-03-16_175524](https://user-images.githubusercontent.com/1538852/37504540-dc374c1c-2943-11e8-8457-342384fe9ad4.png)

### Setup/Environment

* ProcessWire version: 3.0.95
* (Optional) PHP version: 7.1

**Comment by ryancramerdesign** [comment]
I can't duplicate it here. Any other repeater settings vary from defaults?

<img width="287" alt="screen shot 2018-03-16 at 5 45 38 am" src="https://user-images.githubusercontent.com/328272/37514113-62ebe3d8-28dd-11e8-874d-4cab7e247919.png">

<img width="372" alt="screen shot 2018-03-16 at 5 45 14 am" src="https://user-images.githubusercontent.com/328272/37514118-668a98c2-28dd-11e8-81ca-e482e2816dab.png">

**Comment by ryancramerdesign** [comment]
Never mind, I just managed to duplicate it using a different character. Taking a closer look now. Thanks.

**Comment by ryancramerdesign** [comment]
Thanks, this issue is now fixed. The issue turned out to be that apostrophe is a numbered entity `&#039;` and the label rendering function was removing `#` from it, making it `&039;` which had the appearance of double encoding.

**Comment by Toutouwai** [comment]
Thanks for the speedy fix!
