### ISSUE TITLE
FieldsetTab in User template not visible to non-superusers

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#544]
### Short description of the issue

If I create a fieldsetTab on the `user` template, it is not visible for non-superusers even though they have `user-admin` permission and can see all the fields on the main Content tab.

### Expected behavior

They should be able to see fieldsetTabs.
 
### Actual behavior

They can't see them.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks!
