### ISSUE TITLE
getLines for a logfile ignores dateFrom option

### ISSUE THREAD

**Issue by brlnr23** [processwire/processwire-issues#548]
### Short description of the issue
Calling getLines for any logfile ignores the dateFrom parameter. Although it's set, the method returns all existing entries from the logfile. I am referring to the available options mentioned on that [page](https://processwire.com/api/variables/log/)

### Expected behavior

When passing dateForm as option lines from log after that date should be returned.

### Actual behavior

dateFrom option is ignored and lines before the given date are returned as well.

### Optional: Suggestion for a possible fix

I debugged it a bit and figured out, that getLines calls $log-find($limit, $pageNum) but it doesn't pass the options array:
https://github.com/processwire/processwire/blob/master/wire/core/WireLog.php#L249
getEntries() a few lines below in the same class passes the $options array to the $log->find() method. Adding the options array returns the expected result for me, but maybe there's some more I currently don't see ;)

### Steps to reproduce the issue

1) check in PW admin interface that "errors" log exists and that it's not empty
2) call $this->log->getLines("errors", array("dateFrom" => time()));
3) check if/which lines has been returned

### Setup/Environment

* ProcessWire version: 3.0.62

**Comment by ryancramerdesign** [comment]
Thanks @brlnr23 that's some good debugging! You are right, it was simply missing the options array. I have pushed your suggested fix.

**Comment by netcarver** [comment]
@brlnr23 Hi Chris. Could you close this issue if it is resolved to your satisfaction, otherwise post a reply so we know to keep it open and on the radar. Thank you!
