### ISSUE TITLE
Some pictures are squashed down to 20 pixels tall when cropping

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#549]
### Short description of the issue

When cropping an image in a modal with Admin UIKIT, some images are often just 20 pixels tall, making it impossible to resize them. It seems to happen mostly on Firefox, which is now my default browser. Sometimes closing the modal and opening it again fixes the issue, sometimes not. It doesn't happen on all images, so it looks rather random. 

### Expected behavior

Images are properly sized. 

### Optional: Screenshots/Links that demonstrate the issue

![20pixels](https://user-images.githubusercontent.com/1206842/37831872-2dfdd35a-2ea7-11e8-98e0-eb36a75613ce.png)

### Steps to reproduce the issue

1. Click on "Crop" to open a modal and crop the image 
2. See screenshot

### Setup/Environment

* ProcessWire version: 3.0.96 dev
* (Optional) PHP version: 7 
* (Optional) Any 3rd party modules that are installed and could be related to the issue: Croppable Image 3.

**Comment by ryancramerdesign** [comment]
So far I can't seem to duplicate this one (testing in Firefox 59.0.1). Do you find the issue seems to be related to the size of the image? For instance, do you still observe it when attempting the crop feature on a smaller image like 300x300? Also curious to know if you observe the same behavior on an installation not using Croppable Image? Thanks.

**Comment by jacmaes** [comment]
All images uploaded to that field are at least 900 x 500 pixels, so I wouldn't know if it also happens with smaller images. But I can give it a go. I'll also try on another image field without Croppable image. Thanks for looking into this. It seems pretty random, I'd say it happens about half the time. I've disabled my adblocker and Firefox's tracking prevention just in case it interfered somehow. I'll report back as soon as possible.

**Comment by ryancramerdesign** [comment]
Sounds good, thanks, please let me know what you find.

**Comment by netcarver** [comment]
@jacmaes Any update on your findings?

**Comment by jacmaes** [comment]
I'm still experiencing the issue, and it's still occurring randomly, although with less frequency. Let me try to pinpoint the problem once more before closing this issue.

**Comment by netcarver** [comment]
@jacmaes Jacques, any update?  If not, please would you close the issue. As you opened the issue, you will be able to re-open it when you do have more information to add.  Thank you!

**Comment by jacmaes** [comment]
I haven’t experienced the issue recently so I’m closing the issue.
