### ISSUE TITLE
Non-ansi non-existent urls get redirected to frontpage (not to 404 page)

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#55]
### Short description of the issue

Non-existent non-ansi urls (like /привет or /首次提交资源) get redirected to frontpage instead of a 404 page. The http code seems to be 404 as it should.
### Expected behavior

They must be redirected to 404 page with 404 http code.
### Optional: Suggestion for a possible fix

Must be something .htaccess related
### Setup/Environment

- ProcessWire version: Tried it on 3.35, 3.36, 3.37 (with no luck). On some earlier 2.x installs the issue does not exist.

**Comment by LostKobrakai** [comment]
It seems that this redirect is now an optional feature (with the new utf-8 support), as the .htaccess does not have knowledge about your installation using non-ascii urls or not: 

https://github.com/processwire/processwire/blob/master/htaccess.txt#L131-L138

**Comment by ivangretsky** [comment]
Does not look like a feature. It still has to check if a page with specific name exists (whether it is utf-8 or not). And it seems like it actually does that, as I get the 404 code (checked with http://web-sniffer.net/). The optimization feature in .htaccess must be for non-utf8-url-sites-only to avoid this check alltogether. The problem is it redirects 404 to the wrong place.

**Comment by ryancramerdesign** [comment]
What's happening is that characters in the URL are not in the pageNameWhitelist so ProcessWire isn't getting to see them at all. So it falls back to /index.php, which can't see the invalid chars. Something you can do to alter the behavior is to comment out this line at the top of your .htaccess file, by adding a "#" in front of it:
~~~~~
# ErrorDocument 404 /index.php
~~~~~
Or if you don't want the default Apache 404 showing, you can do this:
~~~~~
ErrorDocument 404 /index.php?it=/http404/
~~~~~
Maybe that should be our default, but there's a good chance that either of these suggestions may interfere with other things like secure page files and perhaps things like the redirects module. Still, if this is coming up as a recurrent problem on a site, this is what I'd recommend at the moment.

**Comment by teppokoivula** [comment]
@ivangretsky, just following up on this one: was the problem solved and can this issue be closed, or is there still a problem to solve here?

**Comment by netcarver** [comment]
@ryancramerdesign Does this need revisiting, especially in light of the suggested .htaccess fix likely interfering with redirects modules/secure page file - or does it need a "resolution: not a bug" label applied to it?

**Comment by ryancramerdesign** [comment]
@netcarver I'm not sure this is still an issue, at least I cannot duplicate it anymore. I must have run into it and found another solution at some point, though I don't remember that. Are you (or anyone else) able to duplicate using current PW master or dev?

**Comment by teppokoivula** [comment]
Tested on a couple of sites, but so far no luck duplicating this one. On my sites this seems to work just fine.

**Comment by netcarver** [comment]
@ryancramerdesign @ivangretsky @teppokoivula @LostKobrakai Ok, I intend revisiting this next week. If no one can duplicate by then, I'd like to close this issue unless anyone objects.

**Comment by ivangretsky** [comment]
Just tested it on a couple of recent sites and it does seem to be fixed. Tested on some older ones, and it is present there. Seems like they need upgrade.

Thanks!
