### ISSUE TITLE
Pages::trashed and Pages::restored hooks called twice

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#551]
### Short description of the issue

When you hook into Pages::trashed or Pages::restored, the hooks are invoked twice. This can be tested by adding simple hooks that output (unique, i.e. append a random number to avoid collapsing of entries) a simple message to the log or session.

### Expected behavior

Hooks should only be called once for each operation on a page.

### Example that demonstrates the issue

```php
// site/ready.php
wire()->addHookAfter(
	"Pages::restored(template=forum-thread)",
	function(HookEvent $event) {
		$this->log->save(
			"forumhooks",
			"Pages::restored(template=forum-thread) " . rand(1,9999999)
		);
	}
);
```

#### Screenshot:
![Screenshot](https://user-images.githubusercontent.com/3358724/37875423-3f7bb1f8-303f-11e8-95fb-084735aaa7d1.png)

### Suggestion for a possible fix

The fix should be easy (unless I'm missing some side effect): there is already loop prevention built into PagesTrash in form of the $save argument to PagesTrash::trash and PagesTrash::restore. This should also be added as an if-condition to the invocation of Pages::trashed ([this line](https://github.com/processwire/processwire/blob/4551748659f933641dcd0a6a5e2ee16c5a518f5e/wire/core/PagesTrash.php#L75)) and Pages::restored ([this line](https://github.com/processwire/processwire/blob/4551748659f933641dcd0a6a5e2ee16c5a518f5e/wire/core/PagesTrash.php#L135)) of PagesTrash.php.

```php
/* L75 */
		if($save) $this->pages->trashed($page);
/* L135 */
			if($save) $this->pages->restored($page);
```

The fix for trashing appears to work both for the page tree action and for trashing in the page editor.

* ProcessWire version: 3.0.96@dev

**Comment by ryancramerdesign** [comment]
Thanks @BitPoet that's a good find, as well as a good fix—this has been added.

**Comment by BitPoet** [comment]
Thanks for the quick fix!
