### ISSUE TITLE
Tab fields not working in profile edit screen

### ISSUE THREAD

**Issue by gebeer** [processwire/processwire-issues#552]
### Short description of the issue
Custom Tab fields in user templates are not being displayed correctly on the profile edit screen:

### Expected behavior
Tabs show correctly as in the page edit screen 
![2018-03-26-12 12 05](https://user-images.githubusercontent.com/3088950/37887975-fd9679d4-30ee-11e8-812c-a1ad8dc3943a.png)

### Actual behavior
Tabs display as normal fieldsets
![2018-03-26-12 10 17](https://user-images.githubusercontent.com/3088950/37887937-cae83c8e-30ee-11e8-87c7-a3ff3710335e.png)

### Steps to reproduce the issue
1. add a FieldsetTabOpen and FieldsetTabClose to the user template 
2. add some custom fields inside the tabs
3. configure module ProcessProfile to include the tabs and custom field on the profile edit page
4. Go to profile edit screen

### Setup/Environment
* ProcessWire version: 3.0.96
* (Optional) PHP version: 5.6

**Comment by gideonso** [comment]
I do the same and it is no problem at all.

![tabs](https://user-images.githubusercontent.com/16899800/37892110-43dd6bf4-3109-11e8-9bd4-4906b383be17.png)

**Comment by gebeer** [comment]
@gideonso your screenshot looks like you are not on the profile edit screen but on Access->Users->user
Edit from /youradminurl/profile and you will see that tabs are not working

**Comment by gebeer** [comment]
I just got pointed to https://github.com/processwire/processwire-issues/issues/538 from the forum and saw Ryan's comments there.

Still I do not understand why displaying tabs could be a security issue.

**Comment by ryancramerdesign** [comment]
In the case of tabs it's not a security issue. It's just that the Profile editor doesn't have tab support. If present, they would render as fieldsets in ProcessProfile. The page editor needs tabs because it has specific Content, Children, Settings, and Delete tabs. None of these are applicable to the Profile editor, which is just a single screen. There's quite a bit of code involved to convert TabOpen/TabClose fields to InputfieldWrapper.WireTab elements, and that isn't present in ProcessProfile at this time. Feasibly it could be added, but it's one of those things that would take a lot of code to accomplish and I'm not sure it's worthwhile at this point. If a lot of people need it down the road we can always add it.

**Comment by szabeszg** [comment]
> If a lot of people need it down the road we can always add it.
I would like to use them too if it was possible.
Anyone also needing it can +1 this post in order to see the interest :)

**Comment by teppokoivula** [comment]
@szabeszg made it here first, but I've also had a similar need.

> There's quite a bit of code involved to convert TabOpen/TabClose fields to InputfieldWrapper.WireTab elements, and that isn't present in ProcessProfile at this time. Feasibly it could be added, but it's one of those things that would take a lot of code to accomplish and I'm not sure it's worthwhile at this point.

Isn't there a way to abstract the code mentioned above, so that tabs could be used in Page editor, Profile editor, and potentially elsewhere as well? Not sure what that "elsewhere" would include, though.. but front-end use maybe? Just thinking out loud here :)

**Comment by ethanbeyer** [comment]
@teppokoivula I've been hoping for some of that abstraction in #538 as well; there's a lot of code that handles ProcessPageEdit and ProcessProfileEdit, and I can see the necessity behind their separation, but I would love if the ProfileEdit was as and built the same way as PageEdit.

**Comment by gebeer** [comment]
@ryancramerdesign Thank you for the explanation.
After reading your comment on #538 I understand that the profile edit screen is not meant to be used as a fully featured page edit screen.
But still, for directory type of sites where lots of users log on to edit their personal data, the profile edit process would be a safe place to do that. Since it is lacking a lot of functionality from the page edit process, we currently need to workaround for those scenarios which involves quite a lot of planning and coding.
Also, sending users to the page edit screen at /access/users/edit/?id=xxxx is not so nice because they might get the idea to change the id param in the URL and see what happens etc. So we need to cater for that and keep the users out of parts in the backend with redirection hooks or the like.
To avoid this, I tried to execute the page edit process under a custom URL in a custom process module, but couldn't get that to work either [see forum post here](https://processwire.com/talk/topic/16431-process-module-user-edit-page-under-custom-url/) because of the redirection happening in ProcessPageEdit::___loadPage().
It would really be nice to be able to have a safe place in the backend where users can edit their profiles with all functionality that the page edit process brings.

**Comment by Backoo** [comment]
I add myself to the list of people saying that it would be appropriate to allow logged in users to edit their profile almost the same way as they can make with other PW pages. Hoping to get a (definitive) solution, I posted on the PW forum for this: https://processwire.com/talk/topic/20231-how-should-i-allow-users-to-edit-their-profile/

**Comment by netcarver** [comment]
@ryancramerdesign Ryan, should this be considered a feature request?

**Comment by ryancramerdesign** [comment]
@netcarver Yes, I think this would be fine in the feature requests. If we do a rewrite of the ProcessProfile module at some point in the future then we could add support for these tabs. I usually search the requests repo when doing any major refactoring of any particular module/class.
