### ISSUE TITLE
Hint in AdminThemeUikit Config -> Primary CSS file path

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-issues#553]
Modules->Core->AdminThemeUikit->Custom files->Primary CSS file 
The hint says:
"When blank, the default file used.
site/modules/AdminThemeUikit/uikit/dist/css/uikit.pw.css"

this is not the file which is actually used. Should be:

wire/modules/AdminTheme/AdminThemeUikit/uikit/dist/css/uikit.pw.min.css

ProcessWire 3.0.94

Thank you.

**Comment by ryancramerdesign** [comment]
Thanks, this has been fixed.

**Comment by theo222** [comment]
Thank you.
