### ISSUE TITLE
wireIncludeFile() paths bug on Windows

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#554]
### Short description of the issue

`wireIncludeFile()` has some default paths to look for files. But they do not work due to hard coded `:/` check ([see here](https://github.com/processwire/processwire/blob/dev/wire/core/WireFileTools.php#L718)). It should be `:\` on Windows and some kind of `'\'  . DIRECTORY_SEPARATOR` to be universal. The script throws an error due to unwanted addition of `./` to the path.

Probably the same applies to some other checks in the `WireFileTools` class.

### Setup/Environment

* ProcessWire version: 3.0.96

**Comment by matjazpotocnik** [comment]
Also, problems might arise on windows if $filename is a relative path (`..`) due to the realpath() call in line 706.

**Comment by ryancramerdesign** [comment]
Thanks, I've attempted a fix and have pushed it to the dev branch, but don't have a good way to test it. Please let me know how it works.

**Comment by netcarver** [comment]
@ivangretsky Hello Ivan. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.

**Comment by ivangretsky** [comment]
Good day!

Sorry for not revisiting this earlier. I was just about to complain it does not work, as I thought `site/templates` should be in the include path as for render(). But is explicitly said in the [docs](https://processwire.com/api/ref/files/include/) include() looks for files either in the current dir or accepts absolute path.

I think we can close this, thanks!
