### ISSUE TITLE
Submit button floats to wrong position when last field is not 100% wide

### ISSUE THREAD

**Issue by guyinpv** [processwire/processwire-issues#555]
Simple style issue, nothing more.

When I set up fields on a template and set the very last field in the list to be 50% wide or anything other than 100% wide, the submit button on the page will float up next to the last field instead of being under it. This will be clear in the screenshot.

### Suggestion for a possible fix

Clearing floats or some other kind of style fix so that the submit button stays under the field list.

PW version (latest version freshly installed) 3.0.96

![processwire bug](https://user-images.githubusercontent.com/708955/38103681-e8547f86-333b-11e8-813e-fe206248f7f2.png)

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@guyinpv Hello Zack. Could you close this issue if it is resolved to your satisfaction, otherwise post a reply so we know to keep it open and on the radar. Thank you!

**Comment by guyinpv** [comment]
I installed 3.0.98 and don't see this issue any more.
Thanks.
