### ISSUE TITLE
Cloning an image that ends with -0 in the filename does not work

### ISSUE THREAD

**Issue by td-marc** [processwire/processwire-issues#556]
### Short description of the issue

I use the API to copy an image from one field to another on the same page. Like so:

       // Get the image we want to copy.
       $original = $page->images;
       $file = $original->getFile($original->first()->basename);
       // Clone that image and append it to the image_thumb field.
       $new = $original->clone($page->images->first(), array('action' => 'append', 'pagefiles' => $page->image_thumb));
       $page->save();

### Expected behavior

First image from field 'images' should be copied to field 'image_thumb'.

### Actual behavior

If the image has a filename like myimage-0.jpg, nothing is cloned.

### Optional: Suggestion for a possible fix

In \wire\core\Pagefiles.php, if the script encounters a file that ends with -0, turn it into -1. On line 495 I added this small fix:

`if ($n === 0) $n = 1;`

### Steps to reproduce the issue

1. Upload a file/image that ends with -0 in the filename.
2. Use the API to clone that file.

### Setup/Environment

* ProcessWire version: 3.0.96

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix to this.

**Comment by netcarver** [comment]
@td-marc Hello. Could you close this issue if it is resolved to your satisfaction. Thank you!
