### ISSUE TITLE
Is there a limit for images?

### ISSUE THREAD

**Issue by dauni** [processwire/processwire-issues#557]
### Short description of the issue

Fresh empty standard-installation of 3.0.96. Created a page with title, body and images (array with limit=0). Added 208 images, which works (Thumbs will be generated), but saving the page, actually does not saves anything. After a page rolad, processwires deletes all images. If i add the images in stages with small sets, i can add more than 100 images. The system should warn the user, if there is a limit.
If i add a large number of images there will not be saved anything. A click on the save-button reloads only the page.

### Expected behavior

There should be an error message, if such an operation fails. Or at least an entry in the exception-log

### Actual behavior

Click on save seems to work, but with debug=on there is no message "session: saved" when adding a large amount of images. It saves nothing.

### Steps to reproduce the issue

1. Add a large amount of images to a page
2. Click on save
3. Reload the page

### Setup/Environment

* ProcessWire version: 3.0.96
* (Optional) PHP version: 7.0.28
* (Optional) MySQL version: MariaDB 10.0.34 / InnoDB
* (Optional) Any 3rd party modules that are installed and could be related to the issue: -

**Comment by Toutouwai** [comment]
This issue is related to your PHP configuration setting rather than being a PW issue as such.
You'll need to increase max_input_vars in your PHP configuration.
http://php.net/manual/en/info.configuration.php#ini.max-input-vars
https://stackoverflow.com/a/14166562

**Comment by dauni** [comment]
Ah - OK,
changed max_input_vars from 1000 to 3000 and now it works.
I think, some warning message or log entry should be nice

**Comment by LostKobrakai** [comment]
The problem with having an error is that PHP will silently drop any access input variables, so ProcessWire won't ever notice the missing data.

**Comment by dauni** [comment]
Hm, i think it should be possible to read the value of max_input_vars and compare it with the count of inputs before saving, but this is surely not a common problem
