### ISSUE TITLE
filemtime(): stat failed – ProcessLanguage.module

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#558]
### Short description of the issue

Checking for file-stats on non existing files:
filemtime(): stat failed

/home/httpd/vhosts/icf.church/httpdocs/equip/wire/modules/LanguageSupport/ProcessLanguage.module in handleError at line 228

https://sentry.io/share/issue/da3c9a65d8dd4c2eb52cc8d51ce81aa7/

### Expected behavior

There should be a check if the file exists:

### Actual behavior

There is an exception:
https://sentry.io/share/issue/da3c9a65d8dd4c2eb52cc8d51ce81aa7/

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

```
if(is_file($pagefile->filename)){
   $lastMod = date($this->config->dateFormat, filemtime($pagefile->filename)); 
}
```

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.94 <br />
PHP: 7.1.16 <br />
Webserver: Apache <br />
MySQL: 5.5.56-MariaDB <br />
 <br />
</details><details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 120 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 120 <br />
max_input_vars: 20000 <br />
memory_limit: 256M <br />
post_max_size: 1G <br />
upload_max_filesize: 1G <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.8.0 <br />
AdminPageFieldEditLinks: 3.1.0 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldDescriptionsExtended: 1.0.2 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FrontEndEditLightbox: 1.3.6 <br />
IcfAttachments: 0.0.1 <br />
IcfAuth: 0.0.1 <br />
IcfDownloads: 0.0.1 <br />
IcfFeaturedImage: 0.0.2 <br />
IcfRangeDownload: 0.0.1 <br />
IcfTemplateTranslations: 0.0.1 <br />
IcfUnsplash: 0.0.2 <br />
IcfUtil: 0.0.1 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
Oauth2Login: 0.1.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.1.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.9.25 <br />
WireMailMandrill: 0.0.1 <br />
</details>

**Comment by ryancramerdesign** [comment]
Thanks, it looks like that $lastMod wasn't even in use anymore, so I have just removed the line.

**Comment by netcarver** [comment]
@noelboss  Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!

**Comment by netcarver** [comment]
@noelboss Hello again. I intend closing this issue in a week or so if I've not heard anything back from you - or anyone else - about it by then.

You can always re-open this issue later if you need to.

**Comment by noelboss** [comment]
Looks good, thanks @netcarver & @ryancramerdesign
