### ISSUE TITLE
bilingual page and _init.php

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#559]
My page is bilingual, german (main language) and english. I have a file _init.php with 
`$title = $page->get('headline|title'); ` and in my template
`echo '<h4>'.$title.'</h4>';`

the _init.php file is included in config.php:
`$config->prependTemplateFile = '_init.php';`

### Short description of the issue

This works well in german, but not in english, where the german headline appears. The rest of the page is english, so everything else is ok.
Fun fact: if I put `$page->get('headline|title')` directly in the template (i.e. `echo '<h4>'.$page->get('headline|title').'</h4>';`) , the english headline is also there.

* ProcessWire version: 3.0.97
* PHP version:  7.0.27

**Comment by netcarver** [comment]
@beatep Hi Beate, is this still an issue for you?

**Comment by beatep** [comment]
Just tested it on 3.0.112, and it works. I'll close it.
