### ISSUE TITLE
PageTree Drag 'n Drop Bug, Move as child if no child exists

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#562]
### Short description of the issue

If you want to move a page in the Admin PageTree as a child of another page, this only works if the new parent page already has a child. If you want to move the page to a page that does not yet have any child pages, this does not work. See the following screencast:

![ezgif com-optimize](https://user-images.githubusercontent.com/708183/38568660-7a17be36-3ce9-11e8-9e08-f3800a401745.gif)

### Expected behavior

I should be able to move a page as a child if the parent page does not yet have children.

### Steps to reproduce the issue

1. Try to move a page as a child to another page that does not yet have a child page.

### Setup/Environment

* ProcessWire version: 3.0.97
* (Optional) Any 3rd party modules that are installed and could be related to the issue: AdminThemeReno

**Comment by Toutouwai** [comment]
To move a page by drag-and-drop you have to use the same procedure regardless of whether the new parent page has children or not.

1. "Expand" the desired parent page by clicking on it. If the parent has children then they will be revealed.
2. Click "Move" on the page you want to move.
3. Drag the page to the expanded parent.

So in your screencast you are missing step 1.

**Comment by FlipZoomMedia** [comment]
Haha, oh, my God. :laughing: I have been using ProcessWire for years and neither I nor my customers have understood it to this day. Thank you. :wink:

If you know it, it's logical. But maybe this could be improved from the UX point of view, that when hovering over the parent element, this selection takes place automatically?

**Comment by LostKobrakai** [comment]
But only with a really long time to trigger that, because you don't want to accidentally open a parent, which was closed, but does have the whole 50 children of whatever the limit of the page tree is.

**Comment by FlipZoomMedia** [comment]
Yes, absolutely. I think a hover time of 1 to 2 seconds would be a good one until the parent is selected automatically.

**Comment by rolandtoth** [comment]
Shame but I didn't know that trick either :)

However, I've experimented with such a feature back then:
https://processwire.com/talk/topic/13389-adminonsteroids/?do=findComment&comment=128776

It worked almost fine, there were smaller glitches though I couldn't fix, mainly because lack of time.
(and nerves :))

**Comment by FlipZoomMedia** [comment]
@rolandtoth Wonderful! This looks like a very natural handling! I hope we can integrate this into PW.

**Comment by szabeszg** [comment]
Expanding the tree automatically on hover works when there are only a few children to expand. When you have a lot it can be frustrating that they take up so much space of the viewport that the browser cannot actually show you the target which happens to be outside of the current viewport.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
@netcarver I'd like to leave this one at the current and intended behavior for now, as it's not technically a bug. I do like the suggestion but just think it might take a lot of figuring out, testing and debugging, so probably belongs in the feature requests instead. Thanks.
