### ISSUE TITLE
InputfieldSelector gives incorrect matches count when "custom (field = value)" option is used

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#565]
### Short description of the issue

InputfieldSelector gives an incorrect matches count when "custom (field = value)" option is used.

In the screenshot below the correct matches count should be 3.

![2018-04-16_102059](https://user-images.githubusercontent.com/1538852/38784056-2bfcc4e6-4160-11e8-80fa-15e0c59938e7.jpg)

### Suggestion for a possible fix

Specify the `allowCustom` option for PageFinder in [InputfieldSelector::renderTestSelector](https://github.com/processwire/processwire/blob/566d60b15226d53a68574dff41f1afd13ab5da29/wire/modules/Inputfield/InputfieldSelector/InputfieldSelector.module#L713).

```php
$cnt = $this->wire('pages')->count($selector, array('allowCustom' => true));
```

With this change the matches count is correct;

![2018-04-16_102127](https://user-images.githubusercontent.com/1538852/38784081-a51556b8-4160-11e8-98e2-60640d67bc88.jpg)

### Setup/Environment

* ProcessWire version: 3.0.98

**Comment by ryancramerdesign** [comment]
Thanks, nice job finding that. I've pushed your suggested fix.

**Comment by Toutouwai** [comment]
Thanks.
