### ISSUE TITLE
AdminThemeUikit: admin search prevents default link click behaviour

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#567]
### Short description of the issue

In AdminThemeUikit, when a link in the autocomplete search results dropdown is clicked the default behaviour is prevented and the browser is redirected to the link href via Javascript. This prevents the normal Ctrl-click behaviour for opening the link in a new tab.

This issue has been introduced in AdminThemeUikit - the other core admin themes do not interfere with a link click in this way.

### Steps to reproduce the issue

1. Ctrl-click a link in the admin autocomplete search results. 
2. Note that no new tab is opened and the active tab navigates away from the current page.

### Optional: Suggestion for a possible fix

Check that the link selection event is one that originated from a key press before doing `event.preventDefault()`, etc. Replacing [this section](https://github.com/processwire/processwire/blob/19f557b487967630ebb40bb073390214caaee861/wire/modules/AdminTheme/AdminThemeUikit/scripts/main.js#L364-L374) with...

```js
select: function(event, ui) {
    $(this).val('');
    // follow the link if the Enter/Return key is tapped
    if(typeof event.key !== 'undefined') {
        event.preventDefault();
        if(typeof parent.isPresent == "undefined") {
            window.location = ui.item.edit_url;
        } else {
            parent.jQuery('#pw-admin-main')[0].contentWindow.document.location.href = ui.item.edit_url;
        }
    }
}
```

### Setup/Environment

* ProcessWire version: 3.0.98

**Comment by ryancramerdesign** [comment]
Thanks, another great find. I've pushed your suggested fix.

**Comment by Toutouwai** [comment]
Thanks.
