### ISSUE TITLE
InputfieldImage Crop/Focus/Variations buttons not visible when using RepeaterMatrix (user other that superadmin)

### ISSUE THREAD

**Issue by timso** [processwire/processwire-issues#570]
### Short description of the issue

When using Image Input Field user should be able to Crop (or Focus) using standard buttons. It's working correctly as long as field assigned directly to the template but when using RepeaterMatrix - those buttons disappeared. 

### Expected behavior

Crop / Focus / Variations buttons should be visible http://prntscr.com/j8yvys

### Actual behavior

Buttons are missing for users not having superadmin role when Image field used in RepeaterMatrix (works for direct assigment)

### Suggestion for a possible fix

Your possible fix goes here.

### Setup/Environment
ProcessWire 3.0.98

**Comment by Toutouwai** [comment]
@ryancramerdesign, this is another issue that seems to be due to non-superuser roles not having edit access for repeater item templates. If the role is given edit access for the template then the issue resolves.

Related: https://github.com/processwire/processwire-issues/issues/183

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this

**Comment by timso** [comment]
Thanks @ryancramerdesign !

I have updated my installation with latest DEV and issue is fixed now.

BTW.
Your fix also helped with other issue - non superuser member wasn't able to create new pages using templates having RepeaterMatrix fields assigned (even though proper access rights assigned) - after updated works well.
