### ISSUE TITLE
FieldsetClose - UIkit Admin Theme Error

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#571]
### Short description of the issue

When attempting to edit a FieldsetClose field on 3.0.99, an error is encountered:

### Expected behavior

Field editor is displayed

### Actual behavior

```
Error: Uncaught TypeError: Argument 2 passed to ProcessWire\AdminThemeUikitConfigHelper::configInputfield() must be an instance of ProcessWire\InputfieldWrapper, null given, called in .../wire/modules/AdminTheme/AdminThemeUikit/AdminThemeUikit.module on line 450 and defined in .../wire/modules/AdminTheme/AdminThemeUikit/config.php:362
Stack trace:
#0 .../wire/modules/AdminTheme/AdminThemeUikit/AdminThemeUikit.module(450): ProcessWire\AdminThemeUikitConfigHelper->configInputfield(Object(ProcessWire\InputfieldFieldsetClose), NULL)
#1 .../wire/core/WireHooks.php(822): ProcessWire\AdminThemeUikit->hookAfterInputfieldGetConfigInputfields(Object(ProcessWire\HookEvent))
#2 .../wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldFieldsetClose), 'getConfigInputf...', Array)
#3 .../wire/core/Field.php(1013): ProcessWire\Wire->__call('getConfigInputf...', Array)
#4 /var/www/processwire/w (line 362 of .../wire/modules/AdminTheme/AdminThemeUikit/config.php) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

### Steps to reproduce the issue

1. Create and save a new Fieldset in Tab (Open) field
2. Try to edit the automatically created "_END" field (FieldsetClose)

### Setup/Environment

* ProcessWire version: 3.0.99
* AdminThemeUikit 0.2.7

I'm not getting this on 3.0.98 Master, nor if I use the default PW theme.

Cheers,

Chris

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@chriswthomson  Hello again Chris. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!
