### ISSUE TITLE
PageFrontEdit Modal Close ->Page Refresh

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#574]
When i close a modal PageFrontEdit for an edited Pro Table field I do not see the changes unless I refresh the frontend page. Couldn't a refresh be a standard behavior?  (PW 3.0.98)

**Comment by ryancramerdesign** [comment]
I just tried that here, but it did refresh the Table field in my page after I hit save in the modal. When you click the Save button in the modal, it should save, close the modal and refresh the field. Check in: Setup > Fields > table_field > Input > Front end editing, and make sure you are using a supported option for front-end editing of a table field (option C or D). If so, can you post the exact code you are using to render the field? Also check if there are any other modules installed that might be manipulating the markup.

**Comment by tbba** [comment]
Sorry I could not reply earlier due to work.
I suspect now a mismatch between the modern front end jquery I use and stone-old jquery UI coming from the backend.

**Comment by matjazpotocnik** [comment]
> I suspect now a mismatch between the modern front end jquery I use and stone-old jquery UI coming from the backend.

This could well be the case. PageFrontEdit doesn't play well with Jquery 3 used on frontend. Try jquery migrate or use older jquery, like 2.4.1. There are other issues with PFE, see https://github.com/processwire/processwire-issues/issues/609

**Comment by tbba** [comment]
Im this case this is not a "bug" but a strong hint in the direction of mentioning that issue as "requirements" in the front editing manuals:
https://processwire.com/blog/posts/front-end-editing-now-in-processwire-3.0-alpha-4/
(I wonder when ProcessWire will start using updated jq libraries, but that is another subject :)

I am ready to close this now - should I post a note in the "wishlist" instead (about the mentioning of requirements for front editing - or is there such a hint and I overlooked it?)

**Comment by tbba** [comment]
I close this for now. Thanks for the feedback.
