### ISSUE TITLE
__debugInfo() for $input is empty

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#575]
### Short description of the issue

__debugInfo() for $input is empty

### Expected behavior

It should return an array of the data

### Actual behavior

It's blank - `print_r($input->post)` looks like this:

```
ProcessWire\WireInputData Object ( )
```
 whereas `print_r($_POST)` looks like this:

```
Array ( [messageId] => 1455 [allOrGroups] => single [singleUser] => ,1100 [testFromNumber] => [groups] => )
```

**Comment by ryancramerdesign** [comment]
Here's an alternative that bypasses the on-demand nature of WireInput and makes the debugInfo() load all the input data (not sure if this is a good thing for it to do, but might be more useful in debug data):
~~~~~~
	public function __debugInfo() {
		$info = parent::__debugInfo();
		$info['get'] = $this->get();
		$info['post'] = $this->post();
		$info['cookie'] = $this->cookie();
		$info['whitelist'] = $this->whitelist();
		$info['urlSegments'] = $this->urlSegments;
		$info['pageNum'] = $this->pageNum;
		return $info;
	}
~~~~~

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - the first one works well:

![image](https://user-images.githubusercontent.com/871211/39306251-7752ce02-4914-11e8-8441-3e49a1f3399c.png)

But the second doesn't seem to do anything useful. They're all empty objects:

![image](https://user-images.githubusercontent.com/871211/39306303-acf7182e-4914-11e8-9889-c251193b49d9.png)

**Comment by ryancramerdesign** [comment]
Sounds good, I'll add the first one. I forgot the getArray() calls on the second one. It should be this:
~~~~~~
	public function __debugInfo() {
		$info = parent::__debugInfo();
		$info['get'] = $this->get()->getArray();
		$info['post'] = $this->post()->getArray();
		$info['cookie'] = $this->cookie()->getArray();
		$info['whitelist'] = $this->whitelist()->getArray();
		$info['urlSegments'] = $this->urlSegments;
		$info['pageNum'] = $this->pageNum;
		return $info;
	}
~~~~~~

**Comment by adrianbj** [comment]
> I forgot the getArray() calls on the second one. It should be this:

Right - so of course now the second one works as expected. I honestly don't know at this point whether 2 has any advantages over 1 so I'll leave it to you, but maybe I'll experiment with 2 down the road if 1 isn't working as expected.

**Comment by adrianbj** [comment]
Thanks for adding this Ryan!

**Comment by ethanbeyer** [comment]
This is awesome - something I've wanted for a while now, too!

**Comment by adrianbj** [comment]
> This is awesome - something I've wanted for a while now, too!

I expect there are other PW objects that don't have __debugInfo defined, so please report them if you come across them. It's especially obvious to me now that Tracy uses this method as the default dump.

**Comment by ethanbeyer** [comment]
Pretty sure `Pagefiles` is missing it too. I ran into this with at least three different classes earlier this week, I just don't recall what the other two were right now. Will report back if I discover any others.

**Comment by adrianbj** [comment]
@ryancramerdesign - do you mind if I reopen this so that we can add to it for other objects that need their own debugInfo method?

**Comment by ryancramerdesign** [comment]
I've added custom __debugInfo() methods to the Pagefile(s) classes. It already had debugInfo but it was just inheriting the default WireArray debugInfo, which didn't do anything but show the filenames, so there was definitely room for improvement there.

**Comment by ethanbeyer** [comment]
U R A SAINT

**Comment by adrianbj** [comment]
This is brilliant Ryan - thanks for going the extra mile on files/images.

This is the result in the Tracy Request Info panel:

![image](https://user-images.githubusercontent.com/871211/39366622-4d8623b4-49e9-11e8-9c7f-972eda8152f6.png)

The only thing I am wondering about is the variations section. It seems to be showing PDF and PNG files for a PageImages object. You'll also notice that in the far right column, I also use `getVariations` and it's only showing the 266x260 thumbnail. Any idea why yours is showing the other non-image files?

**Comment by ryancramerdesign** [comment]
Adrian, I think I must have had the exit too early on the non-verbose getVariations() call (in isVariation method). Try the latest update, I think it should hopefully fix that.

**Comment by adrianbj** [comment]
Thanks Ryan - that looks better :)

**Comment by adrianbj** [comment]
Hi @ryancramerdesign - what do you think about something similar for repeater fields? It would be great to see the values for all fields within each repeater item.

**Comment by adrianbj** [comment]
@ryancramerdesign - I'd also love to see this for the SelectOptions field type. At the moment when you dump `$f->type->getOptions($f)` all you get is the ID of the option:

![image](https://user-images.githubusercontent.com/871211/39477364-ef4f5a12-4d13-11e8-9f85-d10bc6476482.png)

Can we get something more like this:

![image](https://user-images.githubusercontent.com/871211/39477420-1c0c4736-4d14-11e8-87a9-d0c61f181dba.png)

**Comment by adrianbj** [comment]
Hey @ryancramerdesign - I just discovered that while `print_r($input)` works well, `print_r($input->get)` is still empty. Do you think this could be fixed also please?

Is there any way that if the response to a `__debugInfo()` call is an empty object, that the full PW object for whatever is being dumped is returned instead because there are still lost of situations where `__debugInfo()` causes more harm than good.

**Comment by adrianbj** [comment]
Just noticed that for `$template`, it doesn't anywhere return the name of the template, eg:

![image](https://user-images.githubusercontent.com/871211/44355650-0a381d00-a462-11e8-9561-7bab4a42ec9a.png)

**Comment by netcarver** [comment]
Just noticed two other open issues regarding __debugInfo() magic methods #114 and #394. Is there any indication that the pushed code here might have solved those issues?

**Comment by adrianbj** [comment]
@netcarver - I don't think so - I think that xDebug issue is unrelated but don't quote me on that.

**Comment by ryancramerdesign** [comment]
@adrianbj @netcarver I have added the additional debugInfo for the classes requested here (Repeaters, SelectableOptions, $input->get, etc.).
