### ISSUE TITLE
Password autocomplete recent changes break Email New User module

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#576]
### Short description of the issue

Just adding here in case you missed my attempt to bump the already closed issue that caused the problem: https://github.com/processwire/processwire-issues/issues/537#issuecomment-383411262

**Comment by ryancramerdesign** [comment]
I've pushed your suggested update for this, though I actually can't seem to test that it still works in Firefox — it appears they might have fixed the underlying issue in Firefox. My copy of Firefox at least no longer tries to autocomplete the password field even if I comment out the entire block of code that was added for it.

**Comment by adrianbj** [comment]
Thanks Ryan!

Yeah, there might not be a need for that block of code at all anymore, although I haven't tested thoroughly to be certain. Thanks for this change though.
