### ISSUE TITLE
Performance and race condition problems when saving user templates that have different parent than default (users)

### ISSUE THREAD

**Issue by apeisa** [processwire/processwire-issues#58]
### Short description of the issue

We found performance and race condition problems when saving user templates that have different parent than default (users). These problems have two kinds of problems in our use case:
- they make saves very slow, since saveParents() is falsely triggered every time user template (in our case member) is saved
- they occasionally create PDO error when duplicate rows get inserted into pages_parents table

Problem is pretty simple: 
1. PW sets users-page (/processwire/access/users/) as parent on construct: https://github.com/processwire/processwire/blob/master/wire/core/User.php#L43
2. Then it is changed to real one when page is loaded from databases (in our case /entity/member/)
3. This causes that PW adds parentPrevious -property. This means that PW thinks that page has been moved.
4. Finally this causes saveParents() to trigger without any need for it

We do a lot of mass editing operations, so occasionally we have seen PDO errors when inserting duplicate rows into pages_parents table. 
### Expected behavior

saveParents() shouldn't be triggered, when page is not moved or cloned.
### Actual behavior

When page with different user template and parent is saved, PW always assumes it is moved from /users/ and for this reason makes multiple unnecessary DELETEs and INSERTs into pages_parents table.
### Optional: Suggestion for a possible fix

Default parent should be implemented in such a way that it takes care of the actual default for custom templates/parents. This line needs re-thinking: https://github.com/processwire/processwire/blob/master/wire/core/User.php#L43

Also saving into pages_parents table should make use of REPLACE or ON DUPLICATE KEY like PW does when saving into pages_access table.
### Steps to reproduce the issue

This one is easy to reproduce by setting up pw where it makes use of multiple parents and templates for users (https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users). Then with this script you see the unnecessary database operations:

```

$p = wire('pages')->get(2560); // 2560 is user with different template and parent
$p->title = "Blaa " . time();
$p->save();

foreach(wire('database')->queryLog() as $log) {
  if(substr($log,0,6) === 'SELECT') {
    continue;
  }
  echo $log . PHP_EOL;
}
```
### Setup/Environment

PW 3 master

**Comment by apeisa** [comment]
Little addition: race condition comes from the fact that saveParents() saves also grandparents, so in our case any entity that is saved also saves our root page /entity/. 

This can easily cause situation where two totally different pages are saved at the same time, and they save exactly same row into pages_parents table. For an example they try to save /entity/ as a parent for page /entity/member/.

**Comment by ryancramerdesign** [comment]
@apeisa I've pushed an attempted fix for this in the latest commit here: https://github.com/processwire/processwire/commit/ca5870b70c68fc4efc39f25a45cbb146ceb01630

I wasn't actually able to duplicate the issue even after setting up the same scenario and test script. But the way you've described it makes sense, so I had enough to go on either way. But since I wasn't seeing unnecessary pages_parents table updates or race conditions here, I'm also not able to confirm that the latest commit solves it. I was wondering if you could try out the changes and let me know if it fixes the issue there? Thanks.

**Comment by sforsman** [comment]
@ryancramerdesign This behavior happens only when the Page is located deep enough in the tree, for an example:

```
Home
* My Users
  * My Category 1
    * My User 1
```

**Comment by ryancramerdesign** [comment]
Thanks for reporting back @sforsman – glad to hear that fixed it. Please let me know if you run into any other issues with it.
