### ISSUE TITLE
ProcessUser.module:161 Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#580]
### Short description of the issue
$roles is defined as string. Should be an array.
https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessUser/ProcessUser.module#L156

https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessUser/ProcessUser.module#L161

**Comment by ryancramerdesign** [comment]
Thanks, good find—fixed.
