### ISSUE TITLE
$pages->clone() fails with error when template includes file/image field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#583]
### Short description of the issue

When attempting to clone a page (or page and children) via `$pages->clone()` the clone fails with an error if the page (or any of it's child pages) contains a File or Image field.

Error is:

> Exception: Can’t save page 0: /clone-me-1/: Call $page->of(false); before getting/setting values that will be modified and saved. [Page::statusCorrupted] fields: files (in D:\_Websites\_www\pw3-raw\wire\core\PagesEditor.php line 515)

### Steps to reproduce the issue

1. Create a File field (or an Image field).

2. Create a template and add the File field to the template.

3. Create a page using the template.

4. Attempt to clone the page via the API:

```php
$p = $pages(1234); // the page to be cloned
$pages->clone($p);
```
5. Observe the error.

As the error suggests, setting output formatting to false before attempting the clone does work. But this is not a solution if the page has children that contain a File/Image field. 

To test this, create a child page under the page to be cloned using the same template. Now even if output formatting is false for the parent and the children the clone fails.

```php
$p = $pages(1234);
$p->of(false);
foreach($p->children as $child) {
    $child->of(false);
}
$pages->clone($p);
```

> Exception: Can’t save page 0: /clone-me-3/clone-child/: Call $page->of(false); before getting/setting values that will be modified and saved. [Page::statusCorrupted] fields: files (in D:\_Websites\_www\pw3-raw\wire\core\PagesEditor.php line 515)

### Setup/Environment

* ProcessWire version: 3.0.100
* PHP version: 7.1

Related forum thread: https://processwire.com/talk/topic/19116-cloning-page-with-children-via-api-fails/

**Comment by denisurn** [comment]
I confirm, that I have the same issue.
I was unable to reproduce it in admin, though.
Unless I explicitly set output formatting to FALSE, the clone fails.
However, forcing output format for children does not help the issue, as this line
`$this->pages->save($copy, $options);`
resets it back to TRUE (for children), which is a bug in my opinion.

**Comment by ryancramerdesign** [comment]
At first I wasn't seeing the error, but once I enabled global output formatting state `$pages->of(true);` I was able to duplicate. Good find. I've pushed a fix for this issue. Thanks!

**Comment by Toutouwai** [comment]
Thanks for the speedy fix.

**Comment by denisurn** [comment]
Cheers!
