### ISSUE TITLE
clone_field value for Field persists in database

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#586]
### Short description of the issue

This is probably an issue of no real consequence, but I noticed that if a field has been cloned at some point in the past then the name of the new field that it was cloned to ("clone_field") persists in the field settings JSON in the database.

![2018-05-05_164010](https://user-images.githubusercontent.com/1538852/39659742-7015301e-5083-11e8-83fd-009b901a9ef5.png)

I thought the only purpose of the clone_field input was to put a value into $_POST so that ProcessField knows that the field should be cloned, and is not a setting belonging to the source field that should be kept in the database.

Or do I have that wrong and the source field has some ongoing connection to the cloned field?

### Expected behavior

Only needed settings are stored for the field in the database.

### Setup/Environment

* ProcessWire version: 3.0.100

**Comment by adrianbj** [comment]
I noticed this also, just yesterday :)

**Comment by ryancramerdesign** [comment]
Thanks I've pushed a fix. Properties that shouldn't get saved are supposed to be prefixed with an underscore, so I just renamed it to "_clone_field", and that seems to solve it. If you want to remove a "clone_field" property for some particular field, you can do so by doing Actions > Check field data.

**Comment by Toutouwai** [comment]
Thanks.
