### ISSUE TITLE
Pages > Recent > Created

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#587]
### Short description of the issue

**Pages > Recent > Created** should list created pages by all users, not only current user.

### Suggestion for a possible fix

remove `&me=1` from line 53

```
ProcessRecentPages.module

49	array(
50		'url' => '?added=1',
51		'label' => 'Created',
52		'icon' => 'users',
53		'navJSON' => 'navJSON/?added=1',
54	),

```

### Setup/Environment

* ProcessWire version: 3.0.98

**Comment by ryancramerdesign** [comment]
Thanks good find, I've pushed a fix for this.

**Comment by fijha** [comment]
Also the value `navJSON` needs to by escaped if there is a `&` character inside:

`AdminThemeDefaultHelpers.php` (line 411)
`AdminThemeUikit.module` (line 665, 747)

**Comment by netcarver** [comment]
@ryancramerdesign Just pinging this back to you as potentially needing further work.

**Comment by netcarver** [comment]
@ryancramerdesign Not sure if you spotted @fijha's follow-up point?

**Comment by ryancramerdesign** [comment]
Thanks @fijha @netcarver I have applied the suggested change.
