### ISSUE TITLE
AdminThemeUikit: .InputfieldFieldsetOpen class is not defined

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#588]
### Short description of the issue

`.InputfieldFieldsetOpen` class is missing from `uikit.pw.css ` causing the background of a fieldset to be white.

```
uikit.pw.css (line 14446-14449)

.InputfieldFieldset > .InputfieldHeader,
.InputfieldFieldset > .InputfieldContent {
  background: #f0f3f7;
}

```

### Optional: Suggestion for a possible fix

```
.InputfieldFieldset > .InputfieldHeader,
.InputfieldFieldset > .InputfieldContent,
.InputfieldFieldsetOpen > .InputfieldHeader,
.InputfieldFieldsetOpen > .InputfieldContent {
  background: #f0f3f7;
}
```

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this issue.

**Comment by netcarver** [comment]
@fijha Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!
