### ISSUE TITLE
WireDatabaseBackup->getAllTables() caching to static var maybe not applicable anymore with multi-instance support?

### ISSUE THREAD

**Issue by CanRau** [processwire/processwire-issues#59]
### Short description of the issue

Don't know if it's a multi-instance related bug or still valid

I tried to run 2 db backups one after another, making a backup if the host pw installation and one of the second instance (both run from the same core so it's multisite, too) the second backup tried to backup tables from the first instance which would result in errors as they differ..

As BitPoet pointed out it's because of the to caching of getAllTables()

As stated in the forum topic I got a workaround by explicitly providing the tables to be backed up like so
`$backup->backup(['tables' => $backup->getAllTables(false, false)]);`

I'm just posting here because it might be interesting to change this behaviour a little..
### Expected behavior

I expected it to just work as I instantiated the class two times, so I don't expect it to reuse the tables of the former instance..
### Actual behavior

Second instance used tables from first instance due to static caching
### Optional: Screenshots/Links that demonstrate the issue

forum topic
https://processwire.com/talk/topic/14608-solved-database-backup-of-main-pw-and-second-pw-instance/

getAllTables()
https://github.com/processwire/processwire/blob/master/wire/core/WireDatabaseBackup.php#L499
### Optional: Suggestion for a possible fix

Maybe just make them unstatic? or unset/re-init them in construct() ?
### Setup/Environment

- ProcessWire version: 3.0.35

**Comment by ryancramerdesign** [comment]
Thanks @CanRau I've pushed a fix for this issue. Please let me know if you run into any more trouble with it.

**Comment by CanRau** [comment]
great, works as expected now thank you ryan 👍
