### ISSUE TITLE
Main dropdown menu fix

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#590]
### Short description of the issue

When there is menu item loading and you quickly move to another item so now you have 2 or more items loading at the same time causing multiple menus to open after they load.

### Suggestion for a possible fix

```
/wire/templates-admin/scripts/main.js

367    if($ul.children().length) $ul.css('opacity', 1.0).fadeIn('fast');
```

**This fixed it:**

```
367    if($ul.children().length) $ul.css('opacity', 1.0);
368    if(hoveredDropdownAjaxItem == $a) $ul.fadeIn('fast');
```

**Comment by ryancramerdesign** [comment]
I have committed the change. Thanks!

**Comment by netcarver** [comment]
@fijha Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!
