### ISSUE TITLE
AdminThemeUikit: Don't hide masthead until PW loads (FOUC)

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#591]
### Short description of the issue

Not sure why the masthead depends on JavaScript and it's hidden until PW loads. I think there is no need for that.

### Suggestion for a possible fix

Remove this CSS rule from:

```
AdminThemeUikit/uikit/dist/css/uikit.pw.css (line 15312-15314)

body.pw-init #pw-masthead > * {
  display: none;
}
```

Add `uk-navbar` class to:

```
AdminThemeUikit/_masthead.php (line 23)

<nav class="uk-navbar-container uk-navbar-transparent uk-navbar" uk-navbar>
```

**Comment by ryancramerdesign** [comment]
Thanks, your suggestion does seem like an improvement here. Technically we are supposed to let Uikit populate that uk-navbar class. But it doesn't appear that it uses it to detect initialization, so looks like it will work! I have added this and it will appear in the next Uikit admin theme update, likely this week.

**Comment by fijha** [comment]
Yes, it actually makes a user feel that PW is loading faster, which is great!

This could be another issue or feature request, but looks like the whole Uikit and AdminThemeUikit depends too much on JavaScript. The basic content/layout should always display without JavaScript and without any FOUC whenever possible. It just feels so much better. This seems not to be an issue with Uikit v2, but Uikit v3 just won't display anything without JavaScript, so every time you reload a page it flicks from nothing to actual content. Wondering why do we need that with modern CSS features and modern browsers. Could be resolved with AJAX, but probably more complicated.

**Comment by netcarver** [comment]
@fijha Hello again. Have you had a chance to see if this is now resolved to your satisfaction in the latest dev version? If so, please could you close the issue. If not, please let us know here so I can update the status of this issue. Thank you.
