### ISSUE TITLE
AdminThemeUikit: menu arrow z-index

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#592]
### Short description of the issue

Arrow is blocked with dropdown menu border and box-shadow.

![arrow](https://user-images.githubusercontent.com/17672049/39927118-901f95e0-5531-11e8-8423-d0368e7e0ddd.png)

### Expected behavior

Should be on top.

![arrow fixed](https://user-images.githubusercontent.com/17672049/39927126-9333939e-5531-11e8-8af7-fc10c530f0d7.png)

### Suggestion for a possible fix

Change `z-index: 99` to `z-index: 200` in AdminThemeUikit/uikit/dist/css/uikit.pw.css#15484

**Comment by netcarver** [comment]
@fijha Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!
