### ISSUE TITLE
AdminThemeUikit: breadcrumbs quick page-tree icon

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#594]
### Short description of the issue

Breadcrumbs quick page-tree icon should be the same as **Pages > Tree** (sitemap), not "tree". Probably a mistake.

### Suggestion for a possible fix

```
AdminThemeUikit.module (line 914)

public function renderQuickTreeLink($icon = 'sitemap', $text = '') {
```

**Comment by ryancramerdesign** [comment]
The "tree" icon is intended here. It's purely subjective, I just thought it looked a lot better in this admin theme. I'm using sitemap in the others though, but may switch them because the quick tree (panel) isn't exactly the same thing as the PageList that we use the sitemap icon for.

**Comment by fijha** [comment]
Actually **Setup > Logs** are using the "tree" icon, so maybe there should be a different one.
