### ISSUE TITLE
Pages > Add New > Bookmarks (wrong separator position)

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#595]
### Expected behavior

Bookmarks separator should be on top of the "Bookmarks" item.

### Actual behavior

Separator is on the bottom.

### Suggestion for a possible fix

Remove `highlight` from:

```
wire/modules/Process/ProcessPageEdit/PageBookmarks.php (line 101)

$add->set($classKey, 'highlight separator');
```

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix for this issue.

**Comment by netcarver** [comment]
@fijha Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue.
