### ISSUE TITLE
adminthemeuikit: long radio options overflow

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#597]
### Short description of the issue

![image](https://user-images.githubusercontent.com/8488586/40055156-47a619c4-5847-11e8-8b2f-9b3c58020c18.png)

### Expected behavior

Should wrap in the next line

### Setup/Environment

* ProcessWire version: latest dev

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix. It looks like this one was intended at some point, but I don't remember why (maybe just a subjective thing). If there's some technical reason still applicable we may need to switch it back, but so far it looks like it should be fine.

**Comment by netcarver** [comment]
@BernhardBaumrock Hi Bernhard, please could you close this issue if it is resolved to your satisfaction. Thank you!

**Comment by BernhardBaumrock** [comment]
thx for the reminder @netcarver
