### ISSUE TITLE
Styling of expanded hidden parent incorrect in page tree list.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#6]
> Briefly describe the issue.

When you expand a branch in the page tree which has a parent which is "hidden", it is no longer lighter colored text once it has been clicked and its children are shown

> What did you expect to happen?

I think it should have the yellow highlighter background, but still be the lighter color text

> What did actually happen?

Text is dark, just like a normal, not hidden page

> Optional: Do you have screenshots/links that demonstrate the issue?

![screen shot 2016-09-26 at 2 42 58 pm](https://cloud.githubusercontent.com/assets/871211/18852931/99301432-83f7-11e6-9ef2-c900ecfe912e.png)
![screen shot 2016-09-26 at 2 43 06 pm](https://cloud.githubusercontent.com/assets/871211/18852930/992e413e-83f7-11e6-9297-b229cb2b038d.png)

This can actually be quite annoying when you have a lot of expanded branches because you have to mouseover to check whether the action button shows Hide or Unhide to know its status.

**Comment by adrianbj** [comment]
PS - to honest I wasn't really sure if this should be in the Issues repo or the Requests repo. I do think it's a bug, but not that critical.

Pity there is no easy way to move or tag.

**Comment by isellsoap** [comment]
If I see this correctly it would be just a matter of removing `:not(.PageListItemOpen)` from [this line](https://github.com/processwire/processwire/blob/master/wire/modules/AdminTheme/AdminThemeDefault/styles/sass/_pagelist.scss#L143).

**Comment by ryancramerdesign** [comment]
I've pushed an update that corrects this. Also thanks for identifying the solution @isellsoap
