### ISSUE TITLE
 Multi-instance does not support multi-language fields

### ISSUE THREAD

**Issue by mjmurphy** [processwire/processwire-issues#60]
### Short description of the issue

The new multi-instance functionality does not work with multi-language fields like TextLanguage, PageTitleLanguage and TextareaLanguage.
### Expected behavior

I installed two multi-language default profile sites from the latest master. 
I followed the example from [Ryan’s recent blog post](https://processwire.com/blog/posts/multi-instance-pw3/) on how to use multi-instance to connect two sites. This is the the code I used:

```
<?php 
// Server path to the other PW languages profile installation
$path = '/path/to/site/locally/pw-bugs/lang-test-1';

// The root URL for the other PW languages profile installation
$url = 'http://lang-test-1/';

// Create a new ProcessWire instance
$site = new ProcessWire($path, $url);

// Find a page using the basic-page template
$items = $site->pages->find("template=basic-page, limit=1, sort=-created");

// output 
foreach($items as $item) {
    echo "<p>$item->title</p>";
    echo "<p>$item->summary</p>";
    echo "<p>$item->url</p>";
} 
```
### Actual behavior

Actual output is :

```
<p>Array</p>
<p>Array</p>
<p>/about/another-child-example/</p>
```
### Steps to reproduce the issue
1. Setup two sites with the multi-language default profile.
2. copy the multi-instance example code above into the template on one of the sites (_main.php) and adjust $path and $url as appropriate.
### Setup/Environment
- ProcessWire version: 3.0.36
- PHP version: 5.6.10
- MySQL version: 
- Fresh install on both sites using the multi-language default profile
### References

Post on forums, where others have also reported the same issue.
[https://processwire.com/talk/topic/14168-problem-with-multi-instance-giving-array-notice/](https://processwire.com/talk/topic/14168-problem-with-multi-instance-giving-array-notice/)
Original blog post by Ryan announcing new multi-instance functionality
[https://processwire.com/blog/posts/multi-instance-pw3/](https://processwire.com/blog/posts/multi-instance-pw3/)

**Comment by ryancramerdesign** [comment]
Thanks @mjmurphy I've pushed a fix for this issue in the latest commit. Please let me know if you run into any more trouble with it.

**Comment by mjmurphy** [comment]
Hi @ryancramerdesign thanks, I just tested again with the example posted, and it is now displaying the default language text. However there still seems to be an issue with multi-language URLs. 

I am not sure if this is the correct way to do this, but I set the other sites language to German like this

```
// change the other sites language to German - de
$site->user->language = $site->languages->get("de"); 

```
before the output code

```
// output 
foreach($items as $item) {
echo "<p>$item->title</p>";
echo "<p>$item->summary</p>";
echo "<p>$item->url</p>";
}
```
this is what it returns

```
<p>German Child Example Title</p>
<p>German Summary Text</p>
<p>/about/another-child-example/</p>
```

The title and summary are correct, but the Url should be:

/de/uber/another-child-example-de/

**Comment by ryancramerdesign** [comment]
Thanks @mjmurphy I've just pushed another update that corrects this. What was happening is that a "ready" event was never getting triggered for instances after the first, so the hooks used by LanguageSupportPageNames were not getting attached. Chances are this missing ready event was causing problems elsewhere too, so we may have just fixed a lot of things with this.

**Comment by mjmurphy** [comment]
Hi @ryancramerdesign, just tested and it seems to be working well. Thanks for fixing, looking forward to using the multi-instance functionality more now.
