### ISSUE TITLE
Mixup of variables in log calls in WireTempDir::removeExpiredDirs

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#600]
### Short description of the issue

Inside WireTempDir::removeExpiredDirs, failures to remove a directory are logged, but the variables $path (original argument passed to removeExpiredDirs) and $pathname (subdirectory path used inside the loop) are switched around between log calls, so the log output will show the wrong directory (or none at all if removal of $path fails and it contained no subdirectories).

This was noticed in [this forum post](https://processwire.com/talk/topic/19248-what-is-wire-temp-dirtxt/).

### Suggestion for a possible fix

$path and $pathname should be switched between lines [278](https://github.com/processwire/processwire/blob/8dda4368eabaa38c4c5efe306e629707ebfdee8c/wire/core/WireTempDir.php#L278) and [291](https://github.com/processwire/processwire/blob/8dda4368eabaa38c4c5efe306e629707ebfdee8c/wire/core/WireTempDir.php#L291) of WireTempDir.php.

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed your suggested fix.

**Comment by netcarver** [comment]
@BitPoet Hi Chris, please could you close this issue if it is resolved to your satisfaction. Thank you!

**Comment by netcarver** [comment]
@BitPoet Hello Chris. I intend closing this issue in a week or so if I've not heard anything back from you - or anyone else - about it by then.

You can always re-open this issue later if you need to.

**Comment by teppokoivula** [comment]
@netcarver, Just a quick reminder: you're a collaborator, so if you close an issue, the author of the issue cannot re-open it. Probably not a big issue in this case, just trying to avoid any unnecessary confusion :)

**Comment by BitPoet** [comment]
Sorry, I missed the github notifications. I'll close this issue. Thanks to @ryancramerdesign for the quick fix!
