### ISSUE TITLE
Toggling repeater item open/closed hides outline in AdminThemeUikit

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#603]
### Short description of the issue

When a repeater item is toggled open and closed the outline of the repeater item becomes hidden in AdminThemeUikit. Seems to be due to the `overflow: hidden` inline style that is applied after the item is toggled.

![repeater-outline](https://user-images.githubusercontent.com/1538852/40335117-29d1d036-5db6-11e8-9385-a66d47f6c14c.gif)

### Setup/Environment

* ProcessWire version: 3.0.103

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. Thanks for pointing me to the overflow. I don't know where that `overflow:hidden` is coming from, but seems to be something in jQuery or jQuery UI as far as I can tell. I've updated the open/close event to remove that inline css, which seems to fix it.
