### ISSUE TITLE
AdminThemeUikit: Some inputs appearing inline with inputfield error notice

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#605]
### Short description of the issue

In AdminThemeUikit inputs with widths less than 100% are displaying inline with the error notice. This looks wrong.

![2018-05-28_115602](https://user-images.githubusercontent.com/1538852/40592039-9b19b076-626e-11e8-8490-0dbcb2170430.png)

Compare AdminThemeDefault:

![2018-05-28_115831](https://user-images.githubusercontent.com/1538852/40592042-a2e7529a-626e-11e8-8b08-50afb5b9aebb.png)

Perhaps error notices should be set to `display: block` so they span the full inputfield width?

### Setup/Environment

* ProcessWire version: 3.0.104

**Comment by ryancramerdesign** [comment]
Thanks, I have fixed the issue and it'll appear in the next AdminThemeUikit update.
