### ISSUE TITLE
[Fieldset (Page)] Can't empty multilanguage Fields

### ISSUE THREAD

**Issue by tobaco** [processwire/processwire-issues#606]
### Short description of the issue

I'm using Fieldset (Page) to group some fields. Some of these fields are multilang fields.
I can fill and update these fields, but I can't empty them. If I clear these fields and save the page the previous content get's restored. Other fields in this fieldset work as expected. When editing the actual repeater page in Home > Admin > Repeaters the fields save and empty normal.

### Expected behavior

I want the fields to stay empty, if I empty them.

### Actual behavior

Field content get's restored

### Steps to reproduce the issue

1. Create multilanguage setup
2. Create a Fieldset (Page) field and add multilanguage and normal fields
3. Fill all fields and save the page
4. Try to empty the fields

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.104
* PHP version: 7.1
* MySQL version: 5.6.3.8
* Multilanguage installation with english (default), german (not yet filled) and chinese  (not yet filled)

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. Are there any other settings on the fields in question? Is it just the multi-language ones you observe the issue with, or both single and multi language? Any difference between required vs. non-required fields?

**Comment by tobaco** [comment]
Hm, can't replicate it now either …
Could it be related to this issue: https://processwire.com/talk/topic/19331-wrong-parent-for-repeater-pages/ ?

I'll close this issue for now and report back if it happens again. Sorry for bothering. 🤭
