### ISSUE TITLE
AdminThemeUikit: usernavigation label format wrong in mobile view

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#608]
### Short description of the issue
The settings in modules setting of AdminThemeUikit -> masthead + navigation -> label format are not (fully) obeyed in mobile view. Please see the attached screenshots - these three pics are saying more than words ;)

* ProcessWire version: 3.0.104
![modules_ _processwire_ _audit_incognito](https://user-images.githubusercontent.com/8448399/40719720-accc90e8-6414-11e8-82e3-b94a5d1fd809.png)
![edit_page__firstname_lastname_ _audit_incognito](https://user-images.githubusercontent.com/8448399/40719732-b2db2d3c-6414-11e8-965f-18aab47cb982.png)
![pages_ _processwire_ _audit_incognito](https://user-images.githubusercontent.com/8448399/40719742-b77b00f6-6414-11e8-804a-ac028e1c57ca.png)

**Comment by ryancramerdesign** [comment]
Thanks, I've corrected the issue and it'll appear in the next AdminThemeUikit update later today.

**Comment by processwired** [comment]
Thanks Ryan! 👍
