### ISSUE TITLE
TemplateFile data merging order

### ISSUE THREAD

**Issue by pine3ree** [processwire/processwire-issues#61]
Hello @ryancramerdesign ,

this is more like a doubt/question.
In `ProcessWire\TemplateFile` wouldn't it be better to reverse the order of merging 

``` php
//..
public function ___render() {
    //..
    $fuel = array_merge(self::$globals, $this->getArray());
    //..
}

public function getArray() {
    return array_merge(parent::getArray(), $this->wire('fuel')->getArray());
}
//..
```

so that api variables do not get accidentally overwritten?

kind regards,
maks

**Comment by LostKobrakai** [comment]
Can you please add the File/Class you're talking about above?

**Comment by pine3ree** [comment]
@LostKobrakai 
sorry, you are totally right !
`ProcessWire\TemplateFile`
thanks

**Comment by pine3ree** [comment]
@LostKobrakai 
ah ok, I had already put in the issue title as well. Now i remember why i didn't specify it in the comment.
kind regards

**Comment by ryancramerdesign** [comment]
The purpose of the $globals in TemplateFile was specifically for API variables originally, so the current code ensured the API variables wouldn't get overwritten. This might be a leftover from PW1. But we're not using $globals for that purpose any longer (and not sure we ever have in PW2+), and to be honest I don't think there's any reason to keep it around. One can already do the same thing by using `$this->wire('name', $value);` and it gets sent to any rendered template files. I'll go ahead and depreciate the setGlobal() method and related vars.

**Comment by ryancramerdesign** [comment]
Btw, for the getArray() method, we actually do support overwriting of API vars, as it's useful to send in a different $page var for instance, among others. We didn't support this back in PW1, it was a different time. :) If a developer is doing their own TemplateFile or $pages->render() calls then being able to swap in different API vars in some cases is definitely useful.

**Comment by pine3ree** [comment]
I now understand it's a choice by design. Thanks for the explaination.
kind regards.
