### ISSUE TITLE
Recent page .sort-date appears in mobile view (Default/Reno)

### ISSUE THREAD

**Issue by rolandtoth** [processwire/processwire-issues#610]
### Short description of the issue

There is a span for date sorting in Created and Modified columns on the Recent page (/admin/page/recent-pages/). When the screen gets small, values like **1 day ago** transform to **15276837151 day ago** because `.sort-date` span elements get visible.

Unfortunately this is not only CSS because the markup also changes, so when going back to desktop size the markup (hence the wrong values) remain.

Doesn't happen in AdminThemeUikit.

### Expected behavior

Keep the .sort-date spans invisible.

### Steps to reproduce the issue

1. Go to Recent pages in the admin (in Default or Reno themes)
2. Zoom in until mobile view kicks in
3. Created and Modified date columns have wrong values
4. Zoom back to normal, wrong values remain in place

### Setup/Environment

* ProcessWire version: 3.0.104
* (Optional) PHP version: 7.0.30

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by rolandtoth** [comment]
Thanks, works as it should now.
