### ISSUE TITLE
PHP Notice: Undefined index: truncateTail in .../wire/core/Sanitizer.php:1091

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#613]
### Short description of the issue

As per the title - let me know if you can't reproduce, but I am seeing it in the admin when editing a page with a repeatermatrix which includes my new truncate call for the matrix_summary.

**Comment by adrianbj** [comment]
https://github.com/processwire/processwire/pull/112

**Comment by ryancramerdesign** [comment]
This one should be fixed on the current dev branch. Thanks.
