### ISSUE TITLE
InputfieldPassword.module confirm input id

### ISSUE THREAD

**Issue by jliebermann** [processwire/processwire-issues#614]
### Short description of the issue

if one changes the id attribute to a value other than the name, the confirm input id is not effected. I consider this a bug. 

### Expected behavior

The confirm input id should be based on the id attribute. Then If one changes the id attribute to a value other than the name, the confirm input id will be based on the id.

### Actual behavior

The confirm input id uses the name attribute instead of the id attribute for it's value. If one changes the id attribute to a value other than the name, confirm input id ignores the change.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Add this code:
$id  = $this->attr('id');
after line 208 in InputfieldPassword.module

Modify code on line 240  in InputfieldPassword.module from:
"size='$size' id='_$name' name='_$name' value='$confirmValue' autocomplete='new-password' /> " . 
to:
"size='$size' id='_$id' name='_$name' value='$confirmValue' autocomplete='new-password' /> " . 

### Steps to reproduce the issue

1. create a module with an form that uses password field
		$form = $this->modules->get('InputfieldForm');
		$field = $this->modules->get('InputfieldPassword');
		$field->name = 'password';
		$field->label = 'Password';
		$field->required = true;
		$field->columnWidth = 50;
		$field->attr('id', 'test_password');
		$form ->add($field);
		$form ->save();

2. Inspect code in browser and note id of "Conform" input field. The id should be '_test_password' but it will be set to '_password'

### Setup/Environment

I am using ProcessWire 3.0.98

* ProcessWire version: 3.0.98
* (Optional) PHP version: 7.1.7

The attached is the modified InputfieldPassword.module
[InputfieldPassword.module.zip](https://github.com/processwire/processwire-issues/files/2070481/InputfieldPassword.module.zip)

**Comment by jliebermann** [comment]
The code fix above should read: (the 3rd time is a charm)

Optional: Suggestion for a possible fix
Add this code:
$id = $this->attr('id');
after line 208 in InputfieldPassword.module

Modify code on line 240 in InputfieldPassword.module from:
"size='$size' id='_$name' name='$name' value='$confirmValue' autocomplete='new-password' /> " .
to:
"size='$size' id='_$id' name='$name' value='$confirmValue' autocomplete='new-password' /> " .

**Comment by Toutouwai** [comment]
Related forum thread: https://processwire.com/talk/topic/19365-inputfieldpasswordmodule-confirm-id-bug/

Just to clarify, the problem with not being able to set the id of the confirm field is that in a custom module the field might be used more than once in separate tabs, resulting in duplicate ids.

@jliebermann, you are able to edit your comments if you make a mistake and need to correct it.

**Comment by ryancramerdesign** [comment]
@jliebermann Thanks I've pushed an update that makes it base that id attr on the main input's id attribute rather than the name attribute.

**Comment by netcarver** [comment]
@jliebermann Can this be closed now?

**Comment by jliebermann** [comment]
Yes. Thank you!

**Comment by netcarver** [comment]
Done, thank you @jliebermann.
