### ISSUE TITLE
Odd display of roles column in Users lister when hooked

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#615]
### Short description of the issue

When `Fieldtype::markupValue` is hooked, the display of items in the Roles column is affected in an odd way. I can see [the code in ProcessPageLister](https://github.com/processwire/processwire/blob/d57b3ffcfc302caa2b5cf1cf1608ab478ff6da69/wire/modules/Process/ProcessPageLister/ProcessPageLister.module#L1207-L1208) that changes the display of values depending on if the markupValue() method is hooked, so that's fine, but what is weird is that first item in the Users lister is not affected.

No hook present:
![2018-06-05_184413](https://user-images.githubusercontent.com/1538852/40959605-42ff1cb2-68f1-11e8-8112-940a4d4a4beb.png)

Hook present in /site/ready.php, but the hook doesn't do anything:

```php
$wire->addHookAfter('Fieldtype::markupValue', function(HookEvent $event) {
    // Nothing is done here
});
```

![2018-06-05_184518](https://user-images.githubusercontent.com/1538852/40959655-76909ca4-68f1-11e8-9b93-241142b43964.png)
![2018-06-05_184801](https://user-images.githubusercontent.com/1538852/40959659-7988375a-68f1-11e8-9012-bbe12496ee05.png)

If some arguments are dumped in the hook (using Tracy Debugger here) then it's even weirder. The first item in the Users lister has the roles value as a separate Role objects, but subsequent items have the roles value as a PageArray.

```php
$wire->addHookAfter('Fieldtype::markupValue', function(HookEvent $event) {
    $field = $event->arguments(1);
    if($field->name !== 'roles') return;
    $page = $event->arguments(0);
    $value = $event->arguments(2);
    bd($value, "$page->name roles value");
});
```

![2018-06-05_185430](https://user-images.githubusercontent.com/1538852/40959832-f2fa64e6-68f1-11e8-91a1-bb656de91dca.png)

This is quite strange. My intention with all this was to try and prevent the guest role from displaying in the Roles column by hooking the markup value of the Roles field, but the inconsistent value supplied to the hook makes this difficult.

### Setup/Environment

* ProcessWire version: 3.0.104

**Comment by netcarver** [comment]
Has anyone else been able to reproduce this issue?

**Comment by matjazpotocnik** [comment]
I can reproduce.

**Comment by matjazpotocnik** [comment]
Now, this is odd. This line in buildListerTableCol() returns false on the first row and true on all subsequent rows:

`$this->wire('hooks')->isHooked($field->type->className() . '::markupValue()')`

So I changed it to this:

`$this->wire('hooks')->isMethodHooked($field->type->className(), 'markupValue')`

**Comment by Toutouwai** [comment]
> So I changed it to this:

> `$this->wire('hooks')->isMethodHooked($field->type->className(), 'markupValue')`

Nice one! That fixes it here.

**Comment by netcarver** [comment]
Great, thanks @matjazpotocnik. Hopefully Ryan will be able to incorporate that soon. I'll look to review in a week and bump again if it's still pending.

/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
@Toutouwai @matjazpotocnik Thanks I was able to duplicate as well and have pushed your suggested fix. The isMethodHooked() provides that needed instance checking that isHooked() doesn't, good find. Though the isHooked() might also have worked if we'd given it the Fieldtype instance (optional 2nd argument), but using isMethodHooked() seems like the best solution.

**Comment by Toutouwai** [comment]
Thanks.
