### ISSUE TITLE
Error After Importing Templates!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [processwire/processwire-issues#617]
![1111222](https://user-images.githubusercontent.com/5323832/41102004-0cc5ba4a-6a66-11e8-9b2f-db382807abd0.PNG)

**Local Environment:** 
**PW: 3.0.105
PHP: 7.1.15**

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate this one. Did you encounter any errors or warnings during the import, before clicking the Commit button? Was your import creating new templates or updating existing templates? Does this happen every time you export then import, or just in this one case? If just in this one case, can you identify any factors that were unique? If you'd like to try pasting in your export data (JSON), I can also take a look to see if there's anything unexpected in there that might be causing it.
