### ISSUE TITLE
ProcessPageEdit: Children tab does not load after page save

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#618]
### Short description of the issue

The list of child pages in the Children tab of ProcessPageEdit is AJAX-loaded. When the Save button is clicked while on the Children tab, ProcessPageEdit reloads with the Children tab active but no list of child pages is shown.

![children-tab](https://user-images.githubusercontent.com/1538852/41209480-06c67766-6d80-11e8-83f2-642ff5018ccc.gif)

### Expected behavior

List of child pages is always shown on the Children tab.

### Setup/Environment

* ProcessWire version: 3.0.104

**Comment by adrianbj** [comment]
This has bugged me for years - don't know why I haven't gotten around to reporting it!

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate that one here. When I click Save while on the Children tab, the Children tab ajax-loads automatically on the next request (spinner spins then contents of tab shows). What browser are you seeing it in? I've tested in the latest Chrome and Firefox (in OS X) but it's working correctly in both. Is it possible there's any other admin enhancements interfering with it? any JS errors?

**Comment by fijha** [comment]
I can confirm that. It doesn't load after save. I need to click some other tab and back to Children tab to load it.

I think It depends on "luck" and how fast your browser loads scripts (cache) and how they are executed one after another.

The problem is that `/wire/templates-admin/scripts/inputfields.js:1276` which attaches the event is executed after the `initPageEditForm()` which triggers it in `/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module:541`

So sometimes it works and sometimes not.

### Suggestion for a possible fix

#### Solution 1

Use `$(document).ready()` in `/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module:541`

— not sure why, but this causes strange layout bug

#### Solution 2 (better/faster)

Don't use `$(document).ready()` in `/wire/templates-admin/scripts/inputfields.js:1274`

**Comment by adrianbj** [comment]
> I need to click some other tab and back to Children tab to load it.

I find that just clicking again on the Children tab triggers the loading.

**Comment by Toutouwai** [comment]
@ryancramerdesign, I don't think any JS (anywhere in the PW admin) should be executing before the DOM is ready. The behaviour of JS that executes before DOM ready is less reliable, especially when several scripts are interacting. It also makes it more difficult to add custom JS to the admin that behaves in a reliable way. I mentioned another instance of this [here](https://github.com/processwire/processwire-issues/issues/480#issuecomment-381314384).

Is there a reason why any JS needs to execute before the DOM is ready?

**Comment by fijha** [comment]
I would suggest to not use "DOM ready" (if possible), but rather put all scripts at the bottom of the page. This type of approach is much better.

**Comment by netcarver** [comment]
I can confirm this is reproducible in 3.0.108 with the Reno theme installed.

**Comment by netcarver** [comment]
@fijha @Toutouwai @adrianbj Do any of you have a live site that exhibits this issue? If so, would you consider granting Ryan temporary access rights to track this down?

**Comment by Toutouwai** [comment]
I have a demo site online I can give @ryancramerdesign access to. I'll PM him via the forums.

> However, the production version of the server, a much faster machine with essentially the same setup, does not exhibit this issue (the tab loads fine there.)

Did you test with browser caching disabled? E.g. save on the Children tab while browser dev tools are open and you have the "Disable cache (while DevTools is open)" option selected in the settings. When I do that I can reproduce the issue every time on remote sites.

**Comment by Toutouwai** [comment]
Ryan tested on my demo installation and was able to reproduce the issue but only intermittently. I also checked again on several different sites, local and remote, and could only reproduce it occasionally this time, so it's definitely an intermittent thing.

I'm certain it's due to the `initPageEditForm()` JS function firing before the DOM is ready. So the intermittent nature of the issue is due the variability of how long it takes until the DOM is ready. To test this theory I edited inputfields.js, using [jQuery.holdReady()](https://api.jquery.com/jquery.holdready/) at [line 1273](https://github.com/processwire/processwire/blob/69424df1585d78f97cc2252072cdf5bb3a524533/wire/templates-admin/scripts/inputfields.js#L1273) to artificially delay the ready event.

```js
$.holdReady(true);
setTimeout(function() {
    $.holdReady(false);
}, 1000);
```

Then the issue occurs every time. So to my way of thinking the simple solution is for `initPageEditForm()` (or at least the part relating to loading the children tab) to wait for the ready event.

**Comment by BernhardBaumrock** [comment]
don't know but can anybody of you try it with a custom ajax loaded tab? I think this one could be related: #332

**Comment by BernhardBaumrock** [comment]
#332

**Comment by Toutouwai** [comment]
> can anybody of you try it with a custom ajax loaded tab?

Yes, when I delay the ready event to force the issue then it occurs also with custom ajax-loaded tabs.
![ajax-tab](https://user-images.githubusercontent.com/1538852/43996460-14475334-9e17-11e8-8d29-cd9327389c24.gif)

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this as there seems to have been a lot of feedback since your last comment.

**Comment by ryancramerdesign** [comment]
@Toutouwai @netcarver Thanks — I think this one should be fixed in commit: https://github.com/processwire/processwire/commit/45d6158be1f91dbc1082d731ec63019fd7cd491e

**Comment by Toutouwai** [comment]
Thanks!
