### ISSUE TITLE
Save + Next not working when template changed

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#62]
### Short description of the issue

If I edit a page, change the template, and then click Save + Next, I am not directed to the next page. Instead, I end up editing the same page I just saved.
### Expected behavior

When I click Save + Next, it should go to the next sibling page.
### Actual behavior

When I click Save + Next, it saves the page, but does not take me to the next page.
### Steps to reproduce the issue

1. Create two pages
2. Edit the first one, and change the template
3. Click Save + Next

And you should still be editing the first page, instead of the next.
### Setup/Environment

- ProcessWire version: 3.0.36

**Comment by LostKobrakai** [comment]
This is probably similar to this one: https://github.com/ryancramerdesign/ProcessWire/issues/2038

**Comment by CaelanStewart** [comment]
Ah, I see. Well, could I suggest a possible resolution to this?

My idea: When you are directed to the confirmation page, add a field to the form that carries the "Save + Next" instruction to the next step? Or, in the case where there is no confirmation page (like when no fields have changed), then just carry on with the "Save + Next" as if nothing were out of the ordinary.

Doesn't seem hard to implement, and helps to maintain continuity and predictability.

**Comment by ryancramerdesign** [comment]
Changing the template changes the flow of what's going to happen after the page is saved, so those dropdown actions are no longer applicable. I've just pushed an update that makes the dropdown actions disappear when you change the template, to avoid any potential confusion there. Thanks.
