### ISSUE TITLE
Extra buttons on PageFrontEdit config

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#621]
### Short description of the issue

When you edit the field, on the Input tab, in the Front-edn editing, by clicking on Configure button, the modal with the options opens. There are three buttons in the modal: **Submit** (this is expected), **Tree** and **Debug Mode Tools**.

### Expected behavior

Just Submit button.

### Optional: Screenshots/Links that demonstrate the issue

![pfe](https://user-images.githubusercontent.com/7663992/41391404-bf1e7248-6f9a-11e8-9d29-cd14dbb14435.gif)

### Setup/Environment

* ProcessWire version: PW 3.0.104
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for the issue.

**Comment by matjazpotocnik** [comment]
Thanks!
