### ISSUE TITLE
PHP Notice: Undefined offset: 2 in .../wire/core/WireHttp.php:894

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#624]
### Short description of the issue

I am getting this notice when using this REST service: https://restcountries.eu/

### Optional: Suggestion for a possible fix

The issue is that https://restcountries.eu/ API's response header returns:
```
"HTTP/1.1 200 "
```
rather than:
```
"HTTP/1.1 200 (OK)"
```

This means that this line #894
```
list($http, $httpCode, $httpText) = explode(' ', trim($responseHeader[0]), 3);
```
can't get a value for `$httpText`

### Steps to reproduce the issue

```
$http = new WireHttp();
$http->getJSON('https://restcountries.eu/rest/v2/alpha/ge');
```

### Setup/Environment

* ProcessWire version: 3.106
* (Optional) PHP version: 7.2

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign!
