### ISSUE TITLE
Images from nested repeater only display for superuser when pagefileSecure is on

### ISSUE THREAD

**Issue by paulashby** [processwire/processwire-issues#625]
### Short description of the issue

Thumbnail images are loaded on main page via ajax. Source pages have repeaters for images each of which includes its own nested repeater for image variations (eg a version of the parent image with a bluer sky).

### Expected behavior

Images from nested repeaters should load for users with any role.

### Actual behavior

Images from nested repeaters fail to load with 404 error for all roles other than superuser.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

1. Turn on pagefileSecure in /site/config
2. Create repeater field called 'nested' and give it image field. 
3. Create repeater filed called 'nest' and give it an image field and the 'nested' repeater.
4. Make a template based on a php file which echoes each of the images as HTML img elements.
5. Make a new page based on the above template and turn off Guest access in its Access tab.
6. Load the page while logged in a superuser - both images load.
7. Load the page while logged in with lesser role than superuser – only the image in the 'nest' repeater loads. The 'nested' repeater image fails to load with a status of 404.

### Setup/Environment

* ProcessWire version: 3.0.98
* (Optional) PHP version: 7.1.18
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by netcarver** [comment]
I've also noticed that the avatar image assigned to the Reno Admin theme fails to display for non-superusers, both in the theme and in their own profile when pagefileSecure is set to true. This despite them being logged in and having the ability to edit their own profile and the avatar image assigned them.

**Comment by ryancramerdesign** [comment]
Thanks @paulashby I was able to duplicate and have pushed a fix for this issue. @netcarver I'm guessing this is the same issue but please let me know if not.

**Comment by netcarver** [comment]
@ryancramerdesign Thanks for the push. The issue I referenced above still persists after an upgrade to current head. I already opened #629 to cover the issue I described above, in case it was different to this one.

**Comment by paulashby** [comment]
That's great news Ryan, thanks a lot!!

All the best,

Paul
---------------------------------------
Paul Ashby
---------------------------------------
paul@primitive.co
Studio: +44 (0)20 8699 8069
Mob: +44 077 6822 4077

**Comment by netcarver** [comment]
@paulashby If the fix has been verified by yourself, please could you close the issue.
