### ISSUE TITLE
InputfieldCKEditor 'extraAllowedContent': empty module config setting prevents use of config.js

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#627]
### Short description of the issue

When the InputfieldCKEditor module config field for "Extra Allowed Content" is empty, the module includes this as an empty string in the inline Javascript configuration for the field.

![2018-06-28_155653](https://user-images.githubusercontent.com/1538852/42012405-1446d43e-7aec-11e8-897e-41fb30dece1a.png)

![2018-06-28_155803](https://user-images.githubusercontent.com/1538852/42012418-2158caf6-7aec-11e8-9e93-338d6a0aae75.png)

This prevents or overrides any `extraAllowedContent` option that might be defined for the field in config.js 

```js
CKEDITOR.editorConfig = function( config ) {
    // Define changes to default configuration here. For example:
    config.extraAllowedContent = 'p(tip)';
};
```

### Suggestion for a possible fix

Somewhere in `InputfieldCKEditor::renderReady` before the $settings array is passed to `$config->js`...

```php
if(empty($settings['extraAllowedContent'])) unset($settings['extraAllowedContent']);
```

### Setup/Environment

* ProcessWire version: 3.0.106

**Comment by Toutouwai** [comment]
Just thinking... if there is something defined for "Extra Allowed Config" then this will also prevent the use of `extraAllowedContent` in config.js.

Really, the settings in the inline JS and the linked config.js file should be merged, but I suspect this might be a CKEditor issue rather than a PW issue.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix for the issue. As to whether they should be merged, I think it just depends on what one's intention is, as the intention might be to completely override, which is what it does now. Though if it ever surfaces as a recurring problem for people we can look into more options.

**Comment by Toutouwai** [comment]
Thanks.
