### ISSUE TITLE
Strange behavior with hook after Page::render

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#630]
### Short description of the issue

I'm trying to replace some content with `$this->addHookAfter('Page::render', $this, 'hookAfterPageRender');`, but this is what happens:

When the page is rendered for the first time (or after some longer time), the hook is called **after content is rendered** and `$event->return = 'replace'` doesn't work.

Than if I refresh the page for the second time, the hook is called **before content is rendered** and `$event->return = 'replace'` works as expected.

So always after some period of time (1 hour or so) it's not working for the first time, but than it works.

### Expected behavior

The hook should always be called **before content is rendered**, so the content can be replaced. Or after? Actually it's a bit confusing…

### Setup/Environment

* ProcessWire version: 3.0.107

**Comment by Toutouwai** [comment]
Your hook code? Steps to reproduce? Seems like something best raised in the forums first to confirm there is actually a bug.

These might help:
https://processwire.com/talk/topic/4212-cannot-hook-before-pagerender/?tab=comments#comment-41368
https://processwire.com/talk/topic/4212-cannot-hook-before-pagerender/?tab=comments#comment-41375

```php
$wire->addHookBefore('PageRender::renderPage', function(HookEvent $event) {
	// $event_2 is the event provided to PageRender::renderPage
	$event_2 = $event->arguments(0);
	$page = $event_2->object;
	if($page->template == 'foo') {
		$event_2->return = "my custom output";
		$event->replace = true;
	}
});
```

**Comment by fijha** [comment]
Yes, I have looked on that topics… but I need hook after (not before) to get content and replace some string inside it.

My hook code is very simple (using inside module):

```php
$this->addHookAfter('Page::render', function($event) {
    $event->return = str_replace('find', 'replace', $event->return);
});
```

### Steps to reproduce the issue

1. Create hook.
2. Create new page and view it or wait some time and view that page again – hook doesn't work.
3. Than right after that it works as expected.

**Comment by somatonic** [comment]
I have installed HelloWorld example module that comes with PW, where there's the same hook. Works always.

PW: 3.0.98

**Comment by fijha** [comment]
OK, finally… it took me so long :(… it was the `@ob_flush(); @flush();` in a function running every hour to get FB shares… I'm using `@ob_flush(); @flush();` to display content before running this function as it can be slow.

But looking at LazyCron.module, using this hook would be much better:

`$this->addHookAfter('ProcessPageView::finished', $this, 'afterPageView'); `

I can't just use LazyCron, because I need to track every page.

So, avoid `@ob_flush(); @flush();` if using hook after Page::render! :)
