### ISSUE TITLE
edit language permissions breaks add new children page

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#631]
### Short description of the issue

Multilanguage install (vanilla with 3 languages profile )
/Books
   /Book 1
   /Book 2
   ....

An editor role with **edit** and **create** permission on the "book" template and **add children** permission on the "books" template.

Editor can add children to the Books parent, but not edit the parent. Everything fine so far.

Now install core permission to edit languages (page-edit-lang-default etc...)

As soon as this is added and added to the editor role, the editor can't add pages to Books parent anymore. 

Solution is to give **edit** permission to the "books" template. Now editor can add book pages again, but also edit the Books parent which we don't want.

When the language permission are removed, it starts working normal again.

### Setup/Environment

* ProcessWire version: 3.0.98 /but happens on all PW versions

Related post: https://processwire.com/talk/topic/19559-language-page-edit-permissions-problem-with-creating-new-pages/

**Comment by ryancramerdesign** [comment]
Thanks @somatonic I was able to duplicate that and have pushed a fix on the dev branch.

**Comment by netcarver** [comment]
@somatonic Hi Philipp, if this is fixed to your satisfaction, please could you close this issue. Thank you!
