### ISSUE TITLE
$session->CSRF->getSingleUseToken($id) doesn't work as expected

### ISSUE THREAD

**Issue by fijha** [processwire/processwire-issues#634]
### Short description of the issue

When you specify unique ID with `$session->CSRF->getSingleUseToken($id)`, the token is not invalidated after `hasValidToken($id)` call and therefore can be used multiple times.

It works without specifying unique ID, but only because there is a random ID generated every time you call `getSingleUseToken()`.

So I need to reset token manually when using unique ID:

```
$session->CSRF->resetToken($id);
$token = $session->CSRF->getSingleUseToken($id); // or just use getToken($id)
```
### Expected behavior

Token should be invalidated after single use (removed from session) or regenerated every time you call `getSingleUseToken($id)`.

### Suggestion for a possible fix

In wire/core/SessionCSRF.php (line 164–165), token is removed from "singles" session variable, but still present in a session.

Add `$this->resetToken($id);` before line 131 (no need for "singles" session variable) or after line 165 (if it's better for some reason) should fix it.

### Setup/Environment

* ProcessWire version: 3.0.107

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this issue.

**Comment by netcarver** [comment]
@fijha Hello. I see that Ryan pushed a fix for this issue. If that resolved things to your satisfaction, please could you close this issue, otherwise could you add a reply here so we can keep it on Ryan's radar. Thank you!
