### ISSUE TITLE
ProcessWire: 3.0.108 Typing "help" in the search causes PHP undefined index errors

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#637]
### Short description of the issue

Typing "help" in the search causes PHP undefined index errors

### Optional: Screenshots/Links that demonstrate the issue

![help](https://user-images.githubusercontent.com/40570/42702319-c2c2446e-868e-11e8-8631-7bad50118bd6.jpg)

![errors](https://user-images.githubusercontent.com/40570/42702290-ac5b2380-868e-11e8-8528-37002c018723.jpg)

### Setup/Environment
<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.108 <br />
PHP: 7.1.12 <br />
Webserver: Apache/2.4.29 (Unix)  <br />
MySQL: 5.7.10-log <br />
 <br />
</details><details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 300 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 60 <br />
max_input_vars: 1000 <br />
memory_limit: 256M <br />
post_max_size: 128M <br />
upload_max_filesize: 2M <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security: *confirmed off <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension:  <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.9.8 <br />
EmailObfuscation: 1.1.0 <br />
MarkupSimpleNavigation: 1.3.6 <br />
ModuleSettingsImportExport: 0.2.9 <br />
ProcessHannaCode: 0.2.0 <br />
ProcessModuleToolkit: 0.2.3 <br />
ProcessPageListerPro: 1.1.1 <br />
ProcessSettingsFactory: 1.0.3 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
SettingsFactory: 1.0.3 <br />
TextformatterHannaCode: 0.2.0 <br />
TextformatterMakeLinks: 1.0.0 <br />
TracyDebugger: 4.10.24 <br />
WireMailSmtp: 0.3.0 <br />
</details>

**Comment by Toutouwai** [comment]
It's working for me.

Maybe try re-downloading v3.0.108 because I notice this issue was opened 7 hours ago but the last commit relating to the new search features was 6 hours ago, and the blog announcement of 3.0.108 was only 45 minutes ago. :wink:

**Comment by gmclelland** [comment]
Yep, it's working now.  I had to download the latest dev from github.

I originally updated via the ProcesswireUpgrade module when I saw it was available.  I was hoping to catch Ryan will he was still in the flow of coding/committing.
