### ISSUE TITLE
$input->requestMethod() does not exist

### ISSUE THREAD

**Issue by stefan-scholl** [processwire/processwire-issues#64]
### Short description of the issue

Documentation mentions `$input->requestMethod()` on https://processwire.com/api/ref/input/request-method/
This method does not exist.

### Expected behavior

Existing.

### Actual behavior

Error: Exception: Method WireInput::requestMethod does not exist or is not callable in this context (in .../wire/core/Wire.php line 416)

### Setup/Environment

* ProcessWire version: 3.0.36

**Comment by ryancramerdesign** [comment]
You'll need PW 3.0.39 or newer for this one. I meant to add a @since tag to this and forgot. I've just added it, so it should identify that in the documentation later this week. Thanks.

**Comment by stefan-scholl** [comment]
Strange. I searched for it in https://github.com/processwire/processwire because I was suspecting something like that.

**Comment by teppokoivula** [comment]
@stefan-scholl 3.0.39 is in the dev branch and GitHub code search only searches from the default branch, which in our case is master.
