### ISSUE TITLE
Modules directory bug with "requires" array sytax

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#640]
### Short description of the issue

Not quite the right place for this, I know, but not sure how to bring to @ryancramerdesign's attention otherwise.

There is a bug with the modules directory when a module has a "requires" property in `getModuleInfo()` using the array syntax as per the Module class [documentation](https://processwire.com/api/ref/module/).

If my module contains the following syntax it is not installable via classname (Modules > New > Add Module From Directory)

```php
'requires' => array(
    'ProcessWire>=3.0.83',
    'AdminThemeUikit',
)
```

Error is:

![module-install](https://user-images.githubusercontent.com/1538852/42871111-a53fc7d4-8acd-11e8-9612-2383743ac728.png)

The module installs fine via "Add Module From URL" with the array syntax.

Changing to the comma separated string syntax allows the module to be installed from the modules directory by classname:

```php
'requires' => 'ProcessWire>=3.0.83, AdminThemeUikit'
```

**Comment by netcarver** [comment]
@Toutouwai I've created a [minimal module](https://github.com/netcarver/ProcessTest) on GH that should allow the testing of this. So far, I can confirm the installation via URL works. Once the module goes live on the PW modules repo, I'll see if I can reproduce this via class name.

Please could you confirm I've setup the requires stanza in the module the way you'd expect in order to trigger this issue.

**Comment by Toutouwai** [comment]
> Please could you confirm I've setup the requires stanza in the module the way you'd expect in order to trigger this issue.

Thanks for creating the test module. There are a couple of differences that could be relevant.

1. The module where I experienced the problem wasn't a Process module but rather extended the Module class directly. Not sure if that would have any impact.

2. The ProcessWire version requirement in my module was for >=3.0.83 whereas yours is for >=3.0.0. Not sure, but I'm guessing the issue relates to a problem parsing the version string, so having two digits after the last dot could be relevant.

This is how my module looked at the time I was experiencing the problem: https://github.com/Toutouwai/BreadcrumbDropdowns/blob/f705cf2076d9af1e695543b3eb7d35cc2fc47221/BreadcrumbDropdowns.module

**Comment by netcarver** [comment]
@Toutouwai @ryancramerdesign The module _**ProcessTest**_ demonstrates this issue. It can successfully be installed via URL but using class name fails.

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. The ProcessTest module was very helpful in testing/fixing it. If there are any other modules in the directory using arrays for that requires info, it may take a few days before they are refreshed.

**Comment by netcarver** [comment]
@Toutouwai I've tested this on the most recent dev commit and it seems to be resolved now. Please close when you have verified.

**Comment by Toutouwai** [comment]
Thanks for the fix.
