### ISSUE TITLE
Add clarity to button labels on module install screen

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#641]
### Short description of the issue

The button labels for installing modules from the repository do not indicate what's actually happen: 

1. The first button is labeled “Download And Install“ - but it only displays the module infos
2. The button on the second screen is again labeled “Download And Install“ > but it only downloads the module
3. The button on the third screen is labeled correctly “Install Now“

I realize this could lead to the assumption that the first button only display infos without the ability to download and install the module – but I think this could be avoided by meaningful titles and descriptions...

### Expected behaviour

The buttons should indicate the correct actions:

1. Button “Display Module Info »“ or “Get Module Info“
2. Button “Download Module Files“
3. Button is correct: “Install Now“

**Comment by adrianbj** [comment]
Just for reference: https://github.com/ryancramerdesign/ProcessWire/issues/988

**Comment by netcarver** [comment]
Given that issue that Adrian referenced has multiple people requesting a change, I've added labels to reflect this.

**Comment by matjazpotocnik** [comment]
Some inconsistency is also present in the modules menu dropdown:

![screenshot 2018-07-29 15 49 37_cr](https://user-images.githubusercontent.com/7663992/43367052-5eeb5d34-9347-11e8-8303-d5ed7de2d780.jpg)

In the Modules menu, there are: Site, Core, Configure, Install and Refresh. On the Modules page we have tabs: Site, Core, Configure, Install and New. Maybe this should be unified by adding New to the menu?

**Comment by adrianbj** [comment]
While we're at this, what about an Upgrade tab / menu item? At the moment, the easiest way to upgrade a module that's not in the module's directory is to use the New option to upload or reference a URL to the upgraded version, but this is not intuitive for new PW users.

**Comment by szabeszg** [comment]
This Install vs New terminology in PW is confusing, at least to me. The term "install" usually means "copying the required files to the right location". However, in ProcessWire "installing" is more like "activating" since the right files are already there.

For example, in WordPress there is "Add New" which is similar to PW's New tab. WordPress uses the term "install"  after the "Add New" button has been hit. WP's "Install Now" is the action of grabbing the ZIP from the internet and unpacking it to the right location. Activate/deactivate are much better terms to be used when already installed files (ie. modules) should be executed (activate) or should not be executed (deactivate).

> While we're at this, what about an Upgrade tab / menu item?

Maybe renaming the tab called "New" to "Add/Update" ?
Similarly: "Add or Update Module from URL" and so forth...

**Comment by teppokoivula** [comment]
> WP's "Install Now" is the action of grabbing the ZIP from the internet and unpacking it to the right location. Activate/deactivate are much better terms to be used when already installed files (ie. modules) should be executed (activate) or should not be executed (deactivate).

Perhaps I'm too used to the PW terminology, but I've always found the WP terminology strange. For an example: if I install an application on my computer or phone, that means making it instantly usable. In the case of the computer I'd have to download the app before installing, and in the case of my phone (using the Play Store) the "install" button automatically downloads and _then_ installs the app.

Neither situation requires a separate "enable" step. Thus I'd argue that the WP workflow is actually the strange one, and our workflow is more of a "traditional" one :)

Regarding button labels I agree with the suggestions made by @noelboss, perhaps with one tweak:

1. Button “Display Module Info »“ or “Get Module Info“
    -> perhaps something along the lines of "Display Module Info / Install" could be used to signal that this is where you should go to start the installation process?
2. Button “Download Module Files“
3. Button is correct: “Install Now“

**Comment by ryancramerdesign** [comment]
For button 2, I think the label change makes works—something indicating that it's going to Download, whether "Download Module Files" or "Download Now", etc. 

But for the first button that begins the process, I'm a little confused about the suggestion. The purpose of that button is to begin the download and install process. It's true that the process has steps to it, and next screen in that process is a confirmation step. But there's still the big picture, which is that this is the download and install process. If we change the first button to something like "Display module info" then I'm afraid the purpose of the initial action (which is to begin the download and install process) would get lost. That would be confusing to me at least. Teppo's suggestion for "Show Module info / Install" seems to answer that concern, and I'd be fine with that, though it does seem like like a lot of words for this. If you think a label change is needed there, then maybe just a button labeled "Continue" would be less literal, while still implying that you are proceeding with the download and install process?

**Comment by teppokoivula** [comment]
This is a relatively common usability issue: when a button or link suggests an action, the user is often left wondering whether clicking it will do something right away. In this case we need to signal that the button starts the download and install process, but we don't want to suggest that it does it right away. 

That's a bit of a dilemma right there, and exactly why I suggested that long-winded alternative. Perhaps we can figure out a shorter alternative that still says more or less the same thing?  :)

**Comment by matjazpotocnik** [comment]
How about adding ... (three dots) at the end of the text?

**Comment by noelboss** [comment]
So, what we have is actually a multi step form… 

There are of course already [visual conscepts](https://duckduckgo.com/?q=step+ui&t=osx&iar=images&iax=images&ia=images) to make this clear to a user ;)

**Comment by netcarver** [comment]
@noelboss Can this be closed now?

**Comment by matjazpotocnik** [comment]
If possible, could my comment at https://github.com/processwire/processwire-issues/issues/641#issuecomment-408679497 be considered?

**Comment by netcarver** [comment]
@matjazpotocnik Yes, sure. That's always bothered me as well.

/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
> Some inconsistency is also present in the modules menu dropdown

@matjazpotocnik Thanks, somehow I missed that, I have just added it.

**Comment by netcarver** [comment]
I'm closing this now. @matjazpotocnik If something in wrong, please post here again.
