### ISSUE TITLE
Page search for users redirects to false URL in 3.0.108

### ISSUE THREAD

**Issue by AndZyk** [processwire/processwire-issues#642]
### Short description of the issue

When searching for users in the page search introduced in 3.0.108, the suggestions redirect to false URLs leading to the 404 page in the front-end.

### Expected behavior

Search for a user in the page search and after selecting the suggested autocomplete item you will be redirected to the user page inside the back-end.

### Actual behavior

You will be redirected to a false URL and land on the 404 page in the front-end.

### Optional: Screenshots/Links that demonstrate the issue

![bildschirmfoto 2018-07-19 um 21 40 21](https://user-images.githubusercontent.com/9403850/42966126-6fabb946-8b9c-11e8-9a44-056ce72fe562.png)

### Optional: Suggestion for a possible fix

I think, instead of a URL like this:
http://example.com/processwire/access/users/username/

You should be redirected to a URL like this:
http://example.com/processwire/access/users/edit/?id=123

### Steps to reproduce the issue

1. Upgrade to 3.0.108
2. Search for a user inside the page search
3. Click on the suggested autocomplete item

### Setup/Environment

* ProcessWire version: 3.0.108
* PHP version: 7.1.12
* MySQL version: 5.6.38

**Comment by ryancramerdesign** [comment]
Thanks, I have pushed a fix for this issue.

**Comment by AndZyk** [comment]
Thank you for the fix.
