### ISSUE TITLE
Allow beautify options to work with $sanitizer->testAll()

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#645]
### Short description of the issue

It would be great if this worked:
![image](https://user-images.githubusercontent.com/871211/42969609-97889114-8b5b-11e8-9e31-3efa3f51db58.png)

### Expected behavior

I would expect that the `Sanitizer::translate` would be passed to methods that support it

### Actual behavior

`Sanitizer::translate` is ignored - note that pageName is not translated.

**Comment by ryancramerdesign** [comment]
The testAll() is just there to test all the methods with their default arguments and intended for “debugging and testing purposes” per the method description. This method has no second argument, but if it did, a beautify argument would only be applicable to just a few of the methods it tests. I think this method should stick to its intended purpose, which is to test the sanitizers with their default arguments. The only common and required argument to all sanitizers is the first argument, which is the value that needs to be sanitized. 

If you would like, I could add a new pageNamePretty() method where a true value for the $beautify argument would be the default argument?

**Comment by adrianbj** [comment]
I realize it's only for testing and debugging, but being able to test all the possible combinations with and without the beautify argument (shown only for the relevant methods) would surely be useful.

As for `pageNamePretty` - as I mentioned here https://github.com/processwire/processwire-issues/issues/644#issuecomment-411035585 I still think it's strange that `pageName` needs a beautify option, but I don't think the Pretty version will really help because devs may also want to consider the pageNameUTF8 as well and I think another option would just confuse things further - thanks though!
