### ISSUE TITLE
Repeater Trash Not Counting As A State Change

### ISSUE THREAD

**Issue by netcarver** [processwire/processwire-issues#646]
### Description

If you click the trash icon on a repeater icon, then navigate away from a page, the usual warning about loosing a change will not be issued.

### Expected behavior

I'd expect the warning to occur as the user may well have intended to delete the repeater item and forgotten to hit the save button.

### Suggestion for a possible fix

Update the trash-click handling JS to also add the InputfieldStateChanged class to the owning repeater. 

### Steps to reproduce the issue

1. Create a repeater field and add to a template
2. Create a page using the template and add a couple of repeater items. Save the page.
3. Click the trash icon on a repeater item.
4. Navigate away from the page (say up one level in the page tree)
5. The normal warning about loosing changes does not appear.

### Setup/Environment

* ProcessWire version: 3.0.108
* PHP version: 7.2

**Comment by netcarver** [comment]
Using AdminCustomFiles, I can get this feature by injecting the following JS...

    $(document).on('click', 'i.InputfieldRepeaterTrash', function() {
        var target = $(this).parents('li.Inputfield');
        target.addClass('InputfieldStateChanged');
    });

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment]
Yes, that fixes it. Thank you.
