### ISSUE TITLE
Image description field not showing when 0

### ISSUE THREAD

**Issue by somatonic** [processwire/processwire-issues#647]
### Short description of the issue

THe image field suddenly has no description field anymore. When I set the image description field to be 0 it should show the textarea. When entering 1 it shows the input.

Latest PW

**Comment by netcarver** [comment]
@somatonic Hi Philipp. Perhaps I'm mis-understanding your initial post but this doesn't seem like a bug. Could you add a couple of screenshots showing the issue?

**Comment by somatonic** [comment]
Ah, must have overseen some word and mixed it up with the other image settings.
