### ISSUE TITLE
Save button disappears after submission error in Admin tree long-click edit modal

### ISSUE THREAD

**Issue by lmdade** [processwire/processwire-issues#65]
This issue was originally posted on the PW forum, where it was recommended I post it here.

### Short description of the issue

When using the long-click modal window to edit a page from the Admin tree, the "Save" button **completely disappears** if there is a field submission error, preventing the page from being saved at all.  This **only happens when fields are validated with the HTML5 required attribute**.

### Expected behavior

When using HTML5 validation, nothing should happen with the form except the browser's default behaviour for flagging fields with errors. The modal window should not submit/reload or do anything.

### Actual behavior

If there are field errors flagged by HTML5 validation, the save button disappears as if the form has been submitted, but the actual submission process is halted by the browser's default error-flagging behaviour.

The user is forced to close the modal window and start _all over again_. None of the changes (even error-free fields) have been saved.

If NOT using HTML5 validation the form works as expected with errors shown after the page reloads (_and the save button reappears!_).

### Possible fix

I'm not really sure what the solution is, but I suspect it is a javascript issue.  The HTML5 validation is halting the browser from submitting the form, but the modal window's javascript code is still executing something in the background.

### Steps to reproduce the issue

1. Set up one or more fields for a template to use HTML5 required attribute for validation.
2. Edit a page using that template via the admin tree long-click edit modal.
3. Submit the form containing an error that should get flagged by HTML5 validation (e.g. missing/incorrectly formatted field).

### Setup/Environment
* ProcessWire version: 3.0.39 dev (but first spotted in ver. 3.0.34)
* Browsers tested: Firefox 49.0.2 and Chrome 54.0.2840.71 (both browsers have the same issue)

It's not really a major issue, the user can just not use the long-click edit modal (or not use HTML5 validation, but I like the convenience of it).

**Comment by ryancramerdesign** [comment]
Thanks, I'm removing the code that hides the save button. I'm not sure why we were hiding the buttons after click, but it doesn't seem necessary. But this update will appear on the dev branch tomorrow. 

I would avoid using the HTML5 required attributes on page editing forms when possible, as they can be problematic in a lot of cases beyond this. For instance, say you are on the "settings" tab of a page editor, and a field on the "content" tab has a required field. If you try to "save" from the settings tab, it won't work, and there's no indication why. There's an assumption built-in to the HTML5 required attribute that the entire form is visible at once, and this is often not the case in PW (i.e. with tabs, field dependencies, collapsed fields, etc.). So I mainly added the HTML5 required support for other uses of Inputfield forms (i.e. FormBuilder or others).
