### ISSUE TITLE
Inputfiled Images with Overwrite existing files ON leaves cropped images in temporary state

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#650]
This is another "1970-01-01 01:00:10﻿" issue not yet resolved and this one looks like a bug. Similar issues can be found here: https://github.com/processwire/processwire-issues/issues/42 https://github.com/processwire/processwire-issues/issues/41

Forum discussion of this issue:
https://processwire.com/talk/topic/19697-cropped-images-are-not-in-pageimages-why/
With the invaluable help of @Toutouwai I could track it down.

### Short description of the issue

If Inputfiled Images with "Overwrite existing files" is ON then creating a cropped image yields created=1970-01-01 01:00:10, ie. when this option is on, ProcessWire does not update the "created" field in the database, which means that an API call like $page->images returns an array of images without any cropped images which were created when "Overwrite existing files" was turned on.

### Steps to reproduce the issue

1. Any ProcessWire version which has "Overwrite existing files" feature (up to v3.0.108 dev)
2. Create an Images field or use an existing one.
3. Turn on Overwrite existing files found on the Input tab.
4. Create a cropped image with the built in crop tool, save the page.
5. Examine the return value of $page->images

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@szabeszg Can this be closed now?

**Comment by szabeszg** [comment]
The fix works, thanks!
