### ISSUE TITLE
Repeater field import replacement removed all sub-fields

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#652]
### Short description of the issue

Repeater field import replacement removed all sub-fields. I have all my data inside a repeater field got removed. I think this could be prevented by some means.

### Expected behavior

I think two ways could solve the issue.
A. A warning before execute.
B. Check the sub-fields inside the repeater when execute the field import, so the sub-field changes can be handled.

* ProcessWire version: 3.0.73 (The version I used is dated. I cannot confirm the issue is still valid for the latest version)

**Comment by Toutouwai** [comment]
The import of repeater fields was not supported prior to [this commit](https://github.com/processwire/processwire/commit/7b19df0175cf3921d1ce7218eebf6e412e2c0c65) which was effective from v3.0.82 onwards. 

Issue relating to that commit: https://github.com/processwire/processwire-issues/issues/416

So your 3.0.73 install pre-dates that.

**Comment by karltdev** [comment]
Noted. Thank you very much. I am closing this.
