### ISSUE TITLE
"Can this template be used for new pages" option: new vs. existing pages situation

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#655]
Let's say you have a template (called 'a') and "Can this template be used for new pages" is set to No or One.  Let's also assume a page using this template has already been created.

Now let's say you have a page that uses template 'b'.  You edit this page and decide to change the template.  The dropdown shows template 'a' as an option.  Should template 'a' be there?

Now I don't know if this is a bug or intended operation, but it's something to think about.  "Can this template be used for **new** pages" is being respected in this scenario because the page with template 'b' is not a _new_ page, but rather an _existing_ page.

However what if you don't want template 'a' to be used ever again, even in the context of _switching_ to that template?

**Comment by ryancramerdesign** [comment]
@jlahijani  It enforces this particular rule in the Template selection for everyone except superusers. When I first added the "noParents" option to templates (which is the name of the setting that enforces that), I thought that superuser should be immune from it. Kind of like a root user is immune from file permissions on unix. Now that you bring it up, I'm not so sure, and kind of leaning towards that it should be enforced for superuser too. Will give it some thought here. Thanks.

**Comment by szabeszg** [comment]
> leaving described behaviour as-is but also adding a note about superusers being able to select templates regardless of said setting.
+1 :)

**Comment by netcarver** [comment]
@ryancramerdesign Any further thoughts on this one?

/remind me to review in 2 weeks

**Comment by ryancramerdesign** [comment]
@netcarver I think it's okay to close this, so I'll close. I already changed this awhile back to enforce the behavior for superuser too. After dwelling on it I just thought that was simpler that way and not likely to cause confusion. I don't really want to have superuser exceptions if possible so moved the old behavior to work with superuser only if `$config->advanced==true;`.
