### ISSUE TITLE
ListerPro Config causes PHP out of memory error

### ISSUE THREAD

**Issue by pieterjanmaes** [processwire/processwire-issues#656]
### Short description of the issue

When I want to adjust config settings in the ListerPro module after update to PW 3.0.109 I get this error:
`Maximum function nesting level of '256' reached, aborting!`

on line 1649 in WireArray.php

### Optional: Suggestion for a possible fix

Maybe related to the following issue? 
#653 

### Steps to reproduce the issue

1. Update to PW 3.0.109
2. Go to a ListerPro page
3. Go to the Config tab

### Setup/Environment

* ProcessWire version: 3.0.109
* PHP version: 7.2.7
* (Optional) MySQL version: 5.7.21
* (Optional) Any 3rd party modules that are installed and could be related to the issue: ListerPro 1.1.1β

**Comment by netcarver** [comment]
@pieterjanmaes This is a known issue with xdebug, not with ProcessWire. More information [here](https://xdebug.org/docs/all_settings#max_nesting_level). 

Please could you review your xdebug config settings and confirm if this is the case - and if it is, please could you close this issue.

Thank you!

**Comment by pieterjanmaes** [comment]
@netcarver When I disable Xdebug on MAMP I get the following error:
`Error: Maximum execution time of 30 seconds exceeded (line 869 of ..../wire/core/Inputfield.php) `

Also tested on my online server, there I have the same issue, on PW 3.0.108 it all worked fine.

**Comment by pieterjanmaes** [comment]
Thanks @ryancramerdesign, tested and everything works fine again!
