### ISSUE TITLE
Language Support Page Names - Bug in Multilanguage use 

### ISSUE THREAD

**Issue by pieterjanmaes** [processwire/processwire-issues#658]
### Short description of the issue

When u have a multilanguage website and change the "Page number prefix for pagination" for the default language in the "Language Support - Page Names Module", and leave the others empty.

The pagination doesn't work for the non-default languages.

### Expected behavior

The "default" value  for Page number prefix for paginatin "page" should work

### Setup/Environment

* ProcessWire version: 3.0.96
* PHP version 7.2 : 
* MySQL version: 5.7.21
* Any 3rd party modules that are installed and could be related to the issue: Language Support - Page Names Module"

**Comment by ryancramerdesign** [comment]
Thanks @pieterjanmaes that's a good find, I have pushed a fix for this.
