### ISSUE TITLE
Can't delete items from 2 repeaters at the same time

### ISSUE THREAD

**Issue by stefan-scholl** [processwire/processwire-issues#66]
### Short description of the issue

2 repeaters on one template. Deleting 1 item in each and saving the page. Only 1 item from the first repeater gets deleted. The other repeater has all the items as before.

### Expected behavior

Deleting items from more than one repeater in one go.

### Actual behavior

Only one repeater deletes the item. You need to delete, save, delete, and save again.

### Setup/Environment

* ProcessWire version: 3.0.36

**Comment by ryancramerdesign** [comment]
Thanks @stefan-scholl that's a great find, I've pushed an update that fixes this.
