### ISSUE TITLE
Selector Arrays don't work with PagesType

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#660]
### Short description of the issue

I discovered today that selector arrays don't seem to work with PagesType objects, like $users. They only allow strings.

### Expected behavior

I expected to be able to use selector arrays, just as with $pages

### Actual behavior

Exception is thrown saying Array is an invalid type

### Setup/Environment

* ProcessWire version: 3.0.104

**Comment by noelboss** [comment]
Just wanted to add this one as well…

https://processwire.com/talk/topic/15523-selector-arrays-with-or/

Cost me some time to find it's not an error on my part but rather an inconsistency.

**Comment by netcarver** [comment]
Let's continue this one over in the requests repo. 

/move to requests
