### ISSUE TITLE
Trash option for pages on listers existed in 3.0.99; no longer in 3.0.109

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#663]
In ListerPro (or listers in general I guess), I had the ability to trash pages in PW v3.0.99:
![trash-available](https://user-images.githubusercontent.com/4558/43972363-f5497ef6-9c88-11e8-84e1-b521ca777692.jpg)

When running 3.0.109 (or some version after 3.0.99), it looks like that option has disappeared:
![trash-unavailable](https://user-images.githubusercontent.com/4558/43972384-074f1a52-9c89-11e8-810a-c9bd446f6219.jpg)

I know it has to do with PW core and not other settings because if I simply downgrade/upgrade my site (by replacing the 'wire' folder) between 3.0.99 and 3.0.109, the feature exists / doesn't exist.

I am a superuser, but to be sure, I also checked the option in the Page List settings as well with no luck:
![page-list-settings](https://user-images.githubusercontent.com/4558/43972493-68afc1fc-9c89-11e8-88f6-7cd099bfd466.jpg)

**Comment by gmclelland** [comment]
I can confirm this behavior with 3.0.112

**Comment by jlahijani** [comment]
I investigate this a bit and I see the line where the issue is.

wire/modules/Process/ProcessPageList/ProcessPageListActions.php line 181 (pw 3.0.116):
```
$trashable = $this->useTrash && $page->trashable();
```

The `$this->useTrash` is evaluating as false, which prevents the action button from appearing in ListerPro.

**Comment by jlahijani** [comment]
This is now fixed as of today's updates.
