### ISSUE TITLE
GitLab for modules directory

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#664]
My GitLab hosted modules do not update version numbers automatically in pw's modules directory. That's really annoying - I don't want to track all my modules and update the entry on pw.com after every commit. On the other hand I don't want to change my workflow just because of pw's modules directory. I'm uploading the modules for the community, not for my own purpose.

Could you please look into that issue? It can't be a big thing to add. Thanks

**Comment by netcarver** [comment]
I'd like to request this be looked at as well. I'm considering migrating my accounts away from GH and this option would certainly be useful, as might BitBucket.

**Comment by ryancramerdesign** [comment]
I'm not so familiar with GitLab—does it basically use the same API as GitHub with regards to making information about the contents of repos consumable externally? I built a WireGitHub class that provides the connection for the modules directory. I could send it to you if it would be helpful to look at.

**Comment by BernhardBaumrock** [comment]
Hey @ryancramerdesign I switched my public modules to github now. But unfortunately the module version does not get updated either. I edited and saved this module: https://modules.processwire.com/modules/rock-finder/ but it still says v1.0.8 instead of 1.0.9: https://github.com/BernhardBaumrock/RockFinder/blob/master/RockFinder.info.php
Am I missing anything?

**Comment by BernhardBaumrock** [comment]
OK it worked now for my RockGrid module... strange. I'll see what happens on the next update of RockFinder :)
