### ISSUE TITLE
Module version inconsistencies

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#665]
I think there are quite some inconsistencies about module version numbers.

`'version' => 1013` would be `1.0.13` not `10.1.3`
on the modules directory `1013` would show up as `1013`
and the problem with string-based version numbers is that one cannot compare them incrementally: https://processwire.com/talk/topic/19767-which-version-numbers-do-you-use-integer-or-string/

Another loosely related comment is here: https://processwire.com/talk/topic/9633-module-bundle-version-numbers/?do=findComment&comment=92686

Thanks

**Comment by adrianbj** [comment]
Based on what you initially posted here I assume you figured out that string version numbers work great? I have been using them exclusively for some time now and I think they are the only way to go.

**Comment by BernhardBaumrock** [comment]
Yes, I thought I need numbers to compare versions - didn't know about php's version_compare()
