### ISSUE TITLE
Duplicating a Select Options field does not duplicate the selectable options setting

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#667]
### Short description of the issue

When duplicating a Select Options field (Edit Field > Actions > Duplicate/clone this field?, or Fields > Add New > Type: Clone existing field...) the selectable options setting for the duplicated field is not kept and must be filled out again. I expected that all field settings would be duplicated.

* ProcessWire version: 3.0.108

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai , I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks for the fix.
