### ISSUE TITLE
Admin Live Search: Exclude option has no effect

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#669]
### Short description of the issue

Exclude options has no effect on my system:
![screen shot 2018-08-15 at 15 12 08](https://user-images.githubusercontent.com/114080/44149803-a059a16e-a09d-11e8-942c-f1709cee4222.png)

### Expected behavior

Should have impact on search results, even for super admins if configured…

### Actual behavior

Does not have impact.

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.108 <br />
PHP: 7.1.20 <br />
Webserver: Apache <br />
MySQL: 5.5.56-MariaDB <br />
 <br />
</details><details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 360 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 360 <br />
max_input_vars: 20000 <br />
memory_limit: 3G <br />
post_max_size: 3G <br />
upload_max_filesize: 3G <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.9.8 <br />
AdminPageFieldEditLinks: 3.1.2 <br />
AdminThemeBoss: 0.2.4 <br />
BatchChildEditor: 1.8.12 <br />
BreadcrumbDropdowns: 0.1.1 <br />
ConnectPageFields: 0.1.9 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FormBuilder: 0.3.4 <br />
FrontEndEditLightbox: 1.4.0 <br />
IcfAttachments: 0.0.1 <br />
IcfDownloads: 0.0.1 <br />
IcfFeaturedImage: 0.0.2 <br />
IcfProcessInviteRequest: 0.0.1 <br />
IcfRangeDownload: 0.0.1 <br />
IcfTemplateTranslations: 0.0.1 <br />
IcfUnsplash: 0.0.2 <br />
IcfUtil: 0.0.1 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFormBuilderFile: 0.0.2 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
ModuleSettingsImportExport: 0.2.9 <br />
Oauth2Login: 0.1.0 <br />
PageimageRemoveVariations: 0.0.4 <br />
ProcessChildrenCsvExport: 1.7.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessFormBuilder: 0.3.4 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.2.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.10.24 <br />
WireMailMandrill: 0.0.1 <br />
IcfAuth: 0.0.2 <br />
</details>

**Comment by gmclelland** [comment]
I can confirm this is happening on sites with Processwire 3.0.110

**Comment by ryancramerdesign** [comment]
Thanks @noelboss and @gmclelland I've pushed a fix for this issue.

**Comment by noelboss** [comment]
This works no for me.
