### ISSUE TITLE
"Open when populated + Closed when blank" option does not work with non-default languages in multilanguage fields 

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#67]
### Short description of the issue

"Open when populated + Closed when blank" option does not work with non-default languages in multilanguage fields 

### Expected behavior

Field have to be open even though there is only translation for one non-default language.

### Actual behavior

"Open when populated + Closed when blank" option in presentation settings of field works only if default language is filled. But if non-default languages are filled it remains to be collapsed. The same behavior with or without "Languages Support - Tabs"

### Setup/Environment

ProcessWire: 3.0.39

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this in the latest commit to the dev branch.
