### ISSUE TITLE
Admin Live Search: Field RuntimeMarkup breaks

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#670]
### Short description of the issue

If a field of the type "[RuntimeMarkup](https://modules.processwire.com/modules/fieldtype-runtime-markup/)" is included as search field, the search does not display any pages anymore (only modules and users). For example, I had a "Fullname" field added, but adding this field broke search for other pages as well.

#### Search Results with RuntimeMarkup field "fullname"

![screen shot 2018-08-15 at 15 22 26](https://user-images.githubusercontent.com/114080/44150277-298c5052-a09f-11e8-890a-c2191f8b1914.png)

#### Search Results *without* RuntimeMarkup field "fullname"

![screen shot 2018-08-15 at 15 22 42](https://user-images.githubusercontent.com/114080/44150288-38992b24-a09f-11e8-8487-bedbc7c3911a.png)

### Expected behaviour

The search should still have results. Even if not including results for actual RuntimeMarkup fields since these are from a third-party module. Compatibility with the module would be even better.

### Actual behaviour

Does not display any pages any more.

### Steps to reproduce the issue

1. Add RuntimeMarkup to configured searchfields
2. Search for any page

### Setup/Environment

<details><summary><strong>Server Details</strong></summary>ProcessWire: 3.0.108 <br />
PHP: 7.1.20 <br />
Webserver: Apache <br />
MySQL: 5.5.56-MariaDB <br />
 <br />
</details><details><summary><strong>Server Settings</strong></summary> allow_url_fopen: 1 <br />
max_execution_time: 360 (changeable) <br />
max_input_nesting_level: 64 <br />
max_input_time: 360 <br />
max_input_vars: 20000 <br />
memory_limit: 3G <br />
post_max_size: 3G <br />
upload_max_filesize: 3G <br />
xdebug:  <br />
xdebug.max_nesting_level:  <br />
 <br />
mod_rewrite: 1 <br />
mod_security:  <br />
 <br />
GD: bundled (2.1.0 compatible) <br />
GIF: 1 <br />
JPG: 1 <br />
PNG: 1 <br />
 <br />
EXIF Support: 1 <br />
FreeType: 1 <br />
Imagick Extension: 1 <br />
 <br />
</details><details><summary><strong>Module Details</strong></summary> AdminOnSteroids: 1.9.8 <br />
AdminPageFieldEditLinks: 3.1.2 <br />
AdminThemeBoss: 0.2.4 <br />
BatchChildEditor: 1.8.12 <br />
BreadcrumbDropdowns: 0.1.1 <br />
ConnectPageFields: 0.1.9 <br />
CronjobDatabaseBackup: 1.1.5 <br />
FieldtypeAssistedURL: 1.0.0 <br />
FieldtypeFieldsetGroup: 0.0.2 <br />
FieldtypeFunctional: 0.0.1 <br />
FieldtypeMultiplier: 0.1.1 <br />
FieldtypeRepeaterMatrix: 0.0.4 <br />
FieldtypeRuntimeMarkup: 0.0.2 <br />
FieldtypeTable: 0.1.5 <br />
FieldtypeTextareas: 0.0.7 <br />
FormBuilder: 0.3.4 <br />
FrontEndEditLightbox: 1.4.0 <br />
IcfAttachments: 0.0.1 <br />
IcfDownloads: 0.0.1 <br />
IcfFeaturedImage: 0.0.2 <br />
IcfProcessInviteRequest: 0.0.1 <br />
IcfRangeDownload: 0.0.1 <br />
IcfTemplateTranslations: 0.0.1 <br />
IcfUnsplash: 0.0.2 <br />
IcfUtil: 0.0.1 <br />
InputfieldAssistedURL: 1.0.1 <br />
InputfieldChosenSelect: 1.2.3 <br />
InputfieldChosenSelectMultiple: 1.1.9 <br />
InputfieldFormBuilderFile: 0.0.2 <br />
InputfieldFunctional: 0.0.1 <br />
InputfieldMultiplier: 0.1.1 <br />
InputfieldRepeaterMatrix: 0.0.4 <br />
InputfieldRuntimeMarkup: 0.0.2 <br />
InputfieldTable: 0.1.5 <br />
InputfieldTextareas: 0.0.7 <br />
LoginRegister: 0.0.2 <br />
LoginWithEmail: 0.0.3 <br />
ModuleSettingsImportExport: 0.2.9 <br />
Oauth2Login: 0.1.0 <br />
PageimageRemoveVariations: 0.0.4 <br />
ProcessChildrenCsvExport: 1.7.0 <br />
ProcessForgotPassword: 1.0.2 <br />
ProcessFormBuilder: 0.3.4 <br />
ProcessSwitchUser: 0.0.6 <br />
ProcessTagParserTest: 1.0.0 <br />
ProcessWireUpgrade: 0.0.7 <br />
ProcessWireUpgradeCheck: 0.0.7 <br />
TextformatterMakeLinks: 1.0.0 <br />
TextformatterOEmbed: 2.0.2 <br />
TextformatterTagParser: 2.2.0 <br />
TextformatterVideoEmbedOptions: 0.3.5 <br />
TracyDebugger: 4.10.24 <br />
WireMailMandrill: 0.0.1 <br />
IcfAuth: 0.0.2 <br />
</details>

**Comment by ryancramerdesign** [comment]
I don't have experience with the module you've mentioned, but am guessing that it's likely got a PHP notice/warning or something (Exception?) that is interfering with the ajax results. It might be good to check in with the module author for this one first as PW isn't doing anything other than a $pages->find() for these live search results on pages. A couple other things you could try: 1) testing with debug mode turn off, which might point out of a PHP notice in the module is the culprit; 2) try hitting enter on the search box after typing in your phrase, as that displays the results without ajax and might better reveal error messages.

**Comment by Toutouwai** [comment]
@noelboss, you cannot search for the values of RuntimeMarkup fields because they are runtime only.

The module readme says:

> The value for this fieldtype is generated at runtime and thus no data is stored in the database. This means that you cannot directly query a RuntimeMarkup field from $pages->find().

And the module throws an exception if you try and include a RutimeMarkup field in a search: https://github.com/kongondo/FieldtypeRuntimeMarkup/blob/902b13dcd43d5605c3ceb9fd62a5e4d2b8004daf/FieldtypeRuntimeMarkup.module#L179-L182

**Comment by gmclelland** [comment]
@noelboss - Based on @Toutouwai 's comment.  I guess this issue can be closed?

**Comment by netcarver** [comment]
Closing this issue, feel free to comment or open new issue if needed.
