### ISSUE TITLE
Admin Live Search: User Templates displayed twice

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#671]
### Short description of the issue

Queries that match a user also show up in the Pages section **when search fields are added to the "Page fields to search" that are also part of the user template**:

![screen shot 2018-08-15 at 15 26 47](https://user-images.githubusercontent.com/114080/44150599-3ec3373c-a0a0-11e8-9cfe-c47b19c79ba5.png)

### Expected behavior

Results matching User-Templates should always only show up in the User-Section.

### Actual behavior

Users show up twice.

### Stepps to reproduce

1. Add a field that is part of the user-template (f.e. email) to "Page fields to search" in the search settings 
2. Save the settings
3. Search for an email…

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.110|
|PHP|7.0.30-1+ubuntu14.04.1+deb.sury.org+1|
|Webserver|Apache/2.4.7 (Ubuntu)|
|MySQL|5.5.60-0ubuntu0.14.04.1|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|120|
|max_input_vars|1000|
|memory_limit|256M|
|post_max_size|120M|
|upload_max_filesize|500M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|2.2.5|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminOnSteroids|2.0.2|
|AdminPageFieldEditLinks|3.1.2|
|AdminThemeBoss|0.2.4|
|BatchChildEditor|1.8.12|
|BreadcrumbDropdowns|0.1.2|
|ConnectPageFields|0.1.9|
|CronjobDatabaseBackup|1.1.5|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.2|
|FieldtypeFunctional|0.0.1|
|FieldtypeMultiplier|0.1.1|
|FieldtypeRepeaterMatrix|0.0.4|
|FieldtypeRuntimeMarkup|0.0.2|
|FieldtypeTable|0.1.5|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|FrontEndEditLightbox|1.4.0|
|IcfAttachments|0.0.1|
|IcfDownloads|0.0.1|
|IcfFeaturedImage|0.0.2|
|IcfProcessInviteRequest|0.0.1|
|IcfRangeDownload|0.0.1|
|IcfTemplateTranslations|0.0.1|
|IcfUnsplash|0.0.2|
|IcfUtil|0.0.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldChosenSelect|1.2.3|
|InputfieldChosenSelectMultiple|1.1.9|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.1|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.4|
|InputfieldRuntimeMarkup|0.0.2|
|InputfieldTable|0.1.5|
|InputfieldTextareas|0.0.7|
|LoginRegister|0.0.2|
|LoginWithEmail|0.0.3|
|ModuleSettingsImportExport|0.2.9|
|Oauth2Login|0.1.0|
|PageimageRemoveVariations|0.0.4|
|ProcessChildrenCsvExport|1.7.0|
|ProcessForgotPassword|1.0.2|
|ProcessFormBuilder|0.3.4|
|ProcessSwitchUser|0.0.6|
|ProcessTagParserTest|1.0.0|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|TextformatterMakeLinks|1.0.0|
|TextformatterOEmbed|2.0.2|
|TextformatterTagParser|2.2.0|
|TextformatterVideoEmbedOptions|0.3.5|
|TracyDebugger|4.10.35|
|WireMailMandrill|0.0.1|
|IcfAuth|0.0.2|
</details>

**Comment by gmclelland** [comment]
Hmm... I'm not seeing that behavior on my setup.  There has been improvements to the autocomplete since 3.0.108.  I would recommend testing with the latest dev version of Processwire.

**Comment by noelboss** [comment]
@gmclelland – it is also happening on 3.0.10

**Comment by gmclelland** [comment]
I'm using 3.0.110 and I'm not seeing that behavior.  I tried it on two different sites.  Maybe it's somehow related to the RuntimeMarkup Module that you were having a problem with?

Some ideas you might can try:
- disabling the RuntimeMarkup module?
- disabling all non-core modules?
- reviewing any hooks that could be interfering somehow? in init.php or ready.php
- test the same site on a different server
- create a new site with just the minimum needed to test if you see the problem

It could be that our site's configurations are different?  I'm just not sure what the difference could be yet.

Sorry, I haven't studied the code enough to really be of help.

Have you changed any of the Page Search module's settings?  If so, maybe include a screenshot.

**Comment by noelboss** [comment]
@gmclelland yep, it only happenes **when search fields are added that match user pages** as stated in the issues description above.

**Comment by ryancramerdesign** [comment]
Thanks @noelboss and @gmclelland I have pushed a fix for this issue

**Comment by noelboss** [comment]
Thanks @ryancramerdesign works
