### ISSUE TITLE
Dragging an image onto a CkEditor textarea doesn't insert hidpi version

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#673]
### Short description of the issue

Dragging an image onto a CkEditor doesn't create hidpi version.

### Expected behavior

Expected a hidpi version of the image to be inserted into the textarea if the setting in ProcessPageEditImageSelect at /processwire/module/edit?name=ProcessPageEditImageSelect is selected.

![hidpi](https://user-images.githubusercontent.com/40570/44173074-8dddbc80-a0a4-11e8-94be-0d334f0f441c.jpg)

### Actual behavior

The image is uploaded and inserted into the text area without the hidpi version
```html
<img src="/site/assets/files/1328/independence-visitor-center-philadelphia-ext-1400.jpg" width="1400" />
```
Instead of
```html
<img alt="" class="hidpi" src="/site/assets/files/1328/museum-philadelphia-1400.500x0-is-hidpi.jpg" width="500" />
```

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.110|
|PHP|7.1.20|
|Webserver|Apache/2.4.33 (Unix) OpenSSL/1.0.2g|
|MySQL|5.7.23-0ubuntu0.16.04.1-log|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|300 (changeable)|
|max_input_nesting_level|64|
|max_input_time|-1|
|max_input_vars|5000|
|memory_limit|256M|
|post_max_size|1024M|
|upload_max_filesize|512M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension||
</details>

**Comment by ryancramerdesign** [comment]
When you drag an image into CKEditor, it does not go through ProcessPageEditImageSelect, which is a completely separate process. Those module settings are unrelated to dragging/dropping images in CKEditor. When you drag an image into CKE, if you want to edit it afterwards (like configuring the setting you mentioned) you'd want to double click it, which will open ProcessPageEditImageSelect and enable you to edit it.

**Comment by gmclelland** [comment]
Thanks Ryan, I understand.  I was hoping CKEditor's drag n' drop upload feature could somehow respect that setting in ProcessPageEditImageSelect so that site editors are consistently inserting images with the Hidpi version regardless of which way they choose.  No biggie, for now I'll just advise them to go through ProcessPageEditImageSelect instead of dragging and dropping an image on the text area to upload.

Maybe someone can move this from the issue repository to the feature request repo?

**Comment by netcarver** [comment]
@gmclelland Hi Glenn, I don't think the issue can be moved - I think you have to close it here and re-open in the requests repository.

**Comment by netcarver** [comment]
@gmclelland Hi Glenn, I'm closing the issue. Please open this as a feature request if you need it.
