### ISSUE TITLE
No Language Support Blank behaviour for module config settings

### ISSUE THREAD

**Issue by ro-webdesign** [processwire/processwire-issues#676]
### Short description of the issue

In a module that has language-enabled config settings fields, there is no option for inheriting the default 
language when the field's default value is blank. This differs from PW native language-enabled fields where the behaviour can be configured at field settings level, but defaults to "Inherit value from default language".

Discussion with examples here: [https://processwire.com/talk/topic/19525-cookie-management-banner/?page=3&tab=comments#comment-171453](https://processwire.com/talk/topic/19525-cookie-management-banner/?page=3&tab=comments#comment-171453)

### Expected behavior

When a module's config setting is rendered on the front end of the site, and non-default language values for that setting are left blank, if a user's context is for a non-default language, that field shouldn't by default render a blank value.

### Actual behavior

Module setting renders a blank value if nothing is entered for that language.

### Steps to reproduce the issue

1. Install multi-language support and add at least one non-default language
2. Install a module that renders config settings on the front end (e.g. CookieManagementBanner) for config settings with 'useLanguages' => true
3. Enter module setting content for the default language but not for the non-default language(s).
4. Display a page on the site that renders the values from this module. When viewed in the non-default language context, the module setting displays nothing.

### Setup/Environment

* ProcessWire version: 3.0.98
* PHP version: 5.4.28 -  7.0.31
* Any 3rd party modules that are installed and could be related to the issue:  CookieManagementBanner, only because this is where the issue was noticed.

**Comment by netcarver** [comment]
@ro-webdesign I'm going to re-open this one over in the request repository.
