### ISSUE TITLE
mail() PHP 7.1 compatibility - Escaped command exceeds the allowed length

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#68]
### Short description of the issue

With php 7.1 you get that fatal error message because the $param variable is blank

### Expected behavior

No error

### Actual behavior

Fatal error message

### Optional: Suggestion for a possible fix

So long as $param is not null it seems to work fine. I got this tip from this: https://github.com/PHPMailer/PHPMailer/issues/861

I know you already check for null and set to an empty string, but perhaps 7.1 is for some reason considering `''` as null in this case? 

So long as $param contains something more than an empty string the error goes away.

### Setup/Environment

* ProcessWire version: 3.0.39
* (Optional) PHP version: 7.1

**Comment by ryancramerdesign** [comment]
Adrian, where are you seeing the error message? I'm guessing in the wire/core/WireMail.php file mail() command, but just wanted to double check that's what you are talking about?

**Comment by adrianbj** [comment]
Yes, exactly! Sorry for not being clear on that.

**Comment by ryancramerdesign** [comment]
Now that I think about it, all of our mail() have been converted to WireMail, so that's likely the only one there is in PW. Looking at the mail function docs on php.net, it seems like this is likely a bug in PHP 7.1, but it's easy enough to workaround–I've pushed an update that fixes it. Thanks.

**Comment by adrianbj** [comment]
Thanks - looks good!
