### ISSUE TITLE
ProcessLanguageTranslator is showing /site/asset/ files

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#680]
### Short description of the issue

ProcessLanguageTranslator Line [668](https://github.com/processwire/processwire/blob/master/wire/modules/LanguageSupport/ProcessLanguageTranslator.module#L668) is not working to avoid showing asset folders' files.

I can confirm that it is the backslash and forward slash issue in Windows.
`Example pathname /site\assets\cache`

### Expected behavior

Files inside /asset/ should not be showing  in the translation file list.

### Actual behavior

Files inside /asset/ are showing in the translation file list, mostly inside FileCompiler.

### Setup/Environment

* ProcessWire version: 3.0.106
* Windows version: 10

**Comment by netcarver** [comment]
@karltdev Hello Karl, can this be closed now?

**Comment by netcarver** [comment]
/remind me to review and close if necessary in 1 week

**Comment by karltdev** [comment]
Yes. I close it now.
