### ISSUE TITLE
Exceptions in fieldtypes caught 

### ISSUE THREAD

**Issue by LostKobrakai** [processwire/processwire-issues#681]
### Short description of the issue

Based on the [latest blogpost on transactions](https://processwire.com/talk/topic/19818-blog-post-using-innodb-with-processwire/) I was looking to create some examples for how easy it is to get broken pages saved. While experimenting I found that errors in Fieldtypes seem to be caught by processwire, so even if there's a transaction it's not rolled back.

### Expected behavior

A thrown exception in a fieldtype somewhere on the path to save a value should not be caught.

### Actual behavior

It is caught somewhere.

### Steps to reproduce the issue

1. Install a fresh instance of processwire (I used the blank preset)
3. Put `if($value == "Test") throw new \Exception("test");` in `Fieldtype::___sleepValue()`
2. Put the following codeblock in `home.php` or somewhere it's executable
4. Execute the code creating the new page. The transaction is not rolled back even though there's an error happening.

```
try {
        $database->beginTransaction();

	$p = new Page();
	$p->template = 'basic-page';
	$p->parent = '/';
	$p->title = "Test";
	$p->save();  

	$database->commit();

} catch(\Exception $e) {
        $database->rollBack();
}
```

* ProcessWire version: 3.0.98 (master)
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Thanks @LostKobrakai I've pushed a fix for this issue

**Comment by netcarver** [comment]
@LostKobrakai Hi Benjamin, can this be closed now?
