### ISSUE TITLE
$pages->findOne() finds unpublished page

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#683]
### Short description of the issue

The docs for `$pages->findOne()` say that the method filters for access control and published state in the same way as `$pages->find()` does. But for some reason it matches an unpublished page in the example below.

![2018-08-20_152655](https://user-images.githubusercontent.com/1538852/44319166-45e8dc00-a48e-11e8-86ea-fd8e85477031.png)

`$pages->find()` does not match the page, as expected.

Clean PW 3.0.110 installation, no hooks or modules (besides Tracy).

### Setup/Environment

* ProcessWire version: 3.0.110

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this issue

**Comment by Toutouwai** [comment]
Thanks for the fix.
