### ISSUE TITLE
$modules->getModuleEditUrl method does not exist

### ISSUE THREAD

**Issue by karltdev** [processwire/processwire-issues#684]
### Short description of the issue

From the API reference in official website, I found this [page](https://processwire.com/api/ref/modules/get-module-edit-url/) about `$modules->getModuleEditUrl()`. However, this method does not exist in the core.

### Setup/Environment

* ProcessWire version:  3.0.111

**Comment by adrianbj** [comment]
Works for me and you can see the method here: https://github.com/processwire/processwire/blob/aa34e8a0f76e45a9acf142d88b469cbd6974f122/wire/core/Modules.php#L3186
![image](https://user-images.githubusercontent.com/871211/44619129-805bcb80-a836-11e8-9ce8-4b8aff6f1997.png)

**Comment by karltdev** [comment]
Sorry my bad. The github search is not working properly. I am using 3.0.96 which does not possess this method yet. I am closing this.

**Comment by adrianbj** [comment]
No worries - just so you know the Github search only works on the `master` branch.
