### ISSUE TITLE
Some templates no longer selectable on Settings > Template

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#685]
### Short description of the issue

Templates no longer selectable on Settings > Template

### Expected behavior

Up until either 3.0.110/3.0.111 you could select a template for a root page (child of homepage) that was marked as "No" or "One" in the "Can this template be used for new pages?" template setting. 

Obviously not being able to select a template marked as "No" is the correct behaviour, although this bug was actually extremely useful! Templates marked as "One" should still be selectable though, if they haven't already been used.

### Actual behavior

Template is not selectable unless marked as "Yes".

### Steps to reproduce the issue

1. Create new template
2. Set "noParents" (Can this template be used for new pages?) to "One"
3. Create a new page (child of homepage)
4. Try and select this template

### Setup/Environment
* ProcessWire version: 3.0.111

**Comment by cb2004** [comment]
I can reproduce

**Comment by chriswthomson** [comment]
Hi Adrian,

Yes I think this is related - didn't spot this earlier. Perhaps Ryan has done what he suggested here and made superusers no longer immune to noParents.

However, the "One" is still a bug I think?

**Comment by chriswthomson** [comment]
@cb2004 - Yes definitely, I think this is a bug. I'll miss being able to select a template regardless of the "noParents" setting, but if the "One" option is working correctly then it is still workable.

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson @cb2004 @adrianbj I have pushed a fix for this issue. Also since it sounds like some still want to have a template be selectable even configured or only 1 allowed, I have modified it so that it still retains the old behavior for superuser if advanced mode enabled `$config->advanced == true;`

**Comment by chriswthomson** [comment]
Hi Ryan,

That's great - advanced mode is a good solution too for retaining the old behaviour. 

Cheers,

Chris
