### ISSUE TITLE
Pagelist - Individual page titles as set in template - what about the checkbox?

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#686]
In a template I set the page title to show a checkbox:
 **{title} | {checkbox}**

<img width="741" alt="bildschirmfoto 4" src="https://user-images.githubusercontent.com/652879/44883105-567f2a80-acb6-11e8-9d3a-c643173f93c4.png">

I remember that this worked (I saw a 0 or 1 for the checkbox in the pagelist)
Since some PW dev updates I do not see a value for the checkbox any more.
Unless I did something wrong here, that feature has disappeared.

ProcessWire 3.0.111 © 2018

**Comment by ryancramerdesign** [comment]
Thanks @tbba and @Toutouwai I have pushed a fix for this issue

**Comment by tbba** [comment]
Great it works again - now with an icon (very small but it's there)
