### ISSUE TITLE
Error message can't translated for moving page to parent and it's restricted

### ISSUE THREAD

**Issue by andoro** [processwire/processwire-issues#690]
### Short description of the issue

This error msg cannot be translated:
Can’t save page %pageID: %pageName: Cannot move '%pageName' because template '%parentPageTemplate' used by page '%parentPage' does not allow children using template '%pageTemplate'.

### Expected behavior

The message should be found in any of the translation files.

### Actual behavior

The message cannot be found in any of the translation files.

### Optional: Screenshots/Links that demonstrate the issue

<img width="1440" alt="ss" src="https://user-images.githubusercontent.com/775765/45264688-ef454100-b440-11e8-862a-c1f7c93cc1a1.png">

### Steps to reproduce the issue

1. Restrict a template (lets call it t01) to accept only defined templates (lets call it t02) for childrens
2. Move a page with different template then t02 as a child page to a page with template t01
3. You will get an error which cannot be translated

* ProcessWire version: 3.0.112 dev
* (Optional) PHP version: 7.2.9

**Comment by ryancramerdesign** [comment]
Thanks @andoro I've pushed an update that makes those error messages translatable

**Comment by andoro** [comment]
Thank you @ryancramerdesign! Will it be included in the next version?

**Comment by netcarver** [comment]
Closing as last stable release included this fix.
