### ISSUE TITLE
Language Support - Tab Text Colours - Improvement Suggestion

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#691]
This indicator would be immensely useful for folks working on multi-language websites to see what does and doesn't have a translation on the current page: https://processwire.com/talk/topic/19708-language-support-tab-text-colours-improvement-suggestion/

As tpr says though the tweak doesn;t work for image descriptions so some additional tweaks would be required there: https://processwire.com/talk/topic/19708-language-support-tab-text-colours-improvement-suggestion/?do=findComment&comment=172816

**Comment by Toutouwai** [comment]
Should be in the requests repo?
https://github.com/processwire/processwire-requests

**Comment by Notanotherdotcom** [comment]
You're right - it's been so long I didn't realise it was there. Will close and add it there.
