### ISSUE TITLE
InnoDB about 20x slower than MyISAM when creating or deleting pages

### ISSUE THREAD

**Issue by mestaritonttu** [processwire/processwire-issues#692]
This has been confirmed in two separate forum threads.
[Thread with testcase](https://processwire.com/talk/topic/19824-innodb-performance-with-csv-import-way-worse-than-myisam-does-pw-core-need-adapting/)
[Most recent thread](https://processwire.com/talk/topic/19934-importing-pages-and-empting-trash-incredibly-slow/)

**Comment by LostKobrakai** [comment]
May I ask what processwire should do about that? Seems to me like that's an issue with mysql.

**Comment by mestaritonttu** [comment]
Well, it's a bit much to ask, but it seems like PW's database would have to be redesigned in order for InnoDB perf to match MyISAM .
[The SE topic](https://dba.stackexchange.com/a/75150) adrian linked to from the thread with the testcase illustrates the nuances of the matter.

> No matter which version of MySQL (Oracle, Percona, MariaDB) you use, none of them can fight to one enemy they all have in common : The InnoDB Architecture.

**Comment by teppokoivula** [comment]
Based on my (very limited) understanding of the differences of MyISAM and InnoDB, there are a number of factors that can affect the performance comparison – at least these:

- Type, number, and other specifics of the indexes
- Datatypes
- Queries (and thus data architecture)

Honestly I have no idea if – and what – we could tweak to make InnoDB perform better, but it does seem like it should at least be investigated a bit before drawing the conclusion that "InnoDB is slow, deal with it".

20x sounds like a major bottleneck. I've heard before of the differences in the scale of x1-2, though :)

**Comment by ryancramerdesign** [comment]
InnoDB can be a lot slower with some mass operations like emptying a very-full trash, or performing mass imports, etc. It really has to be, given the nature of it (just take row-level locking as an example). But for everyday site operation, performance should be strong, and I'd think for most the upsides outweigh the downsides. On the other hand, if you need to perform these mass operations every day (the ones where InnoDB can be slow) and they aren't something that can happen in the background, then no doubt MyISAM may be a better choice for that case. But if you are doing these things on a live site, then consider that the MyISAM version may bring the rest of the site to a halt, while the InnoDB version might take longer, but not affect the performance of the site to everyone else. It's a good compromise in my mind. I'm not aware of any specific things we can change to make InnoDB perform like MyISAM on those mass operations, but I've also expected that with the benefits of InnoDB also come the overhead of time to perform them. For most PW users, I think these time consuming mass operations are rare, so don't see it as a reason to avoid InnoDB.

**Comment by mestaritonttu** [comment]
Ryan's reply prompted me to investigate further on how to play better with InnoDB. To my delight I discovered I could import the 35,5k page test case CSV into an InnoDB PW in mere 2 min 44 sec after I edited Batch Child Editor's code to use transactions! So this actually halves the time MyISAM spends on the import.

Concretely, in the .module file before the block
`foreach($childPagesArray->data as $row) {`
I put
```
$engine = strtolower($this->wire('config')->dbEngine);
if($engine == 'innodb') {
    $this->wire('database')->beginTransaction();
}
```
And after the block I put
```
if($engine == 'innodb') {
    $this->wire('database')->commit();
}
```
This leaves us with the trash emptying. Ryan: would you consider adding such logic to the trash emptying?

From what I read, perhaps there is a need for having a more sophisticated logic, splitting to blocks of 1000: https://mariadb.com/kb/en/library/how-to-quickly-insert-data-into-mariadb/#inserting-data-with-insert-statements

> The reason why you may want to have many BEGIN/END statements instead of just one is that the former will use up less transaction log space.

**Comment by teppokoivula** [comment]
Just for the record, the optimizations mentioned above by @mestaritonttu are similar to the ones I ran into as well while skimming through a couple of InnoDB optimization articles. Thanks for putting up a test case!

It does indeed seem that there are things we can do to speed up at least some "special cases", such as emptying the trash or importing/exporting large number of rows :)

**Comment by adrianbj** [comment]
I am certainly happy to add those transaction bits to the BatchChildEditor module. I was just waiting to get @ryancramerdesign's take on things.

I also wonder if my TableCSVImportExport will benefit from this. Also @kongondo's FieldtypeMatrix? And I bet there are others as well.

**Comment by LostKobrakai** [comment]
> One of the InnoDB articles is this by Ryan himself :) https://processwire.com/blog/posts/using-innodb-with-processwire/
>
> In the article, note the try catch with $database->rollBack(); upon exception.

To be fair, that's less about performance and more about one of the selling points of InnoDB over MyISAM: Being able to garantee that the database stays in a consistent state even if something goes wrong between multiple dependant changes. I actually would like to see processwire use transactions more in the core to prevent e.g. partially saved pages in the face of errors. But they're certainly not there for performance optimization reasons.

**Comment by ryancramerdesign** [comment]
I've added a `$database->supportsTransaction(optional $table = '');` method if it's helpful for any of this. I experimented with wrapping the trash deletion in a transaction, but not seeing any difference here so didn't commit it yet. I hadn't really ever noticed the performance issues described, though maybe just don't have a project with the right scale to see it at present. I do have one dev site with 500k pages in the trash, which is my current "trash test" install, but thus far have not been able to successfully delete them regardless of DB engine or transactions. :)

Also, PW page manipulation/deletion actions usually involve not just database but file system, which makes transactions not quite as useful, but I'm working on a solution for that (transactions for files basically).

**Comment by mestaritonttu** [comment]
> I experimented with wrapping the trash deletion in a transaction, but not seeing any difference here so didn't commit it yet.

Can you share a diff? I could give feedback on the perf. Great to hear about you tinkering with this.

**Comment by ryancramerdesign** [comment]
@mestaritonttu I've pushed my updates to the trash process. It now uses InnoDB transactions if support is there. The empty trash screen now gives you a "pages trashed per second" (PTPS) rate for comparison. My trash has about 450k pages in it at present, and I'm getting a rate of around 10 PTPS with InnoDB. I get the same rate whether transactions are enabled or not, so not sure if I might be missing something important in terms of gaining the performance benefit here? 

With MyISAM I get about 30 PTPS. Though his MyISAM installation only had a couple hundred pages in the trash, so this might not be good enough for comparison purposes. The trash process lets you specify a time limit now, and 30 or 60 seconds seems to be good for testing. What kind of rates do you see there?

**Comment by mestaritonttu** [comment]
That's a nice perf measurement system :)
I put 35k pages in my trash.
At first I did not think to check the time limit:

> Deleted 7200 pages (239 pages per second) - Not all pages could be deleted (28357 remain) - Time limit reached (30 seconds).

I set the time limit to 600

> Deleted 10000 pages (276 pages per second) - Not all pages could be deleted (18357 remain)

Then I was in another tab and missed the next notice when coming back.
Final one was:

> Deleted 8357 pages (360 pages per second)

So your changes have most definitely solved the trash-emptying bottleneck for me! Also, this is without any special MySQL settings, just defaults. PHP settings are (from my docker-compose file):
      PHP_MAX_EXECUTION_TIME: 1000
      PHP_MEMORY_LIMIT: 4096M
      PHP_UPLOAD_MAX_FILESIZE: 4096M
      PHP_POST_MAX_SIZE: 4096M
      PHP_MAX_INPUT_TIME: 1000
      PHP_MAX_INPUT_VARS: 10000

I'll go ahead and close this as the creation part is really the responsibility of batch import modules. Thanks!

**Comment by ryancramerdesign** [comment]
Glad to hear that seems to have sped things up! What kind of computer are
you using? That pages deleted/per second rate is pretty amazing. I get
between 6 and 15 per second with InnoDB or up to 30 per second with MyISAM.
Your computer must be a whole lot faster than mine!

**Comment by adrianbj** [comment]
> the creation part is really the responsibility of batch import modules. 

@mestaritonttu - would you be willing to put together a PR to add this to the BatchChildEditor module?

**Comment by mestaritonttu** [comment]
I have a desktop bought in early 2016: Intel i7-6700k, 32GB memory, low-end SSD storage.

@adrianbj OK, I will try to create a PR with exception handling included :)
