### ISSUE TITLE
Tree menu does not honour listable property

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#695]
### Short description of the issue

The flyout Tree menu is generated by ProcessPageList and is a kind of page list, so the expectation is that it will honour the `$page->listable` property.

Demo case:

```php
$wire->addHookAfter('Page::listable', function (HookEvent $event) {
    $page = $event->object;
    if($page->title === 'Not listable') $event->return = false;
});
``` 

![2018-09-11_215959](https://user-images.githubusercontent.com/1538852/45353400-cffc0e80-b60e-11e8-907d-4198ab170d49.png)

This is caused by the order of if/else conditions here: https://github.com/processwire/processwire/blob/e2478aa401c99bd5bc9c3058a6612b3af950be79/wire/modules/Process/ProcessPageList/ProcessPageList.module#L533-L540

### Suggestion for a possible fix

Make `$page->listable` the first test - when it comes to appearing in a list, setting listable to false should take precedence over whether the page is editable or viewable.

```php
if(!$page->listable()) {
	continue;
} else if($page->editable()) {
	$url = $page->editUrl();
	$editable = true;
} else if($page->viewable()) {
	$url = $page->url();
}
``` 

### Setup/Environment

* ProcessWire version: 3.0.110

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed your suggested fix for this.

**Comment by Toutouwai** [comment]
Thanks.
