### ISSUE TITLE
Unmovable pages can't be Restored from the Trash

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-issues#697]
### Short description of the issue

In order to restore pages from the Trash.  I have to edit a template's setting under Advanced > Uncheck "Allow pages to be moved."  Correct me if I'm wrong, but that seems like a bug?

### Expected behavior

Even if a page isn't movable, I still expected to be able to restore the page to it's original location.

### Actual behavior

Pages can't be restored from the Trash.  Shows a javascript popup alert with a permissions warning.

### Steps to reproduce the issue
In my case I have two templates.  NewsIndex and NewsPosting.

NewsIndex contains only NewsPostings.  I don't want editors moving NewsPostings to another location in the tree, so I checked the "Don't allow pages to be moved" setting in the NewsPosting template settings under the advanced tab.

Now I delete some NewsPostings.  Now I want to restore the NewsPostings from the trash, but it won't let me.

**Comment by ryancramerdesign** [comment]
Thanks @gmclelland I've pushed a fix for this issue.

**Comment by gmclelland** [comment]
Thank you Ryan.  Just tested and it works now.
