### ISSUE TITLE
PW Website - Version numbers different

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#7]
> Briefly describe the issue.

On processwire.com - on the home page - there is a download button which says 3.0.34 and 2.8.34. But, on the actual Downloads, I'm only offered 3.0.34 and 2.8.33.

**Comment by ryancramerdesign** [comment]
This is because the processwire-legacy repo was not yet setup. It is now there, so the version download links should now be up-to-date.
