### ISSUE TITLE
Permissions: Save + Publish / Save + Publish + Add Another not working

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#700]
### Short description of the issue

When adding a new permission there are three buttons:

![2018-09-15_115240](https://user-images.githubusercontent.com/1538852/45579686-e4295f80-b8dd-11e8-8531-c43682cc9376.png)

The Save + Publish and Save + Publish + Add Another buttons don't do what they say because the permission title is a required field that must be filled out on the next step before the permission can be published.

### Suggestion for a possible fix

Either remove the Save + Publish / Save + Publish + Add Another buttons or show the Title field on the first step of Add New.

### Setup/Environment

* ProcessWire version: 3.0.111

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks.
