### ISSUE TITLE
Changing the Button label ( Download And Install )

### ISSUE THREAD

**Issue by rafaoski** [processwire/processwire-issues#701]
### Short description of the issue
In the latest version 3.0.113 DEV there is a small problem with the button label when adding a new module the text is different than in previous versions as below on the screen shot:  

![install-1](https://user-images.githubusercontent.com/12895367/45626011-9e5fc900-ba8e-11e8-814a-1952ee0e7df3.png)  

![install-2](https://user-images.githubusercontent.com/12895367/45626025-b0416c00-ba8e-11e8-856c-bdb5988d8406.png)

### Optional: Suggestion for a possible fix
Changing the Button label ( Get Module Info ) to ( Download And Install ) inside module ( ProcessModule.module )
/wire/modules/Process/ProcessModule/ProcessModule.module

Change line 536:  
$f->value = $this->labels['get_module_info'];  
Change line 527:  
$this->labels['get_module_info']  
Change line 1004:  
$btn->value = $this->labels['download_now'];

**Change To:**   

Line 536:    
$f->value = $this->labels['download_install'];  
Change line 527:  
$this->labels['download_install']  
Line 1004:   
$btn->value = $this->labels['download_install'];

### Steps to reproduce the issue

1. Go to the Modules menu and add a module from the catalog. You will notice a different name of the installer button and an incorrect installer hint name.  

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.113|
|PHP|7.2.8|
|Webserver|Apache/2.4.34 (Unix) |
|MySQL|10.1.34-MariaDB|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|256M|
|post_max_size|8M|
|upload_max_filesize|20M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|2.2.5|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support||
|FreeType|1|
|Imagick Extension||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|TracyDebugger|4.11.28|
</details>

**Comment by matjazpotocnik** [comment]
Isn't wording changed because of https://github.com/processwire/processwire-issues/issues/641 ?

**Comment by rafaoski** [comment]
Looks like you're right ... I could have delved into the topic ... Thanks for checking ...
