### ISSUE TITLE
Changing image focus causes image sizer quality option to be ignored

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#702]
### Short description of the issue

If the focus area for an image is changed it causes any image sizer quality option passed in to `size()` to be ignored.

In this example the quality is set very low which is obvious in the resulting image on the front-end:
```php
<img src="<?= $page->image->size(200,300, ['quality' => 10])->url ?>" alt="">
```
![2018-09-18_212539](https://user-images.githubusercontent.com/1538852/45677906-6f7a4d80-bb89-11e8-9447-0e9e2d7b1cc2.png)

If the focus area for the image is changed in Page Edit then a new variation is generated but this ignores the quality setting. This can be seen in the resulting image on the front-end, which is now clearly not using the quality setting passed in to `size()`:

![2018-09-18_212740](https://user-images.githubusercontent.com/1538852/45678039-b5cfac80-bb89-11e8-8763-c548bc486566.png)

Not sure if other image sizer options are also lost when the focus is changed.

### Expected behavior

Changing focus in admin does not affect the specified image sizer options.

### Setup/Environment

* ProcessWire version: 3.0.113

**Comment by ryancramerdesign** [comment]
The quality setting is not something that is physically stored anywhere (other than your method call), so I don't think there's anything that we can do here. When PW re-creates images, it uses whatever quality setting is defined in the site's configuration.

**Comment by Toutouwai** [comment]
> The quality setting is not something that is physically stored anywhere (other than your method call), so I don't think there's anything that we can do here.

I've responded to this in the [other issue](https://github.com/processwire/processwire-issues/issues/703#issuecomment-423241953) relating to focus changes and image variations.

**Comment by teppokoivula** [comment]
Just a thought, but if we can't reliably re-create the thumbs *as the developer intended*, we probably shouldn't try to re-create them in the first place.

I know I'm probably skipping a few important steps here, but it seems to me that the current approach means that we're just guessing and possibly doing something very wrong, while allowing code to re-create the thumbnails would be a perfectly fine solution that shouldn't mess up anything.

Please correct me if I'm wrong, but with aforementioned issue in mind I'd like to suggest dropping the (broken) re-creation process if it's (by design) impossible to fix :)

**Comment by teppokoivula** [comment]
Note: the same thought process applies to issue #703: not only are we re-creating thumbnails with wrong settings, we're also re-creating just a subset of them, which makes even less sense to me.

**Comment by netcarver** [comment]
@Toutouwai Robin, I'm tempted to close this and leave #703 active to track the conversation. Ok with you?

**Comment by Toutouwai** [comment]
@netcarver, sure - I'll add a note to the other issue so the connection to this issue is clearer.
