### ISSUE TITLE
If you make the browser narrow, you can't click the Save/Publish buttons at the top-right in uikit

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#706]
As you can see in the screenshot below, the browser is wide enough to make edits (think split-screen editing) but the title element is blocking the save button

<img width="680" alt="capture9" src="https://user-images.githubusercontent.com/190857/45744542-b9e5e380-bbf6-11e8-8efd-36982d255bed.PNG">

**Comment by ryancramerdesign** [comment]
By "blocking" you mean that the Save button can no longer be used/clicked? I can't seem to duplicate this one here. Reducing my browser window to a similar width, the Save button remains usable and clickable  as always. Now I can see the same block-level highlight for the h1 in my dev tools, but the button is right floated and the h1 block is highlighting normally as a block-level element (like in your screenshot). Let me know if I'm misunderstanding? Thanks.

**Comment by Toutouwai** [comment]
@Notanotherdotcom, do you have AdminOnSteroids installed? I can reproduce the issue with AOS installed but not without.

**Comment by Notanotherdotcom** [comment]
Yes, just tried switching that off and the problem goes away so actually not a bug for Ryan :)
