### ISSUE TITLE
Track changes is off for fieldgroups - deliberate?

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#707]
### Short description of the issue

It seems that track changes is off by default for fieldgroups, but on by default for several other objects that extend Wire.

![2018-09-21_121126](https://user-images.githubusercontent.com/1538852/45853114-80001300-bd97-11e8-8cbe-03531c65eaea.png)

This makes it difficult if, for example, you are hooking `Fieldgroups::saveReady()` and want to know what properties of the about-to-be-saved fieldgroup have changed.

Not sure if this is deliberate and not a bug - apologies if so. I just thought that if track changes is on for templates then it would also be on for fieldgroups. If you do want to track changes to fieldgroups in something like `Fieldgroups::saveReady()` how would that be achieved? What would be the right method to hook to turn track changes on for all fieldgroups so that it will be on when a fieldgroup is saved by an admin process?

Edit: there seems to be an issue with the `Wire::trackChanges()` method too. According to the [docs](https://processwire.com/api/ref/wire/track-changes/) it is supposed to return a boolean when `$getMode` is omitted or false, but as per the screenshot above it looks like it always returns an integer and never a boolean.

And that integer seems to be wrong when `$getMode` is omitted. E.g.

![2018-09-21_145608](https://user-images.githubusercontent.com/1538852/45857771-82219c00-bdae-11e8-80cd-f3b9ecbea14f.png)

### Setup/Environment

* ProcessWire version: 3.0.113

**Comment by ryancramerdesign** [comment]
There is no guaranteed trackChanges state for any objects, as it is something that can be turned on and off at runtime. ProcessWire keeps it off for many objects when it's unlikely to be needed, so that it doesn't consume extra memory. If you need change tracking on for something, you either have to check that it is on before the changes are made, and if it's not, then you'd have to turn it on. 

0 and 1 are bit boolean representations (false and true), and so I tend to use them interchangeably, unless they can have different meanings. But of course the phpdoc should be clear about that, since they literally are different data types in php. I have updated it for that method. Thanks.

**Comment by Toutouwai** [comment]
> 0 and 1 are bit boolean representations (false and true), and so I tend to use them interchangeably, unless they can have different meanings.

But I don't think that is what's happening there currently. If 0 and 1 were representing true and false then shouldn't the value for `$template->trackChanges()` in my screenshot above be 1 for true? (if trackChanges is set to Wire::trackChangesValues then it _is_ tracking changes)

And how about this example where it is returning a higher integer?
![2018-09-26_090201](https://user-images.githubusercontent.com/1538852/46042997-ebb4f800-c16a-11e8-82d1-f28e2a8d60e5.png)

> If you need change tracking on for something, you either have to check that it is on before the changes are made, and if it's not, then you'd have to turn it on.

That's all good if you are writing the code that makes the changes, but what if you are hooking an event that happens because of core code or code in someone else's module? In my case, I was hooking before fieldgroups are saved and wanted to know if the fieldgroup name had been changed (as a result of renaming a template via ProcessTemplate, or I guess potentially some third-party module). In such a situation is there a way to turn track changes on in a targeted way or would the only way to be to turn track changes on for fieldgroups every time ProcessWire is initialised, in /site/ready.php or /site/init.php?

**Comment by ryancramerdesign** [comment]
For Fieldgroups you'd probably want to do it at ready state. You could do that from an autoload module's ready() method, or from /site/ready.php:
~~~~
foreach($fieldgroups as $fieldgroup) {
  $fieldgroup->resetTrackChanges(true);
}
~~~~
I'm guessing not, but it's possible that doing this will cause PW to detect changes to fieldgroups when it shouldn't (like when editing a template settings), so if that's the case you may need to only apply the above when the context is the one you are targeting.

**Comment by Toutouwai** [comment]
Thanks for the advice.

Will close this as the question of track changes being off for fieldgroups has been answered, although as per my previous comment I'm not sure that trackChanges() is correctly returning a boolean value (including in 0/1 format) when it is used without the `$getMode` argument.
