### ISSUE TITLE
3.0.114: API variable 'procache' is locked and may not be set again

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#708]
### Short description of the issue

After upgrade to PW 3.0.114, there is an error shown after every Modules > Refresh:

> Failed to construct module: \ProCache - API variable 'procache' is locked and may not be set again

Reproducible on a clean PW installation with ProCache as the only installed module. 

### Setup/Environment

* ProcessWire version: 3.0.114

**Comment by tbba** [comment]
I see this too ... but it seems to go away after revisiting the login page?

**Comment by franctic-aerobic** [comment]
I also see this error. And tried what @tbba wrote: Log out and log in. But I still get the error afterward when clicking Modules > Refresh.

**Comment by tbba** [comment]
Yes, and using the "Updates Checker" module page also continues showing it.
