### ISSUE TITLE
Save button does not work when editing template in a popup

### ISSUE THREAD

**Issue by Luoti** [processwire/processwire-issues#71]
### Short description of the issue

**Setup**
I have two templates: "master" and "children". I want to allow children templates to be added under the master template.

1. I open the master template and open Family tab.
2. I add children to the "Allowed template(s) for children" (see screenshot 1)
3. I click the newly added children template to edit children template in the popup.
4. I select the Family tab and set master for the "Allowed template(s) for parents" (see screenshot 2)
5. If I just click "save" the children template is not saved. If I go to the Basics tab in the popup and press enter on the title field the template will be saved.

### Expected behavior

I expect the save button to save the template without submitting the form in the popup with enter key.

### Actual behavior

Save button does not save the template.

### Optional: Screenshots/Links that demonstrate the issue

**Screenshot 1**
![1](https://cloud.githubusercontent.com/assets/1344148/19928921/798ee7a0-a109-11e6-8df4-ed91249c1ea1.png)

**Screenshot 2**
![2](https://cloud.githubusercontent.com/assets/1344148/19928929/7eb2cf26-a109-11e6-8581-de1e3ad712ea.png)

### Steps to reproduce the issue

1. Create two templates named master and children.
1. Open the master template and open the Family tab.
2. Add children to the "Allowed template(s) for children" (see screenshot 1)
3. Click the newly added children template to edit children template in the popup.
4. Select the Family tab and set master for the "Allowed template(s) for parents" (see screenshot 2)
5. Click "save".
6. Click the children template again to open the popup and select the Family tab. See if master is set as "Allowed template(s) for parents"

### Setup/Environment
* ProcessWire version: 3.0.36
* PHP version: 5.6
* No 3rd party modules

**Comment by ryancramerdesign** [comment]
What browser and platform are you seeing this in? I'm using Chrome 54.0.2840.71 in OS X, and so far I can't duplicate it. But I do observe the modal window having the wrong top offset after adding the "children" template and then clicking it. It doesn't happen when clicking one that wasn't just selected. So it's clear there's something there, perhaps manifesting differently depending on the browser. Since I think the issue you are seeing there is very likely related, I'm curious to know if the latest commit also corrects the issue you are seeing? Thanks.

**Comment by Luoti** [comment]
I am using Fedora 24 with Google Chrome 54.0.2840.71 (64-bit). I also tested this problem with Windows 10 machine and cannot reproduce this, so this might be some weird linux glitch that gets resolved with future updates.

I have narrowed the actual problem down more. When I have the popup open (my initial post step 4), and I select the master template to be allowed as parent and then the next thing I click is the "Save" button the template is not saved. If after selecting the master template, I click anywhere in the popup unfocusing the dropdown element and then click the save button, the template actually **is** saved.

I see no errors in the console. When template is not saved the "...setup/template/save?modal=1" POST request is not fired. The modal just closes.

I also tested it with the newest dev branch but it does not fix this problem.

Now that I know that the only thing it takes is to click somewhere in the popup to "fix" it, its not a problem to me at all. More so that this is not reproducible with Windows machine you may close this issue IMO.

**Comment by ryancramerdesign** [comment]
Thanks for the further testing. If there's been no click in the modal window, then presumably nothing could have been changed either, so sounds like it's probably inconsequential that clicking "Save" doesn't actually save it? (since there could be no changes to save?) Or have I misunderstood?

**Comment by Luoti** [comment]
Sorry for not being clear. I created two screencasts to show the problem better. 

**Here the save does not happen when I click the save button right after I have selected the master.**

![problem](https://cloud.githubusercontent.com/assets/1344148/19963774/9e32bc36-a1c6-11e6-9c4c-462a22af0d5a.gif)

**Here after selecting the master I click the the text paragraph above and then I click save and the save works.**

![noproblem](https://cloud.githubusercontent.com/assets/1344148/19963806/c8063a10-a1c6-11e6-8b7c-97c0a0613811.gif)

**Comment by ryancramerdesign** [comment]
Thanks for the additional info. That's definitely strange that clicking on the paragraph of text changes the behavior, while clicking to change a field does not. I have no idea what that could be, but since it appears to be platform specific there's a good chance we're seeing a bug outside of PW here. I'm not sure if there's anything we can do about that, so lets keep this one open a little while longer to see if anyone else can duplicate. I've added a "help wanted" tag so hopefully someone else can try to duplicate.

**Comment by netcarver** [comment]
@Luoti This is a very old issue now, can you confirm if it is still relevant to newer versions of PW? If not, I'm minded to ask for this issue to be closed.

**Comment by Luoti** [comment]
@netcarver It actually is still relevant and I have changed my Linux distribution couple of times after the initial report, so the problem could not have been my messed up install.

But it seems that this does not affect anyone else, and I have learned to live with it, so yes this can be closed.
