### ISSUE TITLE
Pageimages::add() fails to add Pageimage object from another page

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#710]
### Short description of the issue

An attempt to add a Pageimage object from another page to an Images field fails when using `Pageimages::add()`.

Page with source image:
![2018-09-25_114033](https://user-images.githubusercontent.com/1538852/45985148-f9aa4080-c0b8-11e8-9b4f-93e9390a9ba0.png)

Screenshot showing failure of image add, with the code that was used to try and add the image:
![2018-09-25_114629](https://user-images.githubusercontent.com/1538852/45985253-86ed9500-c0b9-11e8-90d6-0fe84fdcc9f0.png)

### Setup/Environment

* ProcessWire version: 3.0.114
* Running locally on Windows 10

**Comment by Toutouwai** [comment]
The below works though, so it's something specific to trying to add a Pageimage object.

![2018-09-25_115827](https://user-images.githubusercontent.com/1538852/45985442-62de8380-c0ba-11e8-8ae9-e185bbdac479.png)

**Comment by ryancramerdesign** [comment]
That capability was not intended, as a Pagefile/Pageimage is bound to a Page ahead of time as part of its constructor. So you can't take a Pagefile from one Page and then add it to another. Though maybe it should have been checking for that scenario, and perhaps thrown an Exception if it occurred. However, I agree it would be nice to be able to just add it in the way you indicated. It was possible with just a little bit of code—I have gone ahead and added it. Thanks.

**Comment by Toutouwai** [comment]
> So you can't take a Pagefile from one Page and then add it to another.

I see. That wasn't clear from the Pageimages::add() docs where it says that a Pageimage is a valid argument.

> However, I agree it would be nice to be able to just add it in the way you indicated. It was possible with just a little bit of code—I have gone ahead and added it.

Thanks for adding that.
