### ISSUE TITLE
Session history grows indefinitely if $config->sessionHistory = 1

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#712]
### Short description of the issue

If $config->sessionHistory = 1 then the session history is not correctly limited to a single item. Instead the history keeps growing indefinitely.

### Optional: Suggestion for a possible fix

At [line 1202 of Session.php](https://github.com/processwire/processwire/blob/e5900e7567215dfc4989e289bec8a3bd7ba481cb/wire/core/Session.php#L1202):

```php
if($cnt >= $historyCnt) $history = $historyCnt > 1 ? array_slice($history, -1 * ($historyCnt-1), null, true) : array();
```

### Setup/Environment

* ProcessWire version: 3.0.114

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I can duplicate that as well, and your suggested fix resolves it here too—thanks.

**Comment by Toutouwai** [comment]
Thanks.
