### ISSUE TITLE
Multi-language page titles but single-language page names issue

### ISSUE THREAD

**Issue by Notanotherdotcom** [processwire/processwire-issues#714]
### Short description of the issue
If you have a multi-lang site and enter English and German page titles but leave the German page name blank for example, when you click save the German page name is populated from the English title, not the German one.

**This only happens in specific circumstances (see steps to reproduce).**

### Expected behavior

Would expect the code that auto-creates the page names to check for the relevant title language and create page name in the correct language

### Actual behavior

See short description

### Steps to reproduce the issue

1. Create new page on multi-lang site with multi-lang page title
2. Enter page titles in both languages
3. DO NOT modify page names in either language at this stage
4. Click Save
5. This has worked fine, but now delete the page name from the second language on the settings tab and re-save the page - it then creates a page name from the wrong language!

**This also crops up when you have a template that automatically generates page names and the pages start off "untitled" as it skips the initial screen where you enter the title and it generates the correct page names.**

The reason for sometimes deleting and re-generating the page-name by the way is it's quicker if you've changed the page title. In my scenario it was in a multi-lang FAQ and the question was completely re-phrased, so typing-a-new-page-name-in-another-language was slower than deleting it and clicking save :)

### Setup/Environment

* ProcessWire version: 3.0.112

**Comment by ryancramerdesign** [comment]
ProcessWire only populates those page names from page titles when you are creating the page. After the page is created, it leaves the page names alone. This is so that the URL to a page does not change again at some later point (avoiding 404s), unless you specifically intend it by changing the name yourself.  It may appear that it's populating the default language into an otherwise blank name field, but actually it's just showing you this: languages with a blank page name inherit from the default language, just like any other multi-language field. Technically the page names for those languages are still blank behind the scenes in the database. You can observe this by changing the default language page name, and all the others that aren't unique for a language will inherit the change as well.

**Comment by adrianbj** [comment]
@Notanotherdotcom - if you're interested I could enhance PageRenameOptions to automatically re-generate alternate language names from titles if the name is blank. Let me know if that would be helpful. It seems like a nice addition to that module to me.

**Comment by Notanotherdotcom** [comment]
@ryancramerdesign - that makes perfect sense of course now you've explained it as there are occasionally times where a page name/title is the same in both languages (or the title is different but the sanitised page name is the same).

@adrianbj - yes please - that would be ideal!

**Comment by adrianbj** [comment]
Hey @Notanotherdotcom - curious on your thoughts about how to best handles this in the PageRenameOptions module. I remembered something related to this before and checked back through my commits. You'll see my comments here: https://github.com/adrianbj/PageRenameOptions/commit/d64f93e2a7ff557e51528bfad4b177fcc702271b

Also, have a read from here onwards: https://processwire.com/talk/topic/7724-page-rename-options/?do=findComment&comment=144060

What do you think about this issue? 

It seems that removing a ML name is a valid approach to resetting it to show the default language's name. Do you think it would be sufficient to make this optional behavior, or do you have an idea for a different approach that I can implement?

**Comment by netcarver** [comment]
@adrianbj @Notanotherdotcom Adrian, Pete, looks like you may have taken this issue offline and that it can be closed now - is that correct?

**Comment by adrianbj** [comment]
I never heard back from @Notanotherdotcom so I haven't proceeded with anything, but it seems like this isn't something that is going to be addressed in the core so if Pete wants an addition to the Page Rename Options module, he can contact me elsewhere so I think this can be closed.

**Comment by netcarver** [comment]
@adrianbj Thanks Adrian. Closing this.
