### ISSUE TITLE
Pageimage::size() can create image of wrong aspect ratio with certain image sizer options

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#715]
### Short description of the issue

This is a very similar issue to [this fixed maxSize() issue](https://github.com/processwire/processwire-issues/issues/709).

In the screenshots below the source image is 450x600.

```php
<img src="<?= $page->images->first->size(800, 700, ['cropping' => false, 'upscaling' => false])->url ?>" alt="">
```

Result:
![2018-09-24_151725](https://user-images.githubusercontent.com/1538852/45936827-01150f80-c00f-11e8-826e-3301aa722cfc.png)

Should be:
![2018-09-24_152032](https://user-images.githubusercontent.com/1538852/45936834-11c58580-c00f-11e8-91c5-7de8182d72dc.png)

### Setup/Environment

* ProcessWire version: 3.0.115

**Comment by phlppschrr** [comment]
This affects many of my projects, too. I am afraid of upgrading any of these to PW 3.0.115. Maybe the new cropping behavior should only be used for new installs (using `$config->installed`), as it was a breaking change?

**Comment by Toutouwai** [comment]
@ryancramerdesign, based on the comment in this week's blog post...

> I've been scouting all over the issue reports this week looking for anything that fits this criteria (dev branch specific), and I've actually not found any issues that do yet

...I guess you missed this one. It is specific to the dev branch.

**Comment by ryancramerdesign** [comment]
I think we need @horst-n for this one. I'm not sure how to make it produce a result like the one mentioned as the expected result above, nor am I sure that the expected result is clear. You are probably right, but at the same time it does seem like an 800x700 requested proportion on a size() call (as opposed to a maxSize call) would seem like you are asking for for an image that's slightly wider than tall, close to square. But then again, cropping is false...  but upscaling is also false, so we have to listen to proportion or cropping, but not both. I don't know what's best here, but I think @horst-n will.

**Comment by horst-n** [comment]
As far as I remember, there was a request from Thomas Aul (?) that we have to respect the requested aspect ratio when calling for a crop variation. If I do not oversee something here, it looks the same to me like with this request, - long discussion and final decission. So this should be handled exactly like the other case.

Maybe I repeat myself here, but if requesting a greater image variation then the original is and do not allow upscaling, is a wrong setup !! or an error by design of the developer. So the system never can deliver a 100% result here. There must be one part more prior before others. 

In the above mentioned request, the majority wanted to have respected the desired crop ratio. For me this is ok too.

Once again, if you want to have perfect results, setup your system accordingly. Means: If you want to request 800 x 700 crops without upscaling, make sure your images have at least 800 x 700 min-size!!

**Comment by horst-n** [comment]
It is always possible to check the requested crop dimensions in a template file if you have not secured a min-size on upload, - and then switch to your individual prefered usage on mismatch. 

I don't think that the core should handle different usecases of / for wrong setups. 

The right result would be to output nothing or to throw an error if you request something impossible. This would be the result with every code. But the sizer gives back a wrong variation to minimize the errors to not break the page output and also to show something in wrong dimensions / sizes then to show nothing.

**Comment by horst-n** [comment]
OH, BIG SORRY for the previous post. Yesterday I misread the initial post completly.
It is exactly like @Toutouwai said in the initial post. With cropping disabled, we get told the desired dimensions / ratio. If upscaling is disabled and the original is smaller then the requested variation, we have to deliver the biggest possible image with the aspect ratio of the original. 

@ryancramerdesign In fact, if someone disables cropping, he tells us that he want to have a variation of the original that contains within the max-sizes of width and height.

It is the same as with a call for max-size. Does a call for max-size already support this correctly, also with smaller originals and disabled upscaling?

**Comment by Toutouwai** [comment]
Using `size()` with cropping set to false was how a max-size image was created in PW before the dedicated `maxSize()` method was introduced. So the expectation is that it works the same as maxSize(), which it did before PW 3.0.113. The "should be" screenshot in the first post is created in PW 3.0.112.

Setting upscaling to false just means that when creating that max-size image you don't want the image enlarged beyond its native size. The scenario where I am using this all the time is in lightbox galleries where you have images of mixed sizes and resolutions. For the enlargement I want an image that fits within some dimensions (so it's not pointlessly larger than the typical screen size), retains its aspect ratio, and doesn't result in an image that is larger than the original.

The `maxSize()` method was affected by this same issue after v3.0.112 (the issue is linked to in the first post) but has now been fixed. Can the same or a similar fix be applied to `size()` with cropping set to false?

**Comment by ryancramerdesign** [comment]
@horst-n @Toutouwai Sounds good, thanks for the replies. Glad that it sounds like the expected result for this size() call is clear. I guess the next question is then how best to achieve it? It sounds like maybe a statement like this below would do it? (consider it pseudocode as I'm writing in the browser and don't know the variable names or what other logic surrounds it at the moment). 
~~~~~
if($currentWidth <= $requestWidth && $currentHeight <= $requestHeight) {
  // original image smaller than requested dimensions
  if(!$options['cropping'] && !$options['upscaling']) {
    // cropping and upscaling disabled: delegate the resize to the maxSize method?
    $resizedImage = $this->maxSize($requestWidth, $requestHeight, $options); 
  }
}
~~~~~

**Comment by horst-n** [comment]
@ryancramerdesign @Toutouwai The solution seems to be one change in the previously introduced calculation for the new target dimensions in the ImageSizerEngine. We have to select the ratio of the source when cropping is disabled, instead of the target ratio for the calculation.
So we only have to change this line https://github.com/processwire/processwire/blob/c1b9349a7c7f1e47b551440d73b5078e5c4ce163/wire/core/ImageSizerEngine.php#L678 to this:

```$ratioTarget = !$this->cropping ? $ratioSource : $targetHeight / $targetWidth;```

Then its working again. Sorry for all the inconveniances.

**Comment by horst-n** [comment]
@ryancramerdesign Ryan, please can you send me a ping that you have read the fix above?

**Comment by ryancramerdesign** [comment]
@horst-n Thanks that's great! I will go ahead and add this now.

**Comment by Toutouwai** [comment]
Thanks @horst-n and @ryancramerdesign - works perfectly now.
