### ISSUE TITLE
AdminThemeUiKit: Layout-Mode "Sidebar left" is showing error-message

### ISSUE THREAD

**Issue by AndreasFaust** [processwire/processwire-issues#717]
An error-message appears occasionally. The error-message appears, disappears and switches from one side to another (if you use layout-mode "sidebar left/right") on navigating through the backend.

ProcessWire: 3.0.114
PHP: 7.2.7
Webserver: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 
MySQL: 5.7.21

<img width="1497" alt="processwire-ui-error" src="https://user-images.githubusercontent.com/15075587/46535984-5b369000-c8ad-11e8-893e-16956e09ceb5.png">

**Comment by ryancramerdesign** [comment]
That error is coming from your database and is not related to the admin theme. Your database server may need a restart, or it may be be overloaded.

**Comment by AndreasFaust** [comment]
You were right. Thank you very much for the quick and profound response!
