### ISSUE TITLE
non-numeric value encountered in FieldtypeFloat

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#718]
### Short description of the issue

I get this error in tracy on every page containing an empty FieldtypeFloat on PHP 7.2.2:

```
PHP Warning: A non-numeric value encountered in ...\wire\modules\Fieldtype\FieldtypeFloat.module:108
```

### Optional: Screenshots/Links that demonstrate the issue

![screenshot](https://i.imgur.com/6Gbw1hS.png)

### Optional: Suggestion for a possible fix

Not sure if that is the best solution, but this fixes it for me:
```
	public static function getPrecision($value) {
		if($value === "") return; // added this line
		$remainder = ceil($value) - $value;
		$precision = strlen(ltrim($remainder, '0., '));
		if(!$precision) $precision = 1; 
		return $precision;
	}
```

### Setup/Environment

* ProcessWire version: 3.0.114
* (Optional) PHP version: 7.2.2

**Comment by ryancramerdesign** [comment]
I'm not seeing the error here, so am thinking it might be PHP version related. But I have just pushed a fix that should correct it there (typecasting to float). Thanks.

**Comment by BernhardBaumrock** [comment]
that was fast! thx, that fixes it :) hope you are fine again after the cat bite! all the best!
