### ISSUE TITLE
Ckeditor extra allowed content

### ISSUE THREAD

**Issue by suntrop** [processwire/processwire-issues#72]
### Short description of the issue

Setting extra allowed content doesn't work. I have set several rules, but the content is always stripped out. I copied the default example: img[alt,!src,width,height]

### Expected behavior

The width/height attributes should be kept after closing the source code dialog. On an older PW version 2.7 I have the exact same settings and it works 

### Actual behavior

The attributes are removed. I tried with another browser (Chrome) and disabled the cache.

### Steps to reproduce the issue

1. Go and edit a textarea/ckeditor field
2. Go to the Input tab and look for the CKEditor Settings and Extra Allowed Content
3. Put in "img[alt,!src,width,height]" and save
4. Edit a page's html source code and try to save an image with width="100"

### Setup/Environment

* ProcessWire version: 3.0.36
* (Optional) PHP version: 7
* (Optional) MySQL version: 5.6.27

**Comment by ryancramerdesign** [comment]
Just tried to reproduce this, but not seeing the issue here. The attributes were retained. I also tried adding a custom `data-test` attribute, i.e. `img[alt,!src,width,height,data-test]` and CKEditor kept my `<img data-test="test" ...>` as well (though HTMLPurifier stripped that custom attribute after save). HTMLPurifier doesn't strip width or height though. 

Are you using CKEditor regular or inline? 

Do you have the ACF option enabled? (I do)

Any other significant changes in your CKEditor configuration? (i.e. adding plugins, disabling plugins, external config or styles files, etc.?)

**Comment by suntrop** [comment]
That's strange :-) 
I am trying this for the last couple hours with no luck. I am using CKEditor in regular mode, with ACF enabled. I didn't saved the page, because it is stripped out the time I close the source dialog. What exactly did you put into the settings field, that worked for you?

**Comment by ryancramerdesign** [comment]
For the allowed extra content I tried both of these:
~~~~
img[alt,!src,width,height]
img[alt,!src,width,height,data-test]
~~~~
Check your JS console to see if some JS error is present. Any other 3rd party modules installed?

**Comment by suntrop** [comment]
It works mostly …
`<p><img src="test" width="100" data-test="test" class="test" id="test" alt="test" title="test" /></p>`
with these settings
`img[alt,!src,width,height,data-test,class,id,title]`
produces this
`<p><img alt="test" data-test="test" id="test" src="test" title="test" width="100" /></p>`
… the class is missing. Since I need the class attr particularly I focused on this one.

There are no JS errors in console. But I installed the CMS (first time) with an Auto-Installer. And it doesn't matter if I test with an _img_ or a _p_

**Comment by Toutouwai** [comment]
> img[alt,!src,width,height,data-test,class,id,title]

Allowed classes are defined separately. For example:
```
img(my-class)
img(*)
```

The [CKEditor documentation page](http://docs.ckeditor.com/#!/guide/dev_allowed_content_rules-section-2) that is linked to from the field settings explain this.

**Comment by ryancramerdesign** [comment]
That's correct what @Toutouwai said. CKEditor wants to know what classes you want to allow rather than just allowing a class attribute. As far as I can tell everything is working correctly here, so I'll close this, but please let me know if you find anything still not working. Thanks.
