### ISSUE TITLE
AdminThemeUikit layout-mode "PageTree in sidebar": PageTree doesn't update on page-add

### ISSUE THREAD

**Issue by AndreasFaust** [processwire/processwire-issues#721]
### Short description of the issue

At AdminThemeUikit, in layout-mode "PageTree navigation in sidebar", the PageTree does not update, when you add a page by clicking "new" at an existing page in the Tree and publish the new child-page via the other iFrame "#pw-admin-main".

### Expected behavior

When a page is added, it should appear in the PageTree immediately.

### Actual behavior

The PageTree stays as it was, until you close and reopen it or reload the admin-page completely.

### Setup/Environment

ProcessWire: 3.0.116
PHP: 7.2.7
Webserver: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 
MySQL: 5.7.21

allow_url_fopen: 1
max_execution_time: 30 (changeable)
max_input_nesting_level: 64
max_input_time: 60
max_input_vars: 1000
memory_limit: 128M
post_max_size: 8M
upload_max_filesize: 32M
xdebug: 
xdebug.max_nesting_level: 

mod_rewrite: 1
mod_security: *confirmed off

GD: bundled (2.1.0 compatible)
GIF: 1
JPG: 1
PNG: 1

EXIF Support: 1
FreeType: 1
Imagick Extension: 1

FieldtypeColorPicker: 2.0.3
FieldtypeRepeaterMatrix: 0.0.4
FieldtypeTable: 0.1.7
FieldtypeTime: 0.0.1
ImageScaling: 1.0.0
InputfieldColorPicker: 2.0.3
InputfieldRepeaterMatrix: 0.0.4
InputfieldTable: 0.1.7
InputfieldTime: 0.2.0
PageTreeAddNewChildsReverse: 1.0.2
ProCache: 3.1.7
ProcessProCache: 3.1.7
ProcessWireUpgrade: 0.0.7
ProcessWireUpgradeCheck: 0.0.7
TracyDebugger: 4.10.24

**Comment by ryancramerdesign** [comment]
I don't know of a way to have that updated automatically. I had tried at one point, but couldn't get it to work despite my best efforts. However, the left/right page tree layouts were considered experimental and will eventually be removed since the functionality was moved directly into the dropdown navigation (Pages > Tree).

**Comment by AndreasFaust** [comment]
Oh no, but thank you a lot for trying! For me, and I hope I'm not the only one, the version with the PageTree as permanent sidebar is the best layout option, because it provides a good overview and enables you to click yourself from page to page without going back or opening the dropdown navigation, repeatedly traversing the tree. Although it is a bit buggy, I use it constantly and would pity it a lot, if it would be removed. Maybe there will be a solution for these minor issues in the future.

**Comment by adrianbj** [comment]
@AndreasFaust - I had high hopes for the permanent sidebar but found it never really worked well enough. I now make use of the tree icon in the breadcrumb to open the tree in a panel overlay, but my most common navigation tool is @Toutouwai's awesome Breadcrumb Dropdowns (http://modules.processwire.com/modules/breadcrumb-dropdowns/)

**Comment by adrianbj** [comment]
@AndreasFaust - PS - don't forget in future to use the "Copy for Github" option when grabbing your site details from Tracy :)

**Comment by AndreasFaust** [comment]
Thank you for the hint!
For me the sidebar navigation works well enough, to favor it over the other possibilities. The striking argument is the concurrency, the permanent overview on everything a common editor needs: on the left the PageTree, on the right the content. It could not be clearer.

**Comment by Toutouwai** [comment]
@AndreasFaust, here is something to try...

In /site/ready.php:

```php
$wire->addHookAfter('AdminTheme::getExtraMarkup', function(HookEvent $event) {
    $parts = $event->return;
    // Add link to custom script
    $parts['head'] .= '<script src="/site/templates/admin-assets/uikit-panes.js"></script>';
    $event->return = $parts;
});
```

In /site/templates/admin-assets/uikit-panes.js:

```js
$(function() {
    // Get the current URL components
    var pathname = window.location.pathname;
    var search = window.location.search;
    // If this is Page Edit and it's a newly added page being edited...
    if(pathname.indexOf('/page/edit/') !== -1 && search.indexOf('new=1') !== -1) {
        // ...then reload the sidebar tree
        $('#pw-admin-tree', parent.document)[0].contentWindow.location.reload(true);
    }
});
```

![reload-tree](https://user-images.githubusercontent.com/1538852/52665654-f84ab900-2f70-11e9-85e4-22a00c927bc2.gif)

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by netcarver** [comment]
@Toutouwai Looks good. Is this something that could be considered for the theme itself, or just for @AndreasFaust's issue? If it's a specific fix, I'd like to close this issue next week - otherwise, we can bump for Ryan's consideration.

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by Toutouwai** [comment]
@netcarver, it's something that should work generally for anyone who wants the sidebar tree to update when a new page is added, but it's a bit hacky so not sure if Ryan would want to include it in the theme.

**Comment by AndreasFaust** [comment]
@Toutouwai Thank you very much for this workaround! 

I needed `wire("config")` to find the correct path to the templates-folder locally:
```
$wire->addHookAfter('AdminTheme::getExtraMarkup', function(HookEvent $event) {
    $config = wire("config");
    $templates = $config->urls->templates;
    $parts = $event->return;
    // Add link to custom script
    $parts['head'] .= "<script src='{$templates}/admin-assets/uikit-panes.js'></script>";
    $event->return = $parts;
});
```
But this is maybe just a problem with my setup.

Another detail: If you create a page, delete it and then create another one, the PageTree confusingly gets reloaded with the old state. 

But anyway: I am very glad, that you found a solution and I hope it will find its way into the theme.

**Comment by Toutouwai** [comment]
> Another detail: If you create a page, delete it and then create another one, the PageTree confusingly gets reloaded with the old state.

That isn't a consequence of my script, and is actually due to the tree pane _not_ being reloaded. 

It's more reason for the thinking that the approach of having the tree pane and main pane as iframes is not really workable because of all the actions that may occur in the main pane that affect the page tree. The tree pane needs to get updated (reloaded) on any such action.

I can see the value in having the tree pane option in the theme, but I think it would be better not to use iframes but to actually render the tree pane in the same page as the rest of the admin, so it loads afresh with every admin page. People could then decide if the extra page load time (which isn't much) is a price they are willing to pay to have the tree pane.

@AndreasFaust, if you want to try reloading the tree pane on every page load you can change the JS to the following (and clear your browser cache):

```js
$(function() {
    // Reload tree pane on every page
    $('#pw-admin-tree', parent.document)[0].contentWindow.location.reload(true);
});
```

**Comment by AndreasFaust** [comment]
Thank you once again — I very much appreciate your help!
Your concept sounds like a good way to go: No more iFrames, just a normal sidebar. By the way, I always asked myself: Do you think, it is technically possible for ProcessWire to have a UI, that works like a single-page-application: that mutates the database without hard page-reloads?

**Comment by netcarver** [comment]
@AndreasFaust Thanks for raising this issue. I'm going to close this now, but please feel free to open a request for a single-page-app UI for PW in the [requests repository](https://github.com/processwire/processwire-requests).
