### ISSUE TITLE
Processwire Does set $rootPath correctly with Composer if There is no Processwire dir in Root.

### ISSUE THREAD

**Issue by clsource** [processwire/processwire-issues#722]
### Short description of the issue

When using ProcessWire alongside Laravel or other projects that does not have the same project structure. Processwire will not find the correct `$rootPath`.

Error

```
"ProcessWire\ProcessWire::buildConfig(): Failed opening required '/var/www/html/public/wire/config.php' (include_path='.:/usr/local/lib/php')"
```

### Expected behavior
If `$rootPath` is not found in any of the expected paths. Look inside `__DIR__ . /../../`. So custom Processwire installations could have different configurations.

### Actual behavior

ProcessWire will set `$rootPath` where the first `index.php` is found. And this path could differ from standard ProcessWire structure.

### Optional: Screenshots/Links that demonstrate the issue

![](https://user-images.githubusercontent.com/292738/46768514-d1c4fa80-ccbe-11e8-998b-4d94eec6888f.png)

### Optional: Suggestion for a possible fix

line 751 of `wire/core/ProcessWire.php`

```php

/**
	 * Get root path, check it, and optionally auto-detect it if not provided
	 * 
	 * @param bool|string $rootPath Root path if already known, in which case we’ll just modify as needed
	 * @return string
	 * 
	 */
	protected static function getRootPath($rootPath = '') {

		if(empty($rootPath) && !empty($_SERVER['SCRIPT_FILENAME'])) {
			// first try to determine from the script filename
			$parts = explode(DIRECTORY_SEPARATOR, $_SERVER['SCRIPT_FILENAME']);
			array_pop($parts); // most likely: index.php
			$rootPath = implode('/', $parts) . '/';
			if(!file_exists($rootPath . 'wire/core/ProcessWire.php')) $rootPath = '';
		}
		
		if(empty($rootPath)) {
			// if unable to determine from script filename, attempt to determine from current file
			$parts = explode(DIRECTORY_SEPARATOR, __FILE__);
			$parts = array_slice($parts, 0, -3); // removes "ProcessWire.php", "core" and "wire"
			$rootPath = implode('/', $parts) . '/';
		}

                // One last check if the rootPath does not follow ProcessWire structure
               // This will assume this is a custom ProcessWire installation.
		if(!file_exists($rootPath . 'wire/core/ProcessWire.php'))
		{
			$rootPath = __DIR__ . '/../../';
		}

                if(strpos($rootPath, '..') !== false) {
			$rootPath = realpath($rootPath);
		}

		if(DIRECTORY_SEPARATOR != '/') {
			$rootPath = str_replace(DIRECTORY_SEPARATOR, '/', $rootPath);
		}

		return $rootPath; 
	}
```

#### 1 - Create two directories: `laravel` and `pw`

```
pw/
  -- composer.json
laravel/
  -- composer.json
```
#### 2 - Install PW as Usual

The `pw` directory is an standard processwire installation.
Should be configured as normal.

The `laravel` directory contains a laravel project that will require `pw` directory as a local path.

#### 4 - Configure `laravel/composer.json`

Add a local repository

```json
...
"type": "project",
"repositories" : [
        {
            "type" : "path",
            "url" : "../pw",
            "options": {
                "symlink": false
            }
        }
    ]
```

Install Processwire using composer

`$ composer require processwire/processwire @dev`

#### 5 - Use Processwire Inside Laravel

Edit: `laravel/routes/web.php`

```php
<?php
use ProcessWire\ProcessWire as PW;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $pw = new PW();
    $users = $pw->pages->find('template=user');
    foreach($users as $user)
    {
        echo $user->name . "\n";
    }
});
```

#### 6 - Visit Laravel Root

`http://localhost/public/`

### Setup/Environment

- ProcessWire version : 3.0.116
- PHP version: 7.2
- (Optional) Any 3rd party modules that are installed and could be related to the issue: Laravel

**Comment by ryancramerdesign** [comment]
Thanks for the suggestion, it looks good. The only thing I'm shy about is adding another file_exists check that will get executed on every single request in order to add this capability. So wanted to look closer at how you are instantiating PW. It appears you are using the auto-detect instantiation rather than a custom one, when it looks like your use case might need it to be custom. This is how you would instantiate PW below. Are you able to get it working when instantiating like this?
~~~~~
$config = ProcessWire::buildConfig($specifyRootPathHere);
$pw = new ProcessWire($config); // this
$pw = new ProcessWire($config, '/specify/url/to/root/'); // or this
~~~~~

**Comment by clsource** [comment]
Ok. I tried those codes and it seems working now.

This is the laravel code I tried.

```php
Route::get("/", function () {

    $root = __DIR__ . "/../../pw";
    $config = ProcessWire\ProcessWire::buildConfig($root);
    $pw = new ProcessWire\ProcessWire($config);

    //$pw = new ProcessWire\ProcessWire($config, $root);

    $users = $pw->pages->find("template=user");
    foreach($users as $user)
    {
        echo "User: {$user->name} <br>";
    }

    $admin = $pw->session->forceLogin("admin");
    echo "Admin : {$admin->name}<br>";
});
```

Both ways seems to work fine. I think in this specific scenario you need to specify exactly where your PW files are so it can detect the proper config.

I think this can be closed for now. Thanks 👍
