### ISSUE TITLE
FieldtypeComments : exception when URL has port

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#725]
### Description
When the website has a port included in the URL (ex : http://mysite.com:81), posting a comment fails, due to exception : 
Error: 	Exception: Invalid email address.

The cause lies in FieldtypeComments/CommentNotifications.php , function getFromEmail()
line : 
$fromEmail = $this->_x('processwire', 'email-from-name') . '@' . $this->wire('config')->httpHost;

### Suggestion for a possible fix
replace with : 
$fromEmail = $this->_x('processwire', 'email-from-name') . '@' . strtok($this->wire('config')->httpHost, ":");

### Setup/Environment
ProcessWire version: ProcessWire 3.0.116

**Comment by teppokoivula** [comment]
For the record it'd be awesome if ProcessWire didn't just assume that httpHost is the domain used for sending emails. Sure, this issue can be fixed either way, but still :)

**Comment by ryancramerdesign** [comment]
@er314 Thanks, I've pushed something similar to your suggested fix for this. @teppokoivula This is just the fallback email address for cases where the user doesn't specify one with their field configuration, so it has to use something or another as a fallback and I can't think of something better than the hostname in this case.

**Comment by teppokoivula** [comment]
@ryancramerdesign, just to clarify: my point was that it would be great if ProcessWire had a config setting for defining the default outbound email address. This has been requested a number of times, but as I said, wasn't a strict requirement for this issue.

Assuming that hostname is a good email address is no doubt valid for a lot of sites, but if there was a config setting for this, then we didn't have to assume at all. And just to be extra clear, I'm aware that there's a setting for admin email – that's a different thing, and shouldn't be used here either.
