### ISSUE TITLE
Crop Image issue in Front End Editor and Repeater

### ISSUE THREAD

**Issue by denisurn** [processwire/processwire-issues#736]
Since there was no reply on forums, I assumed that this is not a known issue.
When a repeater image is cropped in front-end editor modal window, the newly cropped image preview is not displayed (unless page is refreshed).

### Expected behavior

When image is cropped in a form and cropped version is saved, both the form and the image field are updated with the new cropped image preview. 

### Actual behavior

Image is not updated and the old image preview stays. Through web developer tools and "network" tab I get a json error 

`{"error":true,"message":"Field 'headline' is not applicable to this page"}`

### Suggestion for a possible fix

It seems to me, that validation compares the actual page fields against repeater fields, which are different in this context. ¤repeater->getPageFor() maybe?

### Steps to reproduce the issue

1. Do a clean install of Processwire 3.0.98.
2. Install PageFrontEdit module.
3. Add repeater field and add an image field inside of it. Assign it to any template (I picked "home")
4. Create a page and add a button to open an edit modal dialog
`echo '<edit field="' . $page->fields->implode(',', 'name') . '" page="' . $page->id . '">';
echo '<a>edit</a>';
echo '</edit>';`
5. Open modal dialog on the front-end and upload an image to repeater. Save changes.
6. Open the dialog again and crop the image. Click "Apply" and "Save and replace". 

NB! The bug does not happen when editing the same page in admin as well as for "image" fields which are not inside a repeater. 

* ProcessWire version: 3.0.98

**Comment by matjazpotocnik** [comment]
@denisurn, many years have passed; is this still an issue?

**Comment by matjazpotocnik** [comment]
If you're using fields inside a repeater, you have to specify the page ID of the repeater:

```
 	 Supported formats (one or more fields, with specific page "123"):
 	   <edit 123.field_name>...</edit>
 	   <edit field='123.field_name'>...</edit>
 	   <edit page='123' field='field_name'>...</edit>
 	   <edit page='123' field='field1,field2,field3'>...</edit>
```
But yes, repeater support is not great, as only parts of the page are replaced, while in repeater you can modify multiple images, even delete them, and those changes are not visible until the page is reloaded. 

EDIT: tested with repeaters and it's working just fine!

**Comment by matjazpotocnik** [comment]
@denisurn, closing, please reopen if needed.
