### ISSUE TITLE
Missing methods/properties in class doc comment

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#739]
Hi Ryan,

I would like to start this issue as a list for missing properties and methods. I mentioned `$page->numParents` [here](https://processwire.com/talk/topic/20200-new-post-rebuilding-processwirecom-part-2/?do=findComment&comment=175070), but there are others, so here is the list so far and I will add as I find more.

| Class | Method | Property   | Fixed
|--------:|---|---|---|
| Page | | numParents | ✓ |
| Template | | icon | ✓|
| Page | | referencing | |

**Comment by adrianbj** [comment]
@ryancramerdesign - this one is probably easier to describe than to put into the above table.

Some properties inherited from Pagefile  are not listed in the docblock for Pageimage, eg. `URL`, `httpUrl` & `HTTPURL`.

I expect there are others also, and perhaps this is not just an issue with Pagefile and PageImage?

**Comment by ryancramerdesign** [comment]
I don't usually duplicate phpdocs on inherited classes, as IDEs already take all inherited class phpdocs into account. For the API reference (ProcessWireAPI module) it might make sense though for the output on the PW website, at least for some methods/properties. I don't like the redundancy that will create, but for Pagefile/Pageimage I think you are right, the benefits would outweigh the drawbacks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I noticed that `$page->referencing` is missing. Might be others that were added at the same time as well.

**Comment by matjazpotocnik** [comment]
@adrianbj looks like this is fixed: https://github.com/processwire/processwire/blob/71a2e38f9eafeb539eda2ea28a70cdc8e1895e03/wire/core/Page.php#L88
