### ISSUE TITLE
PageTable 'reloaded' event not triggered

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#74]
### Short description of the issue

InputfieldPageTable.js tries to trigger a 'reloaded' event for an element that doesn't exist:
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.js#L18
$container is the element with class 'InputfieldPageTableContainer', which has no child elements with class 'Inputfield'.

Then an event handler is attached:
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldPageTable/InputfieldPageTable.js#L173-L175
But this never fires because no reloaded event is triggered for elements with class 'InputfieldPageTable'.

### Optional: Suggestion for a possible fix

Perhaps line 18 should be:
`$container.parents(".InputfieldPageTable").trigger('reloaded', ['InputfieldPageTable']);`

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by ryancramerdesign** [comment]
I'm not sure I fully understand, are you seeing an error somewhere? It is possible for there to be .Inputfield elements within InputfieldPageTableContainer when PageTable delegates the rendering to the Fieldtype's Inputfield::renderValue.

**Comment by Toutouwai** [comment]
Sorry, I misinterpreted the purpose of the reloaded event - I had thought (and hoped) that it was an event for reporting when the PageTable inputfield had been reloaded after an AJAX change. Which would be useful for any module that wants to extend the functionality of PageTable.

I see now that the reloaded trigger is for any inputfield rendered within the table that needs to reinit when the table changes (image and file fields, maybe others). And the reloaded event handler is not related to the above, but is instead for if the PageTable is inside another AJAXed inputfield (a repeater I guess).

Incidentally, it's not easy to work out what is going on in many of the core JS files because they have much fewer comments than the core PHP files.
