### ISSUE TITLE
CKE pwlink: pages without templates shouldn't be selectable

### ISSUE THREAD

**Issue by Klenkes** [processwire/processwire-issues#742]
### Short description of the issue

In a CKE field if creating a link to another page with the PWLink module you are able to select pages that don't have a template file. This is wrong because it would result in a 404.
This affects the "Autocomplete" field and "Select Pages" with the Tree.

### Expected behavior

In the Autocomplete field those pages shouldn't be listed at all, and in the page tree not selectable.

### Optional: Screenshots/Links that demonstrate the issue

See forum post:
https://processwire.com/talk/topic/20256-cke-pwlink-pages-without-templates-shouldnt-be-selectable/

### Optional: Suggestion for a possible fix

Robin S. shows some hooks in the forum post.

### Setup/Environment
PW 3.0.98 but others too.

**Comment by ryancramerdesign** [comment]
I think this would interfere with some people's workflow, including mine. I usually build out the content of a site before developing the template files. If pages not having template files aren't shown then that would be a problem. How about something added to the selectable label like "no template file" or similar so one can more easily tell?

**Comment by szabeszg** [comment]
> How about something added to the selectable label like "no template file" or similar so one can more easily tell?

Good idea, but how about also making it configurable via config.php perhaps? I'm thinking of excluding them completely, or making those pages to only show up for superusers.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.
