### ISSUE TITLE
Required fields missing asterisk in Repeater "Fields" section

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#748]
### Short description of the issue

A minor issue. Required fields normally are normally signified by an asterisk next to the field name in Edit Template. When editing a Repeater field, the "Fields" section (which is a kind of equivalent for Edit Template) initially shows the asterisk when a required field is first added...

![2018-11-15_142802](https://user-images.githubusercontent.com/1538852/48523935-34736c80-e8e3-11e8-8aad-a9a866414351.png)

...but the asterisk is no longer shown after the field is saved...

![2018-11-15_142815](https://user-images.githubusercontent.com/1538852/48523953-40f7c500-e8e3-11e8-99a4-68b6fe79ab27.png)

### Setup/Environment

* ProcessWire version: 3.0.118

**Comment by Toutouwai** [comment]
It seems I misinterpreted the meaning of the asterisk - it identifies system fields rather than required fields.

Also, the disappearing asterisk issue affects ProcessTemplate as well as Repeater fields.

It's not a major issue but it would be nice to have consistency between the name of the field in the dropdown and the name of the field in the list of selected options. Looks like a simple fix:

Replacing [this line](https://github.com/processwire/processwire/blob/839d9325cccb44e8bd4931047c8173a7990356e4/wire/modules/Process/ProcessTemplate/ProcessTemplate.module#L977) of `ProcessTemplate::buildEditFormFields`:

```php
$name = $field->name;
if($field->flags & Field::flagSystem) $name .= "*";
$select->addOption($field->id, $name, $attrs);
```

Replacing [this line](https://github.com/processwire/processwire/blob/839d9325cccb44e8bd4931047c8173a7990356e4/wire/modules/Fieldtype/FieldtypeRepeater/config.php#L105) of `FieldtypeRepeaterConfigHelper::getConfigInputfields`:

```php
$name = $f->name;
if($f->flags & Field::flagSystem) $name .= "*";
$select->addOption($f->id, $name, $attrs);
```

**Comment by ryancramerdesign** [comment]
The asterisk just indicates a system field, and that's something that I think is only useful to know at selection time. The asterisk is used in a few spots to indicate system fields during selection. Outside of that case, I think folks might assume the asterisk means something else, like a required field, so better to leave it off.

**Comment by Toutouwai** [comment]
Okay.
