### ISSUE TITLE
asmSelect - class="asmOptionDisabled" overridden by UIkit 

### ISSUE THREAD

**Issue by postscript-chris** [processwire/processwire-issues#749]
Latest dev (3.0.118), change:

/wire/modules/Inputfield/InputfieldAsmSelect/asmselect/jquery.asmselect.css

```
.asmOptionDisabled {
    color: #999;
}
```

To:

```
.asmOptionDisabled {
    color: #999 !important;
}
```

**Comment by ryancramerdesign** [comment]
Makes sense, thanks. I just want to make sure I observe the issue first--where are you seeing it occur? (how do I duplicate?)

**Comment by postscript-chris** [comment]
So I am using an AsmSelect field to select multiple related blog articles. When you select a few, you will see that they are not greyed out as they should be, so it is confusing when selecting any further. Using UIKit admin theme.

**Comment by ryancramerdesign** [comment]
I'm not sure I understand. Can you show a screenshot of what you are talking about? They are greyed out here at least, but it's the OS that controls the appearance of the select dropdown, not the stylesheet. So I'm wondering if this might be related to platform or browser. I'm in Chrome on OS X, which browser/platform are you seeing this in? Thanks.

**Comment by postscript-chris** [comment]
Sorry, screenshot would really help wouldn't it (juggling numerous projects this week).

![untitled-1](https://user-images.githubusercontent.com/25509498/49661729-c7667900-fa41-11e8-843b-e3557485fb8a.png)

That should be what you want. Posters at the bottom of the Categories has already been selected but you will see it still has the same styling as the rest above. You are right, fine on Chrome on OS X, but not on Chrome Windows 10. My fix at the top fixes that.

**Comment by ryancramerdesign** [comment]
Thanks @postscript-chris, I understand now—I've pushed your suggested fix to that css file.

**Comment by postscript-chris** [comment]
Cheers @ryancramerdesign
