### ISSUE TITLE
Custom site profile is not recognized on install

### ISSUE THREAD

**Issue by lesaff** [processwire/processwire-issues#75]
### Short description of the issue
Custom generated site profile is not recognized during installation of new PW instance.

### Expected behavior
custom site profile should be listed in the drop down during installation

### Actual behavior
It's not listed

### Optional: Screenshots/Links that demonstrate the issue

![pw-profile-issue](https://cloud.githubusercontent.com/assets/1151181/20017545/e07d130c-a2a2-11e6-865b-bfaef9d99030.gif)

### Steps to reproduce the issue
1. Generate a custom site profile from your existing PW site
2. Create a new PW site
3. Copy the custom site profile to your new site's root folder

### Setup/Environment
* ProcessWire version: 3.0.39
* (Optional) PHP version: 7.0.12
* (Optional) MySQL version: MariaDb 10.1.18

**Comment by gmclelland** [comment]
Do you have install/info.php file like https://github.com/benbyford/artist-profile/blob/master/install/info.php ? I think that might be required?

**Comment by lesaff** [comment]
Yes. I use the site profile export module to create that profile. I only have the title though.

**Comment by BitPoet** [comment]
Could it be that this is a file/directory permissions issue?

**Comment by ryancramerdesign** [comment]
In order for the installer to consider the profile valid, the following conditions must be met:

- Its directory must start with "site-name" where "name" must be alphanumeric (a-z0-9). 
- Within the directory, there must be at least these directories: 
   - install/
   - templates/
   - assets/
- Within the directory there must also be at least these files: 
   - config.php
   - templates/admin.php
   - install/install.sql
   - install/info.php
- The files must be readable to the web server.

If the profile isn't appearing, then most likely one of the requirements above is missing from the profile.

**Comment by lesaff** [comment]
OK, will check based on your conditions. I'll report back later.

**Comment by lesaff** [comment]
It is working fine on latest PW (3.0.43). I haven't tested on older version. I think it was an isolated issue, possibly permission-related. I am closing this issue. Thanks!

**Comment by manuelborst** [comment]
I had a similar problem with the ProcessExportProfile in PW3. It left the template folder empty when exporting a zip file. It worked fine when exporting to a server folder.
