### ISSUE TITLE
Fatal Error: Deleting a Repeater-Item with FieldsetPage and Image/File

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#754]
### Short description of the issue

If you delete repeater item (Matrix) or a cloned item and this repeater item has a fieldset page with an image or file, a fatal PHP error occurs when deleting the item. This error only happens if an image or file field is located in a fieldset page in the repeater item.

`
Fatal Error: Uncaught Error: Call to a member function emptyAllPaths() on null in /var/www/***/***/wire/core/PagesEditor.php:1043
Stack trace:
#0 /var/www/***/***/wire/core/Pages.php(550): ProcessWire\PagesEditor->delete(Object(ProcessWire\FieldsetPage), true, Array)
#1 /var/www/***/***/wire/core/Wire.php(386): ProcessWire\Pages->___delete(Object(ProcessWire\FieldsetPage), true)
#2 /var/www/***/***/wire/core/WireHooks.php(723): ProcessWire\Wire->_callMethod('___delete', Array)
#3 /var/www/***/***/wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Pages), 'delete', Array)
#4 /var/www/***/***/wire/modules/Fieldtype/FieldtypeRepeater/FieldtypeRepeater.module(508): ProcessWire\Wire->__call('delete', Array)
#5 /var/www/***/ (line 1043 of /var/www/***/***/wire/core/PagesEditor.php) 
`

### Steps to reproduce the issue

1. create a RepeaterMatrix field
2. create a FieldsetPage field
3. add an image field *to the FieldsetPage*
4. add the FieldsetPage to the repeater as an item
5. add the repeater field to a template
6. create a new item in the page and upload an image to the image field
7. save the page
8. delete the item and save the page
9. fatal error happened

![screencast-dev2 kostaldesign com-2018 11 22-11-03-51 2](https://user-images.githubusercontent.com/708183/48896270-7e120900-ee47-11e8-8415-d67cab728670.gif)

### Setup/Environment

* ProcessWire version: 3.0.119
* PHP version: 7.2.12
* RepeaterMatrix: 0.0.4

**Comment by takaras** [comment]
It seems that it is fixed with PW version 3.0.120.

**Comment by netcarver** [comment]
@FlipZoomMedia, David, could you see if this is fixed in 3.0.120 as suggested above and close if so.

Thank you!

**Comment by FlipZoomMedia** [comment]
Yes, thank you. The problem is fixed in 3.0.120.
