### ISSUE TITLE
Datetime field: impossible to select time format 17:10:02

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#758]
### Short description of the issue

One of the time output formats for Datetime fields is "17:10:02". But it's impossible to select this format in the dropdown as it is changed to the "17:10" format after the field is saved.

![time](https://user-images.githubusercontent.com/1538852/49266484-46483880-f4bb-11e8-9213-7aafbd0aa010.gif)

### Setup/Environment

* ProcessWire version: 3.0.119
* (Optional) PHP version: 7.1

**Comment by Toutouwai** [comment]
This issue doesn't have a lot of effect on the actual time output format because the "Time Output Format" field value is not actually saved as part of the field config and it's the "Date/Time Output Format Code" field that has an effect, and this field is updated correctly from the selection in Time Output Format.

But the Date/Time Output Format Code field is shown collapsed so there can be confusion because the visible Time Output Format can show a value that is not actually in effect.

The problem part is [here](https://github.com/processwire/processwire/blob/91fdca02ea47631ed6f029120ac10afec057b078/wire/modules/Fieldtype/FieldtypeDatetime.module#L275-L277), where `strpos() !== false` does not sufficiently discriminate between the "17:10" (H:i) and "17:10:02" (H:i:s) options.

**Comment by Toutouwai** [comment]
Possible fix - not sure if there's something more optimal:

```php
$matches = array();
foreach($wdt->getTimeFormats() as $format) {
    $timeFormatted = $wdt->formatDate($date, $format);  
    $f->addOption($format, $timeFormatted);
    if(strpos($field->get('dateOutputFormat'), $format) !== false) $matches[] = $format;
}
if(!empty($matches)) {
    usort($matches, function($a, $b) {
        return strlen($b) - strlen($a);
    });
    $f->value = reset($matches);
}
```

**Comment by ryancramerdesign** [comment]
Thanks, that's a good find. I've pushed an update to correct it.

**Comment by Toutouwai** [comment]
I like what you did there - I haven't seen that before.
Thanks for the fix.
