### ISSUE TITLE
No thumbnail generation for animated GIFs

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#761]
### Short description of the issue

It's not really a bug, but a problem that unnecessarily consumes computing power and disk space. When uploading images to an ImageField, ProcessWire automatically creates the 260px thumbnail version. But also with animated GIFs. The recalculation of animated GIFs takes some time and the thumbnail can quickly grow to a few MB. As with SVGs, no thumbnail should be created here if it is an animated GIF.

### Setup/Environment
* ProcessWire version: 3.0.120

**Comment by LostKobrakai** [comment]
> As with SVGs, no thumbnail should be created here if it is an animated GIF.

Or at least drop the animation and just use the first frame for the preview.

**Comment by ryancramerdesign** [comment]
ProcessWire shouldn't do that unless you've specifically installed the ImageSizerEngineAnimatedGif module. If that module is installed, it's assumed you want to retain animation from resizes of animated gifs. If not installed, then resizes should just use the first frame.

**Comment by FlipZoomMedia** [comment]
Hi Ryan, I have not installed the ImageSizerEngineAnimatedGif module.

![screenshot-dev2 kostaldesign com-2018 12 07-16-53-31](https://user-images.githubusercontent.com/708183/49657755-b406de00-fa40-11e8-8e21-89c7ac02f81c.png)

**Comment by ryancramerdesign** [comment]
Are you sure it is actually generating an animated thumbnail of the animated GIF? In my case, the thumbnail is non-animated (15k thumbnail on a 5mb source GIF). When I click on it in the admin, it's using the original source file, not a thumbnail. This is also with iMagick image sizer installed. The only thing I can guess is maybe your iMagick version has different defaults than mine and is retaining the animation in the resized GIF?

**Comment by FlipZoomMedia** [comment]
Under the following link, I have recorded a short screencast for you, so that you can see that the animated version is being used and that an animated thumbnail is being created. Here you can also see that the original is only 482 KB and the generated thumbnail is 726 KB.

* [Screencast animated GIF (.mp4)](https://drive.google.com/open?id=1bKylPyyWf9poFuBkHBhVu334ut6JXRXS)

I have also tried it with many different GIFs. Always the same. But for testing, also here the file from my screencast.

* [Test GIF from Screencast (.gif)](https://drive.google.com/open?id=1iElGDDXbnarLDWz2GArEBd0v-Zp82X7W)

The following two modules are installed:
* ImageSizerEngine ImageMagick CLI
* IMagick Image Sizer

And the ImageSizerEngineAnimatedGif module is not installed.

This is my default configuration for Imagick. Maybe this will help you.

![imagick-conf](https://user-images.githubusercontent.com/708183/49685686-fdf6cf00-fae7-11e8-94a2-5f610cb2be29.png)

---

**As I write the answer here, I also tried other combinations and was able to break the phenomenon down to a module. The animated thumbnail is created by the module "ImageSizerEngine ImageMagick CLI".**

That's not part of the core, is it?

**Comment by ryancramerdesign** [comment]
The ImageMagick CLI module is a separate module, not part of the core: https://github.com/horst-n/ImageSizerEngineIMagickCLI

The core comes with an ImageMagick module that is not CLI based, also authored by @horst-n. Since your server seems to have the imagick library in PHP, I don't think that you need the CLI module installed unless it's providing some other feature that the core one does not? It looks like ability to resize animated GIFs is one of the features that could be limited to the CLI version (perhaps a configuration setting with the CLI version).
