### ISSUE TITLE
CKEditor pwimage plugin and external images

### ISSUE THREAD

**Issue by suntrop** [processwire/processwire-issues#762]
### Short description of the issue

External images cause error message when double clicking inside CKE.

### Expected behavior

Have access to (at least) align the image (perhaps scale too).
If you are working with external hosted images (Google static maps, hosted image libraries) it would be nice to give users the ability to align those images as well.
I think working with external images isn't a regular practice, but perhaps it is possible to make this accessible.

### Actual behavior

The pwimage modal opens with error messages "No page specified"

### Steps to reproduce the issue

1. Step 1: open any page with CKE 
2. Step 2: paste this into the source: <img src="//placehold.it/200" />
3. Step 3: exit source dialog and double click the image

### Setup/Environment

* ProcessWire version: 3.0.119
* (Optional) PHP version: 7

**Comment by ryancramerdesign** [comment]
Support for external images was not intended here, though can put it in as a feature request. But if you are manually pasting external img tags into the HTML source, chances are you can align them in the same manner by adding a class of "align_left" or "align_right" to the img tag.

**Comment by suntrop** [comment]
It wasn't meant for me personally. I thought it might be not the best way it is currently.

**Comment by ryancramerdesign** [comment]
I think it does sound like a good feature to add in the future, I've got it
on my list to look into further to see what might be possible.
