### ISSUE TITLE
hide spinner and image preview when image upload fails

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#768]
### Short description of the issue
When I try to upload an image to an image field which has minimum required dimensions, and my selected image does not meet this requirement, an error is shown, but there is an endless spinner and still a preview of the image visible. 
This is very confusing because my customers think the image is still uploading, and they can not cancel the upload.

### Expected behavior
Spinner and image preview should be hidden if the requirements are not met.

![image](https://user-images.githubusercontent.com/551551/50019441-fb5a1500-ffd2-11e8-9f90-273973a96655.png)

### Steps to reproduce the issue

1. Create an image field
2. Under input tab select minimum image dimensions
3. add the field to a template
4. create a new page with this template
5. upload an image which is smaller than the required minimum dimensions

### Setup/Environment

* ProcessWire version: 3.0.118
* AdminThemeUikit

**Comment by matjazpotocnik** [comment]
I added `$spinner.css('display', 'none'); ` in line 1989, before `continue;` in InputfieldImage.js

**Comment by jmartsch** [comment]
@matjazpotocnik That only hides the spinner, but as the image preview is still visible, users could still think, that everything went fine, because: Well because, they often don't read error messages.
So the image preview should also be hidden.

**Comment by matjazpotocnik** [comment]
> Well because, they often don't read error messages

OMG, how could that be ;-) 

I'm not sure I would hide the preview. Maybe add `$spinner.parent().css('border','3px solid red');`

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch @matjazpotocnik I've pushed a fix for this issue.

**Comment by jmartsch** [comment]
@ryancramerdesign Thanks Ryan, will test it asap
