### ISSUE TITLE
Please upgrade to jQuery UI 1.12.1

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-issues#769]
### Short description of the issue

jQuery UI v1.10.4 is outdated and has some nasty behavior when using "resizable" and "draggable" together (in modules).

### Expected behavior

jQuery UI 1.12.1 fixes those issues

**Comment by theo222** [comment]
P.S. jQuery UI 1.11.4 also fixes this problem and is probably better compatible with v1.10.x.

**Comment by ryancramerdesign** [comment]
Hi, we're running somewhat of a custom jQuery UI, so upgrading involves more than just replacing some files. I'm not familiar with the issue you've mentioned -- can you detail the issue you are seeing with resizable and draggable and how to reproduce? I can get a closer look. Thanks.

**Comment by theo222** [comment]
Thank you for your attention.

I guess it has to do with this (bad workaround):
https://bugs.jqueryui.com/ticket/6939

But there were many fixes since 10.4 so an upgrade would be nice anyway.
https://jqueryui.com/changelog/1.11.0/#resizable
https://jqueryui.com/changelog/

**Comment by theo222** [comment]
I found out, that my problem has to do with the code of "resizable" only.
It is enough to download a custom version of 1.11.4 with "resizable" selected only (plus dependencies: core,widget,mouse) see here:
https://jqueryui.com/download/#!version=1.11.4&components=1110001000000000000000000000000000000

If I load this file over/after the version shipped with PW in my module, my problem is solved.
I haven't found any side effects with this, while upgrading all elements of jQuery UI is leading to visible problems.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this.

**Comment by ryancramerdesign** [comment]
At this point in time I don't think we'll upgrade our version of jQuery UI, as our version of jQuery UI is somewhat customized, very stable in our current admin (no significant issues), and historically the jQuery UI updates have been painful, turning up small glitches for months. So I don't want to do that unless some security issue arises with jQuery UI, or it gains some new must-have feature at some point.  I understand you might like to use a newer version of jQuery UI, and I agree and do the same for my own projects outside of developing PW. It's not necessary to use the version of jQuery UI included with the PW core, in fact I don't recommend using it for anything but PW admin.

**Comment by matjazpotocnik** [comment]
Just to add that jQuery is also old: https://processwire.com/talk/topic/17806-old-jquery/

**Comment by tbba** [comment]
What about security? 
https://snyk.io/vuln/npm:jquery

**Comment by netcarver** [comment]
@ryancramerdesign @tbba I think Carl has a valid point. Perhaps this could be re-opened and tagged in order to at least keep it in view.

**Comment by ryancramerdesign** [comment]
@tbba @netcarver Thanks, no need to re-open, I went through each item in that list and none of these are applicable to PW's usage.
