### ISSUE TITLE
Login to Admin without cookies results in not helpful message

### ISSUE THREAD

**Issue by NoNoNo** [processwire/processwire-issues#770]
1. Login to Admin (with cookies disabled)

You’ll be greeted with the error message

`This request was aborted because it appears to be forged.`

Suggestion: Maybe implement a more helpful message for this case.

Greetings!

**Comment by ryancramerdesign** [comment]
@NoNoNo the forged request message can happen for a few different reasons, so it could be lack of cookies, but it could also be due browser cache. All PW knows is that it received something in the request that was not expected (or did not receive something that was expected). I have added a JS-based cookies check to the login form, as well as a noscript error and forced nocache headers, just in case. Hopefully one of these will prevent you from seeing that forged error message.
