### ISSUE TITLE
Importing a field accidentally into the Import Template option should give nicer error message

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#771]
This is not a bug, but more of a suggestion.  I exported a field from a site and wanted to imported it into another site.  I accidentally imported it into the Template Import section as opposed to the Field Import section and rightfully got an exception.

Perhaps the error could be nicer?

**Comment by netcarver** [comment]
@ryancramerdesign Ryan, bumping for your consideration - possibly a simple improvement?

**Comment by ryancramerdesign** [comment]
@netcarver @jlahijani We have to throw an Exception when receiving invalid data like that, just to halt the execution before it goes any further. The admin already captures Exceptions to format them as notifications. The notifications can include debug backtrace if debug mode is on, which might look technical, but that's also intended for debug mode and/or superuser. I think it's best that we continue this output for this type of fatal error.

**Comment by netcarver** [comment]
@ryancramerdesign Ok, understood. I had the impression @jlahijani was only talking about improving the wording of the message - but I could be wrong.

**Comment by netcarver** [comment]
@jlahijani Care to suggest an improved wording?
