### ISSUE TITLE
ProField-PageTable and PageClone: Duplicating a page alters the original page's elements

### ISSUE THREAD

**Issue by iamwebrocker** [processwire/processwire-issues#772]
Hi,

this is after
https://processwire.com/talk/topic/20528-pagetable-elements-page-clonecopy-unpublishes-original-elements
did send me here :-)

### Short description of the issue

Duplicating a page that has PageTable elements on it will alter the published state of the orginal page, when in the PageTable field settings the option to "unpublish when parent is unpublished" is active, and when the elements are stored in a specific parent (not as children of the current page).

### Expected behavior

Original page's elements should not be altered when the page is duplicated.
(Bonus: the duplicated elements should have a " (Copy)" suffixed to their name, as it happens with the duplicated page)

### Actual behavior

Original page's elements get unpublished as soon as the page is duplicated.

### Optional: Screenshots/Links that demonstrate the issue

See the forum post: https://processwire.com/talk/topic/20528-pagetable-elements-page-clonecopy-unpublishes-original-elements

### Steps to reproduce the issue

Create a page containing the PageTable field.

Create some content items with the PageTable field.

Publish the PageTable-elements and publish the page.

Look in page tree at the page that stores the PageTable elements ("contents" in the screenshot). As is to be expected, you see the elements, published.

Now, click on the name of the page with the PageTable field, and choose "copy" from the actions (this only appears when you have installed the PageClone core module).

Now you have a (unpublished) copy of the first page.

Look again in the page tree for the stored PageTable elements: Now you have twice as many elements, and ALL are unpublished. So by duplicating a page, the contents of the original page are altered/unpublished. Since this is unexpected and happens without any indication to the editor, this creates a bad situation esp. for pages where already a mix of published and unpublished PageTable elements  has been before. 

To confirm, edit the original page and see that the PageTable-elements are unpublished.

### Setup/Environment

* ProcessWire version: Happened in production with 3.0.33; tested locally with 3.0.98
* Modules: Standard set of the "blank" site, activated ProFields:PageTable v0.1.3, Page Clone (Core) v1.0.3. ﻿for the local test.

**Comment by ryancramerdesign** [comment]
Thanks @iamwebrocker I have pushed a fix for this.
