### ISSUE TITLE
Broken cleanBasename if "C" string isn't empty on localhost (Windows)

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#773]
### Short description of the issue

If I translate the "C" string on the default language at LanguageSupport.module with a valid or a non-valid locale, cleanBasename will always be broken on localhost (Windows). The problem happens on a clean PW installation too. There is no issue on a live server (Linux).

### Optional: Screenshots/Links that demonstrate the issue

Here are the proper results with empty "C" string:
![untitled-1](https://user-images.githubusercontent.com/23142666/50350985-711d2e00-0549-11e9-8067-59dbbdda8a22.jpg)

Here are the results with translated "C" string:
![untitled-2](https://user-images.githubusercontent.com/23142666/50351082-be010480-0549-11e9-8065-d755ef57f1e1.jpg)

### Setup/Environment

* ProcessWire version: 3.0.122

**Comment by netcarver** [comment]
@ryancramerdesign Would you consider this change on behalf of our Windows clientele?

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I've pushed your suggested fix for this issue.

**Comment by netcarver** [comment]
@matjazpotocnik Could you review Ryan's fix for this issue and close if needed?

**Comment by matjazpotocnik** [comment]
It's fixed here, but I didn't open the issue, hence I can't close it.

**Comment by netcarver** [comment]
Right, @matjazpotocnik I mentioned the wrong person. I will close.
