### ISSUE TITLE
string not translatable in fileupload.js

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#774]
The string "Invalid file extension, please use one of:" ist not translatable because it resides in fileupload.js and is no variable.

Please add a JavaScript variable `invalidFileExtension` or similar which is echoed before the script gets loaded.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping for your consideration.

**Comment by ryancramerdesign** [comment]
@jmartsch @netcarver I can't find a file named fileupload.js in the core — is that from a 3rd party module, or is it a different filename? Please provide the full path if possible. I did however find the string you quoted in **/wire/core/WireUpload.php**. The string is already translatable. If you add that file to your translations and translate it does that appear to solve it?

**Comment by jmartsch** [comment]
Hi @ryancramerdesign to clarify, here is a screenshot of the message for an image field:
![image](https://user-images.githubusercontent.com/551551/54040463-bc98bd00-41c5-11e9-80b7-9a6bad3a2b13.png)
the same goes for file fields.

This occurs here
https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldImage/InputfieldImage.js#L2174
and here https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldFile/InputfieldFile.js#L398

There are more hard-coded text strings, that should be translatable in these files. For example https://github.com/processwire/processwire/blob/master/wire/modules/Inputfield/InputfieldFile/InputfieldFile.js#L403

**Comment by jmartsch** [comment]
@ryancramerdesign This is still a problem. Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch I've pushed a fix for this. The translation strings are now in /wire/modules/Inputfield/InputfieldFile/InputfieldFile.module and they are used by both InputfieldFile and InputfieldImage.

**Comment by jmartsch** [comment]
/remind me to check this again tomorrow evening

**Comment by netcarver** [comment]
Closing this now. @jmartsch Jens - post again if needed.
