### ISSUE TITLE
"Add new" only respects first parent relationship.

### ISSUE THREAD

**Issue by Sebi2020** [processwire/processwire-issues#778]
### Short description of the issue

Add-Page button in `Pages -> Tree -> Add new` only respect first allowed parent template.

### Expected behavior

Imagine you have defined two parents for your basic-page template which you call "home" and "basic-page" you should be able to select every page as a parent for the new page that is either a home or a basic template. Processwire 3 only respect the first allowed parent in the list.

### Actual behavior
Only pages with the first allowed template are selectable.

### Optional: Suggestion for a possible fix

Show all pages which have at least the selected template for the new page in their allowed parent list in the select input field.

### Steps to reproduce the issue

Using the first default site setup of ProcessWire:
1. Go to the home template and allow basic-pages as children
2. Go to the basic-page template and allow home *and* basic-pages as parents. Allow basic-pages as children.
3. Make sure you have pages with home and with basic-page templates.
3. Try to add a new page under `Pages -> Tree`. with the basic-page template. If home is the first template in the list you will only be able to select pages with the home-template. Similarly you will only be able to select pages with the basic-page template if basic-page templates are the first allowed parents for basic--page.

### Setup/Environment

* ProcessWire version: ProcessWire 3.0.123

**Comment by LostKobrakai** [comment]
Duplicate to https://github.com/processwire/processwire-issues/issues/699

**Comment by Sebi2020** [comment]
@LostKobrakai It's not a duplicate because the description in #699 is wrong. It has nothing to do with templates being their own parents.

**Comment by LostKobrakai** [comment]
That's exactly what's mentioned in the comments.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this, and #699, for your consideration, as they are now the bottom of the heap.

**Comment by ryancramerdesign** [comment]
Thanks @Sebi2020 I've pushed a fix for this issue.

**Comment by Sebi2020** [comment]
Yes, I can confirm that the bug no longer exists.
