### ISSUE TITLE
$pages('/') returns a PageArray instead of the home page

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#779]
### Short description of the issue

$pages('/') returns a PageArray instead of the homepage

### Expected behavior

It should return the homepage

### Actual behavior

It returns a PageArray

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/871211/50748323-bdc16400-11ed-11e9-9960-150803b030c8.png)

Note that this is also mentioned in the forums half way through this post: https://processwire.com/talk/topic/20596-new-post-new-pw-website-ready/?do=findComment&comment=178408

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Great - works as expected now- thanks!
