### ISSUE TITLE
PagePathHistory (Core) wrong redirection on copied page with ProcessPageClone

### ISSUE THREAD

**Issue by FlipZoomMedia** [processwire/processwire-issues#78]
When I create a new page using the copy function and then change the path of the parent page, the current page is redirected to the original page from which it was copied.

### Example structure
```
- Parent Page (Path: /test/)
---- Child 1 (New created, Path: /test/p1/)
---- Child 2 (New created over copy function from Child 1, Path: /test/p2/)
```

Now change the path of the parent page, for example to /demo/. And now, call the URL: /test/p1/, it will be redirected to /demo/p1/ (Correct). Now call the URL: /test/p2/, it will be redirected also to /demo/p1/ instead of /demo/p2/.

### Suggestion for a possible fix

When copying a page, a hook must be created in the PagePathHistory module, which does not store the original page ID but the new copied.

### Setup/Environment

* ProcessWire version: 3.0.37
* PHP version: 7.0.12
* MySQL version: 5.5.53-MariaDB
* Module: ProcessPageClone, PagePathHistory

**Comment by ryancramerdesign** [comment]
Thanks @FlipZoomMedia , good find, I've pushed a fix for this issue.
