### ISSUE TITLE
New page isn't saved due to processQuickAdd call

### ISSUE THREAD

**Issue by renpw** [processwire/processwire-issues#781]
### Short description of the issue

Create a new page, enter the title and choose the template, click save. Instead of saving, processQuickAdd creates a _new_ new page with blank title and the usual temporary name ('untitled[xxxx...]').

This happens when the parent template has
1) more than one allowed child template, **and**
2) a value for "Name format for children"

To get to this state, the parent template is initially setup for 'quick add' with one allowed child template and "Name format for children" set to "title". Then later, this is changed to have more than one allowed child template, which causes the problem. Took a while to figure out what was happening because "Name format for children" is dynamically hidden as soon as a second child template is selected. I guess the expected behaviour given the hiding of "Name format for children" would either be for the value to be cleared (it isn't) or ignored (it isn't).

I think the cause is that when the 'Add New' page form is submitted, because a template has been selected, $this->template is set. So both of [the following](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L486-L491) tests pass and the call to processQuickAdd executes...

`		if($this->template && $this->parent) {
			// determine whether quick-add can be used
			if(strlen($this->parent->template->childNameFormat) || $input->get('name_format')) {
				$this->processQuickAdd($this->parent, $this->template);
			}
		}`

### Steps to reproduce the issue

1. Create a template for the parent page and two templates for the children.
2. Create and save a parent page.
3. Edit the parent template, set allowed child templates to one and "Name format for children" to "title". Save.
4. Edit the parent template again, set two allowed child templates. Save.
4. Create a child page. Choose a template and enter the title. Save.

### Setup/Environment

* ProcessWire version: 3.0.123 and 3.0.98

**Comment by ryancramerdesign** [comment]
Thanks @renpw I've pushed a fix for this

**Comment by netcarver** [comment]
@renpw Can this be closed now?

**Comment by netcarver** [comment]
/remind me to review and close if necessary in 1 week

**Comment by renpw** [comment]
Brill, that works a charm. Thank you @ryancramerdesign

**Comment by renpw** [comment]
closed
