### ISSUE TITLE
Translation "0" ist not getting saved in 3.0.123

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#785]
### Short description of the issue

After log in to the backend I get a warning saying that the server locale isn't working as expected and I should translate the "C" locale.

![image](https://user-images.githubusercontent.com/17496592/51025617-d5517180-158c-11e9-9fa0-90b2177f0762.png)

When editing  the locale it says I can fill in "0" to skip setlocale(). However, that value is not getting saved.

### Expected behavior

I expect to save value "0" so setlocale() can be skipped.

### Actual behavior

Nothing is getting saved and the original translation "C"is still being used

### Optional: Screenshots/Links that demonstrate the issue

/processwire/setup/language-translator/edit/?textdomain=wire--modules--languagesupport--languagesupport-module&language_id=1045

![image](https://user-images.githubusercontent.com/17496592/51025392-2dd43f00-158c-11e9-9d31-90aafeec3483.png)

### Steps to reproduce the issue

1. Log in to backend
2. Go to setup > Languages > [Language] > Edit "LanguageSupport.module"
3. Try to enter 0 into the translation for "C"
4. Save, the value will not be saved

### Setup/Environment

* ProcessWire version: 3.0.123
* PHP version:  7.0.27
* MySQL version:  5.7.19
* Relevant modules: LanguageSupport

**Comment by ryancramerdesign** [comment]
Thanks @MrSnoozles I've pushed a fix for this issue

**Comment by netcarver** [comment]
@MrSnoozles Can you review the fix and close if appropriate.

**Comment by matjazpotocnik** [comment]
It's working here, "0" is saved.

**Comment by netcarver** [comment]
/remind me to review and close if necessary in 1 week

**Comment by netcarver** [comment]
Closing. Feel free to leave comments or open new issue if needed.
