### ISSUE TITLE
ProFields Table loads pages unnecessarily if using a Page (Select) column

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#789]
Made a video for this one:
https://youtu.be/4sLGRvTzvOk

I originally discussed this issue in the ListerPro subforum here:
https://processwire.com/talk/topic/18969-high-cpu-super-slow-response/?do=findComment&comment=171059

Now that I identified the cause, I don't think this is necessarily a ListerPro issue more than it is a PW or ProFields Table issue specifically.

**Comment by teppokoivula** [comment]
@jlahijani, if you look at Ryan's latest reply at the support forum thread, it appears that this is indeed a ProFields Table issue (or enhancement), and not a ProcessWire core issue.

As such, you might want to consider closing this issue report and continuing the discussion (if needed) via ProFields support channels :)
