### ISSUE TITLE
Reno Add New button FOUC before padding added

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#79]
### Short description of the issue

When you load the admin page list view in Reno, the Add New button doesn't initially have the correct padding. Once the page is fully loaded, the padding is added.

### Expected behavior

It should load with the correct padding immediately

### Optional: Suggestion for a possible fix

There are a couple of things going on compared with the default theme. Firstly `padding: 0.6em 1.1em;` is missing from the from `.ui-button,button.ui-button.ui-state-default,.ui-button.ui-state-default` definition. Adding that sets the correct padding initially, but then once the page loads, extra padding is applied. The problem is that the text label of the button isn't in a span with the `ui-button-text` class like it is in the default theme. Because of that, this line: 
```
if($a.find('.ui-button-text').length == 0) $a.button();
```
https://github.com/processwire/processwire/blob/36984e4a057268b7a45b848e1b3b6ee757583459/wire/templates-admin/scripts/main.js#L102 

adds the button styling which results in the double padding.

**Comment by netcarver** [comment]
@adrianbj @ryancramerdesign Bumping this as there is a more recent FOUC discussion going on in #794, and this might be related.

**Comment by adrianbj** [comment]
I'm going to close this because I don't think the reno theme is getting much use these days and FOUCs in the PW admin are just a fact of life these days so reporting on doesn't seem to be of much value :)
