### ISSUE TITLE
Inline Editor shown in a textarea field #request

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#791]
### Short description of the issue

I miss an Inline Editor that is shown in a textarea field. This will make presentation of the field consistent with other fields in the editing interface - and make the edit-page appear simpler (currently text is shown in full length, this can make the edit-page appear cluttered).

### Expected behavior

The Inline Editor shall show text in a textarea field (in the editing interface).
When Toolbar buttons are loaded, they appear either inside the textarea field, or right above it.

### Actual behavior

The current Inline Editor shows text in full length (as on a web page) and not in a textarea field.

### Screenshot

Screenshot: Current Inline Editor with a long text, it is not shown in a textarea and the full text is shown when creating and editing the page.

![image](https://user-images.githubusercontent.com/129573/51423700-0e5c9800-1bc4-11e9-8ac5-ffd73c9e22b8.png)

### Optional: Suggestion for a possible fix

Fix the current Inline Editor, or create a third kind of editor for CKEditor Textarea fields that will then have:

1. Regular Editor - Textarea field with toolbar. Has the most features and editor customizations.
2. Inline Editor - Text is shown in full length (not in a Textarea field). Toolbar loads when you click in the text. Looks better when there are many CKEditor fields on the page.
3. Inline Editor textarea - Text is shown in a Textarea field. Toolbar loads when you click in the text. Looks better when there are many CKEditor fields on the page.

### Steps to reproduce the issue

The current Inline Editor shows text in full length (as on a web page) and not in a textarea field.

1. Go to Admin, add new field:
2. Type: Textarea
3. Inputfield Type: CKEditor
4. Save
5. Editor Mode: Inline Editor, Add the field to a template
6. Create a Page that uses the template, note that the text is shown in full length.

* ProcessWire version:  3.0.62

**Comment by Toutouwai** [comment]
Another way of putting this issue might be: CKEditor fields in inline mode should honour the Rows setting defined for the field.

@klor, in the meantime you can limit the height of your inline CKEditor fields according to the Rows setting by adding the following hook to /site/ready.php:

```php
$wire->addHookAfter('InputfieldCKEditor::render', function(HookEvent $event) {
    $inputfield = $event->object;
    if($inputfield->inlineMode !== 1) return;
    $height = $inputfield->rows * 2 . 'em';
    $event->return .= "<style>#{$inputfield->id}_ckeditor { overflow:auto; height:$height; }</style>";
});
```

**Comment by ryancramerdesign** [comment]
@klor I have added this as a configuration option to the CKEditor field settings, using the code from @Toutouwai hook for setting an inline style.
