### ISSUE TITLE
relativeTimeStr corrupts Cyrillic characters

### ISSUE THREAD

**Issue by Lazerproof** [processwire/processwire-issues#792]
### Short description of the issue

preg_replace on[ this](https://github.com/processwire/processwire/blob/dev/wire/core/WireDateTime.php#L606) line in relativeTimeStr corrupts Cyrillic characters.

### Expected behavior

```
echo wireRelativeTimeStr(strtotime("-1 week"), [
		'minute' => 'хвилин',
		'hour' => 'годину',
		'day' => 'день',
		'week' => 'тиждень',
	])
```
should output 
```
1 тиждень ago
```

### Actual behavior

```
1 тижден� ago
```
![wirelogger](https://user-images.githubusercontent.com/5707348/51433156-612e6200-1c4d-11e9-9075-a991d8e72baa.png)

### Optional: Suggestion for a possible fix

Changing
```
preg_replace('/\s\s+/', ' ', $out);
```
 to 
```
preg_replace('/!\s+!/', ' ', $out);
```
solves this issue, but there might be better patterns. 
### Steps to reproduce the issue

Try to echo this code
```
wireRelativeTimeStr(strtotime("-1 week"), [
		'minute' => 'хвилин',
		'hour' => 'годину',
		'day' => 'день',
		'week' => 'тиждень',
	])
```

### Setup/Environment

* ProcessWire version: 3.0.124

**Comment by ryancramerdesign** [comment]
If I run the code the output that I get is: `1 тиждень ago`. The result you mentioned looks like the output character set is something other than UTF-8. Can you check that in your HTML file has this in the `<head>`:
~~~~~
<meta http-equiv="content-type" content="text/html; charset=utf-8">
~~~~~
If that's not it, also check the file that you edited where your wireRelativeTimeStr() call is and make sure that the encoding of the file is also UTF-8.

**Comment by netcarver** [comment]
@Lazerproof Can you update us with your findings? Was this just an encoding problem with the page?

**Comment by Lazerproof** [comment]
@netcarver Yes, sorry for delay, currently I don't have this problem, but I did't change anything on local server and this project. I want to test it a little bit more and will close this issue if I can't reproduce it.

**Comment by netcarver** [comment]
/remind me to review in 1 week
