### ISSUE TITLE
Login/Register Frontend module - Password reset

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#796]
> If you want to support a “forgot password” feature, install the core ProcessForgotPassword module. Once installed, this module will provide the behavior by way of that module. 

I do not see any Password Recovery link underneath the frontend login form.
Or is there a misundertanding of how that works?

PW  | 3.0.124
LoginRegister | 0.0.2
password forgotten  | 1.0.3

**Comment by tbba** [comment]
@ teppokoivula  ok, I move the thread away. (I just don't think it helps -  the other repo appears not to have been monitored in over a year).

**Comment by teppokoivula** [comment]
Thanks, @tbba. I definitely get what you're saying, and I have to agree with you – it does look a bit abandoned at the moment. I'd also like to hear what @ryancramerdesign has planned in regards of long-term support of his non-commercial modules.

Ryan, if you're reading this, could you please provide us some insight on this?

Please note that LoginRegister doesn't have a support forum thread either, which is actually something that @kongondo has offered to set up a couple of times on the forums. If this is fine for you, we'd be happy to help you with managing these things – just give us a thumbs-up :)

Thanks for taking the time to answer!
