### ISSUE TITLE
Broken pattern validation in collapsed repeater items

### ISSUE THREAD

**Issue by PWaddict** [processwire/processwire-issues#799]
### Short description of the issue

Validating pattern in a field that belongs to a collapsed repeater item doesn't work. The following error appears in console:

>  An invalid form control with name='my_url_field_repeater1052' is not focusable.

### Steps to reproduce the issue

1. Create a url field and add a pattern under Input like this: http://www\.facebook\.com\/(.+)|https://www\.facebook\.com\/(.+)
2. Add the url field inside a repeater field and then go to the page where the repeater belongs to and add a new repeater item. Write in the url field for example the word "test" and then collapse the repeater item.
3. Try to save the page. Nothing will happen except that in console will appear the above error.

### Setup/Environment

* ProcessWire version: 3.0.123

**Comment by FlipZoomMedia** [comment]
This is unfortunately not a bug of ProcessWire or repeaters, this is an very old bug in Google Chrome. I found this problem even with some modules and input fields. Unfortunately not only the required causes this bug, but also patterns. There are a lot of discussions about this on the net ([https://stackoverflow.com/a/28340579](https://stackoverflow.com/a/28340579)). My workaround, do without the HTML5 browser validation and validate the rest on the server side.

**Comment by netcarver** [comment]
@PWaddict In the absence of any other information, I'm going to mark this as not-a-bug and come back and close it in a few days unless you or anyone else wants to suggest an alternative fix for this.

**Comment by teppokoivula** [comment]
This might be more of a feature request than a bug, but it's really annoying when this happens. I'm wondering if we could solve at least some cases by temporarily opening collapsed repeater items during save event? Just an idea – not sure if that's actually feasible.

**Comment by netcarver** [comment]
@teppokoivula Hi Teppo, yes - this probably makes more sense over on processwire-requests. Will look at moving it over if @PWaddict is happy with that.

**Comment by PWaddict** [comment]
@netcarver ok move that to requests.

**Comment by netcarver** [comment]
@PWaddict Great. I've requested that @ryancramerdesign all me to use Probot/Move to easily allow issues to be ported between environments. Once we are in a position to easily move this, I will do so.

**Comment by Toutouwai** [comment]
I wonder if the features added in PW 3.0.113 could be expanded to work in this scenario: https://processwire.com/blog/posts/processwire-3.0.113-core-updates/

> This update captures that scenario and automatically changes it to the right tab, and opens any fieldsets and Inputfields as needed till it can reveal the field with the missing requirements.

> This update also adds JS API methods, which were built in part to accomodate the above:

> InputfieldFocus($inputfield) - Show given $inputfield element, regardless of where it is (changing tabs, open fieldsets/fields as needed), and focus.
> InputfieldOpen($inputfield) - Open the given $inputfield element.
> InputfieldClose($inputfield) - Close/collapse the given $inputfield element.

**Comment by netcarver** [comment]
@Toutouwai - I moved this one to the [request repo](https://github.com/processwire/processwire-requests/issues/264) - but forgot to lock this. Could you please post again over there.
