### ISSUE TITLE
Wrong order of a fieldset opening and closing in template makes pages not saving any more

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#8]
> Briefly describe the issue.

Page does not save content, but still sends a green "saved" response, if the template has a wrong order of fieldset and fieldset_END. That was one of my recent mystery bugs only in combination with a certain template. Somehow I must have inadvertently dragged the wrong field and ended with a wrong order.

> What did you expect to happen?

Wrong order of a fieldset opening and closing field is not allowed or there is a warning.
Or a correction like we have it when a missing _END field is added.

> What did actually happen?

I could save the template with my error in it. No warning, no automated fix.
The corresponding page opened as normal on editing but any changes to the content were not saved. The failure was silent, no errors, notices or anything.

> Optional: Have you a suggestion for a possible fix?

I corrected the order of the fieldset after I discovered the issue and now PW behaves normal.
I cannot blame PW for it as it was the result of a mistake from my part but maybe that effect is interesting to know for you.

> Tell us about the setup you experienced the bug in.

* ProcessWire version: 3.034 - live and localhost, on 2 different installs.
* (Optional) PHP version: 7-10

**Comment by isellsoap** [comment]
I can reproduce the issue.

**Comment by tbba** [comment]
Thank you for your feedback :-)

**Comment by ryancramerdesign** [comment]
I've pushed an update so that it shows an error message if you get the order wrong with your fieldset open/close fields.

**Comment by tbba** [comment]
Great! Thank you!
