### ISSUE TITLE
 Blank white login page when  site/templates/admin.php damaged or missing

### ISSUE THREAD

**Issue by PawelGIX** [processwire/processwire-issues#80]
### Short description of the issue

If the file "site / templates / admin.php" is damaged or does not exist, the login page displays a white page, the status of 200, no errors. Find the cause can be difficult.

### Expected behavior

Maybe helpful would be an error message or an entry in the log in this case?

### Actual behavior

Nothing. Blank Page. No errors. http 200 status

### Steps to reproduce the issue
delete  site/templates/admin.php and go to login page

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix.
