### ISSUE TITLE
mcrypt_create_iv() is deprecated

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#806]
### Short description of the issue

When rendering a Form Builder Form output to a file, the line `$session->CSRF->renderInput();` is throwing an error in Bugsnag, saying `Function mcrypt_create_iv() is deprecated`.

[PHP's documentation](http://php.net/manual/en/function.mcrypt-create-iv.php) recommends [`random_bytes()`](http://php.net/manual/en/function.random-bytes.php).

This error seems to originate from `WireRandom.php:825`.

**Comment by adrianbj** [comment]
Just as a cross-reference: https://github.com/processwire/processwire-issues/issues/447

**Comment by netcarver** [comment]
@ethanbeyer I'm going to close this as I think that it is already covered by 447 as Adrian pointed out. Many thanks for the submission though!

**Comment by ethanbeyer** [comment]
Sounds good to me @netcarver ! Thanks for doing repo maintenance! <3
