### ISSUE TITLE
Add new page: template not applied

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#807]
### Short description of the issue

When adding a new page via Pages > Add New the correct template for the page is not selected in some circumstances. 

This happens when the allowed parent template permits more than one child template and there is more than one parent page available to add the new page under. The problem is worse when there is at least one child page already under the chosen parent because in those circumstances the wrong template can be pre-selected in the Template dropdown instead of just available for selection (although neither should occur).

### Expected behavior

The template for the page being added should be automatically applied - no other options should be present in the template dropdown because the desired template is already known.

### Steps to reproduce the issue

1. Create a parent template "staff" that new pages will be added under.
2. Create two pages using the staff template - "Brooklyn office" and "Queens office".
3. Create two templates - "associate" and "partner". For each select "staff" as the allowed parent template and for the staff template select "partner" and "associate" as allowed child templates.
4. Create a new "associate" page under "Brooklyn office".
5. Navigate to Pages > Add New > Partner.
6. Select "Brooklyn office" as the parent page.
7. Note that both "associate" and "partner" are available in the "Template" dropdown but associate should not be available here because the user has already requested to add a partner page. Also note that "associate" is preselected, which is the wrong template.

Screencast:
![template_issue](https://user-images.githubusercontent.com/1538852/52389344-f360b200-2af7-11e9-8424-a2257019f6cb.gif)

### Setup/Environment

* ProcessWire version: 3.0.125

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai that was a great description on how to reproduce it and I've pushed a fix for this.

**Comment by postscript-chris** [comment]
I was experiencing this as well. I will test when I can, but I couldn't have even begun to have explained it as well as @Toutouwai. Such a good community.

**Comment by Toutouwai** [comment]
Thanks for the speedy fix!
