### ISSUE TITLE
Admin login password field covered by virtual keyboard in Chrome on iOS

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#808]
### Short description of the issue

The `.uk-offcanvas` and `.uk-offcanvas-bar` in Uikit make it virtually impossible to login via Chrome on iOS - this seems to be new issue with a recent version of Chrome for iOS.

There is mention of this: https://github.com/uikit/uikit/issues/3738 which seems like it might be related, but I don't think it's quite the same bug.

Note that this bug also affects the LoginRegister module.

**Comment by Toutouwai** [comment]
@adrianbj, are you able to add a screenshot? Not sure what you mean by the `.uk-offcanvas` and `.uk-offcanvas-bar`.

I have the latest Chrome and nearly the latest version of iOS (12.1.2, only a minor version different to the very latest) and can use the admin fields okay with the virtual keyboard showing.

Note that my phone is an iPhone SE, so has a smaller screen than most modern phones where less of the screen would be obscured by the keyboard.

![image-1](https://user-images.githubusercontent.com/1538852/52468464-a6f79e00-2bed-11e9-89a6-1350e3a0ae76.jpg)

**Comment by netcarver** [comment]
@adrianbj Hi Adrian, isn't this going to be a problem on small screen devices - at least to a degree - despite which admin theme is used? I've not tried the UIKit admin theme on a small screen device, so I'm kind of asking in ignorance.

**Comment by adrianbj** [comment]
@Toutouwai - sorry it's just the login screen that's the problem (changed title to reflect this) - the password field can't be scrolled into view. The offcanvas classes are uikit classes for the mobile hamburger menu. If you remove the declarations for those two classes from uikit.css, the problem goes away and the password field is automatically pushed up into view. It's something to do with the fixed position of the offcanvas menu.

@netcarver - it shouldn't be - they typically push the focused field above the keyboard so you can see it - this behaviour can be seen in Robin's screeenshot with typical admin fields.

**Comment by Toutouwai** [comment]
I understand now and can reproduce the issue.

> The offcanvas classes are uikit classes for the mobile hamburger menu. If you remove the declarations for those two classes from uikit.css, the problem goes away and the password field is automatically pushed up into view.

I tried removing the styles from those classes in the CSS and it made no difference - the password field is still partially obscured by the keyboard. I also experience the same issue in Page Edit if I edit a text field at the bottom of the layout.

As far as I can see this isn't a Uikit or PW issue but something that occurs on any web page where an input is at the bottom of the page. There isn't enough available space below the input to scroll the page and get the input into the viewable area. If this is what is causing the issue and we don't want to get into the game of trying to detect when a device keyboard is active then a quick solution would be to just add some extra bottom padding to a container element at mobile widths.

This is working for me and doesn't look too strange:

```css
@media only screen and (max-width:767px) {
    #main { padding-bottom:200px; }
}
```

**Comment by adrianbj** [comment]
The catch with the that is the an ipad sideways still doesn't work. You'd need to use a `max-height` instead.

Take a look at github.com - make sure you're signed out and then enter one of the sign in fields. Even with the keyboard displayed, you can still scroll down. This is what I think we need to achieve.

**Comment by adrianbj** [comment]
Actually, ignore my github comment - you can't actually scroll all the way to the bottom. My mistake.

So perhaps something along the lines of your suggestion is the only way. I feel like this is something that might just need to be fixed in Chrome - I am pretty sure it's a new issue in a relatively recent version and it's certainly not how Safari on iOS works.

Any thoughts?

**Comment by Toutouwai** [comment]
You're right that Safari handles the virtual keyboard differently. Seems like opening the keyboard in Safari causes a viewport resize (and therefore you can scroll elements outside the viewport into view) but in Chrome the keyboard overlays the page without resizing the viewport.

Interestingly I found a recent article that suggests that Safari is the worst offender when it comes to keyboard quirks: https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d

Chrome on my iPad doesn't exhibit this problem and seems to behave the same as Safari. But my iPad is older so things might be different in more recent versions of iOS/Chrome. Although the article linked to above suggests that the iOS Chrome keyboard works differently in iPad vs iPhone even on current iPads.

I checked Chrome on Android and no problems there. So if it's just limited to Chrome iOS then we'd have to decide if the market share is big enough to impose the extra bottom padding on everyone. Or maybe we can sniff out the browser and conditionally add the CSS?

**Comment by adrianbj** [comment]
> Chrome on my iPad doesn't exhibit this problem and seems to behave the same as Safari
Yeah, I think this might be the age - it was behaving fine on mine until I updated to the most recent version of Chrome. Maybe that version isn't available for your iPad's iOS version?

Sorry for the sidetrack on it being related to those oncanvas elements - it was just fixing the symptom on the frontend of my site because the menu was then adding the needed padding because it was no longer hidden.

Perhaps we need to file a bug report with Chrome?

**Comment by netcarver** [comment]
@adrianbj Hi Adrian. Do you think this on could be closed now?

**Comment by adrianbj** [comment]
@netcarver - seems like it's no longer a problem on Chrome iOS so maybe something has been changed in the browser?
