### ISSUE TITLE
children.subfield selector syntax not working

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#809]
### Short description of the issue

https://processwire.com/blog/posts/pw-3.0.25/ states that pages may be matched by a subfield of its children. I assume that this means that if the page has _at least one_ child that matches the selector, the parent page will be selected.

Here is an example of what I'm trying to do:

`$pages->find("template=Boxset, children.donated=");`

In the above case I am looking for all of the Boxsets that have at least one child (Box) that is not donated (donated is a date field).

This is a simplified example that I tested with and failed to get working when my more complex query wouldn't work. The more complex query is looking for Orders that reference Boxsets that have at least one child that is not donated. (boxset.children.donated=)  According to the documentation, this should also work.

I am also having trouble with owner selectors. For example, I am trying to find all Boxset pages that are referenced by an Order page where the Order page has a certain delivery date:

`$pages->find("template=Boxset, boxset.owner.template=Order, boxset.owner.delivery_date=1546837200");`

This also does not not return the expected results.

### Expected behavior

I've been running into these issues on several recent projects while assuming I must be doing something wrong and settling for workarounds. But after testing and still not getting expected results I am wondering if a bug was introduced into the core at some point.

### Actual behavior

Expected results are not returned.

* ProcessWire version: 3.0.104
* (Optional) PHP version: 7
* (Optional) Any 3rd party modules that are installed and could be related to the issue: PagesSum

**Comment by Toutouwai** [comment]
I agree that there is something not working correctly with the `children.field` syntax.

I have the following page structure...

![2019-02-08_203130](https://user-images.githubusercontent.com/1538852/52464729-e5d32700-2be0-11e9-9464-044d826e8af6.png)

...with a Datetime field "test_date" that on page "Green" is set to a date that equates to timestamp 1551265200.

This page is found correctly when I search the test_date field directly in the selector:
![2019-02-08_203232](https://user-images.githubusercontent.com/1538852/52464795-187d1f80-2be1-11e9-9ec8-005f4f25f39f.png)

So you would expect a selector for `children.test_date=1551265200` to find the parent "Colours" page, but strangely it finds the "Green" page again.

![2019-02-08_203305](https://user-images.githubusercontent.com/1538852/52464846-47939100-2be1-11e9-837f-7ccb4cbc9225.png)

**Comment by thetuningspoon** [comment]
Thanks @Toutouwai for the confirmation and for adding that nice clean example.

**Comment by thetuningspoon** [comment]
Upon further investigation this morning, it seems that this issue is limited to examples that use the Datetime field, and it effects both children.datefield and field.owner.datefield selectors. It does not seem to be an issue for parent.datefield or page.datefield.

**Comment by Toutouwai** [comment]
Doesn't seem to be specific to Datetime fields for me. I get the same issue for a text field:
![2019-02-10_101405](https://user-images.githubusercontent.com/1538852/52526390-ba555700-2d1c-11e9-824f-8ba85c8dca81.png)
![2019-02-10_101431](https://user-images.githubusercontent.com/1538852/52526394-bd504780-2d1c-11e9-87e8-a399ed82b878.png)

**Comment by thetuningspoon** [comment]
@Toutouwai Thanks for checking. So it seems to be ignoring the children part altogether, which I didn't notice in my case since I was filtering the template. I seem to be observing the same issue now with a text field.

**Comment by somatonic** [comment]
I'm not sure about this selector syntax with children. Originally it only works for children.count. Also the blog post doesn't make it clear: "For instance parent and children keywords may be used here to reference the family hierarchy the page(s) to be matched might live within."

I don't see any code in PageFinder that would do that with "children.subfield". But then I don't really understand all of it.

But what works is 

`$pages->find("children=[foo=bar]");`

**Comment by somatonic** [comment]
And what I found out now is that it only works with a.b.c (PageField.field.property)

So this works for me on a date field for example:

`$pages->find("children.date_start.data>today");`

**Comment by thetuningspoon** [comment]
children.dateField.data worked for me too. That gives me a good workaround for now, at least. Very strange.

**Comment by Toutouwai** [comment]
Just cross-linking this request for working `children.field` syntax (which I made a while ago and had forgotten about): https://github.com/processwire/processwire-requests/issues/174

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your further consideration in the coming week.

/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
I've added support for this. Just done basic testing so far but please let me know if you run into any issues with it. Thanks.

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week
