### ISSUE TITLE
Can't save search bookmark

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#811]
When I access /processwire/page/search/ I get:

`ProcessPageSearch: No search specified`

When I click on "Reset filters and columns to default" I get:

`Session: No search specified`

When I try to "Add new bookmark", I get:

`ProcessWire: Unrecognized path`

![serach](https://user-images.githubusercontent.com/7663992/52577942-7dc05300-2e23-11e9-9ab3-af5703feac54.gif)

**Comment by matjazpotocnik** [comment]
Looks like executeEditBookmarks method is missing in ProcessPageSearch.module, although it's present in ProcessPageLister.

But even if you add a bookmark in ProcessPageLister, you get The process returned no content.

EDIT: It's working in lister, ignore my second statement.

**Comment by gadgetto** [comment]
I can confirm this problem!

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik @gadgetto I've pushed a fix for this issue.

**Comment by matjazpotocnik** [comment]
Thanks, bookmarks are now saved, but I discovered another issue: if bookmark title is integer (eg. title is set to "123", the bookmarks look like this:

![screenshot 2019-02-12 18 47 05_cr](https://user-images.githubusercontent.com/7663992/52657220-774fdb00-2ef8-11e9-96eb-f758b8620a34.jpg)

After I edit the bookmark and change the title from "123" to "abc", then bookmark is displayed ok.

**Comment by matjazpotocnik** [comment]
Aha moment: A key may be either an integer or a string. If a key is the standard representation of an integer, it will be interpreted as such (i.e. "8" will be interpreted as 8, while "08" will be interpreted as "08"). Floats in key are truncated to integer. There are no different indexed and associative array types in PHP; there is only one array type, which can both contain integer and string indices.

So I "fixed" it by appending "\0" to the $title in ProcessPageListerBookmarks.php

`$row[$title."\0"] = $bookmark['url'];`

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I have added your suggested update.
