### ISSUE TITLE
image focus value fraction

### ISSUE THREAD

**Issue by Jehfen** [processwire/processwire-issues#815]
### Short description of the issue

I noticed that in the database's image fields, the fractional part of focus values are a bit overkill:

### Expected behavior

{"focus":{"top":93,"left":49,"zoom":0}}

### Actual behavior

{"top":93.400000000000005684341886080801486968994140625,"left":49.39999999999999857891452847979962825775146484375,"zoom":0}}

### Suggestion for a possible fix

round()

### Setup/Environment

* ProcessWire version: 3+
* PHP version: 7+
* MySQL version: MariaDB 10.2

**Comment by ryancramerdesign** [comment]
We need a floating point number here, as dropping the part after the decimal doesn't given us enough possible values. However, we don't need that many decimals. But when I save focus settings, I end up with numbers that are rounded to one decimal point. So I can't currently reproduce this one.

**Comment by netcarver** [comment]
@junofornow Can you provide any more information that might help Ryan track this down?  Perhaps this is a difference between systems?

**Comment by Jehfen** [comment]
In v3.0.146 it's allready fixed, see attached image. So I can't reproduce it anymore.
On top of the screenshot the value when saving the focus again in a recent version.
In the bottom of the screenshot the value from an old image when I filed the issue a couple of months ago.

![Capture](https://user-images.githubusercontent.com/37275559/71310032-8902e880-240f-11ea-83ea-2a9204745356.JPG)

**Comment by netcarver** [comment]
@junofornow If it's now fixed, please could you close this issue.

**Comment by Jehfen** [comment]
Closed because it seems fixed in recent versions.
