### ISSUE TITLE
"Trash for all" feature does not work if the 404 page is moved under "admin"

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-issues#817]
### Short description of the issue

"Trash for all" feature does not work if the 404 page is moved under "admin"-
If 404 page ist moved back under "home", the trash icon is showing up for the non-superuser.

### Expected behavior

No dependency on location of 404 page.

See also: https://processwire.com/talk/topic/20902-trash-for-all-does-it-work/?tab=comments#comment-181000

PW Version 3.0.123

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
@theo222 The 404 page is a page like any other in the system when it comes to access control. If you move the page to somewhere that requires a login (which the admin does), that's going to potentially break ProcessWire's ability to properly render 404s and could cause a lot of other problems, the least of which is probably the effect on the trash. It's okay to move the 404 page to another location if you want to, but do not move it into the admin and don't move it below some other access controlled parent. Your 404 page needs to be publicly accessible since it loaded and rendered any time a requested URL is not found.

**Comment by theo222** [comment]
Thank you!

**Comment by theo222** [comment]
Reopened because the 404 page affects "trash for all" even if not moved under admin but also when hidden using: $wire->addHookAfter('Page::listable',...

So there is still no way to let the editor see the trashcan while the 404 page is hidden.

**Comment by matjazpotocnik** [comment]
It's in ProcessPageListRenderJSON.php:

```
foreach($this->children as $page) {
	if(!$this->superuser && !$page->listable()) continue;

	if($page->id == $id404 && !$this->superuser) {
		// allow showing 404 page, only if it's editable
		$page404 = $page;
		if(!$page->editable()) continue;
	} else if(in_array($page->id, $this->systemIDs)) {
		if($this->superuser) $extraPages[$page->id] = $page;
		continue;
	}

	$child = $this->renderChild($page);
	$children[] = $child;
}

if(!$this->superuser && $page404 && $page404->parent_id == 1 && !isset($extraPages[$idTrash])) {
	$pageTrash = $this->wire('pages')->get($idTrash);
	if($pageTrash->id && $this->getUseTrash() && $pageTrash->listable()) {
		$extraPages[$pageTrash->id] = $pageTrash;
	}
}
```

Commenting `$page404 && $page404->parent_id == 1` makes Trash appear in the list. Why is page404 so important in displaying Trash is not clear to me, Ryan will have to explain.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @theo222 I'm not sure about the 404 dependency either but as far as I can tell it is not necessary. I have adjusted the code to remove the 404 dependency so it should work now. Thanks.

**Comment by theo222** [comment]
Now I can see the Trashcan if the 404 Page is hidden.
But there is nothing in the trashcan from the editor's perspective and thus nothing to restore for this user.
If I move a page to the trash as editor, the trashcan seems still empty for the editor.
Only the admin user can see that there is something in the trashcan and try to restore it.
What am I missing?
It seems unrelated to the 404 issue. Shall I open a new bug report?
Thank you.

**Comment by ryancramerdesign** [comment]
@theo222 It's fine to keep this one open, I'll investigate what you mentioned next.

**Comment by ryancramerdesign** [comment]
@theo222 I've pushed an additional update that should fix the issue. Please test it out and let me know how it works for you. Thanks.

**Comment by theo222** [comment]
Yes, now everything seems to work as expected.
Thank you Ryan!
