### ISSUE TITLE
Tree menu: uneditable pages without template file have wrong link

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#818]
### Short description of the issue

In the flyout Tree menu, pages that the user does not have edit permission for and that do not have a template file have an incorrect link to /processwire/page/list/navJSON/. See screencast:

![tree](https://user-images.githubusercontent.com/1538852/53052887-bd163000-3504-11e9-997e-6fb94ad05ce2.gif)

Although not as clearly unwanted as the above case, for pages that the user does not have edit permission for that _do_ have a template file the menu item links to view the page on the front-end. I think it would be better if all non-editable pages in the Tree menu did not contain a link, so the purpose of links in the menu is consistent. When a user browses the Tree menu I don't think their intention is to view any pages in the front-end. So somewhat related to this request: https://github.com/processwire/processwire-requests/issues/274

### Setup/Environment

* ProcessWire version: 3.0.125

**Comment by netcarver** [comment]
/remind me to review this issue in 1 week

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks.
