### ISSUE TITLE
Translate missing strings in /wire/modules/Fieldtype/FieldtypeComments/CommentNotifications.php

### ISSUE THREAD

**Issue by beatep** [processwire/processwire-issues#820]
Is it possible to make all the $info['message'] in  /wire/modules/Fieldtype/FieldtypeComments/CommentNotifications.php translatable? This would be great.

**Comment by ryancramerdesign** [comment]
@beatep Were there any in particular that are an issue? The only ones I left untranslated are those that I thought were unlikely to ever occur except in debugging scenarios to developers, whereas any that a regular front-end user might see are already translatable. That was the intention at least. Throughout the core I try to be selective with translatable text to make sure I'm not wasting translators time with translating strings that aren't likely to ever appear outside development. Sometimes I don't calculate that quite right though, so let me know which strings you are running into that need translation and I'll make them translatable here. I'm guessing maybe the "Updated comment [n] to [status]" string? That's one that could appear to administrators at least, so probably should be translated. Let me know of any others you think need it. Thanks.

**Comment by beatep** [comment]
Yes, it was `$info['message'] = "Updated comment $comment->id to '$action'";` as the owner of a post updated a comment to be shown. I think this one and the following would be sufficient.

Thanks!

**Comment by ryancramerdesign** [comment]
Sounds good, thanks, I have updated that notification to be translatable.

**Comment by netcarver** [comment]
@beatep Hello Beate, please go ahead and close this issue if Ryan's push has fixed it for you. Thank you!
