### ISSUE TITLE
CKEditor link dialog in frontend-edit doesn't insert correct language url

### ISSUE THREAD

**Issue by ocorreiododiogo** [processwire/processwire-issues#821]
### Short description of the issue

Link dialog in frontend-edit in CKEditor textarea fields doesn't insert the correct language when page is edited from a language that is not the default. It shows always the default language url.

### Expected behavior

When editing from a page that is viewed in a different language, the link dialog should show and insert the links from that language. Just like in the language fields or tabs inside the admin.

### Actual behavior

Editing a field from the front-end when viewing the page in the non-default language, shows the text in the correct language, but the links in the dialog are in the default language.

### Steps to reproduce the issue

1. Install core multilanguage module, add a second language.
2. Create a multilanguage CKEditor field, and add frontend editing to that field (any option).
3. View a the second language version of a page with that field, and edit in the frontend (click twice).
4. Add a link to an inner page inside the text. Notice the url.

### Setup/Environment

ProcessWire version: 3.0.126 and 3.0.123 (tried in two different sites in different hosts. One was a fresh install)

**Comment by ryancramerdesign** [comment]
Thanks @ocorreiododiogo I was able to duplicate that here as well and have pushed a fix for it. It involved an update to the CKE link plugin which is sometimes hard to get the browser cache to recognize so if it doesn't work at first, try with dev tools open or in incognito window. Thanks.

**Comment by netcarver** [comment]
@ocorreiododiogo Could you review the change and close this issue, if appropriate. Thank you!

**Comment by netcarver** [comment]
@ocorreiododiogo Closing this. Please post more if needed.

**Comment by ocorreiododiogo** [comment]
@ryancramerdesign and @netcarver sorry for the late answer. This seems to be solved now, thanks!
