### ISSUE TITLE
Double-encoded entities in translatable strings

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#827]
### Short description of the issue

A [recent commit](https://github.com/processwire/processwire/commit/6ad523966655a03c60f3d76a9b38f7f3dfd2d33e#diff-46c1c53db7a9f8c3a2f9abe673dcc30f) forces entity encoding within translatable strings from Jan 10 2019 onwards. For strings containing HTML entities this results in double-encoding.

This can cause issues for existing modules that are using entities within translatable strings. For example, @adrianbj's Page Field Select Creator module uses `&nbsp;` to work around issues with the File Compiler wrongly adding the ProcessWire namespace within strings.
https://github.com/adrianbj/ProcessPageFieldSelectCreator/blob/f38548453682ad96e08b0c770d2adc6fcce05c1b/ProcessPageFieldSelectCreator.module#L105-L107

### Optional: Suggestion for a possible fix

Change the encoding option to `1=encode only if not already`

```php
if($config->installed >= 1547136020) {
	// installations Jan 10, 2019 and onwards:
	// make the __('text') translation function return entity encoded text if not already encoded, whether translated or not
	__(true, 'entityEncode', 1);
}
```

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your consideration.

**Comment by ryancramerdesign** [comment]
@Toutouwai I actually thought this one was a potential security issue (though a minor one), as the previous behavior was inconsistent as to when it would return entity encoded values or not (depending on whether translation available), so you couldn't really depend on it. Now its behavior is consistent, but it's true it might be problematic if someone is intentionally using entities or HTML in their translatable strings. Though translatable strings are not intended to be defined with HTML or entities in them, as neither would survive translation in any version of PW. Detecting whether a string is already entity encoded is not an exact science, plus there's overhead in doing it, so I'd like the core to retain the current behavior, as it's more secure and fast. But if a site or module wants to change the behavior, it is also possible to do so by making that `__(true, 'entityEncode', 1);` call from their /site/config.php or a module could also do it.

**Comment by Toutouwai** [comment]
Okay, thanks, closing.
