### ISSUE TITLE
remember displayed fields after page save

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#828]
### Short description of the issue

When you edit a page with ?field=yourfield or ?fields=foo,bar the page editor shows only those fields, but after saving the page it shows all fields again.

### Expected behavior

After saving the page it should show the exact same fields that it showed before.

### Actual behavior

It loses the ?field information in the url and therefore shows the default page edit screen.

**Comment by matjazpotocnik** [comment]
Possible fix: make getRedirectUrl() hookable.

Or something like this in ProcessPageEdit.module, around line 2078:

```
$extras = array();
if($this->input->get('field')) $extras = array('field=' . $this->input->get('field'));
if($this->input->get('fields')) $extras = array('fields=' . $this->input->get('fields'));

$this->processSaveRedirect($this->getRedirectUrl($extras));
```

**Comment by ryancramerdesign** [comment]
Thanks @BernhardBaumrock @matjazpotocnik I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@BernhardBaumrock closing this one now. Please post more if needed.
