### ISSUE TITLE
Stacktrace converted to string breaks Tracy functionality.

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#829]
### Short description of the issue

The `trycatch` in index.php messes with Tracy functionality. 

**Instead of getting:**

![image](https://user-images.githubusercontent.com/871211/54168911-ea803a80-442d-11e9-993f-4fb327da8136.png)

**we get:**

![image](https://user-images.githubusercontent.com/871211/54168927-ff5cce00-442d-11e9-9389-3da2cb45e6e9.png)

which means we can't follow the stack trace nicely through Tracy.

### Optional: Suggestion for a possible fix

Do you think you could remove this `trycatch` if Tracy is installed?

### Steps to reproduce the issue

1. add `trigger_error('test', E_USER_ERROR);` to a template file
2. load a page with that template

Now try commenting out the `trycatch` like this:
```
//try {
	// Bootstrap ProcessWire's core and make the API available with $wire
	$wire = new ProcessWire($config);
	$process = $wire->modules->get('ProcessPageView');
	$wire->wire('process', $process);
	echo $process->execute($config->internal);
	$config->internal ? $process->finished() : extract($wire->wire('all')->getArray());

/*} catch(\Exception $e) {
	// Formulate error message and send to the error handler
	if($process) $process->failed($e);
	$wire ? $wire->trackException($e) : $config->trackException($e);
	$errorMessage = "Exception: " . $e->getMessage() . " (in " . $e->getFile() . " line " . $e->getLine() . ")";
	if($config->debug || ($wire && $wire->user && $wire->user->isSuperuser())) $errorMessage .= "\n\n" . $e->getTraceAsString();
	trigger_error($errorMessage, E_USER_ERROR);
}*/
```
and see how much nicer Tracy handles it.

**Comment by BernhardBaumrock** [comment]
Yes, this would be great!! Thx in advance 👍 

It's not only about looking nicer, it's also about being able to just click on the links and open the corresponding line directly in your IDE - a real timesaver in everyday work!

**Comment by szabeszg** [comment]
> Yes, this would be great!! Thx in advance

What else to add? +1 :)

**Comment by netcarver** [comment]
Isn't this more like a feature request? Is there any problem, as is, with the core's handling of the problem when Tracy is not installed?

**Comment by BernhardBaumrock** [comment]
I'd say it's something in between. One could definitely use ProcessWire without Tracy, but if you are using Tracy, the error can only be fixed in the PW core (see the referenced issue in nette/tracy). Whatever you call it - it would really help me! :) And Adrian's awesome module would definitely deserve this fix/feature.

**Comment by szabeszg** [comment]
I would like to rephrase what Bernhard said: yes, it could be considered as a feature request but still:
1: What if it is caused by an unintended behavior of PW? It is worth investigating first.
2: Tracy Debugger is the number one free module for PW so yeah, it deserves special attention IMHO too.

**Comment by adrianbj** [comment]
@netcarver - yeah, sorry - I did contemplate putting it in the feature request repo, but the current behavior has bugged :) me for a while and it certainly does break how Tracy works.

**Comment by teppokoivula** [comment]
I'm not too familiar with the implementation here, but does `$config->allowExceptions` affect this issue? Overall I seem to remember that `Wire::trackException()` was originally added for similar reasons: to allow third party tools proper access to exceptions.

Sorry if this is completely unrelated – it just seems like this would be the clean solution. If not, then by all means keep this going. If there's any way to handle this without adding module-specific rules in the core, then _please_ take that route instead.

**Comment by adrianbj** [comment]
Nice one @teppokoivula - I hadn't noticed that option before. I am going to see if I can hook into Wire::trackException so Tracy users don't need to manually set that $config setting. I'll report back with how I make out.

**Comment by adrianbj** [comment]
Well that was easy :)

Thanks again @teppokoivula - all sorted!

**Comment by adrianbj** [comment]
For those following here, the fix is now implemented in Tracy and looks to be working great!

**Comment by ivangretsky** [comment]
I've just faced this issue and [reported it back to Tracy subforum](https://processwire.com/talk/topic/26364-show-more-than-15-items-in-the-call-stack/?tab=comments#comment-218923). Actually I was getting it before so many times I didn't recognize it as a bug prior to this moment))) But as @adrianbj  showed me how it could be if this bug is solved I see what i've been missing. Could you please take another look at it @ryancramerdesign ?
