### ISSUE TITLE
Image not uploaded when php5-gd is not installed

### ISSUE THREAD

**Issue by clsource** [processwire/processwire-issues#83]
### Short description of the issue

ProcessWire will load forever an image if `php5-gd` is not present in the server for creating the thumbnail. 

### Expected behavior

Upload the image anyway even if the thumbnail was not possible to be created. 

### Actual behavior

When no engine is found for creating the thumbnail the image loads forever. This is caused by an error 500. because the $engine is null and is trying to get a property of a non object.

### Optional: Suggestion for a possible fix

`PageImage.php` Line 480.

Change to

```
$engineConfigData = (method_exists($engine, 'getConfigData') ? $engine->getConfigData() : null);
```

### Steps to reproduce the issue

1. Create a single image field
2. Upload an image
3. The thumbnail could not be created

### Setup/Environment

Processwire installed but no `php5-gd` module is enabled.

* ProcessWire version: 3.0.33
* (Optional) PHP version: 5.6
* (Optional) MySQL version: 5.6
* (Optional) Any 3rd party modules that are installed and could be related to the issue: php5-gd php-imagick imagemagick

**Comment by teppokoivula** [comment]
According to the docs, ProcessWire requires "PHP's bundled GD 2 library". Is `php5-gd` something different entirely, or was this site installed elsewhere and then moved to a server that doesn't fulfil said requirements?

While the fix doesn't see particularly harmful, I'm just wondering what else this could break. Perhaps we should, at least, display an error somewhere declaring that this environment may not be suitable to run ProcessWire?

**Comment by LostKobrakai** [comment]
GD is only used for image manipulation/resizing, so if somebody does not need to use it (and is fine with pot. broken previews in the backend) one could work without it. But it's certainly not recommended to do so.

**Comment by ryancramerdesign** [comment]
Like Teppo I'm also wondering what this might break, by letting the non-presence of a required library continue down the line… sooner or later there's going to be a fatal error. I'm thinking we might benefit from a ImageSizerEngine that does nothing, just returning the original image. That would probably enable everything to continue working even if there's no GD library (or ImageMagick, etc.). I'm curious what @horst-n thinks would be the best solution (if we should try to solve this at all?)

**Comment by ryancramerdesign** [comment]
I'm going to close this one out since GD is a requirement for running PW. But if a lot of people start experiencing the same issue in the future (like PHP disables it by default in some version) then we'll revisit it.
