### ISSUE TITLE
Image tags not saving

### ISSUE THREAD

**Issue by marloren** [processwire/processwire-issues#830]
### Short description of the issue

On 3.0.127, with tags on an image field enabled, entered tags are not saved to the database.

### Expected behavior

Tags are saved

### Actual behavior

Tags are not saved

### Optional: Screenshots/Links that demonstrate the issue

The following GIF demonstrates the issue:

![tags](https://user-images.githubusercontent.com/35661352/54209761-9d0fd600-44de-11e9-9642-b237585c2637.gif)

### Steps to reproduce the issue

Field settings:

![field-settings](https://user-images.githubusercontent.com/35661352/54209925-e3fdcb80-44de-11e9-9a41-dff8634f6373.png)

Note: the other two relevant options in the "Use Tags?" field have the same results.

### Setup/Environment

* ProcessWire version: 	3.0.127
* (Optional) PHP version: 7.2

**Comment by netcarver** [comment]
@marloren Thank you for the issue report!

**Comment by matjazpotocnik** [comment]
I can't reproduce, it's working here.
![tags1](https://user-images.githubusercontent.com/7663992/54215912-01d02e00-44e9-11e9-97b9-0f74d97de051.gif)
Any errors in console?

**Comment by marloren** [comment]
I've installed Tracy Debugger for the first time, and there's no error in the console.

**Comment by ryancramerdesign** [comment]
@marloren @matjazpotocnik I also can't duplicate this one here. Other than Tracy Debugger, what 3rd party modules are installed? I see something about AdminOnSteroids in the lower left corner of your GIF above—can you try uninstalling that to see if that might be affecting something?

**Comment by marloren** [comment]
I've tried uninstalling all modules in "Site", but I'm still having the same issue, both on Firefox and Chrome. Could it be some sort of name conflict if my image field is named "photo"?

**Comment by marloren** [comment]
When I try to manually enter a tag name directly in the database through PhpMyAdmin, it gets saved correctly, but it does not appear in the tag field as expected.

**Comment by ryancramerdesign** [comment]
@marloren I don't think there would be any issue with using the name "photo". I don't have any idea what the issue could be, and without any JS errors to look at, I think we have to wait and see if anyone else is able to duplicate the issue. Another thing that might be worth trying is to reproduce it on a completely separate blank installation using one of the default site profiles.

**Comment by marloren** [comment]
I've tried with another site on the same server, and it works as expected. Can't still figure out why it's not working for this particular site. I'm going to close this issue, but I'll reopen it if I encounter the same problem elsewhere again.
