### ISSUE TITLE
AdminThemeUikit: insufficient space after icon in flyout menus

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#831]
### Short description of the issue

The width of Font Awesome icons vary, and for wider icons there is not enough space between the icon and the menu item text in flyout menus.

![2019-03-17_205852](https://user-images.githubusercontent.com/1538852/54487225-62e86f00-48f8-11e9-9094-33b8188a5682.png)

Increasing the `margin-right` fixes the collision between icon and text:

```css
.ui-menu .ui-menu-item i.fa {
    margin-right: 8px;
}
```

![2019-03-17_210020](https://user-images.githubusercontent.com/1538852/54487251-ac38be80-48f8-11e9-9d48-27a01475687d.png)

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed your suggested fix. The only thing is that I think we recently reduced that margin to resolve some other reported issue (?). I never noticed any issues regardless of margin settings here so I don't recall what it was, but keep an eye out just in case. Thanks.
