### ISSUE TITLE
Lister: field labels refresh one reload too late

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#832]
### Short description of the issue

There seems to be a Lister feature that displays field labels in template context as the column headers. This is a nice feature but the problem is that these customised column headers only get applied on the next Lister reload _after_ they should be applied.

In the screencast below the title field is given the label "Model" on the car template. On the basic-page template it has the standard "Title" label.

You can see that the "Model" label only gets applied after the Lister is refreshed. And if the template filter is changed between the car and basic-page template on each Lister reload then the label is consistently incorrect.

![lister](https://user-images.githubusercontent.com/1538852/54740989-d1436f00-4c21-11e9-8764-640bbfe82f3c.gif)

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
That was quick, thanks!
