### ISSUE TITLE
Sanitizer selectorValue maxLength's default value causing 404s

### ISSUE THREAD

**Issue by adoxus** [processwire/processwire-issues#835]
### Short description of the issue

An upgrade from `v3.0.123 master` to `v3.0.127 dev` causes over-100-character-long `$page->url`s to throw 404 error. That lead to `core/Sanitizer.php` `selectorValue()` >` maxLength` which is also 100. I think the trigger is `v3.0.125` update.

### Expected behavior

When there should be trimming needed on the URL path by page name's length, it was done by the core automatically and it doesn't affect the workings of `url` variable which includes all the page names of parent pages.

### Actual behavior

Pages with `url` variable longer than 100 characters throw 404 error on previously working ones.

### Optional: Suggestion for a possible fix

By increasing said `maxLength` value of `selectorValue()` in `Sanitizer.php` solves problem, temporarily.

### Steps to reproduce the issue

1. Create any page which has title over 100 characters when sanitized that has at least one parent.

### Setup/Environment

* ProcessWire version: 3.0.127
* (Optional) PHP version: 7.2.14

**Comment by ryancramerdesign** [comment]
Thanks @adoxus I think I may have unintentionally introduced this issue last week with some changes in ProcessPageView.module. We allow up to 2048 chars for page path name, and it looks like I neglected to add that maxLength to a new selectorValue() call. I have just pushed a fix for it. Can you confirm it resolves the issue you are seeing? Thanks.

**Comment by adoxus** [comment]
Thank you @ryancramerdesign. Worked like a charm. 😃
