### ISSUE TITLE
ProcessPageEditLink: JS error on config screen

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#836]
### Short description of the issue

A JS error occurs on the module config screen of ProcessPageEditLink:

```
Uncaught TypeError: $(...).WireTabs is not a function
    at HTMLDocument.<anonymous> (ProcessPageEditLink.min.js?v=108-1553187932:1)
    at l (JqueryCore.js?v=1553187932:2)
    at Object.fireWith [as resolveWith] (JqueryCore.js?v=1553187932:2)
    at Function.ready (JqueryCore.js?v=1553187932:2)
    at HTMLDocument.A (JqueryCore.js?v=1553187932:2)
```

The error prevents other JS on the page from working (e.g. admin dropdown menus).

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by Toutouwai** [comment]
It's a bit unexpected to me that the JS file named the same as the Process module should be included when the module config screen is visited. I expected it would only be included for the module's execute() methods, when the process itself executes. Is it possible to avoid this happening on the config screen? I can imagine other Process modules being affected by this unexpected behaviour.

**Comment by ryancramerdesign** [comment]
I can't duplicate this one. I'm also not seeing ProcessPageEditLink.js showing up in my scripts when configuring this module. I'm guessing something might be loading the module somewhere. It's not necessarily unexpected that the js file would be loaded, so perhaps the ProcessPageEditLink.js needs to be updated either way, but just curious what might be triggering the module to load (independent of its config screen)?

**Comment by Toutouwai** [comment]
Sorry for the false alarm - I thought I was testing on a clean installation but there was actually a hook in ready.php that I had left behind from a previous test.

**Comment by ryancramerdesign** [comment]
No worries, it happens to me all the time too. :)
