### ISSUE TITLE
$page->matches() bug with not equals template

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#837]
### Short description of the issue

Both of the following return true:

```php
$pages(1)->matches('template=basic-page|home');
$pages(1)->matches('template!=basic-page|home');
```

But as shown in the screenshot below, the PageArray resulting from selector `template!=basic-page|home` does not include the Home page.

![2019-03-26_154623](https://user-images.githubusercontent.com/1538852/54968105-5e017a80-4fde-11e9-87e6-414f3b081520.png)

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue. Can you confirm it also fixes it there?

**Comment by Toutouwai** [comment]
Thanks, that's fixed it.
