### ISSUE TITLE
Issues with "parent" in selector OR field condition

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#838]
### Short description of the issue

There seems to be issues when "parent" is used in a OR condition for fields in a selector (field1|field2=value).

A couple of examples:

![2019-03-27_105729](https://user-images.githubusercontent.com/1538852/55036552-d9ffcf00-507f-11e9-9c25-862b2ccd023e.png)

![2019-03-27_105953](https://user-images.githubusercontent.com/1538852/55036556-de2bec80-507f-11e9-9b60-ef98e7c1a2b1.png)

In the latter example the issue also occurs when the selector is `id|parent.id=1`.

Maybe "parent" is a special case that isn't allowed in field OR conditions? If so this should be noted in the Selectors documentation.

Related forum topic: https://processwire.com/talk/topic/21130-problems-with-parent-selecotrs/

### Setup/Environment

* ProcessWire version: 3.0.127

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have added support for this

**Comment by Toutouwai** [comment]
Great, thanks!
