### ISSUE TITLE
The Automatic Page Name Format in the PageTable field stopped working. 

### ISSUE THREAD

**Issue by cstevensjr** [processwire/processwire-issues#840]
### Short description of the issue

The automatic Page Name feature in ProField: Page Table is not working in 3.0.127.

### Expected behavior

If you entered "Ymd:His" this should give you a datetime page name.

### Actual behavior

It's now giving you a name of Ymd-His and variants

### Optional: Screenshots/Links that demonstrate the issue

![image](https://user-images.githubusercontent.com/7488817/55198933-6993a380-518e-11e9-9abc-f8824755082f.png)

### Optional: Suggestion for a possible fix

N/A

### Steps to reproduce the issue

N/A

### Setup/Environment

* ProcessWire version:  3.0.127
* (Optional) PHP version: 7.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@cstevensjr Thanks for the report. I was wondering if you could try specifying `Ymd/His` in the name format (with the slash `/` in it rather than the colon) OR `date:Ymd:His` (with the `date:` prefix), and let me know if either of those work? If so, I know right where to look, but just wanted to confirm. Thanks.

**Comment by trk** [comment]
@ryancramerdesign I tested both methods `date:Ymd:His` and `Ymd/His` not working. My old value is: `dmY:His` also not working anymore.

**Comment by teppokoivula** [comment]
In case it helps, I've been using `ymd-his` at weekly.pw, and it looks like this has stopped working in issue 230 (6th of October 2018).

Can't say for sure what version I updated to back then, though :)

**Comment by cstevensjr** [comment]
I was on-the-road travelling. I can now confirm that neither method worked.

**Comment by ryancramerdesign** [comment]
Thanks @cstevensjr @trk @teppokoivula I have pushed a fix for this issue. Note that there has to be one of these characters present before it'll assume it is a date `:/ ` so a format of `ymd-his` won't work, but a `ymd:his` will.

**Comment by cstevensjr** [comment]
I can confirm that the fix is working.  Thanks.

**Comment by teppokoivula** [comment]
@ryancramerdesign, thanks for the fix, and sorry – looks like my setting was indeed `ymd:his`. `:` is converted to `-` in page name, which threw me off here. Anyway, all should be fine now :D
