### ISSUE TITLE
Page field can't reference current page

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire-issues#842]
### Short description of the issue

It is not possible to reference current page in Page Field (the page the field is attached to) editing the page in admin.
The issue is described [here](https://processwire.com/talk/topic/15850-page-reference-field-excludes-current-page/).

### Suggestion for a possible fix

Remove the [check in ___getSelectablePages](https://processwire.com/talk/topic/17375-page-self-not-saved-in-page-reference/?do=findComment&comment=152635) for everyone or make an optional checkpox "Allow to choose self" in Inputfield Page settings.

**Comment by ryancramerdesign** [comment]
Hi @ivangretsky Page fields are not allowed to reference themselves by design because it creates a circular reference which can easily lead into an infinite loop. As a result, the core performs a lot of checks to prevent you from creating such circular references, so this behavior is intended.

**Comment by netcarver** [comment]
I think you can use Teppo's module to store a reference to the page id in this case @ivangretsky.

**Comment by ivangretsky** [comment]
What module are you talking about, @netcarver?

**Comment by teppokoivula** [comment]
I believe @netcarver was referring to https://github.com/teppokoivula/FieldtypePageIDs. The idea there is to only store IDs, not actual references – this way the core doesn't get entangled in circular references, but the developer has to take some extra steps if actual Page objects are needed :)

**Comment by ivangretsky** [comment]
Thanks, everybody! Thorough answers are given, so closing it.
