### ISSUE TITLE
Name validation feature in the Add Page view fails "index.php" is used as the name

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#843]
If I add a new page, and type in index.php as the page name, the page name validation feature produces strange results: it seems to load an unstyled page list.

I've tested this on a couple of 3.x sites (3.0.129 and 3.0.118) and one 2.7.x site, and it seems to occur consistently in the 3.x versions I have at hand but not in 2.7.x. The sites I've tested are pretty different, in terms of hooks and modules, but please let me know if you can't reproduce this and I'll try to debug it a bit further.

**Comment by matjazpotocnik** [comment]
I can reproduce. It looks like it happens only with the name index.php. When the last "p" is typed in, the redirection from `/processwire/page/add/exists?parent_id=1234&name=index.ph` to `/processwire/page/add/` occurs, and there renderChooseTemplate() method renders the list template selection when no parent/template is known. Don't have more time right now to debug further and find out why it's happening only on index.php name.

Edit: it looks like there is a problem in ProcessPageView in getPage() method around line 345 (else statement)?
Edit2: Oh, already fixed... thx Ryan!

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula @matjazpotocnik I've pushed a fix for this issue.

**Comment by teppokoivula** [comment]
Thanks Ryan, works fine now!
