### ISSUE TITLE
WireCache::getExpires() does not handle string names correctly

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#844]
### Short description of the issue

WireCache::getExpires() does not handle string names correctly. Using strings like 'hour', 'hourly' the current time is not added before date formatting.

### Setup/Environment

* ProcessWire version: 3.0.128

**Comment by ryancramerdesign** [comment]
Thanks @kixe I've pushed a fix for this issue.

**Comment by kixe** [comment]
@ryancramerdesign
thanks. closed.
