### ISSUE TITLE
The old avatar picture still being referenced

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#845]
When editing a user image field (aka avatar) in ProcessUser image in AdminThemeUikit, and you replace the old avatar image with the new one, the old image is still being referenced in session AdminThemeUikit in 'sidenav' array.
![avatar](https://user-images.githubusercontent.com/7663992/55772447-88e2d880-5a8c-11e9-9fce-1633dbfc8b34.gif)

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik I have pushed a fix for this issue. It was due to a session cache that was only generated at the beginning of the session.

**Comment by matjazpotocnik** [comment]
Thanks for the quick fix, Ryan.
