### ISSUE TITLE
$sanitizer->testAll() missing new options

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#85]
### Short description of the issue

$sanitizer->testAll() missing new options

### Expected behavior

testAll() should use almost all of the options listed here: https://processwire.com/api/ref/sanitizer/
I know that not all options are appropriate, like "purifier", but I think many valid ones are missing.

### Actual behavior

The list isn't complete: https://github.com/processwire/processwire/blob/ab7b7a6380adbba0c5571f65391f88b66ee379d1/wire/core/Sanitizer.php#L2317

**Comment by ryancramerdesign** [comment]
That method is just so that I can test out the sanitizers during development. A lot of the sanitizers delegate to others, so it's not necessary to have them all in here. Just the ones needed for testing. Are there any specifically that you think would be useful here? I generally add new ones when there's something specific I need to test. The method isn't really meant as something adding value to the public API, more just tool during development in the Sanitizer class.

**Comment by adrianbj** [comment]
Sorry, I assumed it was meant to be a complete list. I find it really useful myself - sometimes if I have forgotten what sanitizer I want I use it via the Tracy console like this:

```d($sanitizer->testAll("text to sanitize"));```

![screen shot 2016-11-22 at 7 47 41 am](https://cloud.githubusercontent.com/assets/871211/20530372/015ed3b0-b088-11e6-9f7d-b5c8e8b5e595.png)

I often find this more useful than the $sanitizer docs page because I can see the results. You have also been adding lots of new sanitizer methods recently and this is a great way of seeing what's new.

I don't really have any specific ones I want to see added, just having them all would be my ideal.

**Comment by teppokoivula** [comment]
I've been wondering what this method is for, and I have to say that @adrianbj's use case above makes perfect sense. +1 for including *all* available sanitizer methods for clarity :)

**Comment by ryancramerdesign** [comment]
I didn't realize anyone else had a use for this, but agree the mentioned use case makes sense. I'll update to add all the applicable sanitizers to it.

**Comment by ryancramerdesign** [comment]
This has been updated with some additional sanitizers added. Only excluded sanitizers are those that require secondary/non-value arguments, like match(), option() and options().

**Comment by adrianbj** [comment]
Thanks Ryan!

OT - is that whitespace change on line 2362 an indicator that your code editor is now set to trim trailing whitespace? It would be very helpful for those of us submitting PRs if that was to become the standard going forward :)

**Comment by BernhardBaumrock** [comment]
@ryancramerdesign when you add the missing sanitizers could you please also make the method hookable so that we can add our own sanitizers to this list easily?
See https://github.com/processwire/processwire/pull/137
