### ISSUE TITLE
AsmSelect does not honour disabled attribute of the underlying select

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#851]
### Short description of the issue

Inputfields that extend InputfieldSelect such as Select Multiple, Radio Buttons and Checkboxes honour the "disabled" attribute of options - if the option is disabled it may not be selected.

Example:

```php
$wire->addHookBefore('InputfieldSelect::render', function(HookEvent $event) {
	$inputfield = $event->object;
	if($inputfield->hasField != 'colours') return;
	$inputfield->addOptionAttributes(1062, ['disabled' => 'disabled']);
});
```

![2019-04-12_164024](https://user-images.githubusercontent.com/1538852/56012735-e5bae900-5d41-11e9-8a7c-81c8dcabe015.png)
![2019-04-12_164042](https://user-images.githubusercontent.com/1538852/56012740-e9e70680-5d41-11e9-905c-c86e2109e44e.png)
![2019-04-12_164058](https://user-images.githubusercontent.com/1538852/56012743-ec496080-5d41-11e9-9676-167dd728dc44.png)
![2019-04-12_163956](https://user-images.githubusercontent.com/1538852/56012744-ee132400-5d41-11e9-8034-0765e0401398.png)

But InputfieldAsmSelect does not honour the disabled attribute of the underlying select that it modifies, allowing disabled options to be selected.

![2019-04-12_165306](https://user-images.githubusercontent.com/1538852/56013135-7e9e3400-5d43-11e9-9831-0cf53c6a9a70.png)

AsmSelect does support disabled options (it disables items in the dropdown after they have been selected) so I expected it carry over disabled options from the underlying select.

### Setup/Environment
* ProcessWire version: 3.0.129

**Comment by Toutouwai** [comment]
Possible fix - replace [these lines](https://github.com/processwire/processwire/blob/da309f335b3f4bef4a4c8709647757b5080f5781/wire/modules/Inputfield/InputfieldAsmSelect/asmselect/jquery.asmselect.js#L261-L267) with:

```js
if($t.is(":selected")) {
	addListItem(id); 
	addSelectOption(id, true); 						
} else if($t.is(":disabled")) {
	addSelectOption(id, true);
} else {
	numActive++;
	addSelectOption(id); 
}
```

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai  I have pushed your suggested fix for this.

**Comment by Toutouwai** [comment]
Thanks.
