### ISSUE TITLE
Error: Undefined index: <ModuleName> on line: 3274 in /wire/core/Modules.php when Module is not installed

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#852]
### Short description of the issue

If you try to get configuration data via `$modules->getConfig('ModuleX')` and  "ModuleX" isn't installed, you will get a warning:

`Error: Undefined index: ModuleX on line: 3274 in /wire/core/Modules.php`

### Expected behavior

getConfig method should return null or false if called on a module which isn't installed.

### Actual behavior

Throws warning: Error: Undefined index: ModuleX on line: 3274 in /wire/core/Modules.php

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.129|
|PHP|7.2.14|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeMessageMeta|0.0.1|
|InputfieldMessageMeta|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.5|
|ProcessGroupMailer|0.0.1|
|ProcessMessageLister|0.0.1|
|ProcessProMailer|0.0.5|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|TracyDebugger|4.19.10|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @gadgetto I've pushed a fix for this.

**Comment by gadgetto** [comment]
Thanks Ryan, just tested and it now works as expected!
Issue can be closed.

BTW - who closes issues?

**Comment by matjazpotocnik** [comment]
@gadgetto You can close it.

**Comment by gadgetto** [comment]
Done!
