### ISSUE TITLE
Modules Directory or WireHttp issue with URL length

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#856]
### Short description of the issue

I'm noticed an issue with ProcessWireUpgrade where I repeatedly get this error: 

![2019-04-18_162412](https://user-images.githubusercontent.com/1538852/56336903-6e300280-61f6-11e9-863f-0963e2bbd466.png)

After some debugging I found that `null` is returned when WireHttp tries to get JSON from the PW Modules Directory. It's reproducible with WireHttp alone, and seems to depend on the URL length.

Demonstration code for the Tracy console:
```php
$string = str_repeat('a', 882);
$url = "http://modules.processwire.com/export-json/?apikey=pw300&limit=100&field=module_version,version,requires_versions&class_name=$string";
$http = new WireHttp();
$data = $http->getJSON($url);
d($data, 'data');
```

In the demo I use str_repeat() to create a string of an arbitrary length to represent the comma-separated string of module names.

A string length of 881 works as expected:
![2019-04-18_162901](https://user-images.githubusercontent.com/1538852/56337034-278ed800-61f7-11e9-848a-fcf5c61cb596.png)

A string length of 882 gets a null return value:
![2019-04-18_162925](https://user-images.githubusercontent.com/1538852/56337048-3aa1a800-61f7-11e9-91ed-b0aaeb891e8f.png)

The odd thing is that the URL works when loaded directly in a browser, so it seems to be related to WireHttp somehow, but I can reproduce the issue in several different versions of PW. 

This problem only recently started occurring - within the last few days. Is a change at the Modules Directory responsible? Maybe something relating to this: https://github.com/processwire/processwire-issues/issues/753 ?

**Comment by Toutouwai** [comment]
This issue seems to be resolved now. I assume it was something to do with the hosting change: https://processwire.com/blog/posts/processwire-hosting-upgrades/

**Comment by ryancramerdesign** [comment]
@Toutouwai Are you sure it's resolved? I haven't changed anything yet, though maybe Jan did. I was guessing that there was a max length to the URL that the load balancer would pass to the server, but hadn't had a chance to check with Jan about it yet.

**Comment by Toutouwai** [comment]
Yes, it is resolved here. ProcessWireUpgrade is working again on sites where it previously wasn't, and the console test above is no longer returning null.

**Comment by ryancramerdesign** [comment]
Okay great, thanks for letting me know.
