### ISSUE TITLE
fix wording for absolute url in ProcessPageEditLink, because it isn't absolute

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#857]
The "absolute" wording is wrong, because absolute URL's include protocol, host and scheme. In this module a Root-Relative URL is being used. You can read about the differences here: http://www.dirigodev.com/blog/seo-web-best-practices/relative-vs-absolute-urls-seo/

So I changed the wording and the variable.

This led to confusion in the past, and also for me. https://processwire.com/talk/topic/17308-absolute-file-paths-in-inserted-ckeditor-links/?do=findComment&comment=152066

I already created a pull request for this https://github.com/processwire/processwire/pull/140

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch I've pushed a wording adjustment for this. It's using the terms "absolute" and "relative" in speaking about the path component of a URL where you can have /absolute/path/ that is absolute from root, or relative/paths/ and ../relative/paths/ that are relative to the page they appear on. I've adjusted the Inputfield wording and phpdoc for the constants to clarify these terms are speaking about the path component of the URL.

**Comment by teppokoivula** [comment]
@ryancramerdesign, I'm wondering if you'd consider adding clarifying examples here? I think that the wording is still potentially confusing, and as such examples would make it more obvious what's going on here.

So instead of this (current solution):

```
- Full/absolute path from root (default)
- Relative URLs in the same branches only
- Relative URLs always
```

We might have this:

```
- Full/absolute path from root, i.e. /full/path/to/page/ (default)
- Relative URLs in the same branches only, i.e. ../sibling-page/
- Relative URLs always, i.e. ../../path/to/page/
```

**Comment by ryancramerdesign** [comment]
@teppokoivula Unless anyone objects, I think this feature will be dropped because it's always been experimental, and I don't think it's compatible with abstraction of page URLs either, so it can be more trouble than it's worth. It's one of those things that seemed like a good idea at the time, but once link abstraction came along, there's not really any reason to keep the urlType option for this module anymore.

**Comment by teppokoivula** [comment]
Thanks @ryancramerdesign – makes sense. I also think that this feature is somewhat pointless, and potentially even harmful. Never really used it myself, though, so I may be biased :)
