### ISSUE TITLE
WireMail::header() does not allow to set any header

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#858]
### Short description of the issue

**WireMail::header()** does not allow to set **any** header. Some headers are set twice, respectively overwritten later.

### Expected behavior

allowance to modify any header

### Actual behavior

not possible to change:
- _Content-Type_
- _Content-Transfer-Encoding_
overwritten by **WireMail::renderMailHeader()**

**Comment by ryancramerdesign** [comment]
@kixe The features in the WireMail base class are dependent upon it outputting the correct content-type and content-transfer-encoding headers according to what's been provided to the email. Rendering the correct headers here is the primary purpose of the renderMailHeader method, adjusting content-type according to text vs. html, attachments vs. no-attachments, etc. If you could override those headers, then it would break all of that. 

If this is for a descending WireMail module, and you needed for it to do something differently, then it may be best to override the renderMailHeader() method with your own, or not call it in your ___send() method, as WireMail modules typically handle their own header rendering. 

If this is not for a descending WireMail module, and you think there's still a use case for overriding these mail headers, please tell me more about the use case and values you are trying to set for these headers, and there's a good chance I can add support for that. Thanks.

**Comment by netcarver** [comment]
@kixe Hi Christoph, could you give an update on this issue please as it's been a while since Ryan asked for some more information.  Many thanks!

**Comment by netcarver** [comment]
@kixe Hi Christoph. I intend to close this in a couple of days if we can't take this any further. 

/remind me in 2 days
