### ISSUE TITLE
Repeater Matrix: adding new items does not work if dynamic ajax loading is off

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#859]
If dynamic ajax loading is turned off for Repeater Matrix, then adding a new item does not work properly.  It will add the item stub, then after saving, it will disappear.

Regular repeaters do not have this issue.

Video:
https://www.youtube.com/watch?v=e9PkgLodLJw

Tested on PW 3.0.130 with blank site profile.

**Comment by ryancramerdesign** [comment]
@jlahijani RepeaterMatrix requires one of the ajax options (either the "all" or the "new" option), and the "off" option is not supposed to be there — I have updated RepeaterMatrix not to show that option and it'll appear in the next version, thanks for letting me know.
