### ISSUE TITLE
Rename .module files to .module.php

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#860]
### Short description of the issue

Some modules in the core (like InputfieldForm) have a .module file ending. This can be a problem in several situations:

- VSCode Extension "Intelephense" does not recognize those files as PHP files and there is unfortunately no way of telling it to index those files (so code Intellisense does not work)
- Syntax Highlighting only works if you tell your IDE that it should treat .module files as .php files.

The second point is not a problem for most users, but it would not be necessary if we had .module.php files and for newcomers (or maybe also other services like tracy file editor or the like) it might also be nice not having to bother about this.

### Optional: Screenshots/Links that demonstrate the issue

No InputfieldForm here:

![img](https://i.imgur.com/yLLayyY.png)

Happy to hear your thoughts!

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock We do already support .module.php files for those that prefer it for their own modules, but the ProcessWire core standard is to use the .module extension.

**Comment by BernhardBaumrock** [comment]
Hi Ryan,

> We do already support .module.php files
I know that. That's why I thought it would be an easy fix.

I had a closer look and I see that we currently have 133 .module files in the core. Not a single .module.php file. I thought we have a mix, because I get Intellisense for other classes, but that's because those classes are in .php files. So at least I know the reason now.

I found "only" one occurence where a module file was referenced hardcoded via xxx.module - so that could easily be fixed in the core. The problem is, that if anybody had some custom references in his code this would introduce breaking changes on updates. Not the best option, for sure.

Sp I'll ask for this feature in my Intellisense plugin repo. I also have a quickfix for everybody using vscode + intelephense + pw, but I'll continue in the forums with that.

Thx Ryan!
