### ISSUE TITLE
Page does not safe with > n Repeater Items and disabled Repeater Dynamic Loading

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#864]
### Short description of the issue

I found in our system some pages where changes to fields are not saved after clicking on the Safe-Button. My a long investigation I found the reason and workaround but still don't know the exact reason. We saw the issue on 2 pages. On one page, the changes are not saved after having more than 5 Repeater items on it. On the 2nd page, changes are not saved after having more than 8 Repeater items.

If I change the setting "Repeater Dynamic Loading" of the Repeater-Field from off to always ajax, the pages can be saved correctly.

Our Repeater Fields contains many multilanguage Text-Fields, some with CKEditor, some not and some Image Uploads field and also an other repeater field with contains also some text fields.

I tried to reproduce this with an clean PW Setup, containing a Repeater Field only with one CKEditor field, but also after adding 20 items, the issue does not appear here.

So I guess it only appears with the complex setup of fields on a page which have 7 fields with a repeater with has 13 fields where one field is also a repeater with 6 fields.

Fields are in use: TextLanguage, TextareaLanguage (with CKEditor), URLLanguage, Image, Options

### Setup/Environment

* ProcessWire version: 3.0.130
* PHP version: 7.3.3
* Any 3rd party modules that are installed and could be related to the issue:
I don't think so because after disabling all modules, the bug still appears.

**Comment by tiefenb** [comment]
I will continue the invastigation over the next days...

**Comment by tiefenb** [comment]
Okay, the next I found out is, that when I delete some fields from the 13 fields of the repeater it works also. It works after deleting 4 TextLanguage fields. After deleting 2 PageRef, 1 Image and 1 URL Field it didn't work, but after deleting also 2 TextareaLanguage it worked. So I guess it depends on the amount of fields and the type of the fields.

**Comment by Toutouwai** [comment]
You probably need to increase the PHP max_input_vars setting.

**Comment by tiefenb** [comment]
@Toutouwai thanks! this solved my issue.

Is there a possibility to throw an error if the limit is to low for the saved page? I guess this would help many to find quicker such problem

**Comment by Toutouwai** [comment]
@ryancramerdesign, maybe PW could include something like the below at the start of `ProcessPageEdit::execute()`?

```php
$max_input_vars = ini_get('max_input_vars');
if($max_input_vars && count($this->wire('input')->post) == $max_input_vars) {
    $this->error('PHP max_input_vars setting exceeded');
}
```

**Comment by BernhardBaumrock** [comment]
> if($max_input_vars && count($this->wire('input')->post) == $max_input_vars) {

+1 :) But I guess you mean > instead of ==

**Comment by Toutouwai** [comment]
> But I guess you mean > instead of ==

No, because PHP truncates all input variables greater than the max allowed, so the count will equal max_input_vars when it is exceeded.

**Comment by BernhardBaumrock** [comment]
thx, makes sense! :)

**Comment by tiefenb** [comment]
@Toutouwai 

I tried you fix in my local pw install and it works as it should:

<img width="830" alt="Bildschirmfoto 2019-04-28 um 19 06 03" src="https://user-images.githubusercontent.com/488163/56867710-c92cdb00-69e8-11e9-9237-2bbe6cb05cc0.png">

<img width="1110" alt="Bildschirmfoto 2019-04-28 um 19 06 11" src="https://user-images.githubusercontent.com/488163/56867712-cfbb5280-69e8-11e9-8062-defe57e200a0.png">

**Comment by ryancramerdesign** [comment]
Thanks I've pushed an update that adds a check for max_input_vars.

**Comment by tiefenb** [comment]
thanks - I have tested it and it works as expected

**Comment by tiefenb** [comment]
@ryancramerdesign Maybe another idea: can this error also be logged to the processwire logfiles? If yes, admins could check if the error happend also when some (not so into web tech) authors don't say something about the error to the admin.
