### ISSUE TITLE
RepeaterPage::setDepth() does not update depth property

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#867]
### Short description of the issue

When a page containing a Repeater field is saved the depth of repeater pages whose depth has changed is saved via `RepeaterPage::setDepth()`. The problem is that this method does not update the depth property of the repeater pages, and this means that the correct depth of the repeater pages is not accessible within hooks (e.g. `Pages::saveReady`) by using either `$repeater_page->depth` or `$repeater_page->getDepth()`.

### Steps to reproduce the issue

1. Change the depth of a repeater page within a Repeater field.
2. Save the page.
3. Note that attempts to get the depth of the item in a `saveReady()` hook return the wrong depth (they return the previous depth of the repeater page).

Example hook:

```php
$pages->addHookAfter('saveReady', function(HookEvent $event) {
    $page = $event->arguments(0);
    if($page->template != 'repeater_depth') return;
    foreach($page->repeater_depth as $repeater_page) {
        bd($repeater_page->depth, 'repeater_page->depth');
        bd($repeater_page->getDepth(), 'repeater_page->getDepth()');
    }
});
```

Screencast:

![repeater-depth](https://user-images.githubusercontent.com/1538852/57008819-e65ee500-6c46-11e9-8788-7c2bd0db6ddd.gif)

### Optional: Suggestion for a possible fix

Set the depth property within  `RepeaterPage::setDepth()`.

```php
public function setDepth($depth) {
    $name = $this->name;
    $_name = $name;
    $name = ltrim($name, '-');
    if($depth > 0) $name = str_repeat('-', $depth) . $name;
    if($name !== $_name) $this->name = $name;
    $this->depth = $depth; // this line added
}
```

Result:

![repeater-depth2](https://user-images.githubusercontent.com/1538852/57008884-579e9800-6c47-11e9-91e0-64494d646441.gif)

### Setup/Environment

* ProcessWire version: 3.0.130

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have added your suggested fix.
