### ISSUE TITLE
GET parameters are stripped off after login

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#868]
### Short description of the issue

If you send a direct link to a processmodule to one of your users, eg `/processwire/yourmodule/?action=foo&whatsoever=bar`, and the user is not logged in it will be taken to the login screen. That's fine, but after login the user will be taken to `processwire/yourmodule/?login=1`.

### Expected behavior

GET parameters should not be stripped after login.

### Actual behavior

At the moment this only works for the "id" get-parameter (eg when redirecting to a page-edit screen.

Or is this a security feature?

**Comment by Toutouwai** [comment]
> Or is this a security feature?

[Ryan has said](https://github.com/processwire/processwire-issues/issues/636#issuecomment-405946346):

"Query strings (GET variables) are a type of user input. ProcessWire does not pass non-validated user input directly into output, which would be an HTTP 301 redirect header in this case. This is a matter of security and is by design."

**Comment by BernhardBaumrock** [comment]
Thx @Toutouwai , interesting read - so I think it's best to make dedicated executeSomething() methods and only use the ?id=xxx parameter whenever a link should "directly" be accessible (meaning it should work after login).

But I just tested this with ProcessPageEdit (.../page/edit/?id=123&field=myfield) which is then also stripped off :( Not sure if that is the best solution. I admin, I haven't needed direct links in this format yet and I can't think of a situation where they would really be necessary.

I'll close this and bother Ryan with more important stuff and reopen it if it is really a problem. Thx again for the quick help @Toutouwai

**Comment by Toutouwai** [comment]
@BernhardBaumrock, here's a way you could store the query string and redirect to it after login:

```php
$wire->addHookAfter('ProcessLogin::execute', function(HookEvent $event) {
    $url_parts = parse_url($_SERVER['REQUEST_URI']);
    $session = $event->wire('session');
    // Remove any old query string that might be in session (e.g. from previous uncompleted login)
    $session->remove('query_string');
    if(isset($url_parts['query'])) {
        // Inspect $url_parts to make sure they are legit
        // If so save the query string to session
        $session->set('query_string', $url_parts['query']);
    }
});

$wire->addHookAfter('ProcessLogin::afterLoginURL', function(HookEvent $event) {
    $url = $event->return;
    $session = $event->wire('session');
    $query_string = $session->get('query_string');
    $session->remove('query_string');
    $event->return .= (strpos($url, '?') ? '&' : '?') . $query_string;
});
```
