### ISSUE TITLE
Fieldset creation issue when selecting existing fieldset

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#870]
### Short description of the issue

When adding a new fieldset field, if you select an existing fieldset in the "Type" dropdown (e.g. you want to use the same description or visibility as an existing fieldset) then the new fieldset is created without a FieldsetClose.

![2019-05-07_152449](https://user-images.githubusercontent.com/1538852/57269758-c44ce300-70dc-11e9-9af4-7fc3c6830447.png)

![2019-05-07_152821](https://user-images.githubusercontent.com/1538852/57269760-c747d380-70dc-11e9-8b4a-c4f01917532e.png)

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.
