### ISSUE TITLE
$sanitizer->names() does not strip multiple consecutive delimiters

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#871]
### Short description of the issue

`$sanitizer->names()` accepts multiple names in a string separated by a delimiter, the default for which is a space character.

But if multiple consecutive delimiters are (accidentally) included in the string then these consecutive delimiters are not fully removed from the result. My expectation was that multiple consecutive delimiters would be stripped so each sanitized name is separated by only a single delimiter.

![2019-05-08_144133](https://user-images.githubusercontent.com/1538852/57345602-98466600-719f-11e9-9551-72bb0726377a.png)

### Setup/Environment

* ProcessWire version: 3.0.130

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have pushed a fix for this.
