### ISSUE TITLE
InputfieldButton: invalid HTML5 (button element inside a link tag) when using `href` attribute

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#873]
### Short description of the issue

InputfieldButton elements are rendered with invalid HTML5 when used with `href` attribute:
(samples here: /processwire/setup/field/, /processwire/setup/languages/)

**This is the erroneous code:**

```html
<a class="InputfieldButtonLink" href="add/">
    <button class="ui-button ui-widget ui-corner-all ui-state-default" name="button" value="Add New" type="button">
        <span class="ui-button-text">Add New</span>
    </button>
</a>
```

According to the HTML5 specs (http://w3c.github.io/html/textlevel-semantics.html#the-a-element)

> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links).

### Suggestion for a possible fix

**Should be rendering like this if `href` attribute is used:**

```html
<a class="InputfieldButtonLink ui-button ui-widget ui-corner-all ui-state-default" href="add/">
    <span class="ui-button-text">Add New</span>
</a>
```

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
InputfieldButton needs to render an actual `<button>` element. I'm not worried whether it validates here, just that it works as intended across the browsers we support, and markup is clear about what it is doing. We could go with an onclick event, but I feel the current markup is preferable for now. Thanks.

**Comment by gadgetto** [comment]
I'm surprised you see it that way.
Why would we need an onclick event in case of an a tag?
A link is a link and the browser handles it exactly as it should be. If you wrap a button element with an a tag, then the button element becomes functionless/useless anyway.

Adding a role button would even tell assistive systems that this link is meant as a button...

```html
<a role="button" class="InputfieldButtonLink ui-button ui-widget ui-corner-all ui-state-default" href="add/">
    <span class="ui-button-text">Add New</span>
</a>
```

Or am I overlooking something?

@BernhardBaumrock @teppokoivula how do you see this?

**Comment by teppokoivula** [comment]
First and foremost it is, of course, up to Ryan to decide what's the best course of action here.

That being said, I don't know what reason we have to wrap a button in a link, but I would not expect that to keep working indefinitely – it's clearly non-standard markup, so even if it works now, it's not guaranteed to work in all browsers, or keep working in the long term.

While I agree with Ryan in that validation itself (as in getting a stamp of approval or something like that) is not important here, following standards is a good idea if you want to make things that work consistently and don't break randomly in the (near) future.

**Comment by gadgetto** [comment]
Yeah, of course. It is Brian's decision how this is handled. I'm just surprised, because ProcessWire pays a lot of attention to details normally.
