### ISSUE TITLE
Sort by email is not available within the admin for templates

### ISSUE THREAD

**Issue by postscript-chris** [processwire/processwire-issues#875]
As title

**Comment by adrianbj** [comment]
This is kinda related: https://github.com/processwire/processwire-issues/issues/397#issuecomment-336145394

**Comment by postscript-chris** [comment]
I have been building a lot of user systems lately where the users sit under a different parent. My way around this is to add the title field, update that after save and then sort by title but seems like an unnecessary step.

**Comment by ryancramerdesign** [comment]
@postscript-chris I don't understand, not enough here to go on here. Can you provide more info about where the sort-by-email is not available (page list, page lister, somewhere else?) and where you are looking to configure it?

**Comment by postscript-chris** [comment]
Hi @ryancramerdesign.

Sorry, bad issue report, just looked a the title again and it doesnt give enough info.

Template > Family > Sort settings for children > Children are sorted by

Let me know if you need any more info.

**Comment by ryancramerdesign** [comment]
@postscript-chris No problem, I understand what you mean now — I've pushed a fix for this. Thanks.

**Comment by netcarver** [comment]
@postscript-chris Closing this now as it's an old issue and is marked as fixed. If you need me to, just post here again and I'll reopen it. Thank you.
