### ISSUE TITLE
ImageInspector.php and ImageSizerEngine::checkOrientation exif issue

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-issues#878]
### Description of the issue
One of my clients is using Bugsnag integrated with ProcessWire to make sure that there are fewer runtime errors (I think this is more an indictment against me than anything!). A common error that keeps arising is `exif_read_data(image-name.400x200.png): File not supported`.

The stacktrace points to `ImageInspector::checkOrientation`, which attempts to read `exif` data from whatever image is passed. `phpinfo()` reveals that `exif` only has `Supported filetypes: JPEG, TIFF`.

According to this [stackoverflow](https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg), PNGs *can* store EXIF data, but looking at [PHP's source code for exif](https://github.com/php/php-src/blob/master/ext/exif/exif.c#L112), JPEG and TIFF support are currently hardcoded. /shrug

### Optional: Suggestion for a possible fix
As a result of the above, I put a lot of `checkOrientation()`'s meat inside an if statement:

```php
protected function checkOrientation($filename) {
    // first value is rotation-degree and second value is flip-mode: 0=NONE | 1=HORIZONTAL | 2=VERTICAL
    $corrections = array(
        '1' => array(0, 0),
        '2' => array(0, 1),
        '3' => array(180, 0),
        '4' => array(0, 2),
        '5' => array(270, 1),
        '6' => array(270, 0),
        '7' => array(90, 1),
        '8' => array(90, 0)
    );
    
    $result = array('orientation' => 0, 'rotate' => 0, 'flip' => 0);
    $supportedExifMimeTypes = array('image/jpeg', 'image/tiff'); // hardcoded by PHP

    if(in_array($this->info['mime'], $supportedExifMimeTypes)) {
        if(!function_exists('exif_read_data')) return $result;
        $exif = @exif_read_data($filename, 'IFD0');
        if(!is_array($exif)
            || !isset($exif['Orientation'])
            || !in_array(strval($exif['Orientation']), array_keys($corrections))
        ) {
            return $result;
        }

        $correctionArray = $corrections[strval($exif['Orientation'])];

        $result = array(
            'orientation' => $exif['Orientation'],
            'rotate' => $correctionArray[0],
            'flip' => $correctionArray[1]
        );
    }

    return $result;
}
```

(paging @horst-n)

I believe the above code will fix the issue.

**Comment by horst-n** [comment]
@ethanbeyer Many thanks for the fix!
Only thing, due to personal preferences for flat coding style, I would like to check if it is "not" in array and do an early return then:
```	$result = array('orientation' => 0, 'rotate' => 0, 'flip' => 0);
	$supportedExifMimeTypes = array('image/jpeg', 'image/tiff'); // hardcoded by PHP
	if(!function_exists('exif_read_data') || !in_array($this->info['mime'], $supportedExifMimeTypes)) {
		return $result;
	}
```
@ryancramerdesign The above fix from Ethan must go into the ImageInspectors method checkOrientation().

**Comment by ethanbeyer** [comment]
Ah, well said @horst-n. I like that better, too - here's the rewrite of that function for easy copy-pastability for @ryancramerdesign:

```php
protected function checkOrientation($filename) {
    // first value is rotation-degree and second value is flip-mode: 0=NONE | 1=HORIZONTAL | 2=VERTICAL
    $corrections = array(
        '1' => array(0, 0),
        '2' => array(0, 1),
        '3' => array(180, 0),
        '4' => array(0, 2),
        '5' => array(270, 1),
        '6' => array(270, 0),
        '7' => array(90, 1),
        '8' => array(90, 0)
    );
    
    $result = array('orientation' => 0, 'rotate' => 0, 'flip' => 0);
    $supportedExifMimeTypes = array('image/jpeg', 'image/tiff'); // hardcoded by PHP
    
    if(!function_exists('exif_read_data') || !in_array($this->info['mime'], $supportedExifMimeTypes)) return $result;
    
    $exif = @exif_read_data($filename, 'IFD0');
    if(!is_array($exif)
        || !isset($exif['Orientation'])
        || !in_array(strval($exif['Orientation']), array_keys($corrections))
    ) {
        return $result;
    }

    $correctionArray = $corrections[strval($exif['Orientation'])];

    $result = array(
        'orientation' => $exif['Orientation'],
        'rotate' => $correctionArray[0],
        'flip' => $correctionArray[1]
    );

    return $result;
}
```

Does this look good to you, @horst-n?

**Comment by horst-n** [comment]
Only the "if(!function_exists('exif_read_data')" is double now.

**Comment by ethanbeyer** [comment]
Ah, good catch. I need some coffee! I've edited out the redundant one.

**Comment by ryancramerdesign** [comment]
Thanks @ethanbeyer and @horst-n I've committed your suggested fix.

**Comment by ethanbeyer** [comment]
Thanks @ryancramerdesign !
