### ISSUE TITLE
ProFields Table module - Error with Checkbox field when add new row

### ISSUE THREAD

**Issue by maSSaDev** [processwire/processwire-issues#879]
### Short description of the issue

ProFields Table field with row containing Checkbox fieldtype procedure error when trying to save page in admin mode. An error occurs when you add a new table row with a checkbox and do not specify a value for it and try to save the page. After error all table rows in the current page are also deleted.

There is no error when site running in server with database version 5.5.60-MariaDB-cll-lve but after moving site to another server with newer database server 10.2.23-MariaDB-cll-lve it appeared.

### Actual behavior

<strong>Errors</strong>
```
Session: Error saving field "tablefield" - SQLSTATE[01000]: Warning: 1265 Data truncated for column 'checkboxfield' at row 1
Session: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'checkboxfield' at row 1
```

### Suggestion for a possible fix

I found that if i add default='NULL' value to checkbox colType in the file FieldtypeTable.module error disappears. 

<strong>Original FieldtypeTable.module (rows 255-262)</strong>
```
'checkbox' => array(
	'type' => "enum('0','1')",
	'label' => 'Checkbox',
	'input' => 'checkbox',
	'valid' => 'int',
	'settings' => $settings['select'],
	),
```
<strong>Fixed version</strong>
```
'checkbox' => array(
	'type' => "enum('0','1')",
	'label' => 'Checkbox',
	'input' => 'checkbox',
	'valid' => 'int',
	'default' => 'NULL', // Added row
	'settings' => $settings['select'],
	),
```

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.131|
|PHP|7.2.17|
|Webserver|Apache|
|MySQL|10.2.23-MariaDB-cll-lve|

|Module ClassName|Version|
|------:|:-------|
|FieldtypeTable|0.1.9|
|InputfieldTable|0.1.9|

**Comment by adrianbj** [comment]
FYI - this was also reported here: https://processwire.com/talk/topic/22114-critical-error-saving-field-with-unchecked-checkbox/

**Comment by matjazpotocnik** [comment]
@maSSaDev is this still an issue?

**Comment by ryancramerdesign** [comment]
Thanks @maSSaDev This one was fixed awhile back on Table fields (default null) so I'll close it.
