### ISSUE TITLE
Can't set comment status via API

### ISSUE THREAD

**Issue by CanRau** [processwire/processwire-issues#88]
### Short description of the issue

Merging issue from https://github.com/ryancramerdesign/ProcessWire/issues/1034

Original issue description:

https://processwire.com/talk/topic/9181-set-comment-status/

I have been having the same trouble - the moderation settings override what you try to set.

From the linked forum topic to clarify the issue:
"I'm trying to set a comment status when posting new comment via API but pw set to 1 even I set to -2 or 0"

### Expected behavior

To be able to set comment status via API

### Actual behavior

The module is overriding the status on its own.

### Setup/Environment

* ProcessWire version: 3.0.39

**Comment by ryancramerdesign** [comment]
There's a lot involved with managing comment status in this Fieldtype, and likewise a lot of things that get triggered when the status changes. Things like hooks, emails, connections to Akismet, etc. For this reason, I would avoid manual changes to status like this, and instead go straight to the DB to be able to make the change silently, if possible. But if you don't want to do that, I'd need some more context of specifically where you are setting/changing the status, whether it's to an existing or new comment, and how you are saving the page. Assuming you are talking about a change to an existing comment, chances are it's a matter of change tracking and PW not seeing the change.

**Comment by CanRau** [comment]
I just stumbled across this issue checking out comment field api posts and thought it might be good to copy it to the new issue tracker..
to ensure it's still happening I just put this at the top of my site/ready.php
    
    $c = new Comment();
    $c->text = 'comment';
    $c->status = 1;
    $c->email = 'mail@mail.com';
    $c->cite = 'author';

    $p = $pages->get(1211);
    $p->setAndSave('comments', $p->comments->add($c));

comment status will be pending even though I set it to 1

changing existing comments seems to work
after I ran the above I tried the following

    $p = $pages->get(1211);
    $p->comments->first()->status = 1;
    $p->save('comments');

which worked as expected, even changed the status back and forth, trying statuses -2, 0 and 1

I think I can live with this behaviour, chaning the status after first save, or by altering the db table..

**Comment by ryancramerdesign** [comment]
That sounds consistent with how it's built too. When it detects a new comment, it goes through the status rules, whereas existing comments do not. Though existing comments go through a different set or rules, primarily related to changes in spam status.

One thing you could do would be just to turn off the moderation settings when you don't want them, as is the case in your API usage.
~~~~~
$field = $fields->get('comments');
$field->set('moderate', FieldtypeComments::moderateNone);
~~~~~
When moderate is set to none like that, new comments are automatically approved. Meaning, you don't even need to set the status on the API side.

**Comment by CanRau** [comment]
Okay great :)
