### ISSUE TITLE
InputfieldFile: no space between Description and Tags inputs

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#880]
### Short description of the issue

In InputfieldImage there is some space between the Description and Tags inputs, but in InputfieldFile this space is missing.

![2019-05-16_145105](https://user-images.githubusercontent.com/1538852/57823066-56926c80-77ea-11e9-9fad-f8667a157bb3.png)

Also, IMHO it would look better and more consistent with the other inputs if the inner shadow on the Tags input was removed.

![2019-05-16_145449](https://user-images.githubusercontent.com/1538852/57823144-93f6fa00-77ea-11e9-925f-6ee87e459532.png)

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
