### ISSUE TITLE
Empty ModuleConfig values when module is singular

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#881]
### Short description of the issue

Module settings are not accessible when module is set to "singular".

### Expected behavior

Module settings should be accessible via `$modules->get('yourmodule')->mysetting` just like with non-singular modules.

### Actual behavior

Settings are only accessible via `$modules->getConfig('yourmodule')['yourfield']`.

### Steps to reproduce the issue

When I'm saying "check the value" I mean checking the value in the console, not in the module's config screen. The value gets saved in the config screen but is not accessible in the console (or any method in the module)!

1. Install the SingularIssue module: https://github.com/BernhardBaumrock/SingularIssue
1. Save demo settings value `demo`.
1. Check the value in the console, it will be NULL.
![img](https://i.imgur.com/rpARTeY.png)

1. Change module to `singular => false`.
1. Do a modules refresh.
1. Check the value, it will be `demo`.
1. Change module to `singular => true`.
1. Do a modules refresh.
1. Check the value, it will be `demo`.
1. Change the module settings, set demo to `demo2`.
1. Check the value, it will be `null`
![img](https://i.imgur.com/uxkXazs.png)

This works:
![img](https://i.imgur.com/picHOeK.png)

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock Before we look further, I can see that your test module is not setting default values. Setting default values is required for a module, even if the default value is a blank string. So you'd either want to add a __construct() that sets your default values, or update your config to include a 'value' index in the field(s) you are defining. See [here](https://github.com/ryancramerdesign/Helloworld/blob/master/Helloworld.config.php) for an example. If you find the issue remains after doing that (and refreshing modules) please let me know. Thanks.

**Comment by BernhardBaumrock** [comment]
Hi Ryan,

thx for that hint. I've tried adding a default value (https://github.com/BernhardBaumrock/SingularIssue/commit/a5927de7bb7383abf355f53059c751e980cd091f) but it does not change anything...

1) Install my demo module
2) Do NOT save the module config
3) Check the value of `demo` config setting:
```
d($modules->get('SingularIssue')->demo);
```
![img](https://i.imgur.com/gyASJ9f.png)

4) Change module info to "singular=false"

![img](https://i.imgur.com/PzQOcEj.png)
