### ISSUE TITLE
nested pw-optional markup region is not removed

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#883]
### Short description of the issue

When considering the example in the blog post: https://processwire.com/blog/posts/processwire-3.0.117-core-updates/ where _pw-optional_ was introduced, let's try to extend it by nesting _pw-optional_ regions like this:

```
<div id='sidebar' class='uk-width-1-3' pw-optional>
    <div id='widget1' pw-optional class="some defaults"></div>
    <div id='widget2' pw-optional class="some defaults"></div>
</div>
```
The issue is: the attributes of nested _pw-optional_ are not removed from the markup.

### Expected behavior

I need nested _pw-optional_ regions to be removed from the markup because I am trying to implement a _main.php file in which all of the possible "html blocks" supported by the "frontend theme" are defined along with their default classes.

Example of injecting markup into an optional widget:
`<div id="widget1" pw-prepend> <h3>My Cool Widget</h3> </div>`

The result is:
```
<div id='sidebar' class='uk-width-1-3' pw-optional>
    <div id='widget1' pw-optional class="some defaults">
        <h3>My Cool Widget</h3>
    </div>
    <div id='widget2' pw-optional class="some defaults"></div>
</div>
```

By being able to use predefined default classes, one could make sure that – for example – each sidebar widget gets the classes "some defaults".

### What also not works

When nesting _pw-optional_ regions and none of the regions is populated (sticking to the example: not even the sidebar) then all the markup is kept, only the outermost _pw-optional_ is removed but nothing else.

### Setup/Environment
ProcessWire: 3.0.131
PHP: 7.1.29

**Comment by ryancramerdesign** [comment]
@szabeszg I've gone ahead and added supported for nested pw-optional regions. Not sure my test cases are the same as ours, so please let me know if you find anything doesn't work. Thanks.

**Comment by szabeszg** [comment]
Thank you @ryancramerdesign Works great, my comments are over [here](https://github.com/processwire/processwire-issues/issues/984#issuecomment-537511173) at #984.
