### ISSUE TITLE
WireHttp sendCURL $this->headers is an associative array but curl_setopt needs array with header lines

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#884]
### Short description of the issue

In `sendCURL` method of `WireHttp` class the property `$this->headers` is an associative array but `curl_setopt` needs an array with header lines instead.

https://github.com/processwire/processwire/blob/f1d5f128354002d0ed796a9e1cb4f6559c2dcf1b/wire/core/WireHttp.php#L612

Therefore the http headers are not set correctly.

### Expected behavior

**This is a sample on how `curl_setopt` would await `$this->headers`:**

```php
array(
    "charset: utf-8",
    "cache-control: no-cache",
    "accept: application/json",
    "user-agent: ProcessWire/3.0 (SnipREST)",
)
```

### Actual behavior

This is a sample of `$this->headers` is currently set to `curl_setopt`:

```php
array(
    "charset" => "utf-8",
    "cache-control" => "no-cache",
    "accept" => "application/json",
    "user-agent" => "ProcessWire/3.0 (SnipREST)",
)
```

### Optional: Suggestion for a possible fix

```php
// cURL needs headers as array of header lines!
$headerlines = array();
foreach ($this->headers as $key => $value) {
    $headerlines[] = "$key: $value";
}
curl_setopt($curl, CURLOPT_HTTPHEADER, $headerlines);
```

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
Thanks @gadgetto I've pushed your suggested fix for this issue.

**Comment by gadgetto** [comment]
Great!
