### ISSUE TITLE
AdminThemeUikit: AsmSelect has 'uk-form-small' class while regular Select does not

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#886]
ASMSelect dropdowns have ```uk-form-small``` but regulars selects do not.  As a result, ASMSelect dropdowns have a smaller style.  While this is not a bug and probably deliberate, it does look 'off' when you have an ASMSelect and regular Select side-by-side.  Should ```uk-form-small``` be removed?

Screenshot example:
![x](https://user-images.githubusercontent.com/4558/58110652-d03ca880-7ba4-11e9-9001-0f25872caf56.png)

**Comment by Toutouwai** [comment]
This has been raised before and Ryan responded: https://github.com/processwire/processwire-issues/issues/564#issuecomment-384981906

> Regarding asmSelect, that's also intentional that those always use the small selects. The asmSelect isn't just a select, but a closely connected list of items — the select and the items it selects are supposed to be close in visual height, and the small option does that. Anything bigger breaks the visual connection. I understand that when no options are selected, it just looks like a smaller select, but decided it was important for this case.
