### ISSUE TITLE
remove text-transform: capitalize from buttons

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#887]
Right now multiple words on buttons are being capitalized which is wrong, at least in german, but I think it's also wrong in other languages.
Take this button for example (from ProcessLogger module):
![image](https://user-images.githubusercontent.com/551551/58334561-19f4ef80-7e40-11e9-91cc-7ce45f8496c2.png)
![image](https://user-images.githubusercontent.com/551551/58334690-650f0280-7e40-11e9-9ca4-55e48b1d321a.png)

Correctly it would look like this 
![image](https://user-images.githubusercontent.com/551551/58334597-2da05600-7e40-11e9-9912-cd8c69e071a6.png)
![image](https://user-images.githubusercontent.com/551551/58334741-78ba6900-7e40-11e9-8b5f-801510299c14.png)

**Comment by Toutouwai** [comment]
Related: https://github.com/processwire/processwire-requests/issues/152

**Comment by teppokoivula** [comment]
+1. This applies to Finnish as well, as explained by author J. Korpela:

> Capitalizing almost every word in a title of a work, which is common in English (e.g., “On the Origin of Species”), is definitely incorrect in Finnish. Capitalizing words for emphasis, as in ”Very Important” (Hyvin Tärkeää) is not normal in Finnish and may make a very childish impression.

**Comment by jmartsch** [comment]
Please? Just a little reminder for you consideration.

**Comment by BernhardBaumrock** [comment]
You could create a quickfix for it :) 
https://processwire.com/talk/topic/22710-pwquickfixes/

**Comment by ryancramerdesign** [comment]
Thanks @jmartsch I've pushed a fix for this issue. Now the capitalize rule only applies when `html[lang=en]`. The `en` attribute value is translatable from /wire/templates-admin/default.php
