### ISSUE TITLE
CKEditor Custom config options

### ISSUE THREAD

**Issue by neonwired** [processwire/processwire-issues#888]
When using custom config options for CKEditor any disallowedContent rules that have { or } seems to be processed as JSON and result in 'Custom Config Options failed JSON validation.' error.

### Expected behavior
Rules such as `disallowedContent = '*{font*}';` example from the CKEditor docs should be valid

### Actual behavior

Results in 'Custom Config Options failed JSON validation.'

* ProcessWire version: 3.0.123
* (Optional) PHP version: 7.3

**Comment by Toutouwai** [comment]
That's not the correct format for options entered into the "Custom Config Options" field.

![2019-05-26_110231](https://user-images.githubusercontent.com/1538852/58375387-d0beb000-7fa5-11e9-8b19-5c246a0fee8f.png)

The correct format for that would be:
```
"disallowedContent": "*{font*}"
```

**Comment by netcarver** [comment]
@neonwired Does the above comment fix this for you? Can this issue be closed?

**Comment by netcarver** [comment]
@neonwired I'm closing this now. Please post again if this needs re-opening.
