### ISSUE TITLE
Inputfield dependencies: JS and server-side evaluation not consistent for "not equals"

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#889]
### Short description of the issue

As you'll see I struggled to think of a good scenario to illustrate this issue but the point remains.

I have two fields (text fields for the sake of simplicity): "animal" and "number_of_legs".

I want the number_of_legs field to be required when the animal is not a snail, so my required-if condition for number_of_legs is `animal!=snail`. This works well - so far so good:

![dep1](https://user-images.githubusercontent.com/1538852/58388280-ff558d00-8070-11e9-9ac4-2f1cbda9565b.gif)

But then I decide to change the required-if condition for number_of_legs to `animal!=snail|snake`. The interpretation of this is expected to be "the number_of_legs field is required if the animal is not a snail AND the animal is is not a snake". Put another way, "the number_of_legs field is NOT required if the animal is a snail OR the animal is a snake". In support of this interpretation (if any is needed), imagine if this was a $pages->find() selector string: `animal!=snail|snake` would match pages where animal is NOT a snail OR a snake.

Now the inputfield dependency issue becomes noticeable. If the value of animal is "snail" the JS evaluation is that number_of_legs is required - see the screenshot below with inputfield dependency debugging enabled:

![2019-05-27_113913](https://user-images.githubusercontent.com/1538852/58388534-50b34b80-8074-11e9-8287-f6ca26fa856c.png)

This is wrong, and seems to be the result of a logic error involving the "not equals" operator in conjunction with the piped OR conditions. In contrast to the expectation stated above, the JS evaluation seems to treat the dependency as "the number_of_legs field is required if the animal is not a snail OR the animal is is not a snake", which will always evaluate to TRUE because the fail condition would be "the animal is both a snail and a snake" which is impossible.

But as shown in the following screencast, the server-side evaluation of the required-if condition is correct. So the JS evalation indicates that the field is required, but the server-side evaluation is that the field is not required.

![dep2](https://user-images.githubusercontent.com/1538852/58388556-9c65f500-8074-11e9-9092-3e0a2300b278.gif)

Meaning the inputfield dependency is inconsistent between JS and server-side evaluation, with the server-side evaluation being the correct one.

I expect this issue also affects show-if dependencies, but the issue might be obscured or complicated there because although the language around this option is "**show** the inputfield if..." the actual JS behavior is "**hide** this inputfield if..."

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by Toutouwai** [comment]
A possible fix...

Change line 422 of inputfields.js to:
```js
if(matched >= numMatchesRequired) {
```

Although I must admit that I haven't got my head around what is happening with the comparison of `requiredMatches` to `notRequiredMatches`.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed your suggested fix for this. I worked through the logic and came to the same conclusion that it should use the same condition as the showIf, and I'm not sure why it didn't before. Just in case I've missed something, I'll be keeping an eye on it, and likewise please let me know if you find it breaks anything. Thanks.
