### ISSUE TITLE
Inputfield dependencies: field data not saved

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#890]
### Short description of the issue

For this demonstration I have three text fields: department, position, supervisor

The position field has a show-if condition: `department=sales` - the field is only shown if the value of the department field is sales.

The supervisor field has a show-if condition: `position!=manager` - the field is only shown if the value of the position field is not manager.

This setup complies with the [documentation](https://processwire.com/docs/fields/dependencies/) for inputfield dependencies as far as I can see, but the problem is that if the value of the department field is not sales then the value of the supervisor field cannot be saved.

![dep3](https://user-images.githubusercontent.com/1538852/58393389-a0a10b00-8092-11e9-892f-9fe24c61c6bb.gif)

In the screencast above, in both cases (department=distribution and department=sales) the position is not manager so the supervisor field is shown as expected. But when the position field is hidden it seems that the visibility dependency of the supervisor field on the position field causes the save problem.

I understand from the discussion in issue #140 that when a inputfield is hidden its data is deliberately not processed when the containing form is submitted - that makes sense to me. But could something be added here to allow for "not equals" conditions? Because if the value of hidden inputfield foo is effectively "null"/"not present"/"excluded" then it seems like the condition `foo!=bar` should still evaluate to true. Using a "not equals" condition in an inputfield dependency can be quite useful for getting around the limitations for the selector string (e.g. no support for or-groups) so it would be great if setups like the one described in this issue could work.

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue.

**Comment by Toutouwai** [comment]
Thanks
