### ISSUE TITLE
Webp when images field has jpg and png with the same name

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#891]
### Short description of the issue

If you have two or more images in an images field (or in different image fields on the same page) with the same name, eg image.png and image.jpg it's not possible for PW to create and serve the webp version for more than the first image. This might seem like an unlikely scenario, but with my Custom Upload Names module it is extremely common. Regardless of this module, I still think it's a scenario that needs to be handled.

I haven't done much research into webp, so I don't claim to know the best solution, but what about serving them as image.jpg.webp and image.png.webp?

Not saying this is the right way either, but Wordpress seems to serve webp images with the original extension, eg:

![image](https://user-images.githubusercontent.com/871211/58426456-619e9580-8051-11e9-991e-301149553622.png)

That screenshot is from: https://community.centminmod.com/threads/installing-webp-express-wordpress-plugin-on-centmin-mod-nginx.17469/

I am sure there's a good approach that will appear with a little brainstorming.

**Comment by Toutouwai** [comment]
> Not saying this is the right way either, but Wordpress seems to serve webp images with the original extension

That has been discussed a bit in the forum thread: https://processwire.com/talk/topic/14236-webp-support/?do=findComment&comment=184741

Personally I'm not keen on this because arguably it means serving up bad data: file data in one format with the file extension of a different format. If a visitor saves an image they confusingly get WEBP data that looks like a JPG/PNG file, and it becomes a non-trivial job for them to work out what is going on.

I like the solution of image.jpg.webp / image.png.webp though.

**Comment by adrianbj** [comment]
Agreed @Toutouwai that the WP solution is not great - not really sure why I mentioned it other than to maybe indicate that it seems there isn't a standard approach out there yet - all seems a bit messy really!

**Comment by szabeszg** [comment]
> This might seem like an unlikely scenario,

I have a site where I impemented a custom workflow which begins with uploading a high resolution PNG and upon upload PW creates a JPG variation of it as the bases for rendering smaller JPG variations of the image for the frontend. So the high resolution PNG and JPG files are named the same except for the extensions, of course.

> I like the solution of image.jpg.webp / image.png.webp though.

+1 for this. I also do something similar for PDF compatible AI files, depending on the context either file.pdf.ai or file.ai.pdf, for example.

**Comment by teppokoivula** [comment]
+1 for image.[original-ext].webp. I can't really see much harm in this, but it could resolve a number of potential issues.

**Comment by ryancramerdesign** [comment]
I will add support for an option next week that lets you use the longer filenames for cases where people want that.

**Comment by ryancramerdesign** [comment]
Added this one a few months ago, but just to follow up, you can specify the option in `$config->webpOptions('useSrcExt', true);`
~~~~~
$config->webpOptions = array(
	'quality' => 90, // Quality setting of 1-100 where higher is better but bigger
	'useSrcExt' => false, // Use source file extension in webp filename? (file.jpg.webp rather than file.webp)
	'useSrcUrlOnSize' => true, // Fallback to source file URL when webp file is larger than source?
	'useSrcUrlOnFail' => true, // Fallback to source file URL when webp file fails for some reason?
);
~~~~~

**Comment by adrianbj** [comment]
Thanks Ryan!
