### ISSUE TITLE
Inputfield dependencies: required-if not enforced

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#892]
### Short description of the issue

In this demonstration I have three text fields: pet_name, pet_species, registration_number

The pet_species field has a required-if condition `pet_name!=''`

The registration_number field has a show-if condition `pet_species!=fish` and a required-if condition `pet_species!=fish`.

The issue is that in the screencast below the required status is indicated on the registration_number field (JS evaluation works) but it is not enforced when the form is submitted (server-side evaluation not working).

![dep4](https://user-images.githubusercontent.com/1538852/58442452-8bce8100-813f-11e9-81f5-cdbd71cefa1c.gif)

If the show-if condition is removed from the registration_number field then the required-if condition starts working.

![dep5](https://user-images.githubusercontent.com/1538852/58442546-39da2b00-8140-11e9-9b2f-af7c7064e8a6.gif)

Update: alternatively, if the show-if condition remains for the registration_number field but the required-if condition is removed from the pet_species field then the registration_number required-if condition starts working (same effect as screencast above).

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue

**Comment by Toutouwai** [comment]
Thanks
