### ISSUE TITLE
Remove process-logs from modules directory

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#893]
As the log viewer is a core functionality, this module isn't needed anymore, so I think it could be removed safely.
https://modules.processwire.com/modules/process-logs/

**Comment by teppokoivula** [comment]
I must disagree: ProcessLogger was added in 2.5.15, while Process Logs provides similar features for versions 2.1 .. 2.5. And yes, people do still use old versions of ProcessWire :)
