### ISSUE TITLE
Classes added to InputfieldPage are not transferred to InputfieldPageAutocomplete

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#897]
### Short description of the issue

The [addClass()](https://github.com/processwire/processwire/blob/ad2f60b5445d2449920227f96f7ba1ab49777ece/wire/modules/Inputfield/InputfieldPage/InputfieldPage.module#L144-L157) method of InputfieldPage adds classes to the classesAdded property, and the PhpDoc for classesAdded says:

```php
/**
 * CSS class names added to the Inputfield (will be applied to delegate Inputfield)
 * 
 * @var array
 * 
 */
```

The added classes are applied to the delegate inputfield for all inputfield types apart from InputfieldPageAutocomplete.

### Expected behavior

Classes are added to hidden input within rendered InputfieldPageAutocomplete.

### Setup/Environment

* ProcessWire version: 3.0.131

**Comment by Toutouwai** [comment]
Possible fix, added [here](wire/modules/Inputfield/InputfieldPageAutocomplete/InputfieldPageAutocomplete.module):

```php
$inputClass = $this->wire('sanitizer')->entities($this->attr('class'));
$out .= <<< _OUT

<p>
<input type='hidden' name='{$this->name}[]' id='$id' class='InputfieldPageAutocompleteData $inputClass' value='$value' $attrs/>
// ...
```

**Comment by ryancramerdesign** [comment]
@Toutouwai When it comes to the autocomplete, it's kind of ambiguous as to where those classes should be added. You are adding them to the hidden input, but I think people would assume they'd go on the input element. But of course the input element and the value are different things in this case by necessity, so it's like a different animal than the other input types. My opinion is that it's better to leave them off for this particular case and instead rely on a wrapClass, or either one of the input's id attributes. But if you can think of a useful case for why they would be added to the hidden input, I'd be happy to get a closer look and add them if it doesn't seem like it'll cause any problematic side effects.

**Comment by Toutouwai** [comment]
This is mostly about consistency. I have a module that does some Javascript work on inputfields and I want to support all the core inputfields. The class I am adding is for identifying which inputfields have the module activated for them, so they can be targeted in the JS. For my purposes I want to target the actual inputs that send data when a form is submitted, so a wrap class is less good because then I have to deal with the fact that some inputfield types have multiple inputs within them (e.g. checkboxes).

InputfieldPageAutocomplete is the only "odd man out" in the suite of core inputfields so it would be great if you could make a change so that classes can be added to the input element the same as with other inputfields.

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I have updated it to populate the class in that attribute per your suggestion.

**Comment by Toutouwai** [comment]
Thanks
