### ISSUE TITLE
Modal window moves up when closing messages (error/warning/message)

### ISSUE THREAD

**Issue by Da-Fecto** [processwire/processwire-issues#9]
Modal window moves up when closing (error/warning/message) messages in modal. The modal close button becomes unreachable.

* ProcessWire version: 3.034 and down
* behaviour in Chrome, other browsers not tested.

**Comment by ryancramerdesign** [comment]
Do you have the SystemNotifications module installed? Just wanted to double check what the source of the error/warning/message notifications was.

**Comment by Da-Fecto** [comment]
Nope just plain install, source of the messages coming from session... $this->message, no fancy HTML  in it.

**Comment by isellsoap** [comment]
I can reproduce this issue in certain circumstances. It happens for example, if you try to remove error/warning messages of modals on a small viewport.

I created a tiny video showing the bug in action: [modal-bug.zip](https://github.com/processwire/processwire-issues/files/504347/modal-bug.zip)

**Comment by Da-Fecto** [comment]
Issue also on huge display, viewport size doesn't matter over here.

**Comment by rolandtoth** [comment]
I'm afraid this is a Chrome bug (still):
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/c-aQefxk7b0
http://jsfiddle.net/nCA52/

**Comment by isellsoap** [comment]
@Da-Fecto @rolandtoth So should this be issue closed? If it’s a Chrome bug @ryancramerdesign can do nothing to fix this on ProcessWire’s side.

**Comment by rolandtoth** [comment]
If it's that Chrome bug than it should be tested in Firefox to ensure that it doesn't appear there (so it's only happening in Chrome). Unfortunately I couldn't reproduce the way I could earlier.

**Comment by Da-Fecto** [comment]
It's a bug that bugs PW for a while, but I didn't mention it earlier just because of time pressure and had forgotten it after a awhile. For me it's to easy to say, let's close this issue because of a potential Chrome bug. Whole web-development is based on work-arounds and hacks so if there is a solution, like re-initializing the modal after closing messages I will be more then happy.

So for now I leave the issue open.

**Comment by rolandtoth** [comment]
Is there an anchor (or only "#") in the iframe url after clicking on the close button? If yes, simply avoiding that could fix it (using return false in Js).

**Comment by ryancramerdesign** [comment]
There may be a bug in Chrome, but I found the same as @rolandtoth here that doing a return false; seems to fix it on this side at least. Just pushed a commit for that.
