### ISSUE TITLE
Should $sanitizer->filename convert filename to lowercase?

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#90]
### Short description of the issue

I don't think this sanitizer option is currently being used in the core for filename conversion, but its name suggests that it would be the best way to convert a filename. Maybe this is meant for something else entirely?

### Expected behavior

I would expect it would convert the filename to lowercase

### Actual behavior

Filenames don't have their case changed

**Comment by mikerockett** [comment]
What about Linux, which is case-sensitive?

**Comment by adrianbj** [comment]
Hi @mikerockett - my question is not really about whether PW should be lowercasing filenames or not (although I do think it should, which it does), but why this sanitizer method doesn't do it. Maybe it's not meant to, even with the $beautify option set to true. It says it's a "Name filter for ProcessWire filenames", but it won't actually match a filename processed by PW when a file is uploaded.

Again, maybe I am not understanding this method's purpose properly?

**Comment by teppokoivula** [comment]
> [...] my question is not really about whether PW should be lowercasing filenames or not (although I do think it should, which it does), but why this sanitizer method doesn't do it.

While I strongly disagree with your point about lowercasing filenames (and the sanitizing process as it is now), I do agree that this filter should be in line with what the system itself does. Is there a notable chance that someone is relying on current behaviour, thus making this a breaking change?

**Comment by ryancramerdesign** [comment]
The Pagefile/Pagefiles classes use lowercase filenames, but that's it. The filename() sanitizer is not specific to those classes, instead it's provided as a system-wide filename sanitizer. It sanitizes for ProcessWire's name format, which is alphanumeric (any case), hyphen and underscore. If lowercase is needed in a particular scenario, you'd want to run a strtolower() in addition to the sanitizer.

**Comment by adrianbj** [comment]
Thanks for the explanation. I guess I thought the filename sanitizer should match PW's default behavior in the Pagefile/Pagefiles classes. I am curious what purpose this sanitizer has if it doesn't match PW default filename sanitizing?

I am aware of the difference between pageName and name - I use pageName regularly and in fact I normally use pageName for filename matching because it gets lowercased. I guess I don't see the point in having "filename" as an alias of "name" in terms on functionality.
