### ISSUE TITLE
PageTable items are hardly clickable when 1st field is a checkbox

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#901]
### Short description of the issue

Context :
PageTable items are clickable (hence editable) via a link set on the 1st field.
When 1st field is a checkbox, the link is encompassing the html checkbox element.

Problem : 
The markup sets this checkbox as inactive (for good reasons), and as a result, the encompassing link can't be clicked
(at least, this is the behavior observed on Chrome on Windows).
There's just a few "blank" pixels below the checkbox which can actually be clicked.

### Expected behavior

It should not require special clicking skills to edit a PageTable item, when 1st field is a checkbox :-)

### Optional: Suggestion for a possible fix

Several fix possibilities to the markup can be envisioned, nothing complicated.

### Setup/Environment

ProcessWire version: 3.0.127
Chrome on Windows.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign it's really annoying and frustrating that you can't click on page table item as there is no link to click if the first item is "classic" checkbox.

![image](https://github.com/processwire/processwire-issues/assets/7663992/2ac3503a-2e0d-48d6-b0bf-87d0f0f3a2f1)

**Comment by matjazpotocnik** [comment]
So, I played with this:

Option 1 would be to check for the `<input ` tag and that would force an extra edit link as the first element. In InputfieldPageTable.module, in renderTableCol(), I replaced:

```php
if(stripos($out, '<a ') !== false || stripos($out, '<li') !== false !== false || !strlen($out)) {
```
with:

```php
if(stripos($out, '<a ') !== false || stripos($out, '<li') !== false || stripos($out, '<input ') !== false || !strlen($out)) {
```
and got this:


![image](https://github.com/processwire/processwire-issues/assets/7663992/efbe597a-0c8c-4e27-8b1f-443fb723c80b)

Option 2 would be to add an icon that is clickable:

```php
if(stripos($out, '<ixnput ') !== false && stripos($out, 'checkbox') !== false ) {
  // <input type='checkbox'>
  $c = (stripos($out, 'disabled') !== false) ? wireIconMarkup('check-square-o') : wireIconMarkup('square-o');
  $out = $this->renderItemLink($item, $c, $linkURL);
} else if(stripos($out, '<a ') !== false || stripos($out, '<li') !== false !== false || !strlen($out)) {
```

![image](https://github.com/processwire/processwire-issues/assets/7663992/3da22715-fd04-47d1-8ce9-bc3a91e5a7fd)

**Comment by ryancramerdesign** [comment]
@matjazpotocnik @er314 Thanks, I've pushed a fix for this issue, but it needs confirmation.

@matjazpotocnik Thanks for the suggestions. I used something similar to your option 2 except did it at a lower level (FieldtypeCheckbox.module) so that it would apply in other usages as well.

**Comment by matjazpotocnik** [comment]
Ryan, it's working here.

**Comment by ryancramerdesign** [comment]
Great, thanks for testing.

**Comment by er314** [comment]
thanks all
