### ISSUE TITLE
TFA breaks direct admin links

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#902]
### Short description of the issue

If you give someone a link to something like: http://pwtest.test/processwire/page/edit/?id=1030 after login (incl 2FA) you end up at: http://pwtest.test/processwire/page/edit/bookmarks/

### Expected behavior

After login you should be redirected back to the original address like with a regular login. 

If there's a security or other concern, I think it should at least redirect to: http://pwtest.test/processwire rather than the /edit/bookmarks link which is just confusing.

**Comment by ryancramerdesign** [comment]
Thanks Adrian, I've pushed a fix for this.

**Comment by adrianbj** [comment]
Nice - I like the approach of properly handling and retaining login variables - this should help for other scenarios as well!
