### ISSUE TITLE
make the fallback optional if pagefile->url is smaller than webp

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#903]
I understand thats it's crucial to save bandwith. That's why we have webP now, finally.

But there is one line in PagefileExtra.php that delivers the normal image url instead of the webp version, if the webp filesize is larger.

In my case and I think on other sites too this is an unwanted behaviour, as quality and colors are different if you compare a jpg and a webp image.

To illustrate this I attached this image, where you can see that the first three products which are being delivered as JPGs because the filesize is smaller are really different looking than the next 3 which are in webp format , especially in the logo area. This is somewhat hard to see here in github, but on my development site it looks really bad and is a showstopper for me to use webp.

![chrome_2019-06-12_10-36-09](https://user-images.githubusercontent.com/551551/59337138-42b22b80-8d00-11e9-841a-960fd1d15580.png)

What I ask for is an option to skip the filesize check and maybe the option to enter a treshold value when to use the smaller image.

**Comment by ryancramerdesign** [comment]
@jmartsch You can do this already by calling `$image->webp()->url(false);` as that `false` prevents the size fallback. I can add a separate `$config` option or something as well if you think it's needed.

**Comment by jmartsch** [comment]
@ryancramerdesign Thanks. This works fine for me. 
I use this code from the example page (now with added false parameter for the url method):
```
// output webp version for all $image->url() calls
//if($page->template != 'admin') {
  $wire->addHookAfter('Pageimage::url', function($event) {
    static $n = 0;
    if(++$n === 1) $event->return = $event->object->webp()->url(false);
    $n--;
  });
//}
```
The option to disable delivering the fallback image if it is smaller, should be documented somewhere.

**Comment by ryancramerdesign** [comment]
@jmartsch Sounds good - that looks great.

**Comment by jmartsch** [comment]
@ryancramerdesign What would be the best method to skip SVGs? I used the following code, do you have any better ideas?
``` 
// output webp version for all $image->url() calls, skip SVG's
if($page->template != 'admin') {
  $wire->addHookAfter('Pageimage::url', function($event) {
    static $n = 0;

    if(++$n === 1) {
      if (strstr($event->object->filename, '.svg') === false){
        $event->return = $event->object->webp()->url(false);
      }
    }
    $n--;
  });
}
```
