### ISSUE TITLE
Page clone/copy uses existing created datetime

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#905]
### Short description of the issue

When you copy/clone a page, the new page has the same created date as the source page.

### Expected behavior

The created timestamp for the new page would be set to the time it was created.

### Optional: Suggestion for a possible fix

I am using a hook to "fix" this, but I feel like the core behavior should be changed (at least optionally). There is more discussion about this issue here: https://processwire.com/talk/topic/21525-copyclone-page-createdmodified-dates/

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I've pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks!
