### ISSUE TITLE
htaccess 3.0 - quotes missing?

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#906]
Aren't there are quotes missing at the end?

`<Files favicon.ico>
  ErrorDocument 404 "The requested file favicon.ico was not found.
</Files>

<Files robots.txt>
  ErrorDocument 404 "The requested file robots.txt was not found.
</Files>
`

**Comment by teppokoivula** [comment]
That's actually the syntax expected by Apache 1.3. Not sure if anyone still uses that, but since it works in modern versions as well, there hasn't been much of a reason to change it :)

**Comment by ryancramerdesign** [comment]
@tbba The no closing quote is intended, per what Teppo mentioned.

**Comment by tbba** [comment]
Thank you
