### ISSUE TITLE
New $pages->find selector OR issue with check_access broken sometime since 3.0125

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#907]
I am not sure if this is related to https://github.com/processwire/processwire-issues/issues/550 but this selector:

```
template=user, roles=user, first_name!=, phone.raw!=, check_access=0, id|subscriber.id=2854'
```

stopped working properly for non-superusers when I upgraded from 3.0125 to 3.0133.

The find is triggered by an AJAX call (and testing it in Tracy's console results in the same problem, so it may be limited to AJAX requests).

The hook mentioned in #550:

```
$this->wire()->addHookAfter('ProcessPageSearch::findReady', function(HookEvent $event) {
    $selector = $event->arguments(0);
    if(strpos($selector, 'template=user') !== false && strpos($selector, 'name|first_name|last_name%=') !== false) {
        $selector .= ', check_access=0';
    }
    $event->return = $selector;
});
``` 

is still in place, but something changed since 3.0125.

The difference compared with the other issue is that the selector returns the user with the ID of 2854, but not the associated users with the "subscriber" page field to connect them to this "subscriber" user, so it seems like there is an issue with the "OR" pipe.

As soon as I revert to 3.0125, it works as expected again.

**Comment by ryancramerdesign** [comment]
@adrianbj ProcessPageSearch won't accept a check_access=0 from user input, but you already know that based on your use of the hook. The thing is, your hook is requiring the presence of a string `name|first_name|last_name%=` that is not present in your selector, so the check_access=0 would never get added to it. If this is the actual code you are using, it doesn't look to me like it would do anything? But if these are just example snippets and not the actual code, paste in the real code and we can get closer look.

**Comment by adrianbj** [comment]
Ok, let me simplify this down. It has nothing to do with ajax or ProcessPageSearch.

Take this code:
```
echo $pages->count('template=user, check_access=0, id|subscriber.id=2261');
```

On 3.0.125 it returns `6` for both superuser and a non-superuser, but on 3.0.133 it returns `1` for a non-superuser.

If I use (note the `id|` is missing):
```
echo $pages->count('template=user, check_access=0, subscriber.id=2261');
```
for a non-superuser, it returns 5

If I use (note the missing `|subscriber.id`):
```
echo $pages->count('template=user, check_access=0, id=2261');
```
it returns `1`

So it has something to do with the OR pipe and the need for `check_access=0`.

These results are from placing the selector directly in a template file.

In case it's not clear, "subscriber" is a page field that references other users.

Can you reproduce this?

**Comment by adrianbj** [comment]
@ryancramerdesign - do my new examples help you to understand the problem? If you need, I can step through the versions from 3.0125 to 3.0133 to figure out when and hopefully what code change is causing the problem - let me know if you need this.

**Comment by ryancramerdesign** [comment]
@adrianbj Yes that helped clarify it, thanks. I was able to reproduce it with this test case below, which matches the superuser role or users having the superuser role on any PW install. 
~~~~~~
$items = $pages->find("roles.id|id=38, check_access=0");
echo $items->implode("{path}\n");
~~~~~~
The above wasn't working (for non-superuser), but I pushed an update that fixes it. I'm thinking the same will be true for your test case, but wanted to confirm?

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that does seem to fix my issue as well. I am a little nervous about implementing this on a production site though - that's quite a lot of new code to get this working again. 

I see now that this commit (https://github.com/processwire/processwire/commit/3577b81591e62c730c864a2491005d32913a369a#diff-bf4ce11deee917bffc99d4efcc9f72f1) is what broke this in the first place, so I guess it's just a matter of getting `check_access` into that new `getIncludeSelector` method. I am curious though why it was only broken with an "OR" pipe. It seems that `roles.id` or `id` on their own worked just fine without this fix. Does it make sense that individually they were fine, but not together?

**Comment by ryancramerdesign** [comment]
It's necessary because you didn't used to be able to use `id` or other native properties in OR conditions with regular fields. Technically, you still can't, but PW has for awhile supported it by taking parts that can't be combined in the original query/selector and splits them into a separate one, then merges the result from that into the original. The getIncludeSelector() ensures that whatever include/check_access/status mode that was in the original also gets populated to the secondary.

**Comment by adrianbj** [comment]
Thanks - I started using that selector in around January this year and I don't think I realized it was newly "kinda" supported. Anyway glad it's working again and there is a good reason for the needed change.
