### ISSUE TITLE
.htaccess WebP fallback method not working in subdirectories

### ISSUE THREAD

**Issue by TomS-** [processwire/processwire-issues#908]
### Short description of the issue

The fallback solutions given in https://processwire.com/blog/posts/webp-images-and-more/ do not work in a subdirectory 

### Expected behavior

Images should load the webp alternative where supported / or the image should load png / jpeg where not. 

### Actual behavior

Both methods fail under a subdirectory.

### Steps to reproduce the issue

1. Create a processwire installation under a subdirectory
2. Set up the htaccess rules as stated in the post
3. The most obvious one is to use webp that fallsback to png / jpeg, you'll see Internet Explorer doesn't load the images 

### Setup/Environment

* ProcessWire version: 3.0.133

**Comment by ryancramerdesign** [comment]
@TomS- I'm not planning to make those .htaccess changes part of the core, just there as a starting point for readers of the blog post. I'm not the author of those rules, but I'm assuming they would need to be updated for wherever you install them, as with any .htaccess things. For instance prepending your subdirectory to the "site/assets/" that's already in there, i.e. "subdir/site/assets/". Hopefully there's not more to it than that, though if you find there is let me know and we can check with Horst to see what he suggests.
