### ISSUE TITLE
autoRotation => true, It does not work correctly with image->height(300)

### ISSUE THREAD

**Issue by PawelGIX** [processwire/processwire-issues#91]
Version: PW currrent dev 
### Short description of the issue

Source image about 3000x2000px autorotated with EXIF Orientation: Rotate 90 CW.
image->height(600) respect EXIF autorotation but swaps width<->height.
![untitled-1](https://cloud.githubusercontent.com/assets/391153/20537784/b736a8be-b0ee-11e6-8a56-51f1b838a385.jpg)
Output image is cut off from the top and bottom. What should not happen.
Proportions also are broken.

File source image

### Expected behavior

image->height() should process image after autorotation.

Source image 
[dsc07925 1](https://cloud.githubusercontent.com/assets/391153/20537816/e8b3504a-b0ee-11e6-8e10-f3b365e75f71.jpg)

**Comment by ryancramerdesign** [comment]
I'll ping @horst-n for this, as I don't know anything about the auto-rotation code.

**Comment by horst-n** [comment]
Hi,
I have checked this, and GD works like expected. BUT the Imagick-Engine doesn't. 
@PawelGIX: Can you confirm that you are using Imagick-Engine?

**Comment by PawelGIX** [comment]
Hmm.. Where can I check this? I do not see the appropriate variable in the config.php file.
Module "Imagick Image Sizer" is uninstalled.

**Comment by horst-n** [comment]
Forget about the IMagick-Engine. It is working the same as GD.

Just to clarify, what do you expect with a call to width / height when cropping is true, and what if cropping is false;

->width(100, array('cropping'=>true, 'autoRotation'=>false, 'suffix'=>c1ar0w))
->width(100, array('cropping'=>true, 'autoRotation'=>true, 'suffix'=>c1ar1w))
->width(100, array('cropping'=>false, 'autoRotation'=>true, 'suffix'=>c0ar1w))

->height(100, array('cropping'=>true, 'autoRotation'=>false, 'suffix'=>c1ar0h))
->height(100, array('cropping'=>true, 'autoRotation'=>true, 'suffix'=>c1ar1h))
->height(100, array('cropping'=>false, 'autoRotation'=>true, 'suffix'=>c0ar1h))

Can you tell me this please, in regard to the image you uploaded? (width and height for the above examples)

**Comment by jlahijani** [comment]
Not sure if this helps, but when I load the source image PawelGIX provided in Chrome (Windows), it "loads" from right to left, rather than top down.  I'm not an image meta data expert, but I believe that may have something to do with it.

**Comment by netcarver** [comment]
@PawelGIX @horst-n @jlahijani This issue is quite old now, is it still relevant given recent updates to PW?

**Comment by netcarver** [comment]
Closing this as it seems to have gone cold.
