### ISSUE TITLE
Warning: session_set_save_handler() with SessionHandlerDB in multiple ProcessWire instance environment under PHP 7.2

### ISSUE THREAD

**Issue by kixe** [processwire/processwire-issues#911]
### Short description of the issue
The following warning appears in an environment with multiple **ProcessWire** instances under one single domain using session handler for storing sessions to database **SessionHandlerDB** for all instances under **PHP 7.2**
> Warning: session_set_save_handler(): Cannot change save handler when session is active in ... /wire/core/WireSessionHandler.php on line 44

### Expected behavior

No warnings.

### Actual behavior

WireSessionHandler as the base class for **SessionHandlerDB** adds a hook to **Session::init()**
This hook function: **WireSessionHandler::attach(**) calls **session_set_save_handler()** without checking if a session is active. The check is done later inside **Session::init()** before the **session_start()** but should also happen before **session_set_save_handler()**.

### Suggestion for a possible fix

The error is gone if a check for active session is done before calling **session_set_save_handler()**. Add check in **WireSessionHandler::attach()**:

```
	/**
	 * Attach this as the session handler
	 *
	 */
	public function attach() {

		if(function_exists("\\session_status")) {
			if(session_status() === PHP_SESSION_ACTIVE) return;
		}

		session_set_save_handler(	
			array($this, 'open'),
			array($this, 'close'),
			array($this, 'read'),
			array($this, 'write'),
			array($this, 'destroy'),
			array($this, 'gc')
			);
	}

```

### Setup/Environment

+ multisite environment with Option 1
@see https://processwire.com/docs/more/multi-site-support/
+ SessionHandlerDB

* ProcessWire version: 3.0.133
* PHP version: 7.2
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by kixe** [comment]
maybe related: https://bugs.php.net/bug.php?id=75628
No warnings without SessionHandlerDB or in single domain environment.

**Comment by kixe** [comment]
@ryancramerdesign 
The warning appears in debug mode only, when I try to init a second ProcessWire instance (multi-site environment with multiple DBs via **index.config.php**) within my **ready.php**

**ready.php**
`$newPwInstance = new ProcessWire($config->paths->root . 'site/');`

**Comment by kixe** [comment]
@ryancramerdesign 
I made an update of the description of this issue and included a suggestion for a possible fix. Please have again a look inside this. Thanks.

**Comment by ryancramerdesign** [comment]
@kixe Thanks, I've pushed a fix similar to what you suggested.

**Comment by kixe** [comment]
Thanks. Closed.
