### ISSUE TITLE
JS "Uncaught ReferenceError: ProcessWire is not defined" if using Front-End Page Editor + outputting $config->scripts

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#912]
If you use Front-End Page Editor and your _main.php has the following at the bottom:
```
foreach($config->scripts as $file) {
  echo "<script src='$file'></script>\n";
}
```

Then a bunch of scripts from Front-End Page Editor get injected leading to the following JS error:
```
Uncaught ReferenceError: ProcessWire is not defined
    at ckeLoadPlugins (InputfieldCKEditor.js?v=161-1554572226:59)
    at InputfieldCKEditor.js?v=161-1554572226:64
```

An easy way to test this in to do a fresh install of PW using Regular Site Profile (which has Front-End Page Editor ready to go given its settings) and inserting the foreach block about at the bottom of _main.php.

Would you consider this a "bug" in the general sense?  It's a common practice to output JS as I described above, so I would imagine this is something that many people may experience.

**Comment by Toutouwai** [comment]
As I understand it, `$config->scripts` is a FilenameArray that is for use by the PW core, and if you want a FilenameArray for front-end use you create your own for that purpose.

A forum post on the topic: https://processwire.com/talk/topic/5162-how-to-load-js-css-plugins-colorbox-cycle2/?do=findComment&comment=49780

**Comment by jlahijani** [comment]
Yea, I shouldn't use ```$config->scripts``` in the frontend then.  I'll instead use ```setting()```.  While ```$config->scripts``` is convenient for loading in the required JS for "hand-built" PW API-based forms, it has unintended consequences like what this issue brings up.  While I could use ```$config->scripts->remove()```, that approach becomes too hackish.  Closing.
