### ISSUE TITLE
PW Dev Update after 14-June broke Lister Pro here

### ISSUE THREAD

**Issue by tbba** [processwire/processwire-issues#913]
PW 3.0.133 / PHP7.2:

A Lister Pro Page (not the config page) shows this error at the botton of the page and stops working:

`Fatal error: Uncaught PDOException: You cannot serialize or unserialize PDO instances in [no active file]:0 Stack trace: #0 [internal function]: PDO->__sleep() #1 [internal function]: session_write_close() #2 {main} thrown in [no active file] on line 0`

Reverting back to the PW release from 14-June fixed the problem.

The config was not super complicated, I was just looking for newer pages from a certain template, the selector shows:
_template=169, include=all, created<01.01.2019 00:00, limit=25, sort=-modified, get_total=0_

**Comment by ryancramerdesign** [comment]
Thanks @tbba I think I've tracked this one down and have pushed a fix.

**Comment by tbba** [comment]
Yes, its working now. Cool.
