### ISSUE TITLE
No field rendering in admin for Page Reference fieldtype, when view-only access to this field

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#915]
### Short description of the issue

Fieldtype : Page Reference (single page ; untested with multiple pages)
Input mode : whatever ("Select", "Page List Select", ...).
Field-level permission : View (only) for the user's role
Template-level permission : View + Edit for the user's role

Issue : In this context, absolutely no markup is rendered in the admin, for this field.
(while there's correct markup rendering for other fieldtypes, in similar setup : Text, Integer, ...)

### Expected behavior

The field markup should be rendered, showing the page(s) referenced, in read-only.

### Setup/Environment

* ProcessWire version: 3.0.127

Note that on the subject of fieldtypes rendering glitches when access is view-only, there is also this known implementation gap : processwire/processwire-requests#284

**Comment by Toutouwai** [comment]
It works for me.

Access settings:
![2019-06-26_203549](https://user-images.githubusercontent.com/1538852/60164662-1810b880-9852-11e9-87ee-a4120414047d.png)

Superuser:
![2019-06-26_203600](https://user-images.githubusercontent.com/1538852/60164693-24951100-9852-11e9-9573-fbad7a851c27.png)

Editor:
![2019-06-26_203619](https://user-images.githubusercontent.com/1538852/60164717-2eb70f80-9852-11e9-9e97-e9f85bf9d407.png)

**Comment by ryancramerdesign** [comment]
@er314 is it possible that the field has no selection, or that the user lacks access to view the pages that are selected? When rendering an Inputfield produces no output/markup, PW won't render a container for it either.

**Comment by er314** [comment]
Ah right, I forgot about the toggle "Show field in page editor if viewable but not editable (user can see but not change)".
Sorry guys, I've been too prompt at suspecting a bug.
thanks
