### ISSUE TITLE
Autocomplete page field showing dropdown selector in Lister filter interface

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#918]
### Short description of the issue

One of my page reference fields is correctly working as an autocomplete in Lister, but another one is showing a `<select>` inputfield instead.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

![image](https://user-images.githubusercontent.com/871211/60369065-58ce1600-99a7-11e9-912e-fefe951ffe28.png)

But as you can see, they both have the same settings:

![image](https://user-images.githubusercontent.com/871211/60369094-6aafb900-99a7-11e9-85a1-1a8188e73be5.png)

![image](https://user-images.githubusercontent.com/871211/60369114-77341180-99a7-11e9-91ea-7d288cdd4bbf.png)

**Comment by ryancramerdesign** [comment]
This is coming from InputfieldSelector and is the intended behavior. It uses only two methods for page selection: select or autocomplete. It decides which one to use based on the total number of potential selections possible. It uses a threshold number based upon what is practical for selection and memory, and compares that number to the total number of possible matches. If that number falls below the threshold, it will use select. If it falls above that threshold, it will use autocomplete. So it's not a matter of settings, but instead what quantity of results those settings can match.

**Comment by adrianbj** [comment]
I guess the cutoff is somewhere between 56 and 69 because I have 56 of one and 69 of the other.

I must admit I don't understand why Lister doesn't just use the Inputfield settings. Users are used to a particular field working a certain way when editing a page, but differently when using Lister. Oh well :).
