### ISSUE TITLE
WireCache can't save json encoded data (since https://github.com/processwire/processwire/commit/dcf226995ca4e76a6f59a45286f108dd9b9bcead)

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#919]
### Short description of the issue

If you're trying to store json encoded data in WireCache, this line: https://github.com/processwire/processwire/blob/2b0d8f333accde70251591c7224cdb117f17dd95/wire/core/WireCache.php#L453 causes wireCache to try to store an array, but obviously that can't work.

### Optional: Suggestion for a possible fix

Make sure to json_encode the new array (with the `WireCache` key)

### Steps to reproduce the issue

1. Try to store json encoded data in WireCache

**Comment by adrianbj** [comment]
Another thought kinda related to this - I have always wondered why your version of `looksLikeJSON()` doesn't use this approach:

```
    protected function looksLikeJSON($str) {
        json_decode($str);
        return (json_last_error() == JSON_ERROR_NONE);
    }
```

Seems safer to let PHP determine it, rather than simply looking for the presence of `{[`

PS - I have done some speed tests and the two methods seem comparable.

**Comment by teppokoivula** [comment]
> PS - I have done some speed tests and the two methods seem comparable.

To be fair this is likely to depend a lot on the data itself. Haven't done any speed tests myself, but I'd be surprised if json_decode() was as fast as a really simple string comparison, particularly if there's a big block of data.

Also – and this is purely a personal opinion – I find the "try to decode and see if it fails, and use that info to decide if we can decode later" approach somewhat inelegant. Sure, that's not a major factor, and I've seen this approach suggested before, but still :)

**Comment by adrianbj** [comment]
@teppokoivula - yeah, I guess it's not really important - I have always used this approach as I have seen it suggested in many places. Maybe it's not as fast with huge strings. Maybe it's fine as is - probably not super important either way. I probably shouldn't have gone OT with this :)

The new bug mentioned in the OP however is pretty important :)

**Comment by adrianbj** [comment]
@netcarver - do you think maybe the discussion tag will distract @ryancramerdesign from the fact that the original post is defining a real bug that needs addressing? I went off-topic (and shouldn't have), which is where I think the discussion comes in. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - any reason the initial issue here isn't getting your attention?

**Comment by BitPoet** [comment]
Ping @ryancramerdesign: This should be a quick fix by changing [the line in question](https://github.com/processwire/processwire/blob/2b0d8f333accde70251591c7224cdb117f17dd95/wire/core/WireCache.php#L453) to:
```$data = json_encode(array('WireCache' => $data));```

**Comment by adrianbj** [comment]
Agreed @BitPoet - this is exactly what I noted in the first post - "Make sure to json_encode the new array (with the WireCache key)"

**Comment by brlnr23** [comment]
A workaround that also works (at least for me in the current situation): just don't try to cache a JSON string, but convert it to an array before.

**Comment by adrianbj** [comment]
Yeah, but there are times when this isn't ideal which is why I prepend a `~` and then remove it after pulling from the cache.

This is still such an easy PW core fix though - would love to see it finally put to bed :)
