### ISSUE TITLE
$sanitizer->markupToText doesn't escape <br /> correctly

### ISSUE THREAD

**Issue by stefan-scholl** [processwire/processwire-issues#92]
### Short description of the issue

Using $sanitizer->markupToLine to generate one markup-less line. An unescaped "<" is in the output.

The markup got imported (with using $sanitizer->purify() to clean it up) from an external source. The "<" is the rest of a "\<br />" in the HTML code.

### Expected behavior

One line without unescaped "<" in output.

### Actual behavior

Unescaped "<" in output.

### Optional: Suggestion for a possible fix

Grouping the alternatives in the regular expression around https://github.com/processwire/processwire/blob/master/wire/core/Sanitizer.php#L1075

I can reproduce the problem in the tool The Regex Coach. It just matches the "br />" and leaves the starting "<" there.

My personal quick fix was adding a "<" in front of the "br" in the regular expression. But this isn't what is intended in the code. Please group the alternatives (separated with "|") differently.

### Steps to reproduce the issue

1. Have markup with "\<br />
2. Use $sanitizer->markupToText() or $sanitizer->markupToLine()
3. Find unescaped "<" in result.

### Setup/Environment
* ProcessWire version: 3.0.41
* PHP version:  5.5.9 (Ubuntu 14.04 LTS)

**Comment by ryancramerdesign** [comment]
Thanks, good find – I've pushed a fix for this.
