### ISSUE TITLE
ProcessPageLister - properties imageWidth and imageHeight not recognized in class instance

### ISSUE THREAD

**Issue by gadgetto** [processwire/processwire-issues#922]
### Short description of the issue

Using ProcessPageLister class in custom PW module the class properties `imageWidth` and `imageHeight` set by your class instance are not recognized.

### Expected behavior

ProcessPageLister should recognize all module property values you set with your class instance.

### Actual behavior

No matter what values you set, the default class values will always be used.

Setting:

`imageWidth = 60`, `imageHeight = 0` should size thumbnails in list with width 60 and heigh proportional

If I understand that correctly, the Lister column with the images should display the field with a thumbnail width of 60px and a proportional height. But the image column displays all thumbnails with width is set to 130px instead.

### Steps to reproduce the issue

```php
$lister = $modules->get('ProcessPageLister');
$lister->initSelector = '';
$lister->defaultSelector = 'template=template_with_pageimage_field';
$lister->imageWidth = 60;  // <-- not recognized
$lister->imageHeight = 0;  // <-- not recognized
$lister->allowBookmarks = false;
$lister->columns = array('title', ''page_image_field');
return $lister->execute();
```

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.135|
|PHP|7.2.14|
|Webserver|Apache|
|MySQL|5.7.25|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|30 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|FieldtypeMessageMeta|0.0.1|
|FieldtypeSnipWireTaxSelector|0.0.1|
|InputfieldMessageMeta|0.0.1|
|MarkupSnipWire|0.0.1|
|ProMailer|0.0.7|
|ProcessGroupMailer|0.0.1|
|ProcessMessageLister|0.0.1|
|ProcessProMailer|0.0.7|
|ProcessSnipWire|0.0.1|
|ProcessTracyAdminer|1.0.6|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SnipWire|0.0.1|
|TracyDebugger|4.19.23|
</details>

**Comment by ryancramerdesign** [comment]
@gadgetto Those image properties are no longer in use except for certain cases, like if you use a hook to present a PHP array with Pageimage objects in it. When we rewrote the InputfieldImage a couple years ago, it took over the rendering of images so that Lister no longer has to do that.

**Comment by gadgetto** [comment]
OK, thanks! Could you give me a hint for what's the preferred way to set custom thumbnail size in Lister since then?

I have this Lister an would like to resize the thumbnail to width: 60 and heigh: proportional

<img width="1156" alt="Bildschirmfoto 2019-07-10 um 18 49 04" src="https://user-images.githubusercontent.com/876737/60988284-9174d480-a343-11e9-9873-ffdcb1c219f8.png">

**Comment by ryancramerdesign** [comment]
This setting is controlled by the `$config->adminThumbOptions` array via the `gridSize` setting, which controls the output of thumbnails on all image fields, whether in the page editor or in Lister or anywhere it appears. Also note the `scale` setting comes into play as well (for HiDPI scale).

**Comment by gadgetto** [comment]
Thanks for your hint! So it seems it's not possible (without overriding CSS) to resize image output in a Lister instance without affecting all other page image fields too.

Found this forum thread: https://processwire.com/talk/topic/15271-backend-page-table-list-thumbnail-size/

**Comment by ryancramerdesign** [comment]
@gadgetto Lister/ListerPro delegates field rendering to the markupValue() method of each Fieldtype. As a result, you can always use a hook to get exactly the output you want. It can go in /site/ready.php or /site/templates/admin.php. Here's an example (written in browser) where I create different sized thumbnails output depending on the image field: 

~~~~~
$wire->addHookBefore('FieldtypeImage::markupValue', function($event) {
  list($page, $field, $value) = $event->arguments;
  if(!$value) $value = $page->get($field->name); 
  $out = '';

  if($field->name == 'images') {
    // images field where we want 100x0 thumbs
    foreach($value as $image) {
      $thumb = $Image->width(100); 
      $out .= "<img src='$thumb->url' />";
    }
  } else if($field->name == 'photos') {
    // images field where we want linked 300x300 thumbs
    foreach($value as $image) {
      $thumb = $image->size(300,300);
      $out .= "<a target='_blank' href='$image->url'><img src='$thumb->url' /></a>";
    }
  } else {
    // we will let the original method handle other image fields
  }

  if($out) {
    $event->return = $out;
    $event->replace = true; // tell it we are replacing method we hooked
  }
}); 
~~~~~

**Comment by gadgetto** [comment]
Great! This solved it!
