### ISSUE TITLE
own tags (vs predefined ones) not shown

### ISSUE THREAD

**Issue by fluctusz** [processwire/processwire-issues#925]
i think this is related to closed issue https://github.com/processwire/processwire-issues/issues/830

... i have the same behavior with Setting "User selects from list of predefined tags + can input their own".  with selected prededfined tags everything works fine, but "own" tags are not further shown after page-save. The own-tag gets saved in the field_fieldname.tags column, but isn't shown in the admin-form.

ProcessWire 3.0.123
mysql 5.6.44
Version 7.0.32

**Comment by ryancramerdesign** [comment]
I can't duplicate this one here. Can you paste in the list of predefined tags that you are using, as well as the list of tags you are entering manually that aren't getting saved? Also double check your field settings to make sure that the "Use Tags" field has selected the "User selects from predefined list of tags + can enter their own", and that you've entered one or more space-separated predefined tags.

**Comment by fluctusz** [comment]
hi Ryan, thank you for looking into this. yes, field settings are as you describe, i have 3 predefined tags "frontlader testit thirdtag". 
i choose the tag "frontlader" from predefined tags and save the page. tag is shown in tags-field and saved in field_fieldname.tags column.
i input "testanother", hit enter, save the page. only "frontlader" is shown in tags-field. field_fieldname.tags column has now "frontlader testanother".
i choose testit from predefined tags, frontlader and testit are shown in tags-field, colum contains "frontlader testit"
.....now it gets interesting. a input "custom" and "another", save the page, tags-field shows "frontlader testit custom", in the column "frontlader testit another custom" .
choose predefined "thirdtag", save. tags-field: frontlader testit thirdtag, column "frontlader testit custom thirdtag"

i think it should be replicable, isn't it?
thanks, martin

**Comment by matjazpotocnik** [comment]
@fluctusz, there are several improvements to tags in the last dev versions. Could you check if the issue still exists and, if not, close this issue?

**Comment by fluctusz** [comment]
can not say if this is solved but close it.
