### ISSUE TITLE
Vague log message "Configurable module check failed for [module], retrying.."

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#926]
My log files from a couple of past days contained a lot of comments like this:

```
2019-07-11 18:25:19	admin	https://boilerplate.wireframe-framework.com/	Configurable module check failed for Wireframe, retrying...
```

Digging to the Modules class turned up a comment referring to ProcessChangelogHooks:

```
                    // re-try because moduleInfo may be temporarily incorrect for this request because of change in moduleInfo format
                    // this is due to reports of ProcessChangelogHooks not getting config data temporarily between 2.6.11 => 2.6.12
```

After even more digging it appears that – and please correct me if I'm wrong! – this is caused by ProcessWire having old data in cache, which is why the 'configurable' property will be 'null' even though the module is actually configurable. This was likely caused by the fact that Wireframe was recently made configurable, so it's understandable that the site had old data in cache.

Comments mention "change in moduleInfo format" and "2.6.11 => 2.6.12", but in my case this occurred in the latest master release (3.0.123). (I'm assuming that the comment refers to ProcessWire moduleInfo format and ProcessWire version.)

It's great that there's detection for this, but could the message rather point to the underlying issue and explain that the site may need a modules cache flush – or did I get this whole thing wrong? :)

**Comment by ryancramerdesign** [comment]
There's a few cases that can trigger this, so I'm not sure any one error message can say exactly what the case is, but I think your suggestion about instead adding that the user might need to do a Modules > Refresh sounds like a good plan. I'll do that.

**Comment by teppokoivula** [comment]
Thanks, that sounds like a good plan :)
