### ISSUE TITLE
Page clone/copy uses existing createdUser and modifiedUser

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#927]
### Short description of the issue

Similar to https://github.com/processwire/processwire-issues/issues/905 I feel like a new message should have the `createdUser` and `modifiedUser` set to the user who does the copy/clone.

### Actual behavior

Keeps the users from the source message.

**Comment by ryancramerdesign** [comment]
Thanks, I agree. I've pushed an update so that it should now do this. There is one interactive case I'm aware of where it's supposed to keep the original “modified” time/user for the clone (ProcesPageClone ajax clone), so that is still present. It updates the createdUser now either way though.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - I am curious though why the ajax clone would keep the original modified time/user - I guess it hasn't technically been modified at this point, but then even with a non-ajax clone, it still may not have been modified, even if the page was saved again (assuming no field changes).
