### ISSUE TITLE
findOne include=all doesnt seem to work

### ISSUE THREAD

**Issue by postscript-chris** [processwire/processwire-issues#930]
This works and I can foreach:
$testimonial = $pages->find("template=52, testimonial!=, sort=random, include=all, limit=1");

This doesn't work with trying to echo:
$testimonial = $pages->findOne("template=52, testimonial!=, sort=random, include=all");

I think the include=all is the issue.

**Comment by BernhardBaumrock** [comment]
find() returns a PageArray, findOne() returns a single page object. So you can't foreach a single page object obviously.

Does that resolve your issue?

**Comment by postscript-chris** [comment]
Cheers @BernhardBaumrock

This works:
```
$testimonial = $pages->find("template=52, testimonial!=, sort=random, include=all, limit=1");
foreach($testimonial as $t) echo $t->title;
```

This doesn't:
```
$testimonial = $pages->findOne("template=52, testimonial!=, sort=random, include=all");
echo $testimonial->title;
```

**Comment by BernhardBaumrock** [comment]
findOne works just as expected here:
![img](https://i.imgur.com/dolRptZ.png)

I think the support forum would be a better place to get help with this problem. And you should provide better information of what you want to achieve, what you've tried already, what worked, what did not work etc...

**Comment by postscript-chris** [comment]
Thanks for the reply @BernhardBaumrock, can you test with the page unpublished?

**Comment by ryancramerdesign** [comment]
@postscript-chris @BernhardBaumrock The `$pages->findOne()` is an access filtered version of `$pages->get()`, and the presence of `include=all` means you probably want a `$pages->get()` here instead. But the behavior you are seeing here actually is not consistent with what the phpdoc for the methods states, so I think this is a bug. I've pushed a fix that should correct this. Thanks.

**Comment by netcarver** [comment]
@BernhardBaumrock @postscript-chris Is this fixed now, can this issue be closed?

**Comment by netcarver** [comment]
@postscript-chris @BernhardBaumrock I'm closing this now. Please post here again if you need to and I'll re-open this issue.

**Comment by BernhardBaumrock** [comment]
Thx, I've never complained about anything - I've just mentioned that everything works as expected for me ;)
