### ISSUE TITLE
Pages->find() with sort=random doesn't return random results (getting cached?)

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#931]
### Short description of the issue

If I perform a Pages::find() operation with "sort=random, limit=x" twice, I get exactly the same results. Considering that I've specified random sorting, this is unexpected, and actually a bit problematic in this case, where I'm trying to create two random lists of items.

Note: omitting the IDs from the first set of results from latter find operation works, but it still seems strange this has to be done in the first place – is the array of items getting cached regardless of "sort=random", or am I missing something here? :)

### Expected behavior

Each Pages::find( ... sort=random ... ) query should return random items.

### Steps to reproduce the issue

A simple test case:

```php
<?php namespace ProcessWire;
require 'index.php';
$a1 = wire('pages')->find('sort=random, limit=5');
$a2 = wire('pages')->find('sort=random, limit=5');
echo $a1 . "\n" . $a2 . "\n";
```

Test output:

```
> php test.php
5052|4655|5234|5966|5712
5052|4655|5234|5966|5712
> php test.php
4905|6075|5102|4914|6229
4905|6075|5102|4914|6229
```

**Comment by BernhardBaumrock** [comment]
I guess that's because of the mysql query cache: https://dev.mysql.com/doc/refman/5.7/en/query-cache.html

Changing the query does result in a different array (note the comma on the 3rd query):
![img](https://i.imgur.com/l9evhK3.png)

Maybe it would be good to have an option to uncache the result if that is explicitly wanted:
```php
$pages->find("sort=random, limit=5, nocache");
```

This could just add an unique hash to the mysql query so that the mysql query cache gets bypassed.

PS: I don't think bypassing the cache by default would be a good idea, even if it's a `sort=random` call.

**Comment by teppokoivula** [comment]
> Maybe it would be good to have an option to uncache the result if that is explicitly wanted:

I was pretty sure that we already had that, but couldn't find it. Perhaps it's some sort of a workaround I'm thinking of (including a random number with a query, or something along those lines – basically what you suggested).

My initial impression would be that unless "sort=random" bypasses caching at this level, it simply won't do what one would expect it to do. That being said, I've very rarely needed this feature for multiple otherwise identical queries, so it's probably not a very high priority issue.

Might be enough to have a known workaround and document this behaviour (if it is indeed to be expected).

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula @BernhardBaumrock I've pushed a fix for this issue.

**Comment by BernhardBaumrock** [comment]
great, thx
![img](https://i.imgur.com/lenCh6v.png)

**Comment by teppokoivula** [comment]
Confirmed, works as expected now. Thanks @ryancramerdesign :)
