### ISSUE TITLE
Modules directory README line ending handling

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#932]
This is not a ProcessWire (core) issue, but rather related to the modules directory – I wasn't sure where to post this, but this seems to be the easiest way to get it listed *somewhere*. Could/should we have an additional repository for site-specific issues/suggestions?

Anyway, here's the issue:

It seems that the modules directory feature reading README files mishandles files with manual line breaks, and basically merges the lines together. At least this appears to be the case for the newly released WireMailRouter module.

This part of the README ...

> By default all rules are matching the “to” email address of a given message. However you
> can also match other email properties when needed (details further below).

... turns into this in the directory entry:

> By default all rules are matching the “to” email address of a given message. However **youcan** also match other email properties when needed (details further below).

I'm not sure if this has always been the case, but it seemed really obvious in the case of this module.

**Comment by ryancramerdesign** [comment]
@teppokoivula I must have already fixed this one as I'm not seeing the issue at present. Are you still observing the issue anywhere? Thanks.

**Comment by teppokoivula** [comment]
I can't see the problem anymore either, so you're probably right. I'll close this issue :)
