### ISSUE TITLE
Can't add sort field to config for User's lister 

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#934]
### Short description of the issue

Can't add sort field to config for User's lister 

### Expected behavior

I should be able to specify `sort` as a field for the User's lister

### Actual behavior

It is ignored. I was trying "Created Date", but it doesn't seem to work for any field.

### Steps to reproduce the issue

1. Go to Config on the User lister
2. Add `sort` and specify a field for ascending or descending by
3. Save and View

**Comment by Toutouwai** [comment]
It sounds like you're using ListerPro together with the Users lister, so in case you are giving non-superusers limited access to the Users lister watch out for this: https://github.com/processwire/processwire-issues/issues/938

**Comment by adrianbj** [comment]
Thanks @Toutouwai - that is good to know!

**Comment by adrianbj** [comment]
Just a follow up @ryancramerdesign - 

![image](https://user-images.githubusercontent.com/871211/62220164-730f6100-b364-11e9-81cf-6d3cb8d46e64.png)

results in:

![image](https://user-images.githubusercontent.com/871211/62220176-786cab80-b364-11e9-850e-f4820ab899b5.png)

Note the missing sort value.

**Comment by adrianbj** [comment]
Same as #958 :)

Ok, well I feel kinda dumb - I forgot about the "What order should the pages appear in" option when configuring a Lister. Although, I don't really see why that exists - why not just let us use the `sort` field in the "What pages should the Lister show" section?

I guess this can be closed because it would break some sites if you removed that dedicated sort option.
