### ISSUE TITLE
Undefined index: suffix in Pageimage.php on line 1239

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#939]
Calling getVariations() with the noSuffix option, but without the suffix option results in the above PHP warning.

Line 1239:

`if(strpos(trim($options['suffix']), ' ') === false) continue;`

Should maybe be

`if(strpos(trim($options[$key]), ' ') === false) continue;`

Working on the latest dev branch, but the issue is in the latest master also, on line 1110.

**Comment by ryancramerdesign** [comment]
Thanks @chriswthomson I've pushed a fix for this issue.

**Comment by chriswthomson** [comment]
Thanks Ryan
