### ISSUE TITLE
InputfieldInteger: min/max attributes not rendered if set to zero

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#94]
### Short description of the issue
_Edit: changed this issue after discovering the problem in fact relates to zero values_

For InputfieldInteger, if a 'min' attribute is set to zero and no non-zero 'max' attribute is set (or vice-versa) then the attribute is not rendered in the HTML input.

### Expected behavior

'min' or 'max' may be set to zero and rendered in the HTML input.

* ProcessWire version: 3.0.40

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue. Also note that in order to take advantage of min/max attributes, you'll need to have the HTML5 number type selected in the field settings.
