### ISSUE TITLE
Repeater field exportConfigData() doesn't check if any subfields exist

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#942]
### Short description of the issue

If you call `exportConfigData()` on a repeater field that doesn't yet have any assigned subfields, you get a `ErrorException: Invalid argument supplied for foreach()` error.

### Expected behavior

I would expect that the foreach in this method would check to see if it was iterable first - ie making sure there is at least one subfield assigned to the repeater field.

### Steps to reproduce the issue

1. Create and save new repeater field, but don't assign any subfields 
2. Call `exportConfigData()` on that field.

I know this is normally not something that you would do, but it comes into play in Tracy. Here is the original report: https://github.com/adrianbj/TracyDebugger/issues/43

I can add a check in Tracy before calling `exportConfigData()`, but I kinda feel like the repeater field should handle this itself.

Any thoughts?

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I have pushed a fix for this issue.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign
