### ISSUE TITLE
Prepare Processwire for PHP 7.4 Release

### ISSUE THREAD

**Issue by tiefenb** [processwire/processwire-issues#943]
## I just tested ProcessWire with PHP 7.4 Beta 1 and got this Errors:

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Warning: session_name(): Cannot change session name when headers already sent in /var/www/html/wire/core/Session.php on line 239

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/html/wire/core/Session.php on line 242

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/html/wire/core/Session.php on line 243

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/html/wire/core/Session.php on line 244

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/html/wire/core/Session.php on line 245

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wire/core/Modules.php:1772) in /var/www/html/wire/modules/Process/ProcessPageView.module on line 142

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/wire/core/WireInputData.php on line 98

Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module on line 1886

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768

Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wire/core/Modules.php:1772) in /var/www/html/wire/core/Session.php on line 1114

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wire/core/Modules.php:1772) in /var/www/html/wire/core/Session.php on line 1115

**Comment by horst-n** [comment]
As far as I understand it, it is one Notice for one not instantiated variable ('installed') in the file Modules.php that need to be fixed:
```
Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1768
Notice: Undefined variable: installed in /var/www/html/wire/core/Modules.php on line 1772
```

All other depends on debug output of the notices and one call to a deprecated function: get_magic_quotes_gpc():
```
Deprecated: Function get_magic_quotes_gpc() is deprecated in /var/www/html/wire/core/WireInputData.php on line 98
```

The third one belongs to @rolandtoth : 
```Deprecated: Unparenthesized a ? b : c ? d : e is deprecated. Use either (a ? b : c) ? d : e or a ? b : (c ? d : e) in /var/www/html/site/modules/AdminOnSteroids/AdminOnSteroids.module on line 1886```

**Comment by ryancramerdesign** [comment]
Looking at the code block in question, it doesn't look like it's possible for the `$installed` variable to be undefined here, unless I'm missing something. What version of PW are you running, and if the latest, is it possibly a beta bug in PHP 7.4? Here's the coded block in question: https://github.com/processwire/processwire/blob/dev/wire/core/Modules.php#L1754

**Comment by tiefenb** [comment]
It's PW 3.0.137 - sure could also be a PHP Beta Bug. I will also try it soon with a fresh PW setup.

**Comment by tiefenb** [comment]
Beta 2 is also scheduled for Aug. 8th. I will check it asap

**Comment by tiefenb** [comment]
I tried it with the new Beta 2 Version and did not found any bug. :-) Only the AdminOnSteroids warning still appears for what I created an issue in the AOS Repo.
