### ISSUE TITLE
Make getPaginationString() translatable

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#944]
### Short description of the issue

I'd like to be able to make use of `getPaginationString()`, but it doesn't seem like there is a way to translate the `of` and `to` parts of the returned string.

### Expected behavior

Some way to easily translate these.

### Optional: Suggestion for a possible fix

Not sure the best approach to handle this - maybe this method just isn't going to be easily ML. Maybe just have to build up the string manually without relying on this. Not sure?

**Comment by ryancramerdesign** [comment]
@adrianbj Can you clarify what you mean about making it translatable? It looks to me like it already is? https://github.com/processwire/processwire/blob/dev/wire/core/PaginatedArray.php#L297

**Comment by adrianbj** [comment]
Sorry Ryan - you're right. I don't do that much ML work so I wasn't thinking along the lines of translating with the systemPW `_` approach which I typically think of as something for translating the PW admin, rather than translating strings that are output on the frontend like this one. Sorry for the confusion.
