### ISSUE TITLE
Admin > Pages > Pages rather than Admin > Pages > Tree when first opened

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#945]
### Short description of the issue

When you first load the page tree and open Admin > Pages, there is a child called "Pages", but when you reload the page tree with it still open, that child is then correctly titled "Tree".

Obviously not terribly important, but still a bit weird.

### Optional: Screenshots/Links that demonstrate the issue

When first opened:

![image](https://user-images.githubusercontent.com/871211/62222878-f0d56b80-b368-11e9-93e4-9313cad54245.png)

After page reload:

![image](https://user-images.githubusercontent.com/871211/62222954-09de1c80-b369-11e9-8381-df38fca05e6f.png)

**Comment by ryancramerdesign** [comment]
@adrianbj This one is expected and okay. ProcessPageList is dynamically sets the title to Pages when it is rendering the main output, for consistency of headline, since ProcessPageList is used at both page/ and page/list/.
