### ISSUE TITLE
Admin language switch in user profile requires logout/login to change menus

### ISSUE THREAD

**Issue by adrianbj** [processwire/processwire-issues#946]
### Short description of the issue

If you change your language in the admin, the menu items don't change until you logout/login again.

### Expected behavior

Menu cache should be cleared when changing user language so that they are updated immediately.

**Comment by ryancramerdesign** [comment]
Thanks @adrianbj I have pushed a fix for this.

**Comment by adrianbj** [comment]
Thanks @ryancramerdesign - that is much better :)
