### ISSUE TITLE
PW Dev Update 3.0.16 Lister Pro issue

### ISSUE THREAD

**Issue by snobjorn** [processwire/processwire-issues#947]
After updating from ProcessWire 3.0.135 dev to 3.0.136 dev, Lister Pro does not show tabs correct. All content is shown below each other. And the item list is not show. The tab button for updating results spins from the loading of the page, and keep on spinning.

I am using PHP version 7.1.
Lister Pro version 1.1.2.

Going back to version 3.0.135 dev fixed the issue.

**Comment by adrianbj** [comment]
Try a hard browser reload to pull in the new js file.

**Comment by ryancramerdesign** [comment]
@snobjorn I can't seem to reproduce this one either. I agree with Adrian that it sounds like a browser cache issue. Does his suggestion above seem to resolve the issue? Or, if you login from an Incognito/Private window in your browser, does the issue still appear?

**Comment by netcarver** [comment]
@snobjorn Hello, can you update this issue please - did the suggestion above help?

**Comment by jmartsch** [comment]
I think I also experienced a similar issue and remember to get it fixed by installing the latest version of ListerPro 1.1.3

**Comment by jmartsch** [comment]
To clarify: I think it is a cache issue. The latest ListerPro seems to append a timestamp/cache invalidation string at the end of the .js filename, which wasn't the case before.

**Comment by netcarver** [comment]
Ok, I'll close this now then. @snobjorn If you need to re-open then, just post here again.
