### ISSUE TITLE
Typo in ProcessCommentsManager.module prevents the module from working

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#95]
There's a typo (`$buton` instead of `$button`) in ProcessCommentsManager.module and this seems to prevent the module from working at all. This issue was introduced in https://github.com/processwire/processwire/commit/87ea1685b2071388585a30d2d412ad7777a4586b.

**Comment by ryancramerdesign** [comment]
Thanks for your PR, this was added earlier this week so I'll close this.
