### ISSUE TITLE
3.0.137 - ProcessWire\Pageimage::setOriginal() must be an instance of ProcessWire\Pageimage

### ISSUE THREAD

**Issue by rafaoski** [processwire/processwire-issues#951]
### Short description of the issue

After adding images and removing them from the image field, the following fatal error appears:

`Fatal error: Uncaught TypeError: Argument 1 passed to ProcessWire\Pageimage::setOriginal() must be an instance of ProcessWire\Pageimage, null given, called in C:\laragon\www\regular\wire\core\PageimageVariations.php on line 257 and defined in C:\laragon\www\regular\wire\core\Pageimage.php:1334 Stack trace: #0 C:\laragon\www\regular\wire\core\PageimageVariations.php(257): ProcessWire\Pageimage->setOriginal(NULL) #1 C:\laragon\www\regular\wire\core\PageimageVariations.php(337): ProcessWire\PageimageVariations->getInfo('beautiful-12743...', Array) #2 C:\laragon\www\regular\wire\core\PageimageVariations.php(589): ProcessWire\PageimageVariations->find(Array) #3 C:\laragon\www\regular\wire\core\Pageimage.php(1322): ProcessWire\PageimageVariations->remove(Array) #4 C:\laragon\www\regular\wire\core\Pageimage.php(1363): ProcessWire\Pageimage->removeVariations() #5 C:\laragon\www\regular\wire\core\Pagefiles.php(374): ProcessWire\Pageimage->unlink() #6 C:\laragon\www\regular\wire\core\WireHooks.php(912): ProcessWire\Pagefiles->hookP in C:\laragon\www\regular\wire\core\Pageimage.php on line 1334`

### Optional: Screenshots/Links that demonstrate the issue
![error-images](https://user-images.githubusercontent.com/12895367/62414576-a0d2ff00-b61d-11e9-86b2-6980c4e5f680.gif)

![error-images-2](https://user-images.githubusercontent.com/12895367/62414584-af211b00-b61d-11e9-95e6-cfa05e01f49a.png)

### Setup/Environment

ProcessWire: 3.0.137
PHP: 7.2.11
Webserver: Apache/2.4.35 (Win64) OpenSSL/1.1.0i 
MySQL: 5.7.24

**Comment by ryancramerdesign** [comment]
Thanks @rafaoski I've pushed a fix for that.

**Comment by rafaoski** [comment]
Thanks to @ryancramerdesign. It looks like it is now correctly deleting photos.
