### ISSUE TITLE
Invalid JSON in the Module class documentation

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#952]
[The Module class documentation](https://processwire.com/api/ref/module/) provides following example for use in the YourModuleClass.info.json:

```
{
  title: 'Your Module title',
  version: 1,
  // and so on
}
```

I get that this is just an example, but I feel that it would be better to provide a working example, perhaps something along these lines:

```
{
  "title": "Your Module title",
  "version": 1
}
// and so on
```

The problems I see in the example are: 1) keys should be in quotes, 2) string values should be in quotes instead of single quotation marks, and finally 3) the comment probably shouldn't be in the JSON itself, as that'll make it invalid, which can be misleading as someone may see this and think that ProcessWire actually supports that kind of syntax.

Just as an example of the sort of confusion this may cause, I recently had a problem where the modules directory entry wasn't updating for one of my modules. I suspected that it might've had something to do with the JSON info file, so I tried to make it follow the format provided by this example to the point – but that actually broke the whole module, since ProcessWire couldn't interpret the JSON anymore :)

**Comment by teppokoivula** [comment]
Note: added a PR with the small changes suggested above.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula good catch, I have pushed an update to correct the example JSON per your suggestions.

**Comment by teppokoivula** [comment]
Thanks, @ryancramerdesign :)
