### ISSUE TITLE
Make Pagefile::setFilename hookable

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-issues#954]
Please see https://processwire.com/talk/topic/22068-pw-30137-%E2%80%93%C2%A0core-updates/?do=findComment&comment=189468

**Comment by BernhardBaumrock** [comment]
@ryan any news on this? It works really great in my setup and I think this approach can open up a lot of great options for a better DEV/LIVE workflow with processwire. In my current project where I modified the core file it was really just doing a

```
git clone myrepo.git
git submodule update --init --recursive
# restore db dump
```

And I had a working copy of the site that downloaded all assets on demand while working with it! This is really awesome but it would break on every core update. I could implement some hack that does a str_replace and file_put_contents in my dev environment to prevent updates breaking this feature, but it's really just adding three underscores to one core file thanks to the ingenious hook system 🙂 

https://processwire.com/talk/topic/22068-pw-30137-%E2%80%93%C2%A0core-updates/?do=findComment&comment=190216

**Comment by ryancramerdesign** [comment]
@BernhardBaumrock I'm working through issue reports this week, came across this request and just wanted to check if you still needed this hookable? The thread you linked above seemed to indicate you might not need it anymore, so wanted to check. There's a little bit of overhead with every hookable method (relative to a regular method), so for a method that gets called a lot like this one, if there's already another way to accomplish what's needed without the hook, it's better if we don't make it hookable. On the other hand, if the only way to solve a recurring need is by making the method hookable, then we should do so.

**Comment by BernhardBaumrock** [comment]
Thx, it was my fault not having the newest PW version therefore it didn't work as expected!
