### ISSUE TITLE
Session::isValidSession() - hookable method is not actually hookable

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#955]
### Short description of the issue

T﻿he [Session::isValidSession()](https://processwire.com/api/ref/session/is-valid-session/) method is supposed to be hookable - it has three underscores before the method name. But if I add a hook in /site/ready.php or in /site/init.php the hook is never executed:

```php
$wire->addHookBefore('Session::isValidSession', function(HookEvent $event) {
    $this->wire('log')->save('debug', 'Hook isValidSession');
});
```

But if I edit Session.php and add a log line at the top of `isValidSession()`...

```php
$this->wire('log')->save('debug', 'isValidSession');
```

...then I can see that the method is executed regularly.

Somebody had the same problem back in 2015: https://processwire.com/talk/topic/10543-temporarily-lock-out-all-from-admin-except-superusers/?do=findComment&comment=100131

### Setup/Environment

* ProcessWire version: 3.0.135

**Comment by ryancramerdesign** [comment]
@Toutouwai This is because Session is initialized during boot, which occurs before the init and ready states. So by the time your ready.php or init.php file is called (or equivalent module method) the isValidSession() has already been determined. I actually don't think there is a way you can hook this outside of the core. Let me see if I can add some way to make that possible.

**Comment by teppokoivula** [comment]
Alternatively: if it's not feasible, perhaps just add a comment explaining that the method is hookable for core purposes only, and can't be hooked at init/ready states. Could even go as far as suggest another method to hook instead.

Granted I'm not familiar with the specific purpose that one might hook into this one, so perhaps it's something important that can't be reasonably worked around :)

**Comment by Toutouwai** [comment]
If there's some way to make the method hookable in init/ready that would be great, otherwise some note in the docs/phpDoc would help avoid confusion.

My intention with trying to hook this method was to see what might be possible to avoid getting logged out after using Chrome's mobile responsive mode in dev tools (which changes the user agent). I don't want to turn off session fingerprinting but thought it might be possible to allow a user agent change in a targeted way.

**Comment by ryancramerdesign** [comment]
@Toutouwai @teppokoivula  The latest commits support this. In your /site/config.php file:
~~~~~
$config->statusFiles('boot', 'boot.php'); 
~~~~~
Then create a /site/boot.php file:
~~~~~
<?php namespace ProcessWire;
$wire->addHook('Session::isValidSession', function($event) {
  // now this hook will be called
});
~~~~~

**Comment by Toutouwai** [comment]
Thanks, works great!
