### ISSUE TITLE
CKEditor settings in Repeater template context are not applied

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#956]
### Short description of the issue

When a CKEditor field is used inside a Repeater field then in the template context of the Repeater you can successfully override settings such as label and description for the CKEditor field. However, you cannot override "rows", and if any other CKEditor settings have been enabled for template context (e.g. "toolbar") then you cannot override those either.

Not sure of the exact cause, but it seems that the CKEditor settings overrides are only retrieved when a repeater item is AJAX-opened and I think the JS config for the CKEditor field would need to be defined earlier than this, when Page Edit first loads.

Related forum topic: https://processwire.com/talk/topic/20771-different-ckeditor-toolbar-options-for-the-same-field-on-different-templates/?do=findComment&comment=189565

### Steps to reproduce the issue

1. Create a CKEditor field "body". Set the "rows" setting to 15.
2. Create a Repeater field. Add the body field to the Repeater and override the rows setting in the Repeater context to 5.
3. Create a template that uses the Repeater field, and a page that uses this template, and note that the height of the body field inside the Repeater is incorrectly set to an equivalent of 15 rows.

### Setup/Environment

* ProcessWire version: 3.0.135

**Comment by ryancramerdesign** [comment]
@Toutouwai Is this still the case? I seem to remember we might have covered this one in the RepeaterMatrix board, but not positive if this is the same thing or not and wanted to double check.

**Comment by Toutouwai** [comment]
@ryancramerdesign, yes, this issue still exists in PW 3.0.141.

**Comment by richgcook** [comment]
@ryancramerdesign Any thoughts?

**Comment by richgcook** [comment]
I also think this is related @ryancramerdesign https://processwire.com/talk/topic/22029-ckeditor-field-context-per-matrix-type/

**Comment by ryancramerdesign** [comment]
@Toutouwai Thanks, I have pushed a fix for this.

@richgcook Note that Matrix repeaters handle this differently than regular repeaters, but should also work even before this update (at least have working in my testing here), though may require the newest version of matrix. Send me a PM in the forums if you find it's not working for you in matrix.

**Comment by Toutouwai** [comment]
Thanks, working great
