### ISSUE TITLE
session->getIP() returns 0.0.0.0 for IPv6 addresses.

### ISSUE THREAD

**Issue by formmailer** [processwire/processwire-issues#957]
### Short description of the issue

session->getIP() returns 0.0.0.0 for IPv6 addresses.

### Expected behavior

session->getIP() should return the visitors actual IPv6 address

### Actual behavior

session->getIP() returns 0.0.0.0

### Optional: Screenshots/Links that demonstrate the issue

You see this behaviour in the User Comment module (but that's just an example)

Your screenshots/links go here.
![bild](https://user-images.githubusercontent.com/334510/62782492-a5cefd00-baba-11e9-8d21-e23614c088b7.png)

### Optional: Suggestion for a possible fix

Unfortunately not

### Steps to reproduce the issue

Echo the results of session->getIP() when accessing the site from a IPv6 address. 

### Setup/Environment

* ProcessWire version: 3.0.123
* (Optional) PHP version: 7.3
* (Optional) MySQL version: mariadb 10.3
* (Optional) Any 3rd party modules that are installed and could be related to the issue: no

**Comment by ryancramerdesign** [comment]
@formmailer If you output the value of `$_SERVER['REMOTE_ADDR']` what do you see?

**Comment by matjazpotocnik** [comment]
You get `::1` on localhost

https://github.com/ryancramerdesign/ProcessWire/issues/1596

**Comment by formmailer** [comment]
Hi Ryan (@ryancramerdesign),
 `$_SERVER['REMOTE_ADDR']` returns the correct IPv6 address.

Hope this helps!

//Jasper

**Comment by ryancramerdesign** [comment]
Thanks @matjazpotocnik, I'll make note of this, this is good to know. 

@formmailer I'd been reading about people encountering some differences in format and was just curious what the actual output is that you are getting from that variable. Feel free to change the letters/numbers to anonymize the, I'm just interested in the specific format that PHP is showing in your case, as I don't yet have any experience with IPv6 addresses in PHP. I do not have access to any installations that use them for $_SERVER[REMOTE_ADDR] to test from here.

**Comment by formmailer** [comment]
Sorry @ryancramerdesign, misunderstood your question:

`echo $_SERVER['REMOTE_ADDR'];` returns the IPv6 adress, somthing like
`2001:678:2c:0:194:0:28:53`

If the IPv6 adress can be "compressed", it will show the compressed version,
Like `2001:500:200::b` instead of `2001:500:200:0:0:0:0:b`
or `::1` instead of ` 0:0:0:0:0:0:0:1 `

Hope this helps.

//Jasper

**Comment by ryancramerdesign** [comment]
Thanks @formmailer I've pushed a fix for this issue.

**Comment by netcarver** [comment]
Closing due to the age of this one. @formmailer Jasper, comment again if you need it re-opening.
