### ISSUE TITLE
$input->whitelist: Overwrite with null not possible

### ISSUE THREAD

**Issue by brlnr23** [processwire/processwire-issues#959]
# Short description of the issue

Unsetting a previously set whitelist variable with `null` is not possible.

### Expected behavior

Using `$input->whitelist("myvariable", null)` sets "myvariable" to `null`

### Actual behavior

The previous value, which has been assigned before, is still present.

### Steps to reproduce the issue

``` 
$input->whitelist("myvariable", "myvalue");
var_dump($input->whitelist("myvariable"));
// result: string(7) "myvalue"

$input->whitelist("myvariable", null);
var_dump($input->whitelist("myvariable"));
// result: string(7) "myvalue"

$input->whitelist("myvariable", "");
var_dump($input->whitelist("myvariable"));
// result: string(0) ""
``` 

### Setup/Environment

* ProcessWire version:  3.0.123

**Comment by ryancramerdesign** [comment]
@brlnr23 The "null" is the same as an omitted argument, so the whitelist() call where you are intending to set a null value is actually just getting the current value and returning it. To unset a value you would have to do one of the following:
~~~~~
$input->whitelist->remove('myvariable'); 
unset($input->whitelist['myvariable']); // or this also works
~~~~~

**Comment by brlnr23** [comment]
thanks for taking the time to explain this @ryancramerdesign!
