### ISSUE TITLE
image field cuases error when limit set to 1

### ISSUE THREAD

**Issue by gideonso** [processwire/processwire-issues#961]
### Short description of the issue

When a image field limited set to 1, when upload another image to the field in a page, error occurs

Recoverable Fatal Error: Argument 1 passed to ProcessWire\Pageimage::setOriginal() must be an instance of ProcessWire\Pageimage, null given, called in /home/web/processwire/WireCore-3.0/core/PageimageVariations.php on line 257 and defined (line 1334 of /home/web/processwire/WireCore-3.0/core/Pageimage.php)

### Expected behavior

Page save without any error

### Actual behavior

Database record of the image not deleted.

### Optional: Screenshots/Links that demonstrate the issue

![backend_image_field_screenshot png 5114f59ba9ef3b4c94036de3e427ac7b](https://user-images.githubusercontent.com/16899800/63090094-c270a680-bf8c-11e9-8616-2b15718bcb37.png)

### Steps to reproduce the issue

1. Create an image field and set limit to 1. The assign it to a tempate.
2. edit a page with that tempage
3. upload a image to the image field and click save.
4. upload another image to the field and click save.
5. Error shown

### Setup/Environment

PHP 5.6
MariaDB 10
ProcessWire 3.0.137

**Comment by matjazpotocnik** [comment]
Possible duplicate of https://github.com/processwire/processwire-issues/issues/951 and already fixed in https://github.com/processwire/processwire/commit/c2ee22b3348fbc69f0233d27bbdb30bb1f7ddaff (will be fixed in 3.0.138)

**Comment by gideonso** [comment]
I see. Seem It is the same error. I will close this issue this is fixed in 3.0.138. Thanks for the info.

**Comment by gideonso** [comment]
Confirmed that it is fixed.
