### ISSUE TITLE
WebP API generated variations not being removed

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#965]
### Short description of the issue

I've implemented WebP on a dev site, using the method outlined in https://processwire.com/blog/posts/webp-images-on-an-existing-site/. 

When removing an image in the admin, not all .webp versions are removed. 

### Expected behavior

All .webp versions of the original and its variations are removed.

### Actual behavior

Only the .webp version of the original is removed. Versions created by the `Pageimage::url` hook - `$event->return = $image->webp()->url();` - remain.

### Optional: Suggestion for a possible fix

Looks to me like the issue lies in PageimageVariations.php line 608:
`foreach($this->pageimage->extras() as $extra)`

The "extra" here is the original .webp version, which has already been removed in `Pagefile::unlink()`. Surely this should be referencing the variation?

### Steps to reproduce the issue

1. Enable WebP per https://processwire.com/blog/posts/webp-images-on-an-existing-site/
2. Add an image to an image field on a page
3. Generate multiple API variations
4. Delete the image
5. Look in the files folder for the page

### Setup/Environment
* ProcessWire version: 3.0.138
* image field I'm testing is in a RepeaterMatrix item

**Comment by ryancramerdesign** [comment]
@chriswthomson Thanks! You had it exactly right as to what the issue was, thanks for pointing me in the right direction. I have pushed a fix.

**Comment by chriswthomson** [comment]
Nice one, cheers!
