### ISSUE TITLE
Images in Repeater no showing when repeater title contains number of images.

### ISSUE THREAD

**Issue by CaelanStewart** [processwire/processwire-issues#97]
### Short description of the issue

If I have an image field in a repeater, and then show the number of images in the repeater item's title, the images don't show.

### Expected behavior

The images should show regardless of the title of the repeater item.

### Actual behavior

The images do not show.

### Steps to reproduce the issue

1. Create a new repeater field
2. Create a new image field named "images"
3. Add the image field to the repeater
4. Set the repeater's "Repeater Item Labels" option under the "Details" tab to `Item #n: {images.count} image(s)` or just something that contains `{images.count}`
5. Add the repeater field to a page
6. Add a new item to the repeater
7. Upload an image to the field inside the repeater
8. Click save
9. Notice that the image does not show up
10. Now revert the "Repeater Item Labels" option for the repeater to it's default value (or just remove the `{images.count}` part).
11. Edit the page with the repeater, again
12. Notice that the image you uploaded now shows up

### Setup/Environment

* ProcessWire version: 3.0.42

**Comment by ryancramerdesign** [comment]
Thanks @CaelanStewart I've pushed a fix for this issue.
