### ISSUE TITLE
$page->get('some_blank_field|file_field') returns blank PageFiles array instead of null

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#970]
### Short description of the issue

For a File field set to hold only one file and the Formatted Value set to automatic, $page->get('file_field') returns null while $page->get('some_blank_field|file_field') returns a blank PageFiles array.

### Expected behavior

I expected $page->get('some_blank_field|file_field') to return null, since that is how the field is configured and is the value returned from $page->get('file_field').

### Actual behavior

$page->get('some_blank_field|file_field') returns a blank PageFiles array.

### Steps to reproduce the issue

1. Create a file field
2. Set max files to 1 and Formatted Value to "Automatic"
3. Echo $page->get('some_blank_field|file_field') and $page->get('file_field') to the page and weep ;-)

### Setup/Environment

* ProcessWire version: 3.0.123

**Comment by BernhardBaumrock** [comment]
What is some_blank_field ? Is that a file field with the same settings?

**Comment by thetuningspoon** [comment]
Sorry, some_blank_field is any other field with a blank/null value, such as an empty title field.

**Comment by ryancramerdesign** [comment]
Thanks @thetuningspoon that's a good find, I've pushed a fix for this.

**Comment by thetuningspoon** [comment]
Thanks Ryan!
