### ISSUE TITLE
PHP 7.3 Error Exception with strpos in FieldtypeFunctional.module

### ISSUE THREAD

**Issue by noelboss** [processwire/processwire-issues#972]
### Short description of the issue
https://sentry.io/share/issue/0bb82c3c791c4be589988601935691ce/

Deprecated: strpos() [<a href='0function.strpos0'>function.strpos0</a>]: Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### Expected behavior

I *think* this is even an error; 
strpos($content, '__text' === false) should probably be strpos($content, '__text') === false

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.138|
|PHP|7.3.7|
|Webserver|Apache|
|MySQL|5.7.26|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|120 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|128M|
|post_max_size|8M|
|upload_max_filesize|32M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP||
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|6.9.6|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP||
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AccessController|0.2.0|
|AdminHelp|1.0.9|
|AdminOnSteroids|2.0.19|
|AdminPageFieldEditLinks|3.1.2|
|AdminThemeBoss|0.5.5|
|AttachmentsProvider|0.0.1|
|AutoSmush|1.1.3|
|BackendFormsHelper|0.0.1|
|BatchChildEditor|1.8.19|
|BreadcrumbDropdowns|0.1.21|
|CacheABTestHelper|0.0.1|
|CacheHelper|0.0.1|
|ConnectPageFields|0.2.3|
|CronjobDatabaseBackup|1.1.6|
|CustomInputfieldDependencies|0.1.9|
|CustomRestApi|0.0.5|
|FeaturedProvider|0.0.1|
|FeedbackFormHelper|0.0.1|
|FieldtypeAssistedURL|1.0.0|
|FieldtypeFieldsetGroup|0.0.4|
|FieldtypeFunctional|0.0.2|
|FieldtypeMultiplier|0.1.3|
|FieldtypeRepeaterMatrix|0.0.5|
|FieldtypeTable|0.1.9|
|FieldtypeTemplates|1.0.0|
|FieldtypeTextareas|0.0.7|
|FormBuilder|0.3.4|
|FrontEndEditLightbox|1.4.0|
|FrontendRenderingHelper|0.0.1|
|HideUneditablePages|0.0.1|
|InputfieldAssistedURL|1.0.1|
|InputfieldChosenSelect|1.2.5|
|InputfieldChosenSelectMultiple|1.2.2|
|InputfieldFormBuilderFile|0.0.2|
|InputfieldFunctional|0.0.2|
|InputfieldMultiplier|0.1.1|
|InputfieldRepeaterMatrix|0.0.5|
|InputfieldTable|0.1.9|
|InputfieldTextareas|0.0.7|
|InviteListProvider|0.2.0|
|InviteProcessProvider|0.0.1|
|InviteProvider|0.2.0|
|InviteRequestProvider|0.0.1|
|LanguageHelper|0.0.1|
|LinkRedirectHelper|0.0.1|
|LoginRegister|0.0.2|
|LoginWithEmail|0.0.3|
|Migrations|0.3.1|
|MinimalFieldset|0.1.5|
|ModuleDependencies|0.2.3|
|ModuleSettingsImportExport|0.2.9|
|Oauth2LoginProvider|0.1.0|
|PageImagesProvider|0.0.1|
|PageTitlePreviewHelper|0.0.1|
|PageimageRemoveVariations|0.0.4|
|ProDrafts|0.0.8|
|ProcessAdminHelp|1.0.8|
|ProcessChildrenCsvExport|1.8.18|
|ProcessFormBuilder|0.3.4|
|ProcessMigrations|0.1.3|
|ProcessPageListerPro|1.1.2|
|ProcessProDrafts|0.0.8|
|ProcessSetupPageName|2.1.3|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|RelatedProvider|0.0.1|
|TemplateCategoryEntry|0.0.1|
|TemplateChurchEntry|0.0.1|
|TemplateCollectionEntry|0.0.1|
|TemplateDenominationEntry|0.0.1|
|TemplateFieldWidths|0.1.9|
|TemplateInviteEntry|0.2.0|
|TemplateMailHelper|0.0.1|
|TemplatePage|0.0.1|
|TemplateResourceContentEntry|0.0.1|
|TemplateResourceContentEntryHelper|0.0.1|
|TemplateResourceEntry|0.0.1|
|TemplateResourceEntryHelper|0.0.1|
|TemplateUser|0.0.1|
|TextformatterMakeLinks|1.0.1|
|TextformatterTagParser|2.2.0|
|TimedPublishHelper|0.0.1|
|TracyDebugger|4.19.32|
|UserAdminProvider|0.0.1|
|UserMailNotifications|0.0.1|
|WireMailMandrill|0.0.1|
|TextformatterOEmbed|2.0.2|
|TextformatterVideoEmbedOptions|0.3.6|
</details>

**Comment by netcarver** [comment]
@noelboss Yes, that's a bug. As written the needle results in a boolean rather than a string, which matches up with the deprecation message.

**Comment by matjazpotocnik** [comment]
@noelboss @netcarver The link provided is not working anymore. I also searched for string '__text' and can't find it in PW 3.0.138 (and later). Can you provide more info or even close this issue if it's already fixed?

**Comment by netcarver** [comment]
/remind me to review this in 1 week

**Comment by netcarver** [comment]
@noelboss I'm going to close this one now. Just ping the thread again if it needs reopening.
