### ISSUE TITLE
MySQL 8.0.16 breaks Datetime field selector with empty value

### ISSUE THREAD

**Issue by BitPoet** [processwire/processwire-issues#973]
### Short description of the issue

Searching for a Datetime field with an empty value leads to an error when running PW on MySQL 8.0.16 or higher.

Example selector for empty date_show_to:
```$pages->find("template=show,date_show_to=,sort=-date_show_from")```

### Expected behavior

The find call should return pages with an empty date_show_to field as it did on previous MySQL versions.

### Actual behavior

Error is thrown:
```SQLSTATE[HY000]: General error﻿: 1525 Incorrect DATETIME value: ''```

### Optional: Screenshots/Links that demonstrate the issue

This was discovered in [this thread](https://processwire.com/talk/topic/22223-mysql-8017-datetime-error/) in the forum.

### Optional: Suggestion for a possible fix

FieldtypeDatetime::getMatchQuery needs to assign a valid term for an empty date instead of the [empty string](https://github.com/processwire/processwire/blob/dev/wire/modules/Fieldtype/FieldtypeDatetime.module#L191) if the passed selector value is empty.

Most likely this should be ```'0000-00-00 00:00:00'```, though I can't say if this breaks compatibility with PW databases upgraded from older releases.

Unfortunately, this is an [intentional breaking change](https://bugs.mysql.com/bug.php?id=93513) in MySQL without a workaround or sql_mode option to turn off. [Oracle treats this as not-a-bug](https://bugs.mysql.com/bug.php?id=95462).

### Setup/Environment
* ProcessWire version: Any
* (Optional) PHP version: Any
* (Optional) MySQL version: >= 8.0.16

**Comment by ryancramerdesign** [comment]
@BitPoet Thanks for letting me know, I wasn't aware of that. I don't have a good way to test that out here, not having access to that MySQL version at present. As a way to test your suggestion, if you get a chance sometime, can you try adding this somewhere in the /wire/modules/FieldtypeDatetime.module file to see if the query works afterwards?
~~~~~
public function getBlankValue(Page $page, Field $field) {
  return '0000-00-00 00:00:00';
}
~~~~~
This isn't actually a solution, but just a way to test, since the query will use that blank value. But if it seems to work, we'll need a different long term solution since it'll use that blank value on pages values, which we don't want. But hopefully this might point us in the right direction. Thanks.

**Comment by adrianbj** [comment]
Is this related to: https://processwire.com/talk/topic/22114-critical-error-saving-field-with-unchecked-checkbox/

I am now also getting errors like: 
`SQLSTATE[HY000]: General error: 1364 Field 'external_link' doesn't have a default value`

This last one is from the ImageExtra module, but just another example that this MySQL change is potentially going to break quite a few things.

**Comment by BitPoet** [comment]
@ryancramerdesign I tried adding the getBlankValue method, but that leads to a slightly different error.
```
Fatal error: Uncaught ProcessWire\PageFinderException: SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '0' in C:\inetpub\wwwroot\my8\wire\core\PageFinder.php:429
Stack trace:
#0 C:\inetpub\wwwroot\my8\wire\core\Wire.php(386): ProcessWire\PageFinder->___find(Object(ProcessWire\Selectors), Array)
#1 C:\inetpub\wwwroot\my8\wire\core\WireHooks.php(813): ProcessWire\Wire->_callMethod('___find', Array)
#2 C:\inetpub\wwwroot\my8\wire\core\Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageFinder), 'find', Array)
#3 C:\inetpub\wwwroot\my8\wire\core\PagesLoader.php(252): ProcessWire\Wire->__call('find', Array)
#4 C:\inetpub\wwwroot\my8\wire\core\Pages.php(246): ProcessWire\PagesLoader->find('template=blog-p...', Array)
#5 C:\inetpub\wwwroot\my8\wire\core\Wire.php(383): ProcessWire\Pages->___find('template=blog-p...')
#6 C:\inetpub\wwwroot\my8\wire\core\WireHooks.php(813): ProcessWire\Wire->_callMethod('___find', Array)
#7 C:\inetpub\wwwroot\my8\wire\core\Wire.php(442): ProcessWire\WireHooks->runHo in C:\inetpub\wwwroot\my8\wire\core\PageFinder.php on line 429
```
This error is after adding specific sql_mode entries to site/config.php:
```php
$config->dbSqlModes = [
  "5.7.0" => "remove:STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY",
  "8.0.17" => "remove:STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,NO_ZERO_DATE,NO_ZERO_IN_DATE"
];
```

Without the dbSqlModes entry, the error message is
```
General error: 1525 Incorrect DATETIME value: '0000-00-00 00:00:00' in C:\inetpub\wwwroot\my8\wire\core\PageFinder.php:429
```

So it looks like the all-zero datetime value gets converted to an integer somewhere along the way, but it should be passed as an unchanged (probably quoted) string.

(Tested this with PW 3.0.141 on MySQL 8.0.17)

**Comment by ryancramerdesign** [comment]
@BitPoet Thanks for the testing. I've pushed an update in an attempt to fix this. I tried the '0000-00-00' date string per what you mentioned earlier, but it sounds like the MySQL version you've got does not like it, so this time around attempting to match any date below the minimum date allowed by a unix timestamp, as well as NULL (referring to no row present in table), which I'm hoping will allow it to achieve the same result between the different MySQL versions without error. Can you confirm? Thanks.

**Comment by flipzoom** [comment]
Ouch. This update destroys my complete search function. @ryancramerdesign , please revise again, because with the .extend method everything flies through my ears.

Here is an example: 
```php
$q = "demo";
$search_selector  = "(content.FieldtypeText.extends%={$q}),";
$search_selector .= "(content.FieldtypeText.extends~={$q})";

//[...] Many other combinations [...]

$pages->findMany($search_selector, array('loadOptions' => array('joinFields' => array('name', 'title', 'headline_1', 'textarea_1', 'sku_1', 'seo_title', 'seo_description', 'seo_keywords', 'seo_index', 'content', 'content_simple'))));
```

Will end in following errors:
```
Error: Exception: Invalid partial date string 'demo' (numbers, hyphens and space only) (in /var/www/XXXX/wire/modules/Fieldtype/FieldtypeDatetime.module line 215)

#0 /var/www/XXXX/wire/core/PageFinder.php(1310): ProcessWire\FieldtypeDatetime->getMatchQuery(Object(ProcessWire\DatabaseQuerySelect), 'field_date_1', 'data', '%=', 'demo')
```

or this one:
```
Error: Exception: FieldtypeDatetime invalid date operator: ~= (in /var/www/XXXX/wire/modules/Fieldtype/FieldtypeDatetime.module line 223)

#0 /var/www/XXXX/wire/core/PageFinder.php(1310): ProcessWire\FieldtypeDatetime->getMatchQuery(Object(ProcessWire\DatabaseQuerySelect), 'field_date_1', 'data', '~=', 'demo')
```

Before the changes for this ticket everything worked fine.

PW: 3.0142 current DEV from 17th october

**Comment by BitPoet** [comment]
@ryancramerdesign I'm going to take it on a test drive, though I probably won't find the time before Sunday. I have forked the current repo, so it's no problem in that regard if you want to revert this change for the time being.

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia @BitPoet I think the issue there is just that FieldtypeDatetime extends FieldtypeText, so it was getting included in that extends query. There's no benefit to Datetime extending Text any longer (and some drawbacks, like this one) so I've isolated them, which should prevent those date field exceptions from occurring in the extends query.

**Comment by flipzoom** [comment]
Thanks @ryancramerdesign. Works for me. Works again without problems with the extends selector.

**Comment by ryancramerdesign** [comment]
@FlipZoomMedia Great, thanks for testing it out.

**Comment by netcarver** [comment]
@BitPoet Chris, any further updates on this? Can this now be closed?

**Comment by netcarver** [comment]
@BitPoet Chris, I'm going to close this now. If you need me to, just post again and I'll re-open this for you.

**Comment by kixe** [comment]
@netcarver Steve please reopen this, it still does not work.

https://github.com/processwire/processwire/blob/50e916b72f66153e0c61bfe92b0e5fbfd6e5748f/wire/modules/Fieldtype/FieldtypeDatetime.module#L259

PW 3.0.143
PHP 7.2.22
MySQL 8.0.17

**Comment by netcarver** [comment]
Done, thanks Christoph!

**Comment by kixe** [comment]
I am getting really bad results 

##  Example 1

**Selector**
`$pages->find("date_end=''"); // searching for pages where datetime value is not set`

**current PDO Statement**
```
SELECT pages.id,pages.parent_id,pages.templates_id FROM `pages`
LEFT JOIN field_date_end AS field_date_end__blank1
ON field_date_end__blank1.pages_id=pages.id
WHERE (((field_date_end__blank1.pages_id IS NULL OR (field_date_end__blank1.data=''
AND field_date_end__blank1.data!='0')))) GROUP BY pages.id
```
**Result**

```diff
- Fatal error: Exception: SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''
- Fatal error: Exception: SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '0'  
```

**expected PDO Statement**
```
SELECT pages.id,pages.parent_id,pages.templates_id FROM `pages`
LEFT JOIN field_date_end AS field_date_end__blank1
ON field_date_end__blank1.pages_id=pages.id
WHERE field_date_end__blank1.pages_id IS NULL GROUP BY pages.id
```

## Example 2

**Selector**
`$pages->find("date_end=0"); // searching for pages with specific date: timestamp == 0 or 1970-01-01 00:00:00 which is different from an empty value '' or NULL`

**current PDO Statement**
```
SELECT pages.id,pages.parent_id,pages.templates_id FROM `pages` 
JOIN field_date_end AS field_date_end ON field_date_end.pages_id=pages.id
AND (((field_date_end.data IS NULL OR field_date_end.data<'1970-01-01 01:00:00' ))) 
GROUP BY pages.id
```

**expected PDO Statement**
```
SELECT pages.id,pages.parent_id,pages.templates_id FROM `pages` 
JOIN field_date_end AS field_date_end ON field_date_end.pages_id=pages.id
AND field_date_end.data='1970-01-01 00:00:00'
GROUP BY pages.id
```

## Example 3

**Selectors**
`$pages->find("date_end='1969-01-01 00:00:00'");`
`$pages->find("date_end='1969-01-01'");`

**results as expected**

**Comment by kixe** [comment]
@ryancramerdesign 
Could you take another look at it? I need to be able to use the Datetime field properly via selector. Please treat empty/ not set differently from January 1st, 1970. It's just not the same.

**Comment by alexchen1875** [comment]
in `mysql 8.0.20` ,got the same error :

![image](https://user-images.githubusercontent.com/3668637/81495673-94827d80-92e4-11ea-860d-5f7ba42a6dc8.png)

**Comment by ryancramerdesign** [comment]
@kixe I've pushed additional updates for this that hopefully fix example 1. I don't experience any of the errors you are seeing, but I understand you are in MySQL 8 and they changed some things there so that code written for MySQL 5.7 and prior doesn't work in MySQL 8. I think I understand what it's looking for and have made updates consistent with that. However, test it out to confirm, if you can. I've tried to find a solution that would produce the same result in 8.x and prior versions, but don't have 8.x to test with since it's not in any of my environments or available on any servers I have access to. 

Regarding your example 2, the intention is that 0 is not treated as a unix timestamp and instead treated as "empty", just like a blank string. This is for consistency with most other Fieldtypes, though some (like InputfieldInteger) let you configure the behavior of that. Maybe it can be configurable for FieldtypeDatetime too, but I'm thinking someone needing to match that particular date with a 0 is probably not so common enough to warrant a config setting. But for now, if you are looking to match the exact date/time that corresponds to the unix timestamp of "0" then you'd want to instead enter the date for it rather than the unix timestamp (i.e. `1969-12-31 19:00:00` or whatever it is).

**Comment by netcarver** [comment]
@kixe Hi Christoph, could you let us know if things are fixed now?

**Comment by netcarver** [comment]
Closing as no feedback.  @kixe Christoph, just post here again if it needs re-opening.
