### ISSUE TITLE
moduleServiceApi returns wrong version number for core modules

### ISSUE THREAD

**Issue by jmartsch** [processwire/processwire-issues#974]
If you take a look at 
http://modules.processwire.com/export-json/?apikey=pw223&class_name=fieldtype-comments
for the fieltypeComments module it says the version is 100. If I take a look at the local installed module in latest stable core, the version is 107. 
This is wrong for all core modules.

Stumbled across this while developing ModuleManager2.

**Comment by ryancramerdesign** [comment]
That's okay, the modules directory is not actively tracking core version numbers and you can't upgrade them through the modules directory either. When I rebuild the modules site, I may be able to find some way to have it track the core modules that way, though I don't think they need to be in the modules directory at all, so may just remove them unless they are useful to someone there. :) Thanks.
