### ISSUE TITLE
Forgot Password Not working with Login/Register module

### ISSUE THREAD

**Issue by Hurmeli** [processwire/processwire-issues#976]
### Short description of the issue

I installed the Login/Register module and tested it by using the "Forgot your password" function.

It sends the email, but upon clicking the link in the email, it simply loads the Login/Register module login screen instead of password recovery one.

### Expected behavior

I should be able to recover/reset forgotten password.

### Actual behavior

Loads up Login/Register module login screen instead of password recovery one.

Once I logged in the backend I got warning:
"ProcessForgotPassword: Unable to complete password reset. Please make sure you are on the same computer and in the same web browser that you originally submitted your request from."

However I am on the same computer and on the same browser.

If I use the admin login screen's "Forgot your password" function, everything works correctly.

* Processwire version 3.0.135
* Forgot Password version 1.0.3
* Login/Register version 0.0.2

**Comment by Hurmeli** [comment]
Possibly a false alarm. After lunch break it was suddenly working correctly.

**Comment by ryancramerdesign** [comment]
Glad that it seems to be working okay now. I'll close this for now, but if the issue reappears, please feel free to re-open it in the LoginRegister module repo. Thanks.
