### ISSUE TITLE
Can't add new user page of a different template when using "Name Format for Children"

### ISSUE THREAD

**Issue by thetuningspoon** [processwire/processwire-issues#977]
### Short description of the issue

I am taking advantage of the ability to create users of a template different from "user" and adding them in a different part of the page tree. But when I go to create a new page from the page tree using the alte﻿rnate user template, some kind of weird redirect happens and I end up on /access/users/edit/bookmarks/bookmarks/bookmarks/bookmarks/

I have set the "Name Format for Children" property on the parent page, so that the first step of setting up a new page should be skipped.

https://processwire.com/talk/topic/13313-cant-add-new-user-page-of-a-different-template/

### Expected behavior

I should see the page editor.

### Actual behavior

Some kind of weird redirect happens and I end up on /access/users/edit/bookmarks/bookmarks/bookmarks/bookmarks/

### Optional: Suggestion for a possible fix

The problem is in ProcessPageAdd on line 1021:

https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L1021

It is calling Page::setEditor, which is overridden by User::setEditor, which performs a redirect instead of actually setting the editor.

Removing line 1021 (which currently does nothing on a regular Page) fixes the issue.

### Steps to reproduce the issue

1. Setup an alternate user template and parent
2. Set the parent's "Name Format for Children" property
3. Try to add a new child page under the parent from the Page Tree

### Setup/Environment

* ProcessWire version: 3.0.123 
* (Optional) PHP version: 
* (Optional) MySQL version: 
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by postscript-chris** [comment]
This is fixed in the dev branch. I reported this in the last 6 months so I know it was an issue.

**Comment by thetuningspoon** [comment]
Thanks @postscript-chris, I'm not sure how I missed that. All that debugging for nothing. *sigh*
