### ISSUE TITLE
Label of template instead of a name in createdPageMessage

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#978]
### **Short description of the issue**
When page created all users view message "Created page %1$s using template: %2$s";
%2$s - is a name of temlpate.

### **Expected behavior**
If site is multilingual need to display template label.

### **Optional: Suggestion for a possible fix**
I replaced the [Process/ProcessPageAdd.module on line 1059](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Process/ProcessPageAdd/ProcessPageAdd.module#L1059) with this:

```
$template = $page->template->label;
if (empty($template)) $template = $page->template->name;
$this->session->message(
	sprintf(
		$this->_('Created page %1$s using template: %2$s'),
		$page->parent->url . $page->name, $template
	)
);
```

**Comment by ryancramerdesign** [comment]
@germankirichenko Thanks, I have pushed an update to use the label rather than the name

**Comment by netcarver** [comment]
@germankirichenko Hello, can you check if this is now fixed and close the issue if it is. If not, please post a further report here.

**Comment by germankirichenko** [comment]
Fixed) Thanks!
