### ISSUE TITLE
Field "pass" is not editable

### ISSUE THREAD

**Issue by processwired** [processwire/processwire-issues#979]
### Short description of the issue

Field "pass" is not editable (error is thrown)
Error: /wire/core/Fields.php in line 1066:
Call to a member function prepend() on null

### Expected behavior

Field should be editable like any other field.

### Steps to reproduce the issue
Open /processwire/setup/field/edit?id=3

### Setup/Environment

* ProcessWire version: 3.0.140
* (Optional) PHP version: 7.3

**Comment by postscript-chris** [comment]
I can confirm the issue.

**Comment by matjazpotocnik** [comment]
I can also confirm. It happens on other custom fieldtypes too, like StreetAddress. I replaced `$fieldtypes->prepend($fieldtype);` with `if($fieldtypes) $fieldtypes->prepend($fieldtype);` but then I get `PHP Warning: count(): Parameter must be an array or an object that implements Countable in ...\Process\ProcessField\ProcessField.module:1414`, and fixed that with wireCount(). Not sure if I'm on the right track...

**Comment by Toutouwai** [comment]
Maybe change [this line](https://github.com/processwire/processwire/blob/6f71ff3f939b036bd24c394d1def40890dc25981/wire/core/Fields.php#L1064) to:

```php
$fieldtypes = $fieldtype->getCompatibleFieldtypes($field) ?: $this->wire(new Fieldtypes());
```

**Comment by ryancramerdesign** [comment]
Thanks guys, I've pushed a fix for this.

**Comment by netcarver** [comment]
@processwired Can you confirm this is now fixed and close the issue if it has. If it hasn't please report back here.
