### ISSUE TITLE
New translatable param to inputfieldSubmit.module

### ISSUE THREAD

**Issue by germankirichenko** [processwire/processwire-issues#980]
### **Short description of the issue**
I translate the admin panel into several languages.
inputfieldSubmit.module uses title as submit button label.

### **Expected behavior**
English is international, and module names are proper names, IMHO. For developers it is always more convenient to use English.

### **Optional: Suggestion for a possible fix**
I suggest adding a new translatable parameter "Label".
I replaced the [InputfieldSubmit.module on line 51](https://github.com/processwire/processwire/blob/649d2569abc10bac43e98ca98db474dd3d6603ca/wire/modules/Inputfield/InputfieldSubmit/InputfieldSubmit.module#L51) with this:

```
$label = __('Label');
if ($label == 'Label') $label = $this->_('Submit'); // Standard submit button label
$this->attr('value', $label); // Set submit button label
```

**Comment by ryancramerdesign** [comment]
I don't understand what you mean about using 'title' as a submit button label? I'm also not sure of a case where 'Label' would be an appropriate label for a submit button. Can you provide further clarification? Is the 'Submit' text not properly translating or translatable? Thanks.

**Comment by germankirichenko** [comment]
@ryancramerdesign Hi Ryan! First of all thanks for Processwire!) When I translated the admin panel into Russian, I need to translate the text on the submit button. It is impossible to do this separately, because the name of the module ('Submit') is used as text on button. And if you translate __(''Submit"), then not only the text on the submit button is translated, but also the name of the module.

**Comment by ryancramerdesign** [comment]
@germankirichenko Thanks, I understand now. You are right, there are two translatable versions of the Submit text in the module, and they are different contexts. The usual fix for this sort of issue is to use the _x() function with a context name, rather than the __() function. But this particular module title does not need to be translatable, so I've removed the __() call around it, which should fix the issue. Thanks.

**Comment by germankirichenko** [comment]
Thank you, Ryan!
