### ISSUE TITLE
$input->requestMethod() does not return anything when HTTP method is PATCH

### ISSUE THREAD

**Issue by MrSnoozles** [processwire/processwire-issues#982]
### Short description of the issue

$input->requestMethod() does not return anything when the HTTP method is PATCH

### Expected behavior

return `"PATCH"`

### Actual behavior

return `null`
### Optional: Suggestion for a possible fix

https://github.com/processwire/processwire/pull/144

### Setup/Environment

* ProcessWire version: 3.0.123

**Comment by ryancramerdesign** [comment]
Thanks @MrSnoozles I've pushed your suggested fix for this issue.

**Comment by netcarver** [comment]
@MrSnoozles Please could you check if this is now fixed and close the issue if it is. Let us know here if not. Thank you.

**Comment by netcarver** [comment]
@MrSnoozles I'm closing this now. Please post here again if you need to and I'll re-open this issue.
