### ISSUE TITLE
$pages->get() wrongly returns Home page for unused field

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#983]
### Short description of the issue

`$pages->get()` wrongly returns the Home page if the selector is for an empty value in a field that is not in the Home template.

### Steps to reproduce the issue

1\. Create a new text field named "foo". Do not add the field to any templates.

2\. Execute the following code in the Tracy console:
```php
$p = $pages->get("foo=''");
d($p);
```

3. Observe that the Home page is returned.

![2019-09-22_155429](https://user-images.githubusercontent.com/1538852/65382040-49b1f680-dd51-11e9-8843-754d9ebeac45.png)

### Setup/Environment

* ProcessWire version: 3.0.141

**Comment by ryancramerdesign** [comment]
@Toutouwai This is the correct result. If you ran it through find() instead, it would return every page in your site. In your case, Home is just the first page that was matched. A query to match an empty value matches where the field has a literal empty value or is not present at all. In real life situations of course you'd want to use a more specific selector.

**Comment by Toutouwai** [comment]
> A query to match an empty value matches where the field has a literal empty value or is not present at all.

Thanks for the explanation. I assumed that the fields included in a selector would have to at least be present in a page's template in order for the page to be considered a match. I guess the solution is to first get the templates that contain the field and then include those in the selector.

**Comment by adrianbj** [comment]
That seems weird to me. If you are for example trying to find all pages with an empty `body` field, you'll end up getting pages whose templates don't even have a body field. An empty text string surely should not be the same as null (which is what I think is more correct if the field doesn't exist).

An even more relevant example might be a checkbox field. I can see search for `"checkbox_field="` and getting all pages without the checkbox field. I guess the only solution it to limit by adding a template selector as well, but sometimes you want to search multiple templates without having to be explicit - especially for a site search function.

**Comment by Toutouwai** [comment]
It's a bit weird to me too, and it would be nice not to need the extra steps to specify templates when searching for empty values. But changing this now could break existing sites so I don't imagine it can happen.
