### ISSUE TITLE
pw-region-debug ignores markup region's pw-optional attribute

### ISSUE THREAD

**Issue by szabeszg** [processwire/processwire-issues#984]
PW-REGION-DEBUG was Introduced in ProcessWire 3.0.62
https://processwire.com/blog/posts/processwire-3.0.62-and-more-on-markup-regions/#debugging-regions

pw-optional was Introduced in ProcessWire 3.0.117
https://processwire.com/blog/posts/processwire-3.0.117-core-updates/

Probably because pw-optional was introduced later on, it's action is not listed in the PW-REGION-DEBUG listing.

The fact that the optional region was succesfully removed should be listed as well. 

For example, I used pw-optional and later on added a child element by accident, forgetting that the optional element must be empty by default or else it does not get removed. Since in my case the added child element was hidden by default (via display: none), I did not notice that the optional element is no longer removed.

**Comment by ryancramerdesign** [comment]
@szabeszg Sounds reasonable to me, but I've looked into it and currently can't add this feature without a significant refactoring since pw-optional removals occur after debug info is populated. However, I'll put it in the class as a todo feature request for the next time this class is getting major updates. Thanks.

**Comment by szabeszg** [comment]
> I'll put it in the class as a todo feature request for the next time this class is getting major updates.

Thank you in advance! Please also consider this related issue:
[#883 nested pw-optional markup region is not removed](https://github.com/processwire/processwire-issues/issues/883#issue-445986231)

What that issue is about in short: it would be useful to be able to – say – define an optional sidebar wrapper element as a placeholder region, which can be populated width also optional children elements (eg.: "widgets") on the fly.

**Comment by ryancramerdesign** [comment]
@szabeszg With a fresh cup of coffee this morning, I found I could add support for include which pw-optional regions were removed in the debug info, along with the #883 that you mentioned.

**Comment by szabeszg** [comment]
Thank you so much @ryancramerdesign the applied changes work as expected, actions are logged, eg:
```
• REMOVED #test1 nested (×1) optional region
• REMOVED #test3 nested (×2) optional region
• REMOVED #test5 nested (×3) optional region
• REMOVED #test6 nested (×3) optional region
• REMOVED #test4 nested (×2) optional region
• REMOVED #test2 nested (×1) optional region
```
I performed tests with depth 3 and all empty elements are removed just as it is reported when using PW-REGION-DEBUG.

I am closing this and #883 too.
