### ISSUE TITLE
Docs page for PageRender::RenderPage() seems to render wrong

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#987]
Just wanted to mention that the [docs page for PageRender::RenderPage()](https://processwire.com/api/ref/page-render/render-page/) looks a bit off; particularly the params, which are rendered as headings (`<h1>`), and the list below the first argument that is rendered as one long paragraph.

Not sure if the custom format used in the module file is still supported (#param etc.) but apparently it's now parsed as markdown, resulting in the strange result observed on this page.

**Comment by ryancramerdesign** [comment]
Thanks @teppokoivula I've pushed a fix for this issue. It'll appear on the website documentation page during the next processwire.com site core update.

**Comment by teppokoivula** [comment]
Thanks Ryan!
