### ISSUE TITLE
Template Filename override via API broken as of PW 3.0.141

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#989]
The ability to override the template filename via the API broke with 3.0.141.  Please see the recent comments in the following PW request which gets into some detail:
https://github.com/processwire/processwire-requests/issues/204

@Toutouwai

**Comment by adrianbj** [comment]
Just wanted to note that I can confirm this - it breaks the Template Path panel in Tracy which uses the template override functionality.

**Comment by ryancramerdesign** [comment]
@jlahijani @adrianbj Thanks, I don't have a test case setup, but I think I see what the issue is. I've refactored things a bit which hopefully should fix it, though please let me know if not.

**Comment by adrianbj** [comment]
The Tracy template path panel now works again, so I expect it's all fixed.
