### ISSUE TITLE
Multi instance in directory missing / issue in ->url and ->httpUrl

### ISSUE THREAD

**Issue by Rayden** [processwire/processwire-issues#99]
### Short description of the issue

Connecting to PW instance in directory will output urls missing a / after hostname

```php
$site = new ProcessWire($config->paths->root.'content/', 'http://domain.com/content/');
echo $site->pages->get('/')->url."<br>";
echo $site->pages->get('/')->httpUrl."<br>";
```

### Expected behavior

Above PHP should output a slash in front of the directory name

```
/content/
http://domain.com/content/
```

### Actual behavior

```
content/
http://domain.comcontent/
```

### Optional: Suggestion for a possible fix

Dirty work around (not a possible fix), to initiate the instance adding an extra slash to the directory name.

```
$site = new ProcessWire($config->paths->root.'content/', 'http://domain.com//content/');
```

### Setup/Environment

* ProcessWire version: 3.0.36
* PHP version: 5.5.8

**Comment by Rayden** [comment]
Small note that since running the instance on the same domain the following works fine here
`$site = new ProcessWire($config->paths->root.'content/', '/content/');`

**Comment by ryancramerdesign** [comment]
Thanks @Rayden I've pushed a fix for this issue.
