### ISSUE TITLE
Toggle fieldtype : template-defined default value ignored

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#991]
### Short description of the issue

For Toggle fieldtype, when the default value is defined at template level, this value should override the default value defined for the field. But it doesn't.

For example, if default value is set to "No" on the field settings,
and if it is set to "Yes" in this field's instance in a template,
then, one would expect that the initial value displayed in the admin, on new page creation, is "Yes".
But actually the initial value displayed in the admin is "No".

* ProcessWire version:  3.0.141

(Toggle fieldtype is neat, thanks)

**Comment by ryancramerdesign** [comment]
Thanks @er314 I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@er314 I'm closing this now. Please post here again if you need to and I'll re-open this issue.
