### ISSUE TITLE
Removing Images field from template leaves orphaned files

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#992]
### Short description of the issue

Usually when a field is removed from a template, all the data that was stored in that field for pages with the template is deleted - there is no orphaned data left behind. The confirmation step before removing a field explains this:

![2019-10-11_102613](https://user-images.githubusercontent.com/1538852/66608010-f4f7f200-ec11-11e9-99b4-0550a7439099.png)

But when an Images field is removed from a template the image files are left orphaned in /site/assets/files/[page id]. You have to find and remove the orphaned files as a separate task or else they sit around taking up disk space unnecessarily.

### Expected behavior

The files are part of the field data so I expected them to be deleted when the field is removed from the template.

### Setup/Environment

* ProcessWire version: 3.0.141

**Comment by ryancramerdesign** [comment]
Thanks @Toutouwai I've pushed a fix for this issue

**Comment by Toutouwai** [comment]
Thanks.
