### ISSUE TITLE
Parent window jQuery dependency in JqueryUI modal.js

### ISSUE THREAD

**Issue by teppokoivula** [processwire/processwire-issues#993]
Hey Ryan!

This may be a bit of an edge case, but I ran into a bit of a problem with Page Editor injected as a modal version (within an iframe) by the AdminBar module. Everything works fine – except for the case where something within said iframe (in this case the CKEditor link plugin) opens a modal window. This throws a JS error in console and doesn't work at all.

The reason for this is that in wire/modules/Jquery/JqueryUI/modal.js there's a line of code that depends on the parent window (which, in this case, refers to the original front-end window that opened the Page Editor in an iframe) having jQuery loaded. On this particular site the front-end *doesn't* use jQuery, so this resulted in an error.

At first I thought it would be an easy fix, which it actually was – here's the relevant change I made for testing purposes:

```
--- a/wire/modules/Jquery/JqueryUI/modal.js
+++ b/wire/modules/Jquery/JqueryUI/modal.js
@@ -109,7 +109,7 @@ function pwModalWindowSettings(name) {
                closeOnEscape: options.closeOnEscape,
                create: function(event, ui) {
                        if(options.hideOverflow) {
-                               parent.jQuery('body').css('overflow', 'hidden');
+                               parent.document.querySelector('body').style.overflow = 'hidden';
                        }
                        // replace the jQuery ui close icon with a font-awesome equivalent (for hipdi support)
                        var $widget = jQuery(this).dialog("widget");
```

**First of all: what do you think of this change – does it make sense for you, and would you be willing to consider implementing it in modal.js?**

Note: I'm not saying that we should get rid of jQuery, but in this case it would in my opinion make sense to use the vanilla JS feature instead of the jQuery one, as that makes embedding modals outside the Admin work regardless of jQuery. Simple querySelector should also work in IE7+.

Now, even though this resolved my original issue, it also highlighted another issue: `overflow: hidden` CSS style only gets removed (in beforeClose) if following condition is met:

```
if(parent.jQuery != "undefined" && parent.jQuery('.ui-dialog').length)
```

In this case there's a check for jQuery, which in my case already returned `false`. Additionally there's a check for `.ui-dialog`, which also returned `false` as the parent window doesn't have any of those. As a result even though the overflow style gets applied, it never gets removed.

**Referring to my example here, could `overflow: hidden` be removed regardless of the parent window containing jQuery and `.ui-dialog`, at least if the dialog element didn't exist when the style was added either?**

Please let me know if this is a use case that you don't want to support and I'm happy to figure out something else for AdminBar, but to me it seems that it might be pretty easy to resolve in modal.js – I'm just not entirely sure of the best route to take. Embedding modal Page Editor outside of Admin seems like a relatively typical use case for me, but I could be biased :)

### Setup/Environment

* ProcessWire version: 3.0.123
* (Optional) Any 3rd party modules that are installed and could be related to the issue: AdminBar

**Comment by ryancramerdesign** [comment]
@teppokoivula Sounds good to me. I have added your suggested update for the first issue you mentioned. I hadn't planned for support outside of jQuery as modal.js was built for PW's admin, and PW's front-end editor loads jQuery if it isn't already. But if it's as simple as you describe then I think it's of course a good idea to support non-jQuery for this. 

> Additionally there's a check for .ui-dialog, which also returned false as the parent window doesn't have any of those. 

Are you sure there's no .ui-dialog? I don't think the check for the .ui-dialog would ever execute since the first condition in the if() returns false. I could be wrong, but I thought a .ui-dialog would have to be present in order for there to be a modal window to close? 

> Referring to my example here, could overflow: hidden be removed regardless of the parent window containing jQuery and .ui-dialog, at least if the dialog element didn't exist when the style was added either?

That's fine with me. Admittedly I don't know JS like I know PHP, and I rarely code non-jQuery JS, as I don't often need it in PW. While I think I could figure out how to code what you are asking for here, I don't know exactly how to duplicate the test case/environment you need this for. But here's my best guess as a replacement for the beforeClose() method implementation, basically adapting the code from your earlier suggestion. Do you find this does what you are needing?
~~~~~
if(frameElement) {
  // dialog on top of another dialog
  parent.document.querySelector('.pw-modal-hidden').style.display = 'block';
  document.querySelector('body').style.overflow = '';
} else if(options.hideOverflow) {
  parent.document.querySelector('body').style.overflow = '';
}
~~~~~

**Comment by teppokoivula** [comment]
@ryancramerdesign, sorry for dropping the ball on this one :)

I was considering closing this issue, but figured it might still make sense to get this sorted out. I gave the code you posted a try, but it doesn't seem to be quite enough yet. After running a few tests, here's a change set that seems to work for me:

```
diff --git a/wire/modules/Jquery/JqueryUI/modal.js b/wire/modules/Jquery/JqueryUI/modal.js
index d3f1b4c3..731327be 100644
--- a/wire/modules/Jquery/JqueryUI/modal.js
+++ b/wire/modules/Jquery/JqueryUI/modal.js
@@ -122,22 +122,28 @@ function pwModalWindowSettings(name) {
                                .prepend("<i class='fa fa-times'></i>")
                                .find('.ui-icon').remove();

-                       if(frameElement && parent.jQuery != "undefined" && parent.jQuery('.ui-dialog').length) {
+                       if(frameElement && parent.document.querySelector('.ui-dialog')) {
                                // dialog on top of dialog
-                               parent.jQuery('.ui-dialog .ui-button').addClass('pw-modal-hidden').hide();
-                               parent.jQuery('.ui-dialog-buttonpane').css('margin-top', '-10px');
-                               jQuery('body').css('overflow', 'hidden');
+                               var parentButtons = parent.document.querySelectorAll('.ui-dialog .ui-button');
+                               for (var i = 0; i < parentButtons.length; i++) {
+                                       parentButtons[i].classList.add('pw-modal-hidden');
+                                       parentButtons[i].style.display = 'none';
+                               }
+                               var parentPanes = parent.document.querySelectorAll('.ui-dialog-buttonpane');
+                               for (var i = 0; i < parentPanes.length; i++) {
+                                       parentPanes[i].style.marginTop = '-10px';
+                               }
+                               document.querySelector('body').style.overflow = 'hidden';
                        }
                },
                beforeClose: function(event, ui) {
-                       if(parent.jQuery != "undefined" && parent.jQuery('.ui-dialog').length) {
                        if(frameElement) {
                                // dialog on top of another dialog
-                                       parent.jQuery(".pw-modal-hidden").show();
-                                       jQuery('body').css('overflow', '');
+                               var parentModalHidden = parent.document.querySelector('.pw-modal-hidden');
+                               if (parentModalHidden) parentModalHidden.style.display = 'block';
+                               document.querySelector('body').style.overflow = '';
                        } else if(options.hideOverflow) {
-                                       parent.jQuery('body').css('overflow', '');
-                               }
+                               parent.document.querySelector('body').style.overflow = '';
                        }
                }
        }
```

I don't currently have a site with jQuery to test on, so it would be great if you (or someone else) could give this version a try, but at least in my tests it seems to fix biggest issues for a site that _doesn't_ include jQuery. If you feel that this is not worth it, feel free to close the issue, but again I think it could be useful for some sites (at the very least those that use AdminBar but not jQuery.)

Note that I wasn't entirely sure if there are only one or multiple "parentButtons" and "parentPanes", so I opted to place them within a loop, just in case. This is one of the cases where I think jQuery is nicer than vanilla JS: it allows you to add classes etc. to multiple elements simultaneously :)

**Comment by teppokoivula** [comment]
By the way: in order to reproduce this issue I had to dig pretty deep. The issue only showed up while using AdminBar to edit a page that has a PageTable field containing a page that has a CKEditor field. Opening the link editor in said CKEditor and then closing all the dialogs left some overflow rules in place.

**Comment by ryancramerdesign** [comment]
@teppokoivula Thanks, I'll plan to add your changes. But since we're getting into stuff that may not be as straightforward to test in all the cases it might apply, I'll wait till after the master version and put this in when back on the dev branch.

**Comment by teppokoivula** [comment]
Thanks, @ryancramerdesign. Makes sense to me.

**Comment by teppokoivula** [comment]
Hey @ryancramerdesign — sorry to bother, but I wonder if this might be a good time to get back to this one? :)

**Comment by ryancramerdesign** [comment]
@teppokoivula Thanks for the reminder, I'd forgotten to return to this. I've added the code you proposed above, but to play it safe have also kept the jQuery code too, so that it uses jQuery if available in the parent window, and your JS code if not. Eventually we can likely remove the jQuery part, but I didn't have a good test for both cases at the moment.

**Comment by matjazpotocnik** [comment]
@teppokoivula does Ryan's fix work for you? If it does, could you close this issue?

**Comment by teppokoivula** [comment]
AdminBar contains a workaround for this, and it'll be a while before I can safely remove that, so can't test properly right now. On the other hand I don't see why this wouldn't work (and have seen no negative consequences), so I'll close the issue.

Thanks, Ryan!
