### ISSUE TITLE
Fieldset won't remember width after save

### ISSUE THREAD

**Issue by matjazpotocnik** [processwire/processwire-issues#994]
When you edit the FieldsetOpen in the template editor, the width is not saved. See the attached video. PW 3.0.142

![fieldset](https://user-images.githubusercontent.com/7663992/66719655-2bd92e00-edf3-11e9-9342-3bec238fa8f1.gif)

**Comment by hgassen** [comment]
Could it be that you have this module installed? https://modules.processwire.com/modules/template-field-widths/

**Comment by hgassen** [comment]
Could it be that you have this module installed? https://modules.processwire.com/modules/template-field-widths/

In this case, it should happen with other fields, too.

**Comment by matjazpotocnik** [comment]
@hgassen Yes, that's it. After uninstall the widths are saved. Thx!
