### ISSUE TITLE
Error when upgrading to 3.0.142 when CroppableImage3 module is installed

### ISSUE THREAD

**Issue by jacmaes** [processwire/processwire-issues#995]
### Short description of the issue

Site fails to load after upgrading from 3.0.138 to 3.0.142

### Expected behavior

Upgrade should go as planned. I guess it has something to do with the new custom fields for images introduced in 3.0.142.

### Actual behavior
Here's the error in the logs, in "errors.txt":

Compile Error: 	Cannot make non static method ProcessWire\FieldtypeFile::getModuleConfigInputfields() static in class ProcessWire\FieldtypeCroppableImage3 (line 4 of /var/www/vhosts/domain.com/httpdocs/site/modules/CroppableImage3/FieldtypeCroppableImage3/FieldtypeCroppableImage3.module) ^+1

**Comment by teppokoivula** [comment]
Just a heads-up: issue #997 contains a bit more detail into this issue. Basically this is one symptom of that :)

**Comment by ryancramerdesign** [comment]
Thanks @jacmaes I've pushed a fix for this issue.

**Comment by jacmaes** [comment]
Confirmed, it works now. Thanks! Closing the issue.

**Comment by tbba** [comment]
I left a comment in the forum:
https://processwire.com/talk/topic/14090-croppable-image-3/page/13/
