### ISSUE TITLE
WebP httpUrl returns jpg

### ISSUE THREAD

**Issue by esl51** [processwire/processwire-issues#996]
```php
$image->webp->url
```
returns
```
/site/assets/files/xxxx/image.webp
```
but
```php
$image->webp->httpUrl
```
returns
```
http://example.com/site/assets/files/xxxx/image.jpg
```

ProcessWire 3.0.142

**Comment by ryancramerdesign** [comment]
Thanks @esl51 good catch, can't believe I missed that one — I've pushed a fix.

**Comment by netcarver** [comment]
@esl51 I'm closing this issue now. Please post again if you need to, and I'll re-open.

**Comment by csaggo** [comment]
@ryancramerdesign Hi Ryan on 3.0.161 i have this issue again. only difference is i am using a png. i get .png url from ->webp()->httpUrl
