### ISSUE TITLE
Javascript error when creating new Repeater Matrix type

### ISSUE THREAD

**Issue by robertweiss** [processwire/processwire-issues#999]
### Short description of the issue

In the Repeater Matrix Pro Module, there seems to be a javascript problem with the asmConfig. When I edit a repeater matrix field and try to add a new matrix type, a js error occurs.

### Expected behavior

After clicking the ›Add New Matrix Type‹ button, I can edit the new matrix type.

### Actual behavior

After clicking the ›Add New Matrix Type‹ button, the following js error shows up in the console: 
Uncaught TypeError: Cannot read property 'editLink' of undefined
    at HTMLButtonElement.<anonymous> (config.js:68)
    at HTMLButtonElement.dispatch (JqueryCore.js?v=1570167924:2)
    at HTMLButtonElement.u (JqueryCore.js?v=1570167924:2)

### Suggestion for a possible fix

I don’t have a working solution, but I found that the change that established this error is in commit 0a01b472a1d1ee97eeae49273e412031a5480246. Processwire versions before this commit work without a problem.

### Steps to reproduce the issue

1. Install a Processwire version (dev branch) with commit 0a01b472a1d1ee97eeae49273e412031a5480246 or later ([https://github.com/processwire/processwire/commit/0a01b472a1d1ee97eeae49273e412031a5480246](https://github.com/processwire/processwire/commit/0a01b472a1d1ee97eeae49273e412031a5480246))
2. Install the newest version of Repeater Matrix (v5β rev a)
3. Create a new field with Repeater Matrix as type
4. In the field config, click on the tab Details and then ›Add New Matrix Type‹

### Setup/Environment
<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.141|
|PHP|7.3.7|
|Webserver|Apache/2.4.39 (Unix) |
|MySQL|8.0.17|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|600 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|1000|
|memory_limit|512M|
|post_max_size|128M|
|upload_max_filesize|128M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security|*confirmed off|
|EXIF Support|1|
|FreeType|1|
</details><details><summary><strong>GD Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|WebP|1|
</details><details><summary><strong>iMagick Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|Version|7.0.8|
|GIF|1|
|JPG|1|
|PNG|1|
|SVG|1|
|PDF|1|
|WebP|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|AdminOnSteroids|2.0.20|
|FieldtypeRepeaterMatrix|0.0.5|
|InputfieldRepeaterMatrix|0.0.5|
|MarkupSimpleNavigation|1.3.6|
|ProcessHannaCode|0.2.0|
|ProcessTracyAdminer|1.0.6|
|TextformatterHannaCode|0.2.0|
|TracyDebugger|4.19.34|
</details>

**Comment by ryancramerdesign** [comment]
Thanks @robertweiss I've pushed a fix for this issue.

**Comment by netcarver** [comment]
@robertweiss I'm closing this now. Please post here again if you need to and I'll re-open this issue.
